### ISSUE TITLE
Error code shorthand in hooks handling does not work correctly

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#100]
Use case:
```js
// first hook
fastify.addHook('preHanlder', (req, reply, done) => {
  done()
})
// second hook
fastify.addHook('preHanlder', (req, reply, done) => {
  done(new Error('some error'), 400)
})
```
The expected response must have a `statusCode` equal to `400`, instead we got `500`, because of [this](https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L112).
Since the hooks that returns an error is the second, the error status code will be in `code[1]`.

@mcollina suggestions?

**Comment by mcollina** [comment]
Why are we checking if the code is in the first position of an array? Why do we even support this? A user should be able to use boom or attach a statusCode property to the Error.

**Comment by delvedor** [comment]
That behaviour has been added in https://github.com/fastify/fastify/pull/86.

The user can also do:
```js
fastify.addHook('preHanlder', (req, reply, done) => {
  reply.code(400)
  done(new Error('some error'))
})
```
And he will get the expected result, the `done(Error, code)` is just a shorthand.

**Comment by mcollina** [comment]
ok, I don't think we should do this. If you want to return a `400`, you call  `reply()`, and then `done()`. We just need to check if you replied or not within `done()` before advancing to the next hook. And we should support `boom`-style errors, i.e. `err.statusCode`.

**Comment by Ethan-Arrowood** [comment]
@mcollina whats the status of this? Anything I can try to help out with?

**Comment by delvedor** [comment]
Seen how it works [`fastseries`](https://github.com/mcollina/fastseries) which is our hooks runner, I don't think we can fix this easily without degrade the performances.

I think we can close this, the [docs](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) have already been updated with the correct usage.
