### ISSUE TITLE
test/beforeHandler.test.js duplicate test case

### ISSUE THREAD

**Issue by lependu** [fastify/fastify#1006]
Hi! Just a nit:

https://github.com/fastify/fastify/blame/2f96a8033152bc4977c14cd2f5eb8a25bff75316/test/beforeHandler.test.js#L126-L153

https://github.com/fastify/fastify/blame/2f96a8033152bc4977c14cd2f5eb8a25bff75316/test/beforeHandler.test.js#L155-L182

test cases are the exact same tests with different label.
Do we need both of them?

**Comment by mcollina** [comment]
No we don't! Would you like to send a PR?

**Comment by delvedor** [comment]
Closed in #1008
