### ISSUE TITLE
Create a starter project and link it in the README

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1010]
We definitely need a starter project linked from the website and the README.

It should be generated from `fastify-cli`, and have a database layer on top, with a couple of routes, maybe a login, and it should a couple of our plugins.

**Comment by astesio** [comment]
What do you think to generate a new project with fastify-cli and using the [couchbase](https://www.couchbase.com/) and JWT ?

**Comment by mcollina** [comment]
That'd be cool, yes! You can use https://github.com/nigelhanlon/fastify-couchdb.
