### ISSUE TITLE
Possibility of accepting an array of routes?

### ISSUE THREAD

**Issue by rodrigooler** [fastify/fastify#1012]
I was checking the documentation to see if it would be possible to send an array of options as shown below.

```javascript
const options = [{
  method: 'GET',
  url: '/hello',
  schema: {
    querystring: {
      name: { type: 'string' },
      excitement: { type: 'integer' }
    },
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: function (request, reply) {
    reply.send({ hello: 'hello' })
  }
}, {
method: 'GET',
  url: '/world',
  schema: {
    querystring: {
      name: { type: 'string' },
      excitement: { type: 'integer' }
    },
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: function (request, reply) {
    reply.send({ world: 'world' })
  }
}];

fastify.route(options);
```

I have not found a way to do the above example in the documentation and from what I looked at in the source code currently only one correct object is supported?

Would you be able to switch to an array in the future?

**Comment by jsumners** [comment]
This feature was dropped in favor of simply iterating the source array. 

`routes.forEach(r => fastify.register(r))`

**Comment by rodrigooler** [comment]
@jsumners thanks for the tip, I'll do it here in my application. I think it would be nice to have this documented would not it make sense?

**Comment by jsumners** [comment]
Sure. A PR would be most welcome.

**Comment by rodrigooler** [comment]
@jsumners I'm going to apply here and I already send a PR by modifying the .md and putting more details of it, thank you!

**Comment by rodrigooler** [comment]
@jsumners could you look at the PR and check it out please? 

https://github.com/fastify/fastify/pull/1014

**Comment by rodrigooler** [comment]
@jsumners thank you for clarifying the doubt.
