### ISSUE TITLE
Decorators are not accessible between plugin

### ISSUE THREAD

**Issue by antux** [fastify/fastify#1015]
Hi team.

I dont know if it there a bug, but the decorators are not accessible between plugin, only if is it defined outside.

I trying shared the models, from one plugin to others, but the decoratos is undefined.

example:
```
index.js: 
  fastify.decorate('config', config);
plugin 1: 
 fastify.config.db --> work
 fastify.decorate('models', models);

plugin 2: 
 fastify.models --> undefine, dont work.
```

Any idea, thanks.

**Comment by antux** [comment]
Thanks @lependu @StarpTech, i have resolved.

**Comment by delvedor** [comment]
Hi! I highly recommend you to read https://www.fastify.io/docs/latest/Plugins-Guide/ :)

**Comment by antux** [comment]
Perfect. 

Recently i found this framework y i love the combination express + hapi.

Thanks.
