### ISSUE TITLE
Where do the logs go?

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify#1018]
I have been trying to setup some simple logging. Initially I would be happy to just see the routes which have been requested.

Unfortunately I am yet to see any log. Coming from an express/morgan background I was expecting the logs to be written to the process STDOUT by default ({ logger:true }) but this doesn't seem to be the case.

Still stuck on the first example from the documentation. I assume that stream has something to do with the output. Is there a way to direct this to STDOUT?

```
const split = require('split2')
const stream = split(JSON.parse)

const fastify = require('fastify')({
  logger: {
    level: 'info',
    stream: stream
  }
})

fastify.get('/', {}, function (request, reply) {
  request.log.info('Some info about the current request')
  reply.send({ hello: 'world' })
})
```

**Comment by jsumners** [comment]
It should be going to `stdout` when you enable the logger. You should not have to specify `stream: stream` in the options.

**Comment by dbauszus-glx** [comment]
Ok... I just run a quick test in my terminal and see the logs. Same example run in VS Code no output to the terminal. This is odd. Doesn't the pino logger use process.stdout.write like console.log or the Morgan logger? These do appear in the Visual Studio Code terminal.

**Comment by mcollina** [comment]
it uses the same `process.stdout.write` as all the others.

**Comment by dbauszus-glx** [comment]
Aha... It's a Visual Studio Code issue. Fortunately somebody found a workaround for this just yesterday and posted in the pino issue log. Let me change the title of this post and close issue.

https://github.com/pinojs/pino/issues/441

**Comment by skoniks** [comment]
You can use builtin console to fix that problem.
My solution for typescript:

`const server = fastify({
    logger: config('app.debug') ? new class Logger {
      private args;
      constructor(...args: never) { this.args = args }
      info = (msg: unknown) => console.info(msg);
      error = (msg: unknown) => console.error(msg);
      debug = (msg: unknown) => console.debug(msg);
      fatal = (msg: unknown) => console.error(msg);
      warn = (msg: unknown) => console.warn(msg);
      trace = (msg: unknown) => console.trace(msg);
      child = () => new Logger();
    } : false
  });`

**Comment by jsumners** [comment]
> You can use builtin console to fix that problem. My solution for typescript:
> 
> ```
> const server = fastify({
>     logger: config('app.debug') ? new class Logger {
>       private args;
>       constructor(...args: never) { this.args = args }
>       info = (msg: unknown) => console.info(msg);
>       error = (msg: unknown) => console.error(msg);
>       debug = (msg: unknown) => console.debug(msg);
>       fatal = (msg: unknown) => console.error(msg);
>       warn = (msg: unknown) => console.warn(msg);
>       trace = (msg: unknown) => console.trace(msg);
>       child = () => new Logger();
>     } : false
>   });
> ```

This is unnecessary. Set your VSCode debugger profile to use `"outputCapture": "std"` -- https://github.com/microsoft/vscode-docs/blob/56f5a65c45b509f648a4150b9fe1a5b9bb1afa57/docs/nodejs/nodejs-debugging.md?plain=1#L132

**Comment by skoniks** [comment]
> > You can use builtin console to fix that problem. My solution for typescript:
> > ```
> > const server = fastify({
> >     logger: config('app.debug') ? new class Logger {
> >       private args;
> >       constructor(...args: never) { this.args = args }
> >       info = (msg: unknown) => console.info(msg);
> >       error = (msg: unknown) => console.error(msg);
> >       debug = (msg: unknown) => console.debug(msg);
> >       fatal = (msg: unknown) => console.error(msg);
> >       warn = (msg: unknown) => console.warn(msg);
> >       trace = (msg: unknown) => console.trace(msg);
> >       child = () => new Logger();
> >     } : false
> >   });
> > ```
> 
> This is unnecessary. Set your VSCode debugger profile to use `"outputCapture": "std"` -- https://github.com/microsoft/vscode-docs/blob/56f5a65c45b509f648a4150b9fe1a5b9bb1afa57/docs/nodejs/nodejs-debugging.md?plain=1#L132

Using "outputCapture": "std" brokes debbuging in other modules that uses builtin console. It`s usefull only when you use fastify  standalone, without anything else.
