### ISSUE TITLE
Fastify never responds to POST with body when proxied with node-http-proxy

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#1023]
#### What are you trying to achieve or the steps to reproduce?

I'm trying to proxy a fastify service with node-http-proxy, here's the simple case that reproduces the behaviour:

```js
// index.js
const httpProxy = require('http-proxy');
const fastify = require('fastify');

// setup proxy
const proxiedServer = require('./proxiedServer');
const proxy = httpProxy.createProxyServer({target: 'http://localhost:8081', ignorePath: true});

// setup app
const app = fastify();

app.get('/', (req, res) => res.send('Hello world!'));
app.get('/proxy', (req, res) => proxy.web(req.req, res.res));
app.post('/proxy', (req, res) => proxy.web(req.req, res.res));

app.listen(8080, '0.0.0.0', (err, address) => {
  if (err) {
    console.error(err);
    return;
  }
  console.info(`Listening at ${address}`);
});
```

```js
// proxiedServer.js
const fastify = require('fastify');
const app = fastify();

app.get('/', (req, res) => res.send('Hello proxied GET world!'));
app.post('/', (req, res) => res.send('Hello proxied POST world!'));

app.listen(8081, (err, address) => {
  if (err) {
    console.error(err);
    return;
  }
  console.info(`Listening at ${address}`);
});
```

You can find a running example [here on glitch](glitch.com/edit/#!/fastify-http-proxy-body-issue).

#### What was the result you received?

Normal GET and empty POST requests work as expected, i.e.:

```sh
> curl https://fastify-http-proxy-body-issue.glitch.me/proxy
Hello proxied GET world!%

> curl -X POST https://fastify-http-proxy-body-issue.glitch.me/proxy
Hello proxied POST world!%
```

But as soon as you add data to POST request - response never comes back and eventually times out on client. E.g. this eventually times out:
```sh
> curl -d '{"key":"val"}' -H "Content-Type: application/json" -X POST https://fastify-http-proxy-body-issue.glitch.me/proxy
```

#### What did you expect?

POST request with body to also return response.

#### Context

* *node version*: 8, 10
* *fastify version*: 1.7
* *os*: Linux, Mac
* *any other relevant information*:

I've tried adding custom content-type parsers, but that doesn't help.
Enabling logging in fastify shows that request does gets received, just doesn't seem to go to handler (?) for some reason. 
Any tips on how to fix this? Am I just doing something wrong?

**Comment by mcollina** [comment]
I would recommend you to use https://github.com/fastify/fastify-http-proxy instead.
node-http-proxy is very low level and tied to Node.js http req/res object and state management.

**Comment by yamalight** [comment]
@mcollina ah, thanks! somehow missed it.

Just tried it - seems to work for basic example, but fails when I try to use `/api/thing` as prefix, e.g. this results in 404:
```js
inst.register(proxy, {
  upstream: 'http://localhost:8081',
  prefix: '/api/search',
});
```

I've also tried to use set it inside a plugin with a prefix, like so:
```js
app.register((inst, opts, next) => {
  inst.register(proxy, {
    upstream: 'http://localhost:8081',
    prefix: '/search',
  });
  next();
}, {prefix: '/api'});
```
Which also results in 404.

Is that something that's possible to do with it?

**Comment by mcollina** [comment]
Can you please open a bug there with a full example?

**Comment by yamalight** [comment]
@mcollina sure, will do in a minute. thanks for help!
