### ISSUE TITLE
Expose default not found handler

### ISSUE THREAD

**Issue by TheNoim** [fastify/fastify#1025]
Hi,

At the moment it is already possible to set a new notFound Handler. But sometimes when I use it, I set the notFound handler just to handle some cases. It would be great if there is the possibility to use the default NotFoundHandler again. The same for the error handler. 

```javascript
fastify.setNotFoundHandler((request, reply) => {
   // Complicated super secret business logic.

   // Oh I don't need to handle this case
   reply.defaultNotFoundHandler(); // Use default one again
});
```

**Comment by delvedor** [comment]
Once you use `setNotFoundHandler` you are overriding the default one.
A solution could be decorate the reply object and use that decorator:
```js
fastify.decorateReply('notFound', () => {
  this.code(404).send(new Error('Not found')
})

// ...

reply.notFound()
```
Otherwise you can use [`fastify-sensible`](https://github.com/fastify/fastify-sensible) which adds the `notFound` decorator (and many more!) for you :)

**Comment by TheNoim** [comment]
Thanks, didn't know this plugin
