### ISSUE TITLE
Hosting an Angular 6 App with fastify

### ISSUE THREAD

**Issue by ccython** [fastify/fastify#1028]
#### You have already researched for similiar issues?

Yes i have, haven't found any helpful resources.

#### Are you sure this is an issue with the fastify or are you just looking for some help?

This is an approach not documented with fastify or a usecase that i haven't seen yet, so it's
a bit of both?

#### Is this a security related issue?

No.

#### What are you trying to achieve or the steps to reproduce?

Im trying to host both the API backend and the respective Angular App in one HTTP server   (in this case one fastify instance), with the Angular App running under the prefix `/admin/`.  
I want any requests with the `/admin/` prefix that are not files to be redirected to the Angular apps index.html, so the app can handle the URL routing client-side. This however,  
does not seem to work at all, as only the `/admin/` route works - routes like   `/admin/profile/jagobaoth` are **only** accessible when navigating from within the Angular App. It appears the `/admin/*` path does not match.

Here is my `app.js` file:

```js
const fastify = require('fastify')();
const path = require('path');
const fs = require('fs');

if (!Array.prototype.last) {
  Array.prototype.last = () => {
      return this[this.length - 1];
  };
};

fastify.get('/admin/', (req, reply) => {
  console.log("serving /admin/");
  const stream = fs.createReadStream(path.join('', 'dist', 'index.html'));
  reply.type('text/html').send(stream);
});

fastify.get('/admin/:filename(\.[A-Za-z]{1,4})', function (req, reply) {
  console.log("Serving /admin/:filename");
  let filename = req.params.filename;
  let fileext = filename.split('.').last();
  let type = 'text/plain';
  if (fileext == 'css') {
    type = 'text/css';
  }
  if (fileext == 'js') {
    type = 'text/javascript';
  }
  if (fileext == 'html') {
    type = 'text/html';
  }
  const stream = fs.createReadStream(path.join(__dirname, 'dist', filename));
  reply.code(200).type(type).send(stream);
});

fastify.get('/admin/*', (req, reply) => {
  console.log("serving /admin/*");
  const stream = fs.createReadStream(path.join(__dirname, 'dist', 'index.html'));
  reply.code(200).type('text/html').send(stream);
});

fastify.listen(3000, (err, address) => {
  if (err) throw err;
  console.log(`server listening on ${address}`);
 });
```

It has the same result irrespective of the Angular App used.

#### What was the result you received?

Error 404 was returned from the fastify server when trying to access any URL with the  
`admin` prefix. Accessing files does work.

#### What did you expect?

The fastify server should pass the URL to the Angular Apps `index.html` file, and the  
Angular App should then handle the routing client-side.

#### Context

* node version: 10.5.0
* fastify version: 1.7.0
* os: Arch Linux

**Comment by ccython** [comment]
Fixed this myself, sorry.
the order of route declarations had to go like this:  
* `/admin/`
* `/admin/*`
* `/admin/:filename`

Its now working flawlessly.

**Comment by mcollina** [comment]
@delvedor is this working as expected, or is this a bug in find-my-way? Should parametric routes be higher priority than the wildcards?

**Comment by delvedor** [comment]
The current order of execution is:
```
static
parametric
wildcard
parametric with regex
multi parametric
```

We can change it and put wildcard as very last, it is not a breaking change IMHO.

**Comment by mcollina** [comment]
@delvedor I think we should fix this in find-my-way.

**Comment by triadium** [comment]
but is multi parametric less specific? Maybe better this order:
static
parametric
multi parametric
parametric with regex
wildcard

**Comment by smsshiva** [comment]
fastify.use(['/'], serveStatic(path.join(__dirname + '/dist/userapp')));
