### ISSUE TITLE
Req id should not be a feature of logging

### ISSUE THREAD

**Issue by zhaoyao91** [fastify/fastify#1035]
I noticed that the req id generator is set in logging options, this is a strange design, since we could get req.id in route handlers, and the req.id feature does not rely on logging.

#### Context

* *fastify version*: >=1.7.0

**Comment by eljefedelrodeodeljefe** [comment]
I agree. Also, this results in bulkiness, when I want to override it. I know it's a performance decision not to use uuids. But reality is that logs without uuids in distributed system are very ops time expensive.

**Comment by zhaoyao91** [comment]
@delvedor Sorry about this. To solve this problem, it seems we should have some high-level and global consideration, design and refactoring. As I am not a deep developer of this project and have other works to do, it would be hard to submit a PR.

**Comment by delvedor** [comment]
> Regarding UUIDs, it is also a performance issue. We might switch to mcollina/hyperid instead which offers the same uniqueness of UUIDs but it's extremely fast. Or we might want to provide an option flag and docs on how to use UUIDs in a distributed system.

Actually I would prefer to stick with the current solution, and give the user the free choice about which strategy to use.

**Comment by cemremengu** [comment]
Staged for v2.0.0 with #1164 and #1166
