### ISSUE TITLE
 Schema with key or id already exists

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify#1043]
Related issue #922. @delvedor.

I don't know if it's a bug. Or may be it's just a limitation of schemas.
Seems the root cause is quiet similar. If there are 2 or more schemas that depend on each other are defined using `allOf`, e.g.:
```js
app.addSchema({
  $id: 'first',
  type: 'object',
  properties: {
    first: {
      type: 'number',
    },
  },
});
app.addSchema({
  $id: 'second',
  type: 'object',
  allOf: [
    {
      type: 'object',
      properties: {
        second: {
          type: 'number',
        },
      },
    },
    'first#',
  ],
});
```

then if `first` schema will be used after `second` fastify will throw exception:
```
Error: schema with key or id "first" already exists
```
If schema "usages" will go in sequential order, then app will start without any exceptions. See full example below:

#### What are you trying to achieve or the steps to reproduce?

```js
const fastify = require('fastify');
const app = fastify({
  logger: {
    level: 'info',
    prettyPrint: true,
  },
  ignoreTrailingSlash: true,
});
app.addSchema({
  $id: 'first',
  type: 'object',
  properties: {
    first: {
      type: 'number',
    },
  },
});

app.addSchema({
  $id: 'second',
  type: 'object',
  allOf: [
    {
      type: 'object',
      properties: {
        second: {
          type: 'number',
        },
      },
    },
    'first#',
  ],
});

app.get(
  '/',
  {
    schema: {
      description: `get`,
      body: 'second#',
      response: {
        200: 'second#',
      },
    },
  },
  async function(request, reply) {
    return {ok: 'ok'};
  }
);

app.patch(
  '/',
  {
    schema: {
      description: `patch`,
      body: 'first#',
      response: {
        200: 'first#',
      },
    },
  },
  async function(request, reply) {
    return {ok: 'ok'};
  }
);

(async () => {
  try {
    await Promise.all([
      app.listen(3333),
      app.ready(),
    ]);
  } catch (ex) {
    console.log(ex);
    process.exit(1);
  }
})();

```

#### What was the result you received?

App schema validation fails. App doesn't start.
```
Error: schema with key or id "first" already exists
```

Swapping `get` and `patch` methods "solves" issue.

#### What did you expect?

Order of using schemas that depend on each other should not affect app.

#### Context

* *node version*: 9
* *fastify version*: 1.8.0

**Comment by mcollina** [comment]
Can you please include a full stacktrace? Would you like to try sending a
Pull Request to fix this?
Il giorno dom 15 lug 2018 alle 17:31 Alexander Kureniov <
notifications@github.com> ha scritto:

**Comment by SkeLLLa** [comment]
```
Error: schema with key or id "first" already exists
    at checkUnique (/app/node_modules/ajv/lib/ajv.js:478:11)
    at Ajv._addSchema (/app/node_modules/ajv/lib/ajv.js:307:30)
    at Ajv.compile (/app/node_modules/ajv/lib/ajv.js:112:24)
    at build (/app/node_modules/fastify/lib/validation.js:58:27)
    at afterRouteAdded (/app/node_modules/fastify/fastify.js:565:9)
    at Object._encapsulateThreeParam (/app/node_modules/avvio/boot.js:360:7)
    at Boot.callWithCbOrNextTick (/app/node_modules/avvio/boot.js:308:5)
    at Boot._after (/app/node_modules/avvio/boot.js:212:26)
    at Plugin.exec (/app/node_modules/avvio/plugin.js:45:17)
    at Boot.loadPlugin (/app/node_modules/avvio/plugin.js:125:10)
```

I think, let's wait for @delvedor and hear what he thinks about this, because he's already fixed very similar issue. Probably he'll have some good ideas about the way of fixing this.

**Comment by mcollina** [comment]
Would you like to send a PR with the fix?

**Comment by SkeLLLa** [comment]
@mcollina now I'm working on fastify-swagger adding support for OAS-3. So for now I don't have enough time.

**Comment by delvedor** [comment]
Confirmed, I'm working on this.

**Comment by harveyconnor** [comment]
Still getting this in the latest version

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by JakeGinnivan** [comment]
I just hit this. My problem was a setup like this:

``` js
app.addSchema({ '$id': 'one', type: 'object', properties: { thing: { '$ref': 'two#' } })
app.addSchema({ '$id': 'two', type: 'object', properties: { })

app.get('/path', {
    schema: {
       response: { 200: { 'type': 'object', properties: { thing: { '$ref': 'two#' } } } }
    }
}, (req, reply) => { .. })
```

My guess, somehow when adding `two` when it's already been referred to in an earlier `addSchema` it gets added twice.

The fix was to switch the adding of the schemas around

``` js
app.addSchema({ '$id': 'two', type: 'object', properties: { })
app.addSchema({ '$id': 'one', type: 'object', properties: { thing: { '$ref': 'two#' } })
```

Hope this helps someone

**Comment by Eomm** [comment]
That code works actually: https://runkit.com/embed/u0jziy02t8lu

Please open a new issue with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in order to improve our test suite with your use case and avoid regressions

**Comment by harveyconnor** [comment]
@JakeGinnivan yep that works for a simple scenario. In my case we have multiple files depending on each other in such a circular dependency, so it does not work.

**Comment by meerkat999** [comment]
Any solution for this?

**Comment by Eomm** [comment]
This is my 3rd message in a row:

Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Without it, we are unable to help you.**
