### ISSUE TITLE
Enable trust proxy?

### ISSUE THREAD

**Issue by Zaseth** [fastify/fastify#1044]
Hello.

How can I enable trust proxy to get the ip with x-forwarded-for like in Express.js?

**Comment by mcollina** [comment]
Can you please explain this with a bit more detail? What code are you trying to port?

**Comment by Zaseth** [comment]
I'm not trying to port something. Express has a function to enable trust proxy and with that I can get the person's ip address using req.ip. Is this possible in fastify?

**Comment by mcollina** [comment]
No it does not. It should be trivial to add.

**Comment by Zaseth** [comment]
I do want to say that when enabling trust proxy without running the app behind a proxy like nginx, the header x-forwarded-for can be spoofed. Express disables trust proxy by default.

**Comment by mcollina** [comment]
@Zaseth definitely. I think we should add a `trustProxy` option to fastify and use https://www.npmjs.com/package/proxy-addr in a similar way to how express uses it. 

Some pointers: https://github.com/expressjs/express/blob/b97faff6e2aa4d34d79485fe4331cb0eec13ad57/lib/request.js#L292-L324 https://github.com/expressjs/express/blob/c0136d8b48dd3526c58b2ad8666fb4b12b55116c/lib/utils.js#L212-L239

**Comment by Zaseth** [comment]
This could be a very useful feature. There should be a note for the proper configuration for the nginx config when using this feature, but I assume that you already know about this.
