### ISSUE TITLE
fastify-formbody don't respect fastify global bodyLimit options

### ISSUE THREAD

**Issue by vincent178** [fastify/fastify#1048]
```
const fastify = require('fastify')({
  bodyLimit: 1024 * 1024 * 1024,
  logger: true
})

fastify.register(require('fastify-formbody'))

fastify.post('/ssr', (req, res) => {
  res.send('hello world')
})

fastify.listen(9000, (err) => {
  if (err) throw err
  console.log('server is up and running on 9000')
});

```

with this simple code, the fastify-formbody still use 1MiB as the default bodyLimit

### Expected behavior
unless we specify the bodyLimit on plugin level, the fastify-formbody should use global bodyLimit which is `1024 * 1024 * 1024` here.
If we specify the bodyLimit on plugin level, the plugin should use its own bodyLimit
```
fastify.register(require('fastify-formbody'), {bodyLimit: 1024 * 1024})
```

I think this is a bug for fastify-formbody, what do you guys think?

**Comment by delvedor** [comment]
Yes, it is a bug in `fastify-formbody`, would you mind to open a pr there?

**Comment by vincent178** [comment]
@delvedor https://github.com/fastify/fastify-formbody/pull/18

**Comment by vincent178** [comment]
Thank you guys for the fast response, problem solved in https://github.com/fastify/fastify-formbody/releases/tag/v2.0.1, I'm going to close this issue.
