### ISSUE TITLE
Redirecting POST turns it into GET

### ISSUE THREAD

**Issue by Zaseth** [fastify/fastify#1049]
Hello.

I have a very weird problem and I tried a few things before filling in this issue. I want to redirect a POST request, PChat.ASP to PChat.php, but Fastify seems to turn it into a GET request. PChat.ASP contains POST data that I want to retrieve, obviously. 
Better explained:

/PChat.ASP(POST - 302 FOUND) => /PChat.php(GET - 404 NOT FOUND)

The route for PChat.php is very simple and looks like this:

```javascript
fastify.post("/PChat.php", { schema }, async (req, res) => {
	const [action, username, room] = [req.body.action, req.body.name, req.body.room]
})
```

I first tried to use it like this:

```javascript
fastify.post("/PChat.ASP", async (req, res) => {
	return res.redirect("/PChat.php")
})
```

That didn't work, so I googled and came upon something related to Express where the status code needs to be 307 to maintain the POST request.

I tried the following by using 307 as my status code like so:

```javascript
fastify.post("/PChat.ASP", async (req, res) => {
	return res.code(307).redirect("/PChat.php")
})
```

That also didn't seem to work, making me wondering if this is something that has to do with Fastify. I hope this can be resolved 👍

**Comment by mcollina** [comment]
You can pass an status code to redirect. However, there is a bug in the redirect code, if a status code is set it shouldn’t overwrite it. Would you like to send a PR?

**Comment by Zaseth** [comment]
I have no idea how to fix the bug with the redirect code myself.

**Comment by ShraddheyaS** [comment]
Hey, I would like to take this up. I believe [this function](https://github.com/fastify/fastify/blob/fd8fb5e55aa7d20e48892a426a49fcb575d6cec6/lib/reply.js#L144) needs to be changed so that if `code` is already set, then don't override `code` with 302.

**Comment by mcollina** [comment]
Yes exactly! Go for it!

**Comment by ShraddheyaS** [comment]
I think that the test for `reply` will also have to be edited. Specifically, [this](https://github.com/fastify/fastify/blob/36960965710756148cd86bc040d2c6f25ee4d04d/test/internals/reply.test.js#L195) and [this](https://github.com/fastify/fastify/blob/36960965710756148cd86bc040d2c6f25ee4d04d/test/internals/reply.test.js#L214). 
Can you tell me what should be done to fix them?

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/blob/36960965710756148cd86bc040d2c6f25ee4d04d/test/internals/reply.test.js#L195 should ideally stay the same.

https://github.com/fastify/fastify/blob/36960965710756148cd86bc040d2c6f25ee4d04d/test/internals/reply.test.js#L214 would need to be amended.

**Comment by ShraddheyaS** [comment]
The problem seems to be that the variable `this.res.statusCode` is always set (to 200) inside the function `redirect`. I can't seem to understand why. Also, in which case, what should be done to fix this?

**Comment by delvedor** [comment]
I think because `200` is the default value of the Node's core `statusCode`.

**Comment by mcollina** [comment]
IMHO We should track if https://github.com/fastify/fastify/blob/master/lib/reply.js#L123-L126 has been called.

**Comment by delvedor** [comment]
@mcollina or handle the `statusCode` in the same way we are handling the headers.

**Comment by ShraddheyaS** [comment]
@delvedor - How are you handling the headers?

Also, how feasible it is to change the prototype of the function `redirect` so that it used the already set `statusCode` and takes *only* one argument, i.e. the URL.
This will mean that the call to `redirect` will need to be after a call to `code`.

**Comment by delvedor** [comment]
We are storing them inside an object:
https://github.com/fastify/fastify/blob/36960965710756148cd86bc040d2c6f25ee4d04d/lib/reply.js#L90 and we send them with `writeHead`.
https://github.com/fastify/fastify/blob/36960965710756148cd86bc040d2c6f25ee4d04d/lib/reply.js#L188

You can do the same.

> Also, how feasible it is to change the prototype of the function redirect so that it uses the already set statusCode and takes only one argument, i.e. the URL.
This will mean that the call to redirect will need to be after a call to code.

Unfortunately this will introduce a breaking change.

**Comment by Zaseth** [comment]
I have created a GIST to demonstrate the bug. https://gist.github.com/Zaseth/b52d119297980b36d6f751b2dea4f3b9

**Comment by ShraddheyaS** [comment]
I've put in a PR #1051 resolving this. I wasn't sure on how to include the testing and benchmarking results.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1051.
