### ISSUE TITLE
Redirect doesn't work for .swf files

### ISSUE THREAD

**Issue by Zaseth** [fastify/fastify#1052]
Hello.

I want to redirect `/join/join.swf` to `/register.html`. The file `Chat.swf` contains a button to load `/join/join.swf`, but when I want to redirect that, nothing happens!

GIF here: (click to enlarge)

![2018-07-25_16-59-35](https://user-images.githubusercontent.com/24899039/43209146-3de5ad88-902c-11e8-9a21-41a29bd5da1e.gif)

You can see in the network tab that I am getting redirected, but `register.html` isn't actually loaded. I don't know if this is an issue with Fastify or just because it's Flash, but it's still rather weird. Just going to `/join/join.swf` redirects me to `/register.html` though.

The route:
```javascript
fastify.get("/join/join.swf", (req, res) => {
	res.code(307).redirect(302, "/register.html")
})
```

The logs for the redirect:
![tqunrcu](https://user-images.githubusercontent.com/24899039/43209472-f7142564-902c-11e8-86c5-76973d5e7e7d.png)

Edit:
/join/join.swf has the `location` header set to `/register.html`. /register.html also seems to contain the `X-Requested-With: ShockwaveFlash/30.0.0.134` which means that my redirect was successful.

**Comment by delvedor** [comment]
Can you share some code?
