### ISSUE TITLE
Validation Error response has the wrong 'Content-Type'

### ISSUE THREAD

**Issue by roozg** [fastify/fastify#1056]
I'm making a simple POST request using Postman. My request header has both 'Content-Type' and 'Accept' set to 'application/json' but if the validation fails the response comes in the form of plain text with Content-Type 'text/plain; charset=utf-8'. 

I expected it to be a JSON response. Is this the expected behavior? If so how do I make it return a JSON response?

I'm not using any special plugins or third party validations. It's all vanilla Fastify. Bellow is my route.

```js
     fastify.route({ 
        method: 'POST',
        url: '/test',
        schema : {
            body: {
                properties: {
                    name: {type: 'string'},
                    age: {type: 'number'}
                },
                required: ['name', 'age']
            },
        },
        handler: async (req, res) => {...},
    })
```

#### Context

* *node version*: 8.11.1
* *fastify version*: >=1.9.0
* *os*: Windows

**Comment by StarpTech** [comment]
Hi @roozg could you post a reproducible example?

**Comment by StarpTech** [comment]
I can't reproduce it. Here is my postman collection:
[Fastify.postman_collection.zip](https://github.com/fastify/fastify/files/2234971/Fastify.postman_collection.zip)

Example:

```js
'use strict'

const fastify = require('../fastify')({
  logger: true
})

fastify.route({
  method: 'POST',
  url: '/test',
  schema: {
    body: {
      properties: {
        name: {type: 'string'},
        age: {type: 'number'}
      },
      required: ['name', 'age']
    }
  },
  handler: async (req, res) => {
    res
      .send({ hello: 'world' })
  }
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

**Comment by roozg** [comment]
@StarpTech Thank you for the quick reply. I've tried again with a fresh Node project with only Fastify installed and no Typescipt and it is working as expected. So it's going wrong somewhere in my main project and I need to figure out where.
