### ISSUE TITLE
Rename `Server method` documentation

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#1057]
The `Server method` documentation doesn't describe only "methods"

https://github.com/fastify/fastify/blob/92f474ea8c981bca64f46427383ed56d50d40998/docs/Server-Methods.md#basepath
https://github.com/fastify/fastify/blob/92f474ea8c981bca64f46427383ed56d50d40998/docs/Server-Methods.md#log

Which name could fit better?

**Comment by mcollina** [comment]
Server? And we merge it with Factory?

**Comment by jsumners** [comment]
I agree.
