### ISSUE TITLE
Logging: Passing object

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify#1059]
Hello everyone!
I know that with pino is possible to pass a full object to the log.info but seems that this doesn't work as default for fastify.

I would like to use something like:
```
const requestLog = {
      body: request.body,
      query: request.query,
      params: request.params,
      headers: request.headers,
      raw: request.raw,
      id: request.id
    }

request.log.info(requestLog)
```

This command print out undefined but the object has a lot of information.
Thanks!

**Comment by mcollina** [comment]
I'm not getting `undefined` just by testing this quickly. Would you mind adding a full example to reproduce?

**Comment by lgertel** [comment]
Got it working this way:

```
fastify.addHook('onRequest', async (request, reply) => {
    const authenticated = await fastify.authMiddleware({ request, reply })
    if (authenticated) {
      fastify.log.info('User is allowed to use this resource')
    } else {
      const err = new Error()
      err.statusCode = 403
      err.message = 'User not allowed to use this resource'
      throw err
    }

    const requestLog = {
      body: request.body,
      query: request.query,
      params: request.params,
      headers: request.headers,
      raw: request.raw,
      id: request.id
    }

    let child = request.log.child({
      requestLog
    })
    
    child.info('LOG')
  })
```
Maybe because it's inside onRequest?

And one point: i'm using pino-elasticsearch on a docker container.
My app is starting with the command fastify start -l info app.js | pino-elasticsearch

**Comment by allevo** [comment]
Hi!
Thank you for checking out Fastify!

According with the documentation (https://www.fastify.io/docs/latest/Hooks/) the `onRequest` hook receives `req` and `res` (and `next`) parameters that are instances of `IncomingMessage` and `ServerResponse`. That properties aren't set in that instances.

Instead, if you register your handler on `preHandler` hook, the first two parameters are instance of `fastify` classes (`Request` and `Response`)  that have those properties.

Another tips: the body in on yet parsed before `onRequest` hook. If you want, here (https://www.fastify.io/docs/latest/Lifecycle/) you can find the request lifecycle!

*NB:* logging the whole request for each incoming request could be expensive and it could be a security issue!
