### ISSUE TITLE
http2 expectations

### ISSUE THREAD

**Issue by guyisra** [fastify/fastify#1064]
how does fastify expects the entire system to behave when working in http2?

fastify support http2 and fallback to http1 but only when using https

I don't really want node to handle https, but rather some other dedicated proxy to do it, but then - what is expected of me? To create a self signed certificate and allow it in the proxy? or use h2c (http2 over plaintext) between node and proxy, but then not be able to fallback to http1?

Not really an issue, but would like to know the contributors thoughts and expectations when implementing the http2 feature.

thanks

**Comment by mcollina** [comment]
All of these are very interesting questions, and we don’t have many answers for them yet. From an API perspective, we added http2 because we could. The heavy lifting is done by Node core, and not within fastify. Node core http2 support is experimental, and so is fastify’s.

**Comment by guyisra** [comment]
alright, not having an answer is also an answer :)

thanks 👍
