### ISSUE TITLE
Decorating raw request object

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1068]
#### What are you trying to achieve?

I'm using `fastify` with [next.js](https://github.com/zeit/next.js). `Next` has a functionality to use Node `request` object in the `React` component to generate initial props, like this:

```
import React from 'react'

export default class extends React.Component {
  static async getInitialProps({ req }) {
    const userAgent = req ? req.headers['user-agent'] : navigator.userAgent
    return { userAgent }
  }

  render() {
    return (
      <div>
        Hello World {this.props.userAgent}
      </div>
    )
  }
}
```

What I'd like to achieve is to decorate the request with user data. Unfortunately, `fastify` has only API to decorate `fastify` `Request` and `Reply` objects - and I can't access any of these in `Next`.

Is there any recommended way to do this? Like... a `onRequest` hook?

#### Context

* *node version*: 9.11.2
* *fastify version*: ^1.8.0
* *os*: Mac

**Comment by mcollina** [comment]
how are you wiring things up with next.js? Can you provide a full example so that we can take a look?

**Comment by sarneeh** [comment]
So I've created a helper plugin to decorate Fastify `Reply` object with Next [render](https://github.com/zeit/next.js#custom-server-and-routing) method.

```js
const next = require("next");
const fastifyPlugin = require("fastify-plugin");

const nextPlugin = async (server, config, done) => {
    const app = next(config);

    await app.prepare();

    server.addHook("preHandler", (request, reply, done) => {
        reply.render = async path => {
            await app.render(request.req, reply.res, path);
            reply.sent = true;
        };
        done();
    });

    server.addHook("onClose", () => {
        app.close();
    });

    done();
};

module.exports = fastifyPlugin(nextPlugin, {
    name: "next"
});
```

Then I have my custom Fastify server:

```js
const fastify = require("fastify");

const nextPlugin = require("./plugins/next");

const server = fastify({ logger: true });

server.register(nextPlugin, {});

server.get("*", (request, reply) => {
    reply.render('/');
});

server.listen(3000, error => {
    if (error) throw error;
});
```

**Comment by sarneeh** [comment]
I've just used a `onRequest` hook for this. This is second time when Fastify own request and response objects brought some problems to me (the need to access `request.req` and `reply.res`). Of course it doesn't mean that it's a bad approach - just wanted to share a thought 😄 

Can be closed!

**Comment by delvedor** [comment]
@sarneeh from the next major of Fastify every hook will have the Fastify own `Request` and `Reply` objects! https://github.com/fastify/fastify/pull/1066
We are using our own because it is faster, and decorate the Node core objects is very expensive.

**Comment by sarneeh** [comment]
@delvedor Oh! Good to know. Thanks for info 👍
