### ISSUE TITLE
Renaming fields on response schema

### ISSUE THREAD

**Issue by cyberwombat** [fastify/fastify#107]
I've browed the schema specs but was not able to find this. I wonder if you have encountered this issue and how you might suggest dealign with it besides just pre parsing my db output which sort of defeats the purpose a bit.

For example if I wished to pull mongo data and expose it through the schema I might want to rename my `_id` field to `id`.  This seems like a useful option (also along those lines is the restructuring of the response).

**Comment by mcollina** [comment]
I think the best way to restructure the response is to do it manually. Having a fast, generic tool that does restructuring is _very_ tricky.

**Comment by cyberwombat** [comment]
I agree though perhaps a simple added field like "rename": "foo" might be efficient enough?

**Comment by mcollina** [comment]
@cyberwombat yes, but it would require adding the support for it in https://github.com/fastify/fast-json-stringify. The code there is highly complicated, so I would not like to complicate it further. However, you should do a new library for this! It would be pretty handy.

I'm closing this now, as we would not implement this feature, but feel free to keep discussing if you need help in implementing your library.
