### ISSUE TITLE
Handling unexpected errors in request processing

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1078]
#### What are you trying to achieve or the steps to reproduce?

So basically: i'd like to catch somewhere all unexpected errors and handle them somehow.

Giving an example, I'd like this test to pass:

```js
test('handle error manually', async t => {
  t.plan(2);

  const server = fastify();

  const plugin = fastifyPlugin((fastify, config, done) => {
    fastify.setErrorHandler((error, request, reply) => {
      reply.code(500).send('Something really bad happened.');
    });

    fastify.get('/plugin', (request, reply) => {
      throw new Error();
    });

    done();
  });

  await server.register(plugin).ready();

  const response = await server.inject({
    method: 'get',
    url: '/plugin'
  });

  t.equal(response.statusCode, 500);
  t.equal(response.payload, 'Something really bad happened.');
});
```

#### What was the result you received?

```js
0/2
  handle error manually
  not ok Error
```

#### Question

Do I really have to `try { } catch(error) { reply.send(error) }` in all the routes to achieve that?

**Comment by allevo** [comment]
Hi!
fastify doesn't catch uncaught error for you. So, yes you should envelope the throwable code inside a `try / catch`. 

NB: your handler is a plain function, not an `async` one. If your route is declared as `async`, the error is caught by the promise and handles by fastify well.

**Comment by sarneeh** [comment]
@allevo Hmm so if you're catching promise rejection why you're not catching uncaught errors? 🤔

**Comment by delvedor** [comment]
@sarneeh you can checkout a complete answer in https://github.com/fastify/fastify/issues/850 :)

**Comment by sarneeh** [comment]
@delvedor Huh, that makes sense :) I got convinced by the arguments :D Thanks for clarifying things up!
