### ISSUE TITLE
Expose connection.remoteAddr to request?

### ISSUE THREAD

**Issue by jbergstroem** [fastify/fastify#1085]
Was looking for a way to use client ips (`remoteAddr`) for compaing incoming request against a simple whitelist/blacklist and ran short. It looks like it is attached to a `onRequest` hook but I can't help but feel this should exist on a `request` object as part of the normal request/response cycle. I saw that https://github.com/fastify/fastify/issues/1044 seems to address this but felt that the XFF part might be a somewhat different discussion. Thoughts on decorating the request?

**Comment by allevo** [comment]
Hi!
You can access to the nodejs IncomingMessage using [`raw` attributes](https://www.fastify.io/docs/latest/Request/)

**Comment by jbergstroem** [comment]
Ah, of course. Apologies.
