### ISSUE TITLE
Do not store properties on node core req and res

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1087]
The only downside of this is that they would not be available inside of middlewares.

This should include the logger.

**Comment by delvedor** [comment]
I completely agree with this, but this would mean drop middlewares support.

**Comment by mcollina** [comment]
would it? which properties are needed for the middlewares?
As an example, the helmet suite does not rely on any of our added properties.

**Comment by delvedor** [comment]
`log` for example.
A solution could be to provide a plugin that adds the properties that could be needed by a middleware. In this way, we make even more clear that the middlewares support is just a compatibility layer and if a user wants to create a new way to interact with the lifecycle should use a Fastify hook.

**Comment by mcollina** [comment]
I think this is a bad idea.
