### ISSUE TITLE
additionalProperties json schema option doesn't work

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1093]
#### What are you trying to achieve or the steps to reproduce?

I just wanted to use the `additionalProperties` option in my JSON schema for a server route. Here's a test that fails:

```js
const t = require('tap');
const fastify = require('fastify');

t.test('should return 400', async t => {
  t.plan(1);

  const server = fastify();

  const schema = {
    body: {
      properties: {
        name: { type: 'string' }
      },
      required: ['name'],
      additionalProperties: false
    }
  };

  server.post('/', { schema }, (request, reply) => {
    reply.send();
  });

  await server.ready();

  const response = await server.inject({
    url: '/',
    method: 'post',
    payload: {
      name: 'John',
      surname: 'Doe'
    }
  });

  t.equals(response.statusCode, 400);
});
```

I've also checked if this is not an `ajv` issue, but this one passes:

```js
const Ajv = require('ajv');
const ajv = new Ajv();

t.test('should be invalid', t => {
  t.plan(1);

  const schema = {
    properties: {
      name: { type: 'string' }
    },
    required: ['name'],
    additionalProperties: false
  };

  const validate = ajv.compile(schema);

  t.false(
    validate({
      name: 'John',
      surname: 'Doe'
    })
  );
});
```

Any ideas what's wrong?

#### Context

* *node version*: 9.11.2
* *fastify version*: 1.8.0
* *os*: Mac

**Comment by mcollina** [comment]
We use these options in fastify https://github.com/fastify/fastify/blob/28436d1e92db07d3644730772191aff484be5a13/lib/validation.js#L155-L165

```js
{
    coerceTypes: true,
    useDefaults: true,
    removeAdditional: true
}
```

The `removeAdditional` option make sure that the route does not return a 400, but rather the spurious properties are removed.

I think we should add some more documentation about this.

**Comment by sarneeh** [comment]
Woah! I've noticed your default configuration but didn't know that `removeAdditional` creates such behaviour. Thanks for info!

**Comment by sarneeh** [comment]
@mcollina I'd love to but not right now 😢 I'm near the deadlines and have not even a little of spare time. I could do this like in a month, so if it's something that can wait this long you can assign me to this so I'd remember.

**Comment by cemremengu** [comment]
I think this can be closed. @sarneeh do you think the updated readme is more helpful now on this topic?

**Comment by sarneeh** [comment]
@cemremengu It nicely emphasizes the default configuration which was not obvious to find. Although my main problem was that I didn't really know **what kind of behaviors do those default values create**. So how about a short comment next to each of the default property describing what does it do to our schemas?

**Comment by cemremengu** [comment]
@sarneeh see #1124

**Comment by sarneeh** [comment]
@cemremengu Awesome, thank you! 👍
