### ISSUE TITLE
Suspected dead code in listenPromise

### ISSUE THREAD

**Issue by trivikr** [fastify/fastify#1099]
#### You have already researched for similiar issues?
Yes

#### Are you sure this is an issue with the fastify or are you just looking for some help?
This seems to be a dead code in fastify

#### Is this a security related issue?
No

#### What are you trying to achieve or the steps to reproduce?
I was trying to add a test for covering the following line https://github.com/fastify/fastify/blob/6bce249e04c60914280b5919efdb4ded6a745925/fastify.js#L314

I noticed that the address can never be undefined as it's set to `'127.0.0.1'` is calling function https://github.com/fastify/fastify/blob/6bce249e04c60914280b5919efdb4ded6a745925/fastify.js#L347-L359

#### What did you expect?
Is the check on the following line redundant?
https://github.com/fastify/fastify/blob/6bce249e04c60914280b5919efdb4ded6a745925/fastify.js#L314

**Comment by mcollina** [comment]
Go ahead and remove it, it seems a duplicate!

**Comment by trivikr** [comment]
The `address = address || 'localhost'` supposedly fixed the 500ms delay issue on Windows which was discussed and fixed in #1047

However, the current issue existed when the fix was introduced

Should `'127.0.0.1'` change to `'localhost'` on line 351?
https://github.com/fastify/fastify/blob/6bce249e04c60914280b5919efdb4ded6a745925/fastify.js#L351

**Comment by trivikr** [comment]
Fix posted in PR #1102
