### ISSUE TITLE
Suggestion: JSON based plugin configuration

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1100]
I am currently using the framework [eggjs](https://eggjs.org/). The `AutoLoader` of this framework checks a specific folder called [config](https://github.com/eggjs/egg/blob/master/docs/source/en/basics/config.md) and looks for the files `config.js` and and `plugin.js` where the complete configuration of plugins is specified. For packaged plugins downloaded from npm, fastify can do a similar thing and auto-load them from these files so instead doing

`fastify.register(require("fastify-multipart"));`

one can do

```
exports.multipart= {
  enable: true,
  package: 'fastify-multipart',
};
```

Good thing about this approach is that it separates configuration from code completely, and plugins or configuration can be changed depending on the current `environment` whether it is prod or testing.  Maybe the same can be done in fastify at the moment but it can be nice if this baked into the fastify core itself. Below are examples of plugin and config files:

*config.default.js*
```js
'use strict';
const path = require('path');

module.exports = (appInfo) => {
  const config = (exports = {});

  config.middleware = ['errorHandler', 'gzip'];

  config.logger = {
    consoleLevel: 'ERROR',
    dir: path.join(appInfo.baseDir, 'logs'),
  };

  config.gzip = {
    threshold: 1024, // skip response body which size is less than 1K
  };

  config.jwt = {
    secret: process.env.SECRET,
  };

  config.security = {
    csrf: {
      enable: false,
    },
  };

  config.multipart = {
    fileSize: '50mb',
    whitelist: ['.xlsx'],
  };

  config.validate = {
    enable: true,
    package: 'egg-validate',
  };

  config.knex = {
    client: {
      dialect: 'oracledb',
      connection: {
        host: process.env.ORA_HOST,
        port: process.env.ORA_PORT,
        user: process.env.ORA_USER,
        password: process.env.ORA_PASSWORD,
        database: process.env.ORA_DATABASE,
      },
    },

    // load into app, default is open
    app: true,
    // load into agent, default is close
    agent: false,
  };

  return config;
};
```

*plugin.js* (core plugins are already enabled so not specified here)
```js
'use strict';

exports.knex = {
  enable: true,
  package: 'egg-knex',
};

exports.cors = {
  enable: true,
  package: 'egg-cors',
};

exports.validate = {
  enable: true,
  package: 'egg-validate',
};

exports.jwt = {
  enable: true,
  package: 'egg-jwt',
};
```

**Comment by jsumners** [comment]
How would you support encapsulation doing this?

**Comment by mcollina** [comment]
I think this could be built as a plugin on top, if you think you would need such a feature.
I recently wrote https://github.com/fastify/fastify-autoload, more or less to simplify project setup.

**Comment by cemremengu** [comment]
Nice, fair enough. Looks like fastify is infinitely modular/extensible :smile:

**Comment by delvedor** [comment]
> Looks like fastify is infinitely modular/extensible 😄

That's one of our design goals :)
