### ISSUE TITLE
`npm run lint` does not work with pnpm installed dependencies

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1115]
```sh
$ git clone https://github.com/fastify/fastify.git
$ cd fastify
$ pnpm install
$ npm run lint # will fail
```

This results in git commits failing:

![image](https://user-images.githubusercontent.com/321201/44791782-6b51a600-ab70-11e8-917e-1405da7f4628.png)

However, running `standard | snazzy` will work just fine. The issue is with the TypeScript linting.

**Comment by mcollina** [comment]
Can you try?

```
rm -rf node_modules
npm install
```

I would like to check if it's a pnpm bug.

**Comment by jsumners** [comment]
I did that before filing the bug and it works as expected. I do not think that indicates a pnpm bug. pnpm does not create a flat structure like npm does. So it is likely there is some dependency somewhere in the TypeScript setup that is broken.

**Comment by jsumners** [comment]
cc: @zkochan
