### ISSUE TITLE
use jitson for fast JSON parsing in fastify

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1136]
I think we should consider integrating [jitson](https://www.npmjs.com/package/jitson) in v2.

@fastify/fastify what do you think?

**Comment by StarpTech** [comment]
Do you mean as a default parser but you won't replace it with [fast-json-stringify](https://github.com/fastify/fast-json-stringify) right?

IMO usually, the schema of an endpoint is fixed. I don't know how we can benefit from such just-in-time approach. I think we can avoid this complexity and use the native JSON api and in all other cases we can still go with fast-json-stringify.

I could also miss something. @mcollina could you describe your view?

**Comment by mcollina** [comment]
fast-json-stringify is used when we send data. jitson is for parsing. The benefit of using jitson everywhere is that it would increase parsing JSON _even if_ a schema is not defined. Moreover, certain parts of JSON.schema are really hard to optimize in this way.

**Comment by cemremengu** [comment]
> increase parsing JSON even if a schema is not defined.

This will be great

**Comment by StarpTech** [comment]
Nevermind, I mixed up the things 😄 

Parsing -> Ajv
Stringify -> fast-json-stringify

Both use JSON-Schema

In my updated view it would only make sense when we use jitson when no json schema was passed. Do you also consider to support the [turbo-json-parse](https://github.com/mafintosh/turbo-json-parse) as an alternative to JSON-schema?

**Comment by StarpTech** [comment]
Nevermind, I mixed up the things 😄 For clarification:

```
Parsing -> JSON.parse
Validation -> Ajv (JSON-Schema)
Stringify -> fast-json-stringify (JSON-Schema)
```

new way when using jitson

```
Parsing -> jitson (JSON-Schema)
Validation -> Ajv (JSON-Schema)
Stringify -> fast-json-stringify (JSON-Schema)
```

**Comment by mcollina** [comment]
Yes!

**Comment by delvedor** [comment]
I would love to see some benchmarks!

**Comment by allevo** [comment]
Why should not we integrate turbo-parse-json directly?

**Comment by mcollina** [comment]
Not really, as supporting anyOf and other advanced part of the spec would
be extremely hard.
Il giorno mer 5 set 2018 alle 19:46 Tommaso Allevi <notifications@github.com>
ha scritto:

**Comment by cemremengu** [comment]
Is it possible to make stringify faster when _response_ schema is not defined or `JSON.stringify` is as fast as we can get?

**Comment by jsumners** [comment]
I’m okay with it as long as the current mechanism for supplying your implementation remains.

**Comment by mcollina** [comment]
I think we concluded not to do this for v2, to be explored in a plugin.

**Comment by Sanjayjeyavel** [comment]
Hey guys! I would like to work on this. My understanding is that we need to create a new plugin that will parse all requests with jitson. Is there anything else I need to be aware of before getting started?

**Comment by delvedor** [comment]
@Sanjayjeyavel thanks! Nope, you are free to go :)
You can use a [custom content type parser](https://www.fastify.io/docs/latest/ContentTypeParser/) and it should work! :)

**Comment by wen911119** [comment]
How about [simdjson](https://github.com/lemire/simdjson)?

**Comment by delvedor** [comment]
@wen911119 I would love to see some benchmarks, but usually, we prefer to avoid native dependencies unless really necessary.
Furthermore, usually the JSONs are not that big, and the price you pay for jumping between JS and C code is quite high.

**Comment by dnlup** [comment]
@mcollina I tried to put together something very basic:
  https://github.com/dnlup/fastify-jitson
does it come close to what you had in mind?

**Comment by mcollina** [comment]
Yes! You should add:

* [ ] docs
* [ ] benchmark results

**Comment by delvedor** [comment]
@dnlup there is already an open (but possibly dead) pr in https://github.com/fastify/fastify-jitson.
Would you like to open a pr with your implementation there? :)

**Comment by dnlup** [comment]
@delvedor will do!

**Comment by mcollina** [comment]
Closing, this is worked on and probably not a good idea - jitson is not performing as expected.
