### ISSUE TITLE
inject.test.js is failing on master

### ISSUE THREAD

**Issue by trivikr** [fastify/fastify#1138]
#### You have already researched for similar issues?
Yes. I couldn't find this issue at https://github.com/fastify/fastify/issues

#### Are you sure this is an issue with the fastify or are you just looking for some help?
Yes. 

#### Is this a security related issue?
No, this is not a security issue

#### What are you trying to achieve or the steps to reproduce?
Run `npm run test` on fastify master branch (HEAD at 0a874b9b7dc66e376df495bcaa776c5844ecea76)

#### What was the result you received?
Here's a log
```
test/inject.test.js ................................. 54/56
  should error the promise if ready errors
  not ok this should not be called
    at:
      line: 388
      column: 7
      file: test/inject.test.js
      function: fastify.inject.then
    stack: |
      fastify.inject.then (test/inject.test.js:388:7)
    source: |
      t.fail('this should not be called')

  should error the promise if ready errors
  not ok test unfinished
    stack: |
      Object.<anonymous> (test/inject.test.js:374:1)
    test: should error the promise if ready errors
    at:
      line: 374
      column: 1
      file: test/inject.test.js
      function: Object.<anonymous>
    source: |
      test('should error the promise if ready errors', t => {
```

#### What did you expect?
build should pass without any errors

#### Context

* *node version*: 10
* *fastify version*: master
* *os*: Mac

**Comment by mcollina** [comment]
you'll need to update your dependencies, this requires the latest version of avvio.

**Comment by trivikr** [comment]
My bad.

To update my dependencies, I ran
* `rm -rf node_modules`
* `npm install`
* `npm run test`

However, the error was still appearing.
I removed fastify from the workspace and cloned it again, which fixed the issue. Is there a different way to update dependencies? Also, can we add a way to check if dependencies are updated before the tests are run?
