### ISSUE TITLE
Got `404` response for router with `version` option in some case.

### ISSUE THREAD

**Issue by poppinlp** [fastify/fastify#1143]
Here's a simple case to reproduce:

```js
const fastify = require('fastify');

fastify()
  .route({
    method: 'GET',
    url: '/t1',
    version: '0.1.0',
    handler: (request, reply) => {
      reply.send('hello t1');
    }
  })
  .route({
    method: 'GET',
    url: '/t2',
    version: '0.1.0',
    handler: (request, reply) => {
      reply.send('hello t2');
    }
  })
  .listen(12345, 'localhost');
```

Start this app to listen on `12345` port and send some requests by postman with correct url and `Accept-Version`. But the `/t1` got 404 response and `/t2` got correct response.

These requests will works fine if i remove the `version` option in router and `Accept-Version` header.

I have checked [your doc](https://www.fastify.io/docs/latest/Routes/#version) but haven't get any clues.

I'm i using it in wrong way? Thanks.

#### Context

* *node version*: 10.9.0
* *fastify version*: 1.11.1
* *os*: Mac

**Comment by mcollina** [comment]
Does this happens if you do not use plugins/register/prefix, but just a single file?

**Comment by poppinlp** [comment]
@mcollina 
Sry for my making it complicated. I use those two router just for showing the differences.
I have updated the issue description to show the minimum reproduction case.

> Does this happens if you do not use plugins/register/prefix, but just a single file?

Yes, it's still happens.

**Comment by mcollina** [comment]
I think this is really an issue in https://github.com/delvedor/find-my-way or https://github.com/delvedor/semver-store.

**Comment by poppinlp** [comment]
It's fixed in find-my-way. So close this issue.
