### ISSUE TITLE
Add API to iterate over all the routes

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1155]
We added route iteration in https://github.com/fastify/fastify/commit/e93ea55e63f03f6e8a97fa551b6d926f7ad1f0d5, and  removed route it in https://github.com/fastify/fastify/pull/642.

However, it's one of the things that gets asked in gitter or in the issue tracker very often. I think we should add that back in.

**Comment by geeksambhu** [comment]
@mcollina Can I look into this issue?

**Comment by mcollina** [comment]
Go for it!

**Comment by delvedor** [comment]
In my opinion, every feature that is **not essential** for the framework should be released as a separate plugin. In this case is also very easy thanks to the `onRoute` hook.
Why should we have this directly in core?

**Comment by cemremengu** [comment]
There is a plugin for this which prints to _console_
Maybe it can be enhanced for this functionality

https://github.com/PavelPolyakov/fastify-blipp

**Comment by cemremengu** [comment]
This functionality is provided via a plugin. See: https://github.com/cemremengu/fastify-routes
