### ISSUE TITLE
About handle `text/plain` content type.

### ISSUE THREAD

**Issue by poppinlp** [fastify/fastify#1174]
Hi.

I have made a really simple server by fastify and send a request to that with `POST` method and `text/plain` content type. Then i got a 415 response:

```json
{
    "statusCode": 415,
    "error": "Unsupported Media Type",
    "message": "Unsupported Media Type: text/plain"
}
```

Seems there's no default handler for `text/plain` request body content type. And i have read [contentTypeParser.js](https://github.com/fastify/fastify/blob/master/lib/contentTypeParser.js) which dose not have it actually.

I'm interested in the reason since i think it makes sense to support that by default.
Actually, i have found out an [issue you talk about this](https://github.com/fastify/fastify/issues/297#issuecomment-331800305).

#### Context

* *node version*: 10.10.0
* *fastify version*: 1.11.2
* *os*: Mac

**Comment by delvedor** [comment]
We have decided to support only `application/json` natively, everything else needs you to add a custom content type parser, as shown in the [documentation](https://www.fastify.io/docs/latest/ContentTypeParser/).

```js
// by using `{ parseAs: 'string' }` we will handle the request body stream
fastify.addContentTypeParser(
  'text/plain',
  { parseAs: 'string' },
  (req, body, done) => done(body)
)
```

**Comment by poppinlp** [comment]
Thanks. So, seems it's deliberately designed like this.
But why not support that? I think it's the most basic type. Although `application/json` is more popular in real world.  But `application/x-www-form-urlencoded` and `multipart/form-data` are also popular. And they are both in plugins. So the decision to only support json natively seems interesting. :)

**Comment by delvedor** [comment]
@poppinlp general speaking the rule is: *every feature that can be a plugin, should be a plugin.*
In this way is easier to handle future breaking changes and API redesigns.
We decided to keep `application/json` in core (but you can override it) because we want to make sure that is used correctly (read: avoid bad usage of `try catch`) and in the future, we might want to implement some more performant solution, as you can see in https://github.com/fastify/fastify/issues/1136.

**Comment by poppinlp** [comment]
OK. Thanks.

**Comment by Farenheith** [comment]
@poppinlp I've just found this issue while looking for some other things, and just so you can know, (If you don't yet), they ended up implementing `text/plain`.

**Comment by poppinlp** [comment]
> @poppinlp I've just found this issue while looking for some other things, and just so you can know, (If you don't yet), they ended up implementing `text/plain`.

haha, got it, thank you.
