### ISSUE TITLE
Protecting express apps/middlewares

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1175]
#### What are you trying to achieve or the steps to reproduce?

Job scheduling libraries like [agenda](https://github.com/agenda/agenda) or [kue](https://github.com/Automattic/kue) provide an Express middleware/application to get some cool GUI for the scheduling system. As `fastify `supports Express middlewares I guess it would be ok to just do:

`fastify.use(middleware);`

But! I'd like to protect those dashboards at least with some basic authentication.

Unfortunately, AFAIK I can't do that with a `fastify` plugin. This is because the middlewares are a lot earlier in the request lifecycle than hooks like `preHandler` or `beforeHandler` (used i.e. by `fastify-basic-auth`).

Am I missing something or there is no way to accomplish this with `fastify`?

**Comment by delvedor** [comment]
Hi! You can run the authentication before the middlewares in two ways:
1. Use the `onRequest` hook
1. Register an authentication middleware *before* your middleware

You can the lifecycle of every request [here](https://www.fastify.io/docs/latest/Lifecycle/) :)

**Comment by sarneeh** [comment]
Well... You're right :D 

But I can't do that with a typical `fastify` plugin (i.e. `fastify-basic-auth`) as they most often rely on `preHandler` or `beforeHandler` (as it's the best place to do those kind of things). Am I right? :)

**Comment by delvedor** [comment]
You are right, but only with the current version of Fastify. From version 2 we will standardize all the hooks, so you will be able to use the same code both in `preHandler` and `onRequest`.

See https://github.com/fastify/fastify/pull/1066 :)

**Comment by sarneeh** [comment]
That will be freakin' amazing :) Thanks for your help!
