### ISSUE TITLE
Drop node 6 support

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1177]
Fastify is a considerably new framework so I am assuming that it is used mainly for greenfield projects. Given that, I think it will be safe to support node >= 8 (including plugins) in version v2.0. It can simplify code and writing unit tests.

[Node10 is also becoming LTS in October 2018 and Node6 will reach end of life on April 2019](https://github.com/nodejs/Release)

What do you think?

**Comment by delvedor** [comment]
We support the same versions that are currently supported of Node.js.
We have discontinued the support for Node v4 in [Fastify v1](https://github.com/fastify/fastify/releases/tag/v1.0.0-rc.3), and we will discontinue the support for Node v6 once it reaches the EOL (which means Fastify v3).

**Comment by cemremengu** [comment]
Fair enough, cant wait for this :smile
