### ISSUE TITLE
Add more benchmarks

### ISSUE THREAD

**Issue by gajus** [fastify/fastify#118]
The current benchmarks are a bit boring and don't say the full story:

> Benchmarks
> 
> Hapi: 2200 req/sec
> Restify: 6133 req/sec
> Express: 8534 req/sec
> Koa: 9640 req/sec
> Fastify: 21287 req/sec

Some information that people would like to know:

* Time to first byte
* Response time
* Scalability

If you Google "nginx vs express.js benchmark" and similar, there will be quite a few benchmarks/ graphs that would be nice to have.

This is your main selling point. I'd focus on that. Good luck.

**Comment by mcollina** [comment]
As this is OSS, you are definitely welcome to maintain an independent benchmark. We will be happy o optimize _fastify_ according to that. However, we would not be objective in developing one. If youa re interested, there is plenty of data to scavenge in what https://github.com/mcollina/autocannon can provide, and I even wrote my own tool for more easy comparison https://www.npmjs.com/autocannon-compare. 

Plus, there are plenty others things you can try to write fast Node.js HTTP servers, including no using any framework. Also, not all those framework offers the same functionality, so any deep analysis would have to take that into acount.

In our tests, _fastify_ comes out faster in all the directions you mentioned in Node 6.11. In Node 8.1, Koa v2 is almost as fast as, but without a logger and router.
