### ISSUE TITLE
Routes Plugin

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1184]
Per the discussion in #1155, I created [this plugin](https://github.com/cemremengu/fastify-routes).

I think that this is better suited as a core plugin since it offers a solution for a frequently requested functionality. It should also requires minimal maintenance.

If everyone agrees, I would be happy to transfer the ownership to the organization (both github and npm)

@fastify/fastify  Please let me know what you think

**Comment by mcollina** [comment]
I think that should be the path forward. If we agree, remember to add me or @delvedor as owners, so that we can add the module to the npm org.

**Comment by allevo** [comment]
Or move it under fastify GitHub organisation if you want

**Comment by cemremengu** [comment]
@allevo That's actually what I mean by transferring the ownership. Is there another way?

**Comment by cemremengu** [comment]
Let's move forward with this. Transferred repo to Fastify org and gave maintainer access to @mcollina on npm.

Let me know if there is anything else that needs to be done
