### ISSUE TITLE
How does one do a "rest parameter"-like route?

### ISSUE THREAD

**Issue by aaronshaf** [fastify/fastify#1185]
I'd want it to satisfy `/one/two/three/four` and `/one/two/three/four/five`, etc.

I have tried

`fastify.get("/:foo/:bar/:baz+", require("./routes/baz"))`

and

`fastify.get("/:foo/:bar/(.*)", require("./routes/baz"))`

to no avail. Any ideas?

**Comment by delvedor** [comment]
You can use a wildcard, eg:
```js
fastify.get('/:foo/:bar/*', (req, reply) => {
  console.log(req.params) // { foo: 'one', bar: 'two', *: 'three/four' }
})
```

**Comment by aaronshaf** [comment]
To all the lurkers who needed this stupid question to be asked, 

https://media.giphy.com/media/EfHmlClbuNAGc/giphy.gif

**Comment by delvedor** [comment]
No question is a stupid question :)

**Comment by csvan** [comment]
5 years (ish) later, I just wanted to commemorate the heroic sacrifice of @aaronshaf for us all. I and many lurkers have had our projects saved due to this question being asked (and answered!). 

We commend thee <3
