### ISSUE TITLE
Variables per request

### ISSUE THREAD

**Issue by samuelgjabel** [fastify/fastify#1193]
Is some method how to create variables per request?  Like express response.locals['your_param']? Thank you.

**Comment by cemremengu** [comment]
I think you can use `config`

See https://github.com/fastify/fastify/blob/master/docs/Routes.md if that helps

**Comment by samuelgjabel** [comment]
Hm. Thanks but i mean some sharable data (only) per request.

Example: you have authorization middleware (check if user exist in db / verify token). From this step you have user data - or user_id from db & if you have another middleware or get user - route, I want to share data from first step (authorization middleware) - so I dont need to do another DB request.

Its this possible? :)

**Comment by cemremengu** [comment]
I see, you can use [Decorators](https://github.com/fastify/fastify/blob/master/docs/Decorators.md) for this kind of things in general.

Checkout https://github.com/fastify/fastify-jwt for an example

**Comment by delvedor** [comment]
Sure!
You have two ways to achieve that:
1. Add a property to the request object:
```js
fastify.addHook((req, reply, next) => {
  req.locals = ['en-en']
  next()
})

fastify.addHook((req, reply, next) => {
  console.log(req.locals) // ['en-en']
  next()
})
```

2. Same as above, but use also the `decorateRequest` API, to achieve the best performances :)
```js
fastify.decorateRequest('locals', null)

fastify.addHook((req, reply, next) => {
  req.locals = ['en-en']
  next()
})

fastify.addHook((req, reply, next) => {
  console.log(req.locals) // ['en-en']
  next()
})
```

**Comment by samuelgjabel** [comment]
Thanks a lot guys! I think i found what i want :p 

Closing this.
