### ISSUE TITLE
Create an API built in fastify

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1195]
Some of the people on gitter has mentioned that they wanted to have a look at an `open source api built in fastify`.

I think we should do a small app with authentication to demonstrate. Maybe a classical todo list app? We can do it step by step so that it would serve as a tutorial too.

We should also try to showcase as much functionality as possible.

What do you think @fastify/fastify ?

**Comment by StarpTech** [comment]
We already provide an example https://github.com/fastify/fastify-example-twitter but there is still room for improvement regarding docs, code structure...

**Comment by cemremengu** [comment]
@StarpTech oh I missed that one I think it's great. I will go over the TODO list and see how we can improve/polish it.

**Comment by Blaconix** [comment]
Those are exactly my thoughts. I've been taking a look at https://github.com/fastify/fastify-example-twitter/, but then noticed this issue https://github.com/fastify/fastify-example-twitter/issues/24#issuecomment-393343391. 

I also, was unable to run the example. To be honest, I think it would be really appreciated to get a more polished version of this. I am currently learning the in and outs of the framework. Once I get it all down, I might contribute myself with a nice written medium post along with a tutorial.

All in all, thanks a lot for the great framework, can't wait for v2.0.
