### ISSUE TITLE
Produces/Consumes line json

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#1197]
Who do `fastify` and `fastify` ecosystem support the [line json](http://jsonlines.org/)? 

For example, the validation with the swagger description or the serialization with the swagger description?

**Comment by mcollina** [comment]
what do you mean support? I do not think there is any real support for this atm, we should probably write a plugin.

**Comment by allevo** [comment]
In that plugin we ca register the new parser in order the use the request stream directly and piping it to `split2(JSON.parse)`, to ajv object check.
For example:
```js
fastify.addContentTypeParser(['application/nljson'], function (req, done) {
  done(null, pump(req, split2(JSON.parse)))
})
fastify.setSchemaCompiler(function (schema) { // the schema compiler is called for ALL kind of schema: querystring, headers and body. We don't known which kind of schema are we compiling for
  const schema = ajv.compile(schema.items) // item schema
  return function (objectStream) {
    const checkDocStream = through2.obj(function (chunk, enc, cb) {
      const isValid = schema(chunk)
      if (isValid) {
        cb(null, chunk)
        return
      }
      cb(new Error('this should be a 400 Bad request'))
    })
    // We should replace the body with the "checkDocStream" stream
    // but the "req" object is not available here
    req.body = objectStream.pipe(checkDocStream)
  }
})
fastify.post('/', function (request, reply) {
  request.body.on('data', function (d) {
    console.log(d, 'is a checked object')
  })
})
```

For the serialization part:
```js
function createSerializer (reply) {
  if (reply.context.config.nljson) {
    return reply.context.config.nljson
  }
  // if an error occurred, this is the serializer too?
  return compile(reply.context['200'])
}

fastify. addHook('preHandler', function (request, reply) {
  if (willProduceNLJSON(req)) {
    reply.serialize(createSerializer(reply))
  }
})
fastify.get('/', function (request, reply) {
  const reader = getReaderStreamObject() // a stream of object
  return reader // The object mode is not supported by fastify
})
```

The above code doesn't work

**Comment by mcollina** [comment]
Why don't you start a repo? I would avoid `setSchemaCompiler` for this.

**Comment by zhangwinning** [comment]
Hi! still open pr , I would like to help :)

**Comment by mcollina** [comment]
Awesome, ping us when it's done, we'll review!

**Comment by zhangwinning** [comment]
@mcollina Hey, the works of this plugin wheather transform request params to line json type params, or not another meaning?
the above example I have misunderstood a bit.

**Comment by mcollina** [comment]
Both:

1. receive and parse newline delimited json as part of the body of a request
2. "stream" down to the client newline delimited json

**Comment by Fdawgs** [comment]
How are you getting on @zhangwinning?

**Comment by Fdawgs** [comment]
I think it's worth closing this, it's been 4 years and no one else has requested/pushed for this plugin.
