### ISSUE TITLE
Hooks context

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#120]
If you use `decorate` to add a new function to Fastify, that function will have Fastify as context, for example:
```js
fastify.decorate('test', function () {
  console.log(this) // this is fastify
})
``` 
While if you add a hook the context is `undefined`. Could be useful bind it by default?
```js
fastify.addHook('onRequest', function (req, reply, next) {
  console.log(this) // undefined
})
```

**Comment by mcollina** [comment]
Let's leave it as it is and this issue open, and maybe we'll do that if there is a need.

**Comment by jsumners** [comment]
I claim there is definitely a need for this. As a concrete example, I am attempting to use it `fastify-caching` to access `this.cache` so I can store an indicator that the resource can be served from the user's cache:

```js
instance.addHook('onResponse', function (res, next) {
  if (!res.hasHeader('etag')) return next()
  this.cache.set(res.getHeader('etag'), true, 1000, next)
})
```

**Comment by mcollina** [comment]
definitely 👍 . I think we should work on a PR after #330 lands.

**Comment by jsumners** [comment]
Is there anyone familiar with how this works that is willing to start the PR now that #330 is merged? cc: @fastify/fastify

**Comment by StarpTech** [comment]
Should be easy, here a start:

- onSend: https://github.com/fastify/fastify/blob/6d596ab5f7acfc4070d7e4f7e5be22c5132cf331/lib/reply.js#L143
- https://github.com/fastify/fastify/blob/6d596ab5f7acfc4070d7e4f7e5be22c5132cf331/fastify.js#L252

**Comment by StarpTech** [comment]
I created a PR https://github.com/fastify/fastify/pull/408

**Comment by StarpTech** [comment]
I created a new one https://github.com/fastify/fastify/pull/414

**Comment by jsumners** [comment]
It'd be really great if you simply pulled in upstream changes to an existing PR to resolve conflicts in the future.

**Comment by StarpTech** [comment]
For me it was easier to create a new one instead to merge the changes. I can take care about this in future.

**Comment by StarpTech** [comment]
Fixed in https://github.com/fastify/fastify/pull/414
