### ISSUE TITLE
Custom request validation error responses

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1202]
Currently, `ajv` is bailing immediately when there is an error in the request schema sending back the default error message. 

As also stated in one of the `gitter` conversations, we need a way to override this behavior for custom error messages/responses.

**Comment by mcollina** [comment]
Agreed. We have three options:

1. route-specific validation error handler
2. forward the error to our default error handler
3. add another instance handler for validation errors.

I think option 1) could be implement in v1 as a semver-minor. Option 2) and option 3) are mutually exclusive.  Considering our decision for 404s in v2, option 2 _might_ be slightly better as there would need to be some custom handling logic for status codes anyway.

@fastify/fastify what do you think?

**Comment by mcollina** [comment]
@cemremengu would you like to send a PR for implementing option 2?

**Comment by delvedor** [comment]
Agree for option 2.

**Comment by cemremengu** [comment]
Will this be similar to #1084 accompanied by a `setValidationErrorHandler` ?

**Comment by mcollina** [comment]
Similar to #1084 but _without_ a `setValidationErrorHandler`.

**Comment by cemremengu** [comment]
I didnt want to bother you by asking questions but here I am 😄 So at the moment, if I am correct, you can set a custom handler for errors like below:

```js
setErrorHandler(function (error, request, reply) {
  if (error.validation) {
     reply.status(400).send(new Error('validation failed!'))
  }
})
```

What I can do on top is return the validation result (here)[https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L63] so the user can handle it in request but this should be opt-in for the user which I am not sure how to make since this will turn the solution into _option 1_

Given these I am not sure how to approach this in terms of expectations

**Comment by mcollina** [comment]
> So at the moment, if I am correct, you can set a custom handler for errors like below:

I don't think you can. Does it work? In that case we should probably just document it.

**Comment by cemremengu** [comment]
This test passes:

```js
test('should be able to specify custom validation error', t => {
  t.plan(3)

  const fastify = Fastify()

  fastify.post('/', { schema }, function (req, reply) {
    reply.code(200).send(req.body.name)
  })

  fastify.setErrorHandler(function (error, request, reply) {
    if (error.validation) {
       reply.status(422).send(new Error('validation failed'))
    }
  })

  fastify.inject({
    method: 'POST',
    payload: {
      hello: "michelangelo"
    },
    url: '/'
  }, (err, res) => {
    t.error(err)
    t.deepEqual(JSON.parse(res.payload), {
      statusCode: 422,
      error: 'Unprocessable Entity',
      message: 'validation failed'
    })
    t.strictEqual(res.statusCode, 422)
  })
})
```

**Comment by mcollina** [comment]
> Currently, ajv is bailing immediately when there is an error in the request schema sending back the default error message.

Then I do not think how the above statement is true, or maybe I misunderstood you completely.

**Comment by cemremengu** [comment]
It seems like he wanted to treat the validation error inside the body so return [here](https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L63) instead of sending response back.

![image](https://user-images.githubusercontent.com/1297759/47423754-8286cb80-d78e-11e8-860f-aeaffd4f8f39.png)

**Comment by cemremengu** [comment]
On top off my head:
We can add a request option like `breakOnValidationError: true`. If false we attach the validation to request to be processed else respond automatically.

**Comment by mcollina** [comment]
I think the first step is to document the current behavior in https://www.fastify.io/docs/latest/Validation-and-Serialization/. I'm also ok for a flag to attach validation error to the Request.
