### ISSUE TITLE
Support for an array of middlewares in .use()

### ISSUE THREAD

**Issue by trygve-lie** [fastify/fastify#1203]
I am currently in the process of porting a couple of applications written in express to fastify. I can mostly reuse different middlewares but I have encountered a small difference between express and fastify in the `.use()` method which would be nice if they where aligned.

Express supports taking an array of middlewares on `.use()` like this:

```js
const middlewares = [
    (req, res, next) => {
        next();
    },
    (req, res, next) => {
        next();
    },
    (req, res, next) => {
        next();
    }
];
app.use(middlewares);
```
In fastify this does not work.

This is actually quite handy to be able to do if one have multiple middlewares one want to provide as a package. Ex; where I work we have a set of security middleware all apps should have. We distribute these middlewares as one security module which in reality is just a `.middleware()` method which return an array of the security middlewares it depends on makind it so that our apps only need to mound one middleware to get all the different middlewares in that package.

If there is interest in having support for `.use()` to take an array of middlewares in fastify I am more than happy to provide a PR for it. What do you think?

**Comment by trygve-lie** [comment]
Note: Helmet did previously use Connect internally to bundle multiple middlewares into one middleware. They have now [switched to just returning an Array](https://github.com/helmetjs/helmet/commit/421dcdf92cf4b2415770298c859aee2db207a6d5) with the different middlewares.

**Comment by mcollina** [comment]
Sure go for it, PRs are always welcome!

Il giorno lun 8 ott 2018 alle 10:59 Trygve Lie <notifications@github.com>
ha scritto:

**Comment by trygve-lie** [comment]
I found the logical place to solve this to be in middie so I made a PR there: https://github.com/fastify/middie/pull/24

**Comment by delvedor** [comment]
Hi! Sorry for the delay!

You can easily use `middlewares.forEach(fastify.use)` and you will accomplish the same result while supporting it internally introduces more logic that is not needed.
Furthermore, we are trying to maintain a similar interface across the various API, and since we don't have any that accepts an array of elements, we should keep it in this way (see also https://github.com/fastify/fastify/issues/1012).

**Comment by cemremengu** [comment]
Landed in https://github.com/fastify/middie/pull/24
