### ISSUE TITLE
Support for optional route parameters

### ISSUE THREAD

**Issue by simoneb** [fastify/fastify#1206]
It seems that optional route parameters are not supported in fastify routing mechanism, or at least they're supported in an uncommon way.

If I write a route like:

```js
app.get('/:param1/:param2')
```

`GET /some/param` with match and give `{ param1: 'some', param2: 'param' }`, as expected.

Not so expected, also `GET /some/` with match and give `{ param1: 'some', param2: {some falsy value} }`.

(Note that I didn't actually check what value `param2` will get, it's either not in the `request.params` at all or it has a falsy value)

This makes it look like the last parameters is indeed optional, but that's only as long as the trailing slash is included in the request. If the trailing slash is omitted, the route will not match.

It would be useful to have a way to declare a parameter (the last one, clearly) as optional so that the route will match when that parameter is missing, with or without trailing slash.

What other routers (i.e. `react-router` or `express`) do is provide this syntax to mark a route parameter as optional:

```js
app.get('/:param1/:param2?')
```

**Comment by cemremengu** [comment]
Maybe this issue is really for `find-my-way` ?

**Comment by delvedor** [comment]
Sorry for the delay.
There is no support for this and it is not planned. I fear that support it would impact the performances too much.

> Not so expected, also GET /some/ with match and give { param1: 'some', param2: {some falsy value} }.

This is a longer discussion around how trailing slashes should behave. Take a look at https://www.fastify.io/docs/latest/Server/#ignoretrailingslash :)

**Comment by Grawl** [comment]
As a workaround I just duplicate my route. Meh.

**Comment by KaKi87** [comment]
Hey @delvedor, are you sure implementing optional parameters costs more performance than duplicating a route ?...

**Comment by delvedor** [comment]
@KaKi87 fairly sure, adding routes is rather cheap with find-my-way, while adding a complete new logic in a critical piece of code will slow down everything else.

We could support the declaration of multiple paths with the same method at the same time (in the same way we are supporting multiple methods).
@mcollina what do you think?

```js
fastify.get(['/:param1', '/:param1/:param2'], handler)
```

**Comment by mcollina** [comment]
Tbh, we could duplicate the route in find-my-way transparently.

**Comment by KaKi87** [comment]
> Tbh, we could duplicate the route in find-my-way transparently.

I actually were going to say that : if this duplication behavior is acceaptable, then why not keeping it under the hood and let the user use `:foo?`

**Comment by mcollina** [comment]
Happy to review such a PR!

**Comment by KaKi87** [comment]
Sorry I know how to do JS with elegance but not with performance 😅
