### ISSUE TITLE
http caching headers

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#121]
we should provide some support for etag, last-modified and the others.

**Comment by cagataycali** [comment]
Fastify can have a cache solution as a plugin? [like these](https://github.com/kwhitley/apicache) but internal one.🤔

**Comment by mcollina** [comment]
IMHO we have two layers of this.

1) methods to detect and process those headers in `Request`
2) a plugin that uses those, and actually do caching

Would you like to start a plugin?

**Comment by jsumners** [comment]
Reference for people wishing to tackle this issue: https://tools.ietf.org/html/rfc2616#section-14.9

**Comment by allevo** [comment]
But why should this be in fastify?
Cannot this be a plugin that installs some kind of middleware?

**Comment by mcollina** [comment]
@allevo I mean we need to support what is written in https://hapijs.com/tutorials/caching?lang=en_US as "client side caching" _within_ fastify itself, and maybe server-side caching with plugin.

**Comment by jsumners** [comment]
Oooh, okay. That gives me ideas....

**Comment by allevo** [comment]
@mcollina `fastify` can simply parsing the header if we want (but again, why not in a middleware?) or provide a simple shorthand to set the cache header (but again, why not in a decorator?)

**Comment by evanshortiss** [comment]
ETag support out of the box is great since it can save clients significant bandwidth, e.g for mobile devices consuming an API. Similar for other cache headers @jsumners linked.

I think things like `apicache` or my own `express-expeditious` fall into a different category.

**Comment by evanshortiss** [comment]
Of course, performance-wise it might be best as a plugin - just sharing thoughts on general use case.

**Comment by mcollina** [comment]
Etag support out of the box destroys performance :/. After we have spent time generating a response, our cost has already been paid, and bandwidth is mostly cheap. 304s are better sent from a web server (nginx) or a CDN.

IMHO we should just provide some utilities to implement all of that if someone needs to. It’s a bunch of methods/accessors on Request and Reply.

**Comment by jsumners** [comment]
Here's my initial implementation. I intend to look at `catbox` style support before an actual release. https://github.com/fastify/fastify-caching

**Comment by mcollina** [comment]
good job! we need the accessor on Request as well!

**Comment by jsumners** [comment]
@mcollina file bugs over on that repo so they can be a TODO list.

**Comment by delvedor** [comment]
This can be closed, further discussion could be done in [fastify/fastify-caching](https://github.com/fastify/fastify-caching) :)

**Comment by jsumners** [comment]
Fixed by https://github.com/fastify/fastify-caching/releases/tag/v1.0.0
