### ISSUE TITLE
Enabling windows testing for sub-repos

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1213]
Travis recently began beta windows testing https://blog.travis-ci.com/2018-10-11-windows-early-release.

I encountered problems on 2 repos when testing on windows so far so I suggest we enable windows testing for all repos except the main repo which is using appveyor. Once travis is out of beta, we can switch the main repo as well if desired.

Although CI runs will take a bit more time I think its important that we do not regress

I can do the necessary work which is straightforward. Thoughts? @fastify/fastify

**Comment by StarpTech** [comment]
Why do we need this change when appveyor works fine? We only need to maintain a simple yaml file which is touched one time per year?

**Comment by cemremengu** [comment]
Sorry I couldnt make my point. I am actually meaning the sub-repos we have that don't have windows testing. Although it can be changed in the future, I am fine keeping appveyor on the main repo.

**Comment by mcollina** [comment]
AppVeyor is often a source of problems and failed builds. Moreover it has a
weird auth model, and it seems I am the only one that can restart builds.
I’m keen to just use Travis if it works.

Il giorno mar 16 ott 2018 alle 17:35 Cemre Mengu <notifications@github.com>
ha scritto:

**Comment by StarpTech** [comment]
If this is the case I agree. From my experience I never had real problems with appveyor. Let's just try it.

**Comment by delvedor** [comment]
I don't think we should enable Windows on all of our repos, but just a few of them until Windows support is out of beta.

**Comment by cemremengu** [comment]
Added mongodb and compression for now. End of spam :). Let me know if there are more suggestions.

**Comment by cemremengu** [comment]
Oh no I think I just opened a huge can of worms :smile:

**Comment by cemremengu** [comment]
I think this will be superseded by #1226. Should we close?

**Comment by mcollina** [comment]
Let's wait and assess before calling it a deal.
