### ISSUE TITLE
Awaiting for multiple register to finish. How to use Promise and Promise.all().then() with register().

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify#1216]
I need to establish several database connections with fastify-postgres from which I need to pull data before I can start the fastify instance.

With a single register I could use a callback to call the next step of the init process.

I read in another issue that .ready() on the register will return a promise but I wasn't able to make this work.

With async / await not working as hoped for I would like to use a Promise.all().then() construction for this scenario.

Is there any documentation how to turn fastify.register into a promise?

This is the current code...
```
  connections.forEach(connection => {
    fastify.register(require('fastify-postgres'), {
        connectionString: connection.string,
        name: connection.name
      });
    }
  });
```

**Comment by mcollina** [comment]
Just add a `.after(fn)` after you have registered both plugins.

**Comment by dbauszus-glx** [comment]
The function in .after() seems to be only ever called after I initialize fastify.listen(). Is this the expected behavior?

**Comment by dbauszus-glx** [comment]
I see... This works.

```
fastify.register(require('fastify-postgres'), {
  connectionString: myConnectionString,
  name: 'myConnection'
}).after(() => {
  console.log('myConnection is ready');
  getConfigData();

});

initServer();

async function initServer(){

  await fastify.ready();
  
  fastify.listen(process.env.PORT || 3000, '0.0.0.0', err => {
    if (err) {
      console.error(err);
      process.exit(1);
    }  
  });
}
```

But I still need to wrap multiple connections and only run the after functions after all connections have been registered.

**Comment by mcollina** [comment]
> But I still need to wrap multiple connections and only run the after functions after all connections have been registered.

if you register multiple plugins, this could be achieved by using `.after()`

**Comment by dbauszus-glx** [comment]
The problem is that I don't know how many connections are required. This is dependent on the environment settings. For this reason I need to put fastify.register into an iterator.

**Comment by dbauszus-glx** [comment]
Yes. I got there in the end. I didn't understand .after() and .ready() before.

I now have a forEach iterator generating promises which resolve on the after().

I can thus use Promise.all().

```
  let promises = [];

  Object.keys(process.env).forEach(key => {
    if (key.split('_')[0] === 'DBS') {
      promises.push(new Promise((resolve, reject) => {
        fastify.register(require('fastify-postgres'), {
          connectionString: process.env[key],
          name: key.split('_')[1]
        }).after(() => resolve(key));
      }));
    }
  });

  Promise.all(promises).then(values => console.log(values));
```

Thanks for your help. I will close this.

**Comment by cemremengu** [comment]
Maybe we can enrich docs with this info?
