### ISSUE TITLE
plugin register addContentTypeParser doesn't work as expected

### ISSUE THREAD

**Issue by kolbma** [fastify/fastify#1217]
I register multiple plugins which provide content parsers.
But only the content parser of the last registered plugin is recognized.

## 🐛 Bug Report

```
  const parser = (fastify: FastifyInstance, options, next) => {
    const opts = Object.assign({ bodyLimit: 500 * 1024, parseAs: 'string' }, options || {});
    fastify.addContentTypeParser('application/tlsrpt+json', opts,
      (req, body: string): Promise<any> => {
        try {
          const json = JSON.parse(body);
          return json;
        } catch (err) {
          err.statusCode = HttpStatus.BAD_REQUEST;
          throw err;
        }
      });
    console.log('Added Parser');
    console.log('Parser Status: %s', fastify.hasContentTypeParser('application/tlsrpt+json'));
    next();
  };
  const parser2 = (fastify: FastifyInstance, options, next) => {
    const opts = Object.assign({ bodyLimit: 500 * 1024, parseAs: 'string' }, options || {});
    fastify.addContentTypeParser('application/tlsrpt+gzip', opts,
      (req, body: string): Promise<any> => {
        try {
          const json = JSON.parse(body);
          return json;
        } catch (err) {
          err.statusCode = HttpStatus.BAD_REQUEST;
          throw err;
        }
      });
    console.log('Added Parser');
    console.log('Parser Status: %s', fastify.hasContentTypeParser('application/tlsrpt+gzip'));
    next();
  };

  const f = fastify();
  f.register(parser, { bodyLimit: 500 * 1024 });
  f.register(parser2, { bodyLimit: 500 * 1024 });
  f.listen(3001);
```

With 1st register we get parsers
["application/tlsrpt+json","application/json"]
With 2nd register we get
["application/tlsrpt+gzip","application/json"]

Why it always starts from the beginning?

## Your Environment

- *node version*: v8.12.0
- *fastify version*: >=1.12.1
- *os*: win32 x64

**Comment by delvedor** [comment]
> Why it always starts from the beginning?

I'm not sure I've understood the question.

If you want to use your newly added content type parsers outside the plugin, you are registering them you should use [fastify-plugin](https://github.com/fastify/fastify-plugin).
I suggest you also to take a look at our [plugins guide](https://www.fastify.io/docs/latest/Plugins-Guide/) :)

**Comment by kolbma** [comment]
delvedor: I don't like to use them "outside" the plugin. Thay just should stay registered. I'd like to support additional content-types with the "plugins". Something which shouldn't be so questionable and magic. ;-)

**Comment by kolbma** [comment]
Seems that a `parser[Symbol.for('skip-override')] = true;` does the magic. But why is this not the default?

**Comment by mcollina** [comment]
The default is to encapsulate things to foster reuse. By marking it explicit, the amount of things that are altering the parent is limited and explicit. 

Anyway, I think we are past the time to change the default.
