### ISSUE TITLE
Using regex when capturing the parameters

### ISSUE THREAD

**Issue by gajus** [fastify/fastify#122]
The following route definition works in Express.js, but does not work in Fastify, `/cinema-logos/:cinemaId(\\d+)-:cinemaName.svg`.

In Fastify, it produces `params: { 'cinemaId(\d+)-:cinemaName.svg': '1000146-vue.svg' },`, whereas I expect to get `cinemaId` and `cinemaName` as separate parameters.

`:cinemaId-:cinemaName` is not working either, because the matching expression appears to be greedy: `'cinemaId-:cinemaName.svg': '1000146-vue.svg'`.

**Comment by gajus** [comment]
https://github.com/delvedor/find-my-way/issues/15

**Comment by delvedor** [comment]
We will work in [find-my-way](https://github.com/delvedor/find-my-way) to support this, but inside Fastify you could just use the validations methods, that will handle for you also the error (as you can see [here](https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md)).

For example:
```js
fastify.get('cinema-logos/:cinemaId', {
  params: {
    type: 'object',
    properties: {
      cinemaId: {
        type: 'string',
        pattern: (\\d+)
      }
    }
  }, (req, reply) => {
    // your logic  
})
```

I recommend you to read the [documentation](https://github.com/fastify/fastify/blob/master/docs/Validation-And-Serialize.md) and [ajv pattern string](https://epoberezkin.github.io/ajv/keywords.html#pattern).

ps: bonus, if you follow this solution once the [swagger plugin](https://github.com/fastify/fastify-swagger) is ready you will also have the automatic documentation of the parameters ;)

**Comment by gajus** [comment]
> We will work in find-my-way to support this, but inside Fastify you could just use the validations methods, that will handle for you also the error (as you can see here).

That does not solve an issue in any way...

```js
fastify.get('cinema-logos/:cinemaId-:foo', {
  params: {
    type: 'object',
    properties: {
      cinemaId: {
        type: 'string',
        pattern: (\\d+)
      }
    }
  }, (req, reply) => {
    // your logic  
})

```

will be parsed as `:cinemaId-:foo` parameter.

**Comment by gajus** [comment]
Can we keep this issue open until it is resolved (including https://github.com/delvedor/find-my-way/issues/15)?

**Comment by mcollina** [comment]
done!

**Comment by gajus** [comment]
Thank you

**Comment by delvedor** [comment]
Closed in https://github.com/delvedor/find-my-way/issues/17.
