### ISSUE TITLE
Close: Not running error

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#123]
If you call the `close` api without an active server, you will get the `Error: Not running` error.
This is very inconvenient if you are using the `inject` api in your test.

Example:
```js
const { beforeEach, afterEach, test } = require('tap')
const build = require('./server')

var instance = null

beforeEach(done => {
  build(i => {
    instance = i
    done()
  })
})

afterEach(done => {
  instance.close(err => {
    if (err) throw err
    done() // this will never be called
  })
})

test(...)
```
Use the close api is very useful if you must close some db connection, but this error is tricky and annoying.
An user-side solution could be:
```js
afterEach(done => {
  instance.close(err => {
    if (err.message !== 'Not running') throw err
    done()
  })
})
```
Maybe we can directly handle that error in our [internals](https://github.com/fastify/fastify/blob/master/fastify.js#L239).
```js
fastify.server.close(err => {
  if (err.message === 'Not running') err = null
  cb(err)
})
```
Thoughts?

**Comment by mcollina** [comment]
If the server has not been startes, we shouldn't close it in the shutdown phase.

**Comment by allevo** [comment]
This could hide some kind of errors.

Consider:
```js
 process.on('uncaughtException', done => instance.close(done))
```
It may close the server once or more hiding an error handling problem.

**Comment by delvedor** [comment]
> If the server has not been startes, we shouldn't close it in the shutdown phase.

Maybe using [server.listening](https://nodejs.org/api/http.html#http_server_listening)?

> ` process.on('uncaughtException', done => instance.close(done))`

I don't like this solution, I think is too generic :S

**Comment by allevo** [comment]
@delvedor it was just an example.

In that case the error "Not running" will hide.

Maybe a new method can be implemented with a safety guard?

**Comment by mcollina** [comment]
`server.listening`  is ok.

BTW, I think we should move part of the close orchestration to avvio, as it would be balanced and shared between multiple things.

**Comment by delvedor** [comment]
@mcollina yes, we can do that, it will improve *avvio* as utility.
I'll fire a pr asap :)
