### ISSUE TITLE
Remove `simple-get` from tests

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1230]
Current we have `simple-get` and `fastify.inject` being used interchangably. It looks like we can refactor tests to use `fastify.inject` only.

I will prepare a PR if agreed.

**Comment by mcollina** [comment]
IMHO I like having some tests using simple-get, mainly because it validates and verifies that the full setup is working. If they break on a new Node.js version, we know there is something off.
How many are needed? Probably not that many.

**Comment by cemremengu** [comment]
I see fair enough, I was just thinking if could get rid of the dependency and make testing approach consistent. Currently used in 30 files.

**Comment by delvedor** [comment]
I think we should keep both.
`inject` does not perform a complete http request :)
