### ISSUE TITLE
Need some extra dev help on Fastify?

### ISSUE THREAD

**Issue by andrewlinfoot** [fastify/fastify#1235]
## 💬 Questions and Help

Hey Fastify team,

I am reaching out because I saw Fastify on a list of repos with good first-time contributor communities. 🙂

I run a startup where we teach software engineers in India how to be effective remote employees and then help them break into international tech careers via full-time remote jobs.

For the last 4 weeks of training, students complete an open-source apprenticeship where they work full-time contributing to select open source projects for free.

The time commitment from project maintainers in return is pretty minimal.

- A 30-minute on-boarding video call during the first week to get to know each other and clear up any questions
- A list of "good first-time contributor" issues to get started
- Timely pull-request review so that the engineer doesn't get blocked since they will be devoting around 6 hours per day Mon-Fri to the project
- Complete a short survey at the end that will serve as a performance review

I was wondering if the Fastify team would be interested in participating?

The full details of the program are here: https://www.pesto.tech/open-source-apprenticeship/

I would also be happy to answer any questions you have.

**Comment by andrewlinfoot** [comment]
**When will they start?**

Our current batch of students will start their projects on the week of November 5th - 9th, 2018. And will choose their projects on Monday/Tuesday next week.

Our next batch will start projects in late January. From there we will be running one batch per month so new projects will be selected monthly.

**What is the student background?**

Students typically have a CS degree and 1-4 years of professional software development experience before joining our program. Additionally, students will have completed 8 weeks of training with us before starting their open source apprenticeships.

**How many will participate?**

It depends on student interest in the project. You could have one student that picks your project or multiple or none. We confirm dates and number of students with you before finalizing project choices so how many students you want to work with is up to you. Also if you submit Fastify now but your availability changes by the time it is chosen by a student, you can decline to participate then and the student will work on their second choice project instead.

**Will they just work on a single project or on multiple ones?**

Each student chooses one project to work on for the entire four weeks.

**Comment by mcollina** [comment]
@fastify/fastify Do we have something meaningful for a junior dev to do for a month? I do not think we have so many “good first contributions” tasks.

 I very likely won’t have the time to do timely PRs either because I’ll be on an intense travel schedule.

**Comment by jsumners** [comment]
I think it's a flattering offer, but I agree, there isn't much here for a junior to work on.

**Comment by andrewlinfoot** [comment]
No worries. That makes sense. If you ever work on any projects that could use some help, don't hesitate to reach out :)
