### ISSUE TITLE
Move all _ prefixed properties to Symbols in next

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1237]
In the `next` branch, there are a bunch of properties in `Reply` (and maybe `Request`) that are still prefixed with `_` and are not using symbols. They should be migrated to symbols.

**Comment by qnoox** [comment]
Hello, 

Would like to help on this but could you explain a little more on this topic just so that i'm clear on what is the outcome that your looking for or if you could point to an example.

**Comment by jsumners** [comment]
The `pino` library implements private properties/methods via symbols. Take a look at its source code.

**Comment by HugoLiconV** [comment]
in which files are you using symbols? just for reference

**Comment by cemremengu** [comment]
@HugoLiconV checkout https://github.com/fastify/fastify/blob/next/fastify.js

**Comment by HugoLiconV** [comment]
I've never used symbols. Can you tell me why I use them in this case?

**Comment by jsumners** [comment]
Symbols do not get iterated as own enumerable properties. See https://gist.github.com/jsumners/0a586bf6c3dcb835d692251347a0e730

`Symbol('foo') !== Symbol('foo')` so they are a great way for indicating internal API methods/fields. 

`Symbol.for('foo') === Symbol.for('foo')` so they are useful for API methods/fields that are usable by external users if they are comfortable with advanced scenarios.

**Comment by HugoLiconV** [comment]
I'm working on this

**Comment by HugoLiconV** [comment]
I've just made a PR #1245
