### ISSUE TITLE
Use turbo-http

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1239]
Since #365 is closed, we can track the status from this issue separately

https://github.com/mafintosh/turbo-http/pull/18

cc @tinchoz49

**Comment by mcollina** [comment]
I think we can close this as development in turbo-http seems to have stopped.

**Comment by dalisoft** [comment]
You can checkout [my dev env](https://github.com/dalisoft/fastify-dev-env) which supports `turbo-http`.
_It's looks like i'm promoting my dev env, but it's not true_
