### ISSUE TITLE
[types] Fastify error fields

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify#1249]
Now in `fastify.d.ts` routes, middleware and so on use `Error` type. However, as far as I know, Fastify could have couple additional properties like `statusCode` or `validation`.

So it's better to introduce custom interface or class that extends `Error` and use it. Also it will be easier to extend that interface in plugins if they add some new fields to the Error type.

I could try make PR, but I don't know if there are any other properties. So that would be great if someone will help with listing all available error properties.

- *fastify version*: latest

**Comment by mcollina** [comment]
the problem is that the error could come from everywhere. Any application code can add its own property. I don't know how to handle that case with typescript.

**Comment by SkeLLLa** [comment]
If Error will be interface, then it can be done with [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).
Just like it's done here for example: https://github.com/fastify/fastify-mongodb/blob/master/index.d.ts#L47

So if you need to extend Error model with some properties, you can do like with `FastifyInstance`, declare fastify module, and describe interface with additional field `mongo`

**Comment by mcollina** [comment]
Send over a PR!

Il giorno ven 9 nov 2018 alle 06:51 Alexander Kureniov <
notifications@github.com> ha scritto:

**Comment by SkeLLLa** [comment]
@mcollina are there any other fields besides `statusCode` and `validation` used in Fastify?

**Comment by mcollina** [comment]
Let’s start adding those.
