### ISSUE TITLE
header Content deposition not working as for file download

### ISSUE THREAD

**Issue by ramachandranvenkat** [fastify/fastify#1258]
I am not able to return my response as file download using below code. 
it's gives me normal string response rather than downloaded file. 

let me know what needs to be done in order to get this to work. 

```js
     async function ( req, reply)  {
            const data = req.body;
            const format  = req.query.format;              
            reply.type('text/html');     
            reply.header('Content-Disposition', 'attachment; filename=test.html');      
            reply.send(data);
    }
```

## Your Environment

- *node version*: 10,12.0
- *fastify version*: >=v1.12.1
- *os*: Windows

**Comment by cemremengu** [comment]
Can you try setting the type `application/octet-stream` instead of text or maybe not setting it at all?

**Comment by mcollina** [comment]
Can you please include a full repro? Something that does not rely on `req.body` would be very hepful as well.

**Comment by ramachandranvenkat** [comment]
@mcollina 
my code is not it git and it's private project, I am trying to download html templates generated using moasico. everything working fine except content disposition, whereas i can able to get response as normal html string. 
@cemremengu  i tried application/octet-stream but not working.

**Comment by jsumners** [comment]
He didn’t ask for your private code. He asked for a reproduction of the issue. What plugins are loaded? What sort of input is involved? These are questions not answered by your snippet but would be answered if you provide a sample script that reproduces the problem.

**Comment by ramachandranvenkat** [comment]
This is my server side code 

```js

const fastify = require('fastify')({
    logger: true,
    maxParamLength:100000000000,
    bodyLimit: 1000000000000,
});

fastify.register(require('fastify-cors'))
fastify.register(require('fastify-sensible'))
fastify.register(require('fastify-compress'), { threshold: 0 })
fastify.register(fstatic, {     
    root:   path.join(__dirname, '/../')
});

const bodyParser = require('fastify-formbody');

fastify
.register(bodyParser, { bodyLimit: 100000000 })
.post('/export', (request, reply) => {       
   reply.header('Content-disposition', 'attachment; filename=' + request.body.filename);
   reply.type('text/html')
   reply.send(request.body.html)
})

```
client side code 

```js
var localData = `filename=${name()}&format=${format}&html=${html}`


      $.ajax({
        url:`/api/export`,
        method: 'POST',        
        data: localData,
        success: onPostSuccess,
        error: onPostError,
        complete: onPostComplete,
      })

    function onPostSuccess(data, textStatus, jqXHR) {
      console.log('post success', data);     
    }

    function onPostError(jqXHR, textStatus, errorThrown) {
      console.log('post error', jqXHR, textStatus, errorThrown);
     
    }

    function onPostComplete(jqXHR, textStatus, errorThrown) {
      console.log('post complete', jqXHR, textStatus, errorThrown);    
    }
```
let me know how can i get download  html as file.

**Comment by cemremengu** [comment]
This works for me (from localhost). On top of my head, it may be getting filtered via cors. Can you configure the cors plugin as:

```js
fastify.register(require('fastify-cors'), {exposedHeaders: 'Content-Disposition'})
```

**Comment by ramachandranvenkat** [comment]
it's working, thanks

**Comment by hemanth8759** [comment]
> This is my server side code
> 
> ```js
> const fastify = require('fastify')({
>     logger: true,
>     maxParamLength:100000000000,
>     bodyLimit: 1000000000000,
> });
> 
> fastify.register(require('fastify-cors'))
> fastify.register(require('fastify-sensible'))
> fastify.register(require('fastify-compress'), { threshold: 0 })
> fastify.register(fstatic, {     
>     root:   path.join(__dirname, '/../')
> });
> 
> const bodyParser = require('fastify-formbody');
> 
> fastify
> .register(bodyParser, { bodyLimit: 100000000 })
> .post('/export', (request, reply) => {       
>    reply.header('Content-disposition', 'attachment; filename=' + request.body.filename);
>    reply.type('text/html')
>    reply.send(request.body.html)
> })
> ```
> 
> client side code
> 
> ```js
> var localData = `filename=${name()}&format=${format}&html=${html}`
> 
> 
>       $.ajax({
>         url:`/api/export`,
>         method: 'POST',        
>         data: localData,
>         success: onPostSuccess,
>         error: onPostError,
>         complete: onPostComplete,
>       })
> 
>     function onPostSuccess(data, textStatus, jqXHR) {
>       console.log('post success', data);     
>     }
> 
>     function onPostError(jqXHR, textStatus, errorThrown) {
>       console.log('post error', jqXHR, textStatus, errorThrown);
>      
>     }
> 
>     function onPostComplete(jqXHR, textStatus, errorThrown) {
>       console.log('post complete', jqXHR, textStatus, errorThrown);    
>     }
> ```
> 
> let me know how can i download html as file.

can a txt file be download after creating temporarily?
