### ISSUE TITLE
Expose route pattern for monitoring

### ISSUE THREAD

**Issue by KidkArolis** [fastify/fastify#1275]
## 🚀 Feature Proposal

Expose the pattern of the route on the request object so that monitoring tools could automatically breakdown data by route.

## Motivation

I was attempting to use `fastify-metrics` which is linked in the Ecosytem page for monitoring my application. I noticed that it's not grouping requests by route pattern. And furthermore, I realised fastify doesn't expose the route pattern to plugins.

## Example

Right now the prom metrics produced by `fastify-metrics` are in red, but ideally they should be as shown in green:

```diff
-http_request_duration_seconds_bucket{le="0.005",method="GET",route="/jobs/Op4X46WTqqnCKWgV4q",status_code="404"} 0
+http_request_duration_seconds_bucket{le="0.005",method="GET",route="/jobs/:id",status_code="404"} 0
```

This is a best practise in prometheus, where you have a limited number of labels and are not supposed to use distinct values, like full URLs as labels.

The feature would expose the route config or pattern on the request object. For example in express it's:

```
req.route.path // e.g. /jobs/:id
```

This way monitoring tools like prometheus or `elastic/apm` mentioned in https://github.com/elastic/apm-agent-nodejs/pull/594 would be able to log the route pattern and this way correctly group requests.

**Comment by KidkArolis** [comment]
Ok, nevermind, fastify-metrics is doing it correctly! Phew, it's using the (undocumented?) feature where it grabs reply.context.config.url, which happens to be the pattern. I think I was just being thrown off by hitting a 404.

**Comment by KidkArolis** [comment]
Yeah, I was just hitting a 404, which probably shouldn't be labeling metrics with the full URL as well, as that can explode Prometheus. But that's something for the plugin and not for fastify to worry about.

Sorry for a false alarm!

**Comment by jsumners** [comment]
It would be great if you can submit a PR to improve documentation if you have found it lacking.
