### ISSUE TITLE
Questions about mounting Express App

### ISSUE THREAD

**Issue by frostpuppet** [fastify/fastify#1276]
#### You have already researched for similar issues?
yes i have similar problems are present but Im looking for more of an example since I cant get things working right. 

#### Are you sure this is an issue with the fastify or are you just looking for some help?
https://github.com/fastify/fastify/issues/306
Talks about a similar issues so does
https://github.com/fastify/fastify/issues/1175

What im trying to do is use 
https://github.com/bee-queue/arena#readme
inside a fasitfy app.  When i use 

fastify.use (arena) 
 
I get a working sub app but my other routes do no work.  Similary if I disable the arena sub app all my other routes work.  

Can anyone please advise or demonstrate mounting an express sub app.  I seem to always get in a position where the sub app works and the rest of the application hangs on requests.  If i disable the sub app everything works as expected but I have disabled the sub app. 

Thanks

**Comment by mcollina** [comment]
That cannot work. We provide connect-like middleware compatibility. However Express modifies the prototype of the node core Request and Response object heavily, and we cannot guarantee that compatibility.

We should possibly update our docs.
