### ISSUE TITLE
login with url header

### ISSUE THREAD

**Issue by bgbruno** [fastify/fastify#1290]
Hello - I play with fastify and today with auth - and I love that simple code
https://github.com/fastify/fastify-basic-auth

and I want use known format to auto login
http://username:password@example.com

but browser still show me dialog window to username and password

by this it should be achieved by adding authenticate header "WWW-Authenticate: FormBased"
https://stackoverflow.com/a/19102200/1347601

Q it's possible somehow set to skip that behaviour - add that header and read those credentials from url?

**Comment by mcollina** [comment]
I would recommend not to use basic auth for anything but quick tests.

I don’t know the answer to your question, if you figure it out, let us know and send a PR.

**Comment by jsumners** [comment]
I’m fairly sure that format is a browser thing. It should be filling in the `authorization` header accordingly and sending it to the server.

**Comment by delvedor** [comment]
@jsumners I think you are right, if you use the WHATWG URL constructor that value will automatically be extracted.

**Comment by jsumners** [comment]
Regarding URL formatting:

https://tools.ietf.org/html/rfc3986#section-3.2.1
> Use of the format "user:password" in the userinfo field is
   deprecated.  Applications should not render as clear text any data
   after the first colon (":") character found within a userinfo
   subcomponent unless the data after the colon is the empty string
   (indicating no password).  Applications may choose to ignore or
   reject such data when it is received as part of a reference and
   should reject the storage of such data in unencrypted form.  The
   passing of authentication information in clear text has proven to be
   a security risk in almost every case where it has been used.

Regarding HTTP spec:

https://tools.ietf.org/html/rfc2616#section-3.2.2
> The "http" scheme is used to locate network resources via the HTTP
   protocol. This section defines the scheme-specific syntax and
   semantics for http URLs.
>
>   http_URL = "http:" "//" host [ ":" port ] [ abs_path [ "?" query ]]

Thus, it is up to the client application making the request to:

1. Recognize the user information embedded in the URL
2. Base 64 encode said user information
3. Put that base 64 encoded information in an `authorization` header when issuing the request

Chrome does not support it -- https://bugs.chromium.org/p/chromium/issues/detail?id=123150
Neither does Internet Explorer (cannot find current link).
It is unlikely any other browser supports it either.
