### ISSUE TITLE
Error: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by lynxionxs** [fastify/fastify#1293]
When installing the cli via npm, ```sudo npm install fastify-cli --global``` and running ```fastify generate``` i get the following error ```/usr/bin/env: ‘node\r’: No such file or directory``` 
What is wrong?

OS: Ubuntu 18.04
NPM VERSION: v5.4.2
NODE VERSION: v8.7.0

**Comment by cemremengu** [comment]
This issue should be moved to `fastify-cli` 

@mcollina I think we should remove [this line](https://github.com/fastify/fastify-cli/blob/f34ed67536505a144f70074ad0a4c51e14093998/cli.js#L1) completely since it changes between different environments

**Comment by cemremengu** [comment]
Continued in https://github.com/fastify/fastify-cli/issues/138

**Comment by lynxionxs** [comment]
I cannot remove that line . I dont know where that package is installed to

**Comment by mcollina** [comment]
I think a \r slipped in somehow. Use dos2unix to convert and fix it (and test on a Linux system).

That line is necessary.

**Comment by lynxionxs** [comment]
Thats crazy. All the files have windows line endings

**Comment by cemremengu** [comment]
@lynxionxs yet it is :) patch coming in

**Comment by lynxionxs** [comment]
@cemremengu ok good

**Comment by lynxionxs** [comment]
I changed all the fastify-cli files line endings to Unix. Only the node_modules directories kept the Unix line endings. It is now working when i do ```fastify generate```
