### ISSUE TITLE
YEPS benchmark

### ISSUE THREAD

**Issue by evheniy** [fastify/fastify#1297]
Hi

I tested with my own framework and I got an interesting results:

$ autocannon -c 100 -d 5 -p 10 localhost:3000
Running 5s test @ http://localhost:3000
100 connections with 10 pipelining factor

```
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev   │ Max       │
│ Latency │ 0 ms │ 0 ms │ 20 ms │ 22 ms │ 1.99 ms │ 6.18 ms │ 136.02 ms │
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
│ Req/Sec   │ 44831   │ 44831   │ 49791   │ 50367   │ 48681.6 │ 2017.72 │ 44801   │
│ Bytes/Sec │ 5.24 MB │ 5.24 MB │ 5.82 MB │ 5.89 MB │ 5.69 MB │ 236 kB  │ 5.24 MB │
```

Req/Bytes counts sampled once per second.

243k requests in 5.06s, 28.5 MB read

and test:

```
'use strict'

const http = require('http');
const App = require('yeps');

const app = new App();

app.then(async ctx => {
  ctx.res.statusCode = 200;
  ctx.res.end('{"hello":"world"}');
});

http
    .createServer(app.resolve())
    .listen(parseInt(process.env.PORT || '3000', 10));
```

Could you please add it to your benchmark.
Thank you!

**Comment by mcollina** [comment]
Please send a PR to https://github.com/fastify/benchmarks. We list only a subset of the frameworks in the readme.

**Comment by evheniy** [comment]
I created a PR 
https://github.com/fastify/benchmarks/pull/82
