### ISSUE TITLE
Apache benchmark apr_socket_connect

### ISSUE THREAD

**Issue by evheniy** [fastify/fastify#1298]
Hi

When I try to run apache benchmark I see an error:

```
evheniy@users-MacBook-Pro ~/www/benchmarks/benchmarks
$ node fastify.js
```

And test:

```
evheniy@users-MacBook-Pro ~
$ ab -c 100 -n 1000 http://localhost:3000/
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)

Test aborted after 10 failures

apr_socket_connect(): Invalid argument (22)
```

**Comment by mcollina** [comment]
Here is the code we use for plain http: https://github.com/fastify/benchmarks/blob/master/benchmarks/bare.js.
As you can see, you are not calling JSON.stringify, nor writing the full content-type.

The benchmarks are independently maintained, and they are not run by anybody on the fastify team. They have also been validated by the maintainers of other frameworks.

Please open an issue there.
