### ISSUE TITLE
Multiple requests issue

### ISSUE THREAD

**Issue by lynxionxs** [fastify/fastify#1304]
When i run any route on fastify there are 3 requests made to the same route, each with different ```"reqId": x``` 
Even a simple Hello World it happens. 
I tried reinstalling fastify but the issue persists.
I tried different browsers like Chrome, Firefox, Opera, and curl , the issue remains.

When i created a route to add something to the database that query was called 3 times
When i use the Fastifi-cli example it also produces the same multiple 3 output requests

This is the output and script on a simple route
Expected output should be one ```"reqId":x``` for ```"url":"/"```

```bash
max@maxOne:~/Projects/BOX/FASTIFY$ node server
{"level":30,"time":1544033115548,"msg":"Server listening at http://127.0.0.1:3000","pid":12526,"hostname":"maxOne","v":1}
server listening on 3000
{"level":30,"time":1544033162228,"msg":"incoming request","pid":12526,"hostname":"maxOne","reqId":1,"req":{"id":1,"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":38732},"v":1}
{"level":30,"time":1544033162240,"msg":"request completed","pid":12526,"hostname":"maxOne","reqId":1,"res":{"statusCode":200},"responseTime":11.48178100027144,"v":1}
{"level":30,"time":1544033162301,"msg":"incoming request","pid":12526,"hostname":"maxOne","reqId":2,"req":{"id":2,"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":38732},"v":1}
{"level":30,"time":1544033162301,"msg":"request completed","pid":12526,"hostname":"maxOne","reqId":2,"res":{"statusCode":200},"responseTime":0.8633099999278784,"v":1}
{"level":30,"time":1544033162383,"msg":"incoming request","pid":12526,"hostname":"maxOne","reqId":3,"req":{"id":3,"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":38732},"v":1}
{"level":30,"time":1544033162383,"msg":"request completed","pid":12526,"hostname":"maxOne","reqId":3,"res":{"statusCode":200},"responseTime":0.397409001365304,"v":1}
```

server.js

```javascript
const fastify = require('fastify')({
    logger: true
});

fastify.get('/', (req, reply) => {
    reply
        .code(200)
        .header('Content-Type', 'text/html; charset=utf-8')
        .send("<h1>Hello World</h1>")
});

fastify.listen(3000, err => {
    if (err) throw err
    console.log(`server listening on ${fastify.server.address().port}`);
});
```

**Comment by delvedor** [comment]
Hello! This is the correct behavior, the request id does not identify the route, but the single request :)
If you need custom id generation, you can use the [`genReqId`](https://www.fastify.io/docs/latest/Server/#genreqid) option :)

**Comment by lynxionxs** [comment]
@delvedor  Even with the ```genReqId``` the same request is still run 3 times. When i do ```/user/add``` that query is run 3 times, 3 different records are created in the database

```javascript
var i = 0
const fastify = require('fastify')({
    genReqId: function (req) { return i++ },
    logger: true
})

fastify.register(require('fastify-postgres'), {
    connectionString: 'postgres://postgres:12345@127.0.0.1:5432/demodb'
});

fastify.get('/', (req, reply) => {
    reply
        .code(200)
        .header('Content-Type', 'text/html; charset=utf-8')
        .send("<h1>Index route...</h1>")
});

fastify.get('/user/add', (req, reply) => {
    fastify.pg.query(
        "INSERT INTO users(first_name, last_name, pass, login) VALUES('Bob', 'Brown', '12345', 'rexbob')", (err, result) => {
            reply.send(err || result);
        }
    );
})

fastify.listen(3000, err => {
    if (err) throw err
    console.log(`server listening on ${fastify.server.address().port}`);
});
```

**Comment by mcollina** [comment]
Are you sure your browser is not actually doing 3 requests for some reasons?

Have you tried with postman or curl?

**Comment by lynxionxs** [comment]
@mcollina on Curl and postman the request runs only once.  But when i run in any browser Firefox, Chrome, Opera address bar it makes 3 requests. Not sure whats going on. On Express it works as expected there

**Comment by cemremengu** [comment]
@lynxionxs I tried your code and couldn't reproduce the issue using chrome, it works fine

**Comment by lynxionxs** [comment]
@cemremengu it seems the duplicate requests is a chrome only issue. After reinstalling the other browsers works correctly now. So its not a Fastify issue. Thanks guys
