### ISSUE TITLE
Add some helper (getter) functions to request, for Fastify v2

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#1305]
## 🚀 Feature Proposal

Add some useful get function (already present in reply) even in request.

## Motivation

In response/reply there are some utility functions like `getType` (to get the content-type), `getHeader` and `hasHeader` to get/check for a specific header ... so do you think it makes sense to have them even in request (for v2.x) ?

Sometimes I use and could be useful to have, even to behave in a similar way for request and response, like the work already done on hooks.

I'm available to raise a PR for it, if accepted even for the initial version of Fastify v2.
Question: getter functions are encouraged here, or normal functions (I think this approach would be more suitable here) ?

## Example

Small simplifactions (mainly for hiding some data retrieval) could be done in my code, like:
- `if (request.headers['content-type'] === 'myMime') ...` could be rewritten as `if (request.getType() === 'myMime') ...` or `if (request.getHeader('content-type') === 'myMime') ...` 
- `if (request.headers['myHeader'] === 'my-header-value') ...` could be rewritten as `if (request.getHeader('myHeader') === 'my-header-value') ...` 
- and similar for other methods proposed here.

Thanks,
Sandro

**Comment by mcollina** [comment]
I think this is already part of [fastify-sensible](https://github.com/fastify/fastify-sensible#requestis). Do you think we should promote that module more?

**Comment by delvedor** [comment]
I agree with @mcollina, `fastify-sensible` is already providing many of this features, and we will continue to do so. Fastify core should provide a lightweight API, while plugins should enrich it.

Probably we can advertise `fastify-sensible` better.

**Comment by smartiniOnGitHub** [comment]
@mcollina @delvedor ah ok, good to know :-) ... I agree that some more info on `fastify-sensible` could be useful. Thanks again. Now I close the issue.
