### ISSUE TITLE
Fastify.use() to define the routes.

### ISSUE THREAD

**Issue by PranjalAgni** [fastify/fastify#1307]
## Using fastify.use() to define routes.
Hii there 😃, I was playing  with Fastify, and  I wanted to do something like
`fastify.use('/mail', require('mail-service.js'));`

Such that all the type of requests starting from endpoint ( '/mail' ) go to the 'mail-service' file as we can do in express. How can we achieve this in fastify.

I tried  to do that using fastify.use() but it's not working.

**Comment by delvedor** [comment]
Hello!
If your need is to prefix all the routes registered inside `require('mail-service.js')` with `/mail`, you can do that with the [route prefix](https://www.fastify.io/docs/latest/Routes/#route-prefixing) :)

```js
fastify.register(
  require('mail-service.js'),
  { prefix: '/mail' }
)
```
```js
// mail-service.js
module.exports = function (fastify, opts, next) {
  fastify.get('/user/:id', (req, reply) => {})
  fastify.get('/attachments', (req, reply) => {})
  fastify.get('/contacts', (req, reply) => {})
  next()
}
```

Now all the routes registered inside `mail-service.js` will be reachable with `/mail/...` :)
