### ISSUE TITLE
Errors not logged to file

### ISSUE THREAD

**Issue by lynxionxs** [fastify/fastify#1308]
When i add the ```file:``` option to the logger it does'nt log to a file
v1.13.1
```javascript
const fastify = require('fastify')({
    logger: {
        level: 'error',
        file: './logs/error.log'
    }
});

fastify.get('/', function (request, reply) {
    fastify.log.error('Error 123: Something went wrong...');
    reply.send({ hello: 'world' });
});

fastify.decorate('notFound', (request, reply) => {
    reply.code(404).type('text/html').send('Not Found')
});
fastify.setNotFoundHandler(fastify.notFound);

// Start listening.
fastify.listen(process.env.PORT || 3000, (err) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
});
```

**Comment by cemremengu** [comment]
It should be `request.log` see https://www.fastify.io/docs/v1.13.x/Logging/

**Comment by jsumners** [comment]
Where did you learn that `file` is a valid configuration option? It is not as far as I am aware.

**Comment by lynxionxs** [comment]
@cemremengu even with ```request.log``` it does'nt output to the file , just the console

```javascript
const fastify = require('fastify')({
    logger: {
        level: 'error',
        file: './logs/error.log'
    }
});

fastify.get('/', function (request, reply) {
    request.log.error('Error 123: Something went wrong...');
    reply.send({ hello: 'world' });
});

fastify.decorate('notFound', (request, reply) => {
    reply.code(404).type('text/html').send('Not Found')
});
fastify.setNotFoundHandler(fastify.notFound);

// Start listening.
fastify.listen(process.env.PORT || 3000, (err) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
});
```

**Comment by lynxionxs** [comment]
@jsumners https://github.com/fastify/fastify/blob/master/docs/Logging.md

**Comment by jsumners** [comment]
Those docs are invalid. Pino has never accepted a `file` option. You can pass a stream that writes to a file, though.

**Comment by lynxionxs** [comment]
@jsumners i still cant get it to log errors to file with @cemremengu 's link 
```javascript
const fastify = require('fastify')({
    logger: {
        level: 'error',
        stream: (stream) => {
            var f = fs.createWriteStream('./logs/error.log');
            stream.pipe(f);
        }
    }
});

fastify.get('/', function (request, reply) {
    request.log.error('Error 123: Something went wrong...');
    reply.send({ hello: 'world' });
});

fastify.decorate('notFound', (request, reply) => {
    reply.code(404).type('text/html').send('Not Found')
});
fastify.setNotFoundHandler(fastify.notFound);

// Start listening.
fastify.listen(process.env.PORT || 3000, (err) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
});
```

**Comment by jsumners** [comment]
You passed a function, not a stream for the `stream` parameter. That is not valid.

Please review the Pino 4.x.x documentation if you are using Fastify 1.x -- https://github.com/pinojs/pino/blob/v4.x.x/docs/API.md

Or the Pino 5.x.x documentation if using Fastify 2.x -- https://github.com/pinojs/pino/blob/a871790f882e4853b2b2d20c158740318544cd74/docs/api.md

**Comment by cemremengu** [comment]
@jsumners Strange, a few days ago exactly this section was updated via #1292

**Comment by lynxionxs** [comment]
I can't get this to work . It's so simple but you made it complicated. An option like ```{ logFile: "/path/to/logfile.log" }``` would be better. 
Can i create a file logger into Fastify namespace like, ```fastify.myLogger.log("message...")``` to use it anywhere in the application ?

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/blob/b8de32b1dd1ad2524f93ac04e7f41dca453a922a/package.json#L121

Fastify v1 uses Pino v4. Pino v4 only accepts custom streams.

Fastify v2 uses Pino v4. Pino v4 supports a `destination` parameter than can be a string to a file path -- https://github.com/pinojs/pino/blob/a871790f882e4853b2b2d20c158740318544cd74/docs/api.md#destination

Now that I'm at a computer instead of my phone I can see that Fastify adds in this unexpected `file` option:

https://github.com/fastify/fastify/blob/97f02eba295990a22ea673e6031074c3a08b3fe9/fastify.js#L72-L75

https://github.com/fastify/fastify/blob/97f02eba295990a22ea673e6031074c3a08b3fe9/lib/logger.js#L21-L27

At the very least, this is confusing because the docs explicitly say to consult the Pino documentation for options, but Fastify is mangling the options with new ones that Pino does not support.

**Comment by lynxionxs** [comment]
@jsumners even with Fastify v2 and Pino v5 i cannot figure out how to connect the Pino logger to fastify stream

```javascript
const log = require('pino')('./logs/error.log');

const fastify = require('fastify')({
    logger: {
        level: 'error',
        stream: log
    }
});

fastify.get('/', function (request, reply) {
    request.log.error('Error 123: Something went wrong...');
    reply.send({ hello: 'world' });
});

fastify.decorate('notFound', (request, reply) => {
    reply.code(404).type('text/html').send('Not Found')
});
fastify.setNotFoundHandler(fastify.notFound);

// Start listening.
fastify.listen(process.env.PORT || 3000, (err) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
});
```

**Comment by jsumners** [comment]
In that example you created a completely new Pino instance and passed it as the stream. That is incorrect. You would:

```js
const logger = pino(dest)
const fastify = require('fastify')({ logger })
```

**Comment by lynxionxs** [comment]
@jsumners i did it like this. It works good now , thanks :)
```javascript
const pino = require('pino');
const logger = pino({level: 'error'}, './logs/error.log');
const fastify = require('fastify')({ logger });
```

**Comment by ljieyao** [comment]
It is not working for me, anyone can help?

**Comment by Eomm** [comment]
Could you open a new issue with all the info to provide you help?

**Comment by tj-commits** [comment]
The same thing's happening to me. None of these things worked

**Comment by Eomm** [comment]
This is a **five years old issue** and concerns fastify **v1**.

So, again: please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).


locking
