### ISSUE TITLE
Problems with dynamic URLS binding (url="/*") to the single handler function

### ISSUE THREAD

**Issue by yadroRus** [fastify/fastify#1310]
### Hi there! Thanks for bringing fastify in the World!

I'm trying to achieve a dynamic URLs binding by the values i get from DataBase (DB).
### Example: 
We have a site with news, each news has a _**server URL**_ and _**human friendly URL**_ (stored in DB).
	_**SITE.com/news1**_  - server URL (has route in application);
 	_**SITE.com/some_unique_news1_title_here**_ - human friendly URL (need to bind route to it dynamically);

| Server Url | Human Url          |
| ------------- |:-------------:| 
| news1      | some_unique_news1_title_here | 
| ...     | ...|   
| newsN       | some_unique_newsN_title_here      |   

### First

I tried to implement it thru **setNotFoundHandler**:
```javascript
fastify.setNotFoundHandler(function (request, reply) {
    DB.getHumanUrl(request.raw.url).then((data) => { // check if we have such url in DB
      if (!data) { // data: {serverUrl: '...', humanUrl:'...'}
        return;//404
      }
      let route = fastify.routes.get('/' + data.serverUrl); // get already defined route of serverURL, fastify.routes is plagin
      if (route && route.get.method === 'GET') { // run beforeHandler and handler 
        route.get.beforeHandler(request, reply, () => {});
        route.get.handler(request, reply);
      } else {
        //404
      }
    }).catch((error) => {
      console.error(error);
    });
  });
```

The problem i faced with is that **request does not have a session and cookies objects**, seems like **run Middlewares** cycle is skipped here.

### Second
Another way (to have session and cookies in request) is to use **wildcard**:   
```javascript 
fastify.get('/*', (request, reply) => {}))
``` 
But using such URL **'/*'**  breaks application.

**NOTE**: the main idea here is that URL should goes from the site root, but not from some existed folder, like in docs:  
```javascript 
fastify.get('/example/*', (request, reply) => {}))
```

Sorry for stupid question, but does fastify support such kind of URL bindings or any workarounds?

**Comment by mcollina** [comment]
> The problem i faced with is that request does not have a session and cookies objects, seems like run Middlewares cycle is skipped here.

All lifecycle should happen for 404s.
Can you please upload a full example that shows what is not run?

> But using such URL '/*' breaks application.

This should be the preferred way. Can you please upload a full example that shows how?

**Comment by yadroRus** [comment]
As i found during creation an example, the root of the problem was **fastify-static** plagin and it's option - **prefix** (by default it's '/'). this plagin has a code:
```javascript
  fastify.get(prefix + '*', schema, function (req, reply) {
    pumpSendToReply(req, reply, '/' + req.params['*'])
  })
```
which breaks creating a custom GET route with '/*' URL. Workaround is adding prefix different than '/' to above plagin, but in that case we have too add for each static resource in markup this prefics too -> increase html size.
```javascript
const path = require('path');
const fastify = require('fastify')();

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'static')
  //, prefix: '/static/'
});


fastify.get('/*', (request, reply) => {
  reply.send({ hello: 'world' });
});

fastify.listen(3000, (err) => {
  if (err) {
    console.error(err);
    process.exit(1);
  }
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
});
```
It's strange but **setNotFoundHandler** break the same attribute - **prefix** from **fastify-static**. when i added this attribute to code - i could see session.

So issue is not actual any more, the only question i have, from performance reason what is the best solution here - go with
```javascript
fastify.get('/*', (request, reply) => {});
```
or with **setNotFoundHandler**?
