### ISSUE TITLE
Fastify-Cron

### ISSUE THREAD

**Issue by xyz-mtl** [fastify/fastify#1312]
Some Nodejs framework have a Scheduler (cron) component. 
It's very interesting to process "something" in a background process.

Can you add this part as a new plugin 🚀 , please ?

Thank you

**Comment by mcollina** [comment]
Thanks! I’ve tagged this as good first issue, if you or anybody else would like to give a writing this new plugin a shot, let us know!

**Comment by lynxionxs** [comment]
Something like Node-Cron https://www.npmjs.com/package/node-cron. Or wire node-cron into a fastify plugin

**Comment by StarpTech** [comment]
In which way is a scheduler related to a http framework? I'm not happy to manage such requests it will lead to much noise and it could encourage people to focus on fastify only instead to write and practice modular software.

**Comment by mcollina** [comment]
I agree with you. However, if somebody write that plugin and maintains it outside of this org, I don’t see any issue. I’m happy to review it in fact.

**Comment by xyz-mtl** [comment]
@StarpTech & @mcollina 👍  Good point but my main idea is to process background task without impact on any http request. 
[https://docs.totaljs.com/latest/en.html#api~Framework~F.worker](url) An example with Totaljs.

**Comment by mcollina** [comment]
> Good point but my main idea is to process background task without impact on any http request.

How does this relate to Fastify? Fastify is a web framework.

Can you make an example of the API you'd like to have?

**Comment by StarpTech** [comment]
More interesting, what kind of tasks are you trying to execute? A cron which managed IO stuff like requesting other services or CPU intensive tasks? In the second case node is a bad choice because it's single threaded.

https://link.medium.com/mmlvWzbzyS

**Comment by cemremengu** [comment]
I am assuming they are looking for functionality like https://github.com/eggjs/egg-schedule/blob/master/README.md

I personally used this in the past and I think it is not a good idea

**Comment by xyz-mtl** [comment]
@mcollina : Quick example: 
During the signup of new user, you can start a background process to send an email to confirm the account.

@StarpTech : kind of tasks:
- email confirmation
- security process
- database process : rebuild index ...
- archive files expired
- ...

**Comment by jsumners** [comment]
Seems like a separate, queue backed, service to me.

**Comment by mcollina** [comment]
Can you make an example with code?

**Comment by StarpTech** [comment]
@xyz-mtl @jsumners has right. You need delivery guarantee. I can recommend https://github.com/nats-io/node-nats-streaming I have really good experience with that and it is much easier to maintain in comparison with a rabbitmq cluster. You can use it directly in your handlers. You don't need to create a separate api.
