### ISSUE TITLE
To Do List example

### ISSUE THREAD

**Issue by xyz-mtl** [fastify/fastify#1314]
Hi,
💬 Do we have a To Do List example using Fastify with Rest API ?
Thank you

**Comment by cemremengu** [comment]
There is a `twitter` example available https://github.com/fastify/fastify-example-twitter

**Comment by mcollina** [comment]
Would you like to work on it @xyz-mtl?

**Comment by xyz-mtl** [comment]
> There is a `twitter` example available https://github.com/fastify/fastify-example-twitter

Good example using services but for the beginner may be an example less complex is welcome. 👍

**Comment by xyz-mtl** [comment]
May be we can create a new resource page as https://github.com/feathersjs/awesome-feathersjs/blob/master/README.md#examples

More example using the framework can be useful...

**Comment by mcollina** [comment]
Good word @cemremengu! I think that would be a nice addition to the org.

What do you think @fastify/fastify ?

**Comment by allevo** [comment]
@mcollina  Absolutely 👍

**Comment by xyz-mtl** [comment]
May Be include this example in the list 👍 ( https://github.com/siegfriedgrimbeek/fastify-api)
