### ISSUE TITLE
Response payload in default pino logger

### ISSUE THREAD

**Issue by MaxVinogradov** [fastify/fastify#1316]
##### For now I have next config:

```
const fastify = require('fastify')({
  logger: {
    prettyPrint: true,
    serializers: {
      req(req) {
        return {
          method: req.method,
          url: req.url,
          path: req.path,
          parameters: req.parameters,
          body: req.body,
          headers: req.headers,
        };
      },
    },
  },
});
```

Thanks!

**Comment by mcollina** [comment]
Does that not work?

**Comment by MaxVinogradov** [comment]
@mcollina 
 > Does that not work?
For now req works correctly, but I need to show response info - payload, headers, etc.

**Comment by mcollina** [comment]
You'll need to add a `res` serializer:

```js
const fastify = require('fastify')({
  logger: {
    prettyPrint: true,
    serializers: {
      res(res) {
        // the default
        return {
          statusCode: res.statusCode
        }
      },
      req(req) {
        return {
          method: req.method,
          url: req.url,
          path: req.path,
          parameters: req.parameters,
          body: req.body,
          headers: req.headers,
        };
      },
    },
  },
});
```

**Comment by mcollina** [comment]
Would you like to send a PR to https://github.com/fastify/fastify/blob/master/docs/Logging.md to add an example?

**Comment by MaxVinogradov** [comment]
@mcollina okay, tanks. I will add it to docs after NY

**Comment by open-source-explorer** [comment]
> You'll need to add a `res` serializer:
> 
> ```js
> const fastify = require('fastify')({
>   logger: {
>     prettyPrint: true,
>     serializers: {
>       res(res) {
>         // the default
>         return {
>           statusCode: res.statusCode
>         }
>       },
>       req(req) {
>         return {
>           method: req.method,
>           url: req.url,
>           path: req.path,
>           parameters: req.parameters,
>           body: req.body,
>           headers: req.headers,
>         };
>       },
>     },
>   },
> });
> ```

I'm new here :clap: Adding the above mentioned content to the docs works fine :thinking:

**Comment by stefanocapitanio** [comment]
> You'll need to add a `res` serializer:
> 
> ```js
> const fastify = require('fastify')({
>   logger: {
>     prettyPrint: true,
>     serializers: {
>       res(res) {
>         // the default
>         return {
>           statusCode: res.statusCode
>         }
>       },
>       req(req) {
>         return {
>           method: req.method,
>           url: req.url,
>           path: req.path,
>           parameters: req.parameters,
>           body: req.body,
>           headers: req.headers,
>         };
>       },
>     },
>   },
> });
> ```

Hi guys, I tried this, but i'm not logging body payload (neither for request nor response).
Now I'm using preHandler and preSerialization hooks.

**Comment by Eomm** [comment]
@stefanocapitanio this is an old issue, please open a new one describing your use case adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)
