### ISSUE TITLE
Run Fastify in AWS Lambda

### ISSUE THREAD

**Issue by MaxVinogradov** [fastify/fastify#1317]
## How can I run Fastify in AWS Lambda?

For now I'm using `aws-serverless-express`, with next code:

```
const awsServerlessExpress = require('aws-serverless-express')
const Fastify = require('fastify')

const fastify_app = Fastify({
  serverFactory: function (handler) {
    return awsServerlessExpress.createServer(handler)
  }
})


fastify_app.get('/1', async (req, reply) => {
  console.log('!!!###');
  try {

    return reply.send({ hello: 'world' });
  } catch (e) {
    console.log(e)
  }
});

exports.handler = async (event, context) => {
  await fastify_app.ready();
  fastify_app.ready(() => {
    console.log('Ready');
    const server = fastify_app.server;
    return awsServerlessExpress.proxy(server, event, context);
  });
}

```

Then I run serverless-local, send request to endpoint, and see ` !!!###`, but I haven't any response. 
+  I see warning in the console:
```
Serverless: Warning: handler 'user-news' returned a promise and also uses a callback!
This is problematic and might cause issues in your lambda.
```

Could you please check, what's wrong?

**Comment by mcollina** [comment]
There is no mention of `user-news` in your example.

@lmammino should be working on some docs on how to run fastify on lambda. What's the status of that?

**Comment by MaxVinogradov** [comment]
Sorry, small code update, but it still not working!
```

**Comment by mcollina** [comment]
Have you tried

```js

async function start(event, context) {
   await fastify_app.ready();
   awsServerlessExpress.proxy(server, event, context);
}
exports.handler = (event, context) => {
   start().catch(console.log)
}
```

**Comment by MaxVinogradov** [comment]
const awsServerlessExpress = require('aws-serverless-express')
const Fastify = require('fastify')

const fastify_app = Fastify({
  serverFactory: function (handler) {
    return awsServerlessExpress.createServer(handler)
  }
})


fastify_app.get('/1',  (req, reply) => {
  console.log('!!!###');
  return reply.send({ hello: 'world' });
});

exports.handler = async (event, context) => {
  await fastify_app.ready();
  fastify_app.ready(() => {
    console.log('Ready');
  });
  const server = fastify_app.server;
  return awsServerlessExpress.proxy(server, event, context);
}
```

**Comment by MaxVinogradov** [comment]
Wait a moment, please

**Comment by MaxVinogradov** [comment]
```

**Comment by MaxVinogradov** [comment]
Just tried next:
```
const awsServerlessExpress = require('aws-serverless-express')
const Fastify = require('fastify')

const fastify_app = Fastify({
  serverFactory: function (handler) {
    return awsServerlessExpress.createServer(handler)
  }
})


fastify_app.get('/1', (req, reply) => {
  console.log('!!!###');
  return reply.send({ hello: 'world' });
});

async function start(event, context) {
  await fastify_app.ready();
  awsServerlessExpress.proxy(fastify_app.server, event, context);
}
exports.handler = async (event, context) => start(event, context).catch(console.log);

```

The same result - no response

**Comment by MaxVinogradov** [comment]
> user-news

@mcollina it's only lambda endpoint name in serverless  framework

**Comment by MaxVinogradov** [comment]
Strange, but works correctly
```
async function start(event, context) {
  await fastifyServer.ready();
  await initiateMongoDbConnection();
  return awsServerlessExpress.proxy(fastifyServer.server, event, context);
}

exports.handler = (event, context) => {
  start(event, context).catch(console.log);
};
```
+

```
const fastify = require('fastify')({
  serverFactory(handler) {
    return awsServerlessExpress.createServer(handler);
  },
});
```
@mcollina Thank you, but maybe it will be great to add this into the docs.

**Comment by cemremengu** [comment]
@MaxVinogradov would you like to send a PR for adding this to docs?

**Comment by MaxVinogradov** [comment]
@cemremengu okay, I'll try to add it later

**Comment by cemremengu** [comment]
@jsumners Maybe we should a have FAQ for these kind of info that we don't want to add to docs but still want to keep around for referencing later if needed?

**Comment by jsumners** [comment]
Yes, that would be appropriate.

**Comment by khpatel4991** [comment]
A working example would be good

**Comment by adrai** [comment]
fyi: https://gist.github.com/adrai/ca6237c013f5a746cdfd043bb6e02185
