### ISSUE TITLE
Doc: add Errors.md to the document content

### ISSUE THREAD

**Issue by fralonra** [fastify/fastify#1324]
Since we have a good article about error codes, why don't we just add [this doc](https://github.com/fastify/fastify/blob/master/docs/Errors.md) to the content of document and let all users know about it?

**Comment by mcollina** [comment]
I don't understand what you would like to do?

Can you add a link to Errors.md in the Readme https://github.com/fastify/fastify#documentation?

**Comment by poppinlp** [comment]
I guess what he wanna do is to add an error codes doc in [this table](https://www.fastify.io/docs/latest/). :)

**Comment by mcollina** [comment]
I think that's picked up from the README.

**Comment by mcollina** [comment]
cc @lmammino

**Comment by fralonra** [comment]
What I mean is to add a link to README

**Comment by cemremengu** [comment]
@fralonra would you like to send a PR for it?

**Comment by fralonra** [comment]
@cemremengu Sure https://github.com/fastify/fastify/pull/1326
