### ISSUE TITLE
Document the use of fluent-schema

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1329]
We are receiving some questions about JSON schema in gitter and github. I think it’s time we start documenting:

https://www.npmjs.com/package/fluent-schema

in this repo. I think it has a more mnemonic API.

**Comment by Eomm** [comment]
Hi,
I would like to work on it.
Do you have already something in mind?

I was thinking that I should edit the [Validation-and-Serialization.md](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md) adding the missing information. For this could you link me some questions that you received? (I have searched `JSON Schema` in the issues but there are too many confusing results 😅)

Thanks

**Comment by mcollina** [comment]
required property, null property, multiple types for a property, etc..
