### ISSUE TITLE
Do not allow the `reply.sent` property to be overwritten

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1330]
Currently we allow the reply.sent property to be overwritten by a user.
it should be protected by a getter, and accessed directly via a symbol inside `Reply`.

This will likely conflicting with: https://github.com/fastify/fastify/pull/1328, so let's wait for that to land.

I propose we land this in v2.0.0-rc.3.

**Comment by mcollina** [comment]
https://github.com/fastify/fastify-react/pull/46#issuecomment-447586644

**Comment by millette** [comment]
For reference, `reply.sent = true` is used in the [nextjs fastify example](https://github.com/zeit/next.js/blob/canary/examples/custom-server-fastify/server.js).

**Comment by mcollina** [comment]
I changed my mind, and in fact we can enable setting `reply.sent = true` in a more controlled manner.

See https://github.com/fastify/fastify/pull/1336 for more details.
