### ISSUE TITLE
Missing two error codes

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1334]
* [ ] https://github.com/fastify/fastify/blob/1ad553df56f6833048a7e105fb500ac6db60ce2f/lib/reply.js#L65
* [ ] https://github.com/fastify/fastify/blob/1ad553df56f6833048a7e105fb500ac6db60ce2f/lib/wrapThenable.js#L19

I propose we fix those before 2.0.0 is out.

**Comment by 0xsuid** [comment]
@mcollina can you elaborate those issues?

**Comment by 0xsuid** [comment]
Thanks, If you can help me to **reproduce** both errors it will be great.

**Comment by mcollina** [comment]
They are already covered in our tests:

* https://github.com/fastify/fastify/blob/347957c77e384d44b90adc9ad9347a0974ada922/test/async-await.js#L360
* https://github.com/fastify/fastify/blob/c4eb1d96c0febcd2e52e665c68bd85fab55c0787/test/hooks.test.js#L2018

**Comment by 0xsuid** [comment]
This seems to a simple - add code in error.js like below right?
```
createError('FST_ERR_DEC_ALREADY_PRESENT', `The decorator '%s' has already been added!`)
````

**Comment by mcollina** [comment]
Yes, that's it!

**Comment by 0xsuid** [comment]
@mcollina I've changed reply.js(locally). Can you help me to create new test in hooks.test.js according to it?

**Comment by mcollina** [comment]
I think you should just add two more assertions in the test I linked, verifying the error code.

**Comment by 0xsuid** [comment]
@mcollina Can you give me one example - error code located in lib/errors.js and related test :(

**Comment by 0xsuid** [comment]
@mcollina 

fastify/test/hooks.test.js
```
throw new Error('You cannot use `send` inside the `onError` hook')
```
IMO this line supposed to have variable **send** and **onError** OR this line contains ``` ` ``` sign for other purposes??

because I've tried to log that line in test and got same in message : 'You cannot use `send` inside the `onError` hook'

**Comment by mcollina** [comment]
Changing those would be ok.

**Comment by 0xsuid** [comment]
So I am going to change : 
'You cannot use ``` `send` ``` inside the ``` `onError` ``` hook'
To
'You cannot use ``` send ``` inside the ``` onError ``` hook' (without ``` ` ```)

@mcollina

**Comment by 0xsuid** [comment]
Created PR #1348 to fix this issue
