### ISSUE TITLE
Increase code coverage to 99% or 100%

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1335]
I think we have slipped from our 99% target (since @allevo did https://github.com/fastify/fastify/pull/295 and @Ethan-Arrowood did https://github.com/fastify/fastify/pull/340).

We have a bit of prior history on on this: https://github.com/fastify/fastify/issues/289.

**Comment by delvedor** [comment]
If someone wants to work on this, the npm command `npm run coverage` should be helpful. It will run the test and then open a browser window with the code coverage results, which is a perfect starting point! :)

**Comment by Ethan-Arrowood** [comment]
I should have some time today to look into this. I’m excited to dive into the new untested parts of Fastify v2

**Comment by mannyluvstacos** [comment]
Hi @Ethan-Arrowood!

I see that within `/lib` the following files are below 100% coverage:

- logger.js
- reply.js
- contentTypeParser.js
- validation.js
- schemas.js 

Should we divide and conquer this?
What files may I work on?

**Comment by mannyluvstacos** [comment]
:+1: Understood!

I will make a PR to your fork and branch `Ethan-Arrowood:Fix/improve-coverage`

If I run into any issues or have questions, I'll be sure to send them your way.
:metal:

**Comment by flickz** [comment]
Can I still join the effort over the weekend?

**Comment by mcollina** [comment]
Go for it!

Il giorno ven 21 dic 2018 alle 13:46 Oluwaseun Omoyajowo <
notifications@github.com> ha scritto:

**Comment by Ethan-Arrowood** [comment]
@mcollina @delvedor I'm looking into testing the else clause of the http2 conditional: 
https://github.com/fastify/fastify/blob/10cd7a46bd0ed5b6a4fbc54a7320c5bb76966c9e/fastify.js#L988-L994

The only way I can think of doing so is mocking console.error and verifying that it receives that string literal. Should I implement the test like that?

Alternatively:
- should I not test this at all (currently you t.pass() when node ver < 8.8.0)
- should I modify `fastify.js` to let this error bubble up and then catch it in the test runner

**Comment by mcollina** [comment]
I think it's better to have this error bubble up, we should not be starting up if http2 is required and we are on an older Node.js version where this is not available.

**Comment by mcollina** [comment]
You can use `proxyquire` to mock the condition where http2 is not available.

**Comment by Ethan-Arrowood** [comment]
Should I submit the bubble up error part as a separate pr or is it okay to include it within this coverage one?

**Comment by flickz** [comment]
@Ethan-Arrowood How can I trigger an error here https://github.com/fastify/fastify/blob/9f9c88fed17c99675074ef095bd324515bd6c9b9/lib/schemas.js#L46-L56 that wouldn't match `/FST_ERR_SCH_*/` condition and instead returns `swapSchema`? Like to test the case.

**Comment by flickz** [comment]
Yeah, make sense, I looked through also. I don't think there's any error outside of `FST_ERR_SCH_*` that could occur.

**Comment by flickz** [comment]
@Ethan-Arrowood Thinking about creating a `wrapThenable.test.js` for [wrapThenable.js](https://github.com/fastify/fastify/blob/9f9c88fed17c99675074ef095bd324515bd6c9b9/lib/wrapThenable.js) What do you think?

**Comment by Ethan-Arrowood** [comment]
Yes good idea! I think this time you should open a PR from your fork directly to Fastify too.

**Comment by flickz** [comment]
Okay great!

**Comment by Ethan-Arrowood** [comment]
We can close this issue now with the pr merge

**Comment by cemremengu** [comment]
@Ethan-Arrowood @flickz Thank you guys great work!
