### ISSUE TITLE
Automated daily test for v1

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1344]
Currently, greenkeeper will test only the dependencies declared in the master branch. This means that we will not know if something is failing in our v1 release line.

I'm not sure Greenkeeper supports that (https://github.com/greenkeeperio/greenkeeper/issues/848), in the meantime, we should implement an automated daily build *(both in Travis and Azure pipelines)* to ensure that v1 dependencies are not broken.

At the moment, I don't have time to work on this, if someone wants to send a pr, I'm happy to review it :)

Tasks:

* [x] Add cron job to Travis
* [ ] Add cron job to Azure

**Comment by mcollina** [comment]
I tried but i was not able to set it up on azure.

**Comment by cemremengu** [comment]
Is it possible to run citgm as a cron job as well? I had the idea to host it on heroku as a separate tool for quickly verifying if something is broken but didnt have time

**Comment by mcollina** [comment]
It's possible to run it in Travis, yes.

**Comment by delvedor** [comment]
@vagisha-nidhi is this possible with Azure pipelines?

**Comment by vagisha-nidhi** [comment]
Hi @delvedor 
You can schedule your build in Azure Pipelines as well.
You can to edit build pipeline and you will find this option in the Triggers tab.
Here is a screenshot for the same.
![image](https://user-images.githubusercontent.com/13175100/50751017-cbb6c980-126d-11e9-8142-92eec681980a.png)

**Comment by mcollina** [comment]
Done.

Do you know if this shows up only in the visual designer? Where is the docs for this? I couldn't find it.

**Comment by vagisha-nidhi** [comment]
@mcollina You can visit [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml) for more details on scheduling builds. As quoted on the link `Scheduled builds are not yet supported in YAML syntax. After your create your YAML build pipeline, you can use the designer to specify a scheduled trigger.`

**Comment by mcollina** [comment]
Thanks! I would recommend to add some notes when editing the yaml that some configurations are not available there, and check in the designer.
