### ISSUE TITLE
Core plugins list with breaking changes for Fastify v2

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify#1345]
## 💬 Questions and Help

It would be very helpful if some table like in example below will be created for Fastify and it's core plugins. It will help devs of 3rd party plugins to be prepared for upcoming release of Fastify.

So it will contain core plugins (and may be some 3rd party) with links to repo, version that supports Fastify v1 and v2 and info about availability of "next" version that's already compatible with v2.

Plugin | Fastify v1 | Fastify v2 | Available already
------------ | ------------- | ------------ | ------
[fastify-static](https://github.com/fastify/fastify-static) | `<2.0.0` | `>=2.0.0` | [ x ]

Also this could help to track progress to v2 milestone.

**Comment by delvedor** [comment]
Every plugin that already supports Fastify v2 states it in its README.
Regarding the list of which plugin still need to be updated maybe we can use [github projects](https://help.github.com/articles/about-project-boards/)?

**Comment by cemremengu** [comment]
As far as I know only `bankai` and `oauth2` plugins are remaining

**Comment by SkeLLLa** [comment]
The main idea is to have a list in one place where all modules that need to be updated will be present. So I as an author of couple 3rd party plugins can look through it and through my package deps and understand will I need some updates for Fastify v2 support.

For example fastify-oas plugin uses fastify-static https://github.com/SkeLLLa/fastify-oas/blob/master/package.json#L54.
And fastify-static will have new major version bump which will support Fastify v2 and potentially will be incompatible with Fastify v1. So in such list I'll be able to check if I need some updates or not.

And if that would be in github projects, then I think it should be created for "fastify" org, not just fastify repo, so it could gather issues from all repos under `fastify/*`

**Comment by mcollina** [comment]
Done in https://github.com/orgs/fastify/projects/1.

**Comment by mcollina** [comment]
(fastify-swagger has been updated already)

**Comment by SkeLLLa** [comment]
@mcollina looks like that project is private or something. Via link I receive 404 error.

![screenshot_2018-12-23 build software better together](https://user-images.githubusercontent.com/2273103/50386759-74edb380-06f5-11e9-891a-a6ab0c8256b0.png)

PS: I've also updated couple of my plugins including openapi plugin, however I not yet pushed it to npm. I don't want to push them manually so I have to do some scripts that will handle proper detection of "@next" publishes in my CI/CD pipelines.

**Comment by mcollina** [comment]
That project is now public

**Comment by SkeLLLa** [comment]
BTW, probably it will be also good idea after all core plugins will be ready for v2, to reformat or add similar page with table like in the 1st post where developers of community plugins could also add information about compatibility and/or readiness of the module for Fastify v2.

**Comment by mcollina** [comment]
In the meantime.. would you like to get a stab at https://github.com/fastify/website/issues/39? IMHO we should improve the way this info is presented significantly.

**Comment by SkeLLLa** [comment]
@mcollina as far as I understood website takes data from ecosystem.md where there's only name, link and description. May be it will look better if we add some badges based on plugin name in npm like version, license, vulnerabilities count and some mark if it's a core plugin (as suggested in issue you've mentioned).

**Comment by mcollina** [comment]
I think so. A better alternative is to move the ecosystem page to the website and remove it from this repo and render it from a YAML file.

cc @lmammino

**Comment by mcollina** [comment]
I’m closing this.
