### ISSUE TITLE
Fastify Can't Post, no Reply

### ISSUE THREAD

**Issue by galuh1300d** [fastify/fastify#1347]
Hello, is there anyone here that face no reply from fastify post method?
i tried everything, but same result

[here's my github](https://github.com/galuh1300d/fastify)

here's my index.js
```js
const fastify = require('fastify')({
  logger: true
})
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const keys = require('./config/keys')
const cors = require('cors')
require('./models/Saran')

mongoose.connect(keys.mongoURI, () => {
  console.log('MongoDB Connected')
})

fastify.use(cors())
fastify.use(bodyParser.urlencoded({ extended: false }))
fastify.use(bodyParser.json())

fastify.use(session({
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true,
//   cookie: { secure: true }
}))


// require('./routes/adminHalamanRoutes')(fastify)
require('./routes/halamanRoutes')(fastify)
require('./routes/userRoutes')(fastify)
require('./routes/saranRoutes')(fastify)

fastify.get('/', async (request, reply) => {
  return { hello: 'world' }
})

const PORT = process.env.PORT || 5000

const start = async () => {
  try {
    await fastify.listen(PORT)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

here's my routes
```js
const mongoose = require('mongoose')
const Saran = mongoose.model('saran')

module.exports = (fastify) => {

  fastify.post('/api/saran', async (req, res) => {
    const newSaran = new Saran({
      namaLengkap: req.body.namaLengkap,
      namaPanggilan: req.body.namaPanggilan,
      tanggalLahir: req.body.tanggalLahir,
      alamat: req.body.alamat,
      jenisKelamin: req.body.jenisKelamin,
      gerai: req.body.gerai,
      komentar: req.body.komentar
    })
  
    try {
      const saran = await newSaran.save()
      res.json(saran)
    } catch(err) {
      res.status(422)
    }
    
  })
}
```

**Comment by cemremengu** [comment]
```
try {
  const saran = await newSaran.save()
  res.json(saran)
} catch(err) {
  res.status(422)
}
```

You never send/return the response. There is also no `.json` function for response.

You can read more at https://github.com/fastify/fastify/blob/master/docs/Reply.md

**Comment by galuh1300d** [comment]
Thank you for your response, i tried to change it to the fastify suggest me to do
but, it still doesn't give me a reply, it stuck in "incoming request",
also i try to get rid of all of it and give it console.log(), and it stuck too

`const mongoose = require('mongoose')
const Saran = mongoose.model('saran')

module.exports = (fastify) => {

  fastify.post('/api/saran', (request, reply) => {
    const newSaran = new Saran({
      namaLengkap: request.body.namaLengkap,
      namaPanggilan: request.body.namaPanggilan,
      tanggalLahir: request.body.tanggalLahir,
      alamat: request.body.alamat,
      jenisKelamin: request.body.jenisKelamin,
      gerai: request.body.gerai,
      komentar: request.body.komentar
    })
  
    newSaran.save()
    reply
      .code(200)
      .send({ success: newSaran})
  })
}`
