### ISSUE TITLE
Typescript cannot invoke an expression whose type lacks a call signature.

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1349]
## 🐛 Bug Report

Setting up a typescript project using TypeScript 2.0 and Fastify 2.0 if you have the following `tsconfig` properties toggled a TypeScript error is thrown.

`tsconfig.json`
```json
{
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
}
```
`index.ts`
```ts
import * as fastify from 'fastify'
import { IncomingMessage, Server, ServerResponse } from 'http'

const app: fastify.FastifyInstance<Server, IncomingMessage, ServerResponse> = fastify({})

```
`index.ts error`
```
Cannot invoke an expression whose type lacks a call signature. Type '{ default: { 
<HttpServer extends Server | Http2Server = Server, HttpRequest extends 
IncomingMessage | Http2ServerRequest = IncomingMessage, HttpResponse extends 
ServerResponse | Http2ServerResponse = ServerResponse>(opts?: ServerOptions | 
undefined): FastifyInstance<...>; (opts?: ServerOptionsAsHttp | undefined): Fa...' 
has no compatible call signatures.
```

Disabling those tsconfig options removes this error.

## Expected

I'm still new to TypeScript so I don't fully understand what is going on here. I just thought I'd open the issue in case this is something that needs fixing. If this expected behavior, can we document this in the Fastify TypeScript docs?

**Comment by delvedor** [comment]
cc @evanshortiss

**Comment by yooouuri** [comment]
Typescript 3 over here, same error

`"typescript": "^3.2.2"`

**Comment by mcollina** [comment]
I have no idea how to fix this. Would somebody like to send a PR?

**Comment by fox1t** [comment]
Hi to all. First of all if you set `esModuleInterop` to true, it also enables `allowSyntheticDefaultImports`, so there is no need to specify both.
I just reproduced your issue with success. You are using `esModuleInterop` that "converts" commonjs modules to es6 ones. You have to write:
``` typescript
import fastify from 'fastify'
import { IncomingMessage, Server, ServerResponse } from 'http'


const app: fastify.FastifyInstance<Server, IncomingMessage, ServerResponse> = fastify({})
```
in order to get rid of that error. Also, if you remove both `esModuleInterop` and `allowSyntheticDefaultImports` and use `import * as fastify from 'fastify'` it works like a charm.

Anyway i'll check fastify's typings. :)

**Comment by evanshortiss** [comment]
Yeah it's slightly confusing and seems to be based around ECMA compatibility? Could this occur with Babel too?

**Comment by mcollina** [comment]
Any updates on this?

**Comment by tranzium** [comment]
Using `import fastify from 'fastify'` will correct this issue.

The original post has the same code as the official documentation.
Reproduce the issue: `import * as fastify from 'fastify'`

**Comment by Ethan-Arrowood** [comment]
I can confidently say this issue is resolved with the current types in `next` branch. Documentation is currently in the works to accurately show how to import fastify into a typescript project too.
