### ISSUE TITLE
Custom routes for 404 and 500

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#135]
As titled, we should be able to make these customizable, ideally supporting the plugin encapsulation.

**Comment by delvedor** [comment]
Currently you can use the [extendServerError](https://github.com/fastify/fastify/blob/master/docs/Decorators.md#extend-server-error) api, which is encapsulated, but is only for json responses.

Were you thinking about something more general purpose? (for example, html page)

**Comment by mcollina** [comment]
Yes exactly.
