### ISSUE TITLE
Know when client disconnects

### ISSUE THREAD

**Issue by Zaseth** [fastify/fastify#1352]
Hello!

Does Fastify have something to detect if a client has disconnected? It's very important for my project. I know that Express (With HTTP) has it and it works as so:

Express:
```javascript
req.on("close", function() {
  // request closed unexpectedly
});

req.on("end", function() {
  // request ended normally
}):
```

HTTP:
```javascript
http.createServer(function(request, response) {    
    request.connection.addListener('close', function () {
        // callback is fired when connection closed (e.g. closing the browser)
    });
}
```

I checked the Fastify documentation but I couldn't find anything related to the type of event system that is used in the code above here. If Fastify doesn't have this, it'd be great to see this sort of event based system being implemented in Fastify!

**Comment by cemremengu** [comment]
Have you tried [hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) for this? I think you can use `onError` and `onResponse`

**Comment by Zaseth** [comment]
I've tried to add onError but I get the following exception:

```
 throw new Error(`${hook} hook not supported!`)
    ^

Error: onError hook not supported!
```

**Comment by mcollina** [comment]
Can you please clarify your intent?

**Comment by Zaseth** [comment]
> Can you please clarify your intent?

I have to know when a client disconnects (exits the page) so I can perform a certain function. I just don't know if this is possible in Fastify and if so, how?

**Comment by mcollina** [comment]
> I have to know when a client disconnects (exits the page) so I can perform a certain function. I just don't know if this is possible in Fastify and if so, how?

I'm sorry, but you can't know when a client exits the page on a server. The content is served from the web application, rendered on the browser. When `'close'` is emitted on the express request object, it signifies that the current HTTP request has completed and all the data that the user wanted to send has been received. This is completely unrelated to the user exits the page.

**Comment by mcollina** [comment]
`'onError'` is available using Fastify v2.0.0-rc.3, you can install it with `npm i fastify@next`.

**Comment by Zaseth** [comment]
> > I have to know when a client disconnects (exits the page) so I can perform a certain function. I just don't know if this is possible in Fastify and if so, how?
> 
> I'm sorry, but you can't know when a client exits the page on a server. The content is served from the web application, rendered on the browser. When `'close'` is emitted on the express request object, it signifies that the current HTTP request has completed and all the data that the user wanted to send has been received. This is completely unrelated to the user exits the page.

Well HTTP seems to do the trick!

```javascript
"use strict"

require("http")
  .createServer((req, res) => {
    req.connection.addListener("close", () => {
      console.log("Client disconnected")
    })

    if (req.url === "/") {
      res.writeHead(200, { "Content-Type": "text/html" })
      res.write("Hello")
      res.end()
    }
  })
  .listen(80)
```

When you go to `localhost/` and close the page, it'll print `Client disconnected` on the console.

**Comment by jsumners** [comment]
That's because the connection is totally contained on your system and your browser is terminating the [persistent connection](https://en.wikipedia.org/wiki/HTTP_persistent_connection) when you close the window. This is in turn closing the socket open on your local system that connects to the local server on your system. Things don't work out so conveniently in the real world. There are many more layers to consider. 

If you _really_ want to know when the user closes your page you will need to do as @mcollina suggests and trap the browser's [onclose event](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclose) to send an event to your server (which will need to recognize the event _through your own code_).

**Comment by tommuhm** [comment]
> Does Fastify have something to detect if a client has disconnected? It's very important for my project. I know that Express (With HTTP) has it and it works as so:
> 
> Express:
> 
> ```js
> req.on("close", function() {
>   // request closed unexpectedly
> });
> 
> req.on("end", function() {
>   // request ended normally
> }):
> ```

just had the same problem and found that you can do pretty much the same as in express by accessing the underlying req object:
```js
fastify.get('/', {}, (request, reply) => {
   request.req.on('close', () => {
      // on close logic
   }

   // handle request
}
```

Note: the `onError` hook is not called when the client connection is lost!

**Comment by TzachiSh** [comment]
the event on close triggered me when the socket close 

> > Does Fastify have something to detect if a client has disconnected? It's very important for my project. I know that Express (With HTTP) has it and it works as so:
> > Express:
> > ```js
> > req.on("close", function() {
> >   // request closed unexpectedly
> > });
> > 
> > req.on("end", function() {
> >   // request ended normally
> > }):
> > ```
> 
> just had the same problem and found that you can do pretty much the same as in express by accessing the underlying req object:
> 
> ```js
> fastify.get('/', {}, (request, reply) => {
>    request.req.on('close', () => {
>       // on close logic
>    }
> 
>    // handle request
> }
> ```
> 
> Note: the `onError` hook is not called when the client connection is lost!
This events not worked for me 
On close event and end event trigger when request ended normally.

The best practice for me: 
`request.raw.on("error", function(error) { 
   if( code = 'ECONNRESET'){
    // on close logic
   }
 
}`

**Comment by dtinth** [comment]
I am using this to listen to the close event of the **response** object. It gets called when request is finished or client disconnects.

```ts
  reply.raw.on('close', () => {
    console.log('closed')
  })
```
