### ISSUE TITLE
Add license checker somewhere

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#1356]
## 🚀 Feature Proposal

Why not add a license checker?

## Example

[Like there](https://github.com/confluentinc/kafka-connect-jdbc#license)

**Comment by mcollina** [comment]
How about we add https://www.npmjs.com/package/license-checker to our ci run? This is something worthwhile checking on every CI run (so we can things before releases).

I don’t know if this is worthy of a badge, we have already too many.

**Comment by delvedor** [comment]
I like the idea to add it to our CI.
Regarding the badges, I agree that we have too many already, probably a note in the README is enough.

**Comment by allevo** [comment]
Yeah! It's ok for me.
