### ISSUE TITLE
Reply.sent is not assignable

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1365]
While reviewing code not covered by unit tests I discovered the following lines are completely skipped:
https://github.com/fastify/fastify/blob/adfa0c32b818af0f6f477dce5680bc871a5e2669/lib/reply.js#L73-L84

The `set` method is never being executed even though throughout this file and others `reply[kReplySent]` is being assigned, for example:
https://github.com/fastify/fastify/blob/adfa0c32b818af0f6f477dce5680bc871a5e2669/lib/reply.js#L224

I looked up the documentation on `Object.defineProperty()` and it says that if you do not explicitly set the `configurable` and `writable` properties to `true`, the defined property will not be able to changed. Copy the following code snippet into your browser console:
```js
const obj = {}
Object.defineProperty(obj, 'foo', {
  value: 'bar'
})

console.log('obj.foo Before assignment: ' + obj.foo)
obj.foo = 'changed'
console.log('obj.foo After assignment: ' + obj.foo)

Object.defineProperty(obj, 'fuzz', {
  value: 'buzz',
  writable: true,
  configurable: true
})

console.log('obj.fuzz Before assignment: ' + obj.fuzz)
obj.fuzz = 'changed'
console.log('obj.fuzz After assignment: ' + obj.fuzz)
```
Here is an image of the result too:
<img width="623" alt="screen shot 2019-01-04 at 12 56 57 am" src="https://user-images.githubusercontent.com/16144158/50675378-be72b400-0fbb-11e9-89f1-15d300524a3b.png">

This change was introduced in #1336 and detailed in #1330 
I'm going to try and debug this behavior in Fastify; I'm surprised everything is not broken! Alternatively, maybe I'm missing something and somehow the property is still being set.

**Comment by Ethan-Arrowood** [comment]
Reading into the code some more it seems like this was the intended behavior and that you are using the symbol intentionally to allow the user to safely set this property. I guess I'm closing this and will go back to figuring out why the coverage reporter is not picking up on this code being executed.

**Comment by Ethan-Arrowood** [comment]
Okay this is **actually** a bug.

Changing line 21 in skip-reply-send.js to `reply.sent = false` neither fails the test nor throws an error like specified in the setter method.

**Comment by mcollina** [comment]
Good spot! Would you like to send a PR to fix it?

**Comment by Ethan-Arrowood** [comment]
Of course!

**Comment by Ethan-Arrowood** [comment]
#1342 fixed in this PR

**Comment by delvedor** [comment]
Can we close this?

**Comment by Ethan-Arrowood** [comment]
Yes!
