### ISSUE TITLE
Add preSerialization hooks as a route-level hooks

### ISSUE THREAD

**Issue by realYondercode** [fastify/fastify#1369]
## 🚀 Feature Proposal

Add preSerialization hooks as a route-level hook, called when reply.send() is called (just before response serialization is started)

## Motivation

Useful for altering response just before the response serialization (and validation) happens. The response schema is awesome as a response filter, but a response transformer (or anything, since this is an user-defined function) that runs just before the response schema validation would be great.

## Example

- Using a hashids preSerialization to convert integer resource ids on responses into hashids for some resource routes
- Outputs different level of visibility of the same resource depending on the authenticated client's privilege level who requested it. (Strips some object properties for ordinary users, strips none for admins, etc)
- Adding extra metadata on responses

**Comment by mcollina** [comment]
Good idea! Would you like to send a PR?

**Comment by ShogunPanda** [comment]
@mcollina @realYondercode I've written the PR. I also had the same requirement. Enjoy!

PR: #1408
