### ISSUE TITLE
Fastify Typescript RouteSchema missing headers?: JSONSchema

### ISSUE THREAD

**Issue by reposandermets** [fastify/fastify#1378]
Hello

Thank you for the great Fastify project. We're moving from Express to Fastify, because of async/await support and schema driven approach.

While using fastify v2 with typescript the following code:

```js
  const endpointsSchemas: fastify.RouteSchema = {
    querystring: '#schema-id-1#',
    headers: '#schema-id-2#',
    response: {
      200: '#schema-id-3#',
    },
  };
```

produces ts error:

```sh
error TS2322: Type '{ querystring: string; headers: string; response: { 200: string; }; }' is not assignable to type 'RouteSchema'.
  Object literal may only specify known properties, and 'headers' does not exist in type 'RouteSchema'.
         headers: '#schema-id-2#',
```

fix seems simple:
instead of https://github.com/fastify/fastify/blob/master/fastify.d.ts#L185
```js
  interface RouteSchema {
    body?: JSONSchema
    querystring?: JSONSchema
    params?: JSONSchema
    response?: {
      [code: number]: JSONSchema,
      [code: string]: JSONSchema
    }
  }
```

it should be

```js
  interface RouteSchema {
    body?: JSONSchema
    querystring?: JSONSchema
    params?: JSONSchema
    headers?: JSONSchema
    response?: {
      [code: number]: JSONSchema,
      [code: string]: JSONSchema
    }
  }
```

If that is correct I'd be happy to open PR with the fix.

Meanwhile we're using self declared type.

**Comment by reposandermets** [comment]
> Yes, `headers` is missing! Would you like to send a PR?

Hi, yes going to open PR.

**Comment by mandaputtra** [comment]
@reposandermets would you like to write test on the [PR](https://github.com/fastify/fastify/pull/1380) @reposandermets I'm like 2 weeks afk.

**Comment by reposandermets** [comment]
> @reposandermets would you like to write test on the [PR](https://github.com/fastify/fastify/pull/1380) I'm like 2 weeks afk.

@mandaputtra going to give it a try :)
