### ISSUE TITLE
package-lock.json missing

### ISSUE THREAD

**Issue by PacoDu** [fastify/fastify#1383]
## 💬 Questions and Help

I'm wondering why you do not use `package-lock.json` ? Which is against npm recommendation.

Also if you don't want to commit this file, why is it not filtered in the `.gitignore`. This would avoid PRs that add this file (I saw some comments about this in the code reviews).

**Comment by mcollina** [comment]
https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514 sum up my point of view.
I don't know what other members of this community thinks, so we might want to re-evaluate our decision in this regard.

We also support both yarn and npm, and it means that the respective lockfiles would likely conflict. Overall it's probably a good idea not to commit one. 

Note that https://github.com/fastify/fastify/blob/master/.gitignore#L62 excludes them already. Somebody would have to forcefully add them.

**Comment by PacoDu** [comment]
Thanks ! I see your point know based on sindresorhus' comment.

Didn't noticed this one >.< https://github.com/fastify/fastify/blob/master/.gitignore#L62, I originally wrote this in [fastify-gql](https://github.com/mcollina/fastify-gql) and decided to move this issue here.

**Comment by mcollina** [comment]
Feel free to send a PR to ignore it in any of my modules.
