### ISSUE TITLE
Ajv validation in fastify for integer works strange

### ISSUE THREAD

**Issue by rtvv** [fastify/fastify#1387]
Only in fastify i get null after integer validation on Send. Incoming requests with integer check works fine.

This works fine (manual validation):
```
var schema = {
  type: 'object',
  properties: {
    registered: { type: ['integer', 'boolean'] }
  }
}
var validate = ajv.compile(schema)
console.log(validate({ registered: 1 })) //true
```

But this return null in registered object:
```
fastify.route({
  method: 'GET',
  url: '/someUrl',
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          error: { type: 'string' },
          registered: {
            type: ['integer', 'boolean']
          }
        }
      }
    }
  },
  handler: async (req, res) => {
    return res.send({ registered: 1 }) //registered: null 
}
```

If i change 
 `return res.send({ registered: 1 })`
to
 `return res.send({ registered: true })`
It's works and i get true

If i change
 `type: ['integer', 'boolean']`
to
` type: ['number', 'boolean']`
It's works and i get 1

If i change
 `type: ['integer', 'boolean']`
to
` type: 'integer'`
It's works and i get 1

I'm confused. Why is it integer in fastify not working in array with send?

My config:
```
'use strict'
const Ajv = require('ajv')
const ajv = new Ajv({
  useDefaults: true,
  removeAdditional: true,
  coerceTypes: true
})
fastify.setSchemaCompiler(schema => {
  return ajv.compile(schema)
})
```

**Comment by xzanlo** [comment]
Fastify uses Ajv to only validate input data. Response serialization is performed by [fast-json-stringify](https://github.com/fastify/fast-json-stringify). Check this out: https://github.com/fastify/fast-json-stringify/issues/133.

**Comment by rtvv** [comment]
@xzanlo oh, thanks!
