### ISSUE TITLE
Create website with documentation

### ISSUE THREAD

**Issue by lmammino** [fastify/fastify#139]
This should be fairly simple by using GitHub Pages (example [here](https://lmammino.github.io/fastify/Routes) from my fork).

The needed steps I see to make this happen are the following:

- [x] Create an `index.md` in the *docs* folder with everything we want to display in the homepage and links to the rest of the documentation
- [x] Create links between sections (previous / next style)
- [ ] Configure the repository to support github pages pointing to the *docs* folder
- [ ] Select a default theme or customise the Jekyll theme (optional)
- [ ] Get the `fastify.js.org` domain and configure it to display the GitHub pages configured previously (optional)

Once this is done the website will be kept updated by just changing the markdown files in the docs folder.

**Comment by mcollina** [comment]
I would prefer something a bit more custom than the standard jekyll template, but hey it's a stard. We can generate the template from the `readme.md` as well. Anyway, if you want to shot for a custom `index.md`  page, I'll get the jekyll thing enabled via gh-pages.

I think we can do a bit better, maybe something built on top of https://www.npmjs.com/package/marky-markdown and http://www.metalsmith.io/?

Anyway, if you want to contribute any of the above, feel free to!

**Comment by lmammino** [comment]
As much as I love static website generators like metalsmith and hexo, the only reason why I would go with gh-pages is because when it's configured and enabled it becomes a zero-maintenance process (a.k.a. no need for a separate doc build pipeline or separate PRs)

Anyway, if you are concerned about the look n' feel of the website, there should be [a way to use custom Jekyll templates in gh-pages](https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/) (though I haven't tried this option yet).

I can try to give it shot in my personal fork and if I can get to something that is decent enough I will open a PR and we can take it over from there.

How does it sound?

**Comment by mcollina** [comment]
👍

**Comment by delvedor** [comment]
Sounds amazing :)

**Comment by lmammino** [comment]
Sneak preview 😛 

![screen shot 2017-07-23 at 09 57 13](https://user-images.githubusercontent.com/205629/28498048-6335acb6-6f8d-11e7-8249-49893e428e06.png)

**Comment by mcollina** [comment]
Nice Job!

**Comment by mcollina** [comment]
We might integrate https://docsify.js.org for the docs part, it should provide navigable docs.

**Comment by lmammino** [comment]
Other sneaky preview, just completed the home page and basic style. Everything else should be slightly faster. Hopefully, by tomorrow I'll have a complete first preview :)

![localhost-4000- 1](https://user-images.githubusercontent.com/205629/28548552-69e9efa0-70cc-11e7-92ac-9cbc054c14c5.png)

**Comment by lmammino** [comment]
Sneaky preview 3 (a sample of the documentation page). Now benchmarks and ecosystem left and we should be able to preview a first version on which we can iterate on 😉 

![localhost-4000-docs-getting-started-](https://user-images.githubusercontent.com/205629/28588541-d06e2646-7172-11e7-8c30-1deafe481f3e.png)

**Comment by delvedor** [comment]
I think that we should use the UI @lmammino is developing for the docs as well, to have a consistent aspect of the website.

@lmammino you are doing an awesome job! :)

**Comment by lmammino** [comment]
Thanks @delvedor, glad you like what i have done so far.

Here a real preview from my fork master branch: https://lmammino.github.io/fastify/

I will try to align my fork with the latest changes in the official repo , then I'll need to revisit all the links in the doc and finally I should be ok to submit a PR.

**Comment by lmammino** [comment]
Of course, meanwhile, feel free to provide feedback or report anything that you don't like. I took some freedom in some paragraphs, so I expect you to review everything also in terms of copywriting.

**Comment by delvedor** [comment]
This can be closed :)

https://github.com/fastify/website
http://www.fastify.io/
