### ISSUE TITLE
use console.log

### ISSUE THREAD

**Issue by FishOrBear** [fastify/fastify#1394]
I wrote to try this code, but it seems to have no effect.
```
const server = fastify({
    logger: { prettyPrint: true, level: "debug", prettifier: pinoInspector }
});

server.log = console;
```

**Comment by mcollina** [comment]
It seems pretty adeguate that it is not working. Why are you expecting this to work? What are you trying to do?

**Comment by FishOrBear** [comment]
I am using vscode for debugging and I want it to be displayed in the debug console.


This library may be helpful, but I have not used it.
Https://github.com/pinojs/pino-inspector

**Comment by mcollina** [comment]
That’s what you need to use

**Comment by jsumners** [comment]
Use `outputCapture` in your launch configuration. https://code.visualstudio.com/updates/v1_17#_viewing-output-from-direct-stdoutstderr-writes

**Comment by mcollina** [comment]
I didn’t know about that!

**Comment by FishOrBear** [comment]
@jsumners 
```
    {
            "type": "node",
            "request": "attach",
            "name": "debug ing",
            "port": 9229,
            "restart": true,
            "protocol": "inspector",
            "address": "localhost",
            "outputCapture": "std"
        },
```

I added this setting and it seems to have no effect.

**Comment by FishOrBear** [comment]
@mcollina 
The combination of pinoInspector and fastify seems to have no effect.

**Comment by FishOrBear** [comment]
When I use Fastify.log = console, I can't capture the following log.

```
[2019-01-16T14:17:03.295Z] INFO (9780 on XXX): request completed
    reqId: 2
    res: {
      "statusCode": 200
    }
    responseTime: 2.469999998807907
```

**Comment by Eomm** [comment]
Hi,
I have tried to replicate the problem but I wasn't able, ether with or not reassigning `fastify.log`

With this example code:

```js
const pinoInspector = require('pino-inspector')
const fastify = require('./fastify')(
  { logger: { prettyPrint: true, level: 'debug', prettifier: pinoInspector } }
)

fastify.addSchema({ $id: 'one', my: 'hello' })
fastify.get('/', (request, reply) => {
  fastify.log.debug('hello world')
  reply.send(fastify.getSchemas())
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`We are ready!`)
})
```

```json
    {
      "type": "node",
      "request": "attach",
      "name": "Debug Fastify",
      "port": 9229,
      "restart": true,
      "protocol": "inspector",
      "address": "localhost"
    },
```

and runned with: `node --inspect-brk test.js` and then start the debugger on VSCODE v1.30.2, fastify `v2.0.0-rc.4` on node `10.14.2` 

![image](https://user-images.githubusercontent.com/11404065/51277125-04297680-19d7-11e9-85aa-3678844cc275.png)

Could you add more details?

**Comment by FishOrBear** [comment]
Sorry I didn't update nodejs, my version is 10.7, I updated nodejs and solved this problem.
