### ISSUE TITLE
Set allErrors: true in default AJV instance

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1397]
## 🚀 Feature Proposal

Set `allErrors: true` in default AJV instance

## Motivation

Validation should return all errors by default (I believe this is the preferred case most of the time)

This will degrade performance though but not sure how much

**Comment by cemremengu** [comment]
Strange, even with setting `allErrors: true`, I still get only one validation error for the request body. Maybe I am getting this wrong.

**Comment by mcollina** [comment]
Can you make an example of the new output?

**Comment by cemremengu** [comment]
It will basically trigger this line

https://github.com/fastify/fastify/blob/3faaa2cbfd0a158c5480473bf7e97d70ae192b48/lib/validation.js#L147

producing and error message

`body should have required property 'username', body should have required property 'username'`

instead of only

`body should have required property 'username'`

when both `username` and `password` fields are required but not provided.

**Comment by mcollina** [comment]
I think it’ll be good to have as a default, would you mind firing a PR?
