### ISSUE TITLE
Worker Threads support?

### ISSUE THREAD

**Issue by galuh1300d** [fastify/fastify#1401]
Can i use worker threads within fastify?

**Comment by delvedor** [comment]
You can since you are using Node.js.
What do you want to do with them?

**Comment by galuh1300d** [comment]
I planned to build finance application like treasury app.
I want to take benefit of the worker threads, but don't know how to implemented it in fastify.
i will make a research for it.

**Comment by delvedor** [comment]
You can definitely use workers to handle CPU heavy operations but **not** for handling every single request (1 worker = 1 request).

**Comment by delvedor** [comment]
It depends by what you need to do, the only thing that is important is that you **should not** use a worker for every request, but instead use a pool such as https://www.npmjs.com/package/worker-threads-pool.

**Comment by galuh1300d** [comment]
Thank you for your suggestion. i'll check it out

**Comment by Kikobeats** [comment]
Hey @delvedor, can you clarify why a worker per every request is not recommended?

**Comment by delvedor** [comment]
@Kikobeats because as far as I know worker threads are limited, you should use them carefully.
Take a look at [piscinajs](https://github.com/piscinajs/piscina) and its [fastify integration](https://github.com/piscinajs/fastify-piscina).

**Comment by muuvmuuv** [comment]
I still think this is a great idea. JavaScript is single threaded so if you have an API application in fastify that is not a microservice and not in a cluster you have a single core fastify server. Having workers to load balance incoming requests would be super efficient. 

Imagine this:

- 10_000 requests coming in
- fastify knows server has 16 cores, but you limited it to 10 + 4 which you can manually use with piscina to handle heavy tasks (workers can call workers as far as I know)
- fastify thows every request one by one in a worker, so request one goes into worker one and so on
- if the last worker is reached begin at one
- one worker ofc would not process just one request but 10_000 / 14 requests
- async callbacks are thrown back to the requester

The idea of Piscina is nice, but it does not work with the latest fastify version... would have used it for some heavy tasks.

**Comment by fox1t** [comment]
Actually Node.js handles async code using its own “thread pool” internally. What is single threaded, is the main loop and “how you write” your code. We already have non blocking requests and using workers will actually be worst for the specific use case, because of their overhead they adds. On the other hand if you have some CPU heavy code to execute during the request-response phase you should offload it to a dedicated worker to prevent blocking Node.js main loop and therefore the future incoming requests.
