### ISSUE TITLE
Shrink the npm package size by excluding test and docs

### ISSUE THREAD

**Issue by txchen** [fastify/fastify#1405]
## 🐛 Bug Report

Currently the fastify package on npm is including `test`, `docs`, `examples`, `tools`, `.github`. These files are not needed by a package consumer, is it okay to exclude them from npm publish?

## To Reproduce

Paste your code here:

```js
npm i fastify@2.0.0-rc.4
ncdu node_modules
```

## Expected behavior

npm package only contains the files to support runtime and development time (like *.d.ts). Unrelated files should not be published.

## Your Environment

- *node version*: 11
- *fastify version*: >=2.0.0-rc.4
- *os*: Mac

**Comment by cemremengu** [comment]
I think we can add an `.npmignore` file for those

**Comment by delvedor** [comment]
@mcollina and I are convinced that shipping docs, test, and examples, improve the developer experience. You have in your local machine everything you need to debug an error, see an example or read the documentation. This especially useful if you are having connection issues or you are traveling and working.

Until we see a critical case that would be fixed by the removal of those files, I don't think we will remove them :)

**Comment by jsumners** [comment]
I agree. But I think we can skip packing the `.github` directory.

**Comment by mcollina** [comment]
I think we should skip both `.github`  and `tools`. Tools are needed only ti generate the website which lives on a separate repo.

**Comment by txchen** [comment]
@delvedor Fair point for offline mode. However before you told me this, I never expect I can find examples and docs in my node_modules. My guess is most users don't know that, too. Maybe it is not as useful as you think :)

**Comment by jsumners** [comment]
It's useful to a majority of the maintainers of the project.

**Comment by txchen** [comment]
@jsumners For project maintainers, you should have your repo on your local machine. Why would you need to dig your node_modules to find examples and docs?

**Comment by jsumners** [comment]
Because I don’t need to shift focus to other projects/windows. I simply open `node_modules` and explore to the information I need via my editor’s file sidebar. I also don’t have every project on every system I use.

**Comment by delvedor** [comment]
> My guess is most users don't know that, too. Maybe it is not as useful as you think :)

This does not mean that it is not useful, it is part of the dev experience, even if you are not using it.
