### ISSUE TITLE
Change log level to `warn` on stream error when "premature close"

### ISSUE THREAD

**Issue by popeindustries** [fastify/fastify#1406]
## 🚀 Feature Proposal

Change log method to `res.log.warn` if client hang-up error when streaming a response (when error message is "premature close"). The change would be needed at [line 294](https://github.com/fastify/fastify/blob/7e963aa1a2a545e312de1006c510c655a38134ea/lib/reply.js#L294) and [line 306](https://github.com/fastify/fastify/blob/7e963aa1a2a545e312de1006c510c655a38134ea/lib/reply.js#L306) of reply.js 

If this is acceptable, I don't mind making a PR for the change!

## Motivation

Strictly speaking, in a server context, it is not an error if the client hangs up, and these errors create a lot of noise, especially when stress testing a server (with `autocannon`, for example).

## Example

[no example]

**Comment by mcollina** [comment]
Can you send us a PR for this change?
