### ISSUE TITLE
Serialization references not resolved

### ISSUE THREAD

**Issue by MichielDeMey** [fastify/fastify#1410]
## 🐛 Bug Report

References for validation can be added using the `addSchema` method, so in our JSON schemas we can safely use `$ref` to reference them.

However, when trying to do the same for the serialization using `fast-json-stringify` I get the following error:

```
Error: schema is invalid: data.items.$ref should be string, data.items should be array, data.items should match some schema in anyOf
```

Reading up on the documentation (https://github.com/fastify/fast-json-stringify#ref) it seems that external definitions need to be passed as an option, so I was wondering if the `addSchema` function would not already do this?

## To Reproduce

asset.schema.json
```json
{
  "$id": "http://poppy.be/schemas/asset.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Physical Asset",
  "description": "A generic representation of a physical asset",
  "type": "object",
  "required": [
    "id",
    "model",
    "location"
  ],
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "model": {
      "type": "string"
    },
    "location": { "$ref": "http://poppy.be/schemas/geo/point.json#" }
  }
}
```

point.schema.json
```json
{
  "$id": "http://poppy.be/schemas/geo/point.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Longitude and Latitude Values",
  "description": "A geographical coordinate.",
  "type": "object",
  "required": [
    "latitude",
    "longitude"
  ],
  "properties": {
    "latitude": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "altitude": {
      "type": "number"
    }
  }
}
```

assetResponse.schema.json
```json
{
  "$id": "http://poppy.be/schemas/response/assetLocations.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "List of Asset locations",
  "type": "array",
  "items": { "$ref": "http://poppy.be/schemas/asset.json#" },
  "default": []
}
```

Route
```js
app.get('/assets', { schema: { querystring: Schemas.geo.point, response: { 200: Schemas.response.assetLocations } } }, async (req, res) => {
  ...
})
```

## Expected behavior

The serialization should simply be able to resolve the `asset` schema.

## Your Environment

- *node version*: 10
- *fastify version*: >=1.0.0
- *os*: Mac

**Comment by mcollina** [comment]
That's currently not supported, but I think it would be a good feature to have.

See https://www.fastify.io/docs/latest/Validation-and-Serialization/ for what is currently supported.

**Comment by MichielDeMey** [comment]
Would it be possible to extend the `addSchema` call to also register the schema to `fast-json-stringify` instead of just `ajv`? Not sure if it's possible though.

**Comment by mcollina** [comment]
fast-json-stringify has no such feature at the moment. I think it would be
a good addition.

Il giorno ven 25 gen 2019 alle 15:22 Michiel De Mey <
notifications@github.com> ha scritto:

**Comment by Eomm** [comment]
Hi, I would like to work on this issue ✌

The solution I have seen is:
- all the schema added with `addSchema` could be pass to `fast-json-stringify` as externals schemas with the keys equals to `$id` field of added schemas
- put a stronger validation in `Schemas.traverse` (because it modifies the `$ref` field instead of leaving it as is.. this cause the `Error: schema is invalid: data.items.$ref should be string` error)

I have tried in my local env and works 👍
