### ISSUE TITLE
How to call a decorate methods in typescript 

### ISSUE THREAD

**Issue by Jegannathan** [fastify/fastify#1417]

**Comment by cemremengu** [comment]
I think you should be able to call them like you do in JavaScript. Could you please elaborate a little?

**Comment by Jegannathan** [comment]
fastify.decorate('config',{
port:4000
})

in js fastify.config.port is possible

But in typescript fastify.config.port throw an error like property config is not present in Fastify instance

**Comment by Norlandz** [comment]
For above quote

> A blog explaining the process in more detail: https://medium.com/car2godevs/fastify-with-typescript-production-ready-integration-2303318ecd9e

pay attention to this line:

> `fastify` server instance does not contain any property called `db`, so let’s use augmentation again and update *src/@types/augmentation.ts*:
> 
> ```ts
> import * as fastify from "fastify";
> import * as http from "http";
> 
> import { Db } from "../modules/db";
> declare module "fastify" {
>   export interface FastifyInstance<
>     HttpServer = http.Server,
>     HttpRequest = http.IncomingMessage,
>     HttpResponse = http.ServerResponse
>   > {
>     blipp(): void;
>     db: Db;
>   }
> }
> ```

---

For an example (In my case (_not sure if I did it correctly_) eg::)

1. I put `@types` under `src` 
1. I only use `export interface FastifyInstance {` without generics
1. then I can access the property `port`

vv

`H:\Using\JsParserSub\src\@types\fastify`

```ts
import fastify from 'fastify';
// import * as http from 'http';

declare module 'fastify' {
  export interface FastifyInstance {
    // export interface FastifyInstance<HttpServer = http.Server, HttpRequest = http.IncomingMessage, HttpResponse = http.ServerResponse> {
    port: number;
  }
}

```

`H:\Using\JsParserSub\src\main\index.ts`

```ts
const usersRouter: fastify.FastifyPluginAsync = async function (fastify: fastify.FastifyInstance, options: fastify.FastifyPluginOptions) {
  fastify.port; // << watch this
}

```

**Comment by Mir1001** [comment]
> You will need to augment the fastify type definition, so typescript knows about the new property:
> 
> File: `yourproject/@types/fastify/index.d.ts` (if the compiler does not pick up your definitions file, add the location of the @types folder to `typeRoots` in your `tsconfig.json`)
> 
> ```ts
> import fastify from 'fastify';
> 
> declare module 'fastify' {
>   export interface FastifyInstance<
>     HttpServer = Server,
>     HttpRequest = IncomingMessage,
>     HttpResponse = ServerResponse,
>   > {
>     port: number;
>   }
> }
> ```
> 
> Read more about augmentation in the docs: https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation
> 
> A blog explaining the process in more detail: https://medium.com/car2godevs/fastify-with-typescript-production-ready-integration-2303318ecd9e

Thx. There is not enough information on how to do it. Thanks to you, I have managed to define the decorate function in a plugin:
```js
// in folder @types/fastify/index.d.ts
import fastify from "fastify"; 

declare module "fastify" {
  export interface FastifyInstance<
    HttpServer = Server,
    HttpRequest = IncomingMessage,
    HttpResponse = ServerResponse
  > {
    verifyJWT: function;
  }
}
//----------function somewhere in your code
async function authDecorate(server: FastifyInstance, options: Object) {
    server.decorate(
    "verifyJWT",
    function (
      request: FastifyRequest,
      reply: FastifyReply,
      done: HookHandlerDoneFunction
    ) {
      // your validation logic
      console.log("verifyJWT");
      var ok = true;
      if (ok) {
        done();
      } else {
        done(new AuthError("Wrong token. Login again."));
      } // pass an error if the authentication fails
    }
  );

```
