### ISSUE TITLE
Am I missing a step to trigger a preHandler wi

### ISSUE THREAD

**Issue by cwhiteley** [fastify/fastify#1418]
## 💬 Questions and Help
I created a simple fastify route similar to the documentation and it seem that the preValidation and preHandler are not triggering.  Am I missing a step?

const fastify = require('fastify')({
    logger: true
  })

fastify.decorateRequest('user', 'decorate')

fastify.route({
    method: 'GET',
    url: '/',
    preValidation: function (request, reply, done) {
        console.log("preValidation")
        request.user = 'preValidation'
        done()
    },
    preHandler: function (request, reply, done) {
      console.log("preValidation")
      request.user = 'preHandler'
      done()
    },
    handler: function (request, reply) {
      console.log(request.user)
      reply.send({ hello: 'world' })
    }
  })

// Run the server!
fastify.listen(3000, function (err, address) {
    if (err) {
      fastify.log.error(err)
      process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
  })

The above creates a proper reply, but i am unable to alter the request.user within the preValidation or the preHandler.  Additionally the console.log's are not printing.  Have i missed a step?

Context
node version: 11.7
fastify version: 1.13.4
os: Mac

**Comment by cemremengu** [comment]
They are part of Fastify v2. Try the `next` version on npm.

**Comment by Extarys** [comment]
Does this is in v2 also? If not I'll open a new issue. It doesn't seem to be working on my end.

```
  fastify.addHook('preHandler', (request, reply, next) => {
    console.log('\n \nTop preHandler\n \n');
    next();
  });
```

**Comment by mcollina** [comment]
the `preHandler`  hook is also in v1: https://www.fastify.io/docs/v1.13.x/Lifecycle/.

We should really update point-of-view.

**Comment by cwhiteley** [comment]
Thank you - I have verified that these do work within v2.   Thank you.
