### ISSUE TITLE
Json schema $ref id

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#1419]
## 🐛 Bug Report

Hi, testing the (fluent) json-schema I found that the [id-with-ref](https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref) function is broken and return on start:

> { [Error: can't resolve reference #address from id #]
  message: 'can\'t resolve reference #address from id #',
  missingRef: '#address',
  missingSchema: '' }

## To Reproduce

```js
const fastify = require('./fastify')({ logger: { level: 'debug' } })

const body = {
  '$schema': 'http://json-schema.org/draft-07/schema#',
  'definitions': {
    '#address': {
      'type': 'object',
      '$id': '#address',
      'properties': {
        'city': {
          'type': 'string'
        },
        'zipcode': {
          'type': 'string'
        }
      }
    }
  },
  'type': 'object',
  '$id': 'http://foo/user',
  'title': 'My First Fluent JSON Schema',
  'description': 'A simple user',
  'properties': {
    'email': {
      'type': 'string',
      'format': 'email'
    },
    'address': {
      '$ref': '#address'
    }
  },
  'required': [
    'email'
  ]
}

fastify.post('/', { schema: { body } }, (request, reply) => { reply.send('good') })
fastify.listen(3000).catch(console.log)
```

## Expected behavior

The JSON schema is a valid one and use the `$ref: '#id'` function so the error doen't have to be thrown and the `#address` should be resolved.

## Your Environment

- *node version*: 10
- *fastify version*: >= 2.0.0-rc.4 `master branch`
- *os*: Windows

I would like to work on it 😃
I found that the problem is due to this line for the issue #1043  https://github.com/fastify/fastify/blob/310cb60b439fb363b28d42eb2e0f351447c7f11b/lib/schemas.js#L83
-if I comment it the example works fine, but the test fails-

**Comment by mcollina** [comment]
Go for it! I think we removed that property for some reason, can you investigate?

**Comment by Eomm** [comment]
I fixed the problem, PR is coming.

I'll try to explain the problem as best as I can, because I think could be the start of a discussion:

1. the `schemas.js#traverse` is executed and all the field with the value that ends with `#` are changed to the shared-schema corresponding
1. all the fields now are pointing to the same object with the `$id` set
1. that `$id` is a fake one, is not regarding the json-schema standard: is only to reference a shared schema with the pattern `<shared-schema-$id>#`
1. so this `$id` is removed, otherwise, the `AJV.checkUnique` will throw an exception if it finds multiple equals `$id`

So, this deletion may be done only for those `$id` that are not standard, in other word only for the `$id` used in the shared schema (the PR implement this behaviour)

⚠ Warning:
`$id` and `$ref`, looking the draft07, could be set with a [JSON Pointer](https://www.ietf.org/archive/id/draft-handrews-relative-json-pointer-01.txt). [This is even discouraged](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3):

> Using JSON Pointer fragments requires knowledge of the structure of
   the schema.  When writing schema documents with the intention to
   provide re-usable schemas, it may be preferable to use a plain name
   fragment

The warning is due the pattern that JSON pointers could have:

                   "0/objects"                 true
                   "1/nested/objects"          true
                   "2/foo/0"                   "bar"
                   "0#"                        "nested"
                   "1#"                        "highly"

The lastest would match the fastify `<shared-schema-$id>#` and would break the startup.
So, at the actual state, we need to know that if some one use JSON Pointers in `$id` or `$ref`, will have issues.

**Comment by mcollina** [comment]
@Eomm do we support "plain name fragments"?

**Comment by Eomm** [comment]
Sorry, false alarm 😅

I would like to explain for the future: reading the json-schema draft 07 the `$id` MUST be a string, and MUST represent a valid URI-reference. 
This value defines a URI for the json-schema itself.

So, either the `$id` and the `$ref` field must have a URI value.

An URI could be like:

| Format | Regexp | Example | Note
|---|---|---|---|
| Plain name fragment | `^#[A-Za-z]{1}[\w-:.]{0,}$` | `#my-id` | In the root schema there is a `$id=#my-id`
| JSON Pointer fragment | [here](https://tools.ietf.org/html/rfc6901#section-6) | `#/definitions/address` | In the `definitions` there is a field `address: { type: 'object' ....etc...}`
| JSON Relative Pointer | [here](https://tools.ietf.org/html/draft-handrews-relative-json-pointer-01#section-6) | `1#` | ❌ WRONG this format can't be used like an URI ❌

In the json-relative-pointer standard is written:

> Unlike a JSON Pointer, a Relative JSON Pointer can not be used in a URI fragment identifier.

And also in the json-schema draft is written:

> The effect of using a fragment in "$id" that isn't blank or doesn't follow the plain name syntax is undefined

So, I don't know why the json-schema site show the link to the json-relative-pointer in the home page if they don't want to use it 😅

Anyway this is perfect because we will never have collision with the shared-schema feature.

**Comment by mcollina** [comment]
Open an issue on the website, I think they should be fixing it.
I don't understand what would be the solution for us.

**Comment by handrews** [comment]
@mcollina @Eomm JSON Relative Pointer is a proposed standard maintained by the JSON Schema project (and it will be re-submitted when we re-submit the others- they are all temporarily expired for reasons not worth going into here).

In particular, JSON Relative Pointer is used by JSON Hyper-Schema.  It is not used in the URI Fragment syntax for the `application/schema+json` or `application/schema-instance+json` media types, but it is used elsewhere in the project.

As @Eomm notes, the specification for `$id` is quite clear on this already.  JSON Pointer and JSON Relative Pointer are separate specifications, and only JSON Pointer and plain name are allowed.

In the original example posted above, `'$id': '#address'` is a valid plain name fragment identifier.  I personally find naming the definition `#address` as well somewhat confusing (because then it looks like they have to match, which they don't), but it's a legal definition name.

**Comment by mcollina** [comment]
Thanks for joining the discussion @handrews and for the explanation!
