### ISSUE TITLE
Protect against prototype poisoning

### ISSUE THREAD

**Issue by hueniverse** [fastify/fastify#1426]
See: https://hueniverse.com/a-tale-of-prototype-poisoning-2610fa170061

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1427.
Thanks!

**Comment by franciscolourenco** [comment]
This link is in the [docs](https://www.fastify.io/docs/latest/Server/#onprotopoisoning), but it seems to be dead  https://hueniverse.com/a-tale-of-prototype-poisoning-2610fa170061

**Comment by mcollina** [comment]
@franciscolourenco would you like to send a PR to update it using the webarchive link.

**Comment by franciscolourenco** [comment]
Seems like it was only saved once and without anything useful: http://web.archive.org/web/20201203225852/sideway.com/a-tale-of-prototype-poisoning-2610fa170061

**Comment by mcollina** [comment]
Sigh. Then let's remove.

**Comment by hueniverse** [comment]
In case you want the post... I no longer maintain any public presence online other than here.
[post.zip](https://github.com/fastify/fastify/files/6298368/post.zip)

**Comment by jsumners** [comment]
@hueniverse thank you. Are you opposed to us hosting it within https://fastify.io with proper attribution?

**Comment by hueniverse** [comment]
You can do whatever you want with it. Consider it MIT licensed.
