### ISSUE TITLE
attachValidation document is wrong?

### ISSUE THREAD

**Issue by wh1tecat-nya** [fastify/fastify#1429]
https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md

i see "ErrorHandling" section of this document and i'm test by my local environment.
in document, write this

>If you want to handle errors inside the route, you can specify the attachValidation option for your route. If there is a validation error, the validationError property of the request will contain the Error object with the raw validation result as shown below

and attached this code.
```JavaScript
const fastify = Fastify()

fastify.post('/', { schema, attachValidation: true }, function (req, reply) {
  if (req.validation) {
    // `req.validationError.validation` contains the raw validation error
    reply.code(400).send(req.validationError)
  }
})
```

but run this code(scheme is customized) in my environment, "req.validation" is every time undefined.
so I would like to confirm there, "req.validation" is typo "req.validationError" ?

thank you.

**Comment by mcollina** [comment]
Which version of fastify are you using? That document references to v2 (currently at v2.0.0-rc.4).
The one fore v1 is at https://www.fastify.io/docs/v1.13.x/Validation-and-Serialization/

**Comment by wh1tecat-nya** [comment]
@mcollina 
thanks reply.
i'm checked v2.0.0-rc4 and v1.13.4 but which is has same issue.

What i can think from here, is that it has become like this for one of the two reasons.

1.validation logic has bug. "req.validation" is need some value.
2.document is wrong. "req.validation" is typo "req.validationError"

Is there any other possible cause?

**Comment by wh1tecat-nya** [comment]
i've read fastify source code.
and found this. https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L83-L88

looks like document is wrong.
because "req" is not have "validation" property.

**Comment by mcollina** [comment]
Definitely. Would you like to send a PR?

**Comment by wh1tecat-nya** [comment]
sorry, this is first time send PR in my life.
if something wrong, please teach me.

and i have 1 question.
need PR for v1.x branch?

**Comment by mcollina** [comment]
@wh1tecat-nya that would be helpful, thanks! Your PR is ok, we'll wait for more reviews!
