### ISSUE TITLE
Axios POST with data, router POST log "msg":"incoming request".

### ISSUE THREAD

**Issue by standfv** [fastify/fastify#1445]
## 💬 Questions and Help

Axios POST with data, router POST log "msg":"incoming request".

### Please note that this issue tracker is not a help forum and this issue may be closed.

Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Comment by cemremengu** [comment]
What's the problem? Can you give some details?

**Comment by standfv** [comment]
1. https://www.upnhanh.com/image/pJYGH - My method POST "http://localhost:1997/api/v1/auth/login" with data params { username: "standfv", password: "abc" } 
2. I click POST my log command show "incoming request" and not reply.send on router /login  -> https://www.upnhanh.com/image/pJ88I
3. And client error -> https://www.upnhanh.com/image/pJWwJ
If my action method POST widthout data reply success, but action method POST width data error : "incoming request"
