### ISSUE TITLE
Plugins best practices

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1448]
So I'm working with `fastify` some time already and I truly love it! :smile: After some time I came to a reflection about plugins and I'm not sure if I get it right.

Let me explain my case in an example:

My app needs some posts and tags API. These two could be easily separate microservices so I'd like to split them into plugins:

**users.js**
```js
module.exports = async fastify => {
    const db = somedb('conn.string');
    fastify.get('/users/:id', (request, reply) => {
        // db operations
    });
    // other endpoints
}
```

**tags.js**
```js
module.exports = async fastify => {
    const db = somedb('conn.string');
    fastify.get('/tags/:id', (request, reply) => {
        // db operations
    });
    // other endpoints
}
```

Alright! Everything is cool. But... I duplicate database access code right now, and if I'd like even more plugins I'd duplicate this even more.

`fastify-plugin` to the rescue! I will create a shared database plugin which will decorate the fastify instance with a db wrapper, use it in my root `server` file and just use it in all my plugins:

**server.js**
```js
fastify.register(require('dbplugin'), { connstring: '...' });
fastify.register(require('./users'));
fastify.register(require('./tags'));
``` 

**users.js/tags.js**
```js
module.exports = async fastify => {
    // use fastify.db() here
 }
```

And here my concerns come into play:

1. Doesn't relying on shared plugins (via `fastify-plugin`) break encapsulation? It would make sense if I could use `fastify-plugin` `dependencies` field, but nothing like this is available in pure `fastify` plugins and I have no clear indicator that tells me that I forgot to provide a dependency to the encapsulated plugin
2. Relying on shared plugins also makes testing harder, as I need to remember and provide all required plugins in the test (with all configurations)

So my question is: is it a better practice to encapsulate every dependency in a plugin, or rather provide all the shared functionality from a higher-level `fastify` instance? If the latter, then how do I ensure that these dependencies are present (should I do a manual check?)

I hope I've explained my issue well so it's clear. If not, just ask :smile:

**Comment by mcollina** [comment]
First, you should likely await for getting a database instance:

```js
module.exports = async fastify => {
    const db = await somedb('conn.string');
    fastify.get('/users/:id', (request, reply) => {
        // db operations
    });
    // other endpoints
}
```

The plugin/decorator system makes it clear what are the dependencies.

> 1. but nothing like this is available in pure `fastify` plugins

That logic is actually as part of fastify, not fastify-plugin. I think we should just expose it. Would you like to propose some API for this?

Note that they all works via https://github.com/fastify/fastify-plugin/blob/master/index.js#L37.

**Comment by sarneeh** [comment]
> First, you should likely await for getting a database instance

Yeah, that was just an example, I didn't want to make it proper code.

> The plugin/decorator system makes it clear what are the dependencies

I don't understand how it makes it clear what are the dependencies? If I'm using `fastify-mongodb` on the app-level and `fastify.mongo` (or whatever else) on my internal plugin-level then how do I know what kind of dependency does my plugin need?

The `dependencies` meta key would make it much more clear.

> Would you like to propose some API for this?

I'm sorry but I can't right now :cry:
