### ISSUE TITLE
POST Request returns Http Status 504

### ISSUE THREAD

**Issue by panbhatt** [fastify/fastify#1449]
Hi Team,
I am Still using Fastify 1.0RC2 and falls into a weird problem. I am trying to make a HTTP POST Request (having JSON body of 1.5MB) from Angular (via using PROXY CONFIG JSON) to fastify server. However seems like the server is never processing the request. In the Logs i can see ÏNCOMING REQUEST but nothing happens after that. 
I tried it on multiple systems same problem is ouccring on specific HTTP EndPoints. I can clearly see that other requests are being processed successfully prior and after to this. Just this request is being BLOCKED. 

Can anyone help me to figure out where to dive down to find this. 
Note: The MAX BODY Limit is also being increased to 10MB.

**Comment by mcollina** [comment]
We would need an isolated example to be able to reproduce the problem. Can you upload that?

**Comment by panbhatt** [comment]
This issue is resolved after changing the server timeout ( by increasing it).  So closing the issue.
