### ISSUE TITLE
Passing to data with a redirect to another route

### ISSUE THREAD

**Issue by sjorsjes** [fastify/fastify#1450]
## 💬 Questions and Help

I'm building an user registration flow. After an user login (normal form post). I'd like to redirect to user to another page but I want to pass along some data (like notifications). Are querystrings or adding to the `req.session` the best solution here?

```
// Login POST
app.post('/', async (req, reply) => {
  // ... post user info

  const notification = 'Great succes';

  reply.redirect('/dashboard');
});

// Dashboard
app.get('/dashboard', async (req, reply) => {
  // How to get the notification data here?

  reply.view('login', { notification });
});
```

Ideal situation?
```
// Login POST
app.post('/', async (req, reply) => {
  // ... post user info

  const notification = 'Great succes';

  reply.redirect('/dashboard', { notification });
});

// Dashboard
app.get('/dashboard', async (req, reply) => {
  const { pageData: { notification } } = req; // Only lives for this route, once and is not persistent

  reply.view('login', { notification });
});
```

**Comment by mcollina** [comment]
You'll need to build such a system using cookies. Those two routes are completely independent and stateless, so there is no shared way to do this.

You can use https://github.com/fastify/fastify-cookie or https://github.com/mcollina/fastify-secure-session for this purpose.
