### ISSUE TITLE
Response type based on `accept` header

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#146]
I'd like to split the http handle logic from its representation over http.

```js
fastify.route({
  method: 'GET',
  url: '/',
  schema: {
    querystring: {
      name: { type: 'string' },
      excitement: { type: 'integer' }
    },
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: function (request, reply) {
    reply.send({ hello: 'world' }) // <--- obviously send method is wrong
  },
  serializer: {
    // accept header choose which function should be call
    'json': function (req, res, body) {
      // this can be the store object
      return serialize(this, body, res.statusCode)
    },
    'yaml': function (req, res, body) {
      return getYamlFromJson(body)
    },
    'xml': function (req, res, body) {
      return getXmlFromJson(body)
    },
    'html': function (req, res, body) {
      // nice representation of body
      // very inefficient but this should not be called often
      // TODO: add headers too??
      return `<html><body><pre>${JSON.stringify(body, null, 2)</pre></body></html>`
    }
  }
})
```

`getYamlFromJson`and `getXmlFromJson`can be optimized like [fast-json-stringify](https://github.com/fastify/fast-json-stringify) is.

I'm expecting the body passes the ajv validation.

**Comment by mcollina** [comment]
I don't think this is a feature that should live in the framework, but rather in a plugin. However, we should definitely provide all the hooks/decorators/* that is needed to implement this.

**Comment by delvedor** [comment]
I'm not getting the need of this change, furthermore it seems over engineered.
Why not work with the `reply.serializer` api?

**Comment by allevo** [comment]
> I don't think this is a feature that should live in the framework, but rather in a plugin

Definitely!

The only thing the framework should support, is the access to `store` object through the `Request`  or `Reply` object.

The plugin adds a new `Reply` method like
```
module.exports = fp(function (fastify, opts, next) {
  fastify.decorateReply('render', function (obj) {
    const type = this.req.types()[0]
    this.send(this.store.serializer[type](this.res, this, obj))
  })
  next()
})
```

**Comment by allevo** [comment]
> Why not work with the reply.serializer api?

In this way the route configuration is described in the same place (thinking to swagger integration)

**Comment by delvedor** [comment]
Expose the `store` object inside`Reply` and `Request` is very easy, but since `Reply` and `Request` are stored inside `store` we will have also `Reply` and `Request` inside `Reply` and `Request` :P

I don't think we want that. We must figure out a way to remove them.
In any case we should not have a circular dependency.

**Comment by allevo** [comment]
> Expose the store object insideReply and Request is very easy, but since Reply and Request are stored inside store we will have also Reply and Request inside Reply and Request :P

Store contains only the `Request` and `Reply` constructor, not the instance. So the circular dependency doesn't exist.

For the time being, all plugins cannot interact with the route of a request/reply. Maybe can be useful for building plugin to store some custom/plugin dependent information in route definition.

**Comment by allevo** [comment]
Another proposal
```js

const schema = {
  schema: {
    response: {
      '2xx': { .. }
    }
  },
  serializer: function (body) {
    // my serialization login goes here
    // this === Reply instance
    // this._req === IncomingMessage instance
    return JSON.stringify(body) // poor serialization
  }
}

fastify.get('/', schema, function (req, reply) {
  reply.code(200).send({ hello: 'world' })
})
```

Maybe a `fastify.setDefaultSerializer` method should be implemented too.

**Comment by allevo** [comment]
See https://github.com/fastify/fastify-accepts-serializer
