### ISSUE TITLE
Add passport support

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#147]
Add [passport](https://github.com/jaredhanson/passport) support

**Comment by delvedor** [comment]
I'd like to implement this, but before we should be sure about the compatibility.
Fastify [wraps](https://github.com/fastify/fastify/blob/master/docs/Request.md) the standard request object, so we must be sure that this is not causing any problem on how passport works. If we can make it work with [fastify-auth](https://github.com/fastify/fastify-auth) would be awesome.

Furthermore I'd like to avoid monkey patching on the request object. (see the middleware examples)

*ps obviously this will be a plugin :P*

**Comment by allevo** [comment]
> ps obviously this will be a plugin :P

of course!

**Comment by delvedor** [comment]
Passportjs is built to work with Express, even if we support `connect` middlewares.
Seen this I don't think support Passport is a good idea, it monkey patch the core `request` object and it uses some Express related functions.

We should probably develop something line [hapijs/bell](https://github.com/hapijs/bell).
@mcollina thoughts?

**Comment by mcollina** [comment]
I tend to agree.

**Comment by allevo** [comment]
@delvedor [yea](https://github.com/jaredhanson/passport/blob/master/lib/framework/connect.js#L33)

bell cannot be integrated because of [this](https://github.com/hapijs/bell/blob/master/package.json#L51)
I think the installation fails on npm >=3

**Comment by delvedor** [comment]
@allevo I didn't explain myself, I don't want to *use* bell, I want to create something *like* bell :)

**Comment by allevo** [comment]
@delvedor sorry, I wrongly read.

I'm agree with this solution.

With this solution we "break" a *de facto standard* like passport or bell to reimplement the wheel better

**Comment by delvedor** [comment]
Security is hard, I don't think we should reimplement the wheel, bell is an amazing piece of software, probably a port for Fastify would be the best idea.

@mcollina @allevo what do you think about this?

**Comment by allevo** [comment]
@delvedor are you thinking to fork bell and adapt it to fastify?

**Comment by delvedor** [comment]
@allevo not a fork, just clone the repo and adapt it to fastify, obviously maintaining the original license and copyright to the original authors.

**Comment by marcbachmann** [comment]
FYI https://github.com/marcbachmann/passport-light

**Comment by jsumners** [comment]
@marcbachmann would you be able to provide an example that includes using a session?
