### ISSUE TITLE
Split up fastify.js

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1475]
Currently the `fastify.js`  file is very big, and it contains several concerns, all mixed together. Maybe it's time we split it up into tinier files that are easier to read and contribute to.

**Comment by jsumners** [comment]
Yes.

**Comment by delvedor** [comment]
I'll take care of this :)

**Comment by delvedor** [comment]
Next pieces that will need refactoring:
- 404 handling
- route declaration

**Comment by Eomm** [comment]
I'll work on the 404 refactoring ✌

**Comment by Eomm** [comment]
Merged 404

Next pieces that will need refactoring:
+ route declaration

**Comment by Eomm** [comment]
Starting route declaration
