### ISSUE TITLE
How to use a .CER and .PFX files to Https?

### ISSUE THREAD

**Issue by ketrujillo08** [fastify/fastify#1479]
Hi everyone I'm starting using your amazing framework, but now I'm trying to install a private cetificate, but I'm researching that fastify use a cer and key files to enable HTTPS, How I could enable HTTPS on my API with a cer and pfx files?

**Comment by darkgl0w** [comment]
Hi,

As it is stated in the documentation (https://www.fastify.io/docs/latest/Server/), `https` options must be an object that accept the same entries that Node.js core `createServer` method.
Here you can find all options that are accepted to create a secure context: [Node.js 10.15.1 LTS docs](https://nodejs.org/dist/latest-v10.x/docs/api/tls.html#tls_tls_createsecurecontext_options) in your case you will need to pass a `pfx` property.

**Comment by cemremengu** [comment]
@ketrujillo08 Closing this, feel free to reopen if needed

@darkgl0w thanks for the help!
