### ISSUE TITLE
NPM failure on `npm install --save fastify` (Unexpected token in parsing near find-my-way-0.2.4.tgz)

### ISSUE THREAD

**Issue by lmammino** [fastify/fastify#1482]
## 🐛 Bug Report

There seems to be an issue with the current package setup for 2.0.0 (and the other RC).

When trying to install with `npm i --save fastify`

I get the following error:

```plain
npm ERR! Unexpected token  in JSON at position 2079 while parsing near '...d-my-way-0.2.4.tgz"}...'

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2019-02-25T15_20_03_412Z-debug.log
```

Same happens with the following sequence of commands:

```bash
git clone https://github.com/fastify/fastify.git
cd fastify
npm install
```

## Your Environment

- *node version*: v11.8.0 (npm 6.8.0)
- *fastify version*: >=2.0.0
- *os*: Mac
- Also tested on another laptop with node 11.9 and npm 6.5 with same error
- Also tested on different networks using VPNs (so doesn't seem cache related)

## Updated

It seems that even doing the following will raise the error:

``` bash
npm i --save find-my-way
```

Output:

```plain
npm ERR! Unexpected token  in JSON at position 2079 while parsing near '...d-my-way-0.2.4.tgz"}...'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lucianomammino/.npm/_logs/2019-02-25T15_25_12_551Z-debug.log
```

**Comment by mcollina** [comment]
It seems it's a bug on npm :(.

**Comment by delvedor** [comment]
Yup, we are seeing a lot of failing builds on Windows as well.
I've pinged npm on twitter, but I didn't get an answer yet.

**Comment by lmammino** [comment]
Thanks for the quick reply @mcollina and @delvedor 

Fingers crossed then 🤞

**Comment by gunnartorfis** [comment]
I'm seeing this error as well. Not on my local machine though (macOS), but only on Elastic Beanstalk. Both using npm and yarn. 

This is stopping our whole deployment cycle - I will be monitoring this thread for updates. 👀

**Comment by mcollina** [comment]
Can somebody fetch one of those npm log files? Maybe there is some info there that we can help diagnose.

Is this happening only on Fastify v2?

**Comment by lmammino** [comment]
Back home and everything seems to install fine (both fastify v2 and v1)

<img width="1072" alt="screenshot 2019-02-25 at 19 21 18" src="https://user-images.githubusercontent.com/205629/53362647-9310a380-3932-11e9-879c-8af30541e68a.png">

I'll double check tomorrow again at work and get you the npm logs if still failing

**Comment by delvedor** [comment]
Apparently, also CI has started working again. I'll continue to monitor this.

**Comment by lmammino** [comment]
All back to normal even at the office... I'd say definitely an NPM glitch!

**Comment by mcollina** [comment]
CI seems to still be failing.

**Comment by lmammino** [comment]
Is there any option to trigger a build without cache in the CI?

**Comment by mcollina** [comment]
I don't think we have any caching on Azure, but I might be wrong.

**Comment by mcollina** [comment]
Unfortunately it's an NPM bug. I would recommend to contact NPM directly, there is literally _nothing_ we can do. Feel free to reopen if you got something that we can do to fix this.

(One solution might be to deploy Verdaccio instance in between.)

**Comment by mcollina** [comment]
The link this bug is being discussed is https://npm.community/t/error-unexpected-token-in-json-at-position/5671.
