### ISSUE TITLE
How to use `pattern` option in the schema ?

### ISSUE THREAD

**Issue by lagmanzaza** [fastify/fastify#1484]
## 💬 Questions and Help
How to use `pattern` option in the schema?
<img width="593" alt="screen shot 2562-02-26 at 00 01 19" src="https://user-images.githubusercontent.com/5283709/53354606-b6027e00-3959-11e9-8b8c-b050b3abbc29.png">

I try to do this but it doesn't work
### Please note that this issue tracker is not a help forum and this issue may be closed.

Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Comment by Eomm** [comment]
Hi, 
the problem is that you set the type of the property as `number` and the pattern keyword works only for type `string`.

This is a working example:
```js
{
  $id: 'test',
  type: 'object',
  properties: {
    postal: { type: 'string', pattern: '^[0-9]{5}$' }
  }
}
```

For more details, you can find further information [here](https://json-schema.org/understanding-json-schema/reference/string.html#pattern)

**Comment by lagmanzaza** [comment]
Thank you, sir.

I will remember that pattern must use with type String ^_^
