### ISSUE TITLE
Express compatibility

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1503]
## 🚀 Feature Proposal

From the next version of Fastify, I would love to decouple even more Express middlewares from the core framework.
The current solution is to integrate [Middie](https://github.com/fastify/middie) with Fastify and expose it via the `use` API.
I think we should design a new plugin that offers this functionality *(and at the same time remove the `use` API from core)*; technically is possible since Fastify offers everything we might need to achieve this goal.
Moreover, if we expose this functionality as a plugin, we could even improve the Express support, and apply many other modifications to the request object that we are currently not doing in core to avoid a performance hit.
Finally, we will remove the confusion generated by *hooks vs middlewares*.

## Motivation

- Discourage the use of Middlewares and encourage the use of our Hooks.
- Drop an API from core that does not need to be there, and increases the internal complexity.
- Improved Express compatibility.
- Performances++ if you don't need Express compatibility.

## Example
```js
const fastify = require('fastify')()
fastify
  .register(require('fastify-express'))
  .after(() => {
    fastify.use(require('express-stuff'))
  })
  .listen(3000)
```

What do you think?
What can we put inside this plugin to improve express compatibility?
Any feedback is welcome!

**Comment by jsumners** [comment]
Direct Express compatibility has never been a selling point for me. I see it as a detriment, really. I'm on board with removal.

**Comment by delvedor** [comment]
> Direct Express compatibility has never been a selling point for me.

Same for me, but it has helped a lot of people having a fast transition from Express to Fastify. This is still a great feature for us.
But if we want to improve it, we should extract it from core and build a more complete plugin.

**Comment by mcollina** [comment]
I’m on board with the move. I’m not convinced we will gain much in term of speed, but I think it would make things more flexible.

**Comment by delvedor** [comment]
I think we can start working on this even in Fastify v2.
The plan is to work on the `fastify-express` plugin and make it a dependency of Fastify v2, then in Fastify v3 we will remove it from core.
In this way we can road test it and be sure that is working as expected :)

**Comment by mcollina** [comment]
I think the best approach is to keep the module within this repo for v2, and move it to its own repo on v3.

**Comment by Ethan-Arrowood** [comment]
I like this idea a lot! Whomever starts making the changes I can help out with any TypeScript updates that need to be made

**Comment by ericrglass** [comment]
If anyone is interested, I have created the Fastify plugin [fastify-normalize-request-reply](https://github.com/ericrglass/fastify-normalize-request-reply) that has recently been updated to support Express middleware and prehandlers like Passport. I have also used this plugin with the [swagger-stats](http://swaggerstats.io/) and several other Express middleware. I have also put together a simple example project [fastify-passport-example](https://github.com/ericrglass/fastify-passport-example).

**Comment by delvedor** [comment]
I've opened https://github.com/fastify/fastify/pull/2004 and https://github.com/fastify/fastify/pull/2005 to move things forward in https://github.com/fastify/fastify-express/pull/1.

Once the two pr gets merged, `fastify-express` should be ready to go!
We should also create `fastify-middie`, to maintain the current behavior if someone needs it.

**Comment by delvedor** [comment]
I've opened https://github.com/fastify/middie/pull/36, which transforms Middie in a Fastify plugin to have the same functionality we were providing before.

**Comment by mcollina** [comment]
This is done in v3.0.0-rc.1 and following, closing.
