### ISSUE TITLE
Fastify uses different method than expected

### ISSUE THREAD

**Issue by Murbal** [fastify/fastify#1504]
Hello I have a problem. When I make a GET request everything is fine. But when I make a POST request afterwards and then make a GET again, it uses the POST handler instead of the GET one.
How can I solve this?
I am using the project structure given by fastify cli
The code:
```js
//services/users/index.js
const db = require('../../db/db.users');

module.exports = async function (fastify, opts) {
	fastify.get('/users/:id', async (req, rep) => {
		return await db.getUserById(req.params.id);
	});
	fastify.post('/users', async (req, rep) => {
		return await db.createUser(req.body);
	});
};
```

**Comment by mcollina** [comment]
Can you please provide a full example?

**Comment by Murbal** [comment]
Ok it was related to knex. I only initialized knex once and used that for all db actions. Solved it by initializing knex everytime a db action was needed.
