### ISSUE TITLE
Fastify v2.0.0 fails on citgm

### ISSUE THREAD

**Issue by BridgeAR** [fastify/fastify#1508]
Fastify v2.0.0 constantly fails on CITGM (at least in Node.js 11 and 12-pre). The tests pass locally, so I am a bit surprised about the failures. It would be great if you could have a look: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1758/nodes=ppcle-ubuntu1404/testReport/junit/(root)/citgm/fastify_v2_0_0/

**Comment by mcollina** [comment]
That was solved in https://github.com/fastify/fastify/pull/1493. We will issue a new release tomorrow to address it, good catch!

**Comment by delvedor** [comment]
[`v2.0.1`](https://github.com/fastify/fastify/releases/tag/v2.0.1) has just been released :)
Thank, you for letting us know!!
