### ISSUE TITLE
Missing information on 'version' attribute in route declarations

### ISSUE THREAD

**Issue by kokujin** [fastify/fastify#1518]
Can some explain the use of the 'version' attribute on route declarations? The link to the documentation is invalid. Thanks.

`https://github.com/fastify/fastify/blob/versioned-routes/docs/Routes.md#version`

**Comment by Eomm** [comment]
Hi, you can find that info [here](https://github.com/fastify/fastify/blob/master/docs/Routes.md#version)

Where did you find that link? 
If it is on the site we need to fix it 👍

**Comment by delvedor** [comment]
Hello! Thank you for reporting!
Fixed in https://github.com/fastify/fastify/commit/124522f74e6152da53e54641c2d7019d5d3bf4a4 :)
