### ISSUE TITLE
http2 support for lambda

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify#1519]
We are using fastify for AWS Lambda, Google App Engine, Zeit Now v1, cloud applications. All of these are secured via https.

However, there are no certificates. The fastify documentation states that plain text http2 is not supported by browsers.

Is it not possible to enable http2 without the https settings where it is assumed that all traffic is http2?

Is it possible to have a feature for http2 in lambda deployments?

**Comment by mcollina** [comment]
AWS Lambda, Google App Engine, Zeit Now do not support HTTP2. You cannot use it there.
