### ISSUE TITLE
Improve typings for http objects such as Headers

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1525]
Ref: https://twitter.com/garybernhardt/status/1104893610468601856?s=20

Some of our types are currently relying on an `any` default when they should be explicitly typed. An easy fix will be to use the `http.IncomingHttpHeaders` and `http.OutgoingHttpHeaders` interfaces from `@types/node` in place of our `DefaultHeaders` interface. More can be done for the other `Default` types.

**Comment by mcollina** [comment]
I think providing a workflow that uses https://www.npmjs.com/package/json-schema-to-typescript would be fantastic.

**Comment by Ethan-Arrowood** [comment]
Could you share with me what you believe this workflow would be like?

**Comment by Ethan-Arrowood** [comment]
What I have in my mind right now is this:
- User rights schemas in JSON files
- They have `json-schema-to-typescript` auto-compiling their `.json` into `.d.ts` files
- Their `.ts` server code imports the `.json` schema to be used in the `schema` property of our `route` methods. It also imports the type declarations from the generated `.d.ts` files so that the user can pass the schema to the `FastifyRequest` interface and thus typing the `request` (and additionally, the `response`) arguments in the `handler` method property of our `route` methods.

That last part is where I think the magic will happen

**Comment by mcollina** [comment]
+1 with the approach. Best bonus points would be to use something like https://github.com/fastify/fluent-schema and have it automatic spitting out types information.

**Comment by Ethan-Arrowood** [comment]
Sharing this article: https://lorefnon.tech/2018/03/25/typescript-and-validations-at-runtime-boundaries/

**Comment by mcollina** [comment]
This is also very relevant: https://github.com/gcanti/io-ts/issues/197.

**Comment by evanshortiss** [comment]
Also, some generics are currently supported for this, but it's a long list, so not an ideal experience - https://github.com/fastify/fastify/blob/master/fastify.d.ts#L102

**Comment by fuafa** [comment]
I think it would be great if this feature is provided by type inference rather than creating another type definition file, as the json schema already has all the type information.
