### ISSUE TITLE
basePath deprecation

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1529]
In v1 we had the `basePath` key in the Fastify object, that has been changed to `prefix` in https://github.com/fastify/fastify/pull/1183.
Back then we added a deprecation warning, but we didn't remove it in v2.
Do you all agree that we can remove the following snippet in a patch release for v2?
https://github.com/fastify/fastify/blob/ed4af597f3a98065781f2d429c7a853fa5596711/fastify.js#L193-L198

**Comment by mcollina** [comment]
It does not hurt anybody. Let’s cut a next branch and do it there.

**Comment by delvedor** [comment]
I've added it to the v3 milestone ;)

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1750.
