### ISSUE TITLE
Using shared schema with anyOf

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1535]
## 🐛 Bug Report

The docs state about `replace-way` shared schemas that: `You can use the shared schema everywhere`. So I wanted to use a shared schema in an `anyOf` property, but unfortunately it does not work.

## To Reproduce

```js
fastify.addSchema({
  $id: 'shared',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})
fastify.addSchema({
  $id: 'myschema',
  anyOf: [{ type: 'null' }, 'shared#']
})
```

## Expected behavior

I expected the `shared#` schema to be replaced with the actual schema.

## Your Environment

- *node version*: 10.15.1
- *fastify version*: 1.12.1
- *os*: Linux

**Comment by Eomm** [comment]
Hi,
the problem is the `null` string in the [anyOf](https://json-schema.org/understanding-json-schema/reference/combining.html?highlight=anyof#anyof) array.

You should put a `{type: 'null'}`

This is a working example:

```js
const fastify = require('fastify')({ logger: true })

fastify.addSchema({
  $id: 'shared',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})
fastify.addSchema({
  $id: 'myschema',
  anyOf: [{ type: 'null' }, 'shared#']
})

fastify.post('/', { schema: { body: 'myschema#' } }, (_, reply) => { reply.send(fastify.getSchemas()) })

fastify.listen(3000)
```

**Comment by sarneeh** [comment]
@Eomm I'm sorry, it was an error in my example. I tried it with proper `anyOf` and it doesn't work there. Try to `reply.send({ hello: 'world' })` in your example.

**Comment by Eomm** [comment]
The replay payload isn't involved, anyway, it is still working for me.
I have tried the version you write `git checkout tags/v1.12.1`, it is the correct version?
Because maybe you need only to update. We follow the semver so it is safe to update your fastify lib to `1.14.3`.

Could you provide a complete example via gist that reproduces the problem and the complete stacktrace?

**Comment by sarneeh** [comment]
@Eomm Yeah, gimme a minute, I found out that in this fast example it works properly but in my app it doesn't, need to find out what is the difference there. Sorry for that.

**Comment by sarneeh** [comment]
@Eomm Nevermind, I've just found that I had a `{type: 'number'}`, was passing a `"450.00"` string, and had type coercion turned off. Sorry for taking your time and thanks for trying to help! :sweat_smile:
