### ISSUE TITLE
Test failures on CITGM

### ISSUE THREAD

**Issue by BridgeAR** [fastify/fastify#1537]
Currently a few fastify tests fail on CITGM. They do not seem to be related to the latest changes in Node.js core, so I guess they might be flaky tests in fastify? It would be great if that could be verified right quick as I am planning on releasing v11.12.0 in a few hours.

See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1766/nodes=osx1011/testReport/junit/(root)/citgm/fastify_v2_0_1/ and https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1766/nodes=win-vs2017/testReport/junit/(root)/citgm/fastify_v2_0_1/

**Comment by BridgeAR** [comment]
Using version v2.0.1

**Comment by delvedor** [comment]
Thank you for reporting!
We are checking :)

**Comment by mcollina** [comment]
It’s either flaky on our side (but I can’t reproduce), or there is something flaky on how we use http in node core. Some order/event timing might be different under certain conditions.

You can release (you are not breaking us).

**Comment by BridgeAR** [comment]
@mcollina thanks a lot for looking into it!

**Comment by mcollina** [comment]
Reopen, we still need to make that test less flaky.

**Comment by delvedor** [comment]
That test is quite old, probably is flaky in v1 as well.
