### ISSUE TITLE
Reply object methods missing from documentation

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1541]
The Fastify Reply documentation page is misleading. The list of methods at the start of the page does not contain `.removeHeader` but that method is referenced in the body of the page. Similarly the order of the methods in the header are not in order while the rest of the page is. For readability sake everything should be in order and all implemented methods should be documented correctly.

**Comment by delvedor** [comment]
This should be fixed now, if not, feel free to reopen!
