### ISSUE TITLE
Update Server#logger to discuss custom logger option

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1542]
The [Server#logger](https://www.fastify.io/docs/latest/Server/#logger) doc section lists 3 options for the logger server option. I believe the `pinoInstance` option should be expanded (or a new, 4th option should be added) to tell the user they can define or use their own custom logger as long as it follows the rules set forth by our code (I believe it needs a certain list of methods and an optional serializer list for `req`, `res`, and `err`).

**Comment by mcollina** [comment]
docs are managed in the main repo, moving.
