### ISSUE TITLE
Missing POST data using onRequest hook

### ISSUE THREAD

**Issue by Zaseth** [fastify/fastify#1546]
Hello.

I'm having an issue regarding POST data using onRequest hook. I expected the onRequest hook to also return the POST data, but there's no POST data. This may be an issue with `fastify-formbody`, because `req.body` returns "null".

This is my code:

```javascript
const request = require("request-promise").defaults({ jar: true })
const app = require("fastify")()

app.register(require("fastify-formbody"))
app.addHook("onRequest", async (req, res) => {
  const { url, method } = req.raw

  console.log(req.body) // null

  if (url.endsWith(".aspx") && method === "POST") {
    const aspx = url.substr(1).split(".")[0]
    const hooks = ["SDV", "SDCA", "SDFP", "SDCP", "SDS", "SDQ", "SDP"]

    if (hooks.includes(aspx)) {
      try {
        await request.post({ url: `http://maidmarian.com/${aspx}.aspx`, form: req.body }, (err, data) => {
          res.send(data.body)
        })
      } catch (error) {
        Promise.reject(error)
      }
    }
  }
})

const start = async () => {
  try {
    await app.listen(80)

    app.ready().then(() => {
      console.log("mmProxyHTTP listening")
    })
  } catch (error) {
    Promise.reject(error)
  }
}

start()
```

**Comment by jsumners** [comment]
`onRequest` happens before body parsing. See https://www.fastify.io/docs/latest/Lifecycle/

**Comment by Zaseth** [comment]
Oh well that makes sense. Is there anything I can do to parse the POST data?

**Comment by Zaseth** [comment]
![image](https://user-images.githubusercontent.com/24899039/54548949-45bfa900-49a9-11e9-9707-b5795c3b4b02.png)

Adding the above code and commenting `app.register(require("fastify-formbody"))` seems to do the trick, but this defeats the use of fastify-formbody...

**Comment by jsumners** [comment]
That's basically the code for the plugin -- https://github.com/fastify/fastify-formbody/blob/caba6c3c6a35daa30797dece0dc3083d1f981cc8/formbody.js#L13-L17

**Comment by Zaseth** [comment]
Well how can I make the parser return the data to the hook?

**Comment by jsumners** [comment]
I do not have time to dig into `addContentTypeParser` to determine when it really runs in the lifecycle. If you are unable to trace it down, maybe another @fastify/fastify maintainer will chime in when they are able.

**Comment by Zaseth** [comment]
I can really use some help with this as this is just really unpractical..

**Comment by mcollina** [comment]
It’s not really clear what you are trying to accomplish. Have you tried using a preHandler hook?

**Comment by Zaseth** [comment]
I just want to be able to capture the POST data in the onRequest hook, but I don't know how.

**Comment by mcollina** [comment]
The way we recommend to do this is to use an hook that happens after parsing the body: preHandler. Why does that not work for you?

**Comment by Zaseth** [comment]
I haven't tried that yet, but that should work then! I'll take a look at it tomorrow and if it worked for me then I'll close this issue. I was just confused about it not parsing body data.

**Comment by Zaseth** [comment]
Using `preHandler` fixed my issue!
