### ISSUE TITLE
Can't access req.raw in logger serializer function

### ISSUE THREAD

**Issue by lynxtaa** [fastify/fastify#1548]
Can't access req.raw in logger serializer function

## To Reproduce

Paste your code here:

```js
const fastify = require('fastify')({
  logger: {
    serializers: {
      req: req => ({ raw: req.raw }),
    },
  },
})

fastify.use((req, res, next) => {
  req.test = 'TEST'
  next()
})

fastify.get('/', req => Promise.resolve(({ test: req.raw.test })))

fastify.listen(7000)
```
I assume it's because logging happens before running middleware? Is there a way to use serializer for logging  fields decorated in middleware?

## Your Environment

- *node version*: 11.12.0
- *fastify version*: >=2.1.0
- *os*: Windows, Linux

**Comment by liveevil** [comment]
Request body and parameters are also not accessible. Serializer options only able to return headers, url and method from the request.

**Comment by mcollina** [comment]
The request passed to the serializer is node.js core, it is _already_ `req.raw`.

> Is there a way to use serializer for logging fields decorated in middleware?

You might want to create another child logger within a hook with your properties.

> Request body and parameters are also not accessible. Serializer options only able to return headers, url and method from the request.

Logging the request body is _extremely expensive_ and it exposes you to a DoS attack. As such, log it manually if you need so.

---

@fastify/fastify  I think we should change our serializers in v3 and pass down our objects and not the node.js core ones. There is nothing that prevents us to do so.. and it's just a piece we forgot to update in v1 and v2. Wdyt?

**Comment by lynxtaa** [comment]
Child logger approach sounds fine. Thank you.

**Comment by delvedor** [comment]
> I think we should change our serializers in v3 and pass down our objects and not the node.js core ones. There is nothing that prevents us to do so.. and it's just a piece we forgot to update in v1 and v2. Wdyt?

100% agree! I'll open an issue just for this.
