### ISSUE TITLE
Logger: serialize Fastify objects instead of Node.js

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1551]
Since Fastify v2 we can access our `Request` and `Reply` objects anywhere, it could be a useful enhancement *(unfortunately it is a breaking change)* update our logger serializers to handle our objects instead of Node.js core ones.

Thoughts?

Related: https://github.com/fastify/fastify/issues/1548
/cc @fastify/fastify

**Comment by Ethan-Arrowood** [comment]
How will this work with our idea of defining custom Request and Reply objects?

**Comment by delvedor** [comment]
I don't know what is the status of that in Node.js core, maybe @mcollina knows more.
In our case, it does not change much, since you can pass a custom serializer in the options object.
Here we are talking about this line:
https://github.com/fastify/fastify/blob/9b2a54cc11e23277a098feaa595a071e7f515fa8/fastify.js#L295

Since we have standardized the use of our Request/Reply object everywhere in our codebase, we can pass our objects directly to the logger.

**Comment by jsumners** [comment]
Sounds fine to me. But I recommend looking at `pino-std-serializers` to learn about edge cases in logging these sort of things. A lot of data can unintentionally be logged.

**Comment by delvedor** [comment]
Closed in #2017.
