### ISSUE TITLE
Server.close() mutates used shared schemas

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1553]
## 🐛 Bug Report

I've encountered this super weird bug. It seems that if you use a shared schema in an endpoint schema, then shut down the server, the shared schema will get mutated somehow :man_shrugging:  

## To Reproduce

```js
const t = require("tap");
const fastify = require("fastify");

const sharedSchema = {
  $id: "schema",
  type: "object",
  properties: {
    message: { type: "string" }
  }
};
const endpointSchema = {
  response: {
    "2xx": "schema#" // not referencing the shared schema does resolve the issue
  }
};

const setup = () => {
  const server = fastify();
  server.addSchema(sharedSchema);
  server.get("/", { schema: endpointSchema }, async (request, reply) => {
    reply.send();
  });
  return server;
};

t.test("$id", async t => {
  const server = await setup();
  t.ok(sharedSchema.$id); // passes
  await server.close();
  t.ok(sharedSchema.$id); // fails
});
```

I need to admit that it took a while to find out what causes the issue. This is a complete mystery to me. Why does this happen?

## Expected behavior

I expected the schemas not to be mutated because... who on earth would expect that? :smile: I see that most examples in the docs imply creating the schema explicitly in the parameter (not storing it in a variable), but as I'm starting to have a bunch of shared schemas I'd rather move them to separate files for less code clutter.

## Your Environment

- *node version*: v10.15.1
- *fastify version*: 1.14.1
- *os*: Linux

**Comment by Eomm** [comment]
Hi,

> Why does this happen?

Because the schema passed is not cloned and, in the startup phase (ready, listen or close), we manage that object:

https://github.com/fastify/fastify/blob/91d25ad1e901df1b33c3d4728c6e21a83f6914bb/lib/schemas.js#L92

Cloning the input object here:

https://github.com/fastify/fastify/blob/91d25ad1e901df1b33c3d4728c6e21a83f6914bb/lib/schemas.js#L9

Shouldn't break anything (there aren't stream or buffer, but only object with strings or array of strings) 
Would you like to give it a try and send a PR?

**Comment by Eomm** [comment]
Reopen until the backport will be done ✌

**Comment by sarneeh** [comment]
@Eomm I'm sorry that I didn't reply but I'm very hard on time right now :cry: Thank you very much for taking this!

**Comment by sarneeh** [comment]
@Eomm I've updated to the latest version with this fix and unfortunately this still can be pretty frustrating to use (like any API that mutates your data).

As the shared-schema API is encapsulated just like the plugins logic - there's really no way to share a schema from with another plugin other than `require`-ing it from each other. Unfortunately, this implicates another issue, because this fix clones the root schema object, but does not clone it `deeply`. Now, when you're reusing schemas by `require`-ing them from one another, you still have the reference of the `require`-d object, which ends up being broken because the `$id` property is being deleted (and can't be used with `addSchema()` in the owning plugin).

Have you any idea for a solution to this problem? (other than deep-cloning the objects manually on Fastify-user's side, as I still think that external libraries should most certainly not mutate acquired data).

**Comment by mcollina** [comment]
Can you open a new issue with a way to reproduce this? We _are_ be deep cloning this, so maybe there is another latent issue.

**Comment by sarneeh** [comment]
@mcollina Sure, here it is: #1635
