### ISSUE TITLE
Required properties in querystring schema validation.

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify#1554]
Using a schema to validate querystring properties works well on the type like so.

```
  fastify.route({
    method: 'GET',
    url: '/my/route',
    schema: {
      querystring: {
        locale: { type: 'string' },
        table: { type: 'integer' }
      }
    },
...
```

Which returns a 400 with the correct message when a string instead of an integer is provided.

{"statusCode":400,"error":"Bad Request","message":"querystring.table should be integer"}

I would like to propose a feature where an error is returned if a property is defined in the schema but not provided with the querystring on the request.

**Comment by dbauszus-glx** [comment]
I found an answer in [this medium article](https://mikulskibartosz.name/query-string-validation-in-fastify-80c643043732) which recommends to define the querystring as an object like so:

```
      querystring: {
        type: 'object',
        properties: {
          locale: {
            type: 'string'
          },
          table: {
            type: 'string'
          },
        },
        required: ['locale', 'table']
      }
```

**Comment by Eomm** [comment]
Hi, I would add also this resource: https://www.jsonschemavalidator.net/
that is really helpful in these cases if there are some JSON Schema validation problems.

If you put there your schemas, you can see in real time if a `body` (or a `querystring` transformed in a json object) is valid or have a list of errors.
