### ISSUE TITLE
http2 upload file from server

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1563]
hello, its possible create dynamic links for download file?

this is my server

```javascript
const fastify = require('fastify')({
    logger: false,
    http2: true,
    https: {
        key: fs.readFileSync(path.join(serverDirectory, '/certificate/', 'key.pem')),
        cert: fs.readFileSync(path.join(serverDirectory, '/certificate/', 'cert.pem'))
    }
});

fastify.listen(3000, (err, address) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
})
```

i need next, pseudo example

```javascript
fastify.get('/download', (req, reply) => {
    searching file used special parametrs on input, and upload a file
    reply.sendFile('file')
})
```

i did not found example...

on express i found example:

Express has a helper for this to make life easier.
```javascript
app.get('/download', function(req, res){
  var file = __dirname + '/upload-folder/dramaticpenguin.MOV';
  res.download(file); // Set disposition and send it.
});
```

**Comment by Eomm** [comment]
Hi, I checked on our [Ecosystem](https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md) but it seems that there isn't a utility already in place for this use case.

I think that this is a good idea to build a plugin that adds a [`decorateReply`](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md)!

**Comment by MetCoder95** [comment]
Stills open or needed, I can spend time on it :)

**Comment by MetCoder95** [comment]
I'm working on the plugin, will be nice if you can take a look before merging :)
This is the [PR](https://github.com/MetCoder95/fastify-download/pull/1)
Please let me know your thoughts about it
