### ISSUE TITLE
Allow remove route

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#158]
Maybe an unregister method should be implemented.
Thoughts?

**Comment by mcollina** [comment]
I'm -1 on this. What would be the use case?

**Comment by allevo** [comment]
Thinking at a webserver that exposes the API depending from a configuration file. And the configuration file changes after a while. Maybe you want that the changes are reflected to the API without restarting the whole server (it could be time consumer)

Netflix for example does (or did) this thing (https://www.infoq.com/news/2014/12/expressjs-burned-netflix)

**Comment by mcollina** [comment]
Just restart the server. It's cheap and quick. I'm not exactly sure what Netflix was doing at that point, but they are not even talking about removing routes there. Removing routes and plugins would be extremely complex, and I don't think it's worth for the majority of users, and I prefer for us to focus on other features (serializations, 404 and 5xx etc).

**Comment by delvedor** [comment]
I agree with @mcollina.

The only thing that would be nice to have (but at the moment is definitely not needed), is a *reboot* functionality in `avvio`.
