### ISSUE TITLE
printRoutes showing inaccurate result

### ISSUE THREAD

**Issue by anonimusprogramus** [fastify/fastify#1581]
## To Reproduce

```js
fastify.get('/', () => {})
fastify.get('/hello', () => {})
fastify.get('/hello/world', () => {})
fastify.get('/hi/universe', () => {})

fastify.ready(() => {
	console.log(fastify.printRoutes())
})
```

## Environment

- *node version*: 10.15.1
- *fastify version*: 2.2.0
- *os*: Linux

## Result
![Screenshot_20190407_184252](https://user-images.githubusercontent.com/7464749/55683073-c13bc700-5965-11e9-8f64-35303ae5126c.png)

**Comment by jsumners** [comment]
Alternative solution:

```js
server.register(require('fastify-routes'))
server.ready(err => {
  if (err) throw err

  const routes = {}
  server.routes.forEach((val, key) => {
    routes[key] = Object.keys(val).map(k => k.toUpperCase())
  })
  server.log.debug(routes, 'registered routes')
})

**Comment by Eomm** [comment]
Really nice bug! Also v1 is affected.

It seems that if there is an endpoint that start with the same first letter of previous one, the output string is broken.
```js
fastify.get('/', () => {})
fastify.get('/zello', () => {})
fastify.get('/zello/world', () => {})
fastify.get('/zfoo/universe', () => {})

└── / (GET)
    └── z
        ├── ello (GET)
        │   └── /world (GET)
        └── foo/universe (GET)
```

**Comment by mcollina** [comment]
This is working exactly as expected. It shows the prefix trie as it is. We can change that, but that’s currently correct.

**Comment by Eomm** [comment]
Ok, so this issue is releated to #703 

We will work on it soon 👍

**Comment by delvedor** [comment]
Hello! This is definitely not a bug ;)
It shows the internal radix tree that [`find-my-way`](https://github.com/delvedor/find-my-way) creates in memory :)
