### ISSUE TITLE
feature : centralize connectors in fastify / enhancement for plugin

### ISSUE THREAD

**Issue by matth-c3** [fastify/fastify#1583]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

This is not really a feature but more an enhancement . 
Would it be possible to create a new variable call connectors as an object. The role of that variable/object would be to hold connections for the plugins like redis, mongodb, socket.io ... 

**The target is not to have fastify doing any work or verification on the connectors**, just to provide a way to share the connectors from the main object

## Motivation

The developer would not need to declare it in the plugin as it would become accessible globally from the `connectors` object available in fastify. Also the user would not need to declare it in each plugin if those require a connection.

## Example

When declaring a new instance fastify  : 

```
const fast = require('fastify')({
  connectors : {
     redis : ....,
     mongo : ...,
     socket.io : ...
  }
})
```

Thanks.

**Comment by jsumners** [comment]
The decorators feature should cover this.

**Comment by delvedor** [comment]
I agree with @jsumners you can do that already :)

```js
const fastify = require('fastify')()
fastify.decorate('connectors', {
  redis: ...,
  mongo: ...,
  socketio: ...
})
```
