### ISSUE TITLE
genReqId takes precedence over requestIdHeader

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1584]
The documentation states:

https://github.com/fastify/fastify/blob/68241662e2328127cf571d46194b63da20ea55bc/docs/Logging.md#logging-request-id
> By default fastify adds an id to every request for easier tracking. If the "request-id" header is present its value is used, otherwise a new incremental id is generated. See Fastify Factory requestIdHeader and Fastify Factory genReqId for customization options.

But the `genReqId` docs state:

https://github.com/fastify/fastify/blob/68241662e2328127cf571d46194b63da20ea55bc/docs/Server.md#genreqid
> Note: genReqId will be called even when the 'request-id' header is supplied. It is possible to default to that value if provided before generating a new value, as per the example above.

I think this is a conflict. It is reasonable to think that when one supplies _both_ `requestIdHeader` and `genReqId` that the `requestIdHeader` will take precedence and `genReqId` will only be invoked if the header is not found.

For example, the following block should _never_ invoke the provided `genReqId` function:

```js
'use strict';

const crypto = require('crypto');
const got = require('got');

const fastify = require('fastify')({
  logger: { level: 'debug' },
  requestIdHeader: 'x-trace-id',
  genReqId() {
    return crypto.randomBytes(8).toString('hex');
  }
});

fastify.get('/foo', (req, res) => res.send(req.headers));

fastify.listen(0, async err => {
  if (err) throw err;

  const address = fastify.server.address();
  console.log(address);

  const response = await got(`http://${address.address}:${address.port}/foo`, {
    headers: { 'x-trace-id': 'abc123' }
  });
  console.log(`response: ` + response.body);

  fastify.close();
});
```

But if we look at the output, we can see that it does:

```
{"level":30,"time":1554731999451,"pid":6777,"hostname":"mini2018","reqId":"37986ea61a8840a2","req":{"method":"GET","url":"/foo","hostname":"127.0.0.1:61345","remoteAddress":"127.0.0.1","remotePort":61346},"msg":"incoming request","v":1}
{"level":30,"time":1554731999453,"pid":6777,"hostname":"mini2018","reqId":"37986ea61a8840a2","res":{"statusCode":200},"responseTime":1.7521930001676083,"msg":"request completed","v":1}

response: {"user-agent":"got/9.6.0 (https://github.com/sindresorhus/got)","x-trace-id":"abc123","accept-encoding":"gzip, deflate","host":"127.0.0.1:61345","connection":"close"}
```

**Comment by mcollina** [comment]
I thought https://github.com/fastify/fastify/pull/1566 was solving this in the docs.

However we can also change the implementation, as you can see in  https://github.com/fastify/fastify/blob/68241662e2328127cf571d46194b63da20ea55bc/lib/reqIdGenFactory.js#L6-L8 essentially `requestIdHeader` is useless if `genReqId` is specified.

**Comment by jsumners** [comment]
I think the implementation should be changed. If `requestIdHeader` is specified the Fastify itself should decide if `genReqId` should be invoked instead of leaving that up to the `genReqId` implementation.

**Comment by mcollina** [comment]
I'm ok with that. PR?

**Comment by jsumners** [comment]
I’ll try to get to it soonish.

**Comment by jsumners** [comment]
I have also determined that we need the ability to specify what the property name is when logging. For example, currently we log `"reqId":"<output of genReqId>"`. We should have the ability to indicate that the log should be `"<some other name>":"<output of genReqId>"`. Are we opposed to both things happening in the same PR?

**Comment by mcollina** [comment]
go for it!

Il giorno mer 10 apr 2019 alle 21:52 James Sumners <notifications@github.com>
ha scritto:

**Comment by jsumners** [comment]
I see that @Eomm considers the resolution to the original topic as an "enhancement". I see it as a bug fix because it is the generally expected behavior given the options. What say you all?

**Comment by mcollina** [comment]
It's a bug. We can fix it both ways, either by making the doc comply, or by making the code comply.
