### ISSUE TITLE
[Schema]: Custom validation error message (maybe code too)

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify#1586]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

I want to get custom message (maybe custom status codes too) when validation fails.

## Motivation

I built backend using fastify and works very very best, i am trying to validation error responses in my language too :)

### Fastify schema example
```javascript
const schema = {
  body: {
    type: 'object',
    properties: {
      name: {
          type: 'string',
          errorMessage: {
            mismatch: 'The {name} property is not a string',
            missing: 'The {name} property is missing'
          }
      }
    },
    required: ['name']
  }
}
```

### Request example
```javascript
fastify.inject({
    method: 'POST',
    payload: {
      name: 123
    },
    url: '/'
  }, (err, res) => {
    t.error(err)
    t.deepEqual(JSON.parse(res.payload), {
      statusCode: 500,
      error: 'Unprocessable Entity',
      message: 'The {name} property is not a string'
    })
    t.strictEqual(res.statusCode, 500)
  })

fastify.inject({
    method: 'POST',
    payload: {
      hello: 'world'
    },
    url: '/'
  }, (err, res) => {
    t.error(err)
    t.deepEqual(JSON.parse(res.payload), {
      statusCode: 500,
      error: 'Unprocessable Entity',
      message: 'The {name} property is missing'
    })
    t.strictEqual(res.statusCode, 500)
  })
```

**Comment by mcollina** [comment]
I think we would need to integrate with https://github.com/epoberezkin/ajv-i18n.

**Comment by dalisoft** [comment]
Yes, you are right, but, sometimes i need my own message, not only i18n converted

**Comment by mcollina** [comment]
https://github.com/epoberezkin/ajv-errors would get the trick done?

**Comment by dalisoft** [comment]
Thanks a lot, it is really that what i looking.

We need make documentation these. I see fastify has all utility, but it's ecosystem and/or documentation not enough to reach express community. I worked with express more than 4 years and i am switched to fastify because of async/await + speed.

Thanks again.
You can close this issue or keep open. I solve my issue by using ajv-errors

**Comment by mcollina** [comment]
Would you like to add some docs on this? I think it would be really handy.

**Comment by Eomm** [comment]
> I see fastify has all utility, but it's ecosystem and/or documentation not enough to reach express community

I agree with this, and we need your (and all the community) help to fix this 💪

**Comment by pdrgds** [comment]
> I think we would need to integrate with https://github.com/epoberezkin/ajv-i18n.

Is it ok if I send a PR to do this? I need translated error messages for a project I'm on.

**Comment by Eomm** [comment]
@pdrgds Take a look [here](https://github.com/fastify/example) first, you should find an example about how to customize error messages and maybe it is worth to extend that example and refer the example in docs

**Comment by pdrgds** [comment]
ajv-errors is made to create custom messages for each schema.

ajv-18n takes an array of ajv error messages and replaces them with translated versions. This should be done before returning at line 71 of lib/validation.js

**Comment by Eomm** [comment]
If you have already in mind how to solve feel free to open a PR

Consider that the validation function can be customized, so edit that part must keep in mind this aspect

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks !

**Comment by mcollina** [comment]
I'm not sure what you are asking for. This issues is closed. Please open a new one and/or send a PR.
Thanks
