### ISSUE TITLE
Enable to set all hooks (including .use middlewares) in route()

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1587]
## 🚀 Feature Proposal

Currently we do not expose an API to add `onRequest` and route specific middlewares, however our codebase can definitely support them. Adding them would ensure an higher level of flexibility combined with the new `onRoute`  hook.

Missing things:

* [x] `onRequest` - done in https://github.com/fastify/fastify/pull/1594
* [ ] `onSend`
* [ ] `onError`
* [x] `onResponse`
* [ ] middlewares

## Example

Please provide an example for how this feature would be used.

```js
app.route({
  method: 'GET',
  async onRoute (req, reply) { },
  middlewares: [function (req, res, next) {
    next()
  }]
}, async (req, reply) => {})
```

**Comment by jsumners** [comment]
Would they be called middlewares? That’s a term we use to reference Express modules that we support.

**Comment by mcollina** [comment]
No I mean... connect middlewares.

**Comment by mcollina** [comment]
I've updated the example

**Comment by taibahayean** [comment]
I've updated the example

**Comment by jsumners** [comment]
Do they get invoked before the handler? Are they before the `preHandler` or after?

**Comment by mcollina** [comment]
after `onRequest`, before `preParsing`, like https://www.fastify.io/docs/latest/Lifecycle/.

**Comment by mcollina** [comment]
They are the _same_ thing, it's just converting:

```js
app.register(async (app) => {
  app.use((req, res, next) => next())

 app.get( ... )
})
```

to 

```js
app.route({
  method: 'GET',
  middlewares: [function (req, res, next) {
    next()
  }]
}, async (req, reply) => {})
```

**Comment by nwoltman** [comment]
Sounds like a good idea to me 👍

**Comment by taibahayean** [comment]
বুধ, ১০ এপ্রিল, ২০১৯ ৮:৪৯ pm তারিখে Nathan Woltman <notifications@github.com>
লিখেছেন:

**Comment by delvedor** [comment]
https://github.com/fastify/fastify/pull/2005 will fix this one thanks to the for loop that we will use behind the scenes.
It will not apply for middlewares tho.
