### ISSUE TITLE
Serve static file (dev only)

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#159]
In dev environment, I'd like not to have nginx (for example) for serving static files.
Can we thinking to create a plugin that integrates [serve-static](https://www.npmjs.com/package/serve-static) ?

Other integration suggestions are welcomed!

**Comment by delvedor** [comment]
You can easily do it by using `serve-static` as a middleware, like shown [here](https://github.com/fastify/fastify/blob/master/docs/Middlewares.md#restrict-middleware-execution-to-a-certain-paths) :)

**Comment by mcollina** [comment]
I would really prefer to have a fastify-static option, or something very similar so we can encapsulate it with prefix

**Comment by mcollina** [comment]
We can't wrap serve-static, because it is a middleware, and we need a plugin and something specific to fastify.
We could lift some code anyway.

**Comment by delvedor** [comment]
Something like [point-of-view](https://github.com/fastify/point-of-view) could do the job, probably we just need to adapt its logic.

**Comment by allevo** [comment]
[Initial implementation](https://github.com/fastify/fastify-static/tree/init) on branch "init"

**Comment by mcollina** [comment]
I think we should use https://github.com/pillarjs/send to support conditional headers, etc.

**Comment by allevo** [comment]
No cache is available there.
Should we use it?

**Comment by mcollina** [comment]
We should support HTTP caching, but do no cache of content.

**Comment by allevo** [comment]
Code update for using `send` package
Move this discussion to [that repo](https://github.com/fastify/fastify-static)
