### ISSUE TITLE
set status code to 302 on res.redirect by default.

### ISSUE THREAD

**Issue by ToonvanStrijp** [fastify/fastify#1592]
## 🚀 Feature Proposal

Right now fastify `redirect` method set the status code only to `302` when it's not set before. I would like to have this changed and make it act like `express` does. What express does is: set the status code to `302` when `redirect` is called. You can still sent an other code by providing it in the redirect like so: `res.redirect(404, '/login')`.

## Motivation

Right now I'm using the [nestjs](https://github.com/nestjs/nest) framework. Nest currently supports multiple routing libraries such as `express` and `fastify`. `nestjs` is setting the http status code default to `200` or `201` depending on the type of request (`GET`, `POST`). When I'm redirecting the request with `redirect` it returns it with a status of `200` instead of `302` this forms an issue because the browser won't redirect.

I hope we could change `fastify` to set the status to `302` by default when `redirect` is called. You could still sent a custom code by putting it like: `res.redirect(404, '/not-found')`.

**Comment by mcollina** [comment]
This seems a good idea and an oversight from our part. Would you like to send a PR?

**Comment by ToonvanStrijp** [comment]
@mcollina sure no problem. Will do it today or tomorrow ;)

**Comment by mcollina** [comment]
I may have misunderstood this feature request, it might not land, or maybe make it into Fastify@3.

**Comment by delvedor** [comment]
Let us start discussing this again, otherwise, we will not be able to make it land in v3 if we decide to adopt it.


Related: https://github.com/fastify/fastify/issues/1049 https://github.com/fastify/fastify/pull/1051 https://github.com/fastify/fastify/pull/1595

**Comment by mcollina** [comment]
I think we should do this.

**Comment by ToonvanStrijp** [comment]
I think we should do it as well.

**Comment by jsumners** [comment]
My comment at https://github.com/fastify/fastify/pull/1595#discussion_r275134527 still stands.

**Comment by GlenTiki** [comment]
Should this be treated as a documentation issue, or should the breaking change be made? It _appears_ like this is a contentious issue, as I find @jsumners comment is appropriate and yet the underlying argument to change the code to 302 is also fair.

**Comment by ToonvanStrijp** [comment]
@GlenTiki How I see it, if a developer comes from express to fastify this can be an issue that he would end up at. But we can either fix it by adding some clear documentation, or make a breaking change and do it the same as express is doing it. :)

**Comment by jsumners** [comment]
So if I do:

```js
reply.status(303)
// proceed through the request chain to some ultimate handler that does
reply.redirect('/foo')
```

Your assertion is that the result should be?:

```
HTTP/1.1 301 Moved Permanently
Location: /foo
```

When what I really said to do is:

```
HTTP/1.1 303 See Other
Location: /foo
```

**Comment by ToonvanStrijp** [comment]
@jsumners yes indeed. The code above can cause a situation where the developer doesn't know here the 303 status was set. So the solution I'm proposing makes this clearer since the developer is required to specify the status code. If not it's the default 302

**Comment by jsumners** [comment]
I completely disagree. I, the developer, have explicitly said I want to send a `303` _not_ a `302`. But you're saying that if I do not explicitly chain `reply.status(303).redirect('/foo')` then my desire will be overridden with a `302`. That is not a friendly developer experience, IMHO.

**Comment by ToonvanStrijp** [comment]
@jsumners I think either the design or the documentation needs to be changed.

On the other hand `reply.redirect()` ends the request and sends the response. [(https://github.com/fastify/fastify/blob/master/lib/reply.js#L240)](https://github.com/fastify/fastify/blob/master/lib/reply.js#L240). So you basically have two different actions, it either modifies the response or it sends it. Because the `redirect()` is an method that sends the response right away I think it's a better design option to have it set the status code to 302 to default like `express` does. This way you have a better view on what the response it going to be.

So if you guys decide it's better to keep the current code it's fine but then we need to make it clear in the documentation. Cause right now it says: 
> - `.redirect([code,] url)` - Redirect to the specified url, the status code is optional (default to `302`).

**Comment by jsumners** [comment]
I'm not opposed to clearer documentation.

**Comment by ToonvanStrijp** [comment]
Alright then let's do that anyways cause that won't do any harm ;)
