### ISSUE TITLE
Document the use of async functions in hooks.

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1593]
## 🐛 Bug Report

The current documentation is incorrect on how hooks works, as we state:

> * `preValidation(request, reply, done)`: a [function](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#route-hooks) called after the shared `preValidation` hooks, useful if you need to perform authentication at route level for example, it could also be an array of functions.

We need to document that `async preValidation(request, reply)` is also correct, but `async preValidation(request, reply, done)` is **not**.

**Comment by vcanales** [comment]
Wouldn't the following paragraph in Hooks.md address this issue?

> **Notice:** the `next` callback is not available when using `async`/`await` or returning a `Promise`. If you do invoke a `next` callback in this situation unexpected behavior may occur, e.g. duplicate invocation of handlers.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by vcanales** [comment]
Sorry for not being clearer: what I mean is that paragraph is already in the docs.

**Comment by Eomm** [comment]
> Sorry for not being clearer: what I mean is that paragraph is already in the docs.

He is referring to [Routes.md](https://github.com/fastify/fastify/blob/master/docs/Routes.md)

**Comment by mcollina** [comment]
That is not sufficient as quite a few people have asked/made this mistake recently between gitter and help.

**Comment by delvedor** [comment]
Wild idea: check at startup if is an async function and the arity, and if it is an async function with 3 arguments, throw an error.

**Comment by jsumners** [comment]
FYI: I make this mistake myself routinely.

**Comment by treykaws** [comment]
I am experiencing this right now. What is the suggested way to implemented multiple preHandlers or any lifecycle hook asynchronously?

**Comment by mcollina** [comment]
Can you paste some code that is not working for you? Have you tried using an array?

**Comment by treykaws** [comment]
```
fastify.get("/", 
fastify.addHook('preHandler', async (request, reply) => {
  const one = await one(request, reply)
  const two = await two(request, reply)
  return
}),
async (request, reply) {
  code for handler with new request 
})
```
This is essentially what my endpoint looks like. This could very well be an anti-pattern as I am new to how the handlers work in fastify. I am open to any suggestions on a proper way of handling this.

**Comment by mcollina** [comment]
You can call addHook twice, it should all work fine.

**Comment by treykaws** [comment]
Okay cool. I would ideally like to clean up the route though and extract that addHook logic. Where would you suggest I put and how could I have the right scope necessary to keep the functionality?

**Comment by mcollina** [comment]
Just pass an option object with a “preHandler” property with an array and your two functions. Let me know if it works!

**Comment by treykaws** [comment]
Awesome, it's working as expected and much more elegant than having the addHook block directly in the handler. Appreciate all the help!

**Comment by mcollina** [comment]
This doc needs to be improved ;).

**Comment by Eomm** [comment]
Closing thanks to improved docs by @RafaelGSS 💪

**Comment by PierBover** [comment]
What about error managing in an async hook?

The hooks docs specify to use `done(new Error('Some error'))` for non async hooks but there is no info on error handling on an async hook.

https://www.fastify.io/docs/latest/Hooks/#manage-errors-from-a-hook

**Comment by Eomm** [comment]
> What about error managing in an async hook?

you need to `throw new Error('something wrong')`,  would you like to add it to our docs?
I would be helpful!

**Comment by PierBover** [comment]
Sure why not!
