### ISSUE TITLE
Add automatic response time header?

### ISSUE THREAD

**Issue by bompus** [fastify/fastify#160]
I'd like to see maybe another hook that gets executed after User Handler or after Reply, just prior to sending off the headers, which would allow me to setHeader X-Response-Time or whatever I'd like.

Perhaps this is already possible, but the only way I could see is to hijack res.writeHead, etc to inject my header. It'd be much easier if there were simply a hook where I could add this.

If this is already possible and I am ignorant, please let me know!

**Comment by delvedor** [comment]
Hi, thank you for trying Fastify!
We are currently working on a `'onResponse'` hook that will run just after the user handler (in other word, after the `reply.send` call).

**Comment by bompus** [comment]
That would work perfectly. I'll wait for that to arrive, and thank you!

**Comment by jsumners** [comment]
Actually, unless I followed the flow incorrectly, `onResponse` isn't going to work. This new hook is run via the standard library's `onResFinshed` event. That means the headers have already been finalized. 

What we really need is a `postHandler` hook that has the signature `postHandler(fastifyRequest, fastifyReply, next)`.

**Comment by delvedor** [comment]
@jsumners `onResponse` will run once the response has finished, checkout the [lifecycle](https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md).

What you need is the `onSend` or `postHandler` hook, @lucamaraschi is working on it :)

**Comment by lolo32** [comment]
I just impemented onHeaders from express that you could use to do it. Just read the exemple.js file in the package: fastify-onheader.
I'm waiting for pull request to be accepted.

**Comment by lolo32** [comment]
I just impemented onHeaders from express that you could use to do it. Just read the exemple.js file in the package: fastify-onheader.
I'm waiting for pull request to be accepted.
I will make a package that match your needs

**Comment by jsumners** [comment]
This should be more generic than just for headers.

**Comment by delvedor** [comment]
@jsumners the `onSend` hook will provide support for this and more :)

**Comment by jsumners** [comment]
@delvedor right. I was responding to @lolo32.

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
