### ISSUE TITLE
Different color for links

### ISSUE THREAD

**Issue by anonimusprogramus** [fastify/fastify#1601]
Open https://www.fastify.io/docs/latest/Plugins/#route-prefixing-option

Look at the **red-colored** texts, it's not easy to spot which one is **link** or **code**, because both looks the same. 

User on phone may have hard time, doing click-and-hold just know if it's a link.
 
Please use different color for links, just like the other links on the whole docs (caribbean green?).

![Screenshot_20190414_190015](https://user-images.githubusercontent.com/7464749/56092527-67984700-5ee7-11e9-913a-25c9ab4de219.png)

**Comment by mcollina** [comment]
A PR that improves things would be highly welcomed.

Il giorno dom 14 apr 2019 alle 14:00 Anonimus Programus <
notifications@github.com> ha scritto:

**Comment by anonimusprogramus** [comment]
Oh thank you.
I've never made PR, don't know how yet.

Will learn, soon.

**Comment by vcanales** [comment]
I've created a PR for this on https://github.com/fastify/website -- I assume underlining anchored code snippets should suffice, but if you have anything else in mind don't hesitate to comment and I'll apply the changes :)

**Comment by lmammino** [comment]
Closed by https://github.com/fastify/website/pull/125

@mcollina || @delvedor can you close this one please (i don't see the close button in this repo unfortunately)
