### ISSUE TITLE
https rapidSSL

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1602]
Hello, can i use RapidSSL on Fastyfy server? I use https with key.pem cert.pem, but RapidSSL  is 3 files:

    key: privateKey,
    cert: certificate,
    ca: [ intermediateCertificate ]

Its possible?
My current server 

```js
const fastify = require('fastify')({
    logger: false,
    http2: true,
    https: {
        key: fs.readFileSync(path.join(serverDirectory, '/certificate/', 'key.pem')),
        cert: fs.readFileSync(path.join(serverDirectory, '/certificate/', 'cert.pem'))
    }
});
```

**Comment by mcollina** [comment]
you should be able to pass the same `ca` property to `https` as well.

**Comment by borodadada** [comment]
mcollina thanks man, i will try

**Comment by borodadada** [comment]
all work!

**Comment by mcollina** [comment]
Awsome!
