### ISSUE TITLE
Validation route schema (required)

### ISSUE THREAD

**Issue by sinitsyn-alex** [fastify/fastify#1604]
Hi. I have a schema:
```
body: {
    type: 'object',
    properties: {
      login: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      password: { type: 'string' }
    },
    required: ['login|email|phone', 'password']
  }
```
How do I choose one of the required?
`['login|email|phone', 'password']` not work.

**Comment by mcollina** [comment]
I think you should oneOf. Check this article out: http://queirozf.com/entries/json-schema-examples.

We use JSON schema as a format, there are a ton of docs on that on the Web.
