### ISSUE TITLE
Include Node.js v12

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1609]
Node.js v12 was just released 🎉 

I'm opening the discussion on how we will include it here in Fastify. One of the first things I can think of is updating our CI pipeline to also test on v12 as well as trying out the benchmarks if there would be any speed increase from the new update (cc @fastify/benchmarks)

**Comment by mcollina** [comment]
Go ahead and send a PR!

**Comment by zuohuadong** [comment]
+1

**Comment by delvedor** [comment]
Closed in #1610 and #1611.
