### ISSUE TITLE
Usage with webpack hmr?

### ISSUE THREAD

**Issue by leesiongchan** [fastify/fastify#161]
Is there a chance to integrate with `webpack-dev-middleware` and `webpack-hot-middleware`?

**Comment by mcollina** [comment]
@leesiongchan thanks for reaching out! We never tried, but I think it should be doable. Let us know if you try :). It would actually be a nice plugin if it could be pluginified?

**Comment by jberry93** [comment]
@mcollina I made a simple plugin that may need some additions if you are interested. Could I make a PR on fastify's repo or is there a fastify-webpack repo I can open a PR on? Thanks!

**Comment by valentinvichnal** [comment]
@jberry93 Is there a public repo for this? I can help you with the plugin.

**Comment by ansarizafar** [comment]
@mcollina  We can also use backpack-core https://github.com/jaredpalmer/backpack

Backpack is a minimalistic build system for Node.js projects.

**Comment by simoroshka** [comment]
can backpack work with fastify now, or do you need to integrate it first?

**Comment by mcollina** [comment]
I think backpack is not related to fastify, so you should be able to use it.
However I'm not recommending anyone to use that.

**Comment by gajus** [comment]
Note that `webpack-dev-middleware` does not work with webpack v5.
