### ISSUE TITLE
Confusing docs on host/port binding

### ISSUE THREAD

**Issue by yuchi** [fastify/fastify#1612]
:warning: There’s no «Documentation Problem» issue template, so I built my own. Feel free to point me to the correct templates/channels.

## 📝 Documentation Problem

In the [Getting Started][gs] section of the documentation there’s a “Note” section about host binding [(source)][gsn]. That section concludes with (emphasis mine):

> […] When deploying to a Docker, or other type of, container ***this*** would be the easiest method for exposing the application.

Since in the section there are 2 different approaches exposed (`127.0.0.1` vs `0.0.0.0`) the term `this` doesn’t help the reader understand which one should be used in the context of containers.

[gs]: https://www.fastify.io/docs/latest/Getting-Started/
[gsn]: https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md#note

## Solution Proposal

I’m no network/docker expert, so please forgive me if I inferred incorrectly (which would just add value to this issue report!) but I suggest to explicitly give the reader some directions:

> When deploying to a Docker, or other type of, container using `::` (or `0.0.0.0` for IPv4 only) would be the easiest method for exposing the application.

**Comment by delvedor** [comment]
Hello!
There is not the "Documentation Problem" issue template, because we think that a problem with the doc is a bug! :wink:

I'm pinging @jsumners since he wrote that part of the doc and raised the issue at the beginning.

Related: https://github.com/fastify/fastify/pull/667 https://github.com/fastify/fastify/pull/728

**Comment by jsumners** [comment]
The solution may be as simple as making the sentence part of the previous paragraph.

**Comment by yuchi** [comment]
@delvedor good to know! I’m just happy to see that my concerns are shared. (BTW we met in Rome few weeks ago — I told you I would look at fastify!)

@jsumners that same paragraphs covers both `::1` and `::` so if (1) you are actually saying that `::` is preferred in containers and (2) you don’t make it a different sentence altogether and separate the parts by, say, an em dash “—“, then yes it does make a lot of sense.

**Comment by jsumners** [comment]
Submit a PR with your proposed change.

**Comment by yuchi** [comment]
Will gladly do so, can you please confirm that `0.0.0.0` and `::` are the preferred options on containers? I really know nothing of containers and networking, I just happen to know how to bind ports and that’s it…

**Comment by mcollina** [comment]
Yes! 0.0.0.0 is actually _needed_ in containerized environments.
