### ISSUE TITLE
Cannot access with ip

### ISSUE THREAD

**Issue by rabbitooops** [fastify/fastify#1620]
`localhost:8080` can work but `[ipv4]:8080`.
Express.js can work properly.

**Comment by mcollina** [comment]
Which operating system are you working with? We bind ourself to whatever localhost is for security reasons. On Windows it’s your ipv6 address. If you want to bind on all ipv4 addresses, use 0.0.0.0.

**Comment by rabbitooops** [comment]
macos 10.14.4
This is my solution.
```js
const fastify = require('fastify')({})
fastify.listen(8081, function (err, address) {
  if (err) {
    console.log('err', err)
    fastify.log.error(err)
    process.exit(1)
  }
  console.log(address)
  fastify.log.info(`server listening on ${address}`)
})


const express = require('express')
const app = express()
var proxy = require('express-http-proxy')

app.use('/', proxy('localhost:8081'))


app.listen(8080, () => console.log(`Example app listening on port ${8080}!`))
```

**Comment by Eomm** [comment]
Did you add some route to the fastify instance?

```
fastify.get('/', (req, res) => res.send('hello'))
```

**Comment by jsumners** [comment]
What is the problem? Does this documentation not answer the question? https://github.com/fastify/fastify/blob/aea4100062353cf4da1cfcb4fe8167ac0092117c/docs/Server.md#listen

**Comment by imajkumar** [comment]
> `localhost:8080` can work but `[ipv4]:8080`.
> Express.js can work properly.

same with me
