### ISSUE TITLE
Update bourne dependency to use new hapi/bourne namespace

### ISSUE THREAD

**Issue by xM8WVqaG** [fastify/fastify#1621]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report (sortof)

Bourne updated it's package to be part of the `@hapi` namespace, this dependency is now `@hapi/bourne`. See: https://github.com/hapijs/bourne/issues/8

Currently doing `npm install` with fastify drops this warning.

```
npm WARN deprecated bourne@1.1.2: This module has moved and is now available at @hapi/bourne. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
```

## To Reproduce

npm install

## Expected behavior

No warnings.

## Your Environment

- *node version*: 10
- *fastify version*: 2.3.0
- *os*: Linux

**Comment by Eomm** [comment]
Thank you for the issue, we have already a PR #1619 about it

We will land this change in the next release 👍
