### ISSUE TITLE
Log requestes URI in response log

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1624]
We log the incoming request when it happens. This gives us access to the incoming URI in the initial log message. Upon completion of the request, we log a `"request completed"` message that includes the time it took to process the response but not what URI that response is for. This makes it very difficult to tie response times to the URI processed. The only way to do it would be to backtrace up to the incoming request log with the `req.id`. This is not possible in third party log manager solutions.

We issue log statements at the end of a request via the `Reply` object:

https://github.com/fastify/fastify/blob/8e41b2e6bd87effff64eefc27be809b5919b6c6b/lib/reply.js#L458-L478

This logger comes from:

https://github.com/fastify/fastify/blob/8e41b2e6bd87effff64eefc27be809b5919b6c6b/fastify.js#L293-L326

Notice that the `onRequest` hook is invoked _after_ these logger attachments. So it isn't possible to override them via an early plugin.

**Comment by mcollina** [comment]
Ok, would you like to send a PR?

Il giorno gio 2 mag 2019 alle 19:43 James Sumners <notifications@github.com>
ha scritto:

**Comment by jsumners** [comment]
When I can. Unless someone gets to it first.

**Comment by jsumners** [comment]
Leave this to me. I have a different idea than what I have outlined here that will be more robust.
