### ISSUE TITLE
Can you provide ES6 module in your library?

### ISSUE THREAD

**Issue by galuh1300d** [fastify/fastify#1626]
Please provide es6 module support in your library
so we can just import using curly braces to get faster result

in example import { something } from 'fastify'
to replace const fastify = require('fastify')()
Thanks

**Comment by mcollina** [comment]
Are you using babel or the esm module? There is no difference between these and normal require.

**Comment by galuh1300d** [comment]
I'm using esm module
But, i want to simplify import
how can i simplify this import
const fastify = require('fastify')()
as
import fastify from 'fastify'() ?

maybe in the future we can just
import fastify from 'fastify'
or
import { get, post, put, etc } from 'fastify'

i don't know 
maybe this is the future
lol

**Comment by jsumners** [comment]
It’s a completely different paradigm. I don’t see any reason to support it just to conform to a different syntax. ESM loading behaves totally different from the common module pattern.

**Comment by galuh1300d** [comment]
> It’s a completely different paradigm. I don’t see any reason to support it just to conform to a different syntax. ESM loading behaves totally different from the common module pattern.

I know, but maybe in the future it will fasten the development process.
Because everyone will be used to modern syntax in the future that is es6 and beyond.
i wonder if it in the future will be possible so that developers satisfication will increase.
i hope.

**Comment by jsumners** [comment]
Personally, I do not see myself ever using ESM style. It doesn’t offer any benefit to me, just more hassle.

**Comment by galuh1300d** [comment]
> Personally, I do not see myself ever using ESM style. It doesn’t offer any benefit to me, just more hassle.

I see, but as front end developer using react. using esm module will be my great benefits

**Comment by mcollina** [comment]
There are _no benefits_ in using the esm module. In fact, it would make your modules take more time to load, as it's going to transpile the syntax to something that Node.js will understand.

We'll support this once Node.js ships with full "import" support, we are not far away and we are targeting to stabilize it before 12 hits LTS

**Comment by galuh1300d** [comment]
> There are _no benefits_ in using the esm module. In fact, it would make your modules take more time to load, as it's going to transpile the syntax to something that Node.js will understand.
> 
> We'll support this once Node.js ships with full "import" support, we are not far away and we are targeting to stabilize it before 12 hits LTS

Yes, of course. What i meant is for the future of node 12 LTS. Thanks for the response. I know you can do it better than i thought.
