### ISSUE TITLE
Difference between `return` and `reply.send` in handler

### ISSUE THREAD

**Issue by dulesgar** [fastify/fastify#1628]
They both seem to do same thing, except return did not work on preHandler.

**Comment by jsumners** [comment]
Please provide more information. A code snippet would be best.

**Comment by dulesgar** [comment]
`function(req, reply, next) {
return "hello"
}`

and

`function(req, reply, next) {
reply.send("hello")
}`

**Comment by jsumners** [comment]
Your first example is completely invalid. The function would need to be declared `async` for that to work.

Neither function should have a `next` parameter.

The second example is correct for an asynchronous function once the `next` parameter is removed.

**Comment by jasonrberk** [comment]
straight from your quickstart:

![Screen Shot 2022-11-28 at 11 57 03 AM](https://user-images.githubusercontent.com/31823413/204336650-d6592039-8336-46ca-99af-617691f194bd.png)
