### ISSUE TITLE
Response static file Help please

### ISSUE THREAD

**Issue by extremety1989** [fastify/fastify#163]
here is code for express 
app.get('/',function(req,res){
res.sendFile(__dirname+'/client/index.html')
 })

how can i do with fastify ?

**Comment by delvedor** [comment]
Hi!
At the moment we do no have an api like `sendFile`, but you can do it as in the following example:
```js
fastify.get('/', (req, reply) => {
  const stream = fs.createReadStream('./index.html')
  reply.type('text/html').send(stream)
})
```
You can also develop a decorator:
```js
fastify.decorateReply('sendFile', filename => {
  const stream = fs.createReadStream(filename)
  this.type('text/html').send(stream)
})

fastify.get('/', (req, reply) => {
  reply.sendFile('./index.html')
})
```
In this way you can reuse it as many times as you need! :)

**Comment by mandaputtra** [comment]
for sending all the type can i do this? `this.type().send(stream)`

**Comment by delvedor** [comment]
@mandaputtra what do you mean with "all the type"?

**Comment by Extarys** [comment]
sorry to bump this, I have the same question.

Does using `type()` will detect and send the proper mime type?

**Comment by mcollina** [comment]
No, `type` is not going to autodetect the type. A plugin that does that would be awesome.

**Comment by Extarys** [comment]
Thanks @mcollina. It seems the api changed in v2 and `this` is no longer recognized though.
In the mean time I created 2 basic functions for sending html files and js files which seems to do the trick right now but it's dirty.

**Comment by mcollina** [comment]
Can you open a new issue describing the problem you are facing with a way to reproduce?

**Comment by liyiming22** [comment]
> Hi! At the moment we do no have an api like `sendFile`, but you can do it as in the following example:
> 
> ```js
> fastify.get('/', (req, reply) => {
>   const stream = fs.createReadStream('./index.html')
>   reply.type('text/html').send(stream)
> })
> ```
> 
> You can also develop a [decorator](https://github.com/fastify/fastify/blob/master/docs/Decorators.md):
> 
> ```js
> fastify.decorateReply('sendFile', filename => {
>   const stream = fs.createReadStream(filename)
>   this.type('text/html').send(stream)
> })
> 
> fastify.get('/', (req, reply) => {
>   reply.sendFile('./index.html')
> })
> ```
> 
> In this way you can reuse it as many times as you need! :)
> 
> _ps I recommend you to also read the [plugins guide](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md)_

arrow function will break the binding of this to the Fastify Reply instance.
