### ISSUE TITLE
Objection.js integration plugin

### ISSUE THREAD

**Issue by jarcodallo** [fastify/fastify#1637]
## 🚀 Feature Proposal

[fastify-objectionjs](https://github.com/jarcodallo/fastify-objectionjs) is a plugin for the Fastify framework that provides integration with objectionjs ORM.

## Motivation

I currently using fastify and Objection.js in two side projects. I'm hate copy/paste code, so i create a simple plugin for use Objection.js cross all my projects.

I want some feedback about this implementation and if you considerate is a good case for community plugin. Thanks 😄 

## Example

You can see an example of this plugin [here](https://github.com/jarcodallo/fastify-objectionjs#usage).

**Comment by mcollina** [comment]
Nice work! Would you mind sending a PR to https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md? Thanks!

**Comment by jarcodallo** [comment]
Yeah, i will open a PR for that. Thanks.

**Comment by jarcodallo** [comment]
@mcollina i created a PR for this, https://github.com/fastify/fastify/pull/1638
