### ISSUE TITLE
Drop support for Node.js 6.x in Fastify v3

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#1647]
Hi all, 
below you can find the proposal, for Fastify v3, as discussed in [PR#1618](https://github.com/fastify/fastify/pull/1618).

## 🚀 Feature Proposal
Drop support for Node.js 6.x , from documentation, CI build configurations, etc.

## Motivation
Because that release is no more under support, and the majority of installations now seems to be with Node.js 8.x or 10.x .
This would even improve the (right) perception that Fastify is aligned with the state-of-the-art Node.js using latest stable features.

All changes to be done in the 'next' branch.
Note that there was an old issue for this: [issues#1177](https://github.com/fastify/fastify/issues/1177), closed since some time.

## Example
This would help to simplify code base, using Node.js 8.x features too, but for that I'll raise another feature request (linked to this).

Thanks.

**Comment by smartiniOnGitHub** [comment]
Note: for code cleanup/update to Node.js 8.x (since its LTS release I think, right ?) I'll open another issue, because changes could be managed in a different way (and maybe not by me).

**Comment by mcollina** [comment]
Definitely +1! This should be a target for Fastify v3!

**Comment by smartiniOnGitHub** [comment]
Sorry for the delay, I'll start to do some changes for this soon (in the 'next' branch), and post here some update. Bye

**Comment by smartiniOnGitHub** [comment]
@mcollina now I remember that there are even some dependencies that could be updated now that we require Node.js 8 LTS, same PR or a new one (cleaner, after the merge of the first PR) ?

**Comment by mcollina** [comment]
A follow-up PR would be good, I think this is already a significant PR!

**Comment by smartiniOnGitHub** [comment]
time for the other PR now: update dependencies of all tools that was kept for compatibility with Node.js 6 (give me some days) ...

**Comment by smartiniOnGitHub** [comment]
All done for this issue. Thanks to all for the help.
