### ISSUE TITLE
Timeout if no routes are registered

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#165]
As titled if no routes are registered, the `listen` method doesn't call the callback.

Example:
```js
const fastify = require('fastify')()
fastify.listen(0, err => {
  // never called!
})
```

Maybe this issue can depend on `avvio` bug.

**Comment by delvedor** [comment]
I've just tried with [`examples/simple.js`](https://github.com/fastify/fastify/blob/master/examples/simple.js) (without the route) but I didn't have the problem.

Regarding `avvio`, if you don't call `register` but just `ready` it will work anyway.
