### ISSUE TITLE
Report-To handler

### ISSUE THREAD

**Issue by WilhelmErasmus** [fastify/fastify#1650]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

I'm trying to use fastify to run a server for Report-To POSTs. There does not seem to be support for the "application/csp-report" and "application/reports+json" headers.

## To Reproduce

I've tried to add a hook to change the content type to application/json but I get the following response

```js
🏷️  Routes:
POST    /csp-reports
GET     /health
POST    /network-reports
POST    /reports

server listening on 80
application/json
undefined deprecation/intervention reports:
```

## Expected behavior

I expected the content type to be handled

## Your Environment

- *node version*: 10.15.3
- *fastify version*: ^2.3.0
- *os*: Mac

**Comment by Eomm** [comment]
Could you add some code? How do you implemented the [ContentTypeParser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md)?

**Comment by WilhelmErasmus** [comment]
I'm switching to Lambda - I think that fastify is overkill for this use.
