### ISSUE TITLE
Update/simplify code to use Node.js 8.x features as minimum, in Fastify v3

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#1654]
Hi all,
this proposal is related to the other issue (about documentation/general discussion on the same topic) seen in [issue#1647](https://github.com/fastify/fastify/issues/1647), but this is related to code updates/simplifications.

## 🚀 Feature Proposal

Update and simplify code to use at least Node.js 8.x (since its LTS release) features.

## Motivation

Because previous releases are no more under support, and the majority of installations now seems to be with Node.js 8.x or 10.x .
This would even improve the (right) perception that Fastify is aligned with the state-of-the-art Node.js using latest stable features.

All changes to be done in the 'next' branch.

## Example

Search for code block referring to old Node.js versions (if any) and update/remove as needed.
Remove some of the conditionals for async/await and http2 in the tests.

**Comment by smartiniOnGitHub** [comment]
Is it good to set as requirement its LTS release 8.9.0 as seen in the announce [here](https://nodejs.org/en/blog/release/v8.9.0/) ?
Just for info, next LTS main line is for Node.js 10 is 10.13.0, as per related announce [here](https://nodejs.org/en/blog/release/v10.13.0/).

**Comment by mcollina** [comment]
> Is it good to set as requirement its LTS release 8.9.0 as seen in the announce here ?

Those are going to error in yarn. I'm happy to set them in v3 if we want to.

**Comment by smartiniOnGitHub** [comment]
Running unit tests in the 'next' branch I see some deprecations, like the following:
`
(node:33412) Warning: Using 'genReqId' in logger options is deprecated. Use fastify options instead. See: https://www.fastify.io/docs/latest/Server/#gen-request-id
(node:33412) Warning: basePath is deprecated. Use prefix instead. See: https://www.fastify.io/docs/latest/Server/#prefix
(node:33453) Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead

`

and even this:
`
  Skipped: 1
    http/2 request while fastify closing
`
but not sure if/how to handle it.

I think we should update code to address them.
@mcollina is it good to fix them here or do you prefer another issue/PR ?

**Comment by mcollina** [comment]
We should drop those options in v3.
Would you like to send some PRs that:

1. remove the deprecated functionalities (those where added in v1 and deprecated in v2)
2. enable http2 everywhere, dropping support for Node 6.

**Comment by smartiniOnGitHub** [comment]
sure, I'm already doing this in two different issues (with related PR); today I'll open the PR for the first part (the other issue) but I need some feedback on it , so see you soon ;-) . thanks for now

**Comment by smartiniOnGitHub** [comment]
I just found that in Fastify sources, there are many usage of the 'var' keyword to define variables, do you think it would be good to try to change (for what is possible) to 'const' or 'let' ? 
If yes I could try to do some changes, but in another PR (to link to this issue) ...

**Comment by xtx1130** [comment]
@smartiniOnGitHub About why use `var`, please see this discussion. https://github.com/fastify/fastify/pull/1625#discussion_r283170034

**Comment by StarpTech** [comment]
@smartiniOnGitHub @xtx1130 verify it before using `var` Node 8 has significant improvements.

**Comment by xtx1130** [comment]
@StarpTech emmm... I have made an benchmark about `var` and `let`, case is here:
```js
// benchVar.js
'use strict'

const Benchmark = require('benchmark')
let suite = new Benchmark.Suite

suite.add('var', function () {
  function test(){
    var a = 1
    return a
  }
  var s = test()
}).add('let', function () {
  function test1(){
    let b = 1
    return b
  }
  let t = test1()
}).on('cycle', function(event) {
  console.log(String(event.target))
}).on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').map('name'));
}).run()
```
In node v8.16.0, result is almost the same:
```shell
$ node benchVar.js
var x 455,265,468 ops/sec ±1.03% (87 runs sampled)
let x 425,755,615 ops/sec ±4.98% (80 runs sampled)
Fastest is var,let
```
Only in node v6, `var` has significant improvements than `let`:
```shell
$ node benchVar.js
var x 33,052,965 ops/sec ±0.99% (87 runs sampled)
let x 29,757,314 ops/sec ±3.68% (73 runs sampled)
Fastest is var
```
I think is ok to use `let` instead of `var` in node v8+.

**Comment by smartiniOnGitHub** [comment]
@StarpTech @xtx1130 thanks for the info and the draft benchmark :-) . In general (on JVM) I prefer immutable variables, so here in a similar way I could try to use 'const' as much as possible and otherwise use 'let' (and of course check with benchmarks); do you think it would be good as strategy (in its own PR) ?

**Comment by mcollina** [comment]
There are still some cases in Node 8 where let is worse than var.

**Comment by delvedor** [comment]
I don’t think we should move to let, even if there is no perf gain.
var is not bad, and our entire codebase has been written with var. I’m quite sure that move to let will break some code due to the block scoping.
There is no reason to use let unless you need the different scoping rules.
Just because is the new syntax it does not mean that you should use it ;)

**Comment by smartiniOnGitHub** [comment]
In next days I should be able to start to work on this (a feature branch fromm next, to target next), by removing deprecated calls (as seen in unit tests), and maybe other ... tell me if there is something to do on this topic.

**Comment by smartiniOnGitHub** [comment]
@delvedor sorry I wasn't aware of performance differences between 'var' and 'let'/'const', good to know; main reason for trying to use 'const' was to promote immutability ... anyway let's see in the future :-) ... thanks again for all the info.

**Comment by smartiniOnGitHub** [comment]
Sorry for the same reasons (performances) it's better to not upgrade request id generator to generator functions (sync or async), right ?
So I think we can safely close this issue as resolved.
Thanks to all for the help. Bye

**Comment by mcollina** [comment]
Exactly

**Comment by delvedor** [comment]
> main reason for trying to use 'const' was to promote immutability

Be aware that `const` does not promote immutability, it only avoids value reassignment and double declaration.
