### ISSUE TITLE
Remove Travis CI from next branch

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1658]
As title says. I think the azure-pipelines CI is much better than Travis; I see no reason to continue using the service going forward.

**Comment by Eomm** [comment]
We should check only the config of the service (email alerting) and permissions because I don't have access to Azure and I can't do anything right now 😅 ( I can restart only failed jobs from GitHub)

**Comment by delvedor** [comment]
We can remove Travis directly in `2.x`, it is not a breaking change and the builds are stable enough.

@Eomm you should be able to login with Github and manage jobs directly from the Azure UI.

**Comment by Ethan-Arrowood** [comment]
I’ll send a pr for this soon!

**Comment by jsumners** [comment]
I just tried to login for the first time with my GH account and got this:

![Sign in to your account - Vivaldi 2019-05-22 10-43-31](https://user-images.githubusercontent.com/321201/58184116-7f00e780-7c7e-11e9-88f9-d27f3b1ae2f8.png)

**Comment by Ethan-Arrowood** [comment]
I think @martinwoodward was helping us set this up originally. Maybe he or @fastify/leads could make sure everyone has access

**Comment by martinwoodward** [comment]
Well that's not very friendly.  Let me dig into that and get back on this issue. The team are adding GH invite's and GH group support soon which will help a bunch.

**Comment by jsumners** [comment]
Here’s the thing. It picked up that I have other existing accounts due to my previous employer being on O365. I imagine it saw the emails from the list of emails associated with my GitHub account and then tried to do something with those.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1670.
