### ISSUE TITLE
`app.register` not called in AWS Lambda / Serverless

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify#1659]
## 🐛 Bug Report

In AWS Lambda / Serverless framework it not works as excepted

**Note**: _The reason of use Serverless framework it's ecosystem, flexibility and support for many providers, not only AWS Lambda, what works in AWS Lambda or in localhost, works on almost every Serverless provider (Azure, GCloud)_

## To Reproduce

1. Clone [this](https://github.com/dalisoft/fastify-dev-env/) repo.
2. install deps
3. Export to AWS Lambda or try with Serverless framework
4. See, it not registers plugins

Paste your code here: 
```js
const app = fastify();

app.register(myPlugin);
```

## Expected behavior

On AWS Lambda plugins should as expected.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.3.0
- *os*: Mac
- AWS Lambda / Serverless

**Comment by mcollina** [comment]
I'm a bit lost. I don't understand what is the problem, and how to reproduce it. Specifically step 3 is definitely something that I do not know what to do. Can you provide clearer instructions?

The only official docs regarding Lambda are in https://www.fastify.io/docs/latest/Serverless/. Note the disclaimer.

**Comment by dalisoft** [comment]
You can run Serverless in localhost, all scripts are prepared, just run `npm run dev:serverless` and local Serverless will be runned.
Serverless framework manipulates almost same as AWS Lambda / GCloud / Azure Functions env

**Comment by mcollina** [comment]
@lmammino would you mind taking a look?

**Comment by lmammino** [comment]
I'll have a look in few hours

**Comment by lmammino** [comment]
@dalisoft just downloaded your repo and honestly there's a bit too much stuff to test your use case in isolation.

Can you provide a more minimalistic way to reproduce the error? I hope it's possible to do that with just one JS file and a serverless.yml :)

**Comment by dalisoft** [comment]
Sorry, bug caused by [this](https://github.com/fastify/fastify-compress/issues/60) module
