### ISSUE TITLE
Git folder was included in v2.4.0

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify#1662]
Hi!

In v2.4.0 NPM package `.git` folder was included and this can cause 2 issue
- Security issue (may be?)
- Installation fails (after installing fastify v2.4.0)

You can see direct NPM folder online at [here](https://unpkg.com/fastify@2.4.0/)

Have a nice day!

**Comment by delvedor** [comment]
Reported also in https://twitter.com/wa7son/status/1131116436087287808.
It's weird, I thought npm would automatically ignore that. Apparently, it doesn't.

**Comment by dalisoft** [comment]
Yea, for my libraries also same thing happened few week ago. This bug applies only after Node.js 8+ (as i see this after Node.js 8+ on my libraries)
