### ISSUE TITLE
Using uWebSockets.js as HTTP and WS Router

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify#1665]
## 🚀 Feature Proposal

Using [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) as Router system

## Motivation

There some benefits
- Performance will be like speed of the light (very fast)
- Out-of-the-box `WebSocket` compatibility
- Memory efficient (for HTTP and WS)
- Lower latency

Also some things need be done
- wrapping their methods (as they different from Fastify)
- add plugins support

## Example

I made small [app](https://github.com/dalisoft/graphql-dev-env) with [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) (before used `turbo-http`) and performance was improved by 50% on localhost and 150% on real servers (with a lot of reducing cost and memory usage)
_Note: example app isn't related to Fastify, just for example_

**Comment by mcollina** [comment]
I’m -1 in making this a default choice. However providing a module that add this capability would be amazing. From a technical perspective, We might use our inject method to provide this capability.

**Comment by dalisoft** [comment]
Yes, not default choice, but making as optional is much better than not compatible :)

**Comment by delvedor** [comment]
We heavily depend on Node.js http core module, the main requirement to support other http servers is that the API must be the same.

**Comment by dalisoft** [comment]
But we can somehow make it work with fastify? if it's possible, would great (and ws out-of-the-box will be supported)

**Comment by delvedor** [comment]
You should use the [`serverFactory`](https://www.fastify.io/docs/latest/Server/#serverfactory) option, and then find the methods not supported by your custom http server. Once you find them, you can patch it and make it compatible with Fastify.

**Comment by dalisoft** [comment]
Ah, i tried, but can't make it work. I think i should try from scratch :)

**Comment by dalisoft** [comment]
@mcollina @delvedor I ended up with making another server framework, which didn't want at start (but it gives some xp about perf, anyway, i love fastify).

@mcollina uWebSockets.js can't be ported at plug-in level, it should be at core-level
