### ISSUE TITLE
Azure Pipelines is not running on PRs targetting next branch

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1671]
As title says. I believe this is a quick fix in the azure-pipeline configs or on the Azure Dev Ops portal. Will look into it and follow up.

cc @fastify/leads

**Comment by Ethan-Arrowood** [comment]
Based on the configuration I believe this is a change in the repo or dev ops settings so it'll probably need to be fixed by a lead.

**Comment by mcollina** [comment]
I don't know how to do that. It's not obvious.
I've added you as an admin. Would you mind sorting it out?

**Comment by Ethan-Arrowood** [comment]
@martinwoodward I've looked into this further. We don't have any configured `pr` or `trigger` lines in the YAML files; however, Azure Pipelines isn't triggering on my PR's against the `next` branch #1670 and #1569 . The Dev Ops docs says that it should default to all PRs regardless of the branch. 

Any ideas?

**Comment by Ethan-Arrowood** [comment]
@mcollina I've tried digging around the Azure Pipelines side of things and I can't seem to find anything. 

From the Azure Pipelines [triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml) documentation:

> YAML builds are configured by default with a CI trigger on all branches.

and

> If no `pr` triggers appear in your YAML file, pull request builds are automatically enabled for all branches

So I'm really not sure why it wouldn't be running.

@fastify/leads are there any Azure Pipelines settings thing on the GitHub side? Like from the repository level maybe? 

My only other solution is for us to explicitly define which branches prs should trigger on from within the YAML configs. 
My list right now includes:
- master
- 1.x
- next

Any others?

**Comment by mcollina** [comment]
I would go with that path. Only those branches are needed.

**Comment by Ethan-Arrowood** [comment]
Looks like pipelines is triggering the CI on 1.x and greenkeeper branches. So I think this issue is strictly with pull requests.  
<img width="508" alt="Screen Shot 2019-05-29 at 12 54 43 PM" src="https://user-images.githubusercontent.com/16144158/58575850-fac7da80-8210-11e9-930e-fa253c54e058.png">

---

I'll update the configuration and see if that gets us anywhere.

**Comment by Ethan-Arrowood** [comment]
Figured it out 🎉

It *is* on Azure. I'm going to document the steps here in case it ever needs to be updated in the future.

From Pipelines View select the fastify.fastify pipeline
<img width="1317" alt="Screen Shot 2019-05-29 at 3 14 17 PM" src="https://user-images.githubusercontent.com/16144158/58584774-13da8680-8225-11e9-9042-1586621ee704.png">

Select the **Edit** button
<img width="1318" alt="Screen Shot 2019-05-29 at 3 15 14 PM" src="https://user-images.githubusercontent.com/16144158/58584793-1e951b80-8225-11e9-955a-be0df623f36c.png">

Select the 3 dots, and then select **Triggers**
<img width="1317" alt="Screen Shot 2019-05-29 at 3 15 58 PM" src="https://user-images.githubusercontent.com/16144158/58584830-379dcc80-8225-11e9-80d6-b67d2d58bf43.png">

Finally, select **Pull Request Validation** and then edit the branches however necessary.
<img width="1317" alt="Screen Shot 2019-05-29 at 3 13 48 PM" src="https://user-images.githubusercontent.com/16144158/58584863-48e6d900-8225-11e9-982a-b46769a5f9dd.png">

**Comment by Ethan-Arrowood** [comment]
Just need to push a commit to the open PRs targeting `next` and `1.x` and they pipeline will be ran!
