### ISSUE TITLE
How to access Reply in tests ?

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1679]
Hello!

How I can access the Reply object in tests?

I have the follow plugin:
```
// plugins/response.js
module.exports = fp(function (fastify, opts, next) {
  fastify.decorateReply('success', function ({ message = 'Success', data = [], code = 200 }) {
    this.type('application/json')
    this.send(generateResponse(data, message, code, false))
  })
  next()
})
```
and my test:
```
test('responseApi works standalone', (t) => {
  t.plan(2)
  const fastify = Fastify()
  fastify.register(responseApi) // This is my plugin

  fastify.ready((err) => {
    t.error(err)
    // How I access the Reply object here ?
   // t.equal(fastify.res.success(), false)
  })
})
```

**Comment by StarpTech** [comment]
Hi @RafaelGSS the best place is to looking in our tests e.g
https://github.com/fastify/fastify/blob/37dde53dea4f6363db5cc26fceb4868d5944fc53/test/decorator.test.js#L84
I recommend it to check it inside a route handler.
https://github.com/fastify/fastify/blob/37dde53dea4f6363db5cc26fceb4868d5944fc53/test/decorator.test.js#L101
