### ISSUE TITLE
Could you add my sample to examples list?

### ISSUE THREAD

**Issue by lopatnov** [fastify/fastify#1687]
## 💬 Questions and Help

Hello, developers!

I wrote the starter project: https://github.com/lopatnov/fastify-server-starter
It's a simple demo of fastify (js) + babel + webpack + typescript model.
Could you add this project to https://github.com/fastify/example list?

Best regards,
Oleksandr

**Comment by Eomm** [comment]
Yes, I think we could address it adding a new table with the title `External Project` (as per `Project` paragraph).

I will update my https://github.com/fastify/example/pull/11 to fix it so then you could add your project

**Comment by lopatnov** [comment]
Great! Thanks!
