### ISSUE TITLE
May I contribute to testing (specific features are listed below)?

### ISSUE THREAD

**Issue by i0natan** [fastify/fastify#1688]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

A clear and concise description of what the feature is.

:clap: Howdy and thanks for the great work, I started to use Fastify and enjoy it!

I aim to specialize at writing good tests, it's along road but I'm trying :), I also write about it from time to time ([example blog 1](https://medium.com/@me_37286/yoni-goldberg-javascript-nodejs-testing-best-practices-2b98924c9347), [example content 2](https://github.com/i0natan/nodebestpractices) ) and I thought that maybe I can contribute useful enhancements to the already great testing here. I'm about to propose some specific features but mostly looking to hear whether you welcome such changes before I spend a great time. I'm putting forward multiple orthogonal testing features, you may opt for any subset, just share if at least some seem valuable to you.

1. Test code simplification - as one example, we may make the tests a little less verbose using t.throws instead of try-catch statements, see prtscn for example
![image](https://user-images.githubusercontent.com/8571500/58761182-fde10480-8549-11e9-8b8f-7063fcb9f41f.png)

I have other code simplification to propose, just not sure if this level of enhancements is of interest

2. Multi-dependencies version tests - since the code might run with a varying version of dependencies, run *some* of the tests against multiple dependencies version using a tool like [test-all-versions](https://www.npmjs.com/package/test-all-versions) or other

3. Common additional CI checks - vulnerabilities checks, mutation testing, coverage threshold, etc

4. E2E tests - Currently the CI runs only narrow tests (unit, narrow-integration, etc). Maybe it's worth also include a few, no more than 3-5, tests that approach the system realistically across processes, real networking (not in-process hooks or binding), with common HTTP scenarios. For example, OPTIONS request followed by an authentication request and then a payload request. The aim is to catch smoke, across the board. The aim, like any other E2E test, is to see all the units playing together and catch non-functional bugs

5. Run tape in parallel - if we do opt for runnings wider tests (E2E), then utilizing more cores can speed-up significantly (very easy with node-tap)

## Motivation
Easier maintainability fo tests, catch more *types* of issues, speed-up the development

Please outline the motivation for the proposal.

## Example
I've attached an example above with prtscn. Let me know whether you need more

**Comment by mcollina** [comment]
Thanks for the offer! We like to take all the help we could get.

Improving readability on our tests would be awesome. Would you like to start there, maybe one file at a time?

Regarding the other points, I’m pretty sure we do not need to use test-all-versions here, but it would be nice to use it in dependencies. Our integrations already do a) code coverage measurements b) vulnerability checks - I feel we are pretty well covered in this area.

I would like to see what you mean by E2E testing. I think it would be good to have some tests including some popular plugins a database etc.. but not as part of this repo.

Last but not least, I think we are already running our tap tests in parallel, so I’m not sure what you are talking about.

**Comment by i0natan** [comment]
> Would you like to start there, maybe one file at a time?

Sounds like the right way to go. I'll pick one test file where I can apply a few enhancements, get the team feedback and once we fill it's solid - I'll refactor the rest

> I think we are already running our tap tests in parallel

I went over a few of the fastify projects and didn't see the flag --worker, maybe I missed it. Anyway, let's re-visit other ideas as we progress 👍

**Comment by mcollina** [comment]
We are using `-J` _in this project_. That runs tests on all available cores.

**Comment by i0natan** [comment]
@mcollina Yeah, missed that tiny mini J there :)

**Comment by brodybits** [comment]
??

**Comment by i0natan** [comment]
> ??

Is this targeted to me? if yes, I plan to start after next week
