### ISSUE TITLE
Missing caseSensitive options in fastify.d.ts

### ISSUE THREAD

**Issue by hhwang39** [fastify/fastify#1689]
## 💬 Questions and Help
We are using nestjs and using Fastify as middleware. When we pass `caseSensitive` option to Fastify, it shows ts-error since `ServerOptions` in `fastify.d.ts` does not have `caseSensitive` option.
It looks like `ServerOptions` in fastify.d.ts needs `caseSensitive` option added to the code.

**Comment by Eomm** [comment]
Yeah, there are some parameters that are missing from `ServerOptions`:

https://github.com/fastify/fastify/blob/master/fastify.d.ts#L180

Would you mind to send a PR?

(that has been fixed in an open PR that will be merged in `next` branch)

**Comment by hhwang39** [comment]
I just made one. https://github.com/fastify/fastify/pull/1691. Not sure if I need to add the test.

**Comment by Ethan-Arrowood** [comment]
Lets keep this open until your PR is merged

**Comment by delvedor** [comment]
Closed in #1691.
