### ISSUE TITLE
How to access `reply` object inside decorateReply?

### ISSUE THREAD

**Issue by naseemali925** [fastify/fastify#1698]
Hi,
I am trying to use the reply object inside decorateReply?
```
fastify.decorateReply('json', (source, context, variables, operationName) => {
   //The Response Needs To Be Sent From Here.
  });
```
I have a use case where I need to decorate a function to reply object that will send the response. Any help would be appreciated

**Comment by mcollina** [comment]
fastify.decorateReply('json', function (source, context, variables, operationName) {
  this.send() // this is the Reply object.
   //The Response Needs To Be Sent From Here.
  });
