### ISSUE TITLE
Handler error without async functions

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1702]
## 🚀 Feature Proposal

Hello!

Recently I reading a lot of source code fastify and docs and I saw this:

> _Note that Fastify doesn't catch uncaught errors within callback based routes for you, so any uncaught errors will result in a crash. If routes are declared as async though - the error will safely be caught by the promise and routed to the default error handler of Fastify for a generic Internal Server Error response. For customizing this behavior, you should use setErrorHandler._

Why not catch uncaught errors in routes sync? 

If we (or us, hehe) manipulate the response of handler by another handler safely, could catch that error and send to default errorHandler fastify.

Obs: I already see the `fastify-sensible`. But, why not integrate by default in fastify ?

Thanks all for reading that feature request.

**Comment by mcollina** [comment]
> Why not catch uncaught errors in routes sync?

Because it's a false friend. Doing that would _immediately_ have people asking "why don't you do it for callback apis". It's not possible to do that safely. In a callback-based application the best thing you can do in case of an error is to crash.

> If we (or us, hehe) manipulate the response of handler by another handler safely, could catch that error and send to default errorHandler fastify.

I don't understand this sentence.

> Obs: I already see the fastify-sensible. But, why not integrate by default in fastify ?

That's not true.

**Comment by RafaelGSS** [comment]
@mcollina Thanks for the fast answer.

So, I understand that is not possible to make a handler of error safely. So, create all routes in async mode, is the best thing to catch uncaught errors? If "yes", why not advise people to **more** use async mode?

**Comment by mcollina** [comment]
> So, I understand that is not possible to make a handler of error safely. 

It's not possible in Node.js, the following does not work as expected:

```js
try {
  fs.readFile('./something', function () {
    throw new Error('kaboom')
  })
} catch (err) {
  // will not catch
}
```

> If "yes", why not advise people to more use async mode?

That's essentially what that paragraph is about.

**Comment by RafaelGSS** [comment]
Oh well... My mistake

Closing, thanks!
