### ISSUE TITLE
Question :  fastify.decorate() works at runtime, can we use it ?

### ISSUE THREAD

**Issue by fas3r** [fastify/fastify#1707]
## 💬 Questions and Help

I notice that `fastify.decorate()` works at runtime if we set / get from the same scope (meaning that it will not work if we create/set the decorator in plugin A and get it  from plugin B, but it will work if we set/get in the pluginA as there are no dependency needed). 

Example : 

```
// Require the framework and instantiate it
const fastify = require('fastify')({
  logger: true
})


fastify.get('/set', (request, reply) => {

  fastify.decorate('myDecorator', {
   fnKey: () => 'myDecorator created and fnKey is set'
  })
  reply.send({ set: true })
})


fastify.get('/update', (request, reply) => {
  fastify.myDecorator['fnKey'] = () => 'myDecorator changed,sorry'

  reply.send({ update: true })
})

fastify.get('/get', (request, reply) => {
    reply.send({ value_decorator: `value is ${fastify.hasDecorator('myDecorator') ? fastify.myDecorator.fnKey() : 'no created yet' }` })
})

// Run the server!
fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

For the simplicity I did not do any check like `fastify.hasDecorator('...')` execpt in the `/get` but if you visit in this order : 
- `/get` will return 'no created yet'
- `/set` it will create the decorator, then visit `/get` to verify. 
- `/update` to update the decorator. Visit again on `/get`, the decorator is changed

Is it something that we can do or it can have side effect  ?

bonus question,  if we can do it and the decorator is an object,  would it be possible to add a method `updateDecorator('decorator', 'key', value) ` instead of doing `fastify.myDecorator['key'] ` , are you open for a PR on for that matter  ?

Thanks

**Comment by RafaelGSS** [comment]
> I notice that fastify.decorate() works at runtime

This is not true when you bootstrap the application, the `avvio` is responsible to make the async bootstrap order, and when found a `decorate` method, they call [this](https://github.com/fastify/fastify/blob/master/lib/decorate.js#L15) method, to set inside the **current** instance of fastify. 
What happens with your example, is because they have defined inside the **handler**, that is executed just when calling the route.

Obs: Maybe, I think that throw a `throwIfAlreadyStarted` for these cases can be util. Right ? @mcollina @"fastifyteam"


> Is it something that we can do or it can have side effect ?

Your example already answers this.


_If I'm wrong about something, let me know_

**Comment by delvedor** [comment]
You can do it, but I would not recommend it.
You should declare decorators outside routes with an empty value, and then populate them.
Your code can be rewritten as follows:
```js
// Require the framework and instantiate it
const fastify = require('fastify')({
  logger: true
})

fastify.decorate('myDecorator', new Map())


fastify.get('/set', (request, reply) => {
  fastify.myDecorator.set('fnKey', () => 'myDecorator created and fnKey is set')
  reply.send({ set: true })
})


fastify.get('/update', (request, reply) => {
  fastify.myDecorator.set('fnKey', () => 'myDecorator changed,sorry')
  reply.send({ update: true })
})

fastify.get('/get', (request, reply) => {
  reply.send({ value_decorator: `value is ${fastify.myDecorator.has('fnKey') ? fastify.myDecorator.get('fnKey')() : 'no created yet' }` })
})

// Run the server!
fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

**Comment by fas3r** [comment]
Hello @delvedor , 

ok thanks.
