### ISSUE TITLE
schema: nullable option not working on string with format or pattern

### ISSUE THREAD

**Issue by adrai** [fastify/fastify#1709]
## 🐛 Bug Report

Seems there is the option to mark a property in a schema (I tried body schema) as nullable like this:
```js
...
shortbio: { type: 'string', nullable: true },
...
```
But if the property defines a format or a pattern the nullable option is ignored.

## To Reproduce

For example this will **not** work:
```js
...
website: { type: 'string', nullable: true, pattern: '^(https?:\\/\\/)?(www\\.)?([a-zA-Z0-9]+(-?[a-zA-Z0-9])*\\.)+[\\w]{2,}(\\/\\S*)?$' },
email: { type: 'string', nullable: true, format: 'email' },
...
```

As a **workaround** it can be declared like this (see the type value):
For example this **will** work:
```js
...
shortbio: { type: 'string', nullable: true },
website: { type: ['string', 'null'], nullable: true, pattern: '^(https?:\\/\\/)?(www\\.)?([a-zA-Z0-9]+(-?[a-zA-Z0-9])*\\.)+[\\w]{2,}(\\/\\S*)?$' },
email: { type: ['string', 'null'], nullable: true, format: 'email' },
...
```

example: https://github.com/adrai/fastify-schema-example

## Expected behavior

Expecting this **would** work:
```js
...
shortbio: { type: 'string', nullable: true },
website: { type: 'string', nullable: true, pattern: '^(https?:\\/\\/)?(www\\.)?([a-zA-Z0-9]+(-?[a-zA-Z0-9])*\\.)+[\\w]{2,}(\\/\\S*)?$' },
email: { type: 'string', nullable: true, format: 'email' },
...
```

fyi: I want to use the same object schema for body and response.

## Your Environment

- *node version*: 12.4.0
- *fastify version*: 2.5.0
- *os*: Mac

**Comment by mcollina** [comment]
Can you provide a full example? I don't understand if it's a Ajv issue or a fast-json-stringify issue.

> fyi: I want to use the same object schema for body and response.

Which one is not working?

**Comment by adrai** [comment]
I hope this helps: https://github.com/adrai/fastify-schema-example

I don't think it's an issue of fast-json-stringify

**Comment by RafaelGSS** [comment]
@adrai Try just set a `default: null`. Check if helps

**Comment by Eomm** [comment]
You should use:
```
nullableKey: { type: ['number', 'null'] },
```
because the `nullable: true` field is not a standard JSON schema, it is a OpenAPI specification.

I don't know if AJV 6.9.2 support it out of the box. Would you like to check?

**Comment by adrai** [comment]
> @adrai Try just set a `default: null`. Check if helps

this brings: "TypeError: Cannot use 'in' operator to search for 'anyOf' in null" on start

**Comment by adrai** [comment]
> You should use:
> 
> ```
> nullableKey: { type: ['number', 'null'] },
> ```
> 
> because the `nullable: true` field is not a standard JSON schema, it is a OpenAPI specification.
> 
> I don't know if AJV 6.9.2 support it out of the box. Would you like to check?

this is exactly the workaround I described ;-)

**Comment by Eomm** [comment]
It is not a workaround, it is how the JSON schema should be configured.

[Here](https://npm.runkit.com/ajv) you can try that Ajv doesn't support that field:

```
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true});

var schema = {
  "properties": {
    "foo": { "type": "string", nullable: true },
    "bar": { "type": "number", "maximum": 3 }
  }
};

var validate = ajv.compile(schema);

test({"foo": "abc", "bar": 2});
test({"foo": null, "bar": 2});

function test(data) {
  var valid = validate(data);
  if (valid) console.log('Valid!');
  else console.log('Invalid: ' + ajv.errorsText(validate.errors));
}
```

**Comment by adrai** [comment]
@Eomm in these tests (in the ajv repo) I see the opposite: https://github.com/epoberezkin/ajv/blob/master/spec/options/nullable.spec.js

**Comment by adrai** [comment]
Seems this is too complex to handle => https://github.com/epoberezkin/ajv/issues/919

**Comment by adrai** [comment]
fyi: if passing "global" Ajv option nullable: true, it will work => https://github.com/fastify/fastify/pull/1711/files

**Comment by Eomm** [comment]
> fyi: if passing "global" Ajv option nullable: true, it will work => #1711

Great! For sure, this will help someone that will encounter the same issue.
Thank you for checking deeper 👍
