### ISSUE TITLE
Add parse type default on schema

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1710]
## 🚀 Feature Proposal

Hello everyone.

Currently, I working with `fastify` and have the follow schema: 
```
schema: {
      querystring: {
        type: 'object',
        properties: {
          localeId: {
            type: ['number', 'array']
          }
       }
}
```

But, all of the parameters received I need parse to array even if it is the only index

So, I do this in my handler:
```
if (!Array.isArray(localeId)) {
      localeId = [parseInt(localeId)]
}
```
So... I think about add a `parserType` in cases that `type` is greather than 1

## Example

```
schema: {
      querystring: {
        type: 'object',
        properties: {
          localeId: {
            type: ['number', 'array'],
            parserType: 'array'
          }
       }
}
```

**Comment by RafaelGSS** [comment]
I found something that works inside [ajv](https://github.com/epoberezkin/ajv/blob/master/COERCION.md).
In my case, add coerceTypes to `array` works... But in fastify, is not able to send these parameters.

I can send the PR. But, have the following comment:
`//// it should not be customized or used`
[here](https://github.com/fastify/fastify/blob/master/lib/validation.js#L149)

**Comment by Eomm** [comment]
Did you try the [schema compiler](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#schema-compiler)?
What trouble do you have set up?

**Comment by RafaelGSS** [comment]
I do not have a problem setting a new `schemaCompiler`. But my question is, why not send config of ajv default by fastify instance?

**Comment by Eomm** [comment]
I didn't write that part at the beginning but I could dare some design considerations:
- if you control the all the option keys you can validate them
- separation of domains: the ajv configuration is part of the ajv realm, it should not involve the HTTP server
- encapsulation: if you set up a config in the main instance, you would have always the same config
- avoid lockin: if some module doesn't accept a JSON as configuration, it should not be supported by fastify

**Comment by RafaelGSS** [comment]
> separation of domains: the ajv configuration is part of the ajv realm, it should not involve the HTTP server
I agree with that point.

> encapsulation: if you set up a config in the main instance, you would have always the same config

But for now, fastify only set the `schemaCompiler` one time (If you don't pass any schemaCompiler). 
So, always use the same config once the default `schemaCompiler` is added

**Comment by RafaelGSS** [comment]
Closing that issue. But maybe, a flag to set `schemaCompiler` defaults for each route can be util. Sure, when not have any changes, uses the default.
