### ISSUE TITLE
Add TypeScript Update Guide

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1712]
Things are changing in the `next` branch for Fastify's types. These are breaking and so a guide to update from 2 to 3 should be created. This guide will also have information for updating plugins

**Comment by Ethan-Arrowood** [comment]
In case anyone is tracking this issue - started working on the documentation tonight! Really excited to finally get it all down. Here is a snippet of what I have so far:

---

## TypeScript

The Fastify framework is written in plain JavaScript and as such type definitions are not as easy to maintain; however, since version 2 and beyond, maintainers and contributors have put in a great effort to improve the types.

In its current state, the type systems between Fastify v2.x and future v3.x contain breaking changes. Version 3.x type system introduces generic constraining and defaulting, plus a new way to define schema types such as a request body, querystring, and more! As the team works on improving framework and type definition synergy, sometimes parts of the API will not be typed or may be typed incorrectly. We encourage you to **contribute** to help us fill in the gaps. Just make sure to read our [`CONTRIBUTING.md`](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md) file before getting started to make sure things go smoothly! 

> The documentation in this section covers Fastify version 3.x typings

> Plugins may or may not include typings. See [Plugin Types](#plugin-types) for more information.

## Getting Started - Basic Example
- Create a new npm project, install Fastify, and install typescript & node.js types as peer dependencies:
  ```bash
  npm init -y
  npm i fastify
  npm i -D typescript @types/node
  ```
- Add the following lines to the `"scripts"` section of the `package.json`:
  ```json
  {
    "scripts": {
      "build": "tsc -p tsconfig.json",
      "start": "node index.js"
    }
  }
  ```
- Initialize a TypeScript configuration file:
  ```bash
  tsc --init
  ```
- Create an `index.ts` file - this will contain the server code
- Add the following code block to your file:
  ```typescript
  import fastify from 'fastify'

  const server = fastify()

  server.get('/ping', async (request, reply) => {
    await reply.send('pong\n')
  })

  server.listen(8080, (err, address) => {
    if(err) {
      console.error(err)
      process.exit(0)
    }
    console.log(`Server listening at ${address}`)
  })
  ```
- Run `npm run build` - this will compile `index.ts` into `index.js` which can be executed using Node.js. If you run into any errors please open an issue in [fastify/help](https://github.com/fastify/help/)
- Run `npm run start` to run the Fastify server
- You should see `Server listening at http://127.0.0.1:8080` in your console
- Try out your server using `curl localhost:8080/ping`, it should return `pong` 🏓

🎉 You now have a working Typescript Fastify server! This example demonstrates the simplicity of the version 3.x type system. By default, the type system assumes you are using an `http` server. The later examples will demonstrate how to create more complex servers such as `https` and `http2`, how to specify route schemas, and more!

## API Type Documentation

This section is a detailed account of all the types available to you in Fastify version 3.x

All `http`, `https`, and `http2` types are inferred from `@types/node`

Generics are documented by their default value as well as their constraint value(s). Read these articles for more information on TypeScript generics.
- [Generic Parameter Default](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults)
- [Generic Constraints](https://www.typescriptlang.org/docs/handbook/generics.html#generic-constraints)

**Comment by RafaelGSS** [comment]
Good job! Really nice @Ethan-Arrowood.

I have one doubt: 

> `  await reply.send('pong\n')`

why await a non-promise response?

**Comment by Ethan-Arrowood** [comment]
Haha my mistake! I think I originally had just `reply.send` but then switched to `async/await` and forgot I only had to return from the async function instead of using the method. Whoops 🤷‍♀️

**Comment by Ethan-Arrowood** [comment]
https://github.com/Ethan-Arrowood/fastify/blob/typescript-docs/docs/TypeScript.md#getting-started

Holding off on the PR until I get more done!

**Comment by Eomm** [comment]
Done in https://github.com/fastify/fastify/pull/1966
