### ISSUE TITLE
Child is missing from logger interface in TypeScript definitions.

### ISSUE THREAD

**Issue by einnjo** [fastify/fastify#1715]
## 🐛 Bug Report

Cannot create child loggers without circumventing TypeScript due to missing `child` method in the logger interface. The method is there, it's just not typed.

## To Reproduce

```js
   async handler(req: FastifyRequest, reply: FastifyReply<ServerResponse>) => {
      // TS Error: Property child does not exist on type Logger
       req.log.child();
    },
```

## Expected behavior

Child should be present in type Logger.

## Your Environment

- *node version*: 12.4.0
- *fastify version*: 2.5.9
- *os*: Mac

**Comment by Ethan-Arrowood** [comment]
Good find; should be defined. Do you want to send a PR?

**Comment by mcollina** [comment]
We decided not to for a reason.
I would recommend to cast that to an instance of pino instead.

**Comment by einnjo** [comment]
> We decided not to for a reason.
> I would recommend to cast that to an instance of pino instead.

Just sent the PR 😅 , I'll close it then.

**Comment by Ethan-Arrowood** [comment]
I believe I added this in the next types. I’ll make note of this and see what needs updating; I’ll also make a note to add this to a future TypeScript documentation update
