### ISSUE TITLE
Provide proper HTTP cache support

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#1717]
## 🚀 Feature Proposal

While Fastify is a fully working http framework in my opinion it lacks in some basic http caching features:

- Check for response freshness like [`fresh`](https://github.com/jshttp/fresh) package based on `etag` and `if-none-*` headers to avoid sending content twice.

- Automatic `etag` header generation

The plugin [fastify-caching](https://github.com/fastify/fastify-caching) provide that in his own way but it seems very complicated for consumers https://github.com/fastify/fastify-caching/issues/16 and there are some uncommon implementation details.

I see two solution:

1. Provide better and compliant caching plugin
2. Implement it as fastify core feature but this will impact performance.

Personally, I would like to land it like expressjs as a core feature because it is heavily used in the wild and can be assumed by a http framework.

## Motivation

https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2

## Related

https://github.com/fastify/fastify/issues/121

@mcollina 
> Etag support out of the box destroys performance :/. After we have spent time generating a response, our cost has already been paid, and bandwidth is mostly cheap. 304s are better sent from a web server (nginx) or a CDN.

This is true but I would say there are many users which do not maintain a CDN and for ajax requests this doesn't match.

**Comment by mcollina** [comment]
I’m +1 in having this as a plugin. I think it could be be easily implemented, would you like to give it a shot?

The problem with generating etags come from how express implements them: it uses md5 hashing algorithm under the box. Doing this operation tanks Node perf. I’m not sure if there is a more performant algorithm for this, maybe we shuld check how nginx implements this?

**Comment by jsumners** [comment]
The `fastify-caching` plugin matches the goal of Fastify: provide a fast REST framework. Delivering etags for representations is _not the same_ as providing etags for files, e.g. `style.css`. Such work is much better handled by static assets servers and proxies like nginx.

**Comment by StarpTech** [comment]
> Delivering etags for representations is not the same as providing etags for files, e.g. style.css. Such work is much better handled by static assets servers and proxies like nginx.

I agree but I talking about (representations) the use case to deliver html pages or provide a REST API. Has `fastify-caching` not been designed for that?

**Comment by StarpTech** [comment]
@mcollina the common apprach in proxys is to generated the hash based on `Last-Modified` header + content-length.

**Comment by jsumners** [comment]
Yes. And it is left up to the user of the plugin to provide the hashing, or unique id, for the representation. The plugin merely facilitates checking if it has already been cached or not.

**Comment by StarpTech** [comment]
> Yes. And it is left up to the user of the plugin to provide the hashing, or unique id, for the representation. The plugin merely facilitates checking if it has already been cached or not.

This is what I would like to improve. Etag generating and freshness check should happen automatically.

**Comment by delvedor** [comment]
@StarpTech I think you can open a pr to `fastify-caching` (instead of creating a new plugin) and add an option to also generate etgas and freshness checks.
I 100% agree with @mcollina that this feature should live outside core.

Closing the issue since the discussion can continue in https://github.com/fastify/fastify-caching/issues/16.

**Comment by mcollina** [comment]
IMHO I think it’d be extremely good to have another plugin that does exactly as you describe.

**Comment by delvedor** [comment]
> IMHO I think it’d be extremely good to have another plugin that does exactly as you describe.

Maybe I'm missing something.
Why have two plugins? I fear that will lead to confusion.
`fastify-caching` and `fastify-caching-but-with-etag`? 😄

**Comment by mcollina** [comment]
The two things have completely different purposes.

**Comment by mcollina** [comment]
- fastify-caching is currently enabling storing things in a cache for responses that already have an `etag`.
- this-new-plugin will be about generating those etags

The two requirements are cross-cutting concerns, and they both fall under the topic of "http caching". It makes sense to just generate the etags, mainly because it could be used _without_ any other caching mechanism, simply relying on the CDNs/web servers.

**Comment by StarpTech** [comment]
@mcollina thanks for intervention it's right. `fastify-cache` it's a statefull cache store which rely on HTTP caching headers for the keys but it is different from regular http caching. Caching should happen stateless. As mentioned in the linked issue expressjs and koajs provide it for years and this is what we really need in production IMHO.

**Comment by mcollina** [comment]
> As mentioned in the linked issue expressjs and koajs provide it for years and this is what we really need in production IMHO.

In all my experience in putting Node.js applications in production, I think it's not a good approach for deailing with caching: it is a complex matter, and it should not be automated away. Moreover, there a lot of tradeoffs in various solutions, and backing one in the framework seems a bit too far.

I think it would be good to have that as a plugin. How about we call this `fastify-auto-etag`?

**Comment by delvedor** [comment]
`fastify-etag` sounds better.

**Comment by StarpTech** [comment]
> In all my experience in putting Node.js applications in production, I think it's not a good approach for deailing with caching: it is a complex matter, and it should not be automated away. Moreover, there a lot of tradeoffs in various solutions, and backing one in the framework seems a bit too far.

I agree in general but not for etag handling I mentioned. It's a very simple and efficient method to save bandwidth. I vote for the name `fastify-etag` and I propose to rename `fastify-cache` to `fastify-etag-store` because it's confusing.

**Comment by mcollina** [comment]
I've created https://github.com/fastify/fastify-etag to work on this.

**Comment by mcollina** [comment]
@StarpTech @delvedor please review https://github.com/fastify/fastify-etag and open issues.

**Comment by delvedor** [comment]
Closing this one, feel free to reopen if you feel there is still something we need to discuss.
