### ISSUE TITLE
Has anyone tried to instrument New Relic with Fastify?

### ISSUE THREAD

**Issue by romansavchenko** [fastify/fastify#1720]
http://newrelic.github.io/node-newrelic/docs/tutorial-Webframework-Simple.html

It seems like new relic expects a server to be set up more like [Restify or Express](https://github.com/newrelic/node-newrelic/blob/master/lib/instrumentation/restify.js), where the top level object has most of the methods for the server instead of the instance of the server having those methods. 
Anyone have ideas or experience with wrapping Fastify for NewRelic?

[question][discussion]

**Comment by Eomm** [comment]
Personally, I didn't use it before.

Are you working on it? Would you like to share your experience and add `instrumentation` to new relic repo?
For sure if you need help to start we could start together 💪

**Comment by RafaelGSS** [comment]
Hi guys, what do you think about make an example with NewRelic?

**Comment by Eomm** [comment]
Do you know the effort?

I think it could be a good project for fastify/example repo

**Comment by mcollina** [comment]
This was implemented in New Relic

**Comment by A7med-Ragheb** [comment]
@mcollina I still can't see it in the supported list
https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent/#supported-frameworks

Can you please share where newrelic announce that and which version, I installed 7.3.1 and I still see my transactions as normalized uri's *?
