### ISSUE TITLE
Are able to join fastify team ?

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1726]
## 💬 Questions and Help

Reading [here](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md#onboarding-collaborators), the fastify are accepting new members?

If yes, maybe I can be util. I would like to join to fastify team.

Thanks.

**Comment by delvedor** [comment]
Hello! Take a look at [CONTRIBUTING.md](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md) ;)

**Comment by RafaelGSS** [comment]
Hello @delvedor. I checked it, and I also sent the link in issue. Are able for everyone?

**Comment by RafaelGSS** [comment]
I can send the PR with "username, and email to the team you have chosen"?

**Comment by mcollina** [comment]
Hi @RafaelGSS, I would recommend start sending PRs/and fixing bugs first. Take a look at https://github.com/fastify/fastify/issues

**Comment by RafaelGSS** [comment]
Sure.
