### ISSUE TITLE
Joi validation library

### ISSUE THREAD

**Issue by mahmed8003** [fastify/fastify#173]
Can we have [Joi](https://github.com/hapijs/joi) validation library instead of JSON Schema validation? Joi syntax is more concise than JSON schema.
And secondly this can be helpful for Hapi users to convert their Hapi projects to fastify.

**Comment by mcollina** [comment]
Considering the fact that JSON schema is a standard, I prefer Joi more concise API.

I think we should consider adding support for Joi as a schema validator (maybe via a plugin).

**Comment by mahmed8003** [comment]
Another reason

```javascript
static _createValidationSchema() {
        return Joi.object().keys({
            client_id: Joi.string().required(),
            client_secret: Joi.string().required(),
            grant_type: Joi.string().valid('authorization_code', 'refresh_token').required(),
            code: Joi.string().when('grant_type', { is: 'authorization_code', then: Joi.required() }),
            refresh_token: Joi.string().when('grant_type', { is: 'refresh_token', then: Joi.required() })
        });
    }
```

Joi also provides conditional validation, I am not sure if JSON schema validation provides(I am searching) this.

**Comment by allevo** [comment]
@mcollina can this help https://github.com/fastify/fastify/pull/167 ?

**Comment by mcollina** [comment]
@allevo ideally #167 should solve this as well.

**Comment by allevo** [comment]
@mcollina maybe we should study an interface to be able to switch among different validation types

**Comment by delvedor** [comment]
Closed by https://github.com/fastify/fastify/pull/167.
