### ISSUE TITLE
Support ajv-merge-patch

### ISSUE THREAD

**Issue by akaNightmare** [fastify/fastify#1730]
Hello,

I am wondering if there any way to use $merge, $patch custom keywords from the https://github.com/epoberezkin/ajv-merge-patch repo from the box?

Thanks.

**Comment by mcollina** [comment]
You can use `setSchemaCompiler` to pass in your custom instance of Ajv: https://www.fastify.io/docs/latest/Validation-and-Serialization/#schema-compiler.
