### ISSUE TITLE
Lifecycle is not interrupted when onSend executes asynchronously

### ISSUE THREAD

**Issue by ericmacfa** [fastify/fastify#1733]
## 🐛 Bug Report

When an instance `onSend` hook executes asynchronously, responding from a route hook does not always prevent the route handler from being called.

#### Setup

1.  `npm init -y && npm i -S fastify@2.6.0`
2.  Add the code from [this gist](https://gist.github.com/ericmacfa/e5331a632464ec4530c7a42617b67f45) to index.js
    <details>
    <summary>Bare-bones snippet</summary>
    <p>

    ```js
    const fastify = require('fastify')();

    // This issue occurs with both callback and promise based `onSend` hooks
    fastify.addHook('onSend', (request, reply, payload, done) => {
        setTimeout(() => {
            done(null, payload);
        }, 50);
    });
    fastify.route({
        method: 'GET',
        path: '/',
        preHandler: async function(request, reply) {
            console.log('GET / -> preHandler()');
            reply.redirect('/login');
        },
        handler: function(request, reply) {
            console.log('GET / -> handler() !! This should never be shown !!');
            reply.send({ hello: 'world' });
        }
    });
    fastify.route({
        method: 'GET',
        path: '/login',
        handler: function(request, reply) {
            console.log('GET /login -> handler()');
            reply.send('Please log in\n');
        }
    });
    fastify.listen(3000);

    ```

    </p>
    </details>

3.  `node ./index.js`

#### Steps to reproduce

1. `curl -L localhost:3000` (Or via a browser, postman, etc.)
2. Notice that the `/` route handler was called, even though we responded in the `preHandler` hook.
    ```
    server listening on port 3000
    GET / -> preHandler()
    GET / -> handler() !! This should never be shown !!
    GET /login -> handler()
    ```

#### Additional notes (from gist code comments)

-   This issue occurs when either the callback or the promise based `onSend` hook is used.
-   This issue occurs when the promise based `preHandler` hook is used, but not when the callback based version is used.

## Expected behavior

1. `curl -L localhost:3000`
2. The handler for the `/` route should not be called.
    ```
    server listening on port 3000
    GET / -> preHandler()
    GET /login -> handler()
    ```

## Your Environment

-   _node version_: `10.16.0`
-   _fastify version_: `2.6.0`
-   _os_: Mac

**Comment by Eomm** [comment]
Hi,
thank you for reporting. Would you like to give it a shot?

Otherwise, you could apply the following workaround right now:

```js
  preHandler: function (request, reply, next) {
    console.log('GET / -> preHandler()')
    reply.redirect('/login')
    next(new Error('redirect'))
  },
```
NB: this will not trigger the `fastify.setErrorHandler` function 👍

**Comment by ericmacfa** [comment]
I'd like to tale a look, but I'm still wrapping my head around the fastify codebase, so don't wait up for me 😄.  
If I find the source of the bug before someone else opens a PR, then I'll go ahead and submit it 👍
