### ISSUE TITLE
Why is reply.request not documented?

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1734]
Like in the title. I was looking for a way to use `decorateReply`, but still have access to the `Request` object. I didn't see any information in the `Reply` documentation, so I started digging and doing some `console.log`s, and actually, there IS a `Request` object under `reply.request`. So my question is: is it not documented by purpose (maybe because it's not a good practice to use it), or just an oversight?

`fastify@2.3.0`

**Comment by Eomm** [comment]
I think that documenting it could be noisy because where you have the replay object, you have also the request itself and that `reply.request` is the same instance.

It is not clear to me the use case for `decorateReply`, could you argue more?

**Comment by sarneeh** [comment]
@Eomm I wanted to make use of [send](https://github.com/pillarjs/send) which needs Node's Request and Response object to process. Actually, it's also being used the same way in `fastify-static`:

https://github.com/fastify/fastify-static/blob/0e48bf2d219a984b81f328c37352bf0d26fc047a/index.js#L107-L109

**Comment by Eomm** [comment]
I understand now, thank you 👍
I change my mind: if it already used in other plugins we should document it and provide support for it.
There are also tests that cover that property.

Before I was meaing that a user, without checking the code, could add a decorator that accept the request as a parameter (for sure this solution is less elegant).

**Comment by delvedor** [comment]
I'm not sure if is not documented on purpose or we just missed it. @mcollina do you recall something?

**Comment by mcollina** [comment]
I think we should just document that at this point.

**Comment by francisbrito** [comment]
Hello,

I too realized this while building a plugin for paginating responses. I think it would make sense to add TypeScript definitions for the field also.

Is it OK if I write-up a PR for adding the documentation and type definitions of this field?

**Comment by mcollina** [comment]
please do!

Il giorno ven 9 ago 2019 alle 19:48 Francis Brito <notifications@github.com>
ha scritto:

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1792 .
