### ISSUE TITLE
What about cpp code in router http ?

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1736]
## 🚀 Feature Proposal

I thinking about writing the HTTP router in C++ Addons to improve performance of fastify.

I can make some tests with it. (Maybe, the C++ Addon can be not has more performance than actual coded)

## Motivation

Following the motivation of Fastify - Fast and low overhead framework http.

**Comment by RafaelGSS** [comment]
But, the point is: 

- The fastify really needs it?
- Can be another repo like plugin. And send it in fastify instance instead of _find-my-way_:
```
const router = require('addon-http')
const fastify = require('fastify')({ router })
```

**Comment by Ethan-Arrowood** [comment]
Hi @RafaelGSS this seems like a cool idea; however, as I understand it, the _find-my-way_ router is the so-called "secret-sauce" of Fastify. The radix tree routing algorithm is a part of what makes Fastify faster than other libraries such as Express and Hapi. The other key part of Fastify is it's plugin based design (which is powered by [Avvio](https://github.com/mcollina/avvio)).

Because of its plugin-based design I could see how passing in a custom router could theoretically fit into the Fastify motivations.

@fastify/leads will surely have more context to share about this.

**Comment by corbinu** [comment]
@RafaelGSS Maye a wrinkle how would you feel about working with me to port find-my-way into Rust. That way it could be easily loaded into fastify as WASM?

**Comment by mcollina** [comment]
You'd need to match the find-my-way API in this new module. I think you could:

1. implement the radix-prefix-tree in Rust, similar to how we do things in find-my-way
2. store the JS objects that identifies a route (function, context object, etc), in a side map/array and have the radis-prefix-tree return indexes to be looked up there.

The problem with this approach is that the transition cost between JS and WASM _might_ be too much. Using a napi addon might still be _too costly_ if the number of routes are low.

**Comment by delvedor** [comment]
I agree with everything @mcollina said. Plus, I don't think we should ship with a native dependency by default.
Anyhow, the routing provides good performances already, our "bottleneck" is the body parsing and the validation (which is quite fast already).

**Comment by RafaelGSS** [comment]
> @RafaelGSS Maye a wrinkle how would you feel about working with me to port find-my-way into Rust. That way it could be easily loaded into fastify as WASM?

Sounds good. @corbinu. Just for tests

> The problem with this approach is that the transition cost between JS and WASM might be too much. Using a napi addon might still be too costly if the number of routes are low.

@mcollina  Yeah, I understand it, the V8 often turns out to be faster than a WASM, just because the transition has some cost. But provide it like a plugin like an example above, can be util for the application that uses many routes?

> Anyhow, the routing provides good performances already, our "bottleneck" is the body parsing and the validation (which is quite fast already).

@delvedor Well, do not you see something in which compilation for a native code can help in fastify? I'll make some tests with [this schema](https://github.com/pboettch/json-schema-validator) and pass the `.node` to `schemaCompiler`. Do you think than can help more than _ajv_ ?

**Comment by jsumners** [comment]
I am staunchly against shipping a native dependency by default.

**Comment by StarpTech** [comment]
@RafaelGSS Preoptimization is the root of all evil. What's the issue here? Why do you think that the current performance has to be improved? What's your use case?

**Comment by RafaelGSS** [comment]
Hi @StarpTech 
I don't have anyone use case, I just create this discussion for maybe help the fastify.
If the fastify phase is: "Fast", I just have some ideas.
