### ISSUE TITLE
Feature request: Typescript definitions

### ISSUE THREAD

**Issue by 19majkel94** [fastify/fastify#174]
In node.js world type-safe is far more important than in browsers world.

It would be really nice if you provide types definition (*d.ts) for this great framework, as it is done for express or koa 😉

**Comment by mcollina** [comment]
Would you like to contribute those? There is no typescript user in this organization.

**Comment by 19majkel94** [comment]
Oh, what a pity 😞 I was planing to develop a fastify driver for [routing-controllers](https://github.com/pleerock/routing-controllers) and the typings would be really helpful.

BTW, it is weird that in 2017 we build type-safe frontend apps with Angular/Typescript and React/Flow but backend it's still so ES5 that we have to jump through the docs to find "what is the replacement for express's res.json" instead of having intellisense and can quickly read JSDoc in IDE that `reply.send` can handle JSON too 😆

**Comment by mcollina** [comment]
Send a PR!

**Comment by StarpTech** [comment]
@19majkel94 Your statement about the present is complete nonsense. Javascript is by nature a dynamically typed language and that's fine. Frontend development and backend development are still two pairs of shoes and have in mind that

> Type correctness does not guarantee program correctness.

Send a PR and everybody is happy.

**Comment by 19majkel94** [comment]
> Type correctness does not guarantee program correctness.

But it prevent plenty of bugs like typos or missassumptions about runtime types (comparing string to number) as you get instant red alert in IDE/terminal, give great and safe refactoring possibility, improve dev experience on everyday codding with autocomplete or jump to declaration/definition/etc and also serve as a documentation with intellisense and JSDoc.

Types in TypeScript is not like Java bloated with types everywhere. Type inference works great so you won't have to annotate every line of code, it just work as a JavaScript with a better linter 😉 
Many libraries authors had seen this features and switched their codebase to TS, you too can give it a chance:
https://medium.freecodecamp.org/its-time-to-give-typescript-another-chance-2caaf7fabe61

> Send a PR and everybody is happy.

Fastify is still in development, so who would then sync the code with definition? You said that there is no TS dev in the team. So probably I should send it then to the [types repository](https://github.com/DefinitelyTyped/DefinitelyTyped) to let community contribute, just like it's happening with express typings.

**Comment by mcollina** [comment]
I would prefer to have the type definitions on this repo. However, considering the current plugin model, I'm not sure that having plugins adding methods to the prototype of Request and Reply could be mapped by TS.

**Comment by 19majkel94** [comment]
> I'm not sure that having plugins adding methods to the prototype of Request and Reply could be mapped by TS.

No problem - this works very well thanks to declarations merging. The plugin modules has to declare the enhanced properties or methods which they added, just like e.g. express-session:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-session/index.d.ts

**Comment by mcollina** [comment]
If you would like to send a PR and help maintaining this, I'm more than happy to merge.

**Comment by jsumners** [comment]
@19majkel94 there aren't any TypeScript people in the project because the project was started by people who care about performance. Transpiling is antithetical to performance.

Personal opinion: I wish people would stop transpiling at all.

**Comment by 19majkel94** [comment]
> Transpiling is antithetical to performance.

Oh, interesting. Could you describe the problem in more details? Paste some links to researches and benchmarks?

In TypeScript you can write in ES3, ES5, ES2016 or whatever you want. And TypeScript is not like a CofeeScript with his own syntax which needs to be transpiled. All you need to do with TypeScript transpilation is stripping off types annotation, so:
```ts
function add(a: number, b: number): number {
  return a + b;
}
```
would become:
```js
function add(a, b) {
  return a + b;
}
```
which would make the code be able to run on node.js as it's a valid JS. It's not as you think, that typescript compiler will output something like this:
```js
!function(t){function e(r){if(n[r])return n[r].exports;var i=n[r]={exports:{},id:r,loaded:!1};return t[r].call(i.exports,i,i.exports,e),i.loaded=!0,i.exports}var n={};return e.m=t,e.c=n,e.p="",e(0)}(function(t){for(var e in t)if(Object.prototype.hasOwnProperty.call(t,e))switch(typeof t[e]){case"function":break;case"object":t[e]=function(e){var n=e.slice(1),r=t[e[0]];return function(t,e,i){r.apply(this,[t,e,i].concat(n))}}(t[e]);break;default:t[e]=t[t[e]]}return t}
```

**Comment by mcollina** [comment]
I do not want this to become a discussion about TypeScript. Each one of us has its own preference.

I am not a TypeScript user, and I share @jsumners concerns about performance. However, I think we should do our best to support TypeScript users! None of us is using TypeScript, so it's probably better if someone else join the team and help maintaining the typescript definition.

**Comment by jsumners** [comment]
> I am not a TypeScript user, and I share @jsumners concerns about performance. However, I think we should do our best to support TypeScript users! None of us is using TypeScript, so it's probably better if someone else join the team and help maintaining the typescript definition.

I wasn't disagreeing that they should be added by someone who wishes to maintain them. Just clarifying why since https://github.com/fastify/fastify/issues/174#issuecomment-327291373 was basically a "convert to TS and be enlightened" pitch.

**Comment by evanshortiss** [comment]
@mcollina @19majkel94  I playing with fastify to test it and wanted some definitions. I just opened a PR with what I have as a start. It is missing some options and maybe other pieces but makes a nice starting point I believe. PR is #182

**Comment by delvedor** [comment]
Closed by https://github.com/fastify/fastify/pull/182.
