### ISSUE TITLE
Status code on return

### ISSUE THREAD

**Issue by kharandziuk** [fastify/fastify#1746]
## 🐛 Bug Report
Can't set a status code like described here:
https://github.com/fastify/fastify/blob/master/docs/Reply.md#async-await-and-promises

or maybe the documentation is misleading. Everything work with send  
## To Reproduce

```js
fastify.get('/async-await', options, async function (request, reply) {
  var res = await new Promise(function (resolve) {
    setTimeout(resolve, 401, { error: 'unauthorized' })
  })
  return res
})

```

## Expected behavior

expect status code 401, but receive 200

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by StarpTech** [comment]
Hi @kharandziuk the example is wrong would you like to send a PR? You can only return the final payload not the status code. We should also show two examples one with `reejct` and one with `resolve`:

```js
fastify.get('/async-await', options, async function (request, reply) {
  var res = await new Promise(function (resolve, reject) {
    setTimeout(() => reject({ statusCode: 401, message: 'unauthorized' }), 100)
    // or
    // reply.code(401)
    // setTimeout(() => reject({ hello: 'unauthorized' }), 100)
  })
  return res
})
fastify.get('/async-await', options, async function (request, reply) {
  var res = await new Promise(function (resolve) {
    reply.code(201);
    setTimeout(() => resolve({ hello: 'world' }), 100)
  })
  return res
})
```

**Comment by delvedor** [comment]
Hello! Thee documentation is correct, I agree that we can make it a little bit more explicit.
In the meantime, I suggest you take a look to the [`setTimeout`](https://developer.mozilla.org/ro/docs/Web/API/window.setTimeout) documentation, it might help you better understand what's happening there :)

**Comment by kharandziuk** [comment]
@delvedor you are right documentation is correct. it's my bad.  But... on a glance, it doesn't feel like correct.
Obviously, I just copy-pasted the example and after that tried to change the status code(number 200) without thinking about the overall construction.

I would prefer to have everything simpler 
```
fastify.get('/async-await', options, async function (request, reply) {
  reply.code(201)
  var res = await Promise.resolve({ hello: 'world' })
  return res
})

fastify.get('/async-await', options, async function (request, reply) {
  await Promise.reject({ statusCode: 401, message: 'unauthorized' }) // we don't need to return anything here, right?
})
```

but it's up to you guys. I can create a PR, or you can just close the issue

**Comment by kharandziuk** [comment]
also, looks like my second  example is wrong btw

**Comment by StarpTech** [comment]
@delvedor it's not. It's very confusing to use a status code as timeout value :confused: that's why we are here.

**Comment by mcollina** [comment]
I think it's very confusing. We should not use `setTimeout` at all, but rather use `const sleep = promisify(setTimeout)` instead.

This would clarify all the examples, and it would encourage a best practice (never use `new Promise`).
Would you like to send a PR?

**Comment by kharandziuk** [comment]
@mcollina we can resolve it and link to https://github.com/fastify/fastify/pull/1751

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1751.

**Comment by valentinradu** [comment]
@delvedor Sorry to bring this back up. But one thing that's not clear at the moment (I think) is how would one handle a successful response in an `async` context. Is `await` everything then call `reply.code(201)` the way to go?
