### ISSUE TITLE
Fastify timeout route ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1755]
## 💬 Questions and Help

In my work, I have some hard processing data inside the database and may take more than 2 minutes. Something like:

```
fastify.get('/anyRoute', { schema },
    async function ({ query }, reply) {
      const repository = lightningRepository(this.mongo.db)

      try {
        const dataPromisse = repository.getSomethingHard(query.anyParam)

        const [data, totalRecords] = await Promise.all([
          dataPromisse.skip(perPage * (page - 1)).limit(perPage).toArray(),
          dataPromisse.count()]
        )

        reply.success(data, { totalRecords, page, perPage })
      } catch ({ message }) {
        reply.error({ message })
      }
    })
```

And I receive the ERR_EMPTY_RESPONSE in chrome, I think because the process takes a long time.

## Reproduce code
```
'use strict'

const fastify = require('fastify')({
  logger: true
})

fastify
  .get('/', function (req, reply) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve()
        reply.send({ ok: true })
      }, 140000)
    })
  })

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```
- This is expected ?

- I took a look at [this](https://github.com/fastify/fastify-server-timeout) plugin, but I did not test yet. I think about configuring the server timeout (if that's the problem). What do you think?

**Comment by delvedor** [comment]
Yes, it's expected, you can use [fastify-server-timeout](https://github.com/fastify/fastify-server-timeout) to solve your issue :)
