### ISSUE TITLE
discuss: plugin ownership, package scope, evolution of project

### ISSUE THREAD

**Issue by knksmith57** [fastify/fastify#176]
hey y'all!

first, thank you. love this project and the value statement; I started using fastify for small side projects a few releases back and believe it has potential to be _the_ goto JSON API framework.

I'd like to spark a conversation around evolution of the project; specifically, I'm looking for feedback from maintainers regarding ownership and control of plugins and moving to a [scope](https://docs.npmjs.com/misc/scope) for components maintained by the core team.

briefly:

Given the [adopted plugin architecture](https://github.com/fastify/fastify/blob/master/docs/Plugins.md) and desire to [keep core small and focused](https://github.com/fastify/fastify/issues/159), plugins will be critical to fastify's success and adoption. I'm wondering how y'all feel about taking control of the `@fastify` scope on npm and using it to host packages (including plugins) that are authored and maintained by fastify contributors.

A few reasons why I think this could be a good idea:
1. using `fastify-` prefixed package names means anyone can squat or clobber packages. While this lowers the barrier to entry for outside contributors, it leaves the project vulnerable to namespace pollution and unintended influence (more on that later). A bad actor could claim `fastify-static`, `fastify-logger`, and `fastify-error` right now and y'all wouldn't be able to do much about it. It's always possible to start out as a `fastify-` package and migrate to `@fastify/` tho, and that may be a good way to keep the barrier low without sacrificing the other perks discussed next.
2. npm provides excellent facilities for managing scopes. granting publish permissions is easy and distributed control means the project isn't stonewalled if the sole owner of `fastify-importantThing` falls off the grid.
3. Owner of `fastify-importantThing` could, hypothetically and in good faith, code against current private fastify APIs (eg: `._Reply`). If enough people started relying on the package and core wished to make a change that would yield a 10x speedup at the cost of breaking the `._Reply` property access, `fastify` would be faced with a hard choice: break the ecosystem and upset a lot of people or _don't_ make that change and forgo a valuable optimization. publishing under `@fastify/` obviates the dilemma entirely.

Just a few thoughts. would love to discuss more when y'all have time. Thanks!

**Comment by delvedor** [comment]
Hi!
First of all thank you for the interest and the super interesting point of discussion, very much appreciated.

Honestly I didn't thought about your examples for the `fastify-*` names, and the npm scope seems a good solution to solve the issue, we already have the [organization](https://www.npmjs.com/org/fastify) also in npm.

Regarding the internal apis I think we should redact a document or update the [guide](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md) to warn user to **not** use private apis and every variable that starts with the *underscore*, because we could change them at any time. I don't want something like *node/lodash* happen.

We must definitely discuss over your points, again, thanks a lot!

**Comment by mcollina** [comment]
@knksmith57 Thanks so much for checking out Fastify and for your report!!

> using fastify- prefixed package names means anyone can squat or clobber packages. While this lowers the barrier to entry for outside contributors, it leaves the project vulnerable to namespace pollution and unintended influence (more on that later). A bad actor could claim fastify-static, fastify-logger, and fastify-error right now and y'all wouldn't be able to do much about it. It's always possible to start out as a fastify- package and migrate to @fastify/ tho, and that may be a good way to keep the barrier low without sacrificing the other perks discussed next.

The problem with publishing things under the fastify organization is discoverability. Scoped modules are not easily found by NPM searches. A bad actor could do the same for every major framework or module.

> npm provides excellent facilities for managing scopes. granting publish permissions is easy and distributed control means the project isn't stonewalled if the sole owner of fastify-importantThing falls off the grid.

I think we should do that. If we are not, we definitely should at least for the packages in the github org.
@allevo can you please add fastify-accepts and fastify-static to the npm org? I've added you as an admin.

> Owner of fastify-importantThing could, hypothetically and in good faith, code against current private fastify APIs (eg: ._Reply). If enough people started relying on the package and core wished to make a change that would yield a 10x speedup at the cost of breaking the ._Reply property access, fastify would be faced with a hard choice: break the ecosystem and upset a lot of people or don't make that change and forgo a valuable optimization. publishing under @fastify/ obviates the dilemma entirely.

I disagree that publishing under @fastify/ solves the problem. If someone codes against private API, it will create problems independently of where it happens - we might be able to update things ourselves, but it will still be a lot of chore. We should really make it **hard** to do so, maybe migrating `_Reply` to a `Symbol` for instance. Do you want to help and send a PR?

**Comment by knksmith57** [comment]
Hey @mcollina! Thanks for chiming in. Already super pleased that y'all have given some thought to the conversation.

I'll admit that using scoped packages isn't exactly mainstream. Keeping the concepts of authority and control top-of-mind was the main intent of this thread, and I think we've accomplished that; moving `fastify-accepts` and `fastify-static` to the npm org is a great start and the [public `@fastify` org page is already a great discovery tool](https://www.npmjs.com/org/fastify).

With that, If I may, a few follow-ups and responses to your, err, responses 😀:
> The problem with publishing things under the fastify organization is discoverability. Scoped modules are not easily found by NPM searches. A bad actor could do the same for every major framework or module.

So if I'm hearing you correctly, there are two discrete concerns here:
1. scoped packages are hard to find from cold searches on npm
2. there's nothing stopping bad actors from grabbing scopes for popular frameworks or modules

I think #.1 used to be very true and I shared this concern for a long time. Since the https://npms.io launch and [integration work began](http://blog.npmjs.org/post/156076312840/search-update) tho, I've noticed a dramatic improvement.

FWIW cold starts (user has never heard of fastify) using a scope might prove to be _better_ for discoverability purely based on mechanics; `fastify/server` for example, loosely deconstructs to `scope=fastify query=server`.

For warm starts (where users already know about fastify) it is demonstrably better as npm search has first class support for scope search operators. (see [`scope:angular`](https://npms.io/search?q=scope%3Aangular) vs [`angular`](https://npms.io/search?q=angular))

Re: #.2 that's very true. I liken package names to domain names; early bird gets the worm. You own `@fastify`, so there's no need to do this now (or ever), but at least you _can_ do it. If in the future you decide to use scopes, you've already defended against the one thing that no bad actor will ever be able to take away from you and that's the namespace `@fastify/`. [Hapi has done the same thing](https://www.npmjs.com/org/hapi). As have [koa](https://www.npmjs.com/org/koa) and [lodash](https://www.npmjs.com/org/lodash). Express? [not so much](https://www.npmjs.com/org/express). namesquatting and typosquatting have always been a problem on npm.

> I disagree that publishing under @fastify/ solves the problem. If someone codes against private API, it will create problems independently of where it happens

To be clear, publishing under `@fastify/` doesn't solve the problem of preventing people from coding against private APIs; you're absolutely correct, as long as they exist people can (and ultimately will) abuse them.

The problem it _does_ solve is driving adoption and influencing developer behavior. If there is a clear and low-friction path for developers to submit and publish new plugins _or_ to promote a userland `fastify-` package to `@fastify/`, that process can include simple checks and balances to stop these mistakes before they become real problems. [DefinitelyTyped w/ over 16k PRs](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls) is a compelling example of a hugely successful project that uses scoped packages, is entirely driven by ICs and still maintains a quality control process.

> Do you want to help and send a PR?

I'd love to! Let me spin on that for a few days. I would love to become more involved with the project.

Finally, y'all should scoop up https://fastifyjs.com. with that shiny new doc site in the works, a vanity domain  on `.com` would reflect well on the project.

**Comment by allevo** [comment]
@mcollina `fastify-static`, `fastify-accepts`, `fastify-accepts-serializer` moved under `@fastify` org.

**Comment by jsumners** [comment]
I disagree with using the `@fastify/` mechanism for the same reason as @mcollina: discoverability. Also, they are more cumbersome to use in projects. It may seem trivial, but typing `require('fastify-bearer-auth')` is easier than typing `require('@fastify/fastify-bearer-auth')`.

Over in Pino land we simply advertise that we are willing to add plugins to the organization if the author desires it. The plugin author still retains full control over their plugin once it is in the organization.

**Comment by NoNameProvided** [comment]
> It may seem trivial, but typing require('fastify-bearer-auth') is easier than typing require('@fastify/fastify-bearer-auth')

You can use `require('@fastify/bearer-auth')`.

**Comment by jsumners** [comment]
@NoNameProvided it's still more cumbersome.

**Comment by delvedor** [comment]
How about keep a list of *trusted* plugins inside our repository?
Then a plugin creator just need to open a pr or tweet to us and we'll update the list.

**Comment by mcollina** [comment]
@delvedor and myelf have just divided the packages on the fastify team on npm in

1. ecosystem modules, maintained by the **developers** team (everybody in the npm org)
2. fastify itself and dependants modules, mainteind by the **core** team (currently @delvedor and myself)

**Comment by mcollina** [comment]
I think this should be closed.
