### ISSUE TITLE
Schema validation error handling

### ISSUE THREAD

**Issue by treykaws** [fastify/fastify#1760]
I thought this would be the best place to ask this question but if it is not feel free to lock it and tell me to skedaddle.

I am looking for a cleaner solution to dealing with validation errors with requests that have multiple requirements. For instance I have 2 patterns that need to be matched via RegEx defined in the schema. Customizing the error for each one has proven to not be clean. What would be the recommended way to approach this?

Could it be possible to have an error property in the schema validator that is optional to improve flexibility in this regard?

**Comment by Eomm** [comment]
Hi,
I think https://github.com/Eomm/fastify-schema-constraint/ fits your needs

Using standard json schema you can choose to apply the validation or not based on your business logic

**Comment by treykaws** [comment]
> Hi,
> I think https://github.com/Eomm/fastify-schema-constraint/ fits your needs
> 
> Using standard json schema you can choose to apply the validation or not based on your business logic

Hi Eomm,

Thanks for the suggestion. I will take a look at fastify-schema-constraint to see if I can leverage it for my use case. I will be back here to let you know how it works.
