### ISSUE TITLE
how can I diagnose ajv validation error in custom error handler 

### ISSUE THREAD

**Issue by mohammad-khooie** [fastify/fastify#1761]
Hi 
I want to diagnose ajv validation error in my custom error handler 
this is first way that I test 
I add this if block in my custom error handler 
`
if(err instanceof Ajv.ValidationError){  do some things  }
`
but its dosent work for me
whats the best way?

fastify 2.6.0

**Comment by Eomm** [comment]
Hi, why did you close the issue? Do you have found a solution?

**Comment by mohammad-khooie** [comment]
Hi I decided to move this issue to fastify/help repo 
however I did not get my answer
so I decide to re open the issue
thanks for for your attention
