### ISSUE TITLE
Missing `.catch`?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1763]
https://github.com/fastify/fastify/blob/421f214e55f0878317a22a331053ba8937498a28/fastify.js#L306

Is this missing a `.catch` for a reason?

**Comment by mcollina** [comment]
We return the promise, there is no need fo catching there.

Il giorno lun 22 lug 2019 alle 14:21 James Sumners <notifications@github.com>
ha scritto:

**Comment by jsumners** [comment]
What ultimately ends up handling that promise? I am debugging an update from Fastify v1 to Fastify v2 and adding the following there really helped me:

```js
.catch(err => {
  console.log(err)
  throw err
})
```

**Comment by mcollina** [comment]
when you do `await fastify.inject()`, you'll see that error bubble up.
