### ISSUE TITLE
It waste a lot of time in pre-commit hooks

### ISSUE THREAD

**Issue by xtx1130** [fastify/fastify#1769]
## 🚀 Feature Proposal

It will waste a lot of time in pre-commit hooks when I want to submit code. I think we can just run the important test cases in pre-commit

## Motivation

Improve submit efficiency

## Example

```js
// package.json
{
  "scripts": {
    "unit:commit" : "tap -J test/internals/*.test.js"
  },
  "pre-commit": "unit:commit"
}
```

**Comment by Eomm** [comment]
You could use the `-n` flag to skip the pre-commit hooks: `git commit -nm 'my comment``

**Comment by mcollina** [comment]
I disagree, the checks are there to verify the linting and other things -
pushing those checks to CI is just a waste of resources.

Il giorno ven 26 lug 2019 alle 08:33 Manuel Spigolon <
notifications@github.com> ha scritto:

**Comment by delvedor** [comment]
I agree with @mcollina. If you really need to skip them, as said by @Eomm, you can use `-n`.

Usually what I do is to run the hook only for the first commit I need to send:
```sh
git add lib
git commit -m "new stuff"
# test...
git add test
git commit -m "added test" -n
git add docs
git commit -m "added docs" -n
```

**Comment by delvedor** [comment]
Closing the issue as this behavior will not change, thank you anyway for the proposal and contributing to the project!
I hope our answers are helpful :)

**Comment by xtx1130** [comment]
Thanks for your advice!
