### ISSUE TITLE
diagnose ajv validation error in my custom error handler

### ISSUE THREAD

**Issue by mohammad-khooie** [fastify/fastify#1773]
Hi
I want to diagnose ajv validation error in my custom error handler
this is first way that I test
I add this if block in my custom error handler
if(err instanceof Ajv.ValidationError){ do some things }
but its dosent work for me
whats the best solution?

node version: 10
fastify version: 2.6.0
os: Windows

**Comment by RafaelGSS** [comment]
Can you provide a code reproduction?

**Comment by mohammad-khooie** [comment]
this is my error handler class
```
class ErrorUtil {
    static handleError( err, req, reply ) {
        if ( err instanceof ClientError ) {
            reply
                .status( err.responseStatusCode )
                .send( {
                    "success": false,
                    ...err.getErrorObj()
                } );
        } else if ( err instanceof SequelizeValidationError || errinstanceofSequelizeUniqueConstraintError) {
            const errMessages = [];
            
            for ( let errObj of err.errors ) {
                errMessages.push( errObj.message );
            }
            const clientError = new ClientError( errMessages, 409 );

            reply
                .status( clientError.responseStatusCode )
                .send( {
                    "success": false,
                    ...clientError.getErrorObj()
                } );
        } else if ( err instanceof Ajv.ValidationError ) {
            reply
                .status( 400 )
                .send( {
                    "success": false,
                    err
                } );

        } else {
            console.log( err );
            reply
                .status( 500 )
                .send( {
                    "success": false,
                    err
                } );
        }
    }
    static throwClientError( err, responseStatusCode ) {
        throw new ClientError( err, responseStatusCode );
    }
}
```
and this is set error handler code
```
fastify.setErrorHandler( ( err, req, reply ) => {
        fastify.errorUtil.handleError( err, req, reply );
    } );
```

**Comment by Eomm** [comment]
Would you mind to provide a complete and minimal reproducible case?
This will speed up us to give you help 👍

Anyway if I have understood this is what is expected:

```
const Fastify = require('fastify')
const fastify = Fastify({ logger: true })

fastify.setErrorHandler((err, req, reply) => {
  // Is this Ajv.ValidationError?
  reply.send(err.constructor.name)
})

fastify.get('/', { schema: { body: { type: 'object' } } }, async () => { return 'hi' })
fastify.listen(3000)
```

But the AJV-errors are managed here, wrapping in a generic `Error`

https://github.com/fastify/fastify/blob/c1cf60486fd722c5ce07460ee3cc03ab81a25fbf/lib/validation.js#L119

I must check if there is some workaround using custom `schemaCompiler`

**Comment by mohammad-khooie** [comment]
I guessed that fastify wrap ajv error but why?
also I can not use attachValidation and catch ajv validation error in my handler because I have some 
hooks that need some property that should be validated first
anyway I would be  so happy if you give me a solution
thanks

**Comment by Eomm** [comment]
@mohammad-khooie There are many ways to do it really.

One of those is wrapping the validation:

```
const Ajv = require('ajv')

module.exports = function (f, opts, next) {

  f.setErrorHandler(function (error, request, reply) {
    console.log(error instanceof Ajv.ValidationError); // will print true
  })

  f.setSchemaCompiler(function (schema) {
    const ajv = new Ajv({
      coerceTypes: true,
      useDefaults: true,
      removeAdditional: true,
      allErrors: true,
      nullable: true
    })
    // this is the validate function that is being to use
    const validate = ajv.compile(schema)

    return (data) => {
      validate(data)
      // TODO manage the results
      return {
        error: new Ajv.ValidationError('wooo'),
      }
    }
  })

  f.get('/:id', {
    schema: {
      params: {
        type: 'object',
        properties: {
          id: {
            type: 'number'
          }
        }
      }
    }
  }, (request, reply) => { reply.send({ answer: 42 }) })

  next()
}
```

Otherwise, you could create a plugin for this purpose.
The plugin should:

1. listen to the `onRoute` hook
1. for the route that is being created and:
    1. delete the `.schema` key
    1. create an ajv instance using the schema just removed
    1. add a `preValidation` hooks that use the ajv instance and trigger the custom error

In this way, you will build a plugin you can reuse in future.

> I guessed that fastify wrap ajv error but why?

I think it is to remain agnostic since the `validate` function can be customized.
