### ISSUE TITLE
async preValidation hook does not abort request

### ISSUE THREAD

**Issue by tobspr** [fastify/fastify#1776]
## 🐛 Bug Report

When calling `reply.send` within an async preValidation hook, this does not abort the request and thus emits a `Response has already been sent` error. Related: #677

According to the linked issue and pr, it should have been fixed, however it doesn't seem to be (At least for me):

## To Reproduce

Hook:
```js
fastify.addHook("preValidation", async function (request, reply) {
  reply.code(403).send({error: "unauthenticated"});
});
```
Handler:
```js
module.exports = function (fastify, opts, next) {
   fastify.get("/", {}, async (request, reply) => {
       // This gets still executed, and reply.sent is true here
   });
   next();
}
 ```

## Expected behavior

The handler should not get called.

## Your Environment

- *node version*: 10.16.0
- *fastify version*: >=2.5.0
- *os*: Windows, Linux

**Comment by mcollina** [comment]
Would you mind uploading a full example? That use case is currently covered by our unit tests, so maybe there is something off somewhere else.

**Comment by SerayaEryn** [comment]
This might be the same problem as reported with #1733.

**Comment by tobspr** [comment]
Thank you for the quick fix! Any plans when it will be included in an official release?
