### ISSUE TITLE
How do you determine the protocol schema (i.e. http / https) from request object?

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify#1777]
Is there a way of knowing the protocol schema from the request object? I would like to know whether a request is http or https.

At the moment I assume that all requests are https unless specified as http in an environment variable to the process.

I use this for example to fetch templates from other sources.

```
await fetch(`${env.http || 'https'}://${req.headers.host}${env.path}/views/desktop.html`)
```

I could possible use an URL parameter to define the protocol schema but ideally I would like to use the request object.

**Comment by mcollina** [comment]
I don't understand the problem. Are you executing `fetch()` in the browser? inside Node.js? Can you articulate your use case a bit more?

**Comment by dbauszus-glx** [comment]
Inside the handler in node I try to fetch the html template.

I have now solved the problem like so but feel that this is not the most elegant solution.

```
  let _tmpl;

  try {
    _tmpl = (md.mobile() === null || md.tablet() !== null) ?
      await fetch(`https://${req.headers.host}${env.path}/views/desktop.html`) :
      await fetch(`https://${req.headers.host}${env.path}/views/mobile.html`);

  } catch (err) {
    _tmpl = (md.mobile() === null || md.tablet() !== null) ?
      await fetch(`http://${req.headers.host}${env.path}/views/desktop.html`) :
      await fetch(`http://${req.headers.host}${env.path}/views/mobile.html`);
  }
```

Here I try to fetch from https and if that fails try to fetch from http.

I would like to check whether the request object which is passed into the handler does know whether the protocol is http or https.

**Comment by mcollina** [comment]
I think this is the wrong approach. You should not be calling your Node.js process from the same process. Also, check out https://www.fastify.io/docs/latest/Testing/#inject.

**Comment by jsumners** [comment]
The process is either a TLS enabled process or it isn't. The only information available on the request is the parsed URL from the received header. This is typically in the format `GET /foo?bar=baz`. So when it is parsed the result is `protocol: null`. See https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_message_url
