### ISSUE TITLE
fastify should be peerDependencies of its plugins

### ISSUE THREAD

**Issue by thynson** [fastify/fastify#1780]
## 🐛 Bug Report

This is not a bug of fastify itself, but many fastify plugin packages maintained by this orgnization. In most situation plugin packages are installed together with fastify itself, and works well when they're installed by npm.
However, when used inside [pnpm] workspace, plugin packages cannot require fastify pacakge.
To properly fix this bug, these plugin packages, including but not limited to fastify-cors, fastify-websocket, fastify-multipart, need to add fastify to their peer dependencies.

## To Reproduce

Here is a minimal pnpm workspace can reproduce the issue. [fastify-pnpm-workspace.zip](https://github.com/fastify/fastify/files/3456915/fastify-pnpm-workspace.zip).
Unzip it and follow the README to install packages then run the script, warning will be alerted.

## Expected behavior

No warning printed at all

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac
- *any other relevant information*

[pnpm]:https://github.com/pnpm/pnpm

**Comment by jsumners** [comment]
The issue is in `fastify-plugin` -- https://github.com/fastify/fastify-plugin/blob/3d3ca8cf67c431528fd4f6709ec6792608159f54/index.js#L57-L62

I have ignored it for literal years now. It's just a console message that means nothing.

At least, I assume that is what you are talking about. You haven't provided a full description of the issue and I'm not going to download a random zip file when a GitHub repo could be supplied.

**Comment by delvedor** [comment]
Fastify is a development dependency of our plugins. If you install them with `--production` you will not encounter any issue.

**Comment by thynson** [comment]
@jsumners pnpm use fancy links to organize the node_modules, so plugin packages cannot require fastify even if you already install them. I'm trying to use fasitify in a monorepo managed by pnpm workspace, and I encounter bugs due to this reason.

**Comment by thynson** [comment]
I see that all plugins depends on fastify-plugin, so only fastify-plugin need to be fixed.

**Comment by jsumners** [comment]
I am aware of how pnpm works. It is my primary package manager. I have encountered no other issue that `fastify-plugin` not being able to detect that `fastify` is in the scope of Node's `require` function even though it actually is. If you are encountering actual bugs, i.e. functionality not working, please describe them.

**Comment by thynson** [comment]
@jsumners, Hmm, still digging my bug, but seems not related to this one.

**Comment by mcollina** [comment]
@jsumners I think we should be moving that check into fastify itself for v3. Would you mind opening an issue about that?

**Comment by jsumners** [comment]
Sure. Will get to it soon.

**Comment by delvedor** [comment]
What's the status of this one?

**Comment by mcollina** [comment]
I would just change fastify-plugin to use this pattern: https://github.com/pinojs/pino/pull/699#issuecomment-523662498.

**Comment by jsumners** [comment]
That sounds reasonable. I have not had any time to reduce the bug into an easy to reproduce test case. And I don't see it being a priority for me any time soon, either.
