### ISSUE TITLE
Microservices based example using fastify

### ISSUE THREAD

**Issue by techyrajeev** [fastify/fastify#1789]
## 💬 Questions and Help
Please provide an example for below project structure implementation using fastify or create using scaffold by fastify-cli.

└── plugins (from the Fastify ecosystem)
└── your plugins (your custom plugins)
└── decorators
└── hooks and middlewares
└── your services
    │
    └──  service A
    │     └── plugins (from the Fastify ecosystem)
    │     └── your plugins (your custom plugins)
    │     └── decorators
    │     └── hooks and middlewares
    │     └── your services
    │
    └──  service B
          └── plugins (from the Fastify ecosystem)
          └── your plugins (your custom plugins)
          └── decorators
          └── hooks and middlewares
          └── your services

**Comment by RafaelGSS** [comment]
I did not understand what you want. Sounds for me that you want that we make your work.

The Fastify team did some example with [Twitter](https://github.com/fastify/fastify-example-twitter)
And I did some example with microservices for a talk. [Here](https://github.com/RafaelGSS/microservices-example)

Maybe these links can help you.

**Comment by techyrajeev** [comment]
Thanks for your time to reply. Let me clarify, I don't want you to do mine work. After reading the docs It's quite unclear how to proceed with fastify as framework since structure is quite different with express or hapi. Just wanted some examples elaborating above structure which I couldn't find anywhere in docs.

**Comment by RafaelGSS** [comment]
Oh well... Maybe you can test the [fastify-cli](https://github.com/fastify/fastify-cli) 
In my work, we are using the [napd package](https://github.com/RafaelGSS/napd) to generate the structure of our microservices. 

But it is more general, you should choose the structure based on the problem that you need solving.

**Comment by adrai** [comment]
There is not just “one way” to use Fastify and this is really awesome.
Some time ago I switched a whole app from express to Fastify in an hour or so... and then added step by step more cool Fastify stuff... like validation.

Personally, I think this is a great starting point: https://www.fastify.io/docs/latest/Getting-Started/

...and if you have some ideas or advices to make it even better feel free to submit a PR, contributions are always welcome.
