### ISSUE TITLE
Will it listen on socket, not port?

### ISSUE THREAD

**Issue by dananichev** [fastify/fastify#179]
Something similar to 
```javascript
fastify.listen('./www/app.sock', function (err) {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

I mean, node's ``http`` and ``https`` are able to work with sockets. But is ``fastify`` handle routing and other functionality over socket correctly?

**Comment by allevo** [comment]
Hi!
yes it works!

NB: The `server` property is the http/https instance server that inherits from net server which has [`address` method](https://nodejs.org/docs/latest/api/net.html#net_server_address).
Unfortunately the documentation doesn't explain which object is returned by `address` method if the server is binded to a sock file.
So keep attention here `fastify.server.address().port` !

**Comment by mcollina** [comment]
Would you like to send a PR for this behavior?
