### ISSUE TITLE
Integrated websocket support

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1795]
Currently WebSockets are a second-class citizen in Fastify. However, they are now a key part of the modern web.

If you look at the changes done to [fastify-websocket](http://npm.im/fastify-websocket), you can see that it has its own router and a lot of other goodies. It even allows to write websockets routes using the standard “.route()” syntax of fastify.

I think we should integrate _some_ websocket support in Fastify itself. Specifically, we should support hooks for authentication of a Websocket connection. We might even to to add a [nes](http://npm.im/nes)-like capability on top of Fastify itself.

Some tasks:

* [ ] gracefully close websockets https://github.com/fastify/fastify-websocket/pull/46
* [ ] integrated hook for authentication
* [ ] avoid a double router

**Comment by RafaelGSS** [comment]
Great feature. I will follow this feature

**Comment by airhorns** [comment]
Could we consider this closed after https://github.com/fastify/fastify-websocket/pull/95 ?

**Comment by mcollina** [comment]
yes!
