### ISSUE TITLE
Can't bind to public interface

### ISSUE THREAD

**Issue by tobiasmuehl** [fastify/fastify#1796]
## 🐛 Bug Report

Binding to interface `0.0.0.0` or `::` does not make the server accessible from the public internet

## To Reproduce

```js
// Require the framework and instantiate it
const fastify = require('fastify')({
  logger: true
})

// Declare a route
fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})

// Run the server!
fastify.listen(3000, '::', (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

```sh
$ # from same box
$ curl localhost:3000 # works
```

```sh
$ # from another box
$ curl 40.10.2.192:3000 # times out
```

## Your Environment

- *node version*: 11.15.0
- *fastify version*: 2.3.0
- *os*: Linux

**Comment by tobiasmuehl** [comment]
The request from the external box doesn't show up in the fastify logs either

**Comment by jsumners** [comment]
Works here on Node 12.8.0. Node v11 is deprecated.

**Comment by tobiasmuehl** [comment]
Okay, will upgrade node. Found more issues, likely a problem with the local config. Closing for now because most likely not an issue with fastify

**Comment by tobiasmuehl** [comment]
Fucking typo in the IP. Just user error.
