### ISSUE TITLE
Remove hapi, express, koa, restify... from devDependencies

### ISSUE THREAD

**Issue by g-div** [fastify/fastify#180]
It would be a great to move hapi, express, koa and restify to the `package.json` of a new repository called something like `fastify-benchmarks`.

`npm install` would otherwise take much longer as expected, if you are not aware that you are going to install pretty much all node.js web frameworks.

**Comment by delvedor** [comment]
Hi! Thank you for the interest!
You are right we should do that, this is an old legacy of the project.
I'll do that as soon as I've the time :)

**Comment by cagataycali** [comment]
I'm working on it!

**Comment by cagataycali** [comment]
That's just finished. [fastify-benchmarks](https://github.com/cagataycali/fastify-benchmarks)
Any idea, improvement or enhancement about the package?

King regards,
Cagatay.

**Comment by jsumners** [comment]
I think this can be closed.

cc @delvedor @mcollina
