### ISSUE TITLE
Getting protocol from request 

### ISSUE THREAD

**Issue by TzachiSh** [fastify/fastify#1800]
Is there a way of knowing the URL protocol, In express i can extract from req.protocol

But i didn't find a way to extract protocol in fastify...

Thanks!

**Comment by mcollina** [comment]
It should be request.raw.protocol.

**Comment by TzachiSh** [comment]
i tried that key but is undefined 

`
fastify.get('/', async (request, reply) => {
  return {
    protocol:request.raw.protocol
  }
})
`

**Comment by RafaelGSS** [comment]
@mcollina we set the protocol? or is take by _find-my-way?

I don't find where we set the protocol inside context/reply

**Comment by RafaelGSS** [comment]
@TzachiSh do you want to check if is HTTP or HTTPS, right?

**Comment by TzachiSh** [comment]
Correct 
its need to be something like this : 
`
let proto = this.connection.encrypted
    ? 'https'
    : 'http';
`

**Comment by RafaelGSS** [comment]
Please see #1556 
But I think that we should expose to API the "protocol". (will make it even easier for a redirect plugin)

**Comment by mcollina** [comment]
Please send a PR! We’ll be happy to review it.

Il giorno gio 15 ago 2019 alle 14:18 Rafael Gonzaga <
notifications@github.com> ha scritto:

**Comment by TzachiSh** [comment]
Expose raw protocol in the API [#1805](https://github.com/fastify/fastify/pull/1805)

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by Ethan-Arrowood** [comment]
@KaKi87 looks like it was abandoned, feel free to pick up the linked PR and complete it!

**Comment by kibertoad** [comment]
https://github.com/fastify/fastify/pull/2582 is not the same?

**Comment by Ethan-Arrowood** [comment]
Oh ignore me then, looks like this may be able to be closed!

**Comment by KaKi87** [comment]
Okay, any ETA to NPM release ? Thanks

**Comment by Ethan-Arrowood** [comment]
You can pull directly from the master branch of the repo if you need access to it immediately; otherwise, the release will come when the the lead maintainers are available.
