### ISSUE TITLE
Add better typing for JsonSchema type definition

### ISSUE THREAD

**Issue by JemarJones** [fastify/fastify#1804]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

[Currently](https://github.com/fastify/fastify/blob/master/fastify.d.ts#L217) fastify has the JsonSchema type aliased the loose type of `Object`. Instead it would be helpful to users of the library if this type was tightened down to use the `JsonSchema7` definition provided in https://www.npmjs.com/package/@types/json-schema. This change would be as simple as installing those typings and changing the existing alias to point there instead.

## Motivation

To have stricter types for `JsonSchema`.

**Comment by mcollina** [comment]
We have had bad experiences in shipping types from DefinitelyTyped because of the increase in the module size.
Maybe we can add some docs that would explain how to use those instead?

**Comment by JemarJones** [comment]
I see, is that an issue with the types themselves, or with installing DefinitelyTyped packages? Because if it's just an issue with DefinitelyTyped, perhaps this specific type could simply be copied over (with attribution, since DefinitelyTyped is MIT).

**Comment by mcollina** [comment]
Mainly with the DefinitelyTyped packages. You are right, we could potentially vendor that dependency. Note that I would recommend to use http://npm.im/fluent-schema instead.

**Comment by climba03003** [comment]
Resolved by #2863
https://github.com/fastify/fastify/blob/a454883afbd12871aef426ea43480d61240c11cf/types/schema.d.ts#L7-L13
