### ISSUE TITLE
Support for static plugin load

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1812]
## 🚀 Feature Proposal

In `fastify-autoload`, the `require` of plugins is done after the first "tick" of the event loop, i.e. during the asynchronous boot of fastify.
I think it would be good to support an optional function that can be called synchronously _before the plugin is loaded_, so that it can perform certain actions.

## Motivation

The goal for this change is to provide _better error reporting_ in case of syntax issues in the autoload plugin.

## Example

```js
 const fastify = require('fastify')

async function plugin (app, opts) {
  console.log(opts.list)
})
plugin[Symbol.for('plugin-meta')]] = {
  onRegister (app, opts) {  // this is a sync function, no callback and no promise
    opts.list = ['foo', 'bar']
  }
}

const app = fastify()
app.register(plugin)
app.ready()
```

**Comment by delvedor** [comment]
I like the idea, so we can enable direct use of a plugin in the next line without the need to use `after`.
I think we should build this in `avvio`, I fear that add this feature directly into Fastify could cause side effects because we are “tricking” `avvio`.

**Comment by RafaelGSS** [comment]
I agree with @delvedor if in the future Fastify uses another lib to register async plugins, we are don't need to make any modification in our API. (Or just Throw/Warning if "new lib" not support register sync)

**Comment by mcollina** [comment]
@SerayaEryn I think part of your work in #1673 is somewhat related to this. Maybe you would like to send a PR for this as well?

**Comment by SerayaEryn** [comment]
Yes, I can do that. I‘ll take a look at this next week.

**Comment by SerayaEryn** [comment]
I opened a PR in the avvio repository.
