### ISSUE TITLE
docs say that prefix works with fastify-plugin

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1818]
## 🐛 Bug Report

Hello, [here](https://github.com/fastify/fastify/blob/master/docs/Plugins.md#plugin-options) is talking that one of the options that work with `fastify-plugin` is `prefix`, but we know that it not works. And it already documented [here](https://github.com/fastify/fastify/blob/master/docs/Plugins.md#route-prefixing-option).

Should be removed from list initial? or I forgot something?

**Comment by mcollina** [comment]
It should be removed from the list.

Il giorno mer 21 ago 2019 alle 23:02 Rafael Gonzaga <
notifications@github.com> ha scritto:

**Comment by Eomm** [comment]
Closing since pr has been merged 🤟
