### ISSUE TITLE
No way of knowing which context the validation error came from?

### ISSUE THREAD

**Issue by mcchrish** [fastify/fastify#1821]
## 💬 Questions and Help

I'm looking through the docs and also inspecting the error objects everywhere but there's no way of easily knowing the context of the validation error whether it is caused by params, body etc.

https://www.fastify.io/docs/latest/Validation-and-Serialization/#error-handling

Maybe related code:
https://github.com/fastify/fastify/blob/master/lib/validation.js#L96-L123

### Please note that this issue tracker is not a help forum and this issue may be closed.

Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Comment by mcollina** [comment]
This will be fixed in https://github.com/fastify/fastify/pull/1808.

**Comment by Eomm** [comment]
Merged and released in 2.8
