### ISSUE TITLE
Do not create an Error for the default 404 route

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1823]
## 🚀 Feature Proposal

Creating an `Error` is costly, and we should be able to avoid that in https://github.com/fastify/fastify/blob/d48c6a21f21d72b7683808aa88b3fdcd2e0478db/lib/fourOhFour.js#L53. Moreover, it complicates debugging (see #1822 for details).

**Comment by jsumners** [comment]
I think it would just be better if that error included some context, e.g. the request path that led to the error.

**Comment by RafaelGSS** [comment]
How we can get the stack trace on this code?

**Comment by SerayaEryn** [comment]
I can take a look at this.

**Comment by mcollina** [comment]
Thanks!

Il giorno lun 26 ago 2019 alle ore 17:23 Denis Fäcke <
notifications@github.com> ha scritto:
