### ISSUE TITLE
Add hook onResponse by route

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1828]
## 🚀 Feature Proposal

Based on a conversation in gitter today (at 00h52 AM - São Paulo - Brazil), a user of fastify reported to me that would like create a stopWatch metric for each route.

The fastest solution that I found for her is:
```js
const calcTimeByRoute = routeName => (request, reply) => { 
  console.log(`[${routeName}] Elapsed: ${request.YourDecoratorTimer.elapsedTime()}`)
}

fastify.register(async (fastify, opts) => {
  fastify.get('/route1', async (request, reply) => ({}))
  fastify.addHook('onResponse', calcTimeByRoute('route1'))
})

fastify.register(async (fastify, opts) => {
  fastify.get('/route2', async (request, reply) => ({}))
  fastify.addHook('onResponse', calcTimeByRoute('route2'))
})
```

But if we expose something like:

```js
fastify.route({
  url: '/route1',
  method: 'GET',
  handler: async (request, reply) => ({}),
  onResponse: (request, reply) => { ... }
}
```

What do you think? Overhead?

**Comment by mcollina** [comment]
It would have no overhead whatsover. In fact, see https://github.com/fastify/fastify/issues/1587!

Would you like to send a PR?

**Comment by mcollina** [comment]
I think it's a trivial change to add that, as _they are encapsulated per route already_ - we are just not exposing them.

**Comment by mcollina** [comment]
Done in https://github.com/fastify/fastify/pull/1838.
