### ISSUE TITLE
Fixing issues regarding grammar etc. in the docs

### ISSUE THREAD

**Issue by LW2904** [fastify/fastify#1829]
Reading through the docs, I've come across a number of grammatical and structural issues.

I'm willing to proofread them, but I thought I'd create this issue in case anyone else is already working on this, or you don't want project outsiders to mess with your documentation.

I should note that I am not a native speaker, but my writing skills could probably be considered to be on the level of one.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1850.
Feel free to reopen if the issue still applies.
