### ISSUE TITLE
Expose the current plugin name

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1830]
## 🚀 Feature Proposal

Add the metadata of the current plugin name that is registering a route.

## Motivation

For debugging purposes, it is helpful to know which plugin is registering a given route. This would be useful for providing a better usage experience. 
See the discussion in https://github.com/fastify/fastify/pull/1808#discussion_r315879503 for more details.

### Example

We could add an API like

```js
app.currentPluginName
```

or

```js
app.currentPluginTree
```

These could be dynamic getters that changes based on the level these are being called at.

**Comment by mcollina** [comment]
cc @StarpTech

**Comment by StarpTech** [comment]
@mcollina thanks. I will see if I room to play with it.

**Comment by StarpTech** [comment]
I close it dueo to #1836
