### ISSUE TITLE
presence of skip-override ignores prefix.

### ISSUE THREAD

**Issue by jhechtf** [fastify/fastify#1831]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## To Reproduce

Example Repo: https://gitlab.com/jhechtf/fastify-issue

1. create two plugin files in your application that have a shared route, such as `fastify.get('/',...)`
2. For one of them after the `module.exports` assignment add in `module.exports[Symbol.for('skip-override')] = true`
3. When registering them, pass in a `{ prefix: '/api' }`
4. Bring the server up

Paste your code here:

```js
const Fastify = require('fastify');

const fastify = Fastify();

const plugin1 = require('./plugin1');

fastify.register(plugin1, {
    prefix: '/api/v1'
});

const plugin2 = require('./plugin2');

fastify.register(plugin2, {
    prefix: '/api/v1'
})

fastify.listen(3000, (err, add) => {
    if (err) return console.error(err.stack), process.exit();
    console.log(`listening on ${add}`);
})
```

## Expected behavior

The server in this case should throw an error since the same path _should_ be registered twice, but file that adds in the skip-override information does not apply the `/api` prefix, and therefore serves on just `/` instead of `/api`, while the one without the skip-override symbol adds in the path, making it serve on `/api` therefore avoiding the clash.

Paste the results here:

```

```

## Your Environment

- *node version*: 12.6.0
- *fastify version*: >=2.7.1
- *os*: Windows 10

**Comment by mcollina** [comment]
This is documented, and a feature: https://www.fastify.io/docs/latest/Plugins/#route-prefixing-option.
