### ISSUE TITLE
Typescript types not working for http2

### ISSUE THREAD

**Issue by mfbx9da4** [fastify/fastify#1840]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

Types are not being passed to request using http2

## To Reproduce

I have followed the docs for a [simple typescript setup](https://github.com/fastify/fastify/blob/master/docs/TypeScript.md)

```typescript
    import fastify from 'fastify'
    import { Server, IncomingMessage, ServerResponse } from 'http'
    import http2 from 'http2'
    import fs from 'fs'
    import path from 'path'

    function createRoutes(server: ServerInstance) {
      interface Query {
        foo?: number
      }

      interface Params {
        bar?: string
      }

      interface Body {
        baz?: string
      }

      interface Headers {
        a?: string
      }

      const opts: fastify.RouteShorthandOptions = {
        schema: {
          querystring: {
            type: 'object',
            properties: {
              foo: {
                type: 'number',
              },
            },
          },
          params: {
            type: 'object',
            properties: {
              bar: {
                type: 'string',
              },
            },
          },
          body: {
            type: 'object',
            properties: {
              baz: {
                type: 'string',
              },
            },
          },
          headers: {
            type: 'object',
            properties: {
              a: {
                type: 'string',
              },
            },
          },
        },
      }

      server.get<Query, Params, Headers, Body>(
        '/ping/:bar',
        opts,
        (request, reply) => {
          console.log(request.query) // this is of type Query!
          console.log(request.params) // this is of type Params!
          console.log(request.body) // this is of type Body!
          console.log(request.headers) // this is of type Headers!
          reply.code(200).send({ pong: 'it worked!' })
        },
      )
      return server
    }

    type ServerInstance = fastify.FastifyInstance<
      http2.Http2SecureServer,
      http2.Http2ServerRequest,
      http2.Http2ServerResponse
    >

    export async function createServer() {
      const server: ServerInstance = fastify({
        logger: true,
        http2: true,
        https: {
          allowHTTP1: true, // fallback support for HTTP1
          key: fs.readFileSync(path.join(__dirname, '..', 'https', 'fastify.key')),
          cert: fs.readFileSync(
            path.join(__dirname, '..', 'https', 'fastify.cert'),
          ),
        },
      })
      createRoutes(server)
      return server
    }
```

However types are not being passed when http2 types are used

[![enter image description here][1]][1]

Using HTTP1 types like so 

```typescript
    type ServerInstance = fastify.FastifyInstance<
      Server,
      IncomingMessage,
      ServerResponse
    >
```

are passed and work correctly

  [1]: https://i.stack.imgur.com/rnK5W.png

## Your Environment

- *node version*: 10 
- *fastify version*: 2.8.0
- *os*: Mac

**Comment by mcollina** [comment]
@evanshortiss @Ethan-Arrowood would you mind taking a look?
I do not know the answer to this problem.

I'm pretty sure that our next branch (v3) will solve this beautifully.

**Comment by evanshortiss** [comment]
@mfbx9da4 change this line:

```ts
const opts: fastify.RouteShorthandOptions<ServerInstance>
```

to this:

```ts
const opts: fastify.RouteShorthandOptions<
        http2.Http2SecureServer,
        http2.Http2ServerRequest,
        http2.Http2ServerResponse
    >
```

I think that will do the trick :)

**Comment by Ethan-Arrowood** [comment]
@evanshortiss answer looks like the valid solution to me.

Using v3 types should require you to only declare the http2 server generic:
`const server = fastify<http2.Http2SecureServer>({ http2: true })` also be sure to toggle the http2 option for the server instance (new v3 types should throw a type error if you don’t). Also v3 types are only available in the experimental `next` branch

**Comment by mfbx9da4** [comment]
@evanshortiss solution works for now. Is there a way to install `next` version or should I do something like 

```
npm install git://github.com/fastify/fastify.git#next --save
```

Or just way until v3? How long will that be?

**Comment by mcollina** [comment]
v3 is coming out before the end of the year. We might cut an alpha version on npm sooner than that.

**Comment by mfbx9da4** [comment]
That would be great 🙏 Appreciate the speedy response
