### ISSUE TITLE
Custom AJV instance throws schema building error for $ref-way style shared schema references

### ISSUE THREAD

**Issue by weiliddat** [fastify/fastify#1844]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

Using a non-default ajv instance throws a `FST_ERR_SCH_BUILD` error when using a $ref-way shared schema.

## To Reproduce

1. Run the following code - it should throw a `FST_ERR_SCH_BUILD` error.
2. Comment out the custom ajv instance and run it again - no problems.

Paste your code here:

```js
const fastify = require('fastify')({ logger: 'info' });
const Ajv = require('ajv');

const ajv = new Ajv({
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: true,
    allErrors: true,
    nullable: true
});

fastify.setSchemaCompiler(function (schema) {
    return ajv.compile(schema);
});

fastify.addSchema({
    $id: 'http://example.com/common.json',
    type: 'object',
    properties: {
        hello: { type: 'string' }
    }
});

fastify.route({
    method: 'POST',
    url: '/',
    schema: {
        body: {
            type: 'array',
            items: { $ref: 'http://example.com/common.json#/properties/hello' }
        }
    },
    handler: (req, reply) => { reply.send(req.body) }
});

fastify.listen(1234);
```

## Expected behavior

It should work the same way both ways, especially with fastify's default options.
Otherwise, it should be documented that it only works with the default instance of ajv.

Paste the results here:

```js
{ FastifyError [FST_ERR_SCH_BUILD]: FST_ERR_SCH_BUILD: Failed building the schema for POST: /, due error can't resolve reference http://example.com/common.json#/properties/hello from id #
    at Object.afterRouteAdded (/Users/cw/dev/projects/gooddb-server/node_modules/fastify/lib/route.js:224:37)
    at after (/Users/cw/dev/projects/gooddb-server/node_modules/fastify/lib/route.js:165:25)
    at Object._encapsulateThreeParam (/Users/cw/dev/projects/gooddb-server/node_modules/avvio/boot.js:417:7)
    at Boot.callWithCbOrNextTick (/Users/cw/dev/projects/gooddb-server/node_modules/avvio/boot.js:339:5)
    at Boot._after (/Users/cw/dev/projects/gooddb-server/node_modules/avvio/boot.js:230:26)
    at Plugin.exec (/Users/cw/dev/projects/gooddb-server/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (/Users/cw/dev/projects/gooddb-server/node_modules/avvio/plugin.js:175:10)
    at Task.release (/Users/cw/dev/projects/gooddb-server/node_modules/fastq/queue.js:127:16)
    at worked (/Users/cw/dev/projects/gooddb-server/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/Users/cw/dev/projects/gooddb-server/node_modules/avvio/plugin.js:178:7)
  name: 'FastifyError [FST_ERR_SCH_BUILD]',
  code: 'FST_ERR_SCH_BUILD',
  message:
   'FST_ERR_SCH_BUILD: Failed building the schema for POST: /, due error can\'t resolve reference http://example.com/common.json#/properties/hello from id #',
  statusCode: 500 }
```

## Your Environment

- *node version*: 10.16.3
- *fastify version*: 2.8.0
- *os*: MacOS 10.14.6
- *any other relevant information*

**Comment by mcollina** [comment]
Ouch, this looks like a bug. Would you like to send a PR to fix it?

**Comment by Eomm** [comment]
I'm not sure it is a bug, it could be an optimization and maybe we need to add some code and break things to let it work I think, we could plan it for the v3.
I had already worked in a refactor. I could open a draft PR for that.

The trick is here:

https://github.com/fastify/fastify/blob/8891ae8701633503e6732e84de4f7e2d3f4b8451/lib/validation.js#L178-L180

You need to add to your code:

```
ajv.addSchema({
  $id: 'http://example.com/common.json',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})
```

When you execute `fastify.addSchema` we don't know if you are using ajv, joi or something else after you have execute `fastify.setSchemaCompiler`.
So running `fastify.addSchema` is unnecessary since you are not using the default schema compiler.

**Comment by weiliddat** [comment]
Ah right. I had an assumption that addSchema works as a general wrapper for ajv's addSchema, but I guess that's only if I'm using the default validator.
So I guess it's not really a bug, but just documentating this on the validation page under the part for custom compiler?

**Comment by weiliddat** [comment]
Added a PR at https://github.com/fastify/fastify/pull/1846
