### ISSUE TITLE
Serializer per context

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#1845]
## 🚀 Feature Proposal

I would like to have the possibility to customize the logger serializer per context so,
in one context I can log a user with the serializerA, and in another context I can use the serializerB.

Pino support the [`serializers`](https://github.com/pinojs/pino/blob/master/docs/api.md#bindingsserializers-object) configuration in the child logger, where you can overwrite the serializer defined in the parent logger or simply add new ones.

## Motivation

I'm using a JSON schema to drop all the data that I don't want to log out.
In some context I need to see a field with many info, in another context I don't need it

## Example

```
fastify.register(require('./user'), {
  logLevel: 'debug',
  serializers: {
    user: jsonSchemaSerializer(mySchema)
  }
})

fastify.register(require('./special-user'), {
  logLevel: 'debug',
  serializers: {
    user: jsonSchemaSerializer(myOtherSchema)
  }
})
```

**Comment by RafaelGSS** [comment]
I can do this on the weekend. If add serializers by route?

**Comment by mcollina** [comment]
nice! This needs to be well documented.

**Comment by Eomm** [comment]
> I can do this on the weekend. If add serializers by route?

I would start with the context.
A serializer for route could be verbose as the first step

If you need help feel free to ask or open a draft PR 👍
thks

**Comment by RafaelGSS** [comment]
Guys, sorry for the delay, I'll take this issue only on next week(busy), have a problem? If anyone would like to take this issue, feel free to it :smile:

**Comment by Eomm** [comment]
Nevermind, you work on OSS only when you want to 💪
