### ISSUE TITLE
Leverage Github Actions

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1847]
## 🚀 Feature Proposal

We have Github Actions enabled in this repo! What can we do with them?
One thing that would be nice is to move the trigger to CircleCI for deploying the website.
Moreover, we can actually redo the automation for the [website](https://github.com/fastify/website) using actions!

@lmammino and maybe others, would it be nice to have these here?

**Comment by jsumners** [comment]
I really wish they would get enabled for the ldapjs org. I want to do all of my CI stuff there with them. 

How long did it take this org to get approved?

**Comment by mcollina** [comment]
We have been on the first batch

Il giorno mar 10 set 2019 alle 19:19 James Sumners <notifications@github.com>
ha scritto:

**Comment by StarpTech** [comment]
Lets make a plan I would like to evaluate them.

**Comment by Eomm** [comment]
I think another action could be an auto-label when some template issue is used, like questions to start

**Comment by mcollina** [comment]
That would be handy!

Il giorno ven 13 set 2019 alle ore 22:51 Manuel Spigolon <
notifications@github.com> ha scritto:

**Comment by StarpTech** [comment]
AS inspiration https://github.com/sdras/awesome-actions
