### ISSUE TITLE
Microservice explaination/example

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#185]
Quote from [`Plugins Guide`](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md)

> Ok, you are growing very fast and you want to change your architecture and try microservices. Usually this implies an huge amount of work, because of cross dependencies and the lack of separation of concerns.
Fastify helps you a lot in this direction, because thanks to the encapsulation model it will completely avoid cross dependencies, and will help you structure your code in cohesive blocks.

Maybe we have to provide a little example how a developer can use `fastify` for building some microservice architecture

Strike while the iron's hot!

**Comment by delvedor** [comment]
Maybe we can create a repository here with a comprehensive example, entry point, directory structure, plugins, decorators and so on...
@mcollina thoughts?

**Comment by allevo** [comment]
I'd like to creare a complete but not complex example where put some plugins into.

- `fastify-static`: serving static file
- `fastify-swagger`: documentation
- `fastify-react`: for rendering react app on server side (yes, I'm a React fun, sorry!)
- `fastify-multipart`: for file uploading
- `fastify-accepts-serializer`: for accepting different response types

Maybe the classic TodoList is a bit boring.
With TodoList:
- todo microservice
- login microservice

Any suggestions to avoid the TodoList?

**Comment by mcollina** [comment]
A twitter clone is also very nice!

**Comment by allevo** [comment]
@mcollina good example!

So, let's start to rewrite twitter 😂 

Can we start to think how structure the project and how the different pieces can communicate?
I'd like to keep the discussion as public as possible in order to show how a project and a microservices infrastructure can be imagined from zero with `fastify`.

Where will we start the discussion? Here or in a new project?

**Comment by delvedor** [comment]
I think we can do everything (discussion an so on) in a new repository, I'll create that tomorrow :)

**Comment by cagataycali** [comment]
Is there any news / updates?

**Comment by delvedor** [comment]
I've created the repository, further discussions will be done there :)

https://github.com/fastify/example
