### ISSUE TITLE
Question: log response after response has been sent

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#1851]
## 💬 Questions and Help

I would like to understand if this code is an overengineering or not.
I don't have run benchmark right now - I'm not so fast to build them 😅

Target: I have a big JSON object to log.
The logger is configured to write to elastic (with pino-elasticsearch)
I don't want to add overhead to the route.

Assumptions: 
+ pino is formatting the object in sync via [quick-format-unescaped](https://www.npmjs.com/package/quick-format-unescaped) is I have understood the code.
+ The `onSend` hook is executed before the response is submitted
+ The `onResponse` hook run after the response has been submitted but I don't have the payload (the stream is already consumed)

So I'm using the `onSend` to get the payload and to listen for the end of the send, and then I log the JSON object.

```js
fastify.addHook('onSend', function (request, reply, payload, done) {
  const logData = buildLogObject(request, reply, payload)

  const onResFinished = err => {
    reply.res.removeListener('finish', onResFinished)
    reply.res.removeListener('error', onResFinished)

    if (err) {
      fastify.log.error(logData, 'Response errored')
    } else {
      fastify.log[getLevel(reply.res.statusCode)](logData)
    }
  }
  reply.res.on('finish', onResFinished)
  reply.res.on('error', onResFinished)

  done()
})
```

What do you think?

**Comment by mcollina** [comment]
I don’t think it matters much if you log before or afterwards. If you are under significant load it is going to impact the next request, and if you have no load.. it won’t matter.

**Comment by Eomm** [comment]
Thank you 👍
