### ISSUE TITLE
Add ability to change route config interface

### ISSUE THREAD

**Issue by numfin** [fastify/fastify#1852]
## 🚀 Feature Proposal

Im using typescript and i stuck in a problem where i cant change global interface declarations.
![image](https://user-images.githubusercontent.com/8134947/64914791-25f31d00-d761-11e9-8ac5-52e2d054b580.png)

## Motivation

I want to have intellisense in my ide

**Comment by mcollina** [comment]
Would you like to send a PR? Note that we are changing our types in v3.

Il giorno dom 15 set 2019 alle 01:48 Numble Fingers <
notifications@github.com> ha scritto:

**Comment by numfin** [comment]
Actually i dont know how to make it beautifull with current declarations.
Instead i solved my problem with this:
![image](https://user-images.githubusercontent.com/8134947/64927535-c22a2c00-d814-11e9-86ab-5004c6700045.png)

I don't know if it solves an actual problem, but i hope it will help people. struggling with this.

I also leave some keywords for people struggling with this: 
`Subsequent property declarations must have the same type.  Property 'config' must be of type 'any', but here has type`
`All declarations of 'config' must have identical modifiers`
