### ISSUE TITLE
Fastify Reply method not returning objects while strings ?

### ISSUE THREAD

**Issue by deveshrawat** [fastify/fastify#1859]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

M Calling data in that is in Object format but when i return that is not returning anything but after using : `JSON.stringify` it works 

## To Reproduce

Paste your code here:

```js
exports.checkKyc = async (req, reply) => {
    try {
        const userId = req.params.userId
        const resDoc = await Kyc.find({ userId: userId }, { _id: 0 }).limit(1)
        return _.isEmpty(resDoc)
            ? boom.badRequest('No such user found')
            : JSON.stringify(resDoc[0])
    } catch (err) {
        throw boom.boomify(err)
    }
}
```

## Expected behavior

Paste the results here:

```js

```

## Your Environment

- *node version*: 10
- *fastify version*: >=2.7.1
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
Can you please include a full, runnable example to reproduce your problem?

**Comment by deveshrawat** [comment]
When I try to reproduce and by changing the file structure using direct methods instead of router it is working fine i think this is issue with my own file structure , i opened it coz m getting it in my two api i think nothing is there like bug , sorry for wasting your time.
