### ISSUE TITLE
Possibility to change Ajv settings

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#186]
Ajv provides a huge list of properties to get the right configuration https://github.com/epoberezkin/ajv#options

e.g

- `removeAdditional` [filtering data](https://github.com/epoberezkin/ajv#filtering-data)
- `useDefaults`  [filtering data](https://github.com/epoberezkin/ajv#assigning-defaults)

At the moment the parameters are fixed
https://github.com/fastify/fastify/blob/master/lib/validation.js#L6

Please provide a way to pass custom properties to the Ajv instance.

**Comment by allevo** [comment]
Hi!
thanks for the report!
Currently there's a PR https://github.com/fastify/fastify/pull/167 opened by me for this issue.

Please feel free to contribute!

**Comment by StarpTech** [comment]
We could create the ajv instance in index.js and pass it to the [build](https://github.com/fastify/fastify/blob/master/fastify.js#L313) function so that we can pass default options?

**Comment by StarpTech** [comment]
I created a PR https://github.com/fastify/fastify/pull/187

**Comment by mcollina** [comment]
This was fixed.
