### ISSUE TITLE
Coveralls GH action posts too many comments

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1870]
Currently, the coveralls GitHub action is posting too many comments in the pull request. I've checked our coveralls configuration, and the comments are disabled. I'm not even sure that problem is caused by the [coveralls GitHub action](https://github.com/coverallsapp/github-action).

A couple of examples of pr with too many comments: https://github.com/fastify/fastify/pull/1869 https://github.com/fastify/fastify/pull/1867

Related: https://github.com/fastify/fastify/issues/1847 https://github.com/fastify/fastify/pull/1853 https://github.com/coverallsapp/github-action/issues/5

**Comment by StarpTech** [comment]
I think this happens because we run coveralls on every different OS/node.js build

**Comment by XhmikosR** [comment]
You could and should definitely limit where coveralls runs on. I mean, if you test 12 different things you don't need coveralls to run on all of them :)

That being said, there is that coveralls action bug that does result in PR comments even if one has disabled them on coveralls.

**Comment by XhmikosR** [comment]
This is how I do it personally:

https://github.com/validator/grunt-html/blob/24632c8900dc4b179536b16ec0744e8db63b0d33/.github/workflows/test.yml#L38
