### ISSUE TITLE
Timeout on resizing in Hook

### ISSUE THREAD

**Issue by Alexufo** [fastify/fastify#1873]
I use default template of fastify-cli structure. In services I use static plugin
https://github.com/fastify/fastify-static
 and use onSend hook as shown in example.

I install sharp https://www.npmjs.com/package/sharp
and try to resize jpg image on get request

## 🐛 Bug Report

I get 5 seconds timeout on every request.
I check profiler an see this.
https://i.stack.imgur.com/VhSZX.png
At the end of timeline profiler shown  timeout killer function from nodejs core.
After timeout picture return to the browser resized.

When I move this functionality to new route without hooks - all works fine, Images resized around 35ms.

## To Reproduce

install fastify cli
create static.js service
upload to server jpg file
install static plugin  
check uploaded jpg file from browser. Fastify shouuld shown image.
install sharp
past hook to static.js  from example on fastify static page
change them as code at bottom.

```

fastify.addHook('onSend', async (request, reply, payload) => {
          const newPayload = await sharp(payload.filename).resize(200, 100).toFormat('jpg').toBuffer();
         return newPayload
      })

```

- node version*: 12
- fastify version*: >=2.0.0
- os*: Ubuntu 18

**Comment by mcollina** [comment]
One of the things that you currently have is a memory leak, as `payload` should be a stream and you are not consuming it. However I don't think that's the main cause of your problem, or why the process is crashing.

Can you upload a minimal example to reproduce the problem somewhere? Thanks.
