### ISSUE TITLE
Add hacktoberfest flag with issues 

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#1875]
What do you think about create the flag "hacktoberfest" in some quick issues? Can be great for new people to know fastify
## Motivation

https://hacktoberfest.digitalocean.com/

**Comment by StarpTech** [comment]
Sounds awesome!

**Comment by RafaelGSS** [comment]
Go? Hacktoberfest already initialized

**Comment by Eomm** [comment]
@fastify/fastify do you agree to flag some "good first issue" with the flag `hacktoberfest`?
So users can [search them](https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+is%3Aissue&type=Issues)

**Comment by mcollina** [comment]
Yes!

Il giorno ven 4 ott 2019 alle ore 08:29 Manuel Spigolon <
notifications@github.com> ha scritto:

**Comment by Eomm** [comment]
## [Link to search all the hacktoberfest issues in the fastify org](https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+is%3Aissue+org%3Afastify&type=Issues) 

Hope someone will jump in 🤟

**Comment by RafaelGSS** [comment]
good job!!
