### ISSUE TITLE
Overwrite default logger by child logger after authentication?

### ISSUE THREAD

**Issue by olivierto** [fastify/fastify#1880]
Hello! 
Let me explain you a bit my situation. 
After a successfull authentication I wan't the logger to attach some user for every log behind (in the handler for example) .
I'm using a custom auth plugin to verify AWS cognito JWT, and i'm forcing inside the plugin the fastify logger to be replaced by a child logger but it's not working as expected. 

```Typescript
 const logger = fastify.log as any; // should be pino logger
 if(typeof logger.child !== "undefined"){
           fastify.log = logger.child({userId: user.id})
 }
```

Do you have any idea on how to do ? 
May be it's a bad idea to do it this way? any advice? 

Thanks. 

Olivier

**Comment by mcollina** [comment]
We do not have a single `fastify` instance for each request.

You should do:

```js
req.log = req.child({ userId: user.id })
```

instead.

**Comment by olivierto** [comment]
Thanks for your answer mcollina,  it fixes the problem. 
I wasn't aware that the fastify instance wasn't shared accross all the requests.  :)
