### ISSUE TITLE
Broken JSON Schema resolution

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1881]
## 🐛 Bug Report

When using a reference to a full schema definition, instead of to a sub resource of the referenced schema, Fastify's schema resolution incorrectly mutates the reference name. The result is that it cannot find the referenced schema.

## To Reproduce

Paste your code here:

```js
'use strict';

const AJV = require('ajv');
const ajv = new AJV();

ajv.addSchema({
  $id: 'urn:schema:foo',
  definitions: {
    foo: { type: 'string' }
  },

  type: 'object',
  properties: {
    foo: { $ref: '#/definitions/foo' }
  }
});

ajv.addSchema({
  $id: 'urn:schema:response',
  type: 'object',
  properties: {
    bar: { $ref: 'urn:schema:foo' }
  }
});

const fastify = require('fastify')();
fastify.setSchemaCompiler(schema => ajv.compile(schema));
fastify.setSchemaResolver(name => ajv.getSchema(name).schema);

fastify.route({
  path: '/',
  method: 'GET',
  schema: {
    response: {
      '2xx': ajv.getSchema('urn:schema:response').schema
    }
  },
  handler(req, reply) {
    reply.send({ bar: { foo: 'bar' } });
  }
});

fastify.inject({ url: '/' }, (err, response) => {
  if (err) {
    throw err;
  }
  console.log(response.body);
});
```

## Expected behavior

The `urn:schema:foo` reference should resolve to an object schema.

## Cause

https://github.com/fastify/fastify/blob/89dd7493c06774600635b010ebac6a622bfd42f2/lib/schemas.js#L110

Notice that on this line the value of `refValue` will be `'urn:schema:foo'`. Since this string does not have a `#` character, the line will execute `refValue.slice(0, -1)` which will yield `'urn:schema:fo'`.

**Comment by jsumners** [comment]
Note, if you change the second schema to:

```js
{
  $id: 'urn:schema:response',
  type: 'object',
  properties: {
    bar: { $ref: 'urn:schema:foo#' }
  }
}
```

You will encounter a second error inside of `fast-json-stringify`. Basically, this change will cause the schema to be resolved, but the resolved object (the first schema) will not have the "definitions" property. So https://github.com/fastify/fast-json-stringify/blob/e2b5d3524d99b8c366ec8e7b87af6a487b058b6c/index.js#L516 will generate `return schema['definitions']['foo']` which will resolve to `schema.<undefined>.foo`.

**Comment by mcollina** [comment]
Is this a regression or old bug?

Il giorno mar 1 ott 2019 alle 20:34 James Sumners <notifications@github.com>
ha scritto:

**Comment by Eomm** [comment]
Arg, it is a new bug for the new feature

**Comment by delvedor** [comment]
It might be worth considering if it does make sense to refactor the whole schema handling since we have added a lot of features in the past months.

**Comment by Eomm** [comment]
I totally agree, I'm working to ease this part but it will be a PR for the `next` branch since there could be some breaking changes
