### ISSUE TITLE
Simple example with babel-node does nothing

### ISSUE THREAD

**Issue by njlr** [fastify/fastify#1883]
## 🐛 Bug Report

When I try to launch the server, the program finishes immediately with no output. 

```bash
yarn babel-node ./index.js
```

## To Reproduce

`.babelrc`

```json
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-pipeline-operator",
      { "proposal": "minimal" }
    ]
  ]
}
```

`index.js`

```js
import fastify from 'fastify';

const app = fastify();

app.listen(3000, 'localhost', err => {
  if (err) {
    throw err;
  }

  console.log('application on!');
});
```

## Expected behavior

The server should start, console output should appear. 

Paste the results here:

Nothing!

## Your Environment

- *node version*: v11.15.0
- *fastify version*: ^2.9.0
- *os*: Linux

`package.json`

```
{
  "devDependencies": {
    "@babel/core": "7 || ^7.0.0-rc.2",
    "@babel/node": "^7.6.2",
    "@babel/plugin-proposal-pipeline-operator": "^7.5.0",
    "@babel/preset-env": "^7.6.2"
  },
  "dependencies": {
    "@babel/polyfill": "^7.6.0",
    "fastify": "^2.9.0"
  }
}
```

**Comment by mcollina** [comment]
I've never used `babel-node`, this seems to be a problem there. Can you run `babel-node` without passing through `yarn`? Can you compile your code with `babel` and run it?

**Comment by StarpTech** [comment]
The example is not complete. `yarn babel-node` runs a package script but you didn't define it in the example. Have a look at this [example](https://hackernoon.com/using-babel-7-with-node-7e401bc28b04).

**Comment by njlr** [comment]
> The example is not complete. `yarn babel-node` runs a package script but you didn't define it in the example. Have a look at this [example](https://hackernoon.com/using-babel-7-with-node-7e401bc28b04).

I am able to do `yarn babel-node ./file.js` and it works for other examples.
