### ISSUE TITLE
404 with not encoded URI path parameter

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#1884]
## 🐛 Bug Report

If I send a wrong path parameter without appling an `encodedURI` I get a 404 response and a warn:

```
{"level":30,"time":1570179820901,"pid":21956,"hostname":"MSPIGOLON5591","reqId":3,"req":{"method":"GET","url":"/%25what%","remotePort":53476},"msg":"incoming request","v":1}
{"level":40,"time":1570179820902,"pid":21956,"hostname":"MSPIGOLON5591","reqId":3,"msg":"the default handler for 404 did not catch this, this is likely a fastify bug, please report it","v":1}
{"level":40,"time":1570179820902,"pid":21956,"hostname":"MSPIGOLON5591","reqId":3,"msg":"ÔööÔöÇÔöÇ / (ACL|BIND|CHECKOUT|CONNECT|COPY|DELETE|GET|HEAD|LINK|LOCK|M-SEARCH|MERGE|MKACTIVITY|MKCALENDAR|MKCOL|MOVE|NOTIFY|OPTIONS|PATCH|POST|PROPFIND|PROPPATCH|PURGE|PUT|REBIND|REPORT|SEARCH|SOURCE|SUBSCRIBE|TRACE|UNBIND|UNLINK|UNLOCK|UNSUBSCRIBE)\n    ÔööÔöÇÔöÇ * (ACL|BIND|CHECKOUT|CONNECT|COPY|DELETE|GET|HEAD|LINK|LOCK|M-SEARCH|MERGE|MKACTIVITY|MKCALENDAR|MKCOL|MOVE|NOTIFY|OPTIONS|PATCH|POST|PROPFIND|PROPPATCH|PURGE|PUT|REBIND|REPORT|SEARCH|SOURCE|SUBSCRIBE|TRACE|UNBIND|UNLINK|UNLOCK|UNSUBSCRIBE)\n","v":1}
```

## To Reproduce

```js
const fastify = require('fastify')({ logger: true })
fastify.get('/:strangeId', (req, reply) => {
  reply.send({ strangeId: req.params.strangeId })
})
fastify.listen(3000)
```

```
curl -X GET   http://localhost:3000/%what%   -H 'Accept: */*'   -H 'Accept-Encoding: gzip, deflate'   
-H 'Connection: keep-alive'   -H 'Host: localhost:3000'   -H 'User-Agent: PostmanRuntime/7.17.1'
```

All work with an encoded path param:

```
curl -X GET   http://localhost:3000/%25what%25   -H 'Accept: */*'   -H 'Accept-Encoding: gzip, deflate'   
-H 'Connection: keep-alive'   -H 'Host: localhost:3000'   -H 'User-Agent: PostmanRuntime/7.17.1'
```

## Expected behaviour

I wouldn't expect a 404.

With a plain server, the URL is:

```
{ req: '/%what%' }
{ req: '/%25what%25' }
```

```js
const http = require('http')
const server = http.createServer(function manageResponse (req, res) {
  console.log({ req: req.url })
  res.end('hello')
})
server.listen(3000)
```

## Your Environment

- *node version*: 12
- *fastify version*: 2.9
- *os*: Windows

**Comment by mcollina** [comment]
This looks like a bug that might originate from find-my-way.

cc @delvedor

**Comment by delvedor** [comment]
This happens because [fast-decode-uri-component](https://github.com/delvedor/fast-decode-uri-component) instead of throwing an error returns `null`, and because of that `find-my-way` [will call the default route](https://github.com/delvedor/find-my-way/blob/8cb73484d39d531ee7cf5b6735323e6b80985014/index.js#L334-L340).
Then in Fastify, we call the 404 handling, which can't handle that route as well, since also the 404 will get a 404.
This is not a bug in `find-my-way`, but it's instead something we are not handling correctly in Fastify.

**Comment by StarpTech** [comment]
> { req: '/%what%' }

According to https://en.wikipedia.org/wiki/Percent-encoding

> Because the percent character ( % ) serves as the indicator for percent-encoded octets, it must be percent-encoded as %25 for that octet to be used as data within a URI.

so the request path is wrong and 404 is fine.

**But** `%` is part of ASCII and can be used in the URI e.g `http://localhost:3000/%=+`. `%` is only relevant as escape char.

The significant change I made to make it work was in `fast-decode-uri-component`

```diff
++ var isPercent = /^%\d{2}$/

function decodeURIComponent (uri) {
  var percentPosition = uri.indexOf('%')
  if (percentPosition === -1) return uri
++  if (isPercent.test(uri) === false) return uri
```

**Comment by Eomm** [comment]
I know the URL was wrong, but with some path param, it is hard to spot if the variable is a business domain value that I wasn't aware of.

> but it's instead something we are not handling correctly in Fastify.

I would prefer a "500 unparsable path params" to avoid confusion instead of 404

**Comment by StarpTech** [comment]
Just for references: Hapijs has the exact same behaviour as fastify and expressjs throws an error `URIError: Failed to decode param '%deded'`. I agree with @Eomm we should produce a different error.

**Comment by delvedor** [comment]
I agree that we should produce an error, but it's not our fault, so it should be in the 4xx family *(400 should work)*.

**Comment by dougwilson** [comment]
FWIW Express sends back a 400 for the Express error listed above.

**Comment by jsumners** [comment]
`400` makes sense because the request is not valid. But I think `500` also makes sense because the server encountered an error when parsing. 🤷‍♂

**Comment by mcollina** [comment]
I would go with a 400.

**Comment by delvedor** [comment]
I've opened https://github.com/delvedor/find-my-way/pull/134, which is the first step for supporting this feature in Fastify core.
Give it a look!

**Comment by delvedor** [comment]
I've opened https://github.com/fastify/fastify/pull/1888 with the fix, let's continue the discussion there :)

**Comment by rburgst** [comment]
I am still getting error log this with fastify 3.14.2 for the following request

```
http 'localhost:3000/%c0'
```

**Comment by rburgst** [comment]
updated to fastify 3.17.0, same result

**Comment by Eomm** [comment]
> updated to fastify 3.17.0, same result

This is quite old issue, please open a new one with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by rburgst** [comment]
@Eomm done, see #3127
