### ISSUE TITLE
Incoming requests are not "seen" after running fastify for 10 minutes

### ISSUE THREAD

**Issue by tobiasmuehl** [fastify/fastify#1889]
## 🐛 Bug Report

Fastify works fine for the first 10 minutes, then doesn't "see" incoming requests, resulting in a 100% timeout rate.

The project is a pretty basic JSON API, previously running on PHP (Slim 3), that has been rewritten in TypeScript using Fastify. 

After some time, the fastify server does not respond to requests anymore, because requests are sent into a black hole. This only happens after some time (it varies between 5-20 minutes with a stable load of ~300 rps). It can be fixed by restarting frequently, but is an annoying solution. With the graceful shutdown plugin, reloading does not result in downtime.

Don't know what to do about this issue. Running the IBM APM it's clearly visible that incoming requests aren't "seen" (requests to the API are sent at stable rate)

![](https://i.imgur.com/oVggbRQ.png)
I reloaded the server shortly after 15:30

On the client end, this is observed as the response time reaching the client timeout:

![](https://i.imgur.com/k20Fi1x.png)

These long response times are not recorded on the server however:

![](https://i.imgur.com/Jtz929E.png)

Node clinic reports indicate no memory or resource leak.

We have lived with this limitation for weeks now, reloading the API in a 10 minute interval in production. 

Using only a handful of packages in this app:
```json
{"dependencies": {
    "@types/pg": "^7.4.14",
    "appmetrics-dash": "^5.2.0",
    "fastify": "^2.9.0",
    "fastify-autoload": "^1.0.0",
    "fastify-bearer-auth": "^4.2.0",
    "fastify-graceful-shutdown": "^2.0.1",
    "fastify-plugin": "^1.6.0",
    "fastify-postgres": "^2.0.0",
    "make-promises-safe": "^5.0.0",
    "pg": "^7.12.0"
}
```

## To Reproduce

Can't scope the issue properly. 

## Expected behavior

Expect the fastify server to accept all requests, no matter how long the server has been running already.

## Your Environment

- *node version*: ts-node 8.4.1
- *fastify version*: 2.9.0
- *os*: Ubuntu
- Running in PM2 cluster mode

**Comment by tobiasmuehl** [comment]
Considering running instance of fastify per API endpoint, to see if this problem is limited to a specific endpoint

**Comment by mcollina** [comment]
I think this is a bug in your application. If you think it's a bug in the framework, please open an issue with an example on how to reproduce.

**Comment by tobiasmuehl** [comment]
Alright, closing until I can scope this better
