### ISSUE TITLE
Fluent Schema not shown in documentations?

### ISSUE THREAD

**Issue by mcchrish** [fastify/fastify#1900]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

Had me scratching my head if this is an experimental feature since it's hidden. Is this expected?

<img width="550" alt="Screen Shot 2019-10-18 at 7 24 01 AM" src="https://user-images.githubusercontent.com/7200153/67054822-5d962000-f178-11e9-85a5-420e0e9a8d68.png">

**Comment by mcollina** [comment]
It needs to be added in this list: https://github.com/fastify/fastify#documentation. Would you like to send a PR?
