### ISSUE TITLE
Add headers to validation schema

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#191]
Hi, it would be great if we could validate headers too.

**Comment by allevo** [comment]
Hi!
This issue should be implemented in `fastify`, absolutely!
If you want contributing please submit a PR!

[Here](https://github.com/fastify/fastify/blob/master/lib/validation.js#L58) there's the validation stage and [here](https://github.com/fastify/fastify/blob/master/lib/validation.js#L28) `fastify` builds the schema.

**Comment by StarpTech** [comment]
@allevo thanks for pointing out. I will create a PR.

**Comment by delvedor** [comment]
Hi! A pr would be awesome, could you just wait https://github.com/fastify/fastify/pull/167 to land?
We are working on that and the current code will change :)

**Comment by StarpTech** [comment]
yes, I just want to ask about it. Stealth mode on :D

**Comment by delvedor** [comment]
Hi! Since https://github.com/fastify/fastify/pull/167 has just landed now is the right moment to work on this and https://github.com/fastify/fastify/issues/200 before release the next version :)

**Comment by StarpTech** [comment]
Nice. I will start asap.

**Comment by allevo** [comment]
NB: you can fix https://github.com/fastify/fastify/issues/200 too

**Comment by mcollina** [comment]
This has landed on master.
