### ISSUE TITLE
Unable to communicate with Fastify when developing with React Native

### ISSUE THREAD

**Issue by mkhoussid** [fastify/fastify#1913]
Hello,

How can I hit the backend with Fastify? With Express I would have to specify the IP address of my machine, instead of `localhost`. How can this be achieved with Fastify? I'm getting responses with Postman when making requests to `localhost:5000/test` but not with `http://192.168.10.1:5000/test`

TIA

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/blob/8fc4d9dd2774d77e75d44b8b5980d1eb4dd14975/docs/Server.md#listen
