### ISSUE TITLE
TypeScript FastifyError inherits from Error instead of ErrnoException

### ISSUE THREAD

**Issue by patoi** [fastify/fastify#1914]
## 🐛 Bug Report

`FastifyError` inherits from `Error` (JavaScript type), but it can hold other properties as `NodeJS.ErrnoException` (Node.js Error type) defined.

`ErrnoException` in:

Node.js v6:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v6/base.d.ts#L327

Node.js v8: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v8/base.d.ts#L375

```js
    export interface ErrnoException extends Error {
        errno?: number;
        code?: string;
        path?: string;
        syscall?: string;
        stack?: string;
    }
```
Error:
```js
interface Error {
    stack?: string;
}
```

## To Reproduce

`error` argument is a `FastifyError` instance. We need to cast to Node.js `ErrnoException` to get code property.

```js
    fastify.setErrorHandler((error, request, reply): void => {
        const e = error as NodeJS.ErrnoException
        if (e.code === 'ECONNREFUSED' || e.code === 'ENOTFOUND') {
            reply.send(new create.ServiceUnavailable())
```

## Expected behavior

If `interface FastifyError extends ErrnoException` then we needn't cast error.

See: https://github.com/fastify/fastify/blob/master/fastify.d.ts#L51

```js
    fastify.setErrorHandler((error, request, reply): void => {
        if (error.code === 'ECONNREFUSED' || error.code === 'ENOTFOUND') {
            reply.send(new create.ServiceUnavailable())
```

## Your Environment

- *node version*: 10
- *fastify version*: >=2.10.0
- *os*: Mac

**Comment by mcollina** [comment]
I think we need to support both. It can be an `Error` or a `ErrnoException`. We should also add `code` to `FastifyError`.

**Comment by L2jLiga** [comment]
@mcollina any updates on it? I do not see any `code` field :(

**Comment by mcollina** [comment]
This needs a PR. Would you like to send one @L2jLiga ?

**Comment by L2jLiga** [comment]
Sure
