### ISSUE TITLE
Cap speed for connection

### ISSUE THREAD

**Issue by dunklesToast** [fastify/fastify#1916]
## 💬 Questions and Help

Is there any possibility to cap the speed for one single connection?
In a specific project I don't want one client use more than 50MBit/s. Is this possible with fastify or is do i need nginx for this?

**Comment by mcollina** [comment]
Check out https://github.com/fastify/fastify-rate-limit. It does not limit bandwidth, but it might be possible to adapt it by using the Content-Length header.

**Comment by dunklesToast** [comment]
I also found this module but I need bandwidth limit so it's not going to work for me since - if i understand it correctly - will just block the access if a custom give Content-Length was exceeded. Will use nginx then since I'm using it anyway for proxieng!
