### ISSUE TITLE
Mention chainable method of inject in the docs

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1917]
With the latest release of `light-my-request`, our utility that enables the `inject` functionality, there is the support for the chainable API.
We should update the test and doc to mention this :)

Example:
```js
fastify.inject()
  .get('/')
  .headers({ foo: 'bar' })
  .query({ foo: 'bar' })
  .end((err, res) => {
    console.log(res.payload)
  })
```

Related: https://github.com/fastify/light-my-request/pull/53

**Comment by teorossi82** [comment]
@delvedor can I take care of this change? I would go adding the mention/example of the `chainable API` method in the doc and use it in the `test.js` file. What do you think?

**Comment by delvedor** [comment]
@teorossi82 go for it! :)

**Comment by delvedor** [comment]
I'm unassigning this issue, if you or someone else wants to pick it up, go for it!

**Comment by alemagio** [comment]
Hi, i would like to work on this.
I'm using Fastify but this is my first contributing to the project.
Any hint?

**Comment by mcollina** [comment]
Sure thing! You should add to https://github.com/fastify/fastify/blob/master/docs/Testing.md#testing-with-http-injection

The feature is the chainable API in:
https://github.com/fastify/light-my-request

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/2043.
