### ISSUE TITLE
Add fastify-sphinxsearch

### ISSUE THREAD

**Issue by BarryRufer** [fastify/fastify#1919]
Hello.

Your have fastify-elasticsearch, but maybe added fastify-sphinxsearch?

http://sphinxsearch.com/
https://github.com/SiroDiaz/sphinxql

**Comment by mcollina** [comment]
I've transfered the issue to the main repo. It would be nice to have such a module... would you like to contribute one?

**Comment by BarryRufer** [comment]
> would you like to contribute one?
Yes, I would like to try to be of service.

**Comment by Fdawgs** [comment]
How are you getting on @BarryRufer?

**Comment by Fdawgs** [comment]
I think it's worth closing this, it's been 3 years and no one else has requested/pushed for this plugin.
