### ISSUE TITLE
Fastify typings not infered properly

### ISSUE THREAD

**Issue by firasdib** [fastify/fastify#1927]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

I created a clean repo and tried the examples here: https://www.fastify.io/docs/v2.1.x/TypeScript/

The handlers are not receiving the correct typings, and when `request.query` should be of a specific type, it is not.

## Expected behavior

The types should be infered to the request handler method.

## Your Environment

- *node version*: 12
- *fastify version*: >= 2.10.0
- *os*: Mac

**Comment by RafaelGSS** [comment]
Hi @firasdib, can provide a code example?

**Comment by firasdib** [comment]
@RafaelGSS I copied the one on the page I linked

**Comment by Eomm** [comment]
Are you saying that the examples in docs are wrong?

Would you like to send a pr to fix them? 💪🏻

**Comment by firasdib** [comment]
@Eomm I think the typescript types are wrong, not the docs. I don't know for sure, but please do confirm if it works for you.

**Comment by firasdib** [comment]
It seems it stops working when you register plugins/routes. If you use `app.register(myRoutes, { prefix: 'something' });` the typings stop working

**Comment by Ethan-Arrowood** [comment]
Just checked out your codesandbox. It is not working because of how you broke up your code. When you define a handler standalone like that you need to specify the types for said handler function. Standalone, the following function is just an anonymous arrow function with parameters `request` and `reply`. TypeScript cannot infer that this function will be used in the Fastify function handler; thus, TypeScript infers the parameter types as `any`. 
```typescript
const myHandler = (request, reply) => {
  const { foo, bar } = request.query;
  // this should error on 'bar'
  // request.query is 'any'

  reply.send({ foo, bar });
};
```

To fix this you can import `RequestHandler` from the fastify namespace and assign it to the handler function:
```typescript
const myHandler: RequestHandler<any, any, Query> = (request, reply) => {
  const { foo, bar } = request.query; // errors on bar
  reply.send({ foo, bar });
};
```
The `any` are in place of the Http Request and Response typings. You should pass the appropriate objects from `@types/node` `http` module

**Comment by firasdib** [comment]
Thats quite cumbersome. Is there no way to shorten it down, without having to redefine all types?

Having it inline isn’t always optimal, but if there is no other clean solution...


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Ethan-Arrowood** [comment]
This is how TypeScript works. It will infer types, but it needs to be provided the right context. Your `const myHandler` definition provides no type information so there is nothing for TypeScript to infer from. 

If you have `strict` enabled in your configuration, technically that definition would be invalid as TypeScript could not be certain the `query` or `send` parameters exist on the respective objects. 

If you write the handler method inline then TypeScript can infer the types by the prewritten definitions (fastify.d.ts); thus, why your code properly errors that `bar` does not exist on type `Query`. 

---

If you are extrapolating your handler function into its own function definition then you need to tell TypeScript what type it will be. This way you could pass it around to multiple routes and TypeScript can always be certain the parameters and return type will be valid. If that is too cumbersome then I recommend writing it inline.

Hope this helps clear things up!

**Comment by firasdib** [comment]
thanks for the clarification
