### ISSUE TITLE
[Benchmarks] Comparison with not Node?

### ISSUE THREAD

**Issue by jhabdas** [fastify/fastify#193]
Benchmarks look impressive. It would be helpful to see some comparisons, even if 🍎 to 🍊 on Fastify compared to Caddy and Nginx so individuals can understand how more recent JS tools are stacking up with compiled code.

**Comment by mcollina** [comment]
It's not part of the goal here. The benchmarks are part of a very simplicistic case, that might not respect your usecase. I would prefer to see an independent analysis for this.

**Comment by abenhamdine** [comment]
For this purpose, it could be more appropriate to add fastify to techempower bench, eg see https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=json&b=2&l=8vn01r&a=2
to contribute : https://github.com/TechEmpower/FrameworkBenchmarks
