### ISSUE TITLE
Check benchmark on comment

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#1931]
## 🚀 Feature Proposal

It would be useful to run the benchmark in some branches/PR.

## Motivation

Check in a well known and shared environment if we have more or less performance.

## Example

Maybe a GH action that listens for a defined comment and posts the results in the PR.

The code and the configuration are already defined in this repo:
https://github.com/fastify/benchmarks

It should be possible to write a new GH workflow

**Comment by delvedor** [comment]
It's a nice idea, but I fear that we would get inconsistent results.
At the moment the official benchmarks are taken on a physical machine *(CPU-optimized server (Ubuntu 18.04.2 x64 | 8 vCPUs | 32GB | Node 10.15)* to avoid problems related to shared environments.

**Comment by RafaelGSS** [comment]
I think that is a nice idea too. Maybe the inconsistent results can be better explained to the community and provide us a better audit

**Comment by Eomm** [comment]
I'm working to create a GH action in order to try and check the results.
The target would be to check if there is some drop in performance (ie: if the start point is 1000 req/sec in master, and the PR is 900 res/sec it is worth to check deeper)

The server would be a virtual server with 2-core CPU and 7 GB of RAM memory [ref](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources)
