### ISSUE TITLE
Missing version field in RouteShorthandOptions

### ISSUE THREAD

**Issue by Svjard** [fastify/fastify#1932]
## 🐛 Bug Report

Missing the `version` field for Route options as specified in the documentation at https://www.fastify.io/docs/latest/Routes/

## To Reproduce

Create a route in typescript with the version field and typescript will throw an error: ... 'version' does not exist in type 'RouteOptions<Server, IncomingMessage, ServerResponse, DefaultQuery, DefaultParams, DefaultHeaders, any>'

```typscript
fastify.route({
  version: '1.0.0'
})
```

## Expected behavior

Typescript to recognize the version field when setting RouteShorthandOptions.

## Your Environment

- *node version*: 10
- *fastify version*: 2.10.0
- *os*: Mac

**Comment by delvedor** [comment]
Hello! You are right!
Would you like to send a pr to fix this?

**Comment by Svjard** [comment]
Was PR #1933, good to close this now.

**Comment by joanna81** [comment]
12.11.2019 14:45 "Manuel Spigolon" <notifications@github.com> napisał(a):
