### ISSUE TITLE
Unnecessary json stringify by content-type

### ISSUE THREAD

**Issue by YouCanKeepSilence** [fastify/fastify#1936]
## 🐛 Bug Report

When i set Content-Type 'application/json' in header and my payload is json-string the framework uses stringify to convert payload to string. So as result i get a twice stringified string.

## To Reproduce

For example: I got json string from Redis and try to send it with Content-Type 'application/json' header, after it sent i get  twice stringified json string in response.

## Expected behavior

The framework should check the type of payload before stringifying it.

## Your Environment

- *node version*: 10
- *fastify version*: >=2.10.0
- *os*: Mac

**Comment by delvedor** [comment]
Hello! You are right!
Would you like to send a pr to fix this?

**Comment by YouCanKeepSilence** [comment]
Yes, i created one #1937

**Comment by YouCanKeepSilence** [comment]
Merged in #1937 MR.
