### ISSUE TITLE
Invalid QueryString validation

### ISSUE THREAD

**Issue by Neur0plasticity** [fastify/fastify#1943]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

    method fastify.route() ... input querystring does not validate querystrings.

## To Reproduce

step 1) paste code provided, this code is from your demo

step 2) in browser ... localhost:3000/?bob=bob
Paste your code here:

```js
fastify.route({
    method: 'GET',
    url: '/',
    schema: {
      // request needs to have a querystring with a `name` parameter
      querystring: {
        name: { type: 'string' }
      },
      // the response needs to be an object with an `hello` property of type 'string'
      response: {
        200: {
          type: 'object',
          properties: {
            hello: { type: 'string' }
          }
        }
      }
    },
    // this function is executed for every request before the handler is executed
    beforeHandler: async (request, reply) => {
      // E.g. check authentication
      console.log("beforeHandler");
    },
    handler: async (request, reply) => {
      return { hello: 'world'}
    }
  });
```

## Expected behavior

Paste the results here:

```js
/*
   the response object is still returned, when an invalid querystring should immediately send back error 
   
    and kill the route thread.
*/
```

## Your Environment

- *node version*: 12
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux

**Comment by mcollina** [comment]
You are missing the `required` part in your schema. I'd recommend to use https://www.npmjs.com/package/fluent-schema to generate it.
