### ISSUE TITLE
Eslint error for async instance

### ISSUE THREAD

**Issue by ReTWi** [fastify/fastify#1962]
Eslint gives error to line "async api":

> error  Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises

```js
fastify.register(
  async api => {
    api.get('/', async (req, res) => {
      return res.send({ hello: 'world' })
    })
  },
  {
    prefix: '/api'
  }
)
```

If i change to:
```js
fastify.register(
  api => {
    api.get('/', async (req, res) => {
      return res.send({ hello: 'world' })
    })
  },
  {
    prefix: '/api'
  }
)
```

Error will be gone, but fastify will not run :(

**Comment by Ethan-Arrowood** [comment]
You don't return `res.send` just return the payload:
```javascript
return {hello: 'world'}
```

**Comment by ReTWi** [comment]
@Ethan-Arrowood same error :(

> 127:3  error  Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises

```
fastify.register(
  async api => {
    api.get('/', async () => {
      return { hello: 'world' }
    })
  },
  {
    prefix: '/api'
  }
)
```

**Comment by jsumners** [comment]
`fastify.register` _either_ accepts an "async function" or a function with the signature `function (fastifyInstance, options, callback) {}`. If you do not supply a function that returns a promise (i.e. an "async function") then you need to invoke the callback.

Please read https://github.com/fastify/fastify/blob/a0ec0e93a1a16af6275de224108daa7344eeb82b/docs/Plugins.md
