### ISSUE TITLE
Stripe webhooks rawBody

### ISSUE THREAD

**Issue by borabaloglu** [fastify/fastify#1965]
Hi all,

I have to use stripe's webhooks. At constructEvent function, rawBody has to be given as a parameter. However I couldn't make it. As far as I know, fastify has no option as "rawBody". I tried to use custom body parser. Here is the code that I used:

```javascript
fastify.use(bodyParser.json({
  verify: function verify(req, res, buf, encoding) {
    req.rawBody = buf;
  },
}));
```

Somehow it works. It successfully does all the jobs but some reason that I can't understand I got an error such as:

```net/http: request canceled (Client.Timeout exceeded while awaiting headers)```

So, what do you recommend? Can you help me please?

**Comment by mcollina** [comment]
You should not use bodyParser. The body is parsed by fastify internally: https://www.fastify.io/docs/latest/ContentTypeParser
