### ISSUE TITLE
Drop support for EOL Node.js versions

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1972]
In v3 we will drop the support for Node.js v6 and v8.
We should do the same for all of our dependencies, `fast-json-stringify`, `find-my-way`, `avvio`...

**Comment by jsumners** [comment]
Should probably write a bot or something to dump a check list here, or the milestone, for organization modules.

**Comment by Eomm** [comment]
As Christmas present, I will complete [massive-wax](https://github.com/Eomm/massive-wax/tree/first-impl) that let you do these massive tasks to a list of repos:
- clone the project
- edit the project
- open a PR with the changes

example of run:
```
node bin/run upgrade -T='migrate to mit license' -C='license to MIT' -F -b mit -m='.json$' -p='./toMit.js' -r https://github.com/pkgjs/nv -r https://github.com/pkgjs/create -r https://github.com/pkgjs/support -r https://github.com/pkgjs/statusboard -r https://github.com/pkgjs/triagebot -t
```

**Comment by mcollina** [comment]
Wooow, awesome. Could you use this to update any file in there?

**Comment by Eomm** [comment]
yes, you can do whatever to any file in the repo (or create new one as well)

[this](https://github.com/Eomm/massive-wax/blob/first-impl/src/processor/greenkeeper.js) is the file the user should create, for example, to add to greenkeeper ignore a module to a list or repo 😂

**Comment by delvedor** [comment]
Great work @Eomm!!

**Comment by Eomm** [comment]
The tool is ready, I will take care of it for v3 👍

**Comment by jsumners** [comment]
Regarding a checklist: I added a few issues to `fastify-cookie` and labeled them "good first issue" and they got resolved quite quickly by the community. The result being `fastify-cookie` has a `next` branch that is pretty much ready to go for v3 (just needs `fastify-plugin` metadata updates). Maybe the same can be done for other repos?

**Comment by mcollina** [comment]
Definitely +1. We might want to write a tiny script to do this for us.

**Comment by mcollina** [comment]
This is done.
