### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1974]
In Fastify v3 we will have first class ESM support.

```js
fastify.register(import('my-plugin'))
```

**Comment by jsumners** [comment]
How will this work? ESMs is not synchronous as CJS modules are.

**Comment by mcollina** [comment]
See https://github.com/mcollina/avvio/pull/91.
We might be able to ship it even in v2.

**Comment by jsumners** [comment]
The core documentation could be improved: https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_code_import_code_expressions

It's very easy to overlook that the example is telling you that `import()` returns a promise. In fact, the whole document is missing a section detailing that ESMs are not synchronous and do not work the same way that CJS modules do. I can tell you that a lot of people do not realize this fact. They just want to use the syntax for whatever reason.

**Comment by lmammino** [comment]
Really looking forward to being able to use this feature <3

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1984.
