### ISSUE TITLE
Docs: Highlight role of async in declaring routes

### ISSUE THREAD

**Issue by mrchief** [fastify/fastify#1978]
## 🚀 Feature Proposal

I believe the documentation, especially under "Getting Started" doesn't cover the importance of using `async` keyword in declaring routes.

E.g. consider this snippet from docs

```
async function routes (fastify, options) {
  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
}

module.exports = routes
```

There is no `await` call in any of the inside functions, so technically, removing `async` should not cause any issues. However, that is not the case. Removing `async` causes multiple problems

```
function routes (fastify, options) {
  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
}

module.exports = routes
```

will result in a startup error:

```
AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time
```

and ignoring async in the handler

```
async function routes (fastify, options) {
  fastify.get('/', (request, reply) => {
    return { hello: 'world' }
  })
}

module.exports = routes
```

will cause the request to `/` hang and timeout.

## Motivation

Anyone starting fresh needs to understand the significance of these keywords and why one would need them. Ignoring them doesn't produce the same effect as one would expect of standard Promise behavior.

## Example

N/A

**Comment by RafaelGSS** [comment]
Well... 
```js
function routes (fastify, options) {
  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
}

module.exports = routes
```

should call `next`. Can show what part of the documentation (with a link) has an error of reproduction?

**Comment by mcollina** [comment]
> Anyone starting fresh needs to understand the significance of these keywords and why one would need them. Ignoring them doesn't produce the same effect as one would expect of standard Promise behavior.

Plugins should either call the callback or return a promise. Async functions returns a promise. A normal function does not. I'm not exactly sure what you mean from "standard promise behavior", as this seems standard to me.

**Comment by jsumners** [comment]
This document does not make it clear why it has opted to use the `async` keyword to create a promise -- https://github.com/fastify/fastify/blob/37fc92d931217e05a80e7c37886a576d3d4e8c3d/docs/Getting-Started.md#your-first-plugin

It merely has an easy to miss link to the route definition documentation which in turn has this section -- https://github.com/fastify/fastify/blob/37fc92d931217e05a80e7c37886a576d3d4e8c3d/docs/Routes.md#async-await

**Comment by mrchief** [comment]
> Async functions returns a promise.

True. Since you're not awaiting anything here, `async` seems redundant. If the intent is to make the handler always return a promise, then it needs to say so explicitly. 

By standard behavior, I meant that methods that return a promise can choose to return a resolved value instead of a promise and it would still not break anything. Unless the caller tries to rely on promise semantics and expects to chain further, which is what seems to be the case here.

**Comment by mcollina** [comment]
> By standard behavior, I meant that methods that return a promise can choose to return a resolved value instead of a promise and it would (or rather should) not break anything. Unless the caller tries to rely on promise semantics and expects to chain further, which is what seems to be the case here.

I think you are referring to `await` behavior, and not `Promise` behavior. Anyway, I think we could implement something like that. A PR would be helpful.

**Comment by mrchief** [comment]
> I think you are referring to await behavior, and not Promise behavior. 

I haven't made the distinction up until now :) but I get your point. 

> Anyway, I think we could implement something like that. A PR would be helpful.

PR to implement the `await` behavior or just doc updates?

**Comment by mcollina** [comment]
> PR to implement the await behavior or just doc updates?
 
about the change in behavior

**Comment by mrchief** [comment]
Not stale

**Comment by mk-pmb** [comment]
Is this solved in latest version?
