### ISSUE TITLE
Docs: Starting your first server section is not clear enough

### ISSUE THREAD

**Issue by mrchief** [fastify/fastify#1979]
## 🚀 Feature Proposal

Under [Getting Started > Your First Server](https://www.fastify.io/docs/v1.13.x/Getting-Started/#your-first-server), it is not clear how to run the example (`node server.js` in this case).

Later on, the docs talk about plugins and rewriting routes as plugins (https://www.fastify.io/docs/v1.13.x/Getting-Started/#your-first-plugin) and then one is introduced to fastify-cli.

Finally, [Run your server](https://www.fastify.io/docs/v1.13.x/Getting-Started/#run-your-server-from-cli) talks about using the cli to start the server which can be mistaken as the only way to start the server. That leads to https://github.com/fastify/fastify/issues/262 and the eventual fix. 

## Motivation

Running the examples from the docs should not result in errors and surprises. Most of us are simply copy/pasting and trying to get something up and running so adding clarity would help immensely.

## Example

I think adding a section that describes how to run your first server will be helpful in avoiding this confusion and error for first timers.

**Comment by mcollina** [comment]
Would you like to send a PR on how you'd improve the docs?

**Comment by mrchief** [comment]
Yes, would love to. I think a few simple additions should do the trick.

**Comment by mcollina** [comment]
Go ahead and thanks for feedback!

**Comment by mrchief** [comment]
not stale
