### ISSUE TITLE
getting FST_ERR_CTP_INVALID_CONTENT_LENGTH although my request does provide correct body length 

### ISSUE THREAD

**Issue by Denusdv** [fastify/fastify#1986]
Using  "fastify": "^2.10.0"

I'm struggling with pretty weird error I'm getting.

The server has a post service which is supposed to handle requests of gzipped JSONs body.

When I try to test it using curl or any other http client, I'm getting Request body size did not match Content-Length

My request does provide the Content-Length, the length of compressed file

 curl -v -i http://127.0.0.1:8081/eventproxy/track -H 'Content-Encoding: gzip' -H "Content-Type: application/json" -H "Content-Length:479" --data-binary @sampleBatch.json.gz
I'm pretty sure it's related to the Fastify, but can't figure out what I'm missing. Any idea how to get it working.

Thanks

**Comment by mcollina** [comment]
Can you please provide a full example on how to reproduce?

**Comment by Denusdv** [comment]
Server

```
require('dotenv').config();
const  zlib = require("zlib");
const port = 8081;
var fastify;

fastify = require('fastify')({logger: true})


/**
 * Setup an fastify server and define port to listen all incoming requests for this application
 */
const setUpFastify = () => {

    fastify.post('/track', function (req, reply) {
        if (apiKeyValidator(req, reply)) {
            if (req.headers['content-encoding'] && req.headers['content-encoding'] == 'gzip') {
                zlib.gunzip(req.body, function (err, dezipped) {
                    batch_events_handler(req.headers["x-api-key"], JSON.parse(dezipped.toString('utf-8')), reply)
                });
            }
            batch_events_handler(req.headers["x-api-key"], req.body, reply)
        }
    })

    fastify.listen(port, "localhost", () => {
        console.log(`Worker listening on ` + port + ` PID: ${process.pid}`)
    })
}

setUpFastify()
```


curl:

`curl -X POST "http://127.0.0.1:8081/track" -H "accept: application/json" -H "x-api-key: sdsd" -H "Content-Type: application/json"  -H "Content-Length:479" -H "Content-Encoding: gzip"  --data-binary @sampleBatch.json.gz
`

try any binary data

**Comment by Eomm** [comment]
Copy answer from [here](https://stackoverflow.com/questions/59345698/fastify-returns-fst-err-ctp-invalid-content-length/59359972#59359972)

You need to change approach because the default content parser doesn't manage compression and will try to parse the `body`.

So to manage the compression you can overwrite the default `addContentTypeParser` and add the decompression logic:

```
const zlib = require('zlib')
const port = 8081
var fastify

fastify = require('fastify')({ logger: true })

/**
 * Setup an fastify server and define port to listen all incoming requests for this application
 */
const setUpFastify = () => {
  fastify.addContentTypeParser('application/json', { parseAs: 'buffer' }, function (req, body, done) {
    if (req.headers['content-encoding'] && req.headers['content-encoding'] === 'gzip') {
      zlib.gunzip(body, function (err, dezipped) {
        if (err) {
          done(err, null)
        } else {
          done(err, JSON.parse(dezipped.toString('utf-8')))
        }
      })
    } else {
      done(null, JSON.parse(body.toString('utf-8')))
    }
  })

  fastify.post('/track', function (req, reply) {
    reply.send(req.body)
  })

  fastify.listen(port, 'localhost', () => {
    console.log('Worker listening on ' + port + ` PID: ${process.pid}`)
  })
}

setUpFastify()
```

Note that fastify uses [`secure-json-parse`](http://npmjs.com/package/secure-json-parse) to parse the json string.

And the curl, note the `--data-binary`:

```
curl --request POST \
  --url http://127.0.0.1:8081/track \
  --header 'Accept: */*' \
  --header 'Accept-Encoding: gzip, deflate' \
  --header 'Connection: keep-alive' \
  --header 'Content-Encoding: gzip' \
  --header 'Content-Length: 739' \
  --header 'Content-Type: application/json' \
  --header 'Host: 127.0.0.1:8081' \
  --data-binary package.json.gz
```

PS trying the curl with the `@`, the payload sent was 1-byte length

**Comment by delvedor** [comment]
Nice example @Eomm we should add it to our docs and/or to our examples directory :)

**Comment by hello2dj** [comment]
how to solve it. It happens all the time on my production service

**Comment by mcollina** [comment]
@Eomm we might want to do a plugin/hook to haandle this case

**Comment by joelwallis** [comment]
I gotta work on this same issue this week, and it seems the way you're testing the bug isn't enough. By using cURL's `--data-binary` option, you embed fs-specific metadata into the compressed body of the URL, leading to this unmatch of the body length.

I managed to simulate the correct behavior with a custom Node.js script:

```js
const fetch = require("node-fetch");
const util = require("util");
const zlib = require("zlib");

const gzipAsync = util.promisify(zlib.gzip);

(async () => {
  try {
    const json = `{ "username": "joel", "password": "please!" }`;
    const body = await gzipAsync(Buffer.from(json));

    console.log(`body has ${body.length} bytes.`);
    console.log(`json has ${body.length} bytes.`);

    await fetch(`http://your-fastify-app.local:8080/`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Encoding": "gzip",
        "Content-Length": body.length
      },
      body
    });
  } catch (err) {
    console.error('Something went wrong in your test')
    console.error(err);
  }
})();
```

I'm temporarily solving this by overwriting the default `application/json` parser to a custom one that decompresses request bodies before parsing the JSON itself, but I think it should be done as an extension. I see that there's an official project called fastify-compress which looks like a good place to hold this functionality. I'll see if I can provide a pull request with it.

See fastify/fastify-compress#105
