### ISSUE TITLE
preValidation: req.body is not null

### ISSUE THREAD

**Issue by hello2dj** [fastify/fastify#1989]
## 🐛 Bug Report

preValidation req.body has been parsed. but doc says it is null
![image](https://user-images.githubusercontent.com/10645383/70984417-6a41e080-20f5-11ea-887b-ba4fc465f8b5.png)

## To Reproduce

Paste your code here:

```js
   const ff = require('fastify');
   
   const f = ff({});
   
    f.addHook('preValidation', async (req, reply) => {
        console.log(req.body);
        // not null
    });
    
     f.post('/api', async (req, reply) => {
             reply.send("");
     });
  
    f.listen(3001);
```

curl -XPOST -d '{"count": 123}'  -H 'Content-Type: application/json' localhost:3001/api

## Your Environment

- *node version*:  lts/erbium
- *fastify version*: =2.10.0"
- *os*: Mac
- *any other relevant information*

**Comment by RafaelGSS** [comment]
Good catch! This message should show in `preParsing`.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1991.
