### ISSUE TITLE
Reasons for increased performance?

### ISSUE THREAD

**Issue by agauniyal** [fastify/fastify#199]
Would you mind telling major points how you increased the performance of fastify when compared to already lightweight framework like express or restify? ~2.5x is very good benchmark and I'm already looking forward to using fastify as soon as it adds auth strategies :)

**Comment by StarpTech** [comment]
Have an eye on the deps they are highly optimized for performance.

```json
{
    "ajv": "^5.2.2",
    "fast-json-stringify": "^0.12.2",
    "fastseries": "^1.7.2",
    "find-my-way": "^1.3.2",
    "pino": "^4.7.1",
    "reusify": "^1.0.2"
}
```

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify! :)

Our dependencies are very important, but they are not the main reason of our performances.
We worked a lot on internal optimization, we studied how V8 optimizes our code and written a very straightforward logic, as you can see from our internal [lifecycle](https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md).

I recommend you to checkout:
- https://github.com/davidmarkclements/v8-perf
- https://www.youtube.com/watch?v=5z46jJZNe8k
