### ISSUE TITLE
Under Nodejs v13.5.0, Fastify HTTP2.0 use .finished which could be true when .writableEnded is false

### ISSUE THREAD

**Issue by alanlzhang** [fastify/fastify#1993]
Maybe it is a nodejs bug, but in handleRequest.js:
function preValidationCallback (err, request, reply) {
  if (reply.sent === true || reply.res.**finished** === true) return
  if (err != null) {
    reply.send(err)
    return
  }
...
function preHandlerCallback (err, request, reply) {
  if (reply.sent || reply.res.**finished** === true) return
  if (err != null) {
    reply.send(err)
    return
  }
...

when handle **HEAD** request, reply.res.**finished** will be true, but reply.res.**writableEnded** is false. 
use .finished would cause client pending because server early returns. 
I changed my node_modules/fastify source, use **writableEnded**, then everything is Ok.

Since .finished is Deprecated in Nodejs  v13.4.0, I think use .writableEnded (if it exists) is the right thing.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by sheplu** [comment]
Can I take it ?
I am mostly new to fastify but this will let me dive a little bit in the core

**Comment by mcollina** [comment]
go for it!
Il 26 dic 2019, 20:16 +0100, Jean Burellier <notifications@github.com>, ha scritto:

**Comment by kibertoad** [comment]
@sheplu Do you need any help with this?

**Comment by mcollina** [comment]
@kibertoad if you'd like to send a PR, please go ahead. It's unlikely that @sheplu will send one at this point.

**Comment by dnlup** [comment]
I ran some tests, and also version `10.20.1` is affected by this. For version `13.5.0`, the proposed fix works like a charm. For version 10, I don't know if we could resolve the problem in a similar way (`writableEnded` is not available there). I would like to do some research. Any suggestion is appreciated.

**Comment by mcollina** [comment]
I don't think we'll likely get a backport of `writableEndeded` in v10. Go ahead with the research.

Worst case, we'll do some conditionals based on the Node.js version.
