### ISSUE TITLE
multidomain and redirect

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1996]
Hello, i have 2  domains ( first is site http only, second https only )

Need use vhost plug?

Use vhost
```
const server = require('fastify')({
    logger: true,
})
server.register(vhost, {
  upstream: 'http://localhost:3000',
  host: 'site1.com'
})
 
server.register(vhost, {
  upstream: 'http://localhost:3001',
  host: 'site2.com',
})
 
server.listen(80, '0.0.0.0' )



const server2 = require('fastify')({
    logger: true,
})
server2.register(vhost, {
  upstream: 'https://site2.com:3002',
  host: 'site2.com'
})
  
server2.listen(443, '0.0.0.0' )
```

HTTP work
Problem with HTTP2 SSL
Then i go to site2.com -> https://site2.com:3002  site not open, problem with security ( ERR_SSL_PROTOCOL_ERROR )
If open https://site2.com:3002 all fine

And how cretate redirect? http -> https and reverse

**Comment by borodadada** [comment]
> Hello, i have 2 domains ( first is site http only, second https only )
> 
> One port incomming 80 or 443 and several sites
> 
> Need use vhost plug? Or proxy?

**Comment by jsumners** [comment]
See https://github.com/fastify/fastify/blob/master/docs/Recommendations.md#use-a-reverse-proxy
