### ISSUE TITLE
Add `request.headers` helper to avoid `request.req.headers`

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#200]

**Comment by allevo** [comment]
Hi,
you can directly access to `headers`through `req` property of `Request` fastify instance. See [here](https://github.com/fastify/fastify/blob/master/lib/request.js#L5).

Seeing the fastify `Request` constructor the `headers` miss.
But you can do it easily using `decorateRequest` right now!
```js
fastify.decorateRequest('headers', function () {
  return this.req.headers
})
```

In the code:
```js
fastify.get(function (req, reply) {
  const headers = req.headers()
  reply.send(headers)
})
```

See [here](https://github.com/fastify/fastify/blob/master/docs/Decorators.md)

Obviously the provided code adds an little overhead for the function call.
NB: no closures are added here, so the performance is not so bad

**Comment by StarpTech** [comment]
Hi @allevo thanks for the snippet but I would like to know why don't provide a shortcut like `req.params`, `req.body` ? 

```js
fastify.get('/', function (request, reply) {
  request.headers
})

```
is much more cleaner and intuitive

**Comment by mcollina** [comment]
Definitely +1 for having a shortcut! How about a PR?

**Comment by allevo** [comment]
@StarpTech absolutely!

**Comment by StarpTech** [comment]
I will create PR

**Comment by mcollina** [comment]
This was done in #234.
