### ISSUE TITLE
Invalid register hook?

### ISSUE THREAD

**Issue by imbacc** [fastify/fastify#2011]
## 💬I don't know register hook

**fastify.register(require('./config/intercept'))**

![微信图片_20191227160652.png](https://i.loli.net/2019/12/27/KuH1SQeOmIzXhyU.png)

**Comment by mcollina** [comment]
Can you please clarify what you a trying to achieve? Moreover a full, runnable example will be useful.

**Comment by imbacc** [comment]
![image](https://user-images.githubusercontent.com/28825000/71509898-f4ddc900-28c7-11ea-81ba-3ada1af45a0b.png)
register interceptor
