### ISSUE TITLE
body should be object

### ISSUE THREAD

**Issue by MagicFun1241** [fastify/fastify#2012]
## Bug Report

In any case if body validation is enable, the same error appears.

## Example

```js
fastify.post('/', {
    schema: {
        body: {
            type: 'object',
            required: [ 'one' ],
            propertys: {
                one: { type: 'string' }
            }
        }
    }
}, async (request, reply) => {
    return { hello: 'world' };
})
```

Returns:

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body should be object"
}
```

## My Environment

- *node version*: 12.13.0
- *os*: Windows

**Comment by jsumners** [comment]
You have designated that the `POST` body should be an object. So what is the error? Do you have `propertys` in your actual code? If so, you need to rename it `properties`.
