### ISSUE TITLE
Set modifyCoreObjects to false by default in v3

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2013]
In Fastify v1 and v2, [`modifyCoreObjects`](https://www.fastify.io/docs/latest/Server/#modifycoreobjects) is `true` by default because we needed to provide full support for middlewares, in v3 this will no longer apply, as an external plugin will provide the middlewares.

We can either decide to  (1) stop entirely modifying the core objects and rely on the plugins to do that themselves or  (2) set `modifyCoreObjects` to `false` by default.

Thoughts?

1) 👍 
2) 😄 

Related: https://github.com/fastify/fastify/pull/1476 https://github.com/fastify/fastify/issues/1503

**Comment by jsumners** [comment]
We should probably make use of the new deprecation support. It's not fun to keep this stuff around, but we can very easily release new majors that only drop deprecations (keeping our LTS schedule in mind). Plus, I think we are starting to follow along with the _active_ Node core LTS schedule. So these deprecated items will naturally disappear within ~1year of being deprecated.

**Comment by delvedor** [comment]
@jsumners so your suggestion is to set `modifyCoreObjects` to `false` by default and log a deprecation warning if the user tries to configure it?

**Comment by jsumners** [comment]
Maybe? I don't know. This is not a feature I have ever used so I don't know how to handle it.

**Comment by delvedor** [comment]
I agree that normally a deprecation cycle would help, but we have added this feature only for improving the middlewares support, and if the two middlewares plugins will start adding these properties themselves, then I think we are safe enough to remove the feature from here, as from a middleware user nothing will change, where for a not-middleware users, we will execute less code.

**Comment by delvedor** [comment]
Just to be clear, this is the lines we are talking about:
https://github.com/fastify/fastify/blob/e922bbf0a528c25a1b8b661ec8d5b9a8b725666a/lib/route.js#L308-L340

**Comment by mcollina** [comment]
I think the only blocker is the `trustProxy` option.

I would recommend:

* [ ] implement https://github.com/fastify/fastify/issues/1551
* [ ] move the `trustProxy` implementation inside our `Request` object
* [ ] _drop_ `modifyCoreObjects` altogether

**Comment by delvedor** [comment]
@mcollina so you are suggesting to add `ip`, `ips` and `hostname` to our request object?

How about https://github.com/fastify/fastify/issues/327? Should we start again discussing about it? It looks like these two are connected to me.

**Comment by mcollina** [comment]
> so you are suggesting to add ip, ips and hostname to our request object?

Yes, we should also support trustProxy. I would add them as getters.

**Comment by delvedor** [comment]
@mcollina `ip`, `ips` and `hostname` were already there at the end :P
https://github.com/fastify/fastify/blob/e922bbf0a528c25a1b8b661ec8d5b9a8b725666a/lib/request.js#L10-L12

**Comment by delvedor** [comment]
Closed in #2015.
