### ISSUE TITLE
415: Unsupported media type

### ISSUE THREAD

**Issue by Pitu** [fastify/fastify#202]
I've been toying with fastify around and came across an issue when trying to POST to a url from a XMLHttpRequest directly from a html form. It seems the data is sent using `content-type:application/x-www-form-urlencoded; charset=UTF-8` so I went to the documentation to try and figure out how to solve it but I'm still unsure.
Also tried with `fastify.register(require('fastify-accepts'))` but doesn't seem to help on this situation. Would it be possible to get some tips as to how to approach this?

**Comment by mcollina** [comment]
We have @jsumners https://www.npmjs.com/package/fastify-formbody!

We need to add it to the README, and maybe mention it in the docs. Would you (or someone else!) like to send a PR?

**Comment by Pitu** [comment]
Thanks for pointing it out! You can find the PR here 7f02eed

**Comment by jsumners** [comment]
Sorry for being so slow about this. Thank you for the PR.

**Comment by korobaka** [comment]
Reopening this thread, I have the same eerror with the latest version of fastify and fastify formbody. Here is my session.js code:
`
const
    bcrypt = require('bcrypt'),
    umodel = require('../../db/models/users');

module.exports = (req, res) => {
    console.log(req.body);
    const { username, password } = req.body;
    if (!username || !password) {
        let url = "/login?message=Some%20fields%20are%20missing";
        if (username) url+=`&prefill=${username}`;
        res.redirect(url);
        return;
    }
    umodel.findOne({ username }).then(result => {

    })
        .catch((e) => {
            res.redirect("/login?message=An%20internal%20error%20occured,%20please%20retry");
        });
}
`
My routes.js code:
`
module.exports = (fastify, opts, done) => {
    fastify.get("/dms", require('./routes/getTwitterDms'));

    fastify.get("/login", require('./routes/loginPage'));
    fastify.post("/session", require('./routes/session'));
    done();
};
`
And, finally, my index.js code:
`
// Use .env
require('dotenv').config();

// Import modules
const twit = require('twit');
const bcrypt = require('bcrypt');
const fastify = require('fastify');
const mongoose = require('mongoose');

// Create app
const app = fastify();

// Launch RestAPI routes
app.register(require("./api/routes"));

// Register fastify modules
app.register(require('fastify-static'), {
    root: __dirname+"/views",
});
app.register(require('fastify-formbody'));
app.register(require('fastify-cookie'));
app.register(require('fastify-session'), {secret: process.env.SESSION_SECRET});

// Connect database
mongoose.connect(process.env.MONGO_URL, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
})
    .catch(() => {
        throw new Error("Unable to connect to the database!")
    })
    .then(() => {
        console.log("Database successfully connected!")
    });

// Listen
app.listen(process.env.PORT, (error) => {
    if (error) throw error;
});
`

The error I get is this one: 
`
{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: application/x-www-form-urlencoded"}
`

**Comment by mcollina** [comment]
I'd recommend you opening a new issue on fastify-formbody with an example we can run. Thanks!

**Comment by korobaka** [comment]
> I'd recommend you opening a new issue on fastify-formbody with an example we can run. Thanks!

Okay, gonna do this
