### ISSUE TITLE
FST_ERR_SCH_NOT_PRESENT when using string enum containing '#'

### ISSUE THREAD

**Issue by lappalj4** [fastify/fastify#2021]
#1301  🐛 Bug Report
The fastify.addSchema method throws an `FST_ERR_SCH_NOT_PRESENT` error when trying to add a schema where one of the `enum` values contains a `#`.
 
## To Reproduce

Attempt to add a schema containing an  `enum` field where one of the values contains a hashtag character, such as the following example with programming languages:

Paste your code here:

```js
fastify.addSchema({
  $id: '/ProgrammingLanguage',
  description: 'Programming Language',
  type: 'string',
  enum: ['Javascript', 'C++', 'C#']
});

->  FST_ERR_SCH_NOT_PRESENT: Schema with id 'C' does not exist!
```

## Expected behavior

This is somewhere in between a feature request and a bug report. Technically this is the expected result, if I haven't added a schema with the id `C`, but I would at least characterize it as somewhat unexpected behaviour. I'm not deeply familiar with the JSON Schema specification, but should I be allowed to use a `#` reference within a `enum` field of type `string` in the first place?

If yes, I think there should be an option to tell fastify to ignore references within a given schema and treat all values as plain strings. Looking at the documentation I couldn't find a way to do this.

## Your Environment

- *node version*: 12.3.1
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by Eomm** [comment]
You are triggering an unwanted ["replace way"](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#adding-a-shared-schema) schema behaviour.

Right now I'm not sure there is the possibility to understand if you are tring to replace or use the strict value without another param

**Comment by mcollina** [comment]
I feel we should not try to replace # inside enums.

**Comment by jsumners** [comment]
> You are triggering an unwanted "replace way" schema behaviour.

I don't think this feature should exist. It breaks the JSON Schema specification. References should be listed under `$ref` keywords. They should be "found" within `enum` values.

I propose eliminating this feature completely and requiring the user to supply their own AJV instance if they need references.

**Comment by lappalj4** [comment]
@jsumners agreed, I think this feature is rather dangerous as it can trigger the replace in some quite unexpected situations. I'll say it took me a pretty good while to figure out where this error is originating from. 

Seeing as the "Fastify way" seems to generally be to move everything one might consider an extra feature into a separate plugin, I feel this feature would also be better served as one of the [core plugins](https://www.fastify.io/ecosystem/).
