### ISSUE TITLE
I cant use one schema for two different routes

### ISSUE THREAD

**Issue by mohammad-khooie** [fastify/fastify#2024]
🐛 Bug Report

when I want too set my schema to different routs I get this error 
FastifyError [FST_ERR_SCH_DUPLICATE]: FST_ERR_SCH_DUPLICATE: Schema with 'querystring' already present!

## To Reproduce

create a schema with query and add it to different routes
```js
  this is my schema
 "sportSite_sportSiteSessionForGetAllSchema": {
        "params": {
            "type": "object",
            "required": [ "sportSiteUUID" ],
            "properties": {
                "sportSiteUUID": { "type": "string", "format": "uuid" }
            }
        },
        "query": {
            "type": "object",
            "properties": {
                "pageSize": { "type": "integer", "maximum": sportSiteWorkPlanMaxPage },
                "pageNumber": { "type": "integer" }
            }
        }
    }
 and my routes
 fastify.get( "/:sportSiteUUID/sessions/userType/customer", {
        "schema": sportSite_sportSiteSessionForGetAllSchema
    }, httpHandlers.getAllSportSiteSessionsForSportSiteForCustomerHandler );

    fastify.get( "/:sportSiteUUID/sessions/userType/provider", {
        "schema": sportSite_sportSiteSessionForGetAllSchema,
        "preHandler": [
            fastify.authenticate( fastify.tokenUtil ),
            fastify.authorizeByRoles( [ "provider" ] ),
            fastify.authorizeResource( fastify, ( req ) => req.params.sportSiteUUID )
        ]
    }, httpHandlers.getAllSportSiteSessionsForSportSiteForProviderHandler );
```
- *node version*: 13.5
- *fastify version*: >=2.11.0
- *os*: Windows

**Comment by mcollina** [comment]
Would you mind to upload a snippet that can be run to show this problem?

**Comment by adrai** [comment]
Did you also try with addSchema and referencing the schema only?

https://www.fastify.io/docs/latest/Server/#addschema

example: https://www.fastify.io/docs/latest/Validation-and-Serialization/#adding-a-shared-schema

**Comment by mohammad-khooie** [comment]
> Would you mind to upload a snippet that can be run to show this problem?
```js
var fastify = require("fastify")();
var schema = {
    "params": {
        "type": "object",
        "required": [ "id" ],
        "properties": {
            "id": { "type": "string", "format": "uuid" }
        }
    },
    "query": {
        "type": "object",
        "properties": {
            "pageSize": { "type": "integer", "maximum": 5 },
            "pageNumber": { "type": "integer" }
        }
    }
}
var testApi = async(fastify, opts)=>{
    fastify.post( "/test1/:id",
        {
            "schema": schema
        }, async(req, reply)=>{ reply.status( 200 ).send( "test1" );} );

    fastify.post( "/test2/:id",
        {
            "schema": schema
        }, async(req, reply)=>{ reply.status( 201 ).send( "test2" );} );
}
fastify.register( testApi, { "prefix": "/api" } );
fastify.listen( 8000, ( err, address ) => {
    if ( err ) {
        console.log( err );
    }
    fastify.log.info( `server listening on ${address}` );
} );

```

**Comment by mohammad-khooie** [comment]
> Did you also try with addSchema and referencing the schema only?
> 
> https://www.fastify.io/docs/latest/Server/#addschema
> 
> example: https://www.fastify.io/docs/latest/Validation-and-Serialization/#adding-a-shared-schema

no I did not

**Comment by Eomm** [comment]
Right now I can't dig deeper, but this workaround will work for you:

```js
  fastify.post('/test1/:id',
    {
      schema: { ...schema }
    }, async (req, reply) => { reply.status(200).send('test1') })
```

I think the `addSchema` would not solve the problem because you need to use the same schema configuration in two routes, you are not sharing a complex JSON schema object in 2 different JSON schemas.

**Comment by snacqs** [comment]
Hey @Eomm!
I took a look at this issue. It happens [here](https://github.com/fastify/fastify/blob/master/lib/schemas.js#L52) because fastify mutates the original route schema.
Probably we should use [`cachedSchema`](https://github.com/fastify/fastify/blob/master/lib/schemas.js#L63) instead of `routeSchema` everywhere in this function.
It should be an easy fix and I'd like to create a PR for it. Let me know if there are some pitfalls that I should look into 🙂

**Comment by Eomm** [comment]
I don't understand what you mean by using the cachedschema

I think if you have understood the problem, feel free to give it a shot! 💪🏻
The only advice would be to write a failing test before any change of the code

**Comment by moeinrahimi** [comment]
I had this issue on 2.11.0, updating to higher version solved it.
