### ISSUE TITLE
Deploy fastify app on AWS 

### ISSUE THREAD

**Issue by Giacomo92** [fastify/fastify#2027]
I am trying to deploy my fastify app on AWS. I cannot understand how can I wrap my application on the init function. I have defined my routes in a single file and then I have instanced them in the app.js. The deploy finish with no error, no error also on Cloud Watch but I get this error on browser
![Screenshot_20200106_215606](https://user-images.githubusercontent.com/11694429/71848295-66d7be80-30cf-11ea-9e8d-2125e72ae81b.jpg)

See this [repo](https://github.com/Giacomo92/fastify-api)  for the template app I am trying to integrate with Serverless feature.
[Index.js](https://gist.github.com/Giacomo92/0ab6436e534e53786b3e7b91548d28df) the main file of the app. The docs called it app.js
[lambda.js](https://gist.github.com/Giacomo92/7893d6083fd4e0516359c54d5e0ca557)

![Schermata 2020-01-07 alle 15 05 00](https://user-images.githubusercontent.com/11694429/71902615-bc10e000-3162-11ea-94d9-fca0d8795d56.png)

Thank you for the support

**Comment by StarpTech** [comment]
Hi @Giacomo92, this issue is really hard to understand. What do you mean with init function? Please post the full logs with stack traces. That message can mean everything.

**Comment by Giacomo92** [comment]
I have followed the fastify docs [here](https://github.com/fastify/fastify/blob/master/docs/Serverless.md#aws-lambda), but my application has different configuration. I have not defined all the route in the main file.

**Comment by Giacomo92** [comment]
Hi @StarpTech, 
I have added a screen of a full log and I have created two gists with the files I have updated from the teomplate repo with my integration tests. 

I hope everything is clearer now.

**Comment by mcollina** [comment]
You need to instantiate your fastify app inside the `init` function.

**Comment by StarpTech** [comment]
According to https://github.com/fastify/aws-lambda-fastify

you have to change the line to 

```js
else {
  // required as a module => executed on aws lambda
  module.exports = init;
}
```

to 

```js
else {
  // required as a module => executed on aws lambda
  module.exports = init();
}
```

**Comment by Giacomo92** [comment]
I have moved all code in the init function as @mcollina said.
I have changed `init` with `init()` as @StarpTech said.

I got Internal Server error with this log:

![Schermata 2020-01-07 alle 15 58 49](https://user-images.githubusercontent.com/11694429/71904992-84586700-3167-11ea-9f18-c1ac3245f8b8.png)

**Comment by StarpTech** [comment]
Mongodb connection issue? Does it work without Mongodb? Try to return a simple string and see if it works.

**Comment by Giacomo92** [comment]
I have removed all Mongodb and swagger line. Now I got Forbidden:
<img width="224" alt="Schermata 2020-01-08 alle 01 17 13" src="https://user-images.githubusercontent.com/11694429/71939947-b348fa00-31b4-11ea-89ad-310183d66618.png">
I can't understand what I'm doing wrong.
In my local environment it's always working even in the first versione of the gist.
If try to use the same code of [docs](https://github.com/fastify/fastify/blob/master/docs/Serverless.md#aws-lambda) without any additional configuration on AWS it's all working and I can see the "Hello World" message.
So I guess the error must be in the else condition
```
else {
  // required as a module => executed on aws lambda
  module.exports = init();
}
```

or in the lambda.js file.

**Comment by Giacomo92** [comment]
I think Mongodb goes on timeout. I have find this log:
<img width="1016" alt="Schermata 2020-01-08 alle 01 32 04" src="https://user-images.githubusercontent.com/11694429/71940516-e3919800-31b6-11ea-95ff-15247dd55b05.png">
I cannot understand why I am getting this error. In my local environment it's working without any problem
I 'll try to change Mongodb server.

**Comment by StarpTech** [comment]
Yes, it's a connection issue with mongodb. I will close this issue since it is no longer related to fastify.
