### ISSUE TITLE
Request serializer throws "TypeError: Cannot read property 'remotePort' of undefined"

### ISSUE THREAD

**Issue by jcaowml** [fastify/fastify#2028]
## To Reproduce

Paste your code here:

```js
// Require the framework and instantiate it
const fastify = require('fastify')({ logger: true })

// Declare a route
fastify.get('/', async (request, reply) => {
  try {
    request.log.info({ req: request });  // <-- Problem here
    } catch (error) {
    console.error(error);
    }
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
    await fastify.inject('/')
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

## Expected behavior

Should log the request object, serialized

I have a demo of this at: https://runkit.com/jcwml/runkit-npm-fastify

![image](https://user-images.githubusercontent.com/58958183/71855749-c796d500-3096-11ea-8a3c-f6670161fa6f.png)

**Comment by mcollina** [comment]
`req` has a default serializer for node core http request (this will change in Fastify v3)

**Comment by jcaowml** [comment]
I see. Thanks!

**Comment by mcollina** [comment]
You should use a different key for that object. You might want to specify a specific serializer.

Note that the request details are already included in the line.
