### ISSUE TITLE
Add generic parameter for Reply send method

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2030]
Based on a discussion in https://github.com/fastify/help/issues/125 a good feature for the type system (current and future) would be to add a generic parameter to the `reply.send` method to allow the user to specify the payload type being passed in. It is currently set to `any` see [v2](https://github.com/fastify/fastify/blob/master/fastify.d.ts#L180) and [v3](https://github.com/fastifyf/fastify/blob/next/types/reply.d.ts#L22). 

This is not a breaking feature to the type system so it should not block the v3 release.

**Comment by mcollina** [comment]
it seems a good idea!
Il 7 gen 2020, 22:19 +0100, Ethan Arrowood <notifications@github.com>, ha scritto:

**Comment by Ethan-Arrowood** [comment]
Reopening. v3 fix still needed

**Comment by Ethan-Arrowood** [comment]
Closed by #2032 and #2034
