### ISSUE TITLE
fastify.close not working with tap

### ISSUE THREAD

**Issue by balaphp** [fastify/fastify#2037]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## To Reproduce

Paste your code here:

```js
// Please make sure that this code can run on its own.
```

## Expected behavior

Paste the results here:

```js

```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
Please report into the help repo and _fill in the template_.

**Comment by gustawdaniel** [comment]
But I expected this error, not only for tap but other test frameworks.

It is connected with `bull-fastify` plugin. 

Different plugins that have open connections can be the reason for this. I would like to see any docs about debugging this topic.
