### ISSUE TITLE
Tap test case timeout error

### ISSUE THREAD

**Issue by balaphp** [fastify/fastify#2038]
## 🐛 Bug Report

```
npm test

 FAIL  test/sample.test.js
 ✖ timeout!

  test: TAP
  signal: SIGTERM
  handles:
    - type: Server
      events:
        - request
        - connection
        - clientError
      connectionKey: 4:127.0.0.1:3000
  expired: TAP
  stack: |
    emit (node_modules/signal-exit/index.js:77:11)
    process.listener (node_modules/signal-exit/index.js:91:7)

 FAIL  test/sample.test.js 1 failed of 6 28s
 ✖ timeout!

```

This test case not finishing and it says timeout error

## To Reproduce

app.js

```
const Fastify = require('fastify')

function buildFastify () {
  const fastify = Fastify()

  fastify.get('/', function (request, reply) {
    reply.send({ hello: 'world' })
  })
  fastify.lesten(3000)
  return fastify
}

module.exports = buildFastify
```
**test.js**

```
const tap = require('tap')
const buildFastify = require('./app')

tap.test('GET `/` route', t => {
  t.plan(4)

  const fastify = buildFastify()

  // At the end of your tests it is highly recommended to call `.close()`
  // to ensure that all connections to external services get closed.
  t.tearDown(() => fastify.close())

  fastify.inject({
    method: 'GET',
    url: '/'
  }, (err, response) => {
    t.error(err)
    t.strictEqual(response.statusCode, 200)
    t.strictEqual(response.headers['content-type'], 'application/json; charset=utf-8')
    t.deepEqual(JSON.parse(response.payload), { hello: 'world' })
  })
})
```
// run `npm test`

## Current behavior
This program should quit and test result must be shown. 

```
Paste the results here:
 FAIL  admin/auth/auth.test.js
 ✖ timeout!

  test: TAP
  signal: SIGTERM
  handles:
    - type: Server
      events:
        - request
        - connection
        - clientError
      connectionKey: 4:127.0.0.1:3000
  expired: TAP
  stack: |
    emit (node_modules/signal-exit/index.js:77:11)
    process.listener (node_modules/signal-exit/index.js:91:7)

 FAIL  admin/auth/auth.test.js 1 failed of 6 28s
 ✖ timeout!
```

## Expected Behavior
```
Suites:   0 of 1 completed
Asserts:  4 passed, of 4
Time:     8s
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 appt.js  |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

## Your Environment

- *node version*: v12.13.0
- *fastify version*: 2.11.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
This example does not run on its own.

**Comment by balaphp** [comment]
> This example does not run on its own.

I have updated. Basically i used the sample program from test page documentation.
All i added is just listen function.

**Comment by balaphp** [comment]
This could be the issue from tap.end() is not working but when i call 
fastify.close() it should shutdown the process and quit.

**Comment by mcollina** [comment]
Try calling await fastify.listen(3000). There might be a race between listen and close.

**Comment by balaphp** [comment]
No luck, only the fastify.shutdown i mentioned is only helping.

**Comment by Eomm** [comment]
> There might be a race between listen and close.

I agree

Try this working solution:

```
const Fastify = require('fastify')

async function buildFastify () {
  const fastify = Fastify()

  fastify.get('/', function (request, reply) {
    reply.send({ hello: 'world' })
  })
  await fastify.listen(3000)
  return fastify
}

module.exports = buildFastify

//++++++++++++++++++++++++++++++++++++++++++++

const tap = require('tap')
const buildFastify = require('./app')

tap.test('GET `/` route', async t => {
  t.plan(3)

  const fastify = await buildFastify()
  t.tearDown(() => fastify.close())

  const response = await fastify.inject({
    method: 'GET',
    url: '/'
  })
  t.strictEqual(response.statusCode, 200)
  t.strictEqual(response.headers['content-type'], 'application/json; charset=utf-8')
  t.deepEqual(JSON.parse(response.payload), { hello: 'world' })
})
```

**Comment by delvedor** [comment]
You should either `await fastify.listen` or use a callback. It's very likely that `.listen` and `.close` cause a race condition. 

Pro tip: if you are using `.inject`, there is no need to listen. ([docs](https://www.fastify.io/docs/latest/Testing/#testing-with-http-injection))

**Comment by balaphp** [comment]
This sample code is working fine,
 but if i added db connection mongo then its not working.

**Comment by mcollina** [comment]
are you using fastify-mongodb?

**Comment by Eomm** [comment]
> but if i added db connection mongo then its not working.

You need to call `fastify.close()` otherwise, the connection will persist and the process will not end.. and the test will go in timeout

**Comment by balaphp** [comment]
It worked but another issue (my be its my mistake). 
It didnt work when I used both fastify-mysql and fastify-mongodb 
if i remove either one its working.  sorry to trouble you guys.

**Comment by Eomm** [comment]
> It didnt work when I used both fastify-mysql and fastify-mongodb

Now, it is difficult to understand the problem. If the error is the same (timeout error) it could be a pending connection still alive: you need to be aware of all the things that keep a node process alive (like timers, connections, other IO)
You could use [this module](https://github.com/mafintosh/why-is-node-running) to find it

> sorry to trouble you guys.

It is a pleasure to help 👍

**Comment by gustawdaniel** [comment]
```
  fastify.lesten(3000)
```

??

Rather `listen`.
