### ISSUE TITLE
v3 type def clarification for `addHook` method

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2040]
I've been fixing the `hooks.d.ts` part of the new types and I've hit a very difficult snag. We have two hooks `onSend` and `preSerialization` that pass through the `payload` argument to the hook handler. For best type safety, we should allow the user to specify what this is via a generic parameter. But because all of the other hook handlers do not require this generic parameter I cannot just add it to `addHook`. 

What I can do is specify the generic parameter from the specific hook handler definition; and then allow the user to pass this through to the `addHook` function. This requires the user to specify the `onSend` and `preSerialization` hooks like so:

```typescript
type TestPayloadType = {
  foo: string,
  bar: number
}

// equivalent for `onSend`
const preSerializationHook: preSerializationHookHandler<TestPayloadType> = (request, reply, payload, done) => {
  // you can ignore this code its just apart of the unit tests
  expectType<FastifyRequest>(request)
  expectType<FastifyReply>(reply)
  expectType<TestPayloadType>(payload)
  expectType<(err: FastifyError) => void>(done(new Error()))
  expectType<(err: null, res: string) => void>(done(null, 'foobar'))
  expectError(done())
}

server.addHook('preSerialization', preSerializationHook)
```

There does not seem to be a way to pass that generic in line:

```typescript
// THIS CODE IS INVALID
type TestPayloadType = {
  foo: string,
  bar: number
}

// Where would `<TestPayloadType>` go? 
server.addHook('preSerialization', (request, reply, payload, done) => {
  // ...
})
```

Also, please note that **for all other hooks** the normal way of specifying them will work:
```typescript
server.addHook('onRequest', (request, reply, done) => {
  expectType<FastifyRequest>(request)
  expectType<FastifyReply>(reply)
  expectType<(err?: FastifyError) => void>(done)
})
```

---

I've attempted to write a definition that supports passing the payload generic to the `addHook` method but could not figure it out (i believe it might be impossible). So with all of this considered, **is the previously mention specification okay?** Of course, this will be detailed in the TypeScript documentation with code examples -- and I'll include a special note in the type definition comments (editors bubble these up to the user so they can get more info without leaving the editor). 

Lastly, i'm going to make a gist with all of my type def attempts as a reference -- [will add that here when its ready.](https://gist.github.com/Ethan-Arrowood/c0294ae9533a8b1908cf9c1a0e0208c0) <-- check it out. i'll be adding to it with other attempts as I go

**Comment by corbinu** [comment]
@Ethan-Arrowood could we maybe add something to the types that casts server.addHook itself to take the generic?

**Comment by Ethan-Arrowood** [comment]
My current closest attempt is something like that.

```typescript
type addHook<
  Payload = unknown, // default to unknown
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  Logger = FastifyLoggerOptions<RawServer>
> = Payload extends unknown ? ( // check if the generic is specified or not
  <Name extends FastifyHooksStrings>(
    name: Name,
    hook: addHookHandler<Name, RawServer, RawRequest, RawReply, Logger>
  ) => FastifyInstance<RawServer, RawRequest, RawReply>
) : ( // this second option is only for the `onSend` and `preSerialization` hooks
  <Name extends FastifyHooksStrings>(
    name: Name,
    hook: addHookHandlerWithPayload<Payload, Name, RawServer, RawRequest, RawReply, Logger>
  ) => FastifyInstance<RawServer, RawRequest, RawReply>
)
```
But not only is this sorta just broken (not entirely sure why), but if it did work this would prohibit the user from setting those hooks without a generic, and ideally they should be able to do so without specifying it when they don't want to

**Comment by Ethan-Arrowood** [comment]
I want to highlight [attempt 3 in the gist](https://gist.github.com/Ethan-Arrowood/c0294ae9533a8b1908cf9c1a0e0208c0#attempt-3). I will continue to formulate my thoughts around this whole thing and comment back with more updates/maybe even a blog post later.

**Comment by corbinu** [comment]
Well was worth a shot. I think the workaround you have it for now is fine.
