### ISSUE TITLE
Query string validation is not working anymore (Hello World from docs)

### ISSUE THREAD

**Issue by stromcon** [fastify/fastify#2046]
## 🐛 Bug Report

Hello, I took the "Request/Response validation and hooks" from https://www.fastify.io/ and put this in a file, only removed "response" key from "schema", my server contains this :

```javascript
const fastify = require('fastify')({ logger: true })

fastify.route({
  method: 'GET',
  url: '/',
  schema: {
    // request needs to have a querystring with a `name` parameter
    querystring: {
      name: { type: 'string' }
    },
  },
  // this function is executed for every request before the handler is executed
  beforeHandler: async (request, reply) => {
    // E.g. check authentication
  },
  handler: async (request, reply) => {
    return { hello: 'world' }
  }
})

const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

## To Reproduce

Run my script `node server.js`

## Expected behavior

I would expect a 400 because query string is not valid when launching http://127.0.0.1:3000 but server returns payload and status 200

Paste the results here:

Server response is `{hello: 'world'}`, schema is not used

## Your Environment

- *node version*: 12.14.1 (latest LTS)
- *fastify version*:  2.11.0
- *os*: Windows

**Comment by Eomm** [comment]
The 'required' keyword is missing, for this reason the validation is working 👍🏼

**Comment by stromcon** [comment]
Sorry for bad ticket and thanks for reply.
