### ISSUE TITLE
static js files to gzip

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#2051]
Hello, i try use webpack comression, output gzip files.

link rel="preload" href="/dist/4.52e140b28097204e4353.chunk.js" as="script"

js files work, gzip not

image
https://ibb.co/3c45HQM
Webpack created two variants file, js and compressed
sometimes size 1/3 from original, greate time economy

i think this is it
1
"The NginxHttpGzipStaticModule is enabled by adding gzip_static on; to the nginx.conf"
2
https://www.npmjs.com/package/express-static-gzip
3
https://github.com/koajs/static

This is server support? Not client? 

how i can enable this?

**Comment by mcollina** [comment]
I don't understand what you are trying to achieve and what is the problem.

If I understand correctly, using https://github.com/fastify/fastify-static should solve your problem.

**Comment by borodadada** [comment]
sorry, i try understand how use webpack-compress, buy i think no need, fastify static can use compress

this is example and he work
```
fastify.register(require('fastify-compress'), { threshold: 0 })
fastify.register( require('fastify-favicon'), { path: path.join(__dirname, 'public') } );
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'dist'), prefix: '/dist/', decorateReply: false } )
```
Can i compress only - dist ?  row number 3.

**Comment by mcollina** [comment]
compression is enable automatically with fastify-static if the browser supports it, you do no have to do anything.
