### ISSUE TITLE
How to use fastify + nestjs + firebase functions

### ISSUE THREAD

**Issue by RezaRahmati** [fastify/fastify#2053]
I am using NestJS and Cloud Functions, because of performance I want to switch to Fastify.

But I have no idea what to pass to `functions.https.onRequest(???)`

My old code for express is:

```
admin.initializeApp(functions.config().firebase);

const server: express.Express = express();

const startNestApplication = async (expressInstance: express.Express) => {
  const adapter = new ExpressAdapter(expressInstance);
  const app = await NestFactory.create(AppModule, adapter, {});
  app.enableCors();
  await app.init();
  return app;
};

const main = startNestApplication(server);

export const api = functions.https.onRequest(server);

```

And new code is:

```
admin.initializeApp(functions.config().firebase);

const startNestApplication = async () => {
  const adapter = new FastifyAdapter();
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, adapter, {});
  app.enableCors();
  await app.init();
  return app;
};

const main = startNestApplication();

export const api = functions.https.onRequest(???);

```

https://docs.nestjs.com/techniques/performance

**Comment by delvedor** [comment]
Hello! We can't answer Nest.js related questions because we are not connected to the project in any way. You should directly ask this kind of question in the Nest.js repository :)

**Comment by wenesay** [comment]
Hi Below is my code for NestJS + Fastify + Firebase Functions. The issue with my code is that Headers are not received from client to fastify handler.


<pre>
...

import { Logger, NestApplicationOptions, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
// import * as compression from 'compression';
import { AppModule } from './app/app.module';
import Fastify from 'fastify';
import * as http from 'http';
import * as functions from 'firebase-functions';
import fastifyMultipart from 'fastify-multipart';
import * as bodyParser from 'body-parser';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import * as CORS from 'cors';


...
let handleRequest = null

const serverFactory = (handler, opts) => {
  handleRequest = handler
  return http.createServer()
}

const fastify = Fastify({
  serverFactory,
  trustProxy: true
});
fastify.register(fastifyMultipart)
fastify.addContentTypeParser('application/json', { parseAs: 'string' }, function (req, body, done) {
  try {
    console.log('parser:', body);
    const json = JSON.parse(body.toString())
    done(null, json)
  } catch (err) {
    err.statusCode = 400
    done(err, undefined)
  }
})

export const createNestServer = async (fastifyInstance) => {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(fastifyInstance)
  );
  const globalPrefix = 'v1';
  app.setGlobalPrefix(globalPrefix);
  const bodyParserLimit = '50mb'
  // configure app to use bodyParser()
  app.use(bodyParser.json({ limit: bodyParserLimit }))
  app.use(bodyParser.urlencoded({ limit: bodyParserLimit, extended: true }))
  app.use(
    bodyParser.raw({
      limit: bodyParserLimit,
    })
  )

  app.useStaticAssets({
    root: join(__dirname, 'assets', 'public'),
    prefix: '/public/',
  });

  app.setViewEngine({
    engine: {
      handlebars: require('handlebars'),
    },
    templates: join(__dirname, 'assets', 'views'),
  });

  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      whitelist: true
    }),
  );

  return app.init();
}

createNestServer(fastify)
  .then(v => {
    console.log('Nest Ready');
  })
  .catch(err => console.error('Nest broken', err));

const cors = CORS({ origin: true });

export const api = functions.https.onRequest(async (req, res) => {
    cors(req, res, () => {
      // req = Object.assign({ ip: '' }, { ...req }); <== need to enable this , 'cos sometimes req.ip gives error

      if (!fastify.hasContentTypeParser('application/json')) {
        console.log('Not Added: ContentTypeParser'); // This is not printed so it is added
      }
      fastify.ready((err) => {
        if (err) throw err;
          handleRequest(req, res)
        } else {
          res.status(400).send('You shall not pass!!!');
          return;
        }
      })
    });
  });
</pre>

Hope this helps.

Thanks
GN
