### ISSUE TITLE
Log a warning if both promises/async and callbacks are used at the same time

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2055]
## 🚀 Feature Proposal

In https://github.com/fastify/help/issues/133#issuecomment-578073158, it's shown that developers have some issues in grasping the use of async/await and callbacks. I think we should protect them by:

* [ ] I propose to add a `log.warn()` in https://github.com/fastify/fastify/blob/d0c976e82549488ecd27c17421cd3b51264468de/lib/hooks.js#L61 to tell the user if the number of callbacks and promise resolved are higher than the number of hooks.

* [ ] We should also skip https://github.com/fastify/fastify/blob/d0c976e82549488ecd27c17421cd3b51264468de/lib/hooks.js#L66 if `cb` was already called.

**Comment by jsumners** [comment]
Sounds good to me.

**Comment by delvedor** [comment]
I fear I'm missing something, didn't we already address this issue?
In v2 we are logging a warning in case of a hook declared async and with a callback:
https://github.com/fastify/fastify/blob/d0c976e82549488ecd27c17421cd3b51264468de/fastify.js#L369-L381
while in v3 we will throw an error:
https://github.com/fastify/fastify/blob/9dc0207f5df95ff7fbb652f1934127ca7fbf3971/fastify.js#L346-L357

Furthermore, the problem with the logs, is that very unlikely users will ignore them, reason why in v3 we are throwing an error.

**Comment by mcollina** [comment]
Ooh, I totally forgot we already have that done

**Comment by aimansaeedsh** [comment]
Ok, so this is checked if the fastify's "addHook" function is used directly. But is this warning/error also shown when a custom hook is passed in for instance as a "preHandler" at route declaration ?

i.e.
```
const opts = {
  ...,
  prehandler: [someHandlerThatUsesDoneAndAsyncAwait]
}
fastify.post('/purchase', opts, async (request, reply) => {
...
})
```

**Comment by aimansaeedsh** [comment]
we experienced unusual behavior (seemingly identical multiple requests) due to the above. Please to hear your thoughts on this. @mcollina
