### ISSUE TITLE
Set server.timeout to a default value

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2058]
## 🚀 Feature Proposal

We currently do not set [`server.timeout`](https://nodejs.org/api/http.html#http_server_timeout) to any value, and the default is `0`.
I propose to set this value to 60s (or more), in this way hanging http requests will be closed automatically.

## Example

```js
const app = Fastify({
  connectionTimeout: 12000 // 2 seconds
})
```

**Comment by jsumners** [comment]
Sounds good to me.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/2086.
