### ISSUE TITLE
Can't handle HEAD request properly

### ISSUE THREAD

**Issue by tolicodes** [fastify/fastify#2061]
#1301  🐛 Bug Report

When I try to send a `HEAD` request for `sendFile` I get the following error:

```js
app.head(filePath, { logLevel: LOG_LEVEL }, async (request, reply) => {
    console.log('head');
    try {
      const { '*': uriPath } = request.params;
      const isFile = !!uriPath.match(/\.[a-zA-Z0-9]{1,5}(\?.*)?/);
      if (isFile) {
        setCacheControl(reply, FILE_CACHE_CONTROL_MAX_AGE);
        reply.sendFile(uriPath);
      } else {
        const indexPath = 'index.html';
        const indexStr = await fs.readFile(path.join(serveRoot, indexPath), {
          encoding: 'utf-8',
        });
        const indexPayload = await injectEnv(indexStr);
        setCacheControl(reply, INDEX_CACHE_CONTROL_MAX_AGE);
        reply.type('text/html');
        reply.send(indexPayload);
      }
    } catch (e) {
      console.error(e);
    }
  });
```

```
web_1  | {"level":50,"time":1580244056047,"pid":1,"hostname":"3ee631923a16","reqId":5,"err":{"type":"FastifyError","message":"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]: FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /usr/src/server/node_modules/fastify/lib/wrapThenable.js:34:30\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)","name":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","v":1}
```

The way that express handles this is by simply passing through `HEAD` requests to the `GET` method, and then letting `send` (the underlying package that sends responses for both fastify and express) handle it [here](https://github.com/pillarjs/send/blob/ea1748a3b3e00dbcbb0629cf368ced575c6ab7d6/index.js#L710) by not sending the output but sending the headers.

But fastify seems to incorrectly mark this as an error [here](https://github.com/fastify/fastify/blob/0d6055d3e07b726c9bfbc779550adf78dab967f3/lib/wrapThenable.js#L33)

## To Reproduce

```js
app.head(filePath, { logLevel: LOG_LEVEL }, async (request, reply) => {
    console.log('head');
    try {
      const { '*': uriPath } = request.params;
      const isFile = !!uriPath.match(/\.[a-zA-Z0-9]{1,5}(\?.*)?/);
      if (isFile) {
        setCacheControl(reply, FILE_CACHE_CONTROL_MAX_AGE);
        reply.sendFile(uriPath);
      } else {
        const indexPath = 'index.html';
        const indexStr = await fs.readFile(path.join(serveRoot, indexPath), {
          encoding: 'utf-8',
        });
        const indexPayload = await injectEnv(indexStr);
        setCacheControl(reply, INDEX_CACHE_CONTROL_MAX_AGE);
        reply.type('text/html');
        reply.send(indexPayload);
      }
    } catch (e) {
      console.error(e);
    }
  });
```

## Expected behavior

For the HEAD request to properly be handled by `send` and not throw that error

## Your Environment

- *node version*: 10
- *fastify version*: 2.7.1
- *os*: Mac,

**Comment by RafaelGSS** [comment]
It sounds like an implementation bug for me. Can you provide a code example, without business logic?

**Comment by mcollina** [comment]
Note that you should not return the body if it’s a HEAD request.

Then a bunch of quick fixes:

1. remove the try catch and enable the logger on Fastify
2. add a “return reply” at the end of the file if you’d like to mix async/await and send.

**Comment by jsumners** [comment]
Fastify does not provide default handlers for any methods. You should provide a handler for the `HEAD` request that does what you want it to do.

**Comment by tolicodes** [comment]
Here is simplified code. Now it just hangs...

```
import path from 'path';
import fastify from 'fastify';
import staticServe from 'fastify-static';

const app = fastify({
    logger: true,
  });

 app.register(staticServe, {
    root: serveRoot,
    serve: false,
  });

const filePath = `${ROOT_PATH}*`;
  const serveRoot = path.resolve(SERVE_PATH);

  app.register(staticServe, {
    root: serveRoot,
    serve: false,
  });

  const getHandler = (request, reply) => {
    request.log.debug('head');

    try {
      const { '*': uriPath } = request.params;

      return reply.sendFile(uriPath);
    } catch (e) {
      request.log.error(e);
      return e;
    }
  };

app.get(filePath, { logLevel: LOG_LEVEL }, getHandler);

  app.head(filePath, { logLevel: LOG_LEVEL }, getHandler);

  app.listen(Number.parseInt(PORT, 10), '0.0.0.0', (err: Error) => {
    if (err) {
      throw err;
    }
  });
```

**Comment by jsumners** [comment]
You have supplied the same handler to both the `GET` and `HEAD` requests. A `HEAD` request should only return headers -- https://tools.ietf.org/html/rfc2616#section-9.4

**Comment by tolicodes** [comment]
Solved it. I have to return `        return fs.readFile(uriPath);`

**Comment by tolicodes** [comment]
> You have supplied the same handler to both the `GET` and `HEAD` requests. A `HEAD` request should only return headers -- https://tools.ietf.org/html/rfc2616#section-9.4

The way it's handled in express is it passes the body and lets `send` handle that [here](https://github.com/pillarjs/send/blob/ea1748a3b3e00dbcbb0629cf368ced575c6ab7d6/index.js#L710)

**Comment by jsumners** [comment]
PRs for improvements are welcome.
