### ISSUE TITLE
Support synchronous routes

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2065]
## 🚀 Feature Proposal

I propose we call `reply.send()` in synchronous routes if the returned value is not Promise or a Stream.

## Motivation

It seems a lot of newbies to fastify mistake the use of `async`, and we are not providing them a good developer experience.

## Example

```js
'use strict';

module.exports = (server, opts, done) => {

  server.get('/', () => {
    return "Hello World";
  });

  done();
};
```

**Comment by jsumners** [comment]
I have not seen this in our issues, or I just don't remember it. Is this really something a lot of people are doing?

**Comment by mcollina** [comment]
I've seen this on gitter a few times, as well as people playing with the framework.
They don't know that `async` makes the function return a promise.

**Comment by delvedor** [comment]
I fear this solution could result in some edge case that is difficult to predict now.
How about throwing an error in the same way we are doing if the user declares an async hook with the `next` callback in the signature?

I think there are two paths we can follow here:
- the one you have suggested, who translates to being smart and trying to understand what the user wants
- throw an error and try to educate the user about the correct use of the API (and the language).

**Comment by StarpTech** [comment]
> I've seen this on gitter a few times, as well as people playing with the framework.
They don't know that async makes the function return a promise.

I would be very careful with such conclusions as long as they can't be verified. What about a twitter pool or any other survey?

Accepting anything to respond feels handy and comfortable to me. On the other side, this can already be archived with an async function.

In the short term, I agree with @delvedor to produce a better error message. In the long term, we need to check if it's really an intuition thing or just "I have no idea at all what I'm doing here".

**Comment by mcollina** [comment]
I've seen this happening so many times that is pretty clear that newbie JS developers do not understand the critical differences between `async function` and `function`. This issue originates from that request. I'm not going to do a survey because the sample for that survey are going to be totally skewed.

I'm happy to make Fastify return a 500 and an error in that case. Practically, we should change these three lines: https://github.com/fastify/fastify/blob/7fa4bddca07aac18e0600cff40d97b95a96ab970/lib/handleRequest.js#L112-L114.
Making it return would change that block to:

```js
  var result = reply.context.handler(request, reply)
  if (result) {
    if (typeof result.then === 'function') {
      wrapThenable(result, reply)
    } else {
      reply.send(new Error('return a promise or use an async function in the route handler'))
      // or reply.send(result)
    }
  }
```

I think this change should be part of v3.

**Comment by Eomm** [comment]
The `setErrorHandler` will benefit from this feature because it will always be executed regardless it is a sync or async function, it is more homogeneous

**Comment by Eomm** [comment]
Released in v3
