### ISSUE TITLE
Organize docs i18n

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#2068]
Hello all!

I think that we need something to sync updates at original docs to translated docs

How we can generate a debit to translated docs after a merge?

**Comment by jsumners** [comment]
😬

🤷‍♂

**Comment by Eomm** [comment]
Maybe a github action that opens an issue to some "translator" repo when a merge is done and some changes are done in `docs/` dir?

**Comment by RafaelGSS** [comment]
Hey guys, only 3 documents are missing to be translated. I will follow the doc tags here, but If I forget some issue, do you can create on `docs-portuguese` please?

However, I did a little search around the Github Actions available and maybe this https://github.com/JasonEtco/create-an-issue/issues/40 can solve our problems :smile:
