### ISSUE TITLE
Reply Header Example in Docs: Response without Double Quoted

### ISSUE THREAD

**Issue by andreyunugro** [fastify/fastify#207]
Hi,
Maybe this example in the docs will help other noobs like me. :)

There is a note in [Reply Header](http://www.fastify.io/docs/v0.27.x/Reply/#header) documentation:
_Note that if you are using a custom serializer that does not serialize to JSON, you must set a custom 'Content-Type' header._

It is better if the documentation include an additional example to that note.
For example this simple code:

`reply.send('OK');`
will output 

> "OK"

Double quoted because by default fastify will do JSON serialization, while
`reply.header('Content-Type', 'text/html').send('OK');`
or using shortcut
`reply.type('text/html').send('OK');`
will output

> OK

without the double quote.

Hope this helps.
Thanks.

**Comment by mcollina** [comment]
Thanks for opening the issue @andreyunugro! Would you like to send a PR?

**Comment by jsumners** [comment]
The content type documentation is more explicit -- https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md

**Comment by andreyunugro** [comment]
Hi @jsumners 
The thing that I want is: fastify gives response as plain string without default JSON serialization and without other parser just for this 1 route api endpoint resource.
I am having doubt now, which is the correct way without sacrifice the speed. :)

Let me read the whole documenation again.
Thanks.

**Comment by andreyunugro** [comment]
Hi @jsumners,

I have read the document and try to code. :D
`addContentTypeParser` API does not automatically set header Content-Type for Reply.

Sample:
```
// Require fs.
const fs = require('fs');
// Require pino.
const logger = require('pino')(fs.createWriteStream('log/fastify.log'));
// Require fastify.
const fastify = require('fastify')();

fastify.addContentTypeParser('text/plain', (req, done) => {
  logger.info(req);
  done('TEST');
});

fastify.post('/post', (request, reply) => {
  logger.info(request);
  reply.send('OK');
});

// Run the server!
fastify.listen(3210, (err) => {
  if (err) throw err;
  logger.info(`server listening on ${fastify.server.address().port}`);
});
```
If there is a post request with header Content-Type text/plain to /post, the Reply output still default to JSON string (with double quote), not automatically change to text/plain.

Note: When I play around with addContentTypeParser, the variable req has no body in it. I wonder how the parser callback able to parse request body.

The quick way to give string without double quote as Reply is still using type or set header Content-Type.
:)

Thanks.

**Comment by jsumners** [comment]
@andreyunugro does #540 solve this problem?

**Comment by allevo** [comment]
Close for inactivity. Please reopen it if you need it!
