### ISSUE TITLE
Promise rejection without error

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#2070]
## 🐛 Bug Report

If an async hook returns a `Promise.reject()` the flow continue.
This usage of promise should be avoided at all, let me know if you think this is an `invalid` bug.

Here we should check the `err` param
https://github.com/fastify/fastify/blob/7fa4bddca07aac18e0600cff40d97b95a96ab970/lib/hooks.js#L80-L82

## To Reproduce

```js
const fastify = require('./fastify')({ logger: true })
fastify.addHook('onRequest', function (request, reply) {
  return Promise.reject()
})
fastify.get('/', async (request, reply) => { return 'hi' })
fastify.listen(3001)
```

## Expected behavior

The rejection should be managed.

_Originally posted by @Eomm in https://github.com/fastify/help/issues/135#issuecomment-580913741_

**Comment by mcollina** [comment]
This is totally valid.
Il 31 gen 2020, 22:19 +0100, Manuel Spigolon <notifications@github.com>, ha scritto:

**Comment by Ravit436** [comment]
I would like to give it a try

**Comment by mcollina** [comment]
awesome!
Il 2 feb 2020, 11:47 +0100, Raviteja <notifications@github.com>, ha scritto:

**Comment by Ravit436** [comment]
Can you go through my PR #2074 
I have resolved the issue @Eomm @mcollina
