### ISSUE TITLE
Use symbol to denote early termination of request

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2075]
## 🚀 Feature Proposal

Introduce `Symbol.for('fastify.end-request')` to terminate requests prior to reaching the defined request handler. When this symbol is received from a hook, or any function in the request life _prior_ to the defined request handler, Fastify should issue a `res.send()` that sends any headers and content currently attached to `res` to the requesting client.

This should also take the place of returning `undefined` to signal the same thing. Thus, when `undefined` is received from such a function, a deprecation notice/error/warning should be logged.

## Motivation

As highlighted in https://github.com/fastify/fastify/issues/2070 and https://github.com/fastify/help/issues/135 , it is unclear how one should terminate a request response before reaching the handler.

## Example

```js
fastify.addHook('onRequest', () => {
  // do something
  return Symbol.for('fastify.end-request')
})

// or

fastify.addHook('onRequest', (req, res, next) => {
  // do something
  next(null, Symbol.for('fastify.end-request'))
})

// or

fastify.addHook('onRequest', async (req, res) => {
  // do something
  return Symbol.for('fastify.end-request')
})
```

**Comment by Eomm** [comment]
Could be a `reply.terminate()` or `reply.interrupt()` more clear?

**Comment by jsumners** [comment]
When that object is present in the handler, sure. But see #2073.

**Comment by mcollina** [comment]
Why is this more than return reply? It was added exact for that reason.

**Comment by jsumners** [comment]
The most documentation I can find on this is https://www.fastify.io/docs/latest/Hooks/#respond-to-a-request-from-a-hook

🤷‍♂ just an idea to clear up ambiguity around terminating requests early.
