### ISSUE TITLE
Truncated error response when using reply.code(undefined)

### ISSUE THREAD

**Issue by feugy** [fastify/fastify#2078]
## 🐛 Bug Report

When setting the response status code to `undefined` inside error handler, response returned is truncated.

This bug was unveiled while working on an issue with `fastifh-gql` [default error handler](https://github.com/mcollina/fastify-gql/blob/174ebb5185e0377acefcac0b0c638b3a575e61e3/lib/routes.js#L58), which set the response code to `err.statusCode`, that could be undefined.

## To Reproduce

[Codesandbox](https://codesandbox.io/s/upbeat-napier-broov?expanddevtools=1&fontsize=14&hidenavigation=1&moduleview=1&theme=dark)

Paste your code here:
```js
const fastify = require("fastify");
const axios = require("axios");

async function start() {
  const app = fastify({ logger: true });

  app.setErrorHandler(async (err, request, reply) => {
    reply.code(undefined);
    return { errors: [err.message] };
  });

  app.get("/", async (request, reply) => {
    throw new Error("This message will be truncated");
  });

  const port = 8080;
  try {
    await app.listen(port);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }

  await axios(`http://localhost:${port}`);
}

if (require.main === module) {
  start();
}
```

You'll get in return:
```js
(node:1727) UnhandledPromiseRejectionWarning: Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
```

On a browser such as Firefox or Chrome, the response is truncated.

## Expected behavior

The response should not be truncated.

## Your Environment

- *node version*: 13.3
- *fastify version*: >=2.11.0
- *os*: Linux

**Comment by mcollina** [comment]
I think the problem is that `reply.code(undefined)` should not be allowed.
I think we should make it throw if a non-valid status code is passed in.

Would that work?

**Comment by mcollina** [comment]
@feugy can you also open an issue on fastify-gql? It should not pass an `undefined` status code.
