### ISSUE TITLE
elasticsearch plugin for fastify

### ISSUE THREAD

**Issue by motss** [fastify/fastify#208]
Is the fastify team working on a plugin to use Elasticsearch?

**Comment by mcollina** [comment]
No, but you can!

**Comment by StarpTech** [comment]
I don't understand the debate about "if you have plugin for X" fastify provides a plugin system you can implement anything. Pick the Node.js driver and do it!

**Comment by delvedor** [comment]
Hi!
Thank you for checking out the project :)

As suggested by @mcollina you can easily write a plugin to support it, it's very easy!
Have a look at our [plugins guide](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md) and our [mongodb plugins](https://github.com/fastify/fastify-mongodb) as reference :)

**Comment by jsumners** [comment]
@StarpTech there wasn't a debate. He simply asked a question and it has been answered. Please provide constructive feedback in the future.

**Comment by StarpTech** [comment]
@jsumners I'm talking about this in general. That was not a nice answer but I just want to point it out. 🙏

**Comment by cagataycali** [comment]
A pull request for that would be good!

**Comment by delvedor** [comment]
https://github.com/fastify/fastify-elasticsearch
