### ISSUE TITLE
Modifying the request via callbacks and the next() function does not actually fire [Nestjs and Fastify]

### ISSUE THREAD

**Issue by amit12cool** [fastify/fastify#2083]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

I have been facing a issue where in fastify provides request stream in Nestjs middleware. Now, when parsing the stream is done successfully when next() is called the route handler function not gets called.

## To Reproduce

Run the nest application
npm run start
send curl post request at : http://localhost:8080/cats

Refere issue from Nestjs gihub repo
https://github.com/nestjs/nest/issues/4003

Paste your code here:

```js
https://github.com/amit12cool/testMiddleware
```

## Expected behavior

Route handler should be called.

Paste the results here:

``
getHello() function of Appcontroller should be called.
``

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
I would point you to https://github.com/nestjs/nest/issues/4003#issuecomment-582311707. I don't know Nest, and I do not know how to help.

**Comment by amit12cool** [comment]
@mcollina Thanks fo pointing me to the issue but that is raised by me. I was trying to get some help from you guys if you have any idea.

**Comment by mcollina** [comment]
I think the solution is clearly explained in the issue https://github.com/nestjs/nest/issues/4003#issuecomment-582298975.

```js
const app = await NestFactory.create(AppModule, {
    bodyParser: false,
});
```

Will enable you to parse the body manually instead of using the provided utilities. We recommend to use the provided utilities for doing this as there are lot of edge cases with deep security concerns.

Last note: this is not a support forum for Nest.js, and it's unlikely you will get a definitive answer here. If you need help in using Fastify directly, please open an issue on https://github.com/fastify/help.

**Comment by amit12cool** [comment]
The solution provided there doesn't work and before me commenting this on that issue the comment option was disabled by the owner of repo. I know its not related to fastify directly. Thanks
