### ISSUE TITLE
how to set version and name to plugin when using ESM ? 

### ISSUE THREAD

**Issue by fas3r** [fastify/fastify#2087]
Hello,

As documented [here](https://github.com/fastify/fastify/blob/master/docs/Plugins.md#esm-support), it's possible to use ESM for the plugin, but how to set version and name for [dependencies](https://github.com/fastify/fastify-plugin#dependencies) ? : 

```
// main.mjs
import Fastify from 'fastify'
const fastify = Fastify()

fastify.register(import('./plugin.mjs'))

fastify.listen(3000, console.log)


// plugin.mjs
async function plugin (fastify, opts) {
  fastify.get('/', async (req, reply) => {
    return { hello: 'world' }
  })
}

export default plugin
```

Can I continue to use `fastify-plugin` for that purpose ?

Thanks.

**Comment by mcollina** [comment]
You should be able to, did you encounter any problems?
