### ISSUE TITLE
How to disable the default "incoming request" and "request completed" logging.

### ISSUE THREAD

**Issue by SaugataDutta** [fastify/fastify#2094]
### Please note that this issue tracker is not a help forum and this issue may be closed.

Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Comment by mcollina** [comment]
Hi @SaugataDutta. This information is included in our docs at https://www.fastify.io/docs/latest/Server/#disablerequestlogging.

**Comment by SaugataDutta** [comment]
@mcollina  Thanks a lot.

**Comment by arnaduga** [comment]
Hello

I'm sorry, but I have an issue with this option: even if activated, I still have the incoming request and request completed log message.

```
const fastify = require("fastify")({
  logger: {
    level: "info",
    timestamp: () => `,"time":"${new Date(Date.now()).toISOString()}"`,
    disableRequestLogging: true,
    prettyPrint: true,
  },
});

```

```
[2021-02-07T17:22:31.317Z] INFO	 (28848 on Mac.local): Server listening at http://0.0.0.0:5000
[2021-02-07T17:22:58.009Z] INFO	 (28848 on Mac.local): incoming request
    req: {
      "method": "GET",
      "url": "/",
      "hostname": "localhost:5000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 52304
    }
    reqId: 1
[2021-02-07T17:22:58.014Z] INFO	 (28848 on Mac.local): request completed
    res: {
      "statusCode": 200
    }
    responseTime: 4.378115005791187
    reqId: 1
```

Is there anything I'm doing not correctly?

**Comment by arnaduga** [comment]
Damn... Forget about it. I applied this setting to logger, not to server. Sorry.

**Comment by gajus** [comment]
How do I do this when using a custom logger?

```ts
logger: createFastifyLogger(
  log.child((message) => {
    return message;
  }),
),
```

Obviously, I can filter the logs from within Roarr, but is there a way to make Fastify not surface them in the first place?

**Comment by teddybee** [comment]
> How do I do this when using a custom logger?
```
const serverOptions: FastifyServerOptions = {
  logger: logger,
  disableRequestLogging: true,
}

```

**Comment by arturog-sky** [comment]
I believe these logs belong to TRACE or DEBUG level, not INFO.  INFO log messages shout indicate startup, enabling of options, etc...  Can Fastify be changed to issue DEBUG messages for every request/response?  You don't want to disable everything else...

**Comment by jamesarosen** [comment]
@mcollina your link is broken. The correct URL is now https://fastify.dev/docs/latest/Reference/Server/#disablerequestlogging

**Comment by jsumners** [comment]
This thread is five years old. The website has changed.
