### ISSUE TITLE
How to stop parsing data when event 'close' occur on addContentTypeParser()

### ISSUE THREAD

**Issue by lagmanzaza** [fastify/fastify#2096]
In some case, a client cancels an HTTP request, event 'close' occur. I don't know how to stop handling that HTTP request

**Comment by mcollina** [comment]
You should avoid calling the callback or call it with an error if the request is aborted (`'abort'` event).

**Comment by lagmanzaza** [comment]
Could you explain why?

**Comment by lagmanzaza** [comment]
Are there any techniques to cancel an HTTP request from the client?

**Comment by mcollina** [comment]
You should always respond with something, otherwise the client will be left appended or the socket truncated.

**Comment by lagmanzaza** [comment]
Oh, I understood.
Thank you, sir.

I have the last question.
Can I send a response data when event 'close' occurs instead of parse the data to the handler 'hook'?

**Comment by mcollina** [comment]
call the callback with a custom error, and handle it in the error handler.

**Comment by lagmanzaza** [comment]
Thank you, sir
