### ISSUE TITLE
The HTTPInjectOptions typescript interface does not define the 'cookies' property

### ISSUE THREAD

**Issue by gyszalai** [fastify/fastify#2098]
## 🐛 Bug Report

The HTTPInjectOptions typescript interface should define the `cookies` property

## To Reproduce

The following code can not be compiled with typescript (sorry, the code cannot be run as is, but describes the problem well):
```typescript
    const fastify: FastifyInstance = ...
    const response: HTTPInjectResponse = await fastify
        .inject({
            method: 'POST',
            url: '/some-url',
            payload: { 'some': 'payload' },
            cookies: { foo: 'bar' },
        })
```

## Expected behavior

The code should be compilable with typescript, but I get the following error:

```
error TS2345: Argument of type '{ method: "POST"; url: string; payload: {... }; cookies: { foo: string; }; }' is not assignable to parameter of type 'string | HTTPInjectOptions'.
  Object literal may only specify known properties, and 'cookies' does not exist in type 'HTTPInjectOptions'.
```

## Your Environment

- *node version*: 12
- *fastify version*: >=2.12.0
- *os*: Mac

**Comment by Ethan-Arrowood** [comment]
Are cookies apart of HTTP Responses natively like that?

**Comment by gyszalai** [comment]
It's not about the response but the injected request. you can pass cookies to the inject function.

**Comment by Ethan-Arrowood** [comment]
Ahh I see! I think the best change would be to use the [`light-my-request`](https://github.com/fastify/light-my-request/blob/master/index.d.ts) types to define the `inject` definition as this is what is being used internally anyways. 

Would you like to send a PR?

**Comment by gyszalai** [comment]
oops, sorry, I forgot about this one.

**Comment by gyszalai** [comment]
The `InjectOptions` interface of light-my-request doesn't declare the `cookies` property either. Shall I file az issue (and a PR) there?

**Comment by mcollina** [comment]
Just open a PR there.

Il giorno mar 3 mar 2020 alle ore 17:44 Gyula Szalai <
notifications@github.com> ha scritto:

**Comment by gyszalai** [comment]
done
