### ISSUE TITLE
fastify.Router() is possible ?

### ISSUE THREAD

**Issue by nacimgoura** [fastify/fastify#210]
Hello,
thanks for your project :smiley: 
Is it possible to do as with express:
`router = express.Router(),`
I have a problem, I did this in my index.js : 
`app.register(require('./routes/route.js'), { prefix: '/api/indexation' });`
In my route.js, I did this : 
```
const indexWebsite = require('../controllers/indexWebsite');

module.exports = (app, params, next) => {
  app.get('/website', schema, indexWebsite);
  next();
};
```
But in my file indexWebsite I'm forced to put one more time `module.exports = (req, res)`
I would like to be able to import the route directly and then app. use (route). Is that even possible ?
Thank you :smiley:

**Comment by delvedor** [comment]
Hi! Can you show us your `indexWebsite` file?

**Comment by nacimgoura** [comment]
```

module.exports = (req, res) => {
  res.send({
    hello: 'salut',
  });
};

```
But I would like do this (like with expressjs) :
```
var express = require('express'),
	router = express.Router(),


module.exports = function (fastify) {
	fastify.use('/', router);
};

router.get('/', function (req, res, next) {
	proxy.indexProducts(req, res);
});
```

**Comment by mcollina** [comment]
Fastify uses a different model than express. You can define a plugin, and those plugins will define their routes, according to the fastify API. You can use plain express as you said, but you will have little benefit: if that is your goal, you should keep using express.

**Comment by nacimgoura** [comment]
Thank you for your respons :smiley:

**Comment by guotie** [comment]
same request, some time we have to use the router API to do with other framework, such as nuxt

**Comment by mcollina** [comment]
@guotie isn't this requirement fullfilled by:

```js
async myPlugin (app, opts) => {
  app.get('/world', async (req, res) => {
    return {
      hello: 'salut'
    };
  })
};

const server = Fastify()
server.register(myPlugin, {
  prefix: '/hello'
}) // this will have /hello/world return '{ "hello": "salut" }'
server.listen(3000)
```

**Comment by guotie** [comment]
nuxt serverMiddleware need something like this:

```
{prefix: '/api', handler: handleFunc}
```

**Comment by mcollina** [comment]
Can you point me to the docs or an example?

**Comment by delvedor** [comment]
@guotie I guess you need something like https://github.com/fastify/fastify-react.
Otherwise there is https://github.com/lyquocnam/fastify-nuxt :)

**Comment by guotie** [comment]
like 

https://nuxtjs.org/examples/auth-routes

the api/index.js

**Comment by guotie** [comment]
@delvedor fastify-nuxt Not work, I have try
