### ISSUE TITLE
More docs for await app.register() and await app.after()

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2101]
## 🚀 Feature Proposal

The new `await app.register()` and `await app.after()` are going to be popular. It's important that we documented them well.

https://github.com/fastify/fastify/pull/2093
https://github.com/mcollina/avvio/pull/92

**Comment by mcollina** [comment]
cc @delvedor @davidmarkclements

**Comment by jsumners** [comment]
Any PR should target the `next` branch.

**Comment by imrishabh18** [comment]
Hey @mcollina , Can I take up this issue ?

**Comment by mcollina** [comment]
Go for it!

**Comment by nuragic** [comment]
I'm not sure but maybe this issue could be closed, we already have docs here:
https://www.fastify.io/docs/latest/Reference/Server/#register
https://www.fastify.io/docs/latest/Reference/Server/#after
