### ISSUE TITLE
Ideas for type-safe decorators

### ISSUE THREAD

**Issue by alinnert** [fastify/fastify#2110]
## 🚀 Feature Proposal

This is about making decorators type-safe. There are multiple ways to achieve this so I wrote down a few ideas under "Example".

This is mainly for TypeScript users. But also JavaScript users benefit from this if they use an editor which uses TS under the hood. (e.g. VS Code, and I think also IntelliJ/WebStorm to some extend?, maybe even more)

## Motivation

Decorators currently work by adding properties to the `fastify` object and modifying them. This, however, leads to problems in TypeScript projects, because the new properties don't exist on the type of the original object. The message: `Property 'foo' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse>'`.

The solution provided in issue #1417 (to re-define the type of `FastifyInstance<...>`) has some drawbacks, though. Mainly because the modified type is global and static while the fastify instance is not. The fastify instance is also specific to every plugin that creates a new scope. So, actually multiple different instances are being used inside an app. With a global type plugin A can see properties of plugin B even though it shouldn't. You also need to keep the type definition up-to-date and in sync with the plugins you use because 3rd party plugins also affect the type.

### Solution 1) Getter

One easy solution would be a getter method:

~~~ ts
fastify.decorate('port', 8000)

const port = fastify.getDecorator('port')
// port is type 'any'

const port = fastify.getDecorator('port') as number
// port is type 'number'
~~~

**Drawbacks:**

- You have to type-cast the values
- You have to lookup the types of values from 3rd-party plugins

### Solution 2) The Golang way

This one is inspired by Golang and its integrated framework which also supports contexts (which achieve the same goal as `decorate()`). It would look like this:

~~~ ts
app.register(async (fastify, options) => {
  const decoratedFastify = fastify.decorate(fastify, { port: 8000 })

  const port = decoratedFastify.port
  // port is type 'number'

  // It's important to return the new instance
  // since its type includes the property 'port'.
  // Fastify also needs to handle this correctly.
  // See drawbacks.
  return decoratedFastify
})
~~~

This `decorate` function could look like this:

~~~ ts
function decorate<T>(
  fastify: fastify.FastifyInstance<Server, IncomingMessage, ServerResponse>,
  newProps: T
): fastify.FastifyInstance<Server, IncomingMessage, ServerResponse> & T {
  return { ...fastify, ...newProps }
}
~~~

Currently I don't know if it's possible to write this function with the signature `decorate(fastify, name, value)`. But this has the advantage of applying multiple decorators at the same time.

The big advantage here is: You can fully take advantage of type inference. You don't need to type the values you set nor the ones you read.

**Drawbacks:**

This slightly changes the way apps and plugins are need to be written because this works by creating new objects, which have new types (old instance + new properties). Plugins that use `decorate` need to return the new fastify instance. Apps that use such a plugin need to store the returned instance and make further operations with that instance (or use function chaining, which is already supported).

### Solution 3) Don't use decorators at all

I also had the idea to store values in a completely different place: In the plugin's ESM. I came to this solution by looking into the problem that `decorate` tries to solve: Make some data accessible in different places of the code compared to where it gets created or defined.

Currently the `fastify` instance is one and the same for every individual request, right? I don't know. But if this is the case one could use `WeakMap<FastifyInstance, T>` to store values for individual requests.

In the case of an authentication plugin it could do:

~~~ ts
interface User { ... }

export const users = new WeakMap<FastifyInstance<...>, User>()

function plugin (fastify, options) {
  /* ... */
  users.set(fastify, { ... })
}
~~~

Any other plugin that need to read the current user could do:

~~~ ts
import { users } from './auth-plugin'

function plugin (fastify, options) {
  const currentUser = users.get(fastify)
}
~~~

Since there's one `WeakMap` for every possible type this makes it totally type-safe. Also the values get GCed automatically after the request is done.

Alternatively you could also use an ordinary `Map` and clean up the values with the `onResponse` hook. Maybe that's more performant? If Fastify creates a `Symbol` for every request even an object would work.

Btw: This way one plugin cannot accidentally override a value of another plugin. I just saw an issue about that in the 'similar issues' section.

**Drawbacks:**

- Deprecate `decorate` and change existing plugins.
- Plugin scopes don't apply to this (but you can still pass a map to children via `options`, or `export` and `import` it.)
- Maybe there's some drawback I'm not thinking of?

---

Any thoughts on this?

**Comment by Ethan-Arrowood** [comment]
Great write up- I read through it quickly but I’m currently traveling. I’ll review this better on Monday and reply. Thank you for starting this discussion!

**Comment by Ethan-Arrowood** [comment]
Hi @alinnert ! As promised, I just got a chance to read through and digest this. You bring up a lot of good points and some great ideas, but one thing to keep in mind is that Fastify is JavaScript first. It is written in JS and we don't plan on changing that. As far as I know, we have not to modified the Fastify API in order to improve the TS experience. That said, if there is a good enough reason to we could surely bring it up.

The root of the issue with making `decorate` type safe is how the underlying JS method works. Rather than returning the newly decorate instance, it relies upon object prototype modification.

https://github.com/fastify/fastify/blob/67c58c62d985a60f8b1b717d7427453d957b0367/lib/decorate.js#L17-L34


I've struggled to find a true solution for this issue but i did my best to capture an okay user experience in the upcoming doc updates: https://github.com/Ethan-Arrowood/fastify/blob/typescript-docs/docs/TypeScript.md#using-a-plugin

Let me know if you have additional thoughts on this!

---

@fastify/leads do y'all have anything to add that I might've missed / been wrong about?

**Comment by alinnert** [comment]
I was about to ask if not even solution 1 could be implemented because it's not a change, it's a small addition. But then I've realized you can achieve a similar result to that by adding an index signature to the interface `FastifyInstance`. Just add `[x: string]: any` at the very bottom. This allows any number of additional properties on the fastify instance. It doesn't change the behavior of the other properties. I can make a PR if that's fine.

Yes, I did realize that object mutations are the root of the problem. TS would need the opposite of its "type guard" feature to allow for mutations like that (expanding types of variables instead of limiting them throughout their scope).
I'm just surprised and confused that all of this is almost no problem in front-end development but mainly in the back-end. E.g. immutability is a huge thing in React. This (and other patterns) make the front-end more TS friendly without even intending to do so. I'm kind of missing this in Node.

**Comment by Ethan-Arrowood** [comment]
I do not like `any`. We can explore the idea of a type signature that points to `unknown` though requiring the use to either declaration merge or type cast. I'd like more maintainers to weigh in on this though as that can lead to poor type safety if the user never actually calls `decorate`.

And yeah I guess you are correct. I've always toyed with the idea of a totally type safe backend framework but it seems to be more effort than it is worth when we can provide a nearly great type safe experience with fastify

**Comment by alinnert** [comment]
Yes, `unknown` was my first intuition. But I couldn't find any occurrences of `unknown` in that `.d.ts` file, but a lot of `any`. So I've chosen `any` as well. Linters actually disallows the usage of `any` at all. So, I thought the usage of `any` is for compatibility reasons. `unknown` definitely makes more sense, if it's supported by the user's TS version.

Do you mean that this typing encourages users to add properties to the fastify instance without using `.decorate()`? Then it's: `readonly [x: string]: unknown`.

**Comment by Ethan-Arrowood** [comment]
Yeah, in general, one of the pain points of this is the fact that when a user decorates the fastify instance with types they usually do so in a separate definition file. Then while they develop their application they call `decorate` with some plugin. There is no check that the things that plugin is claiming it is decorating fastify with is actually happening.

More over, sometimes a user may remove a plugin but forget to remove the type augmentation. Thus, they now can still be accidentally using the plugin in their code while its not going to be available during runtime.

**Comment by weiliddat** [comment]
Hey @Ethan-Arrowood and @fox1t I'm back after being bogged down with work last year. Will just add in some more findings/ideas in addition to those discussed in https://github.com/fastify/fastify/pull/2502, since this is still open and is more general to decoration.
I didn't find any elegant solutions for fastify type decoration yet, but I think it's still worth discussing.

1. Just a minimal example for returning union types on decorate. The problem with this is that I'm not sure how this works when wrapped in fastify-plugin, since this is only correct when registering a new scope after chaining the decoration.

```ts
const server = {
    decorate<T, K extends string, V>(this: T, key: K, value: V): T & Record<K, V> {
        (this as any)[key] = value;
        return this as any;
    },

    register<T>(this: T, plugin: (instance: T) => any) {
        plugin.bind(this);
        return this;
    },
};

server.register(
    (a) => {
        a
        .decorate('foo', 'bar')
        .decorate('hello', () => 'world')
        .register(
            a1 => {
                a1
                .decorate('baz', 1)
                .register(a2 => a2.baz)
            }
        )

        a.register(
            a2 => a2.foo && a2.hello() // type error is correct
        )
    }
)
```

2. Was playing around with avvio and its types, since that's what fastify is based upon (right?). This example relies on asserting the instance type. I tried adding another generic type and asserting that instead, but it didn't work for some reason.

```ts
import avvio, { context, Plugin } from "./"

type Hello = { hello: "world" }
type Foo = { foo: () => "bar" }

function addHello(instance: any): asserts instance is context<Hello> {
  instance.hello = "world"
  if (!("hello" in instance)) {
    throw new Error()
  }
  return instance
}

function addFoo(instance: any): asserts instance is context<Foo> {
  instance.foo = () => "bar"
  if (!("foo" in instance)) {
    throw new Error()
  }
  return instance
}

const first: Plugin<Hello, {}> = (instance, opts, cb) => {
  console.log("first loaded", opts)
  addHello(instance)
  addFoo(instance)
  instance.use(expectsHello)
  instance.use(expectsFoo)
  cb()
}

function expectsHello(instance: context<Hello>, opts: {}, cb: CallableFunction) {
  console.log("second loaded")
  console.log(instance.hello)
  cb()
}

function expectsFoo(instance: context<Foo>, opts: {}, cb: CallableFunction) {
  console.log("third loaded")
  console.log(instance.foo())
  cb()
}

avvio({}).use(first, { hello: "world" })
```

3. Just an idea - no implementation yet. An optional wrapper like fastify-plugin (or maybe we can indeed extend fastify-plugin, but scoping would then need to be an option) allowing the individual recipients of the instance to define decorator dependencies (also with TS types then). This would be entirely opt-in for TS users, and we can add additional compile- and runtime checks that make sure the types are correct in both cases.

And again, thanks for all the hard work, hope to contribute more now that I have time.

**Comment by Ethan-Arrowood** [comment]
Welcome back and these investigations are looking good. Feel free to ping me or the rest of the typescript crew (fastify/typescript) if you'd like to dig into things again. We also have Discussions enabled on the repo now so that might be a better place to hash this out!

**Comment by IanVS** [comment]
I'm getting started with fastify in a typescript repo currently.  Is https://github.com/fastify/fastify/issues/1417#issuecomment-458601746 still the current best practice to deal with fastify plugins adding configuration options to the fastify instance?

**Comment by Eomm** [comment]
@fastify/typescript is this issue still a thing?

I think we solved the decoration issue via `interfaces`

**Comment by lucsky** [comment]
> I think we solved the decoration issue via interfaces

@Eomm What? How? Where?
