### ISSUE TITLE
Advanced / Custom validation

### ISSUE THREAD

**Issue by frodoe7** [fastify/fastify#2111]
## 💬 Questions and Help

my POST request , should validate the request body with a certain schema
I revised [these docs](https://www.fastify.io/docs/latest/Validation-and-Serialization)

looks no way to use a custom validation method or even test the input with a regex pattern

for example

```json
{
  properties:  {
    email: { type: "string" , minLength : 5 , maxLength : 72 }
  }
}
```

now : 12#xc.com will be accepted but not email
and so on ,,

I have to match the input with a certain regex pattern or write my custom validation function

---

I aware I can do this after receiving the inputs and do my operations on it,
but it is not the best to write a second layer of validation operations

actually the application has much operations so it's the best to have my all validations in a single place inside the schema

**Comment by Eomm** [comment]
You can check the input throug JSON schema.
For your example, you should use [email format](https://json-schema.org/understanding-json-schema/reference/string.html#email-addresses) or the [`pattern`](https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions) property.

> write my custom validation function

If you need more checks, like accessing a DB or something the JSON schema doesn't support you should use our [hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#prehandler)
