### ISSUE TITLE
FST_ERR_DEC_ALREADY_PRESENT: The decorator 'xxx' has already been added!

### ISSUE THREAD

**Issue by wiredmartian** [fastify/fastify#2115]
I'm trying to decorate a request with the current user's data from the jwt auth token;

```
server.addHook("preHandler", async (request, reply, done) => {
    let { userId, email } = await request.jwtVerify();
    userId = AESEncryption.decrypt(userId);
    server.decorateRequest("currentUser", {
        userId: userId,
        email: email
    });
    done();
});

```

**PROBLEM**

The first request `GET` works, but when I make the same request again, I get this error:

```
{
    "statusCode": 500,
    "code": "FST_ERR_DEC_ALREADY_PRESENT",
    "error": "Internal Server Error",
    "message": "FST_ERR_DEC_ALREADY_PRESENT: The decorator 'currentUser' has already been added!"
}
```

**Environments**
*node version*: 11.15
*fastify version*: 2.11
*os*: Linux

**Comment by jsumners** [comment]
Please see the decorators documentation for how to use decorators -- https://www.fastify.io/docs/latest/Decorators/

You define a decorator prior to starting the server, not within route handlers.

**Comment by wiredmartian** [comment]
Alright, thanks :). I ended up with the code below.
```
server.addHook("preHandler", async (request, reply) => {
    let { userId, email } = await request.jwtVerify();
    userId = AESEncryption.decrypt(userId);
    request.currentUser = { userId, email };
});
```

Although, I'm not sure how it differs with the example from the docs. What's the difference between decorating the route request and decorating the global request object? Apart from one being defined before the server starts. It almost seems like they're doing the same thing.

```
// Decorate request with a 'user' property
fastify.decorateRequest('user', '')

// Update our property
fastify.addHook('preHandler', (req, reply, done) => {
  req.user = 'Bob Dylan'
  done()
})
```

**Comment by jsumners** [comment]
Using the decorator defines the shape of request objects. See https://mathiasbynens.be/notes/shapes-ics

**Comment by mcollina** [comment]
@jsumners we should really link that from the docs.

**Comment by jsumners** [comment]
Open an issue and assign it to me. I'll take care of it soon-ish.
