### ISSUE TITLE
Make decorate* methods throw after server is started.

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2116]
## 🚀 Feature Proposal

In https://github.com/fastify/fastify/issues/2115, the reporter is trying to decorate the global request object within a route. This is not supported by Fastify, and we should throw if `server.decorate()`, `server.decorateRequest()` or `server.decorateReply()` are called after `.ready()`.

**Comment by dnlup** [comment]
I would like to help here. I'll try put something together in the next days.
