### ISSUE TITLE
HTTP server errors not surfaced

### ISSUE THREAD

**Issue by gillesdemey** [fastify/fastify#212]
Errors emitted by the HTTP server aren't passed to the listen callback, I understand that you can access the `server` property but surely we can do better here? :)

```javascript
'use strict'

const fastify = require('fastify')

const s1 = fastify()
const s2 = fastify()

s1.listen(3000)

s2.listen(3000, err => {
  console.error(err) // no exception
})

s2.server.on('error', err => {
  console.error(err) // listen EADDRINUSE :::3000
})
```

**Comment by mcollina** [comment]
> Errors emitted by the HTTP server aren't passed to the listen callback, I understand that you can access the server property but surely we can do better here? :)

Surely you can send a pull request, this is OSS.

Joke aside, https://github.com/fastify/fastify/pull/215 fixes it.

**Comment by gillesdemey** [comment]
> Surely you can send a pull request, this is OSS.

Sorry, I thought I'd open a ticket first as a courtesy :) I'll be sure to send in a PR next time! 🙏

**Comment by delvedor** [comment]
I think @mcollina was not saying that you should fire a pr instead of an issue, he was just pointing out the *tone* of your issue :)

> property but surely we can do better here? :)

I know it is not intended, but it sounds like an order ;)
Have a nice day!
