### ISSUE TITLE
Implement #2124 onto next branch

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2129]
#2124 makes a great type change for depending on `light-my-request`. This should be added to the types in _next_ if its not already there.

**Comment by mauriceLC92** [comment]
@Ethan-Arrowood could I take this on?

**Comment by Ethan-Arrowood** [comment]
Go for it!

**Comment by mauriceLC92** [comment]
Thanks! Will check it out

**Comment by mauriceLC92** [comment]
@Ethan-Arrowood The types exist in `2.x` but not in `master`
So does that mean no work here is required? Or is it needed in `master` as well?

**Comment by Ethan-Arrowood** [comment]
No it is needed in master

**Comment by climba03003** [comment]
I will close it as it seems to be resolved.
https://github.com/fastify/fastify/blob/a454883afbd12871aef426ea43480d61240c11cf/types/instance.d.ts#L1

cc @Ethan-Arrowood If you think it is not resolved, free feel to re-open the issue.
