### ISSUE TITLE
How to use a mongoose plugin in fastify ?

### ISSUE THREAD

**Issue by frodoe7** [fastify/fastify#2130]
I'm using this plugin https://github.com/alex-ppg/fastify-mongoose
to support mongoose in my project

now - I'd like to add a mongoose plugin like this one : https://www.npmjs.com/package/mongoose-paginate-v2

to paginate my data , which is something required for any big project
how to add this plugin to my project ?

**Comment by jsumners** [comment]
Neither of those things are managed by the Fastify organization. You should be asking the plugin author how to use their plugin.
