### ISSUE TITLE
Can I use 'onResponse' hook without async or done?

### ISSUE THREAD

**Issue by rfgamaral** [fastify/fastify#2131]
I have small piece of code I need to run on the `onResponse` hook and for now I have it like this:

```ts
fastify.addHook('onResponse', request => {
    Container.reset(request.id);
});
```

Is there anything wrong with this or myabe I should go with:

**Option 2)**

```ts
fastify.addHook('onResponse', async request => {
    Container.reset(request.id);
});
```

**Option 3)**

```ts
fastify.addHook('onResponse', (request, _, done) => {
    Container.reset(request.id);
    done();
});
```

?

**Comment by Eomm** [comment]
> Is there anything wrong with this 

yes it is: you are creating a memory leak and blocking the onRequest hooks, check `hello 2`

```
const Fastify = require('fastify')
const fastify = Fastify({ logger: true })

fastify.addHook('onResponse', async () => {
  console.log('hello 1')
})

fastify.addHook('onResponse', () => {
  console.log('hello 2') // this is not executed
})

fastify.get('/', async function (request, reply) {
  return 'world'
})

fastify.listen(3000)
```

If you don't need to use `await`, `done()` callback is little bit faster because you are not creating promises

**Comment by rfgamaral** [comment]
Thank you so much for clarifying this for me :)
