### ISSUE TITLE
original route url

### ISSUE THREAD

**Issue by CnApTaK** [fastify/fastify#2141]
```
app.route({
	method: 'GET',
	url: '/test/:id',
	handler: async (req) =>
	{
		console.log(req.raw.originalUrl); // i get '/test/123'
		return 'test';
	},
});
```
i make GET request /test/123 and i want to get original url like '/test/:id' inside handler. how to do that?

**Comment by Eomm** [comment]
Here you are `reply.context.config.url`

Would you like to improve our docs?
It seems it is [not well documented](https://github.com/fastify/fastify/blob/master/docs/Reply.md#introduction)

**Comment by CnApTaK** [comment]
OMG! Thank you so much!)
