### ISSUE TITLE
TS types do not cover builder-style .inject() usage

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#2142]
## 🐛 Bug Report

https://github.com/fastify/fastify/blob/master/docs/Testing.md claims that this is legal syntax:

```
fastify
  .inject()
  .get('/')
  .headers({ foo: 'bar' })
  .query({ foo: 'bar' })
  .end((err, res) => { // the .end call will trigger the request
    console.log(res.payload)
  })
```

However, there are only two available types for inject():

```
    inject(opts: HTTPInjectOptions | string, cb: (err: Error, res: HTTPInjectResponse) => void): void
    inject(opts: HTTPInjectOptions | string): Promise<HTTPInjectResponse>
```

Hence builder-style inject fails to compile in TypeScript.

## To Reproduce

```js
        const response: fastify.HTTPInjectResponse = await app
          // @ts-ignore
          .inject()
          .get('/endpoint')
        expect(response.statusCode).toBe(200)
```

## Expected behavior

TypeScript compiler correctly accepts inject() without parameters and expects builder to be returned.

## Your Environment

- *fastify version*: >=2.12.1

**Comment by mcollina** [comment]
This is fixed by https://github.com/fastify/fastify/issues/2098. It'll be part of the next release.

**Comment by kibertoad** [comment]
@mcollina Thanks! Are there any timelines for the next release?

**Comment by mcollina** [comment]
I’ll try to do it tomorrow if I can.

**Comment by kibertoad** [comment]
@mcollina Unfortunately, instead of fixing the issue, 2.13.0 made it worse. Not only typings do not allow builder-style injection, but builder-style injection itself stopped working, so aforementioned example from documentation is broken now.

**Comment by mcollina** [comment]
Would you like to send a PR to https://github.com/fastify/light-my-request to fix it? Thanks

**Comment by kibertoad** [comment]
@mcollina I'll give it a shot, trying to figure out which version of light-my-request broke it...

error is `app.inject(...).get is not a function`

**Comment by kibertoad** [comment]
@mcollina Sorry, that was mistake on my part, app not being readied yet, obscured by the fact that app still exposed inject() method.

That said, original issue is still an issue, fastify.d.ts does not have `inject()` definition that would accept zero parameters.

**Comment by mcollina** [comment]
The offer to send a PR to fix is still open.

**Comment by kibertoad** [comment]
@mcollina Sorry it took a while. Finally created a PR in light-my-request repo.

**Comment by Eomm** [comment]
The inject function is a wrapper of light my request

https://github.com/fastify/fastify/blob/98328a422cdbd65ea2769c44dca3a2a2fff01332/fastify.js#L306

but this interface `.inject()` is made by fastify and not supported by light my request

**Comment by kibertoad** [comment]
@Eomm So you think that https://github.com/fastify/fastify/pull/2208 would be a better way to address it?
Note that https://github.com/fastify/light-my-request/pull/85 prevents it from resolving the problem completely.
