### ISSUE TITLE
[next] get compilers only after startup

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#2144]
In the `next` branch, I wrote a test to count how many AJV instances were being created to be sure to optimize this behaviour and to don't introduce regression about it since it can slow down the startup.

When I merged `master` in `next` I saw that this PR #2077 broken those tests.
This PR has moved the initialization of AJV in the `preReady` event.
This was necessary to let the user run `fastify.addSchema()` **after** the creation of an encapsulation context.

Now, because of this fix, a _plugin_ will not be able to use the context compiler function, unless listening the `preReady` event like this (notice `instance.ready()`):

```js
// THIS IS FOR NEXT BRANCH
const fastify = require('./fastify')()

// this trigger the schema validation creation
fastify.get(`/${Math.random()}`,
  { schema: { body: { type: 'object' } } },
  (req, reply) => reply.send()
)

fastify.register((instance, opts, next) => {
  console.log(instance.validatorCompiler) // it is NOT set
  instance.ready(() => {
    console.log('on ready', instance.validatorCompiler) // it is set
  })
  next()
})

fastify.listen(0, () => {
  console.log('listen', fastify.validatorCompiler) // it is set
})
```
(this in master work BEFORE #2077 : `// it is NOT set` was setted instead)

I think this is a good approach, but I'm not sure it is the best one.
I wonder if a new application hook to listen when a compiler is ready to use could be better? Or it would not so useful

WDYT?

**Comment by mcollina** [comment]
`on('preReady')` and `.ready()` have two different meaning. If this becomes a pattern, we might want to document it more clearly, and I agree that adding one more hook `schemaResolved` would be handy. After that, `validatorCompiler` will be set.

**Comment by Eomm** [comment]
I'll try to add it to the v2 first
