### ISSUE TITLE
where is my error?

### ISSUE THREAD

**Issue by CnApTaK** [fastify/fastify#2147]
```
const Ajv = require('ajv');
const fastify = require('fastify');
const log = console;

const app = fastify({
	logger: false,
	ignoreTrailingSlash: true,
});
const ajv = new Ajv({
	allErrors: true,
	removeAdditional: 'all',
	useDefaults: true,
	coerceTypes: true,
	$data: true,
});
app.setSchemaCompiler(schema => ajv.compile(schema));
app.setErrorHandler(async (err, req, res) => {
	console.error(err)
});
app.addHook('onError', async (request, reply, error) => {
	console.error(error);
});
app.addHook('onResponse', async req => {
	console.info('onResponse: %s', {...req.query});
	const obj = null;
	obj.test += 10;
});

app.route({
	method: 'GET',
	url: '/test',
	schema: {
		querystring: {
			type: 'object',
			properties: {
				id: {
					type: 'integer',
				},
			},
			required: [ 'id' ],
		},
	},
	handler: async () => {
		return 'just test'
	},
});

app.listen(8080, '0.0.0.0', 1000)
	.then(address => log.info(`server listening on ${address}`))
	.then(() => app.printRoutes().split('\n').map(str => {
		if (str.indexOf('└── / ') !== -1) return;
		log.info(str);
	}))
	.then(() => log.info('system is ready to work! :)'))
	.catch(err => {
		const { message, code, stack } = err;
		log.error('SERVER ERROR: %s%s', message, typeof code !== 'undefined' ? ` (${code})` : '');
		log.error('STACK:\r\n%s', stack);
		process.exit(1);
	});
```
with this code i run request to http://127.0.0.1:8080/test?id=123&value=456
in console i get:

> server listening on http://0.0.0.0:8080
> └── /
>     └── test (GET)
> 
> system is ready to work! :)
> onResponse: { id: 123 }

i receive 'just test' as reponse and i see no error anywhere..
but..
if i remove word 'async' in 'onResponse' hook
then i got:

> server listening on http://0.0.0.0:8080
> └── /
>     └── test (GET)
> 
> system is ready to work! :)
> onResponse: { id: 123 }
> C:\test\app.js:26
> 	obj.test += 10;
> 	^
> 
> TypeError: Cannot read property 'test' of null
>     at Object.<anonymous> (C:\test\app.js:26:2)
>     at onResponseIterator (C:\test\node_modules\fastify\lib\reply.js:517:10)
>     at next (C:\test\node_modules\fastify\lib\hooks.js:71:20)
>     at hookRunner (C:\test\node_modules\fastify\lib\hooks.js:86:3)
>     at ServerResponse.onResFinished (C:\test\node_modules\fastify\lib\reply.js:500:7)
>     at ServerResponse.emit (events.js:327:22)
>     at onFinish (_http_outgoing.js:739:10)
>     at onCorkedFinish (_stream_writable.js:685:5)
>     at afterWrite (_stream_writable.js:473:5)
>     at afterWriteTick (_stream_writable.js:460:10)

so.. how i supose to catch errors in async hooks?

**Comment by Eomm** [comment]
Why are you confused by this error?

`null` can't have properties so the error it is quite clear `Cannot read property 'test' of null`
```
	const obj = null;
	obj.test += 10;
```

**Comment by CnApTaK** [comment]
can you first read the post?
problem is that i dont get error when use async hook.
complete silence from app.. cannot even know that some code is not working since that place where error hapened

**Comment by Eomm** [comment]
You have hidden your **main question** very well:

![image](https://user-images.githubusercontent.com/11404065/77173759-51fcab80-6ac0-11ea-88ae-07b5109d0571.png)

> can you first read the post?

I will not reply to this kind of sentence.
The solution is in our docs.

**Comment by CnApTaK** [comment]
i read your docs. there is no word about this situation
