### ISSUE TITLE
TS type defs for inject query is wrong

### ISSUE THREAD

**Issue by rburgst** [fastify/fastify#2148]
## 🐛 Bug Report

after updating from fastify 2.12.1 to 2.13.0 the typescript definition for `fastify.inject` only supports a `string` for the `query` option.

## To Reproduce

Paste your code here:

```typescript
      const response = await fastify.inject({
        method: 'GET',
        url: `/myuri`,
        query: {
          param: 'value',
        },
      })
```
now throws a ts compiler error. Previously this was working fine.

The problem appears to stem from wrong typedefs in `light-my-request/index.d.ts` where query is defined as a string

```typescript

  interface InjectOptions {
    url?: string | {
      pathname: string
      protocal?: string
      hostname?: string
      port?: string | number
      query?: string
    }
    path?: string | {
      pathname: string
      protocal?: string
      hostname?: string
      port?: string | number
      query?: string
    }
    headers?: http.IncomingHttpHeaders | http.OutgoingHttpHeaders
 =>   query?: string
``` 
## Expected behavior

the above code should compile and work just as before.

## Your Environment

- *node version*: 12.13
- *fastify version*: >=2.13.0
- *os*: Mac

**Comment by Ethan-Arrowood** [comment]
Relevant PR here: https://github.com/fastify/fastify/pull/2124

This change needs to be made in the light-my-request repo then we can update the dep here in fastify. 

We should also add unit tests to cover this. 

Are you interested in sending a PR?

**Comment by rburgst** [comment]
created a PR, obviously it fails until its fixed.

**Comment by Eomm** [comment]
Would you like to fix it in https://github.com/fastify/light-my-request ?

**Comment by rburgst** [comment]
done, see https://github.com/fastify/light-my-request/pull/76

**Comment by juriwiens** [comment]
I would like to add that before the light-my-request types were imported, I was able to provide multiple values for the same key like: `query: { fields: ["a", "b"] }`. As the implementation still allows this, however, the types should be extended accordingly, right?

**Comment by mcollina** [comment]
> I would like to add that before the light-my-request types were imported, I was able to provide multiple values for the same key like: query: { fields: ["a", "b"] }. As the implementation still allows this, however, the types should be extended accordingly, right?

Yes, would you like to send a PR to light-my-request?

**Comment by juriwiens** [comment]
> > I would like to add that before the light-my-request types were imported, I was able to provide multiple values for the same key like: query: { fields: ["a", "b"] }. As the implementation still allows this, however, the types should be extended accordingly, right?
> 
> Yes, would you like to send a PR to light-my-request?

Done: https://github.com/fastify/light-my-request/pull/77

**Comment by rburgst** [comment]
@juriwiens this has already been fixed in https://github.com/fastify/light-my-request/pull/76 and merged

**Comment by rburgst** [comment]
also https://github.com/fastify/fastify/pull/2149 is already merged, the only thing missing is a new fastify release

**Comment by Ethan-Arrowood** [comment]
@rburgst I believe @juriwiens is based off of your work and allows for values to be arrays of strings, not just strings 😁

**Comment by mcollina** [comment]
This was fixed
