### ISSUE TITLE
can't catch error from 'onResponse' async hook

### ISSUE THREAD

**Issue by CnApTaK** [fastify/fastify#2150]
i can see that your logger somehow catches my error. but i dont want to use your logger. i want to make my own.
![image](https://user-images.githubusercontent.com/1032312/77183594-3f41a100-6ad7-11ea-8e4f-4ba92539a524.png)

**Comment by jsumners** [comment]
So use your own https://www.fastify.io/docs/v2.12.x/Server/#logger

**Comment by CnApTaK** [comment]
how to catch error to use it in mine? )

**Comment by CnApTaK** [comment]
'onError' hook does not catch my throw

**Comment by jsumners** [comment]
Please read the documentation -- https://www.fastify.io/docs/v2.12.x/Server/#seterrorhandler

**Comment by CnApTaK** [comment]
why? does not work
![image](https://user-images.githubusercontent.com/1032312/77185124-8466d280-6ad9-11ea-9ce3-440de6f00461.png)

**Comment by jsumners** [comment]
Your attitude is unwelcome here. You were warned a previous thread and in this one you continue making aggressive statements like "LOOK AT CONSOLE!!!". We are not here to take your abuse or do the work for you.
