### ISSUE TITLE
Feature: Add support for 'all' method in route definition

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify#216]
I am trying to create proxy plugin for fastify where I need to intercept all http methods but I am not able to do that.
find-my-way router has support for `route.all` but fastify may not be supporting it yet. 
Is it possible to add it?

If there is any other way to achieve this please let me know.

**Comment by delvedor** [comment]
Hi!
At the moment there is no way to do it in Fastify, but since is already supported in [find-my-way](https://github.com/delvedor/find-my-way) it should not be hard to implement.
I'll work on it :)

**Comment by delvedor** [comment]
Done in #224

**Comment by nileshmali** [comment]
Thats Awesome!!! 👍 
Thanks
