### ISSUE TITLE
Fastify crashes when reply code is not recognized

### ISSUE THREAD

**Issue by chiku** [fastify/fastify#2169]
## 🐛 Bug Report

Fastify crashes when reply code is not recognized.

## To Reproduce

Run fastify server that returns an exotic response code.

```js
const fastify = require('fastify')({ logger: true });

fastify.get('/', async (request, reply) => {
  reply.code(525); // exotic response code
  return { hello: 'world' };
});

const start = async () => {
  try {
    await fastify.listen(3000);
    fastify.log.info(`server listening on ${fastify.server.address().port}`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
```

Make a request to the server
```bash
curl http://localhost:3000
```

The application crashes.

The HTTP response code is 500 and the response body is as follows.

```json
{"statusCode":500,"code":"FST_ERR_BAD_STATUS_CODE","error":"Internal Server Error","message":"FST_ERR_BAD_STATUS_CODE: Called reply with malformed status code"}
```

## Expected behavior

The application should not crash

## Your Environment

- *node version*: v10.19.0
- *fastify version*: 2.13.0
- *os*: Mac

**Comment by mcollina** [comment]
The bug that https://github.com/fastify/fastify/pull/2082 tried to fix is `reply.code(undefined)`.  I think an alternative implementation of https://github.com/fastify/fastify/pull/2082/files#diff-d2fdf63c1d7f1d9f68270b6dfa8c930cR201 can be provided to pass the given unit test that does not crash the above code. I do not think we should have a different behavior between v2 and v3, this is just a regression.

@leorossi would you be able to do a follow-up PR?

**Comment by leorossi** [comment]
Yes assign it to me please
