### ISSUE TITLE
Types for register() have a problem

### ISSUE THREAD

**Issue by AmeerTaweel** [fastify/fastify#2172]
## 🐛 Bug Report

The `register` function expects a `ServerOptions` object as it's second parameter where it should expect a `RegisterOptions` object.

## To Reproduce

1. Create a Fastify project using Typescript.
2. Create a route.
3. Try to [register the route with a prefix](https://www.fastify.io/docs/latest/Routes/#route-prefixing).

```ts
app.register(myRoute, {prefix: '/v1'})
```

## Expected behavior

I shouldn't get a TS-Lint complaining about me giving the wrong type.

## Your Environment

- *node version*: 12.16.1
- *fastify version*: 2.13.0
- *os*: Linux (Ubuntu)

**Comment by AmeerTaweel** [comment]
It works if I only do this:
`app.register(myRoute)`

**Comment by AmeerTaweel** [comment]
I think that the problem is in `fastify.d.ts` at line **541**:
```ts
register<Options extends RegisterOptions<HttpServer, HttpRequest, HttpResponse>, PluginInstance extends Function>(plugin: Plugin<HttpServer, HttpRequest, HttpResponse, Options, PluginInstance>, options?: Options): FastifyInstance<HttpServer, HttpRequest, HttpResponse>
```

**Comment by AmeerTaweel** [comment]
The exact error:
Argument of type **'{ prefix: string; }'** is not assignable to parameter of type **'ServerOptions'**.
Object literal may only specify known properties, and **'prefix'** does not exist in type **'ServerOptions'**. **ts(2345)**

**Comment by mcollina** [comment]
would you like to send a PR?

**Comment by AmeerTaweel** [comment]
The problem should be in **`fastify.d.ts`** at line **541**:

```ts
register<Options extends RegisterOptions<HttpServer, HttpRequest, HttpResponse>, PluginInstance extends Function>(plugin: Plugin<HttpServer, HttpRequest, HttpResponse, Options, PluginInstance>, options?: Options): FastifyInstance<HttpServer, HttpRequest, HttpResponse>
```

This is the only definition of types for the `register` function. The thing is, I see that the parameter `options` has the type `Options` that extends the type `RegisterOptions` which is the correct type.

I'd love to send a PR since this would be my first Open Source contribution but I really don't see the problem in the type definition.

**Comment by mcollina** [comment]
I would recommend to create an example repo to demonstrate your problem. It'd be hard or impossible to help you otherwise.

**Comment by AmeerTaweel** [comment]
I did that. Here is the [example-repo](https://github.com/AmeerTaweel/fastify-test-repo). The error will be in `src/index.ts` at line 16.

**Comment by vnazar** [comment]
The problem is that you are using the wrong option type in your plugin definition. If you see in your   _myRoute.ts_ file, you use `ServerOption` when in reality you shoud use `RegisterOptions<http.Server, http.IncomingMessage, http.ServerResponse>`, like this:

```typescript 
import { FastifyInstance, RegisterOptions } from 'fastify'
import * as http from 'http'

export default function(app: FastifyInstance, options: RegisterOptions<http.Server, http.IncomingMessage, http.ServerResponse> , done: Function) {
	app.get('/myRoute', async (req, res) => {
		res.send({message: `My Route`})
	})
	done()
}
```
Regards,

**Comment by AmeerTaweel** [comment]
Thank you so much, it worked:clap:
