### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by jadhavajay** [fastify/fastify#2173]
## 🚀 Feature Proposal

Now that it [has been announced](https://github.com/denoland/deno/issues/2473#issue-453631188) that Deno 1.0 will be released the 13rd of May 2020.

So maybe it's time to consider this?

## Motivation

Another high-performance web-framework made available to Deno.land as well.

## Example
Few existing web frameworks supporting Deno are:
https://deno.land/x/oak/
https://github.com/syumai/dinatra

**Comment by jsumners** [comment]
Deno !== Node.js. We'd have to write a new framework to support that runtime environment.

**Comment by nsisodiya** [comment]
I love fastify. Deno is really cool. I don't think, porting to deno will be hard because deno support typescript and await is first class.

**Comment by nsisodiya** [comment]
I request to keep the issue open.

**Comment by mcollina** [comment]
It would be extremely hard to port. We are leveraging Node.js APIs everywhere, across all of our dependencies.

I might be considering it if you have a significant budget to invest in making it happen.

**Comment by gustavosanchezgalarza** [comment]
Hi: Do you think this announcement could change the current position?
https://deno.com/blog/the-deno-company

**Comment by zekth** [comment]
> Hi: Do you think this announcement could change the current position?
> https://deno.com/blog/the-deno-company

Still does not change the fact that nodeJs Apis differs a lot from Deno.
