### ISSUE TITLE
Proposal: A way to control the order that multiple hooks are applied for the same hook event

### ISSUE THREAD

**Issue by mkinoshi** [fastify/fastify#2175]
## 🚀 Feature Proposal

I am proposing a way to control the order that multiple hooks are applied for the same hook event. Let's say you have two `preHandler` hooks that you register in your code. One is registered at the root level, and the other is registered at a specific route level. In the current implementation, I believe the hook registered at the specific route level has higher precedence over a root level hook, and there is no way to change the order that they are applied.

## Motivation

I have monitoring logic that I would like to apply for all routes, and it injects some logic to each hook event. It is registered at the root level. In addition to this, I have authentication logic applied to some of the protected routes. The authentication logic is registered at the route level so it has higher precedence and runs before the monitoring code. This would lead to inaccurate monitoring results. I would like to control the order of applying hooks on the same hook event without duplicating the monitoring logic on the other hook.

## Example

I propose that a hook definition takes a priority index as an optional third argument. When we have multiple hooks registered for the same hook event, then we will sort the hooks using the priority index when we build hooks. I believe the logic could live [here](https://github.com/fastify/fastify/blob/master/lib/hooks.js#L49). The proposed logic works a similar way to how `z-index` works in css. I do recognize that my solution is not necessarily the cleanest way to solve this issue. I am open to suggestions.

**Comment by Eomm** [comment]
>  I believe the hook registered at the specific route level has higher precedence over a root level hook

This is not true unless you are experimenting a bug in your usage

This simple snipped show the right order:

```js
// root
fastify.addHook('preHandler', (req, reply, done) => {
  console.log('preHandler 1')
  done()
})

fastify.register((instance, opts, next) => {
  // plugin
  instance.addHook('preHandler', (req, reply, done) => {
    console.log('preHandler 2')
    done()
  })
  instance.get('/', (req, reply) => reply.send())
  next()
})

fastify.listen(3000)
```

Regarding the feature-request, I think it is already doable acting on `onRoute` hook and changing the options

**Comment by mkinoshi** [comment]
@Eomm Yeah, you're right. There was a bug in my code that basically flipped the order of registering :/ It's also good to know that it is possible to do it `onRoute` option. Thank you. I will close this one now.
