### ISSUE TITLE
Declaration error in fastify.d.ts : app.use must accept async middleware

### ISSUE THREAD

**Issue by jlguenego** [fastify/fastify#2186]
## 🐛 Bug Report

Small issue, very easy to fix.
Typescript: we cannot use async middleware with linting.
Because it cannot properly check the returned type.
Problem while linting with rule : @typescript-eslint/no-misused-promises

Async middleware must return `Promise<void>`

## To Reproduce

```
git clone https://github.com/jlguenego/node-expose-sspi.git
cd node-expose-sspi
cd example
cd fastify-simple
npm i
npm start
```

The code is perfectly working. But if you look at `server.ts`:

```js
// Require the framework and instantiate it
import fastify from 'fastify';
import { sso } from 'node-expose-sspi';

const app = fastify({ logger: true });

// eslint-disable-next-line @typescript-eslint/no-misused-promises
app.use(sso.auth());

// Declare a route
app.get('/', (request, reply): void => {
  reply.send(request.raw.sso);
});

// Run the server!
const start = async (): Promise<void> => {
  try {
    await app.listen(3000);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};
start();
```
 The middleware `sso.auth()` is async, therefore it will returned Promise<void>.
But the fastify declaration file indicates an output only with void.

If you accept this issue, I can propose you the pull request to correct it. ;)

**Comment by mcollina** [comment]
That code has likely a memory leak. Please read it through in https://github.com/mcollina/make-promises-safe.

The types are actually correct and they are helping you avoiding a very nasty bug.

**Comment by jlguenego** [comment]
Do you mean that in fastify all the middleware must be sync ?
I would propose this :

now: 
```
use(middleware: Middleware<HttpServer, HttpRequest, HttpResponse>): void
```
proposed:

```
use(middleware: Middleware<HttpServer, HttpRequest, HttpResponse>): void | Promise<void>
```

**Comment by mcollina** [comment]
Also in express, all middleware should have a callback. There is no one catching the errors on those promises.

**Comment by jlguenego** [comment]
I have now understood ;) And my middleware is now corrected. Thanks for this ;)
