### ISSUE TITLE
[Reqeust] Please add to techempower.com benchmark suite

### ISSUE THREAD

**Issue by dcworldwide** [fastify/fastify#219]
Would be interesting to see how you guys stack up. 

E.g. https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=fortune&c=5

**Comment by mcollina** [comment]
Definitely, I will be interested too! Those benchmarks are independently developed, and I think it should not be our goal to help maintaining those. You should probably open an issue or send a PR there.

**Comment by dcworldwide** [comment]
OK cool!
