### ISSUE TITLE
Failed building the schema for POST

### ISSUE THREAD

**Issue by MacThanos** [fastify/fastify#2193]
## 🐛 Bug Report

Can't resolve reference of the id from the JSON schema using the default validation engine

## To Reproduce

```js
"use strict";

module.exports = async function (fastify, options, next) {
  fastify.addSchema({
    $id: "http://foo/common.json",
    type: "object",
    definitions: {
      foo: {
        type: "object",
        properties: {
          city: { type: "string" }
        }
      }
    }
  });

  const refToSharedSchemaDefinitions = {
    type: "object",
    properties: {
      home: { $ref: "http://foo/common.json#/definitions/foo" },
      work: { $ref: "http://foo/common.json#/definitions/foo" }
    }
  };

  fastify.post(
    "/",
    {
      schema: { body: refToSharedSchemaDefinitions }
    },
    async (request, reply) => {
      reply.send("working");
    }
  );

  next();
};

module.exports.autoPrefix = "/test";

```

## Expected behavior

Would just simply validate the body as I have copied the example in the document but instead got this error in the terminal

```js
ERROR (FastifyError [FST_ERR_SCH_BUILD]/9807 on 1xx-1xx-1-105.pgi.com): FST_ERR_SCH_BUILD: Failed building the schema for POST: /v1/test, due error can't resolve reference http://foo/common.json#/definitions/foo from id #

FastifyError [FST_ERR_SCH_BUILD]: FST_ERR_SCH_BUILD: Failed building the schema for POST: /v1/test, due error can't resolve reference http://foo/common.json#/definitions/foo from id #
```

## Your Environment

- *node version*: 14
- *fastify version*: >=2.13.0
- *os*: Mac
- *any other relevant information*

**Comment by Eomm** [comment]
I applied a fix here:

```js
module.exports = async function (fastify, options, next) {
```

You should use `async` pattern or `next/callback` one, not both, so just remove the async keyword

```js
module.exports = function (fastify, options, next) {
```

Then I cannot reproduce with:

```js
npm i fastify-cli -g
fastify start -l debug your-file.js
> {"level":30,"time":1586680250399,"pid":9156,"hostname":"EOMM-XPS","msg":"Server listening at http://127.0.0.1:3000","v":1}
```

Could you add more info to replicate or retry with the `module.exports` fix?

> node version: 14

I tried with LTS 12 since that version has not been released yet

**Comment by MacThanos** [comment]
Hi Manuel,

Thanks for the quick response. I tried to install a fresh version of fastify without any plugins and it works. 

I then add in the plugin one by one to see if it throw an error again and it did with the 'fastify-cors'

All I did was to add this in the index entry file

fastify.register(require('fastify-cors'), { 
  // put your options here
})

**Comment by MacThanos** [comment]
also I'm using node v12 and not v14 :-)

**Comment by Eomm** [comment]
I'm still unable to reproduce adding `fastify-cors` to the script above.

I think you are trying to use the schema you have added in `fileA.js` from some `fileB.js`.
'cause of the encapsulation you should add the schema to the root context of both files since it is visible only inside the file/plugin you have added it (unless to use `fastify-plugin` wrapper)

**Comment by MacThanos** [comment]
This is my index entry file which load up all my routes in 'routes'  folder. Are you saying that I should write my JSON schema in this file instead?

```js
"use strict";

const fastify = require("fastify")({
  logger: {
    level: "error"
  },
});


const path = require("path");
const AutoLoad = require("fastify-autoload");

fastify.register(require('fastify-cors'), {
//   // put your options here
})

// Load All Plugins (Routes)
fastify.register(AutoLoad, {
  dir: path.join(__dirname, "routes"),
  options: { prefix: "/v1" },
});

// Run the server!
fastify.listen(7000, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  fastify.log.info(`server listening on ${address}`);
});
```

**Comment by Eomm** [comment]
> Are you saying that I should write my JSON schema in this file instead?

Yes, this is the fast solution


Have you generated the project with `fastify generate`?
If so, you could just create a file `schemas.js` in `plugins/` folder:

```
module.exports = fp(function (fastify, opts, next) {
  fastify.addSchema({
    $id: "http://foo/common.json",
    type: "object",
    definitions: {
      foo: {
        type: "object",
        properties: {
          city: { type: "string" }
        }
      }
    }
  });
  next()
})
```

Then your schema will be available to all the `services/` files.
This is nicer I think

**Comment by MacThanos** [comment]
Your method above works by wrapping the fastify.addSchema inside the ```fastify-plugin```.  I can now reuse  the shared schema ```$ref``` for nested JSON selection.

> Have you generated the project with fastify generate?

I just did a manual NPM INIT to create my project but I will give the CLI a go.

Thanks again for your help. I really like Fastify so keep up the good work 😄
