### ISSUE TITLE
Add an onTimeout hook

### ISSUE THREAD

**Issue by samking** [fastify/fastify#2203]
## 🚀 Feature Proposal

There are hooks for most events in a request's lifecycle, but I believe that a request that times out doesn't go through the onError or onResponse hooks, so there currently isn't any way to respond to timeouts.  This feature proposal is adding an onTimeout hook (or something similar) that would be invoked whenever a request times out.

## Motivation

In our app, we want to know how many currently-outstanding requests there are.  That way, when we stop sending requests to one server (to do a rolling update), we can know when the server is fully drained and it's safe to update it.  To implement our currently-outstanding-request-counter, we can increment a counter when the request comes in, but without an onTimeout hook, we can't properly decrement the counter.  We could manually manage the timeouts out of band, but it would be more convenient to do it all in the context of Fastify hooks.

## Example

```
fastify.addHook('onTimeout', () => counter--)
```

**Comment by mcollina** [comment]
Would you you like to work on this and send a pull request? I can see this being a useful feature, but it might have some perf impact that we should avoid.

**Comment by samking** [comment]
I probably don't have time to do it right now, but if you're open to it, I can look into it in a few weeks!

Thanks!

**Comment by zekth** [comment]
Giving it a shot. Just to be clear, this hook will only be called on the `node httpserver timeout` which results not having acces to the fastify request. (Regarding the example provided)
