### ISSUE TITLE
Always return a promise on `server.listen` even when it is called with a callback.

### ISSUE THREAD

**Issue by klausbayrhammer** [fastify/fastify#2207]
## 🚀 Feature Proposal

Always return a promise on `server.listen` even when it is called with a callback.

## Motivation

When `server.listen` is called with a callback it returns void where `server.listen` without a callback returns a promise. This can lead to confusion when using both in conjunction with `await` because the `await` resolves before the server is actually started/available

## Example

```js
    await server.listen(3000, (err) => {
        console.log(`callback called`)
    })
    console.log('resolved before the server is started')
    await fetch('http://localhost:3000/') // this would lead to request to http://localhost:3000/ failed, reason: connect ECONNREFUSED 127.0.0.1:3000
```

## Another Example
I stumbled upon this because I wanted to test-drive my fastify-server where my test-code looked like this

```ts
import 'jest'
import fetch from 'node-fetch'
import Server from '../server'

const server = new Server();

it('returns HTTP 200 GET when / is called', async () => {
    await server.start()
    expect((await fetch('http://localhost:3000/')).status).toEqual(200)
})
```

and my production code looked like this
```ts
import * as fastify from 'fastify'

const server: fastify.FastifyInstance = fastify({})

export default class {
    start () {
        return server.listen(3000, (err) => {
            if (err) {
                console.log(err)
                process.exit(1)
            }
            console.log(`server listening on ${server.server.address()}`)
        })
    }
}
```

## Conclusion
I know that there is an easy fix for this in my code, but I think it would cause less confusion if somebody uses it similarly

**Comment by Eomm** [comment]
Why not?

```
export default class {
    start () {
        return new Promise((resolve, reject) => {
          server.listen(3000, (err) => {
              if (err) {
                  reject(err)
                  return
              }
              resolve(`server listening on ${server.server.address()}`)
          })
        })
    }
}
```

**Comment by klausbayrhammer** [comment]
I know there is various ways of solving this - the nicest one probably being

```js
export default class {
    start () {
        return server.listen(3000)
            .then((() => console.log(`server listening on ${server.server.address()}`)
    }
}
```

However it took me quite some time to figure out that `server.listen` with a callback does not return a promise because when using it with `await` it simply resolves. In fact I only found it out when I prepared the example for this issue, because I didn't use `await` but `.then()` which lead to the error `Cannot read property 'then' of undefined` which gave me the hint that listen behaves differently with/without a callback passed in.
So the idea was to always return a promise, so people do not have the same issue.

**Comment by jsumners** [comment]
You should never expect a promise to be returned when you use a callback based API. They are, or at least should be, mutually exclusive.

**Comment by Eomm** [comment]
I understand your point but this behaviour is a standard de-facto

For example a user that doesn't use promises, but callback in case of error would see a `unhandled promise rejection` in the console and, if the dev had set the `--unhandled-rejections=strict` the app will crash.

So it is a matter of choice promise or callback: fastify supports both

**Comment by jsumners** [comment]
I think this is sufficiently answered.
