### ISSUE TITLE
Param schemas are not validated properly

### ISSUE THREAD

**Issue by firasdib** [fastify/fastify#2221]
## 🐛 Bug Report

We are setting schemas for our params in the routes, which should validate them to be of specific types (and exist), but requests are not rejected when required params are discarded or of incorrect type.

## To Reproduce

```js
// Schema

const schema = S.object()
    .additionalProperties(false)
    .prop('x', S.number().required());

// Route config

const config = {
  schema: {
    params: schema.valueOf(),
  }
}

// Route registration

server.get('/:x', opts, () => {})

```

## Expected behavior

The request should be rejected when the param is not included or not a number.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.13.1
- *os*: Linux

**Comment by jsumners** [comment]
Shouldn't `.required()` be on `.prop()` instead of `.number()`?

**Comment by Eomm** [comment]
Can't reproduce

```
const fastify = require('fastify')({ logger: true })
const S = require('fluent-schema')

const schema = S.object()
  .additionalProperties(false)
  .prop('x', S.number().required())

const config = {
  schema: {
    params: schema.valueOf()
  }
}
fastify.get('/:x', config, () => {})
fastify.listen(3000)
```
```
curl http://localhost:3000/sad
{"statusCode":400,"error":"Bad Request","message":"params.x should be number"}
```

Do you have customized ajv?

**Comment by firasdib** [comment]
Interesting...

The only customization I have is this:

```js
  ajv: {
    customOptions: {
      strictKeywords: true,
      removeAdditional: false,
    }
  },
```

**Comment by Eomm** [comment]
Do you have an error handler?

**Comment by firasdib** [comment]
User error! It works as expected. Please disregard.
