### ISSUE TITLE
reply.statusCode is not defined in TS type definitions

### ISSUE THREAD

**Issue by moltar** [fastify/fastify#2223]
## 🐛 Bug Report

Docs & implementation have a prop `statusCode`, which isn't available via `FastifyReply<HttpResponse>` definition.

Docs: https://www.fastify.io/docs/latest/Reply/#statuscode

Definitions: https://github.com/fastify/fastify/blob/64296c84b57eb8f6f63bf51579febcfd274a97a5/types/reply.d.ts#L8

**Comment by delvedor** [comment]
Hello! Would you like to open a pr? :)

**Comment by moltar** [comment]
Done!

**Comment by rkaw92** [comment]
Hi, going by the info displayed by GitHub in the commit, this fix should be included in `v2.14.0`: https://github.com/fastify/fastify/commit/2e9994d1c3cb0c61424d624674ec517360542c26

However, upon installing v2.14.0, I find that the type file, `fastify.d.ts`, still lacks the `statusCode` property in the FastifyReply type. Am I missing something? Is the type file built in a way that can result in an inconsistency like this before npm publish?
