### ISSUE TITLE
How to override the default clientErrorHandler?

### ISSUE THREAD

**Issue by chiku** [fastify/fastify#2226]
#### You have already researched for similiar issues?

I looked into the pull request that added a handler for clientError. (https://github.com/fastify/fastify/pull/105/files).

The documentation for Fastify does not mention how to implement a custom clientError handler

#### What are you trying to achieve or the steps to reproduce?

I expect a way to override the default client error handler.

Create a minimal application running on port 3000.

```js
const Fastify = require('fastify');

const fastify = Fastify({ logger: true });

function errorHandler (error, request, reply) {
  request.log.error(error, 'handled error');
  error.message = 'handled: ' + error.message;
  reply.send(error);
}

fastify.setErrorHandler(errorHandler)

fastify.get('/boom', async (request, reply) => {
  throw new Error('BOOM');
});

async function start () {
  try {
    await fastify.listen(3000);
    fastify.log.info(`Server listening on ${fastify.server.address().port}`);
  } catch (err) {
    fastify.log.error(err, 'Failed to start server');
    process.exit(1);
  }
};

start();
```

Simulate a client error by using an incorrect HTTP method.

```bash
curl -X GE http://localhost:3000/boom
```

#### What was the result you received?
```json
{"error":"Bad Request","message":"Client Error","statusCode":400}
```

#### What did you expect?

I expected a way to override the client error handler. This handler is defined in [fastify/fastify.js](https://github.com/fastify/fastify/blob/28fcb5f9438e85031265a9b0ba60bb01791db010/fastify.js#L381)

There is no documented way to override this handler so that I can customise the error response.

#### Context

* *node version*: 12.16.2
* *fastify version*: 2.13.1
* *os*: Mac

**Comment by Eomm** [comment]
What do you want as output? Could you write a demo output?

Your code produce this response, not what you wrote:

```
$ curl http://localhost:3000/boom
{"statusCode":500,"error":"Internal Server Error","message":"handled: BOOM"}
```

**Comment by chiku** [comment]
@mcollina , consider a scenario where a route has a schema configured.

```javascript
const Fastify = require('fastify');

const fastify = Fastify({ logger: true });

function errorHandler(error, request, reply) {
  request.log.error(error, 'handled error');
  error.message = 'handled: ' + error.message;
  reply.send({
    error: {
      code: error.code || 500,
      message: error.message
    }
  });
}

const boomSchema = {
  response: {
    400: {
      type: 'object',
      properties: {
        error: {
          type: 'object',
          properties: {
            code: { type: 'string' },
            message: { type: 'string' }
          }
        }
      }
    },
    500: {
      type: 'object',
      properties: {
        error: {
          type: 'object',
          properties: {
            code: { type: 'string' },
            message: { type: 'string' }
          }
        }
      }
    }
  }
};

fastify.setErrorHandler(errorHandler);

fastify.get('/boom', { schema: boomSchema }, async (request, reply) => {
  throw new Error('BOOM');
});

async function start() {
  try {
    await fastify.listen(3000);
    fastify.log.info(`Server listening on ${fastify.server.address().port}`);
  } catch (err) {
    fastify.log.error(err, 'Failed to start server');
    process.exit(1);
  }
}

start();
```

As of now there is no way that I can enforce the output schema when a client error happens.

```
$ curl -X GET http://localhost:3000/boom
{"error":{"code":"500","message":"handled: BOOM"}}
# adheres to the defined schema

$ curl -X GE http://localhost:3000/boom # typo in method name
{"error":"Bad Request","message":"Client Error","statusCode":400}
# does not adhere to the defined schema
```

**Comment by chiku** [comment]
@Eomm You have to run the following to get the output from the built-in client error handler.
```bash
curl -X GE http://localhost:3000/boom
```

Please note that the typo `GE`. This is what causes a client error.

**Comment by Eomm** [comment]
I didn't get it, thanks for the clarification

It seems legit to me as feature 👍

**Comment by mcollina** [comment]
> Providing a way to override the default clientError handler gives an opportunity to match the defined schema. 

I don't think that would be possible for the single route, but rather you could customize it for the whole server. Fastify routing works as a combination of path + domain, and schemas are associated with that. When the method is wrong, there is no route.

Anyway, a PR to make the clientError customizable would be nice.

**Comment by jsumners** [comment]
```js
fastify.decorateReply('error', function (error) {
  if (error.code === 500) {
    // do something
    return this.send(conformingResponse)
  }
  this.send(anotherConformingResponse)
})

fastify.get('/foo', (req, res) => {
  const error = new Error('boom!')
  error.code = 500
  return res.error(error)
})
```

**Comment by mcollina** [comment]
@jsumners despite this issue including a route, the problem we are talking about happens _before_ routing is done. We don't have an handler or anything.

**Comment by chiku** [comment]
I'll create a PR to make the client error handler configurable over the next few days.

**Comment by chiku** [comment]
I have created a PR https://github.com/fastify/fastify/pull/2249 to allow overriding the default `clientErrorHandler`.

**Comment by chiku** [comment]
Closed by https://github.com/fastify/fastify/pull/2249
