### ISSUE TITLE
preHandler not triggered on setNotFoundHandler

### ISSUE THREAD

**Issue by PierBover** [fastify/fastify#2228]
## 🐛 Bug Report

The [docs](https://www.fastify.io/docs/v1.14.x/Server/#setnotfoundhandler) on `setNotFoundHandler` say that:

> You can also register beforeHandler hook for the 404 handler.

But when you do this, Fastify issues a warning on the console that says:

> (node:92658) Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead

In any case neither the `beforeHandler` or `preHandler` hooks are being triggered when `setNotFoundHandler` is triggered.

I also tried with other hooks such as `onRequest` which aren't being triggered either, although it's not clear from the docs whether these would work or not.

## To Reproduce

```js
const fastify = require('fastify')({
	logger: true
});

fastify.setNotFoundHandler({
	preHandler: (request, reply, next) => {
		console.log('preHandler!');
		next();
	}
}, function (request, reply) {
	reply.status(404);
	reply.send();
});

fastify.listen(5555, '0.0.0.0', function (err, address) {
	if (err) {
		fastify.log.error(err)
		process.exit(1)
	}
	fastify.log.info(`server listening on ${address}`)
});
```

## Expected behavior

I imagine the `preHandler` or even the deprecated `beforeHandler` hook should be triggered. Not sure about other hooks.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by PierBover** [comment]
Jesus, I just noticed I was looking at the v1 docs... thank you Google.

Anyway [the current docs](https://www.fastify.io/docs/latest/Server/#setnotfoundhandler) specify the `preHandler` hook which isn't triggered.

**Comment by Eomm** [comment]
Your script actually works

```
{"level":30,"time":1587804750217,"pid":36644,"hostname":"EOMM-XPS","reqId":1,"req":{"method":"GET","url":"/asd","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":51699},"msg":"incoming request","v":1}
preHandler!
{"level":30,"time":1587804750281,"pid":36644,"hostname":"EOMM-XPS","reqId":1,"res":{"statusCode":404},"responseTime":58.75180101394653,"msg":"request completed","v":1}
```

**Comment by mcollina** [comment]
Is this a doc bug? Would you like to send a PR?

**Comment by delvedor** [comment]
I just tried as well your code and it works as expected:
```
▶ node index.js
{"level":30,"time":1587809583462,"pid":61053,"hostname":"Skadi.local","msg":"Server listening at http://0.0.0.0:5555","v":1}
{"level":30,"time":1587809583462,"pid":61053,"hostname":"Skadi.local","msg":"server listening on http://0.0.0.0:5555","v":1}
{"level":30,"time":1587809585633,"pid":61053,"hostname":"Skadi.local","reqId":1,"req":{"method":"GET","url":"/","hostname":"localhost:5555","remoteAddress":"127.0.0.1","remotePort":65327},"msg":"incoming request","v":1}
preHandler!
{"level":30,"time":1587809585640,"pid":61053,"hostname":"Skadi.local","reqId":1,"res":{"statusCode":404},"responseTime":6.37975600361824,"msg":"request completed","v":1}
```

```
▶ curl localhost:5555 -v
* Rebuilt URL to: localhost:5555/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5555 (#0)
> GET / HTTP/1.1
> Host: localhost:5555
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< content-length: 0
< Date: Sat, 25 Apr 2020 10:13:05 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

I'm using the latest version of Fastify `v2.13.1`.
Regarding the documentation, we should use only `preHandler`.

**Comment by PierBover** [comment]
Sorry guys.

It's true the script by itself works.

I started disabling custom hooks and plugins on my project and it turns out the issue happens when the `fastify-static` is used. Not sure if it's something I did wrong or a bug in that plugin.

I will investigate and open an issue on the plugin if needed.
