### ISSUE TITLE
Cannot get root schema to work from documentation

### ISSUE THREAD

**Issue by xeoneux** [fastify/fastify#2231]
## 🐛 Bug Report

After defining the schema and adding it through `fastify.addSchema`, the route method cannot read the defined schema

Example of what fails:
```js
  fastify.addSchema({
    $id: "CreateUser",
    properties: { name: { type: "string" } },
    required: ["name"],
    type: "object",
  });

  fastify.post(
    "/",
    { schema: { body: { $ref: "CreateUser#" } } },
    async (_req, reply) => {
      reply.send({});
    }
  );
```

## To Reproduce

https://github.com/xeoneux/fastify-root-schema-issue

## Expected behavior

It should read the root schema

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by Eomm** [comment]
That code works in `fastify@next` that we will release soon.

To let that code works in `v2` you need to provide a [new valid `$id`](https://www.fastify.io/docs/v2.13.x/Validation-and-Serialization/):

```
fastify.addSchema({
  $id: 'http://url.com/sh.json',
  properties: { name: { type: 'string' } },
  required: ['name'],
  type: 'object'
})

fastify.post(
  '/',
  { schema: { body: { $ref: 'http://url.com/sh.json#' } } },
  async (_req, reply) => {
    reply.send({})
  }
)
```

**Comment by xeoneux** [comment]
@Eomm  When I do that, I get 
```js
{ [Error: can't resolve reference http://url.com/sh.json# from id #]
  message:
   'can\'t resolve reference http://url.com/sh.json# from id #',
  missingRef: 'http://url.com/sh.json',
  missingSchema: 'http://url.com/sh.json' }
```

**Comment by Eomm** [comment]
Could you add a complete example?

I tried the code above and it work so it should be something else

**Comment by xeoneux** [comment]
It happens when I use the [fastify-response-validation](https://github.com/fastify/fastify-response-validation) plugin along

**Comment by Eomm** [comment]
Please, provide a complete example to reproduce.
I'm happy to help but building code from scratch **hoping** to reproduce your error it is a waste of time for me and for you.

For example, that plugin acts during serialization for `schema.response` not for validation input with `schema.body`.. for this reason, I don't want to guess the problem.

**Comment by xeoneux** [comment]
Hey @Eomm, thanks for all the help so far! I was trying to reproduce the error in the repo above and here's what I was doing: I was registering the response validation plugin BEFORE the routes and that's what caused these error messages. Placing it after the routes did the trick 😄 

Thank you!
