### ISSUE TITLE
error TS1259: Module '"/..../project/node_modules/fastify/fastify"' can only be default-imported using the 'esModuleInterop' flag

### ISSUE THREAD

**Issue by ProgrammingLife** [fastify/fastify#2238]
Installed fastify with: **npm i fastify --save**. Tried to execute a script from here: https://github.com/fastify/fastify/blob/master/examples/typescript-server.ts

Then I do:
```
$ tsc --init
message TS6071: Successfully created a tsconfig.json file.

$ cat tsconfig.json | grep inter
    "esModuleInterop": true, 

$ cat test.ts 
import fastify, { FastifyInstance, RouteShorthandOptions } from 'fastify';
```

run **tsc test.ts**:
> =test.ts:1:8 - error TS1259: Module '"/home/user/projects/node_modules/fastify/fastify"' can only be default-imported using the 'esModuleInterop' flag
> 1 import fastify, { FastifyInstance, RouteShorthandOptions } from 'fastify';
>          ~~~~~~~
>   ../../node_modules/fastify/fastify.d.ts:712:1
>     712 export = fastify;
>         ~~~~~~~~~~~~~~~~~
>     This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
> Found 1 error.

What do I do wrong?

- *node version*: 13
- *fastify version*: >=2.0.0
- *os*: Linux

**Comment by ProgrammingLife** [comment]
I've also tried this code:
```
import * as fastify from 'fastify';
import { Server, IncomingMessage, ServerResponse } from 'http';
const server: fastify.FastifyInstance <Server, IncomingMessage, ServerResponse> = fastify.default();
```

But now I get:

> error TS2339: Property 'default' does not exist on type '{ <HttpServer extends Server | Http2Server = Server, HttpRequest extends IncomingMessage | Http2ServerRequest = IncomingMessage, HttpResponse extends ServerResponse | Http2ServerResponse = ServerResponse>(opts?: ServerOptions): FastifyInstance<...>; (opts?: ServerOptionsAsHttp): FastifyInstance<...>; (opts?: ServerO...'.
> 5 const server: fastify.FastifyInstance <Server, IncomingMessage, ServerResponse> = fastify.default();
> Found 1 error.
>

**Comment by mcollina** [comment]
You are using v2, not v3 which that does refer to. Check out https://www.fastify.io/docs/v2.13.x/TypeScript/

**Comment by ProgrammingLife** [comment]
@mcollina Thanks, that works. But what to use, v2 or v3? Is v3 unstable?

**Comment by mcollina** [comment]
We are launching rc1 off v3 tomorrow.

**Comment by ProgrammingLife** [comment]
@mcollina Great! When will Fastify-cookie, Fasitify-multipart support Fastify v3?

**Comment by Ethan-Arrowood** [comment]
@ProgrammingLife there are already prs to update some of those plugins. Check out this matrix for more: https://github.com/fastify/fastify/issues/2217
