### ISSUE TITLE
Can't customize error message when statusCode is 500

### ISSUE THREAD

**Issue by franciscolourenco** [fastify/fastify#2246]
## 🐛 Bug Report

When setting the status code to 500 in any way, it is not possible to customise the error message.
Most other status codes (400, 501, etc.) works as expected. 

## To Reproduce

```js
module.exports = async function(fastify) {
	fastify.post('/', async function(request, reply) {
		reply.code(500)
		return new Error('Hello World') // responds  with default error message
	})
}
// OR
module.exports = async function(fastify) {
	fastify.post('/', async function(request, reply) {
		reply.code(500)
		throw new Error('Hello World') // responds  with default error message
	})
}
// OR
module.exports = async function(fastify) {
	fastify.post('/', async function(request, reply) {
		const error = new Error('Hello World')
		error.statusCode = 500
		throw error  // responds  with default error message
	})
}

```

## Expected behavior

The reply to the server should contain the customized error message

## Your Environment

- *node version*: v12.14.0
- *fastify version*: >=2.14.0
- *os*: Mac Catalina

**Comment by mcollina** [comment]
Can you please include a full example? What's your error handler?

**Comment by franciscolourenco** [comment]
It seems to be `fastify-sensible` fault. Opened a ticket there instead with full example. Closing this one?
