### ISSUE TITLE
Separate plugin registration options from options passed to plugin instance

### ISSUE THREAD

**Issue by tundrax** [fastify/fastify#225]
As you know Hapi uses two types of options while registering plugins, which I find very useful. 

1) `registrationOptions`: used by the framework while registering the plugin
2) `pluginOptions`: passed to the plugin instance while initializing

At first, this separation didn't make sense and was confusing to some point. After adopting `everything in plugins` approach in developing applications with Hapi, we can see real benefits of this.

1) the plugin can be reused multiple times within the same app, with varying `registrationOptions` or `pluginOptions` combinations
2) prevent future name collisions. eg.: `prefix` key

Set of `registrationOptions` may expand eventually. For example, `vhost` option along with `prefix` would by a nice thing to have. When you use subdomain `https://my.example.com` that points to the plugin, use prefix `/test` (like Stripe does) for further encapsulation.

**Comment by mcollina** [comment]
Thanks for reporting and kickstarting a discussion about this.

Fastify has a very different plugin system compared to Hapi, even if the API looks very similar. Plugins in Fastify are fully encapsulated, and there are multiple means to control scope in Fastify that simply are not possible in Hapi. A plugin in fastify can embed all its dependencies and be certain that those will not collide with others in other places of the codebase.

I'm not completely against this, but I would like to see how the ecosystem develop before making a decision. I see your point about the fact that adding registration config would be semver-major changes, but I do not expect to add many of those.

**Comment by tundrax** [comment]
@mcollina Thank you for clarifying your stance. I have to read fastify plugin system more thoroughly.

What about the `vhost` option for plugins, then devs can choose either `prefix` or `vhost` or both to scope the routes?

**Comment by mcollina** [comment]
vhost is not supported yet, if you want to send a PR, it would be a nice feature to have. However we recommend to so the same using a web server in front.
