### ISSUE TITLE
Ensure onClose hooks works well with asyncAwait

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2250]
## 🚀 Feature Proposal

We currently have no tests to verify that the following works:

```js
fastify.addHook('onClose', async (fastify) => {
  await client.end()
})
```

We should add tests and/or do a fix.

**Comment by jsumners** [comment]
I couldn't even find where we invoke the hook yesterday. I'm not even sure it gets invoked in two different contexts (cb or promise).

**Comment by Eomm** [comment]
Here the test file [close.test.js](https://github.com/fastify/fastify/blob/master/test/close.test.js)

It seems promises are not tested

**Comment by mcollina** [comment]
It’s provided by Avvio.

**Comment by adriancerejo** [comment]
Hi could I try and create a test/fix for this? I'm fairly new to contributing to open source so any guidance would be appreciated!

**Comment by ShogunPanda** [comment]
I was currently taking care of this, and I noticed this won't work properly until mcollina/avvio#110 is merged.

I already have a PR ready for this that will be sent once the issue above is fixed.

**Comment by Eomm** [comment]
Thanks for taking care of it!

Avvio has been released 👍

**Comment by mcollina** [comment]
I think this can be closed @Eomm
