### ISSUE TITLE
mehtod, url, not accesible on request

### ISSUE THREAD

**Issue by jacargentina** [fastify/fastify#2252]
## To Reproduce

```js
import Fastify from 'fastify';

const fastify = Fastify();
fastify.all('/:target', async (request, reply) => {
  const { params, body, method, url } = request;
  var method1 = request.raw.method;
  var url1 = request.raw.url;
  console.log('request', { method, url, method1, url1, params, body });
  reply.code(200).send({ ok: true });
});

fastify
  .listen(3030, '0.0.0.0')
  .then(address => console.log(`server listening on ${address}`))
  .catch(err => {
    console.log('Error starting server:', err);
    process.exit(1);
  });

```

Then do:

`curl http://localhost:3030/testing`

Output is currently this: 

```text
request {
  method: undefined,
  url: undefined,
  method1: 'GET',
  url1: '/testing',
  params: { target: 'testing' },
  body: null
}
```
## Expected behavior

`method` and `url` should be as docs say, ie. 

```text
request {
  method: 'GET',
  url: '/testing',
  method1: 'GET',
  url1: '/testing',
  params: { target: 'testing' },
  body: null
}
```

I 've put `method1` and `url1` just to show the raw values are there.

## Your Environment

- *node version*: 14, tried 12 too
- *fastify version*: 2.14.0
- *os*: Mac

**Comment by delvedor** [comment]
I fear this is a docs bug, you can access those properties in v3 but not in v2.
Doc page: https://www.fastify.io/docs/v2.14.x/Request/
Related: https://github.com/fastify/fastify/pull/2017

cc @lmammino

**Comment by imrishabh18** [comment]
Hey @delvedor , Can you guide me in fixing this bug. As I am new to this thing.

**Comment by delvedor** [comment]
Hello @imrishabh18, thank you for showing interest!
I fear this is a bug in our website, as the documentation in the repository is correct, isn’t it?

**Comment by imrishabh18** [comment]
Ohk, I just got confused with the documentation label.

**Comment by Eomm** [comment]
Looking the docs https://www.fastify.io/docs/v2.15.x/Request/ it seems fixed now

![image](https://user-images.githubusercontent.com/11404065/85789014-2a0b8c80-b72e-11ea-9069-0eccb0f6c3a2.png)

Thks for reporting
