### ISSUE TITLE
ERROR: read ECONNRESET at TLSWrap.onStreamRead

### ISSUE THREAD

**Issue by rtatarinov** [fastify/fastify#2253]
So, I found same issues, but it doesn't have any solution. And I don't understand why these issues closed? Therefore, I decided create new Issue. 

I have an app with docker, node, react and fastify. When I run my app in server it work around 12 hours. Then, I get next error:
``` js
{"level":30,"time":1588536784439,"pid":1,"hostname":"90b57fa33690","reqId":983,"res":{"statusCode":302},"responseTime":0.19920110702514648,"msg":"request completed","v":1}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
My server file:
```js
const redirect = require('fastify')({
  logger: true,
});

const path = require('path');
const fs = require('fs');

const fastify = require('fastify')({
  logger: true,
  http2: true,
  https: {
    cert: fs.readFileSync('somebody.crt', 'utf8'),
    key: fs.readFileSync('somebody.key', 'utf8'),
  },
});

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'build'),
});

fastify.get('/', function (req, reply) {
  reply.sendFile('index.html', path.join(__dirname, 'build'));
});

fastify.get('/env.js', function (req, reply) {
  reply
    .header('Content-Type', 'application/javascript; charset=utf-8')
    .send(`window.__TEACH_ME_CONFIG__ = ${JSON.stringify(require('./env'))};`);
});

fastify.setNotFoundHandler(function (request, reply) {
  reply.sendFile('index.html', path.join(__dirname, 'build'));
});

redirect.all('/*', (req, res) => {
  res.redirect(`https://${req.hostname}${req.req.url}`);
});

redirect.listen(80, '0.0.0.0');

fastify.listen(443, '0.0.0.0', function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }

  fastify.log.info(`server listening on ${address}`);
});
```
I used node version 10.16-alpine

My Dockerfile:
```ruby
FROM node:10-alpine AS build
WORKDIR /app
COPY . .
RUN yarn install --non-interactive && yarn build

FROM node:10.16-alpine
WORKDIR /app
COPY --from=build /app/build ./build
COPY --from=build /app/server.js .
ENV NODE_ENV=production
RUN yarn add fastify && yarn add fastify-static

EXPOSE 80 443
CMD ["node", "server.js"]
```
Dependence:
```
"fastify": "^2.13.1",
"fastify-static": "^2.6.0",
```
My app it is collection of static files. And I try start easy server with ability of redirect. But it work only 12-15 hours, then error.. And I need to run container again.

**Comment by mcollina** [comment]
What issues are you referring to?

**Comment by rtatarinov** [comment]
@mcollina I wrote about problem above. I get server error

**Comment by mcollina** [comment]
Can you please check with the latest Node 12, and possibly with Node 14? There have been a few changes to http2 there.

**Comment by mcollina** [comment]
@ronag @jasnell @addaleax do you know where that ECONNRESET could came from? I have a feeling we are missing an `on('error'` handler somewhere, I just can't figure out where.

**Comment by rtatarinov** [comment]
So, if I  will try node:12-alpine and I will report the result.

**Comment by ronag** [comment]
I will try to dig into this sometime this week.

**Comment by rtatarinov** [comment]
So, I have same error with node 12
```js
{"level":30,"time":1588773240398,"pid":1,"hostname":"4524d782613c","reqId":12,"res":{"statusCode":302},"responseTime":0.26003599166870117,"msg":"request completed","v":1}
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by ronag** [comment]
Can you try v12.16.2

**Comment by ronag** [comment]
I assume this happens on http2?

**Comment by mcollina** [comment]
> I assume this happens on http2?

This is http2 related, yes.

**Comment by ShogunPanda** [comment]
This might also be related to https://github.com/fastify/fastify/issues/2036#issuecomment-625677400 and https://github.com/nodejs/node/issues/33302

**Comment by rtatarinov** [comment]
I have same problem with node 12.16.3. Could you help me with this problem?

**Comment by ronag** [comment]
@mcollina: Would it be possible to use async hooks to get the stack from the point where `destroy` was invoked for these kind of errors? Would make these things easier to debug.

**Comment by ronag** [comment]
As far as I can see the only path where we don't register an error handler is https://github.com/nodejs/node/blob/master/lib/internal/http2/core.js#L2838. But I'm sceptical whether that is relevant in this case...

**Comment by ronag** [comment]
@rtatarinov can you try node v14 as well? We did some change to how errors are propagated from stream_base_commons which might make a difference.

**Comment by rtatarinov** [comment]
So, I seem I found problem, It's problem only `alpine` version. I use node 12.16.3 and it's work 3 days already without errors) I think, I will close this issue, because this problem resolved for me.
