### ISSUE TITLE
`started` flag for fastify no longer set in v3 on ready()

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#2259]
## 🐛 Bug Report

In v3 running `fastify.ready()` no longer sets `fastify[kState].started` to `true`. This results in `lightMyRequest` Chain returned for a builder to be wrapped into a Promise and prematurely resolved, failing with an error.

## To Reproduce

https://github.com/fastify/fastify/pull/2257/files

## Expected behavior

Same code would work in v2. Since this is not listed as a breaking change in migration guide, I assume this is a regression rather than removal of deprecated feature.

## Your Environment

- *node version*: 12
- *fastify version*: 3.0.0-rc1

**Comment by kibertoad** [comment]
@mcollina I would be happy to work on a fix if you could point me in the right direction. I don't see anything firing a `start` event inside `fastify` itself, so I assume this is a regression inside `avvio`.

**Comment by mcollina** [comment]
Wow, you found a nice regression. 

The problem is that the chainable inject() never worked if the server was not started.

I think the solution is to change those two lines https://github.com/fastify/fastify/blob/master/fastify.js#L336-L337

so that we call `ready()` inside the http handler, like so:

```js
return lightMyRequest((req, res) => {
  this.ready(function (err) {
    // figure out what to do with err, we should forward it to lightMyRequest somehow
     httpHandler(req, res)
  })
}, opts)
```

**Comment by kibertoad** [comment]
@Eomm Any ideas how err case should be handled? Simply throwing it doesn't seem to be a correct solution, it breaks three tests.

**Comment by mcollina** [comment]
You should be ok in doing `res.emit('error', err)`.

**Comment by mcollina** [comment]
```
return lightMyRequest((req, res) => {
  this.ready(function (err) {
     if (err) {
        res.emit('error', err)
        return
    }
     httpHandler(req, res)
  })
}, opts)
```

**Comment by kibertoad** [comment]
@mcollina 
```
    if (cb) {
      this.ready(err => {
        if (err) cb(err, null)
        else lightMyRequest(httpHandler, opts, cb)
      })
    } else {
      return lightMyRequest((req, res) => {
        this.ready(function (err) {
          if (err) {
            res.emit('error', err)
            return
          }
          httpHandler(req, res)
        })
      }, opts)
    }
```

This fails with `Error: ERR_AVVIO_READY_TIMEOUT: plugin did not start in time`. Am I missing some step that should signal init being completed successfully?

**Comment by kibertoad** [comment]
@mcollina Did some experiments, so it only timeouts if this code is invoked prior to calling `inject()`:

```js
  const startPromise = new Promise((resolve, reject) => {
    fastify.ready((err, res) => {
      if (err) {
        return reject(err)
      }
      resolve()
    })
  })
```

Obviously I can just remove it, but is the behaviour correct? Shouldn't it work if app was readied previously?

**Comment by mcollina** [comment]
> This fails with Error: ERR_AVVIO_READY_TIMEOUT: plugin did not start in time. Am I missing some step that should signal init being completed successfully?

What fails with this?

**Comment by mcollina** [comment]
(please push your solution)

**Comment by kibertoad** [comment]
@mcollina Looks like I was doing something wrong with callback-style ready() initialization. Switched to promise style and it works now. Fill cleanup PR now.
