### ISSUE TITLE
Remove absolute URL

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#2265]
In our docs, there are some link that refers to `master`

Like https://raw.githubusercontent.com/fastify/fastify/master/docs/Server.md
```
<a href="https://github.com/fastify/fastify/blob/master/docs/Server.md"><code><b>Fastify server</b></code></a>
```

I think we should update all those links to relative ones because if a user browsers old tag in GitHub, he would redirect to `master` causing confusion.

Kudos to @lmammino because the fastify.io site already applies this fix 🙌🏻

----

EDIT checklist of files to fix

- [x] README.md
- [ ] docs\ContentTypeParser.md
- [ ] docs\Errors.md
- [ ] docs\Fluent-Schema.md
- [ ] docs\Getting-Started.md
- [ ] docs\Hooks.md
- [ ] docs\Logging.md
- [ ] docs\Middleware.md
- [ ] docs\Migration-Guide-V3.md
- [ ] docs\Plugins-Guide.md
- [ ] docs\Plugins.md
- [ ] docs\Reply.md
- [ ] docs\Request.md
- [ ] docs\Routes.md
- [x] docs\Server.md
- [ ] docs\TypeScript.md
- [ ] docs\Validation-and-Serialization.md
- [ ] docs\Write-Plugin.md

**Comment by adriancerejo** [comment]
Hey can I try to fix this issue?

**Comment by Eomm** [comment]
Yes go for it! 

it should be needed only "./Server.md" as example

**Comment by Eomm** [comment]
Updated first post with files checklist

**Comment by ivandevp** [comment]
Can I help with the update in main `README.md`?

**Comment by mcollina** [comment]
Sure, go ahead!

**Comment by joobisb** [comment]
@Eomm @mcollina 
i've raised PR for the rest of the pending docs..seems like build is failing could you please help me to figure this out

**Comment by mcollina** [comment]
It’s done
