### ISSUE TITLE
Failed building the schema for ONLY RESPONSE. due error Cannot find reference 'definitions'

### ISSUE THREAD

**Issue by patarapolw** [fastify/fastify#2281]
## 🐛 Bug Report

Failed building the schema for ONLY RESPONSE. due error Cannot find reference 'definitions'

## To Reproduce

This works

```js
    schema: {
      querystring: {
        type: 'object',
        properties: {
          test: {
            $ref: 'schema.json#/definitions/RenderItemMin'
          }
        }
      },
    },
```

But not this,

```ts
    schema: {
      response: {
        200: {
          $ref: 'schema.json#/definitions/RenderItemMin'
        }
      }
    },
```

## Expected behavior

Should work without errors.

## Your Environment

- *node version*: 12
- *fastify version*: 2.14.1
- *os*: macOS Catalina

**Comment by Eomm** [comment]
Please, provide a minimal reproducible example with the issue or we are unable to help you

**Comment by patarapolw** [comment]
Tried, but cannot reproduce with [minimal repo](https://github.com/patarapolw/ts-openapi-fastify). Still,

- I have found new problem with `fastify-oas`, regarding $ref in RESPONSE.
- Problem still persists in the main repo; but I can escape with [$RefParser](https://github.com/APIDevTools/json-schema-ref-parser)

```ts
      response: {
        // 200: (await $RefParser.dereference(schema as any)).definitions!.QueryItem
      }
```

**Comment by mcollina** [comment]
Closing, this is a fastify-oas bug.

cc @Skella
