### ISSUE TITLE
fastify.setErrorHandler  is not working.

### ISSUE THREAD

**Issue by bln7** [fastify/fastify#2282]
## 💥 Regression Report

fastify.setErrorHandler  is not working.

## Last working version

That's my first version. I'm new guy here.

## To Reproduce

```js
fastify.setErrorHandler((error, request, reply) => {
    reply.send(`Internal Server Error - ${error}`);
})

fastify.get('/err', async (req,reply) =>{
    return new Error('my error!')
})
```

## Expected behavior

didn't catch the Error

```js
{
"statusCode":500,
"error":"Internal Server Error",
"message":"Something went wrong"
}
```

## Your Environment

- *node version*: 10, 16, 0
- *fastify version*: >=2.0.0
- *os*:Windows

**Comment by Eomm** [comment]
I think you have fastify-sensible installed, if so, you should register it like this 

```
fastify.register(require('fastify-sensible'), { errorHandler: false } )
```

Because it is hiding your error handler.

Moreover, you should throw error `throw new Error('my error!')` in async functions

**Comment by tj-commits** [comment]
@stale no

**Comment by tj-commits** [comment]
@Eomm 
nope

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
