### ISSUE TITLE
EC2 Hosting

### ISSUE THREAD

**Issue by sarfarazengglb** [fastify/fastify#2285]
## 🐛 Bug Report

I have hosted Simple Fastify App running on port 3000 in EC2 server it is working fine within server.However it is not accessible from Outside.All the Port are open and Security Group Configured properly.To verify i hosted sample nodejs app with same port in express it was working fine and Website was avaliable from outside at port 3000
## To Reproduce

1)Spin ec2 server
2)install node
3)make demo.js with below code

// Require the framework and instantiate it
const fastify = require('fastify')({ logger: true })

// Declare a route
fastify.get('/', async (request, reply) => {
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
4)Run the demo.js
5)curl http://localhost:3000 -PASS
6)curl http://{{YOUR_PUBLIC_IP}:3000 - FAIL

EXPRESS APP WORKING IN SAME SETUP
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))

## Expected behavior

It should work outside the ec2

## Your Environment

[ec2-user@ip-XXXXX]$ node --version
v12.16.3

+ fastify@2.14.1

- EC2
Linux  x86_64 x86_64 x86_64 GNU/Linux

**Comment by Eomm** [comment]
You need to specify `0.0.0.0` https://github.com/fastify/fastify/blob/master/docs/Server.md#listen

**Comment by sarfarazengglb** [comment]
Thank you for your response.It was mistake from my side.

The above examples, and subsequent examples in this document, default to listening only on the localhost 127.0.0.1 interface. To listen on all available IPv4 interfaces the example should be modified to listen on 0.0.0.0 like so:

fastify.listen(3000, '0.0.0.0', function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
Similarly, specify ::1 to accept only local connections via IPv6. Or specify :: to accept connections on all IPv6 addresses, and, if the operating system supports it, also on all IPv4 addresses.

When deploying to a Docker (or other type of) container using 0.0.0.0 or :: would be the easiest method for exposing the application.

**Comment by Creative-Difficulty** [comment]
Updated solution:  
```js
fastify.listen({ port: 3000 }, "0.0.0.0")
```
