### ISSUE TITLE
Add `preRouting` hook to allow URL rewriting

### ISSUE THREAD

**Issue by digitalmio** [fastify/fastify#2287]
## 🚀 Feature Proposal

Add `preRouting` hook in order to modify the original Node req.url object. This will allow to create route rewrite.

## Motivation

Discussed on the `find-my-way` repo: https://github.com/delvedor/find-my-way/issues/150
This hook will allow to change native `req.url` object and in the long run, rewrite URLs. This is technique used in Express. Example middleware: https://github.com/kapouer/express-urlrewrite
Currently, all the hooks are happing too late, so change of the `url` object brings no value.

## Example

Please provide an example for how this feature would be used.
```
fastify.addHook('preRouting', (request, reply, done) => {
   // some code
  req.url = newUrl;
  done();
});
```

**Comment by mcollina** [comment]
Unfortunately it will not be possible to add it as a hook, but rather something like:

```js
const app = Fastify({
  rewriteUrl (req) {
    return "/hello"
  }
})
```

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/2290.
