### ISSUE TITLE
Possible type regression from v2 to v3

### ISSUE THREAD

**Issue by robcresswell** [fastify/fastify#2288]
## 💥 Regression Report

It appears that the type definition for route handlers (`RouteHandlerMethod` in v3) no longer has a binding for `this`. I may be entirely misunderstanding the new types though; the abundance of generics is quite clever, but a little hard to quickly grasp.

## Last working version

Worked up to version: 2.14.1

Stopped working in version: 3.0.0-rc.2

## To Reproduce

This is not strictly correct code, but it should illustrate the point: 

Steps to reproduce the behaviour

In the following file, `this` produces an error

```ts
export const handler: RouteHandlerMethod = async function(req, reply) {
  const id = req.params.id;

  this.log({ id }, 'User deleted')

  reply.code(204).send();
}
```

The error is:

```
'this' implicitly has type 'any' because it does not have a type annotation.ts(2683)
```

## Expected behavior

I'd expect this to work as it did in v2, where I used the `RequestHandler` interface, which seems to have been replaced by `RouteHandlerMethod` ?

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Linux

**Comment by robcresswell** [comment]
Please let me know if I've been unclear or missed anything; or indeed if you have any recommendations on improving what I've done! I've grown fond of centralising my route definitions and then putting the handlers in separate files, which results in the code above.

And finally, thanks so much for the work on Fastify and v3! Aside from the above bug, it cleared up all the minor issues I had with v2, and I'm a huge fan.

**Comment by mcollina** [comment]
We are glad to ear!

**Comment by Ethan-Arrowood** [comment]
Can we verify this was fixed in #2290? @robcresswell can you try with the latest release candidate?

**Comment by robcresswell** [comment]
@Ethan-Arrowood Will do! Should have time later this evening

**Comment by robcresswell** [comment]
@Ethan-Arrowood Yep, seems to have worked! Worth noting it wasn't part of rc3; that was cut without #2290, but running against master its fixed. Thanks!

**Comment by Ethan-Arrowood** [comment]
Sounds good @robcresswell it'll be included in rc4 and the eventual v3 
Thank you!
