### ISSUE TITLE
TS logger options

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify#2289]
## 🐛 Bug Report

Documentation at https://github.com/fastify/fastify/blob/master/docs/TypeScript.md recommends passing pino.Logger as template parameter when constructing fastify instance. I think it should be pino.LoggerOptions, because the former resolves to "BaseLogger" in which "redact" and other fields are missing.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests for the example.

**Comment by zmeyc** [comment]
Do you mean to add an example using @types/pino with more complex logger config (to /examples) + unit test for it?

**Comment by mcollina** [comment]
That'd be perfect. It might just be in the docs.

**Comment by Ethan-Arrowood** [comment]
@mcollina a unit test for this would require adding the pino types to dev deps. Is that okay? If so then i'm +1 for adding a test for pino types

**Comment by mcollina** [comment]
Yes, exactly. I’m ok in having them as devDeps

**Comment by zmeyc** [comment]
I need help with this, I tried:
```
const server: FastifyInstance<
  Server,
  IncomingMessage,
  ServerResponse
> = fastify();
server.log.info("Test")
```
Then run it with:
```
npx ts-node examples/typescript-server.ts
```
This works. Then I add empty dictionary to fastify():
```
> = fastify({});
```
And getting type errors:
```
⨯ Unable to compile TypeScript:
examples/typescript-server.ts:24:12 - error TS2339:
Property 'info' does not exist on type 'FastifyLoggerOptions<Server, IncomingMessage, ServerResponse>'.

24 server.log.info("Test")
```
Now fastify.log is FastifyLoggerOptions and not logger instance.

Same problem when passnig pino.LoggerOptions. fastify.log becomes pino.LoggerOptions.

From JS code it looks like the internal logic is: if parameter contains an object with a set of functions ` ['info', 'error', 'debug', 'fatal', 'warn', 'trace', 'child']` then it's a pre-configured logger instance, otherwise it's a configuration object which will be passed to new pino instance.

I'm not sure how to reflect this in types and it's very confusing to reuse this field in such a way imo, it breaks single-responsibility principle. Maybe it's not late to split it into 2 different fields, i.e. logger and it's configuration?

**Comment by zmeyc** [comment]
In other words,  it's currently not possible to pass options to built-in pino:

This works:
```
const server: FastifyInstance<
  Server,
  IncomingMessage,
  ServerResponse,
  pino.Logger
> = fastify({
  logger: pino({})
})
fastify.log.info("test")
```
This doesn't (both with default 4th template arg or with pino.LoggerOptions)):
```
const server: FastifyInstance<
  Server,
  IncomingMessage,
  ServerResponse
> = fastify({
  logger: {}
})
fastify.log.info("test") // Type error
```

**Comment by Ethan-Arrowood** [comment]
From [example 5](https://www.fastify.io/docs/master/TypeScript/#fastify) of the fastify function typescript docs you should be able to set pino options like so:

```ts
import fastify from 'fastify'
import http from 'http'
import pino from 'pino'

const server = fastify<http.Server, http.IncomingMessage, http.ServerResponse, pino.Logger>({
  logger: {
    messageKey: 'message'
  }
})

server.get('/', async (request, reply) => {
  server.log.info('log message')
  return 'another message'
})
```

**Comment by Ethan-Arrowood** [comment]
If this is broken please let me know so we can fix

**Comment by zmeyc** [comment]
@Ethan-Arrowood The example above works.

The one below doesn't work (because it types fastify.log with configuration object):
```
import fastify, { FastifyInstance } from './fastify'
import * as http from 'http'

const server: FastifyInstance<http.Server, http.IncomingMessage, http.ServerResponse> = fastify({
  logger: {
    messageKey: 'message'
  }
});

server.get('/', async (request, reply) => {
  server.log.info('log message')
  return 'another message'
})
```

```
bug3.ts:11:14 - error TS2339: Property 'info' does not exist on type 'FastifyLoggerOptions<Server, IncomingMessage, ServerResponse>'.

11   server.log.info('log message')
```

**Comment by Ethan-Arrowood** [comment]
Yes this is by design. If you don't specify the logger generic you only can set logger options available to default fastify: https://github.com/fastify/fastify/blob/8b8485ac5ff56d1ead387f6dd76384f996a2cf8e/types/logger.d.ts#L30

If `messageKey` or anything else is missing from that base option interface then we need to fix that.

If this is a custom property that you want to add you'll want to use declaration merging to overload the existing logger option interface with whatever custom types you want

**Comment by zmeyc** [comment]
@Ethan-Arrowood I understand, but the problem is you can't call server.log.info() after this, because server.log becomes FastifyLoggerOptions object (without info() etc).

**Comment by Ethan-Arrowood** [comment]
Based on the tests: https://github.com/fastify/fastify/blob/master/test/types/logger.test-d.ts

You pass in the interface to that generic to be able to call those methods. I see how this can be confusing. Definitely better docs are required here, but also like you said maybe we should look at how the core logging works in fastify (regardless of typescript). Maybe the type definitions can be improved here.

**Comment by Ethan-Arrowood** [comment]
I do remember writing the types for this being difficult. Are you interested in helping solve this @zmeyc ?

**Comment by zmeyc** [comment]
@Ethan-Arrowood  I am, but I don't fully understand how to fix this.

```
expectType<FastifyLoggerOptions>(fastify().log)
```

Imo this check is not correct, log should always be FastifyLoggerInstance.
JS code checks if options are passed in `logger` field and constructs logger instance, otherwise it uses the passed logger instance 'as is'. So fastify().log should always be logger instance and never contain original options. Is my understanding correct?

**Comment by zmeyc** [comment]
Imo cleaner solution is splitting logger into two fields, but this is a breaking change:
1) 'logger' field to pass custom logger instance to replace built-in pino. 4th template parameter should have type of this logger (i.e. FastifyLoggerInstance by default, can be overridden to be pino.Logger).
2) 'loggerOptions' field of type FastifyLoggerOptions to override built-in pino options (if `logger` is not used).

**Comment by Ethan-Arrowood** [comment]
These are great. Thank you! I think the solution you identified is correct, but I'll look at the source code to be certain. 

@fastify/core Read @zmeyc last comment. Regardless of the typescript issue (which we can solve) do y'all have any input on the proposed decoupling of the logger option? If there is a reason why it is the way it is that is useful information as well! Might be worth documenting

**Comment by Ethan-Arrowood** [comment]
In the mean time can you send a PR that updates that type and the corresponding tests too @zmeyc ? Would be good to also include the pino test at that time if you can

**Comment by mcollina** [comment]
I don't understand the question :(. If it's asking to change the relationship between Fastify and Pino, I think it's really ok as it is right now. It helps people and it enables folks to pass some of the logger options down. I concur it relies on duck typing and opaque payloads.

I'm totally fine if this does not apply to TypeScript users, as trying to support duck typing and opaque payloads seems to be really hard there.
I'm not really a fan of changing APIs to accomodate lack of flexibility on the TypeScript side - otherwise Fastify would not be possible in the first place.

**Comment by zmeyc** [comment]
@Ethan-Arrowood PR ready. I didn't add support for augmenting built-in logger's options with 'pino.LoggerOptions', imo benefit is not worth added complexity of typings (and it breaks encapsulation), it's probably better to add more fields to FastifyLoggerOptions in the future.

https://github.com/fastify/fastify/pull/2297

Btw, you did an awesome job with these typings! Interesting idea with generic constraining.

**Comment by Ethan-Arrowood** [comment]
Thank you! Taking a look at both of your PRs this morning. Sorry it is not sooner, spent some time away from coding this weekend 😁
