### ISSUE TITLE
Asynchronous local storage support

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#2298]
## 🚀 Feature Proposal

Support for AsyncLocalStorage via an official plugin. If user enables this functionality, then fastify will automatically create ALS scope for every new request that could be populated within standard hooks.

## Motivation

Certain cross-cutting functionality (logging, monitoring, authentication) benefits from threadlocal-like functionality.

`cls-hooked` can be used as a fallback solution for older Node versions.

## Example

```
fastify.register(require('fastify-als'))

fastify.addHook('onRequest', (req, reply, done) => {
  fastify.setLocal('user', { id: 'fastifyUser' })
});

fastify.get('/', async (request, reply) => {
    return {
        user: fastify.getLocal('user')
    }
});

```

There is prior art already: https://github.com/thorough-developer/fastify-http-context
Maybe it could be used as a basis for an official plugin, or made an official plugin.

I can work on implementing this if approved.

**Comment by mcollina** [comment]
I think having an official module would be good. I would not put it inside the framework as it will slow things down significantly.

https://github.com/thorough-developer/fastify-http-context is an example of such integration.

**Comment by kibertoad** [comment]
@mcollina Considering that https://github.com/thorough-developer/fastify-http-context already exists, what could I contribute from my side to push forward the idea of having an official module?

**Comment by mcollina** [comment]
@thorough-developer wdyt?

cc @jsumners @delvedor @davidmarkclements ?

**Comment by jsumners** [comment]
🤷‍♂️ 

I haven't invested any time to research the API. It seems primarily targeted at things like OpenTelemetry. I have no opinion of a module for this.

**Comment by kibertoad** [comment]
@mcollina Since there is no response from @thorough-developer, I went ahead and built a somewhat more idiomatic fastify plugin using decoration instead of explicit context export: https://github.com/kibertoad/fastify-request-context

If there is interest, I am open to contributing it to `fastify` umbrella, but it would be great to get a review first.

(and I still need to write proper documentation and examples, I'll get to that this week).

**Comment by jsumners** [comment]
It being written in TypeScript, I will vote against it being added to the org. In my opinion, everything in the org should be JavaScript.

**Comment by kibertoad** [comment]
@jsumners It's a very small amount of code, I am perfectly fine to rewrite it in JavaScript if that's the only thing preventing it from being adopted to org.

**Comment by kibertoad** [comment]
@jsumners Aaaaand it's done. Project was fully converted to JavaScript.

**Comment by mcollina** [comment]
@kibertoad can you add some docs on how that would be used?

https://github.com/kibertoad/fastify-request-context/blob/b7e443bcff6d2008272ff73479fbd0d61c861d5e/test/requestContextPlugin.spec.js#L23-L25 would need to be fixed as `new Promise(async` leads to infinite amount of bugs and should not be promoted.

**Comment by kibertoad** [comment]
@mcollina Yup, coming up next, just ran out of time.
Does the comment about `new Promise(async` apply to tests as well? In either case, I do need to rewrite it not to use `await` to make tests runnable in Node 6, now that TS transpilation is out, either way, though.

**Comment by jsumners** [comment]
> In either case, I do need to rewrite it not to use `await` to make tests runnable in Node 6, now that TS transpilation is out, either way, though.

Given that the plugin states it supports Fastify v2, and the discussion is about bringing the module into the org, I'd say yes.

**Comment by mcollina** [comment]
> Does the comment about new Promise(async apply to tests as well? In either case, I do need to rewrite it not to use await to make tests runnable in Node 6, now that TS transpilation is out, either way, though.

`new Promise(async fn)` does not do what you think does. if the fn throws, the error goes to unhandled rejection. This is bad in the module and bad in the tests as well.

**Comment by kibertoad** [comment]
@jsumners @mcollina Rewrote tests to rely just on native promises, added Node 6 to the test matrix.

Next stop: documentation. Is anything else needed?

**Comment by jsumners** [comment]
Not that I'm aware of.

**Comment by kibertoad** [comment]
@mcollina Documentation added. I believe plugin is fully prepared for the inclusion into the org.

**Comment by mcollina** [comment]
@kibertoad I've invited you to the org,can you please move the repo? Also, can you add me on npm so I can add it there as well?

**Comment by kibertoad** [comment]
@mcollina Done!
