### ISSUE TITLE
ES modules support

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2301]
With Node.js `v12.17.0` ES modules are out without the flag (even if they are still experimental).
Fastify should support ES modules as well while keeping the CJS syntax.

Related: https://nodejs.org/en/blog/release/v12.17.0/

**Comment by mcollina** [comment]
We only export a function as default. There is _nothing_ that we should do. Quite notably, https://github.com/fastify/fastify-autoload/pull/76 needs a review.

**Comment by Ethan-Arrowood** [comment]
Our exports changed a little bit in v3. We still only export a function, but we export it as default and under the `fastify` property too

https://github.com/fastify/fastify/blob/12daa3c98340ba79d6e4a3041362eca6b22b5e82/fastify.js#L606

Does this have any impact?

**Comment by mcollina** [comment]
Not really for me.
We might introduce an exports property in package.json to handle accessing fastify through a named property.. but I would not know what would be the advantage.

**Comment by jsumners** [comment]
I vote leaving it alone. The feature is still experimental and getting it wrong will lead to a mess.

**Comment by fox1t** [comment]
PR: https://github.com/fastify/fastify/pull/2480

**Comment by o-t-w** [comment]
A whole year later, ES Modules are no longer experimental. Can this be reconsidered now? As somebody from a frontend background I have been writing all my Node code with ESM imports and it does seem like that is where all Node code is heading.

**Comment by mcollina** [comment]
You can use ESM modules with Fastify, it's all supported and this issue can be closed.
