### ISSUE TITLE
Wrong context inside the error handler

### ISSUE THREAD

**Issue by greguz** [fastify/fastify#2304]
## 💥 Regression Report

The binding to the Fastify instance is no longer accessible inside the error handler without a manual `.bind()` call.

## Last working version

Worked up to version: X.X.X (not sure at the moment)

Stopped working in version: 2.14.1

## To Reproduce

```js
const fastify = require('fastify')

function errorHandler(error, request, reply) {
  this.log.error('oh no', error)
  reply.status(500).send()
}

const app = fastify()
app.setErrorHandler(errorHandler)
app.get('/test', async function () {
  throw new Error()
})
app.listen(3000)
```

And request `/test`.

```
(node:2356) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at errorHandler (/home/greguz/dev/evologi/orderpod-backend/z.js:4:12)
    at handleError (/home/greguz/dev/evologi/orderpod-backend/node_modules/fastify/lib/reply.js:465:18)
    at onErrorHook (/home/greguz/dev/evologi/orderpod-backend/node_modules/fastify/lib/reply.js:437:5)
    at _Reply.Reply.send (/home/greguz/dev/evologi/orderpod-backend/node_modules/fastify/lib/reply.js:111:5)
    at /home/greguz/dev/evologi/orderpod-backend/node_modules/fastify/lib/wrapThenable.js:43:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior

The fastify instance is accessible inside the error handler.

## Your Environment

- *node version*: 12.16.2
- *fastify version*: 2.14.1
- *os*: Linux

**Comment by jsumners** [comment]
If you do not supply a fat arrow function for the handler?

**Comment by greguz** [comment]
Redid the test using an `async` function, same result. Just updated the example code.

**Comment by Eomm** [comment]
Could you check the version where it works?

Tried on fastify@2.12.0 and it is failing as well

**Comment by greguz** [comment]
I've tried any minor version down to the 1.9, and I can confirm that this behavior is consistent between all versions. So, in conclusion, this is not a regression, and I'm not sure if the Fastify instance is intended to be accessible inside the error handler.

**Comment by mcollina** [comment]
It would be to support this. Would you like to send a PR?

**Comment by greguz** [comment]
> It would be nice to support this. Would you like to send a PR?

Sure.

**Comment by greguz** [comment]
Both [merge](https://github.com/fastify/fastify/pull/2305) [requests](https://github.com/fastify/fastify/pull/2306) are now merged. I'm closing this issue. Thanks everyone.

**Comment by miwnwski** [comment]
Am I the only that still have this issue, even post upgrade to v3.5?

**Comment by kibertoad** [comment]
@miwnwski Can you share a minimum reproduction code?

**Comment by miwnwski** [comment]
@kibertoad sure, sorry, I just assumed OPs would suffice.

```js
'use strict'

const http = require('http')
const fastify = require('fastify')

if (!module.parent) {
  index().then(async () => {
    http.get({ hostname: 'localhost', port: 8000, path: '/' }, () => {})
  })
}

async function index () {
  const app = fastify()
  app.setErrorHandler(errorHandler)
  app.get('/', async function (request, reply) {
    throw new Error()
  })

  await app.ready()
  await app.listen(8000)
}

async function errorHandler (err, request, reply) {
  console.log('not expecting undefined: ', typeof this) // -> undefined
}
```

**Comment by miwnwski** [comment]
Was the fix only merged for v2 maybe? I haven't really dug through the source, wanted to know if this was intended or not for fastify v3.x.

**Comment by mcollina** [comment]
Can you send a PR for v3?
