### ISSUE TITLE
Logging errors to external service

### ISSUE THREAD

**Issue by robinvdvleuten** [fastify/fastify#231]
I've read the documentation a couple of times, but I can't figure out how to properly handle any error monitoring in your application. I would like to send them to [Sentry](https://docs.sentry.io/clients/javascript/) for example. Do you maybe have any starting point to look at?

**Comment by jsumners** [comment]
Well, the easiest way would be to use a Pino transport (http://getpino.io/#/?id=transports). But if that is unacceptable then I would pass in a preconfigured Pino instance, via the `logger` option, to Fastify. That logger instance would be configured with a custom stream that does whatever you would like. It could also be an instance of `pino-multi-stream` (https://www.npmjs.com/package/pino-multi-stream). 

Hopefully this answers your question.

**Comment by robinvdvleuten** [comment]
Thanks for your explanation! So if I understand correctly; I create an additional stream which listens for any logged errors and the rest of the logging can be piped to pino as normal?

**Comment by jsumners** [comment]
@robinvdvleuten please read http://getpino.io/#/docs/transports .

Logs are written to `stdout` by default. So your process's `stdout` can be piped into some other process that will deal with the logs in whatever way you desire. There are already several transports that process logs in various ways, e.g. `pino-syslog` to transform the JSON logs into traditional syslog lines.

The other method, supplying an alternate stream, would not be an _additional_ stream. It would replace the default stream to `stdout`.

**Comment by mcollina** [comment]
C
