### ISSUE TITLE
res.sent inconsistency.

### ISSUE THREAD

**Issue by Pruxis** [fastify/fastify#2313]
## 🐛 Bug Report

When having a long running process on an API call and completing the response immediatly, then inside the errorHandler res.sent is false when the response has already been sent.

## To Reproduce

```js
 server.get((_, res) => {
  res.send();
  console.log(res.sent) // true;
  throw new Error('Test')
});
  server.setErrorHandler((error, req, res) => {
    console.log(res.sent) // false;
    if (!res.sent) res.status(500).send();
  });
```

## Expected behavior

res.sent should be true in errorHandler.

## Your Environment

- *node version*: 12.14.0
- *fastify version*: >=2.14.1
- *os*: Mac

**Comment by mcollina** [comment]
I think the bug is even worse than .sent being false. The problem in your code is that re.send() should be the last action in your function.

the error handler purpose is to send a response when when one is not sent. Given your snippet, we might not even want to go there.

**Comment by Pruxis** [comment]
Why should it be the last invocation? Ofcourse it's solvable by wrapping the content of the remaining handler in a promise and not awaiting it.
It seems wrong to me that a boolean is out of sync as the sole purpose of it is to track if send has been called or not.
I see that the reply instance is not shared as mutating sent does not update the value in the errorHandler.

**Comment by mcollina** [comment]
> Why should it be the last invocation?

Invoking a http route can have 3 outcomes, either it succeeds, it fails or it times out. After a successful response is sent, there is no other way to communicate to the other side that something is failed, leading to all possible bugs and data loss scenarios.

The meaning of `reply.sent` is to track that `reply.send()` can be called. The purpose of the error handler is to return an error to the other side, therefore `.sent`  should be false in there.

**Comment by Pruxis** [comment]
I get the design behind it, but for starting long running processes such as processing a few gigabytes of files we often complete just after starting such process/stream.

I was using the errorHandler as a reporting handler aswell to log errors of these long running processes but this all can be solved with just wrapping it in a seperate promise and a generic catch function.

**Comment by jsumners** [comment]
I think it's an incompatible design decision on your part. You seem to be mixing a synchronous HTTP endpoint (returns `200`) with an asynchronous one (returns `204` or similar). Basically, you should do something like:

```js
fastify.get((req, res) => {
  triggerWorkToBeDone((err) => {
    if (err) throw err
    res.code(204).send()
  })
})
```
