### ISSUE TITLE
url wildcard error

### ISSUE THREAD

**Issue by ashareye** [fastify/fastify#2317]
fastify-static don't support static gzip files, so I have to write some wildcard url,  like ...

```js
	fastify.get('/:(.*\.js$)', async (request, reply) => {
		var file = request.raw.url.replace(/.*\//, "") + ".gz";
		reply.type("application/javascript; charset=UTF-8")
			.header("Content-Encoding", "gzip")
			.sendFile(file);
	})

	fastify.get('/:(.*\.png$)', async (request, reply) => {
		var file = request.raw.url.replace(/.*\//, "") + ".gz";
		reply.type("image/png")
			.header("Content-Encoding", "gzip")
			.sendFile(file);
	})
```

## Expected behavior

when I used one of them, it is ok, but both of them would be wrong, 

```js
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/:'
```

It seems that only one '/:' can be used?  so I try to use``` '/:(.*\.(js|png)$)', ```but it can only match *.js file，not png, how can I write a right wildcard url to match png, js, css and others? 
thanks

## Your Environment

- *node version*: 12.13.0
- *fastify version*: 2.14.1
- *os*: Mac

**Comment by delvedor** [comment]
This is expected, you can't declare two dynamic routes at the same level, as the router can't tell the difference.
The regex code is executed after matching a route, so the code you wrote would not work, and is the same as write:
```
GET /user/:id
GET /user/:name
```

I would recommend writing a single route that internally figures out what it should send back.
While this seems a limitation, it improves the performances by an order of magnitude, and it's a conscious decision :)

**Comment by ashareye** [comment]
thanks a lot
