### ISSUE TITLE
Fastify doesn't work on Linux

### ISSUE THREAD

**Issue by xnerhu** [fastify/fastify#2318]
## 🐛 Bug Report

The same node app using Fastify works on Windows but doesn't work on my Linux server. Firewall is disabled. When I use Express.js it works fine.

## To Reproduce

```js
const fastify = require('fastify');

const app = fastify({ ignoreTrailingSlash: true });

app.get('/', (req, res) => {
  res.send('foo');
});

app.listen(5050, (err) => {
  if (err) throw err;
  console.log('started');
})
```

## Your Environment

- *node version windows*: v12.16.3
- *node version linux*: v12.18.0
- *fastify version*: 2.14.1
- *os*: Windows 10, Debian 9

**Comment by jsumners** [comment]
Please read the documentation -- https://github.com/fastify/fastify/blob/39e23753240eb18d4f86af736c65e192b4071248/docs/Server.md#L497-L518
