### ISSUE TITLE
reply.request is missing from the TypeScript declarations

### ISSUE THREAD

**Issue by jcao219** [fastify/fastify#2325]
On the RC of v3

## To Reproduce

```js
(reply as any).request
```

## Expected behavior

`reply.request` should be defined on the declaration

( https://github.com/fastify/fastify/blob/master/types/reply.d.ts )

## Your Environment

- *node version*: 12
- *fastify version*: 3 release candidate
- *TS version*: very current

+1 addon quick question, is it on purpose that `reply` has a reference to `request` at all? Why not make a circular `request.reply`, too?

Thanks!

**Comment by Ethan-Arrowood** [comment]
This should be included in https://github.com/fastify/fastify/pull/2299

**Comment by jcao219** [comment]
Thanks for the ultra-rapid response!

Is it on purpose that there's no analogous `request.reply`?

**Comment by Ethan-Arrowood** [comment]
I'm not the best person to ask about that. Let me see if I can find the commit that added `reply.request` - it might provide some insight

**Comment by Ethan-Arrowood** [comment]
https://github.com/fastify/fastify/commit/95767ad7b35d7769b67b0de33b1dfa9a17e8e2f0

Looks like it was added before I was even a maintainer. @fastify/leads any ideas why we don't also have `request.reply`?

**Comment by mcollina** [comment]
> Looks like it was added before I was even a maintainer. @fastify/leads any ideas why we don't also have `request.reply`?

It was added this way to avoid a ciclic dependency between these two objects. I'm not sure if it has any real perf impact.

**Comment by jcao219** [comment]
I think in the past, garbage collectors with a reference-counting algorithm would be unable to identify unreachable objects if they have circular dependencies. These days, at least for V8's handling of memory usage, such objects will not cause a memory leak, at least.

I'm not sure if there's any performance impact.

The specific use case: somehow, a function only gets the `request` passed in, but something like `reply.setCookie` is needed. We would have to refactor to pass in both request and reply, or just reply only.

**Comment by mcollina** [comment]
> The specific use case: somehow, a function only gets the request passed in, but something like reply.setCookie is needed. We would have to refactor to pass in both request and reply, or just reply only.

I would just pass `reply` in.

The current design come from an _long_ discussion on the phone between @delvedor and me discussing if we should do `ctx` similar to Koa or a two object pattern. That's where we settled.
