### ISSUE TITLE
Fastify app instance become thenable

### ISSUE THREAD

**Issue by lazycoder9** [fastify/fastify#2331]
## 🐛 Bug Report
Hello folks!
We are using `fastify` as on of the core components of our [framework](https://github.com/nodosjs/nodos). We have a part of code, where we are building fastify app - creating an instance of fastify, configuring it, and return a configured instance of fastify. This builder method is asynchronous and we are calling it like
```js
const this.fastify = await buildFastify(this)
```
Everything worked well in version `2.14.1`, but we decided to try fastify v3 and upgraded to `3.0.0-rc.4`. Now we have a problem with building method and it always returns `undefined`.
The reason of this is that in v3 `require('fastify')()` return fastiify instance as `thenable` object (instance has `then` method). And this seems to be useless, because this method always returns `undefined`.
As we know, when we are returning `thenable` object from `async` function it automatically calls `then` method of this object.
## To Reproduce

```js
const buildFastiify = async () => {
    const app = require('fastify')();
    // configure app like app.register(require('middie'))
    return app
}

const fastifyApp = await buildFastify();
```

## Expected behavior
```js
console.log(fastifyApp); // * prints fastify app object *
```

## Actual behavior
```js
console.log(fastifyApp); // undefined
```

## Your Environment

- *node version*: 13
- *fastify version*: 3.0.0-rc.4
- *os*: Mac

**Comment by kibertoad** [comment]
Aren't you supposed to call `await app.ready()` instead of `await app`?

This works: https://github.com/kibertoad/canned-enterprise-node/blob/master/fastify-service-template/src/app.ts

**Comment by lazycoder9** [comment]
@kibertoad many thanks buddy, it works 🎉
