### ISSUE TITLE
Fastify 2 is mutating route schemas

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2334]
[schema-ref-test.zip](https://github.com/fastify/fastify/files/4782205/schema-ref-test.zip)
## 🐛 Bug Report

Fastify is mutating schema definitions by removing their `$id` properties.

## To Reproduce

See the attached zip file with an example project. Start the project and issue two requests:

```sh
$ curl  -d "{}" -H 'content-type: application/json' http://127.0.0.1:8000/foo
$ curl  -d "{}" -H 'content-type: application/json' http://127.0.0.1:8000/bar
```

In the first request, a log will be issued like:

```json
{"level":30,"time":1592245556599,"pid":98495,"hostname":"mini2018","reqId":1,"msg":"schema has $id true","v":1}
```

In the second request, the log will be:

```json
{"level":30,"time":1592245562806,"pid":98495,"hostname":"mini2018","reqId":2,"msg":"schema has $id false","v":1}
```

## Expected behavior

The second log should also return "true". Fastify should not be modifying the source schemas provided to it during route declarations.

## Your Environment

- *node version*: 12
- *fastify version*: 2.14.1
- *os*: Mac

**Comment by mcollina** [comment]
Good spot. Is this happening also on v3? The heavy refactor we applied in that area should have removed this problem.

I guess we should just do a deep clone of the schema?

**Comment by Eomm** [comment]
I would start debugging from here if you change the `false` to `true` the id is not removed:

https://github.com/fastify/fastify/blob/655f28fcc36679b4538e0120eecb1f5524325298/lib/validation.js#L31

(without calling `fastify.addSchema` the schema is not cloned too)

I remember some test that checks for removed $id

**Comment by jsumners** [comment]
> Is this happening also on v3?

I don't know. I have not had any time to test v3 at all. But I don't think so because I didn't see the `cleanId` function in `lib/schemas` on the v3 branch:

https://github.com/fastify/fastify/blob/655f28fcc36679b4538e0120eecb1f5524325298/lib/schemas.js#L134-L143

> I would start debugging from here if you change the `false` to `true` the id is not removed:

Why would that boolean need to exist? Can that `cleanId` method just be removed on the v2 branch?

I'm not so familiar with how the schema support is implemented.

**Comment by Eomm** [comment]
No, it cannot be removed because it is needed for the $ref "replace way" since the same $id would throw an error later during the compile of the schema

**Comment by jsumners** [comment]
> No, it cannot be removed because it is needed for the $ref "replace way" since the same $id would throw an error later during the compile of the schema

Then what would you suggest to fix this?

**Comment by mcollina** [comment]
> Then what would you suggest to fix this?

We should do a deep copy when registering a route as well (similar to what we do in addSchema)

**Comment by Eomm** [comment]
I would clone the schema in the ref resolver user's function. It should work aswell

**Comment by jsumners** [comment]
Using `lodash.clonedeep` and updating the code to this still results in the error:

```js
fastify.setSchemaResolver((ref) => clone(ajv.getSchema(ref).schema));
```

**Comment by Eomm** [comment]
If you change the $id to `$id: '#urn:schema:bar'` the field will not be removed.

We are in this case:

https://github.com/fastify/fastify/blob/65d0e5b15769f67881c37aed8d84b802adf44106/lib/schemas.js#L136

where the `urn:schema:bar` doesn't match the pattern.

The pattern follows [this spec](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3):

>    To specify such a subschema identifier, the "$id" keyword is set to a
   URI reference with a plain name fragment (not a JSON Pointer
   fragment).  This value MUST begin with the number sign that specifies
   a fragment ("#"), then a letter ([A-Za-z]), followed by any number of
   letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons
   (":"), or periods (".").

This strictness was the only way I found to support the "replace way" schema in v2.

Another quick option would be to avoid the fastify schema processing writing:

```
  fastify.route({
    path: '/bar',
    method: 'POST',
    schema: {
      body: { $ref: 'urn:schema:bar' },
      response: {
        '2xx': ajv.getSchema('urn:schema:response:bar').schema
      }
    },
```

This will demand the compiling to the `setSchemaCompiler` defined.


I think a fix could be to skip this process:

https://github.com/fastify/fastify/blob/65d0e5b15769f67881c37aed8d84b802adf44106/lib/validation.js#L31

when a custom compiler is set by the user.


I will work on in a few weeks if someone else would like to give it a shot before it is appreciated 👍

**Comment by jsumners** [comment]
If I get some time I'll try to dig in.

**Comment by jsumners** [comment]
Shoo bot!

**Comment by mehmetegemen** [comment]
Do you still need help? I can.

**Comment by jsumners** [comment]
You are very welcome to dig in.

**Comment by Eomm** [comment]
> You are very welcome to dig in.

This is related to fastify v2: do we release not security patch for that version?

**Comment by mcollina** [comment]
We should if there is a vulnerability

**Comment by jsumners** [comment]
If the community wants to provide a PR against v2 I don't see any reason we can't consider it.

**Comment by mehmetegemen** [comment]
Guys I got corona and having terrible days cause of it, so I have to take back my offer, sorry for that.

**Comment by mcollina** [comment]
@jsumners @Eomm can we close this?
