### ISSUE TITLE
allowHttp1 does not work when https is enabled

### ISSUE THREAD

**Issue by andykais** [fastify/fastify#2341]
## 🐛 Bug Report

going off of the example http2 server, plain http requests fail despite the claim
> Node core req and res objects can be either HTTP/1 or HTTP/2. Fastify supports this out of the box

## To Reproduce
generating a cert and using the sample code:
```js
'use strict'

const fs = require('fs')
const path = require('path')
const fastify = require('fastify')({
  http2: true,
  https: {
    allowHTTP1: true, // fallback support for HTTP1
    key: fs.readFileSync(path.join(__dirname, 'https', 'privateKey.key')),
    cert: fs.readFileSync(path.join(__dirname, 'https', 'certificate.crt'))
  }
})

// this route can be accessed through both protocols
fastify.get('/', function (request, reply) {
  reply.code(200).send({ hello: 'world' })
})

fastify.listen(3000)
```
curl responses look like this:
```bash
$ curl http://localhost:3001 --http1.1
curl: (52) Empty reply from server
```
and `h2url` just hangs forever
```bash
$ h2url http://localhost:3000
⠏ GET http://localhost:3001
```

## Expected behavior
the server should respond with `{"hello": "world"}` like it does when using https
```bash
$ curl https://localhost:3001 --http1.1 --insecure 
{"hello":"world"}
# or
$ curl https://localhost:3001 --http2 --insecure 
{"hello":"world"}
# or
$ h2url https://localhost:3001 
{"hello":"world"}
```

Disabling https and http2 makes http function expectedly

## Your Environment

- *node version*: 14.4
- *fastify version*: >=2.15.0
- *os*: Linux

**Comment by mcollina** [comment]
You _must_ use https when using http2 and http1 on the same port.

**Comment by andykais** [comment]
@mcollina if I want to provide both http1 without https and http2, do I need to run two separate servers?

**Comment by mcollina** [comment]
yes, you need tls to differentiate between http/1.1 and http/2.
Note that browsers cannot conenct to http/2 servers without tls.

**Comment by andykais** [comment]
Thank you, I was aware of that. I am building a local web app though so certs are more of a pain to deal with for users. I wanted to give an option to use http1 if they so desired

**Comment by mcollina** [comment]
Given that each server run on a single port, you need two fastify instances.

**Comment by andykais** [comment]
turns out it is possible! https://github.com/masx200/http-https-http2-polyglot but I will likely still run two separate servers. This seems kind of hacky

**Comment by jsumners** [comment]
I highly recommend doing the TLS termination at your edge instead of in the app -- https://www.fastify.io/docs/v2.15.x/Recommendations/#reverseproxy

**Comment by andykais** [comment]
Its a local web app. One of the goals is to run it without any external processes (like a reverse proxy). Like I said, I will likely just run separate web servers, or make http2/http1 a command line parameter.

**Comment by AlttiRi** [comment]
Nevermind.
