### ISSUE TITLE
Casbin plugin

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2347]
## 🚀 Feature Proposal

[Casbin](https://casbin.org/) provides a common language for defining access policies. 

```js
import { newEnforcer } from 'casbin';

const e = await newEnforcer('path/to/model.conf', 'path/to/policy.csv');

const sub = 'alice'; // the user that wants to access a resource.
const obj = 'data1'; // the resource that is going to be accessed.
const act = 'read'; // the operation that the user performs on the resource.

if ((await e.enforce(sub, obj, act)) === true) {
    // permit alice to read data1
} else {
    // deny the request, show an error
}
```

## Example

I don't have one, but I would expect to have a `casbin` option added via `onRoute` hook that adds a `preHandler` hook that validates that enforces the given policy.

**Comment by jcao219** [comment]
To understand the idea of what we want out of Casbin...
Routes are the "resources" to be protected, am I correct? Then "operation" must be the REST verb.
How do we define "user"?

**Comment by mcollina** [comment]
as an example https://github.com/fastify/fastify-jwt set a user object in `request.jwt`.

**Comment by simoneb** [comment]
NearForm has contributed a couple of fastify plugins for Casbin:

- https://github.com/nearform/fastify-casbin
- https://github.com/nearform/fastify-casbin-rest

Hope it helps!

**Comment by mcollina** [comment]
Can you send a PR to update our ecosystem page?

**Comment by simoneb** [comment]
https://github.com/fastify/fastify/pull/2675
