### ISSUE TITLE
Customize error message

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#235]
Hi, I'm looking for a solution to customize the error message in fastify. It looks like it's not possible with the `onResponse` hook because I only have access to the raw `ServerResponse` object. I also found `extendServerError` but I have no access to the response context and I also can't use my own format without to extend it.

Another good reason is that I don't always want that the error message is exposed to the client.

```js
  fastify.addHook("onResponse", (res, next) => {
    // I want to be flexible like this
    if (resp.error instanceof SystemError) {
     return  {
       message: 'Please call the support',
       code: resp.error.code
     }
    } else if (resp.error instanceof ApplicationError) {
      return {
         code: resp.error.code,
         message: resp.error.msg
      }
    }
     .....
    next()
  })
````

```js
fastify.extendServerError(() => {
 // which type of error ocurred? whats the context?
  return {
    timestamp: new Date()
  }
})
```

It would make sense to provide an interface like in hapi https://hapijs.com/api#error-transformation instead to pass the raw `ServerResponse` object.

**Comment by delvedor** [comment]
You can't customize the error message inside the `onResponse` hook, because the response has already been sent.
Check out [this](https://github.com/fastify/fastify/blob/master/fastify.js#L148-L164) lines.

Regarding the `extendeServerError` utility, it is used [here](https://github.com/fastify/fastify/blob/master/lib/reply.js#L71). At the moment you cannot know who has caused that error (hook, middleware, user handler...).

**Comment by StarpTech** [comment]
@delvedor Is there any reason that speaks against to pass the full error payload to `extendeServerError` ? We can decide based on the error.

**Comment by motss** [comment]
I also agree that it'd be nice if we could further customize the error message before sending it out.

**Comment by delvedor** [comment]
> Is there any reason that speaks against to pass the full error payload to `extendeServerError` ? We can decide based on the error.

No, there is not :D
Fire a pr!

**Comment by StarpTech** [comment]
Fastify checks for boom errors so it's possible to define a custom error response https://github.com/hapijs/hapi/blob/master/API.md#error-transformation we should add this to the documentation.

`_extendServerError` is not called when we use `Boom` whats the reason for this? This should be separated.

**Comment by delvedor** [comment]
Currently we are providing a basic support for boom, I don't know if is a good idea use a Fastify api to modify the Boom object. @mcollina thoughts on this?

**Comment by StarpTech** [comment]
I mean this is already possible and should be documented in the [error section](https://github.com/fastify/fastify/blob/master/docs/Reply.md#errors)

```js
fastify.get('/', function (request, reply) {
  const error = Boom.badRequest('Cannot feed after midnight');
  error.output.statusCode = 499;    // Assign a custom error code
  error.reformat();

  error.output.payload.custom = 'abc_123'; // Add custom key
  reply.send(error)
})
```

**Comment by mcollina** [comment]
I think this can be closed, feel free to reopen if it's not the case.
