### ISSUE TITLE
netlify-lambda: lru is not a function

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify#2356]
## 🐛 Bug Report

I recently updated and migrated to latest technologies (as possible) all my Development Environments, but **fastify** took much longer because of more breaking change, incompatibility and i hope i got last issue, which i self cannot fix

I getting error `Function invocation failed: TypeError: lru is not a function` on **netlify-lambda** serve url at http://localhost:9000/graphql

<details>
<summary>Show full trace</summary>

```bash
❯ npm run dev:functions

> @dalisoft/fastify-dev-env@0.1.0 dev:functions /Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify
> NODE_ENV=development netlify-lambda serve functions --config ./webpack.config.netlify.js

netlify-lambda: Starting server
Hash: 10f09b11c8c44039452e
Version: webpack 4.43.0
Time: 10580ms
Built at: 06/29/2020 12:15:40 AM
     Asset      Size   Chunks             Chunk Names
graphql.js  14.4 MiB  graphql  [emitted]  graphql
 server.js  14.4 MiB   server  [emitted]  server
Entrypoint graphql = graphql.js
Entrypoint server = server.js
[../handler.js] 145 bytes {graphql} {server} [built]
[../node_modules/avvio/boot.js] 10.7 KiB {graphql} {server} [built]
[../node_modules/aws-lambda-fastify/index.js] 3.58 KiB {graphql} {server} [built]
[../node_modules/fastify-cookie/plugin.js] 2.07 KiB {graphql} {server} [built]
[../node_modules/fastify-plugin/index.js] 1.79 KiB {graphql} {server} [built]
[../node_modules/fastify/fastify.js] 19.5 KiB {graphql} {server} [built]
[../src/config.js] 1.24 KiB {graphql} {server} [built]
[../src/errors/index.js] 253 bytes {graphql} {server} [built]
[../src/fastify-plugins/index.js] 608 bytes {graphql} {server} [built]
[../src/instance.js] 1.03 KiB {graphql} {server} [built]
[../src/middlewares/index.js] 120 bytes {graphql} {server} [built]
[../src/routes/index.js] 201 bytes {graphql} {server} [built]
[../src/server-config.js] 632 bytes {graphql} {server} [built]
[./graphql.js] 48 bytes {graphql} [built]
[./server.js] 48 bytes {server} [built]
    + 999 hidden modules

WARNING in ../node_modules/uglify-es/tools/node.js 18:11-32
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/fast-json-stringify/index.js
 @ ../node_modules/fastify/lib/reply.js
 @ ../node_modules/fastify/fastify.js
 @ ../src/instance.js
 @ ../handler.js
 @ ./graphql.js

WARNING in ../node_modules/app-root-path/lib/app-root-path.js 14:10-56
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/app-root-path/index.js
 @ ../node_modules/fastify-oas/lib/openapi/constructor.js
 @ ../node_modules/fastify-oas/lib/openapi/index.js
 @ ../node_modules/fastify-oas/lib/index.js
 @ ../src/fastify-plugins/fastify-oas.js
 @ ../src/fastify-plugins/index.js
 @ ../src/instance.js
 @ ../handler.js
 @ ./graphql.js
Lambda server is listening on 9000
Request from ::1: GET /graphql
[Server]: started in DEVELOPMENT mode

<-- This line occurs immediately if go-to view endpoint -->
Response with status 500 in 568 ms.
Error during invocation:  TypeError: lru is not a function
    at new ContentTypeParser (webpack-internal:///../node_modules/fastify/lib/contentTypeParser.js:31:16)
    at build (webpack-internal:///../node_modules/fastify/fastify.js:155:27)
    at __webpack_exports__.default (webpack-internal:///../src/instance.js:23:61)
    at eval (webpack-internal:///../handler.js:7:134)
    at Module.../handler.js (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/functions-build/graphql.js:109:1)
    at __webpack_require__ (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/functions-build/graphql.js:20:30)
    at eval (webpack-internal:///./graphql.js:2:66)
    at Module../graphql.js (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/functions-build/graphql.js:11685:1)
    at __webpack_require__ (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/functions-build/graphql.js:20:30)
    at /Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/functions-build/graphql.js:84:18

```
</details>

## To Reproduce

1. `git clone https://github.com/dalisoft/dev-env.git`
2. `cd dev-env/backend/fastify`
3. `npm run dev:function`
4. Go-to http://localhost:9000/graphql

Link to code lives [here](https://github.com/dalisoft/dev-env/tree/master/backend/fastify)

## Expected behavior

GraphiQL page rendering

## Your Environment

- *node version*: v14.4.0
- *fastify version*: fastify@2.15.0, apollo-server-fastify@2.15.0, aws-lambda-fastify@1.4.4
- *os*: macOS Mojave 10.14.6
- *any other relevant information*

**Comment by mcollina** [comment]
This seems a webpack problem.. have you tried removing that?

**Comment by dalisoft** [comment]
Removing webpack breaks my lambda function. 
I think too bug related to webpack, i just reported to let you know it has some bugs with netlify lambda compatibility. 

If you think it’s (netlify lambda compatibility ) not important , you can close issue. 

Thanks for very nice framework

**Comment by mcollina** [comment]
If you are a customer, I would recommend contact Netlify support to get help. You are trying to use their product, they make money out of it, and we do not make money out of Fastify. As a result, they are in the best position to help. If they don't, it's not that we have a bug: as you can read in https://www.fastify.io/docs/latest/Serverless/, we do not have instructions for Netlify Lambda because __no one contributed them__. Would you like to send a PR?

---

A 1 minute Google searched showed: https://community.netlify.com/t/how-to-include-dependencies-in-netlify-lambda-functions/2323/6. I'm highly convinced this should fix it.

**Comment by dalisoft** [comment]
Thanks @mcollina 

I sure, i try create issue in their repo. 
You are right, Fastify open source, well maintained without any sponsors. 
I always love projects with best maintainers. 

Thank you again for googling. 
I hope they fix it. 

I will submit PR once i can successfully fix the bug

**Comment by dalisoft** [comment]
I fixed it finally, anyone if wants can use my finalized **Fastify** dev-env at [here](https://github.com/dalisoft/dev-env/tree/master/backend/fastify). 
Works on all 4-environments: Serverless AWS, Netlify Functions, Vercel (before Zeit Now) and HTTP Server

**Comment by dalisoft** [comment]
If anyone interested how i fixed, [here](https://github.com/dalisoft/dev-env/commit/b1ba86b2cc16232765653b1f895c9539a1c0717c) is commit

**Comment by kibertoad** [comment]
@dalisoft Would you consider contributing documentation with example?

**Comment by dalisoft** [comment]
@kibertoad I will do once make sure all of those mode works in Production (live)

**Comment by dalisoft** [comment]
Yep, works in Netlify Lambda, result [here](https://fastify-dev-env.netlify.app/.netlify/functions/graphql), i will add guide as soon as i can get time

**Comment by dalisoft** [comment]
See #2359

**Comment by FallingSnow** [comment]
For anyone who comes across this, this was actually fixed for me by using cjs `tiny-lru`. I have no idea why.

```js
resolve: {
  alias: {
    "tiny-lru": path.join(process.cwd(), "./node_modules/tiny-lru/lib/tiny-lru.cjs.js"),
  }
}
```
