### ISSUE TITLE
pino library occur error at the sever starting

### ISSUE THREAD

**Issue by sudokzt** [fastify/fastify#2357]
## 🐛 Bug Report

```
node_modules/pino/lib/tools.js:165
    throw Error('Missing `pino-pretty` module: `pino-pretty` must be installed separately')
```

The used logger 'pino' error.

## To Reproduce

I tried the fastify basic tutorial. 
1. `yarn add fastify`
2. import fastify and start server

By the way, I used `typescript: 3.9.5`

## Expected behavior

Starting the server without this error and well work with logs.

## Your Environment

- *node version*: v12.8.0
- *fastify version*: 2.15.0
- *os*: mac
- *pino*: 5.17.0

**Comment by sudokzt** [comment]
I installed `pino-pretty: 4.00`. It works well.
Maybe it needs PR for pino-pretty. What do you think about?

**Comment by mcollina** [comment]
It really tells you what to do: install pino-pretty. We do not ship it as it's a development tool and therefore it should not be shipped in production.

**Comment by sudokzt** [comment]
Thank you for replying 👍 
Shouldn't install it as dev dependencies in fastify's package.json?
