### ISSUE TITLE
Error: Property 'setReplySerializer' does not exist on type 'FastifyInstance'

### ISSUE THREAD

**Issue by persona0591** [fastify/fastify#2358]
## 🐛 Bug Report

I'm trying to use setReplySerializer() in my Fastify-powered TypeScript project. However, an error is thrown:

`error TS2339: Property 'setReplySerializer' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.`

## To Reproduce

```js
import * as Fastify from 'fastify';

(async () => {
  try {
    const server = Fastify.fastify();

    // Based upon https://www.fastify.io/docs/master/Server/#setreplyserializer
    server.setReplySerializer(function (payload: any, statusCode: any) {
      return `my serialized ${statusCode} content: ${payload}`;
    });

    await server.listen(3000, '0.0.0.0');
  } catch (err) {
    console.error(err);
  }
})();

```

## Expected behavior

No TypeScript error

## Your Environment

- *Node version*: 12
- *Fastify version*: 3.0.0-rc.4
- *TypeScript version*: 3.9.5
- *os*: Linux

**Comment by mcollina** [comment]
Good spot! That's totally missing from our types. Would you like to send a PR?

**Comment by persona0591** [comment]
A PR is a bit out of my league, I'm afraid - I've just started experimenting with Fastify.

My guess is that a new declaration should be added to `types/instance.d.ts`. For example:

```js
/**
 * Set the reply serializer for all routes.
 */
setReplySerializer(replySerializer: (payload: unknown, statusCode: number) => string): FastifyInstance<RawServer, RawRequest, RawReply, Logger>;
```

But I'm a bit unsure about the tests in `test/types/instance.test-d.ts`. I'd say that the tests for `setSerializerCompiler` or `setValidatorCompiler` are quite similar to those of `setReplySerializer`, but I cannot find tests for neither.

**Comment by chasingSublimity** [comment]
Hi all! I can take a swing at this in the next day or so.

**Comment by persona0591** [comment]
Hi Blake, thanks in advance!

**Comment by Ethan-Arrowood** [comment]
quick bump for @chasingSublimity are you still interested in sending a PR for this? Let me know if you'd like any help contributing :smile:

**Comment by chasingSublimity** [comment]
@Ethan-Arrowood Yes, so sorry! I'd love a bit of help with the types test. I'll create a PR today and tag you in it, if that's ok. :)

**Comment by Ethan-Arrowood** [comment]
Feel free to do so! Happy to help
