### ISSUE TITLE
Change generic parameters order for FastifyRequest

### ISSUE THREAD

**Issue by thomasthiebaud** [fastify/fastify#2367]
## 🚀 Feature Proposal

Is it possible change the order of generic parameters of `FastifyRequest` so it is easier to use?
Can it be change so it is order agnostic? 

## Motivation

Right now `FastifyRequest` the type looks like

```
export interface FastifyRequest<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RequestGeneric extends RequestGenericInterface = RequestGenericInterface
>
```

that I can use like 

```
type MyCustomRequest = FastifyRequest<
  RawServerDefault,
  RawRequestDefaultExpression<RawServerDefault>,
  {
    Headers: {
      test: boolean;
    }
  }
>;
```

It works but it is anoying to have to respecify the default parameters

## Example

Ideally I would like to do something like

```
type MyCustomRequest = FastifyRequest<
  {
    Headers: {
      test: boolean;
    }
  }
>;
```

or maybe access an object so it does not rely on the order

```
type MyCustomRequest = FastifyRequest<{
  Request: {
    Headers: {
      test: boolean;
    }
  }
}>;
```

**Comment by mcollina** [comment]
I think this is already implemented in fastify v3. You can install it with `npm i fastify@next`. We are at rc.5 and it will likely be the last.

**Comment by thomasthiebaud** [comment]
I'm using `fastify@next`. From the [migration guide](https://github.com/fastify/fastify/blob/master/docs/Migration-Guide-V3.md#changed-typescript-support) I can see that `fastify.get` supports it, but I did not managed to do the same wiith `FastifyRequest`

**Comment by mcollina** [comment]
Would you like to send a PR?

cc @Ethan-Arrowood

**Comment by thomasthiebaud** [comment]
I can have a look next week probably

**Comment by Ethan-Arrowood** [comment]
Yes I’d love to see this. Please try and use the same pattern the get, post, etc methods use.

**Comment by thomasthiebaud** [comment]
PR #2373 is ready. I tried to keep the same pattern
