### ISSUE TITLE
Investigate how to support `const app = fastify(); await app;` in TypeScript

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2378]
Related to https://github.com/fastify/fastify/pull/2376

See the test in the PR.

How do we type this behavior? 

If its not possible (which I sorta expect but don't know for sure), then we should provide some type-cast option like:

```ts
// untested code ahead do not assume this is the solution :-) 

const _app = fastify()

const app = _app as unknown as () => Promise<FastifyInstance>

await app; // resolves FastifyInstance
```

**Comment by kbkk** [comment]
@Ethan-Arrowood Could you explain why wouldn't it work?

You can await anything in JS/TS, not just promises - it'll just return the awaited value.

So, given the above, this compiles/works just fine:

```
const _app = fastify()

const app = await _app;
```

**Comment by mcollina** [comment]
The fastify instance is a _Thenable_, it implements a `then()` method that will be called by `await`. This custom method will load all the plugins so far.

**Comment by Ethan-Arrowood** [comment]
Understandable, but if I'm not mistake, this issue is specific to the promise behavior of the main fastify function. As a TS dev, if I `await` something I'm expecting that it's type is a promise as well

**Comment by fox1t** [comment]
This is really a great point @Ethan-Arrowood and I somehow agree with you.

**Comment by L2jLiga** [comment]
@Ethan-Arrowood correct me if I'm wrong but can't we use types union? f.e.:

```typescript
declare function fastify<
  Server extends http2.Http2SecureServer,
  Request extends RawRequestDefaultExpression<Server> = RawRequestDefaultExpression<Server>,
  Reply extends RawReplyDefaultExpression<Server> = RawReplyDefaultExpression<Server>,
  Logger extends FastifyLoggerInstance = FastifyLoggerInstance
>(
  opts: FastifyHttp2SecureOptions<Server, Logger>
): FastifyInstance<Server, Request, Reply, Logger> & Promise<FastifyInstance<Server, Request, Reply, Logger>>
```
