### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2381]
We are at 99.1% right now, going to 100% is within reach!

**Comment by MetCoder95** [comment]
Hi! Stills open, I would like to help :)

**Comment by mcollina** [comment]
go for it! Ask questions if you are stuck.

**Comment by MetCoder95** [comment]
Hi! I have one, related to this function in `lib/warning.js`:
```javascript
  function FastifyWarning (a, b, c) {
    Error.captureStackTrace(this, FastifyWarning)
    this.name = name
    this.code = code

    // more performant than spread (...) operator
    if (a && b && c) {
      this.message = format(message, a, b, c)
    } else if (a && b) {
      this.message = format(message, a, b)
    } else if (a) {
      this.message = format(message, a)
    } else {
      this.message = message
    }
  }
```

There's any chance to fall into any of the if's? When the function is called to instantiate an object with the `new` keyword a few lines below, it seems like is not as we're always instantiating without any arg

```javascript
function emitWarning (code) {
  if (codes[code] === undefined) throw new Error(`The code '${code}' does not exist`)
  if (emittedWarnings.has(code) === true) return
  emittedWarnings.set(code, true)
  process.emitWarning(new codes[code]())
}
```

And actually this file is the one with less coverage, with 81% 😅

**Comment by mcollina** [comment]
We are moving the warnings to a separate module in https://github.com/fastify/fastify/pull/2354.

**Comment by MetCoder95** [comment]
I see I'll move to the next files then. Thanks!

**Comment by simone-sanfratello** [comment]
working on that - in my spare time

**Comment by simone-sanfratello** [comment]
I'm close to the end https://github.com/fastify/fastify/pull/3046

I need some help with windows and mac

**Comment by simone-sanfratello** [comment]
done! :rocket:
