### ISSUE TITLE
Type `FastifyReply` body

### ISSUE THREAD

**Issue by thomasthiebaud** [fastify/fastify#2385]
## 🚀 Feature Proposal

The `send` method from `FastifyReply` accepts a generic parameter `T` ([code here](https://github.com/fastify/fastify/blob/master/types/reply.d.ts#L25)), but it is not used anywhere else

Could we make that `T` parameter part of the `FastifyReply` parameters? `express` is doing something similar here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts#L505

A strech goal would be to change the types to have a different reply type per status code, so it maps event better to the json schema (not sure this is possible)

## Motivation

Having `T` forwarded into `FastifyReply` would allow for better typings, for example

```
type CustomReply = FastifyReply<{
  isTypedReplyBody: boolean;
}>

fastify.get('/', async (request: FastifyRequest, reply: CustomReply) => {
  reply.send({isTypedReplyBody: true}) // ok
  reply.send({raw: true}) // not ok, ts error
})
```

**Comment by delvedor** [comment]
I think it could be done. @Ethan-Arrowood what do you think?

**Comment by Ethan-Arrowood** [comment]
Yeah this is good, you could also look to add this to the .get method generic so it passes through like the request generics are. 

Would you like to send a PR?

**Comment by thomasthiebaud** [comment]
Yes, I can have a look this week

**Comment by thomasthiebaud** [comment]
I pushed a PR with a first commit.

Question: If I want to add the `ReplyPayload` to get, post, .... I can either make it as a second generic parameter or I can change the first parameter to include both `Request` and `Reply` payloads. Do you have any preferences? If I go for the second option I'll have to rename `RequestGeneric extends RequestGenericInterface` to something else. Do you have a preference?
