### ISSUE TITLE
Throw error when plugin callback is not called after certain amount of time

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#239]
This can be easy implemented with setTimeout e.g with a timeout of 5000. It's useful because when you have lots of plugins it's hard to find the root issue.

```js
module.exports = function (fastify, opts, next) {
  fastify.decorate('utility', () => {})

  fastify.get('/', handler)

  // next() oh forgot but don't worry we throw an exception in 5 seconds
}
```

@mcollina

**Comment by mcollina** [comment]
I have been bitten by this some times. I tend to agree that it is hard to debug if it happens.

**Comment by mcollina** [comment]
I don't know if we can extract the plugin stacktrace externally when the timeout expires. It might get tricky.

Let me know if you have a solution. The plugin system is provided by https://github.com/mcollina/avvio.

**Comment by StarpTech** [comment]
I think it would be enough to throw an error like "Callback from plugin `test` was not fired" ?

**Comment by mcollina** [comment]
@StarpTech if the plugin is not a named function, we do not have any meta-info to populate that.

**Comment by delvedor** [comment]
I know that is not easy to spot the *"forgot to call `next`"* error, but I don't like the timer idea, if you have a functions that takes a lot of time to boot (for some reason) the timeout will throw every time.
Maybe we can be more specific about this inside the docs.

**Comment by StarpTech** [comment]
>  if you have a functions that takes a lot of time to boot (for some reason) the timeout will throw every time.

This is bad practice and produces cascading errors and it's in no great implementaiton in an  event driven  environment. A flag could cover both cases.

**Comment by mcollina** [comment]
IMHO a `unref()` timer would solve this problem easily. How to implement it might be tricky, I'm attaching the "help wanted" label because I do not think we have time to work on this right now.

**Comment by allevo** [comment]
@StarpTech if you want: https://www.npmjs.com/package/fastify-register-timeout

**Comment by StarpTech** [comment]
@allevo nice thank you!

**Comment by mcollina** [comment]
This can be closed now.

**Comment by akhilshastri** [comment]
How do i increase default timeout from 1000 to something else ..? https://www.fastify.io/docs/latest/Server/#plugintimeout
