### ISSUE TITLE
Documentation: bad link in Errors section

### ISSUE THREAD

**Issue by PabloDinella** [fastify/fastify#2390]
## 🐛 Bug Report

The link that should point to Server#setErrorHandler is broken.
![image](https://user-images.githubusercontent.com/2482730/86985374-7c55a000-c167-11ea-9a5a-8907084086e0.png)

## To Reproduce

Steps to reproduce the behavior: access https://www.fastify.io/docs/latest/Errors/ and click on **setErrorHandler**

## Expected behavior

The link should point to https://www.fastify.io/docs/latest/Server/#seterrorhandler instead of https://www.fastify.io/docs/latest/Errors/Server.md#seterrorhandler

I think this behavior was introduced with this [PR](https://github.com/fastify/fastify/pull/2283), I ran https://github.com/fastify/website but couldn't understand how to point to my local repository or test any change, so I wasn't able to open a PR to fix it :( Sorry for opening an issue for such a simple thing, if you tell me how to fix docs I will surely directly open a new PR the next time I find a typo :)

**Comment by mcollina** [comment]
@lmammino how could this be fixed? Thanks!
