### ISSUE TITLE
broken links in release notes of v3

### ISSUE THREAD

**Issue by pc-jedi** [fastify/fastify#2393]
Just a minor thing. In the release note of [v3.0.0](https://github.com/fastify/fastify/releases/tag/v3.0.0) all links to markdown files in the docs folder are broken since they point to `blob/v3.0.0/....md` rather then `blob/v3.0.0/docs/....md`. The **docs** is missing in the link.

**Comment by mcollina** [comment]
Thanks, they should be fixed now!
