### ISSUE TITLE
Use route prefix feature and route version feature in conjunction

### ISSUE THREAD

**Issue by jk1z** [fastify/fastify#2394]
## 🚀 Feature Proposal
Use `route prefix` to prefix the route path with versions like v1.1, v2, v3.1 and use `route version` to do the smart routing and fallback by the path prefix in the client's request object.

## Motivation

The motivation behind this is that our company and many others are using route path prefix for versioning purpose. It would be cool to use these 2 features in conjunction to retro fit route versioning to it. 

We couldn't really change the way on how we versioning the routes since a lot of clients have already integrated to us.

## Example
If the highest route version in other routes is v3 but on **User**'s route it only has the following: 
/v1/user
/v2/user
When user requests /v3/user, the `route version` should automatically route the user to use the v2 user route.

## FYI
Is there anyway I can re-route the request in hooks or middlewares to a different route?

**Comment by jk1z** [comment]
Another way to retro fit this is to use smart reverse proxy to trim off version prefix and adds the version to the header, but it's less optimal. I would like to do this in Fastify

**Comment by jsumners** [comment]
That is all handled by the router, [`find-my-way`](https://www.npmjs.com/package/find-my-way). Routing happens before any hook is available in [the lifecycle](https://www.fastify.io/docs/v3.0.x/Lifecycle/).

If you don't want to rewrite the request in your proxy, then you might be able to finagle it via the [`onRoute` hook](https://www.fastify.io/docs/v3.0.x/Hooks/#onroute).

**Comment by jk1z** [comment]
Hmm it probably won't happen, but is it possible for fastify add a lifecycle stage before the routing happens? So the hook can tap into it....that feels like a major change on framework..

**Comment by jsumners** [comment]
The way routing is handled in Fastify is a pillar of its speed. We are unlikely to add hooks into the routing step after the tree has been built.

**Comment by jk1z** [comment]
All good, thanks for the timely reply.😊 I think I will just do some preprocessing in the proxy level.
