### ISSUE TITLE
Improve documentation on using `prettyPrint` option in the logger [TypeScript]

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2395]
Ref #2388 

It would be great if we can improve the documentation for the `prettyPrint` option in our logger. With the v3 type changes users now have to specify `pino.Logger` in order to use that property (https://github.com/fastify/fastify/issues/2388#issuecomment-655632103).

We should document this in multiple places.
- In server.md under the logger option
- In logging.md
- in typescript.md (it is already [there](https://www.fastify.io/docs/latest/TypeScript/#example-5-specifying-logger-types) but is hard to find)

**Comment by mcollina** [comment]
I would actually add that property in our types.

**Comment by Ethan-Arrowood** [comment]
This may cause an issue with custom loggers if they don't implement that property themselves. I'd say its worth an investigation for sure!

**Comment by naseemkullah** [comment]
Is pino-http used as fastify's logger? If so is there a way to just link to pino-http types? But I don't think it is cause fastify's built in logger does not quite have all the same options as pino-http if I'm not mistaken.

**Comment by mcollina** [comment]
> Is pino-http used as fastify's logger? 

no

> If so is there a way to just link to pino-http types?

no

> But I don't think it is cause fastify's built in logger does not quite have all the same options as pino-http if I'm not mistaken.

They have the same features. fastify does not have some features related to skip paths because they are not needed here.
