### ISSUE TITLE
querystring validation ignores additional parameters

### ISSUE THREAD

**Issue by rburgst** [fastify/fastify#2396]
## 🐛 Bug Report

Schema validation for querystrings allows additional properties, even if `additionalProperties` is set to `false`.

## To Reproduce

```js
// Require the framework and instantiate it
const fastify = require('fastify')({
  logger: true,
})

const opts = {
  schema: {
    query: {
      type: 'object',
      properties: {
        test: {
          type: 'string',
        },
      },
      additionalProperties: false,
    },
  },
}
// Declare a route
fastify.get('/', opts, function (request, reply) {
  reply.send({ hello: 'world' })
})
// Declare a route
fastify.put('/', opts, function (request, reply) {
  reply.send({ hello: 'world' })
})

// Run the server!
fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})

```

## Expected behavior

If I send the following request

```
 http 'http://localhost:3000/?test2=hallo'
```

I would expect a 400 since the parameter `test2` is not known. Instead I get 200.

## Your Environment

- *node version*: 12.13.0
- *fastify version*: 2.15.1
- *os*: Mac

**Comment by delvedor** [comment]
Hello! The behavior might be confusing, what happens is that in the `request.query` object you will not find any other property but the one you have declared.
You can verify it with the following code:
```diff
 fastify.get('/', opts, function (request, reply) {
+  console.log(req.query)
   reply.send({ hello: 'world' })
 })
```

@fastify/core do you remember why we ended up with this behavior?

**Comment by mcollina** [comment]
> I would expect a 400 since the parameter test2 is not known. Instead I get 200.

That's how our default config of Ajv works. We ship with `removeAdditional`: https://github.com/ajv-validator/ajv#filtering-data.

You can customize your  ajv instance. See https://www.fastify.io/docs/latest/Validation-and-Serialization/#validator-compiler for more details.
