### ISSUE TITLE
Easier access to FastifyPlugin types

### ISSUE THREAD

**Issue by wolfejw86** [fastify/fastify#2397]
## 💥 Regression Report

FastifyPlugin not typing function arguments correctly.

## Last working version
2.14

Stopped working in version: 3.0

## To Reproduce

In fastify 2.14 I had made a quick and easy access type for myself to quickly and easily type a fastify plugin in a separate file.  
see
```ts
import { FastifyInstance } from 'fastify';

export type FastifyPlugin = Parameters<FastifyInstance['register']>[0];
```

I fully expected this to break somehow in 3.0 and am not asking for it to be supported. However, see the new type for `FastifyPlugin` exported from fastify 3.0

![image](https://user-images.githubusercontent.com/22133869/87168287-3e0dcd00-c29c-11ea-9288-ef187bd7ce67.png)

For some reason it is typing the fastify instance as an `any` which makes it a pain to leverage typescript support throughout the plugin file.  Is this expected? Is anyone else running into this?  For reference I am on Typescript 3.9.4

**Comment by delvedor** [comment]
cc @Ethan-Arrowood

**Comment by Ethan-Arrowood** [comment]
Yes this is intended (and needs to be document better). 

We've had lengthy discussions on this in particular. Essentially, when a plugin is used, it should not make any assumptions on what kind of fastify instance is being passed to it. If it requires a specific method or property then it should verify that the passed in instance has it first. Thus we have made the types reflect that position. This is the best solution for type safe plugins. The recommended path for you is to either set the type of that property as a specific fastify instance you as sure will be passed to your plugin, or implement the method/property checks before calling them. 

I'll add an issue to improve the documentation on this now too as you're not the first person to ask this question!

**Comment by mcollina** [comment]
@Ethan-Arrowood I think the `app` can be typed, but we cannot assume it is HTTP/1.1 or HTTP/2. They will both be an instance of Fastify. As a user, you can't assume that.

**Comment by mcollina** [comment]
@Ethan-Arrowood this seems typed correctly in here: https://github.com/fastify/fastify/blob/fbe073884494676419ac5f5ba7c44ad0054a3abe/types/plugin.d.ts#L12, or am I reading this wrong?

**Comment by Ethan-Arrowood** [comment]
Yes you're correct @mcollina , it is correctly typed. I don't why @wolfejw86 code-sense is saying that is `any`; i'll need to investigate that further. Still requires some better documentation imo

**Comment by wolfejw86** [comment]
Yes, I get it needs to be a "generic" fastify instance but it seems wrong to be typed as `any` right?

**Comment by mcollina** [comment]
@wolfejw86 this seems typed correctly here, see https://github.com/fastify/fastify/blob/fbe073884494676419ac5f5ba7c44ad0054a3abe/types/plugin.d.ts#L12. Apparently this does not work as expected.

**Comment by wolfejw86** [comment]
Oh I see.  I will continue to take a look at it as well.

**Comment by mcollina** [comment]
@wolfejw86 if you would like to send a PR, it would be awesome.

**Comment by wolfejw86** [comment]
This one was slightly tricky.  After some more investigation, I noticed the following conflicting definition with the `fastify-swagger` package - I got there while trying to type out `FastifyInstance` manually - 

fastify 3.0
![image](https://user-images.githubusercontent.com/22133869/87221350-639ce400-c339-11ea-8bc1-e59b745c9638.png)
fastify-swagger 3.1.1
![image](https://user-images.githubusercontent.com/22133869/87221358-78797780-c339-11ea-8f62-9c080ad894f8.png)

I _think_ it's possible that these declarations conflict enough that the TS Language server is only able to type it as any.

See what happens when I put a guard statement and then hover over the asserted type:
![image](https://user-images.githubusercontent.com/22133869/87221453-1705d880-c33a-11ea-8490-e82859f09e7f.png)

Remembering what @Ethan-Arrowood said above, I _think_ this is _mostly_ expected, however I really wish there was a better way to assert which "type" of `FastifyInstance` is coming into this function.  It does seem like there is a frustrating side affect that it is making me "choose" between declarations, when instead what I really want is a nice merge of the types. As is, I could see it being a rather frustrating and verbose experience to filter out all the different typed variations AND only be able to reference a single augmentation of the `FastifyInstance` type when there are lots of times I would want to reference _both_ of these types together.

I'm unsure of the best path forward, because upon further investigation, even with a guard statement, it still lets me reference both types:
![image](https://user-images.githubusercontent.com/22133869/87221603-4537e800-c33b-11ea-8b2e-fa2121e72881.png)
which can't be right because `.swagger` does not exist on the base fastify one and I just asserted above that it was not present with a guard statement.  

What do other people think?

**Comment by mcollina** [comment]
> if you're using Typescript you will have to upgrade all fastify ecosystem modules at once or accept the type as any until you have time to upgrade them all.

I would recommend that, yes.

**Comment by fox1t** [comment]
@wolfejw86 unlucky (or not?) there is no way that you can use older plugins on the > 3.0.0 fastify version. Witch TS 3.9 is even harder to have intersection mismatch since it is more strict when checking them. Try to update all plugins and please report back if you still have issues :)

**Comment by wolfejw86** [comment]
Yep already done and it’s working as expected now. Now I just need to address why fastify-autoload is being so strict with how it allows typescript but that doesn’t belong here 😅

Is there a WIP documentation somewhere that we can add this information to? It may be more obvious to others but definitely wasn’t to me

**Comment by mcollina** [comment]
We should include it in the blog post and the release notes.

cc @delvedor.

**Comment by mcollina** [comment]
@fastify/typescript is this something you plan to address? This has been open for a while.

**Comment by fox1t** [comment]
I think this issue was just due to the change that TS introduced in 3.9 version.
The specific issue was fixed, as far as I know.

We should close this.
