### ISSUE TITLE
Improve documentation on plugins with TypeScript

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2398]
ref #2397 (but also multiple other issues and prs i'll try to dig up later)

~We need to improve the documentation around plugins and typescript. some decisions have been made around why the instance type is as generalized as it is, and the docs do not reflect that decision nor give the user the recommended solution. I'm assigning this to myself and will contribute the change next week.~

Update, there is outstanding work on plugins in Fastify around CJS/ESM + other things. I will let those items continue first and then revisit this documentation addition later

**Comment by Ethan-Arrowood** [comment]
Related: https://github.com/fastify/fastify/pull/2350

**Comment by fox1t** [comment]
I am not sure if the instance is really any. Can you provide a reference of the definition here?

**Comment by Ethan-Arrowood** [comment]
Sorry you're right. Ammending that now!

**Comment by weiliddat** [comment]
Hey @Ethan-Arrowood do you need help here? I was already dealing with plugin types on some projects, between using TS in fastify 2 and fastify 3.

Though as of now, declaring a plugin as a `FastifyPlugin` seems to give the right type for the `FastifyInstance` passed into the function to be called.

![image](https://user-images.githubusercontent.com/899658/90334667-9dfc3f80-dfcf-11ea-890e-680c6ec10120.png)

**Comment by mcollina** [comment]
I think this might be mostly done now.

cc @fox1t

**Comment by Ethan-Arrowood** [comment]
Yes I believe so too. Feel free to close if we are all happy with the new documentation contributions!

**Comment by fox1t** [comment]
I agree that this is ok for the moment.
