### ISSUE TITLE
Querystring schema as real json schema

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#240]
As title.

I'd like to remove extra query parameters using the `additionalProperties: false` ajv configuration set using the custom schemaCompiler.
Currently it is not possible.

**Comment by mcollina** [comment]
Would this be solved by https://github.com/fastify/fastify/pull/187? 

cc @StarpTech

**Comment by allevo** [comment]
I mean
```
{
  type: object,
  required: [ ... ],
  properties: { ... },
  additionalProperties : false
}

**Comment by StarpTech** [comment]
@allevo I also don't get your point. Do you mean we should add `removeAdditional: true` to the default configuration of Ajv?

**Comment by allevo** [comment]
Sorry my bad, the fibers raise... Closed
