### ISSUE TITLE
Fastify v3 register() scope seems to be wrong?

### ISSUE THREAD

**Issue by huming2207** [fastify/fastify#2406]
## 🐛 Bug Report

Hi there,

Firstly, again, here's my repo: https://github.com/huming2207/datasheep-api

It has these handlers with this kind of hierarchy:

- `AuthHandler`
- `ProtectedRequests`
  - `ProjectHandler`
  - `KanbanHandler`
  - `EventHandler`

In the `ProtectedRequests`, it has an `onRequest` hook for verifying JWT token in the beginning, then register the three other protected handlers. See here: https://github.com/huming2207/datasheep-api/blob/master/src/handlers/ProtectedRequests.ts

What happened is that if I add the `server.register(ProtectedRequests, { prefix: "/api" })`  in the server builder function (ref: https://github.com/huming2207/datasheep-api/blob/master/src/common/Server.ts#L60), it will ignore this `/api` prefix. You can see on the swagger panel it will be like this:

![image](https://user-images.githubusercontent.com/4463497/87237441-a7771280-c439-11ea-80e7-6ea88ead25ab.png)

But meanwhile, if I move the prefix setting **inside** of `ProtectedRequests` for each protected handler's registration, it works fine:

![image](https://user-images.githubusercontent.com/4463497/87237465-ee650800-c439-11ea-9de6-b8f49b65e2dc.png)

Is this a bug, or a new change in the Fastify v3? Please point it out if I made any mistakes. Thanks.

Regards,
Jackson

## Your Environment

- *node version*: 12.18
- *fastify version*: 3.0.2
- *os*: Linux
- TypeScript: 3.9.2

**Comment by mcollina** [comment]
Is this a problem only with fastify-oas or the with the actual routing?

**Comment by mcollina** [comment]
Confirmed, this a is a bug in the new `await app.register()` support. if you remove `await app.register()` and just do `app.register()` if should all work well.

**Comment by huming2207** [comment]
Hi @mcollina yes I think it's a `register()`'s bug, not fastify-oas's bug.

I've also tried disabling the fastify-oas and problem still exists.

Jackson

**Comment by mcollina** [comment]
as I said, you can sidestep this by removing the `await` in front of `app.register()`, it should unblock you.

**Comment by mcollina** [comment]
I'll work on a fix

**Comment by huming2207** [comment]
> as I said, you can sidestep this by removing the `await` in front of `app.register()`, it should unblock you.

Yep understood. I was also typing that reply when you sent yours. 😀

**Comment by mcollina** [comment]
You can update your dependencies, avvio@7.1.1 fixes this.

Good spot!

**Comment by huming2207** [comment]
@mcollina Thanks! I can confirm it's fixed!
