### ISSUE TITLE
Add validationErrors property to request object when using attachValidation option

### ISSUE THREAD

**Issue by pruginkin** [fastify/fastify#2409]
![Screenshot_20200714_010820](https://user-images.githubusercontent.com/51276573/87358612-d8a52f00-c56e-11ea-9498-02b4da840a00.png)

* *fastify version*: >=3.0.2
* *os*: Linux

**Comment by pruginkin** [comment]
If I add type any - the error disappears
![Screenshot_20200714_130239](https://user-images.githubusercontent.com/51276573/87413426-f7d5a800-c5d2-11ea-93e5-abf9db9b456e.png)

**Comment by Ethan-Arrowood** [comment]
One (complex) solution idea here is to create an extended interface of the existing request object types that is loaded when a route options object contains that property. This will use discriminant unions I believe. 

One (less complex) solution is to just add `validationErrors` as an optional property to the request object and add a comment that in order for it to be used the user should ensure they have set the `attachValidation` option. This is less safe but i understand it may be worth the trade off from the complexity of previous solution idea.

**Comment by mcollina** [comment]
Both approach seems fine to me.
