### ISSUE TITLE
Cannot listen on a port after closing the server. Error is misleading.

### ISSUE THREAD

**Issue by simihartstein** [fastify/fastify#2411]
## 🐛 Bug Report

I am trying to temporarily swap out my main fastify server instance with a maintenance server while I handle some background processes.
When I try to swap back to my main server that was previously closed, it throws an error saying `Fastify is already listening`

I'm not sure if this is a bug or not supported since the documentation is unclear.

I have already worked around this by migrating the maintenance logic to the prehandler. I'm just looking for some clarification on the expected behavior or a clearer error message.

## To Reproduce

Here is a minimal example to demonstrate:

```js
const create= require("fastify");

const mainServer = create();
await mainServer.listen(8080, "0.0.0.0");

const maintenanceServer = create();
await mainServer.close();
await maintenanceServer.listen(8080, "0.0.0.0");

await maintenanceServer.close();
await mainServer.listen(8080, "0.0.0.0");
// throws an error with message 'Fastify is already listening'

```

## Expected behavior

Either `mainServer` starts listening on port 8080 or a message saying that the fastify instance has already been closed and cannot be reopened.

## Your Environment

- *node version*: 12.16.1
- *fastify version*: >=2.3.0
- *os*: Windows

**Comment by zhangwinning** [comment]
```
const create = require('fastify');

(async function f() {
  const mainServer = create();
  await mainServer.listen(8080);

  await mainServer.close();

  await mainServer.listen(8080);
// UnhandledPromiseRejectionWarning: Error: Fastify is already listening
})()

```
node version : 12.18.1
fastify version: master 
os : mac os 

I can reproduce the error through smaller example.

**Comment by zhangwinning** [comment]
I think it's a bug. close the server, when the fastify[kState].listening = true, should modify fastify[kState].listening  = false.  https://github.com/fastify/fastify/blob/733f53544109511d4dd58fedbdb936f86f3b97da/fastify.js#L279 

if I guess it's no problem. I want go it for fix the bug (*❦ω❦).

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? We should throw a better error. Remember to add unit tests.

**Comment by zhangwinning** [comment]
Hey @mcollina , thanks for the answer. I'll try to polish the patch and submit a fix PR.

**Comment by araujo-luis** [comment]
Why isn't it possible to reopen a closed server? any good reason?
