### ISSUE TITLE
duplicated url slashes "//" when register router with prefix

### ISSUE THREAD

**Issue by MomenNano** [fastify/fastify#2414]
## 🐛 Bug Report

duplicated url slashes "//" when register router with empty path `fastify.get('/')` with prefix option set

## To Reproduce
app.js
```js
fastify.register(require('./dir/index.js'), { prefix: 'v1/'})
```
dir/index.js
```js
module.exports = async (fastify, opts) => {
	fastify.get('/', async (req, reply) => {
		reply.send({ works: true })
	})
}
```
## Expected behavior
register only
`/v1`
`/v1/`

## Actual behavior
it register
`/v1/`
`/v1//`
![image](https://user-images.githubusercontent.com/22351955/87581557-6dc43700-c6d9-11ea-8d28-7346cfe1593b.png)

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Windows

**Comment by darkgl0w** [comment]
Hi,

You don't need to put the slash at the end of your prefix ^^
Doing this will work as intended :)
```js
fastify.register(require('./dir/index.js'), { prefix: 'v1'})
```

**Comment by MomenNano** [comment]
I tried it and it works. but this solution will not work with autoload see this [issue ](https://github.com/fastify/fastify-autoload/issues/91), you need -in autoload- to add the end slash or it will merge the two path "v1/ and /test"
![image](https://user-images.githubusercontent.com/22351955/87584957-9d297280-c6de-11ea-86dc-8ae39396bb76.png)

**Comment by darkgl0w** [comment]
Can you set a repo that I can clone to reproduce the issue ?

**Comment by MomenNano** [comment]
yeah :),
[Here](https://github.com/MomenNano/fastify-reproduce)

**Comment by MomenNano** [comment]
I'm ready and will be happy to send a PR to fix this issue, if you confirm it's a bug

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/issues/2414#issuecomment-658947411 this problem is definitely in autoload. The / should not be needed.

**Comment by darkgl0w** [comment]
Hello,

your issues should be solved with this [PR](https://github.com/fastify/fastify-autoload/pull/94) :smiley:
