### ISSUE TITLE
Move ip, ips and hostname from fields in Request to getters

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2416]
## 🚀 Feature Proposal

In https://github.com/fastify/fastify/blob/d06287a9a612d218d26e3a94b248b5035d5c44cb/lib/request.js#L27-L29 there are the `ip`, `ips` and `hostname` properties that are currently set to `null`. Those are 3 pointers of 64 bytes each that we are carrying around with no specific needs as most code does not need them.

Those are defined and set in https://github.com/fastify/fastify/blob/bf18412f2ba838fc06e3162a13ebcf88b5a283be/lib/route.js#L304-L315.

I recommend that we move those definitions to getters similar to https://github.com/fastify/fastify/blob/bf18412f2ba838fc06e3162a13ebcf88b5a283be/lib/request.js#L36-L58. In order to support the `trustProxy`, I recommend those definitions to be overridden with another `Object.defineProperty()`.

Note that the logger use them: https://github.com/fastify/fastify/blob/bf18412f2ba838fc06e3162a13ebcf88b5a283be/lib/logger.js#L54-L55

**Comment by jsumners** [comment]
I'm okay with them being getters. But I want them to continue being present. They are used quite frequently by people that need to verify the advertised source of requests, e.g. those who need to comply with GDPR or CCPA.

**Comment by mcollina** [comment]
They should not go anywhere.

**Comment by paolochiodi** [comment]
I can work on a PR for this

**Comment by delvedor** [comment]
@paolochiodi go for it! 🚀
