### ISSUE TITLE
Support for Socket.io ?

### ISSUE THREAD

**Issue by DouglasHennrich** [fastify/fastify#242]
There's a way to support socket.io? O saw that there's an websockets module, but I guess it doesn't work with `Socket.io`

Thanks and awesome project 👏

**Comment by chymz** [comment]
Maybe, you can try this : 

```js
const app = require('fastify')();
const io = require('socket.io')(app.server);

io.on('connection', function (socket) {
  socket.on('message', function () { });
  socket.on('disconnect', function () { });
});

app.listen(300);
```

**Comment by mcollina** [comment]
I'm not very conformtable with socket.io as a technology. Most browsers now supports websockets, why socket.io?

**Comment by DouglasHennrich** [comment]
@mcollina My current server it's based on socket.io instead of websockets... that's why I'm asking for it so I can move my backend to `Fastify`.

@chymz I guess this works! Thanks 🙌

**Comment by VeegaP** [comment]
@DouglasHennrich do you have a working sample using the snippet @chymz shared?

**Comment by shanurrahman** [comment]
```
const fastifyPlugin = require('fastify-plugin');
const SocketIOServer = require('socket.io');

/**
 * Create a new Socket.io server and decorate Fastify with its instance.
 * @param {Object} fastify - Fastify instance
 * @param {Object} options - Plugin's options that will be sent to Socket.io contructor
 * @param {Function} next - Fastify next callback
 */
function fastiySocketIo(fastify, options, next) {
  try {
    //   can also be called without using the new keyword, internal implementation
    // looks like   if (!(this instanceof Server)) return new Server(srv, opts);
    // first argument takes the server being used, could be http server express server or anything
    // options are the options for fastify server, so now we can simply change the option and that takes
    // affect everywhere
    const io = new SocketIOServer(fastify.server, options);

    // use io wherever you want to use socketio, just provide it in the registration context
    fastify.decorate('io', io);

    next();
  } catch (error) {
    next(error);
  }
}

module.exports = fastifyPlugin(fastiySocketIo, {
  name: 'fastify-socket.io',
});

```

**Comment by Eomm** [comment]
@shanurrahman would you mind publishing a plugin for this code? 💪

**Comment by bluebrown** [comment]
> @shanurrahman would you mind publishing a plugin for this code? 💪

You really want to add a dependency to your project for this? Its litterrally a wrapper around two lines of code. Retrieving the server and passing the server to socket.io. Fastify is using just the standard server under the hood and that is what socket.io expects as argument.

**Comment by afenghy** [comment]
> websockets

Mobile devices is not supports **websockets** , I tried longtime ago.

**Comment by mcollina** [comment]
According to https://caniuse.com/#feat=websockets websockets are available everywhere.

**Comment by ferco0** [comment]
Some mobile networks don't allow websocket connections.
