### ISSUE TITLE
Refactor internals

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2423]
## 🚀 Feature Proposal

I think we should plan for our a refactor of Fastify internals. Currently the `lib/` folder is really hard to understand for newcomers. I also find it hard to understand if I need to edit `lib/route.js` `lib/handleRequest.js` `lib/server.js` or maybe just `fastify.js`. Most of the time, I need to edit a few of those at the same time.

Fastify grew organically.. maybe it's time for some redesign (there is also a lot of code in `fastify.js` that we should move outside.

---
- [x] Extract the logic that handles 404s from [fastify](https://github.com/fastify/fastify/blob/master/fastify.js#L462-L513) to its own file

**Comment by jsumners** [comment]
Agree.

**Comment by Ethan-Arrowood** [comment]
This seems very inline with the already in progress refractors of error, warning, etc.

**Comment by zekth** [comment]
Do you have an idea of scaffolding? Move the content of `fastify.js` to `lib/factory.js` for example?

**Comment by mcollina** [comment]
> Do you have an idea of scaffolding? Move the content of fastify.js to lib/factory.js for example?

I think that would be the very last step.

Something that can be done now is to extract the logic that handles 404s from https://github.com/fastify/fastify/blob/master/fastify.js#L462-L513 to its own file.

Also create some internal doc on the responsibility of all the fies.

**Comment by RafaelGSS** [comment]
I'm strongly +1 on this. Maybe, we can create a tracking issue for these paths?

**Comment by mcollina** [comment]
Feel free to edit the this one at the top!

**Comment by RafaelGSS** [comment]
We should keep it open? If yes, any idea to add to the tracking issue at the top?

**Comment by mcollina** [comment]
Ok for me!
