### ISSUE TITLE
ValidationErrors without validationContext

### ISSUE THREAD

**Issue by lu-zen** [fastify/fastify#2430]
## 🐛 Bug Report

Validation errors from a custom validator (yup in the case) aren't wrapped with a validationContext.

## To Reproduce

1. error throws inside a custom validator
```ts
// ...
    try {
      const result = (schema as Schema<unknown>).validateSync(data, yupOptions);
      return { value: result };
    } catch (e) {
      return { error: e };
    }
```

2. the validation error reaches this function
https://github.com/fastify/fastify/blob/a2a3726d7f932fa3a03f92900561ddd0d2a9b19f/lib/validation.js#L97-L105

3. return without context (instance of Error)
![image](https://user-images.githubusercontent.com/11050840/88141729-8ac1a400-cbca-11ea-9faa-a0380646ca58.png)

## Your Environment

- *node version*: 12.17.0
- *fastify version*: >=3.1.1
- *os*: Linux

**Comment by Eomm** [comment]
> return without context (instance of Error)

Where do you want to read that field?
In the response or in a custom error handler?

**Comment by lu-zen** [comment]
> > return without context (instance of Error)
> 
> Where do you want to read that field?
> In the response or in a custom error handler?

Custom error handler

**Comment by Eomm** [comment]
You can write:

```
  validatorCompiler: ({ schema, method, url, httpPart }) => {
    return function (data) {
      try {
        const result = schema.validateSync(data, yupOptions)
        return { value: result }
      } catch (e) {
        e.validationContext = httpPart
        return { error: e }
      }
    }
  }
```

We should think if we could improve this code as you pointed out:

```
 function wrapValidationError (result, dataVar) { 
   if (result instanceof Error) { 
     return result 
   } 
```

The logic was to don't change the original `Error` here

**Comment by lu-zen** [comment]
Thanks, it works. I think it's good to add the context field into 3rd party Error objects, it's the intended behavior no?

> To help you in writing a custom `errorHandler`, Fastify adds 2 properties to all validation errors:

> * validation: the content of the `error` property of the object returned by the validation function (returned by your custom `schemaCompiler`)
> * validationContext: the 'context' (body, params, query, headers) where the validation error occurred

Or even remove this responsibility from the framework ([formatting custom messages as well](https://github.com/fastify/fastify/blob/a2a3726d7f932fa3a03f92900561ddd0d2a9b19f/lib/validation.js#L122)) and let user add the context manually to catch the error/format the message.

**Comment by bewong89** [comment]
Hello! I'm keen to make my first contribution here and this looks like a something I could do. Is it ok if I take this issue? 

Reading the discussion above it sounds like we want to add the context field into the error object as it sounds like a bug that it's not here (according to the docs). Is that right?
