### ISSUE TITLE
Parametric routes length

### ISSUE THREAD

**Issue by dractw** [fastify/fastify#2436]
## 🐛 Bug Report

Sometimes parametric routes with long params returns `404`, but if param is several times shorter - all goes ok.

## To Reproduce

```js
fastify.get('/route/:id', (req, res) => {
  res.send(`Requested id: ${req.params.id}`)
}
```

Request: 
`
curl "http://localhost:3000/route/DdzFFzCqrhsjpg5q8KXsB2dkCRinth9h5DSaFQjmVkN9EQASkSfWLJ8S8hNac53JDFMJmSFNxCo3UutQGpQP55gPHfmASrqZ3XxdbjQX"
`

Response:
```{"message":"Route GET:/route/DdzFFzCqrhsjpg5q8KXsB2dkCRinth9h5DSaFQjmVkN9EQASkSfWLJ8S8hNac53JDFMJmSFNDxCo3UutQGpQP55gPHfmASrqZ3XxdbjQX not found","error":"Not Found","statusCode":404}```

## Expected behavior

Requested id `DdzFFzCqrhsjpg5q8KXsB2dkCRinth9h5DSaFQjmVkN9EQASkSfWLJ8S8hNac53JDFMJmSFNxCo3UutQGpQP55gPHfmASrqZ3XxdbjQX` returns from response.
 
## Your Environment

- *node version*: 12.18.1-alpine3.12
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by jsumners** [comment]
This is documented https://github.com/fastify/fastify/blob/master/docs/Server.md
