### ISSUE TITLE
TypeScript: addHook'a 'onSend' callback typings

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify#2439]
## 🐛 Bug Report

addHook('onSend') disallows next() without arguments.
## To Reproduce

```
  fastify.addHook('onSend', function (_request, reply, payload, next) {
    Object.assign(reply.res, { payload })
    next() // <--- error
  })
```

Error:

```
Expected 1-2 arguments, but got 0.
hooks.d.ts[93, 41]: An argument for 'err' was not provided.
```
## Expected behavior

Code compiles, payload not modified.

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.3
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
