### ISSUE TITLE
Empty array as default value in schema doesn't work

### ISSUE THREAD

**Issue by komarnitskyi** [fastify/fastify#2440]
## 🐛 Bug Report

When I use an empty array `[]` as default value for some field, the one is not present in response at all.
When I use any other value - everything works fine. Field returned with defined default value.

## To Reproduce

- Create response schema with at least one field:
```js
S.object()
    .prop('adminSettingsId', S.array().default([]).items(S.string()))
```
- In route handler return  `adminSettingsId: undefined`

## Expected behaviour

`adminSettingsId` has to be present in response with `[]`  as a value

## Actual behaviour
`adminSettingsId` is not present in response at all

## Your Environment

- *node version*: 13.13.0
- *fastify version*: ^2.13.0
- *os*: Mac
- "fluent-schema": "^0.10.0"

**Comment by Eomm** [comment]
Could you add a complete example?

I cannot reproduce with this code (since the serialization is done with FJS)

https://runkit.com/embed/ee7i7u9m1ob1

```
var fastJson = require("fast-json-stringify@1.21.0")

const stringify = fastJson({
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    adminSettingsId: {
      type: 'array',
      default: [],
      items: { type: 'string' }
    }
  }
})

stringify({})

```

**Comment by Eomm** [comment]
fast-json-stringify works https://runkit.com/embed/ukgc7l3kdgld

The issue is that the generated schema doesn't contain the `default` keyword

```
console.log(JSON.stringify(S.object().prop('templates', S.array().items(consentTemplateSchema)).valueOf(), null, 2))
```

It seems a fluent-schema issue /cc @aboutlo

**Comment by Eomm** [comment]
@komarnitskyi I just found that the issue is related to fluent-schema but v1.0.2 fix it.
So you need to update that module to solve.
