### ISSUE TITLE
hasContentTypeParser does not know about buildin parsers

### ISSUE THREAD

**Issue by seriousme** [fastify/fastify#2448]
## 🐛 Bug Report

The [documentation](https://www.fastify.io/docs/latest/ContentTypeParser/) says that hasContentTypeParser() can be used to check if a specific content type parser is available.
This works for parsers you add yourself but not for parsers already build in: `application/json` and `text/plain`

## To Reproduce

```js
// Require the framework and instantiate it
const fastify = require('fastify')({
    logger: true
  })
  
  // Declare a route
  fastify.get('/', function (request, reply) {
    reply.send({ hello: 'world' })
  })

  // check which content type handlers are available
  const mimeTypes = [ 'application/json', 'text/plain', 'multipart/form-data' ];
  mimeTypes.forEach(item => {
    console.log(item, fastify.hasContentTypeParser(item))
  })
  // Run the server!
  fastify.listen(3000, function (err, address) {
    if (err) {
      fastify.log.error(err)
      process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
  })
```

## Expected behavior

Based on https://github.com/fastify/fastify/blob/af77198d0e7c290cd74286fba1e804ce62e4b54d/lib/contentTypeParser.js#L30-L32 I expect to see:
```js
application/json true
text/plain true
multipart/form-data false
```
But I get:
```js
application/json false
text/plain false
multipart/form-data false
```

## Your Environment

- *node version*: 10
- *fastify version*: >=3.1.1
- *os*: Linux
- *any other relevant information*: none

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by seriousme** [comment]
I'm happy to give it a go, but the question is what logic you want to retain ? 

Currently you can't override any parsers you have added yourself:

https://github.com/fastify/fastify/blob/af77198d0e7c290cd74286fba1e804ce62e4b54d/lib/contentTypeParser.js#L36-L43

but you can override the build in ones as hasParser contains special logic to differentiate between native and custom:

https://github.com/fastify/fastify/blob/af77198d0e7c290cd74286fba1e804ce62e4b54d/lib/contentTypeParser.js#L69-L77

Is this the behaviour you want to keep or should it be possible to override custom parsers as well ?

I also noticed that there is another exception made for `application/json` that is not made for `text/plain` 
https://github.com/fastify/fastify/blob/af77198d0e7c290cd74286fba1e804ce62e4b54d/lib/contentTypeParser.js#L58-L66
and I was wondering whether that was intentional ?

Kind regards,
Hans

**Comment by mcollina** [comment]
> Is this the behaviour you want to keep or should it be possible to override custom parsers as well ?

Yes

> I also noticed that there is another exception made for application/json that is not made for text/plain
https://github.com/fastify/fastify/blob/af77198d0e7c290cd74286fba1e804ce62e4b54d/lib/contentTypeParser.js#L58-L66
and I was wondering whether that was intentional ?

Yes

**Comment by RafaelGSS** [comment]
Closing since PR was merged. Feel free to open if it not solve all the issue.
