### ISSUE TITLE
Unable to send a boolean

### ISSUE THREAD

**Issue by JbIPS** [fastify/fastify#245]
Hi,

I'm playing around with this great lib but I went into a bit of trouble while migrating: I can't send correctly a boolean.
```javascript
fastify.get('/is-everything-great', {
  schema: {
    response: {
      200: { type: 'boolean'}
    }
  }
}, async(req, res) => {
   // Get a boolean
  const isEverythingGreat = await getFeelings();
  res.send(isEverythingGreat);
}
```

This returns an empty payload (surely because of https://github.com/fastify/fastify/blob/master/lib/reply.js#L33).

Is this an accepted behavior? If so, what's the recommendations for this use case? Thank you

**Comment by delvedor** [comment]
Hi, thank you for checking out the project!
The correct way to use ´async/await´ in your case is to return `isEverythingGreat `.
```js
async(req, res) => {
   // Get a boolean
  const isEverythingGreat = await getFeelings();
  return isEverythingGreat
}
```
You also have encountered a problem that we are fixing in https://github.com/fastify/fastify/pull/241, we'll also update the documentation to explain better how use correctly `async/await` functions.
Regarding the `false` payload value I'll make a pr :)

**Comment by JbIPS** [comment]
Thank you @delvedor 

I suppose I could do 
```js
async(req, res) => {
   // Get a boolean
  return getFeelings();
}
```
too?

I'll wait for the merge to try it again 😄

**Comment by delvedor** [comment]
Yes if `getFeelings ` returns a promise!
In the meantime you can checkout our [docs](https://github.com/fastify/fastify/blob/master/docs/Reply.md#promises) :D

**Comment by JbIPS** [comment]
Tried master, it works perfectly! The code is not the only one to be incredibly fast on this project 😉

**Comment by delvedor** [comment]
Ahaha, thanks!! :)
