### ISSUE TITLE
CORS is breaking Schemas

### ISSUE THREAD

**Issue by wandersonwhcr** [fastify/fastify#2462]
#  🐛 Bug Report

If I define a schema inside a plugin, `fastify-cors` breaks the application when `preflight` is enabled.

## To Reproduce

I created a simple repository showing the problem.

https://github.com/wandersonwhcr/fastify-cors-problem

## Your Environment

- *node version*: 14
- *fastify version*: >=3.1.1
- *os*: Linux

**Comment by Eomm** [comment]
> I bet it's tied to #2446

I don't think so because in that case the `addSchema` is not executed so there is a missing reference from `fast-json-stringify` to the custom ajv instance.

I think your last comment on the issue could be a solution

**Comment by jsumners** [comment]
> > I bet it's tied to #2446
> 
> I don't think so because in that case the `addSchema` is not executed so there is a missing reference from `fast-json-stringify` to the custom ajv instance.
> 
> I think your last comment on the issue could be a solution

Yes. I will hopefully get the ability to work on it soon, but it's an unknown.
