### ISSUE TITLE
Validation issue with enum

### ISSUE THREAD

**Issue by JSteunou** [fastify/fastify#2469]
## 🐛 Bug Report

Fastify through an error if the validation schema contains an enum without enforced type.

```
,{"type":"object","properties":{"monitor":{"type":"object","properties":{"status":{"enum":["ok","ko"]}},"required":["status"]}},"required":["monitor"]}
,FastifyError [Error]: Failed building the serialization schema for GET: /check/ready, due to error undefined unsupported
,    at Boot.<anonymous> (/project/node_modules/fastify/lib/route.js:271:19)
,    at /project/node_modules/avvio/boot.js:153:12
,    at Object.onceWrapper (events.js:416:28)
,    at Boot.emit (events.js:322:22)
,    at /project/node_modules/avvio/plugin.js:269:7
,    at done (/project/node_modules/avvio/plugin.js:201:5)
,    at check (/project/node_modules/avvio/plugin.js:225:9)
,    at internal/process/task_queues.js:153:7
,    at AsyncResource.runInAsyncScope (async_hooks.js:185:9)
,    at AsyncResource.runMicrotask (internal/process/task_queues.js:150:8) {
,  code: 'FST_ERR_SCH_SERIALIZATION_BUILD',
,  statusCode: 500
,}
```

## To Reproduce

1. add a route with this validation schema

```js
{
    schema: {
        response: {
            200: {
                type: 'object',
                properties: {
                    monitor: {
                        type: 'object',
                        properties: {status: {enum: ['ok', 'ko']}},
                        required: ['status'],
                    },
                },
                required: ['monitor'],
            },
        },
    },
}
```

## Expected behavior

no error at sever start

## Your Environment

- *node version*:  12.18.3
- *fastify version*: 3.1.1
- *os*: Linux
- *any other relevant information*

The only way to avoid this issue for now is to add a `type: string` along with the enum, but per [the spec](http://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values), `type` is optional and is set only to enforce a certain type along with the enum values. Enum can be mixed type.

This detail seems not that important, but it has a lot when combined to TypeScript and OpenAPI auto generated from the schema.  In this case `status` is shown as `string` instead of `enum` in TypeScript and documentation just to make the schema works for fastify.

**Comment by fox1t** [comment]
I've encountered this error in the past using https://github.com/sinclairzx81/typebox to generate schemas and, yes, it is not compliant with the spec.

**Comment by JSteunou** [comment]
This is exactly while using this library that I  have spotted this error. When you say *it is not compliant with the spec*, do you refer to fastify or typebox?

To me typebox is compliant here, `type: xxx` is not mandatory with `enum` per the spec. It should only be here when you need to enforce a single type within the enum.

**Comment by fox1t** [comment]
I think this is a json-fast-stringify not being compliant to that spec (It is used internally by fastify).

The spec itself is ok.

**Comment by JSteunou** [comment]
Ok I understand better, thank you.

**Comment by fox1t** [comment]
This is the line that has that problem `https://github.com/fastify/fast-json-stringify/blob/master/index.js#L134` Would you like to make a PR?

**Comment by JSteunou** [comment]
I could try, but what should be the `default` then? Should `{enum: [...]}` be a special case, or every object without `type` should have the same logic? For example `{}` which is totally empty and the result of TypeBox `Type.Any()` should throw or pass?

**Comment by JSteunou** [comment]
Naïve question ahead:

Why cannot AJV be used as the serializer instead of fast-json-stringify? Just for speed reasons?

Because testing 

```json
{
    "type": "object",
    "properties": {
        "monitor": {
            "type": "object",
            "properties": {"status": {"enum": ["ok", "ko"]}},
            "required": ["status"]
        },
        "optionalany": {}
    },
    "required": ["monitor"]
}
```

compiles and validates very fine with AJV. As it is already used for input validation, maybe it could be used for output serialisation, would avoid maintenance and double work?

**Comment by jsumners** [comment]
AJV is not a serializer. It is only a validator.

**Comment by JSteunou** [comment]
Makes sense.

I though it, or some part of it, could be reuse for the serialisation part.

**Comment by jsumners** [comment]
Both modules work the same way: they read the JSON Schema DSL and generate code from it. In the case of the serializer, the generated code is a function that "knows" the shape of data to be returned from it. AJV returns a function that verifies the shape is what it is supposed to be. Subtle but significant difference.

**Comment by Eomm** [comment]
> I could try, but what should be the `default` then? Should `{enum: [...]}` be a special case, or every object without `type` should have the same logic? For example `{}` which is totally empty and the result of TypeBox `Type.Any()` should throw or pass?

I think [the spec](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#page-8) helps to decide what to do in these cases.

But we need to remember that we are a **serializer**, not a validator, and if you want to serialize an object you must know what the output is, otherwise we would be like `JSON.stringify()`.

The `enum` aims to **validate** that the output of the server is fine with the schema and for this reason, I would not include the `enum` support to `fast-json-stringify` but I would suggest:

- using [fastify-response-validation](https://github.com/fastify/fastify-response-validation) plugin to accomplish this.
- using the [additional-properties](https://github.com/fastify/fast-json-stringify#additional-properties) configuration.

A final thought: I think we should not crash and manage this special case (object without `type` but with `enum`) as an additional-properties object by default.

```
const fjs = require('fast-json-stringify')

const x = fjs({
  type: 'object',
  properties: {
    kind: { type: 'string', enum: ['foobar'] } // if we remove `type` we should not crash an leave all the feature as is now
  }
})

console.log(x({ kind: 'hello' })) // works
console.log(x({ kind: 'foobar' })) // works as expected
```

**Comment by fox1t** [comment]
@Eomm nice idea! I agree with you!

**Comment by JSteunou** [comment]
Can this issue be re-opened plz?
