### ISSUE TITLE
Support async functions as hooks.

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#247]
As titled.

**Comment by delvedor** [comment]
Just to give an example:

```js
fastify.addHook('preHadler', async (req, reply, next) => {
  // some code
  return // no need to call 'next'
})
```

**Comment by allevo** [comment]
I'm not convinced this can be a good thing. Maintaining multiple interfaces are hard!

**Comment by mcollina** [comment]
@allevo yes, but async/await would be big, and we need to fully support it.

**Comment by delvedor** [comment]
Once https://github.com/fastify/fastify/issues/291 land I'll work on this :)
