### ISSUE TITLE
fastify schema trim not working

### ISSUE THREAD

**Issue by jefjos** [fastify/fastify#2475]
## 🐛 Bug Report

I want to accomplish 2 things with my schema - I want to trim the input and I want to validate that the trimmed input has minLength = 1. I tried all the different configurations I came across for doing this, but none of them have worked so far. I am using fastify version 3.0.0, and I believe it uses ajv validator for doing the transform and validation. The validation part is working, however the trim has not happened.

## To Reproduce

I tried the following schema

```
input: {
            type: "string",
            allOf: [
                {
                  transform: [
                    "trim"
                  ]
                },
                {
                  minLength: 1
                }
            ],
            transform: ["trim"],
            trim: true,
            description: "input",
            minLength: 1,
            maxLength: 3
        }
```

I sent the following request body through Postman
```
{
"input": " "
}

```
## Expected behavior

The request must fail with validation error, since after trimming, input is an empty string and fails the "minLength" validation, but it goes through.

## Your Environment

- *node version*: 14
- *fastify version*: >=3.0.0
- *os*:  Windows

**Comment by mcollina** [comment]
I don't understand what is the `trim` transform. Is this supported by Ajv?

**Comment by jefjos** [comment]
Yes -> https://github.com/ajv-validator/ajv-keywords#transform

**Comment by mcollina** [comment]
Have you added ajv-keywords? https://www.fastify.io/docs/latest/Validation-and-Serialization/#ajv-plugins

Can you include a full example?

**Comment by jefjos** [comment]
Thank you. Adding ajv-keywords fixed it.
