### ISSUE TITLE
Refer to tsconfig/bases in typescript docs

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2476]
## 🚀 Feature Proposal

https://github.com/tsconfig/bases includes the default examples for the fastify configuration. We should recommend it in our typescript documentation, and possibly use the relevant one across all of our plugins.

**Comment by fox1t** [comment]
I think that [node12](https://github.com/tsconfig/bases/blob/master/bases/node12.json) is perfect, not only for us but also for our users.

**Comment by L2jLiga** [comment]
I'm voting for [node10](https://github.com/tsconfig/bases/blob/master/bases/node10.json) due to "engine" property in "package.json"

https://github.com/fastify/fastify/blob/e4d8773421a00ff16290b8f83d7270e931c40513/package.json#L101-L103

**Comment by mcollina** [comment]
I would go with node12, but also node10 is ok.

**Comment by fox1t** [comment]
We can close this since https://github.com/fastify/fastify/pull/2484/files#diff-17177d7eb9ef1a38f00590c051d2b873R41 resolved it.
