### ISSUE TITLE
Wildcard route does not parse semicolon correctly

### ISSUE THREAD

**Issue by adityapatadia** [fastify/fastify#2487]
## 🐛 Bug Report

Wildcard parameter in URL does not parse semicolon correctly.

## To Reproduce

```js
// GET http://localhost:4000/transform/example.com/public/college_data/images/appImage/57950_gcvhjmk,l.;dfrfh.png

fastify.get('/transform/:hostname/*',(req, res)=> {
    let path = req.params["*"];
    // path value is 'public/college_data/images/appImage/57950_gcvhjmk,l.'
    // ideally the path value should be '/transform/public/college_data/images/appImage/57950_gcvhjmk,l.;dfrfh.png'
});

```

## Your Environment

- *node version*: 12.8.3
- *fastify version*: >=3.2
- *os*: Mac, Windows, Linux

**Comment by delvedor** [comment]
Hello! The reason this is happening is that some systems do not follow RFC and separate the path and query string with a `;` character, e.g. `/foo;jsessionid=123456`.
Thus, we need to split on `;` as well as `?` and `#`.
This is the code causing your issue: https://github.com/delvedor/find-my-way/blob/fb334f238e2cbda03a3482dacdea06447185cfe3/index.js#L605-L616

**Comment by adityapatadia** [comment]
Understood, is there any way to prevent this behaviour?

**Comment by adityapatadia** [comment]
How can I encode URL before the route module parses it? Is there any way to achieve with hook?

**Comment by zekth** [comment]
In the current state of art you can't as the routing is the first part of the lifecycle of the request. Your client need to encode the filename before sending the request. eg:
```js
const encoded = encodeURIComponent('57950_gcvhjmk,l.;dfrfh.png');
// 57950_gcvhjmk%2Cl.%3Bdfrfh.png
```

**Comment by adityapatadia** [comment]
My issue is that I don't have any control over request because client requests are directly handled by NodeJS. I would find some other way but, it would be great to get a pre-routing hook which allows this.

**Comment by zekth** [comment]
Look at this workaround so: https://github.com/fastify/fastify/issues/2287#issuecomment-630421865

**Comment by adityapatadia** [comment]
This works! Thanks.

**Comment by delvedor** [comment]
The `preRouting` hook works, but you should really send url encoded request.
In other words, your clients are doing the wrong thing, url should always be encoded :)
