### ISSUE TITLE
doc: Add discord badge

### ISSUE THREAD

**Issue by zekth** [fastify/fastify#2488]
## 🚀 Feature Proposal

To promote the use of discord to make the community grow, the addition of a badge within the others on the README can be a plus. Here is how to setup it : https://shields.io/category/chat 
(needs admin permission to allow it on discord side)

## Motivation

Promote the discord server

**Comment by mcollina** [comment]
I don't know how to do that, there seems to be no instructions there (just the markdown sample). Can you send a PR?
