### ISSUE TITLE
Returned rejected Promise are not catchable

### ISSUE THREAD

**Issue by JbIPS** [fastify/fastify#249]
I know the docs says
```js
var res = await new Promise(function (resolve) {
    setTimeout(resolve, 200, { hello: 'world' })
  })
  // note that we are returning the promise without using '.send()'
  return res
```
but I tried 
```js
return new Promise(function (resolve) {
    setTimeout(resolve, 200, { hello: 'world' })
  })
```
because who needs variables? 

The downside is that if the promise is rejected, even a `try/catch` won't catch it before fastify sends a 500
```js
try {
  return new Promise(function (resolve, reject) {
    setTimeout(reject, 200, { hello: 'world' })
  })
} catch(error) {
  switch(error.message) {
    default: res.code(400).send(err);
}
```
will return a 500. 

I figured out adding `await` makes things OK but I think something's wrong elsewhere. Or is it a tweak for perf?

**Comment by mcollina** [comment]
await is transparent.

Can you try with the master branch? We have just landed #241, which should improve things significantly in this area.

**Comment by JbIPS** [comment]
Same thing on master:
`return await new Promise()` is caught, `return new Promise()` is not

**Comment by mcollina** [comment]
can you please upload a full example, so that I understand what you are trying to do? We might have a bug in the promise error handling.

If you are using async-await, you should be using http://npm.im/make-promises-safe to avoid unhandled rejections.

**Comment by motss** [comment]
@JbIPS Will your code cause any SyntaxError or UncaughtException?

**Comment by mcollina** [comment]
In #252 I've added a test for the case, and it's passing. So maybe I'm not really understanding what's happening here.

**Comment by JbIPS** [comment]
I was adding a failing test case in your branch when it hit me that the problem must be that without `await`, the rejected won't be caught by `try/catch`. 

So it has nothing to do with fastify ! Thank you for your time
