### ISSUE TITLE
Run a lighter benchmark on Pull Requests

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#2497]
## 🚀 Feature Proposal

Hey! I don't know if this has been discussed before, so feel free to close if there is already an issue for that.
How Fastify has a big effort on performance always in the PR's I review I try to check comparison between current PR and the `master`. However, this is a manual job without visibility, could be better transferred to a CI.

Maybe this could have been thought of before, and the big problem is run inside an unexpected machine at Actions as can not provide a consistent result. We have a dedicated server to run the benchmarks? May could be good to work as a remote job.

## Motivation

Reviewing some PR's doing manual jobs to compare is slow and could provide an inconsistent result.

**Comment by Eomm** [comment]
I started here https://github.com/fastify/fastify/pull/2152 with the same target.

The idea was:
- on a `strict` comment
- run benchmark on PR-branch
- run benchmark on master-branch
- post the results in a message

The issue was that the action didn't check out the PR branch cause of `ref`

**Comment by jsumners** [comment]
Dupe: https://github.com/fastify/fastify/issues/1931
https://github.com/fastify/fastify/pull/2152

**Comment by RafaelGSS** [comment]
Oh! I forgot @Eomm, sorry. So, the hacky that @jsumners paste in the PR could work?

Otherwise, we have other options to deal with it?

**Comment by Eomm** [comment]
> Otherwise, we have other options to deal with it?

I think there could be another solution thanks to GH that I wasn't aware 👍 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

From the repo `fastify` you can check out a PR with the snippet:

```
git fetch origin pull/<ID>/head:local-branch-name
```

Since the event has the id that can be referenced with ` ${{ github.event.issue.number }}`

So if we write action like that one I wrote that add some `runs` steps it should be doable.
Notice that `Eomm/action-journalist@v1` is useful only to post back the output of the run, but it is doable with this [snippet too](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token):

```
      - uses: actions/checkout@v2
      - run: |
          npm run benchmark > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
```

**Comment by mcollina** [comment]
The problem of using CI is that CI is virtualized. Actual human-run benchmarks can be more reliable. Using CI would not replace the need for human-based checks :(.

**Comment by jsumners** [comment]
Agreed. The CI run checks are useful to get an idea if something is off. They are not a "true" benchmark run.

**Comment by RafaelGSS** [comment]
If we add self runners this could work?

**Comment by zekth** [comment]
> If we add self runners this could work?

This can add significant load on the runner. I'd suggest to run the benchmark on a label addition by a contributor or something like this. Having it running on each PR is pretty overkill.

**Comment by RafaelGSS** [comment]
Yep. But, the problem is where to run the benchmark, as said in previous answers, using the CI is indeterministic.
