### ISSUE TITLE
shound't serialize payload when preserialize hook return a string

### ISSUE THREAD

**Issue by cage1618** [fastify/fastify#2499]
## To Reproduce

```js
// Paste your code here
fastify.addHook('preSerialization', async (req, reply, payload) => {
  return JSON.stringify(payload);
});


```
I get the response "{\\"data\\":\\"abc\\"}"

## Expected behavior

```js
// Paste the expected results here
{"data":"abc"}
```

## Your Environment

- *node version*: 14
- *fastify version*: 3.2.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by RafaelGSS** [comment]
I don't see any bug here. Could explain the really possible bug here?

**Comment by Eomm** [comment]
[From docs](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#preserialization):

> Note: the hook is NOT called if the payload is a string, a Buffer, a stream or null.

So the `preSerialization` is not called if you write `reply.send('this is a string')` for example.

@cage1618 I think the [`setReplySerializer`](https://github.com/fastify/fastify/blob/master/docs/Server.md#setreplyserializer) would fit your needs
