### ISSUE TITLE
Improve developer experience around server listening

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2500]
## 🚀 Feature Proposal

Document or formalize notifying when the Fastify server is listening for and accepting requests.

## Motivation

I have encountered a need to know when the server is listening for and accepting requests. This is different from our `onReady` hook (which is really `onReadyToListen`). Basic premise is, I have to work with a third party API that requires OAuth 2.0 authorization via the [Authorization Code Grant](https://oauth.net/2/grant-types/authorization-code/) instead of the more desirable [Client Credentials Grant](https://oauth.net/2/grant-types/client-credentials/). As a result, I need to obtain a token upon server start which requires the server to be able to process the callback portion of the ACG flow.

## Example

This is currently achievable by:

```js
async function aPlugin(fastify) {
  // Setup some stuff.

  fastify.server.on('listening', doSomeThings)

  function doSomeThings () {
    // Do some things after the server is accepting connections.

    // For example, the scenario described in this issue might do:
    refreshToken()
      .then((token) => {
        fastify.acgToken = token // Added by a decorator.
        setTimeout(refreshToken, ms('1 hour'))
      })
      .catch((error) => {
        fastify.log.error({ err: error })
        process.exit(1)
      })
  }
}

async function refreshToken() {
  await getToken()
}
```

We should either document this or make it more "Fastify-like" with a proper hook.

**Comment by mcollina** [comment]
what should happen to incoming requests while you process the ACG flow?

**Comment by jsumners** [comment]
If we try to explicitly support this ridiculous use case: the server would only respond to the callback endpoint until a token has been acquired. But I think that is too big of an ask. We just need to document how to use this event or create a hook wrapper on top of it.

**Comment by mcollina** [comment]
Do we really need a hook? I think we should just document the node core event. Remember to not use the `async` function in your example, as there won't be anybody catching it.

**Comment by jsumners** [comment]
Documentation is fine.

**Comment by jsumners** [comment]
@mcollina regarding the async function as the listener callback:

Yeah, I realize that's not right. However, I'm not sure how to resolve this case. I can't do:

```js
const { once } = require('events')

async function aPlugin(fastify) {
  await once(fastify.server, 'listening')
  // Now do the ACG flow
}
```

Because it's a plugin and Fastify needs them to start up in a millisecond or two versus potential literal seconds with the round-trip ACG requests.

**Comment by Eomm** [comment]
If the plugin doesn't start, the `listening` event should never be emitted. Is this snippet working?
Is your token with an expiration?

**Comment by jsumners** [comment]
@Eomm I'm saying the easy fix for leaking an uncaught exception by passing a promise as an event handler does not work here because it would cause the plugin to block the server from finish its load.

**Comment by jsumners** [comment]
I updated the original example with a solution.

**Comment by mcollina** [comment]
Considering your problem, I would:

1. have the `/status` health probe for your LB not go "green" until you have finished the ACG flow
2. store the ACG token in Redis or analog and refresh when needed using some external tool
3. if any of the routes where the ACG token is needed is called while processing the request issue a 503 response so the load balancer can route the request to another server

**Comment by wilkmaia** [comment]
From the comments above I believe the current expectation is to simply document this specific use-case, correct? I'll start working on this issue. Please let me know if I misunderstood things, @mcollina @jsumners.

**Comment by jsumners** [comment]
Yes, documentation is the "answer" here. I think it would be best to create a "guide" for it under our guides documentation.
