### ISSUE TITLE
TypeScript: logger type is being lost in routes

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify#2511]
## 🐛 Bug Report

FastifyInstance is defined as:
```
export interface FastifyInstance<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  Logger = FastifyLoggerInstance
>
```

In most other places when FastifyInstance is returned, Logger type is not propagated and lost.

For example, fastify/types/route.d.ts

```
export interface RouteShorthandMethod<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
/* NO LOGGER */
> {
  <RouteGeneric extends RouteGenericInterface = RouteGenericInterface, ContextConfig = ContextConfigDefault>(
    path: string,
    opts: RouteShorthandOptions<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>,
    handler: RouteHandlerMethod<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>
  ): FastifyInstance<RawServer, RawRequest, RawReply>; /* NO LOGGER */
}
```

^ returned FastifyInstance is using default logger type.

This needs to be checked across entire codebase.

Plugins also augment incomplete type and need to be fixed if fastify core is updated. For example, in fastify-websocket:

```
  interface RouteShorthandMethod<
    RawServer extends RawServerBase = RawServerDefault,
    RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
    RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
/* NO LOGGER */
  > {
    <RequestGeneric extends RequestGenericInterface = RequestGenericInterface, ContextConfig = ContextConfigDefault>(
      path: string,
      opts: RouteShorthandOptions<RawServer, RawRequest, RawReply, RequestGeneric, ContextConfig> & { websocket: true }, // this creates an overload that only applies these different types if the handler is for websockets
      handler?: WebsocketHandler
    ): FastifyInstance<RawServer, RawRequest, RawReply>; /* NO LOGGER */
  }
```

## Your Environment

- *node version*: 12
- *fastify version*: >=3.2.1
- *os*: Mac

**Comment by fox1t** [comment]
Would you like to send a PR to fix this?

**Comment by kibertoad** [comment]
@zmeyc Is this still reproduceable in `next`?

**Comment by d3-fidrya-andrey** [comment]
@kibertoad From what I see in https://github.com/fastify/fastify/blob/next/types/route.d.ts in RouteShorthandMethod, Logger is still not customizable and not propagated to FastifyInstance. All other places where FastifyInstance is used also need to be checked for presence of Logger.

**Comment by zmeyc** [comment]
@kibertoad From what I see in https://github.com/fastify/fastify/blob/next/types/route.d.ts in RouteShorthandMethod, Logger is still not customizable and not propagated to FastifyInstance. All other places where FastifyInstance is used also need to be checked for presence of Logger.

**Comment by rubiagatra** [comment]
Hello @zmeyc, If I want to help with this issue I need to.

1. Logger must be checked across the entire codebase.
2. Add `Logger = FastifyLoggerInstance` to every interface
3. Checkout the plugins that affected

**Comment by jhonrocha** [comment]
This is fixed on v4, soon to be released.
