### ISSUE TITLE
logger customLogLevel as per pino-http

### ISSUE THREAD

**Issue by naseemkullah** [fastify/fastify#2514]
## 🚀 Feature Proposal

Add a `customLogLevel` option to fastify's built-in request logger.

## Motivation

https://github.com/pinojs/pino-http/blob/0b35a2c14de4bbb941f0ac004746e9f8863941c5/logger.js#L70 is  a great configuration option as it allows the user to configure log levels based on criteria such as respone status code.

## Example

Exactly as used in pino-http, NB the end goal is to control verbosity based on response status code for request logs (5xx are always desired, but 2xx only for debugging)

```js
const fastify = require('fastify')({
  logger: true,
  customLogLevel: (res, err) => {
      if (res.statusCode >= 200 && res.statusCode < 300) {
        return 'debug';
      } else if (res.statusCode >= 300 && res.statusCode < 400) {
        return 'info';
      } else if (res.statusCode >= 400 && res.statusCode < 500) {
        return 'warn';
      } else if (res.statusCode >= 500 || err) {
        return 'error';
      } else {
        return 'info';
      }
  },
})
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by naseemkullah** [comment]
Sure @mcollina , but before it seems like we are duplicating more and more from `pino-http`, is there a way to embed `pino-http` in fastify directly?

**Comment by mcollina** [comment]
It's not possible as pino-http works on node core objects. Ours works on fastify objects.

**Comment by zekth** [comment]
Adding this capability in fastify implies checking if the `customLogLevel` method is implemented and use it or not at each request, which in the case of no use would be having a bool test on each request like so:
```js
function onResponseCallback (err, request, reply) {
  if (reply.log[kDisableRequestLogging]) {
    return
  }
  if(log.customLogLevel !== undefined) {
    log.customLogLevel(reply,err)
   return
  }
  var responseTime = reply.getResponseTime()

  if (err != null) {
    reply.log.error({
      res: reply,
      err,
      responseTime
    }, 'request errored')
    return
  }

  reply.log.info({
    res: reply,
    responseTime
  }, 'request completed')
}

```

Wouldn't it be better in this case to use `options.disableRequestLogging` to false and add a hook onResponse like so:
```js
fastify.addHook('onResponse', (request, reply, done) => {
  let lvl
  if (reply.statusCode >= 200 && reply.statusCode < 300) {
        lvl = 'debug';
      } else if (reply.statusCode >= 300 && reply.statusCode < 400) {
        lvl = 'info';
      } else if (res.statusCode >= 400 && reply.statusCode < 500) {
        lvl = 'warn';
      } else if (reply.statusCode >= 500 || err) {
        lvl = 'error';
      } else {
        lvl = 'info';
      }
  reply.log[lvl](....)
  done()
})
```

**Comment by jsumners** [comment]
> Wouldn't it be better in this case to use `options.disableRequestLogging` to false and add a hook onResponse like so:

Agreed.

Closing as this is too costly and is possible with the current API as outlined.

**Comment by naseemkullah** [comment]
Thanks!

Ooc and off topic: why was this not implemented as such for pinohttp? is it because express does not offer a post response mechanism?
