### ISSUE TITLE
Types tests not running

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify#2515]
## 🐛 Bug Report

In commit f47b3d2e174d71c2443c9425cb3eddf7f63815fb there was a switch from eslint to standardjs and TS tests don't seem to do anything since then.
```
-    "lint:typescript": "eslint -c types/.eslintrc.json types/**/*.d.ts test/types/**/*.test-d.ts",
+    "lint:typescript": "standard --parser @typescript-eslint/parser --plugin @typescript-eslint/eslint-plugin test/types/*.ts fastify.d.ts",
```

I'm not sure how to fix this because standardjs is not customizable 'by design'. Possible fix is rolling back to eslint and using eslint-config-standard for base rules, but this won't work with VSCode standardjs plugin.

## To Reproduce

Try introducing a syntax error in test/types/hooks.test-d.ts and run `npm run lint:typescript`, error won't be reported.

## Your Environment

- *node version*: 12
- *fastify version*: >=3.2.1
- *os*: Mac

**Comment by fox1t** [comment]
Actually I suppose that tests still run but linting isn't running. Am I wrong?

**Comment by mcollina** [comment]
> Actually I suppose that tests still run but linting isn't running. Am I wrong?

I think you are correct.

**Comment by Ethan-Arrowood** [comment]
https://standardjs.com/index.html#typescript

Relevant that might help here
