### ISSUE TITLE
TypeScript: hooks types

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify#2516]
## 🐛 Bug Report

In hooks.d.ts:

```
export interface preHandlerHookHandler<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault
> {
  (
    request: FastifyRequest<RouteGeneric, RawServer, RawRequest>,
    reply: FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>,
    done: HookHandlerDoneFunction
  ): Promise<unknown> | void;
}
```

It's not possible to use async function without `done` param as `preHandler` hook. Also I think return value should be `Promise<void>`.

Similar changes need to be made in other hooks.

I can fix this, but need to get tests working first: https://github.com/fastify/fastify/issues/2515
This issue seems to be already partially covered by tests.

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=3.2.1
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by zmeyc** [comment]
Not stale, I'll get back to it soon.

**Comment by weiliddat** [comment]
Wanted to solve this but looks like it's been fixed.

**Comment by RafaelGSS** [comment]
Fixed in https://github.com/fastify/fastify/pull/2615
