### ISSUE TITLE
TypeScript: reply.send validates against argument's type, not route method payload's type

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify#2529]
## 🐛 Bug Report

If RouteShorthand method is configured with a specific Reply type, i.e.

```
interface Topics {
  items: { id: string }[]
}

fastify.get<{
  Reply: Topics
}>('/topics',
    { ... skipped ... },
    async (request, reply) => {
      reply.send({ items: [123] })
    }
)
```

reply.send won't detect a typing error because it uses a type of it's argument, not the type it should be validating against (i.e. Topics).

Using `return` form also doesn't detect the error because it's typed as unknown.

## To Reproduce

Configure Reply and pass incompatible type to reply.send() or return.

## Your Environment

- *node version*: 12
- *fastify version*: >=3.2.1
- *os*: Mac

**Comment by mcollina** [comment]
cc @fox1t @Ethan-Arrowood

**Comment by fox1t** [comment]
Fixed by https://github.com/fastify/fastify/issues/2529
