### ISSUE TITLE
Can I user log4js Record   Log （generated by fast log）

### ISSUE THREAD

**Issue by junbao520** [fastify/fastify#2534]
Can I user log4js Record   Log （generated by fast log）？

can i use log4js instead of fast log?

**Comment by Eomm** [comment]
Yes you can

You need to provide the logger with [this interface](https://stackoverflow.com/questions/55264854/how-can-i-use-custom-logger-in-fastify) as parameter.

[Detailed docs](https://github.com/fastify/fastify/blob/master/docs/Logging.md)

**Comment by josteph** [comment]
hi @Eomm can you confirm if this is working with fastify v3 ?
