### ISSUE TITLE
Fastify lags at "Incoming request"

### ISSUE THREAD

**Issue by hunterInt** [fastify/fastify#2535]
## 🐛 Bug Report

When I make a `POST` request to my Fastify server, oftentimes (but not always even for the same route) Fastify just is stuck at "Incoming request":

![image](https://user-images.githubusercontent.com/14793417/92186861-5241f680-ee15-11ea-91e2-cc4e1c89be89.png)
```
{"level":30,"time":1599180160097,"pid":38047,"hostname":"seaweed","reqId":79,"req":{"method":"POST","url":"/api/deleteSelectedFiles","hostname":"0.0.0.0:3000","remoteAddress":"127.0.0.1","remotePort":41244},"msg":"incoming request"}
cuid:  18:42:40:0980
----cuid---- ckenikspu0026cvlle3bl1yjv

```

This lag takes sometimes 5 or more minutes to get past. I have no idea what is causing this, as I have tested it with multiple browsers and I still run into this "lag" a lot, but not every time. Which makes it very difficult to reproduce. I believe this has something to do with Fastify since I just switched to using Fastify from Express and only now am I getting the lag. 

Sometimes when I make other requests to the server while the server is stuck at "incoming request", it "un-lags" itself and finishes the request. 

Example route: 

```
fastify.post('/deleteSelectedFiles', {}, async (req, reply) => {
	console.log('---here I am---');

	const decodedToken = await verifyAuthentication(req, reply);

	//more code etc...
});
```
The console logs `"incoming request"` and is stuck there, but never writes `---here I am---` until several minutes later when it is no longer "stuck". So something somewhere between the `incoming request"` and the `---here I am---` causes the lag.

Any ideas what might be causing this? Or what I could do to trace what is "lagging"?

## To Reproduce

Here is my set-up. I don't know if you will be able to reproduce or not, but if someone could point me to how I should debug this that would be great (I've spent weeks trying to debug it as it is so it's time I ask for some help):

```js
const http2https = require('fastify-http2https');

let fastifyOptions = {
	http2: true,
	logger: true,
	trustProxy: false,
	bodyLimit: 10 * 1024 * 1024, //10MBs
	serverFactory: http2https()
};

let keyPath = path.join(__dirname, '/key.pem');
let certPath = path.join(__dirname, '/cert.pem');

fastifyOptions.https = {
	allowHTTP1: true, //fallback support for HTTP1
	key: fs.readFileSync(keyPath),
	cert: fs.readFileSync(certPath)
};

const fastify = require('fastify')(fastifyOptions);

async function main() {
	await fastify.register(require('middie'));

	fastify.register(helmet);

	fastify.register(require('fastify-cors'), {
		origin: true
	});

	const cuid = require('cuid');

	fastify.use((req, res, next) => {
		req.requestId = cuid();
                console.log('cuid: ', moment().format('HH:mm:ss:SSSS'));
		console.log('----cuid----', req.requestId);
		next();
	});

	const authenticate = {
		realm: 'Westeros'
	}
	fastify.register(require('fastify-basic-auth'), {
		validate,
		authenticate
	});

	fastify.register(require('fastify-static'), {
		root: path.join(__dirname, 'dist'),
		wildcard: false, //Server all *files* in dist folder
	});

	//Server all *routes* that match "/" (AKA front-end SPA routes)
	fastify.get('/*', {}, async (req, reply) => {
		reply.sendFile('index.html');
	});

	//API routes
	fastify.register(
		function (instance, opts, next) {
			require('./app/routes');

			next();
		}, {
			prefix: '/api'
		});

	//Creates an HTTP/2 server
	fastify.listen(consts.port, '0.0.0.0');
}

main();
```

`/app/routes`:

```
fastify.post('/deleteSelectedFiles', {}, async (req, reply) => {
	console.log('---here I am---');
	//more code etc...
});
```

Front-end fetch code:
```
var myHeaders = new Headers();
myHeaders.append("token", "abc123");

var requestOptions = {
	method: 'POST',
	headers: myHeaders,
	redirect: 'follow'
};

fetch("https://0.0.0.0:3000/api/deleteSelectedFiles", requestOptions)
	.then(response => response.text())
	.then(result => console.log(result))
	.catch(error => console.log('error', error));
```

## Expected behavior

No lagging.

## Your Environment

- *node version*: 12.15.0
- *fastify version*: >=3.3.0
- *os*: Ubuntu 20

**Comment by zekth** [comment]
Sorry but this looks incomplete to me. Have you tried to look into your `auth` hooks for `authenticate` and `validate` ?

**Comment by Eomm** [comment]
I would check with [`clinic flame myserver.js`](https://clinicjs.org/flame/) where the code is stuck to understand where to focus

**Comment by jsumners** [comment]
I would use the https://nodejs.org/dist/latest-v12.x/docs/api/perf_hooks.html API to liberally coat the affected code path with metrics to determine where the code is getting stalled.

https://medium.com/the-node-js-collection/timing-is-everything-6d43fc9fd416
