### ISSUE TITLE
definition for request hostname is incorrect

### ISSUE THREAD

**Issue by cmawhorter** [fastify/fastify#2538]
## 🐛 Bug Report

in the docs request `hostname` is defined as providing the hostname -- which is very incorrect for [what it actually does](https://github.com/fastify/fastify/blob/f2982a245e55f6c9d0a88837434e8423db6cc0ae/lib/request.js#L74-L81). 

what it actually does:
- if request.headers['x-forwared-for'] exists, the value is returned. (i believe this could be an array?)
- host header as-is (so it's returning "host" and not "hostname")
- if no host header exists, [return ":authority"](https://github.com/fastify/fastify/issues/2112)

so, the one thing request.hostname doesn't do is return the hostname.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by zekth** [comment]
This case is only when you're using `trustProxy` attribute  otherwise it uses this code:
https://github.com/fastify/fastify/blob/f2982a245e55f6c9d0a88837434e8423db6cc0ae/lib/request.js#L129-L133

**Comment by cmawhorter** [comment]
so that's true about x-forwarded-host (shame on me for not looking at context) but it remains true the host is not the hostname and probably worth mentioning in the docs. 

i can send a PR to change it to "'host' or ':authority' header value or (if one exists)", if you'd like

**Comment by mcollina** [comment]
Also mention `trustProxy`. 

Thanks!

**Comment by rubiagatra** [comment]
so the PR should update the definition of hostname in this https://github.com/fastify/fastify/blob/main/docs/Request.md, right? @mcollina @cmawhorter.

I can help with this

**Comment by mcollina** [comment]
Yes, thanks!
