### ISSUE TITLE
Adding content type parser not accessible while route is called even though addContentTypeParser called

### ISSUE THREAD

**Issue by CodeAnomalies** [fastify/fastify#2551]
## 🐛 Bug Report

After calling addContentTypeParser for 'application/x-www-form-urlencoded' it still give error of `Unsupported Media Type: application/x-www-form-urlencoded`

## To Reproduce

fastify v3.3.0

My file:

```
const qs = require('qs');
const fastify = require('fastify')({
  logger: true
})

fastify.get('/', function (request, reply) {
  reply.send({ hello: 'world' })
})

fastify.post('/test', function (request, reply) {
  reply.send({ hello: 'world' })
})

fastify.addContentTypeParser('application/x-www-form-urlencoded', function (
    request,
    payload,
    done
  ) {
    var body = '';
    request.on('data', function (data) {
      body += data;
    });
    request.on('end', function () {
      try {
        const parsed = qs.parse(body);
        done(null, parsed);
      } catch (e) {
        done(e);
      }
    });
    request.on('error', function () {
      done();
    });
  });

if (!fastify.hasContentTypeParser('application/x-www-form-urlencoded')) {
    console.log('Not Added'); // This is not printed so it is added
  }

fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

When calling `/test` with `Content-Type: application/x-www-form-urlencoded` body: `id=564160757931&name=ironman` I get and error `Unsupported Media Type: application/x-www-form-urlencoded`.

## Expected behavior

I should not be getting `Unsupported Media Type: application/x-www-form-urlencoded` and my route should receive parsed request.

## Environment

- *node version*: 12
- *fastify version*: =3.3.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you mind to add a script to execute to reproduce the problem? curl or node.js would be ok, thx.

**Comment by mcollina** [comment]
You should probably define your content type parser before your post route.

**Comment by CodeAnomalies** [comment]
@mcollina defining  content type parser before post route did not change anything.

curl -d "param1=value1&param2=value2" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:4000/test

`fastify.hasContentTypeParser('application/x-www-form-urlencoded')` return `true` so it is added.

When request arrives I believe it tries to parse at that time `this.customParsers['application/x-www-form-urlencoded']` is `undefined` in `ContentTypeParser.prototype.getParser` function in `/lib/contentTypeParser` which is called from `ContentTypeParser.prototype.run` from same file. I believe this is causing the issue.

```
ContentTypeParser.prototype.getParser = function (contentType) {
  for (var i = 0; i < this.parserList.length; i++) {
    if (contentType.indexOf(this.parserList[i]) > -1) {
      var parser = this.customParsers[this.parserList[i]]
      this.cache.set(contentType, parser)
      return parser
    }
  }

  return this.customParsers['']
}
```

**Comment by CodeAnomalies** [comment]
@mcollina I tried using `fastify-formbody` also but getting same response in that too.

**Comment by mcollina** [comment]
You are sending your payload to the wrong port... you are listening to 3000 not 4000.

The following works as expected:

```js
const qs = require('qs');
const fastify = require('.')({
  logger: true
})

fastify.get('/', function (request, reply) {
  reply.send({ hello: 'world' })
})

fastify.post('/test', function (request, reply) {
  reply.send({ hello: 'world' })
})

fastify.addContentTypeParser('application/x-www-form-urlencoded', function (
    request,
    payload,
    done
  ) {
    var body = '';
    payload.on('data', function (data) {
      body += data;
    });
    payload.on('end', function () {
      try {
        const parsed = qs.parse(body);
        console.log(parsed)
        done(null, 'aaa');
      } catch (e) {
        done(e);
      }
    });
    payload.on('error', function () {
      done();
    });
  });

if (!fastify.hasContentTypeParser('application/x-www-form-urlencoded')) {
    console.log('Not Added'); // This is not printed so it is added
  }

fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

**Comment by CodeAnomalies** [comment]
@mcollina thanks. Now it's working if I define route in same file but if I use `fastify-autoload` and load route in different file then it is not working.

**Comment by mcollina** [comment]
It's clearly not a bug :).

You need to define the content-parser before you register your routes with autoload.

**Comment by CodeAnomalies** [comment]
@mcollina I finally figured it out. I was not exporting routes as plugin in my autoload folder. Just in case someone else gets stuck in this. Thanks for the help and quick response.
