### ISSUE TITLE
Declaration merging broken for FastifyRequest and FastifyReply

### ISSUE THREAD

**Issue by simonplend** [fastify/fastify#2557]
#### What are you trying to achieve or the steps to reproduce?

I've followed the steps for [Creating a TypeScript Fastify Plugin](https://www.fastify.io/docs/latest/TypeScript/#creating-a-typescript-fastify-plugin) exactly (twice), but when I reach step 6 and execute `npm run build` in my terminal I receive four errors from TypeScript (version 4.0.2).

#### What was the result you received?

```
> tsc -p tsconfig.json

error TS2468: Cannot find global value 'Promise'.

index.ts:6:12 - error TS2428: All declarations of 'FastifyRequest' must have identical type parameters.

6  interface FastifyRequest {
             ~~~~~~~~~~~~~~

index.ts:9:12 - error TS2428: All declarations of 'FastifyReply' must have identical type parameters.

9  interface FastifyReply {
             ~~~~~~~~~~~~

index.ts:28:60 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

28 const myPluginAsync: FastifyPluginAsync<MyPluginOptions> = async (fastify, options) => {
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```

#### What did you expect?

A successful TypeScript build with no errors.

#### Context

* *node version*: v12.16.2
* *fastify version*: ^3.4.1
* *os*: Linux (Ubuntu 20.04)

**Comment by Ethan-Arrowood** [comment]
Oh this is weird. I can reproduce your issue in a standalone repo. But when I create a test file inside of fastify it allows me to merge with `FastifyRequest` and `FastifyReply` directly.

**Comment by Ethan-Arrowood** [comment]
Figured it out :) You need to install Node types `npm i -D @types/node` 

But i think this uncovers a different issue; our types are dependent on these so we need to make them a dep or peer dep or use triple slash reference. Or at a minimum document that users need to also install node types.

**Comment by simonplend** [comment]
@Ethan-Arrowood Thanks for looking into this and putting together a fix so quickly! :raised_hands:

**Comment by flipperlite** [comment]
I'm following [this tutorial](https://medium.com/sharenowtech/fastify-with-typescript-production-ready-integration-2303318ecd9e). This same error does not exist on his repo with fastify version `^1.13.4`. However, when I bump to fastify version `^3.27.4` (no other changes), I'm getting the same error as the OP. Was there a breaking change made along the way? I already ran `npm i -D @types/node`.

```
All declarations of 'FastifyInstance' must have identical type parameters.ts(2428)
```

```ts
import * as fastify from "fastify";
import * as http from "http";

import { Db } from "../modules/db";
declare module "fastify" {
  export interface FastifyInstance<
    HttpServer = http.Server,
    HttpRequest = http.IncomingMessage,
    HttpResponse = http.ServerResponse
  > {
    blipp(): void;
    db: Db;
  }
}
```

**Comment by RafaelGSS** [comment]
Try removing `FastifyInstance` parameters:

```diff
declare module "fastify" {
-  export interface FastifyInstance<
-    HttpServer = http.Server,
-    HttpRequest = http.IncomingMessage,
-    HttpResponse = http.ServerResponse
-  > {
+  export interface FastifyInstance {
    blipp(): void;
    db: Db;
  }
}
```

**Comment by Uzlopak** [comment]
This is so counter intuitive. I ran into the same issue, when I wanted to add the on Route options for the response-validation plugin. Installed node typings and now tsd does not throw "All declarations of RouteShorthandOptions must have identical type parameters."
