### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#256]
e.g AppVeyor

**Comment by mcollina** [comment]
I would love to. I don't seem to be able to add appveyor to this organization.

**Comment by StarpTech** [comment]
Why not?

**Comment by mcollina** [comment]
I get this error on their side:
> Object reference not set to an instance of an object.

<img width="1034" alt="schermata 2017-09-20 alle 10 38 46" src="https://user-images.githubusercontent.com/52195/30634599-eed91d80-9def-11e7-9e1f-1c82b657aebe.png">

If you can find a guide or something similar to add it to a github org, I would be extremely happy to add them.

**Comment by StarpTech** [comment]
1. Open an issue https://github.com/appveyor/ci :D
2. Sign up manually and then link

**Comment by mcollina** [comment]
@StarpTech I've tried both ways and it did not work.

https://github.com/appveyor/ci/issues/1803

**Comment by StarpTech** [comment]
crazy, this is a temporary issue my other project works great.

**Comment by mcollina** [comment]
we have AppVeyor installed.
I'll send a PR later with the configs.

**Comment by StarpTech** [comment]
Cool +1
