### ISSUE TITLE
Error code when throwing from a hook

### ISSUE THREAD

**Issue by sergiz** [fastify/fastify#2561]
#### You have already researched for similiar issues?
Yes, I have.

#### What are you trying to achieve or the steps to reproduce?

```js
fastify.addHook('preHandler', async () => {
  throw new Error();
});
```

#### What was the result you received?
The response with status code 500 was sent out.

#### What did you expect?
I would expect the client to get response code 400.

I read https://www.fastify.io/docs/latest/Lifecycle/ and https://www.fastify.io/docs/latest/Hooks/#manage-errors-from-a-hook and as I understand status code should be automatically figured out (they are written on the Lifecycle docs page). Do I just understand the docs wrong and code 500 is set for any error you throw/send? What is the purpose of those error codes shown on the Lifecycle page then?

#### Context

* *node version*: 12.15.0
* *fastify version*: 3.4.1
* *os*: Linux

**Comment by mcollina** [comment]
The docs are wrong. Both `onRequest` and `preHandler` forward the error to `reply.send()` without doing anything special.

**Comment by jackneer** [comment]
Hi, may I help this? thanks!

**Comment by mcollina** [comment]
Go for it!
