### ISSUE TITLE
Inherit fastify instance on register

### ISSUE THREAD

**Issue by Shair17** [fastify/fastify#2563]
I've registered a plugin with

`
app.register(require('./routes'))
`

In routes.js

`
export default function(fastify, opts, done) {
  // here `fastify` should have autocomplete, but it doesn't
}
`

## Your Environment

- *node version*: 12
- *fastify version*: 3.4.1
- *os*: Windows

**Comment by mcollina** [comment]
I don't really understand this issue, can you please clarify it a bit?

Maybe @fastify/typescript can help.

**Comment by Shair17** [comment]
I have tried typescript, it works correctly.
My issue is when I am using javascript with babel to get the latest features, etc.

For example when I use `fastify.register (require ('./ routes'))` in `routes.js` it should export by default a function that receives as parameters (instance, options, done) according to the fastify documentation (https: //www.fastify.io/docs/latest/Plugins/#create-a-plugin) however I don't get autocomplete when making use of the arguments.

This does not affect how fastify works, but it would be great if it got autocomplete.

**Comment by Shair17** [comment]
@mcollina by the way https://github.com/orgs/fastify/teams/typescript throw me 404 error

**Comment by kibertoad** [comment]
@Shair17 I think this is a non-issue. Autocomplete in JavaScript is mediocre at best and is completely up to how good IDE is at guessing things. You can try WebStorm, I think it has best-in-class implementation. 

If you want good autocomplete, definitely consider using TypeScript.

**Comment by kibertoad** [comment]
@Shair17 Link that Matteo gave is not something that is supposed to be open, it's just a way to tag a group of people so that they would get a notification and potentially comment.

**Comment by kibertoad** [comment]
@Shair17 One more thing: occasionally I got better autocomplete in JavaScript when using ES6 imports instead of CommonJS require. Since you are using Babel anyway, try if it improves things for you.

**Comment by fox1t** [comment]
What you are asking for doesn't even work in TS: `export default function(fastify, opts, done) { // herefastifyshould have autocomplete, but it doesn't }` will never have TS based on where it is used. You have to add them manually during the function declaration.

In addition to that you are using require to "import" an ESM file and that is not recommended at least: you are using babel only feature that lets you treat ESM as `module.exports.default`: this behavior isn't compilant to the standard and will never ever work in Node.js nor the browser. You should really use `import/export` syntax if you want to have real ESM.
