### ISSUE TITLE
Import the default (json) content type parser?

### ISSUE THREAD

**Issue by btilford** [fastify/fastify#2566]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

I have an external caller that I can't change sending requests with `content-type: text/json` is there any way to use the default built in JSON parser for this? From what I can tell it's not exported so I can't just call `server.addContentTypeParser('text/json', defaultParser)`.

#### What did you expect?

Ability to accept JSON content that other than `application/json` content type set without having to write custom parser.

#### Context

* *node version*: 12
* *fastify version*: 3.2.0

**Comment by Noor0** [comment]
I'd like to take this but I don't know where to start. I'm unfamiliar with the framework code

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/blob/master/lib/contentTypeParser.js#L207-L223 should be exposed as a top-level function in `fastify.js` (`module.exports`) and a test for it added.

**Comment by VigneshMurugan** [comment]
I am on it @mcollina

**Comment by jsumners** [comment]
@mcollina is that the appropriate solution to this issue? The way I read it, they would just like to supply a config option that says "register these content types to the default parser as well." Something like:

```js
const fastify = require('fastify')({
  extraDefaultContentTypes: ['text/json']
})
```

If we are going to expose the default parser so that anyone can register it as many times as they like on their own, then I wonder if the better approach is to create a new plugin as a separate module. Then we depend on that module in core.

**Comment by mcollina** [comment]
It can also be extracted as a separate module. The case here is for somebody that wants to parse JSON but do some other things on top, so they can reuse the type.

I'd also be ok in the option you are defining.

**Comment by jsumners** [comment]
> The case here is for somebody that wants to parse JSON but do some other things on top, so they can reuse the type.

Not so. They want to reuse the parser function as it is written. They just want to attach new incoming content type values to it.

**Comment by mcollina** [comment]
> Not so. They want to reuse the parser function as it is written. They just want to attach new incoming content type values to it.

Then your approach is likely better!!

**Comment by Eomm** [comment]
> I wonder if the better approach is to create a new plugin as a separate module

I thought the same: it would be like a plugin that registers a content type parser

**Comment by VigneshMurugan** [comment]
I think this issue can be closed now.
