### ISSUE TITLE
Get route options inside handler or inside preHandler hook

### ISSUE THREAD

**Issue by chymz** [fastify/fastify#257]
Hi,
First of all : great job on this !

Maybe a little feature request : can we have an access to route options inside an handler or inside the preHandler hook ?

Here is a sample code : 

```js
fastify.get('/', { foo: 'bar' }, async (req, res) => {
  
  // Something like this ?
  const { foo } = req.route;
  // foo === 'bar'
  
});

fastify.addHook('preHandler', (req, res, next) => {
  // Or like this ?
  const { foo } = req.routeOptions;
  // foo === 'bar'
});
```

It can be useful to add some metadatas on routes and read them in hooks, no ?

Thanks !

**Comment by allevo** [comment]
Hi,
  thanks for trying fastify out!

The route definition is stored into [`Store` object](https://github.com/fastify/fastify/blob/master/fastify.js#L419). In particular, if you define the route in this way:
```js
fastify.get('/', { config: { foo: 'bar' } }, handler)
```
the store has the `config` property set to the right value.

You can find the `Store` instance as the [`Reply` instance property](https://github.com/fastify/fastify/blob/master/lib/reply.js#L15)

So:
```js
fastify.get('/', { config: { foo: 'bar' } }, function(req, reply) {
  reply.send(reply.store.config)
})
```
returns `{ foo: 'bar' }`

**Comment by StarpTech** [comment]
@allevo we should add this to the docs

**Comment by mcollina** [comment]
@StarpTech PR?
