### ISSUE TITLE
Graceful shutdown via `fastify.close()`

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2571]
## 🚀 Feature Proposal

```js
process.on('uncaughtException', function (error) {
  logger.fatal('received uncaught exception, shutting down', {error})
  fastify.close({ graceful: true, window: '5s' }, () => {
    process.exit(1)
  })
})
```

## Motivation

Prior discussions on such a feature revolved around intercepting signals. See:

+ https://github.com/fastify/fastify/issues/260
+ https://github.com/fastify/fastify/issues/582

As highlighted in the proposal, there are cases when the application will encounter trappable errors that should generate a hard exit. However, we don't really want to terminate any current connections that can succeed. So we should be able to stop the server from accepting _new_ connections, and provide a window for closing out current connections. After which, the server should just terminate.

## Example

See proposal section.

**Comment by mcollina** [comment]
what would graceful: true or graceful: false do?

**Comment by jsumners** [comment]
`true` would stop accepting new connections and drain the current ones. `false` is the same behavior as currently implemented.

**Comment by RafaelGSS** [comment]
I'm +1 on this. [Here](https://github.com/fastify/fastify/issues/260#issuecomment-331724065) we have a plugin to deal with it. However, seems to have a huge effort to maintain as previously mentioned by @jsumners. 

But, keeping it on fastify core we need to document/mantain it as well. So, the motivation is not clear for me.

**Comment by jsumners** [comment]
That plugin is about handling interrupts. And I'm honestly not clear what it actually does upon receiving one of those signals.

**Comment by mcollina** [comment]
> `true` would stop accepting new connections and drain the current ones. `false` is the same behavior as currently implemented.

I _thought_ we implemented `true` with the caveat that we drain only current requests, not pipelined requests.

Anyway, can you send a PR? You likely have a clear view of the behavior you'd like to achieve.

**Comment by jsumners** [comment]
I should check the docs before creating issues. https://www.fastify.io/docs/v2.15.x/Server/#close
