### ISSUE TITLE
Typescript types for `setValidatorCompiler` mismatch

### ISSUE THREAD

**Issue by rburgst** [fastify/fastify#2572]
## 🐛 Bug Report

Typescript typings no longer work for setting ajv as a schema validator (even when using the code sample from the README).

## To Reproduce

```typescript
  const ajv = new Ajv({
    // the fastify defaults (if needed)
    removeAdditional: false,
    useDefaults: true, // replace missing properties and items with the values from corresponding default keyword
    coerceTypes: true, // change data type of data to match type keyword
    allErrors: true, // check for all errors
    nullable: true,
  })
  fastify.setValidatorCompiler(({ schema }) => {
    return ajv.compile(schema) 
  })
```

This yields: 

```
src/setupFastify.ts:74:47 - error TS2322: Type 'ValidateFunction' is not assignable to type 'FastifyValidationResult'.
  Types of property 'errors' are incompatible.
    Type 'ErrorObject[]' is not assignable to type 'FastifySchemaValidationError[]'.
      Type 'ErrorObject' is not assignable to type 'FastifySchemaValidationError'.
        Property 'message' is optional in type 'ErrorObject' but required in type 'FastifySchemaValidationError'.

74   fastify.setValidatorCompiler(({ schema }) => ajv.compile(schema))
                                                 ~~~~~~~~~~~~~~~~~~~

  node_modules/fastify/types/schema.d.ts:35:37
    35 export type FastifySchemaCompiler = (routeSchema: FastifyRouteSchemaDef) => FastifyValidationResult
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
```

It would be nice to get an up to date sample on how to configure fastify with different ajv settings.

## Expected behavior

Typescript compilation succeeds 

## Your Environment

- *node version*: 12.13
- *fastify version*: 3.4.1
- *typescript version*: 4.0.3
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by L2jLiga** [comment]
I'll take it

**Comment by brianorwhatever** [comment]
I think the type signature is still broken in v3.9.1

In the docs it says

> The serializerCompiler is a function that returns a function that must return a string from an input object. You must provide a function to serialize every route where you have defined a response JSON Schema.

however the type declaration of the "FastifySchemaCompiler" is a function that returns a "FastifyValidationResult"

**Comment by brianorwhatever** [comment]
Sorry, I just realized this issue is for the validator and not the serializer. The validator is working fine now however the serializer is having the same problem. I will create a new issue for the serializer
