### ISSUE TITLE
Add `.protocol` getter to Fastify's request object

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2577]
Attempts have been made, with https://github.com/fastify/fastify/pull/2222 being the closest to acceptable. But that issue was closed at the author's request.

**Comment by MetCoder95** [comment]
I would like to address this one, can help me to enforce the codebase knowledge

**Comment by jsumners** [comment]
Go for it.

**Comment by kevbook** [comment]
I am using this logic on my app

```js
var protocol = req.connection.encrypted ? 'https' : 'http';
if (server.trustProxy && req.header(X-Forwarded-Proto), then override protocol;
```

**Comment by RafaelGSS** [comment]
This could be closed @jsumners ?
