### ISSUE TITLE
logger serializers need all properties?

### ISSUE THREAD

**Issue by x0us** [fastify/fastify#2578]
I'm a learner programmer and trying to custom logger, i follow the [guide](https://www.fastify.io/docs/v3.4.x/Logging/). however, the following code got error due to " missing the err, req properties", i also found the source code in logger.d.ts define serializers need 3 properties.

I don't know is this a bug? or it's designed like this. please suggestion, thank you.

```js
serverOptions: FastifyServerOptions = {
	logger: {
		prettyPrint: true,
		serializers: {
	            res (reply) {
				// The default
				return {
				  statusCode: reply.statusCode
				}
			  }
		}
	}
}
```

the defination of serializers:

```js
  serializers?: {
    req: (req: RawRequest) => {
      method: string;
      url: string;
      version: string;
      hostname: string;
      remoteAddress: string;
      remotePort: number;
    };
    err: (err: FastifyError) => {
      type: string;
      message: string;
      stack: string;
      [key: string]: any;
    };
    res: (res: RawReply) => {
      statusCode: string | number;
    };
}
```
version: 
"fastify": "^3.4.1",

**Comment by mcollina** [comment]
Maybe @fastify/typescript can help, the code you wrote should work in JavaScript.

**Comment by fox1t** [comment]
Since `req`, `err`, and `res` properties are optional as we can see in https://github.com/fastify/fastify/blob/df9fbc183fa05fa1a23781b3f11fbf81f6854033/lib/logger.js#L76 this should be a typings bug.

@x0us would you like to send a PR? The fix should be an easy one
```ts
serializers?: {
    req?: (req: RawRequest) => {
      method: string;
      url: string;
      version: string;
      hostname: string;
      remoteAddress: string;
      remotePort: number;
    };
    err?: (err: FastifyError) => {
      type: string;
      message: string;
      stack: string;
      [key: string]: any;
    };
    res?: (res: RawReply) => {
      statusCode: string | number;
    };
}
```

**Comment by pgcalixto** [comment]
I assume this was fixed in https://github.com/fastify/fastify/pull/2579 and can be closed, right?
