### ISSUE TITLE
Print stack trace of errors in handlers

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#258]
Hi, it's funny but during testing, I could the see error logs but couldn't discovering where the error comes from. As far I know only the `name` and `message` is logged and there is no option. We should add the stack trace to the error log. This is relevant if you use `async/await` or Promises.

Relevant parts:
https://github.com/fastify/fastify/blob/18b5992e371c910d2989c1574b61bc03a84f370b/lib/handleRequest.js#L127
https://github.com/fastify/fastify/blob/18b5992e371c910d2989c1574b61bc03a84f370b/lib/reply.js#L65

**Comment by allevo** [comment]
Can we use [this](https://github.com/fastify/fastify/blob/master/lib/logger.js#L40) strategy for the error serialization?

**Comment by StarpTech** [comment]
We could use this https://github.com/pinojs/pino/blob/master/lib/serializers.js#L32

**Comment by jsumners** [comment]
I'd rather see an extra log line: `req._log.debug(err.stack)`

**Comment by StarpTech** [comment]
I agree with that but with level error I created PR https://github.com/fastify/fastify/pull/264
