### ISSUE TITLE
Typescript : add readonly

### ISSUE THREAD

**Issue by zekth** [fastify/fastify#2580]
Currently we ship the typings with the library and one thing came to my mind. For example for the `FastifyRequest` we have the current typing:

```typescript
export interface FastifyRequest<
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
> {
  id: any;
  params: RouteGeneric['Params'];
  raw: RawRequest;
  query: RouteGeneric['Querystring'];
  headers: RawRequest['headers'] & RouteGeneric['Headers']; // this enables the developer to extend the existing http(s|2) headers list
  log: FastifyLoggerInstance;
  body: RouteGeneric['Body'];
  ip: string;
  ips?: string[];
  hostname: string;
  url: string;
  method: string;
  routerPath: string;
  routerMethod: string;
  is404: boolean;
  /** in order for this to be used the user should ensure they have set the attachValidation option. */
  validationError?: Error & { validation: any; validationContext: string };

  // `connection` is a deprecated alias for `socket` and doesn't exist in `Http2ServerRequest`
  connection: RawRequest['socket'];
}

```

My proposal is to move it to:
```typescript
export interface FastifyRequest<
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
> {
  readonly id: any;
  readonly params: RouteGeneric['Params'];
  readonly raw: RawRequest;
  readonly query: RouteGeneric['Querystring'];
  readonly headers: RawRequest['headers'] & RouteGeneric['Headers']; // this enables the developer to extend the existing http(s|2) headers list
  readonly log: FastifyLoggerInstance;
  readonly body: RouteGeneric['Body'];
  readonly ip: string;
  readonly ips?: string[];
  readonly hostname: string;
  readonly url: string;
  readonly method: string;
  readonly routerPath: string;
  readonly routerMethod: string;
  readonly is404: boolean;
  /** in order for this to be used the user should ensure they have set the attachValidation option. */
  readonly validationError?: Error & { validation: any; validationContext: string };

  // `connection` is a deprecated alias for `socket` and doesn't exist in `Http2ServerRequest`
  readonly connection: RawRequest['socket'];
}
```

So here what's the concern? The fact that we push readonly makes sense as any modification on those properties would not change anything in the request/response lifecycle (as far as i know). @fox1t brought up that in JavaScript we can modify those values, which makes no sense to set it as readonly. What's your thoughts?

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by Ethan-Arrowood** [comment]
If any of these properties can be modified then they shouldn't be `readonly`. If a properties has "writable: false" then it is appropriate to use `readonly`

**Comment by fox1t** [comment]
> If any of these properties can be modified then they shouldn't be `readonly`. If a properties has "writable: false" then it is appropriate to use `readonly`

I agree with you. We should track them and make them readonly. It would be also a nice way of documenting them.

**Comment by zekth** [comment]
> > If any of these properties can be modified then they shouldn't be `readonly`. If a properties has "writable: false" then it is appropriate to use `readonly`
> 
> I agree with you. We should track them and make them readonly. It would be also a nice way of documenting them.

Not sure there is lot of properties created with `writable: false` currently but some might definitely better have this attribute.

**Comment by zekth** [comment]
> If any of these properties can be modified then they shouldn't be `readonly`. If a properties has "writable: false" then it is appropriate to use `readonly`

I'd add if this property has attribute `writable: false` or has a getter without a setter.
