### ISSUE TITLE
Shorthand declaration with options.handler throwing "handler.apply is not a function"

### ISSUE THREAD

**Issue by theGlenn** [fastify/fastify#2581]
## 🐛 Bug Report
The shorthand declaration Sample doesn't seem to work.
Querying the url throws:

```json
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "handler.apply is not a function"
}
```

## To Reproduce

Simply run the following example: https://www.fastify.io/docs/latest/Routes/#shorthand-declaration

```js
const opts = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  }
}
fastify.get('/', opts)
```

## Expected behavior

```js
Same code
```
Response 
```json
{
  "hello": "world"
}
```
## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: == 3.4.1
- *os*: Mac, Windows, Linux

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
I normally use the following:

```js
const opts = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  }
}
fastify.get('/', opts, function (request, reply) {
  reply.send({ hello: 'world' })
})
```

This is actually more natural, however we should also support the above..

**Comment by fox1t** [comment]
Why putting the route handler inside the opts object should be something we want to do?

**Comment by mcollina** [comment]
We currently say we support this in our docs :/. We can fix the doc and add a better error message for this?

**Comment by delvedor** [comment]
I think the behavior is intended 🤔
This is a documentation issue and not a code one.

**Comment by Eomm** [comment]
I use this pattern every day, I cannot reproduce:

```js
const fastify = require('fastify')()
const opts = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  }
}
fastify.get('/', opts)

fastify.inject('/', (_, res) => console.log(res.payload))
```

**Comment by Eomm** [comment]
> Why putting the route handler inside the opts object should be something we want to do?

It is useful to build many endpoints programmatically (I create an array of `opts`)

**Comment by fox1t** [comment]
> > Why putting the route handler inside the opts object should be something we want to do?
> 
> It is useful to build many endpoints programmatically (I create an array of `opts`)

Never thought about doing this!

And why not mapping also the URL in every opts object and then using it with `.route(`? 🤔

**Comment by Eomm** [comment]
> And why not mapping also the URL in every opts object and then using it with .route(?

Just to don't declare the METHOD - it would be less readable 😅

Yes, you can, but I had many trick-shot with this feature like:

Handler overwriting:
```
const fastify = require('fastify')()

fastify.addHook('onRoute', (routeOpts) => {
  routeOpts.handler = (req, res) => res.send('bar')
})
fastify.get('/', {
  handler: () => {}
})
fastify.inject('/', (_, res) => console.log(res.payload))
```

A lot of proxy:

```
  routes.forEach(pr => {
    fastify.post(pr.path,
      {
        handler: pr.handler || proxyHandler,
        schema: {
          tags: ['proxy'],
          headers: headerSchema
        }
      })
  })
```

**Comment by theGlenn** [comment]
@Eomm this is weird, what version on fastify are you on ?

**Comment by Eomm** [comment]
The last one and the v2 too

Did you tried my snippet? It it works for you the issue should been hidden in some other code

**Comment by theGlenn** [comment]
> fastify.addHook('onRoute', (routeOpts) => {
>   routeOpts.handler = (req, res) => res.send('bar')
> })
> fastify.get('/', {
>   handler: () => {}
> })
> fastify.inject('/', (_, res) => console.log(res.payload))

@Eomm I tried your snippet and it works, but when removing the `addHook` part I get the same `handler.apply is not a function` error again

**Comment by Eomm** [comment]
In your first message, there is not an `addHook` call, so, would you mind to add a complete script that we can run to replicate?

**Comment by theGlenn** [comment]
@Eomm I'm not sure to understand the use of `addHook` it looks more like hack to me doesn't it?

**Comment by Eomm** [comment]
> @Eomm I'm not sure to understand the use of `addHook` it looks more like hack to me doesn't it?

My comment here https://github.com/fastify/fastify/issues/2581#issuecomment-698966213 was just to show to @fox1t how this feature could be used, it is not a suggestion to solve, sorry for the off-topic.

Right now the state of this issue is: we can't replicate.
For this reason, we need a snippet to reproduce the problem that you are experiencing
