### ISSUE TITLE
Plugin for Dependency Injection

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#2587]
## 🚀 Feature Proposal

Provide an official `fastify` plugin that would allow injection dependency within fastify app lifecycle.

## Motivation

Provide first class, fastify-aware dependency injection experience for teams that prefer applying the inversion of control.

## Example

Managing app-scoped singletons and request-scoped service, repository, client and other entity instances.
Exact API would require some tinkering to finalize, but I imagine something along these lines:

```
app.register(fastifyDependencyInjectionPlugin, { 
  dependencies: 'src/**/*.module.js' // load dependencies based on a glob
});

app.register(fastifyDependencyInjectionPlugin, { 
  dependencies: ['src/user.service.module.js'] // load dependencies based on a file list
});

app.register(fastifyDependencyInjectionPlugin, { 
  dependencies: [userServiceModule] // load dependencies based on a a module object list
});

class AbstractModule {
  constructor(moduleId, moduleInstanceId, scope, dependencies) {
}

class UserServiceModule extends AbstractModule {
  constructor() {
    super('userService', 'productionUserService', 'app', [
      { moduleId: 'userRepository'}
    ])
  }

  createUser(userData) {
    this.dependencies.userRepository.createUser(userData)
  }
}

```

Under-the-hood this is likely to use either `awilix` or `inversify`, whichever ends up being a better fit.

**Comment by kibertoad** [comment]
I would be interested in working on this, if there is greenlight to proceed from the `fastify` team.

**Comment by Ethan-Arrowood** [comment]
Seems like a great idea! I've found success creating a plugin first in a personal repo and then proposing it to the team when its ready if they'd like to move it into the fastify org or not.

**Comment by kibertoad** [comment]
@Ethan-Arrowood Yup, I would definitely go that route, but it's always nice to gauge the initial interest in something prior to spending time and effort on it. And on that stage exact implementation and API are not that important.

**Comment by mcollina** [comment]
I think `fastify-autoload` already has 95% of what you'd need. How would this be different?

**Comment by kibertoad** [comment]
@mcollina Please correct me if I'm wrong, but I think that all `fastify-autoload` does is load all plugins. This might work as a very rudimentary DI engine, since potentially you can access other plugins exposed via decorators either on apps, or on requests, but there are several limitations to that approach:

1) Decorators are exposed as a single global state, basically. So if you have 100 modules, each of them see all of other 99 modules. Proper DI resolves dependency graphs and injects only what is needed where it is needed.

2) There is no built-in support for alternate implementations of same dependency. Say, I want to inject `alwaysErroringUserService` instead of `productionUserService` instance, both of which implement same interface. DI allows you to do that out-of-the-box, either in tests, or in runtime (e. g. based on app configuration or even request origin country use one or the other dependency implementation). In tests you can achieve similar effect using (clunky) Jest magic, in runtime you'd have to implement manual layers of abstraction.

3) DI can be used for more than just modules. You can decrease coupling of your code to your configuration by injecting config values that your modules depend upon.

**Comment by jsumners** [comment]
I highly recommend against this. I have implemented this exact thing in an internal wrapper. It's much easier to use native JavaScript for DI.

**Comment by kibertoad** [comment]
@jsumners What were the issues that you have encountered? People seem to be using things like https://www.npmjs.com/package/awilix-koa, although there doesn't seem to be anything like that for fastify.

**Comment by StarpTech** [comment]
> I highly recommend against this. I have implemented this exact thing in an internal wrapper. It's much easier to use native JavaScript for DI.

I have currently no opinion about that in the context of fastify but DI is more than accepting any type. It's about inversion-of-control. A consumer is not responsible to

- define the lifetime,
- service instantiation
- contract-fulfillment.

This can't be archived with fastify-autoload or native Javascript.

**Comment by mcollina** [comment]
I'm +1 to all what @StarpTech said.

**Comment by kibertoad** [comment]
@mcollina Then it sounds to me like this is more of a philosophical question that each team has to answer for itself, whether or not they want to use DI; but there is an existing gap in functionality that this plugin would fill, hence enabling teams to pick to themselves.

That said, considering that majority of core team is indifferent to DI, with one in favour and one against, would including a DI plugin among core plugins be equivalent to `fastify` endorsing the DI approach? Would that be a reason enough to keep such a plugin as a community one?

**Comment by kibertoad** [comment]
@jsumners Points raised by @StarpTech and myself still stand, though. This definitely provides a certain barebones version of dependency management, but full-blown DI engine provides functionality not available when following this approach.

**Comment by mcollina** [comment]
What @jsumners and myself are saying is that what Fastify provides already is "good enough" for our use cases. A more complex use case would probably need a bigger library. Building a new plugin for this would be nice.

**Comment by RafaelGSS** [comment]
I'm +1 on this plugin. On `nestjs` we have this approach in an elegant way.

**Comment by kibertoad** [comment]
@RafaelGSS I'm currently prototyping it, let's see if this can be done in a not entirely intrusive way!

**Comment by delvedor** [comment]
One of the core design concepts of Fastify is: _if something could be a plugin, it should_.
The idea behind this is that you can assemble the plugins you need to have a tailor made framework, without sacrificing security or performance.

**Comment by piavgh** [comment]
I tried to apply the Clean Architecture to my Fastify project:

> `Route => Controller => Service => RepositoryInterface => Entity`

The concrete implementation of `RepositoryInterface` will be injected in `Controller`, something like this:

```js
export default class CompanyController {
  companyService: CompanyService;

  constructor() {
    // Inject the concrete implementation of CompanyRepository here
    this.companyService = new CompanyService(new CompanyFactory(), new CompanyRepository());
  }
  ...
```

But using this way, it's hard to unit test the Controller or Route.

I'm thinking about this IoC container https://github.com/jeffijoe/awilix to solve this problem.

Is it a good approach? Or force applying Clean Architecture into Fastify project is a bad idea?

**Comment by L2jLiga** [comment]
> > I tried to apply the Clean Architecture to my Fastify project:
>
> > `Route => Controller => Service => RepositoryInterface => Entity`
> 
> The concrete implementation of `RepositoryInterface` will be injected in `Controller`, something like this:

I think it's time to advertise my plugin 😄 

I'm working for a while on [`fastify-decorators`](https://github.com/L2jLiga/fastify-decorators) library which provides set of typescript decorators for writing controllers, services and dependency injection

You can find example with `typeorm` [here](https://github.com/L2jLiga/fastify-decorators/tree/v3/examples/typeorm)

**Comment by piavgh** [comment]
> > > I tried to apply the Clean Architecture to my Fastify project:
> > 
> > 
> > > `Route => Controller => Service => RepositoryInterface => Entity`
> > 
> > 
> > The concrete implementation of `RepositoryInterface` will be injected in `Controller`, something like this:
> 
> I think it's time to advertise my plugin 
> 
> I'm working for a while on [`fastify-decorators`](https://github.com/L2jLiga/fastify-decorators) library which provides set of typescript decorators for writing controllers, services and dependency injection
> 
> You can find example with `typeorm` [here](https://github.com/L2jLiga/fastify-decorators/tree/v3/examples/typeorm)

Thank you for the plugin, I will check it.

But can you please tell me what is the reason for using `Decorator` in your plugin?

**Comment by L2jLiga** [comment]
It's relying on TypeScript with `emitDecoratorsMetadata` enabled and `reflect-metadata` to make dependency injection works.

**Comment by kibertoad** [comment]
Here is the candidate plugin to provide an unopinionated, pure-JS solution to the DI problem: https://github.com/kibertoad/fastify-awilix.

In the end I decided to diverge from the original plan and instead of introducing additional abstractions, and expecting certain code structure from the end user, embraced an existing solution, [awilix](https://www.npmjs.com/package/awilix), plugging it into the fastify lifecycly.

As per usual, feedback, comments and suggestions are most welcome, and I also would like to nominate this plugin for the inclusion as the core one :).

@Ethan-Arrowood @mcollina @jsumners @StarpTech @RafaelGSS @delvedor

**Comment by jsumners** [comment]
> Note that diScope allows resolving all modules from the parent diContainer scope:

Does that mean the container does not respect the encapsulation context it was registered in?

https://github.com/kibertoad/fastify-awilix#plugin-options <== has `disposeOnClose` described twice.

**Comment by kibertoad** [comment]
@jsumners Depends on what do you mean.
When you try to dispose of modules, it only affects modules contained in the specified container, not touching anything coming from the above or defined below.
When you try to resolve a module from the container, it can access all the modules from specified container and its parents, but not from sibling or children containers. I would say that this is a deliberate design choice by `awilix` author. What would be the advantage of request-scoped containers not having access to the parent app-scoped modules?

> https://github.com/kibertoad/fastify-awilix#plugin-options <== has disposeOnClose described twice.

Thanks, fixed it.

**Comment by jsumners** [comment]
> When you try to resolve a module from the container, it can access all the modules from specified container and its parents, but not from sibling or children containers. I would say that this is a deliberate design choice by `awilix` author. What would be the advantage of request-scoped containers not having access to the parent app-scoped modules?

Merely unclear about the relationship between the di container and Fastify encapsulation.

**Comment by kibertoad** [comment]
@jsumners Got it. Actually, "Child can see parent, but not vice versa" is consistent with how Fastify encapsulation works. Other than that, I don't think there are any inherent incompatibilities between fastify encapsulation and how DI works. If you add DI decoration deep in the grandchild context, you won't be able to access scoped modules from the grandparent, because you won't have `diScope` on grandparent requests in the first place.

**Comment by jsumners** [comment]
Sounds good to me.

**Comment by kibertoad** [comment]
Closing since plugin was implemented.
