### ISSUE TITLE
Docs: link points to missing anchor

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2588]
https://github.com/fastify/fastify/blob/bc23290f699d9092b98037fb99eb7e48d07c856d/docs/Validation-and-Serialization.md#L201

This is meant to link to the "ajv" option in the server options. It is not doing so. This is easily seen by trying to follow the link at https://www.fastify.io/docs/v3.4.x/Validation-and-Serialization/#ajv-plugins

**Comment by bartkalanski** [comment]
Do you mind if I do this for hacktoberfest ?

**Comment by jsumners** [comment]
Go for it.

**Comment by bartkalanski** [comment]
I appreciate it, thank you!

**Comment by KushalBhanot** [comment]
Hey! I'm not able to follow the issue. Can you please guide me?

**Comment by indranil-tiwary** [comment]
I suppose this is a issue in https://github.com/fastify/website/blob/master/src/website/layouts/docs_page.html. Is it correct?
