### ISSUE TITLE
Use TypeScript Template Literal Types 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#2589]
😊 TypeScript 4.1 introduces something really awesome, template literal types. 

In short, they are incredible and should make our types much easier to manage (and without any breaking changes). One of the immediate things I see we can update is improving our hooks as many have the exact same type definition just slightly different names. Similarly the `get`, `post`, etc. methods all have the same definition and could be simplified as well. 

- [Announcing TypeScript 4.1 beta](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/)
- [I need to learn about TypeScript Template Literal Types](https://dev.to/phenomnominal/i-need-to-learn-about-typescript-template-literal-types-51po)
- [awesome list](https://github.com/ghoullier/awesome-template-literal-types)

**Comment by Ethan-Arrowood** [comment]
Also, i'm not entirely sure how yet but this may also be a huge gain for enabling implicit json schema typing.

[JSON Parser](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/C4TwDgpgBACghgJwM4QQUQQg9ggPAFSggA9gIA7AEySiWAQEtyBzAPigF4oBvIzHAFxR6AV2gBfKADIo+AFChIUNHGAB1ABYMySMHADGEXAGVgq6CTJUadRi3Yc5UWvSbMipCtSinzT51AA-LCIKOj8eABEKupaOnqGUMxYwEkUqAz6LnbuihCRrP7OQr5kHlbeAAZQACTcTABmqD5mZOLVAD5QlQA65HWNzaUQ7UUBwTGa2hC6BkbDhQEBJa0QCuDQAIKUlADSECAAanAANmK4ALIQALZY5V40AEoQ+jiUuLZuADRQcOQgrB++xA92s2W+UGOZwsnjBfwBnCg-iut2kPCgAG1dlAmFBgQBdIRQsRQcTrJTwZAQABSSCw5AA8gAjABWL2AJlWoO8nxYPxRd0sDygz1eCHevOYP3hDh44gc-kl3JowzGwUpYQw2CiGppdMZrPZSRSaXIGSySryBTGQkmcRmCXmq3YQrBlXEA3ITQQLXMoyWzmCGIFP2G+LGxWUqim8TmnPMLthVUinu9eIO4hT9S9Q1W-oDgajsWms0M8bIiYqNEqAlTub9lQjAfVoT19OJToTysxgx9HZ+lTrPuG7XDBYLE2j9tLnYr3cqXyHvrajfH45bVNp9OZbP0HOGP22ewOHcuNywQIOPw7rEWa4DtqnJcd5YgleF7qXI9X94nmKPwKniG6YgNepxiICy4QGOv4PiEVLhNquCVLqW4GruqQIC8EAMAAbhAlBQCIZrEJAe4EcIWAANYUEIdTfnev5CLqiE4MhqH6h2UBYcAIgIGahHESQZFkIRuHgdADSCLU3AMU2SzMa2rF4ChrZoTuRpYYYeEUUJpHshRwDUbRMlyWuikIVqbGqZu+oaXu3HYTpgkkSJhnGeQdGyXmlSFHk8EoGhmyYHAICvt2kr8ue3bwhi+KInFCrOEqrreKqSwbpqES4JEHH0sFCChcaqTMOkjAWq4LDCBs1oKUWMYOnGCzzviX4+U2QbAWGTYWYFnESa+75ghivaQhJA5tQ2MF-naz5Nc686LtmabfvJ4wBW25AFaFuCzbGZYLD8GIAHSncBHb4ox46PsW+2zm+LWTSua0ZZiJ1neeYHQvioarNN969agVkqXlW0hSCWk4fhLnCQZhFGTRnmmT5V11SxwPsWp-XQo5vH8bprlw1A4k41JCBeXJ-mg6ewwRZVbCcIq9Pdul63o9luVY+2EnFaa5rglVVpXTdDUzoN87kCIJwnE9Iw-q9GKS9Lv3mP9kZ7Y1B0Lal1ZZqNHaZrL+Z-hi-ZQWryz1dOL7NTr3QYkb8vrhtQXg4NL1QCL1vzV2duVNwjse4WoP2fuzpB57G3KZjtnczjkPOURhPkfDHkUyj5LQKDBB0zkSUu9j5z4EN3ijc8SBS8AaoijMlfdiNOZ9uNAvMBbwQdj1NcVycqR2+zSEymtwTl5Xa2A9HnOx+QXE8XxAlJ7DKdd5XtWW-3bGT31cckrP+Mub2hVMic0Ajz3BQANxyFf1+Z1AaGItnADkvCRDRIAAIyREIGKRCTYifz8JWJwfpQFfgcAATF-UBf8ICQNJI-Vgl8b7XyAA) credit to https://twitter.com/buildsghost/status/1301976526603206657

**Comment by fox1t** [comment]
I agree that introducing them would be awesome! I'll be glad to review the related PR in the future!

**Comment by Ethan-Arrowood** [comment]
I've already spent some time experimenting with it; unfortunately, some of the template literal tricks don't translate as well to our type definitions (they seem to be better used in TS source rather than definition files). The JSON stuff tho is going to be really cool if i can get it to work. I'm trying to watch what others come up with too as its a pretty obvious idea to use these things to do inferred JSON support in types 😄

**Comment by Ethan-Arrowood** [comment]
Experiment: [wrap server based generics in an object](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201015#code/JYWwDg9gTgLgBACxjMcBmUIjgciSnAKFElkWTACZ1Ns8LKiTp58wBnGrXN9owmAE8wAUzgBlEVABuUgKoA7YBAVwAvORQA6STKlwAPpo46psqIeOUtACQa7zlttbspKkgMYBXKCIdTCAWExACURAEcAHkI4CTgRAA8YEQUAE05-KEVlVQ02Uz0oQgA+dTjE5LTOfMynCnYCxwB+Yy0ASQUPLGAFAHMAWRF2dgBDXpEYuAAucqSU9KtbezN9I2clt08fPxWLFvXXKkyw8K8hmEnYmYURcyDRODD2aNjxeLmqiV3slTKa3ZKZTeFXm1QojVWxgatX24OOQ0gCnYEyus0qCwOy0KdTcGyOIm8vhhi0O7l2T0RyMu0zgNzuxAUySgaBGHjEAHEXrE0aCvoUfrlWpkADTUkLhd7ozgnSLiUoaGVy0Xcx6cEGfJ6y+WPIZauCAgDe1MyMyNKpVJokyvNsROZ3YMBm4utNrCYAANoInexqQBfADc1IAMhBeuMoDMvAoANYKCAAdwUgd9gQA9Km4EIHgAxADysslvMyAr+cN2wrgABVC59OXKynXitqjenze7Q+GZpWANo4ENhqQ4AC6hFbKdbWbEeZs4gL6ox9QhFjyi8y2rzeoAZHAWxmVbwZrwl7mwDAcj6x6OM5O4NPKHOPgvcaTaivn1jzOv8-Xt7vzc4ZhgKAzivOBx2vYJb1zGx3AfKUSWWQkdmxN8qDxMkkLXMoNx-HdQP3BhAOAkRRVbAiUHYQ8GFMTDdhPM8VAvDMUxvac4KLb4lF+VClwrat504RsGy1ZtqXbAcIyrXt+3DYdCBYyDpzeDQ2KPLDf2pA8oWPU9z3k+4p2g6gVOgyJMU2XZSg08iqCIkCFJzIzlKgmwzOol8CW2dS8Jsyg7JIzT6io3EtiJOjdMY-SGSZFk2VvNp2M+YsuMFf5Cj4msFiEjRG1KM1uWRQou17TJhxK3Y5JTQhUgJd0Rl8dAow8BjVDQSJ+MfQS3PfCzaMKbVOXM-E+s-YoAAoIFPSiXPcABKGZswSoaMK88sq2KaravqsQ0Calr0HazKuuWrCcu6tCPP68bJpgaa73m+LzpcD8pD4jaao8OqGt2zp9rajr4MG1dLOEtTLOuqaFug8QHsW87oTWyt3q2769pyA6Ad5IHtFOuBsbAJcmwmqamihmxYaWst0vWwI2oNOBxM7OAo1jBNVF9cbZrTCCHgQMo-xVQrzGCgmRXw7lfFOc4RfaTpuj6QZhjGAKyIlkQPS9IVyQRRiJkvUCbwQTgNAFgrdhFhH0vF2JJftR1Wg6LoQB6AYhlGcZSL3NWNZl+F2EpPXmO5zNIIQYy8NV2IhakEXnosq3I7gW3pYQ+PzDtc5PfNXwfdT-FCgpXXQKqidQ8oY2I69qPzbzlawoTquk4iO3Y-Q+EpYdLOVRzz1W8u9OdaRQOwODm8bD+JxODWahp-YIA) - issue with optional stuff

**Comment by Ethan-Arrowood** [comment]
Adding discussion since this will only be added when 4.1 is officially released and there is more stability in the template literal api

**Comment by Uzlopak** [comment]
Closing this Issue as we basically started using Template Literal Types.
