### ISSUE TITLE
Ensure that fastify Request is encapsulated

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#2598]
## 🚀 Feature Proposal

Fastify `Request` object is bound to the HTTP request lifecycle.

As a developer, I would expect that fastify creates a new `Request` object for every new request. While this is the case, fastify keeps object references across requests. This is due to the nature of prototype inheritance [here](https://github.com/fastify/fastify/blob/810f88aeeb0878551bb5c9289d7175edc391ff98/lib/request.js#L54).
This makes the code vulnerable to memory leaks: https://github.com/fastify/fastify-multipart/issues/158#issuecomment-702055958

We need to ensure that all properties are reset.

## Motivation

As in other HTTP frameworks, the `Request` object is a new instance on every request. The developer shouldn't need to care about it. I propose to rethink that strategy because it's confusing and error-prone.

## Example

```js
fastify.decorateRequest('array', [])

fastify.post('/', async function (req, reply) {
    req.array.push(1)
    reply.code(200).send()
})

http.request(...) // array = [1]
http.request(...) // array = [1, 1]
.....

[ 1 ]
[ 1, 1 ]
[ 1, 1, 1 ]
[ 1, 1, 1, 1 ]
[ 1, 1, 1, 1, 1 ]
[ 1, 1, 1, 1, 1, 1 ]

```

**Comment by mcollina** [comment]
It is not possible to achieve this reliably and in a performant way (I already stumbled on this a few times unfortunately). I think we should document this for v3 and maybe add a better API in v4.

**Comment by Eomm** [comment]
We could support a `factory` option that will run for each request?

```
fastify.decorateRequest('array', function() { return [] }, { factory: true })
```

**Comment by mcollina** [comment]
That'd slow things down considerably. Moreover, we have hooks for this kind of work and it's as is as adding an `onRequest` hook. Now, we could have the `factory: true` option to do all the boilerplate for us (using `'onRequest'`).

**Comment by StarpTech** [comment]
IMO this issue is really important. I'd always prefer correctness over absolute speed. @mcollina do you mean that `fastify.decorateRequest('array', [])` register a shared `onRequest` hook to reset the data?

**Comment by zekth** [comment]
i'd assume that : 
```js
fastify.decorateRequest('array', function() { return [] }, { factory: true })
```
will result in subsequent
```js
 const fn = function() { return [] };
  function onRequest (request, reply, done) {
    reply.array = fn()
    done()
  }
```

**Comment by mcollina** [comment]
The problem is that we can't know how to creat a new instance identical to the value as can be of any custom type or class... and the only solution would be an unreliable (and slow) deep copy.

I think we should deprecate `decorateRequest(prop, value)` with any value that is not `null` or `undefined`. There is really no valid use case for that. 


We could potentially add a new API that allows to set a factory for the instance value, but this is already covered by hooks.

**Comment by jsumners** [comment]
> 
I think we should deprecate decorateRequest(prop, value) with any value that is not null or undefined. There is really no valid use case for that.

Defaulting to an empty string is totally valid. Really, any primitive is valid. Why do you say it isn't?

**Comment by mcollina** [comment]
Right! All value types are good, including functions. It's really objects, arrays, set and maps that are problematic.

**Comment by Eomm** [comment]
> It's really objects, arrays, set and maps that are problematic.

Agree on emitting a warning per these types

**Comment by kdrewes** [comment]
Hello, I want to attempt to tackle this issue.  Please let me know if this issue no longer needs assistance.

**Comment by mcollina** [comment]
Sure!

Could you target the `next` branch?

How do you plan to solve this?

**Comment by gurgunday** [comment]
What's left here?

We now emit a warning if an object is decorated, and others have said complete encapsulation will hurt performance, though I must admit I like the idea of knowing for sure that a completed request is gotten rid of for good from memory, feels safer 😄
