### ISSUE TITLE
Add File Path Support For fastify.listen()

### ISSUE THREAD

**Issue by BboyAkers** [fastify/fastify#2600]
## 🐛 Bug Report

Wanting fastify.listen()  to support string paths.

https://nodejs.org/api/net.html#net_server_listen

This shows a path can be listened to instead of a number. Does Fastify support IPC?
## To Reproduce

```js
const path = '' // Get path from wherever
// @TS-Error path must be type number
fastify.listen(path)
```

## Expected behavior

Should be able to support file paths.

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: 3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by Ethan-Arrowood** [comment]
Will be pairing on this with Austin 😄

**Comment by Ethan-Arrowood** [comment]
Some more relevant info:

Fastify does support IPC: https://github.com/fastify/fastify/blob/3709671b73c9109ef54fa1e85de0d7b7f7946226/test/listen.test.js#L186

The intended change is probably typescript only, adding string to the list of allowed port types
