### ISSUE TITLE
Fastify's default error handling can serve unexpected responses

### ISSUE THREAD

**Issue by mmarti** [fastify/fastify#2602]
## 🐛 Bug Report

I'm not sure if this is a bug or intended behavior (it is documented to some extent, but it seems like setting your own error handler should disable it), so apologies in advance if this should be a feature request versus a bug report.

Fastify's default error handling checks for properties like `status`, `statusCode`, and `headers` [1] on the error that is thrown and then uses them for preparing part of the response.  I was running into an issue when I was testing some errors in a few of my routes.  I expected to hit a normal 500, but instead was greeted with a parse error:

```
Parse Error: The response headers can't include "Content-Length" with chunked encoding
```

It turned out some of the APIs I was testing add a lot of additional properties to the errors that are thrown, one of them being the headers of the failed request, which caused Fastify to then set a dozen or so headers from the failed API call on the response to the end user, which made everything blow up from there.

Long story short, any failed API calls that include the request headers will subsequently have a high likelihood of failing in Fastify to the point where an end user won't even get a valid response, they'll get a malformed blob that will be unusable.

While I certainly understand the value in the current implementation, there doesn't appear to be any way to disable this behavior.  I believe the only two options I have are:

1. Wrap every single API call in my routes and re-throw errors without the `headers` property that gets added by certain SDKs.
1. Use something like `setErrorHandler` [2] and manually iterate through all the headers and call something like `reply.removeHeader('name')` on each one.

Neither of those options are ideal and both add a bit of unnecessary code (first being far worse than the second).  I was hoping I could simply bubble errors to the top and return an error response to the user.  Are there any other options I'm missing, or is there any way to disable the logic (based on the code it doesn't appear there is but maybe I'm missing something)?

If this isn't a bug and is intended behavior.  Is it possible to move L519 [3] up to the top of the `handleError` function (above L507 at a minimum)? In other words, if a user manually specifies an error handler, Fastify won't modify the response based off any of the error properties?  Fastify will only inherit error properties if the user is relying on the default error handling logic?

[1] https://github.com/fastify/fastify/blob/f458cea2d360444fd1a2ca5972e8fca6f2e07d88/lib/reply.js#L507
[2] https://www.fastify.io/docs/latest/Server/#seterrorhandler
[3] https://github.com/fastify/fastify/blob/f458cea2d360444fd1a2ca5972e8fca6f2e07d88/lib/reply.js#L519

## To Reproduce

1. Throw an error inside an async route that has a `headers` property.
1. Fastify will automatically set them on the response.
1. Depending on what the headers are, Fastify will try to serve a malformed blob.

## Expected behavior

At the very least, if I'm manually setting my own error handler, I would expect that the reply argument I receive is pristine and hasn't already had status code or headers set.  If you're relying on Fastify's default behavior, there's still potentially room for improvement by overriding certain header values if they won't be valid for the error response.

## Workaround

This fixes the issue:

```
app.setErrorHandler(async (err, req, res) => {
  Object.keys(res.getHeaders()).forEach((h) => res.removeHeader(h));
  // ...
});
```

I know it's a one-liner, but would be awesome if there was a better way.  Better yet, if it was possible to define the key from the error that should be used for status, I wouldn't need to manually set an error handler at all.  Some SDKs set `error.code === statusCode`, etc.

## Your Environment

- *node version*: 14
- *fastify version*: 3.4.1 (latest)
- *os*: Windows, Linux

**Comment by mmarti** [comment]
@mcollina Could you verify whether the fix was released? It looks like it was merged to the next branch, but has been sitting there ever since.  Is there still any outstanding items that need to be taken care of before it can be merged in with master / released through a new npm version? Thanks.

**Comment by mcollina** [comment]
@mmarti it will be part of the Fastify v4, shipping as soon as that is ready.

**Comment by mmarti** [comment]
Ah, I wasn't aware there was an upcoming major version release. Pardon if there is information elsewhere, but was there a timeline or a place I could follow that progress? Thanks.

**Comment by mcollina** [comment]
Closing this issue as it's done.

We have no formal plan right now. There will be one prepared in the coming months.

**Comment by radomird** [comment]
@mcollina Should we close this issue?
