### ISSUE TITLE
Plugin registration no longer works with webpack

### ISSUE THREAD

**Issue by agramian** [fastify/fastify#2603]
## 💥 Regression Report

The change from #2549 has caused plugin registration to error when using fastify with webpack.

Previously when checking the version of fastify against the version supported by plugins, the fastify version was being derived from the `fastify/package.json` explicitly in [this block](https://github.com/fastify/fastify-plugin/blob/master/plugin.js#L93-L123).

With the change from #2549, there are two error cases introduced by the file reading logic in [this block](https://github.com/zekth/fastify-1/blob/e8ef66273b722080a4be13996431bea7c0deae6a/fastify.js#L593-L598):

1. A `package.json` for reading is not found because of the project/directory organization in which case `Error: ENOENT: no such file or directory, open '/package.json'` is shown.

2. The fastify version is derived from the `version` in the user project `package.json`.  This results in errors of the form `fastify-plugin: {{plugin name}} - expected '>=3.x' fastify version, '{{version from user project package.json}}' is installed`.

## Last working version

Worked up to version: 3.4.1

Stopped working in version: 3.5.0

## To Reproduce

Clone the the *webpack* branch from the project [here](https://github.com/agramian/fastify-examples/tree/webpack).

From a terminal within the project folder execute `npm i; npm run build; npm run start`.

## Expected behavior

Either plugin registration should work as it did before, or the documentation should be updated to recommend how to register plugins going forward when using a bundler like webpack, or as a workaround it should be possible to explicitly define the fastify version when initializing the instance (I will open a PR and reference back here for this).

## Your Environment

- *node version*: v12.18.3
- *fastify version*: >=3.5.1
- *os*: macOS

**Comment by agramian** [comment]
This issue is not resolved via #2605 and should be reopened per my comment https://github.com/fastify/fastify/pull/2605#discussion_r501179125.

If the desired approach is to skip the version check entirely then I can open a PR or if you would rather handle it let me know and I'll hold off.

Keep in mind if the version is derived from the `package.json` then there needs be some logic to make sure the correct `package.json` is being referenced possibly by making sure the  `pkg.name` is "fastify".  The reason for this is that the check is executed at runtime so `path.join(__dirname, 'package.json')` in `loadVersion` will not be executed from the directory of the dependency.

**Comment by mcollina** [comment]
A PR would be likely welcomed.

**Comment by zekth** [comment]
This is because you're running you process in this kind of scaffolding?
```
- dist
-- index.js
- package.json
```

**Comment by agramian** [comment]
> This is because you're running you process in this kind of scaffolding?
> 
> ```
> - dist
> -- index.js
> - package.json
> ```

Yes I understand why the issue is occurring.  It is a regression from the previous behavior of fastify.

Even independent of using webpack, as I indicated at https://github.com/fastify/fastify/pull/2605#discussion_r501179125 the logic for using `fs.accessSync` is incorrect as it would throw an uncaught error rather than return `undefined` as you intended.

I will open a PR later today.
