### ISSUE TITLE
"Premature close" when serving favicon.ico

### ISSUE THREAD

**Issue by jstayton** [fastify/fastify#2616]
## 🐛 Bug Report

Ever since launching a Fastify app to production yesterday, I've seen 8 of the following error (reproduced in development):

```
{"level":50,"time":1602636402140,"pid":56878,"hostname":"JS.local","reqId":41,"req":{"method":"GET","url":"/favicon.ico","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":60778},"res":{"statusCode":500},"err":{"type":"NodeError","message":"Premature close","stack":"Error: Premature close\n    at Duplexify.onclose (/Users/jstayton/Code/piratepx/app/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:62:73)\n    at Duplexify.emit (events.js:326:22)\n    at Duplexify.EventEmitter.emit (domain.js:486:12)\n    at Duplexify._destroy (/Users/jstayton/Code/piratepx/app/node_modules/duplexify/index.js:199:8)\n    at /Users/jstayton/Code/piratepx/app/node_modules/duplexify/index.js:182:10\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)","name":"Error","code":"ERR_STREAM_PREMATURE_CLOSE"},"msg":"Premature close"}
{"level":50,"time":1602636402141,"pid":56878,"hostname":"JS.local","reqId":41,"stack":"Error: premature close\n    at onclosenexttick (/Users/jstayton/Code/piratepx/app/node_modules/end-of-stream/index.js:54:86)\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)","type":"Error","msg":"premature close"}
```

This app has received very little traffic, so 8 isn't some minuscule number in the grand scheme of things. All of them appear to be requests for `/favicon.ico`.

Thanks in advance for any help you can provide!

## To Reproduce

I've been able to reproduce in development by refreshing the page served by the Fastify app in my browser really, really quickly. The error usually appears during the rapid-fire flurry of requests. Not sure if it matters, but I'm using Firefox v81.0.1 on macOS.

I'm also not sure if it matters, but I'm using [`fastify-static`](https://github.com/fastify/fastify-static) to serve the frontend files, including `/favicon.ico`, and [`fastify-compress`](https://github.com/fastify/fastify-compress) to compress.

The entire route file is pretty straight-forward:

```js
const path = require('path')

module.exports = async (fastify) => {
  fastify.register(require('fastify-static'), {
    root: path.join(__dirname, '../../web/dist'),
    wildcard: false,
    setHeaders(reply) {
      if (process.env.NODE_ENV !== 'production') {
        return
      }

      reply.setHeader(
        'Content-Security-Policy',
        "default-src 'none'; connect-src 'self'; img-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"
      )
      reply.setHeader(
        'Strict-Transport-Security',
        'max-age=63072000; includeSubDomains; preload'
      )
      reply.setHeader('X-Content-Type-Options', 'nosniff')
      reply.setHeader('X-Frame-Options', 'DENY')
      reply.setHeader('X-XSS-Protection', '1; mode=block')
    },
  })

  fastify.get('/*', (request, reply) => {
    reply.sendFile('index.html')
  })
}
```

## Expected behavior

I'm actually not sure whether this is expected – and I should handle the error myself in my custom error handler – or whether Fastify should be suppressing the error. I have Bugsnag setup in my error handler to capture all 5xx errors, so this has become quite noisy for me considering how little traffic I'm serving.

## Your Environment

- *node version*: v14.3.1
- *fastify version*: v3.6.0
- *os*: macOS v10.15.6

**Comment by mcollina** [comment]
Could you upload a runnable script to reproduce the error? You can create that in a repo and add a link here and possibly use http://npm.im/autocannon to fire a huge amount of requests.

Somehow either the stream reading the file or the client socket is closed before the file is sent.

**Comment by jstayton** [comment]
Thanks for the quick reply, @mcollina!

Here's a minimal Fastify app to reproduce the error with: https://github.com/jstayton/fastify-premature-close-debug

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fastify-static/pull/149
