### ISSUE TITLE
Error: plugin must be a function

### ISSUE THREAD

**Issue by cethap** [fastify/fastify#262]
Hi,

When I try to run npm start with suggested configuration in package.json
```json
    "scripts": {
        "start": "fastify app.js"
    }
```
and 
```bash
$ npm run
```
the execution show me this:
```javascript
/Path/to/fast/node_modules/avvio/boot.js:147
    throw new Error('plugin must be a function')
```
But I don't understand the bug, because the contain of my file app.js is a basic example

**Comment by allevo** [comment]
Hi,
  your issue is not linked to the example complexity.
I image you are using [`fastify-cli`](https://github.com/fastify/fastify-cli). If so your file should export a function as described [here](https://github.com/fastify/fastify-cli#usage)
```js
module.exports = function (fastify, opts, next) {
  fastify.get('/', (req, reply) => reply.send({hello: 'world'})
}
```

If your problem persist, please write your example down in order to be helped better

**Comment by mcollina** [comment]
This is a bug on `fastify-cli`, it really needs to print a better error message. Specifically, the function  **must** supply three parameters.

**Comment by Ethan-Arrowood** [comment]
@mcollina I got this one 😉

**Comment by magichim** [comment]
I imitated a example on Readme.md. but I had a this error
```
Error: plugin must be a function
    at Boot.use (/Users/songwon/CODE/server/ng-test/node_modules/avvio/boot.js:166:11)
    at Function.server.(anonymous function) [as register] (/Users/songwon/CODE/server/ng-test/node_modules/avvio/boot.js:30:14)
    at runFastify (/Users/songwon/CODE/server/ng-test/node_modules/fastify/node_modules/fastify-cli/cli.js:85:11)
    at start (/Users/songwon/CODE/server/ng-test/node_modules/fastify/node_modules/fastify-cli/cli.js:36:10)
    at Object.cli (/Users/songwon/CODE/server/ng-test/node_modules/fastify/node_modules/fastify-cli/cli.js:108:3)
    at Object.<anonymous> (/Users/songwon/CODE/server/ng-test/node_modules/fastify/lib/bin.js:5:24)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-test@1.0.0 start: `fastify server.js`
npm ERR! Exit status 1
```

still exist bug.

**Comment by delvedor** [comment]
Can you paste your code and the command you are using to execute It?

**Comment by magichim** [comment]
I just copy code on Readme.md example.

##server.js
```
// Require the framework and instantiate it
const fastify = require('fastify')();

fastify.register(require('./our-first-route'));

// Run the server!
fastify.listen(3000, function (err) {
  if (err) throw err
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
})
```

##our-first-route.js

```
async function routes (fastify, options) {
  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
}
module.exports = routes;
```

**Comment by delvedor** [comment]
You should use the [fastify-cli](https://github.com/fastify/fastify-cli) only if you are running a plugin.
Your `server.js` file is not a plugin, but the entry point of the application.
Checkout the [fastify-cli](https://github.com/fastify/fastify-cli) documentation :)

**Comment by magichim** [comment]
It's my fault. I got the code from [ https://www.fastify.io/docs/latest/Getting-Started/#your-first-plugin].

When I type 'npm start' on command, I got the this error message.

**Comment by delvedor** [comment]
I understood you problem.
You can run the server in two ways:
```js
const fastify = require('fastify')();

fastify.get('/', async (request, reply) => {
  return { hello: 'world' }
})

// Run the server!
fastify.listen(3000, function (err) {
  if (err) throw err
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
})
```
With
```
node server.js
```

**OR**
```js
async function routes (fastify, options) {
  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
}
module.exports = routes;
```
With
```
fastify server.js
```

At the [end of the getting started](https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md#run-your-server-from-cli) guide you can see how the CLI works.

**Comment by magichim** [comment]
Thanks! I understand.
But I have another question about fastify-cli.

After fastify-cli installed as --save in local folder, I try to type 'fastify server.js', but not found fastify command. and then I installed globally fastify-cli, but also I got the error message
```
Cannot find module 'fastify'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/fastify-cli/cli.js:13:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
Otherwise, like npm start or test, It is good working!

To use fastify-cli, I have to write on package.json script?

**Comment by jsumners** [comment]
You have to configure your `PATH` to include `./node_modules/.bin/`. Or you can use npm's new `npx` tool https://www.npmjs.com/package/npx

**Comment by mandaputtra** [comment]
Error happen even if a fuction with fastify-cli?

db-connector.js
```
const fp = require('fastify-plugin')
const mongoose = require('mongoose')
module.exports = fp( async (fastify, opts) => {
  const url =opts.url
 delete opts.url
  // put your mongoose options here
  opts.useNewUrlParser = true
  const db = await mongoose.connect(url, opts)
  fastify.decorate('mongo', db)
})
```
app.js
```
module.exports = function (fastify, opts, next) {
  // Place here your custom code!
  // mongoose plugins connect database
  fastify.register(require('./db-connector'), {
    url: 'mongodb://localhost:27017/server'
  })
  ...
  next()
}
```

**Comment by mcollina** [comment]
It shouldn't happen. Can you upload a full project that shows the behavior?

**Comment by Adityapanther** [comment]
I am getting same error after installing and running with `fastify-cli` command `npm start` .  without `fastify-cli command` `server.js` running well with `node server.js`

**Comment by jsumners** [comment]
This issue is three years old. Please open a new issue if you are encountering a problem with the latest versions of the modules.
