### ISSUE TITLE
Schema is validated also for GET requests

### ISSUE THREAD

**Issue by Cosbgn** [fastify/fastify#2627]
## 🐛 Bug Report

The `schema.body` should validate *only* POST & PUT requests as per docs. Fastify now is validating also GET requests.
An live example is here: https://codesandbox.io/s/hungry-stonebraker-o03t6?file=/src/build.js

## To Reproduce

```js
  app.route({
    url: "/",
    method: ["GET", "POST"],
    schema: {
      body: { type: "object" }
    },
    handler: async (request) => {
      return { response: "Hey there" };
    }
  });
```

## Expected behavior

I should be able to get the route without an error.

## Your Environment

- *node version*: 12
- *fastify version*: latest
- *os*: Mac

**Comment by Cosbgn** [comment]
A temporary solution to this issue is to add `nullable:true` in the schema like this:
```
schema: {
      body: { type: "object", nullable:true }
    },
```
However this is not a real solution since the `POST` can not be `null` and the `GET` request should not be validated at all, I can't allow all my schemas to be `null` just for the `GET` requests.

**Comment by mcollina** [comment]
The schema is used as a protection of the handler. Your handler can accept a request with and without a body - so the body can be nullable. 

I find the behavior and the proposed solution correct.

What's your use case? I find a bit unusual have the GET and POST implementation on the same handler when using a schema.

**Comment by Cosbgn** [comment]
My use case is something like this:
```
app.route({
    url: "/todos",
    method: ["GET", "POST"],
    schema: {
      body: { type: "object", properties:{todo_name:{type:"string"} [....ETC] }}
    },
    handler: async (request) => {
                const user = fetch_user() // This actually is in a preHandler and user would be `user = request.user`
		if (request.raw.method === "GET"){
			const todos = await db.get("todos", user.id)
			return {todos: todos}
		}
		else if (request.raw.method === "POST") {
			const new_todo_id = await db.add_one(request.body, user.id)
			return {id:new_todo_id}
		}
    }
  });
```
Pretty much have a route where I can fetch all the data for a user **and** post some new data.
Then I have a different route like `/todos/:todo_id` where I can DELETE or PUT a todo. The logic of the routes seems to make sense for me.

In my opinion the schema should protect the handler only if it's a POST or PUT, it doesn't make sense to validate the body for a GET request because it will always be null, GET requests can never have a body, why should we validate it? 
Also in the docs it mentions that the validation occurs only for a POST or PUT.

The problem of adding `nullable` is that sending a POST request without body will be ok when in reality is not. What's the advantage of also validating GET requests? Is there any advantage I'm missing?

**Comment by mcollina** [comment]
The recommended way would be to remove that if and define two handlers. You essentially have two handlers in one.

---

The advantage is to avoid a few if branches in the validation phase which is already quite expensive.

**Comment by Cosbgn** [comment]
Ok, if this way the handler is faster it makes sense to have it this way. Thanks for the explanation.
