### ISSUE TITLE
logSerializers is missing in typescript (3.6.0)

### ISSUE THREAD

**Issue by botstar-quang** [fastify/fastify#2629]
## 🐛 Bug Report

logSerializers is mentioned in docs but can find it in typescript code and I tried to workaround with any type but it didn't log my custom field, please have a check.

https://www.fastify.io/docs/latest/Routes/#custom-log-serializer
https://www.fastify.io/docs/latest/Routes/#routes-option

## Your Environment

- *node version*: 14
- *fastify version*: 3.6.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by botstar-quang** [comment]
Unfortunately not in these weeks, I'm doing a MVP product so I'll try to workaround atm. Thanks great framework btw!
