### ISSUE TITLE
Reply `send` Method Does Not Set 204 Status

### ISSUE THREAD

**Issue by wooliet** [fastify/fastify#263]
Documentation for `Reply` states that not sending any content results in `204` status response.

https://github.com/fastify/fastify/blob/master/docs/Reply.md#code
> If not settled via `reply.code`, the resulting statusCode will be `200` or `204` if there is not content to send.

I don't think this is the case, but I might be missing something. 

[_reply.js #37_](https://github.com/fastify/fastify/blob/master/lib/reply.js#L37)
```javascript
if (payload === undefined) {
  if (!this.res.statusCode) {
    this.res.statusCode = 204
  }
```

From what I can tell, `res.statusCode` will already be set to `200` (its default value). So calling `reply.send()` will send status `200` and _not_ `204`.

If the above is correct, I believe the relevant portion of the documentation should be removed.

**Comment by mcollina** [comment]
Good spot! I tend to say the code is assuming too much and it should not attach a status code. Would you mind sending a PR?

**Comment by nileshmali** [comment]
@mcollina You mean we should remove below block and update docs?
```
if (!this.res.statusCode) {
  this.res.statusCode = 204
}
```

**Comment by mcollina** [comment]
Yes.
