### ISSUE TITLE
[Minor] Wrong anchor link in Docs

### ISSUE THREAD

**Issue by Jelenkee** [fastify/fastify#2633]
In der [Docs](https://www.fastify.io/docs/latest/Reply/) for Reply the anchor link for _Redirect_ does not work.
* Link: `#redirectdest`
* actual id: `redirectcode--dest`

I don't know how to fix that. Seems like a problem with the markdown-to-html conversion.

**Comment by pgcalixto** [comment]
I assume this issue can be closed now, since it was solved in https://github.com/fastify/fastify/pull/2640, right? :)
