### ISSUE TITLE
Property use does not exist on type FastifyInstance

### ISSUE THREAD

**Issue by matthsena** [fastify/fastify#2634]
## 🐛 Bug Report

I'm trying to use cors middleware in my project, with middie and Typescript, but have a problem with **fastify.use** type, return this error: 
> Property 'use' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>'.ts(2339)

## To Reproduce

```js
import Fastify, {FastifyInstance}  from 'fastify'

import { Server, IncomingMessage, ServerResponse } from 'http'


const build = async (): Promise<FastifyInstance<Server, IncomingMessage, ServerResponse>> => {
  const fastify = Fastify()

  await fastify.register(require('middie'))

  fastify.use(require('cors')())

  return fastify
}

build()
  .then(fastify => fastify.listen(3000))
  .catch(console.log)
```

## Expected behavior

Don't show this issue

## Your Environment

- *node version*: v14.12.0
- *fastify version*: ^3.7.0
- *typescript version*:  ^3.9.5
- *middie version* : ^5.1.0 
- *os*: MacOS Catalina 10.15.7

**Comment by Ethan-Arrowood** [comment]
I believe there is a PR on middie to add the use type

**Comment by mcollina** [comment]
I'll ship a new release of Middie and fastify-express today.

**Comment by mcollina** [comment]
middie and fastify-express shipped.

**Comment by dlydiard** [comment]
I get the same error `Property 'use' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike`.  Should `use()` be in the definition file?
using:

+ fastify 3.9.1
+ middie 5.2.0
+ typescript 3.3.7
+ node 14.4.0

**Comment by fox1t** [comment]
I suppose that fastify-express should decorate the Fastify namespace with the `.use` method as per https://github.com/fastify/fastify-express/blob/master/index.d.ts#L9

Can you provide a repro repo to check against?

**Comment by dlydiard** [comment]
Here you go https://github.com/dlydiard/fastify-express-ts-issue

**Comment by cpeisert** [comment]
I resolved the Typescript error by importing `middie` instead of using `require`.

**Before (error)**

```typescript
const server = fastify();

(async () => {
  await server.register(require('middie'));
})();
```

**After**

```typescript
import middie from "middie";

const server = fastify();

(async () => {
  await server.register(middie);
})();
```

**Comment by BUddha10** [comment]
//util file

async function dbconnector(fastify, options) {
	try {
		await client.connect()
		console.log('db connected succesfully')
		fastify.decorate('db', { client })
	} catch (err) {
		console.error(err)
	}
}
module.exports = fastifyPlugin(dbconnector)

//index file
const dbconnector = require('./utils/db')
fastify.register(dbconnector)


but whenever i try to do "fastify.db" it shows the below error

Property 'db' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike

**Comment by RafaelGSS** [comment]
When you decorate a plugin, is had better to use the declaration merging to add that property to `FastifyInstance`. See at: https://www.fastify.io/docs/latest/TypeScript/

**Comment by bchoii** [comment]
Document location moved to https://www.fastify.io/docs/latest/Reference/TypeScript/

**Comment by YChebotaev** [comment]
Same problem:

<img width="538" alt="Screenshot 2023-11-29 at 18 08 24" src="https://github.com/fastify/help/assets/5302856/91dbdaef-0347-4c34-b7bb-c7552b3b05c0">

<img width="790" alt="Screenshot 2023-11-29 at 18 08 40" src="https://github.com/fastify/help/assets/5302856/a03a46e9-443e-46a5-b09e-b563712a0da0">

**Comment by Uzlopak** [comment]
Its not the same issue. Please open a new issue.
