### ISSUE TITLE
Hooks docs issue

### ISSUE THREAD

**Issue by AviBueno** [fastify/fastify#2639]
The [Hooks documentation (latest v3.7.x)](https://www.fastify.io/docs/v3.7.x/Hooks/) contains examples that end with an empty `return` call.
How do you guys feel about removing those?

---

Examples:

https://www.fastify.io/docs/v3.7.x/Hooks/#onrequest

    fastify.addHook('onRequest', async (request, reply) => {
      // Some code
      await asyncMethod()
      return
    })

https://www.fastify.io/docs/v3.7.x/Hooks/#prehandler

    fastify.addHook('preHandler', async (request, reply) => {
      // Some code
      await asyncMethod()
      return
    })

**Comment by mcollina** [comment]
go for it.

**Comment by pgcalixto** [comment]
I assume this issue can be closed now, since it was solved in https://github.com/fastify/fastify/pull/2643, right? :)
