### ISSUE TITLE
Support case insensitive query parameters

### ISSUE THREAD

**Issue by thomasthiebaud** [fastify/fastify#2644]
## 🚀 Feature Proposal

Could it be possible to support an optional case insentive option for query parameters?  Adding the option `caseSensitive: false` does not seems to impact query parameters

## Motivation

For backward compatibilitites you sometime need to support multiple casing 

## Example

With that code

```
fastify.get<{ Querystring: { test: string } }>(
    "/caseinsensitivequery",
    async (request, reply) => {
      return { test: request.query.test };
    }
  );
```

Both tests below should pass 

```
let res = await request.get("/caseinsensitivequery?test=yes");
expect(res.body).toEqual({ test: "yes" });
res = await request.get("/caseinsensitivequery?tEsT=yes");
expect(res.body).toEqual({ test: "yes" });
```

**Comment by mcollina** [comment]
Yes of course! Would you like to send a PR?

Note that you can work around this pretty easily by overwriting https://www.fastify.io/docs/latest/Server/#querystringparser, which would by recommended fix, e.g. call `toLowerCase()`  if `caseSensitive` is set to `false`.

**Comment by thomasthiebaud** [comment]
I won't be able to access my computer next week, so if someone wants to fix it before they are more than welcome. Otherwise I'll have a look in a week time

**Comment by julesnuggy** [comment]
I'm happy to take a look into this today :-)

**Comment by mcollina** [comment]
Great, thanks!

**Comment by pgcalixto** [comment]
Hey, guys, I've just opened a PR to address this issue but there are some things to consider about this, which I commented in the PR: https://github.com/fastify/fastify/pull/2649

**Comment by julesnuggy** [comment]
Looks like someone else beat me to it 😑

**Comment by pgcalixto** [comment]
I'm sorry, @julesnuggy :(
I've created a PR more to be a point of discussion about what I commented there, than to take someone's credit. You're more than welcome to discuss the problem that I commented in the PR.

**Comment by naseemkullah** [comment]
Looking at closed PRs it seems like this should change to a docs PR to recommend using qs for case insensitivity.

**Comment by jsumners** [comment]
> Looking at closed PRs it seems like this should change to a docs PR to recommend using qs for case insensitivity.

Correct. Would you like to create that PR?

**Comment by naseemkullah** [comment]
Sure!

**Comment by Nazeeh21** [comment]
If this issue still persists can I work on this?

**Comment by mcollina** [comment]
go for it!

**Comment by Nazeeh21** [comment]
I checked the [contributing guidelines](https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md), I have a little doubt. Do I need to fork this repo or I will get contributing access to this repo?

**Comment by jsumners** [comment]
> I checked the [contributing guidelines](https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md?rgh-link-date=2021-07-28T19%3A09%3A49Z), I have a little doubt. Do I need to fork this repo or I will get contributing access to this repo?

Please follow the traditional GitHub workflow of:

1. Forking
2. Creating a feature branch with your changes
3. Issuing a pull request back upstream from your feature branch

**Comment by Nazeeh21** [comment]
I have added the code for handling *caseInsensitive* in `queryStrings`. 
While running the tests, I am passing all the tests but getting `exit code 1`  as below.

![image](https://user-images.githubusercontent.com/56908732/127497255-6676fd49-a1ae-4375-aba1-9cae863eeea0.png)
Will you please help me with this error.

**Comment by jsumners** [comment]
@Nazeeh21 what is unclear about the error? The coverage requirements are not met.

Also, the desired "fix" for this issue is a documentation change, not a code change:

https://github.com/fastify/fastify/issues/2644#issuecomment-756778461

**Comment by Nazeeh21** [comment]
There is a misunderstanding on my side. Sorry for that. I'll soon submit a PR with the required fix in the documentation.
