### ISSUE TITLE
reply.sent is false in setErrorHandler

### ISSUE THREAD

**Issue by sergiz** [fastify/fastify#2653]
## 🐛 Bug Report

reply.sent property is supposed to indicate, if .send() was already used, but it does not work properly in .setEventHandler(). It will be false, even if .send() was used in the route handler. It will only turn true, if .send() was used in .setEventHandler().

## To Reproduce

```js
fastify.setErrorHandler((error, request, reply) => {
  console.log(reply.sent);
});

fastify.get('/', async (request, reply) => {
  reply.send({ test: true });
  throw new Error();
});
```

## Expected behavior

I would expect to see "true" printed in my console, but I see "false".

```js
true
```

## Your Environment

- *node version*: 12.19.0
- *fastify version*: >=3.4.1
- *os*: Linux

**Comment by jsumners** [comment]
You didn't `await reply.send` so the execution order is non-deterministic.

**Comment by sergiz** [comment]
Just tested, and it doesn't make a difference.

"reply.raw.writableEnded" and "reply.raw.writableFinished" are both true under setErrorHandler, while "reply.sent" is false.

**Comment by mcollina** [comment]
This is a bug both in Fastify and your own code. In Fastify the error handler should not be called at all, as you are throwing after having already replied. The error handler is to respond with an error... and there is nothing to respond here.

Note that your code should not be rely on forking the promise chain with that internal call to .send(). It is side-effect logic with can lead to hard to track bugs.

**Comment by RafaelGSS** [comment]
This behavior only occurs because your route handler returns a promise, so:
```
fastify.setErrorHandler((error, request, reply) => {
  console.log(reply.sent) // here is called;
});

fastify.get('/', async (request, reply) => {
  reply.send({ test: true });
  throw new Error();
});
```

```diff
fastify.setErrorHandler((error, request, reply) => {
+  console.log(reply.sent) // here is not called;
-  console.log(reply.sent) // here is called;
});

+ fastify.get('/', (request, reply) => {
- fastify.get('/', async (request, reply) => {
  reply.send({ test: true });
  throw new Error();
});
```

This is definitely a bug, I discovering this issue and the problem occurs because [here](https://github.com/fastify/fastify/blob/master/lib/wrapThenable.js#L37) we are setting `replySent = false`. But, it seems as expected behavior on this code path. @mcollina Do you have an idea where the fix should be placed?

**Comment by sergiz** [comment]
Well my use case is actually this:
```js
fastify.get('/', async (request, reply) => {
  reply.code(202).send();

  await someAsyncFunction();
});
```

I want to run some code after reply is sent. Now in setErrorHandler I check, if reply was already sent and if it was crash the nodejs process. If it was not, I reply with an error. I could refactor that to not use async function as a handler, but then I cannot easily log which request crashed the node. Therefore, I don't really see setErrorHandler being called in this case as a bug, but as a feature :D My only concern was that reply.sent was beeing false in setErrorHandler, but now I used "reply.raw.writableEnded" instead and it's working as I intended.

**Comment by mcollina** [comment]
I highly recommend _not_ to do that. it's an antipattern. Your response will already be sent when the async function resolves, and you are 1) keeping all the req/reply (and related node core objects) alive until the function finishes 2) make it impossible to report an error to the user, breaking the "transactionality" of the request/response pattern of HTTP.

**Comment by sergiz** [comment]
Thanks for the notice, I refactored my handler now. 

Then I guess that in such case unhandledRejection should be thrown instead of it being routed to the SetErrorHandler.

**Comment by kibertoad** [comment]
>  In Fastify the error handler should not be called at all, as you are throwing after having already replied. The error handler is to respond with an error... and there is nothing to respond here.

Isn't there still value in at least logging the error that has occurred in a centralized way, even if you are not going to send any reploy anymore?

**Comment by mcollina** [comment]
> >  In Fastify the error handler should not be called at all, as you are throwing after having already replied. The error handler is to respond with an error... and there is nothing to respond here.
> 
> 
> 
> Isn't there still value in at least logging the error that has occurred in a centralized way, even if you are not going to send any reploy anymore?

There is value. How would you solve this then?

**Comment by kibertoad** [comment]
@mcollina Usually we handled that in our applications by doing `reply.sent` check inside errorHandler itself, to determine if to send reply or not, and logged always. After the #2774 that will no longer be an option.

**Comment by sergiz** [comment]
I think that the https://github.com/fastify/fastify/pull/2774 introduces a breaking change since the error (after reply already being sent) is silently discarded now. I imagined that the fix here would be to have reply.sent value fixed (so it would be true in ErrorHandler, if the reply was already sent (so you would have to depend on reply.raw properties).

**Comment by mcollina** [comment]
> I think that the #2774 introduces a breaking change since the error (after reply already being sent) is silently discarded now. I imagined that the fix here would be to have reply.sent value fixed (so it would be true in ErrorHandler, if the reply was already sent (so you wouldn't have to depend on reply.raw properties).

It is not _silently_ discarded, it's logged: https://github.com/fastify/fastify/pull/2774/files#diff-6e48f882e844850ff4f1e19b8b75c410e8ea1625000a4b05d3a90edd396c08f8R34.

**Comment by sergiz** [comment]
It's true that it is logged, but from programming standpoint there is no way to act on it (unlike if an error was thrown).

**Comment by mcollina** [comment]
> It's true that it is logged, but from programming standpoint there is no way to act on it (unlike if an error was thrown).

What's the use case of acting on the error? a response we already sent and the goal of the error handler is to generate one.

**Comment by sergiz** [comment]
I thought that the purpose of error handler was to handle errors? I believe that I should have the control of what should happen when an errors occurs. Now fastify decides for me that everything is fine and it should go on (which is not, that's how I even came across the thing that made me open this issue).

In my opinion error handler should be called in every case when there is an error, even if response was already sent. It's then up to the user to check "reply.sent" property and decide what to do.

Maybe it's just me, but I have a feeling that fastify is made to run as long as possible no matter what it takes. I prefer to let it crash, if I'm not explicitly handling some case because that indicates that I'm doing something wrong. However, fastify simply swallows many errors (only logging them) instead of throwing them, so the user cannot decide if they want to disregard them or crash the program.

**Comment by mcollina** [comment]
(This issue should have been closed long ago, nothing is related to your comment)

**Comment by mcollina** [comment]
> I thought that the purpose of error handler was to handle errors? I believe that I should have the control of what should happen when an errors occurs. Now fastify decides for me that everything is fine and it should go on (which is not, that's how I even came across the thing that made me open this issue).

From a request/reply and web-framework centric view of the world, if an error happens after a response has already been sent there is _nothing_ Fastify can do. The purpose of the error handler is to return something out to the user to let them know that an application error happened.

> Maybe it's just me, but I have a feeling that fastify is made to run as long as possible no matter what it takes. I prefer to let it crash, if I'm not explicitly handling some case because that indicates that I'm doing something wrong. However, fastify simply swallows many errors (only logging them) instead of throwing them, so the user cannot decide if they want to disregard them or crash the program.

Can you make an example of the error you are encountering where you'd need to crash your application?

**Comment by sergiz** [comment]
> From a request/reply and web-framework centric view of the world, if an error happens after a response has already been sent there is _nothing_ Fastify can do. The purpose of the error handler is to return something out to the user to let them know that an application error happened.

That's correct, there's nothing fastify can do, but the creator of the application that uses fastify can. However, fastify prevents that by swallowing errors instead of throwing them.

> Can you make an example of the error you are encountering where you'd need to crash your application?

A request is received to delete a resource. Fastify receives the request, deletes the resource locally, but then there's a bug and error happens. Fastify replies to the request indicating that error happened and the server keeps going.
The side that made that request sees non-successful response code that indicates that deletion was not successful and the resouce is not deleted on their side, but it was on our side.
If the error was thrown (and we decided to crash the server), it would re-sync on startup, but now it won't because we don't even know that error happened.

This is not really directly related to this issue (it was just about reply.sent not being set to true). I opened a help request for this: https://github.com/fastify/help/issues/371

**Comment by sergiz** [comment]
> From a request/reply and web-framework centric view of the world, if an error happens after a response has already been sent there is _nothing_ Fastify can do. The purpose of the error handler is to return something out to the user to let them know that an application error happened.

I agree. I didn't necessary mean that fastify's error handler should be invoked, but still if a fastify has a problem with what I am (or it is) doing it should clearly tell me that by throwing an error, not sometimes 1) throwing it, sometimes 2) logging it and sometimes simply 3) swallowing it without an indication.

1) Most of the errors from errors.js are thrown which is perfect.
2) Errors like FST_ERR_PROMISE_NOT_FULFILLED and FST_ERR_REP_ALREADY_SENT are only logged which already kinda hides them away and you cannot programically decide what to do with them.
https://github.com/vichle/fastify/blob/2b4b1ee4c61b34d0edf3183f6dbd0525144cbdb7/lib/wrapThenable.js#L34 only logs an error that could be potentically fatal to the application.
3) https://github.com/fastify/help/issues/371#issue-809215837 and here we have an example where an error is swallowed without any indication.

If I understand correctly, fastify is done when response is sent, which is perfectly fine, but what I don't understand is, why does it then not **always** throw an error when something "bad" happens? As demonstrated above, it either does one of the three things.

> Can you make an example of the error you are encountering where you'd need to crash your application?

https://github.com/fastify/help/issues/371
If an unexpected error happened in my handler, there seems to be no way to propagate it upward the stack (so it reaches uncaught exception handler and get a suitable handling there).

Let's say that the error happened at a half way of the handler where some things were already performed. Since it was unexpected error, I would let my application to crash and restart (it will re-sync itself during the startup).

**Comment by mcollina** [comment]
Those two problems arises from the fact that we support both `reply.send(value)` and `return value` inside handlers. We have decided to be lenient on those cases because developers make significant mistakes when using promises. They are essentially "code smells" and bad programming practices.

You are essentially asking for https://github.com/vichle/fastify/blob/2b4b1ee4c61b34d0edf3183f6dbd0525144cbdb7/lib/wrapThenable.js#L30-L36 to lead to unhandledRejections instead of just being logged. I recommend you to create a fresh issue with that (you can reuse part of your comments above).
