### ISSUE TITLE
query params with '+' removed from req.query

### ISSUE THREAD

**Issue by suchcodemuchwow** [fastify/fastify#2658]
```
const querySchema = {
    user_id: { type: 'string' },
    user_phone: { type: 'string' },
};
```

When I tried to send `?user_phone=+467325+44690` in handler `req.query.user_phone` returns **" 467325 44690"** which shows "+" is replaced with "  " (blank) somehow. Is this some security feature or a bug ? 

If it's security feature, how can I override this behaviour I couldn't find information around that in docs.

**Comment by mcollina** [comment]
This is the first result from Google: https://stackoverflow.com/questions/6855624/plus-sign-in-query-string. It's a good answer.

**Comment by suchcodemuchwow** [comment]
Ouch I was testing from postman and assumed it transformed "+" to "%2B" which didn't when I manually . Sorry for taking time :(
