### ISSUE TITLE
Error validating schema after Fastify upgrade

### ISSUE THREAD

**Issue by quiro91** [fastify/fastify#2659]
## 🐛 Bug Report

After upgrading from Fastify 2.11.1 to 2.12.1 (but the issue persists in Fastify 2.15.3) I get the following error:
```
ReferenceError: fastify is not defined
    at $arr$maincomponents (eval at build (/path/node_modules/fast-json-stringify/index.js:149:20), <anonymous>:236:11)
    at Object.$main (eval at build (/path/node_modules/fast-json-stringify/index.js:149:20), <anonymous>:148:17)
    at serialize (/path/node_modules/fastify/lib/validation.js:132:41)
    at preserializeHookEnd (/path/node_modules/fastify/lib/reply.js:327:15)
    at preserializeHook (/path/node_modules/fastify/lib/reply.js:314:5)
    at _Reply.Reply.send (/path/node_modules/fastify/lib/reply.js:167:7)
    at /path/node_modules/fastify/lib/wrapThenable.js:27:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I know this is probably not enough to understand what's going on, but the validation schema looks fine to me and it was previously working. Any suggestion about how I can further debug this?
## Your Environment

- *node version*: 12.9.0
- *fastify version*: >=2.12.1
- *os*: Mac

**Comment by RafaelGSS** [comment]
Can you provide a reproduction code? Without it, we can't figure out what's going on.

**Comment by quiro91** [comment]
Hey @RafaelGSS , I'm trying to put together a reproduction sample, but in the meantime I've got some more detail on the cause of the bug. I believe it's because in our schema we have something like:
```
module.exports = {
    $id: 'responseId',
    type: 'object',
    properties: {
        elements: {
            type: 'array',
            items: { anyOf: ['objectId#'] },
        },
    },
};
```
it appears that while `items: { anyOf: ['objectId#'] }` was supported in Fastify 2.11.1, it isn't anymore. If I put the content of the schema with id `objectId`, then it works. Is this expected?

**Comment by RafaelGSS** [comment]
Not sure @quiro91. It's hard without a simple reproduction code to proves that it's been working as expected.

However, if your code runs properly on Fastify@2 and crashes on Fastify@3 seems a breaking change on `fast-json-stringify`

**Comment by Eomm** [comment]
> Is this expected?

Yes, it is: you may check the [migration guide](https://github.com/fastify/fastify/blob/master/docs/Migration-Guide-V3.md#changed-schema-substitution-2023) to check how to upgrade your schemas
