### ISSUE TITLE
Async handler doesn't support all HTTP response codes that don't require content

### ISSUE THREAD

**Issue by sergiz** [fastify/fastify#2664]
## To Reproduce

```js
fastify.post('/', async (request, reply) => {
  reply.code(202);
});
```

## Expected behavior

There are more HTTP response codes than 204, which do not require any content to be returned. For example 202 or 205. Fastify only supports using 204 and returning "undefined". However, you can use .send() method with others and it's working. For example:
```js
fastify.post('/', async (request, reply) => {
  reply.code(202).send();
});
```

## Your Environment

- *node version*: 12.19.0
- *fastify version*: 3.4.1
- *os*: Linux

**Comment by mcollina** [comment]
Wow, good spot! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by yigitkurtcu** [comment]
If this bug still exists, I can take a look at this.

**Comment by mcollina** [comment]
go for it!

**Comment by yigitkurtcu** [comment]
Should async handler support all HTTP codes to return zero-length payload? Can you give me some ideas for solving to issue? @mcollina

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/blob/master/lib/wrapThenable.js should be adapted to check for the other status codes with no body.

**Comment by sergiz** [comment]
Even after reading docs and the code (wrapThenable.js and reply.js in particular) multiple times, I still don't understand what's the matter with promise resolving with undefined. At what point does payload of "undefined" changes the execution flow?

**Comment by sergiz** [comment]
Even after reading docs and the code (wrapThenable.js in particular) multiple times, I still don't understand what's the matter with promise resolving with undefined. At what point does payload of "undefined" changes the execution flow?

**Comment by mcollina** [comment]
Handling `undefined` makes sure that the following is possible:

```js
fastify.post('/', async (request, reply) => {
  setTimeout(() => {
    reply.code(200).send('hello world');
  }, 1000)
});
```

**Comment by sergiz** [comment]
That is actually incorrect. The error will still be thrown

> Promise may not be fulfilled with 'undefined' when statusCode is not 204

The proper example is in the docs: https://www.fastify.io/docs/latest/Routes/#async-await
You have to await or return reply in such case.

Technically your example works, but the error is throw every time, so I would say such usage is discouraged and undocumented. The docs have shown the proper example at least since Fastify 2.9 (https://www.fastify.io/docs/v2.9.x/Routes/#async-await).

Considering these facts, my proposal is to remove this "undefined" check and error, and handle "underfined" as a proper payload. This way we also don't need to explicily state http response codes that do not require any payload.

**Comment by jsumners** [comment]
I would check if `undefined` is returned _and_ an empty response code has been set. Leave the current `undefined` handling behavior in all other cases.

**Comment by sergiz** [comment]
That would be an option, but there is currently no "undefined handling behavior" as I showed. If someone was doing that, it would mean that he is spamming his logs with that error on every request.

**Comment by jsumners** [comment]
The documentation is was written specifically to highlight the case you are describing as _not supported_. Whereas returning `undefined` _is_ supported.

**Comment by sergiz** [comment]
Which case are we talking about now?

It is true that the documentation says:

>     Don't return any value.
>     Don't forget to call reply.send.

However, the code clearly says that this can't work:
https://github.com/fastify/fastify/blob/528a5f74dbf4ecae0ffd33096bc9ab44599a9293/lib/wrapThenable.js#L29-L31

**Comment by sergiz** [comment]
Which case are we talking about now?

It is true that the documentation says:

>     Don't return any value.
>     Don't forget to call reply.send.

That is true, so we do not run into the following problem:

> When using both return value and reply.send(value) at the same time, the first one that happens takes precedence, the second value will be discarded, and a warn log will also be emitted because you tried to send a response twice.

However, this does not apply, if we want to send response outside the promise chain. Documentation also shows us two examples (https://www.fastify.io/docs/v3.4.x/Routes/#async-await) how to handle such case;; we can either await or return reply, and then safely use reply.send() outside the promise chain.
Such interpretation is also supported by the code. It will log an error telling us that we cannot return "undefined" while not using reply.send() in the same promise chain.
https://github.com/fastify/fastify/blob/528a5f74dbf4ecae0ffd33096bc9ab44599a9293/lib/wrapThenable.js#L29-L31

Even if you disagree with my interpretation of the docs above, the code doesn't lie.

That's why I suggest to simply allow returning "undefined". This shouldn't break anything because the callback-style usage already requires returning or awaiting reply (since the error is logged otherwise).

**Comment by mcollina** [comment]
I think code trumps discussions... so maybe would you like to send a PR to discuss further? I think the code is the way it is to cover for certain use cases. We could always ship breaking changes in v4.

**Comment by sergiz** [comment]
Sure. I will open a PR tomorrow and we can continue the discussion there then.
