### ISSUE TITLE
remove request from our dependency tree

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#268]
Unfortunately, the request module do not follow semver and they have dropped support of a node.js major releases in one of their minor.

What alternatives do we have? Should we write a new one?

**Comment by delvedor** [comment]
We could use [`simple-get`](https://github.com/feross/simple-get) or [`got`](https://github.com/sindresorhus/got).

**Comment by mcollina** [comment]
I'd say https://www.npmjs.com/package/simple-get fits our need perfectly, but got is also beautiful.

**Comment by StarpTech** [comment]
I also like https://github.com/mzabriskie/axios with automatic JSON support just as fastify.

**Comment by delvedor** [comment]
@StarpTech axios is definitely too big, at the moment we are using `request` which suffers the same problem. I prefer something more easy a lightweight.

**Comment by jsumners** [comment]
**simple-get**:

1. No extra dependencies: 👍
2. Old issue and, currently, month old PR with no response: 👎

**got**:

1. Many extra dependencies: 👎
2. Many open issues: 👎

I would vote `simple-get`.

**Comment by bhanuc** [comment]
Have you guys checked out [needle](https://github.com/tomas/needle) and [superagent](https://github.com/visionmedia/superagent)

**Comment by allevo** [comment]
Closed by https://github.com/fastify/fastify/pull/373
