### ISSUE TITLE
Fastify simply considers any object literal as ajv schema

### ISSUE THREAD

**Issue by erfanium** [fastify/fastify#2680]
I want to use `fastest-validator` with fastify as custom validator, but fastify recognizes `fastest-validator` schemes as Ajv schema and manipulates them.

This's what happens here: https://github.com/fastify/fastify/blob/11757779acecf58c5caee1143348523b6c3591aa/lib/schemas.js#L66
There should be an option to force disable this behavior

## To Reproduce

```js
const fastify = require('fastify');
const app = fastify();

app.route({
  method: 'POST',
  url: '/foo',
  schema: {
    body: {  // fastest-validator schema
      foo: 'string' ,
      bar: 'string[]'
    }
  },
  async handler(req, rep) {
    return 'ok';
  },
  validatorCompiler: ({ schema }) => {
    console.log(schema)
  }
});
```
## Expected behavior

In above code, `schema` is `{ type: 'object', properties: { foo: 'string',  bar: 'string[]' } }` instead of `{ foo: 'string',  bar: 'string[]' }`

- *node version*: 14.13.0
- *fastify version*: 3.7.0
- *os*: Linux
- *any other relevant information*

**Comment by Eomm** [comment]
That syntax has been introduced to ease the input definition of the schema, and as you pointed out the check is this one:

https://github.com/fastify/fastify/blob/master/lib/schemas.js#L115

We could:
- avoid augmentation when a custom validator has been set (this would be a breaking change)
- add an option to be stricter


Right now, the only way I see to avoid this behaviour on v3.x would be to add a "fake type" prop that can be deleted on the `validatorCompiler`:

```
  schema: {
    body: {  // fastest-validator schema
      foo: 'string' ,
      bar: 'string[]',
      type: 'hello',
    }
  },
```

**Comment by erfanium** [comment]
@Eomm Thanks, I currently use `schema.properties` in `validatorCompiler` and works fine so far. but as you say, some how we should disable augmentation when using custom validator

**Comment by erfanium** [comment]
@Eomm I would like to make a PR for this, My idea is to add a option argument to `setValidatorCompiler` method:
```js
const fastify = require('fastify')()
fastify.setValidatorCompiler(() => { ... }, { disableAugmentation: true  })
```
Do you think that's good?

**Comment by Eomm** [comment]
The call we need to fix is this one:

https://github.com/fastify/fastify/blob/a927f5d08092ae916a8e64d45ae83730286b14e8/lib/route.js#L263

(it happen before the checks of the validatorCompiler)

I like your proposal 👍 

--

I was thinking if something like this was fair enough to be able to turn on/off this syntactic sugar in each route but maybe it is useless really.

```diff
app.route({
...
  schema: {
+    options: { augmentation: false },
    body: {  // fastest-validator schema
      foo: 'string' ,
      bar: 'string[]'
    }
  },
  validatorCompiler: ({ schema }) => {
    console.log(schema)
  }
});
```

**Comment by erfanium** [comment]
@Eomm Another solution is to add `originalSchema` (I don't know if it's a good name or not) field to route `context`
```js
app.route({
  schema: {
    body: {  // fastest-validator schema
      foo: 'string' ,
      bar: 'string[]'
    }
  },
  validatorCompiler: ({ originalSchema }) => {
    console.log(originalSchema)
  }
});
```

**Comment by Eomm** [comment]
In this case, we could add a `Symbol` to the enhanced schema itself.

```diff
    return {
+      [Symbol.for('fastify.schema.enhanced')]: true,
      type: 'object',
      properties: schema
    }
```

That the `validatorCompiler` could easily check

```js
if(schema[Symbol.for('fastify.schema.enhanced')]) {
  originalSchema = schema.properties
}
```

**Comment by erfanium** [comment]
@Eomm I don't understand, why symbol is needed? There's no need to modify schema itself (by adding a symbol for example)
https://github.com/erfanium/fastify/commit/dd80f8494287442547044828ac1606b573899657
That's what I meant

**Comment by erfanium** [comment]
Also, there's another schema manipulating in `validation.js` file for headers schema, (due headers case-insensitivity)

**Comment by Eomm** [comment]
>  why symbol is needed?

That would give to users the possibility to understand if the schema has been augmented.
Notice that is not a change, since we are linking the original schema in a new object (where we can add what we need) without changing the original one.

> due headers case-insensitivity

Good spot, I forget it!
But notice that all the headers will be lowered case when submitted to a fastify endpoint, so if you avoid that I think the validation would never succeed (unless you write your own `contentParser`)

**Comment by erfanium** [comment]
> That would give to users the possibility to understand if the schema has been augmented

It's not a good idea, for two reasons:
1- Schema augmentor is an internal API, If it changes its behavior, it can easily cause a breaking change for users
2- In typescript, schema type is `unknown`, so `originalSchema = schema.properties` wont work, Unless we change the type, Which is probably not easy

> so if you avoid that I think the validation would never succeed

Yes, But It's the responsibility of the user to check that the custom validator has no problem

**Comment by erfanium** [comment]
I think Fastify core depends a lot on Ajv and proper support for custom validators without breaking changes is hard, It's better to solve these problems more completely in a major refactor

**Comment by jsumners** [comment]
Please do not introduce another case where the original schemas are mutated.

**Comment by erfanium** [comment]
I found a simple way to solve this problem, which seems to be enough for users:
```js
const fastify = require('fastify')();

class CustomSchema {
  constructor(s) {
    this.originalSchema = s;
  }
}

fastify.post('/s', {
  schema: {
    body: new CustomSchema({ foo: 'bar' }),
  },
  handler: async () => ({}),
});

fastify.setValidatorCompiler(({ schema }) => {
  if (schema instanceof CustomSchema) {
    console.log(schema.originalSchema);
  }
});

f.ready();
```
With encapsulating the schema, schema prototype is not equal to `Object` and augmentation will ignored.

Feel free to close this issue.
