### ISSUE TITLE
Router schema validation is bypassed if the content type is text/plain

### ISSUE THREAD

**Issue by multiwebinc** [fastify/fastify#2686]
## 🐛 Bug Report

If you send a POST request with the request header `Content-Type: text/plain`, it ignores the schema validation in the router and executes the handler function anyway.

## To Reproduce

Server:

```js
const schema = {
  body: {
    required: ['in', 'out'],
    properties: {
      in: {
        type: 'string',
        format: 'date',
      },
      out: {
        type: 'string',
        format: 'date',
      }
    }
  }
}

async function routes (fastify, options) {
  fastify.post(
    '/endpoint',
    { schema },
    myController.myRouteHandler
  );
}
```

Send request:

```js
fetch(api_endpoint, {
  method: "POST",
  body: JSON.stringify({foo: "bar"}),
  headers: {
    // Note: The fetch API sends header `Content-Type: text/plain` by default
    // (at least in my browser) but I've included it here anyway.
    'Content-Type': 'text/plain'
  }
});
```

## Expected behavior

I would expect the schema validation to fail and the handler function to not be executed.

## Your Environment

- *node version*: 14.15.0
- *fastify version*: 3.8.0
- *os*: Linux

**Comment by erfanium** [comment]
@multiwebinc The problem is with your schema, root level schema must have `type` key
```
const schema = {
  body: {
    type: 'object',
    required: ['in', 'out'],
    properties: {
      in: {
        type: 'string',
        format: 'date',
      },
      out: {
        type: 'string',
        format: 'date',
      }
    }
  }
}
```

**Comment by mcollina** [comment]
Note that Fastify does not parse `text/plain`. What you'd get as a `req.body` would be a string. If you want your body to be parsed as JSON, set the content-type appropriately.
