### ISSUE TITLE
Custom error properties via schemas

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#2687]
## 🚀 Feature Proposal

Right now setting the schema response of errors doesn't enhance the default error handler.

```js
const Fastify = require('fastify')
const statusCodes = require('http').STATUS_CODES

async function run () {
  const app = Fastify()

  app.get('/async-throw', {
    schema: {
      response: {
        '5xx': {
          type: 'object',
          properties: {
            statusCode: { type: 'number' },
            code: { type: 'string' },
            error: { type: 'string' },
            lang: { type: 'string' },
            message: { type: 'string' }
          }
        }
      }
    }
  }, async () => {
    const e = new Error('async-throw')
    e.code = 'this is a code'
    e.lang = 'this is a custom field' // this will be ignored
    throw e
  })

  let res
  res = await app.inject('/async-throw')
  console.log(res.payload)
  // print:
  // {"statusCode":500,"code":"this is a code","error":"Internal Server Error","message":"async-throw"}
}

run()
```

## Motivation

The user may customize the default error handler properties just defining the output schema.
This will:

- improve the benefit of using schemas
- spread the pattern to throws `Error` and not object ( #2134 )
- easier way to add custom param to an error object on custom routes

## Example

The user will be able to let the script above works out of the box without the need to customize the error handler like this

```js
  app.setErrorHandler(function (error, request, reply) {
    const statusCode = reply.statusCode
    reply.send({
      error: statusCodes[statusCode + ''],
      code: error.code,
      lang: error.lang,
      message: error.message || '',
      statusCode: statusCode
    })
  })
```

**Comment by mcollina** [comment]
My recommendation for any application is to implement their own error handler and to no rely on the default one. I think we should not really make it smarter. However this functionality looks great and something that I'd like to use in any error handler. How could we make those easier to implement? In other terms, how could we make writing error handlers route-aware?

**Comment by Eomm** [comment]
> How could we make those easier to implement?

I would try to think why a custom error handler is needed and, in my opinion, the use cases are:

- return a well-known (json) format --> the user set a response.5xx schema
- log and tracing --> it could be done by an `onError` hook
- obfuscate the error message --> it should be doable by managing the fastify config
- I18N/translation

has someone other use cases?

>  In other terms, how could we make writing error handlers route-aware?

The error handler has the request and its context, so all the schemas we need should be accessible internally, but not by the user that implement a custom error handler

----

Right now what I think is stressful and can be improved:

- if you set a custom error handler you must beware to log the error (we should do as request and reply does - adopting a pino `serializer`)
- if you set additional properties on the `Error` thrown and in the json schema output: nothing happens (and this can be fixed)
- the execution flow of the error should be better documented since it is not easy to understand without trying it (there are a bunch of use cases that could be better explained in the lifecycle doc - I'm working on it)

**Comment by mcollina** [comment]
would you send a PR @Eomm?
