### ISSUE TITLE
Errors in `onSend` makes fastify not respond

### ISSUE THREAD

**Issue by SimenB** [fastify/fastify#2692]
## 🐛 Bug Report

If an `onSend` handler (hook?) throws, the error does not bubble up to the application and the response never finishes.

## To Reproduce

```js
const fastify = require('fastify')();

fastify.route({
  path: '/hello',
  handler(_, reply) {
    reply.code(200).send();
  },
  method: 'GET',
  onSend() {
    throw new Error('boom');
  },
});

fastify.listen(3000);
```

## Expected behavior

It should return a 500 error. Changing `onSend` to

```js
onSend(_, __, ___, done) {
  done(new Error('boom'));
},
```

fixes the error. I think those 2 approaches should behave the same.

## Your Environment

- *node version*: 14.15.1
- *fastify version*: 3.8.0
- *os*: macOS
- *any other relevant information*

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by AyoubElk** [comment]
I think this should be closed.
