### ISSUE TITLE
Plugin for functional programming support

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#2705]
## 🚀 Feature Proposal

New plugin would be aware of common functional containers, such as Either and Task, and would resolve their values for response purposes automatically.

## Motivation

Reduce amount of boilerplate needed for the fully functional fastify routers to work. This is a highly desired feature from adidas dev team, represented by their solutions architect @OrahKokos.

## Example

```js
const { either, task } = require('fp-ts')

app.get('/', (req, reply) => {
  // This will return 200: { id: 1}
  return either.right({ id: 1})

  // Same as above
  return task.of(Promise.resolve({ id: 1}))

  // This will propagate to fastify error handler, which by default will return 500: Internal server error
  return either.left(new Error('Invalid state'))
});
```

First prototype of such plugin can be seen here: https://github.com/kibertoad/fastify-funky

**Comment by mcollina** [comment]
The plugin is really nice! Is anything specifically missing?

**Comment by Ethan-Arrowood** [comment]
Love this! Nice work 😄

**Comment by kibertoad** [comment]
@mcollina Well, probably more structures could be supported, but I guess that can be done in follow-up releases in a non-breaking way if there is demand. Other than that, I would appreciate if someone went over the code, but it should be fairly production ready.

After there is greenlight to do so, I'll transfer the plugin to `fastify` organization, it should already be implemented in a way, consistent with all our other plugins :)

**Comment by kibertoad** [comment]
Oh, and if someone has a better name for the plugin, that would also be great :D

**Comment by jsumners** [comment]
Does it need to be transferred to the org? Putting things in the org immediately burdens others with the responsibility of maintainership. I think that should be reserved for truly "core" plugins to the ecosystem. If this is such a plugin, so be it. But we should think about this each time we consider bringing code into the org.

**Comment by kibertoad** [comment]
@jsumners Would be helpful to define the criteria for what makes a core plugin then. At least for me personally this feels like a rather foundational thing that simplifies using the whole programming paradigm together with `fastify`, but then again, I'm not entirely sure why `nextjs` plugin qualifies for core, and `apollo-graphql` one does not, so I guess it is complicated.

**Comment by Ethan-Arrowood** [comment]
> Oh, and if someone has a better name for the plugin, that would also be great :D

_funky-fastify_ 🕺 

(funky... like **func**tional)

**Comment by Ethan-Arrowood** [comment]
Good point @jsumners - i'm also not sure what the qualifications of that should be. What I've always seen in the past is if a fastify core contributor authors a plugin, we merge that into the core plugins list since we trust the contributor knows how to and will maintain the plugin.

Like all open source repos, if something looses support or becomes unmaintained we can always deprecate, close out, or try and drum up more support when needed.

**Comment by jsumners** [comment]
Unfortunately, I don't have a good suggestion for guidelines. It's really up to the individual author and the team to come to a consensus on a case-by-case basis. Personally, I do not propose a module I author for org membership unless I think it is simple enough for others to maintain _and_ it fills a significant gap in the ecosystem. My go to examples are `fastify-cookie` and `fastify-server-session`. The first is in the org, the second isn't. The first is a definite need by the ecosystem, the second has multiple solutions available and I don't want the org promoting my solution as the definitive one.

For this module, my opinion is: it's really nice, but it doesn't fill that "cookie" role.

**Comment by kibertoad** [comment]
Should we do the voting on whether this belongs to the org then?

**Comment by jsumners** [comment]
Sure. I shall sit out and let the team majority decide. Just wanted to wake us up as a whole for going forward. We can't expand infinitely with our current structure.

**Comment by mcollina** [comment]
Adding a new plugin to the ecosystem adds more work because of issues, help requests, releases and when doing semver-majors. We do not have enough people involved in all the above.

My general rule is that if one of us wants something in, it should be in as long as they are willing to work on it (or it became critical, such as fastify-cookie or fastify-static).

**Comment by kibertoad** [comment]
@mcollina Obviously I would be supporting the plugin in the long run as well, so I don't think it would increase load of the other fastify team members in a significant way. Slightly off-topic, but since you've mentioned that - are there any core plugins that you find to be more neglected than the others right now? I think I could adopt one or two.

**Comment by Eomm** [comment]
> are there any core plugins that you find to be more neglected than the others right now?

I think yes:

- https://github.com/fastify/fastify-citgm (this would be really useful on major releases)
- https://github.com/fastify/fastify-swagger/ (I would like to do more here 😭 )

Some repo-tutorials that some colleagues were looking at some month ago:

- https://github.com/fastify/fastify-example-twitter
- https://github.com/fastify/fastify-example-todo

There are some empty repo too:

- https://github.com/fastify/fastify-sftp

**Comment by kibertoad** [comment]
@Eomm Oooooh, the sftp. The sleepless nights I spent trying to make that one work in Node.js properly. Do we still want that one or should it downright killed, if there was no interest?

`fastify-swagger` is a bit more than I can chew at the moment, but I'll take a look into refreshing tutorials, and see what's going on with citgm.

Thanks!

**Comment by Eomm** [comment]
> Do we still want that one or should it downright killed, if there was no interest?

Personally, I had to deal with sftp too but it was not strictly related to fastify or HTTP

**Comment by kibertoad** [comment]
@Eomm What was the idea for fastify plugin? Is there some kind of state that it is desirable to maintain? Not sure how the whole thing ties in into fastify lifecycle. If it's just a stateless client, doesn't need to be integrated with fastify.

**Comment by kibertoad** [comment]
@Eomm I get `Permission to fastify/fastify-example-todo.git denied to kibertoad.` when pushing to branch for `https://github.com/fastify/fastify-example-todo`. Do I need membership in another group for it?

**Comment by kibertoad** [comment]
@OrahKokos has confirmed that current implementation of the plugin satisfies their needs completely, so I'm getting ready to make the first public release.
So should we vote on whether or not this belongs to the core? If I understand correctly, @jsumners abstains, @Ethan-Arrowood and @mcollina are in favour. @Eomm ? @fox1t ?

**Comment by zekth** [comment]
I really like this kind of implementation but like @mcollina mentionned; it would add work to the team. I'd personnaly let it sit outside like `fastify-session`

**Comment by fox1t** [comment]
I think we can put it in the org.

**Comment by kibertoad** [comment]
@mcollina What's your final call, given the comments so far?

**Comment by jsumners** [comment]
I'd also like to hear from @delvedor.

**Comment by delvedor** [comment]
As long as there is someone of the org who would like to maintain the package I don't see why we should have it in the org :)

If in the future we can no longer maintain a plugin, we can either send out a call for maintainers or deprecate it.

**Comment by kibertoad** [comment]
@delvedor "Should" or "should not" :D?

**Comment by delvedor** [comment]
Should not, comment fixed 😅

**Comment by kibertoad** [comment]
Thanks!

**Comment by kibertoad** [comment]
https://github.com/fastify/fastify-funky -> it's alive! Will publish to npm soon.

**Comment by kibertoad** [comment]
Can someone remind me, what is our npm setup procedure? Which users should I add with admin permissions?

**Comment by mcollina** [comment]
add me and I'll add it to the npm org.

**Comment by kibertoad** [comment]
@mcollina Done! (https://www.npmjs.com/package/fastify-funky quick link to the package on npm)

**Comment by mcollina** [comment]
done
