### ISSUE TITLE
schema validation error on an async response does not trigger the error handler

### ISSUE THREAD

**Issue by iMoses** [fastify/fastify#2707]
## 🐛 Bug Report

When using response schema validation on a route with an async handler errors are not caught by the error handler set using `setErrorHandler`, unlike params schema validation.

### Update
This happens only when an async `preSerialization` handler is also present.

## To Reproduce

Let's take a simple working example:
```js
fastify.addHook("preSerialization", async (request, reply, payload) => payload);
fastify.setErrorHandler((error, request, reply) => {
  reply
    .status(error.statusCode || 500)
    .send(error instanceof Error ? { message: error.message, error: error.name } : error);
});
fastify.get(
  '/:id',
  {
    schema: {
      params: {
        type: 'object',
        required: ['id'],
        properties: { id: { type: 'string' } },
      },
      response: {
        200: {
          type: 'object',
          required: ['id'],
          properties: { id: { type: 'string' } },
        },
      },
    },
  },
  async ({ params: { id } }) => ({ id })
);
```

Now what happens if we mess it up?
1. let's replace the route param from `/:id` to `/:blah`
2. let's replace the response from `({ id })` to `({ blah: id })`

This is what produced from both changes:
1. returns the following response, as expected:
```json
{"message":"params should have required property 'id'","error":"Error"}
```
2. returns nothing and doesn't end the request, prints on the server side:
```
(node:1589948) UnhandledPromiseRejectionWarning: Error: "id" is required!
    at Object.$main (eval at build (/home/imoses/workspace/application/node_modules/fast-json-stringify/index.js:158:20), <anonymous>:135:15)
    at serialize (/home/imoses/workspace/application/node_modules/fastify/lib/validation.js:116:41)
    at preserializeHookEnd (/home/imoses/workspace/application/node_modules/fastify/lib/reply.js:349:15)
    at next (/home/imoses/workspace/application/node_modules/fastify/lib/hooks.js:198:7)
    at handleResolve (/home/imoses/workspace/application/node_modules/fastify/lib/hooks.js:209:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1589948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1589948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior

I expect a validation error on the response schema to be caught and handled by the error handler and not crash the request.

## Your Environment

- *node version*: 14
- *fastify version*: =3.8.0
- *os*: Linux

**Comment by salmanm** [comment]
Just copied your above code into [this sandbox](https://codesandbox.io/s/fastify-2707-4ougx) and I'm seeing response as expected.

`{"message":"\"id\" is required!","error":"Error"}`

**Comment by iMoses** [comment]
one more part needed, as can be seen here: https://codesandbox.io/s/fastify-2707-forked-1ompq?file=/src/index.js

```js
fastify.addHook("preSerialization", async (request, reply, payload) => payload);
```

**Comment by Eomm** [comment]
This plugin should help you: [fastify-response-validation](https://github.com/fastify/fastify-response-validation)

> I expect a validation error on the response schema to be caught and handled by the error handler and not crash the request.

I think that the `preSerialization` should not impact this snippet, since it runs before the error.
Anyway this use case worth a triage for sure

**Comment by iMoses** [comment]
After a bit of debugging...

`hooks.js` line #204
```js
change this:
      result.then(handleResolve, handleReject)
into this:
      result.then(handleResolve, handleReject).catch(handleReject)
```
the issue is that id an error occurs within the `handleResolve` then no one catches it.

**Comment by Eomm** [comment]
That syntax [`p.then(onFulfilled[, onRejected]);`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) manage the error already

I think the problem could be in the `reply.js` file

**Comment by iMoses** [comment]
@Eomm I know, and it's a bug.. Trust me on this one
The issue is that in your current configuration if an error is thrown from within the handler then it will not be catched, and this is exactly what is happening, I debugged it already.

**Comment by iMoses** [comment]
@Eomm i understand your comment about `reply` now, as it seems that the issue can also be fixed by wrapping this line in a `try...catch` [#349](https://github.com/fastify/fastify/blob/master/lib/reply.js#L349)

`preserializeHookEnd` executes internally the `serialize` method which may throw an error in case of validation errors.
as it seems, this method can end up as the callback (`cb`) of `onSendHookRunner` which will be executed as part of its internal `next()` method, which is the main functionality of `handleResolve`. 
This create a case in which `handleResolve` can throw an error and because `handleReject` is activated only on the result promise and not the result of `handleResolve` (as stated before, because of the way promises are handled) this causes everything to breakdown.

Technically, I'd still suggest my original solution as it can catch all errors and will remove the need to make sure everything is covered by a `try...catch`, but both will solve the problem just fine.

**Comment by Eomm** [comment]
With this minimal code I can replicate it:

```js
const fastify = require('./fastify')({ logger: true })

fastify.addHook('preSerialization', async (request, reply, payload) => payload)

fastify.setErrorHandler((error, request, reply) => {
  console.log('setErrorHandler', error)
  reply.send({ custom: error })
})

fastify.get('/:id', {
  schema: {
    response: {
      200: {
        type: 'object',
        required: ['id'],
        properties: { id: { type: 'string' } }
      }
    }
  }
},
function handler () { return { missing: 'id' } }
)

fastify.inject('/asd').then(res => {
  console.log(res.payload)
  console.log(res.statusCode)
})
```

I play it a bit and I agree that the `onSendHookRunner` has the bug, but it is not a matter of promises, since the hook is not throwing, but this works for me (hooks.test.js is green aswell):

```diff
    if (i === functions.length) {
+      try {
        cb(null, request, reply, payload)
+      } catch (error) {
+        handleReject(error)
+      }
      return
    }
```

Checking the `onError` hooks are executed once as well but for sure we need a bunch of tests here

Would you like to push forward your PR?
