### ISSUE TITLE
FastifyInstance interface doesn't expose errorHandler

### ISSUE THREAD

**Issue by ShaulEngler** [fastify/fastify#2711]
## 🐛 Bug Report

While documentation states that `FastifyInstance` has a `errorHandler` method:
https://www.fastify.io/docs/latest/Server/#errorhandler
And it is indeed implemented that way, but when trying to implement in TypeScript with strict compilation it fails as `FastifyInstance` doesn't expose this method:
https://github.com/fastify/fastify/blob/de94d314e940fba2c7021b0e180445a814d4d068/types/instance.d.ts

## To Reproduce

```ts
import { fastify } from 'fastify';
const fastify = fastify();
fastify.get('/testErrorHandler', errorHandler: (error, request, reply) => {
    if (error.code === 'SOMETHING_SPECIFIC') {
      reply.send({ custom: 'response' });
      return;
    }

    fastify.errorHandler(error, request, response); // <-------- this fails compilation
  }, async (_request: FastifyRequest, reply: FastifyReply) => {
  reply.status(204).send();
});

```

## Expected behavior

The above should work

## Your Environment

- *node version*: v12.13.0
- *fastify version*: 3.8.0
- *os*: Mac

**Comment by fox1t** [comment]
Can you please provide a repro repository that we can look into?

**Comment by fox1t** [comment]
I am asking for a repro since we have that handler exposed here: https://github.com/fastify/fastify/blob/de94d314e940fba2c7021b0e180445a814d4d068/types/route.d.ts#L31
