### ISSUE TITLE
Type Support for Stream in Logger Object

### ISSUE THREAD

**Issue by Sidd27** [fastify/fastify#2715]
# Bug Report

Type Error on passing stream option to logger instance of fastify when using with typescript

## To Reproduce

npm init -y
npm i fastify
npm i -D typescript @types/node

```js
const server = fastify({
  // Logger only for production
  logger: {
    stream: logStream
  }
  
});
```

## Expected behavior

Stream Property should be part of FastifyLoggerOptions interface

## Your Environment

- *node version*: 14
- *fastify version*: >=3.8.0
- *os*: Mac

**Comment by Ethan-Arrowood** [comment]
Install @types/pino and augment the logger; should work. There should also be docs explaining this in either the logger or typescript sections

**Comment by Sidd27** [comment]
@Ethan-Arrowood Before closing this you should atleast try using only stream option without passing the complete pino instance I have already referred to both section. before raising this and apart from stream other options works

**Comment by Ethan-Arrowood** [comment]
Yes, this is intended. We do not maintain Pino types so we don't support it 100% in our own types. We have implemented what we decided was the default use case for the logger, and if users want to introduce the pino types into their project that is an opt-in decision

**Comment by Sidd27** [comment]
@Ethan-Arrowood After install only `Install @types/pino` it doesn't works for stream option the only way is to install pino and create a pino instance and pass it. Is this intended ???

**Comment by Sidd27** [comment]
@Ethan-Arrowood What I'm trying to say that with typescript the below example is not possible to achieve.

This is example is taken from official docs https://www.fastify.io/docs/latest/Logging/

```js
const split = require('split2')
const stream = split(JSON.parse)

const fastify = require('fastify')({
  logger: {
    level: 'info',
    stream: stream
  }
})
```

**Comment by Ethan-Arrowood** [comment]
https://www.fastify.io/docs/latest/TypeScript/#fastify

Look at example 5

**Comment by Sidd27** [comment]
@Ethan-Arrowood That's what I have done as of now, But when I m using in JS I don't have to import pino and create and instance and pass it but only for Typescript I have to choose this option. So don't you think the experience is different for typescript and javascript user

**Comment by Ethan-Arrowood** [comment]
Yes the experience is different, JS and TS are not the same; though we try as hard as we can to make it as seem less as possible. You don't have to create your own pino instance if you don't want to, you can use the logger generic parameter on the server instance to augment as well.

**Comment by Sidd27** [comment]
@Ethan-Arrowood Thanks for your valuable time But I want to use the stream option to write logs in file.
