### ISSUE TITLE
preHandlerCallback() catches err, but reply.send() masks as "Reply already sent"

### ISSUE THREAD

**Issue by voxpelli** [fastify/fastify#2719]
## 🐛 Bug Report

I had an error thrown in my code by `fastify-secure-session` (`Error: "k" must be crypto_secretbox_KEYBYTES bytes long`), but my logs instead logged: `FastifyError: Reply was already sent.`

Reason, the error is catched here:

https://github.com/fastify/fastify/blob/d044549a20ddb4324f6f76c9d7f9032807cbff93/lib/handleRequest.js#L123-L128

Then when it tries to send, but is then instead logged as trying to send a reply after one has already been sent:

https://github.com/fastify/fastify/blob/d044549a20ddb4324f6f76c9d7f9032807cbff93/lib/reply.js#L112-L115

## To Reproduce

I have no short code example, I can try to make one if that would help, but I think my above links can help quite far?

## Expected behavior

That the actually caught error is at least also logged, as I thought it was me who had messed up and was sending stuff a second time, when it was actually an error that was maybe not caught correctly or something.

## Your Environment

- *node version*: `14.13.1`
- *fastify version*: `3.8.0` (Though I did look up that the above referred to code lines hasn't been changed between `3.8.0` and `master`)
- *os*: Mac

**Comment by voxpelli** [comment]
A bit more info:

So what happens is that in `fastify-secure-session` there's an `onSend` hook that sets a cookie: https://github.com/fastify/fastify-secure-session/blob/b5795e6663989e9c1cfd2fa5216cb9167cbf153e/index.js#L175-L179

And when doing so, I have it wrongly setup so sodium throws the `Error: "k" must be crypto_secretbox_KEYBYTES bytes long` error here: https://github.com/fastify/fastify-secure-session/blob/b5795e6663989e9c1cfd2fa5216cb9167cbf153e/index.js#L131

So, **TLDR**:

Core problem is, that if a error is thrown in an `onSend` hook, then the error isn't logged, instead only a `Reply already sent` gets logged and that one contains no useful stack trace or anything that would help one find out that the error happened in the `onSend` hook.

**Comment by mcollina** [comment]
This is weird because in https://github.com/fastify/fastify/blob/43ea177527d535cc17ed168dd479e07cc61db19d/lib/reply.js#L356-L373 we are routing the error to the error handler. We are not automatically logging the error as far as I know. Are you logging errors in your error handler?

I think a full repro would be really helpful

**Comment by voxpelli** [comment]
Sorry for not responding, I tried to find some time to reproduce, decided to squeeze it in quickly now, but can't reproduce it right now, so I'm closing it and will open a new one if I run into this again and is able to reproduce it.
