### ISSUE TITLE
fastify.listen crashes if callback not provided

### ISSUE THREAD

**Issue by iCyberon** [fastify/fastify#272]
In v0.28 if no callback function is provided to `fastify.listen` it throws error

```
const fastify = require('fastify')()

fastify.get('/', function(request, reply) {
    reply.send({homepage: true})
});

fastify.listen(3000)
```
https://github.com/fastify/fastify/commit/4d6baea011dbb6e6852e2523fac7cad71bb3360d changed the behavior (wrap always requires _cb to be provided). I was handling server error differently, so I'm not sure if it's the best solution to require callback.

---
Here's what I was doing:
```javascript
fastify.server.on('error', onError)
fastify.server.on('listening', onMessage)

// ...

fastify.listen(3000)
```

**Comment by mcollina** [comment]
Should be good in 0.28.1.
