### ISSUE TITLE
Typescript types for `setSerializerCompiler` mismatch

### ISSUE THREAD

**Issue by brianorwhatever** [fastify/fastify#2722]
## 🐛 Bug Report

Similar to #2572 the serializer does not like the type signatures it is given even when using the code sample from the readme.

## To Reproduce

```js
fastify.setSerializerCompiler(({ schema, method, url, httpStatus }) => {
  return data => JSON.stringify(data)
})
```
![image](https://user-images.githubusercontent.com/7122708/101213066-a6d05a00-362e-11eb-97fb-30c165acb8d9.png)

## Expected behavior

Typescript accepts the types it is given

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by delvedor** [comment]
Thanks for reporting! Would you like to send pr with the fix? Remember to update the test as well :)
