### ISSUE TITLE
'file' does not exist in type 'FastifyLoggerInstance | FastifyLoggerOptions<Server, IncomingMessage, ServerResponse>'

### ISSUE THREAD

**Issue by yinguangyao** [fastify/fastify#2723]
## 🐛 Bug Report

When I entered the path of the log file, ts reported an error.

## To Reproduce

```js
const fastify = Fastify({
  logger: {
    level: 'error',
    prettyPrint: true,
    file: '/root/chatroom.error.log'
  }
})
```
![image](https://user-images.githubusercontent.com/16210045/101272086-fa27e100-37c3-11eb-9f39-3e27a619e76f.png)

## Expected behavior

Typescript accepts the types it is given

## Your Environment

- *node version*: 12.14.0
- *fastify version*: 3.9.1
- *os*: Mac
- *any other relevant information*

**Comment by Ethan-Arrowood** [comment]
You need to augment the logger type for fastify. See the TypeScript documentation page under the Server api definition. One the examples should show how.
