### ISSUE TITLE
Have default request id generation generate unique id:s

### ISSUE THREAD

**Issue by voxpelli** [fastify/fastify#2736]
## 🚀 Feature Proposal

Currently request id:s default to an auto-incremented number, but that number is generated locally in each instance, meaning that if one run two or more instances of Fastify, or restarts a single Fastify instance, then the default generated id:s will be duplicated between between two or more requests:

https://github.com/fastify/fastify/blob/453028bbfbb34a240bddb146549d91261deac495/lib/reqIdGenFactory.js#L3-L9

Instead truly unique string id:s should be generated, by eg. using @mcollina's performant [hyperid](https://github.com/mcollina/hyperid) module.

## Motivation

The general expectation of a request id is that it should uniquely identify a request, across instances and across time. The current solution solves neither.

(Minor bonus motivation: Also, the common style of request id:s is that they are quite long unique text strings, whereas Fastify currently is a bit odd in that it generates an actual number rather than a string, possibly giving people a false impression, as Fastify do persist any incoming `x-request-id` header and few of those will likely be a number. If a developer has assumed that a request id is actually always a number, then that could cause some issues as well.)

## Example

If I want to track down all logs that belong to a single request and filter all of those logs using the request id, then the expectation should be that any log point with the request id of that single request is caused by that request – either within the same application logs or in services called by the current instance and where the request id has been forwarded.

Currently, with a restarted fastify instance or an horizontally scaled fastify instance, the logs of multiple different requests all share the same request id, making the request id in such cases much less useful.

## PR

I can help make a PR if there's agreement on this.

**Comment by fox1t** [comment]
Is this a proposal to make this  https://www.fastify.io/docs/latest/Server/#genreqid the new default?

**Comment by voxpelli** [comment]
Yes, make the suggestion there the new default:

> Especially in distributed systems, you may want to override the default id generation behaviour as shown below. For generating UUIDs you may want to checkout hyperid

**Comment by zekth** [comment]
Regarding distributed systems we usually use the `Trace-Id` like mentionned here: https://www.w3.org/TR/trace-context/#trace-id and those IDs are generated with another process (like nginx for example); offloading fastify.

> Currently, with a restarted fastify instance or an horizontally scaled fastify instance, the logs of multiple different requests all share the same request id, making the request id in such cases much less useful.

One thing would be to identify the instance itself to add request-id in correlation with the instance ID. I faced this issue and add an uuid to the instance.

**Comment by kibertoad** [comment]
Is hyperid faster than nanoid?

**Comment by voxpelli** [comment]
> One thing would be to identify the instance itself to add request-id in correlation with the instance ID.

I think this is pretty much what hyperid does. It generates a unique id for the instance and an auto-incremented id to those, thus getting the speed of auto-increments with the uniqueness of UUIDs. (I think it refreshes the unique ID every once in a while as well, to eg not run out of ID:s in long running instances)

**Comment by voxpelli** [comment]
On tracing id:s: I would say they are meant for tracing services in particular, like AWS XRay, Jaeger, OpenTelemetry, and can identify a sub-trace within the larger request trace, whereas request id:s are more general purpose and always identifies the original request and is mostly used for eg logging.

**Comment by zekth** [comment]
> > One thing would be to identify the instance itself to add request-id in correlation with the instance ID.
> 
> I think this is pretty much what hyperid does. It generates a unique id for the instance and an auto-incremented id to those, thus getting the speed of auto-increments with the uniqueness of UUIDs. (I think it refreshes the unique ID every once in a while as well, to eg not run out of ID:s in long running instances)

The point is having possibility to identify the instance itself and not the request in what i'm saying, to use the ID of the instance on other purposes. Which for example in a log viewer would lead to a query like:
```
request-id = "42" && instance-id = "foo-bar-123"
```

**Comment by fox1t** [comment]
The “instance” part is easy: you can add name to the logger instance. 

> > > One thing would be to identify the instance itself to add request-id in correlation with the instance ID.
> > 
> > 
> > I think this is pretty much what hyperid does. It generates a unique id for the instance and an auto-incremented id to those, thus getting the speed of auto-increments with the uniqueness of UUIDs. (I think it refreshes the unique ID every once in a while as well, to eg not run out of ID:s in long running instances)
> 
> The point is having possibility to identify the instance itself and not the request in what i'm saying, to use the ID of the instance on other purposes. Which for example in a log viewer would lead to a query like:
> 
> ```
> request-id = "42" && instance-id = "foo-bar-123"
> ```

**Comment by voxpelli** [comment]
I feel that any identifying of instances is out of scope of this issue in particular and the request id itself in general – one can never assume that the request id will be generated by this piece of code and it will only ever be able to identify the instance that generated the id and I don’t see how that’s very useful?

Maybe open a new issue dedicated to any such wish?

**Comment by delvedor** [comment]
Not sure if I'm missing something, but I think the current implementation is fine.
If you want to have unique request ids you should override the default implementation.
The reason why currently it is a incremental integer, is that if you don't need that feature, it will cost you close to nothing the fact that we are running it :)

We could improve the documentation section to highlight this. What do you think?

**Comment by voxpelli** [comment]
> Not sure if I'm missing something, but I think the current implementation is fine.
> If you want to have unique request ids you should override the default implementation.

What's the point of a request id that isn't unique?

> The reason why currently it is a incremental integer, is that if you don't need that feature, it will cost you close to nothing the fact that we are running it :)

If I don't have use for a unique request id, when would I ever have use for a non-unique request id?

I would say: Either remove the current default all together and default to have no request id:s, or implement proper request id:s. Sounds like of those two choices you would prefer removing the feature @delvedor?

**Comment by jsumners** [comment]
I'm with @delvedor. The feature should remain as it is. Request id generation and propagation is far more complicated that just slapping a UUID on new requests. Providing the feature as it is, offers those who need to customize it can and aids developers locally with an easy to follow id.

I suspect that most people who care about this feature will already be using some sort of OpenTracing/OpenTelemetry setup anyway. So the request id Fastify generates will be of very little use.

**Comment by mgcrea** [comment]
Also one other downside would be a bit harder to read logs by default, which are already quite verbose, I think it is best to keep it very straightforward by default.

**Comment by mcollina** [comment]
> If I don't have use for a unique request id, when would I ever have use for a non-unique request id?

This feature is "good enough", in the sense that non-unique request ids could be easily made unique from context when a _human_ is reading the logs. Note that we have `hostname` and `pid` to disambiguate. I've _never_ had a use for unique ids in non-tracing scenarios (and then those are governed by the span/trace mechanism).

**Comment by fox1t** [comment]
My 2 cents on this: In a microservice/distributed world it is very important to have unique reqids and to propagate them thru the services in order to have a proper inspection of the req/res cycle. I really like that fastify supports it. On the other side, I am not sure that making this the default would benefit newcomers. If someone needs to have unique reqids across multiple replica of the service he/she is already skilled enough to properly implement it.

**Comment by voxpelli** [comment]
Ok, so no hyperid request id generation in core then, but how about making the default at least be something that looks and feels like the string it is rather than is an auto-incremented integer?

Just changing from `1` to `req-1` would help clarify the nature of it + if you want to keep it less verbose, then the number could be formatted in hexadecimal or base64 representation to ensure it stays short even after many many requests have been made.

**Comment by jsumners** [comment]
> Ok, so no hyperid request id generation in core then, but how about making the default at least be something that looks and feels like the string it is rather than is an auto-incremented integer?
> 
> Just changing from `1` to `'req-1'` would help clarify the nature of it + if you want to keep it less verbose, then the number could be formatted in hexadecimal or base64 representation to ensure it stays short even after many many requests have been made.

I think that is a fair compromise.

**Comment by ognjenjevremovic** [comment]
I might be a month late, but is this already implemented?
If not and if it is up for grabs, may I have a chance to provide a MR for this issue?

> Just changing from `1` to `'req-1'` would help clarify the nature of it + if you want to keep it less verbose, then the number could be formatted in hexadecimal or base64 representation to ensure it stays short even after many many requests have been made.

I agree that using base64 representation of the request _id_ (number) as `req-<base64_number_representation>` would make it less verbose.

**Comment by mcollina** [comment]
I would actually recommend to use `.toString(36)` instead. It's less compact than `base64`, but it would significantly faster to generate. Anyway, it's up for grabs.
