### ISSUE TITLE
404 error with prefixed plugin

### ISSUE THREAD

**Issue by rackaam** [fastify/fastify#2738]
## 🐛 Bug Report

Fastify returns a 404 that doesn't seem right.

## To Reproduce

```js
"use strict";
const fastify = require("fastify")();

fastify.register(
  async (server) => {
    server.get("/:id/stuff", async () => "stuff");
    server.get("/search", async () => "search");
  },
  { prefix: "/abc" }
);

fastify.get("/:foo/bar", async () => "foobar");

fastify.listen(9999, () => {
  console.log("listening");
});
```

## Expected behavior
```
GET http://localhost:9999/abc/abc123/stuff => stuff
GET http://localhost:9999/abc/search => search
GET http://localhost:9999/xyz/bar => foobar
GET http://localhost:9999/abc/search123/stuff => stuff
```

The first 3 work fine but `http://localhost:9999/abc/search123/stuff` returns a 404.
When the `/abc/search` or `/:foo/bar` routes are removed, the `/abc/:id/stuff` route works fine.
~When the same 3 routes are declared without using a prefixed plugin, everything works fine.~

Am I doing something wrong? Or is this a know limitation of fastify router?

## Your Environment

- *node version*: 12
- *fastify version*: tested with 2 and 3
- *os*: Linux

**Comment by jsumners** [comment]
https://github.com/delvedor/find-my-way/blob/d7c712819f11046eabbc3c599e07d26d907ca5fc/README.md#L183-L185

**Comment by rackaam** [comment]
My bad,  for some reasons I thought it was related to the plugin route prefixing so I didn't checked the find-my-way issues.
I found one very similar https://github.com/delvedor/find-my-way/issues/101

I will close this issue.
