### ISSUE TITLE
Ajv@7 upgrade plan

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2742]
Ajv@6 will be discontinued at 28/2/2021, well before we retire Fastify v3. We are at the early stages of Fastify v4 right now, so there might be 6+ months of potentially unsupported validator against security vulnerabilities. However the code in Ajv@6 is really battle tested, so there might be a small chance of that happening.

I see a couple of options.

### Option 1

Quickly release a Fastify v4 with Ajv@7 to minimize the time where Fastify v3 will have an unsupported validator.

### Option 2

Ship Ajv@7 in Fastify@3 even if it has a few breaking changes. We can also decide to do this _only_ if there is a security vulnerability.

### Option 3

Use `peerDependencies` so that Fastify@3 can work with both Ajv@6 and Ajv@7.

### Option 4

Ignore Ajv@7 for Fastify@3 and release Fastify@4 when we are ready.

## Benefits

Ajv has one key feature that is interesting me a lot: a better "standalone mode: https://github.com/ajv-validator/ajv/blob/master/docs/standalone.md. We could potentially support some pre-compiled schemas so that we can speed up our startup time.

See https://github.com/ajv-validator/ajv/releases/tag/v7.0.0 for more details for all the other changes.

----

Feel free to edit this if you see more options for us.

**Comment by kibertoad** [comment]
Isn't there also an option to release fastify 4 in due time, ignoring the fact that v3 will have unsupported validator, which, as you've already said, is exquisitely well battle-tested, and likely to be way more stable than ajv7 for a while?

**Comment by jsumners** [comment]
I think this is truly solved by resolving #2446. I _intend_ to get to that in a couple weeks over holiday. Basically, my plan is to accept an object that conforms to the interface Fastify uses internally to access schemas. This would allow _any_ validator to be used. In turn, that would mean we can remove the direct dependency on `ajv` from Fastify core, and replace it with a `fastify-validator` (or whatever) as a default implementation.

**Comment by mcollina** [comment]
> Isn't there also an option to release fastify 4 in due time, ignoring the fact that v3 will have unsupported validator, which, as you've already said, is exquisitely well battle-tested, and likely to be way more stable than ajv7 for a while?

I've added it to the list. I'm not convinced that's the best course of action because there might be a security vulnerability in Ajv@6 that will go unpatched.

**Comment by Ethan-Arrowood** [comment]
I was going to say something very similar to @jsumners 

essentially - can we enable users to plug in their own validator, default to ajv6, and release that as a feature to v3? Then tell users "hey if you want, plug in ajv v7 into fastify v3 like so". then in fastify v4 we change the default to ajv 7?

**Comment by Ethan-Arrowood** [comment]
If a security vulnerability is reported for ajv@6, then we should update to ajv@7 in fastify@3 even if its breaking (since its security related)

**Comment by kibertoad** [comment]
@Ethan-Arrowood Great point, that makes strong case for Option 2.

**Comment by Ethan-Arrowood** [comment]
> We can also decide to do this only if there is a security vulnerability.

I think this is the crucial part to Option 2

**Comment by Eomm** [comment]
> I think this is truly solved by resolving #2446. I _intend_ to get to that in a couple weeks over holiday. Basically, my plan is to accept an object that conforms to the interface Fastify uses internally to access schemas. This would allow _any_ validator to be used. In turn, that would mean we can remove the direct dependency on `ajv` from Fastify core, and replace it with a `fastify-validator` (or whatever) as a default implementation.
> 
> But, given I haven't done that work yet, I'd choose option 2.

I was thinking the same: I would be able to work on for a couple of days the next week if you agree to work together on a branch targeting Fastify v4.

Regarding **Option 2** I agree on ship it in v3 only if there is a security vulnerability and drafting a PR for this event.
Then release Fastify v4 when we are ready (in my mind after the nodejs 16 release)

**Comment by jsumners** [comment]
> I was thinking the same: I would be able to work on for a couple of days the next week if you agree to work together on a branch targeting Fastify v4.

I intend to target v3. Done correctly, it's a feature addition, not a reinvention of the whole system.

**Comment by mcollina** [comment]
After chatting with @epoberezkin he said he will fix security issues in v6 unless they require massive refactoring. I think we are safe keeping fastify@v3 on ajv@v7.

Anybody would like to send an upgrade PR against `next` branch?

**Comment by kibertoad** [comment]
@mcollina Do you mean keeping fastify 3 on ajv6?

**Comment by mcollina** [comment]
> Do you mean keeping fastify 3 on ajv6?

That's the idea, yes.

**Comment by Eomm** [comment]
> Anybody would like to send an upgrade PR against next branch?

My idea is to do it after #2755 👍

**Comment by epoberezkin** [comment]
Let me know any questions about migration - it’s a relatively big change, release notes should help. There’s been very few issues reported though, all fixed. V6 is on v6 branch, and if any security release is needed, it would be on v6 npm tag. By supporting until the end of Feb 21, I meant fixing any core functionality issues / edge cases that may be discovered; happy to fix any security issues a bit longer - Q2’21 is ok.

**Comment by inigo-garcia** [comment]
@Eomm has you done any progress on it? I will try to help with the migration

**Comment by mcollina** [comment]
@inigo-garcia go ahead, @Eomm is taking some time off.

**Comment by Eomm** [comment]
Could you please wait a couple of days?

I will open a draft pr since the last feature schema controller feature has been done for this purpose, then we could work together on it 👍🏼

**Comment by inigo-garcia** [comment]
Okey, I'm happy to help once it's ready.

**Comment by epoberezkin** [comment]
Btw, if you didn't migrate to v7 yet, you could wait 1-2 weeks and migrate to v8 - beta is released already.

**Comment by mcollina** [comment]
The current eta is with Fastify v4, it's still months to come.. it would definitely be v8!
