### ISSUE TITLE
Our server keeps crashing with SIGPIPE

### ISSUE THREAD

**Issue by StevenLangbroek** [fastify/fastify#2743]
## 🐛 Bug Report

Hey folks, I'm not even sure whether this is actionable by you but I'm not quite sure where else to start. I'll try to provide an appropriate amount of context, but if something is missing please let me know and I'll expand.

We're running exclusively NestJS services in our cluster of services. They're composed through an Apollo Gateway, also NestJS, but given the amount of traffic that passes through it, we switched just this one to NestJS's fastify adapter. The migration was pretty painless, just needed to swap out some variable names and everything seemed to work. Our monitoring however sees our instances regularly (a couple of times an hour) crash with a `SIGPIPE`. The reason I'm opening a bug report here is that the only thing that really changed is that we updated dependencies:

- `"@nestjs/platform-fastify": "^7.5.5"` -> `=> Found "fastify@3.8.0"`
- `"apollo-server-fastify": "3.0.0-alpha.3"`

## Your Environment

- *node version*: 14.15.0
- *fastify version*: 3.8.0
- *os*: Docker / Linux

I've been trying to find info about how to debug a `SIGPIPE` in NodeJS but have come up blank. Any help would be greatly appreciated <3

**Comment by RafaelGSS** [comment]
Hey!

Unfortunately without reproduction code is hard to figure out what's happening. How was the upgrade? I mean, from `fastify@2` to `fastify@3`?

**Comment by StevenLangbroek** [comment]
@RafaelGSS yeah I understand, I just don't know how to generate that information. I can't find good information about how to figure out what socket or pipe it was trying to write to.

We were using NestJS's express adapter before, switching from express to fastify was painless. I've updated fastify from 2 to 3 in other projects and it was pretty smooth (just had to wait for some other dependencies to be updated).

**Comment by RafaelGSS** [comment]
We don't support officially (as far I know) the `@nestjs/platform-fastify`. I would say that is not a problem with `fastify` so far since you are using a third-party library to use `fastify` as router.

When you can reproduce this behavior, I can take a look to understand which side the problem is on.

Some notes that probably you know:

- This behavior occurs when you try to write to a socket that already has closed.
- I would say to check the endpoints/handlers and try to correlate the data, I mean, timeouts, errors, and so on. Try to find if you are sending a message after the reply is sent (streams should be checked as well).

**Comment by delvedor** [comment]
Hello! We are not affiliated with Nest, nor we support the fastify-nest connector.
I suggest you open an issue in the nest repository :)

**Comment by StevenLangbroek** [comment]
Out of curiosity, what kind of code would cause an error like this? Forgetting to listen to `end` event on a stream?

**Comment by mcollina** [comment]
A missing 'error' handler on a stream, but I have never had to debug one.

**Comment by ThisIsMissEm** [comment]
I think we've resolved the issue: we switched from having `yarn` as our docker entrypoint/cmd to just bare `node` and the sigpipes subsided.

**Comment by StevenLangbroek** [comment]
@mcollina in cae you're interested; @ThisIsMissEm and I managed to narrow it down to an interaction between Contrast Security's runtime agent and fastify. Working with their team to resolve but it might take a while, I'll update here.

For future readers; starting your server through a `yarn` command from Docker obscured the source of the error, change it from `CMD ["yarn", "start"]` to `CMD ["node", "dist/main"]` to get better insight into what's happening.

**Comment by zekth** [comment]
I personnaly suggest using 
```
CMD ["node", "--abort-on-uncaught-exception", "/dist/server.js"
```

**Comment by mcollina** [comment]
@StevenLangbroek I guess that agent is messing with some globals that pino does not like. https://github.com/mcollina/sonic-boom or https://github.com/pinojs/pino/blob/eca5800eb924788e987900a762a48f78d12d57e8/lib/tools.js#L344-L346 might be good entry points.

**Comment by StevenLangbroek** [comment]
@mcollina yeah seems both their agent and the instana one use `shimmer` as a transitive dependency, which is causing all sorts of havoc.

**Comment by mcollina** [comment]
This does not surprise me at all.

**Comment by jsumners** [comment]
Leave 👏 prototypes 👏 you 👏 do 👏 not 👏 own 👏 alone 👏

**Comment by StevenLangbroek** [comment]
Prototypes are people too.
