### ISSUE TITLE
migrate pre-commit to husky

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#2752]
In this comment https://github.com/fastify/fastify-jwt/pull/128#discussion_r545066309, jsumners suggest move ```pre-commit``` to ```husky```

## 🚀 Feature Proposal

Migrate ```pre-commit``` to ~~```husky```~~ [```fastify/pre-commit```](https://github.com/fastify/pre-commit)

~~Common configuration adding to ```package.json```~~
```
"husky": {
  "hooks": {
    "pre-commit": "npm test",
  }
}
 ```

## Motivation

```pre-commit``` is not updated for a long time and it is not well-maintained. ~~In comparison, ```husky``` is well maintained and do the same functionality as ```pre-commit```~~

Updated: ```husky``` is too intrusive and we change the target to ```fastify/pre-commit``` when it release.
 
## Checklist
Check the status for core packages.
### Using ```pre-commit``` currently
- [ ] [```fastify```](https://github.com/fastify/fastify)
- [ ] [```fastify-accepts```](https://github.com/fastify/fastify-accepts)
- [ ] [```fastify-accepts-serializer```](https://github.com/fastify/fastify-accepts-serializer)
- [ ] [```fastify-auth```](https://github.com/fastify/fastify-auth)
- [ ] [```fastify-bankai```](https://github.com/fastify/fastify-bankai)
- [ ] [```fastify-bearer-auth```](https://github.com/fastify/fastify-bearer-auth)
- [ ] [```fastify-caching```](https://github.com/fastify/fastify-caching)
- [ ] [```fastify-compress```](https://github.com/fastify/fastify-compress)
- [ ] [```fastify-cookie```](https://github.com/fastify/fastify-cookie)
- [ ] [```fastify-elasticsearch```](https://github.com/fastify/fastify-elasticsearch)
- [ ] [```fastify-env```](https://github.com/fastify/fastify-env)
- [ ] [```fastify-formbody```](https://github.com/fastify/fastify-formbody)
- [ ] [```fastify-helmet```](https://github.com/fastify/fastify-helmet)
- [ ] [```fastify-jwt```](https://github.com/fastify/fastify-jwt)
- [ ] [```fastify-mongodb```](https://github.com/fastify/fastify-mongodb)
- [ ] [```fastify-multipart```](https://github.com/fastify/fastify-multipart)
- [ ] [```fastify-oauth2```](https://github.com/fastify/fastify-oauth2)
- [ ] [```fastify-reply-from```](https://github.com/fastify/fastify-reply-from)
- [ ] [```fastify-routes```](https://github.com/fastify/fastify-routes)
- [ ] [```fastify-static```](https://github.com/fastify/fastify-static)
- [ ] [```fastify-swagger```](https://github.com/fastify/fastify-swagger)
- [ ] [```fastify-websocket```](https://github.com/fastify/fastify-websocket)
- [ ] [```fastify-url-data```](https://github.com/fastify/fastify-url-data)
- [ ] [```point-of-view```](https://github.com/fastify/point-of-view)
- [ ] [```under-pressure```](https://github.com/fastify/under-pressure)
- [ ] [```light-my-request```](https://github.com/fastify/light-my-request)
- [ ] [```middie```](https://github.com/fastify/middie)

### Do not have either```pre-commit``` and ```fastify/pre-commit```
- [ ] [```fastify-basic-auth```](https://github.com/fastify/fastify-basic-auth)
- [X] [```fastify-circuit-breaker```](https://github.com/fastify/fastify-circuit-breaker) https://github.com/fastify/fastify-circuit-breaker/pull/28
- [ ] [```fastify-cors```](https://github.com/fastify/fastify-cors)
- [ ] [```fastify-csrf```](https://github.com/fastify/fastify-csrf)
- [ ] [```fastify-etag```](https://github.com/fastify/fastify-etag)
- [ ] [```fastify-flash```](https://github.com/fastify/fastify-flash)
- [x] [PR] [```fastify-funky```](https://github.com/fastify/fastify-funky) https://github.com/fastify/fastify-funky/pull/5
- [ ] [```fastify-http-proxy```](https://github.com/fastify/fastify-http-proxy)
- [ ] [```fastify-leveldb```](https://github.com/fastify/fastify-leveldb)
- [ ] [```fastify-postgres```](https://github.com/fastify/fastify-postgres)
- [ ] [```fastify-rate-limit```](https://github.com/fastify/fastify-rate-limit)
- [ ] [```fastify-response-validation```](https://github.com/fastify/fastify-response-validation)
- [X] [```fastify-request-context```](https://github.com/fastify/fastify-request-context) https://github.com/fastify/fastify-request-context/pull/27
- [ ] [```fastify-nextjs```](https://github.com/fastify/fastify-nextjs)
- [ ] [```fastify-redis```](https://github.com/fastify/fastify-redis)
- [ ] [```fastify-sensible```](https://github.com/fastify/fastify-sensible)
- [ ] [```releasify```](https://github.com/fastify/releasify)
- [ ] [```fastify-diagnostics-channel```](https://github.com/fastify/fastify-diagnostics-channel)
- [ ] [```fastify-awilix```](https://github.com/fastify/fastify-awilix)

**Comment by zekth** [comment]
Are all `pre-commit` using command `npm test` ? If so we can write a script to create the branches and PR like we did for the `stale bot`.

**Comment by climba03003** [comment]
Yes, ```pre-commit``` is simply just add a hook to execute the ```npm test``` command.
Note that some of the package is missing ```pre-commit``` in ```package.json```, so you need to make sure the automation can handle it.

Steps for automate script:
1. Check if ```pre-commit``` exist in ```package.json```, remove it when it exist.
3. Add ```husky``` as ```devDependencies```

**Comment by jsumners** [comment]
Please see https://github.com/fastify/fastify/pull/1265. 

My comment on the other repository was because that repository wasn't already using either of these packages. Therefore, it could easily be switched to `husky` over `pre-commit`. The problem with migrating repositories that currently use `pre-commit` is updating the installed hooks on contributor systems.

For a long time, Husky provided no solution to this problem. However, recently they have decided on a "solution" in the upcoming v5 release -- https://github.com/typicode/husky/pull/535#issuecomment-725492155. I haven't had time to actually test how this works. I fear that it means having to add a `.husky` directory to every project and encumber every git repository with that directory. The nice thing about the way v4 worked was it didn't require this extra scaffolding just for the source control tool.

**Comment by kibertoad** [comment]
@jsumners What's the preference for the projects that currently don't have any pre-commit hooks installed? Do we want to keep them as-is or add `husky`?

**Comment by jsumners** [comment]
My opinion is `husky@4` for projects that do not currently have a hook manager.

**Comment by kibertoad** [comment]
@jsumners Gotcha. I'll prepare some PRs in the evening then.
Considering that husky 5 will likely require an update again, why use 4? Considering how simple our use-case is, it's unlikely that we'll break anything.

**Comment by jsumners** [comment]
Simply because I haven't tested v5 and I don't know how it will work. I know that v4 works exactly as we are accustomed to with `pre-commit`. 

But be my guest to investigate v5 and report your findings. Also, v5 isn't yet marked as current on npm.

**Comment by climba03003** [comment]
I have updated the checklist to show which packages currently using ```pre-commit``` and none of them. You can better visualize which need to add ```husky``` and which one need to wait for ```husky@5``` (maybe).

**Comment by RafaelGSS** [comment]
Good work! I've add a new package to the tracking list.

**Comment by kibertoad** [comment]
@jsumners Well, it works, but feels a bit intrusive :-/ (https://github.com/fastify/fastify-funky/pull/5/files). Then again, I guess this is our future, highly unlikely they will redesign the whole thing within v5.

**Comment by jsumners** [comment]
🤢

That's what I feared. Unfortunately, no one else is maintaining anything better.

**Comment by Fdawgs** [comment]
Just an FYI, Dependabot will need to be configured in `.github/dependabot.yml` to ignore Husky updates if you plan on using v4 and not proceeding with v5:

```yml
    - package-ecosystem: npm
      directory: /
      ignore:
          - dependency-name: "husky"
            versions: ["5.x"]
      schedule:
          interval: daily
      open-pull-requests-limit: 10
```

Dependabot completely ignored me pinning the major version in `package.json` in my own repos to v4, and bumped them to v5. 😠

**Comment by mcollina** [comment]
Are we still planning to do this, or maybe we move to https://github.com/fastify/pre-commit?

**Comment by climba03003** [comment]
> 
> 
> Are we still planning to do this, or maybe we move to https://github.com/fastify/pre-commit?

I think we are waiting for fixing those issue before releasing. I can change the title for `fastify/pre-commit`

**Comment by mcollina** [comment]
let's do it, +1.

**Comment by jsumners** [comment]
No. I need to get back into fixing up our fork for release.

**Comment by jsumners** [comment]
Our fork of `pre-commit` is now published. We can switch to it. https://www.npmjs.com/package/@fastify/pre-commit
