### ISSUE TITLE
[FST_LIGHTMYREQUEST_DEP01] When I run my test units

### ISSUE THREAD

**Issue by XERXES-MOUSAVI** [fastify/fastify#2761]
## 🐛 Bug Report

When I run my test units , i get [FST_LIGHTMYREQUEST_DEP01] deprecation warning.

I use jest for testing and request injetcion:

#sample.spec.js
```js

describe('SampleTest', () => {
  /** @type {import('awilix').AwilixContainer} */
  let container;

  afterEach(async () => {
    await container.dispose();
  });

  it('sample-test', async () => {
    // resolve awilix containers that I need
    const FastifyOpenApi = container.resolve('FastifyOpenApi');
    /** @type {import('fastify').FastifyInstance} app */
    const app = FastifyOpenApi.getFastify();
    container.resolve('AddSchema');
    container.resolve('AddTagApp');
    const config = container.resolve('config');

    const injectReq = await app.inject({
      url: `${config.API_PREFIX}/tag`,
      method: 'POST',
      payload: {
        title: 'title',
        description: '',
      },
    });
    expect(injectReq.statusCode).toEqual(200);
  });
});
```

My tests passed successfully but I got this deprecation warning:

```
(node:64) [FST_LIGHTMYREQUEST_DEP01] FastifyDeprecationLightMyRequest: You are accessing "request.connection", use "request.socket" instead.
```
I want to know why it happened? and what should I do?

## My Environment
- *node version*: 12.18.3
- *fastify version*: >=3.9
- *os*: ubuntu 20.04
-  jest: 26

**Comment by kibertoad** [comment]
Doesn't warning say anything there is to know? `request.connection` is deprecated and will eventually stop working, use `request.socket` instead.

**Comment by kibertoad** [comment]
What is `FastifyOpenApi`?

**Comment by kibertoad** [comment]
I've checked sources for `light-my-request`, and by itself it is not calling `request.connection` anywhere, so my assumption is that there is some code in your codebase that does it. Could you check?
Alternatively you can set a breakpoint inside `light-my-request` `lib/request.js` 
```
  Object.defineProperty(this, 'connection', {
    get () {
      warning.emit('FST_LIGHTMYREQUEST_DEP01')
      return this.socket
    },
    configurable: true
  })
```
and see where it is being called from, maybe it's some plugin that needs updating.

**Comment by kibertoad** [comment]
@XERXES-MOUSAVI Btw, unrelated, but we've just published plugin for awilix, you might want to check it out: https://www.npmjs.com/package/fastify-awilix

**Comment by jonasfj** [comment]
This might be worth reopening, I have the stack trace:
```
 Uncaught Error: FST_LIGHTMYREQUEST_DEP01
      at Request.get (node_modules/light-my-request/lib/request.js:89:13)
      at forwarded (node_modules/forwarded/index.js:31:24)
      at alladdrs (node_modules/proxy-addr/index.js:57:15)
      at proxyaddr (node_modules/proxy-addr/index.js:231:15)
      at _Request.get (node_modules/fastify/lib/request.js:73:16)
      at _Request.get (node_modules/fastify/lib/request.js:83:18)
      at Object.asReqValue [as req] (node_modules/fastify/lib/logger.js:54:21)
      at Pino.asJson (node_modules/pino/lib/tools.js:118:50)
      at Pino.write (node_modules/pino/lib/proto.js:166:28)
      at Pino.LOG [as info] (node_modules/pino/lib/tools.js:55:21)
      at Object.routeHandler [as handler] (node_modules/fastify/lib/route.js:370:19)
      at Router.lookup (node_modules/find-my-way/index.js:367:14)
```

And if I disable `trustProxy: true,` option then it works fine.

**Comment by mcollina** [comment]
Given that `forwarded` has not been updated in the last 3 years, I do not expect an update is coming soon.

We should either 

1. internalize `proxy-addr` and `forwarded` inside fastify (or this org)
2. revert the deprecation notice in light my request

Any good idea?

**Comment by jsumners** [comment]
Why would `forwarded` need to be updated?

**Comment by mcollina** [comment]
forwarded is using the deprecated (by node core) `req.connection` property. It needs to be updated, but that module has not been released in last 3 years.

**Comment by jsumners** [comment]
Well, I was going to suggest we attempt to get it solved via a PR, but I see one was created back in October and it has no response. Unfortunately, I think that answers the question: bring the modules into the org as forks.
