### ISSUE TITLE
async await return reply.send() but still executed code line below

### ISSUE THREAD

**Issue by aalfiann** [fastify/fastify#2765]
## 🐛 Bug Report

I'm not sure this is a bug or not because I still new with Fastify, My problem is I have already return reply.send() but fastify still executed the code line below. Is there a way to stop reply.send() immediately if I have already sent it?

## To Reproduce

this is the router.
```js
'use strict'

const mongooseHandler = require('../lib/mongoose_handler')

async function dbRoute (fastify, options) {
  fastify.post('/api/test/connection-database', async (request, reply) => {
    await mongooseHandler.connect().catch(err => {
      // I have already turn off the mongodb server so this line will be 100% executed.
      console.log('EXECUTED')
      return reply.code(500).send(err.message)
    })
    console.log('THIS SHOULD NOT BUT STILL EXECUTED, WHY?')
    reply.send('Database connected!')
    await reply
  })
}

module.exports = dbRoute
```

## Expected behavior

I was thinking if I have already return reply.send(), this will not executed the code line below.

I know that I could solve this by this way, but I just don't like this because for complex cases will be many of using `if`.
```js
    const connect = await mongooseHandler.connect().catch(err => {
      // I have already turn off the mongodb server so this line will be 100% executed.
      console.log('EXECUTED')
      return reply.code(500).send(err.message)
    })
    if (connect) {
      console.log('THIS WILL NOT EXECUTED')
      reply.send('Database connected!')
    }
    await reply
```

So how the right way to stop immediatelly after `return reply.send()` ?

## Your Environment

- *node version*: 10
- *fastify version*: >=3.9.2
- *os*: Linux Ubuntu Bionic 18.04
- *any other relevant information*

**Comment by L2jLiga** [comment]
This happens because you catch (swallow) error inside your `catch` block and this doesn't stop execution.

**Comment by aalfiann** [comment]
yes I know it.

I mean is there a feature to skip execution if fastify reply.send() has already sent?

**Comment by jsumners** [comment]
Don't mix and match callback/promise handler style with `async...await`:

```js
'use strict'

const mongooseHandler = require('../lib/mongoose_handler')

async function dbRoute (fastify, options) {
  fastify.post('/api/test/connection-database', async (request, reply) => {
    try {
      await mongooseHandler.connect()
    } catch(err) {
      console.log('EXECUTED')
      return reply.code(500).send(err.message)
    }

    return reply.send('Database connected!')
  })
}

module.exports = dbRoute
```

**Comment by aalfiann** [comment]
OMG, why I forgot about try catch?

Thank you @jsumners
