### ISSUE TITLE
preSerialization won't be exeecuted in case of a custom serializer.

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2770]
If you define a custom [reply serializer](https://www.fastify.io/docs/latest/Reply/#serializerfunc), the `preSerialization` won't be executed.
I think this is a leftover of previous implementations and it should considered a bug.

https://github.com/fastify/fastify/blob/834a4e58de86d7996b50a4663fbf2b0fac4686ee/lib/reply.js#L146-L147

To reproduce:

```js
'use strict'

const fastify = require('fastify')()

fastify.addHook('preSerialization', async (req, reply, payload) => {
  console.log('preSerialization', payload)
  return payload
})

fastify.get('/', (req, reply) => {
  reply
    .type('application/json')
    .serializer(JSON.stringify)
    .send({ hello: 'world' })
})

fastify.inject('/', (e, response) => console.log(response.json()))
```

**Comment by MSE99** [comment]
I have a question, a custom serializer is supposed to only work when an application content type was specified via `reply.type` right ?
