### ISSUE TITLE
fastify with Docker

### ISSUE THREAD

**Issue by juanr2001** [fastify/fastify#2775]
## 🐛 Bug Report

Dockerizing a project to listen on port 3000, `::` must be specified.
I am not 100% sure why, but in express it does not need `::`

## To Reproduce

Dockerfile
```js
FROM node:latest
WORKDIR /app
ADD . .
RUN npm install
CMD node index.js
```

The index.js
```js
const fastify = require('fastify');
const app = fastify({
  'logger': true
});

const port = 3000;

app.get('/', async (req, reply) => {
  return {
    'error': false,
    'username': 'Juan'
  };
});

// Note: '::' is essential for docker to accept connection via IPv6
app.listen(port, '::', function (err, address) {
  if (err) {
    app.log.error(err)
    process.exit(1)
  }
  app.log.info(`Server listening on ${address}`)
})
```

// On your terminal execute following commands
```js

// COMMAND 1: Create image
docker build -t <image name>:latest .

// COMMAND 2: Creates container
docker run --name <container name> -d -p 3000:3000 <image name>:latest

```

NOTE:
**There is not an error thrown, because everything happens inside the docker container. Upon checking the container 
All files to run the project are there. Technically speaking, fastify should listen without** `::`

To access files inside the container execute the following command
```
docker exec -it <container_id | name> bash 
```

## Expected behavior

Does it `::` must specified?

## Your Environment

Docker version 20.10.0, build 7287ab3
Node v12.10.0

**Comment by StarpTech** [comment]
Hi, this is already documented here https://github.com/fastify/fastify/blob/master/docs/Recommendations.md#kubernetes.

Fastify listen by default on `127.0.0.1` but express on `0.0.0.0`.

**Comment by juanr2001** [comment]
@StarpTech 

FML, thanks for the link

 Thank you thank you!

**Comment by jsumners** [comment]
It's more fully documented in https://github.com/fastify/fastify/blob/5e0e674823642d851fefb73d78fc590325c880b2/docs/Server.md#listen

This is a security feature.
