### ISSUE TITLE
Question: keeping context between beforeHandlers

### ISSUE THREAD

**Issue by rstacruz** [fastify/fastify#278]
Is it possible for one `beforeHandler` to hand off data to a handler?

Example: if you have an auth handler, it'd be nice to pass the current user to the primary handler. eg:

```js
fastify.route({
  method: 'GET',
  url: '/dashboard',
  beforeHandler: [ setCurrentUser ],
  handler: (req, reply) => {
    /* consume req.currentUser */
  })
})

function setCurrentUser (req, reply, next) {
  req.currentUser = { id: 2, email: 'john@example.com' }
  next()
}
```

Polluting `req` seems like a weird thing to do.

**Comment by rstacruz** [comment]
Also, the docs don't seem to mention `beforeHandlers` supporting async/await. does it?

**Comment by mcollina** [comment]
@rstacruz have you checked out https://github.com/fastify/fastify-auth? It should do what you want.

As for `beforeHandlers`, would you like to send a PR to add support for async/await there?

**Comment by jsumners** [comment]
I brought this exact issue up in the original PR -- https://github.com/fastify/fastify/pull/115#issuecomment-312728729 . @delvedor's suggestion was to add them to the request as you are doing. And really that's all Hapi does; it just adds them to a consistent key.

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
