### ISSUE TITLE
Setting status to 400 or 404 ignore return when async; however, setting 201 does not

### ISSUE THREAD

**Issue by patarapolw** [fastify/fastify#2792]
## 🐛 Bug Report

Setting status to 400 or 404 ignore return when async; however, setting 201 does not.

A temporary solution is to `throw { statusCode: 400, ...msg }` instead of return.

## To Reproduce

```js
f.get('/', async (req, reply) => {
  const r = await fetch(req.query.url)
  reply.status(r.status)
  
  try {
    return r.json()
  } catch (_) {
    return r.text()
  }
})
```

## Expected behavior

Throwing is not the only way to return statusCode > 300 or < 200.

## Your Environment

- *node version*: Electron 11.1.1
- *fastify version*: 3.9.2
- *os*: Xubuntu 20.04

**Comment by mcollina** [comment]
This looks a lot like a bug! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by nigelhanlon** [comment]
Do you have a custom error handler defined that may not be included in the example? The code above is helpful but so far I cannot reproduce this error. A working example would help narrow down the issue if you have the time to provide one?

**Comment by mcollina** [comment]
@patarapolw a full runnable example that demonstrate the problem would be nice.

**Comment by patarapolw** [comment]
Not reproducible. Maybe I will close for now.

```js
const app = require('fastify')({
  logger: true
})

app.get('/', async (_, reply) => {
  reply.status(400)
  return {
    result: "not ok"
  }
})

app.listen(5000)
```

This works.
