### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2799]
As titled.
It should not be a problem here, but the documentation build should be updated.

Related: https://github.com/github/renaming

/cc @lmammino

**Comment by mcollina** [comment]
Go for it!

**Comment by jsumners** [comment]
This is just a solution in search of a problem. And implementing it is going to cause problems for everyone who has the code forked.

**Comment by delvedor** [comment]
@jsumners I don't agree, if you are maintaining a fork for a pr changing the base branch is the same as changing it when targeting the wrong branch or when we switch from `next` to `master`.
Once we do this, we'll ping the authors of every open pr (again, like we did when we switched from `next` to `master`) to let them know that they need to rebase on a new branch (with zero breaking changes in this case).

**Comment by mcollina** [comment]
The tooling provided by github is going to do all the rebasing automatically, it would also allow the old references to continue working. We can also wait for Node.js core to switch for example and validate the approach.

**Comment by zekth** [comment]
Those references need to be changed:
https://github.com/fastify/fastify/blob/master/.github/workflows/website.yml#L6
https://github.com/fastify/fastify/blob/master/.github/workflows/package-manager-ci.yml#L6

**Comment by zekth** [comment]
> Once we do this, we'll ping the authors of every open pr (again, like we did when we switched from `next` to `master`) to let them know that they need to rebase on a new branch (with zero breaking changes in this case).

> Renaming a branch will:
>Re-target any open pull requests

Not even sure it is necessary

**Comment by delvedor** [comment]
Latest GitHub news about this:

https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

**Comment by makuzaverite** [comment]
May I go for this one

**Comment by Eomm** [comment]
Yes, of course

I would suggest this roadmap:

- [ ] update docs to `HEAD` (example https://github.com/pkgjs/support/pull/41/files )
- [ ] one core maintainer should rename to the `main` branch*
- [ ] check the [fastify/website](https://github.com/fastify/website/) still works
- [ ] update the workflows

This worked well

*to update the local references:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by mcollina** [comment]
The website integration would need to be fixed.

**Comment by mcollina** [comment]
This was done

**Comment by 10xLaCroixDrinker** [comment]
Any plans to do this for any of the 93 remaining fastify repos that use a master branch?

**Comment by mcollina** [comment]
@10xLaCroixDrinker possibly, but it really depends on admins time. There are no tools to massively change github settings inside and org.

**Comment by 10xLaCroixDrinker** [comment]
@mcollina would PRs to update references to master within those repos actions, scripts, docs etc, be helpful to work toward that?

**Comment by mcollina** [comment]
Realistically yes, but it's still a lot of effort to rename the repos and test it all works correctly.

I'd recommend opening a fresh issue.
