### ISSUE TITLE
Content negotiation support

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#2811]
## 🚀 Feature Proposal

Support content negotiation at route definition.
It should be possible to define several handlers for one route. Routing among the handlers should be based on the *Accept* and the *Content-Type* Header. This feature is similar to the existing feature for Versioning. 

## Motivation

This function is very helpful if, for example, you provide an admin view and a user view for the same resource. Currently it is necessary to manually check in the *Accept* header which view is requested. Based on the header, the request is fully completed or blocked with a 403 code if, for example, a normal user requests the admin view. If content negotiation is supported, this authentication step could be relocated to a hook.

## Example

``` javascript
server.route({
  url: '/users/:id',
  method: 'GET',
  handler: async (request: FastifyRequest, reply: FastifyReply) => {
    const normalUserView = {
      id: 1,
      name: 'name'
    }
    return reply.code(200).send(normalUserView);
  },
  accept: 'application/vnd.user+json'
})

server.route({
  url: '/users/:id',
  method: 'GET',
  handler: async (request: FastifyRequest, reply: FastifyReply) => {
    const adminUserView = {
      id: 1,
      name: 'name',
      password: 'password'
    }
    return reply.code(200).send(adminUserView);
  },
  accept: 'application/vnd.user.admin-view+json'
})
```

**Comment by mcollina** [comment]
This would become possible after https://github.com/delvedor/find-my-way/pull/170 lands.

**Comment by airhorns** [comment]
@matthyk happy to guide you through writing a new constraint for `find-my-way`, it'd be great to share that with the Fastify community if you do!

**Comment by matthyk** [comment]
@airhorns sorry for the late reply. I will work on it. I need it for my work anyway. Will send a PR, when I'm done.

**Comment by matthyk** [comment]
I created a WIP PR to address this issue. [delvedor/find-my-way#188](https://github.com/delvedor/find-my-way/pull/188)

**Comment by MetCoder95** [comment]
Taking a look into the issue and PR made, shall this be closed or stills active?

**Comment by mcollina** [comment]
I think closed
