### ISSUE TITLE
Validation tries to set headers but its not possible

### ISSUE THREAD

**Issue by ettancos** [fastify/fastify#2813]
## 🐛 Bug Report
Hi people, while upgrading to v3 I've noticed a strange behavior.

#2426 has changed headers to be a getter, but `validateParam` (https://github.com/fastify/fastify/blob/master/lib/validation.js#L74) does try to assign it if the validation result contains the `value`. This does not come up with ajv because it mutates the original headers if `coerceTypes` is set. Joi returns the modified value that broke my upgrade to v3. I do not know how do other libraries do that. This did not happen on 2.14, what we are currently using.

I see that since #2355 joi is not supported officially, but this still smells like a bug. It is not clear how we should proceed. We can of course consider moving to ajv, but that is a lot more involved than just updating fastify.

## To Reproduce

```js
const Joi = require('joi')
const schemaValidator = ({ schema }) => data => schema.validate(data)

const fastify = require('fastify')({ logger: { leve: 'debug' }})
    .setValidatorCompiler(schemaValidator)

const options = {
    schema: {
        headers: Joi.object({
          'user-agent': Joi.string().required(),
          host: Joi.string().required()
        })
    }
}

fastify.post('/', options, (request, reply) => {
    reply.status(200)
})

fastify.inject({ method: 'POST', url: '/' })
```
This results in the following stack trace:
```
TypeError: Cannot set property headers of #<Request> which has only a getter
    at validateParam (/home/ttancos/node_modules/fastify/lib/validation.js:74:44)
    at validate (/home/ttancos/node_modules/fastify/lib/validation.js:92:19)
    at preValidationCallback (/home/ttancos/node_modules/fastify/lib/handleRequest.js:87:18)
    at handler (/home/ttancos/node_modules/fastify/lib/handleRequest.js:70:7)
    at handleRequest (/home/ttancos/node_modules/fastify/lib/handleRequest.js:30:9)
    at runPreParsing (/home/ttancos/node_modules/fastify/lib/route.js:416:5)
    at Object.routeHandler [as handler] (/home/ttancos/node_modules/fastify/lib/route.js:374:7)
    at Router.lookup (/home/ttancos/node_modules/find-my-way/index.js:367:14)
    at /home/ttancos/node_modules/fastify/fastify.js:401:11
    at manageErr (/home/ttancos/node_modules/fastify/fastify.js:438:11)
```
## Expected behavior
Headers contain the validation result.

## Your Environment

- *node version*: 12.19.1
- *fastify version*: 3.10.1
- *os*: ArchLinux

**Comment by jsumners** [comment]
I think you would be better off waiting for us to land https://github.com/fastify/fastify/pull/2755. I am _almost_ done with my testing. So hopefully it isn't too far off.

But, other than that, can you provide a `package.json` to accompany your reproduction? It's not clear which version of Joi you are using.

**Comment by ettancos** [comment]
> I think you would be better off waiting for us to land #2755. I am _almost_ done with my testing. So hopefully it isn't too far off.
> 
> But, other than that, can you provide a `package.json` to accompany your reproduction? It's not clear which version of Joi you are using.

Right, sorry I forgot the joi version, I was just using the latest from https://github.com/sideway/joi but its the same with older versions too (was testing first on `hapi/joi@14` then I upgraded it to make sure)
```json
{
  "name": "fastify-test",
  "dependencies": {
    "fastify": "^3.10.1",
    "joi": "^17.3.0"
  }
}```

**Comment by Eomm** [comment]
I think this needs a bugfix because the use case is to set to the fastify's `request` headers object with a new value object that would not be possible with that PR

I have a draft for it 👍
