### ISSUE TITLE
Facility for getting the rich Fastify request/reply from a raw one

### ISSUE THREAD

**Issue by airhorns** [fastify/fastify#2815]
## 🚀 Feature Proposal

Add a way to access the Fastify `Request` or `Reply` object with all their handy doodads when all you have in scope is an `http.IncomingMessage` or `http.ServerResponse`.

## Motivation

Many modules within the node.js ecosystem at large expect to deal with `http.IncomingMessage` requests so they interoperate as many other modules as possible. Things like `helmet.js` or `next.js` or `ws` are happy to take in these raw objects I think mostly cause thats how `express` works, and so that's become the lingua franca that all the web frameworks seem to speak.

This works great for fastify because `request.raw` and `reply.raw` are right there to pass into these things. That's how `fastify-helmet` and `fastify-nextjs` work -- they just invoke the bits of the wrapped modules with the raw doodads and we get working integrations.

The issue is that within both `helment.js` and `next.js`, there's callback code that users can provide to do useful stuff during request processing. In `helmet.js`, you might want to mess around with request cookies or the request session to do CSRF protection. In `next.js`, you might want a `getServerSideProps` handler that uses some data from the request to do access control or filter fetched data down to the data that should only be visible to that user. Inside these callbacks however, code is now "within" the context of these plugins, and so all these modules have available are the raw request and reply passed into them. For users of fastify that are using `fastify-helmet` or `fastify-nextjs`, they've lost access to `request.session` or `request.cookies` or any of their custom decorators that Fastify made convenient to access.

So, it'd be great to provide a way to get back to a nice rich `Request` object or `Reply` object when all you have is an `http.IncomingMessage` or `http.ServerResponse`. Plugin implementors could choose to wrap incoming callbacks with a bit of code to automatically call user-land code with the high level objects, or not, and just let the users traverse back to them if need be.

See https://github.com/fastify/fastify-helmet/issues/89 for an example where this feature would have been handy. Also note that issue shouldn't really be closed, it's just hard to fix without a facility like this.

## Example

Inside a next.js app mounted using `fastify-nextjs`:

```typescript
export const getServerSideProps: GetServerSideProps = (context) => {
  // context already has .req, see https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering
 const request: FastifyRequest = TheNewBitOfCode(context.req)
 // now I can access my decorators
 return {
   props: {
       isUserLoggedIn: request.isUserLoggedIn()
     }
  }
}
```

## Implementation notes

The easiest way to do this would be to just set a property on the raw objects pointing back to the request or reply. I *think* that would work fine with the way request encapsulation works, but it's kind of hacky and potentially slow. Another option would be to maintain a `WeakMap` between raw objects and rich objects, and then have globally-accessible functions to find the rich objects when you need them.

**Comment by jsumners** [comment]
We are unlikely to mutate the core objects. That was a mistake made by other frameworks that this one has consciously avoided.

**Comment by airhorns** [comment]
> We are unlikely to mutate the core objects. That was a mistake made by other frameworks that this one has consciously avoided.

Checks out. Otherwise though, do you think this is a good idea?

**Comment by jsumners** [comment]
I'd rather hear from @mcollina.

**Comment by mcollina** [comment]
not adding properties to req and res is one of the key reason of why fastify is _fast_. We could potentially create our own class with those properties in and pass it to https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener. That could create a few problems with our
`createServer`
 API.

**Comment by airhorns** [comment]
That makes sense! I feel like that'd likely be the fastest manner of doing this, but somewhat invasive as well. Is the WeakMap manner of implementing going to be too slow do you think?

**Comment by mcollina** [comment]
You'd have to try the various approach and benchmark them. We can also add a link back for some specific plugins, e.g. fastify-next.

**Comment by zekth** [comment]
I think i can create more problems than it could fix. Unfortunately

**Comment by airhorns** [comment]
> I think i can create more problems than it could fix. Unfortunately

Can you explain more what you mean? This being possible or the poor implementation?

**Comment by zekth** [comment]
> > I think i can create more problems than it could fix. Unfortunately
> 
> Can you explain more what you mean? This being possible or the poor implementation I suggested? I don't actually think we should mutate the raw objects, mostly just adding that for clarity to make sure we're all on the same page.

I was mostly thinking about confusion this can lead to. Because in a sense you'd be able to access rich fastify objects with the node `raw` object. One thing would be to create a flag for this feature to enable or not.

**Comment by airhorns** [comment]
> I was mostly thinking about confusion this can lead to. Because in a sense you'd be able to access rich fastify objects with the node raw object. One thing would be to create a flag for this feature to enable or not.

Can you describe a situation in which a user could make a mistake with this new API that they couldn't before?  I feel like this feature doesn't change any semantics, and `request.raw` / `reply.raw` are already present and available and endorsed. We're just switching from a one directional link to a two way one which should slot in fine to users mental models, the cardinality or relationship between the objects doesn't change at all.

**Comment by zekth** [comment]
I don't have a true illustrated example right now. Just mixing those objects per default can be dangerous and ca lead to potential issues when people are not used to see the difference between them. 
An example is the manipulation of the FastifyReply and the node.raw.reply on the same flow.
Technically wise i'm totally ok with this approach if it does not impact the performances if it fixes the problem you emitted with `helmet` and `next`. I'm just concerned about the developper experience.

**Comment by xxRockOnxx** [comment]
Coming from koa, koa doesnt mutate the raw `req`/`res` object like how express does and instead return another object that can be created via public api called `createContext`.

im not sure about fastify's internals but is this idea have been considered?

**Comment by jsumners** [comment]
@xxRockOnxx I believe you are asking about https://github.com/fastify/fastify/issues/169

**Comment by xxRockOnxx** [comment]
@jsumners i read the whole thread but i think my suggestion just happened to be coincide with it.
the reason i was asking for that kind of api is simply bc just to get an access to whatever decorators the fastify already has.

in certain cases where you use fastify but on some code you just get a raw node-core `req`, stuff like getting cookies, session, body, or whatever an installed decorator already can do, will then require manual work.

again im new and currently digging in on Fastify so some examples mentioned might already possible but you get the point.

**Comment by cusxio** [comment]
I was wondering if there is an interim solution to this problem? Can't really start a production app without access to `req.session`.

i.e. When using `fastify-session` and  `fastify-nextjs`, the session cookie is not sent by `fastify-nextjs`, because it uses [`req.raw`](https://github.com/fastify/fastify-nextjs/blob/72115af354acb57ba1b446d2239e0700abacf8e0/index.js#L77) instead.

**Comment by mcollina** [comment]
Check out https://github.com/fastify/fastify-request-context
