### ISSUE TITLE
JSON-string in the query support

### ISSUE THREAD

**Issue by sheldhur** [fastify/fastify#2816]
## 🚀 Feature Proposal
OpenAPI schema has keyword `content` in parameters, that say that this parameter will contain json.

## Motivation

Sending a JSON-string in the query:
`filter={"someField":{"gte":"10"}}`

## Example

```js
{
  headers: { ... },
  params: { ... },
  querystring: {
    limit: { ... },
    offset: { ... },
    order: { ... },
    filter: {
      content: {
        'application/json': {
          type: 'object',
          properties: {
            someField: {
              type: 'object',
            },
          },
        },
      }
    },
  },
  response: {
    200: { ... },
};
```

**Comment by jsumners** [comment]
Please provide some more information. It is not at all clear what you are asking.

**Comment by sheldhur** [comment]
How i can validate deep object what will be sent as json string in query?
`/somepath?filter={"someField":{"gte":"10"}}`

https://swagger.io/docs/specification/describing-parameters/#schema-vs-content

**Comment by jsumners** [comment]
I'm going to guess that you're providing a schema definition for a route handler. Further, I'm going to guess that you are asking why your schema definition does not work.

Route handler schemas are JSON Schema. The _are not_ OpenAPI descriptions. See https://stoplight.io/blog/openapi-json-schema/ for an explanation of the difference.

**Comment by sheldhur** [comment]
Thanks, that problem is in fastify-oas
