### ISSUE TITLE
Update fast-json-stringify version 2.4.x

### ISSUE THREAD

**Issue by sinclairzx81** [fastify/fastify#2818]
## 🚀 Feature Proposal

Update `fastify` to use `fast-json-stringify@2.4.1`.

## Motivation

Recently I've been getting a few issues posted to the TypeBox repository where users of Fastify are experiencing various problems with the schemas produced by TypeBox. The two main issues appear to be non-resolvable `Symbol` properties which TypeBox uses for tagged unions in the schemas (but the Symbols are unavailable to the evaluated code context that the generated fast-json-stringify code runs in), and the other being support for `Type.Any()` and `Type.Unknown()` schemas (where `fast-json-stringify@2.1.x` doesn't support empty (or `any`) schemas).

I've submitted a few PR's on the `fast-json-stringify` project that resolve these particular issues, and I believe there's also been some enhancements related to `anyOf` and `enum` handling submitted by other users too. I think all these updates are all currently on `fast-json-stringify@2.4.1` so it would be great to update to the latest version if possible.

## TypeBox Issues

https://github.com/sinclairzx81/typebox/issues/26
https://github.com/sinclairzx81/typebox/issues/44
https://github.com/sinclairzx81/typebox/issues/46
https://github.com/sinclairzx81/typebox/issues/49

## Fast-Json-Stringify Issues

https://github.com/fastify/fast-json-stringify/issues/255
https://github.com/fastify/fast-json-stringify/issues/271
https://github.com/fastify/fast-json-stringify/issues/279

## Relevant PRs

fastify/fast-json-stringify#272
fastify/fast-json-stringify#280
fastify/fast-json-stringify#283

**Comment by mcollina** [comment]
The semver range in https://github.com/fastify/fastify/blob/d1f7754635b9f9c4e714953fdd0c152ac426ea41/package.json#L174 includes v2.4.1. Updating this is not needed.

**Comment by sinclairzx81** [comment]
@mcollina Awesome thanks :) I wasn't sure if the semver was working from the `revision` or the `minor` component. Happy to have this issue closed off.

**Comment by kibertoad** [comment]
@mcollina Aren't explicit version bumps still helpful when package-lock is involved?

**Comment by mcollina** [comment]
> @mcollina Aren't explicit version bumps still helpful when package-lock is involved?

Nope. Users should update their dependency with `npm update --depth 9999` or by recreating their lock files from scratch. If they decide to _not_ do so is their choice.

Unless a bump on a dependency is needed for a fix or a new feature. In that case it should be bumped.

**Comment by thatsnotright** [comment]
@sinclairzx81 These are great PRs, and I thank you for the excellent work.  It's really helped me out a lot.  @mcollina Thank you for merging.  These have solved so many issues for me.
