### ISSUE TITLE
Expose isError in request/reply

### ISSUE THREAD

**Issue by theGlenn** [fastify/fastify#2822]
## 🚀 Feature Proposal
It appears there is to discriminate errors response in hooks callbacks.
It would quite handy to have a `isError` property on reply

## Motivation
When disabling `disableRequestLogging` users might want to setup their own logging logic using hooks, in that context you might not want to treat "errored" response the same way as others.

Taking the following example I'd like to avoid logging twice inside both `onResponse` and `onError`

## Example

```ts
fastify.addHook('onResponse', (req, reply, done) => {
  let logMethod = reply.log.info;
  let logMsg = 'request completed';

  if (reply.statusCode >= 400) {
    logMethod = reply.log.warn;
    logMsg = 'request completed with warning';
  }

  if (reply.statusCode >= 500) {
    logMethod = reply.log.error;
    logMsg = 'request completed with 500';
  }

  // We cannot filter errors here
  if (!reply.isError) {
    logMethod({ res: reply }, logMsg);
  }

  done();
})

.addHook('onError', (req, reply, err, done) => {
  reply.log.error({ err: err }, 'request errored');
  done();
});
```

**Comment by mcollina** [comment]
What's your code in the error handler? From the point of view of `onResponse`, if `reply.statusCode >= 500` then we have an error response.

If you want to implement this functionality yourself, it's pretty straightforward.

```js
fastify.decorateReply('isError', false)
fastify.addHook('onError', (req, reply, err, done) => {
  reply.log.error({ err: err }, 'request errored');
  reply.isError = true;
  done();
});
```

I don't really see a reason to add this in core.

----

I'm also slightly concerned that you do:

```
  let logMethod = reply.log.info;
```

This should not be possible/work with pino without tweaking.
