### ISSUE TITLE
Route level hooks validation

### ISSUE THREAD

**Issue by AyoubElk** [fastify/fastify#2823]
## 🐛 Bug Report

Fastify currently doesn't validate route-level hooks:
- Property name typos go unnoticed
- Hooks can both be async and use done callback

## To Reproduce

```js
const fastify = require('fastify')({
  logger: true
})


fastify.addHook('preHandler', (request, reply, done) => {
  console.log('inside shared preHandler')
  done()
})

fastify.route({
  method: 'GET',
  url: '/',
  // Property name typo, hook not called
  preHandlre: function (request, reply, done) {
    console.log('inside route preHandler')
    done()
  },
  preValidation: async function (request, reply, done) {
    console.log('inside route preValidation (using both async and done callback)')
    done()
  },
  handler: function (request, reply) {
    console.log('inside handler')
    setTimeout(() => reply.send({ hello: 'world' }), 1000)
  }
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})

```

## Output

```
❯ node typo.js 
{"level":30,"time":1611921669902,"pid":19370,"hostname":"macbook.local","msg":"Server listening at http://127.0.0.1:3000"}
{"level":30,"time":1611921669903,"pid":19370,"hostname":"macbook.local","msg":"server listening on http://127.0.0.1:3000"}
{"level":30,"time":1611921671922,"pid":19370,"hostname":"macbook.local","reqId":1,"req":{"method":"GET","url":"/","hostname":"127.0.0.1:3000","remoteAddress":"127.0.0.1","remotePort":51239},"msg":"incoming request"}
inside route preValidation (using both async and done callback)
inside shared preHandler
inside handler
inside shared preHandler
inside handler
{"level":30,"time":1611921672929,"pid":19370,"hostname":"macbook.local","reqId":1,"res":{"statusCode":200},"responseTime":1006.7353990077972,"msg":"request completed"}
{"level":40,"time":1611921672930,"pid":19370,"hostname":"macbook.local","reqId":1,"err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (/Users/ayoub/Universe/upwork/gadget/fastify/lib/reply.js:113:26)\n    at Timeout._onTimeout (/Users/ayoub/Universe/upwork/gadget/fastify/typo.js:23:28)\n    at listOnTimeout (node:internal/timers:556:17)\n    at processTimers (node:internal/timers:499:7)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
```

## Expected behavior
Regarding the use of both async/done, I would expect fastify to validate route level hooks the same way it does for shared hooks added using `fastify.addHook()`.

Regarding incorrect hook property names, I'm not sure how we should proceed with that but I believe it should be handled somehow. Maybe wrap all route-level hooks in the route definition inside an object to be able to loop through them and validate?

## Your Environment

- *node version*: 15.2.1
- *fastify version*: 3.9.2
- *os*: Mac

**Comment by mcollina** [comment]
I'm not convinced we should validate the options as it allows other plugin developers to add their custom options. I agree that this is a problem - maybe adding a `hooks` prefix is right approach, would you mind sending a PR? I would recommend we don't remove the current behavior.

(note that your prevalidation hook is wrong, it has both async and a callback).

**Comment by AyoubElk** [comment]
> I'm not convinced we should validate the options as it allows other plugin developers to add their custom options. I agree that this is a problem - maybe adding a `hooks` prefix is right approach, would you mind sending a PR? I would recommend we don't remove the current behavior.

Will send a PR.

> (note that your prevalidation hook is wrong, it has both async and a callback).

Yes I explicitly used both since that is also an issue I believe. Users sometimes [make the mistake of using both](https://github.com/fastify/fastify-postgres/issues/74).
We already validate the hook params [when added using](https://github.com/fastify/fastify/blob/master/fastify.js#L461-L473
) `fastify.addHook()`, I think we should do so for route-level hooks as well.
