### ISSUE TITLE
Incorrect typings for FastifySchemaCompiler

### ISSUE THREAD

**Issue by agarwalarjun123** [fastify/fastify#2825]
Schema Validator should return function with data parameter but instead returns FastifyValidationResult type.

**snippet of code from fastify:**
export type FastifySchemaCompiler = (routeSchema: FastifyRouteSchemaDef) => FastifyValidationResult

Expected Code: 

export type FastifySchemaCompiler = (routeSchema: FastifyRouteSchemaDef) => (data: any) => FastifyValidationResult

## Your Environment

- *node version*: 14
- *fastify version*: 3.9.2
- *os*: Mac

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by climba03003** [comment]
Please check #2805 
It should be fixed when this landed

**Comment by agarwalarjun123** [comment]
is there an estimated ETA on this @climba03003.

**Comment by climba03003** [comment]
The PR #2807 is there, it only need someone in @fastify/typescript to approve the change.
I tagged the wrong one in first comment.

**Comment by agarwalarjun123** [comment]
cool thanks!! will check the PR for updates.
