### ISSUE TITLE
Broken image in docs/master/Encapsulation/

### ISSUE THREAD

**Issue by jonasfj** [fastify/fastify#2831]
Images appears broken in both master and latest:
 * https://www.fastify.io/docs/master/Encapsulation/
 * https://www.fastify.io/docs/latest/Encapsulation/

But the src of the image is `https://www.fastify.io/docs/latest/Encapsulation/resources/encapsulation_context.svg`
I'm guessing this is because of the trailing slash, so markdown works on github, but not after you build to have a trailing slash.

Seems to exist here: https://github.com/fastify/fastify/blob/master/docs/resources/encapsulation_context.svg

**Comment by jsumners** [comment]
https://github.com/fastify/website/issues/225

**Comment by jonasfj** [comment]
ah, closing as duplicate.
