### ISSUE TITLE
Fastify Instance has `any` value

### ISSUE THREAD

**Issue by leorossi** [fastify/fastify#2833]
## 🐛 Bug Report

Importing fastify 

## To Reproduce

```js
import { fastify } from 'fastify';

const app = fastify({
  logger: true
})

app.listen(3000
```

`{ fastify }` has the correct type

![Screenshot 2021-02-04 at 08 31 40](https://user-images.githubusercontent.com/604220/106872158-4b285880-66d3-11eb-8812-f77f9d768cd1.png)

*First symptom*: `fastify({})` seems returning a `any` (but if you dig into the declaration file, no overloads returns a `any`)

![Screenshot 2021-02-04 at 08 31 47](https://user-images.githubusercontent.com/604220/106872319-74e17f80-66d3-11eb-9a34-8ce597ae0800.png)

Hence `app` has `any` type

![Screenshot 2021-02-04 at 08 31 54](https://user-images.githubusercontent.com/604220/106872372-832f9b80-66d3-11eb-8b0b-8fd52f9efe03.png)

## Expected behavior

`app` has `FastifyInstance` type

## Your Environment

- *node version*: 14.14
- *fastify version*: 3.11.0
- *os*: Mac

**Comment by leorossi** [comment]
Maybe related to #2829 ?

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by L2jLiga** [comment]
From my end I'm also import fastify with by name as well in TypeScript and don't face with such issues, my instance typed properly

| package | version |
|----------|---------|
| fastify    | 3.11.0  |
| typescript | 4.1.3 |


*tsconfig.json*:
```json5
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    "target": "ES2020",
    "module": "ES2020",
    "declaration": true,
    "declarationMap": true,
    "outDir": "./dist",

    /* Strict Type-Checking Options */
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,

    /* Module Resolution Options */
    "moduleResolution": "node",
    "esModuleInterop": true,

    /* Source Map Options */
    "inlineSourceMap": true,
    "inlineSources": true,

    /* Experimental Options */
    "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true, /* Disallow inconsistently-cased references to the same file. */

    "typeRoots": [
      "./src/typings",
      "./node_modules/@types"
    ]
  },
  "files": [
    "src/main.ts"
  ],
  "include": [
    "src/**/*.ts"
  ],
  "exclude": ["./dist/**/*.ts"]
}

```

**Comment by mcollina** [comment]
This is in _JavaScript_, not typescript.

**Comment by L2jLiga** [comment]
Oops, sorry then most probably related to #2829 as @leorossi mentioned

**Comment by leorossi** [comment]
@L2jLiga using a `.ts` file works as expected, but VSCode should infer correct types even in plain JS

**Comment by fox1t** [comment]
I am going to look into this ASAP. Any suggestions @leorossi ?

**Comment by leorossi** [comment]
> I am going to look into this ASAP. Any suggestions @leorossi ?

It's unclear to me , I am not very familiar with this TS internals. I would focus on the second screenshot: fastify declaration files defines 4 overloads for the "contructor", and every one returns a `FastifyInstance`, why then it resolves to `any`?

**Comment by fox1t** [comment]
I've just tried to reproduce without success: it is working for me
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1620916/106913120-f7823300-6703-11eb-9021-a0c1c82aa0bc.png">
Can you please provide a repro repo?

**Comment by climba03003** [comment]
Maybe it is cause by `vscode` itself, the language server sometimes broken. I cannot reproduce the same case.
![image](https://user-images.githubusercontent.com/23028015/106915869-82355300-6741-11eb-9009-b058dc8f5e86.png)

**Comment by mcollina** [comment]
@leorossi can you try updating your vscode?

**Comment by leorossi** [comment]
I can confirm that it was the language server.

Tried with a fresh directory, `npm init -y` and stuff... type was resolved correctly.

Deleted `.vscode` on the "failing" project, refreshed `node_modules` and type was resolved correctly.
