### ISSUE TITLE
Error Message for Decorators

### ISSUE THREAD

**Issue by Crypt0Graphic** [fastify/fastify#2834]
I'm using the structure that came with fastify-cli (2.7.0). 

I set decorators under plugins folder so as i understood there is no need manual plugin creation. Am i right? :/

When i call a plugin in app.js after plugins autoload, no problem:

![Screen Shot 2021-02-05 at 11 57 02](https://user-images.githubusercontent.com/9743846/107011844-46ce6f00-67a9-11eb-99ba-fc2198818f81.png)

But if i call it before plugins autoload, it does not work normally. But no any error. An error like "decorator not found" could be nice in general:

![Screen Shot 2021-02-05 at 11 53 30](https://user-images.githubusercontent.com/9743846/107012011-7e3d1b80-67a9-11eb-8d0b-24e7ed4ed0d4.png)

P.S. fastify.decorator() returns error like it's not function but fastify.decorator returns nothing.

**Comment by Eomm** [comment]
I would expect a `initPool is not a function` error. Is your server starting?

**Comment by mcollina** [comment]
> But if i call it before plugins autoload, it does not work normally. But no any error. An error like "decorator not found" could be nice in general:

Unfortunately JavaScript does not allow to intercept missing properties (for example, Ruby supports it).

**Comment by Crypt0Graphic** [comment]
> I would expect a `initPool is not a function` error. Is your server starting?

Yes i got that error and server does not start. 

But what would happen if decorator was not a function? A warning like "Fastify Has Not Such a Decorator" would be cleaner. Not an issue.

**Comment by jsumners** [comment]
`fastify-plugin` provides the ability to denote a plugin requires specific decorators to be present.

**Comment by Crypt0Graphic** [comment]
> `fastify-plugin` provides the ability to denote a plugin requires specific decorators to be present.

I have no trouble with plugins/decorators out app.js. But in app.js it's different. Another example:

![Screen Shot 2021-02-05 at 16 29 40](https://user-images.githubusercontent.com/9743846/107040019-b8211880-67cf-11eb-9cc0-cd633ff1620b.png)

`process.once('SIGTERM', fastify.closePoolAndExit()).once('SIGINT', fastify.closePoolAndExit());`

This works at startup and close connection. Normally it should work at exit. It works at exit when i don't use  fastify.closePoolAndExit(). Like:

![Screen Shot 2021-02-05 at 16 34 59](https://user-images.githubusercontent.com/9743846/107040311-1bab4600-67d0-11eb-8181-dc0a16da3c33.png)

Btw, i don't use Done() in plugins and all works well if i don't use them in app.js. But in plugins that i use in app.js needs it. I can't figure out what is the difference. :/

**Comment by jsumners** [comment]
Please see the docs for `.once` -- https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_emitter_once_eventname_listener

You should supply an anonymous (lambda) function as the second parameter.

**Comment by Crypt0Graphic** [comment]
> Please see the docs for `.once` -- https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_emitter_once_eventname_listener
> 
> You should supply an anonymous (lambda) function as the second parameter.

Thank you. This worked:

`process.once('SIGTERM', () => fastify.closePoolAndExit()).once('SIGINT', () => fastify.closePoolAndExit());`
