### ISSUE TITLE
Logger option genReqId not considered

### ISSUE THREAD

**Issue by dmateiu** [fastify/fastify#2836]
## 🐛 Bug Report

The `genReqId` function specified within the standard Pino Logger options object is not considered, when generating identifiers for incoming requests.

## To Reproduce

```js
fastify({
    logger: {
        genReqId: req => 'whatever string',
    },
});
```

This bug was fixed here https://github.com/fastify/fastify/commit/526e3a5fc243984270ab4cf22609c79c5de409ba, but got reintroduced.

## Expected behavior

According to the docs, the logger's `genReqId` function should be applied. 

The fix might be to check if the `logger.genReqId` is set.

```js
// Update the options with the fixed values
...
options.logger = logger
options.genReqId = logger.genReqId || genReqId
options.requestIdHeader = requestIdHeader
...
```

## Your Environment

- *node version*: 14.15
- *fastify version*: 3.11.0
- *os*: Mac

**Comment by mcollina** [comment]
That type of usage in the logger was deprecated long ago: https://github.com/fastify/fastify/pull/1166/files, and then remove https://github.com/fastify/fastify/pull/1750.

This should work:

```
fastify({
    logger: true,
    genReqId: req => 'whatever string',
});
```

Where did you find that info about `genReqId`?

**Comment by dmateiu** [comment]
I got it from these docs https://www.fastify.io/docs/latest/Server/#logger.

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/blame/master/docs/Server.md#L136 < should be removed.

**Comment by dmateiu** [comment]
Awesome. Thanks for the quick reply and fix!

**Comment by makuzaverite** [comment]
May I fix this one @mcollina

**Comment by mcollina** [comment]
Go for it!
