### ISSUE TITLE
Consider using prettier for code formatting

### ISSUE THREAD

**Issue by mgcrea** [fastify/fastify#2837]
## 🚀 Feature Proposal

Use prettier for code formatting, add a `.prettierc` file and actively check for proper formatting on commit.

## Motivation

Currently looking into writing some unit tests and having to manually adapt the code styling to prevent eslint errors is a pain! Imo prettier is such a net positive for developer experience that it feels like a no-brainer.

Looks like you actively guard against it so I guess you have another view on this, but maybe not definitive?

Adding a prettier config file of your liking and performing a one-shot `--write` to fix current formatting issues would lead to a more pleasant developer experience.

**Comment by mcollina** [comment]
(Copied from https://github.com/fastify/fastify/pull/2269)

FYI: standard --fix does this for you. You can configure your editor to do it as well.

You probably have prettier configured as plugin in your editor to automatically lint every possible JS file it encounters. This is such a bad practice and have caused so much traffic in my repos because valid contributions completely changed the formatting of my projects: it is rude. Hence my distaste for the VSCode prettier extension and its default configuration.

Once upon a time, I set up Fastify to not to contribute to spread this phenomenon. I think changing linting is such a pain for the maintainers to never be a net benefit.

**Comment by mcollina** [comment]
I'm not opposing adding a prettier config that will cause _minimal_ changes to the repo (<100 lines, lesser is better). I don't think it's possible.

**Comment by jsumners** [comment]
Please see the guide to be added by https://github.com/fastify/fastify/pull/2610

**Comment by mgcrea** [comment]
> You probably have prettier configured as plugin in your editor to automatically lint every possible JS file it encounters. This is such a bad practice and have caused so much traffic in my repos because valid contributions completely changed the formatting of my projects: it is rude. Hence my distaste for the VSCode prettier extension and its default configuration.

No I don't have my vscode configured to auto-prettify every js file, I agree this is a bad practice. It only ever runs if there is a prettier config file in the project (which obviously might/should be the default).

However I do have an eslint extension that runs when there is an eslint config file in the project, which is the case here and that nags me (rightfully) for not respecting the code formatting.

I just think that having prettier is a superior developer experience than having to manually please a myriad of style-related eslint rules.

Will have a try at a prettier config file and let you know.

**Comment by mgcrea** [comment]
Ok back from my testing, indeed the changes were in the thousands and not in the hundreds.

Main line-diff contributing issues were:
- standard `space-before-function-paren` that is not configurable in prettier.
-  function block indentation issues that moves indentation of whole blocks.
- semicolons used inconsistently across the project (~300 lines with semicolons).

I personnaly think that prettier is a net-win for any team project, but I would understand your choice of not changing the code too much and keeping the current status-quo.

If you want to have a look at the changes: 

https://github.com/mgcrea/fastify/commit/c2cfa9f55f10bb54dbc093f3cd83ec40f1bd4d87

**Comment by jsumners** [comment]
> * semicolons used inconsistently across the project (~300 lines with semicolons).

Standard relies on automatic semi-colon insertion except for the few cases where that is not viable.

**Comment by jsumners** [comment]
This would be a drastic change to many people's workflow. It also wouldn't account for the _many_ other repositories within the overall ecosystem. I do not see this as a "net benefit" for the project.

The reality is that different projects have different styles. When contributing to a project it is incumbent upon the contributor to accept that fact and conform their contributions to said style. As a corollary, it is incumbent upon the project to make that as easy as possible for potential contributors. We are attempting to do that via https://github.com/fastify/fastify/issues/2837#issuecomment-773996147.

**Comment by mcollina** [comment]
Thanks for the discussion @mgcrea! I think you bring us so many valid points - I guess we'll stick with standard but it's good to keep talking about why.

**Comment by mgcrea** [comment]
I totally understand, thanks for the quick feedback and openness to discussion 👍 .
