### ISSUE TITLE
Array support in querystring validation

### ISSUE THREAD

**Issue by bluenote10** [fastify/fastify#2841]
## 🚀 Feature Proposal

Validating arrays in query strings either has a bug or is a missing feature.

## Motivation

Using a schema involving `type: "array"` for `querystring` currently doesn't work properly. The only solution I have found so far is to not use `type: "array"` at all in `querystring` and do a manual validation of the array items, which defeats the purpose of having a validation schema.

There are a few conventions for passing in arrays in `GET` requests, for instance:

1. repeated parameters: `/route?ids=foo&ids=bar` This seems to be most popular supported by request frameworks like Python's `request` or Java's `Jersey`.
2. plain comma separate: `/route?ids=foo,bar`
3. JSON like array: `/route?ids=[foo,bar]`

See also [suggestions on StackOverflow](https://stackoverflow.com/questions/11944410/passing-array-in-get-for-a-rest-call).

Approach (1) seems to be almost supported already: It works with 2 and more values, but fails to validate a list of length 0 or 1 -- perhaps just a bug?

## Example

```js
const fastify = require("fastify")({
  logger: true,
});

const opts = {
  schema: {
    querystring: {
      type: "object",
      properties: {
        ids: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["ids"],
    },
  },
};

fastify.get("/", opts, (request, reply) => {
  fastify.log.info(request.query);
  reply.send({ ok: true });
});

fastify.listen(8080, function (err) {
  if (err) {
    throw err;
  }
});
```

- [`http://127.0.0.1:8080/?ids=foo&ids=bar`](http://127.0.0.1:8080/?ids=foo&ids=bar) works fine.
- [`http://127.0.0.1:8080/?ids=foo`](http://127.0.0.1:8080/?ids=foo) fails with `querystring.ids should be array`, but should validate to a 1-element array.
- [`http://127.0.0.1:8080/`](http://127.0.0.1:8080/) fails with `querystring should have required property 'ids'`, but should validate to a 0-element array.

**Comment by zekth** [comment]
Good catch. Could you send a PR for this?

**Comment by bluenote10** [comment]
> Good catch. Could you send a PR for this?

I had a quick look into it, and it looks like it is a bit tricky. The problem is that currently the extraction of the query object is based on [`querystring.parse`](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options), which doesn't know anything about the schema. So its behavior simply is:
- `ids=foo&ids=bar` produces `{ ids: ["foo", "bar"] }`
- `ids=foo` produces `{ ids: "foo" }` 
- an empty query string obviously misses the property completely.

As far as I can see, the validation cannot really recover from that easily.

A general design question here is, if the solution should only work for arrays, or whether nested objects should be supported as well (via generic JSON expressions). Currently `{ "type": "object" }` would also fail in a querystring schema, but it is also a less common use case I suppose.

I see two possibilities:

1. The query parser needs to have some schema awareness. The parser function would not only take the query string, but also additional information coming from the schema -- either the schema itself, or for performance reasons, some information statically derived from the schema. This could be something like `arrayLikeProps = { "foo": true }` and then the query parser could make sure to treat the `foo` property as an array. This could also be extended to `objectLikeProps = { "bar": true }`, which would apply a `JSON.parse` on the `bar` data string.

2. Solve the problem as a post-processing step after query parsing or in the coercion logic of the validation.

Any thoughts?

**Comment by mcollina** [comment]
> The query parser needs to have some schema awareness. The parser function would not only take the query string, but also additional information coming from the schema -- either the schema itself, or for performance reasons, some information statically derived from the schema. This could be something like arrayLikeProps = { "foo": true } and then the query parser could make sure to treat the foo property as an array. This could also be extended to objectLikeProps = { "bar": true }, which would apply a JSON.parse on the bar data string.

Fastify allows for a custom query parser to be specified. We use Node.js core one to maximize compatibility. You should be able to write a new query string parser that knows about the schema... however you might have to adjust our internal APIs first, as I don't think we are passing the schema through that step.

---

You can also use https://www.npmjs.com/package/qs as a querystring parser that will parse arrays as you like them. See https://www.fastify.io/docs/latest/Server/#querystringparser.

I think this is the correct answer to your question which would make your schema work, but maybe I'm wrong - I didn't fully grasp what you are trying to do.

We should really include this information in the docs.

**Comment by L2jLiga** [comment]
As workaround it's also possible to use `preValidation` hook:

```javascript
const fastify = require("fastify")({
  logger: true,
});

const opts = {
  preValidation(request, reply, done) {
    if (typeof request.query.ids === 'undefined') request.query.ids = [];
    if (!Array.isArray(request.query.ids)) request.query.ids = [request.query.ids];
    done();
  },
  schema: {
    querystring: {
      type: "object",
      properties: {
        ids: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["ids"],
    },
  },
};

fastify.get("/", opts, (request, reply) => {
  fastify.log.info(request.query);
  reply.send({ ok: true });
});

fastify.listen(8080, function (err) {
  if (err) {
    throw err;
  }
});
```

**Comment by bluenote10** [comment]
Yes, thanks for the input, these are good work-arounds indeed. 

> You can also use https://www.npmjs.com/package/qs as a querystring parser that will parse arrays as you like them.

It should be noted that this probably also cannot support the form `ids=foo&ids=bar`, but relies on the user to give the query parser a "schema hint" via using `ids[]=foo&ids[]=bar`.

So the question becomes if the following issues need to be solved:

- Fastify's default query parser + default schema handling don't work well together.
- The schema could lose its role as "single source of truth" for property handling. This is mainly violated by the `preValidation` approach, because the information which properties are arrays need to be maintained twice. (It is only indirectly violated by the `qs` approach, in the sense that the query parser relies on a schema hint from the incoming request.)

**Comment by zekth** [comment]
I agree that adding this feature in core is adding a lot of checks on querystring parsing for a really tiny use. (of a really sketchy design)
I wonder if it's worth giving it a shot to make this work as a plugin with the kind of code @L2jLiga provided.

**Comment by mcollina** [comment]
> It should be noted that this probably also cannot support the form ids=foo&ids=bar, but relies on the user to give the query parser a "schema hint" via using ids[]=foo&ids[]=bar.

Do you know about a query string parser for Node.js that have the implementation that you are asking for?

> So the question becomes if the following issues need to be solved:

> - Fastify's default query parser + default schema handling don't work well together.
> - The schema could lose its role as "single source of truth" for property handling. This is mainly violated by the `preValidation` approach, because the information which properties are arrays need to be maintained twice. (It is only indirectly violated by the `qs` approach, in the sense that the query parser relies on a schema hint from the incoming request.)

We are not in agreement. I would say that __Fastify does not support passing arrays as part of the query string__, some workarounds are possible but they do not look great.

**Comment by bluenote10** [comment]
> Do you know about a query string parser for Node.js that have the implementation that you are asking for?

No, because they don't start with a schema. Fastify can have schemas, which makes the situation slightly different. 

> We are not in agreement. I would say that Fastify does not support passing arrays as part of the query string.

No disagreement ;) that is a perfectly fine conclusion as well. I was merely summarizing the small problems that this would leave, but these problems may indeed be preferable over the added complexity of entangling query parsing with validation.

Currently, the documentation suggests that everything that can be done with ajv may be supported. The documentation may simply say that query string validation only supports scalar properties and neither arrays (`type: "array"`) nor nested objects (`type: "object"`). This probably has to be documented for query **params** anyway, where nested arrays/objects don't make much sense at all, even though they technically could be specified in the ajv schema.

> [...] for a really tiny use. (of a really sketchy design)

Not so sure how tiny it is though. I ran into this issue in the very first route I wrote in Fastify. There are certainly valid uses cases for that, e.g. passing-in multiple search terms, multiple product ids, etc, which is why it is supported in many APIs. In general programming, a function taking a list of input values is certainly not "sketchy design". The real culprit is the limitation of http requests, and perhaps one might as well drop the REST best practices, follow GraphQL, and use `POST` for everything.

**Comment by zekth** [comment]
> Not so sure how tiny it is though. I ran into this issue in the very first route I wrote in Fastify. There are certainly valid uses cases for that, e.g. passing-in multiple search terms, multiple product ids, etc, which is why it is supported in many APIs. In general programming, a function taking a list of input values is certainly not "sketchy design". The real culprit is the limitation of http requests, and perhaps one might as well drop the REST best practices, follow GraphQL, and use `POST` for everything.

In here is was meaning the specs of arrays is Querystrings.

**Comment by RafaelGSS** [comment]
Hey everyone! Sorry for the late, I've found this behavior 2 years ago:

ref: https://github.com/fastify/fastify/issues/1693.

And my solution was something like:

```js
const fastify = require('fastify')()

const Ajv = require('ajv').default

const ajv = new Ajv({
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: 'array',
  allErrors: true
})

fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schema)
})

const opts = {
  schema: {
    querystring: {
      type: 'object',
      properties: {
        hello: {
          type: 'array',
        },
      },
      required: ['hello']
    }
  }
}

fastify.get('/', opts, (request, reply) => {
  reply.send({ params: request.query })
})

fastify.listen(3535, function (err) {
  if (err) {
    throw err
  }
  console.log(`server listening on ${fastify.server.address().port}`)
})
``` 

Results:

```sh
curl -X GET "localhost:3535/?hello=1"
{"params":{"hello":["1"]}}

curl -X GET "localhost:3535/?hello=1&hello=2"
{"params":{"hello":["1","2"]}}
```

May it can help you @bluenote10. The magic is on: `coerceTypes: 'array'` parameters on Ajv instance.

It's also worth discussing regarding allowing additional parameters to `ajv` instance under fastify initialization. We can add it under `setValidatorCompiler`, but I wouldn't mind changing the default values in fastify instance.

**Comment by mcollina** [comment]
>It's also worth discussing regarding allowing additional parameters to ajv instance under fastify initialization. We can add it under setValidatorCompiler, but I wouldn't mind changing the default values in fastify instance.

this is supported, see https://www.fastify.io/docs/latest/Server/#ajv

**Comment by RafaelGSS** [comment]
> > It's also worth discussing regarding allowing additional parameters to ajv instance under fastify initialization. We can add it under setValidatorCompiler, but I wouldn't mind changing the default values in fastify instance.
> 
> this is supported, see https://www.fastify.io/docs/latest/Server/#ajv

So you just need to send the `coerceTypes` to them, @bluenote10 :smile:

**Comment by mcollina** [comment]
I have a feeling we should document this https://github.com/fastify/fastify/issues/2841#issuecomment-778238445 https://github.com/fastify/fastify/issues/2841#issuecomment-778240710

**Comment by bluenote10** [comment]
> May it can help you @bluenote10. The magic is on: coerceTypes: 'array' parameters on Ajv instance.

Can this be set for certain routes / properties only? The specific use case I had in mind would require mixing array with non-array properties within one schema. My understanding was that setting `coerceTypes: 'array'` in `fastify.setValidatorCompiler` will result in converting all properties in all routes to arrays, which would be quite a radical change.

**Comment by mcollina** [comment]
@bluenote10 setting `coerceTypes: 'array'`  would coerce only the properties that are set as type `array`.

**Comment by bluenote10** [comment]
> @bluenote10 setting coerceTypes: 'array' would coerce only the properties that are set as type array.

I see, so this should fully solve the problem!

Any reason not to enable this by default? In cases that don't use `type: 'array'` in the schema there shouldn't be an impact on performance, because nothing gets coerced as array. As soon as arrays are involved, users probably would want to have it enabled to make it actually do what is intuitively expected. Even for body validation there shouldn't be a difference, because the validation has to run `Array.isArray` anyway, and no further coercion is required in these cases where to object already is an array.

**Comment by mcollina** [comment]
Changing those default settings are semver-major changes. Would you like to open a separate issue for that where we can discuss it?

**Comment by bluenote10** [comment]
> @bluenote10 setting coerceTypes: 'array' would coerce only the properties that are set as type array.

FYI I noticed that the example only works for the array length >= 1 case. To support the empty array case as well the schema definition can be adjusted to have a default, see my comment to the PR as well.

**Comment by Eomm** [comment]
Note that this works with plain fastify config too:

```js
  const fastify = Fastify({
    disableRequestLogging: true,
    ajv: {
      customOptions: {
        coerceTypes: 'array'
      }
    }
  })
```

**Comment by SiarheiFedartsou** [comment]
Hi👋 
Is it currently possible to support validation for `ids=1,2,3` use case?

**Comment by climba03003** [comment]
> Hi👋 Is it currently possible to have array validation for `ids=1,2,3` use case?

Provide a custom `querystring` parser to parse the format of `1,2,3`. Then the validation would be possible.

**Comment by SiarheiFedartsou** [comment]
@climba03003 thanks for the answer! May be you have any examples/docs on how exactly it can be done? Tbh I have problems with googling it :)

**Comment by climba03003** [comment]
@SiarheiFedartsou 
https://www.fastify.io/docs/latest/Reference/Server/#querystringparser

I will lock this issue, or you can create an discussion or use `fastify/help` repo for your question.
