### ISSUE TITLE
Improve errors user experience

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2842]
Fastify has many assertions around in the codebase to make sure that the user didn't misconfigure something, for instance, it checks if a route has been declared twice or if a plugin is not a function.
This is great, we vastly reduce the possibility of weird runtime issues, but for historical reasons the errors we are emitting are everything but user friendly.

We should improve this situation, as it is a big pain point in our user experience.

Example of double route declaration:
```js
'use strict'
const fastify = require('fastify')()
fastify.get('/', () => {})
fastify.get('/', () => {})
fastify.listen(3000, console.log)
```

```
▶ node index.js
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/'
    at Router._insert (.../fst-err/node_modules/find-my-way/index.js:304:9)
    at Router._on (.../fst-err/node_modules/find-my-way/index.js:197:8)
    at Router.on (.../fst-err/node_modules/find-my-way/index.js:74:8)
    at Object.afterRouteAdded (.../fst-err/node_modules/fastify/lib/route.js:253:16)
    at .../fst-err/node_modules/fastify/lib/route.js:187:25
    at Object._encapsulateThreeParam (.../fst-err/node_modules/avvio/boot.js:545:7)
    at Boot.timeoutCall (.../fst-err/node_modules/avvio/boot.js:447:5)
    at Boot.callWithCbOrNextTick (.../fst-err/node_modules/avvio/boot.js:428:19)
    at Boot._after (.../fst-err/node_modules/avvio/boot.js:273:26)
    at Plugin.exec (.../fst-err/node_modules/avvio/plugin.js:131:17) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

What I would expect instead is:
```
FastifyError: Method 'GET' already declared for route '/'
   at fastify.get('/', () => {}) (.../fst-err/index.js:4:9)
```
Which is quite complex, given that our route declaration is asynchronous.

Another example, this time with bad plugin type:
```js
'use strict'
const fastify = require('fastify')()
fastify.register(null)
fastify.listen(3000, console.log)
```
```
▶ node index.js
.../fst-err/node_modules/avvio/boot.js:200
    throw new Error('plugin must be a function or a promise')
    ^

Error: plugin must be a function or a promise
    at assertPlugin (.../fst-err/node_modules/avvio/boot.js:200:11)
    at Boot._addPlugin (.../fst-err/node_modules/avvio/boot.js:233:12)
    at Boot.use (.../fst-err/node_modules/avvio/boot.js:209:25)
    at Object.server.<computed> [as register] (.../fst-err/node_modules/avvio/boot.js:33:14)
    at Object.<anonymous> (.../fst-err/index.js:5:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

As you can see, the error is not being helpful at all.

**Comment by mcollina** [comment]
This is as much of a problem in avvio as it is fastify itself. I think the biggest problem is that we are doing these assertions in the wrong places: we should do them _synchronously_, we the user call those APIs.

I think we should also identify the most common problems and start patching them/moving the error definitions as near the end user as it's possible.

**Comment by delvedor** [comment]
I agree, but in some cases is possible, such as the plugin type check, but in other, like the route declaration, it's not happening synchronously, so we could have false positives.

**Comment by mcollina** [comment]
> I agree, but in some cases is possible, such as the plugin type check, but in other, like the route declaration, it's not happening synchronously, so we could have false positives.

We should move those checks to be synchronous.

**Comment by jsumners** [comment]
100% on board with this happening. It's very inline with https://github.com/fastify/fastify/issues/2760

**Comment by MetCoder95** [comment]
Hi! I'm looking forward to addressing this issue, based on your comments and digging deeper into the code, I just want to summarise my findings and see if I'm correctly understanding how this can be possible in the first instance. 

**For duplicated routes**
Basically, the registering of routes happens after either the Promise is resolved or the `done` callback is called when registering a plugin, this means after previously registered plugins are loaded and `avvio` executes the callback passed to the `after` function. 

Right here [`route.js:L157`](https://github.com/fastify/fastify/blob/master/lib/route.js#L157). To achieve this, the route should be registered once the `route` function is called.

That will mean no check if the dependencies are ready or not for the routes. I'm not sure if this will bring more problems as anyways fastify boots once all the plugins are ready unless I'm missing something.

**For plugin registration**
I'm not sure how to achieve this (so for sure I'm missing something), but I assume that can be made in the same way as `ready` is being overwritten on [`fastify.js:L354`](https://github.com/fastify/fastify/blob/master/fastify.js#L354) but preserving the `register` function set on the `fastify` instance.

Also, should a `FastifyError` object be added in order to have a more customized experience?

Please let me know your feedback and I'll start it in the upcoming days 🙂

**Comment by mcollina** [comment]
> **For duplicated routes**
> 
> Basically, the registering of routes happens after either the Promise is resolved or the `done` callback is called when registering a plugin, this means after previously registered plugins are loaded and `avvio` executes the callback passed to the `after` function. 
> 
> 
> 
> Right here [`route.js:L157`](https://github.com/fastify/fastify/blob/master/lib/route.js#L157). To achieve this, the route should be registered once the `route` function is called.
> 
> 
> 
> That will mean no check if the dependencies are ready or not for the routes. I'm not sure if this will bring more problems as anyways fastify boots once all the plugins are ready unless I'm missing something.

I do not think this is the correct solution as it will break encapsulation. We need to move https://github.com/fastify/fastify/blob/c5d950d208bda6268832cff4f8301162ea0a9c5f/lib/route.js#L252 to happen during the sync call to `route()`, but set all the values inside `Context` asynchronously (these: https://github.com/fastify/fastify/blob/c5d950d208bda6268832cff4f8301162ea0a9c5f/lib/route.js#L240-L246). 

 
> **For plugin registration**
> 
> I'm not sure how to achieve this (so for sure I'm missing something), but I assume that can be made in the same way as `ready` is being overwritten on [`fastify.js:L354`](https://github.com/fastify/fastify/blob/master/fastify.js#L354) but preserving the `register` function set on the `fastify` instance.
> 
> 
> 
> Also, should a `FastifyError` object be added in order to have a more customized experience?
> 
> 
> 
> Please let me know your feedback and I'll start it in the upcoming days 🙂 

As for the plugins, I would just change it inside avvio itself and do not override anything here.

**Comment by MetCoder95** [comment]
>I do not think this is the correct solution as it will break encapsulation. We need to move to happen during the sync call to `route()`, but set all the values inside Context asynchronously.

Hmm, got it. I see now. Just to be sure I understood correctly (first time working with the route registration module), the `Context` values should be set once `avvio` is emitting the `preReady` event to avoid breaking the encapsulation.

> As for the plugins, I would just change it inside avvio itself and do not override anything here.

Sounds good, I'll take a look into `avvio` as well 👍 

What about the `FastifyError`, should be considered or just use a plain `Error` object?

**Comment by MetCoder95** [comment]
The first PR is merged for the improvement of the error experience. I'll open the next PR in the upcoming days into `avvio`

**Comment by MetCoder95** [comment]
After taking a look again into the stated issue and the implementation in `avvio` and `fastify`, I'm not 100% what we're looking to achieve by changing the way `avvio` throws an error?

As `avvio` is made for general use and not only for `fastify`, might be a good idea to let it have its own error codes, pretty similar to how `fastify` handles it. On `fastify` we can just check for the error on the throw by `avvio` on the custom `ready` function, and wrap it with a custom `fastify` error.

https://github.com/fastify/fastify/blob/034d3358cd2036009f8690c1e3889bbb76cdcd1b/fastify.js#L435-L475

What do you think? It's also possible that I'm missing the big picture 😅

**Comment by jsumners** [comment]
I think that is a fair assessment.

**Comment by MetCoder95** [comment]
The PR for `avvio` is done, thanks @mcollina for the help! 🙏 

The feature is waiting for the next major release, should we wait till the new release of `avvio` or start working on it in `fastify` by using an `rc` from `avvio`?

**Comment by mcollina** [comment]
You can start preparing a PR targeting the next branch in avvio.

**Comment by MetCoder95** [comment]
Thanks for all the help! The last PR is merged! 🎉 
Just waiting for the next release of `avvio` for updating the dependency within `fastify`!

**Comment by jsumners** [comment]
Great work.
