### ISSUE TITLE
Timeline for ESM migration

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#2847]
Do you think we should port Fastify (and plugins) to ESM? or stick to CJS as far as we can?

Most notably, Sindre recently said he will port most of his modules to ESM.

We are not in a hurry, as Fastify already loads well with ESM to the shim layer Node.js provides.

**Comment by jsumners** [comment]
What benefit does this provide? To whom? How will affect users who use CJS?

**Comment by mcollina** [comment]
>   What benefit does this provide? To whom? 

It is essentially a marketing operation. Forcing people to use modern patterns will help growth.
The main technical benefit could happen when/if a dependency we use as CJS become ESM.
At that point we will be stuck on the old version until we move ourselves.

> How will affect users who use CJS?

It would create some minor annoyances, as `require('fastify')` becomes `import('fastify').then( ... )`.

---

Another alternative is to _just_ update the example on the website and maybe part of the docs.

**Comment by jsumners** [comment]
> It would create some minor annoyances, as `require('fastify')` becomes `import('fastify').then( ... )`.

I'm not sure how that qualifies as "minor". It radically changes the structure of the code to account for the asynchronous nature of ESM.

> Another alternative is to _just_ update the example on the website and maybe part of the docs.

I think that is fine.

**Comment by jsumners** [comment]
For reference, this is Sindre's announcement https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77

**Comment by mgcrea** [comment]
I do think it would be great to push forward to ESM modules. I personally would rather see a switch to TypeScript but I know this is not aligned with your current vision.

In my (anecdotal) case, I haven't written commonjs for at least 4 to 5 years now (thanks to babel, then ts), and I think the community is ready for the switch. Moreover, there is always the option to have dual support thanks to a build step (which is pretty ubiquitous nowadays), but I'd be fine with pure ESM since it wouldn't change anything for me.

I chose fastify mainly for it's better typescript developer experience vs. express, it's project liveliness and "modern" API (hooks, etc.). Switching to ESM would strengthen its modern aspect and would probably be seen as a positive move from users tired of the deep frozen state of express.

**Comment by delvedor** [comment]
Thank you for raising this issue!
Unfortunately, this will be a big problem that eventually we will need to solve.

From my understanding, this is the situation:
- If you are working with native ESM and import a CJS package, everything works out of the box.
- If you are working with CJS and import an ESM package, require won't work, you will need to use `import`, which is async.

This means that if you are working on a CJS project and one of your dependencies ships native ESM only, your code needs to be heavily refactored.

Given that ESM will be the future, the discussion is not about *"should we move to ESM"*, but rather *"when should we move to ESM"*.
What we should do now, is to figure out a migration plan.
I see two possible paths:

1. v4 will still ship CJS, but all examples/documentation and the cli generator will use ESM, and v5 will migrate the codebase to ESM. Maybe log a warning if we detect CJS usage.
2. Migrate both codebase and documentation to ESM in v4.

The first solution is definitely better, users will have time to migrate, and maybe the community will come up with some tooling to facilitate migrating. But it comes with a significant risk: if one of our dependencies or a dependency of a dependency moves to ESM, that breaking change will be propagated everywhere, as ESM is viral (this is not a question of if, but only when, see [here](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77)). This means that we will very likely be stuck with old versions of dependencies until we migrate.
The second solution is more radical and will disrupt existing applications that will not be able to migrate quickly. Still, given that ESM can handle CJS code without problems, our job as maintainers will be way more manageable than the other way around.

Bonus questions:
- How about TypeScript support? What changes with ESM? (/cc @fox1t @Ethan-Arrowood)
- How crazy would it be to go with option 1 and bundle in Fastify, a compiled version of our dependencies? (à la Next.js)
- Will ESM cause some problems for APM vendors? (/cc @trentm @astorm)

**Comment by mcollina** [comment]
> I haven't written commonjs for at least 4 to 5 years now (thanks to babel, then ts), and I think the community is ready for the switch, the writing is on the wall as most newcomers start directly with ESM (most of them via webpack powered frontend frameworks).

I'm sorry to interject, but you have written commonjs with a different syntax. You have not written ESM - the same holds true for most JS developers out there.

**Comment by mcollina** [comment]
At this time it's impossible/extremely hard to build an APM agent that supports native ESM. I know a few smart people that are working on the problem, so it might well happen in the future. I'm ok in calling that a prerequisite of moving Fastify to ESM.

**Comment by jsumners** [comment]
> Given that ESM will be the future, the discussion is not about _"should we move to ESM"_, but rather _"when should we move to ESM"_.

Is it? The answer I have been given is that _both_ are the future -- https://github.com/nodejs/node/issues/33954#issuecomment-776792555. I will agree that "ESM is the future" when core says they are deprecating CJS.

**Comment by trentm** [comment]
> Will ESM cause some problems for APM vendors? 

Yes. On the APM instrumentation side, I'm not aware of a way to *automatically* handle ESM `import ...`s and `import(...)`s.

As long as those ESM modules are also `require()`able **and** result in loading the same source files -- as the node core modules currently support -- then one can manually pre-`require` those modules for the APM instrumentation to get its monkey-patching done before the app code `import`s.
https://gist.github.com/trentm/49aef693cff58b7e0dc50739846437af 
That requires manually listing all the modules to instrument (which is a regression of sorts for APM usage), or `try/catch` attempting to require every module the APM agent possibly knows how to instrument (which may not be/likely isn't nice for the app author).

> it might well happen in the future.

Say core support for instrumenting `import` happens in node v18. Then users of node 12, 14, 16 are left in a something of a lurch.

**Comment by astorm** [comment]
Hey all -- here's some more color on the existential problem that node-native ESM modules present for APM vendors.  

Most APM vendors with a Node.js agent rely on module hooking/monkey-patching for their  instrumentation.  At a high level this means [using something like require-in-the-middle](https://www.npmjs.com/package/require-in-the-middle) to listen for the first time Node loads a module via `require`, intercepting that loading, monkey-patching the methods we need to instrument, and then returning the patched module to the end users.

With node-native `import` statements bypassing the `require` code paths, this means modules like require-in-the-middle aren't going to work anymore.  It's my semi-informed but still naive understanding that the `import` code paths aren't hookable in the same way that the [`require('module')` module](https://nodejs.org/api/modules.html) is.  

So a future where people aren't using the `require` function to load their modules means APM vendors can't hook module loading, which will break instrumentation.  So my first knee jerk response to a popular module like `fastify` moving to native ESM modules is --- please don't? :). 

More pragmatically, if you are going to make this switch please make sure you have a `require` based fallback that continues to work so folks using APM solutions have a path forward.

A few other things worth noting: 

First --- the CNCF's OpenTelemetry javascript project uses `require-in-the-middle` as well -- I've started a conversation on their gitter about their plans for a native ESM future and might bring it up at their [Javascript SDK SIG meeting](https://github.com/open-telemetry/community).  

Second --- it's my naive understanding that [the Loaders API](https://nodejs.org/api/esm.html#esm_loaders) provided by the Node.js might offer a path forward for instrumenting/hooking ESM modules.  I haven't personally looked too deeply into this and don't know of any general public research around whether ESM loaders are a suitable solution here.

**Comment by mcollina** [comment]
@astorm I would really like to see APM vendors more engaged with Node core, specifically on the parts that matters to them. Put in other words, if "your" product needs some functionality in Node core, you should help in implementing it. Node.js has no "BigCo" behind as it is a community effort as much as Fastify is. APMs should be part of the solution.

**Comment by astorm** [comment]
> I would really like to see APM vendors more engaged with Node core

You and me both @mcollina -- I'll pass that message on the product/engineering managers here and see if helps.  

Two questions regarding that -- one specific and one vague (maybe this isn't the right place for this?)

1. Specifically: If you had the ear of an APM vendor what's the best first/next step they could take to become more engaged with Node/the OpenJS Foundation in the ways you'd like to see?

2. Vague: Speaking on a more nuts and bolts engineering level: Node (like any platform programming language implementation) is a _complex_ project. Coming in as an outsider it can be hard to understand how all the moving pieces come together.  This is especially true for things an APM vendor might be concerned with.
 
   I've known folks who were interested in contributing more, but not having a good map of the territory kept them from engaging or believing they could make a difference.  The more you'all can do to make core Node.js friendly and approachable to the sorts of developers/programmers/engineers who might want to work on the core the better.  More videos/papers/tutorials like Joyee's [how node bootstraps itself](https://njsi2019.sched.com/event/T5G0/how-nodejs-bootstraps-itself-2019-edition-joyee-cheung-igalia) talk or Colin's [what even is a libuv](https://njsi2019.sched.com/event/T5G3/introduction-to-libuv-whats-a-unicorn-velociraptor-colin-ihrig-joyent) would go a long way towards attracting more talent to work on the core.

**Comment by delvedor** [comment]
I agree with @mcollina that APM support is essential, which means that v4 will continue to ship CJS.
There is still the problem about what to do when a dependency will move to ESM.

**Comment by mcollina** [comment]
> 1. Specifically: If you had the ear of an APM vendor what's the best first/next step they could take to become more engaged with Node/the OpenJS Foundation in the ways you'd like to see?

The best way would be to partecipate in the https://github.com/nodejs/diagnostics working group, and allocate time to work on problems in Node.js core. I recommend to open an issue there.

Regarding the issue at hand, consider digging into https://github.com/nodejs/node/issues/36954 https://github.com/nodejs/node/issues/36396 and https://github.com/nodejs/modules (for historical reasons). The current problem is hard because it intersects two "domains": modules and diagnostics. 

This will require some collaboration with other APM vendors to find a technical solution that fits your problems. Something new that came out recently is https://nodejs.org/api/diagnostics_channel.html.
 
> 2. Vague: Speaking on a more nuts and bolts engineering level: Node (like any platform programming language implementation) is a _complex_ project. Coming in as an outsider it can be hard to understand how all the moving pieces come together.  This is especially true for things an APM vendor might be concerned with.

Instrumentations is a _really hard topic_. It will require time and long-term investment, it's not just a one-off feature to add unfortunately. I worked in this topic for years, I know how hard this is. I would recommend studying how async_hooks, AsyncResource, AsyncLocalStorage work to begin with. Reach out to the Diagnostics WG.

**Comment by zekth** [comment]
Regarding typescript there is an issue openned at the moment : https://github.com/microsoft/TypeScript/issues/27957

**Comment by GeoffreyBooth** [comment]
> 1. Specifically: If you had the ear of an APM vendor what’s the best first/next step they could take to become more engaged with Node/the OpenJS Foundation in the ways you’d like to see?

Hi @astorm, I found this thread because it was linked from my thread at https://github.com/nodejs/node/issues/36396. I’m looking for help to get Node’s ESM loaders built out enough to support all important use cases, top of which is instrumentation. I wrote much of the existing loaders code, and I’m happy to coordinate efforts for working on it further; but I have two young children at home now so I no longer have the time to volunteer coding on it myself. If there’s enough interest we could spin up a new Node working group similar to the old Modules WG; I can also help with that.

So to directly answer your question: the first step would be to comment on that thread that you’re interested, along with anyone else from your company who might want to participate; and I can create a new thread or working group to gather together everyone who wants to be involved. Then we can schedule calls to walk people through existing code, discuss next steps, find consensuses on designs before anyone invests time coding, and divide up the work. There’s already a [TODO](https://github.com/nodejs/node/issues/36396#issue-757489834) list in the top post on that thread, which I think might already be enough of a plan for getting loaders close enough to the finish line to handle instrumentation; so at this point the effort mostly just needs volunteers to do the work.

**Comment by astorm** [comment]
Thanks @GeoffreyBooth -- that's useful context and exactly the sort of "next steps" prompt that folks could use.  I've [raised the issue](https://github.com/open-telemetry/opentelemetry-js/issues/1946) with the OpenTelementry project (CNCF foundation project with multiple APM vendors contributing) to see if there's any interest in working on this stuff. Cheers.

**Comment by Divlo** [comment]
> Is it? The answer I have been given is that _both_ are the future -- [nodejs/node#33954 (comment)](https://github.com/nodejs/node/issues/33954#issuecomment-776792555). I will agree that "ESM is the future" when core says they are deprecating CJS.

from @jsumners in https://github.com/fastify/fastify/issues/2847#issuecomment-777716242

In what way do you see CommonJS in the future ? Don't you think it is bad to maintain 2 things to do the same thing ?
I really think migrating gradually all `npm` packages to ESM is the right thing to do.
I will reverse your ask in this comment https://github.com/fastify/fastify/issues/2847#issuecomment-776713052

What benefit does this provide to use CommonJS instead of ESM ?
Of course in a future perspective, because currently lot of things still use CommonJS but hopefully everthing will migrate gradually.

**Comment by jsumners** [comment]
> What benefit does this provide to use CommonJS instead of ESM ?

At least several. A couple are ESM doesn't allow for intercepting dependencies to mock for testing and ESM has zero support for APM.

**Comment by Divlo** [comment]
> > What benefit does this provide to use CommonJS instead of ESM ?
> 
> At least several. A couple are ESM doesn't allow for intercepting dependencies to mock for testing and ESM has zero support for APM.

Valid points. 

I don't know what test framework are you using for `fastify` but `jest` has currently an open issue about mocking with ESM: https://github.com/facebook/jest/issues/10025 and I think most of the tests framework will provide a way to mock dependencies for testing.

**Comment by bitmage** [comment]
Here is a use case that I'm currently relying on CommonJS for:

```js
// helper to load all files in a directory/subdirectories
// we use sync because this is called during boot process,
// but NEVER use sync for something that is going to be called
// upon web requests
const klawSync = require('klaw-sync')
const forEachFileUnder = (path, fn) => {
  return klawSync(fastify.root(path), {
    nodir: true,
    filter: ({path}) => path.endsWith('.js'),
    traverseAll: true,
  })
    .map(({path}) => path)
    .map(fn)
}
fastify.decorate('forEachFileUnder', forEachFileUnder)

// load plugins
forEachFileUnder('plugins', (file) => require(file)(fastify))

// load routes
forEachFileUnder('routes', (file) => require(file)(fastify))
```

I suppose I could rely on a compilation step for this.  But I prefer *not* having the additional complexity of build tools on my server side code.  Being able to set up file structure conventions like this in my `index.js` gets me much of the productivity of an opinionated framework while still keeping my code concise and maintainable.

**Comment by mcollina** [comment]
closing this, it’s really premature still.

**Comment by ziimakc** [comment]
@mcollina do you think time has come?
