### ISSUE TITLE
Calling `reply.send` twice on validation error

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#2859]
Guys https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#schemaerrorformatter

This section recommends:
> You can also use setErrorHandler to define a custom response for validation errors such as
```js
fastify.setErrorHandler(function (error, request, reply) {
  if (error.validation) {
     reply.status(422).send(new Error('validation failed'))
  }
})
```
But in this case, we'll call the `reply.send` twice, it's not a bug/bad pattern?

The first call is under https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L90 when a validation error happens.

cc: @fastify/core

**Comment by mcollina** [comment]
I'm not sure I understand the problem. Calling `reply.send(error)` will trigger the error handler.

**Comment by RafaelGSS** [comment]
But, actually, it's called twice, the first one in the link above and the second inside `errorHandler`.

I mean, when a validation error happens the `replySent` is flagged to `true` ([here](https://github.com/fastify/fastify/blob/95bb21371c6db8df8e7ee568c3f073bb33cb08e4/lib/reply.js#L499)) and inside `setErrorHandler` callback we are calling the `reply.send` again. It shouldn't throw a `FST_ERR_REP_ALREADY_SENT` ? ref https://github.com/fastify/fastify/blob/master/lib/reply.js#L118

**Comment by sergiz** [comment]
kReplySent is then again set to false before error handler is invoked.
https://github.com/fastify/fastify/blob/95bb21371c6db8df8e7ee568c3f073bb33cb08e4/lib/reply.js#L534-L544

**Comment by RafaelGSS** [comment]
Yes, you right! @sergiz. 

cc: @zekth
