### ISSUE TITLE
Deep nested schemas are not getting resolved

### ISSUE THREAD

**Issue by MetCoder95** [fastify/fastify#2874]
## 🐛 Bug Report

Hi! When referencing Schemas that were defined one level up, I noticed that suddenly the deep nested Schemas were not able at all to lookup for the reference of the one level up ones. Throwing the following error:

`Failed building the validation schema for GET: /api/v1/bar/:id, due to error can't resolve reference someNestedSchema#/properties/state from id #`

The curious thing is that doesn't happen on all nested instances, but just in one specific.

## To Reproduce

This is how the schemas are organized:

`index.js`
```js
mainInstance.addSchema({
    $id: 'genericResponse',
    title: 'Some generic response',
    type: 'object',
    properties: {
    // some properties goes here
    },
});

// Let's register our V1 module
mainInstance.register(V1Module, {
    prefix: '/v1',
});
```

On one level deep, `v1/index.js`
```js
v1Instance.addSchema({
    $id: 'someNestedSchema',
    title: 'Some nested schema',
    type: 'object',
    properties: {
     // properties goes here
    },
 });

// Let's register our plugins
v1Instance.register(BarModule, {
    prefix: '/bar',
});

v1Instance.register(FooModule, {
    prefix: '/foo',
});
```

On a third and last level, `v1/bar/index.js` when declaring referencing the one level up the nested schema
```js
barInstance.get('/:id', { 
   schema: {
      body: {
      type: 'object',
      properties: {
        state: {
          $ref: 'someNestedSchema#/properties/state', // This will throw an error
        },
      },
    additionalProperties: false,
    minProperties: 1,
  }
}, handler);
```

The funniest thing is if I do the same for other deep instance at the same level, it works, for e.g. on `v1/foo/index.js`
```js
fooInstance.get('/:id', { 
   schema: {
      body: {
      type: 'object',
      properties: {
        state: {
          $ref: 'someNestedSchema#/properties/state', // This works!
        },
      },
    additionalProperties: false,
    minProperties: 1,
  }
}, handler);
```

A workaround that I found was, for the plugin that was failing, just setting `BarPlugin[Symbol.for('skip-override')] = true;` solve the issue at all, but now all the nested decorators that this plugin contains will pollute the scope of the instance one level up. For this example, the `v1` instance.

Also, if you try to see which schemas are defined within the fastify instances executing `barInstance.getSchemas()`, the upper level defined schemas will be shown as expected.

## Expected behavior

No error should be thrown and the deep level instances should be able to reach upper level defined schemas.

## Your Environment

- *node version*: 14
- *fastify version*: >=3.11.0
- *os*: Mac, Linux
- *any other relevant information*

## Note

I tried to see from the source code what was the issue but wasn't able to find it. Maybe I'm missing something, but I'll be more than happy to also help you fix the issue 🙂 (if there's one)

**Comment by mcollina** [comment]
Would you mind creating a runnable example?

**Comment by MetCoder95** [comment]
I'm trying to replicate my scenario using this example:

```js
const fastify = require('fastify');

const BarModule = (barInstance, options, done) => {
  barInstance.post(
    '/',
    {
      schema: {
        body: {
          type: 'object',
          properties: {
            state: {
              $ref: 'someNestedSchema#/properties/state', // This won't throw
            },
          },
          additionalProperties: false,
          minProperties: 1,
        },
        responses: {
          200: { $ref: 'mainSchema#' },
        },
      },
    },
    (req, reply, done) => reply.send({ hello: 'from bar' })
  );

  done();
};

const FooModule = (fooInstance, options, done) => {
  fooInstance.post(
    '/',
    {
      schema: {
        body: {
          type: 'object',
          properties: {
            state: {
              $ref: 'someNestedSchema#/properties/state', // This will throw an error
            },
          },
          additionalProperties: false,
          minProperties: 1,
        },
        responses: {
          200: { $ref: 'mainSchema#' },
        },
      },
    },
    (req, reply, done) => reply.send({ hello: 'from foo' })
  );

  done();
};

const V1Module = (v1Instance, options, done) => {
  v1Instance.addSchema({
    $id: 'someNestedSchema',
    title: 'Some nested schema',
    type: 'object',
    properties: {
      state: {
        type: 'string',
        enum: ['some-state'],
      },
    },
  });

  v1Instance.register(BarModule, { prefix: '/bar' });
  v1Instance.register(FooModule, { prefix: '/foo' });

  done();
};

const server = fastify();
server.addSchema({
  $id: 'mainSchema',
  title: 'Main schema',
  type: 'object',
  properties: {
    id: { type: 'integer' },
  },
});

server.register(V1Module, { prefix: '/api/v1' });

(async () => {
  await server.ready();

  console.log(
    { server: server.printRoutes(), schemas: server.getSchemas() },
    'Server built and ready to start listening'
  );

  await server.listen(3000);
})();

```

But being honest, I'm not able to do it. In my situation, the schemas are way bigger and with more properties. The main issue is that in this case, `FooModule` routes are not able to refer to an upper-level schema (e.g. from `V1` instance in this example).

So I assume there's some other thing happening

**Comment by mcollina** [comment]
That's often the case. It might also be a complex Fastify bug.. and recreating the problem is 80% of the work.

**Comment by MetCoder95** [comment]
And, to make it even weirder, the issue is gone after I upgraded to `v3.12.0` 😓 

I also notice that the issue was only happening when compiling the validation schema for the `body` property of the route's schema. Header, Params, and even responses were working correctly when referencing upper-level schemas.

Thanks for the support and feel free to close it as it seems it's solved. If I ever face the bug again, I'll update this issue 🙂

**Comment by mcollina** [comment]
This whole area was refactored in v3.12.0 to avoid some odd behaviors.

I think @Eomm would be very glad it fixed your problem!

**Comment by MetCoder95** [comment]
Oh, I didn't know that went out recently! That explains a lot! I was following PR really close, amazing work @Eomm 🙌
