### ISSUE TITLE
Incorrect schema type passed to FastifySchemaCompiler

### ISSUE THREAD

**Issue by evanshortiss** [fastify/fastify#2880]
## 🐛 Bug Report

When using a custom validation library (e.g Joi) it is necessary to pass `validatorCompiler` to the route definition. This function has the signature `(routeSchema: FastifyRouteSchemaDef) => FastifyValidationResult`. Because it uses a fixed `FastifyRouteSchemaDef` the typings are not correct when trying to run the validation.

## To Reproduce

```ts
import { FastifyPluginCallback, FastifyRequest } from 'fastify';
import Joi from 'joi'

const server = fastify({ logger: true });

type RBody = {
  name: string 
}
server.route({
  schema: {
      body: Joi.object().default({}).keys({
        name: Joi.string().required()
      })
  },
  validatorCompiler: ({ schema }) => {
    // Error: Property 'validate' does not exist on type 'FastifySchema'.
    return (data: any) => schema.validate(data)
  },
  method: 'POST',
  url: '/',
  handler: async (request: FastifyRequest<{ Body: RBody }>, reply) => {})
})
```

## Expected behavior

The `schema` passed to `validatorCompiler` should be correctly typed. Perhaps using a Generic?

```ts
server.route<
  RouteGenericInterface, ContextConfigDefault, Joi.Schema
>({
  schema: {
      body: Joi.object().default({}).keys({
        name: Joi.string().required()
      })
  },
  validatorCompiler: ({ schema }) => {
    // Error: Property 'validate' does not exist on type 'FastifySchema'.
    return (data: any) => schema.validate(data)
  },
  method: 'POST',
  url: '/',
  handler: async (request: FastifyRequest<{ Body: RBody }>, reply) => {})
})
```

## Your Environment

- *node version*: 14
- *fastify version*: >=3.9
- *os*: Mac

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by RafaelGSS** [comment]
Yes, `generic` sounds the solution here. Would you mind adding a PR to fix that?

**Comment by evanshortiss** [comment]
@RafaelGSS I'm happy to help with this too. LMK if you'd like a PR 👍

**Comment by RafaelGSS** [comment]
Sure thing!

**Comment by RafaelGSS** [comment]
We can follow the approach as @evanshortiss mentioned (generics) or you can just use the module augmentation for it. Any thoughts regarding it?

Module augmentation example

```ts
declare module 'fastify' {
  interface FastifySchema {
    validate?: (data: any) => any;
  }
}
server.route({
  schema: {
      body: Joi.object().default({}).keys({
        name: Joi.string().required()
      })
  },
  validatorCompiler: ({ schema }) => {
    return (data: any) => schema.validate(data)
  },
  method: 'POST',
  url: '/',
  handler: async (request: FastifyRequest<{ Body: RBody }>, reply) => {})
})
```

Generics:

```ts
server.route<
  RouteGenericInterface, ContextConfigDefault, Joi.Schema
>({
  schema: {
      body: Joi.object().default({}).keys({
        name: Joi.string().required()
      })
  },
  validatorCompiler: ({ schema }) => {
    return (data: any) => schema.validate(data)
  },
  method: 'POST',
  url: '/',
  handler: async (request: FastifyRequest<{ Body: RBody }>, reply) => {})
})
```

cc: @fastify/typescript 

I'm +1 in Generics

**Comment by evanshortiss** [comment]
@RafaelGSS 👍  to Generic approach since it does not modify global interfaces. Apologies for my delay engaging here - busy  work week! 

I had another idea after thinking about this. Maybe there's no need to add a generic to the Route?

WDYT about this sample code? I've tested it and it works with minor changes to types that you can [see in this commit](https://github.com/evanshortiss/fastify/commit/3cb576997e532e8e9d6e7c736fa4bb6535783f3a).

```ts
import fastify, { FastifyRequest, FastifySchemaCompiler } from 'fastify'
import Joi from 'joi'

const app = fastify({ logger: true })

type HelloBody = {
  name: string
}

const compiler: FastifySchemaCompiler<Joi.Schema> = (def) => {
  return (data: any) => def.schema.validate(data || {})
}
app.route({
  method: 'POST',
  url: '/hello',
  schema: {
    body: Joi.object({
      name: Joi.string().default('World')
    })
  },
  validatorCompiler: compiler,
  handler: (request: FastifyRequest<{ Body: HelloBody }>, reply) => {
    reply.send(`Hello, ${request.body.name}`)
  }
})

app.listen('3000')
```

There is possibly some gotchas here. Notice that in my commit I changed [FastifyRouteSchemaDef.schema](https://github.com/evanshortiss/fastify/commit/3cb576997e532e8e9d6e7c736fa4bb6535783f3a#diff-32016d9358c109c04531eccc7c3a8ee96683622d55a39a1ef92ddea1bd64395aR20), since passing `FastifySchema` as the `schema` type in `FastifyRouteSchemaDef` seems incorrect to me since the schema (i.e body, query, etc) has already been chosen by this time.

**Comment by evanshortiss** [comment]
I assume there'd need to be some default, e.g `T = SomeDefault`?

**Comment by evanshortiss** [comment]
Just looked at your PR. Seems ideal @RafaelGSS. Ignore my thoughts about not adding the generic to the overall Route!

**Comment by evanshortiss** [comment]
Closing since the PR was merged 🥳
