### ISSUE TITLE
Support RegExp for the addContentTypeParser API

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#2885]
## 🚀 Feature Proposal

Support `RegExp` for the `addContentTypeParser` API.

## Motivation

Currently, you need to add a new content type parser for each new content type you use. So you have to add 2 parsers if you use the content types `application/vnd.user+json` and `application/vnd.book+json`, even though both are valid JSON objects and could use the same content type parser. This could be possible if the `addContentTypeParser` API supported `RegExp` in addition to string values.

## Example

```javascript
fastify.addContentTypeParser(/s*\+json$/, { parseAs: "string" }, function (req, body, done) {
  try {
    var json = JSON.parse(body)
    done(null, json)
  } catch (err) {
    err.statusCode = 400
    done(err, undefined)
  }
})
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by matthyk** [comment]
Yes, I will send a PR as soon as I am done.

**Comment by matthyk** [comment]
@mcollina 
During the development of the feature, I noticed a strange behaviour, but I don't know if this is intentional or a bug.
Currently if you add the content type `application/jso`, it will be executed even though the content type `application/json` is set in the request. This is due to the use of the method `indexOf` in the [contentTypeParser](https://github.com/fastify/fastify/blob/4a22bb0b4e296ee78e2e4a466d94f360e3a3025b/lib/contentTypeParser.js#L86), which obviously finds the string `application/jso` in the string `application/json`.

**Comment by mcollina** [comment]
`application/jso` looks like a typo? Where does this happen?

**Comment by matthyk** [comment]
It was just an example to show the current behaviour of the contentTypeParser.
Another and more understandable example:

```javascript
const app: FastifyInstance = fastify( options );

app.addContentTypeParser( 'application/vnd.custom+xml', { parseAs: "string" }, (request, body, done) => {} )

app.addContentTypeParser( 'application/vnd.custom', { parseAs: "string" }, (request, body, done) => {} )
```
In this example the first contentTypeParser function will never be called, because the second one also matches the first content type. To achieve the desired behaviour the user have to make the `addContentTypeParser` calls in the right order.
Like this:

```javascript
const app: FastifyInstance = fastify( options );

app.addContentTypeParser( 'application/vnd.custom', { parseAs: "string" }, (request, body, done) => {} )

app.addContentTypeParser( 'application/vnd.custom+xml', { parseAs: "string" }, (request, body, done) => {} )
```

So my question is: Should we leave the responsibility to the user to call the API in the correct order or should Fastify take care of that?

**Comment by mcollina** [comment]
> So my question is: Should we leave the responsibility to the user to call the API in the correct order or should Fastify take care of that?

I think the responsibility is on the user.

**Comment by fox1t** [comment]
Is this behavior pointed out somewhere in the docs?

**Comment by matthyk** [comment]
Currently not. I will update the documentation accordingly since I need to change it anyway to add the regex support.
