### ISSUE TITLE
Docs: Sample code is invalid  in fastify.RequestGenericInterface (TypeScript Docs)

### ISSUE THREAD

**Issue by tobb422** [fastify/fastify#2887]
## 🐛 Bug Report
The following sample code did not work.
https://github.com/fastify/fastify/blob/4a22bb0b4e296ee78e2e4a466d94f360e3a3025b/docs/TypeScript.md#L720

I think it is probably one of the followings?
```typescript
type requestGeneric = {
  Querystring: {
    name: string
  }
}
```

```typescript
interface requestGeneric extends RequestGenericInterface {
  Querystring: {
    name: string
  }
}
```

**Comment by tobb422** [comment]
> yes I believe you're correct - would you like to send a PR fixing the example?

OK!
Is it better to use `type` or `interface`?

**Comment by Ethan-Arrowood** [comment]
Interface

**Comment by tobb422** [comment]
I've sent the following PR.
https://github.com/fastify/fastify/pull/2888
