### ISSUE TITLE
Take code coverage to 99%

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#289]
As titled.

**Comment by jsumners** [comment]
Do you consider this a 1.0.0 blocker?

**Comment by mcollina** [comment]
no.

**Comment by allevo** [comment]
I'll make a PR asap.

**Comment by Ethan-Arrowood** [comment]
If you have a specific part of the code that hasn't been covered I'd be interested in writing some unit tests for it.

**Comment by delvedor** [comment]
@Ethan-Arrowood  thanks you for checking out the project!
You can find [here](https://coveralls.io/github/fastify/fastify?branch=master) the coverage status of the master branch, it will also tell you which part of the code that are not covered by some tests :)

**Comment by Ethan-Arrowood** [comment]
Awesome, I'll see what I can come up with!

**Comment by Ethan-Arrowood** [comment]
Based on the [code coverage](https://coveralls.io/github/fastify/fastify?branch=master) site we have reached 99% coverage! 🎉

**Comment by mcollina** [comment]
I think we can close this :D.
