### ISSUE TITLE
Add fastify-schema-to-typescript to ecosystem

### ISSUE THREAD

**Issue by thomasthiebaud** [fastify/fastify#2897]
Hi team, 

I've been working on this tool to generate typescript types from a json schema. It allows to have types that match the validation schema.

Would it be possible to add it to the ecosystem? If no would it be possible to have some feedback to make it better

Here's the repo https://github.com/thomasthiebaud/fastify-schema-to-typescript

**Comment by mcollina** [comment]
Sure, go for it!
