### ISSUE TITLE
Generate TODO FIXME summary

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#290]
Should we add a script to summarize `TODO` and `FIXME` comments? I know almost any IDE has support for this but I think it would be useful to see the state with a simple command in the CLI.

e.g https://github.com/pgilad/leasot 

```bash
./index.js
  line 7  TODO  dedede

 × 1 todo/fixme found
```

**Comment by jsumners** [comment]
Is this in response to #266 having TODOs in it? I'm quite sure they are there because @mcollina is still working on the PR. Or have you seen other TODOs in the codebase?

**Comment by mcollina** [comment]
I don’t think there are plenty. I don’t think it’s worth automating a check right now, but feel free to open issues if there are.

I might ship #266 with some TODOs, because they are pretty harmless, and removing them might cause a big refactoring of find-my-way.

**Comment by StarpTech** [comment]
@jsumners yes
@mcollina ok that's fine for me then we should create an issue for any TODO / FIXME.
