### ISSUE TITLE
Add support for Fastify to Google Cloud Trace

### ISSUE THREAD

**Issue by simoneb** [fastify/fastify#2900]
## 🚀 Feature Proposal

Google Cloud Trace is Google's service for tracing similar to APM and NewRelic.

It currently [does not support Fastify](https://github.com/googleapis/cloud-trace-nodejs#what-gets-traced) but it [provides plugins for several Node modules already](https://github.com/googleapis/cloud-trace-nodejs/tree/master/src/plugins).

There is an [existing fastify plugin implementation](https://github.com/mkinoshi/fastify-gcloud-trace) but it doesn't seem to be actively maintained nor supporting v3 (there's an [open PR](https://github.com/mkinoshi/fastify-gcloud-trace/pull/19)).

In [ths issue](https://github.com/googleapis/cloud-trace-nodejs/issues/1167) it's mentioned that they don't plan adding support for more libraries but using open telemetry instead. There's already a request for that here https://github.com/open-telemetry/opentelemetry-js-contrib/issues/41.

Somebody has already implemented something for open telemetry https://github.com/autotelic/fastify-opentelemetry

**Comment by RafaelGSS** [comment]
I'm +1 on it.

**Comment by MetCoder95** [comment]
I would like to help on this, on my current org we had to do some workarounds to make it work with Fastify, would be really nice to bring some help here.

The plan should be to add a new plugin, isn't it?

**Comment by simoneb** [comment]
The first thing to do would be to check if any of the existing implementations can be used. There's a fastify plugin and an open telemetry integration linked in the issue description. If we figure out that those are good enough, there may be nothing to do here :)

**Comment by HW13** [comment]
There's a [GCP OpenTelemetry Cloud Trace Exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/tree/master/packages/opentelemetry-cloud-trace-exporter) and that can be used in conjunction with [@autotelic/fastify-opentelemetry](https://github.com/autotelic/fastify-opentelemetry) to provide automated route tracing - with all resulting traces visible on Google Cloud Trace.

```js
const { HttpTraceContext } = require('@opentelemetry/core')
const { AsyncHooksContextManager } = require('@opentelemetry/context-async-hooks')
const {
  BasicTracerProvider,
  SimpleSpanProcessor
} = require('@opentelemetry/tracing')
const { TraceExporter } = require('@google-cloud/opentelemetry-cloud-trace-exporter')

const provider = new BasicTracerProvider()

const gcpExporter = new TraceExporter({
  // If you are not in a GCP environment:
  keyFile: './service_account_key.json'
  // or:
  // credentials: {
  //   client_email: <EMAIL>,
  //   private_key: <KEY>
  // }
})

provider.addSpanProcessor(
  new SimpleSpanProcessor(gcpExporter)
)

provider.register({
  contextManager: new AsyncHooksContextManager(),
  propagator: new HttpTraceContext()
})

const fastify = require('fastify')
const fastifyOpentelemetry = require('@autotelic/fastify-opentelemetry')

const app = fastify()

app.register(fastifyOpentelemetry, { serviceName: 'my-app' })

// ...Add routes

app.listen(3000, () => {
  console.log('app listening on port 3000')
})

```

**Comment by simoneb** [comment]
That's great @HW13, thanks for that. Considering that there's a lot of setup involved, I wonder if it would be worth providing a higher level plugin for fastify, e.g. fastify-google-cloud-trace. Meanwhile I came across another plugin for fastify and Open Telemetry from the same author as fastify-gcloud-trace: https://github.com/mkinoshi/fastify-opentelemetry

**Comment by HW13** [comment]
OpenTelemetry will inevitably involve a bit of a setup (but it's totally worth it! 😄). 

Wrapping that setup in a higher level Fastify plugin wouldn't be ideal, as the OpenTelemetry SDK needs to be initialized before all other modules are loaded ([explained here](https://open-telemetry.github.io/opentelemetry-js/#initialize-the-sdk)). So there could be some inconsistent behaviour depending on when the plugin is loaded.

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/issues/2097

**Comment by MetCoder95** [comment]
Thanks for the help @HW13 didn't know about that 🙏 

Then, the best would be to leave it as it is?

Just out of curiosity, this is documented somewhere? I think would be nice to have a place to point that out when somebody faces a similar situation

**Comment by simoneb** [comment]
Looks like there are quite a few resources and tools to do this and there's no need to write a new plugin. Closing
