### ISSUE TITLE
Breaking change in typing for error

### ISSUE THREAD

**Issue by httpete** [fastify/fastify#2902]
In upgrading to the latest fastify, we see a change in the parameter type for err

From an object to a string. Was this intentional? 

## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/1200635/110139385-f561d180-7da0-11eb-842b-b8cbd56d9d6f.png)

## To Reproduce

```    server.log.error(err); ```

## Expected behavior

Typing to accept an err object as previous release did.

**Comment by mcollina** [comment]
cc @fastify/typescript.

I would also note that the quickst way to fix this is for you to send a PR.

Which version of Fastify were you using before this change?

**Comment by Ethan-Arrowood** [comment]
I'd have to look back at the commit history but I believe you might need to pass in the pino logger types in order to have complete typescript support for the logger

**Comment by zekth** [comment]
Pino and fastify types differs:

https://github.com/fastify/fastify/blob/efa77faeac506c0339c28a6708d42a0876d8e2d5/types/logger.d.ts#L28-L31

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts

Do you have https://www.npmjs.com/package/@types/pino in your project?

**Comment by httpete** [comment]
> Pino and fastify types differs (types ain't shipped in pino package, that's why we don't use them):
> 
> https://github.com/fastify/fastify/blob/efa77faeac506c0339c28a6708d42a0876d8e2d5/types/logger.d.ts#L28-L31
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts
> 
> Do you have https://www.npmjs.com/package/@types/pino in your project?

No I don't have pino. Sounds like I do?

**Comment by httpete** [comment]
> cc @fastify/typescript.
> 
> I would also note that the quickst way to fix this is for you to send a PR.
> 
> Which version of Fastify were you using before this change?

"fastify": "3.7.0" => "3.13.0"

**Comment by climba03003** [comment]
I think it break from #2626.
Which change the obj type from `object` to `Record<string, unknown>`.
`object` and `Record<string, unknown>` is not compatible from each another. `object` can receive nearly any types to pass in.


It should be valid for passing `Error` in `FastifyLogFn`.

**Comment by zekth** [comment]
typing should be `Record<string,unknown> | Error` as `Object` is prohibited. Thoughts @Ethan-Arrowood ?

**Comment by Ethan-Arrowood** [comment]
Ahh i see. Yes I'd prefer `Record<string, unknown>` since its meant to be a proper key/value object and not just a thing that implements object

**Comment by climba03003** [comment]
> 
> 
> Ahh i see. Yes I'd prefer `Record<string, unknown>` since its meant to be a proper key/value object and not just a thing that implements object

Shouldn't it better for using `unknown` for it? I think we should not restrict the user to pass in anything inside the logger and we actually do not block anything to passed inside it (no error, warning, docs, etc). If it strictly narrow the type for TypeScript user, it can have a lot of side-effect or issue about this.
e.g. Should we allow custom `class` to pass in?

**Comment by Ethan-Arrowood** [comment]
good point as well. I'm +1 for `unknown` or maybe something that enforces it at least implements toString if thats a thing possible with TS

**Comment by httpete** [comment]
Thank you - what release will this be in?

**Comment by RafaelGSS** [comment]
https://github.com/fastify/fastify/releases/tag/v3.14.0

**Comment by httpete** [comment]
verified - works perfectly after updating. Thank you.
