### ISSUE TITLE
Auto label PR

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#2906]
## 🚀 Feature Proposal

Add a GH Action that adds:

- the `documentation` label when an issue or PR has the `docs` string on the title or only the `docs/` folder has been edit
- the `typescript` label only when a PR changes the `type/` folder or `fastify.d.ts` file (should be possible with `paths-ignore`)

## Motivation

Better search tags/filter

**Comment by zekth** [comment]
+1 on this.
Also would be interesting to check for prefixes of issues / PRs ?

**Comment by Eomm** [comment]
> Also would be interesting to check for prefixes of issues / PRs ?

Yeah, I did not search if there is already an action for it
