### ISSUE TITLE
onSend hook

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#291]
@lucamaraschi do you have code written for `onSend`? If so, is it public? I'd like to see if I can get this feature added. It is a critical blocker for 1.0.0, as well as something I want to develop. So I'd like to help in any way that I can.

**Comment by mcollina** [comment]
I don't think @lucamaraschi will have time to work on this in the coming week.
If you want to start something, please do - I do not think there is any code written yet.

**Comment by jsumners** [comment]
I have already looked at it and I don't see how it is possible without some significant refactoring.

https://github.com/fastify/fastify/blob/master/lib/reply.js#L161 gets invoked without any context of the registered hooks (that I can see).

**Comment by mcollina** [comment]
I reached out to @lucamaraschi and he said he has some code done ans he will send a PR asap.

**Comment by jsumners** [comment]
Excellent.

**Comment by allevo** [comment]
I'm seeing there're no issues that link this one. Any updates?

**Comment by jsumners** [comment]
Closed by #330
