### ISSUE TITLE
Schema with key or id already exists error after upgrading to 3.12.0

### ISSUE THREAD

**Issue by madx** [fastify/fastify#2914]
## 💥 Regression Report

After having installed 3.12.0 my app stopped booting and this error popped up:

```
Error: schema with key or id "CircleEventShow" already exists
```

My schemas use arrays with `$ref` to reference other schemas and it seems they are fully expanded instead of only referenced, copying the `$id` field and causing this duplicate key or id error.

As per @Eomm request I am opening a new issue as this seems to be different from the error encountered in #2901.

My app is split into self-contained "route plugins" and I use `fastify.register` to load each endpoint. If not using `fastify.register` the code would constantly raise the schema error, even in versions prior to 3.12.0.

## Last working version

Worked up to version: 3.11.0

Stopped working in version: 3.12.0

## To Reproduce

```js
import fastify from "fastify"
import fastifyPlugin from "fastify-plugin"
import S from "fluent-json-schema"

const ShowSchema = S.object().id("ShowSchema").prop("name", S.string())
const ListSchema = S.array().id("ListSchema").items(S.ref("ShowSchema#"))

const app = fastify({
  logger: true,
})

app.addSchema(ListSchema)
app.addSchema(ShowSchema)

const defaultRouteOptions = {
  schema: { response: { 200: S.ref("ListSchema#") } },
}

app.register(
  async (app) => {
    app.get("/resource/", defaultRouteOptions, () => ({}))
  },
  { prefix: "/prefix1" }
)
app.register(
  async (app) => {
    app.get("/resource/", defaultRouteOptions, () => ({}))
  },
  { prefix: "/prefix2" }
)

try {
  await app.listen(4000)
} catch (err) {
  app.log.error(err)
  process.exit(1)
}
```

## Expected behavior

I expect my app to boot fine.

## Your Environment

- *node version*: 15.10.0
- *fastify version*: 3.12.0
- *os*: Linux

**Comment by mcollina** [comment]
Looks like a bug in the new schema handling layer. cc @Eomm @jsumners

**Comment by jsumners** [comment]
Simplified a bit:

```js
import fastify from "fastify";

const ShowSchema = {
  $id: "ShowSchema",
  type: "object",
  properties: {
    name: { type: "string" },
  },
};
const ListSchema = {
  $id: "ListSchema",
  type: "array",
  items: { $ref: "ShowSchema" },
};

const app = fastify({
  logger: true,
});

app.addSchema(ListSchema);
app.addSchema(ShowSchema);

const defaultRouteOptions = {
  schema: { response: { 200: { $ref: "ListSchema" } } },
};

app.register(
  async (app) => {
    app.get("/resource/", defaultRouteOptions, () => ({}));
  },
  { prefix: "/prefix1" }
);
app.register(
  async (app) => {
    app.get("/resource/", defaultRouteOptions, () => ({}));
  },
  { prefix: "/prefix2" }
);

try {
  await app.listen(4000);
} catch (err) {
  app.log.error(err);
  process.exit(1);
}
```

What seems to be happening is that the route validation schema is hitting the following path:

1. https://github.com/fastify/fastify/blob/180be34f266e9f38d0fe0456fc6c84b87f7fe898/lib/schema-controller.js#L88
2. https://github.com/fastify/fastify/blob/180be34f266e9f38d0fe0456fc6c84b87f7fe898/lib/schema-compilers.js#L20
3. https://github.com/fastify/fastify/blob/180be34f266e9f38d0fe0456fc6c84b87f7fe898/lib/schema-compilers.js#L48

What I don't understand is why the validator needs its own AJV instance? Or is it re-using the root AJV instance and trying to re-add the referenced schema again? @Eomm

**Comment by Eomm** [comment]
> What I don't understand is why the validator needs its own AJV instance? Or is it re-using the root AJV instance 

Yes, since there are not new schemas added in the child context (`app.register`) I would expect that the AJV instance is just the root one

> and trying to re-add the referenced schema again?

I'm investigating

**Comment by madx** [comment]
Thanks a lot :pray: :shipit:

**Comment by meerkat999** [comment]
Any solution for this? I had to downgrade to 3.11.0 to get it to work my code

**Comment by jsumners** [comment]
> Any solution for this? I had to downgrade to 3.11.0 to get it to work my code

Please open a new issue with a minimal reproduction.
