### ISSUE TITLE
Introducing Primordials to fastify

### ISSUE THREAD

**Issue by sharukhsharu** [fastify/fastify#2919]
## 🚀 Feature Proposal

Polluting the global Object has always been an issue for every http  frameworks i thought of  Introducing Primordials to solve the issue.

## Motivation

The implementation of Primordials in nodejs for the STL has made it more stable , i thought of implementing that to fastify 
i wish to  hear your thoughts  on this @mcollina @jsumners since this is  a major change , and the dependency factors has also need to be considered.
 

## Example

https://github.com/nodejs/node/blob/v15.10.0/lib/internal/per_context/primordials.js

**Comment by zekth** [comment]
We currently support Node 10 12 and 14. Primordials are still in dev release, adding a conditional statement on versions might unfortunately complexify the codebase and slows it down.

**Comment by sharukhsharu** [comment]
I guess it's a bit risky to introduce this now.

**Comment by mcollina** [comment]
Implementing primordials will remove the compatibility with Jest (because https://github.com/facebook/jest/issues/2549 and many others like it). I don't think this is a viable change right now.

I'm inclined to close this for now, waiting for to Jest stop replacing all the globals.

**Comment by sharukhsharu** [comment]
Sure

**Comment by jsumners** [comment]
I am not clear what this would solve.
