### ISSUE TITLE
Missing types for getDefaultJsonParser and defaultTextParser

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#2930]
## 🐛 Bug Report

When trying to access the default json parser oder default text parser via the `getDefaultJsonParser()` and `defaultTextParser()` methods the TypeScript compiler throws an error.

## To Reproduce

```js
const server: FastifyInstance = fastify()

// Error: Property 'getDefaultJsonParser' does not exist on type 'FastifyInstance'.
server.getDefaultJsonParser('ignore', 'ignore')
```

## Expected behavior

There should be typings for the two methods.

## Your Environment

- *node version*: 14
- *fastify version*: >=3.13.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by matthyk** [comment]
Yes, I will send a PR!
