### ISSUE TITLE
When throwing something that is not instanceof Error it is returned to the client with status 200

### ISSUE THREAD

**Issue by Prinzhorn** [fastify/fastify#2932]
## 🐛 Bug Report

Throwing anything that is not an `Error` will be consider a successful response.

## To Reproduce

`node index.js`

```js
'use strict'

const fastify = require('fastify')()

// Declare a route
fastify.get('/', (request, reply) => {
  throw { up: 1337 }
 
  // throw 1337

  // In this cases fastify will even switch from `application/json; charset=utf-8` to `text/plain; charset=utf-8`
  // throw 'up'
})

fastify.listen(3000, err => {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
})
```

`curl --include http://localhost:3000`

```
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 11
Date: Fri, 12 Mar 2021 17:32:15 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"up":1337}
```

## Expected behavior

I expect status 500 and treat it like any error. Maybe wrap thrown thing in an `Error`. Even if throwing non-errors is an anti-pattern, treating it as success is worse.

## Your Environment

- *node version*: v14.16.0
- *fastify version*: 3.14.0
- *os*: Ubuntu

**Comment by Prinzhorn** [comment]
Well, this seems just like a special case of #2860

**Comment by jsumners** [comment]
You shouldn't throw anything that isn't an `Error`.
