### ISSUE TITLE
Basic auth never replies

### ISSUE THREAD

**Issue by Kinrany** [fastify/fastify#2936]
## 🐛 Bug Report

Hello world with `fastify` and `fastify-basic-auth` fails to respond with 200, 500, or even close connection.

## To Reproduce

Clean reproduction: https://github.com/Kinrany/fastify-basic-auth-bug-repro

Main part:

```js
const Fastify = require('fastify');
const basicAuth = require('fastify-basic-auth');

const app = Fastify();

app.register(basicAuth, {
  authenticate: { realm: 'Realm' },
  validate: (username, password) => {
    if (username !== 'user' || password !== 'password') {
      throw new Error('Unauthorized');
    }
  },
});

app.after(() => {
  app.get('/auth', {
    onRequest: app.basicAuth,
    handler: async () => 'OK\n',
  });
});

app.listen(3000);
```

## Expected behavior

App should reply with 200.

If there's a critical error in the basicAuth module, it should reply with 500.

## Your Environment

- *node version*: 14.16.0
- *fastify version*: 3.14.0
- *os*: Windows with WSL
- *fastify-basic-auth version*: 1.0.1

**Comment by Kinrany** [comment]
This is actually two bugs: one in `fastify-basic-auth` that makes it ignore the request, and another in `fastify` itself that allows this behavior. Not sure it makes sense to have two issues.

**Comment by mcollina** [comment]
You forgot `async` (or callback) in the hook.

```
const Fastify = require('fastify');
const basicAuth = require('fastify-basic-auth');

const app = Fastify();

app.register(basicAuth, {
  authenticate: { realm: 'Realm' },
  validate: async (username, password) => {
    if (username !== 'user' || password !== 'password') {
      throw new Error('Unauthorized');
    }
  },
});

app.after(() => {
  app.get('/auth', {
    onRequest: app.basicAuth,
    handler: async () => 'OK\n',
  });
});

app.listen(3000);
```

**Comment by Kinrany** [comment]
I see, thank you!
