### ISSUE TITLE
Route Methods are showing as `undefined` with `printRoutes()` for fastify > 3.12.0

### ISSUE THREAD

**Issue by initplatform** [fastify/fastify#2938]
## 🐛 Bug Report

Route Methods are showing as `undefined` with `printRoutes()` for fastify > 3.12.0 and node v14.15.4

## To Reproduce

I've created a sample repo to illustrate the issue -> https://github.com/initplatform/fastify-route-method-undefined

You can follow the readme there, but when building and running with fastify@3.12.0 the routes look like:

```bash
└── /
    ├── /
    ├── * (OPTIONS)
    └── health-
        ├── a/health (GET)
        ├── b/health (GET)
```

and with fastify@3.14.0 the routes are:

```bash
└── /
    ├── /
    ├── * (OPTIONS)
    └── health-
        ├── a/health (undefined)
        └── b/health (GET)
```

## Your Environment

- *node version*: v14.15.4
- *fastify version*: >=3.12.0
- *os*: Mac

**Comment by Eomm** [comment]
Good catch! https://runkit.com/embed/7anf0n77d5z9

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
Good spot! I think it's a bug in find-my-way. Would you like to send a PR there?

cc @delvedor

**Comment by ankitverma2211** [comment]
hey I would like to take this issue up and see if this can be my first contribution to open source .  Would need some help though .

 @mcollina

**Comment by RafaelGSS** [comment]
hey @ankitverma2211. This issue is being resolved in https://github.com/delvedor/find-my-way/pull/184. But, feel free to take another issue if you want! 

If you need some help, open a draft PR with what you have done and let us help you. See: https://www.fastify.io/contribute/

**Comment by mcollina** [comment]
This shipped in find-my-way, update your dependencies.
