### ISSUE TITLE
Ensure consistent fastify plugin quality

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#294]
We should provide a standard in quality.

- Travis (CI)
 - AppVeyor (Windows)
-  Code linter (standard)
- Pre-commit hook
- Documentation in readme
- License
- Code coverage report (__Lots of packages missing this__)

CI is missing here:
- [ ] https://github.com/fastify/fastify-cookie
  -  Add CI
- [ ] https://github.com/fastify/fastify-formbody
  -  Add CI
- [ ] https://github.com/fastify/fastify-bearer-auth
  -  Add CI

Perhaps we should document this set.

**Comment by jsumners** [comment]
Can you provide a reason to implement CI other than to say it's implemented on those plugins?

**Comment by StarpTech** [comment]
For a meaningful signal to all visitors that this plugin

- works on Windows
- works on Linux
- that the functionality is checked continuously
- provide a isolated test environment

**Comment by jsumners** [comment]
How does adding show something works on Windows?

I'm not diametrically opposed to the idea. I just don't think it is worth the time and effort on such small projects. `fastify-cookie` and `fastify-formbody` are single functions, and `fastify-bearer-auth` is a single function with an enclosed function (i.e. two functions). These are not complicated projects.

**Comment by StarpTech** [comment]
AppVeyor is a CI which runs on windows. In my opinion it doesn't matter how big a project is. Continues Integration is always a big friend and travis is very easy to setup.

**Comment by mcollina** [comment]
Setting up and maintaining AppVeyor integration takes time. I agree with @jsumners that if the module is small, there is no need. If by any chance somebody reports a bug that is Windows-specific, we can add them as needed.

**Comment by StarpTech** [comment]
I think that's your first impression @mcollina. When the template is created it's a job of 5 minutes. When an issue occurs it's too late :) especially when the most people are using a unix system.

**Comment by mcollina** [comment]
I do not think it should be a requirement. However, let’s put it as a nice to have. Same as for code coverage tracking. It’s a nice to have.

I want to be as lax as possible, while still providing good quality. Mysef or @delvedor have been reviewing all modules in the Readme.

I would argue that most of the production deployment are Linux-based, and bugs in development are less critical.

Travis is needed everywhere, because then we can enable greenkeeper: it will notify us if a new version of fastify or its dependency are breaking them. It’s a goos service for our framework (as we are still changing stuff).

**Comment by StarpTech** [comment]
ok, let's define this as a reference for a great setup without to enforce something.

**Comment by jsumners** [comment]
Over in Pino land we have a (incomplete) template repository for transports -- https://github.com/pinojs/pino-sapling

Feel free to create one for Fastify.

**Comment by mcollina** [comment]
I think we should codify this. Anyone willing to do a draft?

**Comment by delvedor** [comment]
Closed by #774.
