### ISSUE TITLE
The prefixTrailingSlash option "both" doesn't work.

### ISSUE THREAD

**Issue by SamuelBartik** [fastify/fastify#2943]
## 🐛 Bug Report

According to the [docs](https://www.fastify.io/docs/latest/Routes/#routes-option), setting` prefixTrailingSlash` option to `"both"` on a route should register two routes - one with and another without trailing slash. However this isn't the behaviour I have experienced. It literally matches the path specified in the first argument to `fastify.get` method. In my case, the route with trailing slash doesn't get recognized.

Setting `ignoreTrailingSlash: true` on the main fastify instance did work though.

## To Reproduce

To reproduce, run this snippet with fastify version 3.14.0.

```js
const fastify = require('fastify')();

fastify.get("/", async () => "Homepage!");
fastify.get("/route", { prefixTrailingSlash: "both" }, async () => "This is another route.");

fastify.listen(3000);
```

## Expected behavior

Visiting route `/route/` shouldn't return a 404 page.

## Your Environment

- *node version*: 14.16.0
- *fastify version*: >=3.14.0
- *os*: Windows

**Comment by AyoubElk** [comment]
My understanding is that the option `prefixTrailingSlash` is used for route prefixing.

You should read the following section: https://www.fastify.io/docs/latest/Routes/#route-prefixing

You can accomplish the behavior you want by using `ignoreTrailingSlash` option when instanciating Fastify:

```js
const fastify = require('.')({ ignoreTrailingSlash: true })

fastify.get('/', async () => 'Homepage!')
fastify.get('/route', { prefixTrailingSlash: 'both' }, async () => 'This is another route.')
fastify.listen(3000)

```

**Comment by SamuelBartik** [comment]
Thank you very much for your response! I've misunderstood the docs. Closing the issue.

**Comment by slavafomin** [comment]
This option got me confused as well. I believe the documentation should be updated to be more clear regarding this feature.
