### ISSUE TITLE
Docs(contributing): clarification on sort order

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#2949]
## 🐛 Bug Report

Under [onboarding-collaborators](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md#onboarding-collaborators) in `CONTRIBUTING.md` it states:

> The members lists are sorted alphabetically; make sure to add your name in the proper order.

Should they be sorted alphabetically ascending or descending, and on first name or surname?

**Comment by mcollina** [comment]
Surname, descending.

**Comment by jsumners** [comment]
It follows the traditional manner of alphabetical order when writing names in English. https://blogs.transparent.com/english/english-alphabetizing-rules/
