### ISSUE TITLE
Rethinking for docs

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#296]
I'm bit worried about our documentation.
The documentation is the second thing the developers look at: we need to be clear!

From my point of view, we have mixed the classic "Getting started" documentation with the classic "API Reference": some piece of documentation is written for learning `fastify` (like Middleware); other to list the options (like Server Method); other a mixin (like Reply).
This is a mess.

Thoughts?

I'd like that this issue should block the release version `1.0.0`

**Comment by jsumners** [comment]
I totally agree. I started working on at least fixing up grammar a few days ago, but I am super busy lately and haven't had time to complete it. Hopefully I can find some time this week.

**Comment by allevo** [comment]
@jsumners  Me too, I've no time for this.
But can we plan how to structure the docs?

**Comment by jsumners** [comment]
One method would be how I refactored Pino's documentation -- https://github.com/pinojs/pino

I see Readme documents as introductions. They should not be the reference documentation for a large project. So I broke it up into parts, but made one big "jsdoc style" API document -- https://github.com/pinojs/pino/blob/master/docs/API.md . This gave us several documents, all linked from the Readme, that describe things with examples and a single place to go to for the gritty details.

**Comment by mcollina** [comment]
Our current docs are working, even if they are far from ideal! 

I’m +1 on waiting for this to be solved. What we did for pino worked well.

**Comment by gj** [comment]
I'm fixing up grammar and spelling issues as I come across them, but I agree with the sentiment that a general rethinking is in order.

Fastify's an outstanding framework, and I love its performance-first priorities. However, I've had to consult the source code a few times to debug misunderstandings that should ideally be covered in the docs.

Love the idea of a split between a set of introductory, 'getting started'-style docs with trivial examples and a comprehensive API spec.

**Comment by delvedor** [comment]
> Fastify's an outstanding framework, and I love its performance-first priorities. However, I've had to consult the source code a few times to debug misunderstandings that should ideally be covered in the docs.

@gj thank you! :)
If I may, what misunderstandings you had to debug by digging inside the code?

**Comment by gj** [comment]
@delvedor Getting WebSockets working is the main thing that springs to mind. The `fastify-websocket` package is... slightly under-documented, haha. I was migrating from Express, where I'd been using the basic `ws` library. I eventually got the same implementation hooked up with Fastify, but it just took me a little while to realize that Fastify's HTTP server lives in the `fastify.server` property. 😄

**Comment by delvedor** [comment]
Thank you! We should definitely document better that part, you are not the first one that need an easy socket support. Maybe we could add a plugin also for `ws`.

**Comment by gj** [comment]
@delvedor Forgive my ignorance, but what's the need for a plugin? `ws` integrated seamlessly with Fastify (after I figured out the `.server` location, haha), and I'm not sure fallbacks are worth the additional dependencies / performance hit when >94% of browsers support web sockets.

Maybe we should take this discussion to [`fastify-websocket`](https://github.com/fastify/fastify-websocket). 🙂

**Comment by delvedor** [comment]
@gj potentially you can do everything without a plugin, Fastify is very flexible.
The idea of releasing it as a plugin is that you will not need to redo that work in the future, or help newcomers that have not a deep knowledge of the framework apis :)

**Comment by gj** [comment]
@delvedor Let me know what you think: https://github.com/gj/fastify-ws

**Comment by yamalight** [comment]
Just my two cents: I think the current docs are fine for the most part (with exception of some missing API bits that need to be filled out as we found out in the other tickets, e.g. `.after()`). 
I'd say they need one things to be great - general guide to fastify. You currently have an amazing guide for plugins, but something similar for fastify is missing. So if I want to find out how to do X, I most of the time have to go look and existing packages and their docs to figure out if I can do that at all. Having that knowledge centralized (at least for core plugins) would be amazing.

**Comment by jsumners** [comment]
Can you clarify with some examples?

**Comment by yamalight** [comment]
@jsumners I was thinking about something similar to [hapi's tutorials](https://hapijs.com/tutorials). And now that I'm looking at getting started - I think it should be enough to just extend it with a few small things  🤔

**Comment by Ethan-Arrowood** [comment]
One thing I came across recently is serving static files with Fastify. Took me too long to find `fastify-static`. For at least this topic there should be something on the getting started or API documentation page so when users search for "serve static files with Fastify" they get a good detailed guide how to.

**Comment by jsumners** [comment]
Hapi does have some excellent tutorials. But their actual documentation is not a format I would recommend (or support).

**Comment by yamalight** [comment]
@jsumners I do like fastify docs better, but hapi tutorials part is something that I'd love to see in fastify (that'd also eliminate quite a lot of common questions IMO)

**Comment by cemremengu** [comment]
Closing this one since I think docs are much better at the moment. Feel free to reopen or start a new discussion for further improvement ideas.
