### ISSUE TITLE
In "Getting Started" documentation broken link to https://www.fastify.io/docs/latest/Ecosystem

### ISSUE THREAD

**Issue by bervol** [fastify/fastify#2962]
Hi.

On the page https://www.fastify.io/docs/latest/Getting-Started/#extend-your-server the link to the page https://www.fastify.io/docs/latest/Ecosystem is not working.
It is found in this sentence:

> In other words, Fastify is not a "batteries included" framework, and relies on an amazing ecosystem!

Greetings
Bernhard

**Comment by mcollina** [comment]
Thanks for reporting Bernard! Would you like to send a PR to amend the docs?

**Comment by makuzaverite** [comment]
Let me take on this one

**Comment by climba03003** [comment]
Resolved by https://github.com/fastify/website/pull/250
@mcollina Can you help me to close this issue when you have time? Thanks.
