### ISSUE TITLE
HTTP POST/PUT without request body

### ISSUE THREAD

**Issue by dreamzoner** [fastify/fastify#297]
I would like to send a HTTP POST/PUT **without** request body to fastify server however I keep getting "415 Unsupported Media Type". The only workaround I have discovered is to put an empty json object in the request body. Can anyone shed some light on this?

**Comment by jsumners** [comment]
Did you register a content type handler? https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md

**Comment by StarpTech** [comment]
Hi @dreamzoner in general, you would need parser for `application/x-www-form-urlencoded` or `multipart/form-data` but if your call is `Idempotent` you can use `DELETE`  it does not expect a payload.

**Comment by allevo** [comment]
This *may* be a bug. Which behaiour should be kept if I make a request without `Content-type` and with `Content-length: 0` headers?

The [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) is filled with *SHOULD*. So it depends if we want to be full compliant to the RFC or not.

**Comment by StarpTech** [comment]
Since fastify only understand JSON by default it's correct behavior because empty body is invalid json payload.

**Comment by mcollina** [comment]
The problem lies in https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L28.
If there is no content-type, we return (correctly)  a 415, because we do not know how to parse that stuff. We might want to change this, it's pretty opinionated but it is correct: the application do not know what to do with that payload.

If there is no content-type and no content-length, _then_ we have a bug. There is no body to parse, but we might still want to pass it through. 

We might want to add a default content-type parser for "text/plain", if we don't have it already.

**Comment by delvedor** [comment]
> We might want to add a default content-type parser for "text/plain", if we don't have it already.

Agree.

**Comment by delvedor** [comment]
Hi @futurist! You have just found a bug :P
If you do:
```js
fastify.addContentTypeParser('application/jsoff', function (req, done) {
  var data = ''
  req.on('data', chunk => { data += chunk })
  req.on('end', () => {
    done(JSON.parse(data))
  })
})

fastify.addContentTypeParser('', function (req, done) {
  var data = ''
  req.on('data', chunk => { data += chunk })
  req.on('end', () => {
    done(data)
  })
})
```
The content type `application/jsoff` will work, but if you declare the `application/jsoff` after the empty string, `application/jsoff` will not work anymore.

I agree that we should not allow the use of an *empty string* content type parser.
I'll fix this soon.

**Comment by futurist** [comment]
I really want fastify can handle empty content type, that just return raw body string AS IS, I just use fastify hours ago, but found the content-type problem is a big confuse to me.

Is it possible to handle `empty string` just like `text/plain`? Think in browser, if a server don't know what's the `mime-type`, just return raw text. For upload data, if lost content-type, can we handle a similar way?

That way server will always get the data from user, and can decide what to do next.

**Comment by delvedor** [comment]
We could add a *catch all* content type parser, that should fix what you are proposing, something like:
```js
fastify.addContentTypeParser('*', function (req, done) {
  var data = ''
  req.on('data', chunk => { data += chunk })
  req.on('end', () => {
    done(data)
  })
})
```
That would work like the router, if there is a content type parser it will use that, otherwise the *catch all* will get that request. What do you think?
cc @mcollina

**Comment by futurist** [comment]
That way the content-type can extended with [glob](https://github.com/isaacs/node-glob) like? not just empty content-type, but also strings like `application/*`, `*/json`, `*/*` etc? Or just using RegExp as first argument? Like `express route` does.

**Comment by mcollina** [comment]
I would like to restrain in adding regexp-matching capabilities here. Those are very costly in term of performance. I think supporting a _catch all_ content type parser should provide the capability to implement regexp support in a module.

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
