### ISSUE TITLE
Review plugin list and move it to the docs

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#299]
The plugin list is becoming more crowded, and I think we should refactor it. I’ll like to divide it into two parts: core plugins (that we maintain), and ecosystem plugins (that are not part of the org).

Maybe we can divide them by functionality instead, and use another differentiator for the ones that we maintain directly.

**Comment by jsumners** [comment]
As I mentioned before, I think categorizing the list is the way to go. I just couldn't think of catergories for many of them.

**Comment by mcollina** [comment]
👍  for categorizing them.

**Comment by delvedor** [comment]
👍 for categorizing them, then we can just add `community` or `core` tag.

**Comment by Cameron-C-Chapman** [comment]
Is this issue ok to close or is there an idea that the categorization of the plugins should go a little further than just core and community?

I see @mcollina had a question out on #384 about a possible issue with the website but I don't see an issue with the website unless I'm missing something.

**Comment by mcollina** [comment]
the website was not building correctly, it’s fixed now

**Comment by delvedor** [comment]
Closed by https://github.com/fastify/fastify/pull/384.
