### ISSUE TITLE
catch-all addContentTypeParser doesn't fire if no content-type header in request

### ISSUE THREAD

**Issue by cmawhorter** [fastify/fastify#2994]
## 🐛 Bug Report

Docs state `addContentTypeParser('*', ...` is a catch all to "catch all requests regardless of their content type" but the handler is not called if the request does not have a content-type header.  

Additionally, the catch-all does not fire for application/json because of the built-in parser. That makes sense, but I don't see a `removeContentTypeParser` or way to clear all existing parser.

## To Reproduce

```ts
import fastify, { FastifyReply } from 'fastify';

const port = 8000;
const server = fastify();

server.post('/echo', async (request, reply) => {
  console.log('content-type', request.headers['content-type']);
  console.log('request.body', request.body);
  reply.status(200);
  reply.send(request.body);
});

server.addContentTypeParser('*', (req, payload, done) => {
  console.log('catch all parser entered');
  done();
});
```

```sh
# catch-all parser not hit because content-type not sent 
# (on my machine curl won't send content-type if no data sent.  ymmv)
curl -X POST http://localhost:28588/echo 

# catch-all parser hit and works as expected
curl -H 'content-type:whatever' -X POST -d '{}' http://localhost:28588/echo

# catch-all not hit because built-in json parser handles the request (expected)
curl -X POST -H 'content-type:application/json' -d '{}' http://localhost:28588/echo
```

## Expected behavior

- Catch-all should be called even when there is no content type
- Additionally, it should be possible to remove or clear default parsers
- And the docs should probably be changed to "catch all requests if no other matching parser exists" or something.  I knew what it meant but if taken literally it's not doing what it says

## Your Environment

- *node version*: 12.20.2
- *fastify version*: 3.14.2
- *os*: Mac

I'm trying to always get the request body as a buffer.  #707 was about that and the recommendation was to use a plugin. I couldn't get it to work probably because of what I outlined above.

**Comment by matthyk** [comment]
The behavior that the catch all content type parser is not executed if no request payload is sent should be correct. Nothing can be parsed that does not exist.

**Comment by matthyk** [comment]
The behaviour that the catch all content type parser is not executed if no request payload is sent should be correct. Nothing can be parsed that does not exist. 

The third case with the content type `application/json` is weird and in my opinion is actually unwanted behavior that is due to the current implementation of the content type parser. I have also tested this case with Fastify version 3.13.0 where there was no Regex support. This is relevant because for the regex support the logic in the content type parser was partially changed. But with this version you get the same behavior. 
Currently it tries to find an exact matching content type parser before running the catch all parser. I think it should always run the catch all content type parser when it has been registered

**Comment by cmawhorter** [comment]
You're right about 1. Curl user error.  I changed to `curl -X POST -H 'content-type:' -d '{}' http://...` and it's working as expected, so no bug report is invalid.

@mcollina FWIW, I posted in 707 for two reasons -- because that is the top result and linked by everything when googling "fastify raw body", and second because I thought it was closed premature and wanted to trigger a discussion.  I'm just trying to make what I consider the best node web server better like everyone else here.

**Comment by mcollina** [comment]
If you want to override the default JSON parser, you can add another JSON content type parser.

An API to remove existing content type parser would be good. Currently the JSON parser is hardcoded but I think it can be refactored without losing much throughput.

Would you like to work on this?

**Comment by matthyk** [comment]
I will work on this 👍

**Comment by syuilo** [comment]
> The behaviour that the catch all content type parser is not executed if no request payload is sent should be correct. Nothing can be parsed that does not exist.

Some clients may send requests without content-type (JavaScript fetch also creates requests without explicit content-type by default, even if JSON is included in the body).
Other libraries such as express, koa, etc. can fall back and handle such requests.
Is this not possible with fastify?

**Comment by climba03003** [comment]
> JavaScript fetch also creates requests without explicit content-type by default, even if JSON is included in the body

I don't understand what you means by `JavaScript fetch`. However, it should contain types if you pass a proper `string` or `object`. For example, `string` would be `text/plain;charset=UTF-8`, `FormData` would be `multipart/form-data; boundary=`, `URLSearchParams` would be `application/x-www-form-urlencoded;charset=UTF-8`.

https://fetch.spec.whatwg.org/#bodyinit-unions
