### ISSUE TITLE
test: auto generate test certificate

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#2998]
## 🚀 Feature Proposal

Move the current static test certification to auto generate before the test start.
https://github.com/fastify/fastify/blob/main/test/https/fastify.cert
https://github.com/fastify/fastify/blob/main/test/https/fastify.key

## Motivation

It can reduce the `false-positive` warning from security scanner.

**Comment by makuzaverite** [comment]
How to go about this one?

**Comment by climba03003** [comment]
@makuzaverite 
Read More: 
https://node-tap.org/docs/api/test-lifecycle-events/#tbeforefn
You can use the life-cycle of `tap` to generate the `keypair` before the test.

https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
Generate `keypair` by `crypto`.

**Comment by jsumners** [comment]
FWIW, this is one of the simplest ways I've managed to create compatible certificates -- https://github.com/jsumners/self-cert
