### ISSUE TITLE
support templates

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#30]
Something like http://npm.im/vision, that provides plugin-specific views.

**Comment by delvedor** [comment]
Good idea!
Maybe we can use the same syntax of Hapi and expose `reply.view` :)

**Comment by jsumners** [comment]
I'm an avid user of Hapi. I do not care for Hapi's template implementation. It's too rigid and does not promote streaming; even when set to `async`. I usually skip Hapi's template support completely and directly use [Marko](http://github.com/marko-js/marko):

```js
// using Marko's `require` extension
const myTemplate = require('./path/to/template.marko')

const getRoute = {
  path: '/',
  method: 'GET',
  handler (req, reply) {
    return reply(myTemplate.stream())
  }
}
```

**Comment by delvedor** [comment]
https://github.com/fastify/point-of-view
