### ISSUE TITLE
Route middleware not working

### ISSUE THREAD

**Issue by rupamking1** [fastify/fastify#3001]
app.post('/login_group', function (err, req, reply, next) {
  console.log('req.query');
  console.log('req.params');
  next();
}, async function (req, reply) {

});

error

I know about global middleware using app.register but I want separate middleware for each post route

**Comment by mcollina** [comment]
You can implement this using https://www.fastify.io/docs/latest/Hooks/#onrequest and the `onRequest` hook on the route definition: https://www.fastify.io/docs/latest/Routes/#routes-option.

Something like:

```js
app.post('/login_group', {
  async onRequest (req, reply) {
    console.log('req.query');
    console.log('req.params');
  }
}, async function (req, reply) {

});
```
