### ISSUE TITLE
Add prototype poisoning doc to documentation

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#3003]
https://github.com/fastify/fastify/issues/1426#issuecomment-817957913

**Comment by simoneb** [comment]
anybody working on this?

**Comment by mcollina** [comment]
I don't think so

**Comment by jsumners** [comment]
I will now that we have guides support.

**Comment by nuragic** [comment]
For some reason this issue is still opened but it should have been closed by the mentioned PR 🤔
