### ISSUE TITLE
Docs: Database integration concepts

### ISSUE THREAD

**Issue by ruheni** [fastify/fastify#3005]
## 🚀 Feature Proposal

Hello friends 👋🏾
I think it would be valuable to have a section on the docs covering database integration.
This would cover tools and libraries such as knexjs, Sequelize, TypeORM, Mikro-orm, Prisma etc. 

## Inspiration

[Nest Docs](https://docs.nestjs.com/techniques/database)

**Comment by mcollina** [comment]
I think this would be really handy. I would recommend focusing on the barebone adapters we support inside the org first.

My only question is if it is worthwhile having this content here or inside https://github.com/fastify/website.

I guess having a "guides" folder would be amazing (see https://github.com/fastify/fastify/pull/2610).

Anyway, would you be up to update https://github.com/fastify/website as well?

cc @lmammino

**Comment by ruheni** [comment]
"Guides" seem like a better fit for this. This would be a great section for featuring tutorials, videos, and other community content. 🙂

Created an issue on the website repo as requested: [https://github.com/fastify/website/issues/251](https://github.com/fastify/website/issues/251)

**Comment by Eomm** [comment]
Closing

The discussion continues on https://github.com/fastify/fastify/issues/3562
