### ISSUE TITLE
docs: table of content on Server.md

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3010]
## 🚀 Feature Proposal

Add a table of content on the https://github.com/fastify/fastify/blob/main/docs/Server.md page

## Motivation

Ease the navigation and understand how it is organized the page

## Example

On the site, it is difficult to understand what are the server methods and the server options:

![image](https://user-images.githubusercontent.com/11404065/115127806-cebacb80-9fd9-11eb-9066-cf6bd92dac04.png)

**Comment by mcollina** [comment]
Go for it!

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by mcollina** [comment]
Sure, use https://github.com/fastify/fastify/pull/3055 as the basis and solve the review comment.

**Comment by Eomm** [comment]
Done https://www.fastify.io/docs/latest/Reference/Server/#server-methods
