### ISSUE TITLE
Typescript types for `setValidatorCompiler` mismatches with Ajv version > 8.0.0

### ISSUE THREAD

**Issue by J3573R** [fastify/fastify#3025]
## 🐛 Bug Report

With latest Ajv version typescript typing is no longer working when setting ajv instance as schema validator. Tested with code samples from the README.

## To Reproduce

```js
import Fastify from "fastify";
import Ajv from "ajv";

const fastify = Fastify();

const ajv = new Ajv({
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: 'array',
  allErrors: true
})

fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schema)
})
```
Typescript compiler gives following error:
```
src/fastify.ts:13:30 - error TS2345: Argument of type '({ schema }: FastifyRouteSchemaDef<FastifySchema>) => ValidateFunction<unknown>' is not assignable to parameter of type 'FastifySchemaCompiler<FastifySchema>'.
  Call signature return types 'ValidateFunction<unknown>' and 'FastifyValidationResult' are incompatible.
    The types of 'errors' are incompatible between these types.
      Type 'ErrorObject<string, Record<string, any>, unknown>[] | null | undefined' is not assignable to type 'FastifySchemaValidationError[] | null | undefined'.
        Type 'ErrorObject<string, Record<string, any>, unknown>[]' is not assignable to type 'FastifySchemaValidationError[]'.
          Property 'dataPath' is missing in type 'ErrorObject<string, Record<string, any>, unknown>' but required in type 'FastifySchemaValidationError'.

13 fastify.setValidatorCompiler(({ schema }) => {
                                ~~~~~~~~~~~~~~~~~

  node_modules/fastify/types/schema.d.ts:25:3
    25   dataPath: string;
         ~~~~~~~~
    'dataPath' is declared here.


Found 1 error.
```

## Expected behavior

Typescript compilation would succeed with README examples.

## Your Environment

- *node version*: 14.16.1
- *fastify version*: 3.15.0
- *ajv version*: 8.1.0 (Problem appears first time in version 8.0.0)
- *typescript version*: 4.2.4
- *os*: Mac

**Comment by mcollina** [comment]
We don't support Ajv 8 yet.

**Comment by J3573R** [comment]
Fair enough. Got a little bit confused because there weren't any specifications in docs about Ajv versions but taking account that version 8 was published only a month ago, I should have expected that it might not yet be supported.

I think issue can be closed for the moment, Ajv 7 is enough for my current usecase.

**Comment by Gameghostify** [comment]
Using `setValidatorCompiler` should let you use any validator though, right? Similarly to how you can use joi, yup, ...

Why is ajv not technically considered as "just a different library" here? Since any library can be used, one would expect that, even if fastify doesn't support `ajv >= 8.0.0`, the unsupported version should be considered as just another library without baked-in support like joi/yup/...
