### ISSUE TITLE
Express-like res.locals equivalent?

### ISSUE THREAD

**Issue by motss** [fastify/fastify#303]
Any Express-like `res.locals` equivalent?

**Comment by StarpTech** [comment]
I see no problem to extend the `req` with a property like

res.locals
```js
fastify.addHook('onRequest', (req, res, next) => {
  req.locals = {}
  next()
})

fastify.use('/', (req, res, next) => {
  req.locals.a = 1
  next()
})

fastify
  .get('/', function (request, reply) {
    reply
      .send(request.req.locals)
  })
```

**Comment by jsumners** [comment]
For the "problem" see https://twitter.com/matteocollina/status/912241856146280448

But it is currently the only method of doing this.

**Comment by StarpTech** [comment]
Even with this performance lose `~5-10%` you are still faster than the others.

**Comment by delvedor** [comment]
> Even with this performance lose ~5-10% you are still faster than the others.

That is true, but we want that Fastify is "fast", not "still fast".
Every change, even if very little has a cost. We were able to make fastify so fast and support different features because we worked hard on all the small and "still faster" things :)

If you want to make this very fast this could be a way:
```js
fastify.decorateReply('locals', { user: null })

fastify.addHook('preHandler', function (req, reply, next) {
  reply.locals.user = req.body.user
  next()
})
```

In this way you are decorating the prototype of the `Reply`instance and V8 will be super fast when accessing its values or updating them :)

**Comment by jsumners** [comment]
Ah, yes, nice solution. 👍

**Comment by StarpTech** [comment]
but `reply.locals` is not accessible in middlewares.

**Comment by delvedor** [comment]
> but reply.locals is not accessible in middlewares.

Right, it depends where do you need it.
If you want very performant code, I would avoid middlewares :stuck_out_tongue_winking_eye:

**Comment by StarpTech** [comment]
That wasn't the question 😜 He wants to have express like `locals` .

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)

**Comment by luckstech** [comment]
@delvedor I'm getting `FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead.`
Is decorating the request still the best option?

**Comment by RafaelGSS** [comment]
@luckstech Not sure of your usage. But, likely the [fastify-request-context](https://github.com/fastify/fastify-request-context) may help you.

**Comment by jsumners** [comment]
See https://github.com/fastify/fastify/pull/2688

**Comment by mcollina** [comment]
The correct example is:

```
// Needed to avoid future deopts
fastify.decorateReply('locals', null)

fastify.addHook('preHandler', function (req, reply, next) {
  reply.locals = {}
  reply.locals.user = req.body.user
  next()
})
```

**Comment by jonasdevzero** [comment]
@RafaelGSS does this package cause loss of performance?

**Comment by RafaelGSS** [comment]
No, it shouldn't.

**Comment by StarpTech** [comment]
> // Needed to avoid future deopts
fastify.decorateReply('locals', null)

A pattern we should document.

**Comment by marinambur** [comment]
@mcollina Hello! Can I use this code in the module ( or in the middleware) of my nextJs app? As I see now,  it should be exactly in the main file, right before declaring a bootstrap function?

**Comment by mcollina** [comment]
what code? Are you using Fastify-next?

**Comment by marinambur** [comment]
@mcollina this piece of code which you've mentioned in this thread 
```
// Needed to avoid future deopts
fastify.decorateReply('locals', null)

fastify.addHook('preHandler', function (req, reply, next) {
  reply.locals = {}
  reply.locals.user = req.body.user
  next()
})
```
I'm using fastify with nestJs

**Comment by mcollina** [comment]
I have no clue, I'm not a user of Nest.

**Comment by bodinsamuel** [comment]
Hey,

Is it still recommended? The Type definition does not contains `locals` and this is not documented in the main website.
I wonder how other people do it, seems like a normal pattern for transferring user auth info or permissions without copy pasting much.

Thanks

**Comment by lsaadeh** [comment]
> Hey,
> 
> Is it still recommended? The Type definition does not contains `locals` and this is not documented in the main website. I wonder how other people do it, seems like a normal pattern for transferring user auth info or permissions without copy pasting much.
> 
> edit: I guess decorator was the word I wasn't looking for this pattern, it's not helping with typescript but I guess it works
> 
> Thanks

I'm also trying to overcome this issue.. the solutions above don't work with typescript.. I assume they are working for javascript.

**Comment by metcoder95** [comment]
> @mcollina this piece of code which you've mentioned in this thread
> 
> ```
> // Needed to avoid future deopts
> fastify.decorateReply('locals', null)
> 
> fastify.addHook('preHandler', function (req, reply, next) {
>   reply.locals = {}
>   reply.locals.user = req.body.user
>   next()
> })
> ```
> 
> I'm using fastify with nestJs

This approach is the one recommended to overcome to the need of have an analogy of Express’s locals. Decorators can easily help you to fulfill such needs and adjust accordingly to the strategy your application is following. 

If wanting to keep your JS code in sync with the TS types, you Fastify allows you to do interface augmentation thanks to the type definitions Fastify provides out of the box. See the following working example: https://github.com/metcoder95/fastify-racing/blob/4032019fbdfc81f6d49a81665147a3eb9e99574a/index.d.ts#L22

Hope this brings more clarity about the topic :)
