### ISSUE TITLE
hasHeader returns false for existing response header

### ISSUE THREAD

**Issue by dnikolayev** [fastify/fastify#3030]
## 🐛 Bug Report

There is an issue with hasHeader method of Reply. (https://www.fastify.io/docs/latest/Reply/#hasheaderkey)
It returns false in the case of getHeader returning a value, however reply.raw.hasHeader returns true in the same case.

## To Reproduce

Try to add a header directly to reply via .raw anywhere in the code. (Found the place that does it in our code to check why it happens initially).

Then you will be able to do getHeader normally, as it uses .raw object to do hasHeader:
https://github.com/fastify/fastify/blob/73c0b6f598e0568dfd2944d715dfa7aa997ae457/lib/reply.js#L196-L200

But internal hasHeader function doesn't check that:
https://github.com/fastify/fastify/blob/73c0b6f598e0568dfd2944d715dfa7aa997ae457/lib/reply.js#L212

## Example code to illustrate

![image](https://user-images.githubusercontent.com/1105759/115752472-ccbe8700-a3a2-11eb-9695-0e933ece9330.png)

Result:

![image](https://user-images.githubusercontent.com/1105759/115752692-05f6f700-a3a3-11eb-869a-4642ad53bd3c.png)

## Expected behavior

hasHeader should return True for both cases

## Your Environment

- *node version*: 15
- *fastify version*: latest
- *os*: Mac

**Comment by zekth** [comment]
To me `hasHeader` should rely on `getHeaders`. see: https://github.com/fastify/fastify/blob/ba43b314b156b39732dc614826806d4ef61700b8/lib/reply.js#L212

I don't see any drawback on that but @mcollina could you confirm?

**Comment by mcollina** [comment]
confirmed!

**Comment by mcollina** [comment]
Well, it should be based on the same logic. We can avoid generating the wrapper object.

**Comment by zekth** [comment]
I'll work on it.
