### ISSUE TITLE
Setting logLevel per route isn't working as expected

### ISSUE THREAD

**Issue by laSinteZ** [fastify/fastify#3036]
## 🐛 Bug Report

I wanted to disable logging to the `/health` calls.  I've found this part of doc and did as it says: https://github.com/fastify/help/issues/140
https://www.fastify.io/docs/latest/Routes/#custom-log-level

So I've set my `/health` route's `logLevel` as `trace`. But logging still logs all requests as `30`. And, for some reason, if I set `logLevel` to `warn`, `error` or `fatal` for a route, nothing is logged.

That's what I see in my console after GET /, GET /debug, GET /trace, GET /warn, GET /error, GET /fatal.

<img width="1505" alt="Screenshot 2021-04-23 at 14 12 35" src="https://user-images.githubusercontent.com/10958990/115863322-f678bc00-a43d-11eb-8444-78f06ad73862.png">

## To Reproduce

Use repo https://github.com/laSinteZ/fastify-customloglevel or this code and try opening /fatal, /error, /warn, etc.:

```js
const fastify = require('fastify')({
  logger: true,
})

fastify.get('/fatal', { logLevel: "fatal" }, function (_request, reply) {
  reply.send("Log fatal here")
})

fastify.get('/error', { logLevel: "error" }, function (_request, reply) {
  reply.send("Log error here")
})

fastify.get('/warn', { logLevel: "warn" }, function (request, reply) {
  reply.send("Log warn here")
})

fastify.get('/', function (_request, reply) {
  reply.send("No logLevel specified here")
})

fastify.get('/debug', { logLevel: "debug" }, function (_request, reply) {
  reply.send("Log debug here")
})

fastify.get('/trace', { logLevel: "trace" }, function (_request, reply) {
  reply.send("Log trace here")
})

fastify.listen(3000, function (err, address) {
  console.log(`server listening on ${address}`)
})
```

## Expected behavior

Requests should be logged according to the logLevel I believe. Or documentation should be changed.

## Your Environment

- *node version*: v15.6.0
- *fastify version*: 3.15.0
- *os*: Mac

**Comment by laSinteZ** [comment]
Also, I've found this discussion in Discord but it doesn't answer my question tbh:
https://discord.com/channels/725613461949906985/725613462373269567/832654662754369536

**Comment by zekth** [comment]
There is a misunderstand in here, let me show you:
```js
fastify.get('/warn', { logLevel: "warn" }, function (request, reply) {
  reply.log.info('info') // will not be logged
  reply.log.warn('warn') // will be logged
  reply.send("Log warn here")
})
```
The logs you're seeing are the one from the instance, the request logging. See : https://www.fastify.io/docs/latest/Server/#disablerequestlogging

**Comment by laSinteZ** [comment]
@zekth ah, I understand now. That's why nothing is logged if I set "warn"+ level for this, because original logs are of "info" level. I guess we should clarify documentation a little bit, since I am not alone in this misunderstanding.

**Comment by climba03003** [comment]
> 
> 
> @zekth ah, I understand now. That's why nothing is logged if I set "warn"+ level for this, because original logs are of "info" level. I guess we should clarify documentation a little bit, since I am not alone in this misunderstanding.

@laSinteZ I think you should have a basic concept about log level for all logging tools. The log level means current or above.
For example,
`info` level will be `info`, `warn`,`error` and `fatal`.
`fatel` level will be only `fatel`.

Currently, I didn't see any logging tools setting the log level is only logging that level. If you can found one, I would like to know.

**Comment by climba03003** [comment]
> 
> 
> @zekth ah, I understand now. That's why nothing is logged if I set "warn"+ level for this, because original logs are of "info" level. I guess we should clarify documentation a little bit, since I am not alone in this misunderstanding.

@laSinteZ I think you should have a basic concept for the log level. Logger will log all the things on or above the configured log level.
For example,
`info` will be `info`, `warn`, `error` and `fatel`.
`fatel` will be only `fatel`.

In order to disable some log, you will need to change the log level to above the logging level. Which means disable `info` need to set it as `warn` or above.

**Comment by laSinteZ** [comment]
@climba03003
Thank you for the explanation. Though, I am aware of this concept. My misconception was about what "logLevel" per route actually means. I had a (wrong) idea that setting a logLevel for a route will __magically__ turn all logs for this route into __selected level__. So, if I set logLevel __trace__ for a route, everything will be logged as trace. Now I understand that my idea was incorrect. I guess it's my fault and not docs one (since I am not sure how to expand documentation to make it more clear). But another gentleman in discord had also "fallen" for this.

For my usecase I guess I will need to remove automatic logging altogether and write my own, so /health calls will be recorded as trace.

**Comment by zekth** [comment]
Can we close this?
