### ISSUE TITLE
Document to use child logger per plugin

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#304]
```js
module.exports = function (fastify, opts, next) {
  const logger = fastify.logger.child({ plugin: 'your-plugin' })
  fastify.decorate('utility', () => {})

  fastify.get('/', handler)

  next()
}
```

**Comment by delvedor** [comment]
We could do this automatically inside Fastify when the user passes us an option like `name`. @mcollina thoughts?

**Comment by StarpTech** [comment]
I already thought about the same but I also like the convention approach.

**Comment by mcollina** [comment]
We don’t have the data (the name of the plugin) to do this, and all the
requests have their own with the reqId.

I would prefer a convention approach.
Il giorno mar 26 set 2017 alle 14:13 Dustin Deus <notifications@github.com>
ha scritto:

**Comment by delvedor** [comment]
> We don’t have the data (the name of the plugin) to do this

Yes, my idea was to create a child logger **if** the user passes a `name` option.
```js
fastify.register(
  require('./api-v1'),
  { prefix: '/v1', name: 'api version one' }
)
```

**Comment by jsumners** [comment]
If that were going to be supported then I suggest a breaking change to the way options are passed to plugins:

```js
fastify.register(
  require('./api-v1',
  { prefix: '/v1', name: 'api_v1', opts: {plugin_specific: 'options'}}
)
```

**Comment by delvedor** [comment]
@jsumners this could be an interesting discussion.

Related: https://github.com/fastify/fastify/issues/225

**Comment by jsumners** [comment]
@delvedor sort of. Hapi actually solves this particular problem in a different way than the discussion in #225. Hapi requires plugins export an `attributes` property on the exported object, e.g.:

```js
module.exports = fastifyPlugin(afunc)
module.exports.attributes = {
  name: 'plugin name',
  version: '1.0.0'
}
```

**Comment by StarpTech** [comment]
I like the export of an `attribute` property because of separation of concern `metadata` and `plugin`

```js
module.exports = function (fastify, opts, next) {
  fastify.decorate('utility', () => {})

  fastify.get('/', handler)

  next()
}

module.exports.attributes = {
 name: 'plugin name', // avoids to have a fixed schema in opts
 api: '0.28.0' // avoids using hemeraPlugin(fn, version)
}
```

**Comment by mcollina** [comment]
I am 👎  on making that mandatory, I'm 👍  on supporting it.

**Comment by delvedor** [comment]
I like the `attribute` idea.
If we choose to use it, we should also update how the `prefix`option works at the moment.

**Comment by StarpTech** [comment]
@mcollina nothing is mandatory. If you use `attributes.name` or named the function it will be used as plugin. If you use `attributes.api` fastify will wrap it with `fastify-plugin`.

**Comment by StarpTech** [comment]
What's the status here? Should we go with a plugin name ?

**Comment by jsumners** [comment]
To be clear: I don't really like the `attributes` function property in Hapi. I just showed it as an example of what others do. I much prefer https://github.com/fastify/fastify/issues/304#issuecomment-332503403.

That would also allow for more flexibility in the future with how plugins are registered.

**Comment by StarpTech** [comment]
@jsumners but you can register multiple plugins with `register` what's your solution for this?

**Comment by jsumners** [comment]
Hmm, good point. I'd say that is already an odd API. What if the plugins you want to register have conflicting options? How do you specify the correct options to multiple plugins if that is case?

Solution:

```js
fastify.register(
  [require('foo'), require('bar')],
  [
    {prefix: '/foo', name: 'foo', opts: {plugin_specific: 'options'}},
    {prefix: '/bar', name: 'bar', opts: {plugin_specific: 'options'}}
  ]
)
```

**Comment by StarpTech** [comment]
This could be one solution but I don't like it.

> What if the plugins you want to register have conflicting options?

Easy, use `register` with one plugin if you don't want to share options

- With your solution, it's not possible to set the plugin name inside a plugin.
- It would be also nice if we could set default options  inside a plugin

What do you think about that solution? `fastify.pluginName` is a public symbol.

```js
module.exports.options = {
 [fastify.pluginName] = 'fastify-helmet'
} // default options

module.exports = function (fastify, opts, next) {
  fastify.get('/', handler)

  next()
}
```

**Comment by allevo** [comment]
@StarpTech can we consider this outdated?

**Comment by StarpTech** [comment]
yes, we can.
