### ISSUE TITLE
Schema array contains does not validate

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [fastify/fastify#3059]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.7.0

### Node.js version

16.1.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Catalina 10.15.7

### Description

I have a schema:
```
body: {
    type: 'object',
    required: ['events'],
    properties: {
      events: {
        type: 'array',
        minContains: 1,
        contains: { type: 'string' }
      }
    }
  }
```

I expect it to validate `events` prop to contain at least one string, like this:
`{ events: ['1234567'] }`
but instead it does not validate the type inside, thus all of the following is valid:
```
{ events: [1234567] } // integer
{ events: [null] } // null
```
although it works with objects ([], {} etc.), still it is an issue

### Steps to Reproduce

write the schema above and make request to such route

### Expected Behavior

When any not valid item is send, it must throw an exception:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body.events should contain a valid item"
}
```

**Comment by jsumners** [comment]
See https://ajv.js.org/coercion.html
