### ISSUE TITLE
express-style fastify app inheritance

### ISSUE THREAD

**Issue by benderTheCrime** [fastify/fastify#306]
Is there any way I can not pass a function with several routes (fastify.register) and instead do something of the following nature:

```
const fastify = require('fastify');
const app = fastify();
const extended = fastify();

app.use('/foo', extended);

// or

app.register(extended, {});
```

similar to how express would do extensions for routes?

**Comment by mcollina** [comment]
You can wrap each fastify app in a plugin, and specify a prefix in the option. It would be “mounted” under that prefix.

**Comment by StarpTech** [comment]
Example:
```js
this.register(plugin,
  { prefix: "/api/v1" }
)
```

**Comment by benderTheCrime** [comment]
Oh cool, so this is not such an edge case as I thought it was?

When you say:

> You can wrap each fastify app in a plugin

How would I do that exactly?

In the plugin documentation, I see that the API for a plugin is:

```javascript
module.exports = function (fastify, opts, next) {
  fastify.decorate('utility', () => {})

  fastify.get('/', handler)

  fastify.register(require('./other-plugin'))

  next()
}
```

so would I do something like:

```javascript
module.exports = function (fastify, opts, next) {
    return app;
}
```

or 

```javascript
module.exports = function (fastify, opts, next) {
    return next(app);
}
```

making the whole example:

```javascript
this.register(function (fastify, opts, next) {
    // wrap app
}, { prefix: "/api/v1" });
```

**Comment by mcollina** [comment]
@StarpTech example is what you want. Basically you treat the `fastify`  instance in the plugin as the "main" fastify instance and you are done.

Fastify is built to support this use case really, without any performance loss.

**Comment by benderTheCrime** [comment]
Ok, thanks for getting back to me! So I'm having a little difficulty with this.

I'm using fastify@0.29.0.

Here's the code I'm using based on your recommendations:

```javascript
const app =  require('fastify')();
const exposed = require('fastify')();

exposed.get('/baz', function(req, res) {
    return res.send({});
});

app.register(function(fastify, opts, next) {
    fastify.register(exposed);
    next();
}, {
    prefix: '/foo/bar',
});

app.listen(3000);
```

And here's the error I'm getting:

```text
~/node_modules/fastify/fastify.js:155
    res.on('finish', onResFinished)
        ^

TypeError: res.on is not a function
    at fastify (~/node_modules/fastify/fastify.js:155:9)
    at process.nextTick (~/node_modules/avvio/plugin.js:30:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

I've also tried replacing the nested `fastify.register` with `this.register`, but it doesn't appear as though the context there is defined/a fastify app.

Could you please let me know if this looks familiar and if so what I'm doing wrong?

**Comment by benderTheCrime** [comment]
Oh, wait, hold on, you're saying:

```
const app =  require('fastify')();
const exposed = require('fastify')();

exposed.get('/baz', function(req, res) {
    return res.send({});
});

app.register(function(mainFastify, opts, next) {
    mainFastify.register(exposed, opts);
    next();
}, {
    prefix: '/foo/bar',
});

mainFastify.listen(3000);
```

Let me try that.

**Comment by benderTheCrime** [comment]
@mcollina I think I finally understand where the disconnect was, I'm sorry for not being more explicit earlier. 

Let's say I cannot describe my routes inside of a plugin as described in the examples you and @StarpTech provided and I already have Fastify apps A and B and I want to include all of the content in app B inside of app A as disclosed above:

```javascript
const app =  require('fastify')();
const exposed = require('fastify')();

exposed.get('/baz', function(req, res) {
    return res.send({});
});

app.register(function(fastify, opts, next) {
    fastify.register(exposed);
    next();
}, {
    prefix: '/foo/bar',
});

app.listen(3000);
```

For all intents and purposes, `exposed` in this app is a black box to me and I want to put it underneath `app`.

**Comment by jsumners** [comment]
```js
const fastify = require('fastify')()

fastify.register((instance, {prefix: '/foo/bar'}, next) => {
  instance.get ('/baz', (req, res) => res.send({})
  next()
})

fastify.listen(3000)
```

**Comment by benderTheCrime** [comment]
@jsumners I'm afraid that doesn't really take care of what I'm looking for either. 

In any case, it sounds like there's not a way to do what I'm looking for: just using an existing app inside of another app. A full example of this with express would be:

```
const app = require('express')();
const someOtherExpressApp = require('express')();

app.use('/foo', someOtherExpressApp);
```

only, I would like to do it with fastify. In my case, I can't just restructure because I don't know what "someOtherExpressApp" contains.

Closing this, feel free to reopen if anyone else has the same use case!

**Comment by jsumners** [comment]
I think you might benefit from watching @mcollina's presentation on Fastify -- http://www.nodesummit.com/videos/?the-video=34

He directly addresses the pattern of composing many instances of Express.

**Comment by mcollina** [comment]
Every application in fastify should be exposed as a plugin, _not_ tweaking the main instance. Then, you can register multiple applications/plugins on top of it. **Your use case is totally supported, but with a different API**.

**Comment by benderTheCrime** [comment]
@jsumners thanks for sharing, I'll do that!

**Comment by benderTheCrime** [comment]
@mcollina I plan to look over the docs again and watch the video @jsumners shared, but I don't think that I'm splitting hairs when I say:

I'm not opposed to structuring my API differently, however, my use case is derived from multiple developer defining their own routes on an application to be used by the main application instance. In essence, the very use case I'm describing is that I can't change anything about the sub-applications.

I haven't seen any code/patterns yet that explicitly allows me to do this without changing the nature of the applications registered on to the main instance, but that's ok! I'm not asking for a drop-in solution either, I'm going to see what I can do to work with the `.register` plugin API provided.

**Comment by mcollina** [comment]
The same patterns hold with register. Each sub application (when not using fastify-plugin), would be completely encapsulated from the others via prototypical inheritance. This allow us to have zero-cost sub applications (instead of what you do with Express). It’s a different model designed for better performance: let us know how you progress!

**Comment by droidMakk** [comment]
@benderTheCrime , You could try something like this. It' working for me.

> app.js
```js
import users from 'routes/users'
app.register(function (fastify, opts, next) {
    fastify.register(users);
    next();
}, { prefix: '/users', });
```

>routes/users.js
```js
const users = (fastify, opts, done) => {
    fastify.get('/',async (req, rep) => {
        const data = await users_model.users();
        if(data.error) rep.status(500);
        else rep.status(200)
        rep.send(data);
    });
    done();
}

export default users;
```

**Comment by delvedor** [comment]
@droidMakk there is no need to wrap a register inside another register in your example, the following works as well :)
```js
import users from 'routes/users'

app.register(users, { prefix: '/users', })
```

Also, in your second snipped, you could just `return` the data since you are using an async function:
```js
const users = (fastify, opts, done) => {
    fastify.get('/',async (req, rep) => {
        const data = await users_model.users();
		rep.status(data.error ? 500 : 200);
        return data;
    });
    done();
}

export default users;
```

**Comment by droidMakk** [comment]
![image](https://user-images.githubusercontent.com/20293708/84477752-c739e000-acad-11ea-98d7-0b42285642a2.png)

@delvedor  This is what's happening when I try to do that...

**Comment by mcollina** [comment]
In the previous example it seems you have a typo `prefx` instead of `prefix`.
