### ISSUE TITLE
Fastify Typescript

### ISSUE THREAD

**Issue by rupamking1** [fastify/fastify#3060]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

v3.15.1

### Node.js version

14.16.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10.0.19042.964

### Description

Error- Typescript error req.body
<img width="243" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/117527364-1933d480-afe9-11eb-9d46-66730c2d9c56.png">

### Steps to Reproduce

Error- Typescript error req.body

**Comment by mcollina** [comment]
This is covered in https://www.fastify.io/docs/latest/TypeScript/. Remember to add validation ad well for your body.
