### ISSUE TITLE
Custom ajv instance is hard to integrate

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#3061]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Currently, it's not possible to access the validator as API. For example, I'd like to validate the payload of my JWT with ajv in a hook or route. This requires me to bring my own ajv instance. This sounds straight but isn't. In the core, we change the way how ajv errors are formatted and add custom rules. My goal is to use ajv everywhere.

### Steps to Reproduce

Use https://github.com/fastify/fastify-jwt and try to validate the payload of the jwt with a custom ajv instance in the `trusted` hook. This will work but break all my other tests because the ajv instance isn't configured properly.

### Expected Behavior

It would be great to make the validation API public or provide a way to create a custom ajv instance without breaking functionality

> Note: If you use a custom instance of any validator (even Ajv), you have to add schemas to the validator instead of Fastify, since Fastify's default validator is no longer used, and Fastify's addSchema method has no idea what validator you are using.

1)
```js
fastify.validate(schema, data)
```
2)
```js
import Fastify, { Ajv } from 'fastify'
const ajv = Ajv()
const fastify = Fastify({
  ajv
})
// use ajv everywhere
fastify.decorate('ajv', ajv)
```

**Comment by Eomm** [comment]
Did you try the [`fastify.validatorCompiler`](https://www.fastify.io/docs/latest/Server/#validatorcompiler)?

This should works (fast meta code):

```js
let jwtValidateFunc
fastify.register(fastify-jwt)
fastify.addHook('onReady', function (done) {
  const jwtValidateSchema = { .. }
  jwtValidateFunc = fastify.validatorCompiler( { schema: jwtValidateSchema } )
  done()
})

fastify.addHook('preHandler', (request, reply, done)=>{
  const ajvResult = jwtValidateFunc(request.body)
  console.log(ajvResult)
  done()
})
```

**Comment by kibertoad** [comment]
If this works, we probably should document it and cover with tests :D

**Comment by StarpTech** [comment]
Hi @Eomm thanks. Does it allow to compile schema inside a plugin or is it necessary to compile it after `onReady`?

```js
function plugin(fastify, next) {
	const jwtValidateFunc = fastify.validatorCompiler( { schema: jwtValidateSchema } )
}
```

IMO this feels more like a workaround rather than a generalization.

**Comment by seriousme** [comment]
Fastify-openapi-glue is a plugin that also uses its own AJV instance.
It does not use onReady and works like a charm ;-)

```javascript
function setValidatorCompiler(instance, ajvOpts, noAdditional) {
  const defaultOptions = {
    removeAdditional: !noAdditional,
    useDefaults: true,
    coerceTypes: true,
    strict: false
  };
  const ajvOptions = Object.assign(defaultOptions, ajvOpts);
  const ajv = new Ajv(ajvOptions);
  // add default AJV formats
  addFormats(ajv);
  // ajv-formats misses some validators for byte, float, double, int32 and int64 that oai-formats adds
  for (const fmt in oaiFormats) {
    ajv.addFormat(fmt, oaiFormats[fmt]);
  }

  instance.setValidatorCompiler(({ schema, method, url, httpPart }) =>
    ajv.compile(schema)
  );
}
```

https://github.com/seriousme/fastify-openapi-glue/blob/master/index.js#L47

**Comment by StarpTech** [comment]
I will close it for now. Creating a custom instance is the way to go.
