### ISSUE TITLE
`fastify({clientErrorHandler})` shows type error

### ISSUE THREAD

**Issue by giltayar** [fastify/fastify#3062]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

16.1.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3.1

### Description

According to the [docs](https://www.fastify.io/docs/latest/Server/#clienterrorhandler) the fastify factory accepts a `clientErrorHandler` option that enables us to log errors that are client socket errors. And it works too! (no complaints there...)

Unfortunately, the typing is missing for this option, so I have to add a `@ts-ignore` when using `fastify({clientErrorHandler})`.

Another weird symptom of this is that when I _do_ add `clientErrorHandler` option to the call to `fastify`, then `fastifyServer.addHook('onError', someErrorHandler)` _also_ fails type checking! Which is really strange, but I'm guessing is just some weird typing issue around all those generic type parameters.

### Steps to Reproduce

Write this code:

```ts
import fastify from 'fastify'
const app = fastify({clientErrorHandler})
```

And typecheck it with TypeScript. You will get the TS error `Object literal may only specify known properties, and 'clientErrorHandler' does not exist in type 'FastifyServerOptions<Server, FastifyLoggerInstance>'` on the second line.

### Expected Behavior

No error.

**Comment by mcollina** [comment]
Would you like to add this type? Remember to add unit tests for it!

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by KiraPC** [comment]
This issue should be solved due to https://github.com/fastify/fastify/pull/3069 merge.

@giltayar could you check?

**Comment by giltayar** [comment]
@KiraPC type errors are gone. LGTM. 

Thanks!
