### ISSUE TITLE
Grouping server options

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3074]
## 🚀 Feature Proposal

Update the server configuration input to provide a clearer categorization of the options

## Motivation

Increase the focus of some properties; maybe a doc revision could be enough?

## Example

```js
fastify({
  timeouts: {
    connectionTimeout
    keepAliveTimeout
    pluginTimeout
    http2SessionTimeout
  },
  routing: {
    rewriteUrl
    constraints
    exposeHeadRoutes
    caseSensitive
    ignoreTrailingSlash
  },
  security: {
    onProtoPoisoning
    onConstructorPoisoning
    trustProxy
  },
  errorManagement: {
     clientErrorHandler
     frameworkErrors
     return503OnClosing
     schemaErrorFormatter
  }
  etc...
})
```

**Comment by mcollina** [comment]
I think this is worthwhile doing. However we would need to deprecate the other options one-by-one.

**Comment by meehawk** [comment]
Hi @mcollina I am new here and would love to work on this. Any directions would be awesome

**Comment by mcollina** [comment]
Look at the current options and propose a complete mapping to a new grouped structure.

Change the code internally to the new structure, then add normalization layer that converts the old to the new. It should emit deprecation warnings for all the previous options

**Comment by meehawk** [comment]
@mcollina got it. Thank you so much for  this. I will try working on a PR

**Comment by meehawk** [comment]
@mcollina I can think of a very cumbersome logic like so:

```js
function normalizeOptions(options) {
  timeouts = {}

  if(options.connectionTimeout !== null && options.connectionTimeout !== undefined) {
    // print deprecation warning
    timeouts.connectionTimeout = options.connectionTimeout
    delete options.connectionTimeout
  }
  .
  .
  .

  return {
      timeouts
  }
}
```

I am not sure if this is going to be the prettiest approach. Do you have any suggestions on this

**Comment by mcollina** [comment]
Unfortunately that's the only one I know.

**Comment by jsumners** [comment]
A helper function may be useful here.

**Comment by meehawk** [comment]
@jsumners @mcollina this is the logic I eventually was able to come up with. Not sure if this is the most efficient way to do this though:

```js
function normalizeOptions (options) {
  const deprecatedOptionsMap = new Map([
    ['clientErrorHandler', 'errorManagement'],
    ['frameworkErrors', 'errorManagement'],
    ['return503OnClosing', 'errorManagement'],
    ['schemaErrorFormatter', 'errorManagement'],
    ['rewriteUrl', 'routing'],
    ['constraints', 'routing'],
    ['exposeHeadRoutes', 'routing'],
    ['caseSensitive', 'routing'],
    ['ignoreTrailingSlash', 'routing'],
    ['onProtoPoisoning', 'security'],
    ['onConstructorPoisoning', 'security'],
    ['trustProxy', 'security'],
    ['connectionTimeout', 'timeouts'],
    ['keepAliveTimeout', 'timeouts'],
    ['pluginTimeout', 'timeouts'],
    ['http2SessionTimeout', 'timeouts']
  ])

  const normalizedOptions = {}

  for (const key in options) {
    if (deprecatedOptionsMap.has(key)) {
      // !TODO: Print deprecation warning
      const groupKey = deprecatedOptionsMap.get(key)

      normalizedOptions[groupKey] = {
        ...normalizedOptions[groupKey],
        [key]: options[key]
      }

      delete options[key]
    }
  }

  return normalizedOptions
}
```

**Comment by meehawk** [comment]
@mcollina I've made a draft PR. Feel free to leave any comments. Also, it looks like a lot of small details need to be taken care of if we make this change. Do you recommend doing something like

```Grouped params -> flatten it to the old version```

this provides user with a cleaner interface to provide inputs and less overheads on our part

**Comment by mcollina** [comment]
I had that new/old config split in the past it was a significant pain to maintain. Everything should be updated to use the grouped options and the previous properties deprecated.

**Comment by meehawk** [comment]
@mcollina that seems better. I've pushed a PR that uses the new grouped version. I still need to add the method that displays the deprecation warning but rest of it seems to work fine with tests. Can you have a look?

**Comment by jsumners** [comment]
This would target `next`.

**Comment by meehawk** [comment]
@jhonrocha I'd been working on this in the past. Got super busy with school and other stuff. This seems to be super nice feature to have. Would love to update you with what I'd done so far in case you want to refer it as a starting point ✨

**Comment by jhonrocha** [comment]
Thanks, @meehawk ! I am checking your PR and I will take it as a reference for this work.

**Comment by jsumners** [comment]
Please retain the original work if it is still applicable -- https://gist.github.com/jsumners/461ef7a64545108635cc437fde112721

**Comment by jhonrocha** [comment]
Sorry guys, I will not proceed with this. I will focus on something else for the next days.

**Comment by mcollina** [comment]
I don't think we would ever do this, it's too complex with too big of a possible breakage. I'm going to close for now, we can always revisit.
