### ISSUE TITLE
Feat: Integration with adminbro

### ISSUE THREAD

**Issue by rubiin** [fastify/fastify#3077]
## 🚀 Feature Proposal

Admin bro is An Auto-generated Admin Panel for your Node.js Application. Currently express ,koa and hapijs framework plugins are supported for admin bro. Since fastify also needs an admin panel of some sort, I was thinking of having a plugin for fastify .

## Motivation

Please outline the motivation for the proposal.

Reference for the adminbro intregration for hapijs can be found at https://github.com/SoftwareBrothers/admin-bro-hapijs/blob/master/plugin.js

**Comment by mcollina** [comment]
That's a great idea! Let us know how you proceed, we can review things along the way.

**Comment by rubiin** [comment]
> That's a great idea! Let us know how you proceed, we can review things along the way.

Glad you liked the idea. I was thinking of using [hapijs plugin's code](https://github.com/SoftwareBrothers/admin-bro-hapijs/blob/master/plugin.js) as fastify has similar hapi like route declaration

**Comment by trey-m** [comment]
Great idea. Are you currently working on this?

**Comment by rubiin** [comment]
> Great idea. Are you currently working on this?

not working but would like some help though. The above repo has plugin for hapijs and since fastify shares some common hapi sytle syntax as well, i was wondering if we could translate the plugin for fastify @mcollina

**Comment by iagocalazans** [comment]
I think they are [developing something](https://github.com/SoftwareBrothers/admin-js-fastify) like this.
