### ISSUE TITLE
Multiple close callback execution

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3078]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

14

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Calling multiple time the `fastify.close(callback)` function will run only one the close hooks (as expected) but it will run multiple times the `callback` function.

As in the example, I didn't use `process.once` because I'm getting a multiple SIGINT and the second one will kill the server.
The workaround would be simply to put a flag to limit the `fastify.close()` call

### Steps to Reproduce

```js
import fastify from 'fastify'

const server = fastify()

server.addHook('onClose', (instance, done) => {
  console.log({ done });
  console.log('CLOSING 1');
  setTimeout(done, 3000)
})

await server.listen({
  port: 8080,
  host: '0.0.0.0'
})

process.on('SIGINT', function closeApplication() {
  server.close((err) => {
    console.log({ err });
  })
})
```

Now trigger many SIGINT the output will be:

```
$ node close.mjs 
{ done: [Function: worked] }
CLOSING 1
{ err: null }
{ err: null }
{ err: null }
{ err: null }
{ err: null }
{ err: null }
{ err: null }
{ err: null }
{ err: null }
```

### Expected Behavior

The callback should be called only once, as the hooks do.

I think this issue could be in `avvio`, opening here to get thought about it.

**Comment by mcollina** [comment]
I disagree. callbacks MUST always be called as you do not know if it's still processing or not.

I'm ok in calling the callback with an error if called multiple times.

FYI: check out https://github.com/mcollina/close-with-grace. It's an implementation of what you are trying to achieve.

**Comment by Eomm** [comment]
> I disagree. callbacks MUST always be called as you do not know if it's still processing or not.

I understand your point: it could lead to infinite waiting.
Not sure if calling the callback with the error could lead the user to run `process.exit(1)` before the first close has completed

```
server.close(err => {
  if(err) process.exit(1)
})
```

in this case we should guarantee that the second callback will not be executed before the first one.

I'm closing this since it can be implemented with a simple pattern and because ignoring a provided callback can introduce more issues than is trying to solve

> FYI: check out https://github.com/mcollina/close-with-grace. It's an implementation of what you are trying to achieve.

I spot it reading the `fastify-cli` source 😄

**Comment by mcollina** [comment]
> In this case we should guarantee that the second callback will not be executed before the first one.

This is something that we should definitely fix.
