### ISSUE TITLE
fork boom and shot

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#308]
The Hapi community is moving to support only Node 8+.
I do not think this is a message that we can stand behind, as I believe we should support all the maintained versions of Node, and remove them when it is not feasible to support the old ones anymore.

If we want to provide boom-like capabilities, we should fork it and maintain it ourselves.
The same reasoning holds for shot.

**Comment by lmammino** [comment]
for what concerns boom, what about replacing it with [http-errors](https://www.npmjs.com/package/http-errors) so that we don't have to maintain a fork ourselves?

**Comment by StarpTech** [comment]
@lmammino boom is very well-known and I like the API. We also have boom integrated into Fastify.  I see no problem in to maintain a fork because the API and the functionality are settled. I only see the problem in versioning for the users (an example shot@3) . What's the option to create new projects based on the forks ? (foom, inject)

**Comment by jsumners** [comment]
The only async I see in Boom is in the tests -- https://github.com/hapijs/boom/search?utf8=%E2%9C%93&q=async&type=

**Comment by StarpTech** [comment]
@jsumners stale index loot at https://github.com/hapijs/boom/blob/master/test/index.js

**Comment by mcollina** [comment]
I think we should support https://www.npmjs.com/package/http-errors and mention it in the docs, maybe we can keep a light support for that version of `Boom` and add a note on Boom supported  versions in the README.

**Comment by allevo** [comment]
`http-errors` has no method for rendering the error and doesn't support all `boom` features.

We need to figure out if we want to keep the boom features and how

**Comment by StarpTech** [comment]
I try it against. Why not create new projects based on boom (BSD-3 license) and shot (BSD-3license) ?

**Comment by delvedor** [comment]
I'm working on a library like `shot` that should fix the problem.
Regarding Boom, I'm open to other solutions, I'm not a Boom user, but it seems that a lot of people are. So we should try to support it as well as we can.

**Comment by allevo** [comment]
@delvedor why not a `fastify` plugin?

```
const createError = require('http-errors').createError

function buildBoomInterface(error) {
  error.isBoom = true
  // other things....
}

fastify.register(fp(function(fastify, ops, next) {
  fastify.decorate('error', function(msg, code) {
    const error = createError(404, 'This video does not exist!')
    buildBoomInterface(error)
    return error
  })
  next()
}))

fastify.get('/', function (req, reply) {
  const error = fastify.error('DOOM!', 400)
  reply.send(error)
})
```

If that plugin supports a `Boom` like interface, all thing should work correctly!

**Comment by delvedor** [comment]
We have forked `shot`, the project is under the Fastify organization.
[`fastify/light-my-request`](https://github.com/fastify/light-my-request).

**Comment by mcollina** [comment]
I am closing this, as in the end there is no reason to fork boom, as we don’t depend on it directly.
