### ISSUE TITLE
Add a means to access the server object from request/response decorator functions

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#3094]
## 🚀 Feature Proposal

Functions decorated on the request and response do not have a means for accessing the server object. I propose adding a means to do so.

I think the easiest method to do this would be:

1. Only provide the feature for non-arrow function decorator functions
2. Add a new property to the function when it is decorated, e.g. `Symbol.for('fastify.instance')`
    ```js
    fastify.decorateRequest('foo', function foo() {
      const { constants } = this[Symbol.for('fastify.instance')]
      // do stuff
    })
    ```

## Motivation

Some decorators, such as long lived database connections or large "constant" objects, are better suited to be decorated on the server instance to avoid increasing the memory requirements for the short lived request and response objects. But functions decorated on the request and reply objects definitely need access to these server decorations.

As it stands, I find myself routinely wrapping functions with decorator functions to work around this problem. For example:

```js
'use strict'

const fastify = require('fastify')()
const constants = { foo: 'foo' }

fastify.decorate('constants', constants)

fastify.decorateRequest('bar', function () {
  // Will log 'missing constants' since we did not decorate the request
  bar({ constants: this.constants })
})

fastify.register(plugin)

fastify.get('/', function (req, res) {
  req.bar()
  req.bar2()
  res.send()
})

fastify.listen(5000)

// Would be in `bar-plugin.js` which would itself import `bar` like:
// const _bar = require('./bar')
async function plugin (instance) {
  const { constants } = instance
  instance.decorateRequest('bar2', function () {
    // Will log 'foo' since we have wrapped the function in order to pass
    // in the object from the decoration
    bar({ constants })
  })
}
plugin[Symbol.for('skip-override')] = true

// Would be in a `bar.js`
function bar({ constants }) {
  console.log(constants?.foo ?? 'missing constants')
}

```

**Comment by mcollina** [comment]
I'm +1 with this.. but I would not using a Symbol, just a regular property.

**Comment by jsumners** [comment]
But we don't technically own the function. I think the symbol allows us to decorate the function and avoid and conflicts with the owner. No?

**Comment by mcollina** [comment]
> But we don't technically own the function. I think the symbol allows us to decorate the function and avoid and conflicts with the owner. No?

I'm lost :/

**Comment by MSE99** [comment]
Property names are pretty simple and easy to write, but they could also conflict with user decorators on the other hand symbols are a safer alternative but they also are a bit verbose, i think we should go with a regular property name symbols should be kept private and they shouldn't be exposed to users as part of the public API, the implementation is pretty simple either way.

**Comment by jsumners** [comment]
> I'm lost :/

When `fastify.decorateRequest` mutates the function passed by adding a new property to it, we _could_ be conflicting with properties the developer has attached. A symbol reduces that chance dramatically I think.

I'm okay with not using the symbol. I just want to make sure we agree that using a standard string named property can cause this conflict.

What name should we decorate as? `fastifyInstance`?

**Comment by mcollina** [comment]
I was thinking of skipping `decorateRequest` altogether and setting it in the prototype when a plugin is encapsulated.

**Comment by jsumners** [comment]
The request and reply prototypes?

**Comment by mcollina** [comment]
Yes exactly.

**Comment by jsumners** [comment]
What about the example I included in the original post? Notice that it does not use a plugin for the failing case. So the following isn't true:

> setting it in the prototype when a plugin is encapsulated.

**Comment by MSE99** [comment]
Each request has a context associated with it, would it be okay to include a reference to the current instance there when the context is created, we could then define a getter on the Request/Reply prototype which will then fetch the instance from the context.

**Comment by mcollina** [comment]
I think we should do it in https://github.com/fastify/fastify/blob/0e55fce93fc40a8713a8664258854e5b73fb11cb/lib/pluginOverride.js#L40-L41, so that the instance is retained.

**Comment by jsumners** [comment]
Works for me.

**Comment by MSE99** [comment]
@mcollina won't doing it that way will mean that the property will only be available for plugins that make use of encapsulation it also means that the property will only be available inside the scope of a plugin, which is going to confuse some users and won't be used much by plugin authors.

```javascript
server.get('/', async function (req) {
  console.log(req.instance);
  return 'done'
})

async function plugin (instance, opts) {
  instance.get('foo', async (req) => {
    console.log(req.instance)
    return 'done'
  });
}

server.register(plugin)

await server.inject({ method: 'GET', url: '/' }) // logs `undefined` to the console
await server.inject({ method: 'GET', url: '/foo' }) //  logs the fastify instance object to the console
```

**Comment by mcollina** [comment]
It will work for both, it's quite simple to generalize to the root plugin.
