### ISSUE TITLE
reply handling

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#3099]
## 💥 Regression Report

I think it should be related to the reply simplification.
https://github.com/fastify/fastify-nextjs/pull/260

Not sure if it is only test case related only or production related. I am not using this plugin but it is worth knowing the test is currently failed.

## Last working version

Worked up to version: 3.15.1

Stopped working in version: 3.16.1

**Comment by mcollina** [comment]
Sigh. I'll issue a revert asap.

**Comment by mcollina** [comment]
Confirmed, the change is semver-major.

**Comment by climba03003** [comment]
One more to revert https://github.com/fastify/fastify/commit/212fdb7e720b1879f5201678c5fef71f0eacf457

**Comment by mcollina** [comment]
check out #3099
