### ISSUE TITLE
Update to pino@7 when it is available

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3101]
Update to pino@7 when it is available.

This issue is a requirement for v4.

**Comment by mcollina** [comment]
@kibertoad would you like to take this on as it would require some fundamental rework of the typescript types?

**Comment by mcollina** [comment]
Pino v7.0.0-rc.1 just shipped, release notes in https://github.com/pinojs/pino/releases/tag/v7.0.0-rc.1

**Comment by kibertoad** [comment]
@mcollina With pleasure. Should I target next?

**Comment by mcollina** [comment]
> @mcollina With pleasure. Should I target next?

yes exactly!

**Comment by mcollina** [comment]
@kibertoad any updates on this?

**Comment by kibertoad** [comment]
@mcollina yeah, will work on it this week, it was a pre-vacation crunch before. Sorry for the delay.

**Comment by mcollina** [comment]
No worries, just a status check

**Comment by kibertoad** [comment]
Blocked until 7.0.0-rc.4 is released.

**Comment by climba03003** [comment]
> 
> 
> Blocked until 7.0.0-rc.4 is released.

I think we can target to `github:pinojs/pino` until `pino` is release a stable `7.0.0` version.

**Comment by kibertoad** [comment]
This is done. We will just need to update to pino 7 final when it is available.
