### ISSUE TITLE
Missing reference for how to override the schema types

### ISSUE THREAD

**Issue by rustyconover** [fastify/fastify#3104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x.x

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

There is a missing reference in the comment that documents the FastifySchema type.

### Steps to Reproduce

look at the docs.

```
/**
 * Schemas in Fastify follow the JSON-Schema standard. For this reason
 * we have opted to not ship strict schema based types. Instead we provide
 * an example in our documentation on how to solve this problem. Check it
 * out here:
 */
```

### Expected Behavior

Have a reference to follow.

**Comment by mcollina** [comment]
cc @Eomm

**Comment by Eomm** [comment]
Done in https://github.com/fastify/fastify/pull/3290
