### ISSUE TITLE
Get version via hardcode/`require('package.json')`/other method instead of `fs.readFileSync`

### ISSUE THREAD

**Issue by jesec** [fastify/fastify#3110]
## 🚀 Feature Proposal

Currently fastify loads its version via `JSON.parse(fs.readFileSync(pkgPath))`:

https://github.com/fastify/fastify/blob/6278e7bc2102d57b54d88e9f47d6661a2e0a7624/fastify.js#L663-L666

## Motivation

I use webpack. webpack recognize `package.json` as an asset when it is used that way, and, as a result, fastify's `package.json` appears in the `dist/` output of my application. It creates confusion when there are two `package.json`. While of course I can remove it, that sets the `version` field of fastify to `undefined`, which is probably not ideal. 

## Suggestion

I suggest that we use a more deterministic method. The simplest and most deterministic way is to simply hardcode the version, which avoids all the loading and dependency on `package.json`. Alternatively we can `require('package.json')`, which allows webpack to bundle it.

**Comment by mcollina** [comment]
I'm -1 in hardcoding the version number, it should be picked up from the relevant metadata. Let's do the `require('package.json')` change.

Would you like to send a PR?

**Comment by zekth** [comment]
@mcollina i'll do it
