### ISSUE TITLE
Fastify Error Handler will always send an error 500

### ISSUE THREAD

**Issue by VottusCode** [fastify/fastify#3114]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

14.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

The following code is taken from my errorHandler, and while the correct error message gets sent, the code stays at 500, even though I set it to 401 via res.code.

```ts
        // This error is thrown when using the parseAuthHeader function.
        // Unfortunetely, right now there is no better way to figure out
        // whether it's this error other than checking the message.
        if (err.message && /(auth|authorization) (prefix|header)/g.test(err.message)) {
          res.code(401)
          return res.err({
            kind: "UNAUTHORIZED"
            message: "Invalid auth header",
          })
        }

        service("logger").error(err)

        return res.err({
          kind: "INTERNAL",
          message: "Internal Server Error",
        })
```
(the comment is unrelated to Fastify, I left it out to clarify the regex workaround, if someone wanted to know)

The res.err function is decorated wrapper around res.send to form a correct response:
```ts
  res.err = (error: BaseError): ErrorRes => {
    const err: ErrorRes = {/* ...impl */}
    res.send(err)
    return err
  }
```

The response (from DevTools):
![image](https://user-images.githubusercontent.com/53915302/120316288-8b908f80-c2dd-11eb-8ee7-1f3f0e412dfc.png)
![image](https://user-images.githubusercontent.com/53915302/120316332-99deab80-c2dd-11eb-8f92-9268d6c244fc.png)

### Steps to Reproduce

1. Register a custom errorHandler
2. Try to change the statusCode using res.code

### Expected Behavior

The code would change accordingly.

**Comment by mcollina** [comment]
Can you please include a full example that we can run to reproduce your problem? This is supported and covered by tests, so it's something you are doing on your end.

**Comment by VottusCode** [comment]
Sure, the code is located here: https://github.com/VottusCode/asv/blob/admin/admin/src

The snippet comes from here:
https://github.com/VottusCode/asv/blob/admin/admin/src/http/lifecycle/exception.ts#L9-L26

**Comment by mcollina** [comment]
It seems all of this is using another library/framework called Fasteerjs. Could you provide a simple, self-contained snippet to reproduce?

**Comment by VottusCode** [comment]
> It seems all of this is using another library/framework called Fasteerjs. Could you provide a simple, self-contained snippet to reproduce?

I will, unfortunetely I won't be home till tomorrow. Also, I just looked, the code the repo is a bit outdated (misses the res.code call), seems like I didn't commit latest changes.

Also, all the `fasteerExceptions` function is doing is decorating some things, nothing else. In addition to that, the errorHandler does actually get executed, so the issue shouldn't be in the library..

**Comment by VottusCode** [comment]
I haven't been able to reproduce this issue with this minimal setup, even with Fasteer.
(see https://github.com/VottusCode/fastify-err-demo - if you run src/index, it will try standalone fastify, then also 2 ways of using @fasteerjs/exceptions, see src/servers for exact setup)

I'm gonna look into my code again though and sorry if I was just overseeing something stupid :sweat_smile:

**Comment by VottusCode** [comment]
![image](https://user-images.githubusercontent.com/53915302/120546571-50cb4c00-c3f0-11eb-9d9f-b6c09ebfe466.png)
Fixed. Issue was in how @fasteerjs/exceptions was handling exceptions, sorry.

**Comment by mcollina** [comment]
No worries! I'm glad it all worked out.
