### ISSUE TITLE
Option to customize Ajv type coercion behavior based on httpPart

### ISSUE THREAD

**Issue by albertoantunes** [fastify/fastify#3121]
## 🚀 Feature Proposal

Hello! Fastify by default comes with AJV with coerceTypes enabled.
Me and some coworkers found that is a pretty good behavior for both querystring and pathParams as they all come as strings

However, for body validation as JSON, we actually required to have it turned off, as there are some edge cases that we need to validate that are simply wrong with coercion enabled. ex: { "some_integer_prop": null } passes validation because it is coerced to 0.

Our fix was to customize fastify setValidatorCompiler like so:

```javascript
const defaultAjv = new Ajv({
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: true,
    nullable: true,
  })

  const disabledCoercionAjv = new Ajv({
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: false,
    nullable: true,
  })

// Use ajv instance with disabled type coercion for body params
// and default ajv instance for others
  fastify.setValidatorCompiler(({ schema, httpPart }) => {
    if (httpPart === 'body') {
      return disabledCoercionAjv.compile(schema)
    }

    return defaultAjv.compile(schema)
  })
```

It would be nice if there was a built-in option in fastify to selectively enable this behavior like so:

```javascript
const fastify = require('fastify')({
    ajv: {
      customOptions: {
        coerceTypes: true,
        coerceTypesBody: false
      }
    }
  })
```

## Motivation

I understand that maybe this should be a feature of ajv itself to have more granular control of its coercion options,
but I believe this is an issue common enough that many developers have without even realizing until they get a bug in production having a field in database with value 0 that shouldn't be there. And since the default in ajv is to not coerce types, but in fastify is to coerce, I guess many fastify users have this issue without even realizing.

Maybe if not possible to implement this feature, put a section in the documentation warning of this edge case of body validation.

Thanks!

**Comment by weiliddat** [comment]
Does this option not work when initializing the fastify server instance with options?

https://www.fastify.io/docs/latest/Server/#ajv

**Comment by Eomm** [comment]
I love how you have used the validator compiler to cover this use case!

I think this feature can be implemented in a plugin (that should configure the [schemaController.bucket](https://www.fastify.io/docs/latest/Server/#schemacontroller) to work smoothly with the `fastify.addSchema()` method)

**Comment by MetCoder95** [comment]
I'm currently working on this but I'm quite curious, why are you suggesting the `#bucket`?
It shouldn't be enough with just the `compilersFactory`?

Also, there's missing documentation about `setSchemaController`. I'm dropping it here in case somebody wants to open a PR for the docs, otherwise, I'll do it Maybe tomorrow 🙂

**Comment by MetCoder95** [comment]
>If you add schema using fastify.addSchema() you will need to access those schemas through the bucket

But I think the issue is referring to the Ajv instance as it is, isn't it? I might be getting it wrong
Then, should be enough by just checking if the `httpPart` matches a custom Ajv instance set for the route, or maybe the encapsulated instances?
