### ISSUE TITLE
Response Schema is not enforced when sending plain text reply with reply.send(string)

### ISSUE THREAD

**Issue by tnishimura** [fastify/fastify#3123]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Node.js version

10.24.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The response schema seems to be enforced only when the reply body (i.e. the argument to `reply.send`) is an object:

```
import F from 'fastify';
import { Type } from '@sinclair/typebox';

const fastify = F({ logger: true });

fastify.get('/', {
  schema: {
    response: { 200: Type.Object({ hello: Type.String()}) }
  },
},
  (request, reply) => {
    reply.send("this should cause an error, no?");
    // compare this to:
    // reply.send({ wrongKey: "this would cause an error as expected"}); 
  }
)

fastify.listen(3000, function (err, address) {
  if (err) {
    console.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

### Steps to Reproduce

Run the above code and do `curl localhost:3000`.

### Expected Behavior

Since plain text response body would not match the schema, and in fact wouldn't even parse as JSON, it seems like this should throw an exception.

**Comment by StarpTech** [comment]
Hi, intuitively I'd also expect an error. The problem here is that the serialization library can't compare strings with objects and it will pass it as it is.

I also found another issue:

This will succeed:

```js
test('string', t => {
  t.plan(3)

  const fastify = Fastify()
  fastify.get('/', {
    schema: {
      response: {
        '2xx': {
          type: 'integer'
        }
      }
    }
  }, function (req, reply) {
    reply.send('erfer')
  })

  fastify.inject('/', (err, res) => {
    t.error(err)
    t.equal(res.payload, 'erfer', 'it must use the ceil rouding')
    t.equal(res.statusCode, 200)
  })
})
```

**Comment by StarpTech** [comment]
According to https://github.com/fastify/fastify/blob/5dfec548f890277cfc2b2f4653e4dd3889af2b3c/lib/reply.js#L684 the serialization step is skipped entirely for strings.

This can be seen here https://github.com/fastify/fastify/blob/main/lib/reply.js#L156

From the developer's perspective, it feels odd that numbers are handled but strings are skipped. The decision should be made if a schema was passed or not.

**Comment by tnishimura** [comment]
Perhaps the behavior should be that if a response schema is specified, the response is always treated as `application/json` and serialized? However, this may cause confusion because if you specify `{type : "string"}` as the output and do `reply.send("hello")`, the value returned will not be `hello` but instead be `"hello"` with double quotes, since that's what JSON strings look like...

**Comment by StarpTech** [comment]
> Perhaps the behavior should be that if a response schema is specified, the response is always treated as application/json and serialized?

Yes, I have the same in mind but you already found out that the current behavior is a solution to cover all the edge cases.

I think we should throw an error when a schema is specified and a string is sent. For all other cases, the user can overwrite the serialization function.

**Comment by mcollina** [comment]
> @fastify/core I think we should throw an error when a schema is specified and a string is sent. For all other cases, the user can overwrite the serialization function.

I'm not convinced, I think we should be more nuanced. I think we should _always_ pass through the serializer if one is set. Currently we do not support `{ type: "string" }` (a top-level JSON string) as a response schema.

**Comment by StarpTech** [comment]
> I'm not convinced, I think we should be more nuanced. I think we should always pass through the serializer if one is set. Currently we do not support { type: "string" } (a top-level JSON string) as a response schema.

I agree, that's consistent. So in the case of a primitive response value (int, string) + schema, we assume that the user expects the raw value instead JSON values `"value"`?

**Comment by mcollina** [comment]
Yes, exactly.

**Comment by CalogeroMandracchia** [comment]
Hello! Sorry for writing in a closed issue. I didn't understand if top-level string is not supported at all or it should be supported if a schema is given and content-type is set to json.

I wrote this code and if I didn't make any mistake, it's not supported at all.

```js
import fastJson from 'fast-json-stringify';
import Fastify from 'fastify';

//shared schema
const mainSchema = { type: 'object', properties: { key: { type: "string" } } };

//fast-json-stringify
console.log( fastJson(mainSchema)("hello") ); // => {}

//fastify
const fastify = Fastify();
fastify.get('/hello', 
    { schema: { response: { 200: mainSchema } } },
    (req, rep) => rep.type('application/json').send("hello")
);
console.log( (await fastify.inject({ method: 'GET', url: '/hello' })).body ); // => hello
```
I would be happy to try to implement a solution with a little help!

**Comment by Eomm** [comment]
The serialization is skipped if the object that is being sent is a string|buffer|stream or null.
So, the fast-json-stringify function is not executed.

The rationale here is that: all the payloads that are not ready to be transmitted through the HTTP response must be serialized.

So the assumption is that, if the user is sending a string|buffer|stream or null, the serialization phase work can be avoided to speed up the process.

I would suggest to use `reply.serialize()` to force it to run:

```
app.get('/', {
  schema: {
    response: {
      '2xx': {
        type: 'object', properties: { key: { type: "string" } }
      }
    }
  }
}, async function readTodos (request, reply) {
  return reply.serialize('hello')
})
```

**Comment by CalogeroMandracchia** [comment]
Thank you!! `reply.serialize()` works like a charm!
I do return strings sometimes and even if your explanation makes perfect sense I find it a little error-prone but I guess there is no way around it, it must be this way.
Now I have one more reason to use `jest-json-schema` for matching the API response with its own schema :)
Thank you again for answering me on Sunday!
