### ISSUE TITLE
Calling `fastify.close()` promise after hitting a route doesn't resolve

### ISSUE THREAD

**Issue by jason-wihardja** [fastify/fastify#3126]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Node.js version

14.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

The `fastify.close()` promise being called after hitting a route doesn't do anything. The `onClose` hook is not even called.

### Steps to Reproduce

Here's a simple code to demonstrate the issue

```
'use strict';

const fastify = require('fastify')({
    logger: true
});

fastify.get('/ping', async (request, reply) => {
    const result = {
        message: 'PONG'
    };

    setTimeout(async () => {
        console.debug('Server Closing');
        await fastify.close();
        console.debug('Server Closed');
    }, 2500);

    return result;
});

fastify.addHook('onClose', async (instance, done) => {
    console.log('Inside onClose');
    return done();
});

fastify.listen(3000, '0.0.0.0');
```

After starting the server and hitting `/ping` route once, it is expected that the server closing sequence should be executed after 2.5s (as specified in the timeout function). However, `fastify.close()` promise never resolves and thus blocking the complete close sequence from happening. The log inside `onClose` hook is also never executed.

### Expected Behavior

The `fastify.close()` promise should resolve after some time and the program continues with the rest of the server closing sequences

**Comment by mcollina** [comment]
The above code works perfectly here by calling the route with `curl`.

**Comment by jason-wihardja** [comment]
Did the `fastify.close()` resolves? I was expecting the logs to be
```
Server Closing
Inside onClose
Server Closed
```

But on my machine what happens after I curl `/ping` once is
```
Server Closing
```

**Comment by mcollina** [comment]
Yes it resolves. Note that you should not mix callbacks and promises.

**Comment by jason-wihardja** [comment]
Yes, I'm aware of that. But I purposefully mix them here to demonstrate the issue. Do you have any idea as to what else could be causing this issue on my side? Because for some reason it doesn't resolve on my machine. It only resolves after I made a second or a couple more curl to the route

**Comment by mcollina** [comment]
> But I purposefully mix them here to demonstrate the issue.

That's not supported, essentially those two syntaxes are mutually exclusive.

**Comment by jason-wihardja** [comment]
Ok, so I tried converting them all to callback style, which results in the following code
```
'use strict';

const fastify = require('fastify')({
    logger: true
});

fastify.get('/ping', (request, reply) => {
    const result = {
        message: 'PONG'
    };

    setTimeout(() => {
        console.debug('Server Closing');
        fastify.close((cb) => {
            console.debug('Server Closed');
        });
    }, 1000);

    reply.send(result);
});

fastify.addHook('onClose', (instance, done) => {
    console.log('Inside onClose');
    done();
});

fastify.listen(3000, '0.0.0.0');
```

But apparently the same issue still happens.
