### ISSUE TITLE
404 error for requests with invalid uri encoding

### ISSUE THREAD

**Issue by rburgst** [fastify/fastify#3127]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Node.js version

14.16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

when receiving a http request that contains invalid url encoding I get the following log output

```
07:48:34 ✨ incoming request GET xxx /%C0
07:48:34 ⚠️  the default handler for 404 did not catch this, this is likely a fastify bug, please report it
07:48:34 ⚠️  └── / (ACL)
    / (BIND)
    / (CHECKOUT)
    / (CONNECT)
    / (COPY)
    / (DELETE)
    / (GET)
    / (HEAD)
...
```

As stated in #1884, the result should actually be a 400 and we should not log errors to the log.

### Steps to Reproduce

Setup an empty default project
```bash
mkdir my-app
cd my-app
npm init fastify
npm install
npm run dev
```

Then send the following request (e.g. via `httpie`)
```bash
http 'localhost:3000/%c0'
```

### Expected Behavior

The server should return a 400 and not log errors to the log.

**Comment by mcollina** [comment]
This might be a bug in find-my-way

**Comment by climba03003** [comment]
I cannot reproduce the same behavior as yours.

Here is the snippets I used.
```js
const fastify = require("fastify");

const app = fastify({ exposeHeadRoutes: false, logger: "trace" });
app.get('/:strangeId', (req, reply) => {
  reply.send({ strangeId: req.params.strangeId })
})

app.listen(3000);
```

Response.
```
{"error":"Bad Request","message":"'%c0' is not a valid url component","statusCode":400}
```

If your project is empty and not registered any route. Throwing `404` is the correct behavior because it do not have a matching route for the parsing. So, I will not consider it as a bug.
@mcollina @Eomm WDYT?

**Comment by mcollina** [comment]
The bug is that the request is apparently caught by the not found handler of the not found handler. This should not be possible.

**Comment by Eomm** [comment]
@climba03003 the issue is that we reach this statement:

https://github.com/fastify/fastify/blob/506009f6198e5ce0d0c16ecb61dbf62902d9aa5b/lib/fourOhFour.js#L167

and we should not

Moreover the custom 404 handler is not executed:

```diff
+app.get('/', (req, reply) => {
  reply.send({ strangeId: req.params.strangeId })
})

app.setNotFoundHandler(function (request, reply) {
    reply.send('NOT EXECUTED AT ALL')
})
```

**Comment by climba03003** [comment]
To clarify, throwing `404` is the expected result, but we should not fire the `fourOhFourFallBack` and it should be properly handled by `fastify`. Is that right?

**Comment by Eomm** [comment]
Yes, it is 👍🏽

**Comment by climba03003** [comment]
Symptom
1. Not registered any route will trigger this behavior
2. Regitered only `/` route will trigger this behavior

Problem Breakdown
1 . `fastify` build route in https://github.com/fastify/fastify/blob/main/fastify.js#L166
2 . it register default route in https://github.com/fastify/fastify/blob/main/fastify.js#L563-L568
3 . which will look up the `fourOhFour` route in https://github.com/fastify/fastify/blob/main/fastify.js#L179
~4 . it will fallback to the default route in https://github.com/fastify/fastify/blob/master/lib/fourOhFour.js#L40~
~5 . which will be the handler of https://github.com/fastify/fastify/blob/main/lib/fourOhFour.js#L154-L170~
6 . as we call empty setNotFoundHandler in https://github.com/fastify/fastify/blob/main/fastify.js#L381
7 . we should be registered a `basic404` for `/*` in https://github.com/fastify/fastify/blob/main/lib/fourOhFour.js#L107-L112
8 . as a result, step 4 and step 5 should never reached

**Comment by climba03003** [comment]
Flow
When invalid route reached `fastify`
1. it will reach normal router
2. it will reach `fourOhFour` router
3. It is calling `Router.prototype.lookup`
4. It go to `wildcard route` handling
5. it break in https://github.com/delvedor/find-my-way/blob/59a954db3c1487309d45753a17dce40b71d198a1/index.js#L481-L485

Reason behind
`fourOhFour` router do not have `onBadUrl` handler passed in and `find-my-way` will break when both `url is invalid` and `onBadUrl` is not exist.
As a result, no route is actually reached then the `/*` route registered for `basic404` is not reached as well. Finally, it will fallback to the default route in https://github.com/fastify/fastify/blob/main/lib/fourOhFour.js#L154-L170

@mcollina @Eomm 
I think the fix should be add `onBadUrl` handler to `fourOhFour` router?

**Comment by mcollina** [comment]
> I think the fix should be add `onBadUrl` handler to `fourOhFour` router? It may have side effect of all invalid url cannot not reach `404`.

Thanks for the analysis, this is correct! Good job. Would you send a PR?

We might ship this as a semver-major change.
