### ISSUE TITLE
Missing param when mixing parametric and wildcard routes

### ISSUE THREAD

**Issue by happypoulp** [fastify/fastify#3129]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.16.2

### Node.js version

14.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

Hello,

When defining 2 routes (one parametric and one wildcard) such as:
- route 1: /:lang/item/:id
- route 2:/:lang/item/*

Fastify fails at parsing parameter `lang` for the route 2, and only the `*` is present in `request.params`.

### Steps to Reproduce

Here is a reproducible use case:
```js
const fastify = require('fastify')({ ignoreTrailingSlash: true })

const handler = (request, reply) => {
  reply.send(`Parsed params: ${JSON.stringify(request.params)}\n`)
}

// Example: http://localhost:4003/fr/item/12345
fastify.get('/:lang/item/:id', handler)

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// ISSUE on this route, `request.params` is missing param `"lang": "fr"`
// Example: http://localhost:4003/fr/item/12345/edit
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
fastify.get('/:lang/item/*', handler)

fastify.listen(4003)
```

Then run:
```
curl http://localhost:4003/fr/item/1234/edit
```

### Expected Behavior

When running:
```
curl http://localhost:4003/fr/item/1234/edit
```

I expect to receive as response:
```
{"lang":"fr","*":"1234/edit"}
```

but instead I get:
```
Parsed params: {"*":"1234/edit"}
```
As you can see, the `lang` param is missing from the list of params.

Thanks.

**Comment by mcollina** [comment]
This is likely an issue in [find-my-way](https://www.npmjs.com/package/find-my-way), our router. It's probably a simple thing to fix, if somebody would like to take a stab at it.

**Comment by mcollina** [comment]
cc @delvedor wdyt?

**Comment by delvedor** [comment]
Yes, it looks like an issue in the router.

**Comment by AyoubElk** [comment]
This is probably because you are declaring a route: `/:lang/item/:id`, and hitting `/fr/item/1234/edit` which has a suffix `/edit`
My understanding is that having `/edit` would make the router match the wildcard route, which would be the expected behavior

**Comment by climba03003** [comment]
@delvedor 
Tracing Log
```
lookup start /fr/item/12345/edit

pathLen 19, path: /fr/item/12345/edit, prefix: /
longest common prefix 1
parametric route /item/12345/edit [ 'fr' ]

pathLen 16, path: /item/12345/edit, prefix: :
longest common prefix 0
pathLen 16, path: /item/12345/edit, prefix: /item/
longest common prefix 6
parametric route /edit [ 'fr', '12345' ]

pathLen 5, path: /edit, prefix: :
longest common prefix 0
pathLen 5, path: /edit, prefix: /
longest common prefix 1

return using _getWildcardNode

lookup end /fr/item/12345/edit
```

I think the problem is, when the route contain `*`. It may fall into `_getWildcardNode` and which only set `*` for the params.
https://github.com/delvedor/find-my-way/blob/59a954db3c1487309d45753a17dce40b71d198a1/index.js#L554

**Comment by mcollina** [comment]
looks like a good bug indeed :/. Could you attempt a fix @climba03003 ?

**Comment by climba03003** [comment]
@mcollina 
https://github.com/delvedor/find-my-way/pull/194
Here it is.

**Comment by happypoulp** [comment]
Is there a `fastify` release planned soon that will update `find-my-way` to `v4.3.0` ?

**Comment by mcollina** [comment]
You can just update your dependencies, it will be picked up automatically.
