### ISSUE TITLE
304 Not Modified should not require a return value

### ISSUE THREAD

**Issue by mattbishop** [fastify/fastify#3133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Node.js version

14.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

GET handlers that support conditional GETs will return status 304 Not Modified to indicate the cached representation has not changed. According to the spec, they must not return a body:

https://datatracker.ietf.org/doc/html/rfc7232#section-4.1

fastify, however, requires the handler to return `null`, stating only `204` responses can return `undefined`. This should be changed to include `304` as a status that does not return a body.

### Steps to Reproduce

Add this handler to a fastify server instance:

```js
  server.get("/", (req, rep) => {
    rep.status(304)
  })
```

The call it with `GET /`

### Expected Behavior

return status code should be: `304 Not Modified`

Instead I get the 204 No Content error. I have to do this in the handler instead:

```js
  server.get("/", (req, rep) => {
    rep.status(304)
    return null
  })
```

**Comment by zekth** [comment]
Technically i'd say your not sending anything from your route.
```js
fastify.get('/',async (request, reply) => {
  reply.status(304).send()
})
```
would be the thing to do. Moreover you should write
```js
fastify.get('/',async (request, reply) => {
  return reply.status(304).send()
})
```

**Comment by mattbishop** [comment]
Fair enough, but this is different behaviour to `204` status codes. I would think they should be consistent as neither returns a body.

**Comment by mcollina** [comment]
Could you please you try installing the next branch? I think the behavior there would match your expectations.

**Comment by zekth** [comment]
Indeed. So i assume refering to the spec we should add 304 also to the statuscode check in this statement : https://github.com/fastify/fastify/blob/d904fce65f0a173e900461412c3905aa30388918/lib/wrapThenable.js#L19

@mcollina do you agree?

**Comment by mcollina** [comment]
We have removed all special behavior for 204s in next

**Comment by mattbishop** [comment]
I'll have to make a clean project to test fastify/fastify#next as it breaks other plugins I have in my project right now (websockets, compress) due to version errors.
