### ISSUE TITLE
Returning payload didn't send to client when hooking in route-level with async function

### ISSUE THREAD

**Issue by seia-soto** [fastify/fastify#3135]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Node.js version

14.16.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

The expected result is Fastify should send payload(body of HTTP response) to client when I `return` object or string in async function in one of route's preHandler, or such hooks. However, the payload(body) is only sent over to client when I manually code with `reply.send` method, otherwise the result of handler's original function will be sent instead. In this situation, I think when I code hooking function to return payload before original function does, it should be sent over client preventing execution of original function.

### Steps to Reproduce

Following code snippets can be put into route's `preHandler` or `preValidation` property (hook.js respectly).

Code returning unexpected result (returns 1 in status):
```js
export default async (request, response) => {
  return { status: 0 }
}
```

Code returning expected result (returns 0 in status):
```js
export default async (request, response) => {
  response.send({ status: 0 })
  return // NOTE: This is important because Fastify won't stop executing original function at this time.
}
```

Now, prepare the main server.
```js
import fastifyFactory from 'fastify'

import hookFn from './hook'

const fastify = fastifyFactory()

fastify.route({
  url: '/test',
  method: 'GET',
  preHandler: hookFn,
  handler: async (req, res) => {
    return { status: 1 }
  }
})

fastify.listen(3000)
```

### Expected Behavior

Fastify should send body of returned object or string from async hook function in route-level.

**Comment by mcollina** [comment]
Do you consider this a bug or a feature request? I don't think this was ever implemented or documented, but maybe I may be wrong.

I think we should target v4 / the `next` branch for this change.

**Comment by seia-soto** [comment]
I cannot fully understand how Fastify works right now (reading source code), but at this time, I think this issue is one of patch or feature request as I found documentation about this. However, I think it can be more clear if patch available. At this time, I think it's better to update documentation to reference route-level-hook section of Hooks docs from route options section of Routes docs to fix this unclear(maybe only for me) behavior.

**References**

- https://www.fastify.io/docs/latest/Hooks/#respond-to-a-request-from-a-hook
- https://www.fastify.io/docs/latest/Routes/#routes-options

**Comment by mcollina** [comment]
Let's aim for a doc fix then.
Where did we write that returning a value from a hook will send a response?

**Comment by jsumners** [comment]
The linked documentation is rather clear that you must send the response with `reply.send` and then `return reply` in asynchronous functions.

**Comment by seia-soto** [comment]
Yes, it's really clear that I need to write both `send` and `return`. However, adding a reference in another page which I refed in previous comment would be nice. How do you think?

**Comment by jsumners** [comment]
> Yes, it's really clear that I need to write both `send` and `return`. However, adding a reference in another page which I refed in previous comment would be nice. How do you think?

According to the original issue post, you expected the opposite to be true. I am stating that I am not clear how that is expected given that you have linked the documentation clearly stating what the requirements are.

Any pull request to improve the documentation is most welcome.

**Comment by seia-soto** [comment]
> > Yes, it's really clear that I need to write both `send` and `return`. However, adding a reference in another page which I refed in previous comment would be nice. How do you think?
> 
> According to the original issue post, you expected the opposite to be true. I am stating that I am not clear how that is expected given that you have linked the documentation clearly stating what the requirements are.
> 
> Any pull request to improve the documentation is most welcome.

My idea was simple. I thought that I can stop Fastify keep processing the request by sending the response from hook. Then to make response, I need to return stringify-able object or string in async handler. So I expected that Fastify will send response if I return stringify-able thing in async hooks. However, the behavior was different and I thought this was an issue or unexpected behavior, so opened the issue.

Maybe my though is based on the ways other web server libs on Node.JS do. So by turning my biases down, the issue can be resolved. However, for my case, I think it is bit hard to find that section(early response in hook level) if I follow the sections written in Fastify routing docs.

Please, give me feedback if you feel some description is not clear. I am not familar with English.

**Comment by seia-soto** [comment]
I made a simple pull request to resolve this. But one thing, I want to hear feedback as the start of this was just my suggestion and didn't come up before.
