### ISSUE TITLE
Logger calls result in multiple log entries where a single entry is expected

### ISSUE THREAD

**Issue by srigar** [fastify/fastify#3137]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.16.0

### Node.js version

12.18.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Using default fastify logger and it is working well in all places except GCP stackdriver. It is logging each property in object as a separate entry. 

2021-06-16 11:52:39.751 IST gcr-io-gcp-xxxxxx  **res: {**  
2021-06-16 11:52:39.751 IST gcr-io-gcp-xxxxxx  **"statusCode": 200**  
2021-06-16 11:52:39.751 IST gcr-io-gcp-xxxxxx  **}**  

### Steps to Reproduce

`app = fastify({
            prettyPrint: true,
            messageKey: 'message',
});
`

### Expected Behavior

It should have single entry in stack driver instead of multiple.

**Comment by zekth** [comment]
This is because you're using `prettyPrint`. In production environment you should not use it. Use something like:
```js
app = fastify({ prettyPrint: process.env.NODE_ENV!=='production', messageKey: 'message', });
```

**Comment by climba03003** [comment]
It is the expected result for `prettyPrint` enabled. If you need single line JSON, disable `prettyPrint` or follow the suggestion of zekth.

Read more about `pino` can help you understand it. https://github.com/pinojs/pino

If you need all the thing to be single line and preserve some of the feature for `prettyPrint`. You need to create your custom transport for `pino`. Read more on https://github.com/pinojs/pino/blob/master/docs/transports.md#transports
