### ISSUE TITLE
Request.url is misnamed

### ISSUE THREAD

**Issue by dopry** [fastify/fastify#3146]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x.x

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

Request.url is misnamed. 

A url contains a scheme at a minimum and further validation is defined by the scheme, but the general structure is scheme://[authority@]host[:port]/path. The request.url actually returns the path component of the request URL. 

for reference see: https://url.spec.whatwg.org/#url-representation

### Steps to Reproduce

```js
export default async function Server(fastify, opts) {
  fastify.get('/*', async (request, reply) => {
    const url= request.url
    return { url }
  })
}
```

`fastify start example.mjs`

`curl localhost:3000/some/path`

the response is `{ "url": "/some/path" }`

### Expected Behavior

1. Variables named for standards reflect said standards
2. The response is `{ "url": "http://localhost:3000/some/path" }`
3. There is an additional property request.path for getting just the path.

**Comment by climba03003** [comment]
It is a getter which return the `node` request url. `fastify` should behave the same as the `node` core.
https://github.com/fastify/fastify/blob/main/lib/request.js#L111
