### ISSUE TITLE
Emojis not showing up correctly in Fastify, but works in Express 

### ISSUE THREAD

**Issue by IsmaeelAkram** [fastify/fastify#3157]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.0

### Node.js version

14.16.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

Emojis are getting corrupted and not showing up correctly in response. It is not an issue with the browser or code because the equivalent code in Express sends emojis correctly.

I know I can use HTML codes but this is still an issue and a disadvantage to Express.

### Fastify Code:
```typescript
import fastify from 'fastify';

const app = fastify({ logger: true });
const PORT = 8000 || process.env.PORT;

app.get('/', async (req, reply) => {
	reply.header('Content-Type', 'text/html').send('<h2>👋 Hey there!</h2><p>This is the root of the Airline Management system. Take a look at the tests to see how the API works.</p>');
});

const start = async () => {
	try {
		await app.listen(PORT);
	} catch (error) {
		app.log.error(error);
		process.exit(1);
	}
};

start();
```

### Fastify Response:
![image](https://user-images.githubusercontent.com/19865145/123339049-df2a7d80-d517-11eb-9837-3f7f802f1d98.png)

---

### Express Code:
```typescript
import express, { Request, Response } from 'express';

const app = express();
const PORT = 8000 || process.env.PORT;

app.get('/', async (req: Request, res: Response) => {
	await res.setHeader('Content-Type', 'text/html');
	await res.send('<h2>👋 Hey there!</h2><p>This is the root of the Airline Management system. Take a look at the tests to see how the API works.</p>');
});

const start = async () => {
	try {
		await app.listen(PORT);
	} catch (error) {
		process.exit(1);
	}
};

start();
```
### Express Response:
![image](https://user-images.githubusercontent.com/19865145/123338984-c28e4580-d517-11eb-8c22-fdbcb029ff5a.png)

### Expected Behavior

Emojis would show up properly.

**Comment by jsumners** [comment]
Send the text as UTF-8.

**Comment by Eomm** [comment]
```
reply.header('Content-Type', 'text/html; charset=utf-8')
```
will solve

Maybe could it worth add the charset if the user doesn't set it?

**Comment by mcollina** [comment]
I think the only thing we might want to change is adding some docs about this. I don't think we should change anything here.

**Comment by IsmaeelAkram** [comment]
> I think the only thing we might want to change is adding some docs about this. I don't think we should change the behavior here.

Agreed. I thought it was some sort of bug. It didn't cross my mind to use UTF-8. 😅

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by IsmaeelAkram** [comment]
Sure, which doc would I put it in though?

**Comment by IsmaeelAkram** [comment]
I made a pull request to change the docs. #3159
