### ISSUE TITLE
Wrong status code throwing an object

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3160]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.0

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

In https://github.com/fastify/fastify/pull/2134 we introduced the possibility to throw an object as the spec admit.

In a sync route, the throws of an object won't set the 500 status code
This will prevent the execution of the error handler too

### Steps to Reproduce

```
const fastify = require('fastify')({ logger: true })

fastify.get('/a', function (request, reply) {
  throw { appCode: 418 } // status 200
})

fastify.get('/b', async function (request, reply) {
  throw { appCode: 418 } // status 500
})


fastify.setErrorHandler(function (_, request, reply) {
  console.log('CUSTOM ERROR HANDLER')
  reply.status(500).send({ ok: false })
})

fastify.listen(8080)
```

### Expected Behavior

The `/a` route should return the 500 status code if the user didn't customize it yet

**Comment by meehawk** [comment]
@Eomm just resuming work on #3081. Can I take this up next? A brief on what needs to be done would be nice

**Comment by Eomm** [comment]
> Can I take this up next? A brief on what needs to be done would be nice

You can go for it! I think that PR may take a while to be released because it impacts the external interface

The issue should be here:
https://github.com/fastify/fastify/blob/a791bf83c6555f02294d66021982059eea9b5a46/lib/handleRequest.js#L125-L128

I would just start with a set of failing tests:
- one that checks the response error and status code via fastify.inject
- one that checks that a custom status code set by the user is not overwritten
- one that checks the `setErrorHandler` trigger
