### ISSUE TITLE
Tests are failing for the lowest supported Nodejs version

### ISSUE THREAD

**Issue by sergiz** [fastify/fastify#3163]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

main

### Node.js version

10.16.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

If you checkout the master branch and run the test suite using Nodejs v10.16.0, it will fail due to stream.Readable.from not being a function in 10.16.0 since it was added in 10.17.0 (https://nodejs.org/api/stream.html#stream_stream_readable_from_iterable_options).

The CI runs only the latest Nodejs major versions. It should also run the lowest supported version in order to catch such situations in time.

### Steps to Reproduce

Checkout master branch and run "npm test" using Nodejs v10.16.0.

### Expected Behavior

Test suite to pass.

**Comment by jsumners** [comment]
According to our CI configuration, we support `Node 10` -- https://github.com/fastify/fastify/blob/7c1bcd176c6a1aaeef3d07f5c079c2d503013f08/.github/workflows/ci.yml#L19

That means we support the _most recent_ version of Node 10. As of this date, that is 10.24 -- https://nodejs.org/dist/latest-v10.x/

**Comment by sergiz** [comment]
According to the package.json which is an authority here you support v10.16.0 or higher ;)
https://github.com/fastify/fastify/blob/7c1bcd176c6a1aaeef3d07f5c079c2d503013f08/package.json#L117-L119

**Comment by sergiz** [comment]
@jsumners, according to the package.json, which is an authority here, you support v10.16.0 or higher ;)
https://github.com/fastify/fastify/blob/7c1bcd176c6a1aaeef3d07f5c079c2d503013f08/package.json#L117-L119

**Comment by jsumners** [comment]
The `package.json` should be updated. Personally, I would remove the whole `engines` block. But @mcollina or @delvedor may have a reason for it to be there.

**Comment by zekth** [comment]
Meanwhile i agree with @jsumners as people tend to be using and staying tied to LTS versions; some corporate cases might lead you to slower upgrades. In this case it would be nice to be noticed by the warning of npm in case of incompatibility like explained above (which is a 2 years old version).

By this way we need to ensure we support versions from the `package.json` and we need to do it for all versions with a pattern like:
```json
  "engines": {
    "node": "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0"
  },
```

So instead of using this in the CI:
```yaml
 node-version: [10, 12, 14, 16] 
```
We will need to write a job to read `package.json` and extract node versions to generate a matrix to feed the child jobs with the node version. (I can work on it)

**Comment by mcollina** [comment]
We only support the last version of any Node.js LTS line. Giving any stronger guarantees is unfeasible (due to CI limit). Unfortunately we cannot really specify this in the `engine` field... so I guess the only solution is to remove it.

**Comment by zekth** [comment]
Unfortunately npm does not support LTS https://github.com/npm/npm/issues/11113

So +1 on dropping it.

**Comment by sergiz** [comment]
Doesn't LTS apply to major version only? So you are saying that fastify supports only the very latest of every LTS version (meaning latest patch version)? That's kinda weird requirement since new minor and patch versions of the LTS release are released every few weeks.

By the way, the readme still very clearly states the following:

> Requirements
> 
> Node.js v10 LTS (10.16.0) or later.
