### ISSUE TITLE
2.x  application/json put message body FST_ERR_CTP_INVALID_CONTENT_LENGTH

### ISSUE THREAD

**Issue by gclb** [fastify/fastify#3174]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

2.8.0

### Node.js version

8

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.14.3 (18D42)

### Description

FastifyError [FST_ERR_CTP_INVALID_CONTENT_LENGTH]: FST_ERR_CTP_INVALID_CONTENT_LENGTH: Request body size did not match Content-Length
    at IncomingMessage.onEnd (/data-nodejs/node_modules/@zbj/orochi-ts/node_modules/fastify/lib/contentTypeParser.js:177:18)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

relevant code:
```
function onEnd (err) {
    req.removeListener('data', onData)
    req.removeListener('end', onEnd)
    req.removeListener('error', onEnd)

    if (err !== undefined) {
      err.statusCode = 400
      reply.code(err.statusCode).send(err)
      return
    }

    if (asString === true) {
      receivedLength = Buffer.byteLength(body)
    }
    // receivedLength link getDefaultJsonParser  count < contentLength (limit 1)
    if (!Number.isNaN(contentLength) && receivedLength !== contentLength) {
      reply.send(new FST_ERR_CTP_INVALID_CONTENT_LENGTH())
      return
    }

    if (asString === false) {
      body = Buffer.concat(body)
    }

    var result = parser.fn(req, body, done)
    if (result && typeof result.then === 'function') {
      result.then(body => done(null, body), done)
    }
  }
```
### Steps to Reproduce

This phenomenon occurs occasionally when requesting big data content in JSON format post request

### Expected Behavior

Use 3.x core technology in 2.x.
```
if (!Number.isNaN(contentLength) && (payload.receivedEncodedLength || receivedLength) !== contentLength) {
      reply.send(new FST_ERR_CTP_INVALID_CONTENT_LENGTH())
      return
}
``` 
because our typescript can't upgrade above 3. X

**Comment by jsumners** [comment]
Please see our long term support document -- https://www.fastify.io/docs/latest/LTS/

Support for the 2.x line ended months ago.

**Comment by gclb** [comment]
This problem can only be fixed by patch package. There is a disadvantage in this way, and the fastifly version must be fixed, otherwise the patch will automatically fail.

The specific steps are as follows：

1、Install patch
```
yarn add patch-package --dev 
```

2、update node_moudle/fastifly/lib/contentTypeParser.js source code 
First, locate the row of the `rawbody` function [ reference: v2.8.0 line 120 ]

```
function rawBody (request, reply, options, parser, done) {
  var asString = parser.asString
  var limit = options.limit === null ? parser.bodyLimit : options.limit
  var contentLength = request.headers['content-length'] === undefined
    ? NaN
    : Number.parseInt(request.headers['content-length'], 10)

  if (contentLength > limit) {
    reply.send(new FST_ERR_CTP_BODY_TOO_LARGE())
    return
  }

  var receivedLength = 0
  var body = asString === true ? '' : []
  var req = request.raw
  var context = (reply.context || {}).config || {};

  if (asString === true) {
    req.setEncoding('utf8')
  }

  req.on('data', onData)
  req.on('end', onEnd)
  req.on('error', onEnd)

  function onData (chunk) {
    receivedLength += chunk.length

    if (context.receivedEncodedLength && receivedLength > limit) {
      req.removeListener('data', onData)
      req.removeListener('end', onEnd)
      req.removeListener('error', onEnd)
      reply.send(new FST_ERR_CTP_BODY_TOO_LARGE())
      return
    }

    if (asString === true) {
      body += chunk
    } else {
      body.push(chunk)
    }
  }

  function onEnd (err) {
    req.removeListener('data', onData)
    req.removeListener('end', onEnd)
    req.removeListener('error', onEnd)

    if (err !== undefined) {
      err.statusCode = 400
      reply.code(err.statusCode).send(err)
      return
    }

    if (asString === true) {
      receivedLength = Buffer.byteLength(body)
    }
    if (!Number.isNaN(contentLength) && (context.receivedEncodedLength || receivedLength) !== contentLength) {
      reply.send(new FST_ERR_CTP_INVALID_CONTENT_LENGTH())
      return
    }

    if (asString === false) {
      body = Buffer.concat(body)
    }

    var result = parser.fn(req, body, done)
    if (result && typeof result.then === 'function') {
      result.then(body => done(null, body), done)
    }
  }
}
```

3、Run Patch package
If the project is found, the 'patches' patch package will be generated automatically
```
npx patch-package fastify
```

4、Add package.json run script
_This command needs to be executed prior to startup or initialization_
```
"scripts": {
    "postinstall": "patch-package"
},
```
