### ISSUE TITLE
Suggestion: Incorporate json-schema-to-ts by default

### ISSUE THREAD

**Issue by rattrayalex** [fastify/fastify#3178]
## 🚀 Feature Proposal

Use the `schema` prop of the the `opts` param to infer the type parameters `Body`, `QueryString`, `Response`, etc, for automagical TS types for request params/responses/bodies with no explicit typing.

## Motivation

Unify and simplify the story of having amazing TS types for requests and responses. 
Make the json schemas more useful and easier to verify as correct.

## Example

```ts
import Fastify from "fastify";

const fastify = Fastify();

const todo = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    description: { type: 'string' },
    done: { type: 'boolean' },
  },
  additionalProperties: false,
  required: ['name'],
} as const;

const schema = {
  body: todo,
  response: {
    200: todo,
  },
} as const;

fastify.post('/todo', { schema }, async (req, reply) => {
  const { body: todo } = req;
  todo.name // string
  todo.description // string | undefined
  todo.notthere // type error

  if (showReply) {
    reply.send(todo); // typechecked
    return;
  }

  return todo; // also typechecked
});
```

This allows the user to not spell out their types to Fastify manually:
```ts
fastify.post<{ Body: FromSchema<typeof todo>, Response: FromSchema<typeof todo> }>(
  '/todo', 
  { schema }, 
  async (req, reply): Promise<FromSchema<typeof todo>> => {
    // ...
  }
);
```

**Comment by mcollina** [comment]
@fastify/typescript my knowledge of this is not deep enough to check if it's even possible.

**Comment by zekth** [comment]
I really like the idea as it will definitely simplifies the code and developer experience of typescript developers without impacting the JS codebase itself.

I have 2 things that comes to my mind:
- We need to ensure that this won't break anything in the current state of the typings. Or it would be only available on next fastify version.
- This uses complete schemas with `additionalProperties`, `type` and such. Current issue is some of those properties are inherited from the fastify instance and we have also the shorthand declaration of the schemas. See the work done for JTD implementation: https://github.com/fastify/fastify/pull/3156

I definitely thinks it's worth giving a shot to a prototype. Correct me if i'm wrong but to achieve this we would need to inject the schema in `RouteHandlerMethod` https://github.com/fastify/fastify/blob/ff6bd7e6f2b1a499617c396cd7497d8a54681c17/types/route.d.ts#L77

**Comment by mcollina** [comment]
I'm +1 if things needs to be added in v4.

**Comment by climba03003** [comment]
I don't know if it is worth doing. From my understanding it only works if you specify the schema with variables.

Following use case is not available.
- `$ref` and `addSchema`
- 3-party json-schema creation tools. e.g. `fluent-json-schema`, `typebox`, etc.
- Response cannot be restricted as it need to compare with `status code`

**Comment by delvedor** [comment]
I like the idea of improving the dev experience, especially in pain points like this one.
But what happens if a user wants to change the schema-to-ts library? Is it possible?
Keeping it swappable should be required, like we are doing for the json schema validation.

**Comment by ilias-t** [comment]
Yeah love this idea—I would also be pretty great to do a similar thing with a type definition file generated from an [oas](https://swagger.io/specification/) file using a tool like [openapi-typescript](https://www.npmjs.com/package/openapi-typescript). In theory that could alleviate the need to type each route specifically and fastify would know all the types for each route.

The oas file could be generated from something like code comments using a tool like [swagger-inline](https://github.com/readmeio/swagger-inline). This could allow for a single source of truth to validate the schemas for each route with matching type definitions.

**Comment by Uzlopak** [comment]
Is there already some openapi to fastify cli?

It would make sense to use openapi schema to create a fastify app with stubs. Like you take the petstore and scaffold the app. Would make it necessary to give each route a operationId, and as the openapi schema should be complete, we also use refs. As refs usually have names, we can use them to map them to types. 

Only stuff like versioning of paths would need some extra care.

Maybe the routehandlers call the stubs, which are the actual implementation. So when you modify the opeapi schema you allow to overwrite the types and routehandlers, but not the potentially modified stubs. 

This would be so cool. You would go to swagger hub, take a schema, and then you would scaffold the service. Then you "just" fill the stubs with the right functionality and thats it.. you have now a new service with identical API

**Comment by gurumaxi** [comment]
If you are using typescript, to have an automatic `json-schema-to-ts` integration in your handler you can simply override the FastifyTypeProviderDefault interface in your `global.d.ts` file like this:

```
import fastify from 'fastify';
import type {JSONSchema7, FromSchema} from 'json-schema-to-ts';

declare module 'fastify' {
    interface FastifyTypeProviderDefault {
        output: this['input'] extends JSONSchema7 ? FromSchema<this['input']> : never;
    }
}
```

**Comment by RafaelGSS** [comment]
Actually, you can just use the `@fastify/type-provider-json-schema-to-ts`. I don't see `fastify` incorporating `json-schema-to-ts` by default. Instead, one can use the _Type Providers_ to achieve the same goal. I'm closing this issue, feel free to re-open it if you have a stronger opinion.
