### ISSUE TITLE
querystring json schema $ref causes an error in the log

### ISSUE THREAD

**Issue by MoJo2600** [fastify/fastify#3181]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.1

### Node.js version

14.16.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Using `$ref` to reference a shared schema in a request querystring results in the message `ERROR (21429 on 87b2c2b6ca9f): Cannot read property 'type' of undefined` in the debug log.

We are using `$ref` to reference to a shared json schema for our fastify bodies and responses, which is working fine. Only querystring does not behave the same way.

### Steps to Reproduce

The `$ref` in `querystring` leads to the message `Cannot read property 'type' of undefined` while the `$ref` in `response` is working.

Add a `$ref` to reference a shared schema in `querystring`.

```typescript
{
  schema: {
    operationId: 'listAccountRequests',
    querystring: {
      $ref: 'common.json#/definitions/RequestListQuerystring',
    },
    response: {
      200: {
        $ref: 'common.json#/definitions/RequestList',
      },
    },
  },
},
```
`common.json` 

```json
{
  "$id": "common.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "RequestListQuerystring": {
      "additionalProperties": false,
      "properties": {
        "search": {
          "description": "The search term to search for",
          "type": "string"
        },
      },
      "type": "object"
    },
    "RequestList": {
      "additionalProperties": false,
      "description": "A requested accounts list result.",
      "properties": {
        "data": {
          "items": {
            "$ref": "#/definitions/RequestListItem"
          },
          "type": "array"
        },
        "pages": {
          "description": "The number of pages found",
          "type": "number"
        },
        "total": {
          "description": "The number of total items found.",
          "type": "number"
        }
      },
      "required": [
        "data",
        "total",
        "pages"
      ],
      "type": "object"
    }
  ...
  }
}
```

### Expected Behavior

`$ref` is working for `querystring` the same way it is for `response` or `body`

**Comment by climba03003** [comment]
I think it is just typo?
You are referring `common.json#/definitions/RequestListQueryParams` and I can only see `RequestListQuerystring` in `common.json`.

**Comment by MoJo2600** [comment]
@climba03003 Thanks for the hint, I double checked and updated the issue above. If I reference a non existing schema fastify will fail with an exception `Failed building the validation schema for XXX due to error can't resolve reference #/definitions/XXX from ...` which makes sense. With the correct schema, the error is as described. So it seems to me like it resolves the reference but the schema is `undefined`.

**Comment by climba03003** [comment]
I cannot reproduce the same behavior like yours.
Here is my snippets.
```ts
import Fastify from "fastify";

const fastify = Fastify();

fastify.addSchema({
  $id: "common.json",
  $schema: "http://json-schema.org/draft-07/schema#",
  definitions: {
    RequestListQuerystring: {
      additionalProperties: false,
      properties: {
        search: {
          description: "The search term to search for",
          type: "string",
        },
      },
      type: "object",
    },
    RequestList: {
      additionalProperties: false,
      description: "A requested accounts list result.",
      properties: {
        data: {
          items: {
            $ref: "#/definitions/RequestListItem",
          },
          type: "array",
        },
        pages: {
          description: "The number of pages found",
          type: "number",
        },
        total: {
          description: "The number of total items found.",
          type: "number",
        },
      },
      required: ["data", "total", "pages"],
      type: "object",
    },
    RequestListItem: {
      type: "string",
    },
  },
});

fastify.get(
  "/",
  {
    schema: {
      body: {
        $ref: "common.json#/definitions/RequestListQuerystring",
      },
      response: {
        200: {
          $ref: "common.json#/definitions/RequestList",
        },
      },
    },
  },
  function (request, reply) {
    console.log(request.query);
    reply.send({});
  }
);

fastify.listen(3000);
```

**Comment by MoJo2600** [comment]
You are right. It seems to be a side effect on my side somewhere. Thank you for your time. I will try to figure out why it is not working in my project.
