### ISSUE TITLE
reply.server is not defined

### ISSUE THREAD

**Issue by dbuccella** [fastify/fastify#3182]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Plugin version

3.0.0

### Node.js version

15.2.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

The docs state that reply.sender stores:
The Fastify server instance, scoped to the current encapsulation context.
It seems it is always undefined. 
Has this changed? is there any other place in the either the request or reply where the server instance is stored.
It is not always convenient to make everything into a plugin or pass around the instance to imported files.

### Steps to Reproduce

in apiRoutes.js:

```
const handlers= require('myhandlers.js');
fastify.route({method:'GET', path: '/api/user', handler: myhandler.getUsers});

```
in myhandlers.js:

```
function getUsers(req, reply) {
    // get redis
    const redis= reply.server.redis;
    // use redis ...
}
```
reply.server is undefined

### Expected Behavior

reply.server should be populated with fastify instance with all decorators

**Comment by RafaelGSS** [comment]
Can you create a minimal reproducible example?

**Comment by dbuccella** [comment]
The above should be enough. The reply object passed to the handler does not have a .server property.

**Comment by RafaelGSS** [comment]
No, the above is not enough. I can't reproduce your issue. Likely you just not decorated the `reply.server`

**Comment by climba03003** [comment]
I have try different method for the handler registration and I cannot reproduce the bug.
`reply.server` works as expected.
Repo Link: https://replit.com/@climba03003/fastify-issue-3182

**Comment by Eomm** [comment]
The feature you are talking about has been released in v3.17
https://github.com/fastify/fastify/releases/tag/v3.17.0

**Comment by climba03003** [comment]
Oh, I see. He is on `3.15.1` and need to update for the feature.

**Comment by dbuccella** [comment]
That was it. Updated to 3.17.0 and now reply.server is pointing to the instance.
Thanks!
