### ISSUE TITLE
`fastify.close()` promise is not resolved

### ISSUE THREAD

**Issue by arkerone** [fastify/fastify#3186]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.0

### Node.js version

14.17.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.10

### Description

When I catch the SIGINT signal to graceful shutdown the server, the method close is "blocked" but only when I visit a route on a browser (it's ok when I use `curl`). I must reload the page twice to close the server.

### Steps to Reproduce

Try this simple code :
```
const Fastify = require('fastify')

const fastify = Fastify({
  logger: true
})

process.on('SIGINT', async () => {
  try {
    await fastify.close()
    process.exit(0)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
})

fastify.get('/', (request, reply) => {
  reply.send('Hello world')
})

fastify.listen(3000, (err) => {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
})
```
Visit [http://localhost:3000](http://localhost:3000) in a browser and exit the app with CTRL+C, the server doesn't close. Visit the page again (twice in my case) and the server is closing.

**Comment by Eomm** [comment]
> Visit the page again (twice in my case) and the server is closing.

Could you check the network in the browser console if there are pending connections?
Moreover, could you add the logger at debug level and add the tracing?

**Comment by jsumners** [comment]
Sounds to me like the browser is using an HTTP keepalive connection whereas `curl` does not.

**Comment by arkerone** [comment]
> Sounds to me like the browser is using an HTTP keepalive connection whereas `curl` does not.

Yes the browser is using an HTTP keepalive connection but with a 5sec timeout, after this delay the socket should be destroyed.

**Comment by zekth** [comment]
It's the expected behaviour as i read tests: https://github.com/fastify/fastify/blob/493d2531740152c806aa197bbca592cf395d504b/test/close.test.js#L204-L239

**Comment by mcollina** [comment]
I would recommend you to use https://github.com/mcollina/close-with-grace for graceful shutdown.

There are almost infinite reasons why your process might not shut down gracefully in a real-world example.

In this case I think it's just the socket is being kept open for some reason. You might want to change the keepalive timeout.

**Comment by arkerone** [comment]
> I would recommend you to use https://github.com/mcollina/close-with-grace for graceful shutdown.
> 
> There are almost infinite reasons why your process might not shut down gracefully in a real-world example.
> 
> In this case I think it's just the socket is being kept open for some reason. You might want to change the keepalive timeout.

Thanks ! I wanted to make sure this was the normal behavior. I close this issue.
