### ISSUE TITLE
Route Metadata

### ISSUE THREAD

**Issue by VottusCode** [fastify/fastify#3188]
## 🚀 Feature Proposal

Introduce something like "metadata" for route definitions. This would allow hooks to know more about the route, eg. if it needs authorization, etc..

## Motivation

During the transition from middleware-based Express to Fastify, I've many times faced this issue. I have some decorators in place, for ex. `req.user`, and it would be nice if that same hook could also send an error response if the user is not authorized on auth-only route.

## Example

```ts
import fastify from "fastify"

const app = fastify()

app.get("/auth-only", { meta: { authOnly: true } }, async (req, res) => {
  // route logic
})

app.addHook("onRequest", async (req) => {
  const user = //;

  if (req.routeMeta.authOnly && !user) {
    return res.send({ error: "you are not unauthorized" })
  }
})
```

**Comment by Eomm** [comment]
You can already do it in the Fastify way.
It means that you can run the `onRequest` hook only when needed, not for every route that doesn't need the hook: it would be a performance pitfall

```js
const fastify = require('fastify')({ logger: false })
fastify.addHook('onRoute', function routeHook (routeOptions) {
  console.log(routeOptions.config)

  if (routeOptions.config.meta === 'hello') {
    routeOptions.onRequest = hook
  }
})

fastify.get('/', { config: { meta: 'hello' } }, async (request, reply) => {
  return { hello: 'world' }
})

function hook (request, reply, done) {
  console.log('meta hook')
  done()
}

fastify.inject('/')
```

**Comment by VottusCode** [comment]
> 
> 
> You can already do it in the Fastify way.
> It means that you can run the `onRequest` hook only when needed, not for every route that doesn't need the hook: it would be a performance pitfall
> 
> ```js
> const fastify = require('fastify')({ logger: false })
> fastify.addHook('onRoute', function routeHook (routeOptions) {
>   console.log(routeOptions.config)
> 
>   if (routeOptions.config.meta === 'hello') {
>     routeOptions.onRequest = hook
>   }
> })
> 
> fastify.get('/', { config: { meta: 'hello' } }, async (request, reply) => {
>   return { hello: 'world' }
> })
> 
> function hook (request, reply, done) {
>   console.log('meta hook')
>   done()
> }
> 
> fastify.inject('/')
> ```

Alright, thanks a lot!
