### ISSUE TITLE
Links pointing at v8.x node documentation

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#3193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.1

### Node.js version

14.17.3

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Documentation that have links to the node documentation are pointing at https://nodejs.org/dist/latest-v8.x/docs/api/.
As v10 is the minimum version tested on/supported by Fastify v3.x, this should probably be pointed at https://nodejs.org/dist/latest-v10.x/docs/api/.

Happy to open a PR to fix this, just wanted to discuss/raise it first!

### Steps to Reproduce

- Navigate to https://github.com/fastify/fastify/blob/main/docs/Server.md#http2
- Click on `HTTP/2` link in section

**Comment by climba03003** [comment]
I will always prefer latest document.

**Comment by jsumners** [comment]
If the linked docs are equivalent in the latest docs then updating the reference is acceptable. Otherwise, we need to determine if our docs are still correct.

**Comment by Shinyaigeek** [comment]
I will also prefer fastify's docs linked to the latest node.js’s docs from the point of view of one library user’s position. (saving the time and effort of updating docs is also important!)

If it is ok, Shall I work on this updating docs?

**Comment by mcollina** [comment]
I'm to update all references to v14.x. I don't think it should be without version.

Go ahead and make the change!
