### ISSUE TITLE
typescript binding for printRoutes() doesn't take options

### ISSUE THREAD

**Issue by dannydulai** [fastify/fastify#3194]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

Latest

### Plugin version

n/a

### Node.js version

n/a

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

n/a

### Description

the offending code is here:

https://github.com/fastify/fastify/blob/main/types/instance.d.ts#L375

the documentation is here:

https://github.com/fastify/fastify/blob/23371945d01c270af24f4a5b7e2e31c4e806e6b3/docs/Server.md#printroutes

### Steps to Reproduce

n/a

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by matthyk** [comment]
Can be closed due to #3196
