### ISSUE TITLE
Request hangs when returning in `setErrorHandler`

### ISSUE THREAD

**Issue by amis-shokoohi** [fastify/fastify#3209]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

v3.19.2

### Node.js version

v16.2.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

This type of code works in route handlers and `setNotFoundHandler`:
```js
reply.code(someCode)
return { msg: "someMsg" }
```
but it doesn't work in `setErrorHandler`, it just hangs when doing it like that.

### Steps to Reproduce

```js
// index.js
import Fastify from 'fastify'

const fastify = Fastify({ logger: true })

fastify.route({
  method: 'GET',
  url: '/',
  handler: function (request, reply) {
    const err = new Error('ERROOOR')
    err.statusCode = 400
    throw err
  }
})

fastify.setNotFoundHandler(function (request, reply) {
  reply.code(404)
  return { msg: 'Not Found' }
})

fastify.setErrorHandler(function (error, request, reply) {
  const statusCode = error.statusCode
  if (statusCode == 400) {
    // Hangs here
    reply.code(statusCode)
    return { msg: error.message }
  }
  reply
    .code(500)
    .send({ msg: 'Internal Server Error' })
})

fastify.listen(8080)
```
Run `node index.js` and then try `curl http://localhost:8080/ -v`

**Comment by MSE99** [comment]
You're using a synchronous error handler (it doesn't return a promise) you need to call `reply.send` or use an async function that returns whatever you wanted to be included in the reply body.

**Comment by mcollina** [comment]
Given we support synchronous route handler, we should support synchronous not found handlers. This should be quite simple to add, I've tagged it as good first issue.

**Comment by weiliddat** [comment]
I'll be working on this in my fork https://github.com/weiliddat/fastify/tree/3209. 
Anyone else is welcome to work in parallel/together, and I'll be glad to guide anyone who's new to it and wants to learn :)

**Comment by amis-shokoohi** [comment]
@weiliddat I would really like to help out, but I'm a newbie. I don't know where to start. 🤷‍♂️

**Comment by MSE99** [comment]
@amis-shokoohi a good way to start is by writing a failing test that will pass once you finish implementing the feature, you need to locate where in fastify's source code the error handler is invoked (take a look at `lib/reply.js` ).
