### ISSUE TITLE
Lastest Joi breaks for querystring validation

### ISSUE THREAD

**Issue by bhanuc** [fastify/fastify#321]
Fastify version: 0.29.0,
Joi Version: 11.1.1
Sample Code to replicate issue: 
```
'use strict'

const fastify = require('fastify')();
const Joi = require('joi');


const schema = {
    schema: {
      querystring: Joi.object().keys({
        password: Joi.string()
      }).required()
    },
    schemaCompiler: function (schema) {
      return schema.validate.bind(schema)
    }
  }
fastify
  .get('/', schema, function (req, reply) {
    reply
      .send({ hello: 'world' })
  })

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
}) 
```
Err thrown on console -> TypeError: Cannot read property 'bind' of undefined  on line -`return schema.validate.bind(schema)` in schemaCompiler function.
Error originates from - https://github.com/fastify/fastify/blob/master/lib/validation.js#L53 where opts.schema.querystring.type is actually a function, but shouldn't be. 
I can send a PR to fix it.

**Comment by delvedor** [comment]
Hi! Thank you for checking out the project!
Have a look at our [documentation](https://github.com/fastify/fastify/blob/master/docs/Validation-And-Serialize.md#schema-compiler), `Joi` should be handled in a slightly different way :)

**Comment by bhanuc** [comment]
@delvedor Thanks for prompt reply. Had followed the documentation on the website which was displaying the old method, seems it has also gotten updated since then. Loved the integration with joi, was starting a new project and fastify seemed to fit the bill. Would love to get involved with the project.
