### ISSUE TITLE
Why the latest Fastify reply object cannot be Promise.resolve？

### ISSUE THREAD

**Issue by VVGR** [fastify/fastify#3216]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.2

### Plugin version

latest

### Node.js version

14.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

This problem has been bothering me for a few days. I can enter the normal Promise.then callback using 2.0.1, but not with the latest version. I don't know why? The simplified code is as follows

```javascript
const fastify = require('fastify')({ logger: true })

// Declare a route
fastify.get('/', (req, res) => {
  Promise.all([Promise.resolve(req), Promise.resolve(res)]).then((data) => {
    // The latest version is not implemented here
    let [request, response] = data
    response.send({msg : 'hello world'})
  })
})


// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```
To execute the file, visit the url: http://127.0.0.1:3000/
The 2.0.1 version can execute the callback normally, but the latest 3.19.2 cannot execute normally, please help to find out what is the problem? thanks

### Steps to Reproduce

1、Install the latest fastify npm package
2、create a new index.js file, paste the above code, use `node index` to execute, 
3、visit http://127.0.0.1:3000/, return normally
{
msg: "hello world"
}

### Expected Behavior

return

```javascript
{
msg: "hello world"
}
```

**Comment by climba03003** [comment]
`reply` object implemented `.then` in `fastify@2.9.0` which will resolve and consume the `stream` right away when `Promise.resolve`.

I assume this syntax is not supported for latest `fastify@2`.

**Comment by VVGR** [comment]
@climba03003 Thank you for your answer. My problem should be the reason. Thanks again
