### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by stfullstack** [fastify/fastify#3236]
Hi. Really enjoying working with this framework.

I am unable to run async validations. This seems quite fundamental to a framework (i.e registration checking if email is unique for eg.)

**Comment by zekth** [comment]
Can you share a reproductible example of what you re trying to do?

**Comment by mcollina** [comment]
Asynchronous data validation is an anti-pattern: don't do it.

Synchronous data validation is needed to check if the format of the data is correct. Asynchronous data validation perform some logic around said data to validate that the user could perform a certain action.
This is normally done inside Fastify Hooks, not data validation.

**Comment by stfullstack** [comment]
I wish to check if a) empty email, invalid email or if the email already exists in an account. The response must be returned as an array of errors for the frontend. Could you please provide an example of how this would work without using async validation and using hooks?

Thanks

**Comment by zekth** [comment]
To do this you can use a proper json schema check for empty email / invalid email see: https://json-schema.org/understanding-json-schema/reference/string.html#email-addresses

Regarding the check if the email already exists you can do it in your handler.

**Comment by stfullstack** [comment]
Thanks. Unfortunately this won't return all the errors in an array, instead I will get the errors from the schema validation and then a separate error from inside the handler for any async errors. 

This would also mean that if multiple fields have to do async validation in the handler the error messages on the response are going to be unpredictable.

Consider the following example:

A user creates a bank transaction with the following fields:
payee, amount, date, category name.

The category name should be unique. The payee, amount and date are required. A user posts data containing an empty payee and date and a category name that is not unique.

The server response will contain that the payee and date fields are required but it will not mention the category is not unique; the category field will appear valid as it won't show any error... If the user then posts with payee and date fields populated and the same un-unique category name it will only then state that the category field is not unique. I hope that makes sense.

**Comment by climba03003** [comment]
> 
> 
> Thanks. Unfortunately this won't return all the errors in an array, instead I will get the errors from the schema validation and then a separate error from inside the handler for any async errors.
> 
> This would also mean that if multiple fields have to do async validation in the handler the error messages on the response are going to be unpredictable.
> 
> Consider the following example:
> 
> A user creates a bank transaction with the following fields:
> payee, amount, date, category name.
> 
> The category name should be unique. The payee, amount and date are required. A user posts data containing an empty payee and date and a category name that is not unique.
> 
> The server response will contain that the payee and date fields are required but it will not mention the category is not unique; the category field will appear valid as it won't show any error... If the user then posts with payee and date fields populated and the same not unique category name it will only then state that the category field is not unique. I hope that makes sense.

You can enable `ajv` to return all errors.
https://ajv.js.org/options.html#allerrors

**Comment by stfullstack** [comment]
@climba03003 this won't return the async errors though

**Comment by climba03003** [comment]
> 
> 
> @climba03003 this won't return the async errors though

Then, I suggest you to use `preValidation` hooks, for checking all the `async validation` if field exist then store it in `request.<name it yourself>`
Afterward, implement `customErrorHandler` to collection `err` and `request.<name it yourself>` merge it together then return it.

**Comment by stfullstack** [comment]
Surely patching things together in a separate handler isn't the best practice approach is it? 

What I'm asking for here is very common place I think?

**Comment by climba03003** [comment]
> 
> 
> Surely patching things together in a separate handler isn't the best practice approach is it?
> 
> What I'm asking for here is very common place I think?

As the `validation` stage is internal process and you cannot customize it with sync or async. You can only seperate it into two stage if you want the internal validation stage process.

If you can do it all your own, pass a custom validator compiler which always return `true`. Do all your works in any other hooks after `preParsing`.

**Comment by climba03003** [comment]
For your approach, `ajv` already check if data structure is correct or not. And it seems to me you will process the data no matter is data structure is correct or not which means you will need to check the data twice. This is strange to me.

For example,
when `ajv` already check the email is wrong. Your own function have no idea which field is invalid. You need to either analysis the `ajv` error or check it again yourself. Then forward to async validation like checking unique email inside database.

In my eyes, `ajv` is actually useless. You can just disable the validation stage and use any hooks between `parsing` and `handler`.

**Comment by stfullstack** [comment]
Thanks for assisting. I think I have something here that can work for me. Small side note: I'm using a custom validation library called `fastest-validator` instead of the standard `ajv`. Can you see any flaws in this approach I have thrown together for this message:

```js
import fastify from 'fastify';
import FastestValidator from 'fastest-validator';

async function main() {
  const app = fastify();

  // custom error handler for validation handling
  app.setErrorHandler((err, req, rep) => {
    if (err.validation) {
      rep.status(400).send({ errors: err.validation });
      return;
    }
    rep.status(500).send({ error: 'Something went wrong' });
  });

  // set validation compiler to always succeed due to custom handler in `preValidation` hook
  app.setValidatorCompiler(() => () => true);

  // handle validation errors with fastest-validator library
  app.addHook('preValidation', async (req) => {
    for (const key of ['body', 'header', 'querystring']) {
      const schema = req?.context?.schema?.[key]?.properties;
      if (!schema) {
        continue;
      }
      
      // compile and validate request schema
      const validate = new FastestValidator().compile(schema);
      const res = await validate(req[key]);

      // successful validation?
      if (res === true) {
        continue;
      }

      // throw validation errors for custom error handler to deal with
      const err = new Error();
      err.validation = res;
      throw err;
    }
  });

  // fast-validator validation with `recordExists` custom async function to check if email already exists in db
  // all fields are required here
  const schema = {
    body: {
      name: 'string',
      email: 'email|required|normalize|recordExists:users,email',
      password: 'string|min:8',
    },
  };

  app.post('/register', { schema }, async (req, rep) => {
    return { success: 1 };
  });

  await app.listen(3001);
}

main().then();
```

**Comment by zekth** [comment]
Closing as it was answered.
