### ISSUE TITLE
Fastify instance is any when imported using require() in VS Code

### ISSUE THREAD

**Issue by velopert** [fastify/fastify#3244]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.1

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Description

I am planning to write a Fastify tutorial for beginners.
I personally use TypeScript when I use Fastify and it works great.
It also works great when I import it after enabling ECMAScript modules and use `import`.

For beginners, I want to teach them how to use Fastify with pure JavaScript first, and then introduce them how to use ECMAScript module or TypeScript.

If I follow the code from the Quick Start, the app is not typed properly in VS Code.

![image](https://user-images.githubusercontent.com/17202261/128749604-22cf4759-7a1b-4909-8f46-34d27e433db0.png)

To make it typed properly, I have to edit the code as so:

```javascript
const { fastify } = require('fastify')
// Require the framework and instantiate it
const app = fastify({ logger: true })

// Declare a route
app.get('/', async (request, reply) => {
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await app.listen(3000)
  } catch (err) {
    app.log.error(err)
    process.exit(1)
  }
}
start()
```

![image](https://user-images.githubusercontent.com/17202261/128750227-a67a6a2e-96fc-407b-a304-8832ee28513c.png)

Alternative solution is adding a line to fastify.d.ts for developers who are importing it with CommonJS module system.

```diff
export { fastify }

+ export = fastify
```

![image](https://user-images.githubusercontent.com/17202261/128751401-c401a359-9b1a-4721-bcf8-ae0995cafda2.png)

I wish either docs or fastify.d.ts file gets updated.

### Steps to Reproduce

Follow the guide from QuickStart with VS Code

### Expected Behavior

fastify instance should not be typed as `any` in VS Code

**Comment by climba03003** [comment]
Unless TypeScript provide a better exportation system. The following will conflict with each another.

```ts
export default fastify // https://github.com/fastify/fastify/blob/main/fastify.d.ts#L51
export { fastify } // https://github.com/fastify/fastify/blob/main/fastify.d.ts#L179

export = fastify // It is not compatible for the above two exportation.
```

We can not fulfill all the 3 aspect of user as it is the known limitation of TypeScript exportation.

**Comment by velopert** [comment]
Cool!
Thanks for reply.
