### ISSUE TITLE
Cannot recycle an existing app: "listening" prevents restarting an existing web application

### ISSUE THREAD

**Issue by benderTheCrime** [fastify/fastify#325]
Seen here: https://github.com/fastify/fastify/blob/master/fastify.js#L76

I'm unable to start a fastify instance that has been closed as a result of the listening on close. This should be easily fixable, so I'll make a quick attempt!

**Comment by delvedor** [comment]
Hi!
You can't recycle an instance, because [avvio](https://github.com/mcollina/avvio), our plugin manager does not allow that.
The recommended method is to have a builder function that bootstraps a new Fastify instance every time you need it.

```js
const Fastify = require('fastify')

function build (opts) {
  const fastify = Fastify(opts)
  fastify.register(require('./plugin'))
  ...
  return fastify
}
```
In this way if you call `close` you will shoutdown the current instance, and if you need a new one just use again the build function.

We guarantee the load order and the close order of the plugins, the "reboot" is not supported and is not our plan to support it, because is out of the fastify scope :)

**Comment by benderTheCrime** [comment]
Thanks for getting back to me! Truth be told I tried to do this last night and was met with some pain.

I see what you're saying, but exporting a single instance of a service and scaffolding a new one each time I would like to restart are two different things fundamentally. They are not really interchangeable.

**Comment by delvedor** [comment]
> but exporting a single instance of a service and scaffolding a new one each time I would like to restart are two different things fundamentally.

Maybe I'm missing the point, what you want to do?

Remember that use the `close` api will trigger all the `onClose` hooks, for example if you are using a database connector (such as [`fastify-mongodb`](https://github.com/fastify/fastify-mongodb)), the connection to the database will be closed.
The only way to reopen it is to rebuild a new instance of fastify :)

**Comment by benderTheCrime** [comment]
Right, I don't think you missed the point. I want to close and then restart an existing fastify instance. I trust you're right that it's not possible, but a factory is not the same as stopping and restarting an instance!

**Comment by benderTheCrime** [comment]
Couldn't I just start/stop the underlying `fastify.server` independent of the fastify `listen` method?

**Comment by delvedor** [comment]
Ah ok!
Yeah, is not the same thing, but at the moment is the way to do it :D
Why do you need to restart the same exact instance?

**Comment by delvedor** [comment]
> Couldn't I just start/stop the underlying fastify.server independent of the fastify listen method?

You can, fastify exposes the raw server instance of the http server, you can access it via `fastify.server`.

**Comment by StarpTech** [comment]
@benderTheCrime It's uncommon to restart a server. In terms of fault tolerance, it's much safer and best practice to come back in a clear state and this is only possible with a new and fresh restart.

**Comment by benderTheCrime** [comment]
It's a pretty wonky use case, but the short answer is: the actual fastify instance is an export.

I've tested starting and stopping with the `fastify.server` and this works quite well, thanks!

**Comment by benderTheCrime** [comment]
@StarpTech you're probably right about this being a minimal use case, but truth be told, I'd rather have the capability of doing so than not!
