### ISSUE TITLE
The res parameter in the fastify 'onRequest' hook is not an class methods of Node.js ServerResponse

### ISSUE THREAD

**Issue by deni5n** [fastify/fastify#3252]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.2

### Node.js version

16.6.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The documentation at the link "https://www.fastify.io/docs/v1.13.x/Hooks/" says that in the onRequest hook, the res parameter is a Node.js **ServerResponse** class, but the ServerResponse methods (write, end, etc.) are not available. Instead, the reply (status, send, etc.) methods of the **Fastify** are available

Is this a bug in the documentation? 

### Steps to Reproduce

add hook 
```
fastify.addHook('onRequest', (req, res, next) => {
   res.write('res.write is not a function') // error here
   res.end()
 })
```

### Expected Behavior

methods of the http.ServerResponse class are available

**Comment by zekth** [comment]
You're checking the documentation of the version `1.13` and using version `3.19.2`
