### ISSUE TITLE
Following docs using $id with addSchema() gives "data.properties should be object" error

### ISSUE THREAD

**Issue by tlhunter** [fastify/fastify#3255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.1

### Node.js version

16.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

5.10.13

### Description

I'm using the following example from the [Fastify docs](https://www.fastify.io/docs/v1.13.x/Validation-and-Serialization/#shared-schema):

```js
const fastify = require('fastify')()

fastify.addSchema({
  $id: 'greetings',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})

fastify.route({
  method: 'POST',
  url: '/',
  schema: {
    body: {
      type: 'object',
      properties: {
        greeting: 'greetings#',
        timestamp: { type: 'number' }
      }
    }
  },
  handler: () => {}
})

fastify.listen(3000); // added this line
```

Note that the final line was added.

Upon executing the file I get the following error:

```
FastifyError: Failed building the validation schema for POST: /, due to error schema is invalid: data.properties should be object
    at Boot.<anonymous> (/app/node_modules/fastify/lib/route.js:308:19)
    at Object.onceWrapper (node:events:513:28)
    at Boot.emit (node:events:406:35)
    at /app/node_modules/avvio/boot.js:153:12
    at /app/node_modules/avvio/plugin.js:270:7
    at done (/app/node_modules/avvio/plugin.js:202:5)
    at check (/app/node_modules/avvio/plugin.js:226:9)
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
     at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
```

### Steps to Reproduce

1. Copy example code to a file
2. Append the final listen line
3. Execute file

### Expected Behavior

According to the docs, I would expect this to allow the validation to be added to the endpoint.

When I modify the example to not use the schema $ref/registry pattern, and instead use an inline schema, it seems to work fine.

**Comment by climba03003** [comment]
You are using `1.13.x` document but using `3.20.1` for the package.

**Comment by tlhunter** [comment]
Whoops! Thanks DDG
![2021-08-12_21-26-59](https://user-images.githubusercontent.com/551402/129304843-82a710c3-8884-487b-a639-17888449516d.png)
