### ISSUE TITLE
Fastify silently exits if conflicting routes

### ISSUE THREAD

**Issue by danthegoodman1** [fastify/fastify#3258]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.2

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

big sur

### Description

If there are 2 conflicting routes inside of a `server.register(indexRoutes, { prefix: '/indexes' })` for example, fastify will silently exit after a few seconds.

### Steps to Reproduce

inside the `indexRoutes.ts` file that `indexRoutes` (from the description) const imports: `import indexRoutes from '../routes/indexes'`

```ts
server.get<{ Params: { index_uid: string } }>('/:index_uid/settings', async (req, res) => {
    res.send()
  })

server.get<{ Params: { index_uid: string } }>('/:index_uid/settings', async (req, res) => {
    res.send()
  })
```

If I do not have both of these, I get an additional log of the server starting:

```
[1628885210774] INFO (64534 on Dans-MaxBook-Pro.local): Server listening at http://0.0.0.0:7700
[1628885210775] DEBUG (64534 on Dans-MaxBook-Pro.local): Starting Admin API server on port 7700
```

However, when both routes are present, I only get the following log:

```
[1628885158071] DEBUG (64471 on Dans-MaxBook-Pro.local): Starting Admin API server on port 7700
```

This log comes from:

```ts
export function StartServer() {
  server.listen(7700, '0.0.0.0', () => {
    logger.debug('Starting Admin API server on port 7700')
  })
}

```

### Expected Behavior

An error should be thrown when there are conflicting routes.

**Comment by mcollina** [comment]
Can you please include a full example to reproduce?

**Comment by mcollina** [comment]
From your example, the first argument to listen() is an error if it is there. You are actually ignoring it.

**Comment by danthegoodman1** [comment]
See that would make sense… thanks!
