### ISSUE TITLE
Does fastify contain cors ?

### ISSUE THREAD

**Issue by wuchuwei** [fastify/fastify#326]
Does fastify contain cors 
thx

**Comment by StarpTech** [comment]
Good question. We should definitely support this as a plugin. @delvedor WDYT.

**Comment by StarpTech** [comment]
We could take [this](https://github.com/hapijs/hapi/blob/master/lib/cors.js) as a template.

**Comment by delvedor** [comment]
It is not supported in core, but it could be a perfect plugin!

**Comment by mcollina** [comment]
you can use the http://npm.im/cors module through our middleware support.

**Comment by StarpTech** [comment]
Example
```js
const cors = require('cors')
fastify.addHook('onRequest', cors())
```

@mcollina but we don't provide a way to attach specific middleware to a route correct?

**Comment by mcollina** [comment]
@StarpTech it should be `fastify.use(cors())`.

**Comment by gj** [comment]
>@mcollina but we don't provide a way to attach specific middlewares to a route correct?

This looks like it does the trick: https://github.com/fastify/middie#restrict-middleware-execution-to-a-certain-paths

**Comment by mcollina** [comment]
closing as it should be solved.

**Comment by rodrigooler** [comment]
@wuchuwei use `fastify.use(cors()).`

https://github.com/fastify/fastify/issues/326#issuecomment-333533755

**Comment by mcollina** [comment]
I think we should do a plugin for cors.

If you look at: https://github.com/expressjs/cors#enabling-cors-pre-flight, you can see how they define the options route for a request.

IMHO our plugin should define `fastify.enableCors('*')` (or a specific path) that goes and creates that options route.

Side note, the following might just work together with the `cors` widdleware:

```js
fastify.route({
  method: 'OPTIONS'
  path: '*'
}, (request, reply) => { reply.send() })
```

@zhaoyao91 let me know if that works for you.

**Comment by OhIAmFine** [comment]
Thanks for your advices, we made it successfully. @mcollina 

In our practice, when we send a preflighted request  by XMLHttpRequest in client, it will  first send an options request, so we make it successfully by using  [cors](https://www.npmjs.com/package/cors) and fastify.options in our plugins .

```
 fastify.use(cors())
 fastify.options('*', (request, reply) => { reply.send() })
```

**Comment by delvedor** [comment]
I'm working on a plugin :)

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1076 :)

**Comment by SarasArya** [comment]
> Thanks for your advices, we made it successfully. @mcollina @zhaoyao91
> 
> In our practice, when we send a preflighted request by XMLHttpRequest in client, it will first send an options request, so we make it successfully by using [cors](https://www.npmjs.com/package/cors) and fastify.options in our plugins .
> 
> ```
>  fastify.use(cors())
>  fastify.options('*', (request, reply) => { reply.send() })
> ```

But you have write it in every file if you are using prefix
