### ISSUE TITLE
GET request payload validation error

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#3266]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.1

### Node.js version

14.15

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.6

### Description

Fastify currently parses the request payload from `DELETE` requests but not from `GET` requests even though [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3) states the same for both methods.

> A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

and

> A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

The fact that Fastify does not parse the request payload of a `GET` request, but at the same time allows the developer to define a validation scheme for a `GET` endpoint, adds to confusing errors for the developer. So Fastify tries to validate the request payload, which was not parsed before. Thus, the client always receives the error `"body should be object"`since its request payload was not parsed and is, therefore `null` and the validation can only fail.

### Steps to Reproduce

```javascript
const app = require('fastify')()

app.get('/', {
    schema: {
        body: {
            name: {
                type: 'string'
            }
        }
    }
}, function (req, reply) {
   // req.body === null
   reply.send('ok')
})

app.listen(8080)

```

Now when a client makes the following request:

```http
GET / HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 26

{
    "name": "testName"
}
```

it always receives the response:

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body should be object"
}
```

### Expected Behavior

Fastify should therefore either parse the payload of `GET` requests, give developers a warning when they specify a body validation schema, or simply skip the body validation if it is a `GET` request.

**Comment by mcollina** [comment]
I think the behavior we actually want is to throw/error if the definition of a GET route includes a schema for the incoming payload.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
In case you or anybody else would like to take this work, target the next branch.

**Comment by matthyk** [comment]
I take over this work. 
Or should we parse the payload of `GET` requests just like `DELETE` requests so that we treat `GET` and `DELETE` requests identically?

**Comment by mcollina** [comment]
Definitely not. GET should not have bodies.

**Comment by matthyk** [comment]
Alright, then I will throw an error if a GET route includes a schema 👍

**Comment by mcollina** [comment]
You might want to do it for HEAD as well.

**Comment by climba03003** [comment]
We should behave like what the [document](https://github.com/fastify/fastify/blob/main/docs/Validation-and-Serialization.md#validation) said `validates the body of the request if it is a POST, PUT, or PATCH method.`.

If the method is not `POST, PUT or PATCH` and it specify a `body` schema. We can consider it as wrong usage and throw an error.

**Comment by jsumners** [comment]
> Definitely not. GET should not have bodies.

Agreed.

**Comment by matthyk** [comment]
Then we should change the documentation for `DELETE` and `OPTION` and throw an error for `GET` and `HEAD` if a schema is specified?

**Comment by mcollina** [comment]
Yes, that's my idea.
