### ISSUE TITLE
[FSTDEP004] FastifyDeprecation

### ISSUE THREAD

**Issue by siemah** [fastify/fastify#3284]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

3.0.0

### Node.js version

12.22.3

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

I tried to call `preParsing` hook using the async way as suggested in the documentation:

```js
fastify.addHook('preParsing', async (request, reply, payload) => {
  // Some code
  return payload;
})
```

and when i take a look at my terminal i found this warning: 

```shell
(node:37541) [FSTDEP004] FastifyDeprecation: You are using the legacy preParsing hook signature. Use the one suggested in the documentation instead.
server listening on http://[::1]:4321
```

then i tried the other way:

```js
fastify.addHook('preParsing',  (request, reply, payload, done) => {
  // Some code
  return done(null, payload);
})
```

i didnt find any warning.

### Steps to Reproduce

- Create a fastify server
- Add `preParsing` hook using the code above

**Comment by climba03003** [comment]
I cannot reproduce your problem.
https://replit.com/@climba03003/fastify-issue-3284

**Comment by siemah** [comment]
Hey @climba03003  check this code for the `server.ts`:

```js
import fastify from 'fastify';

const server = fastify();

server.register(async(app) => {
  app.addHook('preParsing', async(req, rep,pay) => {
    console.log('here from "preParsing" hook')
    return pay;
  })
  app.get('/warning', async(req, rep) => {
    return {
      hello: "azul"
    }
  })
})
server.listen(3000)
```

and this is `package.json`

```json
{
  "dependencies": {
    "fastify": "^3.20.2",
    "fastify-plugin": "^3.0.0",
    "fastify-sequelize": "^1.0.4",
    "mysql2": "^2.3.0",
    "pino-pretty": "^6.0.0"
  },
  "devDependencies": {
    "@tsconfig/node12": "^1.0.9",
    "@types/node": "^16.7.1",
    "nodemon": "^2.0.12",
    "ts-node": "^10.2.1",
    "typescript": "^4.3.5"
  },
  "scripts": {
    "dev": "nodemon src/server.ts",
    "build": "tsc -p tsconfig.json"
  }
}
```

**Note:**

This warning printted when i use fastify with ts-node and typescript

**Comment by climba03003** [comment]
@siemah 
I cannot reproduce it by using TypeScript.
![image](https://user-images.githubusercontent.com/23028015/131326948-1fd08bc5-bf17-45dc-9d2e-391d036f4c32.png)

**Comment by siemah** [comment]
@climba03003 
I create this [repos](https://github.com/siemah/fastify-hook-warning) to produce the same warning i got

**Comment by climba03003** [comment]
It should be the TypeScript transpile problem.

We test the function against `AsyncFunction` constructor and your target is `es5` which do not have `AsyncFunction`.

**Comment by siemah** [comment]
@climba03003 
I think the documentation need to be updated to inform devs to update `target` to "es2017" after generating the tsconfig using `npx tsc --init`

**Comment by climba03003** [comment]
> 
> 
> @climba03003
> I think the documentation need to be updated to inform devs to update `target` to "es2017" after generating the tsconfig using `npx tsc --init`

@siemah Feel free to send a PR for the documentation improvement.
