### ISSUE TITLE
Suggestion: Adding an official Supabase Plugin

### ISSUE THREAD

**Issue by kiyadotdev** [fastify/fastify#3286]
## 🚀 Feature Proposal

I am proposing an official [Supabase](https://supabase.io/) Plugin for Fastify. This would be similar in nature to the likes of the following official database plugins:
- [fastify-postgres](https://github.com/fastify/fastify-postgres)
- [fastify-mysql](https://github.com/fastify/fastify-mysql)
- [fastify-mongodb](https://github.com/fastify/fastify-mongodb)

## Motivation

[Supabase](https://supabase.io/) is an open source alternative to Firebase built on top of Postgres. While supabase does allow connecting to a postgres database through traditional connection methods (db name, db password, db host, etc) which can be used via the [fastify-postgres](https://github.com/fastify/fastify-postgres) plugin, they provide a robust API to access ones database (thanks to [postgREST](https://postgrest.org/en/v8.0/)).

That being said, it would be pretty cool to include a supabase plugin for the Fastify community.

## Example

An example of how this feature would be used is one could import the supabase plugin as such:

```typescript
import fastify from 'fastify';
import supabasePlugin from 'fastify-supabase';

fastify.register(supabasePlugin, {
  supabaseUrl: 'supabase-url',
  supabaseKey: 'super-secret-supabase-key'
})
```

Then the user could use the supabase plugin to interact with their database!

## Contributing

I am happy to work on an official supabase plugin if the community would find this beneficial. 🚀

**Comment by climba03003** [comment]
You can create the plugin and add it under `Ecosystem.md`  Community.

**Comment by kiyadotdev** [comment]
@climba03003 awesome, thanks! 🙏🏾

**Comment by aggmoulik** [comment]
@kiyadotdev are you still working on the plugin?

**Comment by darkgl0w** [comment]
Hello,

I have a working [`fastify-supabase`](https://github.com/coopflow/fastify-supabase) plugin, but the `fastify-supabase` name is currently used for a dummy package on npmjs.

I have contacted the current owner through his twitter and I am waiting to see if it is keen to transfer the ownership of the package name to my npmjs account.

Regards.

**Comment by ruanmartinelli** [comment]
Done! Good work on the plugin @darkgl0w, seems like you were faster than me 😄
