### ISSUE TITLE
How can i extend fastify schema? (ajv)

### ISSUE THREAD

**Issue by Dec-** [fastify/fastify#3287]
How can i extend fastify schema with custom validator for email or use ajv-format?

https://gist.github.com/robintan/b72b6c483d7dadd227fe1b67243e19be?fbclid=IwAR1KiQ6Ebut4LY0-Q-H7ByEi7qO9hXQyK7_hUB5CxX23C8z_GLbw8nX-J0U

This is not working for me.

**Comment by Eomm** [comment]
What is the error?

The email format is supported right now

**Comment by Dec-** [comment]
Its supported? how can i use it?

**Comment by Dec-** [comment]
im getting this error:

```
fastify.setSchemaCompiler(schemaCompiler);
        ^

TypeError: fastify.setSchemaCompiler is not a function
```

and when using:

```
const schemaCompiler = require('./validator');

fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schemaCompiler)
})
```

i'm getting: Failed building the validation schema for POST: /api/auth/token, due to error ajv is not defined

**Comment by climba03003** [comment]
Your example is not for the latest `fastify` version and you should follow the official document.

https://www.fastify.io/docs/latest/Validation-and-Serialization/#validator-compiler

If you face any issue, please specify the version of package you use and provide a reproducible code.
