### ISSUE TITLE
Issue while using register inside a register function

### ISSUE THREAD

**Issue by LiljebergXYZ** [fastify/fastify#329]
I'm sorry if this is a duplicate, I've been trying to see if this was a known issue or not but did not find any information.

Basically the issue that I have noticed is that if you use the `register` function to create a /parent route and then use `register` again inside that parent route, only the first route will actually be registered. 

Is this the intended behaviour, or am I just missing something?

Here is an example:

index.js
```js
const fastify = require('fastify')()

fastify.register(require('./parent.js'), { prefix: '/parent' })

fastify.listen(process.env.PORT || 3001, function (err) {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```
parent.js
```js
module.exports = function (fastify, opts, next) {
  fastify.register(require('./child1.js'), { prefix: '/child1' })
  fastify.register(require('./child2.js'), { prefix: '/child2' })
  next()
}
```
child1/child2.js
```js
module.exports = function (fastify, opts, next) {
  fastify.get('/', function(req, reply) {
    reply.send('I am child$')
  })
  next()
}
```

Thank you!

**Comment by StarpTech** [comment]
Hi @LiljebergXYZ add new routes in a seperate plugin. This is important because any plugin is encapsulated.

```js
module.exports = function (fastify, opts, next) {
  fastify.register((fastify, opts, next) => { next() }, { prefix: '/child1' })
  fastify.register((fastify, opts, next) => { next() }, { prefix: '/child2' })
  next()
}
```

**Comment by StarpTech** [comment]
I tried but it doesn't work. It look like a limitation or bug

```js
fastify.register(function (fastify, opts, next) {

    fastify.register((fastify, opts, next) => {
      fastify.get('/', function(req, reply) {
        reply.send('I am child 1')
      })
      next()
    }, { prefix: '/child1' })

    fastify.register((fastify, opts, next) => {
      fastify.get('/', function(req, reply) {
        reply.send('I am child 2')
      })
      next()
    }, { prefix: '/child2' })

    next()

})
```

- Call to `/child1` returns `I am child 1`
- Call to `/child2` returns `404`

**Comment by delvedor** [comment]
Hi! Thank you for checking out the project!
I confirm you have just spotted a bug in our prefix system :D

I'll fix that asap :)

ps, `next` should be called when you have finished your work inside your plugin, if inside a plugin you call one or more nested register you should call next once all the others have finished:
```js
function plugin (fastify, opts, next) {
  fastify.register(require('./plugin2'))
  fastify.register(require('./plugin3'), next)
}
```
Or:
```js
function plugin (fastify, opts, next) {
  fastify.register(require('./plugin2'))
  fastify.register(require('./plugin3'))
  fastify.after(() => {
    next()
  })
}
```

**Comment by mcollina** [comment]
@delvedor that should not be necessary, it's definitely a bug.

**Comment by LiljebergXYZ** [comment]
@delvedor Glad to hear I wasn't just being crazy. I sat for a long while trying to debug and see what happened, so I figured I'd submit a bug report instead.
Thanks for the info on `next()` I'll keep that in mind, cheers!

**Comment by LiljebergXYZ** [comment]
While looking into and trying to fix this, I noticed that the url that is working instead is `/parent/child1/child2`

**Comment by mcollina** [comment]
I am working on a fix, it will be out next week
