### ISSUE TITLE
Improving ease of contribution for beginner student contributors

### ISSUE THREAD

**Issue by itsmingjie** [fastify/fastify#3293]
Dear Fastify maintainers,

We're reaching out on behalf of an ongoing partnership between California State University Monterey Bay's [Computing Talent Initiative](https://computingtalentinitiative.org/) and [CodeDay](https://www.codeday.org/), a nonprofit organization. We're working on a program for college students who are new to contributing to open-source software, and we'd love to invite them to help closing some "good first issues" in your project! 

One of the goals of our program is to get more students to become comfortable with contributing to larger open source projects. A large codebase can be really intimidating to look at at first, so we'd love to invite you to host a short webcast to help students establish a mental modal of your codebase! 

If you are interested, our team (cc @SchmitzAndrew) will work with you to create/improve beginner-friendly documentation on how the code is structured, and how to get a local development environment running. We'll also provide primary mentorship to the students. In exchange, we'll need 30-45 minutes of time from a maintainer, and a commitment to be friendly to the students who are opening their first pull request. 

I'm open to discussing more below if you have questions! You can also get in touch with me directly at [mingjie@codeday.org](mailto:mingjie@codeday.org). 

Mingjie, Program @CodeDay
Berkeley CS'24

---
_If you would not like to participate, please feel free directly close this issue — sorry for the interruption!_

**Comment by govind2404** [comment]
hey! I am new to open source and I would love to get started. What should I do?

**Comment by jsumners** [comment]
We have a contributor guide at https://github.com/fastify/fastify/blob/aa9a44d86fd42ef8a25d4283bfa2b5ce4ca4056d/docs/Guides/Contributing.md

Maintainer time is provided as available and according to each contributor's schedules, desires, and goals.

**Comment by zekth** [comment]
I'm available these times, i'll send you an email. Also i think it's a good initiative indeed.

**Comment by mcollina** [comment]
We welcome every contribution however it will be unlikely we will have time to explain how to fix something step-by-step. We will expect the program organizers to help with the basics, e.g. how to run tests & the other tools, write a test and identify the initial place to start the fix.

We usually review PRs pretty quickly and there are plenty of "good first issues" tasks here and in plugins.

I can do the initial 30-45 minute call.

**Comment by itsmingjie** [comment]
Thank you @zekth and @mcollina! I'm happy to help with the next steps -- starting an email thread to start coordinating things! Will post progress/updates under this issue periodically for transparency as well.

**Comment by jsumners** [comment]
Is this issue resolved?

**Comment by zekth** [comment]
Closing as everything continues through emails.
