### ISSUE TITLE
NGINX docs

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3300]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

In https://github.com/fastify/fastify/pull/3298, we added some docs on NGINX. However the config file is not well documented. Add more inline comments on the NGINX configs.

**Comment by mcollina** [comment]
cc @jsumners

**Comment by meehawk** [comment]
Can I take this up @mcollina. Would need help to figure what needs to be done since I am not sure!

**Comment by jsumners** [comment]
> Would need help to figure what needs to be done since I am not sure!

See my comment in the linked issue.

**Comment by meehawk** [comment]
@jsumners does the task require any prerequisite knowledge? If so can you refer me to those so that I can add appropriate docs?

**Comment by jsumners** [comment]
> @jsumners does the task require any prerequisite knowledge? If so can you refer me to those so that I can add appropriate docs?

https://github.com/fastify/fastify/pull/3298#pullrequestreview-747886738

**Comment by hionnode** [comment]
If this is still up for grabs,can I add docs for nginx, the current docs are too short, should I include full instructions for setting up nginx as reverse proxy for fastify, I've set up nginx for my personal projects so hopefully I'll be able to add something here.

**Comment by climba03003** [comment]
> If this is still up for grabs,can I add docs for nginx, the current docs are too short, should I include full instructions for setting up nginx as reverse proxy for fastify, I've set up nginx for my personal projects so hopefully I'll be able to add something here.

@hionnode
I would say the current is enough but lack of explain for each setting.
But, feel free to add more on top of it. I am happen to review it.

**Comment by jsumners** [comment]
> If this is still up for grabs,can I add docs for nginx, the current docs are too short, should I include full instructions for setting up nginx as reverse proxy for fastify, I've set up nginx for my personal projects so hopefully I'll be able to add something here.

Please read the linked discussion. They should be similar to the HAProxy docs.

**Comment by meehawk** [comment]
@hionnode feel free to work on it. I figured I'm decent in NGINX but not much so to be able to doc this

**Comment by weiliddat** [comment]
Ah sorry @hionnode I just realized that you wanted to solve this. Feel free to add your PR and use whatever I've added if it's useful to you.
I guess we were working in parallel and I didn't realize you wanted to solve this issue.
