### ISSUE TITLE
Docs mention "parsed querystring" but the format is not documented

### ISSUE THREAD

**Issue by jakearchibald** [fastify/fastify#3314]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Node.js version

N/A

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

N/A

### Description

From https://github.com/fastify/fastify/blob/main/docs/Request.md

> `query` - the parsed querystring

However, the format of this property is not documented.

### Steps to Reproduce

See https://github.com/fastify/fastify/blob/main/docs/Request.md

**Comment by jakearchibald** [comment]
I guess docs should point out it's specified by https://github.com/fastify/fastify/blob/37a0ebdd5aac640e12112a3deb1b1467a6d2835d/docs/Server.md#querystringParser

**Comment by mcollina** [comment]
Thanks for the good spot! Let me know how do you find the framework @jakearchibald

**Comment by jakearchibald** [comment]
Enjoying it so far, but right now I'm just building little demos to test browser behaviour 😄
