### ISSUE TITLE
Are conditionally set decorated properties deoptimized?

### ISSUE THREAD

**Issue by chasebrewsky** [fastify/fastify#3316]
Over the past week or so I started to learn how V8 optimizes property access through shapes and inline caches by following the blog post link in the decorators documentation ([Shapes and IC](https://mathiasbynens.be/notes/shapes-ics) + [Optimizing Prototypes](https://mathiasbynens.be/notes/prototypes)). After reading this and other information I found about this topic, I was curious if the following scenario would deoptimize the example given in the decorator documentation.

In the decorator documentation, it states that the following should be avoided:

```js
fastify.addHook('preHandler', function (req, reply, done) {
  req.user = 'Bob Dylan'
  done()
})

// Use the attached user property in the request handler.
fastify.get('/', function (req, reply) {
  reply.send(`Hello, ${req.user}`)
})
```

Instead, a user should decorate the request prototype by using a decorator like so:

```js
fastify.decorateRequest('user', '')

fastify.addHook('preHandler', (req, reply, done) => {
  req.user = 'Bob Dylan'
  done()
})

fastify.get('/', (req, reply) => {
  reply.send(`Hello, ${req.user}!`)
})
```

After reading about how V8 optimizes things like property access and function calls, I realized that this example can be optimized since the same "shape" request is being passed to the route handler. Since the same shape is always passed in this example, then property lookup can take advantage of inline caches and the function can be optimized.

What I'm curious about is what would happen if the user string was conditionally set in the `preHandler` hook:

```js
fastify.decorateRequest('user', '')

fastify.addHook('preHandler', (req, reply, done) => {
  if (condition) {
    req.user = 'Bob Dylan'
  }
  done()
})

fastify.get('/', (req, reply) => {
  reply.send(`Hello, ${req.user}!`)
})
```

This would mean that based on the condition, the shape of the object going into the route handler would be different. I read [here](https://itnext.io/v8-function-optimization-2a9c0ececf5e) that after a function receives too many different shapes, it stops filling inline caches. I'm curious about a couple of things in this scenario:

1. Should conditional property setting be avoided in these types of scenarios? If that's the case, wouldn't always setting the user string in the prehandler and omitting the empty user string on the request prototype have the same performance boost from inline caches since the same shape would always reach the handler?
2. Does setting the empty user string on the request prototype instead of leaving it unset prevent repeated object property lookups by forcing there to be a "fallback" value sitting in an inline cache for each shape? When the request prototype property value is not set (ie. when decorateRequest is not used), does V8 repeatedly attempt to look up the property value in the prototype chain, or is a special null value placed in the inline cache to prevent this lookup?
3. Are there any other deoptimizations that occur by having this conditional value? Does it make it harder for TurboFan to optimize the route handler function?
4. Are there any conventions we should follow with handling decorated properties that will speed up our applications?

Thanks!

**Comment by mcollina** [comment]
@chasebrewsky take a look at https://github.com/fastify/fastify/pull/3317.

**Comment by chasebrewsky** [comment]
That's awesome. Good job on the quick turnaround, and I'm glad I could unintentionally point out a bug!
