### ISSUE TITLE
The `+` sign is replaced by a ` ` (whitespace) inside the query params

### ISSUE THREAD

**Issue by Gamote** [fastify/fastify#3326]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.3

### Node.js version

14.17.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6

### Description

If we make a request to a `GET` route, all the `+` signs are replaced with ` ` (white space).

### Steps to Reproduce

1. Define a `GET` route that is expecting a query param `search`:
```ts
type IssueQueryParams = {
  search: string;
};

app.route<{
  Querystring: IssueQueryParams;
}>({
  method: "GET",
  url: "/search",
  handler: async (request, reply) => {
    console.log(request.query);
    void reply.send(request.query);
  },
});
```

2. Make some requests to the route by adding the `search` with values that contain the `+` sign:
```bash
Request: curl --location --request GET 'localhost:3000/search?search=+12345678'
Log: { search: ' 12345678' }
Response: {"search":" 12345678"}

Request: curl --location --request GET 'localhost:3000/search?search="+12345678"'
Log: { search: '" 12345678"' }
Response: {"search":"\" 12345678\""}

Request: curl --location --request GET 'localhost:3000/search?search=+123+456+78'
Log: { search: ' 123 456 78' }
Response: {"search":" 123 456 78"}

Request: curl --location --request GET 'localhost:3000/search?search=another+test'
Log: { search: 'another test' }
Response: {"search":"another test"}
```

### Expected Behavior

Is expected that the `+` sign is not replaced by spaces. So if this bug didn't exist, the results presented above should be replaced by this:

```bash
Request: curl --location --request GET 'localhost:3000/search?search=+12345678'
Log: { search: '+12345678' }
Response: {"search":"+12345678"}

Request: curl --location --request GET 'localhost:3000/search?search="+12345678"'
Log: { search: '"+12345678"' }
Response: {"search":"\"+12345678\""}

Request: curl --location --request GET 'localhost:3000/search?search=+123+456+78'
Log: { search: '+123+456+78' }
Response: {"search":"+123+456+78"}

Request: curl --location --request GET 'localhost:3000/search?search=another+test'
Log: { search: 'another+test' }
Response: {"search":"another+test"}
```

**Comment by Gamote** [comment]
Never mind, I'm tired. I totally forgot that I need to encode the `+` sign in the query params. 🤦‍♂️

**Comment by jsumners** [comment]
`+` is a reserved character and should be encoded if you need a literal `+` in the processed value -- https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

**Comment by Gamote** [comment]
> `+` is a reserved character and should be encoded if you need a literal `+` in the processed value -- https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

Yeah 😅 minutes after posting the issue I realised. But thank you anyway.
