### ISSUE TITLE
fastify(nestjs) + nuxt not work

### ISSUE THREAD

**Issue by Mitch-i** [fastify/fastify#3338]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.20.1

### Node.js version

14.17

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

I try to use nest+fastify+nuxt+any orm and not work. server work normal with app.listen and bad with api.server.emit('request', req, res)

Example https://github.com/Mitch-i/nuxt_nest

```
const fastify = app.getHttpAdapter().getInstance();
await fastify.ready();

// Unlike the Express version which the app instance itself is a handler function, the fastify instance is an object
// we have to return a handler function for Nuxt serverMiddleware
return function (req, res) {
  fastify.server.emit('request', req, res);
};

```

ERROR [ExceptionsHandler] Cannot read property 'findOne' of undefined TypeError: Cannot read property 'findOne' of undefined

### Steps to Reproduce

use that https://github.com/Mitch-i/nuxt_nest

change database conf in https://github.com/Mitch-i/nuxt_nest/blob/main/server/app.module.ts
npm run nuxt:dev

**Comment by climba03003** [comment]
Why combining three framework together?

**Comment by Mitch-i** [comment]
> Why combining three framework together?

nestjs work with express or with fastify. to work only with fastify I don't want.

**Comment by VBetsun** [comment]
it is not `fastify` related problem. You have some misconfigurations of your `nestjs` application. It looks to me like you are configuring `sequilize` module in the same way as a `typeorm` one. I bet if you do everything like described in the [documentation](https://docs.nestjs.com/recipes/sql-sequelize#sql-sequelize) you will solve your issue.
