### ISSUE TITLE
FastifySchema should be a generic & comply to the json schema standart

### ISSUE THREAD

**Issue by ShadiestGoat** [fastify/fastify#3339]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

What I'm trying to ask for is FastifySchema type to be generic & work within a route. This way, it's a lot easier to setup a schema using generics.

### Motivation

This just makes everything for typescript users a lot simpler. Honestly, I think this would work vise versa as well, so it _may_, have types within the actual function. Plus, it helps to follow the philosophy of the module, since it 'forces' you to use propper validation.

### Example

```ts
app.route<{
    Params: {
        id: string
    }
}>({
    method: "GET",
    url: "/rawi/:id",
    schema: {
        params: {
            id: // no types here! _Why_
        }
    },
    handler: async (req, reply) => {
        
    }
})
```

**Comment by RafaelGSS** [comment]
I'm not sure if I understand your question, but looks like you are trying to mix javascript object with Typescript, it's not possible by Javascript itself. Perhaps https://github.com/sinclairzx81/typebox is something that can come close to what you want.

**Comment by ShadiestGoat** [comment]
No haha, I'm using typescript. The function's generic options should be translated onto the schema type.

**Comment by ShadiestGoat** [comment]
What should happen in `route.d.ts`:

```ts
...
export interface RouteShorthandOptions<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  ...
> {
  schema?: FastifySchema<RawRequest, ...maybe more here>;
...
```

**Comment by ShadiestGoat** [comment]
Ah, wait nevermind 

```js
/**
 * Schemas in Fastify follow the JSON-Schema standard. For this reason
 * we have opted to not ship strict schema based types. Instead we provide
 * an example in our documentation on how to solve this problem. Check it
 * out here: https://github.com/fastify/fastify/blob/main/docs/TypeScript.md#json-schema
 */
```
