### ISSUE TITLE
Ecosystem plugins integration testing

### ISSUE THREAD

**Issue by zekth** [fastify/fastify#3342]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

With the same approach as https://github.com/fastify/fastify/blob/main/.github/workflows/benchmark.yml , adding integration testing on PRs to ensure it does not break anything.

Using labels in the first step as we don't want to add it in the CI of the PRs.

This would basically add tests using the `latest` published version of the packages with minimum assertions.

### Motivation

Not breaking the use of the ecosystem plugins.

avoiding issues like:
- https://github.com/fastify/fastify/issues/3332
- https://github.com/fastify/fastify-swagger/issues/425

**Comment by mcollina** [comment]
My colleague @dominykas worked on this problem for quite a while:

* https://github.com/nodejs/package-maintenance/issues/84#issuecomment-559614256 - this is the initial idea for the implementation
* https://github.com/pkgjs/wiby/blob/main/docs/github-workflow.md - this is the current installation instructions (but I'm reworking the comments bit, because Github Actions have a bug that's not been fixed in over a year)

The goal would be to use wiby.

**Comment by dominykas** [comment]
👋 ohai!

I'm happy to chat about this or give some demos or help set this up - the documentation is quite lacking there (and it does require some setup which does not have any automation right now).

I gave a quick demo some 6 months ago of the current state: https://www.youtube.com/watch?v=m4SMPUshtzY - happy to give it again! I'm also somewhat available on the Node.js and OpenJS Foundation slacks if you want to ping me for a live discussion.

**Comment by Eomm** [comment]
We have this repo to revamp
https://github.com/fastify/fastify-citgm

**Comment by mcollina** [comment]
> We have this repo to revamp
> 
> https://github.com/fastify/fastify-citgm
> 
> 

That repo is far from being great unfortunately, it's very hacky and ad-hoc that we have used when doing semver-major releases.

**Comment by zekth** [comment]
After checking the video of @dominykas it explains way better what we can achieve. Using label triggers it would make less noise with all the PR we can have, also easier for prototyping the integration. One thing is we would also want to implement the cleaning process.

I'm definitely interested in working on this.

**Comment by Eomm** [comment]
Done in https://github.com/fastify/fastify/pull/5233
