### ISSUE TITLE
encoding/decoding uri is confused and misconfigured

### ISSUE THREAD

**Issue by mav-rik** [fastify/fastify#3356]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The framework doesn't take care of decoding URLs before routing. This leads to various problems described at [143](https://github.com/fastify/fastify-static/issues/143) and at [234](https://github.com/fastify/fastify-static/issues/234).

The point is that the browser encodes uri for transport purposes. The uri must be decoded right after it reaches the server. It can not be solved just using `server.get(encodeURI(path), () => ...)` as browser encoding and `encodeURI` differs.

### The first example:
```js
const fastify = require('fastify')

const server = fastify()

server.get('/[...]/a .md', () => 'serve 1st file with space')
server.get('/[...]/a%20.md', () => 'serve 2nd file with %')

server.listen(3000)
```

Open browser to test:
1. `http://localhost:3000/[...]/a .md` -> `serve 2nd file with %` (must be 1st file)
2. `http://localhost:3000/[...]/a%2520.md` -> `404 Error` (must be 2nd file)
3. `http://localhost:3000/%5B...%5D/a%20.md` -> `404 Error` (must be 1st file)
4. `http://localhost:3000/%5B...%5D/a%2520.md` -> `404 Error` (must be 2nd file)

0/4 is correct

### The second example (with `encodeURI`):
```js
const fastify = require('fastify')

const server = fastify()

server.get(encodeURI('/[...]/a .md'), () => 'serve 1st file with space')
server.get(encodeURI('/[...]/a%20.md'), () => 'serve 2nd file with %')

server.listen(3000)
```

Open browser to test:
1. `http://localhost:3000/[...]/a .md` -> `404 Error` (must be 1st file)
2. `http://localhost:3000/[...]/a%2520.md` -> `404 Error` (must be 2nd file)
3. `http://localhost:3000/%5B...%5D/a%20.md` -> `serve 1st file with space` (OK)
4. `http://localhost:3000/%5B...%5D/a%2520.md` -> `serve 2nd file with %` (OK)

2/4 is correct

### Expected Behavior

It must be possible to specify routes without any encoding.
The server must decodeURI prior routing it.

Here's hacked example:
```js
const fastify = require('fastify')

const server = fastify({
    rewriteUrl: req => decodeURI(req.url) // the trick that must be applied by default
})

server.get('/[...]/a .md', () => 'serve 1st file with space')
server.get('/[...]/a%20.md', () => 'serve 2nd file with %')

server.listen(3000)
```

Open browser to test:
1. `http://localhost:3000/[...]/a .md` -> `serve 1st file with space` (OK)
2. `http://localhost:3000/[...]/a%2520.md` -> `serve 2nd file with %` (OK)
3. `http://localhost:3000/%5B...%5D/a%20.md` -> `serve 1st file with space` (OK)
4. `http://localhost:3000/%5B...%5D/a%2520.md` -> `serve 2nd file with %` (OK)

4/4 is correct

### Why just don't use the workaround in the example above?
1. It is not documented
2. Many frameworks take care of creating a server so you can not apply the hack

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I would recommend to target the `next` branch as it seems quite a breaking change.

**Comment by mcollina** [comment]
You have likely researched this better than anybody else.

**Comment by Eomm** [comment]
The decoding is already done into the router:

https://github.com/delvedor/find-my-way/blob/master/index.js#L17

The issue could be related to the static path resolution or how the path is stored in the router's tree

https://github.com/delvedor/find-my-way/blob/c561d220e6c0c93b76b72a7461dcdc8620158ba2/index.js#L440-L447

**Comment by mav-rik** [comment]
@Eomm indeed then the issue is on find-my-way side. I'll debug it deeper.
But do you agree that the example I mentioned should work?

**Comment by mav-rik** [comment]
@Eomm here's what I found.
The `fast-decode-uri-component` works identical to `decodeURIComponent` but has different behavior comparing to `decodeURI`.
For instance `fastDecode('%23') === '#'`, but `decodeURI('%23') === '%23'`.
Few more differences that I identified: `%2f`, `%3f`, `%3d`.

It means that it is incorrect to use `fast-decode-uri-component` instead of `decodeURI` (and `find-my-way` barely decodes anything).

Ideally `decodeURI` must be used before `?` (for the route itself) and `fast-decode-uri-component` must be used for query parameters following after ? or #, but the `find-my-way` does not parse query params at all. It mysteriously uses `fast-decode-uri-component` sometimes on dynamic paths for the reason I did not understand.

Fastify uses `querystring` to parse query instead, which is already deprecated and not fast at all. They recommend to use `URLSearchParams` instead, but my quick benchmark didn't show any advantages of using `URLSearchParams`. Moreover I can see that a custom query parser with power of `fast-decode-uri-component` does a great job.

Here's my results
```
# fast-decode-uri-component custom parser
ok ~1.55 s (1 s + 546856700 ns)

# querystring.parse
ok ~17 s (16 s + 900969300 ns)

# URLSearchParams
ok ~17 s (17 s + 147073800 ns)
```

As a conclusion of this research I would suggest to do this:
1. write `fast-decode-uri` in `fast-decode-uri-component` manner but which will behave exactly like `decodeURI` (I am not capable of doing that as I don't understand how `fast-decode-uri-component` really works)
2. add `fast-decode-uri` (or at least `decodeURI`) call at return of `sanitizeUrl` ([here](https://github.com/delvedor/find-my-way/blob/c561d220e6c0c93b76b72a7461dcdc8620158ba2/index.js#L635))
3. get rid of the `querystring` in fastify and use a custom query parser based on `fast-decode-uri-component`

**Comment by Eomm** [comment]
>But do you agree that the example I mentioned should work? 

I'm not 100% settle.
I agree that there is an issue and we should define a well-defined behaviour based on the RFC https://datatracker.ietf.org/doc/html/rfc2616#section-3.2.1

For example, quoting the spec:

>    For example, the following three URIs are equivalent:

      http://abc.com:80/~smith/home.html
      http://ABC.com/%7Esmith/home.html
      http://ABC.com:/%7esmith/home.html


My understanding here is that we should block the user while registering duplicated routes.

So, for example

```
server.get('/[...]/a .md', () => 'serve 1st file with space')
server.get('/[...]/a%20.md', () => 'serve 2nd file with %') // here we should thrown a "Duplicated route" error
```

I did not investigate further, tbh. 
But a shallow read let me think that this problem requires to be checked by multiple people to be sure we are all on the same page.



---

> get rid of the querystring in fastify and use a custom query parser based on fast-decode-uri-component

This is a great and valuable finding!
We should open a dedicated issue for that

**Comment by mav-rik** [comment]
@Eomm I want to notice that `'/[...]/a .md'` and `'/[...]/a%20.md'` aren't duplicated routes. The `%` is used intentionally as it is possible and it is allowed to have such URIs.
For instance the file name may contain `%` which should be encoded as `%25` in URI to be properly processed. That's the whole point of this issue: currently it's impossible to have such two routes at all. To fix it we must apply `encodeURI` right before routing. And now I tend to think that it should be done in `find-my-way` lib.

> get rid of the querystring in fastify and use a custom query parser based on fast-decode-uri-component

After further investigation I can conclude that that was a wrong assumption.
I will describe the problem with `fast-decode-uri-component` on the issue to `find-my-way` lib.

**Comment by moonmeister** [comment]
@mav-rik I'm not finding the `find-my-way` issue, can I get a link? Sorry if I'm missing something obvious.

**Comment by mav-rik** [comment]
> @mav-rik I'm not finding the `find-my-way` issue, can I get a link? Sorry if I'm missing something obvious.

Sure, I was writing [it](https://github.com/delvedor/find-my-way/issues/206) :)

**Comment by climba03003** [comment]
It should be resolved by https://github.com/delvedor/find-my-way/pull/207
Note that it will only be available on `fastify@4`

**Comment by moonmeister** [comment]
When will fastify 4 be released?

**Comment by climba03003** [comment]
> When will fastify 4 be released?

Please subscribe this issue https://github.com/fastify/fastify/issues/3482
