### ISSUE TITLE
Make architectural recommendation

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#336]
For some of the dev, those principles are standard refer to testability and modularity but we should definitely document this. We can adapt this for fastify and prepare some nice slides.

I like the picture.
https://github.com/kimmobrunfeldt/express-example

**Comment by israeleriston** [comment]
great !! this is good path, i am always have problem with choice of the best architecture and good practice

**Comment by jsumners** [comment]
Well https://github.com/fastify/example exists, it just doesn't have anything in it.

**Comment by jsumners** [comment]
@StarpTech given the above repo and @allevo's Twitter clone project, can this be closed?

**Comment by StarpTech** [comment]
It's not exactly the same. https://github.com/fastify/exampleis empty and the twitter example does not issue recommendations. Please let it open.

**Comment by allevo** [comment]
> the twitter example does not issue recommendations

@StarpTech  Please add them!

**Comment by delvedor** [comment]
I think [`fastify-cli`](https://github.com/fastify/fastify-cli) generator gives some useful recommendations.

If someone wants to prepare a presentation I'll be happy to review it.
