### ISSUE TITLE
ServerResponse for HTTP 200 and 201 different

### ISSUE THREAD

**Issue by bharadiasharad** [fastify/fastify#3363]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.22

### Node.js version

12.22.4

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

```
const configurationSchemaToGet = {
    response: {
        200: getConfigurationBody,
    },
};
```

output: 
```
{
  "configurations": [
    {
      "id": "MmZGRm78Vwt9PJ38Chcu3",
      "configurationJson": {
        "fruit": "apple"
      }
    }
}
```

-----------------

```
const configurationSchemaToGet = {
    response: {
        201: getConfigurationBody,
    },
};
```

output: 
```
{
  "configurations": [
    {
      "id": "MmZGRm78Vwt9PJ38Chcu3",
      "configurationJson": {}
    }
}
```

ConfigurationJson is empty when http response is 200 however, it is working as expected for HTTP response 201

### Steps to Reproduce

```
api.get(
                    "/:configurationId",
                    { schema: configurationSchemaToGet},
                    async (req, rsp) => {
                        return ... 
                    },
                );
```

### Expected Behavior

Response for http 200 and 201 should have been same

**Comment by bharadiasharad** [comment]
> Not necessarily. Please read https://datatracker.ietf.org/doc/html/rfc2616/#section-10.2.1 and https://datatracker.ietf.org/doc/html/rfc2616/#section-10.2.2

Correct, here, I meat that the Configuration Json should not be empty in the case of HTTP 200 response.


Please find the steps to reproduce below,


```
api.get(
    "<apiPath>", { schema: { response: { 201: S.object()
        .prop("id", S.string())
        .prop("configurationJson", S.object()) }}}
    async (req, rsp) => {
        return {
            configurations: [
              {
                id: "MmZGRm78Vwt9PJ38Chcu3",
                configurationJson: {
                  key: "value"
                }
              }]
            }
    },
);
```


create an API with the above data. You should be able to reproduce it by changing response code from 201 and 200

**Comment by Eomm** [comment]
@jsumners is right, we the code

But I bet you are looking for this: https://www.fastify.io/docs/latest/Validation-and-Serialization/#serialization

```diff
const configurationSchemaToGet = {
    response: {
-        200: getConfigurationBody,
+        '2xx': getConfigurationBody,
    },
};
```
