### ISSUE TITLE
Documentation and TS Types missed for FastifyInstance#setSchemaController

### ISSUE THREAD

**Issue by MetCoder95** [fastify/fastify#3366]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.x.x.

### Node.js version

>14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Any

### Description

While working on issue #3121, I was looking for a way to set the `SchemaController` from a Plugin, I notice that the Instance method `#setSchemaController` is missing documentation, and the TS types to identify the method signature.

### Steps to Reproduce

**Documentation**: Enough with visiting [Fastify official site](https://fastify.io).
**TS Types**:

```ts
import Fastify from 'fastify';

const app = fastify();

app.setSchemaController(/**<Controller>*/)
/* Line above throws the following:
Property 'setSchemaController' does not exist on
type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>'.
*/
```

**Comment by Grubba27** [comment]
Can I do this ? i wrote the code and I'm starting the PR. I never done anything to open source I could use some help :)

**Comment by sameer-coder** [comment]
Looks like this issue can be closed.
