### ISSUE TITLE
Cannot bundle using esbuild

### ISSUE THREAD

**Issue by re-thc** [fastify/fastify#3371]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Amazon Linux 2

### Description

`readable-streams` depends on `string_decoder` the npm module and not the built-in function. Building Fastify with esbuild breaks due to this confusion (it assumes `string_decoder` as an external but tries to require the npm_module).

Can `readable-streams` / `string_decoder` be dropped and replaced with NodeJs builtins now that fastify 3 supports Node 10.x and above?

### Steps to Reproduce

1. Install Fastify
2. Run Esbuild to build and bundle Fastify

### Expected Behavior

No errors

**Comment by robmcguinness** [comment]
Same when using esbuild to bundle fastify for lambda deployment. As a workaround:

```ts
import resolve from 'esbuild-plugin-resolve';

// esbuild config
// ...
plugins: [    
    resolve({
      'string_decoder/': 'string_decoder',
    }),
  ],
// ...
```

**Comment by climba03003** [comment]
As the problem is related to `readable-streams` and we dropped it.
I assume it as resolved.
