### ISSUE TITLE
ajv override documentation seems outdated

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#3384]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Documentation (https://www.fastify.io/docs/latest/Validation-and-Serialization/) says this:

```
const ajv = new Ajv({
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: 'array', // This line
  allErrors: true
})

fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schema)
})
```

However, this is not a valid code according to fastify TS types:
```
fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schema)
})
```

Following error occurs:
```
TS2345: Argument of type '({ schema, method, url, httpPart }: FastifyRouteSchemaDef<FastifySchema>) => ValidateFunction<unknown>' is not assignable to parameter of type 'FastifySchemaCompiler<FastifySchema>'.   Call signature return types 'ValidateFunction<unknown>' and 'FastifyValidationResult' are incompatible.     The types of 'errors' are incompatible between these types.       Type 'ErrorObject<string, Record<string, any>, unknown>[] | null | undefined' is not assignable to type 'FastifySchemaValidationError[] | null | undefined'.         Type 'ErrorObject<string, Record<string, any>, unknown>[]' is not assignable to type 'FastifySchemaValidationError[]'.           Property 'dataPath' is missing in type 'ErrorObject<string, Record<string, any>, unknown>' but required in type 'FastifySchemaValidationError'.
```

Which one is wrong, types or the documentation?

### Steps to Reproduce

Try to apply example from documentation in TS project.

### Expected Behavior

Example compiles and works correctly.

**Comment by climba03003** [comment]
Are you using `ajv@6` or `ajv@7`. The current typings is strictly bind to `ajv@6`.

**Comment by conor909** [comment]
@climba03003 I'm experiencing this with `ajv@8`, do we need to write our own definitions?

**Comment by kgoedecke** [comment]
@climba03003 is support for AJV 7 or 8 currently planned?

**Comment by Eomm** [comment]
It is in fastify v4

You can already use it in v3 actually:
https://www.nearform.com/blog/upgrading-fastifys-input-validation-to-ajv-version-8/

**Comment by Eomm** [comment]
Does https://github.com/fastify/fastify/pull/3088/files solve this issue?
