### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#34]
Due to using pino-http, we are losing 2k req/s on my laptop.
_maybe_ we can improve pino-http, but we should update our benchmark.

**Comment by delvedor** [comment]
In my local copy I've updated to `fast-json-stringify@0.10.3` and I'm serving *19.8k req/sec*, while with `fast-json-stringify@0.10.2` I was serving around *18.9k req/sec*.

Could you do some bench on your machine and check if the issue has been fixed?

**Comment by mcollina** [comment]
The issue has been fixed!
