### ISSUE TITLE
Create fastify-type-provider-* modules

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3404]
Yes, I'd expect `fastify-type-provider-json-schema-to-ts` and `fastify-type-provider-typebox` would both belong as packages of the Fastify org. Each would take a direct dependency on `json-schema-to-ts` and `@sinclair/typebox` respectively as well as Fastify V4, likely as a peer dependency. 

Each provider package would contain a single module that exports an implementation of `FastifyTypeProvider`. The contents of these modules are as follows.

### fastify-type-provider-json-schema-to-ts
```typescript
import { FastifyTypeProvider } from 'fastify'

import { JSONSchema, FromSchema } from 'json-schema-to-ts'

export interface JsonSchemaToTsProvider extends FastifyTypeProvider {

  output: this['input'] extends JSONSchema ? FromSchema<this['input']> : never
}
```

### fastify-type-provider-typebox

```typescript
import { FastifyTypeProvider } from 'fastify'

import { Static, TSchema } from '@sinclair/typebox'

export * from '@sinclair/typebox'

export interface TypeBoxTypeProvider extends FastifyTypeProvider {

  output: this["input"] extends TSchema ? Static<this["input"]> : never
}
```
These packages are yet to be setup.

_Originally posted by @sinclairzx81 in https://github.com/fastify/fastify/pull/3398#r739474508_

**Comment by mcollina** [comment]
cc @sinclairzx81

**Comment by RafaelGSS** [comment]
Just as a reminder. Let's use the `@fastify` prefix for those packages.

**Comment by sinclairzx81** [comment]
@RafaelGSS Possible suggestion for the `fastify-type-provider-typebox` provider. As AJV 7+ requires the `kind` and `modifer` keywords to be configured by the user. Perhaps the provider package could simply export a default configuration as follows.

### Current

```typescript
import { TypeBoxTypeProvider, Type } from 'fastify-type-provider-typebox'

import fastify from 'fastify'

const server = fastify({
    ajv: {
        customOptions: {
            strict: 'log',
            keywords: ['kind', 'modifier'],
        },
    },
}).withTypeProvider<TypeBoxTypeProvider>()
```

### Proposed

```typescript
import { TypeBoxConfiguration, TypeBoxTypeProvider, Type } from 'fastify-type-provider-typebox'

import fastify from 'fastify'

const server = fastify({ ...TypeBoxConfiguration }).withTypeProvider<TypeBoxTypeProvider>()

```

For future consideration

**Comment by SimenB** [comment]
Will there be an integration with  `FastifyPluginCallback` & `FastifyPluginAsync`, plus `fastify-plugin` or some such? So that the injected `instance` in the callback also gets the inference

**Comment by RafaelGSS** [comment]
We are discussing it in https://github.com/fastify/fastify/issues/3636
