### ISSUE TITLE
Provide requestTimeout feature

### ISSUE THREAD

**Issue by artur-ma** [fastify/fastify#3405]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Didn't find description in docs how to set `requestTimeout`, which will limit the time for each request.
I think it is important to add this.

I can send a PR later today if you accept this proposal.

### Motivation

There is vulnerability in Node that can be fixed be setting `requestTimeout` to > 0

https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/

context:

https://github.com/nodejs/node/issues/40493#issuecomment-954659850

### Example

https://nodejs.org/api/http.html#serverrequesttimeout

**Comment by mcollina** [comment]
Go for it!
