### ISSUE TITLE
Host Constraints not working when http2 enabled

### ISSUE THREAD

**Issue by anker2000** [fastify/fastify#3408]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

21.0.1

### Description

Host constraints will give a 404 error regardless of domain used, when http2 is turned on. Using the inject method as described in the [documentation](https://www.fastify.io/docs/latest/Routes/) seems to work, but when I try the URL in the browser it doesn't. 

Turning off http2 fixes the problem.

Possibly related to [this](https://github.com/fastify/fastify/issues/2112)? 

### Steps to Reproduce

1. Enable http2. 
2. Use host constraints as described in the documentation like this:
`fastify.route({ 
    method: 'GET',
    url: '/test',
    constraints: { host: 'my.testdomain.co' },
    handler: function (request, reply) {
        reply.send('hello world from my.testdomain.co')
    }
})`
3. Try to access 'https://my.testdomain.co/test' in a browser. (inject code mentioned in documentation works, but browser doesn't)

### Expected Behavior

When entering 'https://my.testdomain.co/test' in my browser I expect to see the message 'hello world from my.testdomain.co'.

**Comment by climba03003** [comment]
It is an upstream issue and related to the below line.
https://github.com/delvedor/find-my-way/blob/master/lib/constrainer.js#L95

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by anker2000** [comment]
I'd love to, but I've never done a unit test before. Would you be able to help me out with what I need to do?

**Comment by climba03003** [comment]
> 
> 
> I'd love to, but I've never done a unit test before. Would you be able to help me out with what I need to do?

I will be helping you if you face any problem.

**Comment by luisorbaiceta** [comment]
Hi @anker2000, do you have any plans to work on this? If not, I'll be happy to address this issue and send a PR with unit tests.

**Comment by Eomm** [comment]
Go for it!

**Comment by luisorbaiceta** [comment]
Hi @anker2000, are you testing your http2 server over a secure connection?

**Comment by anker2000** [comment]
Yes, was testing over a secure connection. Just a heads up that using inject to test this doesn't expose the issue.

**Comment by anker2000** [comment]
I messed up my initial attempt at doing a PR because I'm an idiot and I don't know how to do unit tests, but running a forked version that works right now, which basically just changes line 95 in constrainer.js from this:
`          lines.push('   host: req.headers.host,')`
to this:
` lines.push('   host: req.headers.host || req.headers[\':authority\'],')`

**Comment by luisorbaiceta** [comment]
I am sorry but I am not able to replicate the problem, everything is working fine in my end, are you sending the correct host header along with the browser request?

Here is my response (taken from postman):

![image](https://user-images.githubusercontent.com/44276180/143918543-eb538b1a-69b5-44ec-9cd7-7c6e5d870519.png)

And here is my code:

```js
// Require the framework and instantiate it
const fs = require('fs')
const path = require('path')
const fastify = require('fastify')({
  logger: true,
  http2: true,
  https: {
    allowHTTP1: true, // fallback support for HTTP1
    key: fs.readFileSync(path.join(__dirname, 'certs', 'newkey.pem')),
    cert: fs.readFileSync(path.join(__dirname, 'certs', 'cert.pem'))
  }
})

// Declare a route
fastify.route({
  method: 'GET',
  constraints: { host: 'luisorbai.com' },
  url: '/test',
  handler: function (request, reply) {
    reply.send('hello world from luisorbai')
  }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()

```

If I remove the host header, I get the 404 as expected:

![image](https://user-images.githubusercontent.com/44276180/143918863-1e492532-a504-4394-bbd1-e48a3c3c7e2e.png)

**Comment by anker2000** [comment]
I think what you are seeing is similar to what I was experiencing using inject. If you use some platform to simulate a request it the host header will be included, however if you do a real life example using a browser like Chrome you'll find that header.host is empty.

**Comment by luisorbaiceta** [comment]
How are you binding the provided host name with your server? Is your server deployed and visible behind the provided domain?

You need to set a proxy or find a way to add the host header to the request (like I am doing with postman). But I don't think there is any way you can make the browser resolve to a random domain without tweaking the request, or the host file in your computer...

All of this is apart from the bug that is described above of course, but I just want to point that testing this seems impossible directly in your browser if you don't do some of the things that I've mentioned.

**Comment by luisorbaiceta** [comment]
I assume you are binding the host name to your server IP, is that right? Sorry for so many questions but I just want to narrow down all possible scenarios

**Comment by anker2000** [comment]
I had this issue with my local dev setup, which just uses /etc/hosts to point the domain to my local server ip. I've also replicated the issue on my live server, which also just has a domain pointing directly to the server IP. There's no in-between proxy, however I am using iptables to redirect port 443 requests to port 1443.

**Comment by luisorbaiceta** [comment]
> I messed up my initial attempt at doing a PR because I'm an idiot and I don't know how to do unit tests, but running a forked version that works right now, which basically just changes line 95 in constrainer.js from this: ` lines.push(' host: req.headers.host,')` to this: ` lines.push(' host: req.headers.host || req.headers[\':authority\'],')`

I have replicated the issue and can confirm that this fixes it. @anker2000 do you want to open the PR in the `find-my-way` repo, or do you want me to proceed?

**Comment by anker2000** [comment]
Please, if you can proceed that would be great. I don't have the necessary skills to do it.

**Comment by luisorbaiceta** [comment]
Done.

> I'm an idiot and I don't know how to do unit tests

Please don't say this. Two years ago I didn't even know what a PR or a unit test was. Learning is a fun, never ending process, and there is always a first time for everything. Keep up the good work!
