### ISSUE TITLE
Document special case for setting 'set-cookie' header

### ISSUE THREAD

**Issue by michael-melodyarc** [fastify/fastify#3409]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This issue is to confirm the existing behavior is intended and if so, a request to better document the behavior.

Fastify's docs for `reply.header(key, value)` are quite concise and only say the following:

>Sets a response header. If the value is omitted or undefined, it is coerced to `''`.
>For more information, see [`http.ServerResponse#setHeader`](https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_response_setheader_name_value).

If you click through to the official Node.js docs, you'll see this excerpt:

>If this header already exists in the to-be-sent headers, its value will be replaced.

This led me to believe the following code would only send a single cookie with a key of `blueberry`:

```
res.header('set-cookie', 'apple=1');
res.header('set-cookie', 'blueberry=2');
```

But in fact, both cookies are sent.  To clarify, I actually prefer Fastify's behavior, but it definitely confused me because I had code like the following, and it was duplicating headers, and even though i read and reread the docs, I didn't realize what was happening until I actually looked at Fastify's code.

```
    res.header('set-cookie', [
      ...(res.getHeader('set-cookie') ?? []),
      cookie.serialize(/* my really awesome cookie */),
    ]);
```

Relevant Fastify source code: https://github.com/fastify/fastify/blob/main/lib/reply.js#L237

If this is intended behavior, I can try to send a PR later this week to add a one-liner to the docs calling out `set-cookie` having special behavior.

**Comment by zekth** [comment]
Technically the browser takes in consideration only the latest reference of a key for set-cookie header. The fact that this is done this way is to avoid parsing the `set-cookie` header when you add it in the reply. This indeed might looks odd but speeds up the serialization of the reply. I think @mcollina can confirm.

A documentation PR is welcome.

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/pull/1359 implemented this without updating the documentation.

**Comment by genzyy** [comment]
Can I work on this issue? If yes , in which branch I should add the documentation for this?

**Comment by mcollina** [comment]
Go for it. Work on a branch of your chosing and send a PR against main?
