### ISSUE TITLE
Petition to join Fastify Core Team

### ISSUE THREAD

**Issue by galvez** [fastify/fastify#3410]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey there — as some of you know I've been working on a project called Terix, which aims to provide improved frontend tooling for Fastify applications, especially SSR applications. 

Right now this project has accumulated the following repositories:

- https://github.com/terixjs/fastify-walk
- https://github.com/terixjs/fastify-vite
- https://github.com/terixjs/vite-plugin-blueprint
- https://github.com/terixjs/fastify-apply
- https://github.com/terixjs/fastify-api
- https://github.com/terixjs/manifetch

Which support [the vision](https://fastify-vite.dev/meta/philosophy.html) that Fastify and [Vite](https://vitejs.dev/) are a solid basis for building these kinds of applications, no other frameworks needed.

See [https://fastify-vite.dev/](https://fastify-vite.dev/) to see where the project stands.

_Terix_ turned out to be a terrible name choice, since there's already a multinational company named _TERiX_ — so I've decided to drop the name — but instead of coming up with a new name, I thought I'd petition instead to transfer these repositories to Fastify's account and perhaps, officially join the Fastify Core Team with the clear goal of evolving that area of plugins and tooling (frontend, SSR).

**Comment by mcollina** [comment]
I think this would be a good idea. However I don't think you have enough contributions to Fastify proper to join the core team.. how about the plugin team? Or maybe you can rank up a few PRs there too.

**Comment by mcollina** [comment]
cc @delvedor

**Comment by jsumners** [comment]
I share Matteo's concern. But I'm also concerned about adding several new modules for the team to maintain. Particularly since they are in an area unfamiliar to backend focused developers.

**Comment by galvez** [comment]
Fair enough re: joining Plugin team instead, I didn't realize there were multiple teams — but FWIW I'd be taking full responsibility over shaping up all packages to be well documented and tested enough to facilitate the job of others maintaining them as well.

**Comment by galvez** [comment]
The main packages would be **fastify-vite**, **fastify-api**, **manifetch** and **vite-plugin-blueprint**.

**Comment by delvedor** [comment]
I agree with @mcollina and @jsumners. Unfortunately (as far as I know) there are no experts in frontend-tooling among us, which means that you'll be the only person responsible for these plugins. This also means that if someday you'll need to stop maintaining them for any reason, those plugins will become unmaintained.

**Comment by mcollina** [comment]
I think they will be a good addition to the ecosystem. Specifically because they are in the line of fastify-next and fastify-hotwire.
If we cannnot maintain them anymore, we will deprecate them.

Overall I'm +1 to add them in the repo.

**Comment by galvez** [comment]
> This also means that if someday you'll need to stop maintaining them for any reason, those plugins will become unmaintained.

fastify-vite already has users and contributors, I'm sure it's on the verge of having many more. I'd propose the compromise of adding them to Fastify namespace in a trial status, if it turns out it does get traction and more potential maintainers, you keep it, otherwise transfer back to my @galvez username.

I've decided to deprecate the name Terix regardless.

Let me know if I should transfer the repos.

**Comment by mcollina** [comment]
I'm +1 with that plan.

**Comment by jsumners** [comment]
@fastify/core what say you?

**Comment by zekth** [comment]
+1 with the mentionned plan.

**Comment by RafaelGSS** [comment]
I'm overall +1, however, I'm not sure if all those packages should be transferred:

- https://github.com/terixjs/fastify-api (it could be a community plugin)
- https://github.com/terixjs/fastify-apply (the readme tell it as experimental)
- https://github.com/terixjs/fastify-walk (pretty similar to all other community plugins)

**Comment by galvez** [comment]
> https://github.com/terixjs/fastify-apply (the readme tell it as experimental)
> https://github.com/terixjs/fastify-api (it could be a community plugin)

Fair enough. These can wait until they're a little more shaped up.

> https://github.com/terixjs/fastify-walk (pretty similar to all other community plugins)

Had no idea there were similar packages for fastify, can you point me to one of them?

> https://github.com/terixjs/vite-plugin-blueprint (this is a vite plugin, not fastify)

But it's a key supporting package of fastify-vite.

**Comment by climba03003** [comment]
I am generally against any mix of frontend and backend, or frameworks.
But as I am using `vite` in some of my project, I may helps on maintaining `fastify-vite` if it under the organization.

About joining the team, I'm +1 if it is plan to transfer at least one repo inside the organization.

**Comment by Eomm** [comment]
We have already some repositories that are mainly maintained by one single maintainer so I think it is not an issue.

I would just create a `@fastify/frontend` team grouping those repositories that belong to this domain. This should help during PR review requests (instead of tagging `@fastify/plugin` team).

Generally, I'm happy about this proposal because I think vite is a great growing project and a new point of view into the team could help us improve some plugins that could be easier to use for the community.

**Comment by mcollina** [comment]
I have created a frontend team and invited @galvez.
