### ISSUE TITLE
Async handler throws "no undefined" error when used with `fastify-static` and sendFile.

### ISSUE THREAD

**Issue by moonmeister** [fastify/fastify#3412]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Plugin version

4.4.2

### Node.js version

14.18.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6

### Description

I've been running into an error where my 404/500 responses seem to trigger the error: `Promise may not be fulfilled with 'undefined' when statusCode is not 204`. I however indeed sending a response. I finally realized the solve was directly calling `reply.send()` vs calling `reply.sendFile()` from `fastify-static`. Any error code that's not 204 that uses `reply.sendFile()` will trigger this. The response does still send correctly, as the repl shows, but the error is there when it shouldn't be.

Possibly related to #2702 

### Steps to Reproduce

https://replit.com/@moonmeister/fastify-async-static-error?v=1

### Expected Behavior

I'd expect this to not trigger the error

**Comment by climba03003** [comment]
#2702 is on `next` branch. It is expected you cannot have `undefined` return on `async` reply.

I think the below code should solve your problem.
```js
async function(request, reply) {
  return reply.send('something')
}
```

**Comment by moonmeister** [comment]
Thanks, that indeed solves the issue. Is there docs I missed on this? Or is there a way we could more clearly communicate this in the error?

**Comment by mcollina** [comment]
Given this is going to be fixed in v4 (for good), I'm not sure we should spend time documenting this further. 

This is the piece of docs you heve been looking for: https://www.fastify.io/docs/latest/Routes/#promise-resolution.
