### ISSUE TITLE
decorateRequest issue (The decorator 'X' has already been added!)

### ISSUE THREAD

**Issue by askart** [fastify/fastify#3416]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.21.5

### Stopped working in version

3.21.6

### Node.js version

16.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### 💥 Regression Report

`The decorator 'X' has already been added!`

### Steps to Reproduce

Repo: https://github.com/askart/fastify-decorate-request

1) create plugin A
2) decorate request inside plugin A with false value `fastify.decorateRequest("X", false);`
3) wrap plugin A in fastify-plugin
4) create plugin B
5) decorate request inside plugin B with true value `fastify.decorateRequest("X", true);`
6) register plugin A
7) register plugin B
8) run project

### Expected Behavior

no errors

**Comment by climba03003** [comment]
From my point of view, the current behavior is correct. It should throw when you register `A` first.
A do not create new context, so it is modifying its parent.
B is using the modified parent, it must throw error.

The reverse order of A and B should solve your issue.

**Comment by Eomm** [comment]
The regression you are reporting was the issue 😄 
In fact, in fastify 3.21.4 you have the same behaviour of 3.21.6
https://runkit.com/eomm/regression/2.0.0

The X is defined in the root scope (due to the `wrap plugin A in fastify-plugin`) and the B plugin must inherit the X decorator from A in this way.

**Comment by askart** [comment]
Thx, how i can overwrite inherited value X?

**Comment by askart** [comment]
> The reverse order of A and B should solve your issue.

@climba03003, i've tried reverse order, and it's working. But i don't understand why? and where i can read about this in documentation?

>The X is defined in the root scope (due to the wrap plugin A in fastify-plugin) and the B plugin must inherit the X decorator from A in this way.

@Eomm, if it's inherited, can i overwrite it without using decorateRequest?

**Comment by MkLHX** [comment]
Hello, i'm facing the same issue using AdminJS -> AdminJSFastify -> buildAuthenticatedRouter() inside an existing Fastify project already using an app.decorate('authentication', callback())

**Comment by idafoh** [comment]
@MkLHX Facing the exact the same issue with adminjs and fastify, did you find a workaround?

**Comment by Eomm** [comment]
This is a 3yo issue. Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
