### ISSUE TITLE
Decorator check is not working for functions

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3417]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Plugin version

3.0.0

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12

### Description

I can add multiple decorators to the request and reply object.

The error is not thrown when the decorator is a function (a string, number or boolean throws instead)

### Steps to Reproduce

https://runkit.com/eomm/multiple-decoration-issue

```js
const fastify = require('./')()
const fp = require('fastify-plugin')

fastify.register(fp(async function A (a) {
  a.decorateRequest('X', () => {})
  a.decorateReply('X', () => {})
}))

fastify.register(async function B (b) {
  b.decorateRequest('X', () => {})
  b.decorateReply('X', () => {})
})
fastify.ready()
  .then(() => console.log('ok ' + fastify.version))
  .catch(err => console.error(err))
```

### Expected Behavior

it should throw 

```
FastifyError [Error]: The decorator 'X' has already been added!
```

**Comment by mcollina** [comment]
This is expected!

**Comment by mcollina** [comment]
Not a bug really, functions are ok.

**Comment by Eomm** [comment]
Could you elaborate?

I did not read about this different behaviour on docs compared to other primitives datatypes.

Checking docs I read:

> Defining a decorator (using decorate, decorateRequest, or decorateReply) with the same name more than once in the same encapsulated context will throw an exception.

So, a child context decorator overwrite the parent one only for functions?
