### ISSUE TITLE
Typebox example from documentation throws error strict mode: unknown keyword: "kind"

### ISSUE THREAD

**Issue by Jnig** [fastify/fastify#3421]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

5.10.70

### Description

Hi,

I'm trying to use the new Type Providers example from.
https://github.com/fastify/fastify/blob/next/docs/Type-Providers.md

### Steps to Reproduce

``` ts
server.get(
  '/route',
  {
    schema: {
      querystring: Type.Object({
          foo: Type.Number(),
          bar: Type.String(),
        }),
    },
  },
  (request, reply) => {
    // type Query = { foo: number, bar: string }

    const { foo, bar } = request.query; // type safe!
  },
)
```

This will throw the following error:
```
(node:425517) UnhandledPromiseRejectionWarning: FastifyError: Failed building the validation schema for GET: /route, due to error strict mode: unknown keyword: "kind"
    at Boot.<anonymous> (/fastify-objection-starter/node_modules/fastify/lib/route.js:276:21)
```

The error can be fixed by adding `Type.Strict()`.
``` ts
server.get(
  '/route',
  {
    schema: {
      querystring: Type.Strict(
        Type.Object({
          foo: Type.Number(),
          bar: Type.String(),
        }),
      ),
    },
  },
  (request, reply) => {
    // type Query = { foo: number, bar: string }

    const { foo, bar } = request.query; // type safe!
  },
)
```

The issue is caused by `kind: Symbol(ObjectKind)` when omitting `Type.Strict(...)`
``` ts
{
  kind: Symbol(ObjectKind),
  type: 'object',
  properties: {
    foo: { kind: Symbol(NumberKind), type: 'number' },
    bar: { kind: Symbol(StringKind), type: 'string' }
  },
  required: [ 'foo', 'bar' ]
}
```

### Expected Behavior

I'm not sure what the expected behavior is. Updating documentation to use `Type.Strict(...)` could be a solution or perhaps there is also a option that strict mode ignores the `Symbol(ObjectKind)` property.

cc @sinclairzx81

**Comment by sinclairzx81** [comment]
@Jnig Hi, you need to setup the AJV validator to allow the `kind` and `modifier` keywords when using TypeBox. The following is the typical setup for TypeBox when using AJV 7 in isolation. 

Note: the `Type.Strict()` function will strip out these keywords.

```typescript
const ajv = addFormats(new Ajv({}), [
    'date-time', 
    'time', 
    'date', 
    'email',  
    'hostname', 
    'ipv4', 
    'ipv6', 
    'uri', 
    'uri-reference', 
    'uuid',
    'uri-template', 
    'json-pointer', 
    'relative-json-pointer', 
    'regex'
]).addKeyword('kind')
  .addKeyword('modifier')
```

Hope that helps
S

**Comment by Jnig** [comment]
Thanks for the quick reply! Everything is working as expected with your provided snippet.

``` ts
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const ajv = addFormats(new Ajv({}), [
  'date-time',
  'time',
  'date',
  'email',
  'hostname',
  'ipv4',
  'ipv6',
  'uri',
  'uri-reference',
  'uuid',
  'uri-template',
  'json-pointer',
  'relative-json-pointer',
  'regex',
])
  .addKeyword('kind')
  .addKeyword('modifier');

export const server = fastify({}).withTypeProvider<TypeBoxTypeProvider>();
server.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schema);
});
```

**Comment by RafaelGSS** [comment]
@sinclairzx81 could you add that information in the docs?

**Comment by sinclairzx81** [comment]
@RafaelGSS I'm wondering if there is a way to make this easier for users. As mentioned by @Jnig, the TypeBox `Type.Strict(...)` function removes the `kind` and `modifier` properties on the schema by serializing then deserializing the schema. This works because the `kind` and `modifier` properties are defined as Symbols which are non-serializable. The resulting schema is AJV 7 friendly.

The following is TypeBox's `Type.Strict(...)` function.

```typescript
public Strict<T extends TSchema>(schema: T, options: CustomOptions = {}): T {
    return JSON.parse(JSON.stringify({ ...options, ...schema })) as T
}
```
I'm curious if a similar thing could be handled inside the `@fastify/ajv-compiler` package, essentially running a serialization pass to strip out all non-serializable properties from the schema before passing to over to AJV to compile. This would make the schemas a bit more permissive of users applying custom properties (including validate() functions that users may augment their schemas with).

Work was carried out to implement a similar mechanism for the `fast-json-stringify` package earlier this year. Because the serialize / deserialize pass only occurs once, this may prove a tenable option for Fastify routes also. Relevant Issues / PR's below.

https://github.com/fastify/fast-json-stringify/issues/271
https://github.com/fastify/fast-json-stringify/pull/272
https://github.com/fastify/fast-json-stringify/pull/280

Open to thoughts
S

**Comment by Eomm** [comment]
>  I'm wondering if there is a way to make this easier for users.

```
const app = fastify({
  ajv: {
    customOptions: {
      strict: 'log',
      keywords: ['kind', 'modifier']
    }
  }
})
```

The `formats` should be already added in fastify v4, so I think this should work


>I'm curious if a similar thing could be handled inside the @fastify/ajv-compiler package

Not sure about it, is it not enough to set the `strict` ajv parameter to `log`?
https://ajv.js.org/options.html#strict

**Comment by sinclairzx81** [comment]
@Eomm Yeah, that looks like a leaner candidate to include in the documentation.

As for culling non-serializable properties such as `Symbol` and `Function`, I guess my take on that is that, while it would be safe to cull any property that can't be represented in JSON; I do actually feel it would better for users explicitly opt into additional keywords if it's easy to do so. This to avoid implicit handling of the schema in Fastify which would diverge from the way AJV 7.0+ operates by default.

Would also recommend including links to the relevant TypeBox documentation regarding these keywords in the Fastify documentation also.

https://github.com/sinclairzx81/typebox#strict
https://github.com/sinclairzx81/typebox#validation

**Comment by Jnig** [comment]
The ajv custom options work fine, including the log parameter.
Here is a small repo with fastify v3 and v4 for testing: https://github.com/Jnig/fastify-v3-v4

I'm wondering if it could be an issue for other plugins that the symbols are not longer removed. I'm thinking of fastify-swagger for instance and will test that in the next days.

**Comment by Jnig** [comment]
I've created https://github.com/fastify/fastify/pull/3437 to extend the documentation and therefore close the issue.
