### ISSUE TITLE
Validation defaults like `removeAdditional` no longer set

### ISSUE THREAD

**Issue by jstayton** [fastify/fastify#3426]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.1

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.1

### Description

In the "Validation and Serialization" docs, [it mentions the baseline ajv configuration](https://www.fastify.io/docs/latest/Validation-and-Serialization/#validator-compiler) that can be modified by `ajv.customOptions`:

```js
{
  removeAdditional: true, // remove additional properties
  useDefaults: true, // replace missing properties and items with the values from corresponding default keyword
  coerceTypes: true, // change data type of data to match type keyword
  nullable: true     // support keyword "nullable" from Open API 3 specification.
}
```

However, I'm not seeing that `removeAdditional` is being set. (I haven't tested the other options.)

I'm seeing all of the body fields set in the request come through on `request.body`, even when my schema only specifies a subset.

I'm _pretty_ sure the additional fields used to be removed? 🤔 

### Steps to Reproduce

Minimal Fastify app:

```js
import Fastify from "fastify";

const fastify = Fastify({
  logger: true,
  // Uncomment the following to see it working as expected:
  // ajv: {
  //   customOptions: {
  //     removeAdditional: true,
  //     useDefaults: true,
  //     coerceTypes: true,
  //     allErrors: false,
  //     nullable: true,
  //   },
  // },
});

fastify.post(
  "/",
  {
    schema: {
      body: {
        type: "object",
        properties: {
          hello: { type: "string" },
        },
      },
    },
  },
  (request, reply) => {
    return request.body;
  }
);

fastify.listen(3000, (err, address) => {
  if (err) throw err;
});
```

Then make a `POST` request with an additional field. Here's what I tried with HTTPie:

```sh
http POST :3000 hello=there additional=field
```

The response (`request.body`):

```json
{
    "additional": "field",
    "hello": "there"
}
```

### Expected Behavior

I expected the baseline ajv configuration in the docs to be set. In particular, I expected `removeAdditional: true` to be set and remove any additional fields.

**Comment by climba03003** [comment]
`removeAdditional: true` will remove the properties only when `additionalProperties: false` inside the schema.
