### ISSUE TITLE
Test issue in CITGM (node.js v17)

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3428]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Node.js version

v17.1.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Red Hat

### Description

See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2791/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/fastify_v3_23_1/

### Steps to Reproduce

run `npm test`

**Comment by Eomm** [comment]
Relates to https://github.com/nodejs/node/pull/40858

**Comment by anonrig** [comment]
I've added most of the issues related to Node 17 on my latest pull request https://github.com/fastify/fastify/pull/3515. When that pull request is merged, I think we can close this issue.
