### ISSUE TITLE
Object serialization problem against JSON schema in response

### ISSUE THREAD

**Issue by Jiri-Mihal** [fastify/fastify#3429]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.1

### Node.js version

16.3.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

Serialization the route response against the JSON Schema removes valid values when JSON Schema property type is an "object".

### Steps to Reproduce

```js
const app = require('fastify')();

const schema = {
    response: {
        200: {
            type: 'object',
            properties: {
                string_one: {type: 'string'},
                obj_one: { type: 'object' },
                obj_two: { type: 'object' }
            },
            additionalProperties: true,
        }
    }
}

app.get('/', {schema}, (req, res) => {
    res.send({
        string_one: 'foo',
        obj_one: 'value will be removed, it\'s not an object',
        obj_two: {'value_will': 'be removed, but should be kept, because it\'s an object'},
        obj_three: {'property_and_value_will': 'be kept, because additionalProperties are allowed'},
    })
})

app.listen(3000, (err) => {
    if (err) {
        app.log.error(err)
        process.exit(1)
    }
})
```
The script above produces the following result:
```json
{
    "string_one": "foo",
    "obj_one": {},
    "obj_two": {},
    "obj_three": {
        "property_and_value_will": "be kept, because additionalProperties are allowed"
    }
}
```

### Expected Behavior

The value of property `obj_two` should be preserved because it is a valid `object`.
```json
{
    "string_one": "foo",
    "obj_one": {},
    "obj_two": {
        "value_will": "be removed, but should be kept, because it's an object"
    },
    "obj_three": {
        "property_and_value_will": "be kept, because additionalProperties are allowed"
    }
}
```

**Comment by climba03003** [comment]
I think it is the expected behavior.
https://github.com/fastify/fast-json-stringify#additional-properties

> If additionalProperties is not present or is set to false, every property that is not explicitly listed in the properties and patternProperties objects,will be ignored, as described in [Missing fields](https://github.com/fastify/fast-json-stringify#missingFields). Missing fields are ignored to avoid having to rewrite objects before serializing.

**Comment by Jiri-Mihal** [comment]
This problem does not affect `additionalProperties`. Please see `obj_two` where this problem lies. For simplicity, use this code:
```node
const app = require('fastify')();

const schema = {
    response: {
        200: {
            type: 'object',
            properties: {
                string_one: {type: 'string'},
                obj_one: { type: 'object' },
                obj_two: { type: 'object' }
            }
        }
    }
}

app.get('/', {schema}, (req, res) => {
    res.send({
        string_one: 'foo',
        obj_one: 'value will be removed, it\'s not an object',
        obj_two: {'value_will': 'be removed, but should be kept, because it\'s an object'}
    })
})

app.listen(3000, (err) => {
    if (err) {
        app.log.error(err)
        process.exit(1)
    }
})
```

**Comment by climba03003** [comment]
As it is a `object`, it do not has `additionalProperties` and `properties`. The `additionalProperties` will set to `false`, then no output will be expected for `obj_two`.

This rule do not apply to only the `root` context.

**Comment by climba03003** [comment]
This is the working example for your case. You need to explicitly set `additionalProperties` for `obj_two`. Otherwise, it will treat it as `additionalProperties: false`.
```js
const app = require("fastify")();

const schema = {
  response: {
    200: {
      type: "object",
      properties: {
        string_one: { type: "string" },
        obj_one: { type: "object" },
        obj_two: { type: "object", additionalProperties: true },
      },
    },
  },
};

app.get("/", { schema }, (req, res) => {
  res.send({
    string_one: "foo",
    obj_one: "value will be removed, it's not an object",
    obj_two: {
      value_will: "be removed, but should be kept, because it's an object",
    },
  });
});

(async function () {
  const res = await app.inject({ path: "/" });
  console.log(res.payload);
})();
```

**Comment by Jiri-Mihal** [comment]
I see it now, thank you.
