### ISSUE TITLE
feature request: inherit request id from header

### ISSUE THREAD

**Issue by paolochiodi** [fastify/fastify#343]
In a multi services environment request id can be helpful to track the flow of a request through different services. 
In order to do this the request id must be shared adding it to the headers of requests and responses.

This can be accomplished in fastify here https://github.com/fastify/fastify/blob/master/fastify.js#L150 in one of two ways:
- checking for the `request-id` header by default with something like `req.id = req.headers['request-id'] || genReqId()`
- delegating to a custom genReqId function, which requires to provide the req object as input to the function

If maintainers are open to this change I can further investigate and provide a PR

**Comment by allevo** [comment]
Hi and thank you for checking out `fastify`!

Currently, as you pointed out, this cannot be done.
The solution may be not so simple. Anyway, please feel free to send PR!

**Comment by mcollina** [comment]
This was already done within pino-http. It should be as simple as point 1.

**Comment by paolochiodi** [comment]
@mcollina I checked how pino-http works in uses solution 2: https://github.com/pinojs/pino-http/blob/master/logger.js#L53

However, the implementation of the id generator just relay the id already present on the request: https://github.com/pinojs/pino-http/blob/master/logger.js#L102.
I'm afraid this won't work on fastify because as far as I know node.js doesn't automatically create it.

If you're ok with that I'll use solution 2 and make `genReqId` check for the header first

**Comment by paolochiodi** [comment]
OT: there's a specific reason why you're not using uuids for request ids?

**Comment by mcollina** [comment]
generating uuid is extremely slow.

**Comment by mcollina** [comment]
I'm ok with what you propose in https://github.com/fastify/fastify/issues/343#issuecomment-336444686.

**Comment by mcollina** [comment]
Landed in #349
