### ISSUE TITLE
Calling Reply.getResponseTime() multiple times results in different times

### ISSUE THREAD

**Issue by thomaschaaf** [fastify/fastify#3430]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Node.js version

14.18.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.1

### Description

Calling Reply.getResponseTime() multiple times results in different values. Optimally the response time should be set at some point and the function simply return that value.

### Steps to Reproduce

The function uses Date.now() to calculate the value every time it is called.

### Expected Behavior

The response time should be the same for one requests independent of when you are calling the getResponseTime function.

**Comment by mcollina** [comment]
Thanks for reporting. The [documentation](https://www.fastify.io/docs/latest/Reply/#getresponsetime) states:

> Invokes the custom response time getter to calculate the amount of time passed since the request was started.

This is correct and matches the implementation you are describing.

> The response time should be the same for one requests independent of when you are calling the getResponseTime function.

When are you calling `getResponseTime()`? How could it possibly be the same independently on when are are calling it?

**Comment by thomaschaaf** [comment]
@mcollina I am calling it in my application to report a metric to prometheus and there is also a log by fastify: https://github.com/fastify/fastify/blob/main/lib/reply.js#L659 these times now differ. I don't understand why that value is not persisted to the request like the status code but needs to be calculated twice.

**Comment by mcollina** [comment]
At what point in the request lifecycle are you collecting the data to send to prometheus?

Are you asking if we could set the response time once the response is sent with?

**Comment by thomaschaaf** [comment]
We are using nestjs and have an Interceptor (listener attached to the on finish and error event of fastify) Thus after the request is finished we want to execute some code. I did some async stuff (talking to a different server) before collecting the metric from the fastify reply and the numbers were just completely wrong. If of course fetching the value is the first thing I do everything is correct.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
