### ISSUE TITLE
Can't connect on AWS EC2 T4G

### ISSUE THREAD

**Issue by brwnll** [fastify/fastify#3440]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.3

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Amazon Linux 2 AMI (HVM), SSD Volume Type (ARM processor)

### Description

I cannot figure out for the life of me why, but running the hello world fastify example on a T4G AWS EC2 instance (ARM) never accepts a request. `ERR_CONNECTION_REFUSED`.  Script says it's running and never logs a request or error.

Switching the same file to ExpressJS responds as expected.

Did I miss a step to get this up and running? Trying to upgrade from Fastify 0.23.0. 

### Steps to Reproduce

Launch new EC2 t4g.micro.

Install NVM, then NodeJS v16 & git. Clone hello world example, install dependencies and run server.

App says it is up and listening, but attempts to connect result in `ERR_CONNECTION_REFUSED`. 

Installing and using the ExpressJS router is able to return requests as expected.

**Comment by Creative-Difficulty** [comment]
@brwnll I have the same problem, what was the fix??
