### ISSUE TITLE
ajv JSON serialization

### ISSUE THREAD

**Issue by xacrimon** [fastify/fastify#3441]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Replace the current schema JSON response serialization system with validation and serialization introduced in newer ajv versions.

### Motivation

ajv recently introduced support for serializing JSON with some impressive performance.
For performance and cohesiveness reasons I propose switching to it instead of fast-json-stringify.

**Comment by Eomm** [comment]
It should be already doable with the actual `schemaCompiler` interface.
Did you try it?

**Comment by mcollina** [comment]
As written in th Ajv docs, they support serialization only for JTD, not JSON Schema
