### ISSUE TITLE
Instance listen method definition - callback's Error should be nullable

### ISSUE THREAD

**Issue by sf3ris** [fastify/fastify#3448]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Node.js version

14.18.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.3 LTS

### Description

After registering a new [FastifyInstance](https://github.com/fastify/fastify/blob/ea0e90137406db6e601c13c312ede4aeefb03235/types/instance.d.ts#L22) we usually use the `listen` method to start receiving requests.
The `listen` method definition is declaring the callback's `error` as a non nullable `Error` type but instead when we spin up the server without any problem, that error is null.

Actual `listen` method ts definition:
```ts
  listen(port: number | string, address: string, backlog: number, callback: (err: Error, address: string) => void): void;
  listen(port: number | string, address: string, callback: (err: Error, address: string) => void): void;
  listen(port: number | string, callback: (err: Error, address: string) => void): void;
  listen(port: number | string, address?: string, backlog?: number): Promise<string>;
  listen(opts: { port: number; host?: string; backlog?: number }, callback: (err: Error, address: string) => void): void;
  listen(opts: { port: number; host?: string; backlog?: number }): Promise<string>;
```

The major problem is that the linter (eslint) with the rule [@typescript-eslint/no-unnecessary-condition](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md) will incur in an error because is expecting an `Error` and should never be null.

### Steps to Reproduce

Enabling the typescript linter rule:
```json
{
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "./tsconfig.json",
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "ignorePatterns": ["build/*"],
    "plugins": ["@typescript-eslint"],
    "extends": [
        "standard",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "prettier"
    ],
    "rules": {
        "@typescript-eslint/no-unnecessary-condition": "error",
    }
}

```

```ts
server.listen(port, host, (err, address) => {
  if (err) { // Unnecessary conditional, value is always truthy.eslint@typescript-eslint/no-unnecessary-condition
    server.log.error(err);
    process.exit();
  }
  console.log(`Server listening at ${address}`);
});
```

### Expected Behavior

I think the definition should declare the callbacks `error` as nullable to respect the real `listen` method behavior and avoiding using workarounds to make the linter be successful.

**Comment by sf3ris** [comment]
If the issue is confirmed, I can try to fix it opening a PR.

**Comment by mcollina** [comment]
Yes, confirmed.
