### ISSUE TITLE
Wrong TypeScript definition for validatorCompiler

### ISSUE THREAD

**Issue by joshuaavalon** [fastify/fastify#3457]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.1

### Node.js version

14.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

First, [buildValidator](https://github.com/fastify/fastify/blob/1dc4717fda444a790a1eedc9ffe18dfe9ab08aa8/fastify.d.ts#L140) in options accepts [`ValidatorCompiler`](https://github.com/fastify/ajv-compiler/blob/69ea0cf3beab5002b3ddaf0262a6e07875567683/index.d.ts#L3)

```ts
export type ValidatorCompiler = (
  externalSchemas: unknown,
  options: Options
) => Ajv;
```

However, actually it accepts

https://github.com/fastify/fastify/blob/53fe09f6664776330054a968237f04701ecdc6b7/lib/schema-controller.js#L100

https://github.com/fastify/fastify/blob/1dc4717fda444a790a1eedc9ffe18dfe9ab08aa8/fastify.d.ts#L145-L148

Second, `fastify.validatorCompiler` is not defined.

### Steps to Reproduce

I follow the [official guide](https://www.fastify.io/docs/latest/Server/#schema-controller) to try to use Ajv V8. I discover this problem when I code in TypeScript.

### Expected Behavior

There should be not TypeScript errors.

**Comment by climba03003** [comment]
There must be a TypeScript error, because we use `ajv@6` and the typings for `ajv@6` and `ajv@8` is not compatible.

**Comment by Eomm** [comment]
Could you try this blog post too: https://www.nearform.com/blog/upgrading-fastifys-input-validation-to-ajv-version-8/ ?

**Comment by joshuaavalon** [comment]
> There must be a TypeScript error, because we use `ajv@6` and the typings for `ajv@6` and `ajv@8` is not compatible.

Yes, fastify does ship with ajv@6. However, the [official guide](https://www.fastify.io/docs/latest/Server/#schema-controller) states that you can replace the custom validator via server config, including ajv@8. There also examples in `@fastify/ajv-compiler`'s REMAME.


> Could you try this blog post too: https://www.nearform.com/blog/upgrading-fastifys-input-validation-to-ajv-version-8/ ?

I don't have any problems if I casts the types to `any`.

My problems are the TypeScript definition is not the same as the implementation. 

`buildValidator` in the server configuration accept server configuration `ajv` object instead of `ajv` options directly.

**Comment by climba03003** [comment]
> 
> My problems are the TypeScript definition is not the same as the implementation.
> 
> `buildValidator` in the server configuration accept server configuration `ajv` object instead of `ajv` options directly.

It is hard to tell is the TypeScript definition is matching the real case or not. 

When you use a custom validator builder, it should be stated that the option is matching `ajv` options. By eliminating the an extra level of `customOptions`, because most of the user would not need it when using a custom validator, the typing using `Ajv.Options` is totally acceptable in my side.

If it need to match the real case, the `options` would simply be `unknown` or `any`. Because we should not restrict any of those usage and the typing is useless in this case.
```ts
export type ValidatorCompiler = (
  externalSchemas: unknown,
  options: any
) => any;
```
