### ISSUE TITLE
Clear error reporting?

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [fastify/fastify#3461]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I feel that a clearer error reporting system would be helpful, especially in routing and logging.

### Motivation

I once tried logging a subset of the `req` object, not understanding the serializer. Then I got an error saying `cannot get property 'accept-version' of undefined`. Errors like this make it hard for beginner developers to use.

### Example

Code:
```node
...
fastify.setErrorHandler(async (err, req, res) => {
  req.log.error({
    req: {
      method: req.method,
      url: req.url
    }
  });
  ...
});
...
```
Current error:
```
Cannot get property 'accept-version' of undefined.
```
Proposed error:
```
Invalid request in serializer.
```
Or something similar.

**Comment by climba03003** [comment]
`cannot get property 'accept-version' of undefined` is throw by `nodejs`. How can we modify this message case by case?

I propose to update this line
https://github.com/fastify/fastify/blob/48a99a470f82461c711a2c914e8221e49c731b07/lib/logger.js#L53
to `req.headers && req.headers['accept-version']`

**Comment by mcollina** [comment]
Let's do that!
