### ISSUE TITLE
Can't pipe streams

### ISSUE THREAD

**Issue by coolaj86** [fastify/fastify#3471]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

Similar to https://github.com/fastify/fastify/issues/534

### Fastify version

3.24.0

### Plugin version

N/A

### Node.js version

14.18.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.0.1

### Description

A basic echo test of piping the request as the respond fails:

```js
reply.send(request.raw)
```

### Steps to Reproduce

1. Create a new fastify project
   ```bash
   npm init fastify
   ```
2. Create a route that handles an upload `./routes/api/upload/index.js`
   ```js
   'use strict';

   module.exports = async function (fastify, opts) {
     fastify.addContentTypeParser('*', { parseAs: 'buffer' }, function (request, payload, done) {
       done();
     });

     fastify.post('/:name', async function (request, reply) {
         reply.send(request.raw)
     });
   };
   ```
3. Run
   ```bash
   npm run dev
   ```
4. Test
   ```bash
   echo 'Hello' > file.txt
   curl http://localhost:3000/api/upload/file.txt -d @file.txt
   ```

### Expected Behavior

Data should go strait through the pipe.

**Comment by climba03003** [comment]
How can the data be passed through when it is already `drain`?

**Comment by Eomm** [comment]
Did you try?

```diff
-  fastify.post('/:name', async function (request, reply) {
+  fastify.post('/:name', function (request, reply) {
      reply.send(request.raw)
  });
```

**Comment by coolaj86** [comment]
```diff
-  fastify.addContentTypeParser('*', { parseAs: 'buffer' }, function (request, payload, done) {
+  fastify.addContentTypeParser('*', function (request, payload, done) {
```

I had copied from a few different examples and left in `parseAs: 'buffer'`. I thought this was just indicating content-type (like `encoding`, e.g. "It's okay that this in not UTF-8"). I didn't realize that, without taking any imperative action, it was consuming the buffer.

**Comment by coolaj86** [comment]
> ```diff
> -  fastify.post('/:name', async function (request, reply) {
> +  fastify.post('/:name', function (request, reply) {
>       reply.send(request.raw)
>   });
> ```

FYI: If that had made a difference, it would definitely be a bug. Promises are synchronous unless they have something async, IIRC, and a Stream should not start "flowing" until `stream.resume()`, `stream.uncork()`, or `stream.on('readable', fn)`.

**Comment by fox1t** [comment]
The promise constructor is executed "synchronously", not the promise itself! 
An async function will always be executed asynchronously, regardless of the code inside it!
