### ISSUE TITLE
Schema with key or id already exists since version 3.12.0 and even 3.24.0

### ISSUE THREAD

**Issue by meerkat999** [fastify/fastify#3478]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.0

### Node.js version

14.17.4

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Hello everyone, I'm trying to generate the schema for two endpoints (create and update), each service has to receive an object named MyObject and returns the same body (MyObject)

I created two schemas for my objects:

- myObject
- myAttr

myObject has one property that references myAttr

But when I try to register the schemas into the endpoints (create and update schemas), the console said:
`schema with key or id "myAttr" already exists`

See the code on this [Minimal, Reproducible Example](https://runkit.com/meerkat999/runkit-npm-fastify)

(It's my first Issue on github, be easy pls :) )

### Steps to Reproduce

[Minimal, Reproducible Example](https://runkit.com/meerkat999/runkit-npm-fastify)

``` 

app.addSchema({ '$id': 'myObject', type: 'object', properties: { thing: { '$ref': 'myAttr#' }}})
app.addSchema({ '$id': 'myAttr', type: 'string'})

const createSchema = {
    response: {
        200: {
            $ref: "myObject#"
        }
    },
    body: {
        $ref: 'myObject#'
    }
}

const updateSchema = {
    response: {
        200: {
            $ref: "myObject#"
        }
    },
    body: {
        $ref: 'myObject#'
    }
}

app.get('/create', {
    schema: createSchema
}, (req, reply) => { })

app.get('/update', {
    schema: updateSchema
}, (req, reply) => { })

```

[Minimal, Reproducible Example](https://runkit.com/meerkat999/runkit-npm-fastify)

### Expected Behavior

No console errors

**Comment by mcollina** [comment]
cc @Eomm

**Comment by meerkat999** [comment]
@jsumners

**Comment by MetCoder95** [comment]
I think the issue is not related directly with fastify itself but with a dependency, in specific `@fastify/ajv-compiler`, as I notice that in the version `v1.0.0`, the dependency is not checking if the schema already exists, causing the chance to collide by trying to add the same schema twice (which is happening in this case).

But, on the most recent version `>v2.0.0`, this is already fixed, but not sure if planned to be added to `fastify@v3.x.x`.

Collision cause in `ajv-compiler`:
```js
  const sourceSchemas = Object.values(externalSchemas)
  for (const extSchema of sourceSchemas) {
    ajv.addSchema(extSchema)
  }

```

**Comment by Eomm** [comment]
I think this issue could be a duplicated https://github.com/fastify/fast-json-stringify/issues/308
