### ISSUE TITLE
Refactor Context constructor and avoid positional arguments

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3481]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

In the `next` branch, the `Context` constructor has a lot of positional arguments that make the code hard to read.
This should be moved to use an option object: https://github.com/fastify/fastify/blob/fd8503a60623613a5f20b04965b540f62a266051/lib/context.js#L7

**Comment by climba03003** [comment]
Resolved by #3483
