### ISSUE TITLE
serializerCompiler documentation misleading ?

### ISSUE THREAD

**Issue by haoadoresorange** [fastify/fastify#3487]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi,

I'm not really sure about this but it seems that the documentation for the `serializerCompiler` [here](https://www.fastify.io/docs/latest/Validation-and-Serialization/#serializer-compiler) saying that
> You must provide a function to serialize every route where you have defined a response JSON Schema.

is a little bit misleading. You **don't have** to provide a function, only when you want to change the default.

Unless I'm missing something.

**Comment by mcollina** [comment]
Good spot! Would you like to send a PR to fix the sentence?

**Comment by mm1995tk** [comment]
Hello.
If you don't mind, I'd like to submit a PR.

**Comment by Eomm** [comment]
Go for it!

**Comment by haoadoresorange** [comment]
Nice ! Thank you in advance @mm1995tk !

**Comment by climba03003** [comment]
Resolved by #3490
