### ISSUE TITLE
Restructure docs folder with major version subfolders

### ISSUE THREAD

**Issue by lachlancollins** [fastify/fastify#3492]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, I thought it would be best if I added this as an issue separate from #3474 to better gather opinions. One of the big goals of moving to a newer website compiler (such as Docusaurus) is link validation to ensure we aren't pushing broken links to production. Many of these newer solutions also allow the use of Markdown-embedded metadata at the top of the file to customise page title, descriptions, ordering, URL paths, etc.

The current solution for generating docs is to fetch the docs from each GitHub release. However, this prevents us from having any capacity to modify any broken links or add metadata to old releases going into the future. Additionally, in fastify/website#291 there seems to be consensus that it is unnecessary to keep minor version documentation (e.g. 3.23.x vs 3.24.x) visible on the website.

For these reasons, I propose a new structure to docs in the main repo:

- /docs
  - /v1
    - Pages.md
    - Go.md
    - Here.md
  - /v2
    - Also.md
    - Here.md
  - /v3
    - And.md
    - Here.md

This would mean the docs are always built from the `main` branch, and hence docs of any major versions can be fixed or updated if or when changes are required. I believe this would be a framework-agnostic issue, but I am especially interested in this change for [`website-next`](https://github.com/fastify/website-next) and Docusaurus.

If there is support for this change, I would be happy to restructure this myself (using v2.15.3 for v2 and v1.14.6 for v1) and submit a PR into #3474. Thanks!

**Comment by climba03003** [comment]
I am not a fan on keeping the old docs in `main` repo.
The old docs can be merged to `1.x` and `2.x` branch. Then pull the docs on those branch.

**Comment by lachlancollins** [comment]
Oh amazing - I didn't notice this repo had 1.x and 2.x branches, that's a much better solution. Thanks @climba03003!

**Comment by jsumners** [comment]
Yes, maintaining the docs on their version branches is the proper way to do this. The proposal would have introduced a much bigger maintenance burden than we already face.
