### ISSUE TITLE
How to use class-validator & class-transformer in fastify as alternative of ajv?

### ISSUE THREAD

**Issue by i-coderdev** [fastify/fastify#3497]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have searched existing issues to ensure the issue has not already been raised

**Comment by L2jLiga** [comment]
Hey, I think this issue can be helpful https://github.com/L2jLiga/fastify-decorators/issues/565

Btw you can't use it instead of AJV but can with

**Comment by i-coderdev** [comment]
I really don't like the ajv, I think if fastify team remove this kind default validation then it can be more perfect to use.

**Comment by i-coderdev** [comment]
> 

I use typeorm so I don't like to use ajv I want to use classt-validator in typeorm entitie file, and also some important plugins are not support schema validation like fastify-multer.
So it is important to remove default validation way.

**Comment by mcollina** [comment]
I don't think this is going to happen, closing.
