### ISSUE TITLE
Alias preParsing to onRequest hook. Deprecate preParsing

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3503]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently we have `onRequest` and `preParsing` that happens together. I think `preParsing` should be removed.

```
Incoming Request
  │
  └─▶ Routing
        │
        └─▶ Instance Logger
             │
   4**/5** ◀─┴─▶ onRequest Hook
                  │
        4**/5** ◀─┴─▶ preParsing Hook
                        │
              4**/5** ◀─┴─▶ Parsing
                             │
                   4**/5** ◀─┴─▶ preValidation Hook
                                  │
                            400 ◀─┴─▶ Validation
                                        │
                              4**/5** ◀─┴─▶ preHandler Hook
                                              │
                                    4**/5** ◀─┴─▶ User Handler
                                                    │
                                                    └─▶ Reply
                                                          │
                                                4**/5** ◀─┴─▶ preSerialization Hook
                                                                │
                                                                └─▶ onSend Hook
                                                                      │
                                                            4**/5** ◀─┴─▶ Outgoing Response
                                                                            │
                                                                            └─▶ onResponse Hook
```

**Comment by jsumners** [comment]
Can you discuss how this would affect https://github.com/fastify/fastify/pull/1377 and https://github.com/fastify/help/issues/37?

**Comment by mcollina** [comment]
In essence we refactored the lifecycle of a request between v2 and v3 and we removed the internal middleware support in v3.
A long time ago, onRequest happened before routing, and we had middlewares between onRequest and preParsing.

At this point we have two hooks running one after another with no real benefit.

We could also alias preParsing into onRequest and deprecate it.

**Comment by jsumners** [comment]
> We could also alias preParsing into onRequest and deprecate it.

This is a good approach.

**Comment by kerm1it** [comment]
can I work for this?

**Comment by RafaelGSS** [comment]
Go for it!

**Comment by darkgl0w** [comment]
Some packages will be affected by this change (to keep track of the packages that will need changes) :
- [ ] `fastify-compress` (adds `preParsing` hooks)
- [ ] `fastify-cookie` (adds `preParsing` hooks)
- [ ] `fastify-caching` (references in tests)
- [ ] `fastify-request-context` (should investigate but it seems to add `preParsing` hooks and there are references in tests)
- [ ] `fastify-websocket` (references in tests)
- [ ] `fastify-vite` (I have seen references to `preParsing` but I don't know to what extents it's used. cc @galvez )

About `fastify-compress`, I am currently working on the package (see https://github.com/fastify/fastify-compress/issues/198) and so I can add another step and submit a 3rd PR that removes the `preParsing` hooks (like this the 1st 2 PRs can land as a patch version and a 3rd one removing the use of `preParsing` could land as a major following `fastify` v4 release).

**Comment by mcollina** [comment]
Not that those modules would not directly break but rather they'll see a deprecation warning as we settled into this approach:

> We could also alias preParsing into onRequest and deprecate it.

IMHO I think we can move most of them to onRequest, there is no actual reason to keep them on preParsing.

**Comment by darkgl0w** [comment]
> IMHO I think we can move most of them to onRequest, there is no actual reason to keep them on preParsing.

I agree, I think that was the consensus when `preParsing` has been deprecated and since then `onRequest` has been my go to.

**Comment by kerm1it** [comment]
I also think so. We should deprecate it first, otherwise it will cause break change.

**Comment by darkgl0w** [comment]
It is already deprecated.
Adding a `preParsing` hook currently trigger this warning :
```sh
> (node:18534) [FSTDEP004] FastifyDeprecation: You are using the legacy preParsing hook signature. Use the one suggested in the documentation instead.
> (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by galvez** [comment]
fastify-vite does not use it directly, just allows it to be passed to route definitions via the wrapper. I'll remove it.

**Comment by kerm1it** [comment]
> It is already deprecated and adding a `preParsing` hook currently triggers this warning :
> 
> ```sh
> 
> > (node:18534) [FSTDEP004] FastifyDeprecation: You are using the legacy preParsing hook signature. Use the one suggested in the documentation instead.
> 
> > (Use `node --trace-warnings ...` to show where the warning was created)
> 
> ```

And what should I do？Remove it directly？ because I see this is feature for 4.0.0

**Comment by darkgl0w** [comment]
you should alias `preParsing` to `onRequest` hook and keep the current deprecation message in place.

**Comment by jsumners** [comment]
@kerm1it that deprecation was about the _signature_ of the `preParsing` hook. This issue is about deprecating the hook entirely. So @darkgl0w is correct about the course of action.

**Comment by kerm1it** [comment]
Thanks, I already have a todo list about this issue, everyone can help me review it. If no problem,  I will follow it to do.

- [ ] move `preParsing` to `onRequest` and run it for compatibility
- [ ] remove  `preParsing` from hooks
- [ ] update warning message
- [ ] test  `preParsing` whether can work as before
- [ ] test warning message whether update
- [ ] remove `preParsing` hook related message from docs

**Comment by mcollina** [comment]
@kerm1it go for it!

**Comment by Eomm** [comment]
@kerm1it are you working on this?

**Comment by Eomm** [comment]
@darkgl0w regarding the:

>  fastify-compress (adds preParsing hooks)

I think we are blocked by this issue: right now the `onRequest` does not have the ability to manipulate the payload (as the `preParsing` hook does).

So, I think we need to wait this feature before proceeding on that side.
Do you agree with that or have you another idea?

**Comment by kerm1it** [comment]
I'm so sorry for this.
I can't work for this because of supporting a emergency project of my company for a long time suddenly.

**Comment by mcollina** [comment]
Turns out this is actually a bad idea and we need preParsing as it fulfill a need.

This explains why we need this: https://github.com/fastify/fastify/pull/2286.

**Comment by darkgl0w** [comment]
> @darkgl0w regarding the:
> 
> > fastify-compress (adds preParsing hooks)
> 
> I think we are blocked by this issue: right now the `onRequest` does not have the ability to manipulate the payload (as the `preParsing` hook does).
> 
> So, I think we need to wait this feature before proceeding on that side. Do you agree with that or have you another idea?

Sorry for the somewhat late response, I was between 2 flights and I couldn't take the time to respond due to a very tight schedule.

Regarding `fastify-compress` the `preParsing` hook is in fact needed because we need to manipulate the request payload and with the `onRequest` hook it is currently impossible.

@mcollina > As it is now abandoned should we revert the changes that where pushed to `fastify-cookie`, `fastify-caching`, `fastify-request-context` and `fastify-websocket` ?

NB: The approach of @Eomm in https://github.com/fastify/fastify/pull/3598 to merge the `preParsing` ability to access and modify the request payload inside the `onRequest` hook was interesting.

**Comment by mcollina** [comment]
> @mcollina > As it is now abandoned should we revert the changes that where pushed to fastify-cookie, fastify-caching, fastify-request-context and fastify-websocket ?

I would keep those changes. `onRequest` should have been used in all cases anyway.

The approach @Eomm had is great. It's just that I'm not sure it's worth the breakage in the first place. The current preParsing hook does its job.

I forgot why we added it in the first place. It's also a bit confusing for people.

I thought one

**Comment by darkgl0w** [comment]
Ok nice, that makes sense in terms of DX having a dedicated hook is more intuitive than having one with multiple functionalities :)

Regarding the aforementioned packages in my previous comment I will add back the `preParsing` test cases at least to make sure that future PRs won't introduce any problem ^^
