### ISSUE TITLE
Add GETOnly to Server options

### ISSUE THREAD

**Issue by akaNightmare** [fastify/fastify#3520]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be great to add `GETOnly`(fiber analog) to pass GET requests only

### Motivation

Rejects all non-GET requests if set to true. This option is useful as anti-DoS protection for servers accepting only GET requests. The request size is limited by maxParamLength if GETOnly is set.

### Example

```javascript
fastify({
 // ... other options
 GETOnly: true,
})
```

**Comment by mcollina** [comment]
Thanks for suggesting this! I think this could be easily achieved by using a onRequest (send a standard response for non-gets) o onRoute (throw when a non-get is registered) hook.

I'm going to mark this as a "plugin" issue.

**Comment by DanieleFedeli** [comment]
I am working on this,

It simply add an hook on preRequest, if it is different from 'GET' it respond with a custom status code.
Now I am updating the README.

This is my first time contributing to an open source project, so any advice is welcome.

https://github.com/DanieleFedeli/fastify-get-only

**Comment by RafaelGSS** [comment]
@DanieleFedeli could you add this plugin to our [Ecosystem](https://github.com/fastify/fastify/blob/main/docs/Guides/Ecosystem.md#community)?

**Comment by DanieleFedeli** [comment]
I have just created a [pull request](https://github.com/fastify/fastify/pull/3548)
