### ISSUE TITLE
addContentTypeParser Request does not have isMultipart property

### ISSUE THREAD

**Issue by PS1TD** [fastify/fastify#3521]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Node.js version

16.12.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

21.04

### Description

While setting up apollo with fastify using the apollo-server-fastify I have stumbled on missing typescript definitions.
Using the code provided by apollo here: https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-fastify

addContentTypeParser request does not have isMultipart property(at least that's what typescript thinks from its definitions)
Also in apollo docs done() does not accept any arguments which typescript also complains about because it expects an err and body.
Setting it to body(null, null) worked but not sure if it might cause any issues later on.

### Steps to Reproduce

Follow the  apollo-server-fastify starter boilerplate code
https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-fastify

### Expected Behavior

Expected typescript to know the correct definitions.

**Comment by jsumners** [comment]
We do not have any affiliation with the Apollo project. It sounds like you should be filing an issue with them.

**Comment by PS1TD** [comment]
I get that apollo probably needs to update their docs, however, it seems that the issue is related to typescript definitions being different from what actually seems to work. If there is a way to write it so that typescript does not complain, I would love to know.
P.S I will open an issue with apollo as well.

**Comment by climba03003** [comment]
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-fastify/src/ApolloServer.ts

I can see that it never use `fastify-multipart` or any other multipart parser packages.
It is true that no `isMultipart` should exist on the `request` object.

**Comment by PS1TD** [comment]
Would including fastify-multipart be the solution?
