### ISSUE TITLE
Config Option Proposal: logger.useLocalhost

### ISSUE THREAD

**Issue by galvez** [fastify/fastify#3522]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add an optional flag, say,`logger.useLocalhost` to determine the local bind address should be displayed as `localhost` instead of `127.0.0.1`.

### Motivation

Right now, running a Fastify server locally binds to 127.0.0.1 as expected.

```
[08:03:15 UTC] INFO: Server listening at http://127.0.0.1:3000
```

Typically I use Cmd+Click directly on the terminal to load that URL on my browser.

The problem is that a number of external supporting services whitelist `localhost`, not `127.0.0.1` by default.

Which forces me to manually switch navigation over the `localhost` address.

### Example

```js
const app = Fastify({
  logger: {
    useLocalhost: true,
  }
})
```

**Comment by climba03003** [comment]
I do not understand the problem. What services in particular allow `localhost` but not `127.0.0.1`?
https://github.com/fastify/fastify/blob/9814c3828ff020a90bcb364cea06d2cee5f4b1bc/lib/server.js#L128

The address is actually provided by `http` / `https`.

**Comment by galvez** [comment]
**Adyen**, **Firebase** etc come to mind instantly — there are others.

**Comment by mcollina** [comment]
Unfortunately this is not doable in the current state of things.

Fastify adopts a secure pattern by  _always_ listening to 127.0.0.1 (ipv4 address), not 0.0.0.0. On Windows, localhost resolves to ::1 (ipv6 address) and then ::1. When a browser try to open localhost, if it tries ::1 first... they will have 1s wait, completely destroying the user experience.

Given the DNS change in v17/v18, I think our only possibility is to support binding to multiple host/port combos and use that to bind to both 127.0.0.1 and ::1. Then we can advertise localhost as a domain.

**Comment by galvez** [comment]
Got it. Probably better to try and always get `127.0.0.1` whitelisted then.

**Comment by mcollina** [comment]
I think we'd have to do the double binding I described above anyway.
