### ISSUE TITLE
Proposal: `env` option for Server, built-in `dev` flag

### ISSUE THREAD

**Issue by galvez** [fastify/fastify#3523]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

1) Allow Server to receive a precomputed `env` option, which is exposed as `instance.env`.

2) Automatically determine if `process.env.NODE_ENV` is not `production` via a `fastify.dev` flag.

### Motivation

This has become a recurring idiom:

```js
const dev = process.env.NODE_ENV !== 'production'

const app = Fastify({
  logger: {
    ...dev && {
      prettyPrint: {
        translateTime: 'HH:MM:ss Z',
        ignore: 'pid,hostname'
      }
    }
  },
})
```

It would be nice if Fastify would automatically set a `dev` flag, and logging options could be set specifically for the development environment. 

Along the same line, allow Fastify's Server to receive a `env` option and expose `.env` on the instance.

### Example

```js
const app = Fastify({
  dev: {
    logger: {
        prettyPrint: {
          translateTime: 'HH:MM:ss Z',
          ignore: 'pid,hostname'
        }
      }
  },
})
```

Proposed usage with `env-schema` (requires feature addition to `env-schema`):

```js
const env = require('env-schema')({
  schema: {
    type: 'object',
    required: ['NODE_ENV'],
    properties: {
      NODE_ENV: {
        type: 'string',
        default: 'dev'
      }
    }
  },
  dotenv: true,
  // Default behavior, customizable
  dev: env => env.NODE_ENV !== 'production',
})

const app = Fastify({
  env,
  dev: {
    logger: {
        prettyPrint: {
          translateTime: 'HH:MM:ss Z',
          ignore: 'pid,hostname'
        }
      }
  },
})
```

**Comment by zekth** [comment]
In your example `dev` is not a flag it's a whole object. I'm not really into this way of managing env; because in the case you're showing you're only making a difference between `dev` and `prod` which lacks of customization. What about a config factory for example? I think lot of people like i do, have written their own config factory for plugins based on environment variable. Like `dev/staging/experimental/prod/....` .

```js
  // Default behavior, customizable
  dev: env => env.NODE_ENV !== 'production',
 ```
This adds a underlying behavior based on environment variable, which hasn't been ever done in fastify afaik. I'm not really into this neither, because it's not explicit in the code.

**Comment by mcollina** [comment]
This is a fundamental antipattern which causes significant problems in production for a lot of people.

A few modules in the express family turns on some optimizations only if NODE_ENV is set to production. Then, some folks started using NODE_ENV to load their app config file. The end result is that the deployed staging/qa/etc environments run different code than production.

I'm happy if you'd like to add:

1. docs about this, including some good presets
2. add some of this into fastify-cli (as we run the process, we can  avoid the side effect above).

**Comment by galvez** [comment]
Got it. Come to think of it this can be addressed elegantly by using a config factory like @zekth suggested.

Would be nice still to be able to set a `dev` option to true explictly, so plugins can make informed decisions on when to turn on some specific DX features. This would be different from only enabling features in production, which I imagine can be troublesome like you said — rather this would make it possible to specifically enable development features only.

**Comment by mcollina** [comment]
> Would be nice still to be able to set a dev option to true explictly, so plugins can make informed decisions on when to turn on some specific DX features. This would be different from only enabling features in production, which I imagine can be troublesome like you said — rather this would make it possible to specifically enable development features only.

It's not really different unfortunately. As soon as we do that, we'll start seeing issue of folks that run them on production servers.. because they want some behavior on a plugin. It's something we should avoid.

**Comment by jsumners** [comment]
> Automatically determine if process.env.NODE_ENV is not production via a fastify.dev flag.

I am staunchly against this for the reasons Matteo listed. I wish this was never introduced into the community. An application should assume it is running in production unless explicitly specified otherwise.

**Comment by galvez** [comment]
> As soon as we do that, we'll start seeing issue of folks that run them on production servers.. because they want some behavior on a plugin.

Got it. This is a solid argument, it's a spot between a rock and a hard place to introduce something like this directly in Fastify. Maybe `fastify-cli` is really the place to be looking at, indeed.

I'm closing this issue, thanks everyone for the great feedback.
