### ISSUE TITLE
Graphql story ?

### ISSUE THREAD

**Issue by krircc** [fastify/fastify#354]
now there is express-graphql server, and some framework base on it. but it has PATENTS. I think a fastify-graphql server is more cool. also this is cool Attractive for node web Ecosystem?

**Comment by mcollina** [comment]
Have you tried https://www.npmjs.com/package/fastify-apollo?

**Comment by krircc** [comment]
ok, i find this one. but not try.

**Comment by krircc** [comment]
ok, i find this one. but not try.
