### ISSUE TITLE
Lots of links to the documentation from google are 404

### ISSUE THREAD

**Issue by Teiem** [fastify/fastify#3540]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey,

when i google "fastify route" the first result i get is "https://www.fastify.io/docs/latest/Routes/" which seems to not exist anymore. The is true for nearly every other google link to any part of your documentation.

**Comment by climba03003** [comment]
The documents are re-organized recently and it take some time for Search engine to reflect the changes.

**Comment by mcollina** [comment]
How did you reach that link?

**Comment by Teiem** [comment]
I basically reach those links no matter what i google, e.g. "fastify route" or "fastify ssl"

**Comment by luisorbaiceta** [comment]
There are two options for this. 

1. Wait until site gets crawled again by google
2. Request a crawl in the google search console (someone with credentials)

**Comment by climba03003** [comment]
I think it can be closed safely. I have searched in google, it display the correct links already.
