### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by astesio** [fastify/fastify#355]
Hi guys, 

I tested your framework and it is awesome :)

I have a question,  how I use https using fastify? -> Can I use https with [spdy](https://goo.gl/WRE9V8) or use other library?

Cheers!

**Comment by delvedor** [comment]
Hi! Thank you for checking out the project!
Turns out that we forgot to document it :P

It's very easy:
```js
  const fastify = require('fastify')({
    https: {
      key: fs.readFileSync(path.join(__dirname, 'file.key')),
      cert: fs.readFileSync(path.join(__dirname, 'file.cert'))
    }
  })
```

In any case I suggest you to handle the ssl termination with NGINX or similar, handle it inside Node is very expensive in terms of performances :)

**Comment by mcollina** [comment]
@astesio spdy is not supported, but we plan to add support for HTTP2 #181 using the new node core module.

**Comment by astesio** [comment]
Thanks so much. It is perfect :).

**Comment by svarogaden** [comment]
> Hi! Thank you for checking out the project!
> Turns out that we forgot to document it :P
> 
> It's very easy:
> 
> ```js
>   const fastify = require('fastify')({
>     https: {
>       key: fs.readFileSync(path.join(__dirname, 'file.key')),
>       cert: fs.readFileSync(path.join(__dirname, 'file.cert'))
>     }
>   })
> ```
> 
> In any case I suggest you to handle the ssl termination with NGINX or similar, handle it inside Node is very expensive in terms of performances :)

Hello . 


> Hi! Thank you for checking out the project!
> Turns out that we forgot to document it :P
> 
> It's very easy:
> 
> ```js
>   const fastify = require('fastify')({
>     https: {
>       key: fs.readFileSync(path.join(__dirname, 'file.key')),
>       cert: fs.readFileSync(path.join(__dirname, 'file.cert'))
>     }
>   })
> ```
> 
> In any case I suggest you to handle the ssl termination with NGINX or similar, handle it inside Node is very expensive in terms of performances :)




Hello! Could you give some advice on how to use an SSL certificate like PFX? I try this, but it does not work

const fastify = require('fastify')({
    https: {
      key: fs.readFileSync('certificate.pfx'),
      cert: 'sskey'
    }
  })

**Comment by jsumners** [comment]
The `https` options are directly passed to `https.createServer()`. So you'd need to supply:

```js
{
  https: {
    pfx, // string or Buffer
    passphrase: 'secure pass phrase for pfx if required'
  }
}
```

See https://nodejs.org/dist/latest-v12.x/docs/api/https.html#https_https_createserver_options_requestlistener

**Comment by svarogaden** [comment]
Can you modify the example from the documentation for use with a pfx certificate?
===========================================================
'use strict'

const fs = require('fs')
const path = require('path')
const fastify = require('fastify')({
  http2: true,
  https: {
    key: fs.readFileSync(path.join(__dirname, '..', 'https', 'fastify.key')),
    cert: fs.readFileSync(path.join(__dirname, '..', 'https', 'fastify.cert'))
  }
})

fastify.get('/', function (request, reply) {
  reply.code(200).send({ hello: 'world' })
})

fastify.listen(3000)
