### ISSUE TITLE
Double colon route breaks default fallback when there is another route with a common prefix.

### ISSUE THREAD

**Issue by emfomy** [fastify/fastify#3550]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3.1

### Description

I register two routes:

- `GET /hello`
- `GET /hello:world`

Both routes work fine. However, the server freeze when sending request to `/hello:worl`, `/hello:world1`, `/hello:bar`, `/hello123` (i.e. and route start with `/hello`).

Without `GET /hello` registered, these routes can fall back to 404 properly.

### Steps to Reproduce

```javascript
const fastify = require("fastify")({
  logger: true,
});

fastify.get("/hello", async (request, reply) => {
  return { hello: "" };
});

fastify.get("/hello::world", async (request, reply) => {
  return { hello: "world" };
});

const start = async () => {
  try {
    await fastify.listen(3000);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
```

### Expected Behavior

The server should work fine fallback properly.

**Comment by climba03003** [comment]
I can confirm it is a bug. And it related to the infinite loop in `.find` method.

https://github.com/delvedor/find-my-way/blob/695654cdd452d2993ada90cc87bdf8d695aee076/index.js#L497-L505

**Comment by mcollina** [comment]
Can you open an issue on find-my-way with a reproducible example?

**Comment by emfomy** [comment]
The bug is fixed on `find-my-way` release [v5.1.1](https://github.com/delvedor/find-my-way/releases/tag/v5.1.1).

**Comment by emfomy** [comment]
Is `fastify` compatible with `find-my-way` v5 rather than v4?

**Comment by climba03003** [comment]
> Is `fastify` compatible with `find-my-way` v5?

`find-my-way@5` on the branch `next`. You may need to backport the fix to `find-my-way@4`.

**Comment by emfomy** [comment]
`find-my-way` has released [v4.5.1](https://github.com/delvedor/find-my-way/releases/tag/v4.5.1) with this bugfix.

Will fastify update the package.json file?

**Comment by luisorbaiceta** [comment]
Do you want to send a PR @emfomy ?

**Comment by emfomy** [comment]
OK, I'll do it.

**Comment by climba03003** [comment]
> 

There is no need to update the `package.json` in here. We do not lock the version of `find-my-way`.
Just reinstall your local environment packages, `npm` or `yarn` will fetch the latest.

**Comment by luisorbaiceta** [comment]
Yep, but in my opinion, it's a good thing for developers contributing to fastify to signal which is the currently used version, even if the version is not locked
