### ISSUE TITLE
Optional URL parameters?

### ISSUE THREAD

**Issue by ryexley** [fastify/fastify#356]
I've looked through all of the docs, including those for find-my-way, and I can't seem to find anything that indicates that defining an optional URL parameter is possible. Am I missing something? Would love to be able to do something like:

`fastify.get( "some/:optional?/parameter", ( req, res ) => { ... } );`

Is there a way to do that?

**Comment by delvedor** [comment]
Hi! Thank you for checking out the project!
No, there is no way to do that at the moment, if you want you can fire a pr in [`find-my-way`](https://github.com/delvedor/find-my-way) :)
But I don't think there is an easy solution, and the performances could be affected as well.

At the moment an "hacky" solution could be:
```js
fastify.get('/some/:optional/parameter', handler)
fastify.get('/some/parameter', handler)

function handler (req, reply) {}
```

**Comment by ryexley** [comment]
OK, thanks for clarifying.

**Comment by galvez** [comment]
I miss this feature very much.

@delvedor check out https://github.com/lukeed/matchit -- maybe it's fast enough for Fastify? Check its benchmarks.

**Comment by delvedor** [comment]
@galvez fastify uses find-my-way as other than extremely good performances, it offers a feature that Fastify uses to build the encapsulation system. 
You can take a look at https://github.com/delvedor/find-my-way/pull/167, which introduced a similar feature, but unfortunately the pr is on hold.

**Comment by N00nDay** [comment]
Optional parameters in the middle of the url may not be possible but at the end they work. For example:

Route:
`/something/something-else/:optional`

You can access this route with the following two examples:
`/something/something-else/anything-you-want`
and
`/something/something-else/`

As long as you use the slash at the end it will still hit that end point.
