### ISSUE TITLE
Docs: Database integration concepts

### ISSUE THREAD

**Issue by ruheni** [fastify/fastify#3562]
## 🚀 Feature Proposal

Hello friends 👋🏾

I think it would be valuable to have a section on the docs covering database integration. This would cover tools and libraries such as knexjs, Sequelize, TypeORM, Mikro-orm, Prisma, etc. 

## Inspiration

[Nest Docs](https://docs.nestjs.com/techniques/database)

**Comment by mcollina** [comment]
Moved

**Comment by Fdawgs** [comment]
Closed by #3704
