### ISSUE TITLE
First timers only label?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#3566]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This was brought to my attention through a work conversation on open source -- https://www.firsttimersonly.com

In short, it advocates for a `first-timers-only` label that indicates:

1. this is a good issue for someone new
2. this is an issue we are willing to give extra coaching on in order to get new people into contributing to open source

Should we add this?

**Comment by delvedor** [comment]
I like the idea, but don't we have that already with the `good-first-issue` label?

**Comment by jsumners** [comment]
No. That label is saying "this is a good first issue for anyone looking to contribute to the project." This proposed label is more specific to people having never contributed to OSS before at all.

**Comment by jsumners** [comment]
I think if we were to add this one someone would have to sponsor each issue with the label. They'd be saying: "I'm willing to spend extra time to help coach the person who works on this."

**Comment by mcollina** [comment]
I don't think I would have the bandwidth for that :(.

**Comment by jsumners** [comment]
To clarify the closing of this issue: we welcome contributions from first timers. Unfortunately, we, as a team, do not have the time to coach first timers directly. We always provide constructive feedback through the pull request process, though. So please do not be put off by the closure of this proposal.
