### ISSUE TITLE
Nest + Fastify + AsyncLocalStorage middlewares 

### ISSUE THREAD

**Issue by B5nan** [fastify/fastify#3567]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Node.js version

14/16/17

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The middlewares are not working if fastify (adapter) is installed. When it is removed the middleware starts to work (express adapter), for both GET and POST requests.

### Steps to Reproduce

https://github.com/B4nan/nest-fastify-als

yarn
yarn start
curl localhost:3000
curl -X POST localhost:3000

### Expected Behavior

To return stored value not undefined.

**Comment by luisorbaiceta** [comment]
Fastify does not have middleware pattern behavior out of the box. This issue should be opened in the Nest repo as It is related with how nest adapts the fastify instance

**Comment by B5nan** [comment]
https://github.com/nodejs/node/issues/41278
https://github.com/nodejs/help/issues/3661
https://github.com/nestjs/nest/issues/8843
https://github.com/B4nan/nest-fastify-als
https://github.com/mikro-orm/mikro-orm/discussions/2531#discussioncomment-1822709

**Comment by mcollina** [comment]
Please, use Nest [Discord](discord.gg/NestJS) channel (support) for such questions.

**Comment by B5nan** [comment]
@mcollina pino not work also https://github.com/iamolegga/nestjs-pino/issues/546

**Comment by mcollina** [comment]
I'm not a nest user and I do not have time to invest in maintaining it.
