### ISSUE TITLE
AsyncLocalStorage

### ISSUE THREAD

**Issue by mittche** [fastify/fastify#3569]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

```

'use strict'
const middie = require("middie");
const Fastify = require('fastify')
const minimist = require('minimist')
var { AsyncLocalStorage } = require('async_hooks');

const storage = new AsyncLocalStorage();
const state = { counter: 0 };

async function start (opts) {
  opts = opts || {}

  if (opts.verbose) {
    opts.logger = {
      level: 'info'
    }
  }

  const app = Fastify(opts)
  await app.register(middie);

  app.use((req, res, next) => {
    const id = state.counter++;
    console.log('In Middleware with id ' + id);
     req.custom = "something else";
     storage.run({ id }, next)
  });

  app.post("/test", (req, reply) => {
    const id = storage.getStore()?.id;
    console.log('post', id);

    return {
      regular: req.custom,
      raw: req.custom,
    };
  });

  app.listen(opts.port, (err) => {
    if (err) {
      throw err
    }

    app.log.info('server listening on port %d', app.server.address().port)
  })
}

if (require.main === module) {
  start(minimist(process.argv.slice(2), {
    integer: 'port',
    boolean: 'verbose',
    alias: {
      'port': 'p',
      'verbose': 'v'
    },
    default: {
      port: 3000
    }
  }))
}
```

### Fastify version

3.25.1

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The data loaded from AsyncLocalStorage is  undefined
15:07:47 ✨ request completed 2ms
15:07:50 ✨ incoming request GET xxx /test
post undefined

### Steps to Reproduce

https://github.com/mittche/fastify

npm i
npm run start

curl -XPOST -d '{}' -H "Content-Type: application/json" localhost:3000/test

### Expected Behavior
With express work well
```

const express = require('express')
var { AsyncLocalStorage } = require('async_hooks');

const storage = new AsyncLocalStorage();
const state = { counter: 0 };

const app = express()
const port = 3000

app.use((req, res, next) => {
  const id = state.counter++;
  console.log('In Middleware with id ' + id);
  storage.run({ id }, next);

  req.custom = "something else";
  next();
});

app.get('/test', (req, res) => {
  const id = storage.getStore()?.id;
  console.log('post', id);
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})

```

In Middleware with id 0
post 0
In Middleware with id 1
post 1
In Middleware with id 2
post 2
In Middleware with id 3
post 3
In Middleware with id 4
post 4
In Middleware with id 5
post 5
In Middleware with id 6
post 6
In Middleware with id 7
post 7
In Middleware with id 8
post 8
In Middleware with id 9
post 9
In Middleware with id 10
post 10
In Middleware with id 11
post 11
In Middleware with id 12
post 12
In Middleware with id 13
post 13
In Middleware with id 14
post 14
In Middleware with id 15
post 15

_No response_

**Comment by zekth** [comment]
There is a mistake in your code
```js
  app.use((req, res, next) => {
    const id = state.counter++;
    console.log('In Middleware with id ' + id);
    storage.run({ id }, next); // pass the callback

    req.custom = "something else";
    next(); // calls the callback
  });
```
In this case you're calling the next callback twice in 2 different ways.

**Comment by mittche** [comment]
ok will try

**Comment by luisorbaiceta** [comment]
fastify/middie#124

**Comment by mittche** [comment]
but with post not work

**Comment by kibertoad** [comment]
see https://github.com/fastify/fastify-request-context/pull/12 and issue linked in it.
can you try using fastify-request-context and see if it helps?

**Comment by mittche** [comment]
seems to work storage.enterWith({ id });
