### ISSUE TITLE
Async context is broken for POST requests when its created inside 'onRequest' hook

### ISSUE THREAD

**Issue by B4nan** [fastify/fastify#3570]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.1

### Plugin version

5.3.0

### Node.js version

16.10

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.0

### Description

When `next` handler is executed inside `AsyncLocalStorage`, the context gets lost for requests with payload. Post request without a payload will work fine.

Originally discovered in nestjs project, connected issue: https://github.com/nestjs/nest/issues/8837

Note that I had similar issues with express middlewares too and they were caused by the middleware being registered too early, before the body parser. Not sure how that works in fastify, but I would say here the issue will be very similar.

### Steps to Reproduce

storage.ts
```ts
import { AsyncLocalStorage } from 'async_hooks';

export const storage = new AsyncLocalStorage<any>();
export const state = { counter: 0 };
```

main.ts
```
  const fastify = Fastify({ logger: true });
  await fastify.register(middie);
  fastify.use((req: any, res: any, next: any) => {
    const id = state.counter++;
    console.log('In Middleware with id ' + id);
    storage.run({ id }, next);
  });

  fastify.get('/', function (request, reply) {
    const id = storage.getStore()?.id;
    console.log('get', id);
    reply.send({ id });
  });

  fastify.post('/', function (request, reply) {
    const id = storage.getStore()?.id;
    console.log('post', id);
    reply.send({ id });
  });
```

minimal repro here:

https://github.com/B4nan/fastify-middie-als

```
yarn
yarn start
# get request works fine, will print the context ID as a response
curl localhost:3000
# fails to get the ID from ALS if there is actual payload
curl -d '{}' -H 'Content-Type: application/json' localhost:3000
# without the payload it will work fine (even for post request)
curl -X POST localhost:3000
```

### Expected Behavior

The async context should not be broken, requests with payload should work the same as those without it in this manner.

**Comment by mcollina** [comment]
Here is the Node core issue about this: https://github.com/nodejs/node/issues/41285.

**Comment by B4nan** [comment]
Thanks a lot for additional debugging and escalating this!

**Comment by luisorbaiceta** [comment]
> > Could you please try to substitute your first fastify.use with this, and see if it solves the problem?
> 
> `enterWith` helps, but it is not actual solution. it will keep the async context open. imagine there is a handler where we want the context, and another one where we do not want the context. with `enterWith`, we would keep the async context created by first handler also for the other one. we need boundaries for this.

If you need to handle the lifetime of your async context you can extend the [`AsyncResource`](https://nodejs.org/api/async_context.html#class-asyncresource) class and `bind` your storage functions to that context. Hope this helps

**Comment by MohammedElattar** [comment]
> I've reproduced it with Fastify (standalone):
> 
> use strict'
> 
> const { AsyncLocalStorage } = require('async_hooks')
> const Fastify = require('.')
> 
> const storage = new AsyncLocalStorage()
> const app = Fastify({ logger: false })
> global.__storage = storage
> 
> let counter = 0
> app.addHook('onRequest', (req, reply, next) => {
>   const id = counter++;
>   console.log('In Middleware with id ' + id);
>   // storage.enterWith({ id })
>   // next()
>   storage.run({ id }, next);
> });
> 
> app.get('/', function (request, reply) {
>   const id = storage.getStore()?.id;
>   console.log('get', id);
>   reply.send({ id });
> });
> 
> app.post('/', function (request, reply) {
>   const id = storage.getStore()?.id;
>   console.log('post', id);
>   reply.send({ id });
> });
> 
> app.listen(3000, function (err, address) {
>   if (err) {
>     app.log.error(err)
>     process.exit(1)
>   }
> })
> and with Node.js core:
> 
> 'use strict'
> 
> const { AsyncLocalStorage } = require('async_hooks')
> const { createServer } = require('http')
> 
> const storage = new AsyncLocalStorage()
> 
> let counter = 0
> createServer((req, res) => {
>   const id = counter++;
>   console.log('In Middleware with id ' + id);
>   storage.run({ id }, function () {
>     req.resume()
>     req.on('end', onEnd(res))
>   });
> }).listen(3000)
> 
> function onEnd (res) {
>   return () => {
>     const store = storage.getStore()
>     console.log('store is', store)
>     res.end(JSON.stringify(store))
>   }
> }
> The next step is for me to identify if it's something we need to fix in Node.js core or support in Fastify.
> 
> Thanks for the repro, this has been helpful.
> 
> I would note that using `enterWith()` is the **only solution** to this problem in a short timeframe. That should be good for your use case without any known side effect.

I tried to apply this solution but there is no overload for `next` in the callback of the onRequest
