### ISSUE TITLE
Thank you and Happy new year!

### ISSUE THREAD

**Issue by mariusa** [fastify/fastify#3580]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Dear Matteo & team, 

Just wanted to say Thank you for a professional set of packages, critical for node web app development! And thanks for the awesome docs and support provided every time :)

Happy new year!

**Comment by mcollina** [comment]
Thank you @mariusa!
