### ISSUE TITLE
Clarification on async/await and `Reply.send()`

### ISSUE THREAD

**Issue by michael-melodyarc** [fastify/fastify#3581]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I've looked at a handful of issues, and the docs also make some mention, but trying to do a sanity check on if this is correct.

I have a simple async function that is a decorator on reply (it's basically a super simplified `reply.sendFile()` function, but ultimately beside the point):

```js
app.decorateReply('sendFile', async function (file) {
  this.type(mime.getType(file)).send(await readFile(path.join(dir, file)));
});
```

I then have a simple route that is calling it:

```js
app.get('/cool-page', (req, res) => res.sendFile('cool-page.html'));
```

Is this okay, or should I not be using an implicit return on the arrow function in the route?  The above code works without errors, but it was a little weird with the implicit return and the promise from the async function.

Or perhaps something like:

```js
app.get('/cool-page', async (req, res) => {
  await res.sendFile('cool-page.html');
});
```

What is the proper / best practice way to do this while also trying to be as concise as possible?

Thanks,

**Comment by sergiz** [comment]
Both examples are functionally the same.

The reply object (that will be returned from res.sendFile) has "then" method and will be handled the same as your async function which returns a Promise.

**Comment by michael-melodyarc** [comment]
I was getting tripped up a bit on part of the docs, but I think I was misinterpreting it:

> If the handler's promise is resolved with undefined, it will be ignored causing the request to hang and an error log to be emitted.

And:

> If you want to use async/await or promises but return a value with reply.send: Do not return any value.

I think I was taking that too literally, because I'm technically returning a value (e.g. a promise that resolves to undefined) from the arrow function with the implicit return.

Anyhows, appreciate the confirmation; feel free to close this out.  Thanks.

**Comment by sergiz** [comment]
I explained it wrong. Your both examples would have the same result since you are returning a promise that resolves to undefined. The problem is your decorator that would introduce a race condition. You need to await for reply.send before letting the promise to resolve, so you either return that line in your decorator or await for it. It's hard to notice this in v3, but will be much easier in v4.

**Comment by michael-melodyarc** [comment]
Okay, so putting that together, would the following be correct?

```js
// decorator - return
app.decorateReply('sendFile', async function (file) {
  return this.type(mime.getType(file)).send(await readFile(path.join(dir, file)));
});

// -- OR --

// decorator - await
app.decorateReply('sendFile', async function (file) {
  await this.type(mime.getType(file)).send(await readFile(path.join(dir, file)));
});

// -------------------------------------------------

// route - implicit return
app.get('/cool-page', (req, res) => res.sendFile('cool-page.html'));

// -- OR --

// route - await res.sendFile
app.get('/cool-page', async (req, res) => {
  await res.sendFile('cool-page.html');
});

// -- OR --

// route - await res directly
app.get('/cool-page', async (req, res) => {
  res.sendFile('cool-page.html');
  await res;
});
```

```js
// this wouldn't work
// route - no return or await
app.get('/cool-page', (req, res) => {
  res.sendFile('cool-page.html');
});
```

I really appreciate helping me wrap my head around this.  I'd like to think I have a good mental model of Fastify, but this one use case through me for a bit of a loop, haha.

**Comment by sergiz** [comment]
These two examples would work as well:

```js
// route - return res.sendFile
app.get('/cool-page', async (req, res) => {
  return res.sendFile('cool-page.html');
});

// route - return res directly
app.get('/cool-page', async (req, res) => {
  res.sendFile('cool-page.html');
  return res;
});
```

And contrary to your belief, this would work as well 😅
> ```js
> // this wouldn't work
> // route - no return or await
> app.get('/cool-page', (req, res) => {
>   res.sendFile('cool-page.html');
> });
> ```

`res.send` works as a `callback` when used in non-promise context.

**Comment by michael-melodyarc** [comment]
The first two make sense; the last one would definitely still get me :P Anyways, I think that about answers my questions, so feel free to close this out.  Thanks again :)
