### ISSUE TITLE
redact prop is missing from FastifyLoggerOptions and Logger interfaces

### ISSUE THREAD

**Issue by kobik** [fastify/fastify#3600]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.0.1

### Description

Hi,

When I try to set `redact` prop in the logger options according to the example in the [docs](https://www.fastify.io/docs/latest/Reference/Logging/)
```ts
const server = fastify({
  logger: {
    redact: ['req.headers.authorization'],
  }
})
```

I'm getting this error
```
No overload matches this call.
  The last overload gave the following error.
    Type '{ redact: string[]; }' is not assignable to type 'boolean | FastifyLoggerInstance | FastifyLoggerOptions<Server, FastifyRequest<RouteGenericInterface, Server, IncomingMessage, unknown>, FastifyReply<...>> | undefined'.
      Object literal may only specify known properties, and 'redact' does not exist in type 'FastifyLoggerInstance | FastifyLoggerOptions<Server, FastifyRequest<RouteGenericInterface, Server, IncomingMessage, unknown>, FastifyReply<...>>'.ts(2769)
```

Currently, I'm working around it by augmenting `FastifyLoggerOptions` like thaat
```ts
declare module 'fastify' {
  interface FastifyLoggerOptions {
    redact: string[],
  }
}

const server = fastify({
  logger: {
    redact: ['headers.authorization'],
  }
})
```

### Steps to Reproduce

Use the following snippet in Typescript
```ts
const server = fastify({
  logger: {
    redact: ['req.headers.authorization']
  }
})
```

**Comment by climba03003** [comment]
Duplicated #3329

Please see comment in https://github.com/fastify/fastify/pull/3330#issuecomment-945414326
It is intended to not include the complete type of `pino`.
