### ISSUE TITLE
Use fast-uri with Ajv to speed up cold start

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3607]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

A long time ago we identified the dependency uri-js as the main performance bottleneck for cold start (see https://github.com/garycourt/uri-js/issues/40). Unfortunately the maintainers did not want to work in improving the performance. A few months back @zekth forked uri-js into https://github.com/fastify/fast-uri fixing that performance issues and others.

We should use this for the fastify v4 launch. To do so we need:
- https://github.com/ajv-validator/ajv/pull/1862 landed.

**Comment by zekth** [comment]
landed in : https://github.com/fastify/fastify/pull/3687
