### ISSUE TITLE
Issue with Schemas when using Typebox Nullable

### ISSUE THREAD

**Issue by cooliopas** [fastify/fastify#3614]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi!

I have this Typebox type:
```
const User = Type.Object({
    id: Type.Number(),
    name: Type.String(),
    created_at: Type.String({ format: 'date-time' }),
    updated_at: Type.String({ format: 'date-time' }),
})
```
that results in this Schema:
```
{
    "type": "object",
    "properties": {
        "id": {
            "type": "number"
        },
        "name": {
            "type": "string"
        },
        "created_at": {
            "format": "date-time",
            "type": "string"
        },
        "updated_at": {
            "format": "date-time",
            "type": "string"
        }
    },
    "required": [
        "id",
        "name",
        "created_at",
        "updated_at"
    ]
}
```

It works fine to validate this data ('String' is because both date properties are strings, as required):
```
const userString = {
    id: 1,
    name: 'Pablo',
    created_at: '2022-01-11T19:11:47.000Z',
    updated_at: '2022-01-11T19:11:47.000Z',
};
````

Running
```
const validString = ajv.validate(User, userString)
// returns true
```
Works as expected.

When using this data ('Object' is because one of the date properties is a date object instead of a string):
```
const userObject = {
    id: 1,
    name: 'Pablo',
    created_at: (new Date()),
    updated_at: '2022-01-11T19:11:47.000Z',
}
```

Running
```
const validObject = ajv.validate(User, userObject)
// returns false
```
Still works as expected. 'created_at' should be a string, NOT an object.

When using Fastify, it behaves different.
Using the same Typebox type and the same data:
```
server.get('/string', { schema: { response: { 200: User, }, } }, async (request, reply) => {
    return userString
})
// returns status 200
```
This works as expected.

When using this (remember userObject has one of the date properties as a date object):
```
server.get('/object', { schema: { response: { 200: User, }, } }, async (request, reply) => {
    return userObject
})
// returns status 200
```
It should fail, but it doesn't.

So, lets assume Fastify is doing something internally to convert that date object to string, and that's why it gets validated.
But then the same situation started failing when using a Nullable type.

I have this extra Typebox types:
```
const Nullable = <T extends TSchema>(type: T) => Type.Union([type, Type.Null()])

const NullableUser = Nullable(User);

const NestedUser = Type.Object({
    user: User
})

const NestedNullableUser = Type.Object({
    user: Nullable(User)
})
```

When testing with AJV, it fails every time I use object instead of string, as expected.

When using those types on Fastify, it only fails for **NestedNullableUser**:
```
server.get('/nested_nullable_object', { schema: { response: { 200: NestedNullableUser, }, } }, async (request, reply) => {
    return {
        user: userObject
    }
})
// returns:
// {
//   "user": null
// }
```
It stills returns status 200, but **user** is **null**.

Why **user** is **null** only for **NestedNullableUser** but its ok for **NestedUser**, even when using object instead of string?

I have a reproduction repo at https://github.com/cooliopas/typebox_nullable_issue with a full set of tests.
```
yarn fastify_test // runs server and display test endpoints
yarn ajv_test // runs AJV validations
```

Thanks in advance!

**Comment by climba03003** [comment]
I think you have something wrong in your assumption.
`request` is using `ajv` for `validation` and `response` is using `fast-json-stringify` for `serialization`.

**Comment by climba03003** [comment]
I think it is the expected behavior. When it is non-nested schema, we try to serialize every property inside.
But when it comes to `anyOf`, we check if it match the `schema` before trying to serialize every property inside.

In your case, the `Date` object one will never fulfill either of the schema on `ajv.validate`. So, it will be fallback to `null`.
```js
// debug the issue
// 1.  it will loop through the seperate anyOf schema with ajv.validate
//     we dry run the step on hand
const Ajv = require("ajv");
const AjvFormats = require("ajv-formats");
const ajv = new Ajv.default();
AjvFormats(ajv);
ajv.addKeyword("kind");
// 1.1. we check if it match the schema before
console.log(
  ajv.validate(
    {
      type: "object",
      properties: {
        id: { type: "number" },
        name: { type: "string" },
        created_at: { format: "date-time", type: "string" },
        updated_at: { format: "date-time", type: "string" },
      },
      required: ["id", "name", "created_at", "updated_at"],
    },
    obj2
  )
);
// 1.2. we check if it match the schema before
console.log(ajv.validate({ type: "null" }, obj2));
// 1.3. non of the above match, we fallback to null
const result = { user: null }
```

**Comment by cooliopas** [comment]
Thanks @climba03003 for clarification on how it works and for taking the time to confirm its working as expected.

Best regards.
