### ISSUE TITLE
Support constraints when registering plugins

### ISSUE THREAD

**Issue by ghost** [fastify/fastify#3615]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

When registering a plugin, you can currently pass a prefix that apply to all routes in the plugin.  It'd be awesome to have that same functionality, but with a version or host constraint instead of a path prefix.  I don't believe there is a simple way to do this at the moment without manually passing through options to every route, but I'd love to be wrong!

### Motivation

We have a few subdomain specific APIs within our app, so rather than manually passing through options to the plugin and then passing them into each route within the plugin, it'd be really nice to simply set a constraint when registering the plugin itself and have all the routes within the plugin inherit it.

### Example

```js
fastify.register(require('./routes/v1/users'), { prefix: '/v1' }) // currently supported
fastify.register(require('./routes/v1/users'), { constraints: { host: 'auth.fastify.io' } }) // not supported
```

```js
fastify.register(require('./routes/apple'), { constraints: { host: 'apple.fastify.io' } })
fastify.register(require('./routes/berry'), { constraints: { host: 'berry.fastify.io' } })
```

```
GET https://apple.fastify.io/
  200 => I LOVE APPLES

GET https://berry.fastify.io/
  200 => I LOVE BERRIES
```

**Comment by mcollina** [comment]
This would be awesome to add. Would you like to send a PR?

**Comment by michael-melodyarc** [comment]
I'm slammed this month, but I can definitely take a stab hopefully sometime early February.  Do you have any pointers or guidance on where or how it should be implemented?  Would it work similar to how the prefixes work, or do you think it would be different?  Or would we want to implement it in a more generic way so you could actually pass any route options during register versus specific ones (I don't know if that would actually make sense or even work :P)?

**Comment by Eomm** [comment]
This is already doable within a plugin that listens for the `onRoute` hook and add the `constraints` property when necessary.

```
fastify.register(function plugin (instance, opts, next) {
  instance.addHook('onRoute', function hook (routeOptions) {
    routeOptions.constraints = { host: 'apple.fastify.io' }
    instance.register(require('./routes/apple'))
  })
  next()
})

fastify.register(function plugin (instance, opts, next) {
  instance.addHook('onRoute', function hook (routeOptions) {
    routeOptions.constraints = { host: 'berry.fastify.io' }
    instance.register(require('./routes/berry'))
  })
  next()
})
```

I have always been afraid to add new `fastify's private field names` to the plugin's options object to avoid collisions.

https://www.fastify.io/docs/latest/Reference/Plugins/#plugin-options

**Comment by michael-melodyarc** [comment]
@Eomm Very interesting! I've actually never used the `onRoute` hook before, so never even occurred to me that was possible.  Would this be seen as the "official" or recommended way of doing it, or is this still slightly a hack?  I think it'd still be a cool feature to have for simplicity sake, but this is also still lightweight / easy to understand, so I could also see leaving this in userland and not adding to core.  Thanks :)

**Comment by mcollina** [comment]
Good spot! All of this could a also be automated with a combo of `onRegister` and `onRoute`. It looks like it is a good plugin to be developed.

**Comment by Eomm** [comment]
> is this still slightly a hack?

Not at all: it is the infinite possibilities fastify offers

**Comment by cesarvspr** [comment]
Are we sure that we need a new plugin for this? So this means new repo right? 
How can we move forward with this? I am willing to help 
@climba03003

**Comment by climba03003** [comment]
> Are we sure that we need a new plugin for this?

Yes

> So this means new repo right?

Yes, most likely this would be a community plugin.

> How can we move forward with this?

Create the plugin, submit PR for adding it as community plugin.

**Comment by Ceres6** [comment]
Hi!

I'm currently working on  creating the mentioned plugin and will submit a PR to add it to community plugins as soon as it's working

**Comment by simoneb** [comment]
@Eomm @climba03003 you may want to take a look at the implementation we're putting together here https://github.com/nearform/fastify-constraints/pull/1

**Comment by Ceres6** [comment]
Hi! We have released v1.0.0 of nearform/fastify-constraints. Maybe you can check it to decide if it resolves this issue.

**Comment by climba03003** [comment]
@Ceres6 
Next step should be send a PR here and update https://github.com/fastify/fastify/blob/main/docs/Guides/Ecosystem.md

**Comment by Ceres6** [comment]
@climba03003 
Done!
