### ISSUE TITLE
CI: run lint once

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3621]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Refactor the package.json scripts and the CI to run the linter only once.
(now it runs for every node version and OS)

This will:

- speed up a bit the pipeline
- improve the readability

### Motivation

This output is confusing:

![image](https://user-images.githubusercontent.com/11404065/149630306-8b7bbbda-0b3f-4623-8bc2-c1d1115c2813.png)

**Comment by jsumners** [comment]
💯
