### ISSUE TITLE
Register Type does not support extended servers or request types

### ISSUE THREAD

**Issue by angus-88** [fastify/fastify#3633]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Node.js version

14.17.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

I have a Custom Request type that extends http.IncomingMessage

```
interface CustomRequest extends http.IncomingMessage {
  userId: string;
}
```
A server with the correct type generic

```
const server = fastify<http.Server, CustomRequest>();
```

A request handler that users the request property
```
const whoAmI = (
  request: FastifyRequest<RouteGenericInterface, http.Server, CustomRequest>,
  reply: FastifyReply,
): void => {
  reply.send(request.raw.userId);
};
```

I then have a plugin that adds a the handler to a route

```
const users = (fastify: FastifyInstance<https.Server, CustomRequest>): void => {
  fastify.get('/whoami', whoAmI);
};
```

but when i register the plugin i get the following error

```
server.register(users);

Type '(fastify: FastifyInstance<Server, CustomRequest>) => void' is not assignable to type 'FastifyPluginAsync<FastifyPluginOptions, Server>'
```

It's worth noting that registering the route directly works as expected.
```
server.get('/whoami', whoAmI);
```

I'm not sure if I am doing anything wrong or if it's just the Fastify.Register type is incomplete
instance.d.ts: `register: FastifyRegister<FastifyInstance<RawServer, RawRequest, RawReply, Logger> & PromiseLike<undefined>>;`
register.d.ts: `export interface FastifyRegister<T = void>`

### Steps to Reproduce

```
import http from 'http';

import fastify, {FastifyInstance, FastifyRequest, FastifyReply} from 'fastify';
import { RouteGenericInterface } from 'fastify/types/route';

interface CustomRequest extends http.IncomingMessage {
  userId: string;
}

const server = fastify<http.Server, CustomRequest>({});

const whoAmI = (
  request: FastifyRequest<RouteGenericInterface, http.Server, CustomRequest>,
  reply: FastifyReply,
): void => {
  reply.send(request.raw.userId);
};

const users = (fastify: FastifyInstance<http.Server, CustomRequest>): void => {
  fastify.get('/whoami', whoAmI);
};


server.get('/whoami', whoAmI);

server.register(users);
```

### Expected Behavior

No typescript error, generics are properly handled and expected

**Comment by RafaelGSS** [comment]
The request body should be defined in the `RouteGenericInterface`.

```ts
request: FastifyRequest<{ Body: YourInterface }>
```

See https://www.fastify.io/docs/latest/Reference/TypeScript/#using-generics

**Comment by angus-88** [comment]
Thanks for the reply Rafael, I was trying to extend the root Request type, rather than the headers or body of the request? 

Is this possible or discouraged?

**Comment by RafaelGSS** [comment]
I'd say it's discouraged. What is your use case? I mean, the type system was designed to solve it easier by just passing the expected data in `Body`/`Params`/`Query.

**Comment by angus-88** [comment]
That's fair enough, it's to hold complex objects with requesting user information. I can add it to the request `Headers`, I was just trying to keep the server added information separate from the headers from the original request.

**Comment by mcollina** [comment]
You should _not_ customize the raw node core objects. That's one of the main performance issues in other frameworks.
