### ISSUE TITLE
Add TypeProvider generic to FastifyPluginAsync 

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#3636]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

@RafaelGSS This seems to be working as expected

```typescript
// npm install "https://github.com/fastify/fastify.git#next" --save
// npm install "https://github.com/fastify/fastify-type-provider-typebox.git" --save
// npm install @sinclair/typebox --save

import Fastify, { FastifyPluginAsync }  from 'fastify'
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import { Type }                from '@sinclair/typebox'


const aPlugin: FastifyPluginAsync = async (fastify) => {       // FastifyTypeProvider
    fastify.withTypeProvider<TypeBoxTypeProvider>().get('/', { // remap to TypeBoxTypeProvider
        schema: {
            body: Type.Object({
                x: Type.String(),
                y: Type.Number(),
                z: Type.Boolean()
            })
        }
    }, (req) => {
        const { x, y, z } = req.body // Now works
    });
};


const fastify = Fastify()
fastify.register(aPlugin)
```
I think there was some plans to make it a bit easier to supply the provider as a generic argument across `FastifyInstance` and `FastifyPluginAsync` types, which would permit the following.
```typescript
const aPlugin: FastifyPluginAsync<{TypeProvider: TypeBoxTypeProvider }> = async (fastify) => { ... }
```
But I believe this was pending quite a few refactorings.

_Originally posted by @sinclairzx81 in https://github.com/fastify/fastify-type-provider-typebox/issues/2#issuecomment-1015852821_

**Comment by sinclairzx81** [comment]
@RafaelGSS Just had a bit of a deeper look at this. From the original issue https://github.com/fastify/fastify-type-provider-typebox/issues/2#issue-1105737990, the user is reporting a problem registering plugin where both instance and plugin are mapped to use the same provider. Original code as follows.

```typescript
type TypeBoxPluginAsync =
FastifyPluginAsync<Record<never, never>, RawServerDefault, TypeBoxTypeProvider>;

const server = fastify({
  ajv: { plugins: [ajvTypeBoxPlugin] },
}).withTypeProvider<TypeBoxTypeProvider>(); // we would expect this to be fine.

const aPlugin: TypeBoxPluginAsync = async (server) => {};


server.register(aPlugin); // type error: FastifyTypeProviderDefault !== TypeBoxTypeProvider
```
I would expect the above to work as both `instance` and `plugin` are mapped to the same provider, however looking at the `register()` definitions [here](https://github.com/fastify/fastify/blob/next/types/register.d.ts#L11-L31) I see.

```typescript
export type FastifyRegisterOptions<Options> = (RegisterOptions & Options) | ((instance: FastifyInstance) => RegisterOptions & Options)
                                                                                        ^ Not generic: Defaults to FastifyTypeProviderDefault
```
To resolve this; there would be a need to propagate the current `FastifyInstance` (or its current arguments) into the `FastifyRegisterOptions<...>` definition above such that the FastifyInstance that is resolved is the current (not the default). I think that would yield the expected behavior (as the user has already mapped both instance and plugin).

It may be good to treat the above change as a separate issue, as I'd imagine generic argument refactorings wouldn't just be limited to plugins; rather part of a larger body of work.

Hope this helps!
S

**Comment by rubenferreira97** [comment]
The ability to supply only some generics would allow a lot of customizability and "manual correction" where TS inference does not work as expected.

@sinclairzx81 @RafaelGSS I have found some difficulties coming with a generic preValidation for a set of routes that might be related with this issue. This problem is not plugin specific and the variables type are assumed as never (which I think is normal since I can't infer the schema). Is there any known approach that could solve this?

```TS
import Fastify, {
  ContextConfigDefault,
  FastifySchema,
  preValidationAsyncHookHandler,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerDefault,
} from 'fastify';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { Type } from '@sinclair/typebox';
import { RouteGenericInterface } from 'fastify/types/route';

type TypeBoxPreValidation = preValidationAsyncHookHandler<
RawServerDefault,
RawRequestDefaultExpression<RawServerDefault>,
RawReplyDefaultExpression<RawServerDefault>,
RouteGenericInterface,
ContextConfigDefault,
FastifySchema,
TypeBoxTypeProvider
>;

declare module 'fastify' {
  interface FastifyInstance {
    authenticate: TypeBoxPreValidation
  }
}

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>();
// some fastify.decorate('authenticate', ...);

fastify.get('/', {
  schema: {
    params: Type.Object({ id: Type.String() }),
    body: Type.Object({
      x: Type.String(),
      y: Type.Number(),
      z: Type.Boolean(),
    }),
  },
  preValidation: fastify.authenticate,
}, (req) => {
  // The `x`, `y`, `z` types are never.
  const { x, y, z } = req.body;
});
```

This works:

```TS
import Fastify from 'fastify';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { Type } from '@sinclair/typebox';

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>();

fastify.get('/', {
  schema: {
    params: Type.Object({ id: Type.String() }),
    body: Type.Object({
      x: Type.String(),
      y: Type.Number(),
      z: Type.Boolean(),
    }),
  },
  preValidation: (req, res) => {
     // However, this not allow code reuse.
  },
}, (req) => {
  // The `x`, `y`, `z` types are infered.
  const { x, y, z } = req.body;
});
```

**Comment by sinclairzx81** [comment]
@rubenferreira97 Try the following

```typescript
import Fastify, {
    ContextConfigDefault,
    FastifySchema,
    preValidationAsyncHookHandler,
    RawReplyDefaultExpression,
    RawRequestDefaultExpression,
    RawServerDefault,
    FastifyTypeProvider
} from 'fastify';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { Type } from '@sinclair/typebox';
import { RouteGenericInterface } from 'fastify/types/route';

type TypeProviderPreValidationAsyncHookHandler<
    TypeProvider extends FastifyTypeProvider, 
    Schema extends FastifySchema
> = preValidationAsyncHookHandler<
    RawServerDefault,
    RawRequestDefaultExpression<RawServerDefault>,
    RawReplyDefaultExpression<RawServerDefault>,
    RouteGenericInterface,
    ContextConfigDefault,
    Schema,        // Generic
    TypeProvider   // Generic
>;

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>();

const schema = {
    params: Type.Object({ id: Type.String() }),
    body: Type.Object({
        x: Type.String(),
        y: Type.Number(),
        z: Type.Boolean(),
    }),
}

declare module 'fastify' {
    interface FastifyInstance {
        authenticate: TypeProviderPreValidationAsyncHookHandler<TypeBoxTypeProvider, typeof schema>
    }
}

const preValidation: TypeProviderPreValidationAsyncHookHandler<TypeBoxTypeProvider, typeof schema> = async (req, res) => {
    const { x, y, z } = req.body // ok
}

fastify.get('/', {
    schema,
    preValidation
}, (req) => {
    const { x, y, z } = req.body;
});
```
The issue is due to the hooks needing the same type information specified on the route. So, you can pull the schema out from the route so it can be shared with the handler. You can use the `typeof schema` to infer the correct type context for the hook. The only changes here are to your `TypeBoxPreValidation` which I've updated to be generic enough to support multiple providers and schemas.

Once the plugins and associated types are refactored to support generic object passing, defining external hooks with providers should be a bit easier.

```typescript
const preValidation: preValidationAsyncHookHandler<{
    TypeProvider: TypeBoxTypeProvider, 
    Schema: typeof schema
}> = async (req, res) => {
    const { x, y, z } = req.body // ok
}
```
Hope that helps
S

**Comment by RafaelGSS** [comment]
@rubenferreira97 Looks like a different issue even correlated. Could you create a new issue for the types hooks?

**Comment by sinclairzx81** [comment]
@rubenferreira97 That's ok. And yeah you're quite right that if you do need to share the same hook across different routes, constraining to one set of schemas will be a problem. 

Possibly the easiest approach here is to just change `typeof schema` to `any` which will enable the hook to be added to varying routes. However, you would be trading type safety on the `body` (as the assumption here is that `body` data could be anything due to the hook being shared by multiple routes). So for example...

```typescript
import { TypeBoxTypeProvider }   from '@fastify/type-provider-typebox'
import { Type }                  from '@sinclair/typebox'
import { RouteGenericInterface } from 'fastify/types/route'
import Fastify, {
    ContextConfigDefault,
    FastifySchema,
    preValidationAsyncHookHandler,
    RawReplyDefaultExpression,
    RawRequestDefaultExpression,
    RawServerDefault,
    FastifyTypeProvider
} from 'fastify'

// -----------------------------------------------------------------------------
// Support Type
// -----------------------------------------------------------------------------

type TypeProviderPreValidationAsyncHookHandler<
  TypeProvider extends FastifyTypeProvider, 
    Schema extends FastifySchema
  > = preValidationAsyncHookHandler<
    RawServerDefault,
    RawRequestDefaultExpression<RawServerDefault>,
    RawReplyDefaultExpression<RawServerDefault>,
    RouteGenericInterface,
    ContextConfigDefault,
    Schema,        // Generic
    TypeProvider   // Generic
>;

// -----------------------------------------------------------------------------
// Shared Hook
// -----------------------------------------------------------------------------

const preValidation: TypeProviderPreValidationAsyncHookHandler<TypeBoxTypeProvider, any> = async (req, res) => {
    req.body // We can no longer rely on the request body being
             // the correct type as it's shared by multiple
             // routes. You will need to check and assert the body
             // type manually.
}

// -----------------------------------------------------------------------------
// Routes
// -----------------------------------------------------------------------------

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>();

fastify.get('/a', {
    preValidation,
    schema: {
        params: Type.Object({ id: Type.String() }),
        body: Type.Object({
            x: Type.Number(),
            y: Type.Number(),
            z: Type.Number(),
        })
    }
}, (req) => {
    const { x, y, z } = req.body // correct
})


fastify.get('/b', {
    preValidation,
    schema: {
        params: Type.Object({ id: Type.String() }),
        body: Type.Object({
            a: Type.String(),
            b: Type.String(),
            c: Type.String(),
        })
    }
}, (req) => {
    const { a, b, c } = req.body // correct
}))
    }
}, (req) => {
    const { a, b, c } = req.body // correct
})
```
Also, for scenarios where you may have required data that is mandated by the hook (for example, a token, or other such data). It should be possible to provide more specific constraints for the hook. So for example.

```typescript
const RequiredHeaders = Type.Object({
    Foo: Type.String()
})

const preValidation: TypeProviderPreValidationAsyncHookHandler<TypeBoxTypeProvider, { 
    headers:      typeof RequiredHeaders, 
    body?:        any,
    params?:      any,
    querystring?: any
}> = async (req, res) => {
    const { Foo } = req.headers // ok
}
```
But this will require each route that uses the hook to provide a `RequiredHeader` also.
```typescript
fastify.get('/a', {
    preValidation,
    schema: {
        headers: RequiredHeaders, // Because this route uses the above hook, it is now
                                  // necessary to specify the dependent schema used
                                  // by the hook, otherwise its a type error.
        params: Type.Object({ id: Type.String() }),
        body: Type.Object({
            x: Type.Number(),
            y: Type.Number(),
            z: Type.Number(),
        })
    }
}, (req) => {

    const { Foo } = req.headers // ok

    const { x, y, z } = req.body    // ok
})
```
So a couple of ideas. I think the former approach (i.e. just using `any` on the hook + manual assertion) is probably easier approach as it means routes don't necessarily need to be explicit about defining schemas for the dependent hook. Also it may enable easier composition for multiple external hooks with varying schema requirements.

Hope this helps!

**Comment by rubenferreira97** [comment]
@sinclairzx81 Sorry for the late response. Your last approach is what I want to accomplish but unfortunately does not infer types (`Foo: any` even if is declared as a `Type.String`).

A quick question is this a `ResolveFastifyReplyType` bug or a limitation?

```TS
import { TypeBoxTypeProvider } from "@fastify/type-provider-typebox";
import { Type } from "@sinclair/typebox";
import { RouteGenericInterface } from "fastify/types/route";
import Fastify, {
  ContextConfigDefault,
  FastifySchema,
  preValidationAsyncHookHandler,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerDefault,
} from "fastify";

// -----------------------------------------------------------------------------
// Support Type
// -----------------------------------------------------------------------------

type TypeBoxPreValidationAsyncHookHandler<Schema> = preValidationAsyncHookHandler<
  RawServerDefault,
  RawRequestDefaultExpression<RawServerDefault>,
  RawReplyDefaultExpression<RawServerDefault>,
  RouteGenericInterface,
  ContextConfigDefault,
  Schema,
  TypeBoxTypeProvider
>;

// -----------------------------------------------------------------------------
// Shared Hook
// -----------------------------------------------------------------------------

const AuthError = Type.Object({
  msg: Type.String(),
});

const Id = Type.Object({
  id: Type.Integer(),
});

export interface FooSchema extends FastifySchema {
  params: typeof Id;
  response: {
    200: typeof Id;
    401: typeof AuthError;
    403: typeof AuthError;
  };
}

const preValidation =
  <Schema extends FooSchema>(barParams: number[]): TypeBoxPreValidationAsyncHookHandler<Schema> =>
  async (req, res) => {
    // TypeScript can infer that Schema extends FooSchema, or else id wouldn't be a number
    const { id } = req.params; // Type is infered. id: number ✔️
    const isLoggedIn = true;
    if(!isLoggedIn) {
      // ResolveFastifyReplyType can't resolve this type. Is it a limitation/bug? Any solution?
      res.status(401).send({ msg: 'Not logged in.' }); // ❌ ERROR casting as any `{ msg } as any` for now
    } 
  };

// -----------------------------------------------------------------------------
// Routes
// -----------------------------------------------------------------------------

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>();

fastify.get(
  "/a",
  {
    preValidation: preValidation([1, 2, 3]),
    schema: {
      params: Id,
      response: {
        200: Id,
        401: AuthError,
        403: AuthError,
      },
    },
  },
  (req, res) => {
    const { id } = req.params; // Type is infered. id: number ✔️
    // res.status(200).send(1); // Compile error e.g. if a raw number is sent ✔️
    res.status(200).send({ id }); // Send must be object Id or AuthError ✔️
  }
);

```

**Comment by sinclairzx81** [comment]
@rubenferreira97 Hi, Type Providers are written to infer types from JS values (as opposed to explicit generics). Internally the resolver infrastructure checks the value of the user supplied object schema then tries to determine the correct types from that. While it is technically possible to provide a `interface` or `type` (in your example `FooSchema`) the recommend approach is to pass a JS object value for `FooSchema` with the `typeof` operator. This helps ensure that the infrastructure sees the correct type information.

<details>
   <summary>Before</summary>

```typescript
export interface FooSchema extends FastifySchema {
  params: typeof Id;
  response: {
    200: typeof Id;
    401: typeof AuthError;
  };
}

const preValidation =
  <Schema extends FooSchema>(barParams: number[]): TypeBoxPreValidationAsyncHookHandler<Schema> =>
  async (req, res) => {
    // TypeScript can infer that Schema extends FooSchema, or else id wouldn't be a number
    const { id } = req.params; // Type is infered. id: number ✔️
    const isLoggedIn = true;
    if(!isLoggedIn) {
      // ResolveFastifyReplyType can't resolve this type. Is it a limitation/bug? Any solution?
      res.status(401).send({ msg: 'Not logged in.' }); // ❌ ERROR casting as any `{ msg } as any` for now
    } 
  };

```
</details>

```typescript
const FooSchema = {
    params: Id,
    response: {
        200: Id,
        401: AuthError
    }
}

const preValidation = (barParams: number[]): TypeBoxPreValidationAsyncHookHandler<typeof FooSchema> =>
    async (req, res) => {
        // TypeScript can infer that Schema extends FooSchema, or else id wouldn't be a number
        const { id } = req.params; // Type is infered. id: number ✔️
        const isLoggedIn = true;
        if (!isLoggedIn) {
            // ResolveFastifyReplyType can't resolve this type. Is it a limitation/bug? Any solution?
            res.status(401).send({ msg: 'Not logged in.' }); // ✔️ Inferred from Object Schema
        }
    };
```
Hope that helps
S

**Comment by Liam-Tait** [comment]
A workaround to this problem is to write a type which is compatible with `FastifyPluginAsync`

```ts
import type { TypeBoxTypeProvider } from "@fastify/type-provider-typebox"
import type {
  FastifyPluginAsync,
  FastifyPluginOptions,
  RawServerBase,
  RawServerDefault,
} from "fastify"

export type FastifyPluginAsyncTypebox<
  Options extends FastifyPluginOptions = Record<never, never>,
  Server extends RawServerBase = RawServerDefault,
> = FastifyPluginAsync<Options, Server, TypeBoxTypeProvider>

```

I think a good place for a type like this to be available from `@fastify/type-provider-typebox`

This would mean an async plugin could go from
```ts
async function plugin(fastify: FastifyInstance, _opts): void {
  const server = fastify.withTypeProvider<TypeBoxTypeProvider>()

  server.get('/', {
    schema: {
      body: Type.Object({
        x: Type.String(),
        y: Type.Number(),
        z: Type.Boolean()
      })
    }
  }, (req) => {
    const { x, y, z } = req.body
  });
}
```

to
```ts
const plugin: FastifyPluginAsyncTypebox = async function(fastify, _opts) {
  fastify.get('/', {
    schema: {
      body: Type.Object({
        x: Type.String(),
        y: Type.Number(),
        z: Type.Boolean()
      })
    }
  }, (req) => {
    const { x, y, z } = req.body
  });
}
```

**Comment by mcollina** [comment]
@Liam-Tait do you think you could open a PR to improve this?

**Comment by RafaelGSS** [comment]
Exporting this type in the `@fastify/type-provider-typebox` seems ok to me. What do you think @sinclairzx81 ?

**Comment by Liam-Tait** [comment]
@mcollina happy to help

**Comment by sinclairzx81** [comment]
@RafaelGSS Hi! I think exporting `FastifyPluginAsyncTypebox` on the `@fastify/type-provider-typebox` package would be ok.

I am wondering though if it would be beneficial to have Fastify export a few core utility types to make it easier to construct various types at various call sites. It's previously been mentioned that there are some considerations to having the current generic argument lists expressed as generic object parameters (similar to `Body`, `Params`, `QueryString` on routes), but given the amount of work involved in making that change (certainly a breaking change for v4), possibly this functionality could be expressed through utility types instead.

I've drafted a quick example of a few of these types to permit the following usages. These could potentially be added to `types/generic.d.ts` along with other generic utility mapping types.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/FASwtgDg9gTgLgAjgTwgUwQbwQFVWgISgA890AFGKANxABM0YEBfBAMyrAQCIABNgIYBnOCDbIA9CnQBaCFVoMYM6WgBGJbqEixE2MhlYcoXAOS8hIAHYBjADYCQMKfg3FT26PAQAxYaPF2TgRTQRExZA9gCQkEGXiExKTklNS09IzMxOjYgEEALgQAcTQrRhAbP3DxAEkrEQFbDAA+X38IuoamnLisvv6BweTgYGFkW3YAV1tRKCsECDtJgHNrXIAKMIDkQpKymAqq7c64Rps0AB59fEoaekZCgyJSG4V7pmZmgBoEAH0oCBwISFaYAaysUAA7lYAJRYYAIdjtcQAOmWaDg61MElMP0wCMRCCENgAFmgwAJCvjCYSNHQdrh8CiAPJqABWaBsmOpNMJxEeTIAynADlZlusYV8CbyEAyDCiAHKTMBqRgSqUyxEALwF6BRRCgdjQjQl0sJzBhZuYBOYP3WMDQAEc4QBeVo8xE2OYiLAIYg-ZA-LUsBAuhAOx0ounIG0wgDcwGtPSGKdTaeyMQQBF2pXKlWRyHIS1WVlyQnGNgQrSOESLKzW5dsyfTLdbmRGXvqiEW9as2eKuYO+eqheLDYrV0ZFDeSl1hBIBluikYLFaYbGE02BZ+-0BwIQYIh0Nd7oJWwiaIxWJxeLNxLJFKpZsR0bnLPZnO5z75b+FovFkrfoicpMkqKpqoBmoIDqU5oPqUCGsaVimjKFpWjadoRie8I0p2PrYP6spBiGYYRlGUD0rGiYdt6iDnoEYY1uIpr0cgKIOqsIhqj2Ja5JarHsWgnFwNxY59paIyZm20kyRkPQAKoQjASh0G0I4DvsFQILkMDLMqpRAjkPQ4GS7CGnYULWMsB6iHYIAoEg+BCAgpQCGoRoIHMGBwFACAUhAnnKYwaCqUxyAIOimmVgIun6VYhmZsYXDTLASghRFg5afIAKMA5MV6WABlCCiuCmWw5mWWKCBegwCAgM5UBsGwwWqcICACAgPQOs1DpNCiRlSbJQ3DTIIzgF4iCqAgABU7XOQYzlJSErFRINI3ra2PRhScZxoAAsgIEDoHQVwomdnzNhtV2piMaDEBNdXxYwgjnBpebbV2u23Og8AgGgQgXASABKAiQoKjDUCud0iVYdDzU5KIg2DEOMAQwgYGGC2I6D4MwJDMAACJoIIkx2HAGoIEjQNOpM-2INDpRw7BxVUzTdNEyTZMAKL3Q6QiWHMFxI7j+Nrsz2OQtTjq0yIHMCKTcA8-I-0C1YQs4yjMDfMDoPU4s4UM7D8PoCzutoPrcsK0rfOq+ryN44wYtY6zFvE-L3O8yrICC8Lmva4iAAyUDLOiTCG0zWNhUHIeMDtTShuLUfB6HcfnBTi4zlDxAwxHCNhRndxKAnkcFgXy6E27CsU6eiK+w7MAAPyFHX+MU6z0t003lNmx3Iht2b+tdy7diBgS0eh134+MOnryF4wXdl+8UpJndD1TXs70FqnlwEtvLnZ4zzkb0OH1dOc325X9Qj9-b+P7znznbwA2qYLeMKYAC69+H+Lb8wGjQgMANwQM-V+Gt66fwQHOU2t9Ubo2LgjP+lsyZOzzlvT6TRAY0j-hTREoD24yzgJA8Oxt-oSyloQ5BitPb829mrP+rRgH4J7oQyB0DyFs1lpXD2ytaE+3AaLXBICMHnBfsPSIX8SG-wHiPKh1svb8NgVrBATCRFoDETIiRUDpGS3NrI7h1DeG2wYUI0BU8YDEIPkbROBZzF71UWfdRphzFsJsSOOxajTFqJfovJQliH5uO2L4lcDjThNB8bPcuriS4jmCTAAkzQRiXWuik-oW0Cx1l4o2GwB0johVOudRJa1UklLksAVeuhHoiRgC9DAx9DgZLEmWCsF9fr-SwQgZkgI6HOSkTE7YmTrBdNmPUBO1MvTKQuGUVuCBpmOwpiLLOATnYCLgYAhBJsJaLIrpzcmBI4nf2sf0iIBzMZoNiZE94VDq44U6d070Xdhk9IWZrLu2yZ7Tjno3OcS4l7UXKfdSp69MrDgGU07JFwcCHKZvU0FtZwUtKoD9UQ-1UGbLCoM0sEL9kvyed6fxP9jniExXi0ZwCcC4vufUVx4zUpTLQDMuZWt04v22QSo5iDVn-3geS1lmtomcqUdcnFpg4nstzui0ulyi68tFdK9+X92H53lfExJQA)

```typescript
// ----------------------------------------------------------------------------------
// A: GenericFastifyInstance > FastifyInstance
// ----------------------------------------------------------------------------------

async function pluginA(fastify: GenericFastifyInstance<{ TypeProvider: TypeBoxTypeProvider }>, _opts: unknown) {
  fastify.get('/', {
    schema: {
      body: Type.Object({
        x: Type.String(),
        y: Type.Number(),
        z: Type.Boolean()
      })
    }
  }, (req) => {
    const { x, y, z } = req.body
  });
}

// ----------------------------------------------------------------------------------
// B: GenericFastifyPluginAsync > FastifyPluginAsync
// ----------------------------------------------------------------------------------

const pluginB: GenericFastifyPluginAsync<{ TypeProvider: TypeBoxTypeProvider }> = async (fastify, _opts: unknown) => {
  fastify.get('/', {
    schema: {
      body: Type.Object({
        x: Type.String(),
        y: Type.Number(),
        z: Type.Boolean()
      })
    }
  }, (req) => {
    const { x, y, z } = req.body
  })
}

const fastify = Fastify()
fastify.register(pluginA)
fastify.register(pluginB)
```
And would also allow `FastifyPluginAsyncTypebox` to be defined as in future.

```typescript
export type FastifyPluginAsyncTypebox = GenericFastifyPluginAsync<{ TypeProvider: TypeBoxTypeProvider }>
```
Open to thoughts

**Comment by RafaelGSS** [comment]
That's a good approach too. However, I'd go by:

* Export `FastifyPluginAsyncTypebox` on `@fastiy/type-provider-typebox`
* List all the efforts needed to refactor our types (this issue + https://github.com/fastify/fastify/issues/4081)
* In case it would need too much work, I'd go on your approach and then in the future a smooth change to the refactored version

**Comment by Eomm** [comment]
@fastify/typescript is this solved?

**Comment by mcollina** [comment]
yes
