### ISSUE TITLE
Drop querystring in favor of URLSearchParams

### ISSUE THREAD

**Issue by eladchen** [fastify/fastify#3645]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The docs says the default query string parser is the [querystring](https://nodejs.org/api/querystring.html) node module, which is deprecated.

I suggest using URLSearchParams instead.

### Example

TypeScript:

```ts
const server = fastify({
  querystringParser(query) {
    const parameters: { [k: string]: string | string[] } = Object.create(null);
  
    for (const [name, value] of new URLSearchParams(query).entries()) {
      const parameterValue = parameters[name];
  
      if (Array.isArray(parameterValue)) {
        parameterValue.push(value);
      }
      else if (typeof parameters[name] === "string") {
        parameters[name] = [parameterValue, value];
      }
      else {
        parameters[name] = value;
      }
    }
  
    return parameters;
  }
});
```

**Comment by mcollina** [comment]
Unfortunately URLSearchParams is significantly slower. We'll have to develop something ourselves but that's not high in priorities. querystring is so widespread that's not going away.
