### ISSUE TITLE
Fastify doesn't respect $ref default value

### ISSUE THREAD

**Issue by mikicho** [fastify/fastify#3649]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7 (19H2)

### Description

Fastify doesn't respect `$ref` default value.
Fastify does respect default value if specify directly in the schema.

### Steps to Reproduce

add schema:
```
  fastify.addSchema({
    $id: 'request/query/limit',
    type: 'number',
    default: 20,
  });
```

schema:
```
{
url: '/',
schema: {
    querystring: {
      type: 'object',
      properties: {
        limit: { $ref: 'request/query/limit' },
        offset: { type: 'number', default: 0 },
      },
    },
    ...
}
```

then in the handler:
```
async function handler(req) {
  console.log(req.query); // { offset: 0 } - limit is missing
}
```

### Expected Behavior

```
async function handler(req) {
  console.log(req.query); // { offset: 0, limit: 20 }
}
```

**Comment by zekth** [comment]
Are you using your own `ajv` instance ? like using `setValidatorCompiler` ?

**Comment by mikicho** [comment]
No, im using the default one:
`const fastify = Fastify()`

**Comment by mcollina** [comment]
does this work when using Ajv@6 directly?

**Comment by mikicho** [comment]
@mcollina I think not:
https://codesandbox.io/s/ajv-playground-forked-1qib7?file=/src/index.js

**Comment by mcollina** [comment]
can you check if works in the latest version? If not you might want to open an issue there.

**Comment by mikicho** [comment]
This is indeed [a limitation of Ajv](https://github.com/ajv-validator/ajv/issues/337#issuecomment-258769266).
Thanks.
