### ISSUE TITLE
uws.http experimentation?

### ISSUE THREAD

**Issue by alexhultman** [fastify/fastify#365]
If you don't mind goofing around a bit I would be interested in getting some results from testing uws.http with fastify.

So the idea is that you replace Node.js's http server with the one in uws. I don't have any time for this myself and it doesn't seem supported by fastify currently to swap the underlying http server used. If anyone wants to experiment that would be interesting. I know Express.js is way too bloated to see any gains in perf. but fastify could maybe. I already experimented with Aero.js (which is just as performant as fastify) but since it is not as well-known and has a strange license it is no use (Aero.js saw major gains in perf).

Btw, if you want to add more obscure http libraries to the benchmark you could look at Sails.js - I'm pretty sure Sails.js is the slowest web library available for Node.js. Could be fun.

**Comment by mcollina** [comment]
Yes it would be of interest! Adding support for this should be simple enough, sure you don't want to try?

**Comment by ansarizafar** [comment]
> So the idea is that you replace Node.js's http server with the one in uws.

Its a great idea. Any update?

**Comment by mcollina** [comment]
No, not really, would you like to send a PR?

**Comment by ansarizafar** [comment]
I have just started playing with Fastify and loving it. I am not familiar with Fastify internals. 

As the name suggests Fastify is all about performance and integration with uws can be a big performance boost. UWS integration should be a priority before 1.0 release.

**Comment by trivikr** [comment]
**FYI**: @valentinvichnal tested fastify with µWS in [VPS benchmarks](https://github.com/valentinvichnal/vps-compare-upcloud-linode-digitalocean#4---http)

**Comment by trivikr** [comment]
uws is supported in [fastify-ws](https://github.com/gj/fastify-ws) plugin

**Comment by mcollina** [comment]
Unfortunately not completely. uws also provides http equivalents, and it would be good to add support for them in here too.

**Comment by trivikr** [comment]
There was some discussion [on twitter](https://twitter.com/trivikram/status/960088957689065472) about this support.

**Comment by jimmiehansson** [comment]
Awesome initiativ this is something that would be an excellent addition!

**Comment by tinchoz49** [comment]
Hi everyone! quick question...the idea is to define a boolean option to support `uws.http` or would you prefer something like:

```javascript
const fastify = require('fastify')({
   createHttp() {
      return require('uws').http
   }
})
```

with this second approach, we can use in the future another `http` modules like `turbo-http`

**Comment by mcollina** [comment]
A better approach would be to expose our handler (what we pass to http createServer). However I fear it wouldn’t be that easy, as some methods would be different.

**Comment by tinchoz49** [comment]
Well, I was playing with `fastify` and `turbo-http` and I get this result:

![screenshot_2018-03-21_16-25-42](https://user-images.githubusercontent.com/819446/37732703-9c0895da-2d24-11e8-8010-0065007726a4.png)

Of course, benchmarks are always a relative number it depends on many things but what can I say? fastify with turbo-http can be really awesome to keep experimenting :smiley: 

I have to fork turbo-http to add support for `res.writeHead`, `res.hasHeader` and `req.headers`

**Comment by mcollina** [comment]
@tinchoz49 support turbo-http with fastify would be truly awesome. Send a PR to turbo-http on it.

**Comment by alexhultman** [comment]
@tinchoz49 for reference, could you run that same test but with uws.http. Should be a lot faster than turbo-http.

**Comment by mafintosh** [comment]
@tinchoz49 you wanna send a PR for those missing features btw? :)

**Comment by tinchoz49** [comment]
Hi @mafintosh, yes I will do it :+1:

**Comment by tinchoz49** [comment]
Hi @alexhultman, how are you? I tested fastify with uws and this is what I got:
```
❯ autocannon -c 100 -d 10 -p 100 --m GET 'http://localhost:3000'
Running 10s test @ http://localhost:3000
100 connections with 100 pipelining factor

Stat         Avg     Stdev   Max     
Latency (ms) 1.01    10.15   286.4   
Req/Sec      98412.8 7625.51 107600  
Bytes/Sec    8.59 MB 674 kB  9.36 MB 

984k requests in 10s, 85.6 MB read
```

I have to add some noop functions to ignore errors for missing features: `res.hasHeader()`, `server.removeListener()` and `server.address()`

**Comment by benoneal** [comment]
Any further progress on this? It looks very promising (and valuable, for my use case), and I'd prefer not to have to maintain my own fork of fastify.

**Comment by mcollina** [comment]
This is a project made by volunteers, and there is no official roadmap. We have repeatedly asked if somebody wanted to contribute a PR for this, but none has come yet. Would you like to?

You threaten to fork fastify if we do not implement this instead of sending a PR. The chances that the maintainers implement a feature under such a threat are zero. I would argue that sending a PR is a better way of engaging with this community.

**Comment by benoneal** [comment]
@mcollina Your first paragraph is reasonable, but I feel you've dramatically misinterpreted my comment. @tinchoz49 commented on the 22nd Mar that he was volunteering to submit a PR for this, then later that day (the post immediately above mine) posted preliminary performance stats on his work so far into doing that. Then nothing for 7 weeks. My comment, being the very next comment, was merely asking if there was any further progress on the work that had already been started. 

I have no idea how you'd construe my comment on forking as a threat, given that forking... well... _isn't a threat_, but I was simply stating that I'd rather not do the work myself (especially given someone else had already started it).

**Comment by delvedor** [comment]
> and I'd prefer not to have to maintain my own fork of Fastify.

Probably you didn't meant that, but it sound like a threat (not to the project itself, but to the maintainers). Thank you for clarifying that :)

I don't know if @tinchoz49 will continue to work on this, I did some work on my computer but there are some compatibility issues with some api.
I'll open  a pr soon to show my findings.

**Comment by tinchoz49** [comment]
Hi everyone! @delvedor @benoneal Yes, I had started to work on a PR for fastify, basically to do something like this:
```javascript
const fastify = require('fastify')({
  createServer (httpHandler, options) {
    return require('turbo-http').createServer(httpHandler)
  }
})
```

But I didn't continue it and I never publish it because first I want to see if we can merge the PR that I made for turbo-http to work with fastify. https://github.com/mafintosh/turbo-http/pull/18

@delvedor If you want, I will happy to help you with your PR :smiley:

**Comment by delvedor** [comment]
@tinchoz49 ops, I missed that, sorry!
Great work!
If it is ok for you, since I've already opened the pr, we can work there. I'll be very happy to have a review also from you :)

**Comment by tinchoz49** [comment]
@delvedor don't worry and I'm ok to keep working in your PR :relaxed: . I will try to do a review today.

**Comment by mahdisml** [comment]
i tested fastify with uws 
`
const fastify = require('fastify')({
    createServer (httpHandler, options) {
      return require('uws').http.createServer(httpHandler)
    }
  })`
But there was no performance effect.Was my code wrong?

**Comment by alexhultman** [comment]
@ansarizafar I don't think that's fastify-realted enough to be discussed in this fastify repo.

I think it makes more sense to close this issue, since the new direction uws is taking differs and is not suited for fastify-like wrappers.
