### ISSUE TITLE
Internal references inside a single imported schema file not found

### ISSUE THREAD

**Issue by then3rdman** [fastify/fastify#3650]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I am not sure that this is a bug as much as it is design.

In our API we are adding a single schema file with `$id: Global` which contains all the definitions, a considerable few of those definitions are referencing other definitions as such `{ $ref: #/definitions/** }. 

This seems to present two issues. The first being that when using this schema on a route eg 
`{ $ref: 'Global#/definition/Thing' }`
If that definition references another as shown above, the reference is broken, with Fastify throwing an error. If the internal reference is changed to explicitly reference global eg `{ $ref: Global#/definitions/NestedThing  }` this works. Is this how it is meant to work? 

The second issue, that might be related, is that when using Fastify-Swagger, it is not able to resolve any of the definitions within the Global scope. 

I can provide more specifics as required but honestly was just hoping to get some clarification as to whether we are doing something wrong / this is designed behaviour or something is amiss.

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by then3rdman** [comment]
Can be easily reproduced here

https://github.com/then3rdman/fastify-issue

**Comment by mcollina** [comment]
I'm sorry but I do not understand how to reproduce the problem with your code. Please provide _clear instructions_ on how to reproduce the problem.

**Comment by then3rdman** [comment]
simply running the server will produce the problem 
`yarn dev`

**Comment by then3rdman** [comment]
Apologies, was a mistake in the schema names. Simply run the server and you get get the error. 

`yarn dev`

**Comment by mcollina** [comment]
This will fix your problem:

```diff
diff --git a/schema.json b/schema.json
index 5d2e4ca..51bc437 100644
--- a/schema.json
+++ b/schema.json
@@ -36,7 +36,7 @@
       "additionalProperties": false,
       "properties": {
         "address": {
-          "$ref": "#/definitions/Address"
+          "$ref": "Global#/definitions/Address"
         }
       },
       "required": ["address"],
```

**Comment by then3rdman** [comment]
I know that will fix it. That's already in code under the working endpoint
schema.

Thats not a solution as that is invalid JSON schema. The internal
references should work with just #, as is the spec

**Comment by mcollina** [comment]
The error generates in Ajv and there is nothing that Fastify can do here:

```js
const Ajv = require('ajv')
const schema = {
  "$id": "Global",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Address": {
      "$id": "Address",
      "additionalProperties": false,
      "properties": {
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "id": {
          "$format": "uuid",
          "type": "string"
        },
        "line1": {
          "type": "string"
        },
        "postcode": {
          "$maxLength": 4,
          "$minLength": 4,
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": ["id", "line1", "city", "state", "postcode", "country"],
      "type": "object"
    },
    "Error": {
      "$id": "Error",
      "additionalProperties": false,
      "properties": {
        "address": {
          "$ref": "#/definitions/Address"
        }
      },
      "required": ["address"],
      "type": "object"
    },
    "Works": {
      "$id": "Works",
      "additionalProperties": false,
      "properties": {
        "address": {
          "$ref": "Global#/definitions/Address"
        }
      },
      "required": ["address"],
      "type": "object"
    }
  }
}

const ajv = new Ajv()

ajv.addSchema(schema)

ajv.compile({
  type: "array",
  items: { $ref: "Global#/definitions/Error" },
})
```

**Comment by then3rdman** [comment]
OK thanks, didn't realise it was completely isolated to the AJV code. Thanks for the help

**Comment by mcollina** [comment]
No worries, it's often hard to diagnose these
