### ISSUE TITLE
Deprecate variadic `.listen` signature

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#3652]
> I think we should introduce a breaking change where `.listen` only accepts an object. Start with a deprecation notice for v4, but remove the variadic signature for v5.
>
> _Originally posted by @jsumners in https://github.com/fastify/fastify/pull/3606#discussion_r790275606_

The Fastify code is quite difficult to follow and maintain in a lot of places. We should be taking every opportunity we can to simplify the code, and to make the public interfaces less confusing. We emulated Node core's `.listen` method in an effort to retain as much familiarity as possible. I am quite certain I made the argument to do such. But at this point I think:

1. Variadic interfaces are confusing for developers and should be avoided now that object destructuring, and parameter defaults, are widely available.
2. Many newcomers to Fastify have likely never touched Node core's `net.Server`.
3. We owe it to ourselves to make the code we maintain easier.

**Comment by Eomm** [comment]
I would keep two interfaces:

- `listen(port[, callback])`
- `listen(options[, callback])`

the first one is too much handy

**Comment by mcollina** [comment]
What would be the effects of such confusion? What mistakes users would make?

**Comment by jsumners** [comment]
> What would be the effects of such confusion? What mistakes users would make?

I think that people don't even realize more parameters are available for the `.listen` method. I think that is the biggest cause of people asking things like https://discord.com/channels/725613461949906985/725613462373269567/934671135482708139:

![image](https://user-images.githubusercontent.com/321201/150988865-e65692fc-5e17-4dce-b667-2dd754551b7b.png)

Even though we specifically call out the reason for that, and the various method signatures, [in the docs](https://www.fastify.io/docs/latest/Reference/Server/#listen) I think people latch on to the first example. I think that by supporting _only_ the options object we will reduce that error, while also making our code easier to maintain. By forcing people to use the options object, I think they will be more likely to explore the full set of options available to the method.

**Comment by fox1t** [comment]
I agree with @Eomm: passing just a port is so handy I would leave it as an option.

**Comment by jsumners** [comment]
> I agree with @Eomm: passing just a port is so handy I would leave it as an option.

I think this completely negates the suggestion. Writing `.listen({ port: 8000 })` is not very difficult.

**Comment by MetCoder95** [comment]
If I can add my two cents in here, I do agree with @jsumners that variadic interfaces can make everything more complicated, even more in an era where IntelliSense and auto-suggestions on Text Editors and IDEs are a thing where developers rely the most, meaning fewer visits to documentation and heavily relying on TS types for that (which is also quite bad but it is what it is).

Having a single argument can make some stuff easier in long term, and reduce the verbosity of the code a little, at least enough to simplify some stuff. I still need to visit quite often docs for Node.js core quite often because the same situation :)

**Comment by jsumners** [comment]
I'm not sure how to make a decision here. Going on comment votes, I'd say the resolution passes. But actual comments puts it at 2 - 2.

**Comment by climba03003** [comment]
I will go for a single object option. It just better for code maintenance.

**Comment by mcollina** [comment]
Let me propose a slightly different take: we shift the examples everywhere to use the option object instead of the variadic arguments, and mark that our preferred way to call listen().

**Comment by jsumners** [comment]
@mcollina That doesn't solve the maintenance part of the issue.
