### ISSUE TITLE
Calling reply.callNotFound inside frameworkErrors can result in an uncaught exception

### ISSUE THREAD

**Issue by Allain55** [fastify/fastify#3660]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Plugin version

4.5.0

### Node.js version

17.4.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Following the example below it'll instantly log an error:
```
TypeError: Cannot read properties of undefined (reading 'preHandler')
    at notFound (node_modules/fastify/lib/reply.js:707:21)
    at Reply.callNotFound (node_modules/fastify/lib/reply.js:309:3)
    at frameworkErrors (test.js:14:17)
    at onBadUrl (node_modules/fastify/fastify.js:613:14)
    at Object.handler (node_modules/find-my-way/index.js:621:33)
    at Router.lookup (node_modules/find-my-way/index.js:378:14)
    at node_modules/light-my-request/index.js:87:41
    at Request.prepare (node_modules/light-my-request/lib/request.js:132:12)
    at makeRequest (node_modules/light-my-request/index.js:87:14)
    at node_modules/light-my-request/index.js:113:7
```

If an url with an invalid uri is opened in the browser then an uncaught exception will happen.

### Steps to Reproduce

Run this example:

```
const fastifyStatic = require('fastify-static');

(async () => {
	process.on(
		'uncaughtException',
		(err) => {
			console.log('uncaughtException', err);
		}
	);
	
	const fastify = require('fastify')({
		logger: true,
		frameworkErrors: (error, req, reply) => {
			return reply.callNotFound();
		}
	});
	
	fastify.register(
		fastifyStatic,
		{
			root: '/www' // doesn't need to exit
		}
	);

	await fastify.listen(8080);
	
	await fastify.inject({
		method: 'GET',
		url: '/%'
	});
})()
	.catch((err) => {
		console.error(err);
	})
```

### Expected Behavior

Calling reply.callNotFound should work in this case.

**Comment by mcollina** [comment]
I transferred this to Fastify proper, it's a bug there.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

For some reason there is no `context` defined in:
https://github.com/fastify/fastify/blob/25147feda161e0f51e5b32e88bec87793188a8d4/lib/reply.js#L707

Likely we are not instatiating something correctly in https://github.com/fastify/fastify/blob/main/fastify.js#L611-L612

**Comment by VigneshMurugan** [comment]
@mcollina 

Problems lies in https://github.com/fastify/fastify/blob/25147feda161e0f51e5b32e88bec87793188a8d4/lib/reply.js#L698

We are using string null checker here which is causing https://github.com/fastify/fastify/blob/25147feda161e0f51e5b32e88bec87793188a8d4/lib/reply.js#L706 to set context to null.

I am raising the PR for the same

**Comment by mcollina** [comment]
Where is that assigned to undefined? I think we should not be in that position.

**Comment by VigneshMurugan** [comment]
`reply.context[kFourOhFourContext] ` is coming in as undefined

![image](https://user-images.githubusercontent.com/9670465/151168204-b84f9cb8-a548-4bfc-b695-f947ee3745c5.png)

![image](https://user-images.githubusercontent.com/9670465/151168230-ba08ea9f-7076-45d7-b9f0-c00546ec3ccf.png)

**Comment by mcollina** [comment]
> I transferred this to Fastify proper, it's a bug there.
> 
> 
> 
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.
> 
> 
> 
> For some reason there is no `context` defined in:
> 
> https://github.com/fastify/fastify/blob/25147feda161e0f51e5b32e88bec87793188a8d4/lib/reply.js#L707
> 
> 
> 
> Likely we are not instatiating something correctly in https://github.com/fastify/fastify/blob/main/fastify.js#L611-L612

As I said in the text above, We are not initializing Reply and the context correctly in 

https://github.com/fastify/fastify/blob/main/fastify.js#L611-L612

**Comment by VigneshMurugan** [comment]
Sorry I think I got confused here. This is what I analysed. Kindly correct me and point me to the place where I am going wrong.

In line number https://github.com/fastify/fastify/blob/20f934307c29ab97988222a165c84f16b7146ce6/fastify.js#L611 we are initialising the onBadUrl Context with https://github.com/fastify/fastify/blob/20f934307c29ab97988222a165c84f16b7146ce6/fastify.js#L57-L62 where we don't have the `kfourOhFourContext`

So https://github.com/fastify/fastify/blob/25147feda161e0f51e5b32e88bec87793188a8d4/lib/reply.js#L698 will fail as it isn't null but undefined.

So this line  https://github.com/fastify/fastify/blob/25147feda161e0f51e5b32e88bec87793188a8d4/lib/reply.js#L704 would assign undefined context.

So as per your last comment I should be modyfying this context object https://github.com/fastify/fastify/blob/20f934307c29ab97988222a165c84f16b7146ce6/fastify.js#L57 to accommodate fourOhFourContext. Is that what you are suggesting ?

**Comment by VigneshMurugan** [comment]
https://github.com/fastify/fastify/pull/3661
