### ISSUE TITLE
Optional route parameter throws error on root path

### ISSUE THREAD

**Issue by michael-melodyarc** [fastify/fastify#3663]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Node.js version

16.13.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

21.10

### Description

Marking a parameter as optional throws an error when using root path.  I'm not sure if this is related to `fastify` or `find-my-way`, so let me know if this is the wrong place.

### Steps to Reproduce

```js
app.get('/:id?', (req, res) => 'hello world'); // throws Error: The path could not be empty

app.get('/anything/:id?', (req, res) => 'hello world'); // works
```

### Expected Behavior

I'd expect both snippets of code to work correctly.  In the first case, it'd accept routes for both the root path with no parameters, and requests with a single parameter after the root path.

Examples that work:
```
https://fastify.io/
https://fastify.io/applesauce
https://fastify.io/123456
```

Examples that would not work:
```
https://fastify.io/a/b
https://fastify.io/a/b/c
```

**Comment by mcollina** [comment]
what error does it throw?

**Comment by michael-melodyarc** [comment]
It throws with an error of `Error: The path could not be empty`.

**Comment by mcollina** [comment]
Can you include the stacktrace?

**Comment by michael-melodyarc** [comment]
Yeah, sorry, I'm not intentionally trying to be obtuse, haha.  The stack trace is pretty bare, so I didn't think it was super valuable, but it does point to it being in `find-my-way` instead of `fastify`.

```
AssertionError [ERR_ASSERTION]: The path could not be empty
    at Router.on (/<removed>/node_modules/find-my-way/index.js:82:3)
    at Router.on (/<removed>/node_modules/find-my-way/index.js:96:10)
    at Object.afterRouteAdded (/<removed>/node_modules/fastify/lib/route.js:255:16)
    at /<removed>/node_modules/fastify/lib/route.js:182:25
    at Object._encapsulateThreeParam (/<removed>/node_modules/avvio/boot.js:551:7)
    at Boot.timeoutCall (/<removed>/node_modules/avvio/boot.js:447:5)
    at Boot.callWithCbOrNextTick (/<removed>/node_modules/avvio/boot.js:428:19)
    at Boot._after (/<removed>/node_modules/avvio/boot.js:273:26)
    at Plugin.exec (/<removed>/node_modules/avvio/plugin.js:132:19)
    at Boot.loadPlugin (/<removed>/node_modules/avvio/plugin.js:267:10)
```

**Comment by Eomm** [comment]
Could you open an issue to https://github.com/delvedor/find-my-way/ ?

This recreates the error:

```
const FindMyWay = require('find-my-way')
const findMyWay = FindMyWay({ })
findMyWay.on('GET', '/:id?', (req, res) => { })
```

**Comment by michael-melodyarc** [comment]
Will do - thanks.
