### ISSUE TITLE
Open missing TS issue automation

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3664]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be nice to add automation that opens a new issue when a PR is labelled as `missing-types`.

### Motivation

Adding TS to a PR is not mandatory, but we should track the things that are missing.

In this way, the TS community may help us to keep the types in sync within the Node.js interface.

### Example

- a maintainer add a `missing-types` label to a PR
- the automation creates a new issue tagged: `good-first-issue`, `typescript`

**Comment by KiraPC** [comment]
Hello @Eomm 

I've started to work on this but I have some question:

- is it ok to reuse already existing action?
- What the title and body of the issue should contains?

I did something like "Missing Typescript for PR ${{ github.event.pull_request.title }}", but no idea about the body.

**Comment by Eomm** [comment]
> is it ok to reuse already existing action?

Which one?

> What the title and body of the issue should contains?

Maybe:

title: `ts: add missing types to [${{ github.event.pull_request.title }}]`
body: 

```
PR #123 has introduced a new feature that requires updating Fastify's typings and tests.

Learn how to [contribute](https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md)
Get inspired by [this example PR](https://github.com/fastify/fastify/pull/3231)
```

**Comment by KiraPC** [comment]
@Eomm Ok for title and body, can be done.


> 
> Which one?
> 

I tested [this](https://github.com/marketplace/actions/actions-ecosystem-action-create-issue) on my forked repo and worked well.

Or [this](https://github.com/marketplace/actions/create-an-issue) could be another option, but I don't know if in the template markdown I can use github events as placeholder.

**Comment by Eomm** [comment]
I would go for: https://github.com/octokit/request-action
It is more flexible

**Comment by KiraPC** [comment]
I tried this right now, make different tests, but this action has some problems.

First of all, the string parsing when you use colon fails, because returns [object object], there is an issue opened [[HERE](https://github.com/octokit/request-action/issues/118)

Second, I was not able to figure out how to pass a list for the labels parameter, if I use a list in yaml github workflows validate the steps and reject because it does not expect a sequence at that level, if I use string octokit validate the field expecting a list.

**Comment by Eomm** [comment]
They did not try to encode it:

```
title: ts%3A add missing types to [${{ github.event.pull_request.title }}]
```

Or, to use the `format` utility: https://docs.github.com/en/actions/learn-github-actions/expressions#format

It might work

**Comment by KiraPC** [comment]
I tried both, but neither using the encoded neither the format worked, you can check on my forked repo issues the title results.

We can change the title, maybe.

**Comment by Eomm** [comment]
> We can change the title, maybe.

Let's go for this as the first step.
Note that we need to remove the `github.event.pull_request.title` as well

**Comment by Fdawgs** [comment]
@Eomm Would you say this is closed by https://github.com/fastify/fastify/pull/3668 now?
