### ISSUE TITLE
pluginTimeout not able to set 0 (disable)

### ISSUE THREAD

**Issue by vip30** [fastify/fastify#3665]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Node.js version

16.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

According to https://github.com/fastify/fastify/blob/main/fastify.js#L364 , we're not able to set pluginTimeout to 0 which means disable the timeout

### Steps to Reproduce

```
const server = fastify({ logger: true, pluginTimeout: 0 });

server.register(// load many things and exceed 10s)
```

### Expected Behavior

We should able to set timeout to zero base on https://github.com/fastify/avvio

**Comment by mcollina** [comment]
Why would you want to disable the timeout?

**Comment by VigneshMurugan** [comment]
I agree with the point that the logic in https://github.com/fastify/fastify/blob/b15c7c566888c7953715c031a8b3bfe13c3d1960/fastify.js#L364 will not allow you to set it to 0. 

But my question is why would you want to disable a timeout ?

**Comment by vip30** [comment]
Actually, I am following this issue https://github.com/fastify/help/issues/188#issuecomment-628824762 to set the plugin timeout to zero, but yes I know we can wrap the register in an async function and await the long operation before register the plugin

**Comment by mcollina** [comment]
I guess I was wrong. Thanks for reporting, I'm closing this.
