### ISSUE TITLE
Async errors aren't caught by `setErrorHandler`

### ISSUE THREAD

**Issue by kurtextrem** [fastify/fastify#3675]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Node.js version

17.1.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Errors thrown in async functions of async routes don't bubble up to `setErrorHandler`'s function

### Steps to Reproduce

```js
const fastify = require('fastify')({ logger: true });
fastify.setErrorHandler(function (error, req, rep) {
   console.log(error)
   rep.send(error)
});

fastify.get('/async', async function (req, rep) {
   setImmediate(function() {
      throw new Error('a')
      rep.send('')
   });

  await rep
});

fastify.get('/sync', async function (req, rep) {
   throw new Error('a')
});

fastify.listen(3000);
```

### Expected Behavior

Node server doesn't crash from the thrown Error in the `/async` route, but currently it does. Only for the sync route it does not and logs the error. The docs also do not mention this.

The use case for this is when you e.g. have an axios request that fails, we want to have a global error handler instead of needing to send the error response in a try catch deep inside the route's handler.

**Comment by MetCoder95** [comment]
Hi! I'm not sure I'm totally following your problem. From your code, I don't see anything wrong happening.
Recent Node versions exit the process on unhandled exceptions, which is the reason why the `/async` endpoint is exiting the process when being hit.

The `/async` endpoint is successfully fulfilling the request as you're just surrounding the function with the `async` keyword, transforming it into a promise. Then, as immediately resolves, the lifecycle of the request continues, and just after serving the response back the `setImmediate` callback is being executed, throwing and exiting your process.

Meanwhile, on the `/sync` endpoint, you're doing exactly the same, but in this case, as you're using the keyword `throw` to throw an error, the Promise returned gets immediately `rejected`, causing `fastify` to properly handle it serving a `500` status code to the client.

Fixing your example will be something like this:
```js
const fastify = require('./fastify')({ logger: true })
fastify.setErrorHandler(function (error, req, rep) {
  console.log(error)
  rep.send(error)
})

fastify.get('/async', async function (req, rep) {
  await new Promise((resolve, reject) => {
    setImmediate(function () {
      return reject(new Error('a'))
      rep.send('') // <-- never called
    })
  })
})

fastify.get('/sync', async function (req, rep) {
  throw new Error('a')
})

fastify.listen(3000)
```

P.D. of course this is totally an example and not recommended at all :)

**Comment by mcollina** [comment]
This is how Node.js work, there is nothing specific about fastify.

**Comment by kurtextrem** [comment]
Ah thank you!
