### ISSUE TITLE
custom-errors-message doesn't work?

### ISSUE THREAD

**Issue by Arimanecro** [fastify/fastify#3678]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Node.js version

17

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Hi.
Is this bug or I'm doing wrong?
I got examples of the code from here -- https://github.com/fastify/fastify/blob/main/docs/Reference/Validation-and-Serialization.md#schemaerrorformatter

### Steps to Reproduce

```
import ajvErrors from "ajv-errors";

const app = fastify({
  ajv: {
    customOptions: {
      jsonPointers: true,
      allErrors: true
    },
    plugins: [ajvErrors],
  },
}

const itemSchemaTpl = {
  type: "object",
  properties: {
    id: { type: "string" },
    title: { type: "string"},
  },
  required: ["id", "title"],
  errorMessage: {
    required: {
      title: "SHIIIIIT",
    },
  },
};
app.get("/items/:id", {
  schema: {
    response: {
      200:  itemSchemaTpl,
    },
  },
  handler: (req, res) => res.send({id:"2"})
});
```

### Expected Behavior

Response is **{"statusCode":500,"error":"Internal Server Error","message":"\"title\" is required!"}**
**BUT I expected message - SHIIIIIT**

**Comment by mcollina** [comment]
What version of ajv-errors are you using?

**Comment by Arimanecro** [comment]
> What version of ajv-errors are you using?

"ajv-errors": "^1.0.1"

**Comment by Eomm** [comment]
Ajv is used as a validator for the input.

You are using the schema as a serializer for the output so it won't work.
```
  schema: {
    response: {
      200:  itemSchemaTpl,
    },
  },
```

Take a look here: https://github.com/fastify/fastify-response-validation
