### ISSUE TITLE
How can I enable Gzip in Fastify ?

### ISSUE THREAD

**Issue by keuller** [fastify/fastify#368]
Hi guys,

Anyone knows which plugin/middleware that can I use to enable gzip compression in routes ?

Thanks.

**Comment by jsumners** [comment]
https://github.com/expressjs/compression ?

**Comment by StarpTech** [comment]
@keuller https://expressjs.com/en/advanced/best-practice-performance.html If you want to build a high-performance application you should use a reverse proxy (Nginx, Apache, IIS) otherwise you can use the middleware mentioned above.

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
