### ISSUE TITLE
jsonShorthand is missing in TypeScript type declaration for Fastify

### ISSUE THREAD

**Issue by Hornwitser** [fastify/fastify#3680]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Node.js version

17.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux

### Description

When trying to use the [`jsonShorthand`](https://www.fastify.io/docs/v3.27.x/Reference/Server/#jsonshorthand) option to Fastify server the TypeScript compiler raise the following error:

```
bug.ts:2:11 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ jsonShorthand: boolean; }' is not assignable to parameter of type 'FastifyServerOptions<http.Server, FastifyLoggerInstance>'.
      Object literal may only specify known properties, and 'jsonShorthand' does not exist in type 'FastifyServerOptions<http.Server, FastifyLoggerInstance>'.

2 Fastify({ jsonShorthand: false })
            ~~~~~~~~~~~~~~~~~~~~

```

### Steps to Reproduce

Install fastify and typescript and try compiling the following file
```ts
import Fastify from "fastify"
Fastify({ jsonShorthand: false })
```
with `npx tsc --skipLibCheck file.ts`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Hornwitser** [comment]
No, not really. If anyone wants to do it, just go ahead and do it.

**Comment by DanieleFedeli** [comment]
I can pick this up.
