### ISSUE TITLE
`package-manager-ci` is currently failing

### ISSUE THREAD

**Issue by Divlo** [fastify/fastify#3691]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Since this PR #3682, `package-manager-ci` GitHub Action is failing.
It fails because ESLint v8 requires Node.js >= 12.22.0, and it is running on Node.js v10 (so that would naturally be fixed by #3482).
This is a tracking issue so we can fix this.

Several comments :
- Is it necessary to run linting multiple times depending on the Node.js version? It might be better to run linting only once using maybe Node.js `lts/*` version.
- This issue could be avoided if we would ran that action also on PRs not only for `main` branch as it is currently the case:
https://github.com/fastify/fastify/blob/8a4a9b09bdf01ed26b7c9732ad25bcfdac4f5ec1/.github/workflows/package-manager-ci.yml#L3-L6
- Just because of curiosity, is it necessary to test depending on the `package-manager`, is `fastify` work differently across different package managers?

**Comment by zekth** [comment]
This issue has been tackled in : https://github.com/fastify/fastify/pull/3623

In `package-manager-ci` we should use `test:ci` and not `test`

Would you create a PR to fix this?

**Comment by Divlo** [comment]
> This issue has been tackled in : #3623
> 
> In `package-manager-ci` we should use `test:ci` and not `test`
> 
> Would you create a PR to fix this?

Oh great!
Sure, here is the PR: #3692 :smile:
