### ISSUE TITLE
Not found handler not called when request HTTP method is not supported

### ISSUE THREAD

**Issue by markwainwright** [fastify/fastify#3702]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.3

### Description

When handling a request that uses an HTTP method that Fastify does not support (e.g. `PURGE`), Fastify responds with a 404, but this response is hard to customize because:

1. The handler set with `setNotFoundHandler` is not called
2. The handler set with `setErrorHandler` _is_ called, but the error passed in does not have a `statusCode` property, nor `name: "FastifyError"` etc, so it's not reliably distinguishable from an unhandled error from somewhere else.

https://github.com/fastify/fastify/blob/9b1877626bb345f3a4746d678bc56b0bb23b7f2a/lib/handleRequest.js#L57-L58

If possible, calling the notFoundHandler seems like the most intuitive approach to me. Otherwise I think calling `reply.send(new FST_ERR_NOT_FOUND())` instead of a plain `Error` would be acceptable.

Let me know if I can clarify anything. Thank you!

### Steps to Reproduce

Say I want a plain text response instead of JSON:

```js
const fastify = require('fastify')();

fastify.setNotFoundHandler((request, reply) => {
  reply.status(404).send("Resource not found");
});

fastify.setErrorHandler((error, request, reply) => {
  reply.status(error.statusCode || 500).send(error.message);
});

fastify.listen(3000);
```

```sh
curl -vX PURGE localhost:3000
```

### Expected Behavior

Response status: 404
Response body: `Resource not found`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by markwainwright** [comment]
Hi @mcollina, please see #3705, thanks!
