### ISSUE TITLE
pnpm tests broken for v4

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3709]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

mian branch / v4

### Node.js version

v16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

gituhb actions

### Description

Our pnpm tests are failing https://github.com/fastify/fastify/runs/5249770711?check_suite_focus=true.

### Steps to Reproduce

Check Github actions

**Comment by Eomm** [comment]
I think the issue is hidden here:

https://github.com/fastify/fastify/blob/65479ae199b92b6c527925d7a033e364967c16e9/package.json#L124-L125

There is some clean to-do

I will take a look later this weekend 👍🏽

**Comment by Eomm** [comment]
Reopening due to this new error during the `ts` check:

>   test/types/schema.test-d.ts:6:16
>   ✖  6:16  Cannot find module ajv or its corresponding type declarations.
