### ISSUE TITLE
Delayed `preHandler` hook setup will make the `preHandler` hook get lost

### ISSUE THREAD

**Issue by BigMurry** [fastify/fastify#372]
For the following test code:
```js
test('delayed hook', t => {
  const fastify = Fastify()
  // delay the preHandler hook setup
  setImmediate(() => {
    fastify.addHook('preHandler', (request, reply, next) => {
      request.req.preHandlerMsg = 'from delayed preHandler hook'
      next()
    })
  })
  // delay the onRequest hook setup
  setImmediate(() => {
    fastify.addHook('onRequest', (req, reply, next) => {
      req.onRequestMsg = 'from delayed onRequest hook'
      next()
    })
  })
  fastify.get('/', (request, reply) => {
    t.is(request.req.preHandlerMsg, 'from delayed preHandler hook') // This will fail
    t.is(request.req.onRequestMsg, 'from delayed onRequest hook') // This will pass
    reply.code(200).send({hello: 'world'})
  })
  fastify.listen(0, (err) => {
    t.error(err)
    fastify.server.unref()

    request({
      method: 'GET',
      uri: 'http://localhost:' + fastify.server.address().port + '/'
    }, (err, response, body) => {
      t.error(err)
      t.strictEqual(response.statusCode, 200)
      t.strictEqual(response.headers['content-length'], '' + body.length)
      t.deepEqual(JSON.parse(body), { hello: 'world' })
      t.end()
    })
  })
})
```
The delayed `preHandler` will missing (not exist in the router handler store), but the delayed `onRequest` will not.

I debug this a little find that:
https://github.com/fastify/fastify/blob/07f7e9bfebac52439114f9931f3915ee82048d4e/fastify.js#L386-L406
In this section, it can be found that the `onRequest` and `onResponse` hooks in `store` will hold the corresponding references of `_fastify._hooks.onRequest` and `_fastify._hooks.onResponse`. But the `preHandler` hook in `store` object will not hold the reference. So that later on `addHook` will not effect the `preHandler` hooks in `store` object.
I think this behavior is a little strange. Meant to act this way?

**Comment by delvedor** [comment]
Why do you need to delay the hooks registration?
The behaviour for the `preHandler` is correct, because we must attach to it the `beforeHandler`([docs](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#beforehandler)).

`addHook` is a synchronous api, if you need to perform some async work before add a hook, you must use a plugin, that will handle all the async-related problems for you.

Feel free to re-open if you have other questions or bugs :D

**Comment by BigMurry** [comment]
Yes, it should be a synchronous api and should not delay the registration. But, if we don't do it carefully, we may have trouble to write the test.

For example, in `hooks.test.js` file, if we move the `onRequest hook should support encapsulation / 1` test above the `hooks - add preHandler` test, the test will fail. And this gives me some hard times to figure out why. :D

**Comment by delvedor** [comment]
Yeah, it's an old file that has been modified different times, it definitely needs a little refactor :P
