### ISSUE TITLE
Drop Coveralls?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#3720]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I don't think Coveralls is checking things correctly. When we look at the CI results for commit https://github.com/fastify/fastify/pull/3712/commits/5a77a6b9a93d0b1e1c830a8c9bce997b2bcc7646 we can see that Coveralls is suggesting coverage remains at 100% for all OSes, but `tap` is saying otherwise:

https://coveralls.io/jobs/94867280
![fastify - Vivaldi 2022-02-20 18-57-15](https://user-images.githubusercontent.com/321201/154870207-1abffa81-21bf-4d6e-b6a6-7297c8ba1437.png)

https://github.com/fastify/fastify/runs/5267302531?check_suite_focus=true
![fastify - Vivaldi 2022-02-20 18-58-03](https://user-images.githubusercontent.com/321201/154870226-abfc2622-d256-4933-b3cb-5f476dfa44c1.png)

With #3717 and #3719, we will have coverage reports attached to the GitHub Actions panel itself. We'd have to download the artifacts to inspect what coverage is missing, instead of browsing a hosted website (Coveralls), but at least it'd be consistent and accurate(?).

**Comment by Eomm** [comment]
Does coverall merge the coverage report into one?

I think tap is not working on win because of this test

https://github.com/fastify/fastify/blob/77680ff3de42902718313c404946fe16f8b5e8ff/test/listen.test.js#L215

**Comment by mcollina** [comment]
I'm always in for removing coveralls.

**Comment by jsumners** [comment]
> Does coverall merge the coverage report into one?

I have no idea. I never look at it.

**Comment by Fdawgs** [comment]
> Does coverall merge the coverage report into one?

Yeah, because we're using the parallel option it amalgamates them into a single report:
https://github.com/fastify/fastify/blob/39661e6ea6ce83c835e383ff2f0531680461d27d/.github/workflows/ci.yml#L82
