### ISSUE TITLE
ec2 with Fastify "SyntaxError: Unexpected token ..."

### ISSUE THREAD

**Issue by Lev488** [fastify/fastify#3728]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2

### Plugin version

1.0.0

### Node.js version

14.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.2

### Description

I have a problem with Fastify when running my server on ec2 AWS. 

### Steps to Reproduce

ec2 returns error when trying to run the server 
```/var/www/html/node-app/server/node_modules/fastify/fastify.js:160
      ...constraints,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/node-app/server/app.js:6:35)```

### Expected Behavior

_No response_

**Comment by mcollina** [comment]
What version of Node.js are you using?

```
$ node
Welcome to Node.js v14.17.0.
Type ".help" for more information.
> const obj = { foo: 42 }
undefined
> { ...obj }
{ foo: 42 }
```

**Comment by Lev488** [comment]
v14.16.0

**Comment by mcollina** [comment]
That syntax is supported on Node v14, you are likely using a different version of Node.js on your EC2 server on AWS.

```
$ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> const obj = { foo: 42 }
undefined
> { ...obj }
{ foo: 42 }
````

**Comment by Lev488** [comment]
In AWS I wrote your example it returned as expected { foo: 42 }
