### ISSUE TITLE
Possible serialization bug with response schema

### ISSUE THREAD

**Issue by Jnig** [fastify/fastify#3749]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2, 4.0.0-alpha.1

### Node.js version

14.19

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux

### Description

Hi,

I'm using fastify with a response schema. In the schema I've a property called user, which can be `null` or a object with `id` and `email`.

When the user object has the properties `id` and `email` everything works as expected. If the object contains an additional property, the whole user object is converted to `null` in the response. This was somehow unexpected, but I'm not sure if this is really a bug.

### Steps to Reproduce

```ts
const fastify = require("fastify")({
  logger: true,
});

const opts = {
  schema: {
    response: {
      "2xx": {
        type: "object",
        properties: {
          id: {
            type: "number",
          },
          name: {
            type: "string",
          },
          user: {
            anyOf: [
              {
                type: "null",
              },
              {
                type: "object",
                properties: {
                  id: {
                    type: "number",
                  },
                  email: {
                    type: "string",
                  },
                },
                additionalProperties: false,
              },
            ],
          },
        },
      },
    },
  },
};

// returns {"id":1,"name":"foo","user":{"id":1,"email":"foobar@local"}}
fastify.get("/", opts, function (request, reply) {
  reply.send({ id: 1, name: "foo", user: { id: 1, email: "foobar@local" } });
});

// returns {"id":1,"name":"foo","user":null}
fastify.get("/with-additional", opts, function (request, reply) {
  reply.send({
    id: 1,
    name: "foo",
    additionalProp: "foo",
    user: { id: 1, email: "foobar@local", firstName: "foobar" },
  });
});

fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```

### Expected Behavior

Additional properties in the user object should be removed instead of setting the object to `null`. This would mirror the behavior for other additional properties. `additionalProp` is removed from the output.

The following code
```ts
reply.send({
    id: 1,
    name: "foo",
    additionalProp: "foo",
    user: { id: 1, email: "foobar@local", firstName: "foobar" },
  });
```
should return
```
{"id":1,"name":"foo","user":{"id":1,"email":"foobar@local"}
```

following is returned
```
{"id":1,"name":"foo","user":null}
```

**Comment by Eomm** [comment]
`fast-json-stringify` does not support the `type: null` atm

you need to use this schema:

```
const schema = {
  type: 'object',
  properties: {
    id: {
      type: 'number',
    },
    name: {
      type: 'string',
    },
    user: {
      nullable: true,
      type: 'object',
      properties: {
        id: {
          type: 'number',
        },
        email: {
          type: 'string',
        },
      },
      additionalProperties: false,
    },
  },
}
```

Closing as duplicates https://github.com/fastify/fast-json-stringify/issues/388

**Comment by Jnig** [comment]
@Eomm thanks for pointing to the fast-json-stringify issue
