### ISSUE TITLE
Response has unexptected output

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#375]
Root issue https://github.com/fastify/fastify-static/issues/13

I already removed `point-of-view`, `send` (fastify-static) package to escape the issue but it still exists. The rest is routing.

For me, it looks like that we have an issue in the response pipeline. The responded file in `marko-fastify` has the content of a different file.

**Comment by allevo** [comment]
Could you provide an simple example? A test is even better...

**Comment by StarpTech** [comment]
No, but you can checkout the marko-fastify example and test it.

**Comment by allevo** [comment]
Could you provide a simple "todo" list in order to reproduce the error?
Like:
- clone repo <>
- checkout the branch <>
- npm i
- npm start
- navigate to here <>
- the url <> is not downloaded as aspected

**Comment by StarpTech** [comment]
- Clone https://github.com/marko-js-samples/marko-fastify
- npm i
- node ./server.js
- open localhost:8080
- open devTools and look in the console, you will see an error. If you compare the source code of the js files with the files in the static folder you will recognize that many files are responded with incorrect content. If you refresh the page other files will be affected.

**Comment by allevo** [comment]
Really, could you provide a "curl" command that return a different content?

I don't want to navigate among js errors. Please provide a simplest example in a smaller context.

**Comment by StarpTech** [comment]
This issue is not reproducible with a fixed js ressource. It's not that hard to checkout that simple repository and check the responses.

**Comment by BigMurry** [comment]
This issue is related with `find-my-way` I guess. In `find-my-way` with version `1.7.0` we may face many routes finding problems. Background see  https://github.com/delvedor/find-my-way/pull/29
So in `fastify` if we upgrade `find-my-way` to version `1.7.1`, the problem should disappear :). I've tested on my computer.

**Comment by themre** [comment]
Probably this is related. I create redirects for leaflet image tiles and responses are created randomly.

**Comment by themre** [comment]
Just bumped find-my-way, tested and it works! when can we expect new version of fastify?

**Comment by delvedor** [comment]
There is no need to release a new version of fastify since `find-my-way` has been released as patch. If you reinstall fastify you will have the latest version of `find-my-way`.
That's how semver works ;)

Can you confirm me that the latest version of `find-my-way` fixes also this issue?

**Comment by themre** [comment]
yes, my version with latest find-my-way works expect. there are at least 50+ tiles provided at once and they are all correctly displayed. previously they were randomly displayed.

**Comment by delvedor** [comment]
cc @StarpTech @allevo

**Comment by StarpTech** [comment]
After a reinstall, I cant reproduce it +1
