### ISSUE TITLE
Custom errorHandler is not invoked for async plugins

### ISSUE THREAD

**Issue by markrzen** [fastify/fastify#3762]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2.1

### Description

When using async/await, setting a global error handler, will not get invoked by schema param validation errors when originating inside a async plugin.

### Steps to Reproduce

```js
const createFastifyServer = require('fastify');

async function randomPlugin(fastify) {
  fastify.route({
    method: 'GET',
    url: '/test/:uuid',
    schema: {
      params: {
        uuid: {
          format: 'uuid'
        }
      }
    },
    handler: async () => ('OK')
  });
}
randomPlugin[Symbol.for('skip-override')] = true;

async function bootstrap() {
  const fastify = createFastifyServer();

  await fastify.register(randomPlugin); // Errors from this plugin goto default error handler

  fastify.setErrorHandler((error, request, reply) => {
    console.log(error);
    reply.code(500).send('NOT OK');
  });

  return fastify;
}

async function init() {
  const fastify = await bootstrap();
  fastify.listen(8080, 'localhost', (err) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
  });
}

init();
```

### Expected Behavior

I expect the custom errorHandler to be called, rather than the default.

**Comment by markrzen** [comment]
It appears that the reply.context is all defaults when we `await fastify.register(plugin);`

**Comment by markrzen** [comment]
I agree the awaiting of plugin registration is a bit odd, but I noticed it was partially (maybe unintentionally) documented herE:
https://www.fastify.io/docs/latest/Reference/Plugins/#asyncawait

**Comment by mcollina** [comment]
This does not surprise me. I would recommend you to move the errorHandler definition before the await. I would need to investigate why this is happening.

I'm not even sure the current behavior is wrong. By using await, you are making sure all plugin so far have been loaded. At that point the error handler is not defined yet, so no error handler in your routes.

I'm not really sure why you are actually using await in this case, it's totally not needed. Was some eslint/editor/typescript config that recommended you to?

**Comment by markrzen** [comment]
Yeah, I really didn't need await on the register, I just saw it in the documentation of ready/after and though "shoot this might be needed?". I suspect I got bit by an accidental `await`...

**Comment by markrzen** [comment]
Is there a reason the documentation for plugin async/await calls out await on the register?

```js
await fastify.register(require('my-plugin'))

await fastify.after()

await fastify.ready()

await fastify.listen(3000)
```

**Comment by markrzen** [comment]
@mcollina You are 100% correct. Things are working correctly, I just misunderstood the code flow around the server context.
