### ISSUE TITLE
different ips results coming from the request fastify route and context mercurius

### ISSUE THREAD

**Issue by YuriFontella** [fastify/fastify#3763]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have a project using fastify, and the ip that comes from request.ip is the client's.

When migrating the project to mercurius, the context.reply.request.ip is no longer the ip of the client, but the ip of the server.

It is possible to verify that different ips come with this project:
https://github.com/goproclube/fastify-mercurius

Fastify:
```
http get https://fastify-mercurius.herokuapp.com/ip
```
Mercurius: [https://www.graphqlbin.com/v2/new](https://www.graphqlbin.com/v2/new)
```
https://fastify-mercurius.herokuapp.com/graphql
```
```
query {
   ip
}
```
Is there something I'm doing wrong?

**Comment by Eomm** [comment]
I would try the https://www.fastify.io/docs/latest/Reference/Server/#trustproxy setting first

**Comment by YuriFontella** [comment]
Regardless of this proxy configuration, I continue to receive the server's ip in the request.

Complicated, on the same server I have an api with fastify and the request returns the client's ip.

**Comment by mcollina** [comment]
`context.reply.request` in mercurius and `request` within Fastify are exactly the same objects. You are calling the same methods and they would return the same results.

In order for this to work you need to set `trustProxy: true` when configuring Fastify.
