### ISSUE TITLE
Inconsistent Typescript definition for FastifyRequest

### ISSUE THREAD

**Issue by MarcoLeko** [fastify/fastify#3775]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

monterey 12.2.1

### Description

The actual `FastifyServerOptions` comes with a generic `Logger` type that enables developers to extend from the default pino logger and also use custom logger methods:
```ts
export type FastifyServerOptions<
  RawServer extends RawServerBase = RawServerDefault,
  Logger extends FastifyLoggerInstance = FastifyLoggerInstance
> = {
   ...
  logger?: boolean | FastifyLoggerOptions<RawServer> | Logger,
  ...
}
```

However the issue starts when using the `FastifyRequest` type which provides the `FastifyLoggerInstance` and no generic.

This limits the user from using custom logger function e.g. `req.log.foo('Ooops!')' // yields to typescript error even though is defined`

To prevent this we could streamline the `FastifyRequest` type accordingly to be generic but also extend from the `FastifyLoggerInstance` like so:

**Possible solution**
```ts
export interface FastifyRequest<
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  ContextConfig = ContextConfigDefault,
  Logger extends FastifyLoggerInstance = FastifyLoggerInstance
> {
  ...
  log: Logger;
  ...
}

``` 

### Steps to Reproduce

* Pass in a custom logger instance to fastify which contains custom logger function
* Define middleware/hook where type of `FastifyRequest` is used
* Call the custom logger function in the middleware/hook
=> Typescript error custom function is not of type `FastifyLoggerInstance` 

### Expected Behavior

`FastifyRequest` should provide a generic Logger similar as in `FastifyServerOptions`

**Comment by MarcoLeko** [comment]
Let me know, if I can provide any help by opening up a PR

**Comment by mcollina** [comment]
Can you check the main branch/v4.0.0-alpha.2? This should be fixed already there.

**Comment by MarcoLeko** [comment]
If Im not mistaken, I dont see the fix applied there yet. Checking: https://github.com/fastify/fastify/blob/v4.0.0-alpha.2/types/request.d.ts

**Comment by mcollina** [comment]
Would you like to send a PR there then? Thanks!

**Comment by MarcoLeko** [comment]
I wrote you a private mail, think might need access rights to create a remote bugfix branch and create a PR against the main branch :)

**Comment by jsumners** [comment]
See https://jrfom.com/posts/2017/03/08/a-primer-on-contributing-to-projects-with-git/

**Comment by MarcoLeko** [comment]
Thank you, will have a look

**Comment by MarcoLeko** [comment]
Since now we fixed the issue, what needs to be done in order to close this bug ticket?
Do we need to publish a new 3.x version in order to make these changes accessible to the user?

**Comment by MarcoLeko** [comment]
> Since now we fixed the issue, what needs to be done in order to close this bug ticket?
Do we need to publish a new 3.x version in order to make these changes accessible to the user?

@mcollina @RafaelGSS would be really important to get your input on that question

**Comment by mcollina** [comment]
I'll ship a new release of v3 whenever I have the chance.
