### ISSUE TITLE
How do I use Https through typescript?

### ISSUE THREAD

**Issue by shuaqq2004** [fastify/fastify#378]
https://github.com/fastify/fastify/issues/355

const opt: fastify.ServerOptions = {
    https: false  --> boolean
};

const server: fastify.FastifyInstance = fastify(opt);

js:
const fastify = require('fastify')({
    https: {
      key: fs.readFileSync(path.join(__dirname, 'file.key')),
      cert: fs.readFileSync(path.join(__dirname, 'file.cert'))
    }
  })

**Comment by delvedor** [comment]
cc @evanshortiss

**Comment by evanshortiss** [comment]
@shuaqq2004 @delvedor PR #383 should solve this with the updated typings
