### ISSUE TITLE
Reply's `content-type` header value suffix stripped when charset is omitted

### ISSUE THREAD

**Issue by JakobJingleheimer** [fastify/fastify#3788]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

17.7.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2

### Description

In the example here, fastify strips `; version=2` (and appends `; charset=utf-8`) when `reply.send()` is called.

### Steps to Reproduce

**Bad**:
```js
reply.header(
  'Content-Type',
  `application/vnd.example.com+json; version=2`,
);

reply.send({ foo: 'bar' });

fastify.log.info(reply.getHeaders());
// content-type: application/vnd.example.com+json; charset=utf-8
```

**Good**:

```js
reply.header(
  'Content-Type',
  `application/vnd.example.com+json; version=2; charset=utf-8`,
);

reply.send({ foo: 'bar' });

fastify.log.info(reply.getHeaders());
// content-type: application/vnd.example.com+json; version=2; charset=utf-8
```

### Expected Behavior

The existing suffix should not be stripped and `; charset=utf-8` should be appended after.

**Comment by xtx1130** [comment]
Seems like this pr https://github.com/fastify/fastify/pull/2315 has a problem, I will take a look

**Comment by JakobJingleheimer** [comment]
Wow! Thanks for the fast turnaround!
