### ISSUE TITLE
Remove server.unref from tests

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3790]
It would be good to remove this monkey patch:

https://github.com/fastify/fastify/blob/2afc0d757eff238ae5ac0bd91033fe43a83d18d9/lib/server.js#L139-L147

To do this, we need to remove all the `fastify.server.unref()` calls from the `test/` folder and replace it within:

```
t.teardown(() => { fastify.close() })
```

**Comment by climba03003** [comment]
Even if we do not use it inside the `test`. This monkey patching is needed.
Because the user may call `.unref` themself and expect all the server should be `unref`.

**Comment by Eomm** [comment]
You are right, but I would clean the tests in any case (minus one for the coverage)

**Comment by jsumners** [comment]
I was going to say the same thing as @climba03003. We must expose a functioning `unref`.

**Comment by climba03003** [comment]
> Is anyone working on this issue? If not I'd like to give it a shot myself, but I'd need a little guidance since it'd be my first contribution to the project

AFAIK, no one is working on this now. You can send a draft Pull Request for advise.

**Comment by xtx1130** [comment]
> Is anyone working on this issue? If not I'd like to give it a shot myself, but I'd need a little guidance since it'd be my first contribution to the project

You can follow https://github.com/fastify/fastify/blob/main/docs/Guides/Contributing.md this contribution guide to send a pr
