### ISSUE TITLE
having more than 2 response types breaks the TypeProvider 

### ISSUE THREAD

**Issue by turkerdev** [fastify/fastify#3791]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0-alpha.2

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Having more than 2 response types breaks type inference.

https://user-images.githubusercontent.com/48413508/159679002-2aeb02c5-15e9-45f8-afe4-cba9d2acc8a6.mp4

### Steps to Reproduce

https://codesandbox.io/s/reverent-lamport-lgtuz0?file=/index.ts:425-448

**Comment by RafaelGSS** [comment]
I don't see any issue in the video. You are basically sending `"45"` (not the `reply` object) and when you remove the type `string` as response it should throw.

An important point here is that TypeProvider **is not capable** to define response types based on the status code, it means if you define a couple of responses to different status codes, it will behave like:

```ts
schema: {
  response: {
    200: number,
    500: string
  }
}
```
```ts
response: string | number 
```

instead of

```ts
response200: number
response500: string
```

---

I think we have discussed it in some issue @sinclairzx81, do you remember?

**Comment by turkerdev** [comment]
Oh, I see. I thought it could infer according to statusCode. My bad.

**Comment by sinclairzx81** [comment]
@turkerdev Hi, just ran your code locally and everything seems in order. Just keep in mind that currently TypeProviders take a union of all possible status codes, but do not currently narrow based on the status code. (Although this may be enabled at some point in the future)

Also, just be mindful that you won't be able to directly assign Zod schemas to Fastify without first mapping them to JSON Schema. There might be a couple of libraries out there to handle this.

If you can get Zod working over TypeProviders, you should consider submitting this as a Type Provider plugin! Would be a cool addition to the existing providers :)

**Comment by turkerdev** [comment]
@sinclairzx81 I'm not familiar with creating packages and maintaining them ¯\_(ツ)_/¯, but here I did create it.
https://www.npmjs.com/package/fastify-type-provider-zod

**Comment by sinclairzx81** [comment]
@turkerdev Hey, this is awesome! Excellent work!

@RafaelGSS Is there a process for adding remotely authored community plugins to Fastify? I think having a Zod Type Provider would be pretty nice option for a lot of existing users who do preference Zod. Could also potentially include additional type provider packages for `RunTypes` and `io-ts` as well if overriding the validation and serialization is as straight forward as.... 

```typescript
fastify.setValidatorCompiler(validatorCompiler); // where the validation and serialization compilers
fastify.setSerializerCompiler(serializerCompiler); // are exported on the TypeProvider package.
```
I think @turkerdev 's implementation there might service as a good model integrating some of these other type mappers.

**Comment by RafaelGSS** [comment]
You can create a PR to add this plugin to our community ecosystem, this is totally acceptable.
