### ISSUE TITLE
docs: guide with a list of open source projects that use fastify

### ISSUE THREAD

**Issue by vitoladev** [fastify/fastify#3797]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

it would be great to have a guide on the documentation with a list of open source projects that use fastify as their web framework, such as the ecosystem guide has a list of plugins maintained by the community and the fastify team.

open source projects using fastify that i found searching on GitHub:
[Hospital Run](https://github.com/HospitalRun/hospitalrun-server)
[Roomler.Live - Live video conferencing & collaboration tool using WebRTC (Janus Gateway)](https://github.com/gjovanov/roomler)
[Daily.dev API](https://github.com/dailydotdev/daily-api)

**Comment by Eomm** [comment]
We have such a list here:
https://github.com/fastify/website/blob/master/src/website/data/organisations.yml

But it is up to the organization to send a PR

**Comment by vitoladev** [comment]
In this case, I thought about open source projects themselves, not organizations or enterprise users, I think it would be a good showcase of projects that rely on fastify.
an example of this kind of section is the [docusaurus showcase](https://docusaurus.io/showcase) with open source projects that rely on their project to build documentation, such as jest, react native, ionic, etc.
