### ISSUE TITLE
[v4] Clarifcation on correct way to call listen

### ISSUE THREAD

**Issue by michael-melodyarc** [fastify/fastify#3800]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I know v4 is still prerelease, so if you don't want v4-related issues in the main tracker, just let me know where is the best place to put them.

It looks like some of the docs are still in the process of being updated, but I was trying to switch over an app to use v4 and was hitting a bit of a snag on the initial listen call.  Despite seemingly still supporting the old way, albeit deprecated now, I was getting errors since listen was returning `undefined` instead of a promise.

My existing/working code was:

```js
app.listen(env.PORT, '0.0.0.0').catch((err) => app.log.error(err));
```

After upgrading to v4, I was getting this error:

```
app.listen(env.PORT, '0.0.0.0').catch((err) => app.log.error(err));
                               ^
TypeError: Cannot read properties of undefined (reading 'catch')
```

I tried using the new options bag instead:

```js
app
  .listen({ port: env.PORT, host: '0.0.0.0' })
  .catch((err) => app.log.error(err));
```

But received the same error.

I then ultimately switched to a callback:

```js
app.listen({ port: env.PORT, host: '0.0.0.0' }, (err) => {
  if (err) app.log.error(err);
});
```

Which did work as expected, but I believe the first two should also work based on the docs and the types file.  Is this a bug, or am I just doing something wrong?

Thanks!

**Comment by mcollina** [comment]
Thanks for catching this! Keep reporting v4 bugs!

**Comment by mcollina** [comment]
@jsumners could you take a look?

**Comment by xtx1130** [comment]
The same question as https://github.com/fastify/fastify/issues/3783. I have tried master branch, and it is okay for this case. I think we can publish a new alpha version to resolve this problem

**Comment by jsumners** [comment]
Right. This was fixed but not published as a new alpha until today.

**Comment by michael-melodyarc** [comment]
Ah, awesome, I searched but didn't have that exact magical incantation of words, so I never found that previous issue.  On a side note before this gets closed.  Is the recommended / best practice way using the options bag and callback? Or does callback/promise not matter / doesn't have a recommended way?
