### ISSUE TITLE
Fastify project example

### ISSUE THREAD

**Issue by zekth** [fastify/fastify#3802]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Write an example project to be included in the docs with explanations on the different choices. From dev environment to deployment.

### Motivation

Lot of people seem to request some guidance on how to architecture / debug a fastify project. As it's a non opinionated framework we won't enforce the user to use a specific architecture; however fastify team can provide some guidances.

Same issue can be duplicated as a TypeScript environment

**Comment by simoneb** [comment]
Listing a couple of resources that I'm aware of, in case we want to consider reusing or extending those instead of coming up with something new altogether:

- https://github.com/fastify/fastify-cli/ has a boilerplate to start from
- https://github.com/nearform/mrm-preset-nearform/tree/master/fastify-app - at NearForm we have built our own (very slim) boilerplate to kickstart Fastify apps, inspiring from fastify-cli
- https://github.com/delvedor/fastify-example is a much richer example app

**Comment by mcollina** [comment]
We should also document them on the website.

**Comment by franciscolourenco** [comment]
I was just browsing https://codebase.show/projects/realworld and realized there is no fastify example. Afaik it is the most popular "TodoMVC" version at the moment?

**Comment by tanvirraj** [comment]
this project [covid-green-backend-api](https://github.com/covidgreen/covid-green-backend-api)
also very good to be an example written by nearform team members

**Comment by Shyam-Chen** [comment]
I created a TodoMVC-like example [here](https://github.com/Shyam-Chen/Fastify-Starter/tree/main/src/modules/todos).

**Comment by avanelli** [comment]
> 


> I was just browsing https://codebase.show/projects/realworld and realized there is no fastify example. Afaik it is the most popular "TodoMVC" version at the moment?


I created this RealWorld implementation using Fastify: [Fastify + Knex.js - Realworld Example App](https://github.com/avanelli/fastify-realworld-example-app)  

The project has been submitted today for approval.
Any review, comment or contribution will be more than welcome! 
(Raising test coverage is in progress)

**Comment by avanelli** [comment]
> 

The project has been accepted and is now officially listed in [RealWorld Backends](https://codebase.show/projects/realworld?category=backend&language=javascript) 👍 

Please help us improve it with suggestions and contributions!

**Comment by lord007tn** [comment]
I could help with this 

I've been working for about a month now and I face many problems using fastify and typescript.

it would be nice to provide a full working example of using fastify with typescript and the file structure/architecture in a production-ready app.

also, why not have a section on the website ` built with fastify ` to showcase real-world open-source projects? It will boost people's willingness to learn and add a solid foundation of trust to the framework.

**Comment by climba03003** [comment]
I think it is what https://github.com/fastify/demo want to archive, so closing.
