### ISSUE TITLE
Allow find-my-way allowUnsafeRegex option within fastify option

### ISSUE THREAD

**Issue by BCsabaEngine** [fastify/fastify#3805]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to use allowUnsafeRegex in the internal router (drill down to findmyway). I understand the slow down effect when use it. But it is a developer choose. I think.

### Motivation

I cannot setup internal router with fastify options.

### Example

```
    const server = fastify({
        genReqId: () => nanoid(),
-->     allowUnsafeRegex: true,
        bodyLimit: 2 * 1024 * 1024,
        ignoreTrailingSlash: true,
    });
```

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by BCsabaEngine** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Should I work on https://github.com/fastify/fastify/tree/v3.x branch? I see your mention, but I think the bigger options refactor will be in v4.x.

**Comment by BCsabaEngine** [comment]
> Remember to add unit tests.

And don't forget Server.md + examples too :)

**Comment by jsumners** [comment]
To start with, a simple implementation of this specific feature should be added to the current `main` branch. That feature should be backported automatically to the `v3.x` branch. The deprecation issue would be separate work.

**Comment by BCsabaEngine** [comment]
https://github.com/fastify/fastify/pull/3817
