### ISSUE TITLE
Can't correctly set `ByteString` headers with non-ASCII chars

### ISSUE THREAD

**Issue by AlttiRi** [fastify/fastify#3808]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

17.5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I can't correctly set `ByteString` (`BinaryString`) headers with non-ASCII chars since `fastify` additionally converts headers to `ByteString`.

It makes no sense, since `headers()` method already expect a `ByteString`.

If I try to put a `String` that is not `ByteString` (for example, `{"x-header": "Rock & roll 音楽 ('🎵🎶').txt"})` it will fail with `"Invalid character in header content [\"x-header\"]"` error.

If I put an ASCII string, it works, of course. But, in fact, the conversion is not need, since `bStrToStr(ascii) === ascii`.

https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary
https://webidl.spec.whatwg.org/#idl-ByteString

### Steps to Reproduce

Here is fastify server (http://127.0.0.1:3000):
```js
import fastify from "fastify";
const server = fastify({logger: true});


const name = "Rock & roll 音楽 ('🎵🎶').txt";
const autoDL = false;
const RFC5987 = false;

const RFC5987Str = RFC5987 ? `; filename*=UTF-8''${encodeURIComponent(name)}` : "";
const type = autoDL ? "attachment" : "inline";
const header = `${type}; filename="${name}"${RFC5987Str}`;
const bHeader = str2BStr(header);

server.get("/", async (request ,reply) => {
    reply.headers({
        "Content-Disposition": bHeader,
    });
    reply.send("🎵🎶🎵🎶🎵🎶");
});

const start = async () => {
    try {
        await server.listen(3000, "127.0.0.1");
    } catch (err) {
        server.log.error(err);
        process.exit(1);
    }
};
void start();


function str2BStr(string) {
    return arrayBufferToBinaryString(new TextEncoder().encode(string));
}
function arrayBufferToBinaryString(arrayBuffer) {
    return arrayBuffer.reduce((accumulator, byte) => accumulator + String.fromCharCode(byte), "");
}
function bSrt2Str(bString) {
    return new TextDecoder().decode(binaryStringToArrayBuffer(bString));
}
function binaryStringToArrayBuffer(binaryString) {
    const u8Array = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        u8Array[i] = binaryString.charCodeAt(i);
    }
    return u8Array;
}
```

Run in the console:
```js
function bSrt2Str(bString) {
    return new TextDecoder().decode(binaryStringToArrayBuffer(bString));
}
function binaryStringToArrayBuffer(binaryString) {
    const u8Array = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        u8Array[i] = binaryString.charCodeAt(i);
    }
    return u8Array;
}
console.log(bSrt2Str((await fetch("http://127.0.0.1:3000/")).headers.get("Content-Disposition")));
console.log(bSrt2Str(bSrt2Str((await fetch("http://127.0.0.1:3000/")).headers.get("Content-Disposition"))));
```
I need to call `bSrt2Str` **twice**:

![image](https://user-images.githubusercontent.com/16310547/161249167-8be4813e-5367-45ce-80fd-66d4682ff6a6.png)

Also set `autoDL` to `true` and restart the server, the downloaded file will have the wrong name.

### Expected Behavior

Here is a server made with `http` (http://localhost:8000/):

```js
import http from "http";

const host = "localhost";
const port = 8000;
const server = http.createServer(requestListener);
server.listen(port, host, () => {
    console.log(`Server is running on http://${host}:${port}`);
});

const name = "Rock & roll 音楽 ('🎵🎶').txt";
const autoDL = false;
const RFC5987 = false;

const RFC5987Str = RFC5987 ? `; filename*=UTF-8''${encodeURIComponent(name)}` : "";
const type = autoDL ? "attachment" : "inline";
const header = `${type}; filename="${name}"${RFC5987Str}`;
const bHeader = str2BStr(header);


function requestListener(req, res) {
    res.setHeader("Content-Disposition", bHeader);
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.writeHead(200);
    res.end("🎵🎶🎵🎶🎵🎶");
}


// --- Util ---
function str2BStr(string) {
    return arrayBufferToBinaryString(new TextEncoder().encode(string));
}
function bSrt2Str(bString) {
    return new TextDecoder().decode(binaryStringToArrayBuffer(bString));
}
function arrayBufferToBinaryString(arrayBuffer) {
    return arrayBuffer.reduce((accumulator, byte) => accumulator + String.fromCharCode(byte), "");
}
function binaryStringToArrayBuffer(binaryString) {
    const u8Array = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        u8Array[i] = binaryString.charCodeAt(i);
    }
    return u8Array;
}
```

The header is the correct `ByteString`. Only one `bSrt2Str` is needed:
```js
console.log(bSrt2Str((await fetch("http://localhost:8000/")).headers.get("Content-Disposition")));
```
![image](https://user-images.githubusercontent.com/16310547/161249669-59748312-15fc-4d75-ab4b-8310e3766059.png)

Also the file is downloaded with the correct name, if you set `autoDL` to `true`.

**Comment by AlttiRi** [comment]
The live example of the header like that I want to do with `fastify`:
https://xenforo.com/community/attachments/_圖片_🖼_image_100-loading-perf-png.266674/?hash=b66fd2461d70a0c017941f3bcf7b5e4a

The related issues:
https://github.com/nodejs/undici/issues/1317
https://github.com/jshttp/content-disposition/issues/43

**Comment by AlttiRi** [comment]
Yeah, it looks that fastify writes the header string as is in [`response.writeHead`](https://nodejs.org/api/http.html#responsewriteheadstatuscode-statusmessage-headers).

The reason is `Transfer-Encoding: chunked`.

`http` adds it, `fastify` does not.

Well, that was unexpectedly for me, that it will add the less count of headers that `http` module which it uses.

Hm, however [it](https://xenforo.com/community/attachments/_圖片_🖼_image_100-loading-perf-png.266674/?hash=b66fd2461d70a0c017941f3bcf7b5e4a) does not have that header.

**Comment by xtx1130** [comment]
@AlttiRi Did you submit a issue to nodejs?

**Comment by AlttiRi** [comment]
I will do today.

**Comment by xtx1130** [comment]
@AlttiRi Thanks for you report, and I hope you can link nodejs issue to this one. I'm interested in this too.

**Comment by AlttiRi** [comment]
https://github.com/nodejs/node/issues/42579

**Comment by ShogunPanda** [comment]
Please see my comment on the issue above, it explain why it happens and how to solve it.
