### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by LANCENET** [fastify/fastify#3818]
## 👮 [Responsible Disclosure](https://github.com/nodejs/security-wg/blob/master/processes/responsible_disclosure_template.md)

Do not open issues that might have security implications. It is critical that security related issues
are reported privately so we have time to address them before they become public knowledge.

Individuals who find potential vulnerabilities in a package are invited
to complete a vulnerability report on the dedicated HackerOne organization:

[https://hackerone.com/nodejs-ecosystem](https://hackerone.com/nodejs-ecosystem)

Vulnerabilities can also be reported by emailing security-ecosystem@nodejs.org or Fastify core members: 

- [Matteo Collina](mailto:matteo.collina@gmail.com)
- [Tomas Della Vedova](https://twitter.com/delvedor)

**Comment by climba03003** [comment]
I think the template should be updated or removed.
https://github.com/fastify/.github/issues/16
