### ISSUE TITLE
Can't use serve-static middleware

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#382]
Hi, I just want to test `serve-static` package which exports an express middleware to serve static files but I don't get it to work. Do we have incompatibilities with the express middlewares?

```js
const path = require("path")
const fastify = require("fastify")();
const serveStatic = require('serve-static')

fastify.use('/static', serveStatic("/static"))

fastify.listen(8080, err => {
  if (err) throw err;
  console.log(`Server listening on ${fastify.server.address().port}`)
})

```

- `http://localhost:8080/static` returns 404
- `http://localhost:8080/static/test.js` returns 404

**Comment by SerayaEryn** [comment]
I had the same problem. Passing the absolute path of the "/static" folder to `serveStatic()` solves the problem:
```js
const path = require("path")
const fastify = require("fastify")();
const serveStatic = require('serve-static')

fastify.use('/static', serveStatic(path.join(__dirname, "/static")))

fastify.listen(8080, err => {
  if (err) throw err;
  console.log(`Server listening on ${fastify.server.address().port}`)
})
```

**Comment by allevo** [comment]
Hi!
thanks for checking out `fastify`!

[`serve-static`](https://www.npmjs.com/package/serve-static#servestaticroot-options) accepts the directory you want to serve.

`/static` means that there's a folder on your root `/` that you want to serve. Instead `path.join(__dirname, "/static")` means that the folder you want to serve is located near your file.

**Comment by StarpTech** [comment]
thanks, now clear for me but I will create a PR to update the docs.
https://github.com/fastify/fastify/blob/master/docs/Middlewares.md
