### ISSUE TITLE
Allow setting of log level for metrics like "request completed"

### ISSUE THREAD

**Issue by jcollum-nutrien** [fastify/fastify#3834]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

https://github.com/fastify/fastify/blob/edbb82035c6e121cc835d6e654a4e88434296af0/lib/reply.js#L645

This is hardcoded at "info" level. Personally I think those kind of things belong at the trace level since I will only care about those values in production some of the time. 

Simply adding a `metricsLogLevel` setting for the logger would do it. 

### Motivation

Logging metrics is more for tracing than info. 

### Example

```
  reply.log[settings.metricsLogLevel]({
    res: reply,
    responseTime
  }, 'request completed')
```
For instance. Pseudocodish. 

Seems like an easy add, I can do a PR if the team is open to that.

**Comment by mcollina** [comment]
There is already an option to disable them all. You can do [`disableRequestLogging`](https://www.fastify.io/docs/latest/Reference/Server/#disablerequestlogging)
