### ISSUE TITLE
Using setErrorHandler from a plugin doesn't work

### ISSUE THREAD

**Issue by sazzer** [fastify/fastify#3839]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Plugin version

N/A

### Node.js version

17.9.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Description

I'm attempting to write a plugin to be able to throw errors and render them as RFC-7807 Problem Details.

However, I've found that calling `setErrorHandler` from within a plugin doesn't seem to work.

i.e. this works:
```
    const server = fastify({
      logger: true
    });

    server.setErrorHandler(handleError);
```

And this doesn't work:

```
    const server = fastify({
      logger: true
    });

    server.register(async function (fastify) {
      fastify.setErrorHandler(handleError);
    });
```

### Steps to Reproduce

```
import fastify, { FastifyReply, FastifyRequest } from 'fastify';

async function handleError<T>(error: T, request: FastifyRequest, reply: FastifyReply) {
  reply.code(409);
  reply.header('content-type', 'appliction/problem+json');

  return {
    ok: false
  };
}

const server = fastify({
  logger: true
});

server.register(async function (fastify) {
  fastify.setErrorHandler(handleError);
});

server.route({
  method: 'GET',
  url: '/',
  handler: async function () {
    throw new Error('Oops');
  }
});

server.listen(8000);
```

### Expected Behavior

The error handler gets called and sends back the desired response.

**Comment by sazzer** [comment]
Note that the following things don't seem to make any difference:
* Whether the route handler is sync or async
* Whether the plugin registration function is sync or async
* Whether the error handler itself is sync or async

The only thing I've found that makes a difference is whether the call to `setErrorHandler` is directly on the server or within a call to `register()`.

**Comment by mcollina** [comment]
Read up on https://www.fastify.io/docs/latest/Reference/Encapsulation/#encapsulation.
