### ISSUE TITLE
Performance comparison: Fastify vs express

### ISSUE THREAD

**Issue by sanzhardanybayev** [fastify/fastify#3841]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi everyone! 

Recently I had a hard choice picking up the Node.JS framework for a small backend app that issues JWT tokens and sends fetch requests to Google Cloud Platform. 

Initially I chose express.js. But later on I decided to refactor it with **fastify**. 

Few weeks later I decided to do load testing with **Node.JS** **clustering** on. 

Fastify is well known for its performance.  So I expected it to perform better than express.js.

I was so surprised when I found out that **express.js** significantly outruns **fastify** in load testing with k6. 

Testing environment: 
**1. Node.JS 17.9.0**

<img width="847" alt="image" src="https://user-images.githubusercontent.com/13291424/163943217-2b5f9c5a-b8b4-4ab3-af74-7be11817392c.png">

Are there any reasons for that? How come express.js is almost twice as fast?

**Comment by zekth** [comment]
Without any description of the code nor your testing script we can't answer your question.

**Comment by sanzhardanybayev** [comment]
@zekth yeah, sure. I'll setup some time to provide it.

**Comment by RafaelGSS** [comment]
For reference, see https://github.com/fastify/benchmarks

**Comment by PazzaVlad** [comment]
If you use a database or even somehow small business logic, you won't notice any difference in performance between node.js frameworks. In a real-world app, framework itself will use like 0.1% of execution time.
Check out maybe you use some sort of caching in the express version etc.

**Comment by sanzhardanybayev** [comment]
@PazzaVlad I see. Yeah, there's just and HTTP call.  The logic is identical for both **express.js** and **fastify**.   I'm also inclined towards not having enough business logic to make full comparison.  But still, the performance difference is pretty significant even for such a small business logic.  

I'll try to setup some time and provide example code.

**Comment by budarin** [comment]
with perhaps even equal speed of both frameworks, fastify benefits from a more correct code architecture

piling up middleware turns the Express code into spaghetti and it becomes unpredictable

**Comment by avin-kavish** [comment]
yeah, honestly, I came for the performance, but stayed for the plugin, hooks, validation and other features of the framework. Express doesn't have any of that.
