### ISSUE TITLE
Can not register a wildcard (catch-all) route handler

### ISSUE THREAD

**Issue by sher** [fastify/fastify#3845]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2.1

### Description

```js
fastify.all('/*', handler);
```
When registering a wildcard (catch-all) route below assertion error is thrown.
```sh
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/*' with constraints '{}'
```

### Steps to Reproduce

```js
fastify.all('/*', handler);
```

**Comment by mcollina** [comment]
I'm pretty confident this is heavily tested in our suite, so maybe are you specifying some config or other routes? Anyway, could you include an example we can run?

**Comment by sher** [comment]
```ts
import 'make-promises-safe';
import path from 'path';
import fastify from 'fastify';
import statics from 'fastify-static';
import type { FastifyInstance } from 'fastify';

init().then(start);

async function init() {
  const server = fastify({ logger: true });

  await server.register(statics, {
    root: path.join(process.cwd(), 'public', 'assets'),
    prefix: '/assets',
  });

  await server.register(statics, {
    root: path.join(process.cwd(), 'public'),
    prefix: '/',
  });

  server.all('/*', async function (request, reply) {
    return reply.send({ ok: true });
  });

  return server;
}

async function start(server: FastifyInstance) {
  const port = process.env.PORT || 3000;
  await server.listen(port);
}
```

@mcollina I just realised, after submitting an issue, that `fastify-static` declaration `prefix` was causing the assertion error.

**Comment by climba03003** [comment]
Yes, the problem is [`fastify-static`](https://github.com/fastify/fastify-static#wildcard) register `${prefix}*` by default. Which also means that the below code is registering `/*`.
 ```js
await server.register(statics, {
  root: path.join(process.cwd(), 'public'),
  prefix: '/',
});
```
