### ISSUE TITLE
Empty fastify plugin versions released?

### ISSUE THREAD

**Issue by mil7** [fastify/fastify#3854]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi there,
yesterday evening Renovate proposed few minor version updates on some fastify plugins. From Github's view these versions do not exist. For example version [3.13.0 of fastify-autoload](https://github.com/fastify/fastify-autoload/compare/v3.12.0...b3da246e2eb1f71aaebaeb5f24c6876dabf0d3a8).

Do we have to wonder? Or just ignore these proposals?

I undestand that [preparations for v4 of Fastify](https://github.com/fastify/fastify/issues/3482#issuecomment-1046916608) are ongoing and that the [plugin names have been changed](https://github.com/fastify/fastify/issues/3733) in the last 24 hours. For me it looks like somebody accidently hit the wrong button. No harm done. 💐

**Comment by climba03003** [comment]
> 
> Do we have to wonder? Or just ignore these proposals?

I think `renovate` is trying to point to `v3.13.0`, but the deprecated version is not inside the git history.
So, there is no tag for that version.

I recommend to change the package name.

**Comment by jsumners** [comment]
> I undestand that [preparations for v4 of Fastify](https://github.com/fastify/fastify/issues/3482#issuecomment-1046916608) are ongoing and that the [plugin names have been changed](https://github.com/fastify/fastify/issues/3733) in the last 24 hours. For me it looks like somebody accidently hit the wrong button. No harm done. 💐

This is an artifact of the module renaming. It is detailed in the issue you linked. It is also outlined in https://github.com/fastify/fastify-autoload/pull/233
