### ISSUE TITLE
Plugin Registration Complained to Version

### ISSUE THREAD

**Issue by ekoeryanto** [fastify/fastify#3865]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1

### Description

```bash
expected '>=3' fastify version, '4.0.0-rc.1' is installed
```

### Steps to Reproduce
```ts
import fastify from 'fastify';
import Sensible from '@fastify/sensible';

const app = fastify()

app.register(Sensible)

app.listen({port: 1233})
```
### Expected Behavior

Fastify v4 accept plugin defined with version >=3.x

**Comment by climba03003** [comment]
It is expected behavior.

Check [`semver`](https://github.com/npm/node-semver#prerelease-tags)
> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.

**Comment by ekoeryanto** [comment]
Ah, i meant when we are in RC, mmm... it is better to accept RC version when plugin is defined with >=3. and revert back when it stable so we can test it with the plugins

**Comment by climba03003** [comment]
> Ah, i meant when we are in RC, mmm... it is better to accept RC version when plugin is defined with >=3. and revert back when it stable so we can test it with the plugins

`semver` comparison is complicated and we rely on `semver` libaray. From what you means, we need either clone `semver` and do the mutation or just completely disable the version check.

If you need to test with the `pre-release`, you may alter the `meta` fields.
```js
// override.js
function overidePluginMeta(plugin, version = '>= 4.0.0-rc.0') {
  if(plugin[Symbol.for('plugin-meta')]) {
    plugin[Symbol.for('plugin-meta')] = { ...plugin[Symbol.for('plugin-meta')], fastify: version }
  }
  return plugin
}

module.exports = { overidePluginMeta }

// commonjs.js
const { overidePluginMeta } = require('./override.js')
const Sensible = overrideMeta(require('@fastify/sensible'))

// esm.js
import { overridePluginMeta } from './override.js'
import RawSensible from '@fastify/sensible'
const Sensible = overridePluginMeta(RawSensible)
```

**Comment by NOT-HAL9000** [comment]
> From what you means, we need either clone `semver` and do the mutation or just completely disable the version check.

The release candidate should be included imo. Why not just enable the prerelease option?

```javascript
var semver = require("semver@7.3.2")

semver.satisfies('4.0.0-rc.1', '>=3.x') // false
semver.satisfies('4.0.0-rc.1', '>=3.x', { includePrerelease: true } ) //true
```
https://runkit.com/embed/a4kbuscwfrgy 

I just changed this,

https://github.com/fastify/fastify/blob/62a8fc9fa34711d78c7aaa53c7128e880b7016f8/lib/pluginUtils.js#L100-L109

to this. It works as expected. 

```javascript
function checkVersion (fn) {
  const meta = getMeta(fn)
  if (!meta) return

  const requiredVersion = meta.fastify

  // INCLUDE PRERELEASE OPTION
  if (requiredVersion && !semver.satisfies(this.version, requiredVersion, { includePrerelease: true})) {
    throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
  }
}
```
Is this something that can be reopened and changed asap? I would like to continue testing v4 with existing plugins.

**Comment by jsumners** [comment]
We will be starting the RC phase soon. At that point, we will this out.

**Comment by NOT-HAL9000** [comment]
Great news. Do you have an ETA for the update to RC?

**Comment by climba03003** [comment]
> Why not just enable the prerelease option on the semver `satisfies` check? It will cover all plugins, not just sensible. All release candidate versions should be able to use all prior plugins (given that they support >= versions) imo.
> 
> ```js
> var semver = require("semver@7.3.2") // current fastify semver version
> 
> semver.satisfies('4.0.0-rc.1', '>=3.x') // returns false 
> semver.satisfies('4.0.0-rc.1', '>=3.x', { includePrerelease: true } ) // returns true 
> ```
>

Good, I missed this flag from reading the document.
