### ISSUE TITLE
Add option to encode URL before inserting

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fastify#3867]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

A new boolean option for the `fastify.route` method that allows encoding URL with encodeURI function before inserting. Default: false.

### Motivation

The find-my-way library has a path decoding error. In short, find-my-way cannot parse the path correctly if there are encoded characters in the static and parametric parts of the path https://github.com/delvedor/find-my-way/issues/234. The only way to fix it, that I found is to encode a URL before inserting and matching encoded URLs. The path-to-regexp library does it in the same way. There is a PR in the find-my-way, that fixes it. It adds a new `encode` option for the find-my-way `on` method. https://github.com/delvedor/find-my-way/pull/253. This fix is a breaking change.

If you have other ideas on how to add this fix to the fastify, please share, I don't insist on my suggestion. Just want to raise this problem here.

### Example

```js
  fastify.route({
    method: 'GET',
    url: '/',
    encode: true,
    handler: (req, reply) => {
      reply.send({ hello: 'world' })
    }
  })
```

**Comment by climba03003** [comment]
I would leave it as a global option only.
Although it is more flexible for the developer to customize the application behavior. 
It allows mis-use of option or lead to any consistence behavior if they can opt-in / opt-out for each route.

**Comment by jsumners** [comment]
@ivan-tymoshenko why did you close the issue?

**Comment by ivan-tymoshenko** [comment]
@jsumners The https://github.com/delvedor/find-my-way/pull/253 was closed in favor of https://github.com/delvedor/find-my-way/pull/282, which fix https://github.com/delvedor/find-my-way/issues/234 without the need to add the `encode` option.

**Comment by KaKi87** [comment]
Hi,
It would still be nice to have this feature for schema validators that only validate encoded URIs.
Thanks
