### ISSUE TITLE
Docs contain app.use example

### ISSUE THREAD

**Issue by greebowarrior** [fastify/fastify#3869]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue / Observation 

If I’m understanding it correctly, `app.use()` is being removed in v4.
If so, the docs on main branch still contain an example with `app.use()` on the Middleware page. Presumably that page may need rewriting as well?

**Comment by climba03003** [comment]
The document is correct. The example is the use-case when you install either `@fastify/express` or `middie`.

**Comment by greebowarrior** [comment]
Ahhh, okay, so I wasn't understanding it correctly 😂
