### ISSUE TITLE
Add path url to Request object

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#387]
as titled, I'd like to have `path` in the fastify Request object
```js
fastify.get('/foo', function (req, reply) {
  reply.send({path: req.path}) // <--- this is '/foo'
})
```

**Comment by mcollina** [comment]
👍  PR?

**Comment by allevo** [comment]
I'll do it :+1:

**Comment by jsumners** [comment]
I think the path and all such components (query string, anchor) should be available as properties of the object. See #393 for an example of why.

**Comment by wong2** [comment]
agreed

**Comment by delvedor** [comment]
I think that this would fit nicely in a plugin, a decorator that adds to the request `url`, `querystrinng` and `anchor` and an hook to get that data.

Fastify is built to be super lightweight and extensible via its plugin system, in core we should support all the basic functionalities and the apis for the plugin system.

**Comment by jsumners** [comment]
But these are core pieces of information that a plugin would want to use.

**Comment by delvedor** [comment]
If a plugin needs this data, it can register the `fastify-url-data` plugin itself ;)
Again, I don't think this should be a core provided thing.

But since there are different opinions, we can vote!
Put a 👍  if you want this feature in core, put a 👎  if you want this feature as external plugin *(in this comment)*.

cc @mcollina @allevo

**Comment by delvedor** [comment]
Let's not forget that add this feature in core would mean run some code to extract the "clean" `url`, the `anchor` and the `querystring` and add them to the `request` object for every request, even if you do not need that data.

IMHO everything that is not mandatory should be supported as plugin.

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L14

At least part of this information is already being parsed on every request. The suggestion is to go ahead and cache that data upon the first parsing of it. By shifting it into a plugin, this information will be parsed _multiple_ times per request.

**Comment by mcollina** [comment]
I think we are already doing most of this for every request anyway (url in find-my-way). Parsing the anchor or the querystring can be done via accessors on first use.
We might have to refactor find-my-way to expose that data and avoid doing this twice.

**Comment by allevo** [comment]
I'm not convinced at all.

If the developers have not had that feature until now maybe it is not needed to keep this feature in the core

And a "communication/protocol" between `find-my-way` and `fastify` is dangerous.

**Comment by mcollina** [comment]
So, `path` as another problem: plugin prefixes. Express does a lot of work in rewrite those for each prefixes.
Maybe we should not do them at all.

**Comment by jsumners** [comment]
I would say provide the path as it is configured for the handler. For example,

```js
const routes = function (instance, opts, next) {
  instance.get('/bar', (req, reply) => {
    reply.send(req.path) // '=> '/bar'
  })
}

fastify.register(routes, {prefix: '/foo'})
```

**Comment by mcollina** [comment]
@jsumners that is a very expensive thing to do, I would avoid doing it for every request, bur rather do it on-demand with an accessor.

**Comment by allevo** [comment]
From `fastify` point of view, we don't need that feature: `fastify` engine (`avvio`, `find-my-way`, etc...) doesn't need this feature in order to work. So there's no reason to add it here.

I'm 👍  to add this feature on-demand and in a plugin.

I'd like to keep `fastify` as light as possible without features that aren't needed for the engine.

**Comment by mcollina** [comment]
Closing this for now, but we should re-evaluate it in the future.

**Comment by jsumners** [comment]
Does this solve the issue (and issue #388)? https://github.com/fastify/fastify-url-data

**Comment by wong2** [comment]
@jsumners looks nice, please release it

**Comment by jsumners** [comment]
It is now published under my npm profile. It'll get moved to the org when possible.

**Comment by moeinrahimi** [comment]
won't req.raw.url help?

**Comment by mcollina** [comment]
sure, this is a3y old issue, a lot has changed
