### ISSUE TITLE
Fastify close method should postpone closing keep-alive connections

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#3870]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

`Fastify` closes `keep-alive` connections forcibly immediately after calling `server.close`, although at this time these connections may not have time to complete their requests yet.
It is necessary to forcibly close incomplete requests and `keep-alive` connections after some configurable `shutdownTimeout`.

### Motivation

Some slow keep-alive connections will be terminated immediately forcibly

### Example

```js
  // cache the closing value, since we are checking it in an hot path
  avvio.once('preReady', () => {
    fastify.onClose((instance, done) => {
      fastify[kState].closing = true

      router.closeRoutes()

      if (fastify[kState].listening) {
        // No new TCP connections are accepted
        instance.server.close(done);

// ->> wrap code into setTimeot
        setTimeout(() => {
            for (const conn of fastify[kKeepAliveConnections]) {
                // We must invoke the destroy method instead of merely unreffing
                // the sockets. If we only unref, then the callback passed to
                // `fastify.close` will never be invoked; nor will any of the
                // registered `onClose` hooks.
                conn.destroy()
                fastify[kKeepAliveConnections].delete(conn)
              }
        }), shutdownTimeout).unref();
        
      } else {
        done(null)
      }
    })
  })
  ```

**Comment by climba03003** [comment]
I would wait until https://github.com/nodejs/node/pull/42812 lands.
We should not add more monkey patching when the core already implementing the feature we needs.

**Comment by budarin** [comment]
ok, will wait for it in node
