### ISSUE TITLE
[first-class-vite support]

### ISSUE THREAD

**Issue by skimhugo** [fastify/fastify#3871]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Fastify is great, but the dev tool chains is not that good.
I found https://github.com/axe-me/vite-plugin-node
and I use it for my project, it is so great. Fastify can easily use it realize modern JS toolchain.

- dev mod have HMR.(by vite ssr)
- test mod have HMR.(by vitest)
- use vite plugin ecosystem to do something
- prod mod have HMR(not yet)
- only support esm due to ssr

But when use this mod, fastify plugin like autoload is not work.

So I think it's time for you guys support some vite plugin. It is best support some plugin like vite-plugin-fastify,vite-plugin-fastify-autoload, and add test in the version change.

vite can bring a lot to fastify. It is worth doing something.

**Comment by zekth** [comment]
Your issue is unclear. Seems like the problem is just due to imports inside `fastify-autoload` rather than `fastify` itself.

> But when use this mod, fastify plugin like autoload is not work.

Please make a more descriptive issue.

**Comment by Fdawgs** [comment]
Like [fastify-vite](https://github.com/fastify/fastify-vite)?

**Comment by skimhugo** [comment]
@Fdawgs I didn‘t find this project, I will do some work on it. thanks.  you guys are amazing.
