### ISSUE TITLE
Inconsistent behavior of the same hook when it is added using `addHoook` and when it is described in the route

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#3874]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Node.js version

18.0.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Monterey 12.3.1 (21E258)

### Description

[Here](https://www.fastify.io/docs/latest/Reference/Hooks/#onrequest) is described `onRequest `handler could be either synchronous or asynchronous.

but [here](https://www.fastify.io/docs/latest/Reference/Routes/) 'onRequest' could be only synchronous

if I'm going to write a plugin that will provide an asynchronous method for adding it as a hook for `onRequest`, then I won't be able to use it as a handler in the route.

### Steps to Reproduce

view documentation

### Expected Behavior

I would like to be able to describe asynchronous handlers for hooks with the ability to use them as handlers in routes as well

**Comment by climba03003** [comment]
How can we improve the document? Change the syntax to `onRequest(request, reply[, done])`?

**Comment by budarin** [comment]
`onRequest` in route options  is exclusively synchronous - says this, but for for compatibility it should have two versions of the interface: synchronous and asynchronous.

By the way, if I describe the handler as synchronous, typescript swears that it can't use the handler:
>Avoid referencing unbound methods which may cause unintentional scoping of `this`.
>If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead.

Somwhere in a plugin
```ts
const checkSid = (req: FastifyRequest, reply: FastifyReply, done: HookHandlerDoneFunction): void => { ... }

fastifyI.decorate('checkSid', checkSid);
```

Somwhere in route description
```ts
...
onRequest: fastify.checkSid,
                     ^^^^^^ above typescript error
...
```

**Comment by climba03003** [comment]
I think it should be `TypeScript` problem only.
Can you try it in `JavaScript`?

**Comment by budarin** [comment]
I can and even am sure that everything will work, but unfortunately our project is written entirely in typescript :(

**Comment by budarin** [comment]
PS: 'onRequest' in route config is exceptionally synchronous (

**Comment by climba03003** [comment]
> PS: 'onRequest' in route config is exceptionally synchronous (

Not sure what it means.

**Comment by mcollina** [comment]
I don't think it's even a doc issue. `onRequest` can be `async`, there are no problems with it.

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by budarin** [comment]
Try to [demo](https://github.com/budarin/fastify-problem)

**Comment by climba03003** [comment]
> Try to [demo repo](https://github.com/budarin/fastify-problem)

`plugin` registration is `async`. At the stage of your route registration, `.checkSid` is `undefined`.

**Comment by budarin** [comment]
Have fixed plugin registration to callback variant, but the plugin still async - it doesn't work!

**Comment by climba03003** [comment]
> Have fixed plugin registration to callback variant, but the plugin still async - it doesn't work!

You cannot control how plugin is registration in `sync` or `async`.
`plugin` registration can only be `async`, it is by design.

**Comment by budarin** [comment]
I mean not registration order but the plugin function
```ts
onRequest: function() { ...}
```
ws
```ts
onRequest: async function() { ...}
```

**Comment by climba03003** [comment]
> I mean not registration order but the plugin function
> 
> ```ts
> onRequest: function checkSid() { ...}
> ```
> 
> ws
> 
> ```ts
> onRequest: async function checkSid() { ...}
> ```

In your updated demo, the `.checkSid` is still `undefined` when it pass to the `route`.
That's why I am explaining why it happen.

**Comment by budarin** [comment]
Thank you, I realized that at the time of registration of the rout, the `checkSid` of the hedgehog was not declared in the request

**Comment by budarin** [comment]
there were only problems with typing
if you add an asynchronous function

```js
onRequest: async function checkSid() { ...}
```
I get an error even though the code works correctly
![image](https://user-images.githubusercontent.com/8055157/166858651-34e059b0-fb38-47b0-ae2d-7cedd3f2f8fa.png)

**Comment by mcollina** [comment]
The fundamental problem is that folks use both async and done at the same time: **this should not be done**. The goal of those split definitions is to avoid that.

**Comment by aboqasem** [comment]
> The fundamental problem is that folks use both async and done at the same time: **this should not be done**. The goal of those split definitions is to avoid that.

That means that the current implementation & types are not correct, because it is passed even if the function is `async`. And types do not correctly behave the way you just explained they should.

**Comment by mcollina** [comment]
It's not possible to know before calling the function if it will return a promise or not, so `done` is passed in both cases. Either return a promise or call `done()`. The current setup has removed most of the bug reports caused by misuses of callbacks, so it's working as intended even if it's not strictly correct.

**Comment by heathprovost** [comment]
I believe this should be looked at again before closing it... We recently upgraded to es-lint 8 and they added more sophisticated type checking and the manner in which fastify is declaring the hook types no longer passes the linter rules.

If you write something like this and assign it as a preValidation route handler (for example):

```ts
function protect (): preValidationAsyncHookHandler {
  return async (req, rep): Promise<void> => {
    return await validateUser(req)
  }
}
```

...

```ts
app.route({
  method: 'GET',
  url: '/',
  preValidation: protect(),
  handler: async (req, rep) => {
    await rep.redirect(302, '/graphql')
  }
})
```

The linter will complain now:
```
Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
```

This is because preValidation *route* hooks are only declared for `preValidationHookHandler`, but the actual type in this case is really  `preValidationAsyncHookHandler`. I understand the argument that it does not matter in practice because it works either way, but the problem is **technically* the linter is right here and the declaration that fastify is using is not complete. This is what it has in the routes.d.ts file for this:

```ts
  // hooks
  # ... other hooks
  preValidation?: preValidationHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig> | preValidationHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>[];
```

there are no declare here for `preValidationAsyncHookHandler` here (even though that type is actually exported and could be included). All of the hook declarations in this block should have the Async versions or'd into them as well like this (as least this is one way to fix it - we tested and it works):

```ts
  // hooks
  # ... other hooks
  preValidation?: preValidationHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig> | preValidationHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>[] | preValidationAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig> | preValidationAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>[];
```

It may not be an urgent issue as it can generally be worked around with a linting exception, but I believe that technically this needs to be fixed for it to be _correct_.

**Comment by mcollina** [comment]
Why the following is not correct?

```typescript
function protect (): preValidationAsyncHookHandler {
  return async (req, rep): Promise<void> => {
    await validateUser(req)
  }
}
```

**Comment by heathprovost** [comment]
That is correct. The part where it goes wrong is this part:
```ts
app.route({
  method: 'GET',
  url: '/',
  preValidation: protect(),
  handler: async (req, rep) => {
    await rep.redirect(302, '/graphql')
  }
})
```

because here the type that is acceptable for the preValidation property on a route is `preValidationHookHandler`, which is the non-async version. So the linter screams because the protect() function returns `preValidationAsyncHookHandler` instead. The older versions of es-lint were not smart enough to detect this mismatch, so it was just kind of ignored. But version 8 sees it and correctly complains that it is wrong.

**Comment by mcollina** [comment]
Could you include a reproducible example? or maybe you'd like to send a PR?

We can definitely fix the types!

**Comment by aboqasem** [comment]
> The fix (seems to me anyway) would be to just add the async versions of all those handler types into the routes.d.ts file so that can accept either, like this:
> 
> 
> 
> ```ts
> 
> // hooks
> 
> # ... other hooks
> 
> preValidation?: preValidationHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig> | preValidationHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>[] | preValidationAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig> | preValidationAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>[];
> 
> ```

I tried just that, but similar to `string | "hi"` is `string`, `void | Promise<void> /* or anything */` is `void`.

https://github.com/fastify/fastify/issues/3874#issuecomment-1121360492

**Comment by heathprovost** [comment]
> I tried exactly that. But similar to how string | "hi" is string, void | Promise<void> /* or anything */ is void.

I'm not sure what you mean exactly, but you can easily test this:

- install eslint version 8 (or just the latest version)
- write a function that returns an AsyncHookHandler (preValidation for example)
- try to assign it to a route like in my example

When you lint your code eslint will complain with the error I posted.

**Comment by aboqasem** [comment]
> I'm not sure what you mean exactly, but you can easily test this:

I am not saying that there is no linter error, I am pointing out that the solution you suggested would not work.

**Comment by heathprovost** [comment]
It does for this specific version of eslint. I’m not claiming it is the correct solution, just that it definitely made the linter stop complaining.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aboqasem** [comment]
> It does for this specific version of eslint. I’m not claiming it is the correct solution, just that it definitely made the linter stop complaining.

Oh! I would love to see the solution if you push it.

**Comment by mmiszy** [comment]
Should this issue be reopened? It never got fixed.

**Comment by climba03003** [comment]
> Should this issue be reopened?

No, since there are same issue that open.
https://github.com/fastify/fastify/issues/4376
