### ISSUE TITLE
Replace Snyk webhook with GitHub's own dependency review action

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#3883]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When opening a PR in Fastify repos a Snyk webhook is triggered, which checks if the PR has added any vulnerable dependencies: 

![image](https://user-images.githubusercontent.com/43814140/167102430-dc1f936a-0702-4210-9dd8-924b46f4868f.png)

GitHub have introduced their [own GitHub Action](https://github.com/actions/dependency-review-action) that does the same thing.
With this we can remove the Snyk webhook from https://github.com/fastify/fastify/settings/hooks, and it'd be nice to get rid of another third-party dependency that may go down and cause issues, like how we removed Coveralls for similar reasons.

**Comment by climba03003** [comment]
I agree to remove `snyk`.
It cause problem on `First-time Contributor` and signal a false positive CI success to us.

**Comment by mcollina** [comment]
Go for it!

**Comment by xtx1130** [comment]
+1 for this suggestion.
And we can change fastify docs introductions from snyk to Github dependency-review-action:
https://github.com/fastify/fastify/blob/main/docs/Guides/Write-Plugin.md?plain=1#L83-L85

And remove this badge:
https://github.com/fastify/fastify/blob/main/README.md?plain=1#L11
