### ISSUE TITLE
onResponse doesn't have access to the server instance?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#389]
It looks to me like functions registered to the `onResponse` hook do not have access to the Fastify instance, e.g.:

```js
instance.decorate('foo', 'foo')
instance.addHook('onResponse', function (res, next) {
  // here, `this` will be undefined or at least _not_ equivalent to `instance`
  if (this.foo === 'foo') console.log('success!')
  next()
})
```

Is there a reason for this? The documentation doesn't make any mention of this and I would expect `this` to be bound like it is in other hooks.

**Comment by delvedor** [comment]
The hooks does not bind the server context at the moment. 
Related: https://github.com/fastify/fastify/issues/120

**Comment by jsumners** [comment]
Oops, I forgot about that issue.
