### ISSUE TITLE
Incorrect types for response methods (code, headers) - await is required

### ISSUE THREAD

**Issue by ZiiMakc** [fastify/fastify#3894]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

3.0.1

### Node.js version

16.15.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I get eslint error  [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) that requires to `await` promises, but `response.code` or `response.headers` doesn't seems to be a promise.

```
const myApp = fastify();

myApp.get('/', async (req, res) => {
  res.headers({}); // bad
  res.code(1); // bad

  await res.code(1); // ok
  await res.headers({}); // ok
});
```

### Steps to Reproduce

tsconfig.json:
```
{
  "exclude": ["**/node_modules"],
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "module": "ES2022",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowJs": true,
    "checkJs": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "removeComments": true,
    "importHelpers": true,
    "importsNotUsedAsValues": "error",
    "preserveValueImports": true,
    "downlevelIteration": true,
    "newLine": "LF",
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "exactOptionalPropertyTypes": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "skipLibCheck": true
  }
}
```

### Expected Behavior

Response `response.code` `response.headers` types should not result in eslint error

**Comment by climba03003** [comment]
`.code` and `.headers` itself return `reply` which can be `await`.
There is nothing wrong with the `fastify` type or `eslint` and It is how `eslint` interpret `.then` method as `Promise`.

**Comment by ZiiMakc** [comment]
@climba03003 but then I'm forced to make function async and add everywhere await, even if not needed, or allow `void` to silence eslint. Maybe something like `PromiseLike` can work as a solution?

**Comment by climba03003** [comment]
> @climba03003 but then I'm forced to make function async and add everywhere await, even if not needed, or allow `void` to silence eslint. Maybe something like `PromiseLike` can work as a solution?

I don't understand what you means by `foreced to make function async`.
`PromiseLike` is not a solution, it is `PromiseLike` currently.

**Comment by ZiiMakc** [comment]
> > @climba03003 but then I'm forced to make function async and add everywhere await, even if not needed, or allow `void` to silence eslint. Maybe something like `PromiseLike` can work as a solution?
> 
> I don't understand what you means by `foreced to make function async`. `PromiseLike` is not a solution, it is `PromiseLike` currently.

If I try to use it like this there will be eslint error `no-floating-promises`:
```
myApp.get('/',  (req, res) => {
  res.headers({}); // error no-floating-promises
  res.code(1); // error no-floating-promises
  res.send('plain string')  // error no-floating-promises
});
```

So I'm forced to do it like this:
```
myApp.get('/',  async (req, res) => {
  await res.headers({}); // fine
  await res.code(1); // fine
  await res.send('plain string')  // fine
});
```

Is the second example correct?

**Comment by climba03003** [comment]
No, you should not await on `code` or `headers` unless you know what you are doing.

As I said before, the type is correct. This is a false positive error from eslint. And this is a known issue that currently do not have fix for it.

You need `void Promise` to suppress the false positive error

**Comment by ZiiMakc** [comment]
Reported issue at [eslint](https://github.com/typescript-eslint/typescript-eslint/issues/4961). I hope there can be another solution, because if some method on `PromiseLike` object will need actually need await you will never know using `void` workaround.

**Comment by christian-bromann** [comment]
I am running into the same issue and would also like to see a resolution here. I don't know why `FastifyReply` needs to have a promise like `then` method but I would suggest maybe something like this:

```ts
header(key: string, value: any): Omit<FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>, 'then'>;
```

To avoid conflicts with Eslint.
