### ISSUE TITLE
Child log level in bindings is deprecated

### ISSUE THREAD

**Issue by orov-io** [fastify/fastify#3895]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Node.js version

16.14.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

Hi all!

I'm trying to change the logger level in certains situations in a 'onRequest' hook. The code is this:
`req.log = req.log.child({
                    level: Logger.getCustomLogLevel(req),
                    userID: Logger.getUserID(req),
                })`

with this code, the level is changed, but pino shows this log as a warning: 

>  [PINODEP007] PinoWarning: bindings.level is deprecated, use options.level option instead

As the FastifyLoggerInstance interface only defined the bindings argument, it's impossible to satisfy pino necessity and the log it's shown in every request.

I keep on mind that adding the options argument to the interface, or remove the level from bindings and pass it correctly to pino in the child function will solve this.

These are the project dependencies, if needed:

`"dependencies": {
        "@fastify/auth": "^2.0.0",
        "@fastify/cors": "^7.0.0",
        "@fastify/env": "^3.0.0",
        "@fastify/jwt": "^5.0.1",
        "@fastify/sensible": "^4.1.0",
        "@mikro-orm/core": "^5.1.3",
        "dotenv": "^16.0.0",
        "fastify": "^3.29.0",
        "fastify-plugin": "^3.0.1",
        "i18next": "^21.8.0",
        "i18next-fs-backend": "^1.1.4",
        "mongoose": "^6.3.2",
        "pino-multi-stream": "^6.0.0",
        "pino-papertrail": "^2.1.0",
        "uuid": "^8.3.2"
    }`

Thanks!

### Steps to Reproduce

Create a child logger changing the log level in any part of the code.
See the PINOWARNING log

### Expected Behavior

Changing the log level for a child not throw any warning from pino

**Comment by climba03003** [comment]
Would you like to send a PR to update the corresponding type?

There is type error in this file https://github.com/fastify/fastify/blob/v3.x/types/logger.d.ts

**Comment by climba03003** [comment]
Then you should use
```js
req.log.child({ userID: Logger.getUserID(req) }, { level: Logger.getCustomLogLevel(req) })
```
in your file.

**Comment by orov-io** [comment]
ok, i have the code working on my project, I'm trying to figure out about how to send the PR

**Comment by orov-io** [comment]
I think is forking the project, checking out the v3.x branch, commit, push and finally send the PR, it's correct?

**Comment by climba03003** [comment]
> I think is forking the project, checking out the v3.x branch, commit, push and finally send the PR, it's correct?

Yes

**Comment by orov-io** [comment]
I'm having some problems commiting: 

![image](https://user-images.githubusercontent.com/48791471/167830824-840beed0-643a-4b68-9b8d-15362b7560cd.png)

Any help? I just added this to types file:

```typescript
export interface redactOptions {
  paths: string[];
  censor?: string | ((v: any) => any) | undefined;
  remove?: boolean | undefined;
}

export interface ChildLoggerOptions {
  level?: LogLevel | string;
  redact?: string[] | redactOptions;
  serializers?: { [key: string]: SerializerFn };
}

// And in the FastifyLoggerInstance:
child(bindings: Bindings, options?: ChildLoggerOptions): FastifyLoggerInstance;
```

**Comment by orov-io** [comment]
Also I think that the coverage issue it's not my fault:
![image](https://user-images.githubusercontent.com/48791471/167833029-b75c8501-a4bb-4a10-a429-358f185f7ca5.png)

**Comment by climba03003** [comment]
> Any help? I just added this to types file:
> 
> ```ts
> export interface redactOptions {
>   paths: string[];
>   censor?: string | ((v: any) => any) | undefined;
>   remove?: boolean | undefined;
> }
> 
> export interface ChildLoggerOptions {
>   level?: LogLevel | string;
>   redact?: string[] | redactOptions;
>   serializers?: { [key: string]: SerializerFn };
> }
> 
> // And in the FastifyLoggerInstance:
> child(bindings: Bindings, options?: ChildLoggerOptions): FastifyLoggerInstance;
> ```

If the test is unrelated to `TypeScript`, you can safely ignore it. 
It sometimes fail per environment, for example `WSL` always fail for some test.
`git push --no-verify` can skip the test hook running.

**Comment by orov-io** [comment]
I just made the PR: https://github.com/fastify/fastify/pull/3896

I think its ok, but tell me if not.

**Comment by Fdawgs** [comment]
closed by https://github.com/fastify/fastify/pull/3896
