### ISSUE TITLE
@fastify/helmet-9.0.0 requires fastify-4.0.0, but the latest npm published version is 3.29.0

### ISSUE THREAD

**Issue by AmitGazal** [fastify/fastify#3900]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

3.0.1

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3.1

### Description

@fastify/helmet-9.0.0 requires fastify-4.0.0, but the latest npm published version is 3.29.0

### Steps to Reproduce

ncu -u
npm i
<run code using fastify and @fastify/helmet>

### Expected Behavior

FastifyError: fastify-plugin: @fastify/helmet - expected '4.x' fastify version, '3.29.0' is installed

**Comment by climba03003** [comment]
It is correct, the latest plugin is start targeting the `fastify@4`.
If you face this case in new installation, please install the previous version of that plugin.
