### ISSUE TITLE
What is the defaultRoute?

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#3911]
## 💬  Question here 

I met the [getDefaultRoute](https://www.fastify.io/docs/latest/Reference/Server/#getdefaultroute) and [setDefaultRoute](https://www.fastify.io/docs/latest/Reference/Server/#setdefaultroute) methods in the documentation, but I didn't find a description of what it is anywhere.

Could you explain what it is?

**Comment by mcollina** [comment]
If anybody could look into this and improve the docs it would be amazing.

**Comment by climba03003** [comment]
`defaultRoute` is actually representing what it means.
By setting this handler, whenever a request do not match any url specified of your application. You will fall into this handler.
More elaborate on https://github.com/delvedor/find-my-way#findmywayoptions

Important Note: If you override the `default route`, it means that the `404 router` will never triggered. That also means `setNotFoundHandler` will not works, no hooks fired.

**Comment by budarin** [comment]
does this mean that this route will respond to all requests with all possible methods?

**Comment by climba03003** [comment]
> does this mean that this route will respond to all requests with all possible methods?

I think the answer is yes. But use it with caution.

**Comment by climba03003** [comment]
Re-open it, it need the update on document.
You can unwatch your issue if you do not want notification spam.

**Comment by budarin** [comment]
Ok
