### ISSUE TITLE
Incorrect typings for getDefaultRoute

### ISSUE THREAD

**Issue by lbfalvy** [fastify/fastify#3919]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Node.js version

16.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch with kernel 5.17.9

### Description

`FastifyInstance.getDefaultRoute` is incorrectly typed as a field of `DefaultRoute<RawRequest, RawReply>`, it should be a method with that same return type.

### Steps to Reproduce

Try to use `getDefaultRoute` in typescript code; Typescript will warn about two required parameters (request and response) and the code will fail to compile.

### Expected Behavior

The method is typed as having no parameters and returning a function that has the aforementioned two.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
