### ISSUE TITLE
How to get an fastify instance in the route handler?

### ISSUE THREAD

**Issue by leecade** [fastify/fastify#392]
```js
const handler = async (req, replay) => {
  // `fastify` from where?
  const client = await fastify.pg.connect()
}

fastify.get('/', options, handler)
```

**Comment by delvedor** [comment]
Hi! thank you for checking out Fastify!
You can't, we highly recommend to use the plugin system and not put the route handlers in different files.
Have a look [here](https://github.com/fastify/fastify-mongodb/issues/9) :)

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
