### ISSUE TITLE
How to get raw query string?

### ISSUE THREAD

**Issue by wong2** [fastify/fastify#393]

**Comment by BigMurry** [comment]
You can get the full url from `request.req.url`, and the raw query string can be retrieved from there.

**Comment by wong2** [comment]
@BigMurry thanks! hope there is something like `request.querystring`

**Comment by BigMurry** [comment]
@wong2 Already have a JSON format one from `request.query`

**Comment by delvedor** [comment]
Agree with @BigMurry!
Closing this, if you have more questions feel free to reopen :)

**Comment by wong2** [comment]
my api accept query like: `/:uid/avatar?imageView2/0/w/300/h/300/q/80`, and I need to redirect to a new url, while preserve the query string, currently it's hard to do actually.
