### ISSUE TITLE
fastify.js utility but not plugin, can add ecosystem?

### ISSUE THREAD

**Issue by imjuni** [fastify/fastify#3938]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I create tool called by [fast-maker](https://github.com/imjuni/fast-maker). 

fast-maker not a plugin but create route system using by directory structure(like next.js and PHP codeigniter).

I want to add this tool in Fastify Ecosystem document. But ecosystem document only describe plugin package.

So, I want to add `Community Tools` section after add fast-maker.

This change can raise some problem?

**Comment by climba03003** [comment]
I would say yes.

**Comment by imjuni** [comment]
This change already add via https://github.com/fastify/fastify/pull/3939

Thank you!
