### ISSUE TITLE
There are no type descriptions for server properties

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#3942]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0-rc.3

### Description

There are no type descriptions for server properties:
- pluginName
   https://www.fastify.io/docs/latest/Reference/Server/#pluginname

- validatorCompiler
   https://www.fastify.io/docs/latest/Reference/Server/#validatorcompiler
  
- serializerCompiler
   https://www.fastify.io/docs/latest/Reference/Server/#serializercompiler

It is possible that other instance properties are not typed

### Steps to Reproduce

<img width="944" alt="image" src="https://user-images.githubusercontent.com/8055157/170848533-eef52be4-16fe-4911-8d25-2e79e938c495.png">

### Expected Behavior

Availability of type descriptions for the specified properties

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by budarin** [comment]
By the way, they are not present at all in the instance of fastify

```js
const fastify = require('fastify')({
    logger: true,
});

// Declare a route
fastify.get('/', function (req, reply) {
    const { pluginName, validatorCompiler, serializerCompiler } = fastify;
    req.log.info(`${typeof pluginName}, ${typeof validatorCompiler}, ${typeof serializerCompiler}`);

    reply.send({ hello: 'world' });
});
```
here are the log entries

```json
{"level":30,"time":1653837768101,"pid":25388,"hostname":"WIN-40K96OG4L3A","msg":"Server listening at http://127.0.0.1:3000"}
{"level":30,"time":1653837770753,"pid":25388,"hostname":"WIN-40K96OG4L3A","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"127.0.0.1:3000","remoteAddress":"127.0.0.1","remotePort":55850},"msg":"incoming request"}
{"level":30,"time":1653837770755,"pid":25388,"hostname":"WIN-40K96OG4L3A","reqId":"req-1","msg":"undefined, undefined, undefined"}
{"level":30,"time":1653837770770,"pid":25388,"hostname":"WIN-40K96OG4L3A","reqId":"req-1","res":{"statusCode":200},"responseTime":15.357467889785767,"msg":"request completed"}
```

**Comment by mcollina** [comment]
`pluginName` is expected to be undefined for the root object. I'm going to change it to `'fastify'` so that's it's clearer.

As for `validatorCompiler` and `serializerCompiler` I'm unsure. I tried to play around and I got a few undefined too. @Eomm wdyt?

**Comment by Eomm** [comment]
Yes, those types are missing and only the input is mapped actually

**Comment by TommyDew42** [comment]
Hi, is @budarin working on this issue? If we need someone to work on it, I’m happy to help!!

**Comment by mcollina** [comment]
@TommyDew42 I think you can take it!

**Comment by budarin** [comment]
@TommyDew42  

Unfortunately I don't know enough about the internal implementation of fastify to solve this problem (

**Comment by denes-fekeshazy** [comment]
Looks like there is a merged PR for this. Should this issue be closed or is there more work to do on this?
