### ISSUE TITLE
Hooks reply

### ISSUE THREAD

**Issue by astesio** [fastify/fastify#395]
I have a doubt.
Following the documentation you can see [here](https://www.fastify.io/docs/latest/Hooks/#scope) says that 
_If you get an error during the execution of you hook, just pass it to next() and Fastify will automatically close the request and send the appropriate error code to the user.

If you want to pass a custom error code to the user, just use reply.code():_

`fastify.addHook('onRequest', (req, res, next) => {
  // some code
  reply.code(400)
  next(new Error('some error'))
})`

Above ours has an error, where second param it is res, bellow has reply, it is undefined, but if you change of the right, I receive the following error in my terminal.

**Unhandled Exception TypeError: reply.code is not a function**

My doubt it is, ours have or no reply in addHook('onRequest', .... ?

Thanks.

**Comment by jsumners** [comment]
Interesting, fastify.io seems to be out-of-sync with the master on that page (ping: @lmammino). The example should be:

> If you want to pass a custom error code to the user, just use `reply.code()`:
> ```js
> fastify.addHook('preHandler', (request, reply, next) => {
>   reply.code(500)
>   next(new Error('some error'))
> })
> ```

However, you state you are working with the `onRequest` hook. That being the case, you really want to do:

```js
fastify.addHook('onRequest', function (req, res, next) {
  res.statusCode = 400
  next(Error('some error'))
})
```

**Comment by astesio** [comment]
@jsumners thanks for answer my question, well I need validation if an uri created by my first user in my application it is already using, if it is true, I will reply an error, otherwise I will let pass. See the [image](https://www.fastify.io/docs/latest/Lifecycle/) diagram I think it is the better location for validation for this situation. 
What do you think ?

**Comment by jsumners** [comment]
I'm sorry, I don't follow your question.

**Comment by astesio** [comment]
I did not understand, but I no problem. ;)

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
