### ISSUE TITLE
Logger configuration options vs pino `transport`

### ISSUE THREAD

**Issue by mweberxyz** [fastify/fastify#3950]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Something hasn't quite been sitting with me right since my pino-pretty PR https://github.com/fastify/fastify/pull/3933 was merged.

Pino allows transport/destination configuration via either a call to `pino.destination` after pino is instantiated, or passing a `transport` configuration object to the initial instantiation. Pino allows multiple transports to be used by passing an array of transports.

Fastify could now allow both a stream and a file output in logging by converting the `file` and `stream` arguments in logger configuration, which would remove the possible `FST_ERR_LOG_INVALID_DESTINATION` error in logger. Additionally, fastify could map the previously recommended `prettyPrint` argument to the expected pino transport configuration, which would mean the previously merged documentation change PR could be reverted and less of pino's internals would need to be exposed to casual users of fastify's logger.

Alternatively, fastify could deprecate all three logger transport configuration options (`prettyPrint`, `file`, and `stream`), and update documentation to point users at pino's documentation to set up transports using pino's native configuration. This might add a little overhead to user, but would make fastify's logger implementation more stable with regards to future pino changes.

I can work up a branch for either strategy if it is agreed that the current implementation and documentation has potential for confusing users. Thoughts?

**Comment by mcollina** [comment]
> Fastify could now allow both a stream and a file output in logging by converting the file and stream arguments in logger configuration, which would remove the possible FST_ERR_LOG_INVALID_DESTINATION error in logger. Additionally, fastify could map the previously recommended prettyPrint argument to the expected pino transport configuration, which would mean the previously merged documentation change PR could be reverted and less of pino's internals would need to be exposed to casual users of fastify's logger.

What error are you seeing? I'd like to understand what's the actual problem you are facing.

**Comment by mweberxyz** [comment]
I'm not having any problems currently; I am digging into lib/logger.js and the logging documentation to see if there's any improvements to be made.

One such improvement would be to allow the user to specify both a stream and a file output for pino -- which is now possible with pino but is not allowed per the current fastify implementation.

**Comment by mcollina** [comment]
> stream and a file output for pino

I don't think that's possible with pino.

**Comment by mweberxyz** [comment]
I am going to keep poking around at it; if I land on any proposed improvements, I'll create a PR. Thx.
