### ISSUE TITLE
http error does not return the proper status code

### ISSUE THREAD

**Issue by gunwd** [fastify/fastify#3959]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4-rc.4

### Plugin version
    "@fastify/secure-session": "^5.1.0",
    "@fastify/sensible": "^5.0.0",

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5

### Description

For authentication, since I was repeating myself, I created function that takes the Fastify object (to throw various http errors in my routes using fastify-sensible) and a session cookie to verify the integrity of requests. When I threw an unauthorized error, I would handle that error accordingly for all the routes by setting setErrorHandler() and checking reply.statusCode().

<img width="564" alt="Screen Shot 2022-06-01 at 15 22 56" src="https://user-images.githubusercontent.com/74139498/171403508-7bde3dee-7205-4ba5-9485-c394f31ee8ed.png">
<img width="593" alt="Screen Shot 2022-06-01 at 15 11 32" src="https://user-images.githubusercontent.com/74139498/171402557-4e39ccda-dd5d-454b-89a7-d32d082fe6e6.png">

After updating to Fastify v4, even though I throw an unauthorized error from the function, I get a 200 status code, so I cannot check for various types of errors. TBH, I was probably doing sth wrong and now it's exposed. But still, maybe there's a problem, as before the upgrade, everything was working as expected.

### Steps to Reproduce

<img width="928" alt="Screen Shot 2022-06-01 at 15 32 04" src="https://user-images.githubusercontent.com/74139498/171405133-7819114b-1e0f-4070-9972-ac0e030295fb.png">

Here, if the 401 error is thrown, setErrorHandler would see the status code and respond accordingly. After v4, the status code is 200.

### Expected Behavior

The status code should be 401, and the error handler should redirect to `/p/login`, not `/p/account`

**Comment by climba03003** [comment]
Can you post the code that we can copy and paste.

**Comment by gunwd** [comment]
Of course! Here's a demo where Fastify v3 would return "Unauthorized!" but v4 returns "Boom!".

index.js:
```
const routes = async (fastify, options) => {
  fastify.setErrorHandler(async (error, request, reply) => {
    if (reply.statusCode === 401) {
      return "Unauthorized!";
    }

    return "Boom!";
  });

  fastify.get("/", async (request, reply) => {
    // Status code 401
    throw fastify.httpErrors.unauthorized();
  });
}


module.exports = routes;
```
Then, server.mjs:

```
import Fastify from "fastify";
const PORT = process.env.PORT || 5000;

const fastify = Fastify({
  logger: false,
  trustProxy: false,
});

await fastify.register(import("@fastify/sensible"));
fastify.register(import("./index.js"));

const start = async () => {
  try {
    await fastify.listen({ port: PORT });
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();
```

**Comment by mcollina** [comment]
That's a documented breaking change. The error handler will _not_ have the status code set up for you, this is now up to you to do.

The following code would do the trick:

```js
const routes = async (fastify, options) => {
  fastify.setErrorHandler(async (error, request, reply) => {
    if (err.statusCode === 401) {
      reply.code(401)
      return "Unauthorized!";
    }
    reply.code(500);
    return "Boom!";
  });

  fastify.get("/", async (request, reply) => {
    // Status code 401
    throw fastify.httpErrors.unauthorized();
  });
}
```
