### ISSUE TITLE
Export `LightMyRequest.InjectOptions` from `fastify` so we stick to the same version used by our current Fastify version

### ISSUE THREAD

**Issue by StanleySathler** [fastify/fastify#3960]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I've been writing some utility functions for my project.

They accept a few params like `headers` and `payload`, so they're forwarded straight to a `FastifyInstance.inject()` call.

The problem is: we can't export `LightMyRequest.InjectOptions` from Fastify, and need to install it ourselves. But then, there's no easy way to ensure the locally installed `light-my-request` is in the same version as the one used by `fastify`.

I think it would be nice to be able to export it from `fastify`.

### Example

```ts
import type {LightMyRequest.InjectOptions} from 'fastify';

type Options = {
  app: FastifyInstance;
} & LightMyRequest.InjectOptions;

export const createEffect = async ({ app, ...injectOptions}) => {
  const response = await app.inject({
    method: 'POST',
    url: `/effect`,
    ...injectOptions,
  });
};
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by StanleySathler** [comment]
Sure thing! Will raise a PR in a bit 🚀

**Comment by StanleySathler** [comment]
Well... seems it is actually exported. 😂 🚀 
https://github.com/fastify/fastify/blob/main/fastify.d.ts#L193

Problem solved! ✔️
