### ISSUE TITLE
Inside the url building doc, show how to access the params

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3971]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

all

### Node.js version

all

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

see title

### Steps to Reproduce

see title

**Comment by mcollina** [comment]
Yes. I opened it quickly from mobile and there is an actual bug in the app.

**Comment by Fdawgs** [comment]
What page?

**Comment by mcollina** [comment]
https://www.fastify.io/docs/latest/Reference/Routes/#url-building

**Comment by jsumners** [comment]
Resolved by #3989.
