### ISSUE TITLE
Type Schema Body for Fastest-validator npm

### ISSUE THREAD

**Issue by armada45-pixel** [fastify/fastify#3974]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Make fastify-fv plugin work full function for typescript.

[github fastify-fv](https://github.com/erfanium/fastify-fv "github fastify-fv")
[github fastest-validator](https://github.com/icebob/fastest-validator "github fastest-validator")

```typescript
const FV = require("fastest-validator")
import type { ValidationSchema } from "fastest-validator"

export default fp(async (app) => {
  const fv = new FV()
  app.register(fvPlugin, fv)
})
```

You can use
```typescript
  app.route({
    method: 'POST',
    url: '/a',
    schema: {
      body: { // fastest-validator schema
        name: 'string',
        age: { type: 'number', min: 18, max: 99 },
        category: 'string[]',
      },
    },
    async handler(req) {
      // code
    },
  })
```

And I can't overriding declared module
```typescript
declare module "fastify" {
  interface FastifySchema {
    body?: ValidationSchema | ValidationSchema[]
  }
}
```
Will show error type
(property) FastifySchema.body?: unknown
Subsequent property declarations must have the same type.  Property 'body' must be of type 'unknown', but here has type 'ValidationSchema<any> | ValidationSchema<any>[] | undefined'.ts(2717)
schema.d.ts(27, 3): 'body' was also declared here.

### Motivation

Fastest-validator faster then Ajv.
["fastest-validator benchmark"](https://github.com/icebob/validator-benchmark#validator-benchmark "github fastest-validator benchmark")

Fastest-validator have a lot of type , prefix , function , strict

### Example

```typescript
import fastify from 'fastify'
const FV = require("fastest-validator")
import fvPlugin from 'fastify-fv'
import type { ValidationSchema } from 'fastest-validator'

const app = fastify()
const fv = new FV()

app.register(fvPlugin, fv) // register the plugin

app.route({
  method: 'POST',
  url: '/a',
  schema: {
    body: { // fastest-validator schema
      name: 'string',
      age: { type: 'number', min: 18, max: 99 },
      category: 'string[]',
    },
    params: { // fastest-validator schema
      name: 'string',
      age: { type: 'number', min: 18, max: 99 },
      category: 'string[]',
    }
  },
  async handler(req) {
    // code
  },
})

app.listen(3000)

declare module "fastify" {
  interface FastifySchema {
    body?: ValidationSchema | ValidationSchema[]
  }
}
```

**Comment by climba03003** [comment]
> Argument of type 'Validator' is not assignable to parameter of type 'FastifyRegisterOptions | undefined'.

The error is correct. You are not passing `fastify` plugin in the `.register` function.

> Subsequent property declarations must have the same type. Property 'body' must be of type 'unknown', but here has type  ValidationSchema | ValidationSchema[] | undefined'.ts(2717)

`unknown` cannot be merged to any type which is `TypeScript` limitation.
I think this area can be improved and welcome a PR for improvement.

**Comment by armada45-pixel** [comment]
> > Argument of type 'Validator' is not assignable to parameter of type 'FastifyRegisterOptions | undefined'.
> 
> The error is correct. ~You are not passing `fastify` plugin in the `.register` function.~ Please send a PR to update the types on https://github.com/erfanium/fastify-fv which is old and do not specified the option.
> 
> > Subsequent property declarations must have the same type. Property 'body' must be of type 'unknown', but here has type  ValidationSchema | ValidationSchema[] | undefined'.ts(2717)
> 
> `unknown` cannot be merged to any type which is `TypeScript` limitation. I think this area can be improved and welcome a PR for improvement.

I sorry for not involved info about register. I will delete that point.
Main point of question is wan't to overriding declared module FastifySchema->Body
