### ISSUE TITLE
`setDefaultRoute` should have the same signature as `setNotFoundHandler`

### ISSUE THREAD

**Issue by GeoffreyBooth** [fastify/fastify#3977]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The `setDefaultRoute` method takes a function of the signature `(RawRequest, RawReply) =>`. This is unlike all the other handlers, such as `setNotFoundHandler`, which expects a function like `(FastifyRequest, FastifyReply) =>`. This can lead to subtle bugs, as the input parameters have slightly different properties. **If possible, please fix this before releasing Fastify 4.** It would be a shame if this breaking change had to wait until Fastify 5.

---

For context, my app passes the same handler to both `setDefaultRoute` and `setNotFoundHandler`:

```js
app.setDefaultRoute(serveIndexHtmlHandler)
app.setNotFoundHandler(serveIndexHtmlHandler)
```

All that each of these do is serve a static `index.html` file. Upon reading other issues in this repo, I perhaps don't need `setDefaultRoute` at all in my case; but if my app _did_ want a certain HTML file returned for `/` and a separate error HTML file returned for 404 routes, I would still need both (I think).

The handler was initially implemented like this:

```js
const serveIndexHtmlHandler = (request, reply) => {
  reply.sendFile('index.html')
}
```

This works fine for `setNotFoundHandler`, but not `setDefaultRoute`, because `RawMessage` lacks the `sendFile` method. This took a substantial amount of debugging to discover.

**Comment by jsumners** [comment]
`setDefaultRoute` was added specifically to provide a way for someone to interact with the underlying "raw" requests. https://github.com/fastify/fastify/pull/2733

**Comment by GeoffreyBooth** [comment]
> `setDefaultRoute` was added specifically to provide a way for someone to interact with the underlying “raw” requests. See #2733

This was not clear to me from the [documentation](https://www.fastify.io/docs/latest/Reference/Server/#getdefaultroute):

> ### `getDefaultRoute`
> 
> The `defaultRoute` handler handles requests that do not match any URL specified by your Fastify application. This defaults to the 404 handler, but can be overridden with [setDefaultRoute](https://www.fastify.io/docs/latest/Reference/Server/#setdefaultroute).
>
> ### `setDefaultRoute`
> 
> Note: The default 404 handler, or one set using setNotFoundHandler, will never trigger if the default route is overridden. Use [setNotFoundHandler](https://www.fastify.io/docs/latest/Reference/Server/#setnotfoundhandler) if you want to customize 404 handling instead.

These sections don’t mention anything about underlying raw requests. They’re also listed high on the page, before `routing` or `route`. I don’t get the sense from this presentation that these are low-level APIs. The docs describe them as handlers, which made me assume they should follow the pattern of other handlers such as `setNotFoundHandler`.

I understand if you don’t want to change the signatures of these functions, but I would suggest an update to the docs to remove some of this confusion and make the intended uses of these APIs clear.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by GeoffreyBooth** [comment]
> Would you like to send a Pull Request to address this issue?

I can, but I don’t know what it should say. I think the docs should clarify what these APIs are _for:_ why do they exist and when should they be used? I’m reading https://github.com/fastify/fastify/pull/2733 and I don’t see an answer. If these APIs have no utility for end users, perhaps they shouldn’t be documented at all?

**Comment by PaulaPaul** [comment]
@RafaelGSS can you have a look at this?
