### ISSUE TITLE
Server Sent Events not working on fastify v 4

### ISSUE THREAD

**Issue by sarunluitel** [fastify/fastify#3979]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5

### Description

Updated the fastify version to v4. An endpoint that sends Server Sent events gave errors as :
[ERROR] 23:53:43 Error: Cannot set headers after they are sent to the client

The same code was working on v3.

### Steps to Reproduce

initialize a endpoint with server sent events:

```
  reply.raw.writeHead(200, {
    'Cache-Control': 'no-cache',
    'Content-Type': 'text/event-stream',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no',
    'Access-Control-Allow-Origin': 'https://www.example.com',
    'Access-Control-Allow-Credentials': 'true',
  });
  reply.raw.write('event: established \n\n');
```

### Expected Behavior

establish connection and send future message as available on the server.

**Comment by sarunluitel** [comment]
Found a solution to this.
With v4 the function exit automatically sends a response and cannot send further events and gives the error.  need to explicitly specify reply.hijack() before using any raw values

```
  reply.hijack();
  reply.raw.writeHead(200, {
    'Cache-Control': 'no-cache',
    'Content-Type': 'text/event-stream',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no',
    'Access-Control-Allow-Origin': 'https://www.example.com',
    'Access-Control-Allow-Credentials': 'true',
  });
  reply.raw.write('event: established \n\n');
```
I'm leaving the issue open for the maintainers to see and add this to the migration guide.

**Comment by climba03003** [comment]
You should use `.hijack` before actually touching the `.raw` stream.
I would say the previous (`fastify@3`) behavior is not good enough.
