### ISSUE TITLE
App-level version prefixing

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#3980]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support defining endpoint prefix globally for the whole app.

I'm not sure whether per-route prefix should override or append the global one, open to opinions.

If this is approved, I'll send a PR.

### Motivation

Sometimes it is convenient to version whole application as a bundle (e. g. when you are routing across different app versions for backwards compatibility reason on a reverse proxy level), and do not handle versioning in a granular fashion per-route.

### Example

```
const fastify = require('fastify')({
  globalPrefix: '/v1'
})
```

**Comment by climba03003** [comment]
I am not sure if it is a good feature. If it should be added, I will use `prefix` as the option name.

The reason behind why I think it is not good.
Since the route is currently added synchronous and how the `onRoute` hooks changed.
I think it's not a good idea to register route in top-level.
Instead, all operation should be inside a plugin.
Which means you should
```js
import Fastify from 'fastify'
const fastify = Fastify()

// plugin registration is async, but will executed in order
fastify.register(pluginA)
fastify.register(pluginB)
fastify.register(pluginC)
fastify.register(pluginD)
fastify.register(pluginE)

fastify.register(function(fastify, _, done) {
  // here will have all the plugin decoration
  
  // you should add route in here
  
  done()
}, { prefix: '/v1' }) // here is the global prefix
```

**Comment by kibertoad** [comment]
@climba03003 This works, but it relies on forcing to use plugins, which can be an overkill, depending on how the rest of the app is structured and whether there is need for strongly encapsulated app modules.

**Comment by climba03003** [comment]
> @climba03003 This works, but it relies on forcing to use plugins, which can be an overkill, depending on how the rest of the app is structured and whether there is need for strongly encapsulated app modules.

The structure in above is used to reduce user error. Just imagine people do not `await` the `plugin` but they use `onRoute` hooks.

```js
import Fastify from 'fastify'
const fastify = Fastify()

// plugin registration is async, but will executed in order
fastify.register(pluginA) // onRoute hook used

fastify.get('/', () => {}) // this route will never be catched in `pluginA`

await fastify.listen({ port: 0 })
```

Or some people is using `await` but they do understand how encapsulation works

```js
import Fastify from 'fastify'
const fastify = Fastify()

// plugin registration is async, but will executed in order
await fastify.register(pluginA)
fastify.register(pluginB)

fastify.setErrorHandler(() => {}) // it will be used by pluginB, but not pluginA

await fastify.listen({ port: 0 })
```

**Comment by jsumners** [comment]
I agree, this is already achievable by registering the routes within a plugin.

**Comment by mcollina** [comment]
I agree with @climba03003, this is not needed and could be easily achieved with the current plugin system.
