### ISSUE TITLE
Fill Migration-Guide-V4.md

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#3988]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

As titled, it's currently missing all the content of the release blog post https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e

**Comment by Fdawgs** [comment]
Will have a go at this next week as I plan on moving some of the hospital's minor Fastify-based APIs over to v4, so will probably stumble on things not covered in the blog post.

Few questions related to the breaking changes:

-   **Making it mandatory to `return reply`**
    -	Is there any reason a user should/would use `reply.send('hello')` now that returns are mandatory? In v3 you would either use a `return` or use a `reply.send()`, `reply.send()` seems redundant now.
-   **Route registration now being synchronous**
    -   Does this only apply to `.register()` functions, or to all server functions i.e. will `.addHook()` need to be `await`ed?
-   **Deprecation of variadic .listen signature**
    -   As they are not mentioned explicitly I wanted to double-check, are the following options still valid?:
        ```js
        fastify.listen(
        	{
        		port: 0,
        		host: "localhost",
        		exclusive: false,
        		readableAll: false,
        		writableAll: false,
        		ipv6Only: false,
        	},
        	(err) => {}
        );
        ```

**Comment by 112RG** [comment]
I too am confused about ``return reply`` being mandatory.

Since routes like this still function?

```
  fastify.get('/', async (req, reply) => {
    reply.view('login', { captcha: process.env.CAPTCHA_LOGIN, sitekey: process.env.CAPTCHA_SITE_KEY, token: await reply.generateCsrf() })
```

**Comment by climba03003** [comment]
> Since routes like this still function?

Yes, and you can also do the following.
```js
fastify.get('/', async function(request, reply) {
  return reply.view('index')
})
```

**Comment by mcollina** [comment]
> Is there any reason a user should/would use reply.send('hello') now that returns are mandatory?

There are advanced cases for which it's still needed, but the majority of users should not use it.

> Does this only apply to .register() functions, or do all server functions (i.e. .addHook()) need to be awaited?

only `register`

> Can the functions be chained or do they need to be awaited individually?

You can just await the last one

> Deprecation of variadic .listen signature

All other options are still there

**Comment by mhamann** [comment]
One thing that's unclear to me from the Medium post is whether it's possible to migrate to Fastify v4 without converting your entire app to ESM? Based on the new way plugins are shown to be imported `async import('module")`, it feels like this is going to cause a ton of pain for v3.x users who are still largely doing CJS. Maybe I'm missing something?

**Comment by jsumners** [comment]
No. We are not ESM only and likely never will be.

**Comment by Fdawgs** [comment]
So i've almost completed a migration of one API from v3 to v4.

I think what is already in the migration guide, as well as what is in the Medium post, covers the majority of changes.

The documentation around the changes to the error handler need to be expanded though, as I ran into the same issue as https://github.com/fastify/fastify/issues/3959 with checking `res.statusCode`.
