### ISSUE TITLE
Fastify as light as possible or as a minimum framework?

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#399]
I'd like to start talking about this question.

I have to explain myself (the list is only for the clarification, not carved in stone):
- routing is needed
- start up process is needed
- encapsulation is needed
- validation is not needed
- serialization is needed
- parsing URL and query string is not needed
- logging is not needed
- others...

Actually we are able to split to project into two parts in order to keep the needed (to be defined) features in a lower layer an build a minimum framework above it.

This is only an idea born last night. Don't judge me :smile:

Please vote up to keep the framework as light as possible, down for making the framework the minimum framework.

@mcollina @delvedor feel free to close this issue immediately if this issue is out of the scope

cc @fastify/fastify avoid to many comments!

**Comment by StarpTech** [comment]
> Fast and low overhead web framework, for Node.js - Fastify is a web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture

Everything should be clear.

**Comment by mcollina** [comment]
IMHO we should add as much features as possible without creating:

a) a too complex API
b) any slowdown

This is definitely ok to ask. Regarding `req.path`  and other things, those are __very complicated__, and it might be that they are not in our roadmap for 1.0.0.

BTW, logging is __standardized__ but disabled by default. In this way we can log things internally without having to create another wrapping layer that would cost a lot of throughput in production, as everybody needs logging.

**Comment by avilang** [comment]
Hi guys , What think about schedule task? like [egg schedule](https://github.com/eggjs/examples/tree/master/schedule)

**Comment by mcollina** [comment]
@avilang what do you mean?

**Comment by avilang** [comment]
@mcollina 
The HTTP Server we have developed through frameworks is a request/response model.but there are still lots of scenes that require it to execute some timed tasks.such as:
1. Report application state at regular time
2. Update local caches at regular time from a remote interface
3. Split files and delete temporary files at regular time
It would be better if Fastify can provide a set of mechanism to make it more elegant to write and maintain timed tasks

**Comment by jsumners** [comment]
I don't understand how any of that is the responsibility of an HTTP framework.

**Comment by delvedor** [comment]
@avilang thank you for the proposal. I don't think this should be something that the http framework should do. But luckily Fastify has a powerful plugin system, you can build a plugin that does exactly what you need :)

Regarding the overall discussion I think Fastify should keep its mission to provide a extremely low overhead framework, with a set of powerful api to extend it. In this way the developer can build its "tailor made" framework :)
What do you think?

**Comment by allevo** [comment]
I'm thinking the same thing. I'd like to keep the framework as light as possible. Only the features needed in order that `fastify` works.

Anyway, is there some feature that is not essential?

**Comment by allevo** [comment]
Closed for inactivity
