### ISSUE TITLE
[ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by screendriver** [fastify/fastify#3994]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.29.0

### Stopped working in version

4.0.0

### Node.js version

18.2.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Node.js running in Docker in an continuous integration environment

### 💥 Regression Report

Since the update to `fastify` `v4.0.0` we receive randomly:

```sh
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at onSendEnd (/builds/my/project/node_modules/fastify/lib/reply.js:493:7)
    at onSendHook (/builds/my/project/node_modules/fastify/lib/reply.js:427:5)
    at fallbackErrorHandler (/builds/my/project/node_modules/fastify/lib/error-handler.js:124:3)
    at handleError (/builds/my/project/node_modules/fastify/lib/error-handler.js:54:5)
    at onErrorHook (/builds/my/project/node_modules/fastify/lib/reply.js:594:5)
    at _Reply.Reply.send (/builds/my/project/node_modules/fastify/lib/reply.js:119:5)
    at defaultErrorHandler (/builds/my/project/node_modules/fastify/lib/error-handler.js:85:9)
    at handleError (/builds/my/project/node_modules/fastify/lib/error-handler.js:58:18)
    at onErrorHook (/builds/my/project/node_modules/fastify/lib/reply.js:594:5)
    at _Reply.Reply.send (/builds/my/project/node_modules/fastify/lib/reply.js:119:5)
    at /builds/my/project/node_modules/fastify/lib/wrapThenable.js:23:15
```

Sometimes it works ~~sometimes~~ most of the time not so I guess this is some kind of timing issue or race condition. All of our route handlers looks like this

```ts
{
    async handler(_request, reply) {
        return reply.type('application/json').send({
                foo: 'bar',
        });
    },
    method: 'GET'
};
```

or

```ts
{
    async handler(request, reply) {
        await delay(3000); // simulate slow responses

        return reply.type('application/json').headers({ my: 'header' }).send({ foo: 'bar' });
    },
    method: 'GET'
}
```

### Steps to Reproduce

Unfortunately I don't have any steps or repository to reproduce the issue. Our CI jobs are failing mostly all the time because of this. Locally I cannot reproduce the issue (I guess because my machine has more power and is faster)

**Comment by mcollina** [comment]
Thanks for reporting. Unfortunately we cannot help without a reproduction.

For this to trigger the behavior you are describing you would need to have something like:

```js
    async handler(request, reply) {
        somefunction().then(() => {
          reply.type('application/json').headers({ my: 'header' }).send({ foo: 'bar' })
        })
    },
```

Note that there is an `async` function that return undefined. Depending on how fast `somefunction()` is, the above code would fail or pass.

To avoid this problem, refactor your code to:

```js
    async handler(_request, reply) {
        await somefunction()
        return {
                foo: 'bar',
        };
    },
```

**Comment by screendriver** [comment]
> Unfortunately we cannot help without a reproduction.

I try to create something reproducible.

> Note that there is an async function that return undefined

We don't have this. All of our `handler()` functions returning what `reply` returns. 

```ts
async handler(request, reply) {
    return reply.status(200).send();
}
```

```ts
async handler(request, reply) {
    try {
        const data = await fs.readFile(pathToFile);
        return reply.status(200).type('image/png').send(data);
    } catch (error: unknown) {
        request.log.error(error);
        return reply.status(404).send();
    }
}
```

and so on. We also don't use any callbacks and no `.then` on Promises. Everything is `async` and `await`ed.

Is there any difference between `return reply.status(200).send();` and 

```ts
await reply.status(200).send();
return reply;
```

?

**Comment by AveryBibeau** [comment]
I've been running into this issue, but have not been able to produce it locally, only in a remote server. This error is thrown for me when calling `reply.redirect` after changing session data with @fastify/session.

The stack trace points to these two lines:
https://github.com/fastify/session/blob/master/lib/fastifySession.js#L164
https://github.com/fastify/session/blob/master/lib/session.js#L135

However, [modifying `reply.redirect` to return the reply](https://github.com/AveryBibeau/fastify/commit/0965ee8b204ff4ccd4f92b170f6170ab56bac639) fixed the issue for me completely. I did not experience this with v3 and as @screendriver  mentioned, maybe this is due to changes to returning replies with v4?

**Comment by climba03003** [comment]
> and so on. Do you have an idea why these changes does not have this issues and why it worked v3 without any issues?

Can you try if `4.0.3` fixed the problem? It may be cause by the same reason of https://github.com/fastify/fastify/pull/4021

**Comment by mcollina** [comment]
@AveryBibeau could you send a PR with https://github.com/AveryBibeau/fastify/commit/0965ee8b204ff4ccd4f92b170f6170ab56bac639 and a test? Thanks!

**Comment by mcollina** [comment]
I've opened a PR to implement this feature: https://github.com/fastify/fastify/pull/4037.

We should really do this change in fastify-sensible.
