### ISSUE TITLE
SyntaxError: Illegal return statement

### ISSUE THREAD

**Issue by lalexdotcom** [fastify/fastify#3995]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

It seems that the generated file `error-serializer.js`is not valid Javascript. The last line of the file is a return statement outside of a function.
```
SyntaxError: Illegal return statement
    at Object.../../node_modules/fastify/lib/error-serializer.js
[...]
```

Manually commenting the last line allow to launch even with Webpack.

When I run my code using ts-node, no error is done. When the project is bundled with Webpack, one way or another, the whole code is evaluated, and the SyntaxError is thrown by node...

I definitly have no idea why Webpack is evaluating this code so soon (I'm not familiar enough with its "magic"), but anyway, returning outside of a function is no valid JS and this Error could be thrown later in the code I guess...

### Steps to Reproduce

Main script
```typescript
import fastify from 'fastify';

(async () => {
    console.log('Start CLI !');

    const fast = fastify({ logger: true });
    await fast.listen({ port: 15987 });
})();
````

Webpack config (both ts-loader or swc-loader throw the error)
```typescript
const config: Configuration = {
    mode: 'development',
    target: 'node16',
    entry: './main.ts',
    context: FOLDER,
    module: {
        rules: [
            {
                test: /\.ts$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'swc-loader',
                    options: {
                        jsc: {
                            parser: {
                                syntax: 'typescript',
                            },
                            target: 'es2016',
                        },
                    },
                },
            },
            // {
            //     test: /\.ts$/,
            //     exclude: /(node_modules)/,
            //     use: {
            //         loader: 'ts-loader',
            //     },
            // },
        ],
    },
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
    },
};
```

### Expected Behavior

No error 0:-)

**Comment by climba03003** [comment]
It is a shame no one catch it when it land.

**Comment by mcollina** [comment]
This should be fixed. @lalexdotcom could you please update your dependencies and check if everything is working as expected?

**Comment by climba03003** [comment]
@mcollina it require `fastify` update and use the new `standalone` mode of `fast-json-stringify`

**Comment by lalexdotcom** [comment]
@mcollina The `error-serializer.js` seem fine now, but I get a `Error: Cannot find module 'fast-json-stringify/serializer'` error now... I didn't change anythin to my ts-node / webpack config, I will investigate on module resolve... (I'm on a npm workspace and not very familiar with it)

**Comment by lalexdotcom** [comment]
Aaaaand we're good! NPM workspace update handling is a bit weird, but with all dependencies up-to-date  it works...

Awesome work @mcollina & @climba03003 , you're as good and fast as fastify! 😁
(sorry for the joke, I know it's terrible 😅)
