### ISSUE TITLE
Allow payload to be modified in `onSend` hook

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#400]
https://github.com/fastify/fastify/pull/330#issuecomment-340032197

Blocker for #229.

**Comment by delvedor** [comment]
Just a nit, the payload **can** be modified, it cannot be replaced.

**Comment by StarpTech** [comment]
@delvedor @jsumners could we write down your analysis? Why do you think that we can't replace/modify the payload? It's much easier to write down our thoughts.

https://github.com/fastify/fastify/blob/master/lib/reply.js#L212

```js
fastify.addHook('onSend', (request, reply, payload, next) => {
  payload = { foo: 'bar' } // Not possible?
  payload.foo = 'bar' // Not possible?
  next()
})

```

**Comment by mcollina** [comment]
```js
payload = { something: 'else' }
```

does not work atm

the best API would be:

``` js
fastify.addHook('onSend', (request, reply, payload, next) => {
  next(null, { foo: 'bar' })
})
```

Or with async/await

```js
fastify.addHook('onSend', async (request, reply, payload) => {
  return { foo: 'bar' }
})
```

This probably needs quite a rework.

**Comment by delvedor** [comment]
Closed by https://github.com/fastify/fastify/pull/474
