### ISSUE TITLE
Documentation and type defs mismatch schemaController bucket factory implementation

### ISSUE THREAD

**Issue by avin-kavish** [fastify/fastify#4002]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

https://www.fastify.io/docs/latest/Reference/Server/#schemacontroller

In the above docs `addSchema` is mentioned as a method of the bucket. According to the latest version of `schema-controller.js`, it is `add`.

In addition, line 147 of fastify.d.ts mentions `addSchema` . Whereas the current implementation is more like,

```
  schemaController?: {
    bucket?: (parentSchemas?: unknown) => {
      add(schema: unknown): void;
      getSchema(schemaId: string): void;
      getSchemas(): Record<string, unknown>;
    };
```

Checked both version 3.29 and 4.0, issue is present.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by avin-kavish** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue?

Hey, I'm a bit tight on time, so I'm glad to see it got picked up :)
