### ISSUE TITLE
Add integration CI step

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#4006]
> This IS an issue in fastify. #3996 introduced a **production dependency** on fast-json-stringify (see [these lines](https://github.com/fastify/fastify/pull/3996/files#diff-f6017ca412ba95771e5839b4b2cbd40b2d5cdd11d698991016945639ba54b6b5R6-R7)), and more to that, to a **specific version** (4.0.1) of that library.

Thank you for linking to the actual code. We _**definitely**_ want to add direct dependencies to the dependencies list.

I think we really need a CI step that does:

1. `pnpm install --production` or `npm install --legacy-deps --legacy-peer-deps`
2. `node some_basic_server.js`
3. `curl /several_endpoints`

That should catch these cases in the future as neither of the options in step one will install the transitive dependency in such a fashion that Fastify itself will have access to it.

_Originally posted by @jsumners in https://github.com/fastify/fastify/issues/3998#issuecomment-1153824043_

**Comment by marcelfranca** [comment]
Hi! I'll be taking this issue
