### ISSUE TITLE
Server will also listen on a random port when calling app.listen({path: 'foo.sock'})

### ISSUE THREAD

**Issue by segevfiner** [fastify/fastify#4007]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.2

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

If I pass to `listen` only a `path` to listen on, the server will also listen on a random port.

I think this happens due to this code here: https://github.com/fastify/fastify/blob/78adc9cc76f26ad2461d15103452f64487d806df/lib/server.js#L297-L299

P.S. I got a deprecation warning even for `app.listen(option, (err) => { ... })` which AFAIK should not be deprecated.

### Steps to Reproduce

```js
const Fastify = require('fastify');
const app = Fastify({logger: true});
app.listen({ path: 'foo.sock' });
```

### Expected Behavior

It only listens on `path`.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by segevfiner** [comment]
Why not? Just need to figure out how to correctly fix this without introducing a bug in another case first. 😛

**Comment by segevfiner** [comment]
Hmm. Debugging it a bit, it seems to happen from this code: https://github.com/fastify/fastify/blob/78adc9cc76f26ad2461d15103452f64487d806df/lib/server.js#L44-L47

If I set `host` to an empty string, then it seems to only listen on `path`. I wonder what's the right condition here. I'm not entirely sure what is all that `hasOwnProperty` stuff about?

**Comment by jsumners** [comment]
There's a lot of hackery in there to retain the deprecated variadic signature variations. It's not fun and is a big reason for this deprecation: settle on a simple interface. The linked snippet in particular is: "pull `host` from the passed in `listenOptions` _if that object has the property_, but if `listenOptions` _does not_ have the `host` property, add it."

It's likely the fix here is as easy as "if `listenOptions` does not have `host` but _does_ have `path`, then don't set `host`". However, pay attention to the `normalizeListenArgs` function. That is the thing causing a lot of this headache.
