### ISSUE TITLE
reply send empty

### ISSUE THREAD

**Issue by SudoDios** [fastify/fastify#4014]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

hello developers.
i update fastify to version 4.0.2.
And after the update, this problem arose for me :
```javascript
fastify.get('/group', async (req,res) => {

        const category = await fastify.mongo.client.db('rbanoo').collection('user')
        category.findOne().then((result) => {
            res.send(result)
        })

    })
```
in this code res.send() is empty without error.

**Comment by kyranet** [comment]
Yes - you need `return res;` at the end, you can see the changes in the [Medium post](https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e) :)

**Comment by SudoDios** [comment]
Very nice.
Thanks.
