### ISSUE TITLE
Empty response when validation is used

### ISSUE THREAD

**Issue by vasilianeugen** [fastify/fastify#4017]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.2

### Plugin version

3.0.1

### Node.js version

16.14.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I have a schema that previously worked on Fastify 3.x

export const userLogInSchema: FastifySchema = {
  tags: ['user'],
  description: '[Cognito] - User login',
  body: S.oneOf([S.ref('UserLoginRequest'), S.ref('RefreshTokenRequest')]),
  response: {
    200: S.oneOf([S.ref('AuthResponse'), S.ref('MFASetupResponse'), S.ref('MFALoginResponse')])
  }
}

I get now an empty JSON as response {}
If I remove the response validation part, the then I get again a value as it worked before. 
The response is valid as it is conform to the MFALoginResponse schema. Anyway if there is a validation problem there should be an validation error.

The S is from the 'fluent-json-schema' lib

### Steps to Reproduce

Example found in description.

In handler code the JSON returned value is correct and I use reply.send([JSON]) to send it. 

### Expected Behavior

The endpoint returns the JSON value that is put in reply.send()

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by vasilianeugen** [comment]
It seems that the use of oneOf is response is the problem. If I use only one validation it works. Also other endpoints that have simple response validations work correctly.

This one works:
export const userLogInSchema: FastifySchema = {
  tags: ['user'],
  description: '[Cognito] - User login',
  body: S.oneOf([S.ref('UserLoginRequest'), S.ref('RefreshTokenRequest')]),
  response: {
   200: S.ref('MFALoginResponse')
  }
}

**Comment by Eomm** [comment]
To replicate your issue we need your schemas or a minimal reproducible code that we can run.
We do not have the whole schema here:

```
body: S.oneOf([S.ref('UserLoginRequest'), S.ref('RefreshTokenRequest')]),
response: {
200: S.oneOf([S.ref('AuthResponse'), S.ref('MFASetupResponse'), S.ref('MFALoginResponse')])
```

the new version adheres more strictly to the JSON schema spec, so I suspect that you have some `$id`s to update

**Comment by vasilianeugen** [comment]
My first schema is 

```
export const mfaLoginResponseJsonSchema = S.object()
    .id('MFALoginResponse')
    .prop('ChallengeName', S.string())
    .prop('Session', S.string()) 
```

And when I looked into code it seems that if the first schema validates, it dose and retunrs `{}` 
**MFALoginResponse** dose not have required fields so I guess it validates and returns `{}` because of that.

```
 function main (input) {
      let json = ''      
            if(ajv.validate("MFALoginResponse", input))
              json += anonymous0(input)
          
            else if(ajv.validate("AuthResponse", input))
              json += anonymous1(input)
          
          else throw new Error(`The value ${JSON.stringify(input)} does not match schema definition.`)
        
      return json
    }
```
It would be good that for `oneOf` we would not have` if ... else` but instead check the next schema in case the first one returns empty json` {}` and so on

**Comment by Eomm** [comment]
> Previously in 3.x it worked correctly and returned the schema that matched.

It was a bug, actually 😄 the old v2 (included in fastify v3) returns all the properties regardless of the schema

Here an example:
https://runkit.com/embed/dotem4i1p7gl

> MFALoginResponse dose not have required fields so I guess it validates and returns {} because of that.

Yes, indeed

> It would be good that for oneOf we would not have if ... else but instead check the next schema in case the first one returns empty json {} and so on

Not sure about it. What if a user would like an empty object instead?
I think you need to define your schemas to don't overlap them, or you should arrange your `oneOf` array to keep the schema with fewer constraints in the latter position.

This behaviour is described on the docs: https://github.com/fastify/fast-json-stringify#anyof-and-oneof

> // without "required" validation any object will match

---

Talking about the standard, the `oneOf` keyword must match only one element of the array, so we should think if we must run all the validations and throw an error accordingly

As ajv explains:

> The data is valid if it matches exactly one JSON Schema from this array. Validators have to validate data against all schemas to establish validity according to this keyword.

https://ajv.js.org/json-schema.html#oneof

My opinion on that, is that fast-json-stringify is not a validator

**Comment by Eomm** [comment]
Things have changed and fast-json-stringify has evolved.

Closing as stale

Feel free to open a new issue with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)
