### ISSUE TITLE
Stream replies not working when async preHandler hook is defined.

### ISSUE THREAD

**Issue by wieringen** [fastify/fastify#4018]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Node.js version

16.0.0

### Operating system

Mac OS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.5

### Description

When defining an async preHandler, all routes with an async handler returning a stream stop working. In the example below you will notice that after calling /notworking the response body is empty and the console shows an error.

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
  at new NodeError (node:internal/errors:372:5)
  at write_ (node:_http_outgoing:748:11)
  at ServerResponse.write (node:_http_outgoing:707:15)
  at Readable.ondata (node:internal/streams/readable:754:22)
  at Readable.emit (node:events:527:28)
  at Readable.read (node:internal/streams/readable:527:10)
  at flow (node:internal/streams/readable:1011:34)
  at emitReadable_ (node:internal/streams/readable:592:3)
  at processTicksAndRejections 

### Steps to Reproduce

```js
import fastify from "fastify";
import { Readable } from 'stream'

const api = fastify({
  logger: true
})

api.addHook('preHandler', async () => {
  console.log("do async stuff")
})

api.post('/notworking', async (req, reply) => {
  const s = new Readable();
  s.push('not working');
  s.push(null);
  reply.send(s);
});

api.post('/working', function (req, reply) {
  const s = new Readable();
  s.push('working');
  s.push(null);
  reply.send(s);
});

api.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
  console.log("listen")
});
```

### Expected Behavior

The stream is returned as normal.

**Comment by mcollina** [comment]
You can:

```js
import fastify from "fastify";
import { Readable } from 'stream'

const api = fastify({
  logger: true
})

api.addHook('preHandler', async () => {
  console.log("do async stuff")
})

api.post('/working', async (req, reply) => {
  const s = new Readable();
  s.push('not working');
  s.push(null);
  reply.send(s);
  return reply
});

api.post('/workingAgain', async function (req, reply) {
  const s = new Readable();
  s.push('working');
  s.push(null);
  return s
});

api.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
  console.log("listen")
});
```

This is a documented semver-major change documented in https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e.

**Comment by mcollina** [comment]
That should totally not happen, you have found a nice bug!

**Comment by climba03003** [comment]
> ```js
> reply.
> ```

Why return `reply.` ? It should be syntax error.

**Comment by jcbbb** [comment]
@climba03003 Yeah, it was a typo.

**Comment by mcollina** [comment]
I confirm this is crashing Fastify and it should not happen.
