### ISSUE TITLE
How to throw 404 error in router?

### ISSUE THREAD

**Issue by wong2** [fastify/fastify#402]
I've setup a 404 handler with `setNotFoundHandler`

```
fastify.setNotFoundHandler((request, reply) => {
    reply.code(404).type('text/html').send('Not Found')
})
```

Now my question is, how can I throw a 404 error in router to use this handler?

```
fastify.get('/:uid', async (request, reply) => {
  const user = await User.findById(request.params.uid)
  if (!user) {
    // ?? how can I throw a 404 error here to use the previous 404 handler?
  }
})
```

**Comment by mcollina** [comment]
The not found handler is triggered when no route matches, you need to return a 404 manually inside your route if a user cannot be found.

**Comment by delvedor** [comment]
In addition to what @mcollina said, if you have the exact same code for all your 404s, you can do something like the following:
```js
fastify.decorate('notFound', (request, reply) => {
  reply.code(404).type('text/html').send('Not Found')
})

fastify.setNotFoundHandler(fastify.notFound)

fastify.get('/:uid', async (request, reply) => {
  const user = await User.findById(request.params.uid)
  if (!user) {
    return fastify.notFound(request, reply)
  }
})
```

**Comment by sebdeckers** [comment]
Using #404 and [`npm:http-errors`](https://www.npmjs.com/package/http-errors) you'd be able to do:

```js
const { NotFound } = require('http-errors')
fastify.get('/:uid', async (request, reply) => {
  const user = await User.findById(request.params.uid)
  if (!user) {
    throw new NotFound()
  }
})
```

**Comment by wong2** [comment]
@sebdeckers nice!

**Comment by codyzu** [comment]
In case anyone stumbles upon this when looking to generate 404 responses, fastify now has a `reply.callNotFound()`, https://www.fastify.io/docs/latest/Reply/#callnotfound

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

This issue is **6 years old**
