### ISSUE TITLE
Provide a one-line log format as a pino transport

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#4027]
I would like to customize this log line,
```
[11:55:06.743] INFO: incoming request
```

Ideally I would like to have this,

```
11:55:06.743 - info - GET /my/route/
```

_Originally posted by @avin-kavish in https://github.com/fastify/fastify/discussions/4026_

---

We should either build a custom config on top of pino-pretty or build a new [pino transport](https://getpino.io/#/docs/transports)

**Comment by TommyDew42** [comment]
Hi! I’ll take this one!

**Comment by jm61** [comment]
yes a bit like the logs in morgan logger very concise and readable!

**Comment by TommyDew42** [comment]
For this, we will have a pino transport that format message as `<time> - <level> - <message>` and change the logging message (e.g. [this one](https://github.com/fastify/fastify/blob/4139133f66d979d1c1bf73d3f30031998f8bfcc4/lib/route.js#L418)) to:
```js
childLogger.info({ req: request }, `${request.method} ${request.url}`)
```

Does it make sense to you? @mcollina

**Comment by mcollina** [comment]
It's probably better to leave that line unchanged and do:

```
11:55:06.743 - info - GET /my/route/ - incoming message
```

**Comment by TommyDew42** [comment]
OK! So I assume how we obtain `"GET /my/route/"` will be done in the pino transport, from `options.req`.

But I am still a bit confused the feature requirement. Do we only want this new one-line log format when `transport.target` is set to `"pino-pretty"`?

**Comment by mcollina** [comment]
This should either be some config for pino-pretty or a new module altogether

**Comment by avin-kavish** [comment]
Can we just have the option to customize the log format fully? Like in [morgan](https://github.com/expressjs/morgan#using-format-string-of-predefined-tokens)

**Comment by TommyDew42** [comment]
@mcollina I have been looking at pinojs documentation these days and want more guidelines on this. 😃 

> some config for pino-pretty 

Does it mean we wanna have a separate pino-transport file where we pre-config the pino-pretty's [options](https://github.com/pinojs/pino-pretty#options) to format the log?

----
> or a new module altogether

And I assume this just mean we write a pino-transport from scratch?

**Comment by jsumners** [comment]
I would rather this be a new module than adding more complexity into pino-pretty. What _I_ assume the original requestor wants is https://en.m.wikipedia.org/wiki/Common_Log_Format

**Comment by climba03003** [comment]
> What _I_ assume the original requestor wants is https://en.m.wikipedia.org/wiki/Common_Log_Format

I think we need some discussion on what and how to show the log.
We can achieve the above mentioned log format for `combine request and response` display.
But we lack of information for the custom log, for example "how to display extra attributes", "how to display user custom log"?

**Comment by TommyDew42** [comment]
@climba03003 

If `<time> - <log level> - <method> <route>` is what we want, I think we can just change the default log message to it.

If we want to implement the [common log format](https://en.m.wikipedia.org/wiki/Common_Log_Format), maybe we can do the following?
```js
const fastify = require('fastify')({
  logger: "common-log-format"
})
```

Users can always implement their own pino transport if they want to display more attributes.

**Comment by mcollina** [comment]
Let's not do that. This new transport should:

1. require no modification to Fastify
2. be on another module that's part of this org

**Comment by TommyDew42** [comment]
Ah I see. Just like what you said: pino-colada but maintained by us.

Do you have a greater picture/plan on the new module except the things we wanna achieve in this issue? It seems to me the things we wanna achieve in this issue isn't worth creating a standalone module. But ofc if we will extend the functionalities in the future then yes it's definitely worth it!

**Comment by jsumners** [comment]
Make `@fastify/common-log-transport` and the issue is solved.

**Comment by avin-kavish** [comment]
I think common log format is specific to http request logging, not sure how it would handle when a user logs a custom message.

**Comment by TommyDew42** [comment]
@jsumners @mcollina 
How should we start the work? Do we create a new module first then I can fork and work on it?

**Comment by TommyDew42** [comment]
@mcollina @climba03003 @jsumners 
Would like to make sure we are aligned before starting any work.

The [one-line-logger](https://github.com/fastify/one-line-logger) will be a module on top of [pino-pretty](https://github.com/pinojs/pino-pretty), similar to [pino-colada](https://github.com/lrlna/pino-colada).
Let's start with sth simple before we making it follow the [common log format](https://en.m.wikipedia.org/wiki/Common_Log_Format), following Matteo's suggestion:
```
11:55:06.743 - info - GET /my/route/ - <incoming message>
```

But I got a question: what does `<incoming message>` here refer to?

**Comment by climba03003** [comment]
> what does <incoming message> here refer to?

@TommyDew42 

The format is

```
HH:mm:ss.SSS - <level> - <method> <route path> - <message>
```

The message is comes from `pino.log(<message>)`

**Comment by jsumners** [comment]
I'm retreating from this issue. I already maintain too many prettifiers.

**Comment by TommyDew42** [comment]
How do we change the logger of a fastify instance after it is created?

```js
const plugin = (fastify, options, next) => {
  fastify.decorate('log', log); // The decorator 'log' has already been added!
  next();
};
```

**Comment by mcollina** [comment]
You don't.

**Comment by Eomm** [comment]
> How do we change the logger of a fastify instance after it is created?

Users must set the pino instance by themself:

eg:
```
fastify({
  logger: require('pino-one-liner')
})
```

**Comment by mcollina** [comment]
That's not the expected API, what should be done is:

```js
fastify({
  logger: {
    transport: 'pino-one-liner'
  }
})
```

or similar

**Comment by TommyDew42** [comment]
An update on the work. Some problems I ran into:
1. The log are always printed with the object passed in. Not sure if it is from pino or pino-pretty. Looking at their source code.
    ![Screenshot 2022-07-26 at 12 00 54 AM](https://user-images.githubusercontent.com/46992350/180823304-d99aafd5-3a75-43aa-91db-4b9d12e1c1fa.png)
2. Trying to write unit test with getting output from a stream but somehow it didn't work:
```js
test("hello", (t) => {
  const splitStream = split(JSON.parse);

  splitStream.on("data", (line) => {
    // do checking
    
    // but the on data listener doesn't work. nth is done
    // not even console.log(line)
  });

  const server = fastify({
    // destination gets passed to pino-pretty
    logger: pino(oneLineLogger({ destination: splitStream })),
  });

  server.get("/", () => "hello world");

  server.inject(
    {
      method: "get",
      url: "/",
    }
  );
});
```

Will keep looking into them

**Comment by TommyDew42** [comment]
I have struggled with writing unit tests. I would like to use our one-line-logger in a fastify instance and inject a request to it. 

How can I capture the log of the server? I tried to use `sonic-boom` but it doesn't have a `"data"` listener which allow us to read the data.

**Comment by TommyDew42** [comment]
Found we can use `Writable` to capture the log! Will follow the [pattern](https://github.com/pinojs/pino-pretty/blob/68f22d4548297dcb83b7d675dd56c5f2cd5df7ac/test/basic.test.js#L54-L65) in `pino-pretty` to write unit tests.

**Comment by TommyDew42** [comment]
Say we have this now:
```js
fastify({
  logger: {
    transport: 'one-line-logger'
  }
})
```

What unit tests should we include?
Here are what I can think of/get from searching the codebase:
* log when server started
* the log when requests of different methods come in and response are sent
* log from a child logger
* 404 error
* error log
* url rewrite log
* log when double response.send()
* wrapThenable error log: 'Promise errored, but reply.sent = true was set'
* a more couple of errors related to Stream
