### ISSUE TITLE
Schema errors since Fastify 4

### ISSUE THREAD

**Issue by qqilihq** [fastify/fastify#4028]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.6

### Description

First: Thank you for your work on Fastify 4. The changes look definitely promising (especially looking forward to the type providers which should make our code much cleaner) and I have just upgraded an existing project to Fastify 4.

During upgrading, I encountered the following errors related to the schema which caused me quite some head banging:

* `schema with key or id "…" already exists`
* ` "…" resolves to more than one schema`

### Steps to Reproduce

While I cannot give our entire schema here, I try to show the (as I think) relevant parts which contribute to this issue. We define our schema using typebox, and after upgrading our dependencies I had to apply [these](https://github.com/fastify/fastify/issues/3421) suggestions. Also we use `@fastify/swagger`.

```typescript
export const File = Type.Object(
  {
    _id: Type.Ref(ObjectId),
    creator: Type.Ref(ObjectId),
    owner: Type.Ref(ObjectId),
    // .. further irrelevant properties omitted
  },
  { $id: 'File' }
);

export type File = Static<typeof File>;

export const Article = Type.Object(
  {
    _id: Type.Ref(ObjectId),
    imageBig: Type.Union([Type.Ref(File), Type.Null()]),
    imageSmall: Type.Union([Type.Ref(File), Type.Null()]),
    // .. further irrelevant properties omitted
  },
  { $id: 'Article' }
);

export type Article = Static<typeof Article>;

export const ObjectId = Type.String({
  pattern: '[0-9a-f]{24}',
  $id: 'ObjectId',
});

export type ObjectId = Static<typeof ObjectId>;
```

I load these through a plugin as follows:

```typescript
import fastifyPlugin from 'fastify-plugin';
// .. imports

export default fastifyPlugin((fastify) => {
  fastify.addSchema(ObjectId);
  fastify.addSchema(File);
  fastify.addSchema(Article);
  return Promise.resolve();
});
```

The crucial parts:
* `File` has more than one `$ref` to `ObjectId`
* `Article` has more than one `$ref` to `File`

When starting the server, I would either see `schema with key or id "ObjectId" already exists` or `"File" resolves to more than one schema`. The behavior was unfortunately not really systematic or deterministic, and depended on the presence or absence of other (seemingly unrelated) routes.

After spending several hours, I came up with the following fixes which got the back to running:

1. In fastify's `schema-controller.js` copy the schemas in `getSchemas`:
   ```diff
   diff --git a/node_modules/fastify/lib/schema-controller.js b/node_modules/fastify/lib/schema-controller.js
   index 1484019..98aeafe 100644
   --- a/node_modules/fastify/lib/schema-controller.js
   +++ b/node_modules/fastify/lib/schema-controller.js
   @@ -59,7 +59,7 @@ class SchemaController {
      }
    
      getSchemas () {
   -    return this.schemaBucket.getSchemas()
   +    return JSON.parse(JSON.stringify(this.schemaBucket.getSchemas()))
      }
    
      // Schema Controller compilers holder
   ```

2. In `fast-json-stringify`, `$refs` seem to get dereferenced to full schema objects, but when occuring several times the duplicate `$id` properties lead to the issue described above. My (very dirty) fix was to simply strip out all `$id`, but I'm sure that's not the right way to do it:
   ```diff
   diff --git a/node_modules/fast-json-stringify/index.js b/node_modules/fast-json-stringify/index.js
   index 1952905..484ceb7 100644
   --- a/node_modules/fast-json-stringify/index.js
   +++ b/node_modules/fast-json-stringify/index.js
   @@ -964,6 +964,21 @@ function buildValue (locationPath, input, location) {
              // Ajv does not support js date format. In order to properly validate objects containing a date,
              // it needs to replace all occurrences of the string date format with a custom keyword fjs_date_type.
              // (see https://github.com/fastify/fast-json-stringify/pull/441)
   +
   +          // fix for --
   +          // * schema with key or id "…" already exists
   +          // * reference "…" resolves to more than one schema
   +          function stripId(obj) {
   +            delete obj.$id;
   +            Object.entries(obj).forEach(([_key, value]) => {
   +              if (typeof value === 'object') {
   +                stripId(value);
   +              }
   +            });
   +            return obj;
   +          }
   +          stripId(location.schema);
   +
              const extendedSchema = clone(location.schema)
              extendDateTimeType(extendedSchema)
      ```

Various code comments and issues (such as [this](https://github.com/fastify/fast-json-stringify/issues/242)) suggest issues due to mutation of the schema, and I guess my issue is also caused by this.

I would love to provide a runnable example, however I was not really able to reproduce it within a manageable amount of code yet. If there's any more details I can provide, please let me know. On the other hand, I will be happy for any feedback, suggestions, etc.

**Comment by jsumners** [comment]
I don't use the schema container you are referencing. So I don't know what you're stating. It sounds like either:

1. You have duplicate schema ids.
2. You are registering the same schema multiple times under the assumption each will be registered in a different schema encapsulation context.

A reproduction repo would be most helpful.

**Comment by jsumners** [comment]
@fastify/typescript 

cc: @sinclairzx81

**Comment by climba03003** [comment]
It is not related to `TypeScript` and actually related to how `fast-json-stringify` treat the `$ref` key.
If you move the `response` to `querystring`, that means it used by `ajv`.
The server can be started successfully.

Minimal repro extracted from https://github.com/qqilihq/fastify-issue-4028
```js
import Fastify from "fastify";

const fastify = Fastify();
fastify.addSchema({
  $id: "ObjectId",
  type: "string",
});
fastify.addSchema({
  $id: "File",
  type: "object",
  properties: {
    _id: { $ref: "ObjectId" },
    name: { type: "string" },
    owner: { $ref: "ObjectId" },
  },
});

fastify.get("/", { schema: { response: { $ref: "File" } } }, () => {});

await fastify.ready();
```

**Comment by sinclairzx81** [comment]
@jsumners I had a quick look at this, and wasn't able to reproduce the duplicate ID error through Fastify, so for example, the following is ok.

```typescript
import { Type } from '@sinclair/typebox'
import Fastify from 'fastify'

const fastify = Fastify({
    ajv: {
        customOptions: {
            keywords: ['kind', 'modifier']
        }
    }
})

const File = Type.Object({
    name: Type.String(),
    size: Type.Integer()
}, { $id: 'File' })

fastify.addSchema(File)

fastify.post('/', {
    schema: {
        body: Type.Object({
            image: Type.Union([Type.Ref(File), Type.Null()]),
        })
    }
}, (req, res) => res.send('ok'))

fastify.listen({ port: 5000 })
```
But was able to get `fast-json-stringify` throwing duplicate ID errors if configuring both `ajv` and the `schema` options (which maybe indirectly configured somehow). I believe the preference is to configure `schema` only.
```typescript
import { Type } from '@sinclair/typebox'
import Serialize from 'fast-json-stringify'

const File = Type.Object({
    name: Type.String(),
    size: Type.Integer()
}, { $id: 'File' })

const T = Type.Object({
    image: Type.Union([Type.Ref(File), Type.Null()]),
})

Serialize(T, { 
    schema: { File },
    // ajv: { schemas: { File } } // uncommenting this line produces the error
                                  //
                                  // Error: schema with key or id "File" already exists
})
```
Not sure if the second example might be a clue as to what error might be occurring, but for all intents and purposes, the reference external schema should be working ok (as per the users example).

Hope that helps
S

**Comment by qqilihq** [comment]
First: Thank you all for your efforts!

Unfortunately, it still doesn't work for me. I have updated the [repro repo](https://github.com/qqilihq/fastify-issue-4028) above, and I still get:

```
FastifyError [Error]: Failed building the serialization schema for HEAD: /article, due to error reference "ObjectId" resolves to more than one schema
    at Boot.<anonymous> (/Users/pk/Desktop/fastify-schema-issue/node_modules/fastify/lib/route.js:318:21)
    at Object.onceWrapper (node:events:509:28)
    at Boot.emit (node:events:402:35)
    at /Users/pk/Desktop/fastify-schema-issue/node_modules/avvio/boot.js:160:12
    at /Users/pk/Desktop/fastify-schema-issue/node_modules/avvio/plugin.js:276:7
    at done (/Users/pk/Desktop/fastify-schema-issue/node_modules/avvio/plugin.js:201:5)
    at check (/Users/pk/Desktop/fastify-schema-issue/node_modules/avvio/plugin.js:225:9)
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8) {
  code: 'FST_ERR_SCH_SERIALIZATION_BUILD',
  statusCode: 500
}
```

**Comment by qqilihq** [comment]
@mcollina Thanks for the reply. Actually (knowingly) I define it only once end then use $ref to refer to it, e.g. here:

https://github.com/qqilihq/fastify-issue-4028/blob/main/src/schemas/file.schema.ts#L6

If there's something I'm misunderstanding fundamentally, I'll be happy for any hint :-)

**Comment by qqilihq** [comment]
```
git clone https://github.com/qqilihq/fastify-issue-4028.git
cd fastify-issue-4028
yarn
yarn start
```

**Comment by mcollina** [comment]
The problem is caused by `exposeHeadRoutes: true`, I think we are not resetting something correctly.

**Comment by mcollina** [comment]
https://github.com/fastify/fast-json-stringify/pull/470 solves the problem. Update your deps, it work for me now!
