### ISSUE TITLE
Routes with period next to param confuse route parser

### ISSUE THREAD

**Issue by tlhunter** [fastify/fastify#4030]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.29.0

### Stopped working in version

4.0.3

### Node.js version

18.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux 5.15.23-051523-generic #202202110435 SMP Fri Feb 11 09:38:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 💥 Regression Report

This seems to be an issue with `find-my-way`. The following two routes worked with Fastify v3 but do not with v4:

```
/v1/foo/:code.png
/v1/foo/:code
```

The error is as follows:

```
/home/tlhunter/foo/server/node_modules/find-my-way/index.js:277
      throw new Error(`Method '${method}' already declared for route '${path}' with constraints '${JSON.stringify(constraints)}'`)
            ^

Error: Method 'GET' already declared for route '/v1/qr/:' with constraints '{}'
    at Router._on (/home/tlhunter/foo/server/node_modules/find-my-way/index.js:277:13)
    at Router.on (/home/tlhunter/foo/server/node_modules/find-my-way/index.js:136:10)
    at Object.addNewRoute (/home/tlhunter/foo/server/node_modules/fastify/lib/route.js:257:18)
    at Object.route (/home/tlhunter/foo/server/node_modules/fastify/lib/route.js:196:19)
    at Object._route [as route] (/home/tlhunter/foo/server/node_modules/fastify/fastify.js:268:27)
    at default (file:///home/tlhunter/foo/server/lib/routes/v1/qr.mjs:37:10)
    at file:///home/tlhunter/foo/server/lib/server.mjs:81:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

### Steps to Reproduce

Create a file with the following content and execute it against Fastify v3 and v4:

```js
import fastify from 'fastify';
export const server = fastify();

server.route({
  method: 'GET',
  url: '/v1/foo/:code.png',
  handler: async () => {
    return 'first';
  },
});

server.route({
  method: 'GET',
  url: '/v1/foo/:code',
  handler: async () => {
    return 'second';
  },
});

server.listen(8000, '0.0.0.0', (err, address) => {
  console.log(err, address);
});
```

### Expected Behavior

I would expect two routes to be registered, one that would capture `GET /v1/foo/hello` and another that would capture `GET /v1/foo/hello.png`.

**Comment by climba03003** [comment]
I think this use-case should be a valid one.
And it can achieve by the workaround, changing the `param` to `regex`.

@ivan-tymoshenko wdyt?

**Comment by ivan-tymoshenko** [comment]
It started work differently after this PR https://github.com/delvedor/find-my-way/pull/237.
 - `/:code.png` is parsed using a regular expression `/^(.*?).png$/`.
 - `/:code` is parsed as non regexp param
They are both parametric nodes now that have `/v1/foo/:` template.

I will think about the special case when we have different static ending in the multi-parametrical nodes. Technically it's possible to support.
