### ISSUE TITLE
process.env.VALUE not work

### ISSUE THREAD

**Issue by slemac** [fastify/fastify#4033]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Node.js version

16.15.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

is not reading system environment variables.
This problem happens if I try to access it via request.log.info but if I use console.log it works fine.
vgr:  request.log.info("JWT:", process.env.JWT_PRIVATE_KEY); => no work
vgr.: console.log("JWT 2:", process.env.JWT_PRIVATE_KEY); => work! 

### Steps to Reproduce

1)  set environment variable on system: set JWT_PRIVATE_KEY=JWT_PRIVATE_KEY_VALUE
2)  create server fastify with logger in true
3) read through req.log.info the previously created environment variable
[test-fastify-js.zip](https://github.com/fastify/fastify/files/8927678/test-fastify-js.zip)

### Expected Behavior

read the environment variable previously set on the system.

**Comment by climba03003** [comment]
Please provide the repro in `Github Pepository`, `Github Gist` or `write it inside the issue`.
It is not a good idea for developer to download a anonymous zip file.

**Comment by mcollina** [comment]
This is normal and expected. Fastify logger is pino, and pino does not support the self-concatenation and variadic arguments behavior.

if you want you can use:

```js
request.log.info(`JWT: ${process.env.JWT_PRIVATE_KEY}`); 
```

or

```js
request.log.info("JWT: %s", process.env.JWT_PRIVATE_KEY); 
```
