### ISSUE TITLE
Deprecation warning descriptions in docs/Guides/Database.md

### ISSUE THREAD

**Issue by phasetr** [fastify/fastify#4036]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

(I posted a related issue in [fastify / fastify-mysql](https://github.com/fastify/fastify-mysql/issues/96).)
In the newest [docs/Guides/Database.md](https://github.com/fastify/fastify/blob/main/docs/Guides/Database.md), we have a description `fastify.listen(3000, err => {`, but this leads a deprecation warning, like

>FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.

This should be `fastify.listen({ port: 3000 }, err => {`. I checked only a mysql code, but other database codes will raise the same warnings.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by phasetr** [comment]
I see. I will make a pull request.

**Comment by phasetr** [comment]
I send a pull request and it is merged.
