### ISSUE TITLE
Fastify ValidationResult type and AJV v8 ErrorObject mismatch

### ISSUE THREAD

**Issue by avin-kavish** [fastify/fastify#4045]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20

### Description

AJV error object is like this,

```ts
export interface ErrorObject<K extends string = string, P = Record<string, any>, S = unknown> {
  keyword: K
  instancePath: string
  schemaPath: string
  params: P
  // Added to validation errors of "propertyNames" keyword schema
  propertyName?: string
  // Excluded if option `messages` set to false.
  message?: string
  // These are added with the `verbose` option.
  schema?: S
  parentSchema?: AnySchemaObject
  data?: unknown
}
```

Fastify type is like this,
```ts
export interface ValidationResult {
  keyword: string;
  dataPath: string;
  schemaPath: string;
  params: Record<string, string | string[]>;
  message: string;
}
```

In version 3 of Fastify (and the AJV version it used), AJV errors were directly assignable to ValidationResult type and vice verca.
But in v4 the types mismatch. looks like AJV no longer has the `dataPath` key. It was changed [here](https://github.com/ajv-validator/ajv/commit/242631a8fb5c8b3d196d79333c8956c0ab5675ea).

### Steps to Reproduce

Try this in v3 and v4 projects.

```ts
import { ValidationResult } from 'fastify'
import { ErrorObject } from 'ajv'

const foo = {} as ErrorObject

const bar = {} as ValidationResult

const baz: ErrorObject = bar

const bass: ValidationResult = foo
```

### Expected Behavior

Edit:
Maybe fastify is internally converting the ErrorObject to a ValidationError. In that case, it wouldn't be an issuue. But it maybe the case that, fastify is not handling this new ErrorObject properly.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by avin-kavish** [comment]
Adding more info for whoever picks this up, in `lib/context.js` it looks like `defaultSchemaErrorFormatter` is using `instancePath` so it's the type defs that are outdated.

**Comment by alex-laz** [comment]
#4066
