### ISSUE TITLE
wrong log output when using inject and console.log

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4046]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.x

### Stopped working in version

4.x

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### 💥 Regression Report

Opening (and closing) this issue, I would like to share a finding useful for devs.

A sample script could return the wrong order output:

```
const fastify = require('fastify')
const app = fastify({ logger: true })

app.get('/', function (request, reply) { return 'hello ' })

app.inject('/', (err, res) => {
  console.log(res.payload)
})
```

V3 output:

```
{"level":30,"time":1655645389704,"pid":39342,"hostname":"MSpigolon-ITMAC21","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
{"level":30,"time":1655645389706,"pid":39342,"hostname":"MSpigolon-ITMAC21","reqId":"req-1","res":{"statusCode":200},"responseTime":1.9972500801086426,"msg":"request completed"}
hello 
```

V4 output:

```
{"level":30,"time":1655645381172,"pid":39296,"hostname":"MSpigolon-ITMAC21","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
hello 
{"level":30,"time":1655645381176,"pid":39296,"hostname":"MSpigolon-ITMAC21","reqId":"req-1","res":{"statusCode":200},"responseTime":3.9191670417785645,"msg":"request completed"}
```

### Steps to Reproduce

```
// npm i old@npm:fastify@3
// npm i old-pino@npm:pino@6

'use strict'
const fastify = require('fastify')
//const fastify = require('old')
const app = fastify({ logger: true })

app.get('/', function (request, reply) { return 'hello ' })

app.inject('/', (err, res) => {
  console.log(res.payload)
})
```

### Expected Behavior

The `hello` message should be the latest.

To solve it you need to use the fastify logger:

```
app.inject('/', (err, res) => {
  app.log.info(res.payload)
})
```

Other suggestions before closing?

**Comment by climba03003** [comment]
I think it is expected the log do not follow the order.
`pino@7` prints the log in async and do not flush immediately as you expect.
`console.log` will fall between because it is in sync.

**Comment by mcollina** [comment]
What @climba03003 said. I would also note that console.log is a really poor logging mechanism to be used only when debugging things.

Note that you can flip this configuration by creating a `pino.destination({ sync: true })`.

However if pretty printing is enabled logging would always be async.
