### ISSUE TITLE
Additional error logging when using setErrorHandler

### ISSUE THREAD

**Issue by koanplaned** [fastify/fastify#4048]
Hi all,

I recently upgraded from fastify version 3.26.0 to 4.0.1 and now have an issue with the setErrorHandler method.

My setErrorHandler is implemented like this

```javascript
fastify.setErrorHandler(function (error, request, reply) {

  // some custom logging operations

  reply.send(error);
}
```
In the previous version 3.26.0, the application did just my custom-defined logging and then returned a well-formed json like this:
```json
{
  "message": "Error intentionally triggered",
  "error": "Internal Server Error",
  "statusCode": 500
}
```

Since the 4.0.1 version, there is now an additional error logging done by fastify, which I can not turn off. I narrowed the issue down to following statement:
```javascript
// Problematic part in the code
reply.send(error);
```
```bash
# Excerpt of the additional logging
 err: {
      "type": "Error",
      "message": "The error message",
      "stack":
          Error: The error message
...
```

My observation: If I send the "complete" error object, the additional logging occurs, but when I just send parts of the error (e.g. the error message) the additional logging is gone:
```javascript
reply.send(error.message);
```

Is there a way to turn off the additional logging, when returning the "full" error object?

I want to use the "full" object, since I also need the statusCode and the error in the reply message like this:
```javascript
{
  "message": "Error intentionally triggered",
  "error": "Internal Server Error",
  "statusCode": 500
}
```

As a workaround, I tried to construct this object myself, but I don't understand, how I can access the actual error statusCode to send it back, for example like this:
```javascript
reply.send({
  "message": error.message
  "error": error.error
  "statusCode": error.statusCode
})
```

The property "error.statusCode" is undefined on the error object, so I guess there must be another way to access it somehow. 

Help would be really appreciated here :-)

**Comment by Bilal-Solution507** [comment]
> Hi [@mcollina](https://github.com/mcollina),
> 
> I tried both options, but this didn't change the result. The error handler still returns with error code 500 instead of 400 and with missing error.error property for both options.
> 
> // Result with updated route handler implementation
> 
> HTTP/1.1 500 Internal Server Error
> content-type: application/json; charset=utf-8
> content-length: 82
> Date: Sat, 18 Jun 2022 12:36:20 GMT
> Connection: close
> 
> {
>   "message": "headers must have required property 'client-locale'",
>   "statusCode": 500
> }
> I also played around with the setErrorHandler function a little bit more, e.g.
> 
> fastify.setErrorHandler(function (error, request, reply) {
>     reply.send(error);
> }
> 
> // or 
> 
> fastify.setErrorHandler(async function (error, request, reply) {
>     reply.send(error);
>     return reply;
> }
> With these tweaks, the error response was correct - but the additional error logging happened again.
> 
> I added a new folder v4-2 and updated the code with the route handler adjustments: https://github.com/koanplaned/fastify-error-handler-issue/tree/master/v4-2
> 
> Please note: The previous /test-route is now split up into two routes in the v4-2 implementation:
> 
> GET /tests/option-1 -> async route handler with additional return statement GET /tests/option-2 -> route handler without async option and without return statement

I also ran into this situation. Fastify provides two built-in methods for error handling:

setNotFoundHandler() – for handling unmatched routes (404 errors)

setErrorHandler() – for handling all other runtime errors (e.g. validation, thrown exceptions)

I used both methods to manage route and application-level errors.

However, the main issue is that in recent versions of Fastify, the error (err) passed to setErrorHandler() isn't always a structured object with properties like statusCode. Sometimes, it's just a plain string. Because of that, you can’t rely on err.statusCode, err.validation, or err.stack being available.

That’s why both setNotFoundHandler() and setErrorHandler() are necessary: one handles 404 explicitly, and the other deals with general application errors — but you have to normalize the error yourself if it's not structured.

**Comment by Eomm** [comment]
This is a 3yo closed issue. Please, open a new issue with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

Without it, we are unable to help you.
