### ISSUE TITLE
request.routerPath returns `undefined` in v4

### ISSUE THREAD

**Issue by avin-kavish** [fastify/fastify#4050]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20

### Description

`request.routerPath` property is undefined in fastify v4.

### Steps to Reproduce

```
    app.addHook('onRequest', logOnRequest)
    function logOnRequest(request: FastifyRequest, reply: FastifyReply) {
      app.log.info(request.routerPath)
      return Promise.resolve()
    }
```

In v3, it prints the path as passed, eg: `/hello/:id`. In v4, it prints `undefined`

### Expected Behavior

There should be a way to access the matched router path in v4.

**Comment by climba03003** [comment]
Please provide the minimal repro that can run directly.
In your example, there is no route declared.

**Comment by avin-kavish** [comment]
Actually, I found out that it only happens when the requested path doesn't match any of the router paths. I.e. a `404`. So that behaviour might be okay, imo.

**Comment by climba03003** [comment]
Duplicate of https://github.com/fastify/fastify/issues/4025
