### ISSUE TITLE
Fastify v4 does not handle 'request' handler on FastifyInstance.server

### ISSUE THREAD

**Issue by pikokr** [fastify/fastify#4053]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Node.js version

v16.15.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Adding the 'request' listener on FastifyInstance does not work at all. 
I'm using socket.io with fastify, and it doesn't work at all with socket.io because it injects the handler by adding the 'request' event handler.

### Steps to Reproduce

Here is my code

```ts
import fastify from "fastify"
import * as SocketIO from "socket.io"

declare module "fastify" {
  interface FastifyInstance {
    io: SocketIO.Server
  }
}

const server = fastify()

server.decorate("io", new SocketIO.Server(server.server))

server.io.on("connection", (socket) => {
  server.log.debug(`Socket connected: ${socket.id}`)
})

server.addHook("onClose", () => {
  server.io.close()
})

const port = process.env.PORT ? parseInt(process.env.PORT) : 3000

await server.listen({ port })
```

### Expected Behavior

It should handle the request injected to the FastifyInstance.server.

**Comment by climba03003** [comment]
The problem related to when you are not specify the `host`.
`fastify@4` will initialize two server, so when you using `localhost` for connection.
It will connect to `::1` in Windows which didn't attached by `socket.io`.

**Comment by pikokr** [comment]
It works! Thank you :D
