### ISSUE TITLE
octet-stream returns unsupported mime-type on first reply attempt

### ISSUE THREAD

**Issue by Mxnuuel** [fastify/fastify#4059]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.29.0

### Stopped working in version

4.0.3

### Node.js version

16.13.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04 or Windows 10 (Multi-plattform based application)

### 💥 Regression Report

I'm trying to return an audio-stream that is being requested over a preview route.

it goes through 3 stages.

Step 1 - Ensure that the zip file is existing
Step 2 - Ensure that the zip file is unzipped
Step 3 - Ensure that the audio file is created

When Step 1 is not the case and it downloads the zip file, no matter what i do, i get a "mime-type not supported error" when returning the stream.

I tried to check if the path exists before sending the stream, and it does, which makes it even weirder.

I had no issues with it before so i'm asking myself how that is possible

### Steps to Reproduce

```
//fastify.get('/preview/audio')
audio : async function(req, reply){
        const fs = require('fs')
        const utf8 = require('utf8')
        const mp3 = require('mp3-cutter')
        const StreamZip = require('node-stream-zip');
        const p = INSERT_ROOT_PATH
        
        let set = 0

        let id = 75
        let setid = 1
        
        reply.header("Content-Type", "audio/mp3");

        if(fs.existsSync(`.data/audio/${id}.mp3`)) return fs.createReadStream(`${p}/.data/audio/${id}.mp3`)
        if(!fs.existsSync(`.data/osu/${id}.osu`)){
            //Build your download file logic here passing checkPass as callback
            //download file from https://catboy.best/osu/1
            return download(checkPass)
        }

        return await checkPass()

        async function checkPass(){
            if(!fs.existsSync(`.data/maps/${setid}.osz`)){
                //Build your download file logic here passing cut as callback
                //download file from https://catboy.best/d/1
                return download(cut)
            }
            return await cut()
        }

        async function cut(){
            const osuFile = fs.readFileSync(`.data/osu/${id}.osu`, 'utf-8');
            const lines = osuFile.split('\n');
        
            let audio;
            let time = -1;
        
            for(var i = 0; i < lines.length; i++) {
                if(lines[i].startsWith('AudioFilename:')) {
                    audio = utf8.encode(lines[i].split(':')[1].trim());
                }
        
                if(lines[i].startsWith('PreviewTime:')) {
                    time = parseInt(lines[i].split(':')[1].trim());
                    break;
                }
            }

            if(typeof(audio) == 'undefined') return {error: errors.UNKNOWN}
            
            const zip = new StreamZip.async({
                file: `${p}/.data/maps/${setid}.osz`,
                storeEntries: true
            });

            await zip.extract(audio, `${p}/.data/temp/${id}.mp3`);
        
            if(time == -1) time = 142 / 2
            else time = time / 1000
        
            const startTime = 142 < 30 ? 0 : time;
            let endTime = 142 < 30 ? 142 : time + 30;
        
            if(endTime >= 142) endTime = 142 - 1;

            mp3.cut({
                src: `${p}/.data/temp/${id}.mp3`,
                target: `${p}/.data/audio/${id}.mp3`,
                start: startTime,
                end: endTime
            })

            fs.rmSync(`.data/temp/${id}.mp3`);
            return await ready()
        }

        async function ready(){
            console.log(fs.existsSync(`.data/audio/${id}.mp3`)) //Should return true
            const file = fs.createReadStream((`.data/audio/${id}.mp3`))
            const buff = fs.readFileSync(`.data/audio/${id}.mp3`);

            reply.header('Content-Length', buff.length);
            return reply.send(file)
        }
    }
```

### Expected Behavior

a working audio-stream that can be played with a length of 30 seconds

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Mxnuuel** [comment]
this should do it:
https://github.com/Mxnuuel/fasitfy-issue

please note that you need to change the path inside the code to your own root path.

**Comment by climba03003** [comment]
Didn't `download` actually return `undefined`?

https://github.com/Mxnuuel/fasitfy-issue/blob/ad1b56eefe1df9debdee4fd9092f6ceb8fe5ef13/index.js#L28
https://github.com/Mxnuuel/fasitfy-issue/blob/ad1b56eefe1df9debdee4fd9092f6ceb8fe5ef13/index.js#L37

It is return `undefined` in `async` handler.
https://github.com/Mxnuuel/fasitfy-issue/blob/ad1b56eefe1df9debdee4fd9092f6ceb8fe5ef13/index.js#L97-L108

**Comment by Mxnuuel** [comment]
download is a void method executing the callback that triggers the console.log
https://github.com/Mxnuuel/fasitfy-issue/blob/ad1b56eefe1df9debdee4fd9092f6ceb8fe5ef13/index.js#L106
https://github.com/Mxnuuel/fasitfy-issue/blob/ad1b56eefe1df9debdee4fd9092f6ceb8fe5ef13/index.js#L89

on every attempt it triggers the check that returns true.
await download and return reply wouldn't work because it *has* to give back a audio-file as response
i don't know if it's my logic's flaw but it worked before too

**Comment by Mxnuuel** [comment]
oh i understand, that's my logic just having it's flaws again. It works now thank you very very much!!
