### ISSUE TITLE
Migration guide is missing fastify listener change step

### ISSUE THREAD

**Issue by goriunov** [fastify/fastify#4060]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

As descrived in the title migration guide 3 to 4 is missing  fastify listener change step from 

```
fastify(PORT, HOST, () => {})
```

to

```
fastify({port: 3000, host:'0.0.0.0'}, () => {})
```

**Comment by Fdawgs** [comment]
Dupe of https://github.com/fastify/fastify/issues/3988
