### ISSUE TITLE
functions is undefined in preParsingHookRunner

### ISSUE THREAD

**Issue by vjau** [fastify/fastify#4068]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Node.js version

14.19.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

After my project was upgraded to v4, each route give me this error 

```
[07:39:40 UTC] INFO: incoming request
    reqId: "req-1"
    req: {
      "method": "GET",
      "url": "/hello",
      "hostname": "localhost:3005",
      "remoteAddress": "127.0.0.1",
      "remotePort": 51692
    }
/home/vincent/dev/cadenweb-server2/node_modules/fastify/lib/route.js:493
    if (err || i === functions.length) {
                               ^

TypeError: Cannot read property 'length' of undefined
    at next (/home/vincent/dev/cadenweb-server2/node_modules/fastify/lib/route.js:493:32)
    at preParsingHookRunner (/home/vincent/dev/cadenweb-server2/node_modules/fastify/lib/route.js:524:3)
    at runPreParsing (/home/vincent/dev/cadenweb-server2/node_modules/fastify/lib/route.js:475:5)
    at Object.routeHandler [as handler] (/home/vincent/dev/cadenweb-server2/node_modules/fastify/lib/route.js:424:7)
    at Router.lookup (/home/vincent/dev/cadenweb-server2/node_modules/find-my-way/index.js:359:14)
    at Server.emit (events.js:400:28)
    at parserOnIncoming (_http_server.js:900:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
```

Looking at it with the debugger, it seems the function ```preParsingHookRunner``` in ```fastify/lib/route.js``` has ```undefined``` passed as the ```functions``` parameter.

### Steps to Reproduce

I cannot share my full project.
I don't know where to start to write a repro.
Perhaps it's related to plugins. 
Here is a list of my fastify related packages installed
```
"@fastify/basic-auth": "^4.0.0",
"@fastify/cookie": "^7.0.0",
"@fastify/cors": "^8.0.0",
"@fastify/mongodb": "^6.0.1",
"@fastify/request-context": "^4.0.0",
"@fastify/sensible": "^5.1.0",
"@fastify/static": "^6.4.0",
"@sinclair/typebox": "^0.23.5",
"fastify": "^4.1.0",
"fastify-plugin": "^3.0.1",
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by vjau** [comment]
I'm trying to build a repro.
The problem appears when the routes using a TypeBox schema are enabled. 
I have tried to write a minimal repro, but then i encounter another bug which also seems TypeBox related.
```
err: {
      "type": "FastifyError",
      "message": "Failed building the validation schema for GET: /typedHello, due to error strict mode: unknown keyword: \"kind\"",
      "stack":
          FastifyError: Failed building the validation schema for GET: /typedHello, due to error strict mode: unknown keyword: "kind"
              at Boot.<anonymous> (/home/vincent/dev/temp/fastify-typebox-bug/node_modules/fastify/lib/route.js:309:21)
              at Object.onceWrapper (events.js:519:28)
              at Boot.emit (events.js:412:35)
              at /home/vincent/dev/temp/fastify-typebox-bug/node_modules/avvio/boot.js:160:12
              at /home/vincent/dev/temp/fastify-typebox-bug/node_modules/avvio/plugin.js:276:7
              at done (/home/vincent/dev/temp/fastify-typebox-bug/node_modules/avvio/plugin.js:201:5)
              at check (/home/vincent/dev/temp/fastify-typebox-bug/node_modules/avvio/plugin.js:225:9)
              at internal/process/task_queues.js:141:7
              at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
              at AsyncResource.runMicrotask (internal/process/task_queues.js:138:8)
      "name": "FastifyError",
      "code": "FST_ERR_SCH_VALIDATION_BUILD",
      "statusCode": 500
    }
```

What is strange, is that when copying and pasting this repro code in my main project, the typebox error seems swallowed and become the initially reported bug.

Here is my attempt at a repro:
https://github.com/vjau/fastify-typebox-bug

**Comment by mcollina** [comment]
Please use https://github.com/fastify/fastify-type-provider-typebox to integrate typebox with Fastify v4.

**Comment by vjau** [comment]
> Please use https://github.com/fastify/fastify-type-provider-typebox to integrate typebox with Fastify v4.

Yes, that fixes the problem.
Perhaps this should be mentionned in v4 migration guide since this is a breaking change.
Also the Typebox part in https://www.fastify.io/docs/latest/Reference/TypeScript/ is not up to date. If you do it like mentioned, it won't work.

**Comment by vjau** [comment]
> this seems a completely different error from the one at the top.

The error in the repro happens during the startup phase of the server. The server doesn't start and can't accept requests.
For some reason, in my main project, something is causing the problem to not trigger an error during the startup phase.
The error reported in this issue then happens during a request, even if the request doesn't use a schema.

**Comment by mcollina** [comment]
Going back to this issue, could you upload a reproduction script?

**Comment by vjau** [comment]
I cannot, since i don't understand why the error is swallowed in my project, and using fastify-type-provider-typebox and the ajv plugin fixes the problem.

**Comment by sarneeh** [comment]
@mcollina Can we please reopen this? I just encountered this issue while trying to write tests using `supertest`.

The error is exactly the same as the initial report:

```
/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:512
    if (err || i === functions.length) {
                               ^

TypeError: Cannot read properties of undefined (reading 'length')
    at next (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:512:32)
    at preParsingHookRunner (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:543:3)
    at runPreParsing (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:494:5)
    at Object.routeHandler [as handler] (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:443:7)
    at Router.lookup (/Users/jsarnowski/Workshop/fastify-bug/node_modules/find-my-way/index.js:377:14)
    at Server.emit (node:events:527:28)
    at parserOnIncoming (node:_http_server:956:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

It happens in pure JS with a minimal setup. Here's a reproduction repo: https://github.com/sarneeh/fastify-fastify-issues-4068.

**Comment by sarneeh** [comment]
> @mcollina Can we please reopen this? I just encountered this issue while trying to write tests using `supertest`.
> 
> The error is exactly the same as the initial report:
> 
> ```
> /Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:512
>     if (err || i === functions.length) {
>                                ^
> 
> TypeError: Cannot read properties of undefined (reading 'length')
>     at next (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:512:32)
>     at preParsingHookRunner (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:543:3)
>     at runPreParsing (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:494:5)
>     at Object.routeHandler [as handler] (/Users/jsarnowski/Workshop/fastify-bug/node_modules/fastify/lib/route.js:443:7)
>     at Router.lookup (/Users/jsarnowski/Workshop/fastify-bug/node_modules/find-my-way/index.js:377:14)
>     at Server.emit (node:events:527:28)
>     at parserOnIncoming (node:_http_server:956:12)
>     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> ```
> 
> It happens in pure JS with a minimal setup. Here's a reproduction repo: https://github.com/sarneeh/fastify-fastify-issues-4068.

Sorry, false alarm. I just forgot to call `fastify.ready()`. Perhaps OP had the same issue 🤔

**Comment by rmmurad** [comment]
Encoutered the same issue within a project and it appears to be the order of the routes maybe this is fixed in newer version of fastify

**Comment by Eomm** [comment]
This is a 3-year-old issue.

Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
