### ISSUE TITLE
Techempower Framework Benchmarks

### ISSUE THREAD

**Issue by nbrady-techempower** [fastify/fastify#407]
Hey Guys!

I just stumbled upon this while looking at another JS framework (There are multiple JS frameworks? Who knew?) Selfishly, I'd love to see how this stacks up against the JS frameworks in our [Framework Benchmarks Tests](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/JavaScript)

I may take a shot at it in the next couple of weekends, but if one of the core contributors wants to give it a shot I'd be happy to help with any direction!

**Comment by jsumners** [comment]
See https://github.com/fastify/benchmarks

**Comment by mcollina** [comment]
Feel free to ping myself or @delvedor, we will help!

**Comment by activestylus** [comment]
I would like to see how this stacks up against Mitol, which gets a pretty good score on Techempower

https://github.com/Helidium/Mitol

**Comment by jsumners** [comment]
Closing due to OP inactivity. Please open additional benchmark requests on the https://github.com/fastify/benchmarks repository.
