### ISSUE TITLE
Update TypeScript docs regarding typebox

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#4073]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

In https://github.com/fastify/fastify/blob/main/docs/Reference/TypeScript.md?plain=1#L199, we mention to use typebox directly. The guide should be updated to use the new type provider.

**Comment by Fdawgs** [comment]
Closed by #4077
