### ISSUE TITLE
Entity with 2 references to the same schema throws an error inside a nested route

### ISSUE THREAD

**Issue by noamokman** [fastify/fastify#4083]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x & version on main

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

Hey, 
I'm getting a duplicate schema error when loading an entity that references the same schema twice,
I managed to create a bit of code that recreates the issue,
When I use `fastify.register` to warp a single endpoint I think it somehow duplicates the schemas but i'm not sure.

### Steps to Reproduce

Running this bit of code results in an error, but it should work:
```ts
import Fastify, { FastifyInstance } from 'fastify';

const uuidSchema = {
  format: 'uuid',
  $id: 'UUID',
  type: 'string',
};

const EntitySchema = {
  $id: 'Entity',
  type: 'object',
  properties: {
    id: { $ref: 'UUID' },
    id2: { $ref: 'UUID' },
  },
};

const EntitySchemaRef = { $ref: 'Entity' };

const controller = async (fastify: FastifyInstance) => {
  fastify.get(
    '/',
    {
      schema: {
        response: { 200: EntitySchemaRef },
      },
    },
    async () => ({ id: 'a4e4c954-9f5f-443a-aa65-74d95732249a' }),
  );
};

const fastify = Fastify();

fastify.addSchema(uuidSchema);
fastify.addSchema(EntitySchema);

fastify.register(controller);

await fastify.ready();
```

Running this code, without the `register` does work as expected:
```ts
import Fastify from 'fastify';

const uuidSchema = {
  format: 'uuid',
  $id: 'UUID',
  type: 'string',
};

const EntitySchema = {
  $id: 'Entity',
  type: 'object',
  properties: {
    id: { $ref: 'UUID' },
    id2: { $ref: 'UUID' },
  },
};

const EntitySchemaRef = { $ref: 'Entity' };

const fastify = Fastify();

fastify.addSchema(uuidSchema);
fastify.addSchema(EntitySchema);

fastify.get('/',
    {
      schema: {
        response: { 200: EntitySchemaRef },
      },
    },
    async () => ({ id: 'a4e4c954-9f5f-443a-aa65-74d95732249a' }),
);

await fastify.ready();
```

### Expected Behavior

we should be able to use entity with 2 refs to the same entity inside a controller.

**Comment by noamokman** [comment]
I tested this snippet on the latest commit from main

**Comment by climba03003** [comment]
cc @ivan-tymoshenko Do you have time to take a look on it?

It maybe related to `fastify` itself but not `fast-json-stringify`.

**Comment by ivan-tymoshenko** [comment]
@noamokman Did you update dependencies before testing on the main branch?

**Comment by noamokman** [comment]
> Hmm this test is working on the main.
> ```js
> test('issue-4083', t => {
>   t.plan(1)
>   const fastify = Fastify()
> 
>   const uuidSchema = {
>     format: 'uuid',
>     $id: 'UUID',
>     type: 'string'
>   }
> 
>   const EntitySchema = {
>     $id: 'Entity',
>     type: 'object',
>     properties: {
>       id: { $ref: 'UUID' },
>       id2: { $ref: 'UUID' }
>     }
>   }
> 
>   const EntitySchemaRef = { $ref: 'Entity' }
> 
>   fastify.addSchema(uuidSchema)
>   fastify.addSchema(EntitySchema)
> 
>   fastify.get('/',
>     {
>       schema: {
>         response: { 200: EntitySchemaRef }
>       }
>     },
>     async () => ({ id: 'a4e4c954-9f5f-443a-aa65-74d95732249a' })
>   )
> 
>   fastify.ready(() => t.pass())
> })
> ```

Yeah that's the example that works, the first one doesn't, just moving the endpoint

**Comment by ivan-tymoshenko** [comment]
This one is also working.
```js
test('issue-4083', t => {
  t.plan(1)
  const fastify = Fastify()

  const uuidSchema = {
    format: 'uuid',
    $id: 'UUID',
    type: 'string'
  }

  const EntitySchema = {
    $id: 'Entity',
    type: 'object',
    properties: {
      id: { $ref: 'UUID' },
      id2: { $ref: 'UUID' }
    }
  }

  const EntitySchemaRef = { $ref: 'Entity' }

  const controller = async (fastify) => {
    fastify.get(
      '/',
      {
        schema: {
          response: { 200: EntitySchemaRef },
        },
      },
      async () => ({ id: 'a4e4c954-9f5f-443a-aa65-74d95732249a' }),
    );
  }

  fastify.addSchema(uuidSchema)
  fastify.addSchema(EntitySchema)

  fastify.register(controller)

  fastify.ready(() => t.pass())
})
```

**Comment by ivan-tymoshenko** [comment]
This one is also working.
```js
test('issue-4083', t => {
  t.plan(1)
  const fastify = Fastify()

  const uuidSchema = {
    format: 'uuid',
    $id: 'UUID',
    type: 'string'
  }

  const EntitySchema = {
    $id: 'Entity',
    type: 'object',
    properties: {
      id: { $ref: 'UUID' },
      id2: { $ref: 'UUID' }
    }
  }

  const EntitySchemaRef = { $ref: 'Entity' }

  const controller = async (fastify) => {
    fastify.get(
      '/',
      {
        schema: {
          response: { 200: EntitySchemaRef }
        }
      },
      async () => ({ id: 'a4e4c954-9f5f-443a-aa65-74d95732249a' })
    )
  }

  fastify.addSchema(uuidSchema)
  fastify.addSchema(EntitySchema)

  fastify.register(controller)

  fastify.ready(() => t.pass())
})
```

**Comment by noamokman** [comment]
@ivan-tymoshenko I recreated the test and in order to see the error you need to change the last line
```
t.test('issue-4083', async t => {
  t.plan(1)
  const fastify = Fastify()

  const uuidSchema = {
    format: 'uuid',
    $id: 'UUID',
    type: 'string'
  }

  const EntitySchema = {
    $id: 'Entity',
    type: 'object',
    properties: {
      id: { $ref: 'UUID' },
      id2: { $ref: 'UUID' }
    }
  }

  const EntitySchemaRef = { $ref: 'Entity' }

  const controller = async (fastify) => {
    fastify.get(
      '/',
      {
        schema: {
          response: { 200: EntitySchemaRef }
        }
      },
      async () => ({ id: 'a4e4c954-9f5f-443a-aa65-74d95732249a' })
    )
  }

  fastify.addSchema(uuidSchema)
  fastify.addSchema(EntitySchema)

  fastify.register(controller)

  await fastify.ready()
  t.pass()
})
```
this fails with the error I mentioned

**Comment by noamokman** [comment]
It works 🎉 thanks very much!
