### ISSUE TITLE
Serialization issues after the recent fast-json-stringify update

### ISSUE THREAD

**Issue by a88zach** [fastify/fastify#4092]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

After the release of version 4.2.0, we are seeing serialization issues with complex schemas created with Typebox.  
I've included a reproducible example below.

This is likely the cause:  https://github.com/fastify/fastify/pull/4049

### Steps to Reproduce

clone https://github.com/a88zach/fastify-schema-issue

install modules and run the test

The test will fail with the following error

`no schema with key or ref \"805a7e61-8dcb-423a-b9f7-24dd1496e728#/items/anyOf/0/properties/type/anyOf/0\"`

### Expected Behavior

Test should pass as the schema and response are both valid

**Comment by mcollina** [comment]
@ivan-tymoshenko could you take a look?
