### ISSUE TITLE
`schemaErrorFormatter` uses an insufficient validation type

### ISSUE THREAD

**Issue by zedeus** [fastify/fastify#4093]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Node.js version

16.15.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Irrelevant

### Description

The `FastifySchemaValidationError` type used for the `schemaErrorFormatter` callback has a small subset of the fields available from the full Ajv validation error object.
https://github.com/fastify/fastify/blob/8fccc461c090b488598831b74bc837d5c5d2b9a9/types/schema.d.ts#L25-L28

This is the proper object:
https://github.com/fastify/fastify/blob/8fccc461c090b488598831b74bc837d5c5d2b9a9/fastify.d.ts#L178-L190

### Steps to Reproduce

```typescript
import Fastify from "fastify";

const fastify = Fastify({
	schemaErrorFormatter: (errors, dataVar) => {
		const [error] = errors;

		const path = (error.instancePath ?? "")
			.replace("/", ".")
			.replace(/\/(\d)/, "[$1]");

		let { message } = error;
		if (error.keyword === "enum") {
			const values = error.params.allowedValues as string[];
			message += `: ${values.join(", ")}`;
		}

		return new Error(`${dataVar}${path} ${message.replace(/"/g, "'")}`);
	}
});
```

```typescript
test.ts:12:13 - error TS2339: Property 'keyword' does not exist on type 'FastifySchemaValidationError'.

12   if (error.keyword === "enum") {
               ~~~~~~~

test.ts:13:25 - error TS2339: Property 'params' does not exist on type 'FastifySchemaValidationError'.

13    const values = error.params.allowedValues as string[];
```

Workaround:
```typescript
import Fastify, { ValidationResult } from "fastify";

const fastify = Fastify({
	schemaErrorFormatter: (errors, dataVar) => {
		const [error] = errors as unknown as ValidationResult[];

		const path = (error.instancePath ?? "")
			.replace("/", ".")
			.replace(/\/(\d)/, "[$1]");

		let { message } = error;
		if (error.keyword === "enum") {
			const values = error.params.allowedValues as string[];
			message += `: ${values.join(", ")}`;
		}

		return new Error(`${dataVar}${path} ${message.replace(/"/g, "'")}`);
	}
});_
	
```

### Expected Behavior

Compiles, resulting in pretty errors like this:
`body.roles[0] must be equal to one of the allowed values: internal, owner, admin, communicator`
`body.roles must NOT have more than 1 items`
`querystring.ownerId must NOT have fewer than 28 characters`

**Comment by mcollina** [comment]
This is somewhat expected as the validation library is configurable. It would be good to implement generics for this.
