### ISSUE TITLE
Response stream?

### ISSUE THREAD

**Issue by brwnll** [fastify/fastify#41]
Is there a way for me to stream a response via fastify (essentially access `res.write`)?

**Comment by mcollina** [comment]
Just pass a stream to `reply.send()`. It would be forwarded: https://github.com/fastify/fastify#reply.

**Comment by brwnll** [comment]
Is the `schema.out` property still respected? Should it be removed if I'm returning via stream?

**Comment by mcollina** [comment]
No it is not, that is used only when a JSON is returned.

**Comment by brwnll** [comment]
Thanks

**Comment by brwnll** [comment]
When passing a stream, it doesn't appear to write out as the buffer fills?

I'm testing using a large MongoDB collection, and pass the query stream to `fastify.send`. Instead of getting a stream of continues response from the API when I curl the URL, the connection hangs while I watch the memory consumption of the API grow and grow.

Am I missing something?

**Comment by brwnll** [comment]
Sorry, that issue was incorrect, I wasn't returning the stream I thought I was. But I have run into something that seems to be an issue:

```js
// `stream` is a MongoDB query stream

// This response works
stream.on('data', chunk => {
  reply.res.write(JSON.stringify(chunk))
})

// This doesn't
reply.send(stream)
```

**Comment by mcollina** [comment]
if you need to call JSON.stringify on your objects, you can use https://www.npmjs.com/package/ndjson

**Comment by AutoSponge** [comment]
I was able to respect the schema by switching to a generator/iterable approach. Each "pump" to the stream passes through a reusable serializer. The laziness may not be faster in the long run, but on slow connections or when the client may `abort()` early, it's perfect. It also uses less memory.

My client is using oboe.js so the output is different from ndjson, but I'll probably implement that as well now that I know it exists.
