### ISSUE TITLE
Connection closed on bad request in reused connection

### ISSUE THREAD

**Issue by katreniak** [fastify/fastify#4101]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Node.js version

v16.15.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora release 34 (Thirty Four)

### Description

When fastify server receives request with invalid url in a reused connection, it closes the connection instead of `400 Bad Request` reply. 

The closed connection is then propagated by load balancer (ALB) as `502` error. This turns client errors into closely monitored  server errors. 

The problem is not reproducible when invalid url is received on new connection.

Further context:
- reproducible in express
- not reproducible in hapi
- not reproducible in fastify over http2

### Steps to Reproduce

Program:
```js
// file: server.js
const fastify = require("fastify")({logger: true});
const route = fastify.get("/ping", async () => "Hello world\n");
fastify.listen({ port: 3000 });
```

Run server:
```
$ node server.js
```

Run client invoking 2 requests over reused connection
* the first request is correct and keeps the connection alive
* the second request has invalid character `' '` in the query. Server closes the connection instead of replying `400 Bad Request`. 
```
$ curl 'http://localhost:3000/ping' 'http://localhost:3000/ping?a b' -v
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /ping HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
< content-length: 12
< Date: Fri, 01 Jul 2022 10:58:37 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
<
Hello world
* Connection #0 to host localhost left intact
* Found bundle for host localhost: 0x556db5c09650 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /ping?a b HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.76.1
> Accept: */*
>
* Connection died, retrying a fresh connect(retry count: 1)
* Closing connection 0
...
```

Not reproducible when the bad request is sent to new connection. Curl retries in new connection and correctly gets 400 response.
```
* Issue another request to this URL: 'http://localhost:3000/pi ng'
* Hostname localhost was found in DNS cache
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#1)
> GET /pi ng HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Length: 65
< Content-Type: application/json
<
* Connection #1 to host localhost left intact
{"error":"Bad Request","message":"Client Error","statusCode":400}
```

Pcap file with captured network communication between client and server. Proves that the tcp connection is closed from the server side in packet number 10.
[capture.zip](https://github.com/fastify/fastify/files/9028583/log2.zip)

![image](https://user-images.githubusercontent.com/3446570/176889217-553f4fe1-0e75-4936-a95a-82215a0c25f0.png)

### Expected Behavior

Bad request in in reused connection shall be replied with `400 Bad Request`

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
Something that would be really helpful is to have a reproducible example that just uses Node.js.

**Comment by mcollina** [comment]
@ShogunPanda could you take a look?

**Comment by ShogunPanda** [comment]
@mcollina Sure, will take a look soon!

**Comment by katreniak** [comment]
Thank you for looking at this. 

This minimal fastify example with `/ping` endpoint that makes it reproducible: https://github.com/katreniak/fastify-4101

When it is running, just 
```
curl 'http://localhost:3000/ping' 'http://localhost:3000/ping?a b' -v
```

And  `Connection died, retrying a fresh connect(retry count: 1)` is visible in the curl log.
