### ISSUE TITLE
"No schema with key or ref" when using a reference to a 

### ISSUE THREAD

**Issue by UltimateLobster** [fastify/fastify#4108]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

The following error occurs when sending a request to an endpoint whose schema (request/response schema) is a typebox schema containing a reference to an object with a union field:

`no schema with key or ref "..."`

### Steps to Reproduce

clone https://github.com/UltimateLobster/fastify-validation-issue
run `yarn install`
and then `yarn test`

The test will fail with `no schema with key or ref \"FooSchema/properties/type/anyOf/0\"`

### Expected Behavior

The test should pass successfully since the endpoint returns a valid object that matches the response schema

**Comment by mcollina** [comment]
@Eomm @sinclairzx81 @ivan-tymoshenko is this fixed by the latest changes?

**Comment by ivan-tymoshenko** [comment]
@mcollina No, it's another one. I will take a look.
