### ISSUE TITLE
Figure out what to do with typed decorators

### ISSUE THREAD

**Issue by wyozi** [fastify/fastify#4110]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When [this PR](https://github.com/fastify/fastify/pull/3203) was merged to main in [this commit](https://github.com/fastify/fastify/commit/d37d8997dd22f4ace29a29320ac50a43ec98731f#diff-f86d0644c15a00c507413e99f283c1f856275409929539a74b8196a42da25018), it also removed all the changes made in [this PR](https://github.com/fastify/fastify/pull/2981)

Ideally AFAIC PR 2981 would be re-added. This might be a bit problematic since #3203 hijacked the first generic slot for all `decorate*` functions, so re-adding it would be a breaking change. Also this means that since typed decorators wasn't actually added in v4, the feature isn't and cannot be used by anyone.

There's few options I can think of:
1. Re-add typed decorators as a supplement to 'this types' even if it's a (very small) breaking change
2. Add typed decorators to `decorate*` functions in fastify v5
3. Introduce `typedDecorate*` functions that do the same as `decorate*` but with type checking
4. Forget that typed decorators can even exist and ignore this issue

There's also this tiny documentation change that should probably be removed now: https://github.com/fastify/fastify/pull/2981/files#diff-c2db295d2a99e431bb24ac08c3953353dbb702f62b48587aa2cd76a0b78e0dbf

**Comment by mcollina** [comment]
Would you like to send a PR for restoring the functionality that was added in 2981 and I later removed by mistake? I would prefer to not wait for v5... and also that was slotted in to be released in v4.

**Comment by wyozi** [comment]
Made https://github.com/fastify/fastify/pull/4111 with something that could at least be a starting point
