### ISSUE TITLE
Different json-schema generate method suggestion

### ISSUE THREAD

**Issue by imjuni** [fastify/fastify#4112]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, 

Thank you for good framework!

I create simple tool for generate json-schema. [simple-tjscli](https://www.npmjs.com/package/simple-tjscli). 

Can I add this tool on ecosystem document? (like [fast-maker](https://github.com/imjuni/fast-maker))

And I create [fastify boilerplate](https://github.com/imjuni/maeum) using fast-maker + simple-tjscli.

You can see simple-tjscli working result this [file](https://github.com/imjuni/maeum/blob/master/src/schema/v1/poke-detail/IReqPokeDetail.ts)

**Comment by mcollina** [comment]
sure go ahead

**Comment by imjuni** [comment]
I write user guide like [fluent-schema](https://www.fastify.io/docs/latest/Guides/Fluent-Schema/).

How about this content? 

[Schema-Conversion.md](https://github.com/fastify/fastify/files/9047281/Schema-Conversion.md)
