### ISSUE TITLE
Multiple requests are sent, when using an array of `onRequest` hooks and Postgres

### ISSUE THREAD

**Issue by mkhoussid** [fastify/fastify#4124]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Node.js version

v16.12.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1

### Description

Every time I attempt to access the `/api/admin/auth` route, it is hit twice for some reason.

I've noticed two things that "solve" this issue.

The first is changing `multi_requests_bug/api/routes/admin.js:**9**` from,

```
onRequest: [logEvent(), verifyAdminSessionId]
```
to,

```
onRequest: logEvent({ onAfterLog: verifyAdminSessionId })
```
My `logEvent` function takes an `onAfterLog` prop, a function, that it executes after logging events.

The second way to "solve" this issue, oddly enough, is to remove the line `multi_requests_bug/utils/registerPlugins.js:**18**`.

I'm beyond confused and I'm about 90% sure, that this is either a bug or, I suspect, this has something to do with the ordering of either plugins or middleware.

As a side note, I suspect this issue is linked to Postgres, because if I change `multi_requests_bug/api/controllers/admin.js:**4**` from,

```
const { rows } = await request.db().client.query(`SELECT * FROM multi_requests.user WHERE email = $1`, [mode]);
```

to,

```
const rows = [];
```

then the issue goes away as well.

### Steps to Reproduce

I've created a reproducible demo [here](https://github.com/mkhoussid/multi_requests_bug)

**Comment by mcollina** [comment]
Either call done or use an async function. Don't use them both at the same time.

**Comment by mkhoussid** [comment]
> ```
> onRequest: [logEvent(), verifyAdminSessionId]
> ```

I'm sorry, what do you mean? I have an array of middleware functions, which all call `done`/`next`.

**Comment by mkhoussid** [comment]
> Either call done or use an async function. Don't use them both at the same time.

I'm sorry, what do you mean? I have an array of middleware functions, which all call `done`/`next`.

**Comment by mcollina** [comment]
https://github.com/mkhoussid/multi_requests_bug/blob/master/middleware/verifyAdminSessionId.js

this doesn't work the way you think it works. Either use callbacks or promises, don't mix them.
