### ISSUE TITLE
Is HTTP/2 still experimental?

### ISSUE THREAD

**Issue by SebastianZimmer** [fastify/fastify#4142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In [this PR](https://github.com/fastify/fastify/pull/1522), experimental status has been removed from the [HTTP/2 section in Server.md](https://github.com/fastify/fastify/blob/main/docs/Reference/Server.md#http2). However, [HTTP2.md](https://github.com/fastify/fastify/blob/435c43726c3972dab290ef05fa43522e10e8e1d3/docs/Reference/HTTP2.md) states that HTTP/2 is still considered experimental.

1. Should the "experimental" notice be removed?
2. Or is HTTP/2 actually still considered experimental?
    2a. If so, what must happen for it to become stable?
3. Or is it experimental only for the Node core versions that also supported HTTP/2 only experimentally (>=8.4.0, <10.10.0)? Maybe the docs could then explicitly differentiate.

**Comment by mcollina** [comment]
Yeah, the docs needs updating ;). Would you like to send a PR?

**Comment by SebastianZimmer** [comment]
Thanks for the feedback. Yes, I shall send a PR shortly.

**Comment by SebastianZimmer** [comment]
Done with https://github.com/fastify/fastify/pull/4144
