### ISSUE TITLE
decorate* dependencies argument is not documented

### ISSUE THREAD

**Issue by jdmarshall** [fastify/fastify#4147]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The Decorators section of the docs delegates definition of the dependency argument to `decorate()` which then only shows that an array is a legal third argument, but never utilizes those variables for anything. 

It is completely opaque then what or if they are useful for anything aside from ensuring that sibling decorators exist (and how would you use the siblings anyway, since the request and reply aren't arguments to your decorator function?)

**Comment by mcollina** [comment]
Would you like to help documenting this?

**Comment by MujahidAli954** [comment]
I want to work on this

**Comment by MujahidAli954** [comment]
> ### Prerequisites
> * [x]  I have written a descriptive issue title
> * [x]  I have searched existing issues to ensure the issue has not already been raised
> 
> ### Issue
> The Decorators section of the docs delegates definition of the dependency argument to `decorate()` which then only shows that an array is a legal third argument, but never utilizes those variables for anything.
> 
> It is completely opaque then what or if they are useful for anything aside from ensuring that sibling decorators exist (and how would you use the siblings anyway, since the request and reply aren't arguments to your decorator function?)

Dependency argument is documented I readed  documentation.

**Comment by MujahidAli954** [comment]
> 

kindly explain more about which actual part you are talking about because I readed  documentation and dependency argument is defined with example

**Comment by jdmarshall** [comment]
What's it do? What's it for? How does it work? Does it pass variables to the current function? Does it modify execution order?

None of these are explained. The only thing that _is_ explained is that if you have a dependency that is not met, it results in an error. None of the examples actually utilize the dependency.

**Comment by jdmarshall** [comment]
```
fastify.decorate('utility', fn, ['greet', 'log'])
```

This is the only example in https://www.fastify.io/docs/latest/Reference/Decorators/ where the argument is undefined, and the other sections that talk about decorators point back to this example, so one might count that as 3 or 1 depending on perspective.

**Comment by xtx1130** [comment]
> It is completely opaque then what or if they are useful for anything aside from ensuring that sibling decorators exist

In fact, I did not find any other use for `[dependencies]`

**Comment by leandroandrade** [comment]
Hi, here is an example of how use decorators dependencies.  Maybe we can improve docs with this example. What are you think?

```
'use strict'

const fastify = require('../fastify')({
  logger: false
})
const fp = require('fastify-plugin')

async function greetDecorator (fastify, opts) {
  fastify.decorate('greet', () => {
    return 'greet message'
  })
}

async function hiDecorator (fastify, opts) {
  fastify.decorate('hi', () => {
    return 'hi message'
  })
}

async function utilityDecorator (fastify, opts) {
  fastify.decorate('utility', () => {
    return `${fastify.greet()} | ${fastify.hi()}`
  })
}

fastify.register(fp(greetDecorator, { name: 'greet' }))
fastify.register(fp(hiDecorator, { name: 'hi' }))
fastify.register(fp(utilityDecorator, { dependencies: ['greet', 'hi'] }))

fastify.get('/', function (req, reply) {
  // Response: {"hello":"greet message | hi message"}
  reply.send({ hello: fastify.utility() })
})

fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
})

```

**Comment by mcollina** [comment]
Sure, would you like to send a PR?

**Comment by leandroandrade** [comment]
Great! I'll send it.

**Comment by cesarvspr** [comment]
I see that https://github.com/fastify/fastify/pull/4343 merged. Is there any activity pending on this issue?
