### ISSUE TITLE
Unable to use logger other than pino

### ISSUE THREAD

**Issue by sgrigorev** [fastify/fastify#4148]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I tried to update the fastify 3.28.0 to the version 4.2.1 and noticed that now it makes me to use pino logger. I used in previous version own logger class that fits fastify's interface. 

Type of logger in fastify v4.2.1:
```
export type FastifyBaseLogger = pino.Logger & {
  child(bindings: Bindings, options?: ChildLoggerOptions): FastifyBaseLogger
}
```
where pino.Logger is:
```
type Logger<Options = LoggerOptions> = BaseLogger & LoggerExtras<Options> & CustomLevelLogger<Options>;
```
so it requires that my logger must have all fields from LoggerExtras and CustomLevelLogger.

Regarding the code there is a [TODO](https://github.com/fastify/fastify/blob/0ca63a0819a154023c4de14e2723578a2b3f0961/types/logger.d.ts#L23) to use `pino.BaseLogger` instead of `pino.Logger`. Could we start using `pino.BaseLogger` or is there any significant issue that blocks us?

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests (we use `tsd` for TypeScript).
