### ISSUE TITLE
Expose schema in `request` object

### ISSUE THREAD

**Issue by FlameWolf** [fastify/fastify#4149]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be great if we can access the schema from the request object so that a content parser can use it to correctly populate the request body instead of relying on hacks like you see in line 58 [here](https://github.com/FlameWolf/formzilla/blob/master/index.js).

### Motivation

Need for having access to request schema for content parsing.

### Example

[https://github.com/FlameWolf/formzilla/blob/master/index.js](url)

**Comment by Eomm** [comment]
Since yesterday you can: https://www.fastify.io/docs/latest/Reference/Request/#getvalidationfunction

**Comment by climba03003** [comment]
It is not the same request.

The request here is retrieve the `route options`, more particular `schema` for custom usage.

**Comment by mcollina** [comment]
The schema is part of the route context: https://github.com/fastify/fastify/blob/95f9fa5abc105397a715fc376c3a6e704181d2e1/lib/context.js#L21

**Comment by climba03003** [comment]
>The schema is part of the route context: 

Yes, it is. However, the document stated that `context` is for `fastify` internal usage.
Users should not use or modify it directly.

We need a properly to deprecate the `context` and expose some useful inside `context` in `public` API.

**Comment by metcoder95** [comment]
Not so sure if deprecate it will be the best approach, but at least expose some public API where the users can take use to understand the route settings

**Comment by climba03003** [comment]
> Not so sure if deprecate it will be the best approach

If deprecation or removal is not possible.
I would 
1. refactor to a `symbol` property.
2. expose the same `context` with `Proxy` to provide `readonly` usage.

In this case, user is safe to use `context`.

**Comment by mcollina** [comment]
Allowing unvetted access to context enables quite a few plugins (even in our orgs). This was an escape-hatch to enable quick evolution of the framework for with flexibility.

I think we can design a new API to a address those cases. I would probably consider it semver-major and be done with it.

**Comment by Eomm** [comment]
Meanwhile, the user can write:

```
fastify.addSchema({ $id: 'foo' ... })
fastify.get('/',
  { schema: fastify.getSchema('foo') }, 
  () => { const schema = fastify.getSchema('foo') })
```

**Comment by metcoder95** [comment]
To recap, the agreed solution will be:

1. Hide the context object through a `symbol`
2. Create a new API that exposes such route internals that can be used by implementation and plugins
	- Here will be worth it to decide what we want to expose and what not

I think we can safely land the new API as a minor by exposing it but not hiding the `context` object through a symbol yet, just marking any not desired access to it as with a deprecation warning (not so sure if we can track all and distinguish but I'll try to make some assessment).

And leverage the context behind a `symbol` for the major. 

Please let me know if my assumptions are correct, otherwise, let me know if I'm missing something 🙂

**Comment by mcollina** [comment]
Based on past experiences, I'd restrain in landing this change in a minor. This can have unpredictable consequences and unexpected performance drops.

There is no hurry to implement this so we can safely do it for the next major.

The PR can land in a next branch.

**Comment by metcoder95** [comment]
Perfect, sounds good. Then everything remains the same but with the exception of aiming for next `major` 👍

**Comment by metcoder95** [comment]
Is there a new `next` branch prepared for pointing the PR?

**Comment by mcollina** [comment]
There is a next branch
