### ISSUE TITLE
Document how to execute a benchmarks

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#415]
On new merge request we should check if there's a regression or not.
It's needed a "TODO" list in order to provide a guide for making the benchmark

Like:
- check master branch out
- execute this script
- check your branch out
- execute this script
- compare the results

where "execute this script" is TBD.

**Comment by StarpTech** [comment]
- Print Platform information for better understanding https://github.com/hemerajs/hemera/blob/master/benchmark/platform.js

**Comment by StarpTech** [comment]
I've implemented a handy tool to checkout multiple repositories, run commands and print them in the console for copy & paste https://github.com/StarpTech/branch-comparer

**Comment by StarpTech** [comment]
This PR will fix this issue https://github.com/fastify/fastify/pull/421 💪

**Comment by StarpTech** [comment]
@allevo can we close it? The user only has to do `npm run bench` to compare master with the current branch and paste the results in the PR.

**Comment by mcollina** [comment]
This can be closed now.
