### ISSUE TITLE
Add fastify-stream-react-views / React SSR + Islands in TypeScript

### ISSUE THREAD

**Issue by WNemencha** [fastify/fastify#4153]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hello there! 🖖

I'm the author and maintainer of this small plugin I made for internal usage in side-projects originally and as it's getting stabler I'd like some review/tests/bugs reports if any (surely) from anyone willing to do it! 

Here's the plugin: https://github.com/EthicDevs/fastify-stream-react-views

And also, i'm building a sort of framework like next.js but not that is file-system based (uses a JSX/AST powered routes.tsx file to declaratively write your view routes and controllers handlers mappings) and it uses fastify internally, so I tought it would be nice to speak about it too! You can found the main project here aswell as some example code (basic yet):

- https://github.com/EthicDevs/react-monolith
- https://github.com/EthicDevs/react-monolith-samples

Hope its the right place and it does not looks like "advertisment" (even if it is, shame on me 😅), hope you'll like it and find plenty of bugs to be fixed!

### Motivation

To include the `fastify-stream-react-views` plugin into the `community plugins` list and the `react-monolith` framework in `community tools` if that seems appropriate to people who works over there! 😅 

### Example

See readme's for the projects aswell as associated `-samples` project.

**Comment by Eomm** [comment]
thank for improving the Fastify plugin ecosystem
Would you like to send a Pull Request to add it to the ecosystem?

**Comment by Fdawgs** [comment]
@WNemencha would you like to add this to the ecosystem?

**Comment by WNemencha** [comment]
@Fdawgs @Eomm Hey, sorry for the late reply, been busy a lot these days ^^

I have been working on documenting/testing the whole thing before its officially submitted in a PR, so that its really useful and usable. Some progress has been made already but a lot still needs to be documented before it can really be made public.

Is it ok for you if we keep this issue open and i get back to it once docs/tests are ready, with a PR for inclusion in the list?
