### ISSUE TITLE
IPC server support

### ISSUE THREAD

**Issue by ciffelia** [fastify/fastify#4161]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add `.listenIPC(path[, backlog])` method to listen on a named pipe or an UNIX domain socket.

### Motivation

In fasitfy@4 it is possible to create an [IPC server](https://nodejs.org/docs/latest-v16.x/api/net.html#ipc-support) (i.e. server listening on a named pipe or an UNIX domain socket).

```js
const fastify = require('fastify')({ logger: true })

// https://nodejs.org/docs/latest-v16.x/api/net.html#serverlistenpath-backlog-callback
fastify.listen('/path/to/socket.sock')
```

While this behavior is not documented, there are [type definitions](https://github.com/fastify/fastify/pull/2601) and [tests](https://github.com/fastify/fastify/blob/3709671b73c9109ef54fa1e85de0d7b7f7946226/test/listen.test.js#L186-L204).

However, it seems that we will not be able to use this method in v5 because variadic listen method is deprecated and will be removed. (#3652)

```
[FSTDEP011] FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.
```

### Example

Create a Docker plugin:

```js
const fastify = require('fastify')({ logger: true })

fastify.get('/', async () => {
  return { status: 'TODO' }
})

fastify.listenIPC('/run/docker/plugins/myplugin.sock')
```

**Comment by Eomm** [comment]
I think `fastify.listen({ path: '/path/to/socket.sock' })` should work

**Comment by ciffelia** [comment]
I didn't notice that, thanks!

**Comment by jsumners** [comment]
The docs state that the `.listen` method accepts the same configuration object as Node core -- https://www.fastify.io/docs/latest/Reference/Server/#listen

(looks like we have a bug to fix in those specific docs, too)
