### ISSUE TITLE
FastifyError: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.2.0' is installed

### ISSUE THREAD

**Issue by adilfaayiz** [fastify/fastify#4168]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Node.js version

18.7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13 Ventura

### Description

I'm using NestJS with GraphQL I've installed it as per their instruction but getting below error

```FastifyError: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.2.0' is installed```

I'm clueless what to do here, I've tried every possible options so it's not working.

Also getting below warning 

``` warning " > apollo-server-fastify@3.10.0" has unmet peer dependency "fastify@^3.17.0". ```

### Steps to Reproduce

Installed the new NestJs and GraphQL and add GraphQLModule configuration on AppModule and start it, It will through the error in CLI.

### Expected Behavior

It should run smoothly without any version error.

**Comment by climba03003** [comment]
Please reach `apollo-server-fastify` for the support of `fastify@4`.
