### ISSUE TITLE
setErrorHandler's typing definition seems different than the signature fastify accepts

### ISSUE THREAD

**Issue by wtchangdm** [fastify/fastify#4171]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

N/A

### Node.js version

16.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5

### Description

Hi, I was setting a custom error handler and noticed that the `setErrorHandler` typing definition seems different than the actual function signature it accepts.

Simply put, the server `error handler` typing definition indicates that it accepts `(fastify, error, req, res)`
https://github.com/fastify/fastify/blob/c6cd0e9aa4d2a88a34ebb551edb958b7a5597d50/types/instance.d.ts#L487-L489
and the route one seems incorrect as well:
https://github.com/fastify/fastify/blob/95f9fa5abc105397a715fc376c3a6e704181d2e1/types/route.d.ts#L43

However, the function `setErrorHandler` function itself expects `(error, req, res)`, same as the documents.

https://github.com/fastify/fastify/blob/c6cd0e9aa4d2a88a34ebb551edb958b7a5597d50/lib/error-handler.js#L68

https://github.com/fastify/fastify/blob/c6cd0e9aa4d2a88a34ebb551edb958b7a5597d50/docs/Reference/Server.md?plain=1#L1406-L1411

https://github.com/fastify/fastify/blob/c6cd0e9aa4d2a88a34ebb551edb958b7a5597d50/docs/Reference/Routes.md?plain=1#L87-L92

Is this intended? If not, I think I can make a simple pull request to correct this (unless I missed something).

Thanks.

### Steps to Reproduce

N/A. It's about typing.

### Expected Behavior

Make `setErrorHandler` typing definition match the the handler fastify expects.

**Comment by climba03003** [comment]
The current typings is correct.
`this` is a special function argument in TypeScript, it used to indicate the `this` binding and do not actually accept as a actual argument.

**Comment by wtchangdm** [comment]
Thank for explaining, @climba03003! I didn't know that.

This issue was created because I saw the following prompt:

![img](https://i.imgur.com/NSSyapP.png)

Not sure is there any way to make it more clear?

**Comment by climba03003** [comment]
> is there any way to make it more clear?

Yes, but require a quite a lot of works.
It should be parts of https://github.com/fastify/fastify/issues/4081
