### ISSUE TITLE
How to handle errors thrown in onResponse hook when disableRequestLogging is true

### ISSUE THREAD

**Issue by paganwinter** [fastify/fastify#4173]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have `disableRequestLogging` set to `true` and do my own logging.
However I very recently noticed that when there's an error thrown within the `onResponse` hook, it is not caught by the error handler set using `setErrorHandler`.
If `disableRequestLogging` is false or unset, the default log is indeed able to catch this error and includes it in the response log.

How can I achieve this behaviour when not using the default request logging?

Consider the below code:
```js
const app = require('fastify')({
  logger: true,
  disableRequestLogging: true,
});

(async () => {
  app.setErrorHandler(async (err) => {
    console.log(err); // error from onResponse isn't caught here
  });

  app.get('/', async (req, rep) => {
    rep.send('hello');
  });

  app.addHook('onResponse', async () => {
    throw new Error('oops'); // silently ignored
    console.log('done');
  });

  await app.listen(3000);

  const res = await app.inject({
    url: '/',
  });
  console.log(res.statusCode, res.body);
})();
```

**Comment by climba03003** [comment]
I am not sure if `setErrorHandler` is the right place for it since `error handler` needs `request` and `reply`.
When the request reached `onResponse`, it means the user can no longer do anything about the `request`.

https://github.com/fastify/fastify/blob/abab5882d13555616c81cd88c9541ade28698fe0/lib/reply.js#L677-L728

**Comment by mcollina** [comment]
An error handler purpose is to send a response to the user. onResponse is fired after a response is sent, so it seems correct to me to not route the error there.

Given the request to disable request logging, it also seems correct to not log anything in case of errors.

Maybe we should just improve our docs?

**Comment by paganwinter** [comment]
I think the docs could call this out maybe.
I just noticed this after 1.5 years of working with Fastify :)

I am logging the response inside the hook, but using a custom logger function attached to req. I wanted to ensure that user code does not alter the logger in any way causing the logging to fail.

I suppose I'll use try..catch in my onResponse hook.

**Comment by avanelli** [comment]
Hello, I would like to help improve the docs about this.
Is it reasonable to add a Note here https://www.fastify.io/docs/latest/Reference/Hooks/#onresponse ?

**Comment by mcollina** [comment]
Go for it!

**Comment by avanelli** [comment]
Created PR #4178 
In addition, I added a note on the `setErrorHandler` docs to clarify that it is not catching any error from the `onResponse` hook.
