### ISSUE TITLE
reply gets sent by finishing writing a file

### ISSUE THREAD

**Issue by Calemy** [fastify/fastify#4175]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Node.js version

16.13.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

after the filestream.on('finish') callback it reply.sent turns true even tho we never called reply.send()

### Steps to Reproduce

install dependencies via npm

```js
import { fastify as f } from 'fastify'
import fs from 'node:fs'
import fetch from 'node-fetch'

const fastify = f({logger: true})

fastify.get('/', async (req, reply) => {
    await download(reply)
})

async function download(reply){
    const fileStream = fs.createWriteStream(`./1.osz`);

    const file = await fetch('https://catboy.best/d/1')

    file.body.pipe(fileStream);
    console.log(reply.sent) //<- False
    fileStream.on("finish", async () => {
        console.log(reply.sent) //<- True
    });
}

fastify.listen({port: 3000})
```
### Expected Behavior

reply.sent should not change since we didn't call reply.send()

**Comment by climba03003** [comment]
The current behavior is expected.

```js
import { fastify as f } from 'fastify'
import fs from 'node:fs'
import fetch from 'node-fetch'

const fastify = f({logger: true})

fastify.get('/', async (req, reply) => {
    // it seems like you want to wait, until download finish
    await download(reply)
})

async function download(reply){
    const fileStream = fs.createWriteStream(`./1.osz`);

    // however, when the fetch is done
    // download is actually resolved
    // and the route handler is resolved as well
    const file = await fetch('https://catboy.best/d/1')

    file.body.pipe(fileStream);
    console.log(reply.sent) //<- False
    fileStream.on("finish", async () => {
        console.log(reply.sent) //<- True
    });
    // which means fastify will move forward here
}

fastify.listen({port: 3000})
```

**Comment by Calemy** [comment]
how do i prevent that behaviour, i want to wait until the file has finished downloading and send the file to the end user after. I'm working with callbacks and it seemed to have worked before on my old version of a project but with the rewrite it does not work anymore. what can i do?

**Comment by climba03003** [comment]
You should read the [migration guide](https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V4.md#need-to-return-reply-to-signal-a-fork-of-the-promise-chain)

```js
fastify.get('/', async (req, reply) => {
    await download(reply)
    // tell fastify to wait for sending payload
    return reply
})
```

**Comment by Calemy** [comment]
i'm gonna try this right now and give updates on it, thank you for the fast response :)

**Comment by Calemy** [comment]
okay wow i don't know how my old code works then but well now it does. Thank you again for your time and the precise explanation!

Have a great day 👍
