### ISSUE TITLE
How to detect the HTTP protocol version? (I.e HTTP/1.1, HTTP/2.0)

### ISSUE THREAD

**Issue by unreleased** [fastify/fastify#4181]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,

I'm trying to find a way to detect the HTTP version of the request being made, I've checked the documentation but cannot see anything for the `request` object. I noticed another issue (https://github.com/fastify/fastify/issues/3893) I saw `req.httpVersion` except, when it comes to using this inside my script that's not defined.

Use case:
I'm using HTTPS w/ HTTP/2.0 with the option `allowHTTP1` set to `true`. I want to return the `Transfer-Encoding: Chunked` header for HTTP/1.1 requests but that's not an allowed header for HTTP/2.0, because there seems to be no way for me to conditionally check the HTTP version I cannot do this.

```TypeError [ERR_HTTP2_INVALID_CONNECTION_HEADERS]: HTTP/1 Connection specific headers are forbidden: "transfer-encoding"```

Any help would be greatly appreciated!

**Comment by Fdawgs** [comment]
Hi @unreleased, you can find this in `request.raw.httpVersion`.

**Comment by mcollina** [comment]
note that transfer-encoding is managed by Node.js, so you should not set it.

**Comment by Uzlopak** [comment]
Closing as answered.
