### ISSUE TITLE
Documentation: adjust logging configuration with TypeScript

### ISSUE THREAD

**Issue by pschaub** [fastify/fastify#4184]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently there is a documentation how to adjust the logging configuration to use `pino-pretty`:
https://www.fastify.io/docs/latest/Reference/Logging/

If you use TypeScript and try to use the code from the documentation you will run into an IDE type warning:
```Type argument cannot be inferred from usage```

**Issue: The documentation should contain a recommendation how to solve this issue.**

### Suggestion

I don't know if my solution is correct or could be optimized ("it works on my machine").
I am not sure if the other generics should be set to something else.

```sh
$ npm install -D @types/pino
```
**(Edit: do NOT use `@types/pino`! see answers..)**

```ts
import {Logger} from 'pino';
import http from 'http';

const fastify = Fastify<http.Server, http.IncomingMessage, http.ServerResponse, Logger>( ... );
```

**Comment by mcollina** [comment]
You should not use `@types/pino`, pino typings are not shipped within Pino itself.

**Comment by pschaub** [comment]
@mcollina You're right, `@types/pino` is a stub types definition and should not be used. Thanks!

But why did you close this issue? I think the documentation should contain an example to use the correct generics to solve the IDE errors.

**Comment by mcollina** [comment]
Would you like to send such a PR?
