### ISSUE TITLE
How can I Send out a request in Postman?

### ISSUE THREAD

**Issue by avilang** [fastify/fastify#419]
I start-up a HTTP Service through fastify and create a post request.
Then,is run well in Browser.But is bad in Postman.
error message:
`  "error": "Unprocessable Entity",
    "message": "",
    "statusCode": 422`

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
By default Fastify supports only `application/json` as content type. Are you setting it in your headers of your post request?

**Comment by avilang** [comment]
Yes,I have set it.
Content-Type: application/json;charset=UTF-8

**Comment by delvedor** [comment]
Can you paste your body?

**Comment by avilang** [comment]
```js
// app.js

const path = require('path');
const fastify = require('fastify')();
const fse = require('fs-extra');

fastify.get('/', async function(request, reply) {
  let fileBuffer = await fse.readFile(
    path.join(__dirname, './index.html')
  );

  reply
    .code(200)
    .type('text/html')
    .send(fileBuffer);
});

fastify.post('/post', async function(request, reply) {
  reply
    .code(200)
    .type('application/json')
    .send({ msg: 'post ok' });
});

fastify.listen(3000, function(err) {
  if (err) throw err;
  console.log(`server listening on ${fastify.server.address().port}`);
});
```
index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <script src="https://cdn.bootcss.com/axios/0.16.2/axios.js"></script>
</head>
<body>
  <script>
    var axiosInstance = axios.create();
    axiosInstance.post('/post', {}).then(function (data) {
      console.log(data);
    });
  </script>
</body>
</html>
```

**Comment by avilang** [comment]
that is run well in Browser.But is bad in Postman

**Comment by StarpTech** [comment]
@avilang What's your postman command? Click on "Code" at the right corner and paste the Curl or HTTP command in the issue.

**Comment by avilang** [comment]
```
curl -X POST \
  http://localhost:3000/post \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'postman-token: c77485cb-c3f6-2c70-cfe4-6c67950924e4'
```
@StarpTech

**Comment by StarpTech** [comment]
@avilang this is the same issue https://github.com/fastify/fastify/issues/297
fastify is responsible to parse `application/json` but your body contains no valid json.

Use an empty object as body
```
{}
```
or specify a [custom content-type parser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md) which can handle empty strings

**Comment by StarpTech** [comment]
Feel free to open another issue I think it's done.

**Comment by varunkamra** [comment]
> @avilang this is the same issue #297 fastify is responsible to parse `application/json` but your body contains no valid json.
> 
> Use an empty object as body
> 
> ```
> {}
> ```
> 
> or specify a [custom content-type parser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md) which can handle empty strings as valid json

https://github.com/fastify/fastify/blob/main/docs/Reference/ContentTypeParser.md is the correct URL to content parser readme if anyone gets a 404.
