### ISSUE TITLE
nullable schema like this {type: ["string", "null"], nullable: true, format: "url"} doesn't work for multipart form

### ISSUE THREAD

**Issue by hs-dev-web** [fastify/fastify#4199]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

the data being sent was a multipart form.

I don't put the link property inside required list
why it always complaining about the format like this:

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "body/link must match format \"url\""
}
```

I have set this:

`fastify.register(require('@fastify/multipart'), { addToBody: true })`

### Steps to Reproduce

easy to reproduce, please use this schema:

```
body: {
            type: 'object',
            required: ['image'],
            additionalProperties: false,
            consumes: ['multipart/form-data'],
            properties: {
                image: { format: 'binary' },
                link: { type: ["string", "null"], nullable: true, format: "url" },
            },
        }
```

and then submit the multipart form, duaaarrr it compalining

### Expected Behavior

allow nullable: true property passed without error bad request

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
