### ISSUE TITLE
setErrorHandler is not called on plugin error

### ISSUE THREAD

**Issue by qlaffont** [fastify/fastify#4204]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.0

### Plugin version

4.2.0

### Node.js version

16.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

Hi,
When I try to return an error from fastify plugin, I see that setErrorHandler is not called. 

I don't know why because I call my error handler plugin before to register my new plugin.

Thanks for the help ! 

### Steps to Reproduce

- Go to https://github.com/flexper/fastify-auth-prisma
- run `pnpm dlx ts-node test/core/real.ts`

### Expected Behavior

Should return formated error from https://github.com/flexper/unify-fastify

**Comment by climba03003** [comment]
I don't see how it will trigger the `error handler`. 
There is not route inside your example.

All yours request should go through `not found handler`.

**Comment by qlaffont** [comment]
My plugin will return an error for any route if it is not wrote in config. So for any route it will return an unauthorized error.

(if route exist or not).

**Comment by climba03003** [comment]
Just one through, it is reproducible when using `npm`?

**Comment by qlaffont** [comment]
I don't think it's due to package manager because package is loaded without any error.

**Comment by climba03003** [comment]
> I don't think it's due to package manager because package is loaded without any error.

It could cause by how package resolve since, `unify-errors` exists in two package as `dependency` and you are using `constructor` to check.

It depends on how `require.cache` to treats that two links and how the installed dependency structure.

**Comment by qlaffont** [comment]
I have done the same thing with npm. 

```
npm install
npx ts-node test/core/real.ts
```

Same issue, so i can confirm that currently is not working. 


As I see on your example, your preValidation is not in a fastify plugin so It not works.

A working example will be : 

```//@ts-nocheck
import fastify from 'fastify';
import fp from 'fastify-plugin';
import { Unauthorized } from 'unify-errors';
import unifyFastify from 'unify-fastify';

(async () => {
  const server = fastify();

  await server.register(unifyFastify, { hideContextOnProd: false });

  await server.register(
    fp(async (f) => {
      f.addHook('preValidation', async (request, reply) => {
        console.log('pre-validation hit');
        throw new Unauthorized();
      });
    }),
  );

  server.listen({ port: 3000 }).then(() => console.log('ready'));
})();
```

**Comment by climba03003** [comment]
I have tried both using `fastify-plugin` with or without it.
It doesn't affect the result, since it does not have encapsulation.

```js
import Fastify from 'fastify'
import FastifyPlugin from 'fastify-plugin'
import { Unauthorized } from 'unify-errors'
import unifyFastify from 'unify-fastify'

const fastify = Fastify()

await fastify.register(unifyFastify, { hideContextOnProd: false })
fastify.register(FastifyPlugin(function(fastify, _, done) {
  fastify.addHook('preValidation', function(request, reply, done) {
    console.log('pre-validation hit')
    throw new Unauthorized()
  })
  
  done()
}))


fastify.setNotFoundHandler(function() {
  console.log('not found handler hit')
})

{
  const { statusCode, payload } = await fastify.inject('/')
  console.log(statusCode, payload)
}
```

**Comment by climba03003** [comment]
I see the problem now.
It still something related to the `not found` handler. The only different is that I have added a custom `not found` handler and it works.

Without it, it doesn't.

**Comment by qlaffont** [comment]
Okay i will push an update on unify-fastify to add it, but it seems anyway that there is a bug on fastify

**Comment by mcollina** [comment]
Can you include a reproduction without external modules? Thanks

**Comment by qlaffont** [comment]
```typescript
import fastify from 'fastify';
import fp from 'fastify-plugin';

(async () => {
  const server = fastify();

  await server.register(fp(async(f) => {
    f.setErrorHandler((error, request, reply) => {
      console.log("error handler is called");
      reply.status(400).send("error");
    })
  }));

  await server.register(
    fp(async (f) => {
      f.addHook('preValidation', async (request, reply) => {
        console.log('pre-validation hit');
        throw new Error('test');
      });
    }),
  );

  server.listen({ port: 3000 }).then(() => console.log('ready'));
})();
```

```
pnpm dlx ts-node test.ts 
```

"error handler is called" will never be displayed

**Comment by climba03003** [comment]
I believe the problem is more complicated than I though.
Here are the multiple way trigger the same problem.

1. `await plugin registration`

```js
import Fastify from 'fastify'

const fastify = Fastify()

// if it is not await, it works fine
await fastify.register(async function(fastify) {
})

fastify.setErrorHandler(function(error, request, reply) {
  return reply.code(401).send({"error":"Unauthorized"})
})

fastify.addHook('preValidation', async function(request, reply) {
  console.log('pre-validation')
  throw new Error()
})

{
  const { statusCode, payload } = await fastify.inject('/')
  console.log(statusCode, payload) // should be 401 {"error":"Unauthorized"}
}
```

2. Set `error handler` within the `plugin`

```js
import Fastify from 'fastify'
import FP from 'fastify-plugin'

const fastify = Fastify()

// it doesn't matter if this is awaited or not
fastify.register(FP(async function(fastify) {
  fastify.setErrorHandler(function(error, request, reply) {
    return reply.code(401).send({"error":"Unauthorized"})
  })
}))

fastify.addHook('preValidation', async function(request, reply) {
  console.log('pre-validation')
  throw new Error()
})

// provide a empty not found handle works fine
// fastify.setNotFoundHandler()

{
  const { statusCode, payload } = await fastify.inject('/')
  console.log(statusCode, payload) // should be 401 {"error":"Unauthorized"}
}
```

**Comment by budarin** [comment]
have the same problem - throw an error in plugin and get `unhadledRejection` error instead processed it in setErrorHandler

**Comment by mcollina** [comment]
> I have the same problem - throw an error in the async request decorator and I get the unhandledRejection error instead of processing it in setErrorHandler - spent half a day looking for a problem

It's a different problem. Open a new issue with a minimum reproducible example.

**Comment by mcollina** [comment]
@climba03003 I have a fix coming for this.

**Comment by mcollina** [comment]
@qlaffont please check if https://github.com/fastify/fastify/pull/4205 solves this for you.
