### ISSUE TITLE
Headers type are not coherent with schema specified

### ISSUE THREAD

**Issue by DanieleFedeli** [fastify/fastify#4206]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.2

### Plugin version

2.1.1

### Node.js version

18.5.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0

### Description

When specifying a schema for headers, the type is not coherent with what is used on the schema.

Repository: https://github.com/DanieleFedeli/fastify-header-type

### Steps to Reproduce

```typescript
import Fastify from "fastify";
import { JsonSchemaToTsProvider } from "@fastify/type-provider-json-schema-to-ts";

const fastify = Fastify().withTypeProvider<JsonSchemaToTsProvider>();

const schema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
  },
  required: ["name"],
} as const;

fastify.get(
  "/",
  {
    schema: {
      headers: schema,
      params: schema,
      querystring: schema,
      body: schema,
    },
  },
  (req, reply) => {
    const fromParams = req.params.name;
    //    ^? TypeScript: fromParams is string
    const fromHeader = req.headers.name;
    //    ^? TypeScript: fromHeader is any
    const headers = req.headers;
    //    ^? TypeScript: headers is any
    const fromQs = req.query.name;
    //    ^? TypeScript: fromHeader is string
    const fromBody = req.body.name;
    //    ^? TypeScript: fromBody is string
  }
);

fastify.route({
  url: "/",
  method: "GET",
  schema: {
    headers: schema,
    params: schema,
    querystring: schema,
    body: schema,
  },
  handler: (req, reply) => {
    const fromParams = req.params.name;
    //    ^? TypeScript: fromParams is string
    const fromHeader = req.headers.name;
    //    ^? TypeScript: fromHeader is any
    const headers = req.headers;
    //    ^? TypeScript: headers is any
    const fromQs = req.query.name;
    //    ^? TypeScript: fromHeader is string
    const fromBody = req.body.name;
    //    ^? TypeScript: fromBody is string
  },
});


```

### Expected Behavior

I expect to have headers.name typed as string

**Comment by DanieleFedeli** [comment]
I investigated a bit and seems like the error come from here:
<img width="888" alt="Screenshot 2022-08-18 alle 19 24 12" src="https://user-images.githubusercontent.com/37077048/185457023-5780185b-8464-41a9-b337-f3d90e50a28d.png">

Inside my repository node_modules
<img width="418" alt="Screenshot 2022-08-18 alle 19 26 06" src="https://user-images.githubusercontent.com/37077048/185457322-6164665b-230b-4ac7-96b0-a40f63206dd2.png">

Fastify code
<img width="1548" alt="Screenshot 2022-08-18 alle 19 26 53" src="https://user-images.githubusercontent.com/37077048/185457453-ee2e040e-0227-42ef-a492-ef2c0df1f43c.png">

Looks like `import * as http from 'http'` is not resolved when importing fastify.

**Comment by Uzlopak** [comment]
did you install @types/node?

**Comment by DanieleFedeli** [comment]
This was the issue
