### ISSUE TITLE
feature to check if route already exists

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#4215]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be very useful if the Fastify instance exposes a method to check if a route is already registered in the current context just like it is implemented for content type parsers and constraints.

### Motivation

This feature could be useful for plugins to check if a certain route already exists and then add the route only if it does not yet exist in the current context.

### Example

```js
const fastify = require("fastify");

const app = fastify()

app.register(async (instance) => {
  instance.get('/test', async () => { return 'firstInstance' })

  instance.register(async (secondInstance) => {
    if (!secondInstance.hasRoute('/test')) {
      secondInstance.get('/test', async () => { return 'secondInstance' }) 
    }
  })
})

app.ready()
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by matthyk** [comment]
Absolutely! I will try to get the PR ready the next few days
