### ISSUE TITLE
@fastify/static with @fastify/compress,  @fastify/basic-auth not work together

### ISSUE THREAD

**Issue by suhaotian** [fastify/fastify#4219]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.2

### Node.js version

16.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

Here is the reproduce repo:

https://github.com/suhaotian/fastify-bug-reproduce

just run the code and visit `http://localhost:3080/public/index.html` and type username/password: ode/123456

you will see blank page, but it shouldn't. 

but disable the `@fastify/compress` plugin or the `@fastify/basic-auth` plugin, the page will work.

### Steps to Reproduce

just run the code and visit `http://localhost:3080/public/index.html` and type username/password: ode/123456

you will see blank page, but it shouldn't. 

but disable the `@fastify/compress` plugin or the `@fastify/basic-auth` plugin, the page will work.

### Expected Behavior

the page should work without disable some plugins

**Comment by mcollina** [comment]
You have a bug in your code: you are mixing promises and callbacks. This fixes it:

```diff
diff --git a/index.js b/index.js
index d87b286..3bcefc3 100644
--- a/index.js
+++ b/index.js
@@ -21,20 +21,13 @@ app.register(async (instance, opts, next) => {
     authenticate: {
       realm: "Simon Area.",
     },
-    validate: async (username, password, req, res, next) => {
-      try {
+    validate: async (username, password, req, res) => {
         const data = await readFile("basic-auth.json", "utf-8");
         const info = JSON.parse(data);

-        if (info[`${username}:${password}`]) {
-          next();
-        } else {
-          next(new Error("invalid payload!"));
+        if (!info[`${username}:${password}`]) {
+          throw new Error("invalid payload!");
         }
-      } catch (err) {
-        console.log(err);
-        next(err);
-      }
     },
   });
```

**Comment by suhaotian** [comment]
@mcollina It works! Thanks bro!!

**Comment by Durss** [comment]
> You have a bug in your code: you are mixing promises and callbacks. This fixes it:
> 
> ```diff
> diff --git a/index.js b/index.js
> index d87b286..3bcefc3 100644
> --- a/index.js
> +++ b/index.js
> @@ -21,20 +21,13 @@ app.register(async (instance, opts, next) => {
>      authenticate: {
>        realm: "Simon Area.",
>      },
> -    validate: async (username, password, req, res, next) => {
> -      try {
> +    validate: async (username, password, req, res) => {
>          const data = await readFile("basic-auth.json", "utf-8");
>          const info = JSON.parse(data);
> 
> -        if (info[`${username}:${password}`]) {
> -          next();
> -        } else {
> -          next(new Error("invalid payload!"));
> +        if (!info[`${username}:${password}`]) {
> +          throw new Error("invalid payload!");
>          }
> -      } catch (err) {
> -        console.log(err);
> -        next(err);
> -      }
>      },
>    });
> ```

Good lord you just saved me 2 years later thank you 🙏🏻 !
