### ISSUE TITLE
priorities for hooks

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4220]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to have an priority-Option for in addHook.

To implement this, I would modify addHook to not push the hook into the hook-Array, but push them into a HookSet. If no priority is given, it will default to 1. After the hook is added, it would do something like [...hookSet.values()].sort((a,b) => a.priority - b.priority) (or something faster by iterating over the hookSet) and assign its result to the actual hook-Array.

So theoretically it would not be a breaking change and it would be a relative small change. 

### Motivation

I want to write a plugins for my fastify server. Those plugins add hooks but because the hooks are working in the order of how they were added, it can result in incompatiblities. 

### Example

```js
fastify.addHook('preParsing', (request, reply, payload, done) => {
  // run this second
  done(null, newPayload)
}, { priority: 10 })

fastify.addHook('preParsing', (request, reply, payload, done) => {
  // run this third
  done(null, newPayload)
}, { priority: 20 })

fastify.addHook('preParsing', (request, reply, payload, done) => {
  // run this first
  done(null, newPayload)
}, { priority: 0 })
```

**Comment by mcollina** [comment]
I think three positional arguments are one too many.

Maybe do:

```js
fastify.addHook({
  phase: 'preParsing', // in our types we have this identified as `name`, but I think phase is a better term 
  hook: (request, reply, payload, done) => {
    // run this second
    done(null, newPayload)
  },
  priority: 10
})
```

I'm ok with the feature, however, I'm a bit worried if its extensive usage would result in harder-to-debug applications.

**Comment by metcoder95** [comment]
Is there any specific usage that wants to be covered with the feature?
AFAIK, the hooks are being appended in the order they're being attached ([ref](https://github.com/fastify/fastify/blob/0824881947ca7ccf9a947ced2dc539630aba47d5/lib/hooks.js#L58-L61)).

In encapsulated context, it still has more sense that upper levels have higher priority than ones in child instances.
Not so sure if this is in the documentation tho 🙂

**Comment by Uzlopak** [comment]
I want to implement authentication plugins for my solution. For that I want that the plugins add two hooks. One for handling the authentication and one to handle the case if not authenticated. The latter i would only add, if it was not already added. 

So the first registered plugin adds a onRequest hook to handle the authorization and another hook for for the unauthorized-case. It also decorates the fastify instance with a attribute named e.g. 'hasUnauthorizationHook'

Now my second plugin gets registered and also adds an authorization hook to onRequest, and because we already have a unauthorizedHandler (check if hasUnauthorizationHook exists)  it does not add the Unautorized Handler. 

Now i cant move the second authorization hook before the unauthorization hook. So if the user uses the authorization method of plugin 2, he cant because the unauthorization hook of plugin 1 will deny the access.

If I can set priorities, I can say: Well authorization hooks have a priority of -100 and the unauthorized hook has a priority of 100. So the authorization hooks are behind each other, and if the various authentication methods failed, i get it caught in the unauthorized hook, and deny access.

**Comment by avanelli** [comment]
> I'm ok with the feature, however, I'm a bit worried if its extensive usage would result in harder-to-debug applications.

Although it seems an exciting feature, I believe that the complications it could lead to are more significant than the advantages. Adding hooks with **arbitrary** priority numbers will quickly lead to unpredictable order execution in complex apps.

**Comment by Uzlopak** [comment]
Basically: I need more lifecycle stages. :D

**Comment by mcollina** [comment]
@Uzlopak the behavior you are describing in https://github.com/fastify/fastify/issues/4220#issuecomment-1228405761 is exactly why this feature is problematic. I would recommend to avoid plugins add those hooks and let your users install those hooks directly. https://github.com/fastify/fastify-auth was born to implement that fallback use case.

**Comment by Eomm** [comment]
> I want to implement authentication plugins for my solution. For that I want that the plugins add two hooks. One for handling the authentication and one to handle the case if not authenticated. The latter i would only add, if it was not already added.

I think this should be solved by using the `onRoute` hook. You will get the hook array, and you can inject a new hook in any position at that stage.
_It seems like the `fastify-redis` route's configuration if I understood the case_

If this feature will be implemented, I think that the `onRoute` hook must get the hook array already sorted

**Comment by mcollina** [comment]
I think this would make things more problematic instead of improving them.

**Comment by jsumners** [comment]
Closing as it seems the consensus is this would add too much complexity. As for the original problem, one solution is to use a single hook that inspects the request and decides between two functions: authorized and unauthorized. Such functions may decorate the request for later request processors to inspect.
