### ISSUE TITLE
Add support for named pipes (for ports) in new .listen method

### ISSUE THREAD

**Issue by jacknkandy** [fastify/fastify#4223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to make a request / suggestion for the new `.listen` method to be updated to work with named pipes for ports. 

I was attempting to deploy a Node.js app using fastify within a Microsoft Azure App Service, and encountered this error 

```
Application has thrown an uncaught exception and is terminated:
RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received \\.\pipe\5bff2bb4-cd18-4399-a4d8-9c95c968e908.
    at new NodeError (node:internal/errors:372:5)
    at validatePort (node:internal/validators:217:11)
    at Server.listen (node:net:1500:5)
    at C:\home\site\wwwroot\node_modules\fastify\lib\server.js:182:12
    at manageErr (C:\home\site\wwwroot\node_modules\fastify\fastify.js:540:11)
    at exit (C:\home\site\wwwroot\node_modules\fastify\lib\hooks.js:100:5)
    at manageTimeout (C:\home\site\wwwroot\node_modules\fastify\lib\hooks.js:117:11)
    at _encapsulateThreeParam (C:\home\site\wwwroot\node_modules\avvio\boot.js:557:7)
    at Boot.timeoutCall (C:\home\site\wwwroot\node_modules\avvio\boot.js:453:5)
    at Boot.callWithCbOrNextTick (C:\home\site\wwwroot\node_modules\avvio\boot.js:435:19)
```

Related to the following code:

```
this.fastify.listen({ port: process.env.PORT, }, (error, address) => {
    if (error) {
        this.fastify.log.error(error);
        process.exit(1);
    }
});
```

Although the `InjectOptions` interface shows the port can accept a string `port?: string | number` I assume that the string is just being converted to a number.

This request/issue is related to the following issue https://github.com/MicrosoftDocs/azure-docs/issues/92530#issue-1227644752

> I have some feedback regarding the section "[Get port number](https://docs.microsoft.com/en-us/azure/app-service/configure-language-nodejs?pivots=platform-windows#get-port-number) in the linked article:
> 
> > ### Get port number
> > You Node.js app needs to listen to the right port to receive incoming requests.
> > In App Service on Windows, Node.js apps are hosted with [IISNode](https://github.com/Azure/iisnode), and your Node.js app should listen to the port specified in the `process.env.PORT` variable. The following example shows how you do it in a simple Express app:
> 
> The heading indicates that the environment variable will be a port **number**, while in fact it is a [named pipe](https://en.wikipedia.org/wiki/Named_pipe#In_Windows). In the listed example this is not a problem as Express handles named pipes. However, other frameworks may require ports to be numbers, and they will therefore not work with the given pipe.
> 
> I would suggest adding a note to the paragraph explaining that this is in fact not a number, but a named pipe.
> 
> > **Note:** The value specified in `process.env.PORT` is not a number, it is in fact a string representing a [named pipe](https://en.wikipedia.org/wiki/Named_pipe#In_Windows). Express handles this with ease, but be aware that other frameworks might not.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 896b5d4c-ac3b-f0a2-5102-9e59bbe2ed48
> * Version Independent ID: 32fd9660-0d08-205c-c7f3-57b00f35e667
> * Content: [Configure Node.js apps - Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/configure-language-nodejs?pivots=platform-windows)
> * Content Source: [articles/app-service/configure-language-nodejs.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/app-service/configure-language-nodejs.md)
> * Service: **app-service**
> * GitHub Login: @cephalin
> * Microsoft Alias: **cephalin**

Unfortunately with Azure App Services you are unable to forward a custom ports through to IIS which is serving the app, and must use the assigned `PORT` environment variable which Azure manages.

I was able to use the old variadic listen method (noting that is deprecated and will be removed in v5). 

```
this.fastify.listen(process.env.PORT || 3000, error => {
    if (error) {
        this.fastify.log.error(error);
        process.exit(1);
    } 
});
```

I wonder why it works using the old method, but no longer works using the new.

Thanks!

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jacknkandy** [comment]
Not knowing much about named pipes, I first had a closer look at what was happening in the fastify code to see how it was working with the variadic method. 

https://github.com/fastify/fastify/blob/a3433a238df8cf5c07cc881a691c6518058dbf14/lib/server.js#L316-L320

I realise that its treating the string as a path instead of a port. So I am able to overcome my issue using the newer method which takes an object param as such:

```
this.fastify.listen({ path: process.env.PORT }, (error, address) => {
    if (error) {
        this.fastify.log.error(error);
        process.exit(1);
    }
});
```

I'll close this request, but hopefully this could be useful reference for anyone who encounters the same issue.

**Comment by jsumners** [comment]
The listen method accepts a standard `http.createServer` options object. If core supports named pipes on Windows, so does Fastify.

**Comment by dornfeder** [comment]
Thanks for the solution @jacknkandy, that helped a lot!  

Unfortunately, the listen method throws an error if you put *actual* Port numbers as `path` property, so for my case, having to run the code both on Azure with Named Pipes as well as locally with a real port number, this was the solution I came up with: 

```ts
const portNumber = Number(process.env.PORT);
await app.listen({
  host: '0.0.0.0',
  ...(isNaN(portNumber) ? { path: process.env.PORT } : { port: portNumber }),
}); 
```

It's not sexy, but it works.

**Comment by jacknkandy** [comment]
> Thanks for the solution @jacknkandy, that helped a lot!
> 
> Unfortunately, the listen method throws an error if you put _actual_ Port numbers as `path` property, so for my case, having to run the code both on Azure with Named Pipes as well as locally with a real port number, this was the solution I came up with:
> 
> ```ts
> const portNumber = Number(process.env.PORT);
> await app.listen({
>   host: '0.0.0.0',
>   ...(isNaN(portNumber) ? { path: process.env.PORT } : { port: portNumber }),
> }); 
> ```
> 
> It's not sexy, but it works.

No problem. Yeah this is pretty much the same way I handled it,
