### ISSUE TITLE
Fastify latest version not running on Node 16

### ISSUE THREAD

**Issue by akshg05** [fastify/fastify#4229]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 18.0.4

### Description

When trying running my app, I'm getting error : 
Uncaught SyntaxError
const hostPath = listenOptions.path ? [listenOptions.path] : [listenOptions.port ?? 0, listenOptions.host ?? 'localhost']
SyntaxError: Unexpected token '?'

I am not sure if this syntax is supported in node 16

### Steps to Reproduce

Just make a sample project with fastify and run it. Runtime is node 16

### Expected Behavior

It should run without errors.

**Comment by Uzlopak** [comment]
Looks like you are running node12 or older or latest node 16 has broken optional chaining.

**Comment by akshg05** [comment]
Thanks for responding. Yes seems like somehow my vs code terminal was picking up node 12.
