### ISSUE TITLE
Update v4 migration guide to use querystring instead of query

### ISSUE THREAD

**Issue by multiwebinc** [fastify/fastify#4237]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Description

In [Fastify v3](https://www.fastify.io/docs/v3.29.x/Reference/Validation-and-Serialization/#schemaerrorformatter), you could use either `query` or `querystring` for route validations, but for [fastify v4](https://www.fastify.io/docs/v4.5.x/Reference/Validation-and-Serialization/#schemaerrorformatter), `query` has been removed. This is not mentioned in the [Migration guide](https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/). I upgraded from 3.14.1 and I don't remember ever seeing any deprecation notices about this, and it is also not mentioned as being deprecated on the 3.29.x docs.

### Steps to Reproduce

n/a

**Comment by multiwebinc** [comment]
Wait, on second thought, I was confused about two parts of the docs. Maybe it is still supposed to work with `query` because it is mentioned [here](https://www.fastify.io/docs/master/Reference/Validation-and-Serialization/#validation), but this is actually a bug in the code. For example, this creates the error `FastifyError: Schema with 'querystring' already present!`:

```
async function routes(fastify) {
  fastify.get(
    '/api/properties/:slug/availability',
    {
      schema: {
        query: Yup.object().shape({
        }),
      },
      validatorCompiler: () => true,
      handler: availabilityController.getAvailability,
    }
  );
}
```

Changing `query` to `querystring` works as expected.

**Comment by climba03003** [comment]
`query` should works as usual,  maybe somewhere inside your code mess it up.
For example, `onRoute` hooks modify the schema.

I do not use `yup`, but it should not make any different.
```js
import Fastify from 'fastify'

const fastify = Fastify()

fastify.get('/', {
  schema: {
    query: { type: 'object', properties: { hello: { const: 'world' } } }
  }
}, (request) => request.query)

const response = await fastify.inject('/?hello=world')
console.log(response.body)
```

**Comment by multiwebinc** [comment]
@climba03003 The problem arises when I use Yup. I just did a fresh install of Fastify (`npm init fastify` then `npm i yup`) and get the same error. Here is my `routes/root.js`:

```js
'use strict'

const Yup = require('yup');

module.exports = async function (fastify, opts) {
  fastify.get('/', {
    schema: {
      query: Yup.object(),
    },
    validatorCompiler: () => true,
  }, (request) => request.query)
}
```

But if I swap out `query` for what you have, or rename it as `querystring` using Yup, then it works.

**Comment by climba03003** [comment]
> Would this be a bug with Fastify or with Yup?

Yes, I can confirm it is the problem with custom `class` object.

The problem caused by we mutated the `schema` but return early when `schema` is not a raw object.
https://github.com/fastify/fastify/blob/6f6f7aa2d069a506b69ca42fbecef170ee667d4b/lib/schemas.js#L63-L67

Then, when it comes to auto `HEAD` route, the schema `cloned` do not contain [`kSchemaVisited`](https://github.com/fastify/fastify/blob/6f6f7aa2d069a506b69ca42fbecef170ee667d4b/lib/schemas.js#L92) and leads to failure.

Would you like to send a PR to address the issue?

**Comment by multiwebinc** [comment]
@climba03003 I would make a PR, but I am really totally unfamiliar with the codebase. Even with your description I have no idea what would need to be changed.

**Comment by Uzlopak** [comment]
I think @climba03003 meant that you provide a PR not the other way round.

**Comment by climba03003** [comment]
> I think @climba03003 meant that you provide a PR not the other way round.

Oh, I click the wrong button.
I plan to reply, but clicked edit.
