### ISSUE TITLE
How to import fastify error codes?

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4250]
### Discussed in https://github.com/fastify/fastify/discussions/3842

<div type='discussions-op-text'>

<sup>Originally posted by **teemupiiroinenwirepas** April 20, 2022</sup>
We would like to map fastify error codes from https://github.com/fastify/fastify/blob/main/lib/errors.js to our own error codes, but we cannot find a way how to import the codes. How the importing should be done, or how the error code mapping should be done to the application specific error codes?

Br,
Teemu</div>

---

We should:

- [ ] export the errors from this utility https://github.com/fastify/fastify/blob/main/lib/errors.js
- [ ] generate/update the corresponding page https://github.com/fastify/fastify/blob/main/docs/Reference/Errors.md
- [ ] generate/update the typescript interface as well

**Comment by Uzlopak** [comment]
Also dont forget that fastify plugins have their own errors. Maybe we should register those errors also?

**Comment by fitiskin** [comment]
I'd like to do this. Assign it to me please, if @teemupiiroinenwirepas don't mind.

**Comment by Eomm** [comment]
> Maybe we should register those errors also?

This integration would be nice, but it should be transparent for the `@fastify/errors` users

**Comment by mcollina** [comment]
Let's not include plugins.

**Comment by fitiskin** [comment]
I can't understand how [this](https://www.fastify.io/docs/latest/Reference/Server/#frameworkerrors) is supposed to be working while we can't import `FST_ERR_BAD_URL` directly.

**Comment by fitiskin** [comment]
Should we export only error codes (string names) or the errors produced by `createError`?

Error codes:
```js
const fastify = require('fastify')

exampleErrorHandler((err) => {
    if (err.code === fastify.errorCodes.FST_ERR_NOT_FOUND) {
        //
    }
})
```

Errors: 
```js
const fastify = require('fastify')

exampleErrorHandler((err) => {
    if (err instanceof fastify.errorCodes.FST_ERR_NOT_FOUND) {
        //
    }
})
```

As I guess we shouldn't export the `appendStackTrace` utility function.

**Comment by Eomm** [comment]
> Should we export only https://github.com/fastify/fastify/discussions/3842#discussioncomment-2609598 (string names) or the errors produced by createError?

The latter 👍🏽 

> As I guess we shouldn't export the appendStackTrace utility function.

Yes, there is not value for the user getting it
