### ISSUE TITLE
Wrong serialization with anyOf schema

### ISSUE THREAD

**Issue by noamokman** [fastify/fastify#4251]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

There seems to be a bug where if the schema is anyOf between a string and a number, if we send the number  it is received as string.
I have here a tests that demonstrates the issue

### Steps to Reproduce

```js
'use strict'

const t = require('tap')
const Fastify = require('../fastify')

t.test('any-of', async t => {
  t.plan(1)
  const fastify = Fastify()

  const schema = {
    type: 'object',
    properties: {
      value: {
        anyOf: [
          {
            type: 'string'
          },
          {
            type: 'number'
          }
        ]
      }
    },
    required: [
      'value'
    ]
  }

  const controller = async (fastify) => {
    fastify.post(
      '/',
      {
        schema: {
          body: schema
        }
      },
      async (body) => (body)
    )
  }

  fastify.register(controller)

  await fastify.ready()

  const body = {
    value: 5
  }

  const response = await fastify.inject({
    method: 'POST',
    url: '/',
    body
  })

  t.strictSame(response.json().body, body)
})

```

### Expected Behavior

sending a number value should be received as a number value

**Comment by jsumners** [comment]
See https://ajv.js.org/coercion.html. It `anyOf` will match the first valid type.

**Comment by noamokman** [comment]
oh wow, thanks!
