### ISSUE TITLE
Replace querystring with fast-querystring package

### ISSUE THREAD

**Issue by anonrig** [fastify/fastify#4252]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Since `node:querystring` is deprecated, with the help of @mcollina, I developed a package as fast as (in certain cases faster than) `node:querystring` and released it under MIT license.

I believe we can replace the deprecated module, and use it in `find-my-way` pkg.

The benchmarks, code & docs are available from https://github.com/anonrig/fast-querystring.

**Comment by mcollina** [comment]
Note that `node:querystring` is not deprecated but legacy.

**Comment by xr0master** [comment]
**question**: why not use `URLSearchParams` as the official replacement for legacy querystring? I don't want to underestimate the great work of the author, but there is a big difference between the built-in official module and the third-party library. At least in matters of further support.

**Comment by Uzlopak** [comment]
URLSearchParams is slow. We will not degrade the performance just for the sake of a module which is just marked as legacy and is not deprecated.

**Comment by xr0master** [comment]
I think that in real use the difference will be zero. But the chance that this library will stop receiving updates in a few months is quite high. On the other hand, reverting changes and reverting back to an obsolete module is also not difficult. IMO

In any case, thanks for your work, a wonderful project that I enjoy using in projects. Especially after the dead express.js
