### ISSUE TITLE
How to format error message in Fastify response?

### ISSUE THREAD

**Issue by mikemfleming** [fastify/fastify#426]
I want to send back a more human readable error message when a request fails validation because the one that is sent back by default is a bit mangled. What is the best way to go about doing this?

Server response to a bad request:
```
{
    "error": "Bad Request",
    "message": "[{\"keyword\":\"required\",\"dataPath\":\"\",\"schemaPath\":\"#/anyOf/0/required\",\"params\":{},\"message\":\"should have required property '.name'\"},{\"keyword\":\"anyOf\",\"dataPath\":\"\",\"schemaPath\":\"#/anyOf\",\"params\":{},\"message\":\"should match some schema in anyOf\"}]",
    "statusCode": 400
}
```

**Comment by mikemfleming** [comment]
In the event that I'm using a regex pattern in my schema validation it returns that pattern to the client which seems a bit unsafe. Thoughts?

**Comment by BigMurry** [comment]
Perhaps you can try this 
https://github.com/epoberezkin/ajv-errors

But first you need to get  the raw schema validation errors, can use `extendServerError`:
```js
fastify.extendServerError(err => {
  if (err.ajv) { // I don't try this as I use joi. In joi I can get err.isJoi === true
    // do your customization here
  }
})
```

**Comment by mcollina** [comment]
@mikemfleming you should really customize these. There is a `fastify.setNotFoundHandler()` and  `fastify.setErrorHandler()`.

**Comment by mcollina** [comment]
I'm also happy with a better default, if you want to send a PR.

**Comment by mikemfleming** [comment]
Thanks for the quick responses!

I looked through the source code but haven't found where to alter this just yet. I'll continue to look at it, but in the meantime this is what solved my issue:
```
fastify.setErrorHandler((error, reply) => {
    error.message = JSON.parse(error.message);
    reply.send(error);
  });
```
It's fine for internal use although it could be improved. I'm also not sure if/how it affects optimizations from fast-json-stringify.

**Comment by jsumners** [comment]
@mikemfleming can you try current master (which should become v0.37.0) to see if this issue is solved for you?

**Comment by delvedor** [comment]
Closing this, feel free to reopen if you have more questions :)

**Comment by rungta08** [comment]
How to give a custom validation error format???

**Comment by Eomm** [comment]
Check out here:
https://github.com/fastify/example/tree/master/validation-messages

And right now customizing AJV is even easier:
https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#ajv-plugins

**Comment by mustakimkr** [comment]
I think We need to standardize the validation error message. It's quite hard to extract error messages and show proper error messages to users.

`[
    {
        "instancePath": "",
        "schemaPath": "#/errorMessage",
        "keyword": "errorMessage",
        "params": {
            "errors": [
                {
                    "instancePath": "",
                    "schemaPath": "#/required",
                    "keyword": "required",
                    "params": {
                        "missingProperty": "name"
                    },
                    "message": "must have required property 'name'",
                    "emUsed": true
                }
            ]
        },
    }
]` 

quite horrible to extract the proper message from this. we need to standardize defaults.

**Comment by Eomm** [comment]
This issue is 4 years old. Open a new one to discuss it.

Meanwhile a lot has been done to do it:
https://stackoverflow.com/a/77296637/3309466

Anyway, the format is defined by the validation framework.
Fastify uses AJV under the hood, so the error is an AJV error.
If you don't like it, you need to use another lib such JOI.

I wrote the schema compiler in case: https://github.com/Eomm/joi-compiler
The error there are totally differents

Locking the issue as completed
