### ISSUE TITLE
Variadic listen signature is not working anymore

### ISSUE THREAD

**Issue by simoneb** [fastify/fastify#4267]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.x

### Stopped working in version

4.x

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

-

### 💥 Regression Report

As per the [blog post](https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e) (note that this is not mentioned in the migration guide of the docs, just the blog post) the variadic signature of the `listen` method is deprecated.

What I found is that it's actually broken for a fairly simple use case, that of providing the port via an environment variable. I suspect the problem is with the type. If you provide it as a number, it works. When it comes from an environment variable it's a string. This scenario doesn't work anymore.

I would have expected the signature to be deprecated but still work, but in practice this use case no longer works.

### Steps to Reproduce

With this server:

```js
// index.js
import fastify from 'fastify'

const app = fastify({
  logger: true
})

app.listen(process.env.PORT, '0.0.0.0')
```

Running with:

```sh
PORT=12345 node index.js
```

Gives (note that it runs on a random port):

```sh
{"level":30,"time":1662976097851,"pid":6028,"hostname":"X86","msg":"Server listening at http://0.0.0.0:63694"}
```

### Expected Behavior

It should be running on the port specified in the PORT environment variable.

**Comment by Fdawgs** [comment]
> As per the [blog post](https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e) (note that this is not mentioned in the migration guide of the docs, just the blog post) the variadic signature of the `listen` method is deprecated.

https://www.fastify.io/docs/master/Guides/Migration-Guide-V4/#deprecation-of-variadic-listen-signature, only in master atm but it's there. 😁

**Comment by mcollina** [comment]
Even if it's deprecated, this should be fixed.

**Comment by simoneb** [comment]
@marco-ippolito is planning to look into this

**Comment by marco-ippolito** [comment]
The problem seems to appear only when the port is passed as string, I'm working on a fix

**Comment by jsumners** [comment]
Yep. Bug. Will be so glad when we can remove all of this code.
