### ISSUE TITLE
exposeHeadRoute and manually generated head routes not really distingiushable

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4271]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The automatically generated Head route (exposeHeadRoute: true) gets in fastify-rate-limit the routelimit hook twice. 

I can patch it as you can see https://github.com/fastify/fastify-rate-limit/pull/267 by checking if the exposeHeadRoute is set to true. But this can also mean that if you explicitly set exposeHeadRoute on a head-route to true to also not adding the rateLimit hook to the head-route.
See:
https://github.com/fastify/fastify-rate-limit/blob/93ce1e5ae90ffb92f9030f9e3117980ec9e0606d/test/route-rate-limit.test.js#L1410

So it would be nice that we could make the HEAD-routes generated by exposeHeadRoute detectable. Like adding an additional atrtibute to the routeOptions like autogeneratedRoute or isFastify for expressing that fastify added that route?! 

Or we decide that setting exposeHeadRoute on head makes no sense anyway and the linked PR to the plugin is sufficient. Maybe throwing an error if we set exposeHeadRoute on a head-route could also be applicable.

**Comment by climba03003** [comment]
`isFastify` is the property means to be the `route` added by `fastify`.
I create this property for this purpose, but something also need to be fixed inside the core.

**Comment by climba03003** [comment]
Nope, we are re-using the mutated option which cause the problem.
