### ISSUE TITLE
addSchema prevents reuse of fluent-json-schema objects

### ISSUE THREAD

**Issue by esatterwhite** [fastify/fastify#4276]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Node.js version

16.14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux 5.10.136-1-MANJARO  x86_64 GNU/Linux

### Description

Using `addSchema`  seems to prevent the reuse of the same schema with modifications - this is particularly restrictive when using `fluent-json-schema`.  This prevents you from being able to re-use the schema object for both input and response validations.

```javascript
fastify.addSchema(Thing)

fastify.route({
  method: 'POST'
, path: '/thing'
, schema: {
    body: Thing.only('whiz')
  , response: {
      200: Thing
    }
  }
})
```

Additionally, when Using the openapi bits in `@fastify/swagger` It seems you have to use `addSchema` to have them show up properly in the `compoments.schema` section of the documentation.

Commenting out `fastify.addSchema(Thing)` allows me to re-use the schema for multiple purposes, however, the swagger/openapi documentation ends up missing a lot of information. and the use of `ref` no longer works.

### Steps to Reproduce

There is a reproduction gist [here](https://gist.github.com/esatterwhite/9fc6e3bf0ee4ef08b5063120f865bc3b)

### Expected Behavior

When using fastify w/ fluent-json-schema, I would expect to be able to define a full schema object , register that with fastify as a canonical type, and be able to reuse the fluent schema object to generate subsets of that for other validation points.

**Comment by mcollina** [comment]
What error are you getting?

@Eomm @climba could you take a look?

**Comment by esatterwhite** [comment]
A validation error for `bang` being required
```bash
curl -X 'POST' \
  'http://localhost:3000/whizbang' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "whiz": "string"
}'
```
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "body must have required property 'bang'"
}
```

In the gist linked, the post route will expect both the `whiz` and `bang` properties to be sent in the body as the registered schema has both a `required`.

But the body schema is a modification for only whiz. If I don't call `addSchemas`, the route works as expected

**Comment by esatterwhite** [comment]
I gather its because the schema controller caches by id so route validator is pulling the original validator instead of the one defined on the route

**Comment by climba03003** [comment]
> I gather its because the schema controller caches by id

You cannot have the same `$id` throughout the same `application`. The `$id` should be globally unique.

**Comment by esatterwhite** [comment]
How would one go about making fluent-json-schema and the swagger plug in work together with out having to redefine the same schema multiple times?

**Comment by esatterwhite** [comment]
I don't want to use the ID more than once necessarily. Is there a way to keep out the I'd? Or have the route validators not reference the global cache if they are given a fluent instance.

**Comment by Eomm** [comment]
I wonder if:

- should the `$id` be removed from the route's schema?
- OR should we throw an error if the same **root** `$id` is found in the schema bucket?

I think the latter is easy to add

----

Generally, I think the user should be able to customize the $id when using `fluent.only()/without()`

**Comment by esatterwhite** [comment]
I feel like the routes validation schemas should only reference the shared schemas if the schema is a `ref`
Having to manually set a dummy id, and by all accounts, a globally unique dummy id, for every route validation schema feels a little ham-fisted.

**Comment by zrosenbauer** [comment]
@Eomm IMO throw the error. Removing it from the bucket is an unexpected side effect that would be buried (cause a debugging nightmare IMO).

Also dumb question here... is this a fastify issue or fluent-json-schema issue...?

Isn't this line here: [https://github.com/fastify/fluent-json-schema/blob/664f052223ec67da9c1f300c0baddabcbbee2c7f/src/ObjectSchema.js#L344](https://github.com/fastify/fluent-json-schema/blob/664f052223ec67da9c1f300c0baddabcbbee2c7f/src/ObjectSchema.js#L344) saying it merges the existing schema but overrides the properties.... aka the ID is the same though the return value is not.... IMO a new ID should be generated or something of that nature otherwise its not a 1 to 1 (but I'm very new to fastify code bases here :smile:)

**Comment by esatterwhite** [comment]
In the case of route validators, the id doesn't seem to have much usefulness or significance unless you are using a ref. The ids are not being registered twice, so I do not think this is an error case. 

> a new ID should be generated or something of that nature otherwise its not a 1 to 1

1 to 1 with what? I think a generates ID would be more confusing. As an end user, I won't know what it is and will be unable to reference it. 

Only and without could at least remove the id, it is a new schema. If I want to give it an id I can do that.

**Comment by zrosenbauer** [comment]
Again if we omit the ID wouldn't that be on the fluent side? I don't know the return value of `.only`.

I just used your gist and this was output:
```js
console.log(WhizBang.only('whiz').valueOf())

const consoleOutput = {
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  '$id': 'whizbang',
  title: 'WhizBang',
  properties: { whiz: { type: 'string', minLength: 1 } },
  required: [ 'whiz' ]
}
```

Aka this needs to be fixed on the fluent side (https://github.com/fastify/fluent-json-schema/issues/193).

Moving convo there...
