### ISSUE TITLE
Is it possible for the request.validateInput (and other such funcs) add the errors property by analogy as ajv does?

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#4281]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I suggest adding to `request.ValidateInput`, as well as the functions returned by `compilerValidationSchema ` and `getValidationFunction`, the `errors` property after performing the validation, as does `ajv`:

```js
const validate = ajv.compile({
  type: 'object', 
  properties: { 
    foo: { 
      type: 'string' 
    } 
  } 
})

validate({ foo: 1 }) // false
validate.errors  // validation errors
```

### Motivation

It is important for us to receive not only the result of the check, but also errors of data inconsistency with the scheme

### Example

for getValidationFunction:
```js
const validate = request.getValidationFunction({
  type: 'object', 
  properties: { 
    foo: { 
      type: 'string' 
    } 
  } 
})

validate.errors // undefined
validate({ foo: 0.5 }) // false
validate.errors // validation errors 

validate({ foo: 'bar' }) // true
validate.errors // undefined
```

for compileValidationSchema:

```js
const validate = request.compileValidationSchema({
  type: 'object', 
  properties: { 
    foo: { 
      type: 'string' 
    } 
  } 
})

validate.errors // undefined
validate({ hello: 'world' }) // false
validate.errors // validation errors
```

for request.validateInput:

```js
request.validateInput.errors // undefined
request.validateInput({ foo: 'bar'}, {  
  type: 'object', 
  properties: { 
    foo: { 
      type: 'string' 
    } 
  } 
}) // true
request.validateInput.errors // undefined

request.validateInput({ hello: 'world'}, 'query') // false
request.validateInput.errors //validation errors
```

**Comment by metcoder95** [comment]
Hey! That should be already possible as the new APIs don't mess with the Ajv or any other validation function compiled, meaning that you can still access such errors and result properties.

Here's an example:
```js
const fastify = require('fastify')

const app = fastify({ logger: true })

app.post(
  '/',
  {
    schema: {
      body: {
        type: 'object',
        required: ['name'],
        properties: {
          name: { type: 'string' }
        }
      }
    }
  },
  (request, reply) => {
    const customCompiled = request.compileValidationSchema({
      type: 'object',
      required: ['something'],
      properties: {
        name: { type: 'string' },
        something: { type: 'string' }
      }
    })
    const routeValidation = request.getValidationFunction('body')

    const result = routeValidation({ something: 'something' })
    const customResult = customCompiled({ name: 'John' })

    // console.log(routeValidation)
    console.log(routeValidation.errors)
    console.log(customCompiled.errors)

    reply.send({ hello: 'world' })
  }
)

app.inject({
    method: 'POST',
    url: '/',
    payload: {
        name: 'John'
    }
}).then(() => console.log('done'))

```

and then prints:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/10200776/190582723-afed5a51-1ae7-4464-97a8-9eaa90263a69.png">

**Comment by budarin** [comment]
To be honest, I haven't tried with `compilerValidationSchema` and `getValidationFunction` - I checked with `request.ValidateInput` and in this case there are definitely no `errors`, which is why I assumed that other methods have the same situation

**Comment by budarin** [comment]
the description of the types of these functions also reflects the fact that functions have this property

```ts
  getValidationFunction(httpPart: HTTPRequestPart): (input: any) => boolean
  getValidationFunction(schema: {[key: string]: any}): (input: any) => boolean
  compileValidationSchema(schema: {[key: string]: any}, httpPart?: HTTPRequestPart): (input: any) => boolean
  validateInput(input: any, schema: {[key: string]: any}, httpPart?: HTTPRequestPart): boolean
  validateInput(input: any, httpPart?: HTTPRequestPart): boolean
```

**Comment by climba03003** [comment]
`validateInput` shouldn't have the `errors` property. It will mess up with multiple usage of same function.

If the problem is only incorrect typings. Would you like to send a PR to address the issue?

**Comment by budarin** [comment]
I'll try
