### ISSUE TITLE
CORS error while trying to run in Localhost

### ISSUE THREAD

**Issue by rmi111** [fastify/fastify#4287]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,
I have been trying GraphQL tutorial from the official documentation. I built the backend using the typescript-helix version, it uses fastily. It runs at http://localhost:4000/graphql routes. All the queries works well when I am using curl and graphiql playground. 

Then I tried to build their frond end react based project which try to connect to the GraphQL server using ApolloClient. Instead of their given server code I tried to connect from the one I built. But I am getting the following errors:

```Access to fetch at 'http://localhost:4000/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

Below is the both index file where the relevant code resides.

[index_server.txt](https://github.com/fastify/fastify/files/9593263/index_server.txt)
[index_client.txt](https://github.com/fastify/fastify/files/9593265/index_client.txt)

I tried many different way to resolve the issue ,but nothing worked. Spent whole night behind this. 
Thanks

**Comment by climba03003** [comment]
I didn't read any code. But you should use [`fastify-cors`](https://github.com/fastify/fastify-cors).
Please check the readme and allow the `origin` of the `request` you have.

Another way is use `proxy` in the frontend project, so the `frontend` and `backend` are under the same domain.

**Comment by climba03003** [comment]
After reading the code, I suspect you are actually mutating the `.raw` stream directly.
In this case, non of the `fastify` hook and `plugin` will works. Their data is actually stored inside the `requset` object and should be handled by `fastify`.

If you plan to directly interact with `.raw`, you need to do all the thing yourself including `.setHeader`.

**Comment by rmi111** [comment]
Ok that explains a lot. How can I avoid without mutating the raw, or if I go in that approach, how can I write header, 
I tried the setHeader approach, but it gives me another error, cannot set header after being sent.

**Comment by climba03003** [comment]
> How can I avoid without mutating the raw

I suggest to reach `graphql-helix` for supporting `fastify`. 
It use `.writeHead` directly, that means you can either make an wrapper of it. or `.raw.setHeader` before hand for the `CORS`.

Maybe that would works?

```js

// forward header to `.raw` before direct interact with `.raw` by `graphql-helix`
const headers = reply.getHeaders()
for(const key of Object.keys(headers)) {
  reply.raw.setHeader(key, headers[key])
}

```

**Comment by rmi111** [comment]
That worked. Thanks for your help.
