### ISSUE TITLE
Docs: Testing - request package has been deprecated

### ISSUE THREAD

**Issue by CristiTeo** [fastify/fastify#4296]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The `request` package has been deprecated.
Inside the documentation for Testing guide exists an example that is using it.
https://www.fastify.io/docs/latest/Guides/Testing/#example
<img width="1216" alt="Screenshot 2022-09-22 at 13 48 46" src="https://user-images.githubusercontent.com/81955552/191727753-ba6dcdb3-ec3f-41e0-877c-d917bd4f0030.png">

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by CristiTeo** [comment]
Sure, I am working on this.

**Comment by simoneb** [comment]
@mcollina any thoughts about which library we should recommend. The only thing we settled on so far is Node 18's new global fetch, but we thought it best to also include something else which is usable from Node < 18

**Comment by jsumners** [comment]
Use the basic `Client` from Undici https://gist.github.com/jsumners/0e5b3b929e692757364f545f97b6273f#file-index-mjs-L93-L99
