### ISSUE TITLE
TypeError: currentNode.createStaticChild is not a function

### ISSUE THREAD

**Issue by nicolaturcato** [fastify/fastify#4299]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.6.0

### Plugin version

4.2.1

### Node.js version

18.7

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

I'm trying to upgrade to Fastify v4.x but since first release of v4 I'm getting this error:
`unhandledRejection: TypeError: currentNode.createStaticChild is not a function`
which happens on `node_modules/find-my-way/index.js:190:33`.
I'm running the latest versions of Fastify and Plugin version on Node.js v18.7.

### Steps to Reproduce

I immediately get the error when trying to start the server.

**Comment by climba03003** [comment]
Can you provide a reproducible code?

**Comment by climba03003** [comment]
`Wildcard` follow by `Static` path is no longer supported.
Please change the `path` to `RegExp` path as mention in the `find-my-way` issue.

If you think it is not a duplicate issue. Feel free to re-open.

**Comment by nicolaturcato** [comment]
@climba03003 forgot to answer back... Thanks a lot that was the issue!
