### ISSUE TITLE
docs: add the note that request.params is always Record<string, string> when using TypeBoxValidatorCompiler

### ISSUE THREAD

**Issue by seia-soto** [fastify/fastify#4314]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Describe the type of request.params is always `Record<string, string>` when using TypeBoxValidatorCompiler to the one of following section:
- https://www.fastify.io/docs/latest/Reference/TypeScript/#typebox
- https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#validation

### Motivation

> This is not a bug, but I think this is unintended for me didn't fully understand how typebox work.

When testing with light-my-request, I thought Typebox will automatically detect the numeric(or string readable as number) parameter. However, in actual, it light-my-request and Fastify processed the parameter just directly to string. To remove future mistakes, I think it would be nice to add this to documentation.

- Manual numeric exmaple on here: https://github.com/fastify/fastify-type-provider-typebox/issues/25#issuecomment-1186074277

Note that I don't know where is the correct place to add this phenomenon except for TypeScript section or Validator section. The recommendation is welcomed.

### Example

I set up example route to simply check the type of `request.params.test`.

```typescript
import Fastify from 'fastify';

const fastify = Fastify()

fastify.get('/:test', async (req, res) => {
	console.log(req.params);

	return {
		a: typeof req.params.test,
	};
});

fastify.listen(80)
```

Accessed to `http://localhost/1` and checked the following response came.

> Checking the type of `request.params.test` on preValidation hook resulted same.

```json
{
  "a": "string"
}
```

Following to above result, TypeBoxValidatorCompiler will throw validation error for all Params JSON Schema expressing its non-string value because it only validates using `typeof`.

**Comment by seia-soto** [comment]
Note that this can be recognized as useless. I agree with that 😄.

**Comment by climba03003** [comment]
You example do not show you are using `TypeBoxValidatorCompiler` and any `schema`.
The current behavior is correct when you don't have `schema`.

**Comment by seia-soto** [comment]
Oh, I understand. However, still there is no magic required.

```ts
import { TypeBoxTypeProvider, TypeBoxValidatorCompiler } from '@fastify/type-provider-typebox'
import { Type } from '@sinclair/typebox'
import Fastify from 'fastify'

// Servers
const fastifyWithTypeBox = Fastify()
  .withTypeProvider<TypeBoxTypeProvider>()
  .setValidatorCompiler(TypeBoxValidatorCompiler)

fastifyWithTypeBox.get('/:test', {
  schema: {
    params: Type.Object({
      test: Type.Number()
    })
  },
}, (req, reply) => {
  return req.params
})

const fastify = Fastify()

fastify.get<{ Params: { test: number } }>('/:test', {
  schema: {
    params: {
      type: 'object',
      properties: {
        test: {
          type: 'number'
        }
      }
    }
  }
}, (req, reply) => {
  return req.params
})

// Requests
fastifyWithTypeBox.inject({
  url: '/1',
  method: 'GET',
})
  .then(response => {
    console.log(response.body.toString()) // {"statusCode":400,"error":"Bad Request","message":"params/test Expected number"}
  })

fastify.inject({
  url: '/1',
  method: 'GET',
})
  .then(response => {
    console.log(response.body.toString()) // {"test":1}
  })
```
