### ISSUE TITLE
Adding shared schema in current encapsulated context

### ISSUE THREAD

**Issue by rluvaton** [fastify/fastify#4316]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

What if we could write inside an encapsulated context shared schema

let's say I have a typical REST server and these are my routes (I use the GitHub routes as an example)

```
# Repo management
GET /repos/:owner/:repo
DELETE /repos/:owner/:repo
GET /repos/:owner/:repo/events

# Issues management
GET /repos/:owner/:repo/issues
POST /repos/:owner/:repo/issues

# Single issue management
GET /repos/:owner/:repo/issues/:issue_number
PATCH /repos/:owner/:repo/issues/:issue_number
DELETE /repos/:owner/:repo/issues/:issue_number

# and more...
```

Currently for each route group here I would need to duplicate my scheme parameters
```typescript
export default async function (fastify) {
  // fastify routes here...

  // GET /repos/:owner/:repo
  fastify.get(
    "/",
    {
      schema: {
        params: {
          type: "object",
          properties: {
            owner: {
              type: "string",
            },
            repo: {
              type: "string",
            },
          },
        },
      },
    },
    async (req) => {
      // ...
    }
  );

  // DELETE /repos/:owner/:repo
  fastify.get(
    "/",
    {
      schema: {
        params: {
          type: "object",
          properties: {
            owner: {
              type: "string",
            },
            repo: {
              type: "string",
            },
          },
        },
      },
    },
    async (req) => {
      // ...
    }
  );

  // GET /repos/:owner/:repo/events
  fastify.get(
    "/",
    {
      schema: {
        params: {
          type: "object",
          properties: {
            owner: {
              type: "string",
            },
            repo: {
              type: "string",
            },
          },
        },
        querystring: {
          type: "object",
          properties: {
            per_page: {
              type: "number",
            },
            page: {
              type: "number",
            },
          },
        },
      },
    },
    async (req) => {
      // ...
    }
  );
}

// Prefix for fastify autoload
export const autoPrefix = `/repos/:owner/:repo`;
```

and so on...

what if instead, we can define a shared schema that will be merged with the routes schema in the current context?

### Motivation

The motivation is that I won't need to respecify the parameters every time

FYI, this started as a [StackOverflow question](https://stackoverflow.com/questions/73907366/setting-shared-schema-for-multiple-fastify-routes/73916447#73916447) and the great @Eomm answered me with a workaround

### Example

```typescript
export default async function (fastify) {
  // fastify routes here...
  fastify.setSharedSchema({
    params: {
      type: "object",
      properties: {
        owner: {
          type: "string",
        },
        repo: {
          type: "string",
        },
      },
    },
  });

  // GET /repos/:owner/:repo
  fastify.get("/", async (req) => {
    // ...
  });

  // DELETE /repos/:owner/:repo
  fastify.delete("/", async (req) => {
    // ...
  });

  // GET /repos/:owner/:repo/events
  fastify.get(
    "/",
    {
      schema: {
        querystring: {
          type: "object",
          properties: {
            per_page: {
              type: "number",
            },
            page: {
              type: "number",
            },
          },
        },
      },
    },
    async (req) => {
      // ...
    }
  );
}

// Prefix for fastify autoload
export const autoPrefix = `/repos/:owner/:repo`;
```

----

**Comment by Eomm** [comment]
This can be done by a plugin. The scope of the fastify core is providing the minimal tool set to build things like the one you proposed.

The plugin needs to define a Decorator and a onroute hook.. And it is done! Would you like to build such a community plugin?

**Comment by iifawzi** [comment]
Hi, I think I have an interest in working on this, I'm just wondering, how far this should support. Should it only support sharing high-level schema keys? (without handling nested schemas) or the plugin should manage to merge the schemas together if keys already exist.

I mean, if we have such an API: 
```JS
    server.post("/api", {
        schema: {
            description: 'post some data',
            tags: ['user'],
            summary: 'qwerty',

            response: {
                '202': {
                    properties: {
                        id: { type: 'number' }
                    }
                }
            }
        }
    }, (req: any, reply: any) => {
        reply.send({ id: 1, name: 'Foo', image: 'BIG IMAGE' })
    })
```

and  shared schema :

```JS
response: {
    202: {
           properties: {
                  name: { type: 'string' }
          }
    }
}
```

Should this even be supported? should the plugin manage to merge the properties? 
What do you think?

**Comment by rluvaton** [comment]
Thanks, we can work on it together! I think that it should merge for the following reason to be able to apply common schemas for example if I have multiple search routes and they all include page number and size query params but each one can contain different filters...

**Comment by iifawzi** [comment]
That's cool, go for it, you've already proposed the solution, and I will get into it with you when needed.

My thoughts are that this will require a bunch of checks if we're going to merge properties and schemas, like what if keys are present in both the shared schema and the route schema, and so on.

**Comment by Adibla** [comment]
Hi, about this topic I published a plugin that could address this request.
https://github.com/Adibla/fastify-shared-schema
Is it useful? It seems to me that the topic is the same. Thank you!

**Comment by Eomm** [comment]
> It seems to me that the topic is the same

I think so. Would you like to add it to the ecosystem page?

**Comment by Adibla** [comment]
Yes, thank you very much, can I send a MR for that?

**Comment by Adibla** [comment]
> > It seems to me that the topic is the same
> 
> I think so. Would you like to add it to the ecosystem page?

Thank you, I have opened a MR for it https://github.com/fastify/fastify/pull/4551
