### ISSUE TITLE
Performance: spread is faster than the Object. assign especially on small objects

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#4317]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue
Node v18.10.0

## Big object

```js
import Benckmark from 'benchmark';

const bigObj = {
    nullable: false,
    200: {
        properties: {},
        if: {
            type: 'object',
            properties: {
                error: { type: 'object' },
            },
            required: ['error'],
        },
        then: {
            type: 'object',
            properties: {
                error: {
                    type: 'object',
                    properties: {
                        id: {
                            type: 'string',
                        },
                        code: {
                            type: ['integer'],
                            minimum: 100,
                            maximum: 599,
                        },
                        message: { type: 'string' },
                        data: {},
                    },
                    required: ['code', 'message'],
                },
            },
            required: ['id', 'error'],
        },
        else: {
            type: 'object',
            properties: {
                id: {
                    type: 'string',
                },
                result: {},
            },
            required: ['id', 'result'],
        },
    },
    201: {
        type: 'object',

        additionalProperties: false,

        properties: {
            id: {
                type: 'string',
                format: 'uuid',
            },
            version: {
                type: 'string',
            },
            params: {},
        },

        required: ['id', 'version'],
    },
};

var suite = new Benckmark.Suite('Object shallow clone');
suite
    .add('Object.assign', function () {
        return Object.assign({}, bigObj);
    })
    .add('spread', function () {
        return { ...bigObj };
    });
```
Benchmark:
```js
Object.assign   x 672,910 ops/sec ±0.44% (90 runs sampled)
spread          x 658,559 ops/sec ±1.40% (89 runs sampled)

Fastest: [ 'Object.assign', 'spread' ]
```

## Small object
```js
import Benckmark from 'benchmark';

const smallObj = { a: 1, b: '2' };

var suite = new Benckmark.Suite('Object shallow clone');
suite
    .add('Object.assign', function () {
        return Object.assign({}, smallObj);
    })
    .add('spread', function () {
        return { ...smallObj };
    });
```
Benchmark:
```js
Object.assign   x 16,256,524 ops/sec ±0.32% (94 runs sampled)
spread          x 72,286,696 ops/sec ±0.47% (88 runs sampled)

Fastest: [ 'spread' ]
```

**Comment by Uzlopak** [comment]
So?

**Comment by budarin** [comment]
do you think it's useless? then I can close the issue

**Comment by budarin** [comment]
I understand you meant to write a PR, but unfortunately I don't have a stand where I could test and measure the difference in performance with guarantee - on my laptop, my services give floating performance during each testing - for this you need a dedicated machine on which performance tests would give reproducible results

**Comment by jsumners** [comment]
They are not equivalent -- http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals

**Comment by budarin** [comment]
I meant only this variant of `Object.assign({}, ...obj)`

**Comment by Eomm** [comment]
> I meant only this variant of Object.assign({}, obj)

That's fair to optimize if your tests show a benefit.

@RafaelGSS could be interested in it, he runs a repo to find these little performance differences across node.js versions

**Comment by budarin** [comment]
@Eomm
We also collect such optimizations on the project - we have a collection

I suggest the guys at Babel to write present performance.environment, but they don't show much desire (
https://github.com/babel/babel/issues/15002

We will have to write optimized code instead of the usual one when it hurts everywhere in our hands (

**Comment by budarin** [comment]
@RafaelGSS 

Number('10)    x 843,837,928 ops/sec ±1.53% (92 runs sampled)
parseInt('10') x 201,513,260 ops/sec ±0.65% (94 runs sampled)
'10'-0         x 857,157,978 ops/sec ±0.19% (94 runs sampled)



Number('10.1)      x 856,941,926 ops/sec ±0.18% (94 runs sampled)
parseFloat('10.1') x 19,568,197 ops/sec ±0.55% (94 runs sampled)
'10.1'-0.0         x 848,217,817 ops/sec ±1.02% (94 runs sampled)
