### ISSUE TITLE
Trying to move from express to fastify using h2c on cloudrun... still hang or crash

### ISSUE THREAD

**Issue by richtera** [fastify/fastify#4318]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Plugin version

2.0.2 (@fastify/express) with express@4.18.1

### Node.js version

v14.20.1 v16.17.1 and v18.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

WLS2 Ubuntu 22.04.1 LTS and google cloud cloudrun managed node:xx-slim and node:xx-alpine

### Description

I am still getting errors like this one
```javascript
_http_outgoing.js:354
  this.outputData.push({ data, encoding, callback });
                  ^

TypeError: Cannot read property 'push' of undefined
    at ServerResponse._writeRaw (_http_outgoing.js:354:19)
    at ServerResponse._send (_http_outgoing.js:327:15)
    at ServerResponse.end (_http_outgoing.js:849:10)
    at /run/node_modules/fastify/lib/error-handler.js:43:17
    at fallbackErrorHandler (/run/node_modules/fastify/lib/error-handler.js:128:3)
    at handleError (/run/node_modules/fastify/lib/error-handler.js:33:5)
    at onErrorHook (/run/node_modules/fastify/lib/reply.js:681:5)
    at _Reply.Reply.send (/run/node_modules/fastify/lib/reply.js:132:5)
    at runPreParsing (/run/node_modules/fastify/lib/route.js:493:11)
    at next (/run/node_modules/fastify/lib/hooks.js:168:7)
docker run failed
```
with an alpine docker I just get a hang instead.
I tried v14, v16 and v18 with alpine dockers just a hang with slim this error and the docker exits.

### Steps to Reproduce

All I did is use my express router with `@fastify/express` plugin using Fastify({ http2: true }) as the constructor.
I have not been able to upgrade past v14 because of spdy under express which is why I tested fastify, but I am still seeing the same hang in deployment with an alpine docker, when I switch to a slim docker, I get at least the above error message which could possibly help to narrow down the problem.

### Expected Behavior

Should work normally.
i.e. the listener should either return the result or manage any errors without crashing the container.

**Comment by richtera** [comment]
Basically what I need to find out is whether this is specifically a problem with `@fastify/epxress`/`express` or just generally `fastify` before rewriting all my middle tier code.

**Comment by Eomm** [comment]
> using Fastify({ http2: true }) as the constructor.

It could be the first issue [as written in the docs](https://github.com/fastify/fastify-express#fastifyexpress)

<img width="866" alt="image" src="https://user-images.githubusercontent.com/11404065/193639133-182e04c4-f671-4aa3-83b8-55860bca6b78.png">


> this is specifically a problem with @fastify/epxress/express

If removing the http2 config does not solve, I think the issue is that some middleware "does something" that is not supported by `@fastify/express`. The big thing is to spot which one.

>  just generally fastify

All my production applications say: no, it is not this case.

**Comment by richtera** [comment]
Everything works fine without http2 enabled. Ok but still rewriting the middlewares should be wirth it then?

**Comment by richtera** [comment]
@Eomm It makes sense. I was thinking of doing that as the second step, thinking I can prove fastly will work with node http2. Maybe I can mock up something smaller just to make sure it's all working.

**Comment by richtera** [comment]
@Eomm You were correct it was directly related to the express plugin. Without it I was able to get our app running with node 16 on cloudrun. Previously with anything >= 15 it would just hang due to spdy. Thank you!
