### ISSUE TITLE
Route onRequest hook use plugin issue cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by anhlevfx** [fastify/fastify#4320]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.6.0

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

Hello, I'm facing a weird issue when develop an authentication plugin to use global on any route, use typescript. I describe what I did below.

### Steps to Reproduce

1. Create authentication plugin
```
export const authentication = fp( async function (fastify, opts) {
    fastify.decorate('authentication', async function (request: FastifyRequest, reply: FastifyReply) {
        try {
            await request.jwtVerify()
        } catch (err) {
            reply.send(err)
        }
    })
})
```
2. Create type.d.ts to typescript know the decorator property.
```
declare module 'fastify' {
    export interface FastifyInstance{
        authentication: onRequestAsyncHookHandler;
    }
}
```
3. In index.ts root of project, I registered plugin
```
const fastify = Fastify({
    logger: true
})
fastify.register(authentication)
```

4. Add onRequest option for routes need authentication (route declared in index.ts)
```
fastify.post<{ Body: string }>('/api/v1/xxx', {
    onRequest: [
        fastify.authentication
    ]
}, (request, reply) => {
})
```
But, when make a request from postman, I got an error
Cannot read properties of undefined (reading 'length'), through from
```
if (err || i === functions.length) {
      cb(err, request, reply)
      return
    }
```
in node_modules/fastify/lib/route.js:512

If I move codes in step 4 to  inside plugin, everything works fine.

**Comment by Eomm** [comment]
Try to avoid mixing async/await and callback style:

```
export const authentication = fp( async function (fastify, opts) {
    fastify.decorate('authentication', async function (request: FastifyRequest, reply: FastifyReply) {
        try {
            await request.jwtVerify()
        } catch (err) {
            // NO: reply.send(err)
            return reply.send(err) // return is important
            // OR:
            throw new Error('ops')
        }
    })
})
```

**Comment by anhlevfx** [comment]
Thanks @Eomm I tried this but the error still happen.

**Comment by Eomm** [comment]
New test, add the `await` while registering the plugin:

```
const fastify = Fastify({
    logger: true
})
await fastify.register(authentication)
```

**Comment by anhlevfx** [comment]
@Eomm add await before register worked. Do you have any idea why we need to do that?
Thank you!.

**Comment by mcollina** [comment]
I think we should fix this and throw a good error.

**Comment by climba03003** [comment]
The problem related to the user do not know the execution order.
From the above example, people plan to use the decoration inside plugin immediately which is never be possible.

```js
// 1. sync operation
const fastify = Fastify()

// 3. async operation - process.nextTick
fastify.register(fp(async function(instance) {
  instance.decorate('authentication', () => {})
}))

// 2. sync operation
fastify.post('/', {
  // when you use it directly, it is undefined
  onRequest: [ fastify.authenticate ]
}, () => {})
```

**Comment by mcollina** [comment]
I think `fastify.<method>` should validate the hooks functions during startup.

**Comment by anhlevfx** [comment]
@mcollina Great! It will be easier to debug.

**Comment by Eomm** [comment]
> I think we should fix this and throw a good error.

First step: we should not accept an `undefined` hook

**Comment by jhhom** [comment]
Hi, I'm interested in taking on this "good first issue", shall I opened a pull request?

My idea is to:
1. throw an error from `fastify.post` and other route registration functions (i.e `fastify.get`, `fastify.route`, ...) if the hook functions passed in the options are `undefined`
2. throw an error from `fastify.addHook` if the function passed is undefined

This can be done from the [`prepareRoute`](https://github.com/fastify/fastify/blob/main/lib/route.js#L117) and the [`route` function](https://github.com/fastify/fastify/blob/main/lib/route.js#L156).

**Comment by Eomm** [comment]
> I think these checks and error can be thrown in the [prepareRoute](https://github.com/fastify/fastify/blob/main/lib/route.js#L117) and the [route function](https://github.com/fastify/fastify/blob/main/lib/route.js#L156).

The best position is after the `onRoute` hook execution because that function could add hooks to the route itself.

> throw an error from fastify.addHook if the function passed is undefined

I think this is already covered, but I would split the steps into separate PRs

**Comment by jhhom** [comment]
@cesarvspr Yes I'm working on it, will open a PR soon.
