### ISSUE TITLE
Vercel serverless code does not work. Fastify can't be initialized properly.

### ISSUE THREAD

**Issue by xxRockOnxx** [fastify/fastify#4328]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Node.js version

16.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

unknown

### Description

Following the docs: https://www.fastify.io/docs/latest/Guides/Serverless/

```javascript
const app = fastify()

export default async (req, res) => {
  // register a route or plugin
  // ...
  await app.ready()
  app.server.emit(req, res);
}
```

I'm not sure if it is Vercel specific but every other request fails because of any of the following depending on how you test it:

- Cannot add route when fastify instance is already started!
- Root plugin has already booted serverless

I thought maybe Vercel is preserving state or keep the server running for certain duration so I tried checking by doing:

```javascript
const app = fastify()

export default async (req, res) => {
  console.log(app.server.listening)
  // ...
}
```

But it is being logged as `false` so I think the server is being shutdown.

Moving the initialization of fastify inside the handler however works.

Was there a breaking change on Fastify end? I could probably submit a PR that moves fastify inside the handler instead.

Or is this an issue on Vercel side?

### Steps to Reproduce

- Copy the Vercel code from Serverless section of the docs
- Deploy to Vercel
- Make a request twice

**Comment by climba03003** [comment]
Inside the document, the `server` is never be `started`.
I assume the current behavior is correct.

You probably need to move the `registration of plugin` outside the serverless function. 
So, it wouldn't register in every request.

**Comment by xxRockOnxx** [comment]
> Inside the document, the server is never be started.
Sorry I don't follow. If it never got started, that means we are running new code? Unless for some reason the state is maintained but the server is just not started?

> You probably need to move the registration of plugin outside the serverless function.
I'm trying to register plugin/routes depending on URL instead of registering all routes so that I can minimize what's being loaded. Is this not good to do it this way?

**Comment by climba03003** [comment]
> If it never got started, that means we are running new code?
No. It is not `started` means the `http` server never listen to a port. And it is correct that `app.server.listening` will always be `false`.

> Is this not good to do it this way?
It is never be possible to dynamic add route in `fastify`. You need to create a whole new instance each time.

**Comment by climba03003** [comment]
I am closing this issue as dynamic add route is not going to be happen.

Once called `await fastify.ready`, `route`, `hooks` can not be changed. You should do it outside the `serverless` function as the document stated.

**Comment by xxRockOnxx** [comment]
> No. It is not started means the http server never listen to a port. And it is correct that app.server.listening will always be false.

Got that.

> Once called await fastify.ready, route, hooks can not be changed.

So that does mean Vercel is saving state of Fastify instead of making new instance each request?

I thought serverless meant no long-running server and so has to start from 0 each time.

> It is never be possible to dynamic add route in fastify. You need to create a whole new instance each time.

I see. That's why initializing fastify inside the handler in my example made it work.

**Comment by climba03003** [comment]
> So that does mean Vercel is saving state of Fastify instead of making new instance each request?

code outside `serverless` function will be cached for a few request determine by how frequent the requests are.
code inside `serverless` function will be executed for each request.

From what it means from your code, the `fastify` instance maybe the same for consecutive request.
You may be `route`, `hooks` for a instance that called `fastify.ready`
