### ISSUE TITLE
Add midnight-smoker to do some basic integration testing

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#4333]
Check out https://www.npmjs.com/package/midnight-smoker.

The goal is to catch configuration and dependency errors, e.g. a needed dependency wrongly classified as a devDepedency.

**Comment by jsumners** [comment]
That's what https://github.com/fastify/fastify/blob/acba25acc3e97e3598daf79537a39a5272dba7b8/.github/workflows/integration.yml does.
