### ISSUE TITLE
Exceeding Maximum Header Size Causes Connection Reset

### ISSUE THREAD

**Issue by james-gardner** [fastify/fastify#4335]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.8.1

### Node.js version

16.13.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Hi,

This is the first time I've ever logged an issue here so apologies in advance if this isn't helpful. I've looked around the tickets to see if I could find anything similar but no luck so far. 

Here's an outline of what I'm trying:

When I provide headers that exceed the size limit specified by  `max-http-header-size` I'm introduced with an error 400 which doesn't pass through my error handler:

Here's an example of how I'm defining my error handler, just with a log as an example:

``` 
  fastify.setErrorHandler((err) => {
    // Was hoping to see the error surface here.
    console.log(err);
  });
```

Not such a big deal since I get a nice error message anyway:

```
  {
    "error": "Bad Request",
    "message": "Client Error",
    "statusCode": 400
  }
```

However, the error doesn't make it to my logger. 

Subsequent calls give me a 'connection reset' error and the application itself continues to run ignoring any further requests.
 
Am I missing something fundamental? I've tried setting the max-http-header-size to something tiny using NODE_OPTIONS and get the same behaviour. This does appear to be intermittent when using smaller string values but I can get this to happen every time if I set `user-agent` to a really long string value (2000+ chars).

Any help is appreciated!
 
  

### Steps to Reproduce

Set max header size to something small using NODE_OPTIONS and start your server:

`NODE_OPTIONS=--max-http-header-size=300 && npm run dev`

Hit an endpoint with a header that exceeds 300 (should be easy!).

Error 400.

Hit it again with the same headers:

Connection Reset

### Expected Behavior

It should consistently return error 400 each time the headers go above the max size.

**Comment by RafaelGSS** [comment]
Could you share a reproducible code?

**Comment by climba03003** [comment]
When `max http header` reached, it will fall into `client error`. It cannot be run by a normal route cycle.
You should pass `clientErrorHandler` for handling those error.

**Comment by climba03003** [comment]
For `Postman` it probably throwing `431` because of it's underlying `node`.
I would believe `cURL` result more than `Postman`.
