### ISSUE TITLE
Missing content-type header when replying with stream data

### ISSUE THREAD

**Issue by D10f** [fastify/fastify#4336]
Hello, I'm trying to send a stream back as a response using the code below. [According to the documentation](https://www.fastify.io/docs/latest/Reference/Reply/#streams), the header 'content-type' should be handled automatically if not explicitly set. However I'm getting an error in one of my test cases regarding this as the header is missing.

The obvious solution is to set it manually, which I've done and everything works perfectly, but I just wanted to ask here in case this needs to be updated?

This code snippet is the simplest test case I wrote while I was trying to figure out what was wrong. Following the example in the documentation however leads to the same issue.

```js
fastify.addContentTypeParser(
  'application/octet-stream',
  (req, body, done) => done(null, body)
);

fastify
  .withTypeProvider<TypeBoxTypeProvider>()
  .post(
    '/upload/:id/:chunkNumber',
    { schema: createChunkSchema },
    (request, reply) => {
      // reply.header('Content-Type', 'application/octet-stream');
      reply.send(request.body);
    }
  );
```
And my rather simplistic test case:
```ts
test('should receive a buffer', async () => {
  const res = await supertest(server.server)
    .post(`/upload/123/123`)
    .set('Content-Type', 'application/octet-stream')
    .send(Buffer.from([1, 2, 3, 4, 5, 6]));

  expect(res.headers).toHaveProperty('content-type');
  expect(res.headers['content-type']).toEqual('application/octet-stream')
  expect(res.body).toBeInstanceOf(Buffer);
});
```
The resonse headers do not have the property `content-type` set at all.
The response body I receive from this is an empty object `{}`.

* [Reproducible example](https://github.com/D10f/fastify-reproduce-test/tree/master)
* *node version*: 16.17.1
* *fastify version*: 4.7.0
* *vitest version*: 0.23.4
* *supertest*: 6.3.0
* *os*: Linux pop-os 5.19.0-76051900-generic

**Comment by metcoder95** [comment]
@D10f would you like to send the PR with the change? 🙂

**Comment by D10f** [comment]
I've created the PR, hopefully everything is correct (please bear with me on this...) [#4337 ](https://github.com/fastify/fastify/pull/4337)

I wasn't really sure how to phrase it so, following the guidelines, I tried to be as brief and concise as possible about it.

**Comment by D10f** [comment]
Hi, sorry I've been out this weekend and couldn't get access to my computer. But it looks like everything is sorted out, thank you very much for the help!
