### ISSUE TITLE
Instances with type-providers are not assignable to `FastifyInstance`

### ISSUE THREAD

**Issue by driimus** [fastify/fastify#4342]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Node.js version

18.1.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.5 LTS

### Description

Fastify instances with an enabled type-provider are not subtypes of the base `FastifyInstance` interface.

## Example

A fastify server with type-providers enabled will not be usable as input for the `@fastify/aws-lambda` plugin, which expects a `FastifyInstance` parameter.

```ts
export default function awsLambdaFastify<TEvent, TResult = LambdaResponse>(
  app: FastifyInstance,
  options?: LambdaFastifyOptions
): PromiseHandler<TEvent, TResult>;
```

## Cause
A more detailed explanation can be found in the [reproduction repo](https://github.com/driimus/fastify-instance-assignability#cause). 

In short, the assignability issue stems from certain methods of `FastifyInstance` being contravariant on `TypeProvider`. Because of that, the compiler has to flip the assignability check's direction, which boils down to the following outcome:

```diff
Types of property 'handler' are incompatible.
  Type 'RouteHandlerMethod<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., FastifyBaseLogger>' is not assignable to type 'RouteHandlerMethod<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, any, any, any, FastifyTypeProviderDefault, FastifyBaseLogger>'.
    Types of parameters 'request' and 'request' are incompatible.
      Type 'FastifyRequest<any, RawServerDefault, IncomingMessage, any, FastifyTypeProviderDefault, any, FastifyBaseLogger, ResolveFastifyRequestType<...>>' is not assignable to type 'FastifyRequest<any, Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, any, TypeBoxTypeProvider, any, FastifyBaseLogger, ResolveFastifyRequestType<...>>'.
        Type 'ResolveFastifyRequestType<FastifyTypeProviderDefault, any, any>' is not assignable to type 'ResolveFastifyRequestType<TypeBoxTypeProvider, any, any>'.
+          Type 'FastifyTypeProviderDefault' is not assignable to type 'TypeBoxTypeProvider'.
```

### Steps to Reproduce

1. Check out the [Minimal reproduction repo](https://github.com/driimus/fastify-instance-assignability), which uses the `"@fastify/aws-lambda": "^3.1.3"` plugin.
1. Install dependencies
1. Run `pnpm tsc --noEmit` to check for type errors
1. Notice the assignability error 

From the CI run: https://github.com/driimus/fastify-instance-assignability/actions/runs/3259362782/jobs/5352129645#step:6:11
```
Error: src/index.ts([27](https://github.com/driimus/fastify-instance-assignability/actions/runs/3259362782/jobs/5352129645#step:6:28),41): error TS2769: No overload matches this call.
  Overload 1 of 2, '(app: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, options?: LambdaFastifyOptions | undefined): PromiseHandler<...>', gave the following error.
    Argument of type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider>' is not assignable to parameter of type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.
      The types returned by 'after()' are incompatible between these types.
        Type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>'.
          Type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.
            Types of property 'register' are incompatible.
              Type 'FastifyRegister<FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider> & PromiseLike<...>, RawServerDefault, FastifyTypeProvider>' is not assignable to type 'FastifyRegister<FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>, RawServerDefault, FastifyTypeProvider>'.
                Type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>'.
                  Type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.
                    The types of 'addSchema(...).addHook' are incompatible between these types.
                      Type '{ <RouteGeneric extends import("/home/runner/work/fastify-instance-assignability/fastify-instance-assignability/node_modules/.pnpm/fastify@4.8.1/node_modules/fastify/types/route").RouteGenericInterface = import("/home/runner/work/fastify-instance-assignability/fastify-instance-assignability/node_modules/.pnpm/fastif...' is not assignable to type '{ <RouteGeneric extends import("/home/runner/work/fastify-instance-assignability/fastify-instance-assignability/node_modules/.pnpm/fastify@4.8.1/node_modules/fastify/types/route").RouteGenericInterface = import("/home/runner/work/fastify-instance-assignability/fastify-instance-assignability/node_modules/.pnpm/fastif...'. Two different types with this name exist, but they are unrelated.
                        Types of parameters 'hook' and 'hook' are incompatible.
                          Types of parameters 'opts' and 'opts' are incompatible.
                            Type 'RouteOptions<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., FastifyBaseLogger> & { ...; }' is not assignable to type 'RouteOptions<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, any, any, any, FastifyTypeProviderDefault, FastifyBaseLogger> & { ...; }'.
                              Type 'RouteOptions<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., FastifyBaseLogger> & { ...; }' is not assignable to type 'RouteOptions<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, any, any, any, FastifyTypeProviderDefault, FastifyBaseLogger>'.
                                Types of property 'handler' are incompatible.
                                  Type 'RouteHandlerMethod<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., FastifyBaseLogger>' is not assignable to type 'RouteHandlerMethod<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, any, any, any, FastifyTypeProviderDefault, FastifyBaseLogger>'.
                                    Types of parameters 'request' and 'request' are incompatible.
                                      Type 'FastifyRequest<any, RawServerDefault, IncomingMessage, any, FastifyTypeProviderDefault, any, FastifyBaseLogger, ResolveFastifyRequestType<...>>' is not assignable to type 'FastifyRequest<any, Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, any, TypeBoxTypeProvider, any, FastifyBaseLogger, ResolveFastifyRequestType<...>>'.
                                        Type 'ResolveFastifyRequestType<FastifyTypeProviderDefault, any, any>' is not assignable to type 'ResolveFastifyRequestType<TypeBoxTypeProvider, any, any>'.
                                          Type 'FastifyTypeProviderDefault' is not assignable to type 'TypeBoxTypeProvider'.
  Overload 2 of 2, '(app: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, options?: LambdaFastifyOptions | undefined): CallbackHandler<...>', gave the following error.
    Argument of type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, TypeBoxTypeProvider>' is not assignable to parameter of type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.
```

### Expected Behavior

I would expect specialised versions of the `FastifyInstance` interface, such as the ones using a custom type provider, to be assignable to `FastifyInstance`.

I am aware of some available workarounds:
1. Extracting the type-provider enabled instance into a separate reference (similar to the [scoped type-provider](https://www.fastify.io/docs/latest/Reference/Type-Providers/#scoped-type-provider) docs suggestion).
1. Extending affected function signatures to include generic parameters which are propagated to their input argument of type `FastifyInstance`.

However, both of them seem inferior to ensuring that subtypes of `FastifyInstance` are assignable to the base interface. 
I haven't look at the way type providers are being used in details, but it seems possible: https://github.com/fastify/fastify/compare/77b7582...driimus:fastify:test/type-provider-contravariance

**Comment by mcollina** [comment]
cc @sinclairzx81 @fastify/typescript

**Comment by sinclairzx81** [comment]
@driimus @mcollina Hi. This is a good find!

I think it would be ok to update the existing providers to have them infer as `unknown` (instead of `never`) if it means contravariant assignment becomes possible (which would be super desirable). I wouldn't anticipate there being any issues doing this. Just a quick script below to test with, [TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQMoGMAWBTEBDAGjlRjxmHTgF84AzKCEOAcgAEBnYAO3QBs9gUAPQwAnmGwAjCAA9mAWABQoSLDgAxPO3K1RRJJu3BdASS7a8PbEUM7RycdgAKDAG7AAJtijU6DJsy0WnYKikpCQnAAtDGxcfEJiUnJieGRLhDuXlBp0Sn5BYXxSkrYMqrw3DDeQejYKI4AQrIZWd5wZdVcHuwawcb2jq2e7QhKcHAQAK4wYDMAXHAwmMDsANrM3HMwzAC6HTJdPSgYOPhwAPzEpOToADzLqxtbM3sAfHCLU1wA1lwQAHcuEoaBMweCIZCodCYbDYRE4AA9OBYSwAc3q3z+gK4SwgcC42Fc7Vo0A6UAYOTCigRRTp9NSNMiyGw2lyDI5DJKilo33Q5AguOq2gAFNwLFZFrYBmYJXUAJSIKjc9CC7RwcWkKxwAC8fSMuhF8oAdADgMsHBJhtk7pbsM0ZNbvG8jdzhTAxeYtQqgA)

```typescript
import { TSchema, Static } from '@sinclair/typebox'
import Fastify, { FastifyInstance, FastifyTypeProvider } from 'fastify'

// ----------------------------------------------------
// Provider
// ----------------------------------------------------

export interface TypeBoxProvider extends FastifyTypeProvider {
  output: this['input'] extends TSchema ? Static<this['input']> : unknown
}                                                                 // ^ change unknown to never for error

// ----------------------------------------------------
// Test
// ----------------------------------------------------

function test(instance: FastifyInstance) {}

const instance = Fastify().withTypeProvider<TypeBoxProvider>()

test(instance) // ok !
```

Would just need to submit a PR to update the relevant lines in each type provider package accordingly (and maybe include some documentation for other providers to infer `unknown` on unresolvable types)

#### TypeBoxTypeProvider

https://github.com/fastify/fastify-type-provider-typebox/blob/main/index.ts#L52

#### JsonSchemaToTsTypeProvider

https://github.com/fastify/fastify-type-provider-json-schema-to-ts/blob/main/index.ts#L13

@driimus Did you want to take a look at submitting these PR's?

**Comment by driimus** [comment]
@sinclairzx81 happy to prepare PRs for those soon. 

I presume the convention is to update type-provider packages, then manually sync changes to type tests in this repo. Is that right? 
https://github.com/fastify/fastify/compare/77b7582...driimus:fastify:test/type-provider-contravariance

**Comment by sinclairzx81** [comment]
@driimus Hey, awesome :)

Not too sure the best convention for updating across multiple Fastify packages (it's probably better to get some inputs from @fastify/typescript contributors on matters of logistics; noting I'm just an external contributor this side). But I think given the nature of the update, the important thing will likely be to ensure all implementations are consistent across projects, so the order in which they're applied might not matter so much in this case....

However, in saying this... it might be good to submit https://github.com/fastify/fastify/compare/77b7582...driimus:fastify:test/type-provider-contravariance as a PR first as this would be a good place to document the rationale behind the change and provide something to link back to on the Type Provider PR's.

Hope this helps! 
S
