### ISSUE TITLE
setBindings is no longer available on the typing of FastifyBaseLogger

### ISSUE THREAD

**Issue by silenceisgolden** [fastify/fastify#4344]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.3.0

### Stopped working in version

4.8.1

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### 💥 Regression Report

FastifyLoggerInstance had a method called setBindings that I am using currently to preserve context across multiple log method calls. It looks like FastifyLoggerInstance was replaced with FastifyBaseLogger in https://github.com/fastify/fastify/pull/4224, but the typings (at least) show the method as missing when my typecheck runs in my CI checks:

```
// tsc --noEmit

> tsc --noEmit

src/_framework/context-from-params.ts:41:14 - error TS2339: Property 'setBindings' does not exist on type 'FastifyBaseLogger'.

41    state.log.setBindings(metadata);
                ~~~~~~~~~~~

src/_framework/context-from-request.ts:31:[16](<redacted>/actions/runs/3227392130/jobs/5282140045#step:5:17) - error TS2339: Property 'setBindings' does not exist on type 'FastifyBaseLogger'.

31    request.log.setBindings(metadata);
                  ~~~~~~~~~~~


Found 2 errors in 2 files.

```

### Steps to Reproduce

Sorry that I cannot link to the project, but I think if you have a default simple fastify project that calls `request.log.setBindings()` in 4.3 and upgrade it to 4.8, the type checking should fail with a similar error as above.

### Expected Behavior

I would expect that this method would be preserved in source code and types unless there was a major version change.

**Comment by silenceisgolden** [comment]
👏🏻 to @BlackHole1, @climba03003 and @mcollina. Thanks for addressing this so quickly.

**Comment by tzafrir-benami-sage** [comment]
@mcollina Will this approach works? `FastifyBaseLogger` is a type alias and not an interface
> 
> ```ts
> declare module "fastify" {
>     interface FastifyBaseLogger {
>         setBindings(bindings: import("pino").Bindings): void;
>     }
> }
> ```

I guess that my real question is why is `FastifyBaseLogger` not an interface so users can take advantage of declaration merging and extract them

**Comment by tzafrirben** [comment]
@mcollina Will this approach works? `FastifyBaseLogger` is a type alias and not an interface
> 
> ```ts
> declare module "fastify" {
>     interface FastifyBaseLogger {
>         setBindings(bindings: import("pino").Bindings): void;
>     }
> }
> ```

I guess that my real question is why is `FastifyBaseLogger` not an interface so users can take advantage of declaration merging and extract them

**Comment by mcollina** [comment]
I don't know, would you like to try a fix in a PR?

**Comment by tzafrir-benami-sage** [comment]
Agreed - I will try to create a commit according to contribution guide lines.
