### ISSUE TITLE
FastifyRequest Query return null prototype

### ISSUE THREAD

**Issue by Eduwardo** [fastify/fastify#4353]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Node.js version

16.x.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

FastifyRequest return a correct object with expected keys/values but with a null prototype:

`Empty <[Object: null prototype] {}> query `

Which is a problem for example if you want to assign the exact query object to mongoose filters where the prototype object must not be undefined or null

### Steps to Reproduce

      // Require the framework and instantiate it
      const fastify = require('fastify')({ logger: true })
      
      // Declare a route
      fastify.get('/', async ({query, body, params, headers}, reply) => {
        console.log('query', query);
        return query
      })
      
      // Run the server!
      const start = async () => {
        try {
          await fastify.listen({ port: 3000 })
        } catch (err) {
          fastify.log.error(err)
          process.exit(1)
        }
      }
      start()

REQUEST: 

GET - http://localhost:3000?key=value

LOG: 

query Empty <[Object: null prototype] {}> { key: 'value' }

### Expected Behavior

it should behave like params object of FastifyRequest

**Comment by Eomm** [comment]
> Which is a problem for example if you want to assign the exact query object to mongoose filters where the prototype object must not be undefined or null

Is it changed overtime?
I checked #4252 and the behaviour is always the same.

Note that you can get the prototype with:

```
const o = Object.create(null)
console.log(o)
Object.setPrototypeOf(o, {}.__proto__)
console.log(o)
```

> it should behave like params object of FastifyRequest

I was wondering if we should evict the prototype from all the object that manages user input data. It could be a security strengthening

**Comment by mcollina** [comment]
As a generic note, it's better to have these objects be null-prototype based to protect against possible prototype pollution attacks.

> it should behave like params object of FastifyRequest

We should likely apply a null prototype there too.


---

@anonrig might this be an unwanted breakage with fast-querystring?

**Comment by climba03003** [comment]
> might this be an unwanted breakage with fast-querystring?

It should be by design using `null` prototype.

**Comment by anonrig** [comment]
This is a desired/expected outcome. Previous implementation was also using null prototype base, as well as fast-querystring. 

Null prototypes are important for prototype pollution attacks.
