### ISSUE TITLE
Make request.params null prototype based to protect against prototype pollution attacks

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#4357]
There are no known attacks using params & prototype pollution. However, it seems a good practice to use a null prototype there. Wdyt?

**Comment by jsumners** [comment]
I think `Object.create(null)` objects are surprising and cause unexpected errors.

**Comment by Eomm** [comment]
I think we should plan this for v5!

@fastify/core do you agree?

**Comment by Uzlopak** [comment]
I think this is a good idea. Where are the params Object get build?

**Comment by Eomm** [comment]
I would start from here:
https://github.com/fastify/fastify/blob/8974714cddce705c190f344de383618f9d8cdde1/lib/fourOhFour.js#L64

**Comment by Uzlopak** [comment]
The place to do change this is in find-my-way and not in fastify.

Provided a PR
https://github.com/delvedor/find-my-way/pull/333

**Comment by mcollina** [comment]
This is done and shipped as part of find-my-way v9.
