### ISSUE TITLE
Support `application/x-www-form-urlencoded` content type in core

### ISSUE THREAD

**Issue by mmarti** [fastify/fastify#4369]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

From the [ContentTypeParser reference docs](https://www.fastify.io/docs/latest/Reference/ContentTypeParser/):

>Natively, Fastify only supports `'application/json'` and `'text/plain'` content types.

My proposal is to add support for one additional content type: `'application/x-www-form-urlencoded'` using node's built-in `querystring` module's `parse` function.

### Motivation

There are a few reasons for this proposal.

1. Fastify already supports parsing query strings using node's built-in `querystring` module's `parse` function.  This would seem to be a natural fit to have the same behavior for basic form bodies.  Anyone who needs more complex parsing could still use a plugin or swap it out for something like the userland `qs` module.
1. Supporting basic form bodies in core would round out Fastify's support for arguably the top three most common content types: JSON, plain text, and basic form bodies.

I love Fastify's minimalist approach and understand why most things are left to userland plugins, but this is one missing feature that has always struck me as a pretty natural fit in Fastify core.  Apologies in advance if this discussion has already taken place; I tried searching issues and PRs but didn't see anything.  If the team is open to consider adding this to core, I can work on getting a draft PR.

### Example

The current userland logic:

```mjs
import { parse } from 'node:querystring';

fastify.addContentTypeParser(
  'application/x-www-form-urlencoded',
  { parseAs: 'string' },
  async (req, body) => parse(body),
);
```

It'd be awesome to not need to copy/paste this across all my projects 😆

**Comment by mcollina** [comment]
Should we add https://github.com/fastify/fastify-formbody/blob/master/formbody.js as part of core? cc @delvedor @jsumners

**Comment by climba03003** [comment]
I am not really convince to add this code.
From my use-case, I really didn't use `application/x-www-form-urlencoded` and if it added in core. I need to do the reverse way to remove the support of `application/x-www-form-urlencoded`.

Another issue is maintenance.
`QueryString` has no standard on `object` and `array`. There are way many difference standard or common practice outside the world. I can only see bunch of request of continue maintaining this part of feature.

**Comment by climba03003** [comment]
I believe most of the developer or company will eventually comes up with a set of default plugin. Which means from each start of the project, they will copy and paste the some set of plugin.

I suggest you to create a dedicated plugin with contain all those `plugin` and you only need to registered once.
For example, I made [one](https://github.com/kaka-repo/fastify-packed) for my own usage.

**Comment by delvedor** [comment]
Is there any data on how formbody is used in the wild?
One of the reasons we didn't add it, is that normally API servers don't use it unless you are building a pure frontend API (and even in that case, it is not guaranteed that you will need it).

Given how easy is to add it via a plugin, I don't see a strong reason to add it in core directly.

**Comment by climba03003** [comment]
`querystring` in `body` expected to be fairly more complex usage compare to `query`. Once it is added, people always expect to work out-of-the-box (e.g. Even with `query` itself, I can see some issue on the `validation` with `ajv`). 

Since there is no `standard`, I can only see maintenance burden.

**Comment by mcollina** [comment]
Unless somebody else from the maintainers feel strong about this one, I think we can leave formbody where it is. Closing for now, I'm happy to reconsider if someone else of the team feels otherwise.

**Comment by jsumners** [comment]
I agree. I do not see a need to support this out of the box. Fastify is designed for writing API services first. We have `text/plain` because people send JSON with that content type. 

As said before, it is a good idea to establish a set of preferred plugins and bootstrap projects with a template.
