### ISSUE TITLE
Close method is not executing Callback

### ISSUE THREAD

**Issue by wandersonwhcr** [fastify/fastify#4370]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Node.js version

16.18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian 11.5 Docker 20.10.20 Node Image 16.18

### Description

If I initialize Fastify and execute one request, `close` method will not call _callback_ function.

Basically, I am executing Fastify with Docker. When I receive `SIGTERM` or `SIGINT` signals, I want to close connections gracefully, but `fastify.close` _callback_ is not called and process receives a timeout from Docker.

### Steps to Reproduce

Create a file `index.js` with this content:

```js
const fastify = require('fastify')({
  logger: true,
});

fastify.listen({ host: '0.0.0.0', port: "3000" })
  .catch((error) => {
    fastify.log.fatal(error);
    process.exit(255);
  });

process.on('SIGINT', handleSignal);
process.on('SIGTERM', handleSignal);

function handleSignal(signal) {
  fastify.log.info(`Signal Received: ${signal}`);
  fastify.close()
    .then(() => {
      fastify.log.info('Stopped');
      process.exit(0);
    })
    .catch((error) => {
      fastify.log.fatal(error);
      process.exit(254);
    });
}
```

Execute it with `node index.js`.

Make one request to `http://localhost:3000`.

Send `SIGTERM` or `SIGINT` to the process.

### Expected Behavior

Close _callback_ must be called after `Fastify` close ended.

**Comment by climba03003** [comment]
I cannot reproduce your issue. The `.then` method is called without any problem.
![image](https://user-images.githubusercontent.com/23028015/197525244-76e5b17b-0f35-42ac-864e-a98c04504424.png)

**Comment by wandersonwhcr** [comment]
TY @climba03003 , I will check again what is happening here.

**Comment by wandersonwhcr** [comment]
If someone is facing this problem, please upgrade Node.js version.

I was using `node:16.18-alpine` docker image and `http` server was not calling `done` callback at this line:

https://github.com/fastify/fastify/blob/675b00d6ca7a7eeaad073e6469c70b50fcd532eb/fastify.js#L409

I upgraded to the current LTS version `node:18.12-alpine` and it works like a charm.
