### ISSUE TITLE
Request bodyLimit

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4375]
Right now, you can set the `bodyLimit` in two ways:

```
const app = Fastify({ bodyLimit: serverLimit })

app.post('/route-limit', {
  bodyLimit: routeLimit,
  handler (req) { return req.rawBody }
})
```

A custom `ContentTypeParser` or a `preParsing` hook function:

- can access the `serverLimit` via `app.initialConfig.bodyLimit`
- can't access the `routeLimit` unless a private API `request.context._parserOptions.limit`

I think we should add a getter `request.routeBodyLimit` that returns the custom `routeLimit || serverLimit`

WDYT?

Ref https://github.com/Eomm/fastify-raw-body/issues/35

**Comment by mcollina** [comment]
Sure thing!

**Comment by climba03003** [comment]
Shouldn't the `bodyLimit` be the part of `argument` for `addContentTypeParser`?
It is essential the provider should handle the `bodyLimit`.

**Comment by climba03003** [comment]
After some investigation, the issue in `fastify-raw-body` shouldn't be an issue.

You are using `parseAs` option which means that `fastify` will check the `bodyLimit` for you.
The error should be throw to the client, or something is wrong couple with `raw-body`.
For example, `fastify` terminate the `request` but `raw-body` didn't know it.

**Comment by Eomm** [comment]
> Shouldn't the bodyLimit be the part of argument for addContentTypeParser?

No, as it may change per single route, meanwhile the parser function is a single one.

> You are using parseAs option which means that fastify will check the bodyLimit for you.

No, the contentTypeParser is added in some cases.

> Parser config - Parser Level

I think this should not exist as it would be confusing for a user.
A developer that implements a `contentTypeParser` or a `preParsing` hook (latter my case) should be able to access the `bodyLimit` the user sets in the fastify "native" API - the parses may add a 3rd option to set a custom limit, but it would be a parser's custom feature

**Comment by climba03003** [comment]
> No, as it may change per single route, meanwhile the parser function is a single one.

I means we (fastify) already know which `bodyLimit` should be used. Why don't we pass it to the `custom parser`?
`function parser(reply, payload, options, done) { payload.bodyLimit }` which is much more flexible.

> should be able to access *something* the user sets in the fastify "native" API

It always the battle and we can provide a single object for all the route option. Certainly not adding it one by one.

```js
function WrapProxy(obj) {
  return new Proxy(obj, {
    get(target, prop) {
      consst value = target[prop]
      if(typeof value === 'object' && value !== null) {
        return WrapProxy(value)
      }
      return value
    },
    set() {
      // once it comes to `request` context, route option should not be mutate
      return true
    }
  })
}
```

**Comment by jsumners** [comment]
> Right now, you can set the `bodyLimit` in two ways:
> 
> ```
> const app = Fastify({ bodyLimit: serverLimit })
> 
> app.post('/route-limit', {
>   bodyLimit: routeLimit,
>   handler (req) { return req.rawBody }
> })
> ```
> 
> A custom `ContentTypeParser` or a `preParsing` hook function:
> 
> * can access the `serverLimit` via `app.initialConfig.bodyLimit`
> * can't access the `routeLimit` unless a private API `request.context._parserOptions.limit`
> 
> I think we should add a getter `request.routeBodyLimit` that returns the custom `routeLimit || serverLimit`
> 
> WDYT?
> 
> Ref [Eomm/fastify-raw-body#35](https://github.com/Eomm/fastify-raw-body/issues/35)

Ship it.
![giphy](https://user-images.githubusercontent.com/321201/83882820-a3582680-a710-11ea-93ee-0f63c7b70a7e.gif)

**Comment by Eomm** [comment]
> It always the battle and we can provide a single object for all the route option. Certainly not adding it one by one.

Yeah, I agree on this.

Right now we were listing them all one by one.

Are you suggesting something like: `request.routeConfig.bodyLimit`?
It can be the first step before a refactor

**Comment by climba03003** [comment]
> Are you suggesting something like: request.routeConfig.bodyLimit?

`routeConfig` is mapped to `fastify.get('/', { config: {} }, () => {})`

I means `routeOption` which is `ReadOnly` and should contain all the property inside the option.
Maybe we can remove part of them like `config`, `hooks`, etc.

**Comment by Eomm** [comment]
Great! I like your proposal!
I will work on it in the following weeks if some new contributor doesn't beat me!

**Comment by debadutta98** [comment]
Hi, I am interested to take up this issue but I need more clarity on the issue's description 

- what are `serverLimit` and `routeLimit` here? what is the type of it?
- is there any different meaning of defining `bodylimit` in two different way

Thank you!

**Comment by climba03003** [comment]
> Hi, I am interested to take up this issue but I need more clarity on the issue's description

The original issue is about `bodyLimit` only, but I want to take a step further.
The solution is to include all the `route option` and expose to the user with a single object.

Some of the field can be calculated (e.g. `bodyLimit`) and removed (e.g. `config`, `hooks`, etc.)

> what are serverLimit and routeLimit here? 

`Server Limit` is the global config on `Fastify(options)`
`Route Limit` is per route config on `fastify.route(options)`

> what is the type of it?

Should be `number` or `undefined`.

> is there any different meaning of defining bodylimit in two different way

`Server Limit` is fallback value if `Route Limit` is not exist.

**Comment by Eomm** [comment]
> what are serverLimit and routeLimit here? what is the type of it?

These two were just 2 variable names to differentiate the server's `bodyLimit` option (`const app = Fastify({ bodyLimit: 42 })`) and the route's `bodyLimit` option (`app.post('/route-limit', { bodyLimit: 42 } })`)

> is there any different meaning of defining bodylimit in two different way

- The server's `bodyLimit` is the default value for every route
- The route's `bodyLimit` overwrites the server's bodyLimit only for the single route

**Comment by debadutta98** [comment]
> > what are serverLimit and routeLimit here? what is the type of it?
> 
> These two were just 2 variable names to differentiate the server's `bodyLimit` option (`const app = Fastify({ bodyLimit: 42 })`) and the route's `bodyLimit` option (`app.post('/route-limit', { bodyLimit: 42 } })`)
> 
> > is there any different meaning of defining bodylimit in two different way
> 
> * The server's `bodyLimit` is the default value for every route
> * The route's `bodyLimit` overwrites the server's bodyLimit only for the single route

make sense 👍

@Eomm 
is the `routeBodyLimit` should append to the req body which is accepted through the handler passed as an option to a HTTP method or route method
