### ISSUE TITLE
Wrong typings for hooks on route options

### ISSUE THREAD

**Issue by brettwillis** [fastify/fastify#4376]
The in the snippet below, the hook types are a union of two identical types like `onRequestHookHandler<...> | onRequestHookHandler<...>` etc, and this excludes the async hook type, which should be valid to use here, right?

Are these supposed to be <code>onRequestHookHandler<...> | onRequest<em><b>Async</b></em>HookHandler<...></code>, etc?

https://github.com/fastify/fastify/blob/5c75f4993255a7e3fc5afbdc4b8171be52ecb618/types/route.d.ts#L48-L56

**Comment by aradwann** [comment]
It's a union between a onRequestHookHandler<...> (single value ) and a onRequestHookHandler<..>[] (array of values )

**Comment by brettwillis** [comment]
Ah yes you're right. @mcollina @aradwann do you still want a PR to include the async version in those types?

While we're at it, are there any thoughts about the non-standard camel-case naming of those types?

**Comment by mcollina** [comment]
> Ah yes you're right. @mcollina @aradwann do you still want a PR to include the async version in those types?

Given my understanding, yes, we should update this. Would you like to send a PR?

> While we're at it, are there any thoughts about the non-standard camel-case naming of those types?

We probably didn't know there was a standard. Could you link?
I would not change any types name right now - maybe open a separate issue? We might consider it for the next major.

**Comment by aradwann** [comment]
@mcollina according to https://google.github.io/styleguide/tsguide.html#identifiers class / interface / type / enum / decorator / type parameters should use UpperCamelCase
I see that most types/interfaces are written in UpperCamelCase here so I think `onSendHookHandler` should be `OnSendHookHandler` for consistency

**Comment by ismailmmd** [comment]
Hey, I have created a PR for above issue. 🙏 please review
