### ISSUE TITLE
Bump `find-my-way` to v7.3.1

### ISSUE THREAD

**Issue by arinashilyaeva** [fastify/fastify#4377]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Update `find-my-way` package to the latest version in the next Fastify release, resolves https://github.com/fastify/fastify/discussions/4324

### Motivation

There is a [fix](https://github.com/delvedor/find-my-way/pull/307) in the latest `find-my-way` version that is important for our development team, and we would really appreciate it if it would be included in the next realase. I will be happy to open a PR, but if I understand correctly you have github actions workflow for it

**Comment by mcollina** [comment]
There is no need for us to ship a new release. This is already covered by our semver range, you should just update your dependency to get the new version.

**Comment by climba03003** [comment]
You can re-install the package or use `npm update find-my-way`.
`fastify` do not lock particular version of `find-my-way`.

**Comment by arinashilyaeva** [comment]
Ok, got it, thank you
