### ISSUE TITLE
Official fastify plugin for Prometheus

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#4381]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I suggest creating a lightweight plugin that would decorate app and request with a prom-client instance, and expose metrics endpoint.

There is an existing community plugin, but it is much more heavyweight and opinionated.

I can write this plugin, and also as a community one if that is a preferred path, but this feels fundamental enough for inclusion in core plugin set.

### Motivation

Metrics are a fairly fundamental piece of modern service architecture, and currently we do not offer any official solutions there.

### Example

req.prometheus would expose prom-client instance, see official documentation for usage syntax.

**Comment by Uzlopak** [comment]
Huh? 

I only know prometheus in combination with graphana, where you expose an endpoint so that prometheus/graphana can consume the latest metrics. 

How would a prometheus attribute to the request be beneficial?

**Comment by climba03003** [comment]
Didn't there are tons of those plugin?
https://github.com/SkeLLLa/fastify-metrics
https://github.com/immobiliare/fastify-metrics

Why would it beneficial as a `official` plugin instead of using the `community` one.

**Comment by Eomm** [comment]
> Metrics are a fairly fundamental piece of modern service architecture, and currently we do not offer any official solutions there.

I think we should support opentelemetry out of the box, otherwise those who don't use prometheus would be excluded.

I already testes https://github.com/open-telemetry/opentelemetry-js and was a pain to add 😅 
So I agree we could work on that direction

**Comment by climba03003** [comment]
> I think we should support opentelemetry out of the box, otherwise those who don't use prometheus would be excluded.

https://www.npmjs.com/package/@opentelemetry/instrumentation-fastify

Didn't `open-telemetry` provide an official integration in their side? 
If we implementing in our side, I feel the same pain as `fastify-nextjs` and `nextjs`.

**Comment by mcollina** [comment]
The question is that one of those modules has been either neglected or kept out-of-date. I'm an happy user of https://github.com/SkeLLLa/fastify-metrics without problems.

I don't think we should be competing with community modules that are doing well.

**Comment by kibertoad** [comment]
> I don't think we should be competing with community modules that are doing well.

Good point. I'll proceed with building a lightweight plugin as a community module to target our specific use-case, with the general idea that community-driven fastify-metrics is a semi-officially endorsed one.
