### ISSUE TITLE
Fastify adds incorrect `content-length` and `transfer-encoding: chunked` headers by default

### ISSUE THREAD

**Issue by piranna** [fastify/fastify#4382]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Node.js version

v18.11.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.10

### Description

These are in fact two errors that seems to me they are related:

1. when replying a string or buffer without setting a `Content-Length` header by hand, Fastify adds one by itself from the actual content length. Problem is, it's being set in the header as a quoted string, while according to [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) it should be unquoted. It's said, it should be like `Content-Length: 3495`, but in fact Fastify is generating `Content-Length: "3495"`.
2. when replying a Readable object without setting a `Content-Length` header by hand, Fastify DON'T adds one by itself (that's sort of ok), but it's adding a `"transfer-encoding": "chunked"` header by itself that I've not asked for, and that in fact it's invalid because I'm returning a range request GET.

### Steps to Reproduce

1. reply a request with a string or buffer object, and check the `Content-Length` header
2. reply a request with a Readable object, and check the `transfer-encoding` header

### Expected Behavior

1. `Content-Length` header should not have quotes on its length
2. `"transfer-encoding": "chunked"` header should not be added by default when replying a Readable object

**Comment by mcollina** [comment]
Thanks for reporting! Unfortunately, I cannot reproduce your reporting issues with `curl -v` and this server:

```
'use strict'

const { Readable } = require('stream')

const fastify = require('../fastify')({
  logger: false
})

const schema = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          hello: {
            type: 'string'
          }
        }
      }
    }
  }
}

fastify
  .get('/', schema, function (req, reply) {
    reply
      .send({ hello: 'world' })
  })

fastify
  .get('/str', function (req, reply) {
    reply
      .send("this is a string")
  })

fastify
  .get('/buf', function (req, reply) {
    reply
      .send(Buffer.from("this is a string"))
  })

fastify
  .get('/stream', function (req, reply) {
    const str = "this is a string"
    reply.header('content-length', str.length)
    reply
      .send(Readable.from(str))
  })

fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
})
```

Please include a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by piranna** [comment]
ok, I'll try to arrange something in the next days. Thank you for reviewing @mcollina :-)

**Comment by piranna** [comment]
I've researched a little bit more, the error is happening me on tests with Jest (I haven't tested on production). Light-my-request library accept a `OutgoingHttpHeaders`, so whoever is setting it, it doing it with a string instead a number, but I'm not sure where could I take a look...

**Comment by climba03003** [comment]
`Transfer-Encoding: chunked` is added when you use `Trailers`. It is a **HARD** requirement for using `Trailers`.
Can you double check are you using `Trailers` in that case?

`Content-Length: <num>` doesn't matter if it set as `string` or `number`. `node` will handle it properly.

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 17
Date: Fri, 28 Oct 2022 07:47:43 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"hello":"world"}
```

```js
import http from 'http'
import net from 'net'
import { Readable } from 'stream'

const data = JSON.stringify({ hello: 'world' })

const server = http.createServer(function(request, response) {
  response.writeHead(200, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': `${Buffer.byteLength(data)}`
  })
  const stream = Readable.from([data])
  stream.pipe(response)
})
server.listen(function() {
  const client = net.createConnection({ port: server.address().port })
  client.write('GET / HTTP/1.1\r\n\r\n')
  client.setEncoding('utf8')
  client.on('data', data => {
    console.log(data)
  })
  client.on('end', () => {
    client.end()
    server.close()
  })
})
```

**Comment by piranna** [comment]
> `Transfer-Encoding: chunked` is added when you use `Trailers`. It is a **HARD** requirement for using `Trailers`. Can you double check are you using `Trailers` in that case?

No, I'm not using them, or at least not in a conscious way. In fact, I didn't know what trailers were until facing this issue, and still don't have clear what's the use case... so no, I think I'm not using them.


> `Content-Length: <num>` doesn't matter if it set as `string` or `number`. `node` will handle it properly.
> Unless, someone add it with explicit `quotes`

It was working fine, just found that issue when doing some clean-ups on my fixtures, since the ones generated automatically by Fastify were having quotes. I think it's not a huge problem, since I didn't found the issue before, and as you've said Node.js properly manage it, but since spec dictates it's unquoted, I opened the issue to ensure we are being standard compliant.

Who is adding it, I don't know.

**Comment by climba03003** [comment]
> No, I'm not using them, or at least not in a conscious way. In fact, I didn't know what trailers were until facing this issue, and still don't have clear what's the use case... so no, I think I'm not using them.

Better to have a minimal repro. Or at least the plugin list.

> I think it's not a huge problem, since I didn't found the issue before, and as you've said Node.js properly manage it

NodeJS will not `unquote` it. It render what's the user pass.
If `fastify` add `quotes`, it render with `quotes`. I didn't see `fastify` explicit adding the `quotes` either.
Maybe something wrong with `test suite` or `plugin`?

**Comment by AlexcastroDev** [comment]
Hello guys, i face this right now, lol.

the Content-Range works, but the Content-Length does not in my example:
![image](https://github.com/fastify/fastify/assets/10711649/4c093e5a-bdac-44ae-9252-3c5210d40326)

I can provide a simple example with docker:
https://github.com/AlexcastroDev/streaming-music-research

**Comment by climba03003** [comment]
> can solve this, or i'm could not see the big picture.

@AlexcastroDev Your issue is totally different than the author one. Please remember to use `return reply.send()` when you are in `async` function.

**Comment by AlexcastroDev** [comment]
> > can solve this, or i'm could not see the big picture.
> 
> @AlexcastroDev Your issue is totally different than the author one.
> 
> Please remember to use `return reply.send()` when you are in `async` function.

Thank for helping, the return fix this, and i use Readable on Event to solve.

Sorry for posting here, should i delete comment?

**Comment by piranna** [comment]
> @piranna is this issue still a thing?

I don't know, I'm not working on the company or the project where the issue appeared anymore, so I can't tell, but definitely I remember it was pretty reproductible.
