### ISSUE TITLE
mysql plugin for fastify

### ISSUE THREAD

**Issue by wedgwood** [fastify/fastify#439]
Hi @mcollina, @delvedor, could you add repo `fastify/fastify-mysql`, then I could create PR to fill it.
I think mysql is so popular that fastify should support it officially :)

**Comment by delvedor** [comment]
Hi!
The repo is [here](https://github.com/fastify/fastify-mysql) :)
Thanks!

**Comment by wedgwood** [comment]
@delvedor I have a commit. Please review it. Thanks! :)
