### ISSUE TITLE
fastify PromiseLike intersection type triggers @typescript-eslint/no-floating-promises rule when using reply.send 

### ISSUE THREAD

**Issue by alsoscotland** [fastify/fastify#4399]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Node.js version

16.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5.1

### Description

fastify is declaring a typescript intersection of the PromiseLike type
https://github.com/fastify/fastify/blob/main/fastify.d.ts#L33-L39

I am working in a project where we prefer to have the [@typescript-eslint/no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) eslint rule enabled

The type intersection is causing typical route handlers to trigger an eslint error when using reply methods.

Curious if anyone has thoughts problem or ideas for an adjustment that would alleviate the issue

### Steps to Reproduce

// in eslintrc rules block
`
'@typescript-eslint/no-floating-promises': [
    'error',
    { ignoreVoid: false, ignoreIIFE: true }
]
`

// in a fastify route definition
`    
	app.get('/', (req, reply) => {
        /* triggers the eslint error - Promises must be awaited, end with a call to .catch, or end with a call to .then with a rejection handler (@typescript-eslint/no-floating-promises) */
        reply.send('OK'); 
    });
`

### Expected Behavior

Using reply methods such as reply.send should not trigger the eslint floating promises error

**Comment by climba03003** [comment]
`void reply.send()` or `(request, reply) => reply.send()`

**Comment by jsumners** [comment]
Duplicate. Please search the issues.

**Comment by alsoscotland** [comment]
I searched issue originally but did not find the duplicate.  I found after your answer @climba03003 (thank you) 
[3894](https://github.com/fastify/fastify/issues/3894#issuecomment-1123722799)

For what it's worth
I suppose the only solution proposed is `void reply.send()` above but 
the issue ticket filed for the false positive in eslint was also closed as `working-as-expected`

[eslint-4961](https://github.com/typescript-eslint/typescript-eslint/issues/4961)

**Comment by Uzlopak** [comment]
First of all it is not an error, but is classified as such by eslint. Second of all the typings are correct and represent the shape of reply at runtime.
Should we remove the .then() method from reply because eslint claims it needs to be awaited? No. 

So we have to conclude that everything is correct and eslint reports a false positive. For false positive cases eslint has the eslint-disable-next-line annotation. So we can only recommend to annotate it accordingly.
