### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#44]
Another feature that I think we need to implement are *Hooks*.

I'm developing in my local copy the `onRequest` hook to make some experiments and I'm very happy with the result. A decision that I must take at the moment is: where call the `onRequestHook` inside the lifecycle of fastify.

These are the two options:
1) *after* the middleware execution but *before* the routing function:
```
new request => middlware => onRequest => router => validation => Request/Reply => handler
```

2) *after* the routing function, the validation and the creation of the object Reques and Repy, but *before* the user's handler.
```
new request => middlware => router => validation => Request/Reply => onRequest => handler
```
From the function perspective the difference is:
in the first case the function makes changes on the "vanilla" request and response object from node core, in the second case the function will work on Request and Reply objects from fastify.

But the main difference is that in the first case the change will work for all the routes (for example can change the *req.url*), while in the second one the user will access the instances of Request/Reply of the specific route. This means that the user could add methods/data to the Request/Reply instances (at runtime!) and use them in the route handler.

Thoughts?

cc: @mcollina @lucamaraschi @davidmarkclements

**Comment by mcollina** [comment]
I'm in for the 2nd approach, but maybe we should have both.

**Comment by delvedor** [comment]
I'm for the second approach as well, since the user can update the Request from fastify and request from core node (and the body!).

> but maybe we should have both.

Why?

**Comment by mcollina** [comment]
because I can see the value of executing things before and after validation happen.

**Comment by davidmarkclements** [comment]
How about the following hooks:

preMiddleware
postMiddleware
preValidation
postValidation
preReply

```
new request => preMiddleware => middleware => postMiddleware => router => preValidation => validation => postValidation => Request/Reply => preReply=> handler
```

**Comment by mcollina** [comment]
If we can have all of those wihout perf it, I'm in.

**Comment by delvedor** [comment]
@davidmarkclements just to understand, since *postValidation* and *preReply* are almost consecutive, where do you want to call *postValidation*?

I guess here, between the two highlighted lines.
https://github.com/fastify/fastify/blob/hooks-support/lib/tier-node.js#L83-L84

**Comment by davidmarkclements** [comment]
I think if they all default to the same noop function it shouldn't much overhead to have the option of 2 hooks or 10 hooks - obv. the overhead will increase per hook added - possibly the best way is to compile a single function (e.g. new Function) instead of calling the user hooks individually 

I think I've got the wrong name for preReply - perhaps it should be afterReplyWrapper? not sure on internals, maybe not needed 

But you bring up a point too, preValidation is also postRouter - we could alias or just stick with focal points

**Comment by delvedor** [comment]
@davidmarkclements check #45.

At the moment we are executing the user code directly, do you think that compile it will increase the performances sensibly?

**Comment by davidmarkclements** [comment]
possibly - but it's premature optimization I think - see what perf is like and then we could look at options

**Comment by delvedor** [comment]
I've tried to run the benchmarks with just this hooks:
```js
fastify.addHook({
  onRequest: function (req, reply, next) {
    req.req.test = true
    next()
  }
})
```
and the result is almost unchanged.
If I add the above hook three times, there is a ~7% perf decrease.

**Comment by davidmarkclements** [comment]
so it's looping through an array of three functions on each request?

I think it's something we'd have to very careful with, once you compile the func you've lost closure scope

but the idea would be something like:

```js
var compiledHooks = Function(arrayofFns.map(function (fn) { return  '!' + fn + '()' }).join(''))
```

Also once you have too many inlined funcs in compiled hooks, it'll probably hurt perf, 
so you'd need to split it up - another way is to compile a function that simply calls the hooks (to avoid the loop through array) - but you'll still lose closure

**Comment by delvedor** [comment]
> so it's looping through an array of three functions on each request?

Yes, [this](https://github.com/fastify/fastify/blob/daeab27b4c3f5f57d50a89923f25ef4d0b15ee2c/fastify.js#L86-L91) is how the hooks are executed.
`onRequestRaw()` returns the array of the *onRequestRaw* hooks.
___
I agree with you, compile could be risky.

Maybe add a flag `{ compile: true }`, so the user is aware of what is happening (same for the function that calls all the hooks without the loop), something like the *extreme mode* in pino.

**Comment by davidmarkclements** [comment]
yeah possibly - I'd say make a first pass at implementation and then see what we can do from there

**Comment by davidmarkclements** [comment]
(we could also have an explicit compile option where they can pass in a context object made up things they want to access)

**Comment by lucamaraschi** [comment]
I like the compilation idea... @davidmarkclements don't u think this might become hard to debug tho?Looking again at the developer experience and ease of use.

**Comment by delvedor** [comment]
I agree with @lucamaraschi, the compilation can be very hard to debug, I think the flag `compile: true` is the best choice.

The next feature we will support are plugins, and can happen that a plugin registers a hook, and if the compilation won't cause issues for the user, maybe can cause issues to the plugin.

**Comment by davidmarkclements** [comment]
yah compile is an advanced optimization - not necessary for first pass
