### ISSUE TITLE
waiting for async `onResponse` hook to complete during testing

### ISSUE THREAD

**Issue by Alex-Yakubovsky** [fastify/fastify#4400]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Apologies if this is something already solved, I did try to go through the documentation thoroughly and existing test files.

It would be helpful if either:

a) `app.inject` would resolve once `onResponse` hooks have been executed (if the hooks are async, wait for them to resolve)
b) introduce a method that returns a promise that is resolved once all the `onResponse` hooks are complete. Perhaps something like `await app.postHandlerHooks()` (probably with a better name). 
c) if this is a solved problem, an example in the documentation

### Motivation

I'm writing automated testing for a route that has an `onResponse` hook added that runs some async code. I'd like to make assertions on the state of my application after the `onResponse` hook has been resolved.

### Example

If I have a route like

```js
fastify.route({
    method: 'GET',
    url: '/my/route',
    handler: (request, reply) => {
        // simple handler, just for illustrative purposes
        reply.send({ hello: "world" })
    },
    onResponse: async (request, reply) => {
        await saveRequestDataToDatabase(request)
        callToSomeLibrary()
    } 
})
```

In this simplified example, I'd like to make sure that `callToSomeLibrary` has been called, so my test would look something like

```js
await app.inject({ method: 'GET', path: '/my/route' })
// assume I have some setup code that replaces `callToSomeLibrary` with `mockCallToSomeLibrary`
expect(mockCallToSomeLibrary).toBeCalled() // <<<<< this fails
```

One hack I can do is to add a timeout

```js
await app.inject({ method: 'GET', path: '/my/route' })
setTimeout(() => expect(mockCallToSomeLibrary).toBeCalled(), 1000) // works
```

**Comment by Uzlopak** [comment]
Is callToSomeLibrary async or why does it race?

**Comment by Alex-Yakubovsky** [comment]
> Is callToSomeLibrary async or why does it race?

no, but `saveRequestDataToDatabase` is async, so `callToSomeLibrary` is only called after `saveRequestDataToDatabase` resolves

**Comment by mcollina** [comment]
I don't think this is feasible to add without impacting the runtime performance.

**Comment by Uzlopak** [comment]
At my previous employer we had something like that for tracking "auditing data". We treated it as fire and forget and did not give the guarantee that the data is stored 100%. I mean you already processed the data in a different microservice and there is no way to roll back  those stateful changes. I mean, why would you roll back stuff, because some logging failed.

You should also consider to not store requests on every request but collect the data and store it every 5 seconds  (10 seconds or 60 seconds whatever) in a bulk write. 

On closing the fastify instance or when you send SIGTERM you should make the final bulk write.

Maybe you want to utilize a pino transport and log data with pino?

But i also think that it is a antipattern if your case is similar to the one i described.

**Comment by Eomm** [comment]
Does this work?

```
process.nextTick(()=>{
  expect(mockCallToSomeLibrary).toBeCalled()
})
```

**Comment by Alex-Yakubovsky** [comment]
responding to @mcollina 

> I don't think this is feasible to add without impacting the runtime performance.
Damn, any ideas on how to approach testing the above? I could just export the `onResponse` function and test it standalone, but I think I'd feel most confident my route works correctly if I made a request to the route itself.

responding to @Uzlopak 
I see what you're saying and it makes a lot of sense, but our use case is slightly different than the example I gave. I just wanted to give a simple example for illustrative purposes. Basically, we have an API that we charge our users based off of the number of calls made. We track usage in the `onResponse` hook. From a business perspective that is an important piece of code and we want to feel confident works correctly.

respond to @Eomm 
>Does this work?
>
> ```
> process.nextTick(()=>{
>  expect(mockCallToSomeLibrary).toBeCalled()
> })
> ```

This is roughly what is happening in the `setTImeout(...)`, the issue is what if `saveRequestDataToDatabase` hasn't been resolved by the next tick (e.g., the operation takes time to talk to the database) and therefore `callToSomeLibrary` hasn't been called yet.

**Comment by climba03003** [comment]
> From a business perspective that is an important piece of code and we want to feel confident works correctly.

If it is a important business logic, please do it inside `handler` which ensure everything work properly before sent.
Putting your business logic inside `onResponse` is prone to race-condition.

**Comment by Alex-Yakubovsky** [comment]
> If it is a important business logic, please do it inside handler which ensure everything work properly before sent.
Putting your business logic inside onResponse is prone to race-condition.

That's a direction I was considering as well. Totally subjective, it just _felt_ like the logic belonged within the `onResponse`. Can you elaborate on/link to the documentation on your point about:

> Putting your business logic inside onResponse is prone to race-condition.

This is something I couldn't find more info about from a quick google search.

**Comment by climba03003** [comment]
`onResponse` hook is fired **after** the response sent to client. Anything done in here cannot guarantee the working order between request and success.

Let's say, 
1. What if `onResponse` hook throw an error? How can you rescue the calls?
2. While running `onResponse` hook, the client fire multiple calls. The counts is behind the actually calls.

When you know the when the `onResponse` hook is fired, you actually see a lot of problem when you place your business logic inside. The test already show you, you cannot guarantee it is called, when your client get the reply.

**Comment by climba03003** [comment]
I am closing it as `Not Planned`.

`onResponse` hook is **fired** after the response sent which means when you can **wait** for it. It collided with `onSend` hook.
`onSend` hook is a stage that can do anything, not only mutating the `response`. You can do job here if you need to wait before response.

**Comment by Alex-Yakubovsky** [comment]
Appreciate the guidance 🙏 .

In my use case, we don't want to wait for usage to be recorded prior to returning a response to the client, so rescuing from calls is not a requirement. We want the response to be sent first, then record usage, which was the motivation behind reaching for `onResponse`.

But from a more high level, what is the recommended approach to testing `onResponse` hooks? Just to test as a regular function, passing in a fake `FastifyRequest`, `FastifyReply`? What if I was relying on something in `FastifyReply` being set by the `handler` and using that data within the `onResponse` hook and wanted to check that indeed that data is set correctly and functions are correctly called with said data?

**Comment by climba03003** [comment]
> But from a more high level, what is the recommended approach to testing onResponse hooks?

Mocking if you need to know if it is called by application lifecycle.

> Just to test as a regular function, passing in a fake FastifyRequest, FastifyReply?

It can be done.

> What if I was relying on something in FastifyReply being set by the handler and using that data within the onResponse hook and wanted to check that indeed that data is set correctly and functions are correctly called with said data?

Add an extra `onResponse` hook to check for the result. If the function is encapsulation, use `onRoute` hook to append the checking function in the end.

**Comment by Alex-Yakubovsky** [comment]
> Add an extra onResponse hook to check for the result. If the function is encapsulation, use onRoute hook to append the checking function in the end.

Ah okay, this is really helpful. I didn't consider using the `onRoute` hook to append the checking function. Thank you for the help!
