### ISSUE TITLE
Cannot compile empty response schema

### ISSUE THREAD

**Issue by edosrecki** [fastify/fastify#4403]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Node.js version

16.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6

### Description

Fastify does not support specifying an empty response schema, e.g. a schema for `204 No Content` HTTP response.

A workaround is to add `type: 'null'` to the schema, but it just feels wrong to use it, cause its intent is to specify JSON serialized `null` value, and not an empty response.

### Steps to Reproduce

```js
const fastify = require('fastify')()
fastify.get(
  '/',
  {
    schema: {
      response: {
        204: {
          description: 'Empty response',
        },
      },
    },
  },
  (req, reply) => {
    reply.code(204).send()
  }
)
fastify.listen({ port: 3000 }, (error) => {
  console.error(error)
})

/*
FastifyError [Error]: Failed building the serialization schema for GET: /, due to error schema is invalid: data/properties/description must be object,boolean
    at Boot.<anonymous> (/REDACTED/node_modules/fastify/lib/route.js:364:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at /REDACTED/node_modules/avvio/boot.js:160:12
    at /REDACTED/node_modules/avvio/plugin.js:275:7
    at done (/REDACTED/node_modules/avvio/plugin.js:200:5)
    at check (/REDACTED/node_modules/avvio/plugin.js:224:9)
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8) {
  code: 'FST_ERR_SCH_SERIALIZATION_BUILD',
  statusCode: 500
}
*/
```

**Comment by Uzlopak** [comment]
Hmm. Seems like it does not work because it thinks that it is a content-type "description".

For more info:
https://github.com/fastify/fastify/pull/4264

**Comment by climba03003** [comment]
```json
{
  "description": "Empty response",
}
```

is identical to 

```json
{
  "type": "object",
  "properties": {
    "description": "Empty response",
  }
}
```

You should disable `jsonShorthand`.
https://www.fastify.io/docs/latest/Reference/Server/#jsonshorthand
