### ISSUE TITLE
Please add route shorthand declarations for the remaining supported http methods.

### ISSUE THREAD

**Issue by smallandsimple** [fastify/fastify#4405]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

(Similar but not identical to issue #9)

### 🚀 Feature Proposal

Currently, the Fastify shorthand declarations are limited to:
`fastify.get(path, [options], handler)`
`fastify.head(path, [options], handler)`
`fastify.post(path, [options], handler)`
`fastify.put(path, [options], handler)`
`fastify.delete(path, [options], handler)`
`fastify.options(path, [options], handler)`
`fastify.patch(path, [options], handler)`

Please add shorthand methods for the other valid route methods:
'SEARCH', 'TRACE', 'PROPFIND', 'PROPPATCH', 'MKCOL', 'COPY', 'MOVE', 'LOCK' and 'UNLOCK'

### Motivation

My organization has planned to begin using the search http method and phase out the use of POST for routes that query with a JSON body.  We currently use the shorthand declarations and would like to be able to maintain that consistency, as we also are phasing out and migrating from Express.js to Fastify.

### Example

```
const fastify = require('fastify')({ logger: true })

fastify.search('/', async (request, reply) => {
  return { found: 'world' }
})

const start = async () => {
  try {
    await fastify.listen({ port: 3000 })
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

**Comment by Uzlopak** [comment]
I think this can be done in under an hour to be implemented.

Add the missing shorthand methods here:
https://github.com/fastify/fastify/blob/675b00d6ca7a7eeaad073e6469c70b50fcd532eb/fastify.js#L244

Add a new test file, testing all shorthand methods and checking in the handler, that the method is set correct on the request-object.

**Comment by meeraj257** [comment]
@Uzlopak - can this issue be assigned to me? I like to work on this

**Comment by climba03003** [comment]
I am not really convinced to add those function in minor.
`search`, `trace`, `copy`, `move`, `lock` and `unlock` is a generic wording that easy to mess with a people decorator.

The extension for those method as a plugin also easy enough.

**Comment by Uzlopak** [comment]
I created a PR. We can decide to reject or approve it based on code.

**Comment by Uzlopak** [comment]
Will be part of v5.x
