### ISSUE TITLE
Fastify no longer replies with a stream when using async handler function

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#4411]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Node.js version

16.x / 18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.1 LTS

### Description

Fastify seem to be failing to respond with a stream when using async handler function in newer versions.
I.e. doing this works as expected:
```js
fastify.get('/sync', function (request, reply) {
  const stream = getStream();
  reply.send(stream);
});
```

But doing this returns empty response:
```js
fastify.get('/sync', async function (request, reply) {
  const stream = await getStreamAsync();
  reply.send(stream);
});
```

### Steps to Reproduce

Here's a simple repro on stackblitz: https://stackblitz.com/edit/node-vx6e1f?file=index.js,index.test.js

### Expected Behavior

Async function sending back a stream should still work.
And it used to work as expected in older versions (see e.g. [old exoframe test suite](https://github.com/exoframejs/exoframe/actions/runs/2623227904) and [corresponding fastify code](https://github.com/exoframejs/exoframe/blob/c2fcafc7d9d2f45468e00e0646e3a6818f97d835/packages/exoframe-server/src/routes/logs.js#L82))

**Comment by jsumners** [comment]
`return reply.send(stream)`

**Comment by yamalight** [comment]
@jsumners that does indeed fix the issue! was that an intended change at some point? 🤔

**Comment by jsumners** [comment]
Yes. It is a v4 change. I updated my original response.

**Comment by yamalight** [comment]
@jsumners got it, thanks for clarification! 
still not sure why it worked with fastify@4.2.0 before, but that fixed it 🤔 
closing this, thanks for the help!
