### ISSUE TITLE
CI workflow is failing for `node 14` on `windows-latest`

### ISSUE THREAD

**Issue by driimus** [fastify/fastify#4425]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Only raising the issue for visibility. Feel free to close if there's already a planned resolution.
https://github.com/fastify/fastify/blob/5c8039c40e11be4a9c3617c145cd2667e0c68f24/.github/workflows/ci.yml#L1

This workflow (or any others that use `npm@<7` and the latest `tap` version) will fail for `node 14` on `windows-latest`. 
Context and workarounds: https://github.com/fastify/fastify-type-provider-typebox/pull/43#issuecomment-1315778519

You can see newer PRs experience the failure (e.g. #4415, #4421)

**Comment by jsumners** [comment]
In each instance where that workflow uses a specific Node.js version it is `lts/*`, except for line:

https://github.com/fastify/fastify/blob/5c8039c40e11be4a9c3617c145cd2667e0c68f24/.github/workflows/ci.yml#L75

None of those versions ship with `npm@9`.

**Comment by climba03003** [comment]
More like an upstream issue.
`fastify > tap > @babel/generator > @jridgewell/gen-mapping`

**Comment by Uzlopak** [comment]
I actually dont understand why this really happens because @isaacs puts all the dependencies also in the final tar file which gets pushed to npm.

**Comment by climba03003** [comment]
Is it possible to push the `node_modules` to `npm.js`?
This folder should be ignored in any configuration.

**Comment by Uzlopak** [comment]
Maybe the bundled dependencies need to be part of devDependencies to avoid issues, when npm tries to overwrite them in the installation phase of the dependencies?

**Comment by Uzlopak** [comment]
Isaacs released new tap version..we have to trigger the workflows again
