### ISSUE TITLE
Supporting logging formatters for child loggers, such as request.log

### ISSUE THREAD

**Issue by markrzen** [fastify/fastify#4426]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

How do folks feel about supporting logging formatters for child loggers, such as request.log? Similar to how log serializers are copied down to the child log.

### Motivation

The immediate goal for is to allow me to change the structure of the request id binding in all request logs.

Today it looks like `reqId=$value`, but I would like it to be in a completely different structure:

E.g.
```
operation: {
  id: $value
}
```

This can not be done by simply using the requestIdLabel configuration, but I suspect is possible via the pino binding formatter.

### Example

```
    formatters: {
      bindings(bindings) {
        if (bindings.reqId) {
          bindings.operations = { id: bindings.reqId };
        } 
        return bindings;
      }
    },
```

**Comment by markrzen** [comment]
@mcollina Absolutely, I just wanted to make sure you didn't see any obvious flaw to the idea. It could be potentially breaking, which is unfortunate, but it does follow the existing pattern for serializers. I will submit a PR.

**Comment by mcollina** [comment]
I'd be -1 to make a breaking change. I'm +1 to making developer configure their stuff. I'd personally do it via pino formatters. It might even be just docs.

**Comment by markrzen** [comment]
I am recommending we allow folks to use pino formatters, the hard part is passing them into the request/route child logger creation. I was following the pattern that was used for serializers. I could add a new pattern to make it backwards compatible, but it would be a new logging configuration "requestLoggerFormatters" or some maddness.

**Comment by mcollina** [comment]
What different way would you recommend?

**Comment by markrzen** [comment]
Going to punt on this for now. Found a way to move quicker using a different mechanism.
