### ISSUE TITLE
Is it possible enforce having schema on Fastify controllers? 

### ISSUE THREAD

**Issue by agjs** [fastify/fastify#4431]
Hey folks. I'm wondering if it's possible to somehow make Fastify fail if you define a controller without e.g. a response schema? Is there some option already that could make this happen?

Thanks a lot in advance!
Cheers

**Comment by Uzlopak** [comment]
TBH

I am thinking, that we should start to write a eslint plugin. I mean we constantly get issues regarding async await misuse. Maybe thats something we should start with.

**Comment by mcollina** [comment]
I tend to agree.

**Comment by agjs** [comment]
If you guys need a hand with this, I could get myself familiar with the plugin API and maybe create one. I do whatsoever think that having this as some sort of an option would make it a lot simpler, cause my sentiment here is that you should never really have an endpoint without validating your input (and often output), therefore, it feels like something that could *implicitly* make Fastify better, by upfront suggesting best practices. I think you guys are doing that a lot already, and this feels like something that could be part of that. 

I guess it's too late to enforce something like this by default (or maybe not), but having an option that we could pass when instantiating Fastify feels like a more natural solution, then needing to install a plugin. Or even, hook into one of the req/res hooks. 

Anyway, either way, I'm happy to assist if any of this makes sense. 

And yea, as I always say on [my stream](https://twitch.tv/programmer_network (shameless advertising)), Fastify is the best thing that happened to Node.js community in a long time, so keep up the great work.

Cheers

**Comment by Eomm** [comment]
> but having an option that we could pass when instantiating Fastify feels like a more natural solution, then needing to install a plugin

We tend to keep the core as dry as possible, so if something can be a plugin, it should be a plugin

**Comment by agjs** [comment]
> > but having an option that we could pass when instantiating Fastify feels like a more natural solution, then needing to install a plugin
> 
> We tend to keep the core as dry as possible, so if something can be a plugin, it should be a plugin

Fair enough, I can't argue that. Thanks for your responses. I'll either just solve this for the current project I'm working on, or make a plugin. Let's see where I end up.

Cheers

**Comment by agjs** [comment]
Alright, I've turned this into a plugin and I will most likely push it for review tomorrow, or in a day or two. @Eomm @mcollina

I also followed the structure and the guidelines from another plugin (fastify/cors) and right now I just have to write some unit tests.

I'm having an issue with onRoute actually being executed in the unit test, so hopefully I'll figure that one out in a day or two. Still in **draft**, but [here is the repo](https://github.com/agjs/fastify-enforce-schema)

**Comment by Eomm** [comment]
I have few comments:

- there is a `next();` call in the `onRoute` hook that is a misprint
- you can't publish the module name `@fastify/enforce-schema` as `@fastify` is an "official" namespace for the fastify org
- your users [must `await fastify.register()`](https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/#synchronous-route-definitions-2954) your plugin to let it works correctly

**Comment by agjs** [comment]
> I have few comments:
> 
> * there is a `next();` call in the `onRoute` hook that is a misprint
> * you can't publish the module name `@fastify/enforce-schema` as `@fastify` is an "official" namespace for the fastify org
> * your users [must `await fastify.register()`](https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/#synchronous-route-definitions-2954) your plugin to let it works correctly

Thanks for the comments, @Eomm. I tried following some of the existing core libraries from Fastify, mainly to ensure that I do things according to your guidelines. I "namespaced" the package with @fastify/ as I had an impression that I'd transfer the plugin ownership to you, hence, why I did it. I will remove it.

And thanks a lot for the `await` comment, that's probably by the hook didn't work in my unit test(s), even though, the documentation stated that is synchronous and when I logged things, they did seem to happen in the right order. Will get back to this tonight, once I'm done with work.

Cheers

**Comment by jsumners** [comment]
> I "namespaced" the package with @fastify/ as I had an impression that I'd transfer the plugin ownership to you, hence, why I did it.

@fastify/core we should open a discussion and determine some qualifications for this going forward. In my opinion, there should be some data showing necessity of the plugin in the ecosystem prior to accepting new packages to maintain.

**Comment by agjs** [comment]
> > I "namespaced" the package with @fastify/ as I had an impression that I'd transfer the plugin ownership to you, hence, why I did it.
> 
> @fastify/core we should open a discussion and determine some qualifications for this going forward. In my opinion, there should be some data showing necessity of the plugin in the ecosystem prior to accepting new packages to maintain.

You by no means have to accept this in any way, as indeed, I have built this for my own project. And indeed, if anyone else ever is going to need this or not, remains a question. Either way, I'll publish it, in case someone does. Will you "accept" it or not, that's completely up to you folks, it changes nothing for me personally.

Cheers

**Comment by agjs** [comment]
Hey folks. I just wanted to tell you that the plugin has been built and you can find it on npm.

[fastify-enforce-schema](https://www.npmjs.com/package/fastify-enforce-schema)

Thanks for your suggestions and help, I will close this one now.

Cheers
