### ISSUE TITLE
Awaiting rep.code() hangs

### ISSUE THREAD

**Issue by Igorgro** [fastify/fastify#4433]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.0

### Node.js version

16.x, 18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux

### Description

When calling `await rep.code(...)` the request hangs. For example the followin code
```js
app.get('/', async (req, rep) => {
    console.log('Setting code 404');
    await rep.code(404);
    console.log('Code set');
    return { message: 'not found' };
});
```
Makes the request to hang at await.

### Steps to Reproduce

Create a minimal fastify app and add the following route code:
```js
app.get('/', async (req, rep) => {
    console.log('Setting code 404');
    await rep.code(404);
    console.log('Code set');
    return { message: 'not found' };
});
```
If the await is replaced with void (ignore promise), everythig works correctly.

### Expected Behavior

The request doesn't hangs when setting http code

**Comment by mcollina** [comment]
Sure thing it hangs, the promise will be resolved when the response is sent.
Take a look at:
https://www.fastify.io/docs/latest/Reference/Routes/#async-await
