### ISSUE TITLE
Wrong types for FastifyRegister with custom logger

### ISSUE THREAD

**Issue by marcoreni** [fastify/fastify#4435]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.0

### Node.js version

18.12.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6.1

### Description

We're using a custom logger (based on Pino) in our implementation. When using `withTypeProvider`, we're having some issues with Typescript and the registration of plugins / routes.

If I understand correctly, [FastifyRegister](https://github.com/fastify/fastify/blob/45c8564e6cff193763c4fe0616d103405e353e18/types/register.d.ts#L20) does not use the generic for the logger, hence we're not able to pass the custom instance inside the register function.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/2797489/203072319-42adfd83-549f-4ad4-9cb9-6f1fc0bcfd8c.png">

### Steps to Reproduce

```ts
import { TypeBoxTypeProvider } from "@fastify/type-provider-typebox";
import { fastify } from "fastify";
import { pino } from "pino";

const server = fastify({
	logger: pino(),
}).withTypeProvider<TypeBoxTypeProvider>();

type AppFastifyInstance = typeof server;

const routes = async (instance: AppFastifyInstance): Promise<void> => {
	instance.get("/bar", {}, async (res, reply) => {
		return reply.send("ok");
	});
};

/** "routes" goes in error */
await server.register(routes, {
	prefix: "/foo",
});

```

### Expected Behavior

It should work :)

**Comment by RafaelGSS** [comment]
Good catch! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by sinclairzx81** [comment]
@marcoreni Hi. 

The issue may be related to `server.register()` as it's possible to replicate the issue without configuring a TypeProvider.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMwIYGcbGQTzgXxSghDgCI1NscyBuAWAChRJZE4xgA7CAok8px50mTAMYQumOOgCmUAG7y4AXhQYsuABRIANhADmB+QC4O3CFoCUBGwHo7cADwBaF3B5wJXZMAMBXKFQsSVFGb2lifxhZdFU4DBwuMTgtbkxUZNkzGBwwWQhkGXklKCszAAViEGA5JwUIYAATAD5VNoQmODh0mEyxWQA6YxgtMjsAI1QoMgAaRHx5xOTUqFj5tbBdHBsVDq7uuDWYQK4j2S2cQbkuJrGIAGsyKwZGbvwXpnww1AB3VGA8DkinkgzWBlqMSgWiiMXQ8yQDmc7nkxCgcEkRwg0ViBzAa18AA8zONkBAIHMvi8gA)

```typescript
import { fastify } from "fastify";
import { pino } from "pino";

const server = fastify({ logger: pino() }) // <-- no configuration

const routes = async (instance: typeof server): Promise<void> => {
  instance.get("/bar", {}, async (res, reply) => {
    return reply.send("ok");
  });
}

await server.register(routes, { // <- error on routes
  prefix: "/foo",
});
```
However, it's possible to write your example code this way which mitigates type errors on `.register()`.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYCEIA82YAKUEAbsACYZRwC+cAZiSHAEQACDAhgM4zANUAehjoMAWjAlyVKONGYARnlYBuALAAoUJFiJGvfoIA0cAGKGBqAJIA7Pl1sBjDHUbM23PlbVad0eCQwYFsINyYIFlZg0N9NLSEhOABhCFsGYABzAFcoVxgAC1cealJqOBgw7JKKooqxOCkySmoAOi0nNL44EqgymgBeA29BAAokABsITMzqAC5GkIhRgEo6FdaAd2BCggxiZtkAHj2cfDEDmWoAPlWtBKS9uAByEIdnDGe4XnNLQTt3i4Ol14CRsjAMDw4ENeKhnHBRm8YI4XAsLCMbPZkR81gNroh7po4MS4Ik4AB5MD8NJcCYLABKEk66SyuXyDSaVxo20KIVqrjAE2ymRCWhJcGZ3WZGRyeQo0LgSJRGC2OwKe0uLSgJzEZw10i1txWhPFZIAIhgMrZXGCITx2poAJDS1ly1qzGCjVhCRRcKCsUwIWimWHw0Z5HimPKC1C4-EILSOx15GC5WxwaMTVCtEq2CheiAAa1YKw0Ttopa0tEJZMZIr45UFwtFmi4my4Ox6pTaeXrEKg4Yg4MhgcaeQyuAW3oYEAgrHWpKSRaAA)

```typescript
import { TypeBoxTypeProvider } from "@fastify/type-provider-typebox";
import { fastify, FastifyInstance } from "fastify";
import { pino } from "pino";

// Configure the server to use the type provider.
const server = fastify({ logger: pino() }).withTypeProvider<TypeBoxTypeProvider>()

// Ensure instance is typed as FastifyInstance
const routes = async (instance: FastifyInstance) => {

  // Optional: Re-configure type provider within the plugin
  const configured = instance.withTypeProvider<TypeBoxTypeProvider>()

  // Define routes.
  configured.get("/bar", {}, (res, reply) => reply.send("ok"));
}

// Register plugin
await server.register(routes, { prefix: "/foo" }) // ok
```

Hope this helps!
S

**Comment by marcoreni** [comment]
@jagu-sayan , I think what you're encountering is a different bug. If I'm right, it's discussed here: https://github.com/fastify/fastify/issues/4241 . 

@sinclairzx81 you're right, it's not related to TypeProvider per se. If I use your workaround I'll lose the TypeBox Provider type enhancements, since `instance` will be treated as the default FastifyInstance. Anyway, I opened a PR to fix the problem.

**Comment by jagu-sayan** [comment]
Thanks @marcoreni 
I do an `import { fastify } from "fastify";`, but I  have `"moduleResolution": "NodeNext"` in my  `tsconfig.json`, if I put `"moduleResolution": "Node"`, my problem is reolved.

**Comment by Uzlopak** [comment]
We are currently fixing nodenext issues.
