### ISSUE TITLE
Replace SEARCH method with QUERY method

### ISSUE THREAD

**Issue by agad** [fastify/fastify#4437]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It appears the SEARCH method is now being called the QUERY method by the IETF.  Please see: https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/.    Looks like the new method name will become the standard.   

### Motivation

To make sure Fastify adheres to IETF standards.

**Comment by jsumners** [comment]
A draft is not an RFC. I wouldn't recommend implementing anything until it has at least reached a full RFC state.

**Comment by agad** [comment]
Good point, I thought it had reached past draft stage.  However, wasn't the search method also a draft, or did that approach RFC state and this draft suggests to amend the RFC?  Trying to figure out what to support for an API where I really want to offer something that is not the usual GET query string mess.

**Comment by jsumners** [comment]
`SEARCH` is part of the webdav spec https://www.rfc-editor.org/info/rfc5323

**Comment by agad** [comment]
Ohhhhhhhhhhh, so its actually separate from the new query method and that is likely why they changes the method name.  Got it.  OK, my confusion.  Closing the request.
