### ISSUE TITLE
Cannot find reference (array schema)

### ISSUE THREAD

**Issue by mikevercoelen** [fastify/fastify#4440]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Node.js version

16.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.7

### Description

If using an array of ref schema's, an error is thrown:

```
Cannot find reference "XXX"
```

### Steps to Reproduce

```
const EventAttachment = Type.Object({
  id: Type.String()
}, {
  $id: 'EventAttachment'
})

const Event = Type.Object({
  id: Type.String(),
  attachments: Type.Ref(EventAttachment)
}, {
  $id: 'Event'
})

fastify.addSchema(EventAttachment)
fastify.addSchema(Event)

const ReplyEventSchema = Type.Object({
  events: Type.Array(Type.Ref(Event))
})

fastify.get<{ Reply: ReplyEventSchema }>('/events', {
    schema: {
      response: {

        // get rekt
        200: ReplyEventSchema
      }
    }
);    
```

**Comment by L2jLiga** [comment]
Hi @mikevercoelen,
in order to use schema references this schemas should be added to fastify instance - [reference](https://www.fastify.io/docs/latest/Reference/Server/#addschema)

*example*:
```typescript
const EventAttachment = Type.Object({
  id: Type.String()
}, {
  $id: 'EventAttachment'
})

const Event = Type.Object({
  id: Type.String(),
  attachments: Type.Ref(EventAttachment)
}, {
  $id: 'Event'
})


const ReplyEventSchema = Type.Object({
  events: Type.Array(Type.Ref(Event))
})

// Registering shared schemas within fastify instance
fastify.addSchema(EventAttachment)
fastify.addSchema(Event)

fastify.get<{ Reply: ReplyEventSchema }>('/events', {
    schema: {
      response: {

        // get rekt
        200: ReplyEventSchema
      }
    }
); 
```

**Comment by mikevercoelen** [comment]
Hi thanks for the quick reply!

Yup, that's what I've done already, it's still crashing. Try it.

**Comment by mikevercoelen** [comment]
I found the issues, due to the order of when things are imported
