### ISSUE TITLE
"Content-Length required" status code response 400 instead of 411

### ISSUE THREAD

**Issue by ccarcaci** [fastify/fastify#4443]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.0

### Node.js version

16.18.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Description

I have specified this json schema validator for my endpoint:
```
const MAX_UPLOAD_SIZE = 500000
const uploadJsonSchema = {
  schema: {
    headers: {
      type: 'object',
      properties: {
        Authorization: {
          type: 'string',
          pattern: '^(Bearer\\s)',
        },
        'Content-Type': {
          type: 'string',
          enum: ['text/plain; charset=utf-8'],
        },
        'Content-Length': {
          type: 'number',
          maximum: MAX_UPLOAD_SIZE,
        },
      },
      required: ['Authorization', 'Content-Type', 'Content-Length'],
    },
    params: {
      type: 'object',
      properties: {
        storyUrl: { type: 'string', pattern: '^[a-zA-Z0-9][a-zA-Z0-9\\-_]{1,62}[a-zA-Z0-9]$' },
      },
    },
    body: {
      type: 'string',
      maxLength: 500 * 1000,
    },
  },
}
```

Content-Length header is mandatory and as per [HTTP Status specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411) I'm expecting to receive a 411 status code.
I've received a 400 status code instead.

```
$ curl --verbose --request POST    --header "Content-Type: text/plain; charset=utf-8"    --header "Authorization: Bearer the.jwt.token"   http://localhost:3000/story/grow-software-engineer
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /story/grow-software-engineer HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: text/plain; charset=utf-8
> Authorization: Bearer the.jwt.token
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=utf-8
< content-length: 66
< Date: Sat, 26 Nov 2022 09:48:56 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
< 
* Connection #0 to host localhost left intact
{"message":"headers must have required property 'content-length'"}
```

### Steps to Reproduce

Define an endpoint using the schema reported above:
i.e.
`server.post('/story/:storyUrl', uploadJsonSchema, uploadHandler(redisClient))`

Hit it with a POST call without Content-Length header.

### Expected Behavior

Expected behavior is 411 error status code as response.

**Comment by Uzlopak** [comment]
Please provide a minimal viable code example. A repository which we can clone etc..

**Comment by metcoder95** [comment]
Though the main point is in fact true by spec, the behavior is completely expected and I'm not sure if something should be changed/fixed at the Fastify level.

Here what is happening is that the request is reaching the proper `JSON Schema` defined and doing a proper validation by returning `HTTP 400` as the validation failed (the property is missed).
As `fastify` doesn't have a way to treat the `spec` headers in a custom manner, here there are two things that can be done:

1. Schedule a `preValidation` handle that does the custom check against the `header` so you can reply with `HTTP 411` as desired
2. Set a custom error handler through `Server#setErrorHandler` (see [reference](https://www.fastify.io/docs/latest/Reference/Server/#seterrorhandler)), and make a check against the error passed as an argument to the callback handler

**Comment by ccarcaci** [comment]
> Please provide a minimal viable code example. A repository which we can clone etc..

Here a repository: https://github.com/ccarcaci/fastify-no-411
Usage:
```
npm start
curl --verbose --request POST \
     --header "Content-Type: text/plain; charset=utf-8" \
     --header "Authorization: Bearer the.jwt.token" \
     http://localhost:3000/411
```

**Comment by ccarcaci** [comment]
> Though the main point is in fact true by spec, the behavior is completely expected and I'm not sure if something should be changed/fixed at the Fastify level.
> 
> Here what is happening is that the request is reaching the proper `JSON Schema` defined and doing a proper validation by returning `HTTP 400` as the validation failed (the property is missed). As `fastify` doesn't have a way to treat the `spec` headers in a custom manner, here there are two things that can be done:
> 
>     1. Schedule a `preValidation` handle that does the custom check against the `header` so you can reply with `HTTP 411` as desired
> 
>     2. Set a custom error handler through `Server#setErrorHandler` (see [reference](https://www.fastify.io/docs/latest/Reference/Server/#seterrorhandler)), and make a check against the error passed as an argument to the callback handler

Understood.
Is it viable to have embedded into fastify framework specific handlers for `Content-*` that catches if in JSON Schema they are defined and generate errors compliant with the spec?

**Comment by climba03003** [comment]
> Is it viable to have embedded into fastify framework specific handlers for Content-* that catches if in JSON Schema they are defined and generate errors compliant with the spec?

No, since `JSON Schema` may not contain only the `JSON Schema`. It can be a custom validator, for example `Joi`, `Yup`, etc.
Supporting this application logic would be too heavy.

Note that `400` is a valid status code in this case. It is not as specific as `411`, but it is not a wrong status code.

**Comment by Uzlopak** [comment]
If you use fastify-multipart for uploads we could theoretically handle the error in there...

**Comment by ccarcaci** [comment]
Fair enough.
Thank you for your answers.
