### ISSUE TITLE
Incorrect example in default text parser docs

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#4446]
https://github.com/fastify/fastify/blob/df5d94f541c50f690e8beebd143fdb3d861d991b/docs/Reference/Server.md?plain=1#L1673

This is incorrect. It should be `fastify.defaultTextParser` not `fastify.defaultTextParser()`.

**Comment by SaumyaBhushan** [comment]
Hi @climba03003 I would like to work on this.
