### ISSUE TITLE
request is undefined in onSend Hook on post request without body

### ISSUE THREAD

**Issue by SerayaEryn** [fastify/fastify#445]
When you send a post request without body, in the `onSend` Hook `undefined` is being passed as `request`.
I think the request should be defined in this case (Or if that is not possible documented that the `request` may be `undefined`). 

I didn't find the reason for this, but I wrote a test that reproduces the problem. I hope it helps:

```js
'use strict'

const t = require('tap')
const test = t.test
const sget = require('simple-get').concat

test('request should be defined in onSend Hook', t => {
  t.plan(3)
  const fastify = require('..')()

  fastify.register(plugin)
  function plugin (fastify, opts, next) {
    fastify.addHook('onSend', (request, reply, payload, done) => {
      if (!request) {
        reply.code(500)
      }
      done()
    });
    next()
  }
  plugin[Symbol.for('skip-override')] = true

  fastify.post('/', (request, reply) => {
    reply.send(200)
  })
  fastify.listen(0, err => {
    fastify.server.unref()
    t.error(err)
    sget({
      method: 'POST',
      url: 'http://localhost:' + fastify.server.address().port,
      headers: {
        'content-type': 'application/json'
      }
    }, (err, response, body) => {
      t.error(err)
      t.strictEqual(response.statusCode, 422)
    })
  })
})
```

**Comment by delvedor** [comment]
This happens because your are sending an empty body and since the content type parser expects a json by default it will not work.
You should send `{}` or use a [custom content type parser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md).

Related: https://github.com/fastify/fastify/issues/419 https://github.com/fastify/fastify/issues/297

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)

**Comment by SerayaEryn** [comment]
@delvedor I think I am unable to reopen. ;)

I don't want to send an empty body by myself. But since the hooks documentation doesn't mention this case, where the `request` is undefined, other people using the `request` in the `onSend` hook might run into this problem. If the `request` is used in the `onSend` hook without checking if it is present a `TypeError` will be thrown.
At least I expected the `request` to be present in the `onSend` hook all the time after reading the docs.

I looked into the code now and could open a PR to pass a `request` object in this case.

**Comment by mcollina** [comment]
go ahead and open a PR!
