### ISSUE TITLE
JSON-Schema Serialization - response schema $ref to id

### ISSUE THREAD

**Issue by kinothUI** [fastify/fastify#4453]
I was suppsed to reference schema on my routes as following: 
```
...
schema: {
    querystring: { $ref: "toId" }, // works
    response: { $ref: "toOtherId" } // doesn't work
}
```
But since https://github.com/fastify/fastify/blob/f4843b4fd9a35f187c931e7efe61ad17c94fe67a/lib/validation.js#L12 compileSchemasForSerialization function is written in a completly differrent style, it cannot work at all as I thought
This does not corresponde to the docs, which says ref to id should work on both validation and serialization
https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#json-schema-support

Am I missing something?

**Comment by climba03003** [comment]
You need statusCode. The response is a key-value object with `status code` matching `schema`.

```
schema: {
    querystring: { $ref: "toId" }, // works
    response: { 200: { $ref: "toOtherId" } } // doesn't work
}
```
