### ISSUE TITLE
Erro while auto loaded routes

### ISSUE THREAD

**Issue by israeleriston** [fastify/fastify#446]
/Users/tiagomarcos/Documents/projects/fastify-demo/node_modules/fastify/fastify.js:398
        opts.handler.bind(_fastify),
                     ^

TypeError: opts.handler.bind is not a function

 server this context is fastify instance, and others options is extracted using object destructuring, 
  server[method](path, options, handler)

how to proceed with this problem, while using automatic loaded to routes?

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
Can you paste here your code or put it in a gist?

**Comment by israeleriston** [comment]
Fastify is amaiziing!! i'm much happy 


follow gist, i'm sorry, is order files, so inverted
https://gist.github.com/israeleriston/53e46c3bf5132b70c333e38ae7489f63
const registerRoutes = (server, route) => {
  const { method, url } = route
  let options = pick(route, ['name', 'version'])
  const handler = getHandlers(route)

  server[method](url, options, handler)
}

**Comment by jsumners** [comment]
Can we see a route that is causing the problem?

**Comment by israeleriston** [comment]
yeeeah!

const opts = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          ok: { type: 'string' }
        }
      }
    }
  }
}

module.exports = {
  method: 'get',
  url: '/some-route',
  name: 'some-route',
  version: 'v1.0.0',
  handler: (req, reply) => {
    return reply.send({ ok: true })
  },
 opts
}

**Comment by israeleriston** [comment]
yeaah!

https://gist.github.com/israeleriston/e3e3451e0eda51b3c3add553e4c4492b

**Comment by israeleriston** [comment]
my idea is create auto loaded the routes using fastify, i no know the best form e best practices to doing this, all options welcome

**Comment by israeleriston** [comment]
in which part does the arrow function?

**Comment by jsumners** [comment]
Your handler is an arrow function.

**Comment by israeleriston** [comment]
const opts = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          ok: { type: 'string' }
        }
      }
    }
  }
}

const handler = (req, reply) => {
  return reply.send({ ok: true })
}

module.exports = {
  method: 'get',
  url: '/some-route',
  name: 'some-route',
  //   useWrap: true,
  version: 'v1.0.0',
  handler
}

**Comment by israeleriston** [comment]
erro

/Users/tiagomarcos/Documents/projects/fastify-demo/node_modules/fastify/fastify.js:398
        opts.handler.bind(_fastify),
                     ^

TypeError: opts.handler.bind is not a function

**Comment by israeleriston** [comment]
if you can tell me another way to load routes, I would change without problems, the problem is loading route by route

**Comment by jsumners** [comment]
```
const handler = (req, reply) => {
return reply.send({ ok: true })
}

module.exports = {
method: 'get',
url: '/some-route',
name: 'some-route',
version: 'v1.0.0',
handler
}
```

The `handler` in that code is an arrow function. Does it work if it is not an arrow function?

```
const handler = function (req, reply) {
return reply.send({ ok: true })
}

module.exports = {
method: 'get',
url: '/some-route',
name: 'some-route',
version: 'v1.0.0',
handler
}
```

**Comment by israeleriston** [comment]
/Users/tiagomarcos/Documents/projects/fastify-demo/node_modules/fastify/fastify.js:398
        opts.handler.bind(_fastify),
                     ^

TypeError: opts.handler.bind is not a function

sorry, after I went to understand, yes ... even exchanging presents the same error

**Comment by israeleriston** [comment]
is there any other way, so I can do this self loading of the routes? Please, if you have, tell me, what do I change?

**Comment by jsumners** [comment]
I think you need to set a breakpoint at the `server[method](url, options, handler)` line in your `registerRoutes.js` file and then inspect all of the objects. Make sure they are what they should be.

I was attempting to do it myself, but I am not able to completely re-create your environment from your provided gists.

**Comment by israeleriston** [comment]
I'm going to submit this project to github, maybe it's easier for you to take a look and thus recreate the environment

**Comment by israeleriston** [comment]
I'am solved, follow

const registerRoutes = (server, route) => {
  const { method, path } = route
  const opts = pick(route, ['name', 'version'])
  const handlers = getHandlers(route)

  server[method](path, opts, ...handlers)
}

thank you to everyone involved!!
and continuous play in pursuit of assembling a healthy architecture with fastify and testing all its power!!!

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
