### ISSUE TITLE
The introductory documentation is so sketchy that it is impossible to start a complete demo  !

### ISSUE THREAD

**Issue by smil4ever** [fastify/fastify#4461]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I tried to start a demo following the instructions in the Getting Started documentation and had various problems along the way. It took 2 hours and still couldn't run through the demo program. Garbage documentation can affect the interest and motivation of the taster to use it. I wish the getting started documentation was more detailed, or just give a complete minimized demo!

**Comment by jsumners** [comment]
Closing due to abusive tone. Provide constructive feedback.
