### ISSUE TITLE
schema `examples` not working well with openapi examples

### ISSUE THREAD

**Issue by trim21** [fastify/fastify#4464]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

support object examples in `schema.response[200|...].examples`

it raise a error now `FastifyError [Error]: Failed building the serialization schema for GET: /r, due to error schema is invalid: data/examples must be array`

[fastify-swagger](https://github.com/fastify/fastify-swagger) could rewrite array examples to named exampels, but it's better to just write example name by myself

### Motivation

I'm using fastify with https://github.com/fastify/fastify-swagger to generate openapi spec

openapi support a named examples value in `{ [name: string]: {value: unknown, ...}`

https://spec.openapis.org/oas/v3.1.0#fixed-fields-5

eg, 

```ts
{
  example1: {value: ...},
  example2: {value: ...},
}
```
and this become a selector in swagger UI

![image](https://user-images.githubusercontent.com/13553903/206622348-026f0823-74d4-453f-9e0d-8144c9b705ea.png)

But it doesn't pass it's validation of fastify

### Example

```ts
import { fastify } from 'fastify';

const app = fastify();

app.get(
  '/r',
  {
    schema: {
      description: `a description string`,
      operationId: 'auth-login',
      response: {
        200: {
          description: 'Successful response',
          type: 'object',
          properties: {
            name: { type: 'string' },
          },
          headers: {
            'X-RateLimit-Remaining': { type: 'integer' },
            'X-RateLimit-Limit': { type: 'integer' },
            'X-RateLimit-Reset': { type: 'integer' },
          },
          examples: {
            Response1: { value: { name: 'hello' } },
            Response2: { value: { name: 'world' } },
          },
        },
      },
    },
  },
  async function handler(req, res) {
  },
);

await app.listen({ port: 4000 });
```

**Comment by climba03003** [comment]
You are talking about `OpenAPI 3.x`, but in `fastify` it is `JSON Schema`.

`examples` is expected to be an `array` which never would be a `key-value` pairs.
https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=examples#id2

> The examples keyword is a place to provide an array of examples that validate against the schema.

**Comment by Uzlopak** [comment]
Do you get compilation errors in fastify When adding examples key?

**Comment by trim21** [comment]
> Do you get compilation errors in fastify When adding examples key?

Do you mean typing error? I'm using `@sinclair/typebox` and it take `any` as `examples`.

**Comment by Uzlopak** [comment]
Fastify compiles the schemas with ajv. When the schemas are invalid you get a compilation error. 
But if you dont get compilation errors, than how to handle examples is something to be handled in @fastify/swagger and not in fastify core

**Comment by trim21** [comment]
Oh I understand, I create because this issue is raised by fastify and I didn't add swagger plugin here.
