### ISSUE TITLE
Typescript doesn't compile with yarn pnp

### ISSUE THREAD

**Issue by erezarnon** [fastify/fastify#4467]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Node.js version

18.7.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.10

### Description

When using yarn version 3 with pnp, building fastify with typescript gives an error that fastify isn't found. The attached repo was created by exactly following the instructions in https://www.fastify.io/docs/latest/Reference/TypeScript/, except that I replaced npm with yarn.

### Steps to Reproduce

```
git clone https://github.com/erezarnon/fastify-ts-pnp
cd fastify-ts-pnp
yarn
yarn build
```

See the first error:
```
index.ts:1:21 - error TS2307: Cannot find module 'fastify' or its corresponding type declarations.

1 import fastify from 'fastify'
```

### Expected Behavior

It should compile with no errors, just like when using npm

**Comment by climba03003** [comment]
I am closing this issue because it is an issue between `TypeScript` and `Yarn`.

`yarn` required to patch for every single version of `TypeScript` and here is the list of similar issue.
https://github.com/microsoft/TypeScript/issues/50990
https://github.com/yarnpkg/berry/issues/5125
https://github.com/yarnpkg/berry/issues/5115

**Comment by erezarnon** [comment]
It works just fine when I swap out fastify for express

**Comment by climba03003** [comment]
fastify is tested against yarn v1, npm, pnpm.
And yarn v3 is the only one overriding the modules system, so it's fail to resolve the module.

How can a library fix a problem that due to overriding of modules system?


Saying replacing with some other framework do not helps in any case.

**Comment by erezarnon** [comment]
Not trying to cast blame or say whose job it is to fix, and I'm certainly no expert on the internals of the module system. Just saying that if the goal is to have many people using fastify, then it'd be good to have a solution.

For those running into this issue in the future, I was able to solve it by running things through `yarn pnpify`
