### ISSUE TITLE
remove support `reply.send(promise)`

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#448]
I think the more natural way to handle promises would be by returning a promise. So, I think we should remove `reply.send(promise)` before 1.0.0. I think it's just a source of confusion and complexity.

What do you think?

**Comment by delvedor** [comment]
👍

**Comment by jsumners** [comment]
Would the replacement recommendation be?:

```js
fastify.get('/foo', async function (req) {
  return Promise.resole({hello: 'world'})
})
```

**Comment by allevo** [comment]
Good point! 👍

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/458.
