### ISSUE TITLE
ContentTypeParser.remove, does not throw if parser does not exist

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4482]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I find it quite inconsequent, if the remove method of ContentTypeParser in case it is not a string or RegExp throws a FST_ERR_CTP_INVALID_TYPE-error but not an Error if there is no parser matching the contentType. 

Imho the else case of this if-condition should throw an Error
https://github.com/fastify/fastify/blob/897360ad9a01340b45d94f001d8c46aeee22581f/lib/contentTypeParser.js#L152

**Comment by climba03003** [comment]
I am not sure if it should be a bug or something that should fix.
Does anyone really care about if the `content-type` that should be remove is not exist?

**Comment by RajPabnani03** [comment]
@climba03003 Yes it Matters if the content-type is available or through error when the value on removal is not equal to NULL !!!

**Comment by climba03003** [comment]
You say it matters.
But I don't see the later part of the comment show how does it matter.

**Comment by kamilogorek** [comment]
It's really hard to spot the typo in the content type parser that you want to remove, as the input there is a raw string.
