### ISSUE TITLE
How to redefine decorator log?

### ISSUE THREAD

**Issue by polRk** [fastify/fastify#4483]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I am trying to add a custom decorator `log` and get an error `FastifyError: The decorator 'log' has already been added!`

**Comment by polRk** [comment]
For now i don't wanna to log req and res fields.

```
function defaultErrorHandler (error, request, reply) {
  setErrorHeaders(error, reply)
  if (!reply[kReplyHasStatusCode] || reply.statusCode === 200) {
    const statusCode = error.statusCode || error.status
    reply.code(statusCode >= 400 ? statusCode : 500)
  }
  if (reply.statusCode < 500) {
    reply.log.info(
      { res: reply, err: error },
      error && error.message
    )
  } else {
    reply.log.error(
      { req: request, res: reply, err: error },
      error && error.message
    )
  }
  reply.send(error)
}
```

**Comment by mcollina** [comment]
Could you clarify how these two requirements are connected?

You can disable all Fastify default logging with https://www.fastify.io/docs/latest/Reference/Server/#disablerequestlogging.

Note that you shouldn't redecorate the logger, just do: 

```js
app.addHook('onRequest', async (req, reply) => {
  const log = app.log.child(fillMe)
  req.log = log
  reply.log = log
})
```

**Comment by polRk** [comment]
> Could you clarify how these two requirements are connected?

At the moment, fastify passes objects `req` and `res` to `log.info`, I don't want this behavior.

**Comment by polRk** [comment]
In general, I don't want fastify to trigger logging events at all (now it does when errors occur)

**Comment by delvedor** [comment]
You can find everything you need [here](https://www.fastify.io/docs/latest/Reference/Logging/).

**Comment by polRk** [comment]
> You can find everything you need [here](https://www.fastify.io/docs/latest/Reference/Logging/).

I can not redefine decorators app.log, req.log, reply.log :(
I can not turf off fastify error logging (can't remove fn defaultErrorHandler) :(

**Comment by jsumners** [comment]
Supply your own logger and ignore the bits you don't want.

**Comment by polRk** [comment]
> Supply your own logger and ignore the bits you don't want.

I can not redefine decorators app.log, req.log, reply.log :(

**Comment by climba03003** [comment]
> I can not redefine decorators app.log, req.log, reply.log :(

You can by passing to the [`fastify({ logger })`](https://www.fastify.io/docs/latest/Reference/Server/#logger).

**Comment by polRk** [comment]
> > I can not redefine decorators app.log, req.log, reply.log :(
> 
> You can by passing to the [`fastify({ logger })`](https://www.fastify.io/docs/latest/Reference/Server/#logger).

And how ca i by pass that fastify code `defaultErrorHandler`?

**Comment by climba03003** [comment]
It is your logger, that means you can ignore any fields you want, log something you want.

**Comment by polRk** [comment]
The proposed solutions are not suitable due to the strong connectivity of fastify and logger.

I close the thread, because no solution is qualified.
