### ISSUE TITLE
Without file not able to access fields in multipart/form-data type

### ISSUE THREAD

**Issue by vasu-rangpariya-xl** [fastify/fastify#4486]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.6.0

### Node.js version

^16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.1 LTS

### Description

When we create route that accepts data as an multipart/form-data and when we don't pass file/binary in payload we are not able to access fields that is passed in body and also there is some kind of sequence like always we have to pass fields in first and last need to contain binary/file 

### Steps to Reproduce

- create route that accepts multipart/form-data
- try to access the form body with req.file()
- now don't pass any file or binary just only pass fields which contains any type of data like ( string,int..etc ) 
- then try to access that fields in  req.file() / req.body anywhere it is not available

### Expected Behavior

Should be able to access those fields in req.body  although we don't pass any file or binary

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by imbhaskarn** [comment]
Hey @mcollina I would like on this project.

**Comment by mcollina** [comment]
go for it

**Comment by climba03003** [comment]
After looking at this issue again. The behavior is expected since `request.file` will trigger the `body stream` to resume and start parsing.
You are required to use either `request.parts()` or `attachFieldsToBody` if you like automatic process.
