### ISSUE TITLE
Using Fastify with Socket.io in Firefox yields a 404

### ISSUE THREAD

**Issue by oscelest** [fastify/fastify#4493]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11

### Node.js version

19.3

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I'm currently trying out setting up a backend that uses Fastify and Socket.io but I've run into a problem when attempting to reach it through Firefox, and I'm not sure if I've run into a bug or not, or whetever it's actually a problem with Fastify or rather Socket.io or firefox.

The server is a very simple Fastify server produced with the following code:
```
const app = Fastify({logger: true});
const port = +(process.env.SERVER_BACKEND_PORT || 4000);
  
app.addHook("preHandler", (request: FastifyRequest, reply: FastifyReply, done) => {
  reply.header("Access-Control-Allow-Origin", "*");
  done();
});
  
app.ready().then(() => {
  const io = new Server(app.server, {
    cors: {origin: "*"}
  });
    
  io.on("connection", socket => {
    socket.on("ping", () => {
      socket.emit("pong");
    });
  });
});
  
app.listen({port});
```

When I attempt to reach the URL `http://localhost:4000/socket.io/?EIO=4&transport=polling` I'm expecting to see the following message `0{"sid":"[insert generated sid here]","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}` but instead just get a 404 when using Firefox.

Using either Chrome or Edge yields the correct result and attempting to download the file with Powershell or cURL also yields the correct result, so I'm kinda stumped on what's going on and was hoping to find help here.

### Steps to Reproduce

- Host the server
- Visit the polling URL in Firefox

### Expected Behavior

Receive the SID message from Socket.io instead of a 404 error.

**Comment by climba03003** [comment]
My advice is explicitly specify the `host` to `127.0.0.1` or do not use `localhost` for connection.
In windows `localhost` will first be resolved as `IPv6` and `fastify` is started the server in listening both `IPv4` and `IPv6` if you don't explicit set as `127.0.0.1`.

So, you are required to listen on both servers. https://www.fastify.io/docs/latest/Reference/Server/#listen

**Comment by climba03003** [comment]
I have tried with the below code, including a dummy html which cannot reproduce the problem.

```js
const Fastify = require('fastify')
const { Server } = require("socket.io");

const app = Fastify({logger: true});
const port = +(process.env.SERVER_BACKEND_PORT || 4000);

app.get('/', function(request, reply) {
  reply.type('text/html; charset=utf-8').send(`<!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
      <h1>Look at the server log to see if the connection happened</h1>
    </body>
    <script src="/socket.io/socket.io.js"></script>
    <script>
      var socket = io();
    </script>
  </html>`)
})
  
app.addHook("preHandler", (request, reply, done) => {
  reply.header("Access-Control-Allow-Origin", "*");
  done();
});
  
app.ready().then(() => {
  const io = new Server(app.server, {
    cors: {origin: "*"}
  });
    
  io.on("connection", socket => {
    socket.on("ping", () => {
      socket.emit("pong");
    });
  });
});
  
app.listen({ port });
```

![image](https://user-images.githubusercontent.com/23028015/210261049-76fe0291-a574-4265-8ba8-1b0c5edc1b83.png)

**Comment by JoaoOtavioS** [comment]
hey guys, use https://www.npmjs.com/package/fastify-socket.io 👍
