### ISSUE TITLE
New security process

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4494]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Right now we have a security policy that requires creating an issue on Hakone:
https://github.com/fastify/fastify/blob/main/SECURITY.md

By enabling the security reporting from GitHub, we could ease the process:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/11404065/210315439-2943b117-6093-4dc0-aa1b-312786022dd3.png">
GitHub

### Motivation

- Centralize issues
- Involve members
- Improve the process

### Example

I wonder if we must get Open JS foundation's approval to modify the security policy

**Comment by mcollina** [comment]
I think the HackerOne system is still better _right now_, because that's a per-repo setting and we handle our vulns org-wide.

Can we turn that setting on for all our repos in a single click/command?

**Comment by climba03003** [comment]
The only problem would be permission if you use `Github` one. Maybe just configuration problem.
I am inside the `Security Team` but mostly excluded from seeing any new security process (e.g. verify fix).

**Comment by jsumners** [comment]
> I think the HackerOne system is still better _right now_, because that's a per-repo setting and we handle our vulns org-wide.
> 
> Can we turn that setting on for all our repos in a single click/command?

No. https://twitter.com/Kate_Catlin/status/1591216873605304320?s=20&t=bBMqKELxllnrThpJf1gddg

**Comment by mcollina** [comment]
I think that settles it for now, we'll reconsider once that's available.
