### ISSUE TITLE
ContentTypeParser Image regrex failed to capture any image type when router added

### ISSUE THREAD

**Issue by anilkumarum** [fastify/fastify#4495]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11.0

### Node.js version

19.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

linux mint

### Description

I try to add custom parser to parse all image files.
I copy image content parser code from fastify documentation but fail to capture any image format.
This code throw error:
`FastifyError: Unsupported Media Type: image/jpeg\n    at ContentTypeParser.run`.
```js
fastify.addContentTypeParser(/^image\/.*/, { parseAs: "buffer" }, (req, payload, done) => {
	done(null, payload)
});
```

But  when i remove regrex and add hardcoded image format then no error thrown and image parsed successfully. 
This code work:
```js
fastify.addContentTypeParser("image/png", { parseAs: "buffer" }, (req, payload, done) => {
	done(null, payload)
});
```

### Steps to Reproduce

```js
fastify.addContentTypeParser(/^image\/.*/, { parseAs: "buffer" }, (req, payload, done) => {
  done(null, payload);
});
```

### Expected Behavior

I want to capture all image mime type format.
Suggested regrex must work.

**Comment by Uzlopak** [comment]
`image/jpeg\n` . \n looks suspicious

**Comment by climba03003** [comment]
Can you provide the payload you sent to the server? 
It is important to judge whether it is intended or bug.

**Comment by anilkumarum** [comment]
@climba03003 I send blob from client-side. `content-type` auto set by browser based on blob type. 
 I add hook to print headers:
```js
fastify.addHook("onRequest", async (request, reply) => {
	console.log(request.headers);
});
```

request headers:
```js
  connection: 'keep-alive',
  'content-length': '965',
  dnt: '1',
  'content-type': 'image/jpeg',
  accept: '*/*',
  'sec-gpc': '1',
```

**Comment by anilkumarum** [comment]
@Uzlopak i attached request headers. 
`image/jpeg\n` is raw log without pino-pretty

**Comment by climba03003** [comment]
> I send blob from client-side. content-type auto set by browser based on blob type.

I cannot reproduce the problem you describe with the below code. 
Please double check is the `content-type parser` added inside the `encapsulated` context different from your route. 

```js
import Fastify from 'fastify';

const fastify = Fastify();

fastify.addContentTypeParser(/^image\/.*/, { parseAs: "buffer" }, (req, payload, done) => {
	done(null, payload)
});
fastify.post('/', function(request, reply) {
  reply.type(request.headers['content-type']).send(request.body)
})

{
  const { payload, statusCode } = await fastify.inject({
    method: 'POST',
    path: '/',
    payload: 'dummy',
    headers: { "content-type": "image/jpeg" }
  })
  console.log(statusCode, payload)
}
```

**Comment by anilkumarum** [comment]
Fastify throw error only when router added.

fastify common code
```js
import Fastify from "fastify";

const fastify = Fastify();

fastify.addContentTypeParser(/^image\/.*/, { parseAs: "buffer" }, (req, payload, done) => {
	done(null, payload);
});

const { payload, headers, statusCode } = await fastify.inject({
	method: "POST",
	path: "/images/upload",
	payload: "dummy",
	headers: { "content-type": "image/jpeg" },
});
console.log(statusCode, headers["content-type"], payload);
```
this code doesn't throw error
```js
fastify.post('/', function(request, reply) {
  reply.type(request.headers['content-type']).send(request.body)
})
```
But i use router then fastify throw error:
```js
function imgRoutes(fastify, options, done) {
	fastify.post("/upload", uploadImg);

	done();
}
fastify.register(imgRoutes, { prefix: "/images" });

async function uploadImg(request, reply) {
	reply.send(request.headers);
}
```

**Comment by climba03003** [comment]
Although the concept is wrong, but I can reproduce when encapsulation context is created.
