### ISSUE TITLE
a method to set `req.ip` from customized http header

### ISSUE THREAD

**Issue by trim21** [fastify/fastify#4499]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

add a method to read ip from customized http header

### Motivation

I'm using cloudflare as cdn. cloudflare send client ip with http header [`cf-connecting-ip`](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#cf-connecting-ip)

but `proxy-addr` can only read header from `X-Forwarded-*`, I hope there can be a new method to set `req.ip`

### Example

```ts
import Fastify, { FastifyRequest } from 'fastify';

const fastify = Fastify({
  logger: false,
  genReqIp: (req: FastifyRequest): string => {
    const ip = req.headers['cf-connecting-ip'];
    if (ip) {
      return ip;
    }

    return req.connection.remoteAddress ?? '0.0.0.0';
  },
});


fastify.get('/', function (req, reply) {
  reply.send(req.ip);
});


{
  const { statusCode, payload } = await fastify.inject({
    url: '/',
    headers: { 'Cf-Connecting-Ip': '1.2.3.4' },
  });
  console.log(statusCode, payload);
}
```

**Comment by metcoder95** [comment]
You can use https://github.com/pbojinov/request-ip, which already supports `fastify`'s request object.

On the other hand, not sure if it might be a good idea to replace it with `fastify`, it supports a pretty good range of custom IP headers

**Comment by trim21** [comment]
> You can use https://github.com/pbojinov/request-ip, which already supports `fastify`'s request object.
> 
> On the other hand, not sure if it might be a good idea to replace it with `fastify`, it supports a pretty good range of custom IP headers

reading them is pretty easy, but I can't find how to set it to fastify request...

**Comment by metcoder95** [comment]
Currently, it cannot be set as is exposed through a getter function, missing the setter.
A workaround will be to decorate the `request` with a custom property (e.g. `realIp`) to store the value within the request

**Comment by trim21** [comment]
> Currently, it cannot be set as is exposed through a getter function, missing the setter. A workaround will be to decorate the `request` with a custom property (e.g. `realIp`) to store the value within the request

yes, that's what I'm doing now.

**Comment by metcoder95** [comment]
> On the other hand, not sure if it might be a good idea to replace it within `fastify`, it supports a pretty good range of custom IP headers

The only downside is that it does not support the priority of headers, which might be valuable for the `Request#ips` one, so double-checking my thoughts about it.

>yes, that's what I'm doing now.

Rather than a function, might be good to allow customizing the IP gathering in some sort. Maybe allowing not only understanding whether to trust the proxy or not, but also the main header for inferring the IP, and if not fall back into a default one.

Thinking out loud 😅

**Comment by trim21** [comment]
> allow customizing the IP gathering in some sort

yes

**Comment by Uzlopak** [comment]
What would make sense is to extended fastify/forwarded to handle custom headers. Then in fastify/proxy-addr modify to handle the custom headers in proxy-addr. Then in fastify replace again proxy-addr with @fastify/proxy-addr.

**Comment by jsumners** [comment]
I'm not convinced. I think our current implementation follows accepted "standards". Does the `cf-connecting-ip` follow the forward for "[spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)"? Does it represent an array of proxies? Or is it a singular value that has already parsed the array of proxies?

I think we should stick close to the accepted HTTP specs and let users add their own tooling around deviations such as this one.

**Comment by trim21** [comment]
> I'm not convinced. I think our current implementation follows accepted "standards". Does the `cf-connecting-ip` follow the forward for "[spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)"? Does it represent an array of proxies? Or is it a singular value that has already parsed the array of proxies?
> 
> I think we should stick close to the accepted HTTP specs and let users add their own tooling around deviations such as this one.

But `X-Forwarded-For` is just a "de-facto standard", not a spec...

I don't mean to support headers like `cf-connecting-ip` under the hood, I'm hoping to allow user to extract ip by themselves, there are also some proxy using `x-real-ip`.

**Comment by jsumners** [comment]
Right, but we handle it according to that de-facto standard -- https://www.fastify.io/docs/latest/Reference/Server/#trustproxy. How are we to guarantee our feature works if we allow changing of the header name?

**Comment by trim21** [comment]
> Right, but we handle it according to that de-facto standard -- https://www.fastify.io/docs/latest/Reference/Server/#trustproxy. How are we to guarantee our feature works if we allow changing of the header name?

I don't understand your concerning... In my understand this issue suggesting expose a option to tell fastify to not use `proxy-addr` to extract request `ip` and `ips`, not add feature to parse header like `x-real-ip` and `cf-connecting-ip` to `proxy-addr.

**Comment by Eomm** [comment]
You can do that already:

```
const fastify = require('fastify')({ logger: true });

fastify.decorateRequest('ip', {
  getter: function () {
    return this.headers['x-custom'];
  },
});

fastify.get('/', async (request, reply) => {
  return { hello: request.ip };
});

fastify.listen(8080);

// curl http://localhost:8080/ -H 'x-custom:foo'
```

**Comment by trim21** [comment]
> You can do that already:
> 
> ```
> const fastify = require('fastify')({ logger: true });
> 
> fastify.decorateRequest('ip', {
>   getter: function () {
>     return this.headers['x-custom'];
>   },
> });
> 
> fastify.get('/', async (request, reply) => {
>   return { hello: request.ip };
> });
> 
> fastify.listen(8080);
> 
> // curl http://localhost:8080/ -H 'x-custom:foo'
> ```

thanks！

**Comment by jsumners** [comment]
The `trustProxy` setting turns on this function:

https://github.com/fastify/fastify/blob/687459a0664619b843630b2cf9726b42b798c3ca/lib/request.js#L39-L57

Which is invoked by `req.ip`:

https://github.com/fastify/fastify/blob/687459a0664619b843630b2cf9726b42b798c3ca/lib/request.js#L102-L117

Both ultimately look at the `x-forwarded-for` header through the path:

1. https://github.com/jshttp/proxy-addr/blob/1cdd2f78e0fcc23ceae4723e6b837345c2499772/index.js#L57
2. https://github.com/jshttp/forwarded/blob/af3830a175dbe316be3d943f505171c73853eb04/index.js#L30
