### ISSUE TITLE
Error handler has 200 as reply status code instead of 500

### ISSUE THREAD

**Issue by HiiiiD** [fastify/fastify#4501]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11.0

### Node.js version

18.5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

`setErrorHandler(err,req,reply)` returns 200 as `reply.statusCode` instead of 500.
I'd expect that if an API breaks due to unexpected error, the error handler reply status code should be 500.

**This feature has changed from fastify 3 to fastify 4 (just tested it) because on Fastify 3 it correctly returns 500.**

### Steps to Reproduce
```
import fastify from 'fastify';

const app = fastify();

app.setErrorHandler((error, request, response) => {
    console.log(error, error.statusCode, response.statusCode);
    response.status(response.statusCode).send({ error: error.message })
})

app.get('/', (request, reply) => {
    const m = structuredClone(request);
})

await app.listen({ host: '0.0.0.0', port: 8080 })
```
### Expected Behavior

Expected behavior is to have `reply.statusCode` equal to 500 instead of 200

**Comment by HiiiiD** [comment]
Also I've performed a migration from Fastify 3, where it sets the status code to 500, to Fastify 4 that now sets it to 200. Can't find any related change log for it. Am I missing smth?

**Comment by metcoder95** [comment]
The `Reply#statusCode` is always set to `200` on instantiation, and the default error handler set by `fastify` if no function has been provided is the one that sets the `statusCode` to `500`.

By providing a custom error handler it relies to your function to set the `statusCode` desired

**Comment by HiiiiD** [comment]
Okk then, thank you for your clarifications

**Comment by Uzlopak** [comment]
Also if it is a fastify Error you could pass the statusCode through

```js
app.setErrorHandler((error, request, response) => {
    console.log(error, error.statusCode, response.statusCode);
    response.status(error.statusCode || 500).send({ error: error.message })
})
```

**Comment by CalogeroMandracchia** [comment]
I looked into the code and in Fastify V3 `onErrorHook()` calls `handleError()` which always set `500` and then if `reply.context.errorHandler` is defined it also calls the custom function.
In Fastify V4 `buildErrorHandler()` launched at startup checks if a `setErrorHandler()` was defined and if not takes the old `defaultErrorHandler() `from the object `rootErrorHandler`. And when a request arrives `handleError() `calls whatever was set at startup.

So it's not a bug, it was designed for sure like this and I can understand there are less steps so it is faster.
But for all the people migrating to V4 I won't be surprised if they are not happy about it.
I didn't find any mention in the migration [guide](https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/).

It is confusing finding out there was an error but also a `200` code! Maybe the developer simply forgot or there was a bug.
In those case having `handleError()` always set `500` would help.

**Comment by metcoder95** [comment]
>So it's not a bug, it was designed for sure like this and I can understand there are less steps so it is faster.

Was redesigned in here #3261, and noted as `semver-major`, it is well documented but the side-effects on the `statusCode` management were not taken into account.

A documentation change highlighting will be a good idea 🙂

**Comment by metcoder95** [comment]
Nevermind, correcting myself, it is in the documentation:

>The root error handler is Fastify’s generic error handler. This error handler will use the headers and status code in the Error object, if they exist. The headers and status code will not be automatically set if a custom error handler is provided.

See: [Fastify#Errors](https://www.fastify.io/docs/latest/Reference/Errors/#errors-in-fastify-lifecycle-hooks-and-a-custom-error-handler)

**Comment by CalogeroMandracchia** [comment]
So just to be sure we are on the same page: between helping the developer by setting a default 500 and making fastify faster by saving few cpu cycle, we are going with the latter + updating the documentation?

**Comment by CalogeroMandracchia** [comment]
Changing the behavior again is a good point. Whatever we do there are people who are going to complain so there is no solution :/

**Comment by mcollina** [comment]
I don't think we should change the behavior again as we will stumble back into https://github.com/fastify/fastify/issues/2860.

Note that you can always rethrow the error and ultimately it will set a 500 status code. If you handle it, then you need to set the status code correctly.

We should update the docs.
