### ISSUE TITLE
support WHATWG responses

### ISSUE THREAD

**Issue by erfanium** [fastify/fastify#4512]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

as WHATWG fetch APIs (fetch, Request, Response, Headers, ...) have already landed in Node.js +v17, It may a good reason to support them as well.

I know it could be difficult to support both Request and Response everywhere in fastify. but I suggest we can support it step by step.

The first step would be to only support returning WHATWG **response** objects in route handler functions.

### Motivation
Vercel Edge functions, Supabase functions, Cloudflare workers, Deno and bun are using WHATWG APIs.
### Example

```js
import fastify from "fastify"

const app = fastify();

app.route({
  method: "GET",
  url: "/",
  handler() {
    return fetch("https://example-api.com")
  }
})

app.listen({
  port: 3000
})
```

**Comment by mcollina** [comment]
The snippet you have listed seems appealing from a developer experience perspective.
We could support this easily by adding the logic within `reply.send()`, however, don't expect this to be performant at all (sigh).
As things are all of `fetch()` is _significantly_ slower than almost anything else.

I don't think we could ever support `Request`.

**Comment by Uzlopak** [comment]
Is this feature request inspired by bun?

**Comment by erfanium** [comment]
@Uzlopak I saw this usage like 2 years ago from Deno. but It's quite popular today. Vercel Edge functions, Supabase functions, Cloudflare workers, Deno Deploy and also bun are using WHATWG APIs

**Comment by jsumners** [comment]
I don't understand the example. Is this not possible as-is today? Doesn't this example return a `Promise` that either resolves to some payload to send or an error?

**Comment by erfanium** [comment]
@jsumners 
return type of fetch is `Promise<Response>`
it's not a literal serializable object
https://developer.mozilla.org/en-US/docs/Web/API/Response

**Comment by jsumners** [comment]
Sounds like a plugin with a `preSerialization` hook that does inspection and returns the right thing.

**Comment by erfanium** [comment]
@jsumners 
yeah it could be done in plugin-land. but I think it's better for fastify to support this by default. because:
it'
- it's not about third-party APIs
- fastify already have similar features. e.g. you can return ReadableStream from handler.

**Comment by jsumners** [comment]
`ReadableStream` support is a natural fit as one of the primary features of Node.js is handling streams. It's also easy to support; we really only check for the existence of the `.pipe` method on the object to determine that it is stream: https://github.com/fastify/fastify/blob/8ebe376185ebed16627b24c21472e91c44509bb5/lib/reply.js#L145-L175

It seems like supporting this `return fetch('a thing')` will require some more significant inspection. This, as @mcollina stated, is likely to be slow. I think this can at least be proved via a plugin.

**Comment by erfanium** [comment]
@jsumners

> It seems like supporting this return fetch('a thing') will require some more significant inspection. This, as @mcollina stated, is likely to be slow. I think this can at least be proved via a plugin.

are you mean this feature should be implemented via plugin? if yes, so you can close this issue as 'not planned'

**Comment by metcoder95** [comment]
On top of that, I also think that some of the APIs within `node:streams` are not yet ready to work with WHATWG streams. e.g. `streams#finished` does not have support yet for WHATWG streams and fastify heavily depends on it to handle streams as a response to requests.

Though some tricks can be made, not sure if is really worth it given the current constraints and possible performance regressions implications.

But definitely, it is a good idea for a plugin, and maybe revisit once performance improvements and first-class support for them are done within Node first 🙂

**Comment by climba03003** [comment]
> On top of that, I also think that some of the APIs within node:streams are not yet ready to work with WHATWG streams. e.g. streams#finished does not have support yet for WHATWG streams and fastify heavily depends on it to handle streams as a response to requests.

FYI, it is recently added https://github.com/nodejs/node/commit/32254988ba7c0c0a68d8dfbc32430466370bf170

**Comment by metcoder95** [comment]
> > On top of that, I also think that some of the APIs within node:streams are not yet ready to work with WHATWG streams. e.g. streams#finished does not have support yet for WHATWG streams and fastify heavily depends on it to handle streams as a response to requests.
> 
> FYI, it is recently added [nodejs/node@3225498](https://github.com/nodejs/node/commit/32254988ba7c0c0a68d8dfbc32430466370bf170)

Saw it Yesterday, but didn't know how long it was going to take to land it. It seems faster than expected, I'll give it a shot to make some comparisons. Thanks for the hint 🙂

**Comment by erfanium** [comment]
I have made a fastify plugin for this
https://github.com/erfanium/fastify-web-response

@jsumners @climba03003 @metcoder95 
Would you review my code?
I'm not familiar deeply with node/web streams. I have used `Readable.fromWeb(response.body)` to convert `ReadableStream` to `Readable`. `fromWeb` method also takes an option parameter but I'm not sure should i set any config or not

**Comment by metcoder95** [comment]
>I'm not familiar deeply with node/web streams. I have used Readable.fromWeb(response.body) to convert ReadableStream to Readable.

LGTM, but you should have it in mind that the full `WebStreams API` is stills experimental, so might be good to point that out in the documentation.

Is there any reason why you're disabling the serializers? It shouldn't be needed as `fastify` identifies it is a stream and pipes it down to the request. [Ref#L21](https://github.com/erfanium/fastify-web-response/blob/72cb7875fcc2c5a352b8e4bbe15aa1fb9582d1f4/index.js#L21)

>fromWeb method also takes an option parameter but I'm not sure should i set any config or not

No needed 👍

**Comment by erfanium** [comment]
@metcoder95 thanks

> Is there any reason why you're disabling the serializers? It shouldn't be needed as fastify identifies it is a stream and pipes it down to the request. [Ref#L21](https://github.com/erfanium/fastify-web-response/blob/72cb7875fcc2c5a352b8e4bbe15aa1fb9582d1f4/index.js#L21)

it doesn't work without this hack. fastify will json serialize the readable object and. i think that's a bug in fastify.

**Comment by mcollina** [comment]
Why don't you call `reply.serialize(null)`?

**Comment by erfanium** [comment]
@mcollina 
I don't know how `reply.serialize` can help here. if you mean `reply.serializer` then yes, it will work we I use `reply.serializer(noop)` but `reply.serializer(null)` doesn't work.

it's better but the hack is still exist

**Comment by mcollina** [comment]
> it's a better solution but the hack is still exist

Using a public API instead of an undocumented symbol is significantly better.

**Comment by jsumners** [comment]
Looks good to me.

**Comment by mcollina** [comment]
Same! Would you like to open a PR to add it to our ecosystem plugins?

**Comment by metcoder95** [comment]
PR is merged, should we close the issue as well?
