### ISSUE TITLE
Custom logger not work

### ISSUE THREAD

**Issue by jdgjxxchy** [fastify/fastify#4515]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11.0

### Node.js version

19.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5

### Description

I want to use my custom logger as fastify logger. When I read the doc, I found a way to do so but it does not work.
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/44478385/212479395-a52d5682-0145-4c1f-b7da-5ec448ac2fd9.png">

I read the source code and find out that whatever logger instance I set to logger prop, `createLogger` function will always return a pino logger instance instead of my validated logger instance
<img width="888" alt="image" src="https://user-images.githubusercontent.com/44478385/212479510-95222e3e-fcc6-443f-a2e5-790ace54f782.png">

### Steps to Reproduce

```
import { Logger } from 'tslog'
import type { ILogObjMeta, ISettingsParam } from 'tslog/dist/types/BaseLogger'
import fastify from 'fastify'

class CustomLogger<LogObj> extends Logger<LogObj> {
  constructor(settings?: ISettingsParam<LogObj>, logObj?: LogObj) {
    super(settings, logObj)
  }

  silent(...args: unknown[]): (LogObj & ILogObjMeta) | undefined {
    return this.silly(...args)
  }

  level: string
}

const logger = new CustomLogger({
  type: 'pretty',
})
logger.level = 'info'
console.log(logger)
const server = fastify({ logger })
console.log(server.log)
```

Use `npm install fastify tslog` to install dependencies

### Expected Behavior

I expect that when I use a custom logger instance, fastify will use my logger to log

**Comment by mcollina** [comment]
What error are you getting?

**Comment by haim-rubin** [comment]
As I understand there's no error just the custom logger doesn't override the default one

**Comment by climba03003** [comment]
> As I understand there's no error. just the custom logger doesn't override the default one

From what I can see, your logger will go through the last condition but not the first one. Since, you are missing `.child` method.

Even if it go through the `createPinoLogger`, it doesn't override your logger. But create a [new one using the `.child` method](https://github.com/fastify/fastify/blob/8ebe376185ebed16627b24c21472e91c44509bb5/lib/logger.js#L31-L40).

**Comment by climba03003** [comment]
I am closing this issue because there is no bug exist.
You are missing the required function `child` and that's why it doesn't work.

**Comment by jdgjxxchy** [comment]
> 

Thank you for your solution. But I found that typescript does not throw error even if I missed `child` function. Maybe It can be solved by add `child` to `BaseLogger`.
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/44478385/212557990-e93b3392-33ca-49b7-bb1b-bc6e772f1c3e.png">
