### ISSUE TITLE
Support wildcards anywhere in the route

### ISSUE THREAD

**Issue by zetti-caletti** [fastify/fastify#4519]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support wildcards anywhere in the route and not only in the end.

### Motivation

Using NestJS. When using it with express the following route works:
(*)\_(:targetWidth)\_:originalExtension.:extension

When using NestJS mit fastify it doesn't work. I get following error:
Error: Wildcard must be the last character in the route

**Comment by climba03003** [comment]
> (*)_(:targetWidth)_:originalExtension.:extension

I am not sure what is the path you would like to achieve, but `wildcard` set in the middle of route is problematic and never been able to handle.
See https://github.com/delvedor/find-my-way/issues/202#issuecomment-1108498641

If you have any more question, you may raise an issue to `find-my-way`.
