### ISSUE TITLE
Errors in core, create with @fastify/errors or use native Errors 

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4521]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Well in #4520 there are basically two opinions about errors:

- all thrown errors should be created by @fastify/errors 
- errors which are exposed at runtime should be generated by @fastify/errors ans errors which are thrown at startup should be native errors. 

For the first you could argue that alot of errors are already transformed and it was always the target to replace all native Errors.
For the latter you could argue, that in fastify.js we throw native Errors because the input objects are already invalid. 

Can we have a clarification, a clarifying discussion or can i have a link to place were this was already discussed and/or clarified, please?

**Comment by metcoder95** [comment]
I might be missing the source of truth for this but at the moment of working on #2954 and #3106, it was _somehow agreed_ to use `@fastify/errors` instead of native errors.
I also within that work made adjustments to some of them that were relatively close to the scope of the PR, but not all of them.

**Adding my two cents**, I would say that it can be beneficial to standardise all of them into `@fastify/errors`, so the error codes that the errors use are uniform and well documented in the documentation, so developers can easily see the error code, and go into the documentation for a better understanding of the problem

**Comment by mcollina** [comment]
> all thrown errors should be created by @fastify/errors

This is the intent. We can even wrap 3rd party errors using the `cause` property now.

**Comment by metcoder95** [comment]
I took the time to aggregate the current native errors within the codebase and listed them here. Some of them are quite trivial, but others might require maybe some more elaboration and agreement 🙂 

- [ ] `lib/contentTypeParser`
	- [#L315](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/contentTypeParser.js#L315)
	- [#L355](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/contentTypeParser.js#L341)
- [ ] `lib/context`
	- [#L107](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/context.js#L107) - This might not be required, or will need deeper chat as is made to format the errors given by the validation. As well, we allow to submit of custom formatters that should return an `Error` instance (maybe just enforce a specific shape to be returned?).
- [ ] `lib/fourOhFour`
	- [#L181](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/fourOhFour.js#L181) - Similar as per context. Here might be good to replace it just to indicate the error is generated from Fastify itself.
- [ ] `lib/hooks`
	- [#L53](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/hooks.js#L53)
- [ ] `lib/pluginUtils`
	- [#L95](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/pluginUtils.js#L95)
- [ ] `lib/route`
	- [#L134-L142](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/route.js#L134-L142)
	- [#L187-L193](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/route.js#L187-L193)
	- [#L501-L507](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/route.js#L501-L507)
	- [#L513](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/route.js#L513)
- [ ] `lib/validation`
	- [#L22](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/lib/validation.js#L22)
- [ ] `fastify`
	- [#L92-L102](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L92-L102)
	- [#L119-L124](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L119-L124)
	- [#L159](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L159) - This might be subject to be wrapped with a under a `reason` prop.
	- [#L466](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L466) - Maybe `FST_ERR_REOPENED_SERVER` can be open to be more general.
	- [#L482](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L482) - Similar as previous one
	- [#L769](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L769)
	- [#L781-L785](https://github.com/fastify/fastify/blob/46a6d1fe6d3f99378353de4e7aa54c58c17822e9/fastify.js#L781-L785)

These are the ones that I could identify, please edit the comment if I missed some more.
Might be good to also label the issue as `good first issue`?

**Comment by alainrk** [comment]
Hi! I have tried to write down a PR addressing this issue https://github.com/fastify/fastify/pull/4554.
It's a while I'm not in the ecosystem, so every hint/help/suggestion is appreciated!

**Comment by Uzlopak** [comment]
I guess I can close this as #4554 got merged.
