### ISSUE TITLE
Missing types for the fastifyInstance.addresses() method

### ISSUE THREAD

**Issue by Baptiste-Garcin** [fastify/fastify#4523]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Node.js version

18.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0

### Description

The `.addresses()` server method is not present in the types for the fastify instance but this method is present in [the documentation](https://www.fastify.io/docs/latest/Reference/Server/#addresses) and in the instance.

### Steps to Reproduce

Simply create a `fastify` instance and call `.addresses()`

```typescript
import fastify from 'fastify';

const fastifyInstance = fastify();
const addresses = fastifyInstance.addresses();
//  Property 'addresses' does not exist on type 'FastifyInstance  & PromiseLike  >'.
```

The tsconfig.json I use:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

### Expected Behavior

The `fastifyInstance.addresses()` method should be in the `FastifyInstance` type.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
