### ISSUE TITLE
Done is not a method

### ISSUE THREAD

**Issue by RjManhas** [fastify/fastify#4525]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

0

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

22h2

### Description

Im trying to stop my custom plugin and i get this rid error even though it should work

### Steps to Reproduce

`import mongoose from 'mongoose';
import Fastify, {FastifyInstance, FastifyError} from 'fastify'

import fp from'fastify-plugin';
export = (fastify: FastifyInstance,  done: (err?: FastifyError) => void) => {
    
    mongoose.set('strictQuery', false);

    const url: string = "db link";
    mongoose.connect(url, {dbName:"artaxnetwork"}, (err) => {
        if (err) {
            fastify.log.info(err.message);
            process.exit() 
        } else {
            fastify.log.info(`Connection established to mongodb on url ${url}`);
        }
    }); 

    done();
    
    
}

`

### Expected Behavior

to just run the done method

**Comment by mcollina** [comment]
The signature for that is: `app, opts, done`
