### ISSUE TITLE
Flush log output needed, when fastify closes

### ISSUE THREAD

**Issue by Farnsi** [fastify/fastify#4526]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11.0

### Node.js version

18.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.10

### Description

When you log with pretty-print in dev/test mode, like in your (view your [example](https://www.fastify.io/docs/latest/Reference/Logging/), the log will not be visible, if the test end sand `fastify.close()`.

### Steps to Reproduce

Create a fastify app, without a server and use it in e.g. vitest test.

fastify logger conf

```js
{
  // logger: pino({}, require('pino-pretty')({ sync: true })), // <--- this will do the job
  logger: {
    level: 'trace',
    transport: {
      target: 'pino-pretty',
      options: {
        ignore: 'pid,hostname',
        translateTime: 'HH:MM:ss Z',
        sync: true, // <-- doesn't change anything
      },
    },
  },
}
```

Without an await timeout in the test, some logs will not be visible.

### Expected Behavior

Flush output all log, if the app closes, or change the logger example to

```js
  logger: pino({}, require('pino-pretty')({ sync: true })),
```

**Comment by climba03003** [comment]
`transport` is using a worker to write the log.
Putting `sync` or `async` has no effect at all, since the main-thread is exited. The `worker` will be terminated immediately.

**Comment by mcollina** [comment]
This should work out of the box. Could you include an example to repro?

**Comment by Farnsi** [comment]
Example

```js
import Fastify from 'fastify'
import pino from 'pino'
import pinoPretty from 'pino-pretty'

const app = Fastify({
  // logger: pino({}, pinoPretty({ sync: true })), // <--- this will do the job
  logger: {
    level: 'trace',
    transport: {
      target: 'pino-pretty',
      options: {
        ignore: 'pid,hostname',
        translateTime: 'HH:MM:ss Z',
        sync: true, // <-- doesn't change anything
      },
    },
  },
})

app.log.info('a')
app.log.info({ x: 1 }, 'b')
app.log.info('c', 'd')

await app.close()
```

**Comment by mcollina** [comment]
I guess it's a problem in how vitest set up their environments. It's possible we should do something or they have a bug.

Could you please create a repository to reproduce your problem?

**Comment by Farnsi** [comment]
A better example that shows the problem:

```js
import Fastify from 'fastify'
import pino from 'pino'
import pinoPretty from 'pino-pretty'

async function build() {
  const app = Fastify({
    // logger: pino({}, pinoPretty({ sync: true })), // <--- this will do the job
    logger: {
      level: 'trace',
      transport: {
        target: 'pino-pretty',
        options: {
          ignore: 'pid,hostname',
          translateTime: 'HH:MM:ss Z',
          sync: true,
        },
      },
    },
  })

  app.log.info('Hello world')

  return app
}

async function run() {
  console.log('run')
  const app = await build()
  await app.close()
  console.log('closed')
}

await run()
```

Output is:

```
run
closed
done
[09:52:27 UTC] INFO: Hello world                   <--- in test environment this will not be visible
```

Enable logger `logger: pino({}, pinoPretty({ sync: true })), // <--- this will do the job`
Output is:

```
run
[10:53:04.601] INFO (10750): Hello world
closed
done
```

The first example causes the problem within a test environment, e.g. vitest surpresses the output.

**Comment by mcollina** [comment]
I _still_ don't see any vitest in your example. Please create a repository to reproduce.

> The first example causes the problem within a test environment, e.g. vitest surpresses the output.

It's likely a problem in vitest. Depending on what they do, it might be possible to deal with it in pino or not. In case I would file a bug there. _Please include a reproduction_.

> How can we detect, if fastify is really closed and the log is flushed?

Currently the logs do not need to be flushed. I think you can call `app.log.stream.flushSync()` to get them flushed yourself.

**Comment by Farnsi** [comment]
My last example is without vitest, vanilla node app.
It demonstrates, that the logger, used as stream argument, logs in the correct order, it is synced.
As transport argument, the log output will be written at the end, not synced.

That vitest cut off the not synced output is another problem of vitest.
In production no problem, in test driven development anoying.

But i close it here, i think the problem is unsynced transport and that is an issue of pino itself and not of fastify.
