### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by arthurfiorette** [fastify/fastify#4528]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4

### Plugin version

1.x.x

### Node.js version

v16.14.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

WSL

### Description

The PR #2691 introduced the [`getSchemaCompiler`](https://github.com/fastify/fastify/pull/2691/files#diff-e5866ff20d3d7c44302e5bf2096c0c2112e6e8de8e41c0f0df9dbf7146f4ba71R685) function to support error serialization according to what we have in the schemas. The problem is that in #4264 they added [`contentType`](https://github.com/fastify/fastify/pull/4264/files#diff-47b0948ab224d4db8f374686960e631b9a6497c073ac72097afb05d8ba130c31R157) parameter to it and forgot to include it [here](https://github.com/fastify/fastify/blob/d34f81bfa01842432a4eb06da25fd83c7b30742d/lib/error-handler.js#L99). Which is leading to a `Cannot read properties of undefined (reading 'split')` error [here](https://github.com/fastify/fastify/blob/d34f81bfa01842432a4eb06da25fd83c7b30742d/lib/schemas.js#L188).

### Steps to Reproduce

I'm creating a step repo, but the description should have been clear enough

### Expected Behavior

Probably treat the `contentType` parameter as optional.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by salesh** [comment]
Please correct me if I am wrong in understanding the code

[1] case https://github.com/fastify/fastify/blob/90fb718ea8239e59b3abdf6906fb82554d8cc0db/lib/error-handler.js#L33


We can use there `reply[kReplyHeaders]['content-type'])` ?

```diff
-const serializerFn = getSchemaSerializer(reply[kRouteContext], statusCode) 
+const serializerFn = getSchemaSerializer(reply[kRouteContext], statusCode, reply[kReplyHeaders]['content-type'])
```

[2] case https://github.com/fastify/fastify/blob/90fb718ea8239e59b3abdf6906fb82554d8cc0db/lib/error-handler.js#L60

deleting will happen before so contentType will be `undefined` https://github.com/fastify/fastify/blob/90fb718ea8239e59b3abdf6906fb82554d8cc0db/lib/error-handler.js#L53

For this one in https://github.com/fastify/fastify/blob/68914519a3fd65ce65ba8db8962940eecf7f0fc8/lib/schemas.js#L159
change is
```diff
-  if (!responseSchemaDef) {
-    return false
-  }
+ if (!responseSchemaDef || !contentType) {
+   return false
+ }
```

**Comment by mcollina** [comment]
cc @Eomm

**Comment by kamilogorek** [comment]
Closed in https://github.com/fastify/fastify/pull/4531

**Comment by Uzlopak** [comment]
I take your word for it ;)
