### ISSUE TITLE
Fastify is excellent 2

### ISSUE THREAD

**Issue by tj-commits** [fastify/fastify#4529]
No issue here, just: I love it. Fastify is awesome! I totally agree with the pinned issue.

**Comment by Uzlopak** [comment]
Closing as it is no issue ;)

**Comment by tj-commits** [comment]
@Uzlopak why? this alr exists

**Comment by Uzlopak** [comment]
Platforms like npm keep track of open issues. Other pages like snyk determine the health of projects/npm packages also on the open issues counter.
See https://snyk.io/advisor/npm-package/fastify

So basically by opening non-issues or keeping non-issues open can reduce the calculate quality/project health. And tbh we have already a "fastify is excellent" issue, which you also commented. So I really dont see a necessity for this issue to be open.
