### ISSUE TITLE
onTimeout hook not triggering on request timeout

### ISSUE THREAD

**Issue by OppoOskar** [fastify/fastify#4532]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Node.js version

16.15.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 36

### Description

onTimeout hook not triggering as expected. I made a simple test-case described below which explains the issue.

When setting `requestTimeout` and letting the request take longer than the set time, the `timeout` event is not triggered. Nodes own `close` is triggered as soon as the timeout actually happens and the fastify `onSend` is triggered when the request has actually completed (by that time the client has already gotten an error).

When the timeout happend the client receives the response: `{"error":"Bad Request","message":"Client Error","statusCode":400}`. Which feels wrong as the client actually didn't send a bad request, the server was just to slow to deal with it.

### Steps to Reproduce

```
// CommonJs
const fastify = require("fastify")({
    logger: true,
    requestTimeout: 10 * 1000,
});

const __sleep = async (seconds) => {
    return new Promise((resolve) => setTimeout(resolve, seconds * 1000));
};

let requestStarted;

const getSecondsSinceRequestStarted = () => {
    return (new Date(Date.now())).getSeconds()-requestStarted.getSeconds();
}


fastify.get("/", async (request, reply) => {
    requestStarted = new Date(Date.now());
    console.log(getSecondsSinceRequestStarted(),"s : Request recieved");
    request.raw.on("close", (data) => {
        console.log(getSecondsSinceRequestStarted(),"s : node event close");
    });
    await __sleep(20); // Sleep for 20 seconds to trigger 10second timeout.
    return { hello: "world" };
});

fastify.addHook("onError", async () => {
    console.log(getSecondsSinceRequestStarted(),"s : onError");
});
fastify.addHook("onResponse", async () => {
    console.log(getSecondsSinceRequestStarted(),"s : onResponse");
});
fastify.addHook("onSend", async (data, test) => {
    console.log(getSecondsSinceRequestStarted(),"s : onSend");
});
fastify.addHook("onTimeout", async () => {
    console.log(getSecondsSinceRequestStarted(),"s : onTimeout");
});

const start = async () => {
    try {
        await fastify.listen({ port: 1111 });
    } catch (err) {
        fastify.log.error(err);
        process.exit(1);
    }
};
start();

```

StdOut:
```
0 s : Request recieved
10 s : node event close
20 s : onSend
```

Response to client:
```
{"error":"Bad Request","message":"Client Error","statusCode":400}
```

Response headers:

```
Content-Length:  65
Content-Type:  application/json
```

### Expected Behavior

Expected behavior:
* onTimeout event should trigger at the same time as node event close triggers.
* Client response should not be error 400(Bad request), rather 408(Request timeout)

**Comment by climba03003** [comment]
It should trigger on `connectionTimeout` not `requestTimeout`.

https://github.com/fastify/fastify/blob/842dc1379d4f664c0c151fc0e27faeff03ed7760/docs/Reference/Hooks.md?plain=1#L265-L268
