### ISSUE TITLE
Performance regression with fastify.head method

### ISSUE THREAD

**Issue by 7rulnik** [fastify/fastify#4533]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.1.0

### Stopped working in version

4.2.0

### Node.js version

18.12.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0

### 💥 Regression Report

After merging https://github.com/fastify/fastify/pull/4052 `fastify.head` method takes a much more time.
Previously it took less than 1ms, after this PR it takes 50+ ms.

We are using this method there https://github.com/fastify/fastify-static/blob/master/index.js#L352-L354 and with a large amount of files, it takes a lot of time to start the server.

### Steps to Reproduce

You can just use the console.time around https://github.com/fastify/fastify-static/blob/master/index.js#L352-L354

```js
console.time('fastify head')
fastify.head(route, routeOpts, function (req, reply) {
    pumpSendToReply(req, reply, '/' + file, rootPath)
})
console.timeEnd('fastify head')
```

### Expected Behavior

I think the performance regression of adding a route should be much lower in this case

**Comment by metcoder95** [comment]
I think the compromise made on startup with the change is a good tradeoff if we look for consistency in the behavior of the framework (in this case not calling the `onRoute` hook while silently registering the sibling `HEAD` route, or removing the `HEAD` route at all given a manual registered one).

Doing a quick assessment, I'm assuming the [removal/check](https://github.com/fastify/fastify/pull/4052/files#diff-cf6996cafd1df0bc168a5c5f3a7470f11fc3aea9f908091d5dd6be2e7b30a2c3R258) of the silent sibling `HEAD` route might be the culprit of the regression, but still believe is a good tradeoff for consistency.

But happy to hear more thoughts about it 🙂

**Comment by Uzlopak** [comment]
I can confirm this performance bottleneck. You also need the wildcard option set to false.

You can basically reproduce it with this: 

```js
'use strict'

const path = require('path')

const fastify = require('fastify')({ logger: { level: 'trace' } })

fastify
  .register(require('..'), {
    // go crazy and expose big fat node_modules folder.
    root: path.join(__dirname, '../node_modules'),

    wildcard: false,
  })
  .listen({ port: 3000 }, err => {
    if (err) throw err
  })
```

Setting wildcard to true avoids that issue and the server spins up immediatly. Also the memory footprint is horrible with wildcards: false as each file gets its own route.

**Comment by 7rulnik** [comment]
I guess it is worth mentioning that originally I faced it with https://github.com/nestjs/serve-static/blob/master/lib/loaders/fastify.loader.ts#LL33C38-L33C38

So maybe it makes sense to fix usage in nestjs

**Comment by climba03003** [comment]
I believe the calculation time exist anyway. It looks like there is a regression because the works moved from `delayed` to `instant`.
Which means the most heavy task is not calculated before is calculated currently.

When you check with the overall time, it should be large difference.

```mjs
import Static from '@fastify/static'
import Fastify41 from 'fastify41'
import Fastify42 from 'fastify42'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

console.time('fastify 4.1.0 warmup')
const fastify41 = Fastify41()
fastify41.register(Static, {
  root: join(dirname(fileURLToPath(import.meta.url)), 'node_modules'),
  wildcard: false
})
await fastify41.ready()
console.timeEnd('fastify 4.1.0 warmup')

console.time('fastify 4.2.0 warmup')
const fastify42 = Fastify42()
fastify42.register(Static, {
  root: join(dirname(fileURLToPath(import.meta.url)), 'node_modules'),
  wildcard: false
})
await fastify42.ready()
console.timeEnd('fastify 4.2.0 warmup')
```

**Comment by mcollina** [comment]
I think we can speed wildcard up quite a bit by processing the files when they are ready and not all at once.

**Comment by Uzlopak** [comment]
Tbh, the wildcard option in fastify-static has the wrong name and behavour. 

I quote:
----

#### `wildcard`

Default: `true`

If set to `true`, `@fastify/static` adds a wildcard route to serve files.
If set to `false`, `@fastify/static` globs the filesystem for all defined
files in the served folder (`${root}/**/**`), and just creates the routes needed for
those and it will not serve the newly added file on the filesystem.

The default options of https://www.npmjs.com/package/glob are applied
for getting the file list.

This option cannot be set to `false` with `redirect` set to `true` on a server
with `ignoreTrailingSlash` set to `true`.

----

If I set wildcard false, than potentially a gazillion routes are added. But the documentatin says: `it will not serve the newly added file on the filesystem.`. So it sounds more like a "only existing files at start are supplied by wildcard false. But what if I delete the file after start? I guess you get 500 Internal Server Error but I would expect 404 Not found. 

So what is the purpose of the wildcard false option? 
Maybe we should not allow the wildcard false option anyway...

**Comment by mcollina** [comment]
> I guess you get 500 Internal Server Error but I would expect 404 Not found.

If this is the behavior, we can fix handle it and return a 404 instead. It's not hard. Have y got a reproduction?

> So what is the purpose of the wildcard false option?

There are valid cases for _not_ specifying a wildcard, most specifically if you are developing an SPA and you want everything to be redirected to the same entry route.

**Comment by mcollina** [comment]
I'm ok to change the name of the option.

**Comment by mcollina** [comment]
I have investigated this problem a bit.
The major performance hit is done in https://github.com/delvedor/find-my-way/blob/main/index.js#L140. More specifically, that function is `O(routeLength^3)`, and this overall operation is `O(files*routeLength^3)`. TL;DR this is going to be _very_ slow as we are creating so many routes.
