### ISSUE TITLE
No request hook triggered on closed socket

### ISSUE THREAD

**Issue by OppoOskar** [fastify/fastify#4534]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Node.js version

16.15.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 36

### Description

No error/timeout hook is triggered if socket is closed. 

When intentionally killing the socket of a request no fastify request hook (other than onSend) is triggered.

### Basic server, logging when hooks are triggered
```
// CommonJs
const fastify = require("fastify")({
    logger: true,
});

let requestStarted;

const getSecondsSinceRequestStarted = () => {
    return (new Date(Date.now())).getSeconds()-requestStarted.getSeconds();
}

fastify.get("/", async (request, reply) => {
    requestStarted = new Date(Date.now());
    console.log(getSecondsSinceRequestStarted(),"s : Request recieved");
    request.raw.on("close", (data) => {
        console.log(getSecondsSinceRequestStarted(),"s : node event close");
    });
    await new Promise((resolve) => setTimeout(resolve, 5 * 1000));
    return { hello: "world" };
});

fastify.addHook("onError", async () => {
    console.log(getSecondsSinceRequestStarted(),"s : onError");
});
fastify.addHook("onResponse", async () => {
    console.log(getSecondsSinceRequestStarted(),"s : onResponse");
});
fastify.addHook("onSend", async (data, test) => {
    console.log(getSecondsSinceRequestStarted(),"s : onSend");
});
fastify.addHook("onTimeout", async () => {
    console.log(getSecondsSinceRequestStarted(),"s : onTimeout");
});

const start = async () => {
    try {
        await fastify.listen({ port: 1111 });
    } catch (err) {
        fastify.log.error(err);
        process.exit(1);
    }
};
start();
```

### Seperate small script intentionally killing the socket before request is finsihed
```
const http = require("http");

const start = async () => {
    const res = http.get({ hostname: "localhost", port: 1111, path: "/" });
    await new Promise((resolve) => setTimeout(resolve, 1 * 1000));  
    console.log("Destroying socket");
    res.destroy();
}

start();
```

### Stdout of fastify server
```
0 s : Request recieved
1 s : node event close
5 s : onSend
```

### Expected Behavior

Some request hook other than `onSend` triggering.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
I believe this issue want us to implement something on https://github.com/fastify/fastify/blob/main/docs/Guides/Detecting-When-Clients-Abort.md

But, I doesn't see a reason to do so. 
From the use-case a imagine, it would be used to terminate the going resources (e.g. Database). But, it is dangerous in terminating in the middle and create a lot more problem on the cleanup process if someone is not familiar enough.
When the socket is aborted, you can't even return anything useful to the client.

Moreover, you cannot provide a reliable way to detect what you want.

**Comment by OppoOskar** [comment]
In my use-case files are created when a request is received and always need to be cleared once the request is finished. However I cannot clear them onSend (which is the only hook triggered at the moment) since I if the request isn't aborted the files should be send to the user and cleared afterwards.

The current workaround I'm using is decorating the request with aborted if the  node endpoint "close" event is triggered and only if the decorated  request.aborted is true, clear the files in the "onSend" hook. 

Otherwise files are cleared in in the "onError", "onTimeout" or "onResponse" hooks.

But its really important that files always be cleared.

**Comment by mcollina** [comment]
I would recommend against that approach, because a process crash can happen for unpredictable reasons and you'd have leftover files everywhere.

**Comment by OppoOskar** [comment]
Agreed in normal cirumstances but a process crash is not really a concern in this case since the files are always saved in a mounted tmpfs volume in a docker container. 

So if the process crashes the container restarts and all files are automatically cleared and will start up with an empty folder.

I am only concerned with files not cleared properly on a request abort/finish.

**Comment by metcoder95** [comment]
Just curious, why not clear the file that belongs to a given request within the main handler?

If if strictly required, it might add a smaller overhead on the overall latency of the request, but if it is part of the critical path to clean up the files, it should belong to the request handler, to avoid nondeterministic scenarios like the one you described.
