### ISSUE TITLE
requestTimeout returns 400 "Bad Client" on request timeout

### ISSUE THREAD

**Issue by OppoOskar** [fastify/fastify#4535]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Node.js version

16.15.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 36

### Description

When requestTimeout is set on fastify instance and a request is timed out, error 400 "Bad Client" is automaticly sent to client.

### Steps to Reproduce

Set requestTimeout to something low on a fastify instance and make a simple get endpoint which sleeps for a while then returns.

### Example fastify instance
```
// CommonJs
const fastify = require("fastify")({
    logger: true,
    requestTimeout: 2
});

fastify.get("/", async (request, reply) => {
    await new Promise((resolve) => setTimeout(resolve, 5 * 1000));
    return { hello: "world" };
});

const start = async () => {
    try {
        await fastify.listen({ port: 1111 });
    } catch (err) {
        fastify.log.error(err);
        process.exit(1);
    }
};
start();
```

###  Endpoint response:
```
{"error":"Bad Request","message":"Client Error","statusCode":400}
```

### Expected Behavior

Expected error 408 (Request Timeout).

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Uzlopak** [comment]
Here a failing unit test.

Strangely: Node 14 and Node 16 return a 400 Bad Request Error. Node 18 returns 200

So there seems to be bigger issue under the hood?

```js
'use strict'

const { test } = require('tap')
const Fastify = require('..')
const sget = require('simple-get').concat

test('requestTimeout should return 408', t => {
  t.plan(3)

  const fastify = Fastify({ requestTimeout: 10 })
  fastify.get('/', async function (req, reply) {
    await new Promise(resolve => setTimeout(resolve, 100))
    return reply.send({ hello: 'world' })
  })

  fastify.listen({ port: 0 }, err => {
    t.error(err)
    t.teardown(() => { fastify.close() })

    sget({
      method: 'GET',
      url: 'http://localhost:' + fastify.server.address().port
    }, (err, response, body) => {
      t.error(err)
      t.equal(response.statusCode, 408)
    })
  })
})

```

**Comment by climba03003** [comment]
> So there seems to be bigger issue under the hood?

It depends on how fast to receive the request. 
If you want a reliable one, I suggest to use `POST` with large payload.

**Comment by mcollina** [comment]
> Here a failing unit test.
> 
> 
> 
> Strangely: Node 14 and Node 16 return a 400 Bad Request Error. Node 18 returns 200
> 
> 
> 
> So there seems to be bigger issue under the hood?
> 
> 
> 
> ```js
> 
> 'use strict'
> 
> 
> 
> const { test } = require('tap')
> 
> const Fastify = require('..')
> 
> const sget = require('simple-get').concat
> 
> 
> 
> test('requestTimeout should return 408', t => {
> 
>   t.plan(3)
> 
> 
> 
>   const fastify = Fastify({ requestTimeout: 10 })
> 
>   fastify.get('/', async function (req, reply) {
> 
>     await new Promise(resolve => setTimeout(resolve, 100))
> 
>     return reply.send({ hello: 'world' })
> 
>   })
> 
> 
> 
>   fastify.listen({ port: 0 }, err => {
> 
>     t.error(err)
> 
>     t.teardown(() => { fastify.close() })
> 
> 
> 
>     sget({
> 
>       method: 'GET',
> 
>       url: 'http://localhost:' + fastify.server.address().port
> 
>     }, (err, response, body) => {
> 
>       t.error(err)
> 
>       t.equal(response.statusCode, 408)
> 
>     })
> 
>   })
> 
> })
> 
> 
> 
> ```

This is expected. We changed this in node.js core, watch this: https://m.youtube.com/watch?v=_rFz0PeKduc.

**Comment by Uzlopak** [comment]
Well. I just try to have a unit test.

Cant even get it done with a slow loris attack...

```js
'use strict'

const { test } = require('tap')
const Fastify = require('..')

test('requestTimeout should be resilient against a slow loris attack and return 408', t => {
  t.plan(2)

  const fastify = Fastify({ requestTimeout: 1000 })
  fastify.get('/', function (req, reply) {
    reply.send({ hello: 'world' })
  })
  let socket
  let intervalId

  fastify.listen({ port: 0 }, err => {
    t.error(err)
    t.teardown(() => {
      fastify.close()
      socket.destroy()
      clearInterval(intervalId)
    })

    const {
      address: host,
      port
    } = fastify.server.address()

    socket = require('net').connect({ port, host }, () => {
      socket.write(`GET / HTTP/1.1\r\n`);
      socket.write(`Host: ${host}:${port}\r\n`);
      socket.write('Accept: */*\r\n');
      socket.write(
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36\r\n"
      );

      intervalId = setInterval(() => {
        console.log('KeepAlive')
        socket.write(`KeepAlive: ${Math.random() * 1000}\r\n`);
      }, 500);
    });

    socket.setTimeout(0);

    socket.on('timeout', () => {
      console.log('timeout')
    })
    socket.on('data', (data) => {
      const result = data.toString()
      console.log(result)
      t.ok(result.indexOf('HTTP/1.1 408') !== -1)
    })
  })
})

```

```js
'use strict'

const { test } = require('tap')
const Fastify = require('..')

test('requestTimeout should be resilient against a slow loris attack and return 408', t => {
  t.plan(2)

  const fastify = Fastify({ requestTimeout: 1 })
  fastify.post('/', function (req, reply) {
    reply.send({ hello: 'world' })
  })
  let socket
  let intervalId

  fastify.listen({ port: 0 }, err => {
    t.error(err)
    t.teardown(() => {
      fastify.close()
      socket.destroy()
      clearInterval(intervalId)
    })

    const {
      address: host,
      port
    } = fastify.server.address()

    socket = require('net').connect({ port, host }, () => {
      socket.write(`POST / HTTP/1.1\r\n`);
      socket.write(`Host: ${host}:${port}\r\n`);
      socket.write('Accept: */*\r\n');
      socket.write('Content-Length: 1024\r\n');
      socket.write('User-Agent: Mozilla/4.0 (compatible; MSIE5.01; Windows NT)\r\n');
      socket.write('Connection: Keep-Alive')
      socket.write('Content-Type: application/x-www-form-urlencoded')

      // intervalId = setInterval(() => {
      //   console.log('KeepAlive')
      //   socket.write(`KeepAlive: ${Math.random() * 1000}\r\n`);
      // }, 500);
    });

    socket.setTimeout(0);

    // socket.on('timeout', () => {
    //   console.log('timeout')
    // })
    socket.on('data', (data) => {
      const result = data.toString()
      console.log(result)
      t.ok(result.indexOf('HTTP/1.1 408') !== -1)
    })
  })
})

```

**Comment by ShogunPanda** [comment]
@mcollina Thanks for the advertising. ;)

I do confirm on Node 16 and below it behaves differently due to lack of `connectionsCheckingInterval`.
