### ISSUE TITLE
`fastify.setErrorHandler` not working

### ISSUE THREAD

**Issue by tj-commits** [fastify/fastify#4539]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Catalina 10.15.7

### Description

When I use `fastify.setErrorHandler` it does not work! `fastify.setErrorHandler` doesn't run

### Steps to Reproduce

```
const Fastify = require('fastify')

const fastify = Fastify({ logger: true })

fastify.setErrorHandler((error, request, reply) => {
  fastify.log.error(error.statusCode)
  reply.send("Error")
})

fastify.listen({ port: 8080 })
```
Still uses default
<img width="570" alt="Screen Shot 2023-01-30 at 8 58 45 AM 1" src="https://user-images.githubusercontent.com/57005320/215512488-aa58df2a-b6ee-4a7c-98f6-61d712e676ad.png">

### Expected Behavior

I expected it to just say "Error" and do what I told it to do

**Comment by mcollina** [comment]
"not found" is not an error condition. Check out setNotFoundHandler in the docs.
