### ISSUE TITLE
Validation error with a 'oneOf' json schema set on same type definition

### ISSUE THREAD

**Issue by radubarbos** [fastify/fastify#4541]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

We have a request validation schema that accepts for a property a string or an array of strings containing some allowed values.

The property json schema is like this:
```
"type": {
            "description": "description",
            "oneOf": [
              {
                "$ref": "#/definitions/positionType"
              },
              {
                "type": "array",
                "minItems": 1,
                "items": {
                  "$ref": "#/definitions/positionType"
                }
              }
            ],
            "default": "display"
```

The positionType definition is like:
"positionType": {
      "type": "string",
      "enum": [
        "display",
        "video"
      ]
    }

So these examples are valid requests:
type: "display"
type: ["display", "video"] 
But these are rejected with the error message saying that the type property has to match one of the options.
The error message "/properties/type/oneOf","keyword":"oneOf","params":{"passingSchemas":[0,1]},"message":"must match exactly one schema in oneOf"}]"

In fastify 3.x this does not happen.

### Steps to Reproduce

Create a json schema like above and do a POST call with a valid body that respects the schema.

### Expected Behavior

The request body validation should pass.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

---

Note this might be due to the updated version of Ajv.

**Comment by radubarbos** [comment]
I've created a sample example that ca be just run here https://github.com/radubarbos/fastifyissue

**Comment by mcollina** [comment]
The change in behavior is due to `coerceTypes: 'array'` default that we changed in v4. The following works:

```js
const fastify = require('fastify')
const Ajv = require('ajv')

const ajv = new Ajv({
  coerceTypes: true,
  useDefaults: true,
  removeAdditional: true,
  allErrors: true
})

const requestSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://test/request-config-schema.json",
  "type": "object",
  "definitions": {
    "positionType": {
      "type": "string",
      "enum": [
        "display",
        "video"
      ]
    }
  },
  "properties": {
    "positions": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "pattern": "^[a-zA-Z0-9_-]+$"
      },
      "additionalProperties": {
        "type": "object",
        "description": "Position data required for ad calls.",
        "properties": {
          "alias": {
            "type": "string",
            "description": "The alias to be used for the ad call.",
            "pattern": "^[a-zA-Z0-9_]*$"
          },
          "type": {
            "description": "The type of the creative.",
            "oneOf": [
              {
                "$ref": "#/definitions/positionType"
              },
              {
                "type": "array",
                "minItems": 1,
                "items": {
                  "$ref": "#/definitions/positionType"
                }
              }
            ]
          }
        },
        "required": []
      }
    }
  },
  "required": [
    "positions"
  ]
}
ajv.addSchema(requestSchema)

const app = fastify({
  logger: true
})

app.setValidatorCompiler(({ schema, method, httpPart }) => {
  return ajv.compile(schema)
})

app.get('/', (req, res) => {
  res.send('OK')
})

app.post('/json', {
  schema: {
    body: {
      $ref: requestSchema.$id
    }
  }
}, async (req, res) => {
  res.send('The POST payload was valid.')
})

app.listen({ port: 3000 })
```
---

As a side note, I've found that our docs does not report this correctly, so I've opened a PR (https://github.com/fastify/fastify/pull/4544)
