### ISSUE TITLE
TypeBox type provider on single file route

### ISSUE THREAD

**Issue by Matix-Media** [fastify/fastify#4545]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,

Following issue: If I have a single route file, like this:
```ts
import { Type } from "@sinclair/typebox";
import { RouteOptions } from "fastify";

export default {
    method: "POST",
    url: "/login",
    schema: {
        body: Type.Object({ username: Type.String(), password: Type.String() }),
    },
    handler: async (request, reply) => {
        const username = request.body.username;
    },
} as RouteOptions;
```

There is no (to me apparent) way to use the TypeBox type provider (even if registered on fastify instance)

```ts
const fastify = Fastify({});
fastify.withTypeProvider<TypeBoxTypeProvider>();
```

Is there a way I maybe don't know of or how would you tackle this issue?

**Comment by Shyam-Chen** [comment]
Ref https://www.fastify.io/docs/latest/Reference/Routes/#route-prefixing

**Comment by Matix-Media** [comment]
I know about route-prefixing. But I don't want multiple routes in one file. I want one route, per file. The problem with that is, that when I use TypeBox, TypeScript does not detect the TypeBox types (for example in the body or parameters).

**Comment by Shyam-Chen** [comment]
https://github.com/Shyam-Chen/Fastify-Starter/blob/main/src/modules/todos/registry.ts Try it out?

**Comment by Matix-Media** [comment]
Well, this solution still requires creating an own plugin for each route, but I guess it seems like it's the only current option. It would be nice to be able to simply export an RouteOptions object with TypeBox support.

**Comment by mcollina** [comment]
Fastify is designed to operate as a library, so that applications using it do not need to rely on globals. Therefore, all the metadata of an application are attached to the actual application object.

The mechanism to build modular applications in Fastify are plugins. It's ok to have one route per plugin.
