### ISSUE TITLE
Await fastify.register not solves onRoute hooks

### ISSUE THREAD

**Issue by Adibla** [fastify/fastify#4547]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, I'm thinking about create a plugin that would changes some schemas of my registered routes based on some rules. I thought to go using **onRoute** hooks in my plugin, and following this 
https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V4.md
i saw that it's necessary to add await on my plugin registration. I tried this but it doesn't work for me (using example provided). 

```
let loader = async () => {
  try {
    await fastify.register((instance, opts, done) => {
      instance.addHook('onRoute', (routeOptions) => {
        const { path, method } = routeOptions;
        console.log({ path, method });
      });
      done()
    });

    fastify.get('/product', {
      handler: async (request, reply) => {
        return { hello: 'world'}
      }
    
    await fastify.listen(3000);

  } catch (err) {
    log.fatal(err)
    throw err
  }
}

loader()
```
am i doing something wrong or Is there another method to change routes schemas  of my fastify parent instance?

Thank you.

**Comment by metcoder95** [comment]
Hey!
Here the issue is that the registered plugin is creating its own encapsulated context. For instance, it does not affect the route registered in the parent context.

To do so, you either need to use `fastify-plugin` library or indicate on the plugin to `skip-verride` equals `true`.

See the following example:
```js
let loader = async () => {
  const plugin = (instance, opts, done) => {
    instance.addHook('onRoute', (routeOptions, done) => {
      const { path, method } = routeOptions;
      console.log({ path, method });
    });

    console.log('plugin registered');

    done();
  };

  plugin[Symbol.for('skip-override')] = true;

  try {
    await app.register(plugin);

    app.get('/product', {
      handler: async (request, reply) => {
        return { hello: 'world' };
      },
    });

    await app.listen({ port: 3000 });
  } catch (err) {
    throw err;
  }
};

await loader();
```

**Comment by metcoder95** [comment]
The recommended way is to use [`fastify-plugin`](https://www.npmjs.com/package/fastify-plugin)

**Comment by Adibla** [comment]
Thank you, I completely forgot fp 😅
