### ISSUE TITLE
Using Ajv draft `dependentRequired` in schema

### ISSUE THREAD

**Issue by Matix-Media** [fastify/fastify#4549]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello, I would like to know how I can use the draft `dependentRequired` (draft 2019-09) from ajv in Fastify schemas. As of right now, I get the following error, saying that `dependentRequired` is not a valid keyword:
```
FastifyError [Error]: Failed building the validation schema for POST: /api/v1/user/:id, due to error strict mode: unknown keyword: "dependentRequired"
    at Boot.<anonymous> (D:\Development\JS\new-car-booking-system\node_modules\fastify\lib\route.js:359:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at Boot.emit (node:domain:489:12)
    at D:\Development\JS\new-car-booking-system\node_modules\avvio\boot.js:160:12
    at D:\Development\JS\new-car-booking-system\node_modules\avvio\plugin.js:275:7
    at done (D:\Development\JS\new-car-booking-system\node_modules\avvio\plugin.js:200:5)
    at check (D:\Development\JS\new-car-booking-system\node_modules\avvio\plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9) {
  code: 'FST_ERR_SCH_VALIDATION_BUILD',
  statusCode: 500
}
```
I am pretty sure I have to supply my own ajv instance to Fastify, but I sadly do not know how I would do that.

I was already in the talk with @sinclairzx81 who told me about the `dependentRequired` keyword of Ajv sinclairzx81/typebox#319

**Comment by sinclairzx81** [comment]
@Matix-Media Hi, the following should configure Fastify to use the 2020-12 spec as was suggested on https://github.com/sinclairzx81/typebox/issues/319, however there might be an easier way to have Fastify use the `ajv/dist/2020` implementation internally. The example below creates a custom `FastifySchemaCompiler` and explicitly imports the `ajv/dist/2020` implementation.

Have tested locally and should work ok.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQQFYDc4DMoRHA5AQ1QHoATYAZxiICYAGO3OIouAOnblElgFMS4AFjyg8AsACgu0eADF8lYOgCeAGjgBvOHIXKAygGMhIfAGFsYYABthcAL4YsOXOnkxFS3BKmwNcACpKYDwAQhAAHgFBAApYKMAkNvaY2HgAAi46SkQwgTwAtGCx8cJ5OUEARuGekuDSvpE8an4GRvh2Dim4qeTAAHb6lvjAUNm5lWHVEsxwebNz8wuLS8srq2vreVMsLTzGZuBWNgCuPb0A5nAwQnAkUPjo8HR0eQCM1Dd3D3DkQfqKwPp8G4IL0tjMNhDIVDoXMJDwwtx4PoQZQ4Ds9uZDlAAFxaVzudGmTHWKAAHmahl2+AAfHAALxwAAUmnIlOMdgAlPTaeoJHA4MjeqiUPhLPEgTx6XBejwAO6IVCMjmsZEHayM1mtDl8uAiGBHKC9JkiyxHHhcum0gCEJvFMB4jJNZq5Ov5AH4mZonY04MIsDi4LaSBLWH7oOQ4PJI70lJzXXBcczA6KzXHxLYJGCYdmc7nNuJpiYRBK0cIUDZZcArnAYhA4gkoNH+PsLCSs3mO52VhJBajyGWbAztG5lEqdaxK1cGrX68JyblQhFcjPilBqWPxPzWP2YAA1UV26AtrGMwnHklc6bsVhwOt+4qCYRicTtrtvt9g3S-dxwABKECOe1X3fEDc35fkJH7KByygVhIEoRlcCIXA1F5TdvjZfBcTQ8C4EqEglFxBpWAAeXKJAeH0GBmXjfkwiI3JWAAOSOEBymEJUVFouBCP8RiSLAYFelFRliJYtiOI5DkuPQ3CAC8GKCUjBOAEERLE1j2KgJVpPjWxUO4hIgl6BJehgX8eAARyOYY+GwpgWEUPAPE4CMEnQPo+DUeFfngXA5OqXDcNwDxcQAbX83AAF1uIzWS035OL9KZERLLUEQwEsJQLVpDKsu3HgTMZVLWHw7LtRfAsWFAmqczBPweEoYDapa9Y4EggdYL6CiqKVOCIAQpDcGVMqk3ouAXk5VgrkK4rGu5XVGtYJByBBHTpqEXpGV7CBrFYSwIDOS8WAgABrDroOEVhuso6jlXg6ihpGiACLG3EXjUXjJtsZUZq2kQI0tRbyGW1atqkjbZp2vaDqOhyMCGSxcR826+DwAK4EKCAglgJQLpg67eh6u7+sG5DntezRxo+nj3rUBS4AAZimv65sB3KlpWtaIdZ6GeH2w7jtvc7xCggmbt6+6Bse8nSpepQ3om+ncWZn7If++agYB0Hud+zbtpRXb+dhoWzqAA)

```typescript
import Ajv from 'ajv/dist/2020' // ... imported here
import Fastify, { FastifySchemaCompiler } from 'fastify'
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import { Type, TSchema } from '@sinclair/typebox'

// -------------------------------------------------------------------------------
// SchemaCompiler using the draft 2020-12 draft specification
// -------------------------------------------------------------------------------
export const SchemaCompiler: FastifySchemaCompiler<TSchema> = ({ schema }) => {
  const validate = new Ajv().compile(schema)
  return (value) => !validate(value) 
    ? ({ value, error: validate.errors as any })
    : ({ value })
}

// -------------------------------------------------------------------------------
// Server with Provider and Compiler
// -------------------------------------------------------------------------------
const server = Fastify()
  .withTypeProvider<TypeBoxTypeProvider>()
  .setValidatorCompiler(SchemaCompiler) // ... override here

// -------------------------------------------------------------------------------
// Specify Route
// -------------------------------------------------------------------------------    
server.post('/', {
  schema: {
    body: Type.Object({
      x: Type.Number(),
      y: Type.Optional(Type.Number()),
      z: Type.Optional(Type.Number()),
    }, {
      dependentRequired: { // if 'y' is defined, expect 'z'
        'y': ['z']
      }
    })
  }
}, (req, reply) => reply.send(req.body))

// -------------------------------------------------------------------------------
// Test
// ------------------------------------------------------------------------------- 
server.inject().post('/').body({ x: 1 }).then(res => res.json()).then(console.log) // ok
server.inject().post('/').body({ x: 1, y: 1 }).then(res => res.json()).then(console.log) // fail: expected 'z' property
server.inject().post('/').body({ x: 1, y: 1, z: 3 }).then(res => res.json()).then(console.log) // ok
server.inject().post('/').body({ x: 1, z: 3 }).then(res => res.json()).then(console.log) // ok
```
Hope this helps!
S

**Comment by Matix-Media** [comment]
> ```ts
> server.inject()
> ```

What does the `.inject()` mean?

**Comment by gurgunday** [comment]
Why isn't this the default? I'd love to see it in Fastify v5.

**Comment by Eomm** [comment]
Closing as solved

@gurgunday opened a new issue here: https://github.com/fastify/ajv-compiler/issues/105
The `ajv-compiler` module makes easy this changes if we will not ship it with v5 tho

We were able to run fastify v3 with ajv 8 https://www.nearform.com/blog/upgrading-fastifys-input-validation-to-ajv-version-8/
