### ISSUE TITLE
cache plugin for fastify

### ISSUE THREAD

**Issue by wedgwood** [fastify/fastify#457]
What about a cache for fastify(default memory based, and could be extended using other backend suck as memcached, redis, leveldb and so on). It may be like,

```javascript
fastify.register(require('fastify-cache'));
fastify.register(require('fastify-cache'), {storage: redisStore});

// ...
// ...

await fastify.cache.set('sth', value);
const value = await fastify.cache.get('sth', defaultValue);

```

**Comment by delvedor** [comment]
Hi! Checkout [`fastify-caching`](https://github.com/fastify/fastify-caching) :)
