### ISSUE TITLE
Proposed updates to the reply.getResponseTime() documentation 

### ISSUE THREAD

**Issue by tomanagle** [fastify/fastify#4575]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The `.getResponseTime()` portion of the docs states `Note that unless this function is called in the [onResponse hook](https://www.fastify.io/docs/latest/Reference/Hooks#onresponse) it will always return 0.`. However, I've tested it with `onResponse` and it doesn't return 0, it returns a very small number. This behaviour is expected, but is not represented in the docs.

I'd also like to add something to say that if you'd like to record route response time metrics, this is the place to do it.

What are your thoughts?

Reference: https://www.fastify.io/docs/latest/Reference/Reply/#getresponsetime

### Motivation

Improve documentation & show how easy it is to response response time reliably (much harder in other frameworks)

### Example

Note: To measure the ensure request response time, the function must be called in a `onResponse` hook. Calling the function in other hooks will result in `0` or very low numbers that do not represent the entire request response time.

If you would like to record request response time metrics, the result of `.getResponseTime()` in a `onResponse` hook is the recommended way to do that.

**Comment by mcollina** [comment]
getResponseTime() returns the time since the request was received by Fastify. The name of the getter might be a bit misleading.

**Comment by metcoder95** [comment]
The documentation states:

>Invokes the custom response time getter to calculate the amount of time passed since the request was started.

Maybe we can be more explicit on what it truly measures:

>Invokes the custom response time getter to calculate the amount of time passed time since the request was received by Fastify.

Thoughts? 🤔

**Comment by climba03003** [comment]
It should be changed to another name for example `requestElapsedTime`.
Even better would be a `getter` only, like `reply.elapsedTime` or `request.elapsedTime`.

Then `deprecate` the confused `.getResponseTime()` and the reminder about only use in `onResponse` hook.
Since, it is very clear that it is a elapsed time between the request received and the time it called.

**Comment by metcoder95** [comment]
SGTM 👍

**Comment by mcollina** [comment]
Doing two PRs is ok.

**Comment by codershiba** [comment]
@mcollina I would like to work on this issue
