### ISSUE TITLE
Origin header is undefined/empty when using app.inject

### ISSUE THREAD

**Issue by kamatheuska** [fastify/fastify#4584]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

5.8.0

### Node.js version

18.12.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

Seems that app.inject sends an empty Origin header which causes integration test to fail if fastify cors is settled.

If you think this could be a first good issue I could try to figure it out why that is the case and submit a PR

### Steps to Reproduce

Here is the test, notice the origin header. Without it, the test would fail with a 500 error, and every other test in the project as well.

https://github.com/kamatheuska/inventory-app/blob/master/packages/api/test/plugins/cors.test.ts#L10

### Expected Behavior

As a user, I expect `app.inject` to fake an origin header for me.

**Comment by metcoder95** [comment]
> Instead of adding it by default, we should provide a generator or function to set the default value. So, the user do not need to pass the header one by one.

I do agree with this statement, though (and just thinking out loud) the change of a generator will have the same effect as the end-user submitting the origin while executing `Fastify#inject`. As remarked by @climba03003, the origin is not present all the time and it is not a requirement while making a request (unless CORS comes to the game).

It shouldn't be better to document how to build the origin from the `Fastify#addresses` property, or maybe even go the extra and provide it through a new property e.g. `Fastify#host` returns the full URL: `fastify.host() // returns '<http | https>://<host>:<port>'`?

**Comment by mcollina** [comment]
Origin can be any value, not the current address.

I think we should add `fastify.url()` that returns a valid URL for our application. I added this to Platformatic and it's incredibly useful.

**Comment by metcoder95** [comment]
>Origin can be any value, not the current address.

Exactly that. It is determined by different factors, and those factors might be better to be scoped to the scenario that is looking to test the app behavior under a given `origin`

>I think we should add fastify.url() that returns a valid URL for our application. I added this to Platformatic and it's incredibly useful.

That sounds good to me 👍

**Comment by metcoder95** [comment]
Should this issue remain open now that #4586 has been opened?

**Comment by mcollina** [comment]
think we can close this
