### ISSUE TITLE
Register on a decorated server does not preserve the decorated type

### ISSUE THREAD

**Issue by Zajozor** [fastify/fastify#4585]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Node.js version

16,18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

If I call `.decorate` on `FastifyInstance` and then type it as something that extends the FastifyInstance I'd expect the following `.register` calls to have callbacks using this extended type.

### Steps to Reproduce

```
  const example = fastify()

  const decoratedExample = example.decorate(     // Let's just attach a string for demonstration
    'example',
    'example'
  ) as typeof example & { example: string }

  decoratedExample.example        // Great typing here, all works, it's a string

  decoratedExample.register(
    async innerServer => {
      innerServer.example             // Broken here -> Property 'example' does not exist on type 'FastifyInstance ...
    },
    { prefix: '/example' }
  )
```

### Expected Behavior

I'd expect `innerServer` to be of the same type as the outer instance, eg. `typeof example & { example: string }` in this case.

Or am I perhaps missing some obvious reason why it should not work like this ? Thanks 🙏🏻

**Comment by climba03003** [comment]
>　Or am I perhaps missing some obvious reason why it should not work like this ?

You didn't miss anything. It just how TypeScript works. 
The types stored as the variables itself, but it never mapped to the function signature.

You must decorate the variables globally in TypeScript in order to let it works. 
Although it will appear in the place it shouldn't, it is the best we can do now.
