### ISSUE TITLE
Add fastify.url to return the current url of the application

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#4586]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I think we should add `fastify.url` as it would be a convenient API.
I spend way too much time coding `http://localhost:${server.server.address().port`, so maybe we could get it done in Fastify itself.

Wdyt?

### Example

In Platformatic, we addded:

https://github.com/platformatic/platformatic/blob/d8ad6a97e552c4d2c365a27b1a427738aaa6833c/packages/service/index.js#L208-L215

**Comment by climba03003** [comment]
We should also provide the correct `protocol` based on `server` setting (maybe server instance class would be better).

**Comment by mcollina** [comment]
Yes, exactly

**Comment by jsumners** [comment]
How is this different from the discussion in https://github.com/fastify/fastify/issues/387?

**Comment by climba03003** [comment]
> How is this different from the discussion in https://github.com/fastify/fastify/issues/387?

In the discussion is used for `requset`.
In here is used for a friendly shortcut for test-case.

**Comment by Uzlopak** [comment]
i already see that people report bugs, saying that fastify.url does not respect their top level domain and just report http://127.0.0.1:3000 (instead of http://www.mysecret.tld:3000)

**Comment by nikensss** [comment]
I would like to contribute to this. 

I checked the solution in platformatic. Is this a matter of taking huge inspiration in that and adding it here?

**Comment by mcollina** [comment]
Ouch, this is indeed correct. Maybe we should call it localUrl instead?

**Comment by climba03003** [comment]
Or `listenHost` ?

**Comment by mcollina** [comment]
listenOrigin is likely the more correct one

**Comment by Uzlopak** [comment]
I would prefer something like originUrl as listen is a Verb indicating a function.

**Comment by climba03003** [comment]
> I would prefer something like originUrl as listen is a Verb indicating a function.

originUrl does not indicate what origin it is. and it is odd to have both origin and url since origin is part of url.

Would `listeningOrigin` or `currentListeningOrigin` be specific enough?

**Comment by mcollina** [comment]
`listeningOrigin` would work for me.
