### ISSUE TITLE
Improve Contribution Guide's VSCode setup instructions

### ISSUE THREAD

**Issue by evpirnia** [fastify/fastify#4593]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

While following the instructions for Setting Up Your Environment using Visual Studio Code, I was prompted with 3 settings options when the docs imply that just one option would be presented. I think the docs need to be updated to include info on the 3 different options and link to the VSCode docs for the user to identify and select which one would work best for their use case.

**Comment by jsumners** [comment]
Can you describe them? Or provide a PR? The directions worked at the time of writing.

**Comment by evpirnia** [comment]
Yes, working on a PR now! :)

**Comment by evpirnia** [comment]
resolved by merge above 🚀 , closing issue!
