### ISSUE TITLE
remove callback from register, and remove error from .after()

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#460]
Currently the only way to handle specific error handling and keep booting is by specifying `.after()`. However, this is very subtle and it can lead to complex side effects. I think we should remove this feature: if a plugin errors, the whole loading errors and there is no way to handle that plugin specifics.

**Comment by allevo** [comment]
I'm 👍  for this. Maybe `avvio` could wrap the original error in order to track which plugin fails.

**Comment by delvedor** [comment]
I agree that the current method is not easy to use.
But in the case that you need to load a plugin (or perform an operation) if another one fails, how can you do that without the `after` api?

**Comment by mcollina** [comment]
That will not be possible with this change.

**Comment by delvedor** [comment]
> That will not be possible with this change.

I know. Do we really want to drop that use case? (in any case, we should document it better)

**Comment by mcollina** [comment]
There is an alternative option which is just remove the callback from `register`.

**Comment by delvedor** [comment]
Yes, in my opinion the best thing to do is:
- remove the callback from register and use `after`
- if `after` does not handle the error, that error should reach the next error handling

**Comment by delvedor** [comment]
From avvio `v3.2.0` we can passthrough error in the `after` and `ready` apis, checkout https://github.com/mcollina/avvio/pull/35.

**Comment by jsumners** [comment]
Is this solved?

**Comment by mcollina** [comment]
This is not solved. It has to be done in avvio (likely v5), but I would not have the time until the new year.

**Comment by mcollina** [comment]
I'm currently thinking of dropping this for 1.0.0.
I will not have time in the coming weeks, and I do not want 1.0.0 to be blocked on me.

What do you all think?
