### ISSUE TITLE
Standardize Validation Error

### ISSUE THREAD

**Issue by metcoder95** [fastify/fastify#4605]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

While listing the errors subject to be replaced by native `FastifyErrors`, I completely missed the `Error` object that is raised out of a Validation Error of an incoming request:
https://github.com/fastify/fastify/blob/ec173331c76b8cb31baa5d8764cee9f4f9b6421c/lib/validation.js#L135-L139

The issue is to open the chat about if this `Error` should also be subject to a native `FastifyError` object by default.

Reference: https://github.com/fastify/fastify/discussions/4602

**Comment by Eomm** [comment]
For sure we can add a `code` thing - not sure we can can set it as native FastifyError without touching it because it does not support additional fields `validation` and `validationCOntext` that must be propagated to custom error handlers and hooks

**Comment by metcoder95** [comment]
>For sure we can add a code thing 

I think that should be enough, that's the only part that deviates from the other error work anyways

>it does not support additional fields validation and validationCOntext that must be propagated to custom error handlers and hooks

SGTM, it was the part I was missing. Wasn't sure of its direct impact, thanks! 🙇

**Comment by lilsweetcaligula** [comment]
Hey, new to Fastify. What code would we want to use for validation errors? Would something like `ERR_BAD_REQUEST` work, or do we want to be more specific - `ERR_VALIDATION`? (I have deliberately omitted the `FST_` prefix to convey that it's not a `FastifyError` instance)

P.S. Should we add the `code` prop to here as well? https://github.com/fastify/fastify/blob/main/fastify.js#L689

**Comment by metcoder95** [comment]
Hey! Something specific like `FST_ERR_VALIDATION` sgtm 👍 
I think we should keep the `FST` prefix to indicate are made by fastify explicitly, not necessarily couple them to `FastifyError`.

>P.S. Should we add the code prop to here as well? [main/fastify.js#L689](https://github.com/fastify/fastify/blob/main/fastify.js?rgh-link-date=2023-03-17T12%3A26%3A15Z#L689)

From my side, sounds good!

**Comment by lilsweetcaligula** [comment]
@metcoder95 Thank you for your reply. With regard to: https://github.com/fastify/fastify/blob/main/fastify.js#L689 - I was wondering if it would make sense to try and refactor that line of code to use the error serializer (i.e. `lib/error-serializer.js`)?

**Comment by metcoder95** [comment]
> I was wondering if it would make sense to try and refactor that line of code to use the error serializer (i.e. lib/error-serializer.js)?

Don't think is needed as the error response is hardcoded and directly forwarded to the response stream. The validation might just pile some overhead

**Comment by erfanium** [comment]
I think it's better to use `INTERNAL_SERVER_ERROR` code for all 5xx error. for example, as s user `FST_ERR_ASYNC_CONSTRAINT` is not meaningful to me. it says something about fastify internals that i don't want to know.

**Comment by erfanium** [comment]
have reviewed #4632. I have a concern.
as a user (http client), why I need to know the details about 5xx errors? an error code like `FST_ERR_ASYNC_CONSTRAINT` is not helpful for me. i think we are exposing too much data on internal server errors which can cause: 

- security risk: user can find out more server detail
- backward compatibility difficulty: if we want to change 5xx errors in the future, we need care about backward compatibility because the `code` key is exposed to the user

**Comment by lilsweetcaligula** [comment]
@erfanium All good points. I have reverted the change for the `FST_ERR_ASYNC_CONSTRAINT` scenario. Commit https://github.com/fastify/fastify/pull/4632/commits/d1dc335c7048620caa8267d74562141b67e0b09c

**Comment by erfanium** [comment]
@lilsweetcaligula removing the `code` field is against this main goal of this issue. we want

- same response structure for all errors. (all 4xx 5xx errors to have `code` field)
- not exposing too much data on 5xx errors.

my personal opinion is to use general `INTERNAL_SERVER_ERROR` code for all 5xx error responses. but this behavior should approved by the maintainers. @Eomm

**Comment by metcoder95** [comment]
> my personal opinion is to use general INTERNAL_SERVER_ERROR code for all 5xx error responses. but this behavior should approved by the maintainers. @Eomm

Those are valid points, though the change can decrease the DX as those errors (prefixed with `FST`) are documented and stated that are directly thrown by Fastify. Scoping all of them into `INTERNAL_SERVER_ERROR`, beyond being a breaking change, can make debugging slightly complicated for developers.
We can go the other way around and change the default error parser to identify and delete those leaking pieces from the response. Nonetheless, it is important to also remark that developers have all the power to change the current behavior using [`Fastify#setErrorHandler`](https://www.fastify.io/docs/latest/Reference/Server/#seterrorhandler).
Then, will be interesting to measure and compare the weight of the change and its effects with what the framework already provides 🙂
