### ISSUE TITLE
defaultErrorHandler called after custom one 

### ISSUE THREAD

**Issue by akaNightmare** [fastify/fastify#4606]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

4.5.0

### Node.js version

18.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0

### Description

According to the documentation
```
Fastify is provided with a default function that is called if no error handler is set. It can be accessed using fastify.errorHandler and it logs the error with respect to its statusCode.
```
defaultErrorHandler must be called only if no `fastify.errorHandler` provided. Now, it's not true.

### Steps to Reproduce

```ts
import fastify from 'fastify';

server = fastify();

server.setErrorHandler(async (error, request, reply) => {
  void reply.send(error);
});

server.get('/error', (req, rep) => {
    throw new Error('some error');
});

(async () => {
  await server.inject({ method: 'GET', path: '/error' });
})();
```

### Expected Behavior

defaultErrorHandler must **NOT** be called after custom error handler

**Comment by climba03003** [comment]
The current behavior is correct. The default handler is called when `Error` is exist in custom handler.
It is the last fallback of error handling even if you provide a custom one.

**Comment by paul-jolimoi** [comment]
What can be done regarding this issue?

If I understand well, the default error handler is called because `reply.send` has been called with the `error` which will call the default error handler.

As specified here: https://www.fastify.io/docs/latest/Reference/Lifecycle/

Any improvement can be done to the documentation?

**Comment by mcollina** [comment]
I think mentioning it in `send()` would be good.
