### ISSUE TITLE
{"level":50,"time":1677758906461,"pid":959849,"hostname":"lapn222398","err":{"type":"FastifyError","message":"fastify-plugin: Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done'

### ISSUE THREAD

**Issue by Tweniee** [fastify/fastify#4607]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

4.5.0

### Node.js version

16.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu

### Description

{"level":50,"time":1677758906461,"pid":959849,"hostname":"lapn222398","err":{"type":"FastifyError","message":"fastify-plugin: Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise: Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise","stack":"FastifyError: fastify-plugin: Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise\n    at manageErr (/home/abhishek/Desktop/fastify/express/node_modules/fastify/fastify.js:552:33)\n    at /home/abhishek/Desktop/fastify/express/node_modules/fastify/fastify.js:539:11\n    at Object._encapsulateThreeParam (/home/abhishek/Desktop/fastify/express/node_modules/avvio/boot.js:562:7)\n    at Boot.timeoutCall (/home/abhishek/Desktop/fastify/express/node_modules/avvio/boot.js:458:5)\n    at Boot.callWithCbOrNextTick (/home/abhishek/Desktop/fastify/express/node_modules/avvio/boot.js:440:19)\n    at release (/home/abhishek/Desktop/fastify/express/node_modules/fastq/queue.js:149:16)\n    at Object.resume (/home/abhishek/Desktop/fastify/express/node_modules/fastq/queue.js:82:7)\n    at /home/abhishek/Desktop/fastify/express/node_modules/avvio/boot.js:174:18\n    at /home/abhishek/Desktop/fastify/express/node_modules/avvio/plugin.js:275:7\n    at done (/home/abhishek/Desktop/fastify/express/node_modules/avvio/plugin.js:200:5)\ncaused by: AvvioError: Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise\n    at Timeout._onTimeout (/home/abhishek/Desktop/fastify/express/node_modules/avvio/plugin.js:122:19)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)","name":"FastifyError","code":"FST_ERR_PLUGIN_TIMEOUT","statusCode":500},"msg":"fastify-plugin: Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise"}
[nodemon] app crashed - waiting for file changes before starting...

### Steps to Reproduce

npm i fastify-plugin @fastify/mongodb
plus do what same work as done on the website

**Comment by Fdawgs** [comment]
Closing as plugin related.

Please open an issue in https://github.com/fastify/help or https://github.com/fastify/fastify-mongodb

Please provide list of steps, sample code, or a link to code or a project that reproduces the behavior, as requested in the bug report template.

**Comment by Eomm** [comment]
https://backend.cafe/how-to-use-fastify-and-mongodb
