### ISSUE TITLE
type integer in querystring accepts Infinity and -Infinity even if they're out of range

### ISSUE THREAD

**Issue by unek** [fastify/fastify#4613]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14.0

### Node.js version

18.12.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.10

### Description

I have a JSON schema for querystring that looks like:
```js
offset: { type: 'integer', minimum: 0, maximum: 9223372036854775807, default: 0 } },
limit: { type: 'integer', minimum: 1, maximum: 1000, default: 100 } },
```
For whatever reason, both accept `-Infinity` and `Infinity` as valid values. I've set ajv's `strictNumbers` to true, which it should be by default. I also tried to use the `number` type, same results.

Currently I have this workaround:
```js
offset: { type: 'integer', minimum: 0, maximum: 9223372036854775807, default: 0, not: { enum: [-Infinity, Infinity] } },
limit: { type: 'integer', minimum: 1, maximum: 1000, default: 100, not: { enum: [-Infinity, Infinity] } },
```
but it's not perfect. I don't think `-Infinity` should be validated as correct when it's clearly lower than the minimum.

### Steps to Reproduce

```js
schema: {
  query: {
    type: 'object',
    properties: {
      offset: { type: 'integer', minimum: 0, maximum: 9223372036854775807, default: 0 },
      limit: { type: 'integer', minimum: 1, maximum: 1000, default: 100 },
    },
  },
},
```

call with `?offset=Infinity` or `?offset=-Infinity`

### Expected Behavior

`-Infinity` is lower than the minimum of `0` therefore validation should be rejected.

**Comment by climba03003** [comment]
I would just close it for now as it is an upstream issue.
https://github.com/ajv-validator/ajv/issues/2212
