### ISSUE TITLE
listening host 0.0.0.0 by default

### ISSUE THREAD

**Issue by wooandoo** [fastify/fastify#4619]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

it would be nice that fastify listens host 0.0.0.0 by default

### Motivation

to avoid the error 502 bad gateway like https://github.com/fastify/fastify/issues/3752

### Example

good description in a previous issue: https://github.com/fastify/fastify/issues/3752

**Comment by KingkorAtMaxint** [comment]
@jsumners yes, it's definitely a insecure default. But it'd be nice to have a warning message when `NODE_ENV = production` as it can save 48 hours of hair pulling for some us who don't know the default value for host😄
