### ISSUE TITLE
New logger API

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4624]
As a breaking change, we can simplify the input by splitting the `logger` option into multiple and dedicated properties:
 
---

After writing my [comments around a simplification suggestion](https://github.com/fastify/fastify/pull/4520#discussion_r1084094683) around the `validateLogger` function I have determined that we need to re-think how we deal with this issue.

It was a mistake (that I am responsible for) to accept either an object of options or an instance for the `logger` property. It's a simpler UX, but basically impossible to handle in a concise and maintainable way with the new throwing requirement. I think it is a good idea to introduce the throwing requirement. But I think it means we need to:

1. Deprecate support for `{ logger: <logger_instance> }`.
2. Introduce `{ loggerInstance: <logger_instance> }`.
3. If `loggerInstance` is provided, it takes precedence over `{ logger: <options> }`.

The other avenue is to deprecate `{ logger: <options> }`, but I am quite certain that more people pass in options than they do logger instances. We'd break many more people with this avenue.

_Originally posted by @jsumners in https://github.com/fastify/fastify/pull/4520#pullrequestreview-1265646050_

**Comment by Shobhitsingh-2503** [comment]
Is this issue still open ? I want to work on this.

**Comment by SimenB** [comment]
>3. If loggerInstance is provided, it takes precedence over `{ logger: <options> }`.

Shouldn't it be an error to provide both? When would you want to pass `logger` if you also pass your own instance?

**Comment by jsumners** [comment]
> Shouldn't it be an error to provide both?

It could be handled as an error, yes.

> When would you want to pass `logger` if you also pass your own instance?

You wouldn't. That's the purpose of the requirement: when the developer passes their own logger instance, but for some reason _also_ passes a set of logger options, then ignore the logger options and only use the passed in instance.

**Comment by SimenB** [comment]
Right, which is why I think it should be an error (or at least a warning, but since this'll go into a major anyways, just erroring seems better) and not silently ignored. 👍

**Comment by jsumners** [comment]
I prefer things to "just work" according to the most likely intention. But if everyone else wants it to error so that folks have to handle errors when starting a server, that's fine by me.

**Comment by voxpelli** [comment]
If the function signature gets overloaded so that TypeScript yells at you if you try to specify both, then that would make a runtime error less useful, as it could be caught in the type check stage.

And its pretty obvious that `loggerInstance` should take precedence, so I don't think there's really a need to throw an error (generally I do prefer to throw errors as early as possible otherwise, so generally I would agree with @SimenB here, but I think I'm actually leaning towards @jsumners on this specific one)

**Comment by metcoder95** [comment]
>And its pretty obvious that loggerInstance should take precedence, so I don't think there's really a need to throw an error (generally I do prefer to throw errors as early as possible otherwise, so generally I would agree with @SimenB here, but I think I'm actually leaning towards @jsumners on this specific one)

If that's documented, I think is ok to do it, otherwise can lead to ambiguity, especially if not using TS to error this on the type checking.

**Comment by aarontravass** [comment]
Can I give this a try?

**Comment by metcoder95** [comment]
Be our guest 😉

**Comment by trey-m** [comment]
Was it considered to just add a `loggerInstance` to the logger options input? If its passed, that takes precedent.

**Comment by aarontravass** [comment]
No, the loggerInstance is separate from logger. For example, if you pass a logger instance such as pino to loggerInstance and a configuration to logger, the pino instance passed will take precedence.

On Sep 7, 2023, at 9:15 PM, Trey Martin ***@***.***> wrote:

﻿

Was it considered to just add a loggerInstance to the logger options input? If its passed, that takes precedent.

**Comment by trey-m** [comment]
Yeah, I hear you. But what I'm asking is -- would adding the `loggerInstance` property to the logger options object make more sense (if not already considered)? Reason being now we have 2 top level props that impact how logging takes place. This route would as well only beak those users passing `<loggerInstance>` to logger.

**Comment by aarontravass** [comment]
Yes, it does make sense. 

@jsumners @metcoder95 @mcollina @Eomm  what do you guys think?

**Comment by jsumners** [comment]
I would rather have a property that is configuration and a property that is an instance. Having a property that is configuration that _might_ contain an instance would lead to a very similar situation to the one we are in now.

**Comment by Eomm** [comment]
Closed by https://github.com/fastify/fastify/pull/5020
