### ISSUE TITLE
error TS2614: Module '"@fastify/fast-json-stringify-compiler"' has no exported member 'SerializerFactory'

### ISSUE THREAD

**Issue by seriousme** [fastify/fastify#4629]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14

### Node.js version

v16.19.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.2

### Description

Hi,

running Typescripts tsc  (v4.9.5) from GitHub CI results in:
```
Error: node_modules/fastify/fastify.d.ts(8,33): error TS2614: Module '"@fastify/fast-json-stringify-compiler"' has no exported member 'SerializerFactory'. Did you mean to use 'import SerializerFactory from "@fastify/fast-json-stringify-compiler"' instead?
Error: node_modules/fastify/types/schema.d.ts(2,10): error TS2[6](https://github.com/seriousme/fastify-openapi-glue/actions/runs/4350791294/jobs/7748670225#step:11:7)14: Module '"@fastify/fast-json-stringify-compiler"' has no exported member 'SerializerFactory'. Did you mean to use 'import SerializerFactory from "@fastify/fast-json-stringify-compiler"' instead?
Error: Process completed with exit code 2.
```

I checked  @fastify/fast-json-stringify-compiler and it looks to me like SerializerFactory tries to refer to:
`type FastJsonStringifyFactory = () => SerializerSelector.SerializerFactory`
https://github.com/fastify/fast-json-stringify-compiler/blob/a068619bafa4e2e8c449e6056a20f28a7711b4cd/types/index.d.ts#L3

Kind regards,
Hans

### Steps to Reproduce

See https://github.com/seriousme/fastify-openapi-glue/pull/461
4.13.0 has no issues,  4.14.0 and 14.14.1 break my CI 

### Expected Behavior

No error

**Comment by Uzlopak** [comment]
Are you using a package-lock?

**Comment by seriousme** [comment]
Yes, https://github.com/seriousme/fastify-openapi-glue/blob/master/package-lock.json
I just tried rebuilding the package-lock.json but that did not help.

**Comment by climba03003** [comment]
Please update `@fastify/fast-json-stringify-compiler` to latest version.
You are on `4.1.0` and the latest is `4.2.0`

**Comment by Uzlopak** [comment]
@climba03003 
Reopening for the following question:

Should we set in package.json the necessary version for @fastify/fast-json-stringify-compiler to 4.2.0?

**Comment by seriousme** [comment]
Manually bumping @fastify/fast-json-stringify-compiler to 4.2.0 indeed solves this issue, would be nice if this was fixed in general:
https://github.com/fastify/fastify/blob/4723c1b228f4a3d9e0ba38a137084b7fa2b622db/package.json#L183

**Comment by climba03003** [comment]
> Should we set in package.json the necessary version for @fastify/fast-json-stringify-compiler to 4.2.0?

Wouldn't mind if you send PR to bump the version.
But it is unlikely be a release version for it.

**Comment by Uzlopak** [comment]
Provided PR #4630

**Comment by seriousme** [comment]
Thanks
