### ISSUE TITLE
Optional URL parameter not working after upgrading to Fastify v4

### ISSUE THREAD

**Issue by mateus4k** [fastify/fastify#4637]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi there,

After upgrading Fastify from v3 (`3.29.1`) to v4 (`4.15.0`), I encountered a breaking change that was not mentioned in the [upgrade guide](https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V4.md). The issue is about optional URL building.

Before the upgrade, I had a route similar to the following, where "a" was required but "b" was optional:

```ts
fastify.get('/:a/:b', (request, reply) => {
  const { a, b } = request.params;
});
```

However, after upgrading to v4, some of my integration tests were broken, and I realized that requests without a value for "b" were returning a "404 fallback reached" error. Adding a question mark at the end of the optional variable fixed the issue:

```ts
fastify.get('/:a/:b?', (request, reply) => {
  const { a, b } = request.params;
});
```

I didn't find anything about this in the [URL building docs](https://github.com/fastify/fastify/blob/main/docs/Reference/Routes.md#url-building) or the upgrade guide. However, I can contribute to the project, but I need guidance on where to place it.

**Comment by mcollina** [comment]
Good catch! A PR would be highly welcomed!

**Comment by mateus4k** [comment]
Do you want me to add this only in the migration guide or in the URL building docs as well?

**Comment by climba03003** [comment]
> Do you want me to add this only in the migration guide or in the URL building docs as well?

Yes, please.
