### ISSUE TITLE
Async onSend hook with await is not sending any response

### ISSUE THREAD

**Issue by Chetan-Goyal** [fastify/fastify#4638]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.6.0

### Node.js version

16.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0.1

### Description

While using `async - await` with `onSend` hook, The returned response is not received in the client side and content length is 0.

### Steps to Reproduce

1. Add Below hook.
```js
fastify.addHook("onSend", async (request, reply, payload, done) => {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return "Hello World!";
  });
```
2. Send any response from route via `reply.send(someData)`
3. Check the response received in the client side.

### Expected Behavior

Final Response should be `Hello World!`

**Comment by climba03003** [comment]
Can you provide the full example code that we can run directly?
Have you tried if the issue exist in latest version?

**Comment by Chetan-Goyal** [comment]
Hello there. Sorry for the delay.
It was working properly when I tested it in a new project.
I guess there's some issue in my implementation. I am closing this issue for now but will reopen this after doing some more research and will later try to provide a reproducible code example as well.
