### ISSUE TITLE
Serialization Error in Response Validation Message

### ISSUE THREAD

**Issue by YasarTutuk** [fastify/fastify#4641]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Node.js version

19.7.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Using a query schema that has a response validation defined, if the response returned is not valid according to the schema and the  code is 400 fastify returns a FST_ERR_FAILED_ERROR_SERIALIZATION error. The original error for the actual missing field in the response is found in 'Original error' field.

### Steps to Reproduce

Create a schema such as:
```
const querySchema = {
  schema: {
    querystring: {
      type: 'object',
      properties: {
        x: {
          type: 'number',
          minimum: -90,
          maximum: 90
        },
        y: {
          type: 'number',
          minimum: -180,
          maximum: 180,
        },
      },
      required: ['lat', 'lon']
    },
    response: {
      400: {
        description: 'Succesful response',
        type: 'object',
        properties: {
          hello: { type: 'string' },
          world: { type: 'string' }
        },
        required: ['hello', 'world']
      }
    }
  }
}
```

and register a sample endpoint. 
```
fastify.get('/api/sample/', querySchema, service.sample);
//
export const sample = async (request: FastifyRequest, reply: FastifyReply) => reply.code(400).send({ "hello": "value" });
```

Call the endpoint with a valid request like:
http://localhost:8080/api/sample?x=5&y=2

You will get:
```
{"statusCode":500,"code":"FST_ERR_FAILED_ERROR_SERIALIZATION","message":"Failed to serialize an error. Error: \"hello\" is required!. Original error: \"world\" is required!"}
```

If you change the resonse schema to validate a 200 response instead and use a code 200 you will get:
```
{"statusCode":500,"error":"Internal Server Error","message":"\"world\" is required!"}
```

### Expected Behavior

You should not get FST_ERR_FAILED_ERROR_SERIALIZATION when you return 400 and the response is not valid just like a 200 response.

**Comment by climba03003** [comment]
I am closing it as It is expected behavior.
See https://github.com/fastify/fastify/issues/4592 for more detail on why it happened.
