### ISSUE TITLE
Logger validation fails when passing pino logger via fastify-cli (since #4520)

### ISSUE THREAD

**Issue by stefanosala** [fastify/fastify#4657]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Node.js version

18.12.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0.1

### Description

Hey team,
after the additional validation on the logger object from #4520, I'm getting this error locally:

```
➜  node_modules/.bin/fastify start -w a.js --pretty-logs --options --ignore-watch="out.csv node_modules ui .nyc_output apps" -a 127.0.0.1
FastifyError [Error]: Invalid logger object provided. The logger instance should have these functions(s): 'child'.
    at FastifyError (/Users/stefanosala/Sites/cogsyapp/cogsyapp/node_modules/@fastify/error/index.js:13:14)
    at validateLogger (/Users/stefanosala/Sites/cogsyapp/cogsyapp/node_modules/fastify/lib/logger.js:128:11)
    at createLogger (/Users/stefanosala/Sites/cogsyapp/cogsyapp/node_modules/fastify/lib/logger.js:81:7)
    at fastify (/Users/stefanosala/Sites/cogsyapp/cogsyapp/node_modules/fastify/fastify.js:139:33)
    at runFastify (/Users/stefanosala/Sites/cogsyapp/cogsyapp/node_modules/fastify-cli/start.js:146:19)
    at async main (/Users/stefanosala/Sites/cogsyapp/cogsyapp/node_modules/fastify-cli/lib/watch/fork.js:40:13) {
  code: 'FST_ERR_LOG_INVALID_LOGGER',
  statusCode: 500
}
```

### Steps to Reproduce

We run `fastify` via `fastify-cli` with this code:

```javascript
import pino from 'pino';

const logger = pino();

const app = async (fastify, opts) => { };

app.options = { logger };

export const options = app.options;

export default app;
```

This is because the `logger` gets stripped of the `child` method [here](https://github.com/fastify/fastify-cli/blob/master/start.js#L139). (I've also opened [an issue](https://github.com/fastify/fastify-cli/issues/574) on that project, but no clear indications on how to proceed)

Have you got any recommendations on how to workaround this?

Also, I understand the root cause is not on this repo, but in `fastify-cli`, but I have the feeling that this might have been a BC? Also opening this to hopefully increase visibility on the other issue 🙏

Let me know if and how I can help!
Thank you!

**Comment by mcollina** [comment]
I think the fix for this is in the fastify-cli module.

**Comment by mcollina** [comment]
> Also, mostly for my sake, should #4520 have been a BC change, hence requiring a major release?

I don't see how that impacts on this problem. The stripping seems to be done in fastify-cli itself.

**Comment by stefanosala** [comment]
I'm gonna close this because it doesn't belong here :)

#4520 throws a new error, which _might_ be considered BC change, but again I don't hold strong feelings about that.
