### ISSUE TITLE
bug: labeller bot removes the label

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4661]
The labeller bod should not remove the labels when already set:

https://github.com/fastify/fastify/blob/6eb145aeb905b6c9e1a84cdc67ae8b9f038fd5fd/.github/labeler.yml#L6

<img width="681" alt="image" src="https://user-images.githubusercontent.com/11404065/229888854-b2d268ef-3a80-4de0-b792-7d8bbcf6ffba.png">

**Comment by luisorbaiceta** [comment]
Seems to be a known issue with the sync option. [This](https://github.com/actions/labeler/issues/112#issuecomment-1136485391) appears to solve it
