### ISSUE TITLE
Inconsistent schema validation for response

### ISSUE THREAD

**Issue by qqilihq** [fastify/fastify#4675]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Node.js version

19.3.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### Description

Using a JSON schema with a string format such as `format: "email"` does not always validate the response:

* For a plain `{ type: "string", format: "email" }` the email validation is **not** triggered and strings such as `invalid` will validate successfully.

* However, when wrapping it into an `anyOf` (in our case to allow `null`), the validation triggers and `invalid` will **not** pass validation.

### Steps to Reproduce

```js
const Fastify = require("fastify");

const fastify = Fastify();

fastify.get(
  "/",
  {
    response: {
      200: {
        type: "object",
        required: ["email"],
        properties: {
          email: { type: "string", format: "email" },
          emailOrNull: {
            anyOf: [
               { type: "string", format: "email" },
               { type: "null" }
            ],
          },
        },
      },
    },
  },
  () => {
    return {
      email: "invalid", // this will PASS validation, even though it does not confirm to the format
      emailOrNull: "invalid", // this gives a “The value of '#/properties/emailOrNull' does not match schema definition.”
    };
  }
);
fastify.listen({ port: 1234 }).then(() => console.log("Ready"));
```

### Expected Behavior

Validation error should also trigger for `email: { type: "string", format: "email" }`

**Comment by climba03003** [comment]
You are mixing up `validation` and `serialization`.
Incoming `payload` is using `validation`, but outgoing `response` is using `serialization`.

So, it is expected result because there is no `validation` exists.

Having validation on using `anyOf`, `oneOf`, `allOf`, `ifElse` are unfortunate side-effect for guessing which `schema` should be used for `serialization`.

**Comment by qqilihq** [comment]
Makes sense now, thank you for the explanation. 

Mentioned side-effect has has pushed me towards wrong assumptions (probably not only me). #4653 seems like a good idea!
