### ISSUE TITLE
Unknown format for schema validation in response

### ISSUE THREAD

**Issue by qqilihq** [fastify/fastify#4676]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Node.js version

19.3.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### Description

This might be related to my previous ticket: https://github.com/fastify/fastify/issues/4675

We use `idn-email` format within our schemas (e.g. to allow email addresses such as `ümläut@example.com`). `idn-email` is from the [`ajv-formats-draft2019`](https://github.com/luzlab/ajv-formats-draft2019) package which provides additional `idn-*` formats, which we add as follows:

```
const fastify = Fastify({
  ajv: {
    plugins: [ajvFormatsDraft2019],
  },
});
```

1. For **incoming** data (`body`) the validation works as expected (`foo@example.com`, `ümläut@example.com` pass, `invalid` fails)
2. For responses, the validation simply does not happen if I declare `email: { type: "string", format: "idn-email" },` (see #4675)
3. If I declare the property as “nullable” (using `anyOf` see below), at least the following log will show, but validation also will not work:

   ```
   unknown format "idn-email" ignored in schema at path "#/properties/email/anyOf/0"
   unknown format "idn-email" ignored in schema at path "#/properties/email/anyOf/0"
   unknown format "idn-email" ignored in schema at path "#"
   unknown format "idn-email" ignored in schema at path "#"
   ```

### Steps to Reproduce

```js
const Fastify = require("fastify");
const ajvFormatsDraft2019 = require("ajv-formats-draft2019");

const fastify = Fastify({
  ajv: {
    plugins: [ajvFormatsDraft2019],
  },
});

fastify.post(
  "/",
  {
    schema: {
      body: {
        type: "object",
        properties: {
          email: { type: "string" },
        },
      },
      response: {
        200: {
          type: "object",
          properties: {
            email: {
              anyOf: [
                 { type: "string", format: "idn-email" }, 
                 { type: "null" }
              ],
            },
          },
        },
      },
    },
  },
  (request) => ({ email: request.body.email })
);

fastify.listen({ port: 1234 }).then(() => console.log("Ready"));
```

**Comment by climba03003** [comment]
`ajv` option here is not used for `serialization`.
The one responsible for response is `fast-json-stringify`.

**Comment by StepanMynarik** [comment]
@climba03003 

Just encountered this in project where I sometimes use request schema as response schema (mostly for convenience).
I also don't use ajv at all, I use Typebox for validation instead. Still the error mentioned in this issue is thrown in my project (from deep bowels of ajv).

It seems like using `const fastify = Fastify().setValidatorCompiler(TypeBoxValidatorCompiler);` doesn't use Typebox for response validation but only for request validation?
Little confused here 😆 

See [this issue](https://github.com/sinclairzx81/typebox/issues/677) that I (mistakenly?) made on Typebox repository for more info.

**Comment by climba03003** [comment]
As state in previous comment, there is NO validation for response. 
You need to do it yourself, only SERIALIZATION for response.

**Comment by 123NeNaD** [comment]
@climba03003 Hi,

Thanks for the detailed response!

I have the same issue, where I configured a custom format with Ajv, and the input validations are passing correctly, but the response serialization is adding these `unknown format "objectId" ignored in schema at path` messages in the console.

This is my code where I configured the Ajv:

```ts
import { Ajv } from 'ajv';
import ajvKeywords from 'ajv-keywords';

...

const server: FastifyInstance = fastify({
  ajv: {
    customOptions: {
      coerceTypes: 'array', 
      removeAdditional: 'all', 
      useDefaults: true,
    },
    plugins: [
      (ajv: Ajv) => {
        // Add objectId format using Mongoose's isValidObjectId
        ajv.addFormat('objectId', {
          type: 'string',
          validate: (value) => mongoose.isValidObjectId(value),
        });
      },
      (ajv: Ajv) => {
        ajvKeywords.default(ajv, ['transform']);
      },
    ],
  },
});
```
Now, I am not sure how to customize the serialization behavior, so it would also take these custom formats into account. Is that even possible?

**Comment by 123NeNaD** [comment]
Ok, I figured out how to pass the Ajv options to the serializer. Since response serialization uses its own Ajv instance, we need to define the custom format there as well (thanks @climba03003 for the hint).

We can do this with `serializerOpts`:

```js
const server: FastifyInstance = fastify({
  ajv: {
    customOptions: {
      coerceTypes: 'array',
      removeAdditional: 'all',
      useDefaults: true,
      formats: {
        objectId: {
          type: 'string',
          validate: (value) => ObjectId.isValid(value),
        },
      },
      keywords: ['transform'],
    },
  },
  serializerOpts: {
    ajv: {
      formats: {
        objectId: {
          type: 'string',
          validate: (value) => ObjectId.isValid(value),
        },
      },
    },
  },
});
```

This way the serializer recognizes the format and avoids the “unknown format ignored” warnings.
