### ISSUE TITLE
setErrorHandler return only string or blank object

### ISSUE THREAD

**Issue by roninaruka** [fastify/fastify#4677]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

in my code setErrorHandler return only string or blank object 
```
const server = fastify({  logger: true });

server.setErrorHandler(async (error, req, reply) => {
        reply.status(200).send("I am response") ; //  response content-type  html/plain  with string `I am response`
        //or when use 
        reply.status(200).send({ ok: false }); // response content-type application/json with json `{}`
        // or when use
        reply.status(200).send({ error: { status: true, message: constant.FATAL_ERROR, errorCode: constant.FATAL_ERROR_CODE } }); 
        // response content-type application/json with json 
        `{
            "statusCode": 500,
            "code": "FST_ERR_FAILED_ERROR_SERIALIZATION",
            "message": "Failed to serialize an error. Error: \"error\" is required!. Original error: \"error\" is required!"
        }`
});

server.listen({ port:  5000 }, async (error, address) => {
    if (error) {
        console.log(error);
    }    
});
```
can anyone give me right code so i can send full json

**Comment by 3ddyBoi** [comment]
I tried reproducing your issue based on the code you provided, but I couldn't replicate the same behavior. When I send a response with `{ ok: false }`, I receive the correct JSON object as a reply, which is not a blank object.
![image](https://user-images.githubusercontent.com/70267476/231529637-14bfd266-be09-4a1b-8d74-21fdf87da5c9.png)

**Comment by roninaruka** [comment]
@3ddyBoi first of all thanks your efforts
as i also reproduce other but all work fine 
it only give unexpected result in my project

**Comment by climba03003** [comment]
Please beware `route schema` also take effect on `error handler`.
So, if your route specify a schema that do not contain any property of your error return.
That would result in what you say in this issue.
