### ISSUE TITLE
[feature] Request hostname and host

### ISSUE THREAD

**Issue by Worldwidebrine** [fastify/fastify#4682]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

https://nodejs.org/api/url.html#urlhost
https://nodejs.org/api/url.html#urlhostname
> The key difference between url.host and url.hostname is that url.hostname does not include the port.

### Motivation

Currently, `req.hostname` is `example.com:1234`

### Example

```js
req.hostname // example.com
req.host // example.com:1234
```

**Comment by mcollina** [comment]
Agreed! Let's change it in v5. Would you like to send a PR?

**Comment by lord007tn** [comment]
can we add 
`req.port`
when `{ port: 0 }` Fastify choose one randomly 
i would like to get that in runtime from instance
ik I can parse the address for now 
but as a DX i think having the port directly is better what do you think ?

**Comment by aarontravass** [comment]
I can take this up but just want to make sure no one is working on it since it's a major change

**Comment by metcoder95** [comment]
Implemented through #4766

**Comment by chrisbenincasa** [comment]
Hey everyone - found this after looking into why some features in our app broke upon upgrading from v4 to v5. Was this not considered a breaking change? It was not mentioned in the migration guide AFIACT. 

Perhaps it was technically incorrect for us to rely on hostname to include port, but nonetheless we did. In any case I feel like this behavior change should've been mentioned somewhere, assuming I didn't miss anything. 

Thanks for the great software!

**Comment by jsumners** [comment]
We likely missed looking at then "semver-major" label. Would you like to provide a PR updating the migration guide?
