### ISSUE TITLE
Plugin Testing Guide

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#4687]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add a Plugin Testing Guide in `Testing.md` or `Write-plugin.md`.

### Motivation

Currently, there is no section in either `Testing.md` or `Write-Plugin.md` that explains how to test a written plugin. For example, how to test the decorated FastifyRequest, FastifyInstance and FastifyReply. Since we should only include plugins in the ecosystem list containing sufficient tests, we should also provide a guide that explains how to test a plugin.

**Comment by mcollina** [comment]
I agree! Would you like to write one? There are around 50 examples in this org!

**Comment by matthyk** [comment]
Absolutely! I would place it in the `Write-plugin.md`guide

**Comment by jsumners** [comment]
For what it's worth, this exists https://github.com/jsumners/unit-test-patterns-and-strategies/tree/master/lessons/012-testing-fastify-plugins

**Comment by Ekott2006** [comment]
Hello, Has this issue been covered?

**Comment by matthyk** [comment]
I'm currently pretty busy, so I haven't gotten around to starting the guide yet. You are welcome to take over the issue @Ekott2006 👍

**Comment by Ekott2006** [comment]
Sorry, I am writing a whole documentation page. if yes, do I need to follow any pattern????

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/blob/main/docs/Guides/Style-Guide.md

**Comment by Ekott2006** [comment]
@mcollina  Sorry, where are the examples ??

**Comment by mcollina** [comment]
There are 53 plugins maintained by us: https://fastify.dev/ecosystem.

**Comment by Uzlopak** [comment]
I guess it was fixed but this issue was not closed. Sry. But maybe you find something else ;).
