### ISSUE TITLE
Crash when using `reply` in a response log serializers and a request using an unsupported HTTP version is sent

### ISSUE THREAD

**Issue by bienzaaron** [fastify/fastify#4706]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.16.3

### Node.js version

18.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### Description

When a custom response log serializer uses fields from `reply` other than `statusCode`, Fastify crashes if a request using an unsupported HTTP version is received.

### Steps to Reproduce

fastify server:
```
const Fastify = require('fastify');

const fastify = Fastify({
  logger: {
    serializers: {
      res(reply) {
        return {
          statusCode: reply.statusCode,
          headers: reply.getHeaders()
        }
      }
    }
  }
});

fastify.get('/', async () => 'hello, world');

fastify.listen({ port: 3000 });
```

send a request using telnet:
```
> telnet localhost 3000
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/0.9

Connection closed by foreign host.
```

Fastify crashes with stack trace:
```
{"level":30,"time":1682523174228,"pid":6053,"hostname":"bcd0744fbac0","msg":"Server listening at http://[::1]:3000"}
{"level":30,"time":1682523174229,"pid":6053,"hostname":"bcd0744fbac0","msg":"Server listening at http://127.0.0.1:3000"}
 /Users/me/scratch/fastify-crash-repro/app.js:9
          headers: reply.getHeaders()
                         ^

TypeError: reply.getHeaders is not a function
    at Object.res (/Users/me/scratch/fastify-crash-repro/app.js:9:26)
    at Pino.asJson (/Users/me/scratch/fastify-crash-repro/node_modules/pino/lib/tools.js:132:33)
    at Pino.write (/Users/me/scratch/fastify-crash-repro/node_modules/pino/lib/proto.js:205:28)
    at Pino.LOG [as info] (/Users/me/scratch/fastify-crash-repro/node_modules/pino/lib/tools.js:62:21)
    at Object.routeHandler [as handler] (/Users/me/scratch/fastify-crash-repro/node_modules/fastify/lib/route.js:415:19)
    at Router.callHandler (/Users/me/scratch/fastify-crash-repro/node_modules/find-my-way/index.js:398:14)
    at Router.lookup (/Users/me/scratch/fastify-crash-repro/node_modules/find-my-way/index.js:376:17)
    at Server.preRouting (/Users/me/scratch/fastify-crash-repro/node_modules/fastify/fastify.js:799:14)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1091:12)

Node.js v18.16.0
```

This is caused because a less-than-complete `reply` object is passed for `res` in the log message here: https://github.com/fastify/fastify/blob/main/lib/route.js#L415
There's another similar occurrence here: https://github.com/fastify/fastify/blob/main/lib/route.js#L444

### Expected Behavior

I think there are a two potential issues here:

1. the `res` log serializer is called with a less-than-complete `reply` object. This should either be addressed if possible, or clarified in the documentation and types otherwise. Currently it says:
    > The object received by req is the Fastify [Request](https://www.fastify.io/docs/latest/Reference/Request) object, while the object received by res is the Fastify [Reply](https://www.fastify.io/docs/latest/Reference/Reply) object

2. An error thrown from a log serializer should not crash the Fastify server.

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.


1. I would add the headers and clarify that on the docs - the reply obj can't be created for those conditions
2. Not sure if pino can handle it - cc @climba03003

**Comment by bienzaaron** [comment]
Sure 🙂

**Comment by climba03003** [comment]
I would rather clarify it on document since both place will be removed once `node@18` EOL.
Mocking an unusable `Reply` object would create more flaky behavior.

**Comment by metcoder95** [comment]
>will be removed once node@18 EOL. Mocking an unusable Reply object would create more flaky behavior.

If this will be the end goal, not so sure about the possible value-added if this will be automatically handled and possibly out of the control of `fastify` in the near future. The documentation path seems a good way to go
