### ISSUE TITLE
Why I can not pass an array at serializeInput function ?

### ISSUE THREAD

**Issue by pullmann4rent** [fastify/fastify#4707]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,

I want to add an array to my serializeInput array, but its not working. Why ?

this not work (Posts is an array of items)
`const serzialInput = reply.serializeInput(Posts, schema);`

this works.
`const serzialInput = reply.serializeInput({Posts}, schema);`

```
const schema = {
  schema: {
    response: {
      type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'number' },
            name: { type: 'string' },
            images: { 
              type: 'array',
              items: { image: { type: 'string' } }
            }
          }
        }
    }
  }
}

const postRoutes = (fastify: FastifyInstance, options: FastifyPluginOptions, done: any) => {
  fastify.get('/posts', async (req, reply) => {
    const serzialInput = reply.serializeInput({Posts}, schema);
    return serzialInput;
  });

  done();
};
```

My response is this
```
{
  "Posts": [
    {
      "id": 1,
      "name": "beitrag",
      "images": [
        {
          "image": "http://image.xl/"
        }
      ]
    }
  ]
}
```
but I want to remove the "Posts" at first, I only want the array

**Comment by metcoder95** [comment]
Hey!

This happens because of the way you are passing your schema.
If passing the whole schema, the serializer will interpret it as an object with an `array` inside.

```js
  fastify.get('/posts', async (req, reply) => {
    const serzialInput = reply.serializeInput({Posts}, schema);
    return serzialInput; // Returns { posts: [] }
  });
```

If instead, you pass only the schema definition for the array, the serializer will understand you are looking for an array and apply the needed serialization

```js
  fastify.get('/posts', async (req, reply) => {
    // Using the same schema you shared
    const serzialInput = reply.serializeInput(Posts, schema.schema.response);
    return serzialInput; // Returns [{ id: '', name: '', images: [{}]]
  });
```

**Comment by climba03003** [comment]
Close as it is mis-understanding on how to use `serializeInput`

**Comment by tzafrirben** [comment]
@climba03003 `serializeInput` Typescript [declaration](https://github.com/fastify/fastify/blob/main/types/reply.d.ts#L61) expect an object and TS compiler will throw an error if user provide an array of objects (regardless of the schema).

The following is a valid  "vanilla" Javascript code but not will not compile for TS

```javascript
const input = reply.serializeInput([{id: 1}, {id: 2}], {
    type: 'array',
    items: {
      type: 'object',
      properties: {
         id: { type: 'string' },
       },
     }
});
      
return reply.send(input);
```

Compliation error: "Argument of type '{ id: number; }[]' is not assignable to parameter of type '{ [key: string]: unknown; }'"

**Comment by pullmann4rent** [comment]
> @climba03003 `serializeInput` Typescript [declaration](https://github.com/fastify/fastify/blob/main/types/reply.d.ts#L61) expect an object and TS compiler will throw an error if user provide an array of objects (regardless of the schema).
> 
> The following is a valid "vanilla" Javascript code but not will not compile for TS
> 
> ```js
> const input = reply.serializeInput([{id: 1}, {id: 2}], {
>     type: 'array',
>     items: {
>       type: 'object',
>       properties: {
>          id: { type: 'string' },
>        },
>      }
> });
>       
> return reply.send(input);
> ```
> 
> Compliation error: "Argument of type '{ id: number; }[]' is not assignable to parameter of type '{ [key: string]: unknown; }'"

But serialize not works, if I have an array and set properties id and name and my array has only id then I dont get error, when I use it with schema options then I get missing parameter name, but on serzializeInput it does not show me errors so why its not working ?

```
import { FastifyReply, FastifyRequest } from "fastify";
import Posts from '../posts';

const schema = {
  schema: {
    response: {
      200: {
      type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'number' },
            name: { type: 'string' },
            images: { 
              type: 'array',
              items: { image: { type: 'string' } }
            }
          },
          required: ['images']
        }
      }
    }
  },
}

const getPosts = (req: FastifyRequest, reply: FastifyReply) => {
  const serialize = reply.compileSerializationSchema(schema);
  const res = serialize({Posts});
  return res;
};

export {
  getPosts
};
```

I say required images and my array has no images, so why I dont get error ? Why its send the request with my data ?

**Comment by pullmann4rent** [comment]
> Hey!
> 
> This happens because of the way you are passing your schema. If passing the whole schema, the serializer will interpret it as an object with an `array` inside.
> 
> ```js
>   fastify.get('/posts', async (req, reply) => {
>     const serzialInput = reply.serializeInput({Posts}, schema);
>     return serzialInput; // Returns { posts: [] }
>   });
> ```
> 
> If instead, you pass only the schema definition for the array, the serializer will understand you are looking for an array and apply the needed serialization
> 
> ```js
>   fastify.get('/posts', async (req, reply) => {
>     // Using the same schema you shared
>     const serzialInput = reply.serializeInput(Posts, schema.schema.response);
>     return serzialInput; // Returns [{ id: '', name: '', images: [{}]]
>   });
> ```

But if I have an array where images not exists in my array and I say in my schema required images, why I dont get an error ? It shows me the array but it should say you dont have images in your array ...

**Comment by climba03003** [comment]
serializer is not a validator (although it validate in some aspect, do not assume it do all the work that validator does). It will try it's best to serialize input.
If you need to validate the input, please use a proper validator.

And your example is passing an invalid input of schema, so the output is not what you expect.
@metcoder95 already answered why it happened.

**Comment by pullmann4rent** [comment]
> serializer is not a validator (although it validate in some aspect, do not assume it do all the work that validator does). It will try it's best to serialize input. If you need to validate the input, please use a proper validator.
> 
> And your example is passing an invalid input of schema, so the output is not what you expect. @metcoder95 already answered why it happened.

Ahh ok now I understand thank you, but there are some ways to serialize and validate so which you prefer ?

First option: write schema with addschema and add it in options like this:
`fastify.get('/', { schema: schema }, getPosts)`

Or validate and serializeInput function 

Which is recommend ?

**Comment by climba03003** [comment]
> Which is recommend ?

Directly pass in `route option` is better.
You don't need to reinvent the wheel and do `serializeInput` yourself.

Note that if your are passing unknown schema to `serializeInput`, you are actually slowing your application down.
The main reason is that it create a new serialize function each time.
