### ISSUE TITLE
Why has the tagging format changed?

### ISSUE THREAD

**Issue by lholmquist** [fastify/fastify#4711]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I noticed that starting with 4.16.0, the tagging format has changed.  There is no longer a "v" prefix.    I ask, because we have some automated processes that clone the latest tagged version based on the value we get from `npm show fastify version` and i just noticed that our script has broken because we were expecting that prefix.

Is this going to be the new format?

**Comment by climba03003** [comment]
I believe it just changes of tools for releasing, or changes of npm setting.

**Comment by mcollina** [comment]
Oh my bad. I'll fix the tooling. Good spot, this won't happen again.

**Comment by mcollina** [comment]
Do you need v4.17.0 retagged?

**Comment by lholmquist** [comment]
> Do you need v4.17.0 retagged?
Sure

**Comment by Eomm** [comment]
This would break the website tooling too

**Comment by Uzlopak** [comment]
We can double tag for now

**Comment by mcollina** [comment]
I'll get to it asap, these days are flying.

**Comment by jsumners** [comment]
+ Correct tags have been added
+ Releases have been updated
+ Incorrect tags have been removed

**Comment by lholmquist** [comment]
Thanks everyone for the quick turn around !
