### ISSUE TITLE
Loading multiple routes is broken: Error: rootplugin has already booted

### ISSUE THREAD

**Issue by brwnll** [fastify/fastify#472]
Just upgraded from 0.23 to 0.34 and my existing API broke. I'm trying to see if there is a new structure I should be using.

The error I'm getting is: 
`Error: rootplugin has already booted`

The application structure is a directory with many JSON files with my route schemas. 

```js
// Load our controllers we need for our routes
const controllers = {}
const ctrls = fs.readdirSync('./controllers')

for (const ctrl of ctrls) {
  controllers[ctrl.split('.')[0]] = require(`./controllers/${ctrl}`)
}

// Load the routes
const files = fs.readdirSync('./routes')

for (const file of files) {
  const routes = require(`./routes/${file}`)

  for (const route of routes) {
    // Add in the function that will handle the route request
    // Uses lodash to support dot notation expression strings
    route.handler = _.get(controllers, route.handler)

    // Add the route to the server
    fastify.route(route)
  }
}

fastify.listen(9988, function(err) {
  if (err) throw err

  winston.info(`listening on ${fastify.server.address().port} pid ${process.pid}`)
})
```

**Comment by israeleriston** [comment]
I have commited an architecture that I am doing, there is an example of separation of responsibility from routes and middlewares.

https://github.com/israeleriston/architecture-node/blob/master/src/server.js
line 15, see if you can enjoy anything

**Comment by mcollina** [comment]
I would recommend not to do that kind of dynamic loading: just call `fastify.register(module)` without special magic. You can nest plugins as many times you want without significant performance overhead: wrap both middlewares and routes in plugins. They are fast and safe.
Keep the definition of your routes together and do not split it in multiple files, it will make it harder to debug and use.

**Comment by brwnll** [comment]
I disagree that desperating routes based on function makes things more complicated. I've always experienced single monolith files to be much harder to control through project growth, but if that's the only way fastify can register routes, that's fine. I merged all routes into a single file, but am still getting there error. Here's the entire index.js file

I don't understand why this error is being thrown, or even what is throwing it:

`(node:4435) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: root plugin has already booted`
`(node:4435) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

```js
const _ = require('lodash')
const fs = require('fs')
const fastify = require('fastify')({
  logger: true,
})
const winston = require('winston')

fastify.register(require('fastify-formbody'), {}, (err) => {
  if (err) throw err
})

const config = require('./lib/config')

// Before anything else, lets load our config
config.load(process.env.NODE_ENV)
  .then((config) => {
    // Make our config available
    global.config = JSON.parse(config.Body.toString())

    // Load our controllers we need for our routes
    const controllers = {}
    const ctrls = fs.readdirSync('./controllers')

    for (const ctrl of ctrls) {
      controllers[ctrl.split('.')[0]] = require(`./controllers/${ctrl}`)
    }

    const routes = require(`./routes`)

    for (const route of routes) {
      // Add in the function that will handle the route request
      // Uses lodash to support dot notation expression strings
      route.handler = _.get(controllers, route.handler)

      // Add the route to the server
      fastify.route(route)
        .catch(winston.error)
    }

    fastify.listen(9988, function(err) {
      if (err) throw err

      winston.info(`listening on ${fastify.server.address().port} pid ${process.pid}`)
    }).catch(winston.error)
  })
```

**Comment by mcollina** [comment]
some notes:

1. fastify has its own logger, there is no need to use winston, check out https://github.com/fastify/fastify/blob/master/docs/Logging.md
2. your project is also crashing, because `fastify.listen` does not return a promise. Use https://github.com/mcollina/make-promises-safe to actually find out where your are missing a catch.
3. I _recommend_ not loading things dynamically because I prefer it that way, but I would recommend you to write a plugin to do this.
4. do not put a callback on register, it's useless.
5. adding things to `global` is __an extreme bad practice in Node__, you should not do it.
5. wrap your config logic in a register, and attach that to the fastify instance
6. I do not understand this division between routes and controllers.

Here is how I would rewrite that into:

```js
const fs = require('fs')
const fastify = require('fastify')({
  logger: true
})

fastify.register(require('fastify-formbody'))

fastify.register(async function (fastify, opts) {
   config config = await require('./lib/config').load(process.env.NODE_ENV)
   fastify.decorate('config', config) // no globals

   // you might want to use util.promisify and async/await here instead
   const ctrls = fs.readdirSync('./controllers')

    // you might need to adjust some of this.
    for (const ctrl of ctrls) {
       // all controllers will receive the config in fastify.config
       fastify.register(require(`./controllers/${ctrl}`))
    }
})

fastify.listen(9988, function(err) {
  if (err) throw err

  fastify.log.info(`listening on ${fastify.server.address().port} pid ${process.pid}`)
})
```

If you need pretty logging, pipe the result of this to https://www.npmjs.com/package/pino-colada.

**Comment by israeleriston** [comment]
@mcollina  is my way for registration is bad? why?

**Comment by brwnll** [comment]
Thanks for your feedback @mcollina. Does the project take donations/tips I can contribute to for your time?

**Comment by delvedor** [comment]
In addition to the perfect explanation of @mcollina, we update few days ago our getting started guide, it also contains advices about this.
I suggest you to read [this](https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md#your-first-plugin) paragraph :)
