### ISSUE TITLE
fastify fails if serverFactory returns the same instance of http server

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fastify#4725]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This happens because fastify uses the `serverFactory` to create a [main server](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L23) and a [secondary server](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L141).

Example:

```js
'use strict'

const { createServer } = require('http')
const fastify = require('fastify')

const server = createServer(() => {})
const app = fastify({
  serverFactory: () => server
})

app.listen({ port: 0 }, (err, address) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }
  console.log(`Server listening on ${address}`)
})

```

**Comment by metcoder95** [comment]
It is somehow the expected behavior, given that the server factory is manipulating the server instantiation, which of course `fastify` cannot guess how they are being created.

One option is not to create a secondary server when `options.serverFactory` is submitted, as we cannot control how the factory instantiates its server instances.

**Comment by climba03003** [comment]
It is known that we initialize the first server and stored.
We can check if the returned value is difference than the first one by simple `===` assertion.
Then skip `.listen` call if it is `true`.

**Comment by metcoder95** [comment]
>We can check if the returned value is difference than the first one by simple === assertion.
Then skip .listen call if it is true.

Sure, but that would mean that we are applying a fix for a scoped to a single case, right?
I'm ok with doing so, just wanted to double-check I'm not missing something. 
If following this approach, we should companion this with a documentation update to indicate that by doing this singleton approach, you'll disable listening to the secondary address on `localhost`

**Comment by climba03003** [comment]
> If following this approach, we should companion this with a documentation update to indicate that by doing this singleton approach, you'll disable listening to the secondary address on localhost

Yes

or even simple check for `server.listening` property. It allow to provide more descriptive error or warning.
https://nodejs.org/api/http.html#serverlistening

The first server should throw error. The second server should emit warning.

**Comment by metcoder95** [comment]
Great! SGTM 👍

**Comment by aarontravass** [comment]
I am trying to understand the server code, but how does it work even when you do not pass serverFactory? Both functions, [`createServer`](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L23) and [`listen`](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L25) are called but node does not throw an error. How?

**Comment by Tryndamere-wang** [comment]
like this: 
     fastify.listen({ port: 8009, host: '127.0.0.1' })
The passed parameter contains host, and the value is ‘localhost’, so that the error will disappear

**Comment by aarontravass** [comment]
> like this: fastify.listen({ port: 8009, host: '127.0.0.1' }) The passed parameter contains host, and the value is ‘localhost’, so that the error will disappear

But in the [documentation](https://github.com/fastify/fastify#example) the host is not specified and when the host is null [it assumes `localhost`](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L57) as default and then, logically, it line [65](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L65) should execute. Am I going wrong?

**Comment by Tryndamere-wang** [comment]
> > like this: fastify.listen({ port: 8009, host: '127.0.0.1' }) The passed parameter contains host, and the value is ‘localhost’, so that the error will disappear
> 
> But in the [documentation](https://github.com/fastify/fastify#example) the host is not specified and when the host is null [it assumes `localhost`](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L57) as default and then, logically, line [65](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L65) should execute. Am I going wrong?

 like this: fastify.listen({ port: 8009, host: '127.0.0.1' }) The passed parameter contains host, and the value is not ‘localhost’, so that the error will disappear

**Comment by Tryndamere-wang** [comment]
> > like this: fastify.listen({ port: 8009, host: '127.0.0.1' }) The passed parameter contains host, and the value is ‘localhost’, so that the error will disappear
> 
> But in the [documentation](https://github.com/fastify/fastify#example) the host is not specified and when the host is null [it assumes `localhost`](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L57) as default and then, logically, line [65](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L65) should execute. Am I going wrong?

my wrong, value is not 'localhost'

**Comment by aarontravass** [comment]
I wonder if something like this might work
```javascript
const serverFromServerFactory = options.serverFactory
  if (options.serverFactory.listening) {
    return { serverFromServerFactory, undefined }
  }
```

**Comment by metcoder95** [comment]
>I am trying to understand the server code. How does it work even when you do not pass serverFactory? Both functions, [createServer](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L23) and [listen](https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/server.js#L25) are called but node does not throw an error. How?

Take a look at https://github.com/fastify/fastify/blob/a2981d727821c76c63bf2445332b04af17d52780/lib/server.js#L279.
There `getServerInstance` does sanity checks to validate if `serverFactory` is present or not, and what to do next.

>I wonder if something like this might work

Sadly it won't, you need to execute that check just after `serverFactory` returns the server instance, and only if Fastiy is trying to create a secondary server to listen to the second host

**Comment by aarontravass** [comment]
> Sadly it won't, you need to execute that check just after `serverFactory` returns the server instance, and only if Fastiy is trying to create a secondary server to listen to the second host
I guess we can just check it in dns.lookup. Something like this
```javascript
  dns.lookup(listenOptions.host, { all: true }, (dnsErr, addresses) => {
    if (serverOpts.serverFactory.listening && addresses.length) {
      return
    }
```

**Comment by metcoder95** [comment]
Feel free to open a PR with your suggestion, and we can iterate over it 🙂 

Just remember to take into consideration the suggestion from the following comment: https://github.com/fastify/fastify/issues/4725#issuecomment-1535578631
