### ISSUE TITLE
preClose hook is missing in the site docs

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fastify#4728]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I there a reason why it is not in the docs?

**Comment by climba03003** [comment]
No reason.
The auto build workflow just stopped 2 month ago.

https://github.com/fastify/website

**Comment by mcollina** [comment]
@loige could you take a look?

**Comment by climba03003** [comment]
@mcollina I do not have access to the `secrets`, can you check if the below command works?

```sh
curl -X POST 
  -H 'Content-Type: application/json'
  -H 'Circle-Token: ${{ secrets.circleci_token }}'
  -d '{"branch":"master"}'
  "https://circleci.com/api/v2/project/gh/fastify/website/pipeline"
```

**Comment by luisorbaiceta** [comment]
Related to [this](https://github.com/fastify/website/pull/399#issue-1666532183). Will address this later today

**Comment by climba03003** [comment]
Actually, it just broken on CircleCI.
The current using API is deprecated, and `Circle CI` apps is removed from organization I think.

So, we need to
1. Grant permission to `Circle CI`
2. Update to use API v2 (the script I posted above)

**Comment by luisorbaiceta** [comment]
Fixed [here](https://github.com/fastify/website/pull/401#issue-1693866790)
