### ISSUE TITLE
broken Circle CI integration

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#4732]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The Circle CI token need to be updated.
The API endpoint also need to be updated.

![image](https://user-images.githubusercontent.com/23028015/236393364-9ba828a0-e31c-48df-b813-fdc17bbb38c7.png)

The website build trigger from `fastify/fastify` is broken since March.
That means whenever new document updated in here will not reflect in the website unless we manually run the build step on `fastify/website` or PR is merged in `fastify/website`.

Shell script for `v2` endpoint required to be tested by anyone who has Circle CI access.
[Circle CI Document](https://circleci.com/docs/api/v2/index.html#operation/triggerPipeline)
```sh
curl -X POST \
  -H 'Content-Type: application/json' \
  -H 'Circle-Token: ${{ secrets.circleci_token }}' \
  -d '{"branch":"master"}' \
  "https://circleci.com/api/v2/project/gh/fastify/website/pipeline"
```

cc @mcollina @luisorbaiceta @lmammino

**Comment by Eomm** [comment]
I would not invest too much time here - the website next is ready.

I would invest this time to complete these config tasks:

- align the companies and teams
- integrate the search engine ( https://github.com/fastify/website-next/issues/28 )
- go live and add a new trigger

The search engine is in charge of @ShogunPanda, but docusourus integrates algolia by default, so it would be a matter of creating an API key to complete this task too.

So, if we have pressure - I would start investing more effort on the new website IMHO

**Comment by luisorbaiceta** [comment]
I have access to circle CI but the token can only be read when it's created. I will test this afternoon with a newly created API token. If this works someone with access to the Github repo secrets and to Circle CI will have to create and add the new token.

I will copy the companies and teams folder from the old site to the new site and open a PR this afternoon too @Eomm

**Comment by luisorbaiceta** [comment]
I managed to trigger the pipeline as suggested. The only tricky part is that with the v2 of the API *project API keys* are no longer allowed, so a *personal token* needs to be generated. Next step would be to add a personal access token to our Github secrets by someone with permissions to do so.

I'll open a PR to edit the workflow and we can merge as soon as the secret is added.

[Link to Circle CI docs](https://support.circleci.com/hc/en-us/articles/360060360811-CircleCI-API-v2-Returns-404-Not-Found-)

![image](https://user-images.githubusercontent.com/44276180/236520868-0b1b38f5-a60d-4c09-b3a9-524fff8f28ae.png)
