### ISSUE TITLE
Vercel docs need some attention

### ISSUE THREAD

**Issue by andybak** [fastify/fastify#4733]
https://www.fastify.io/docs/latest/Guides/Serverless/#vercel

To quote: "it is as simple as configuring your vercel.json file like the following"

and "Then, write api/serverless.js like so:"

Nah. Not even close ;-)

There's no instructions for how to configure package.json and most examples on Github fail because of versioning issues (trying to find a working version for fastify-autoload kept me busy. Do I need it? No idea but the github examples I found used it)

Ideally your example would be complete - if that's too long then an example repo would be helpful. I'm only dabbling with fastify because of a casual interest in porting a glitch app to vercel. I'm sure I could get it working given a bit more time but I wanted to flag up a gap in your documentation.

**Comment by lord007tn** [comment]
would you provide an example on how to do it based on you research 
I was looking to host on vercel but didn't find solution until now

**Comment by andybak** [comment]
If I come back to it then I will but I exhausted the small time window I had for this.

**Comment by Ekott2006** [comment]
Hello, Can i try to fix the issue

**Comment by Eomm** [comment]
Sure, go ahead!

**Comment by Ekott2006** [comment]
Hello, I have a question. For the docs which is better

`   app.register(FirstRoutePlugin); `
`  async function FirstRoutePlugin(fastify, options) {
        fastify.get("/", async () => ({ message: "Welcome to Fastify and Vercel" }))
}   ` 
Which is shorter or more standard code 
`app.register(import("../src/app/FirstRoute.js"));`
And then show the file

**Comment by Ekott2006** [comment]
`app.register(import("../src/app"))`  is not working. It only works when i add the extension `app.register(import("../src/app.js"))`

**Comment by aarontravass** [comment]
I'd say, avoid writing shorter code since it can confuse the reader. Avoid jargon and keep it as simple as possible.

**Comment by Ekott2006** [comment]
I have made a pull request with the updated code

**Comment by mcollina** [comment]
Thanks!

**Comment by andybak** [comment]
Docs still seem incomplete to me:

> Vercel provides zero-configuration deployment for Node.js applications. To use it now, it is as simple as configuring your vercel.json file like the following:

OK. So some parts I can guess. Sign up for vercel, create a new project. But it asks me to select a template. So I search for node and this seems likely: https://vercel.com/new/templates/other/nodejs-serverless-function-express

But I'm not 100% sure, to be honest. It's off-putting.

Ideally you'd test these docs on the kind of person they are intended for. Do they work? Are any parts unclear? 

etc etc

**Comment by mcollina** [comment]
@Ekott2006 would you like to take a stab at improving the documentation?

Overall I don't think any of the core team is deploying Fastify to Vercel, so possibly we should just remove it from our docs.

**Comment by andybak** [comment]
My use case was "something I can learn and deploy in 30m": and none of your other examples seemed a good fit.

Personally I think you need docs for something along those lines, whether it's Vercel or some other lightweight platform.

**Comment by Ekott2006** [comment]
@andybak You can deploy with vercel in 10 minutes

I don't have much idea for the website version ( I used the cli) but don't choose any template -- I haven't used vercel before the day previously
First Install the vercel-cli (``` npm i -g vercel ```), login and other config
Then type ``` vercel ``` (for deployment) or ``` vercel dev ``` (which I used while developing the quickstart).

Ensure that the fastify code is in api folder 
Any issues chat me up or post it here 

Enjoy Fastify and Vercel!!!!!!!!

**Comment by andybak** [comment]
Personally I ended up doing something else now and the only reason I'm still commenting here is because I want to help.

My original point was something like "It would be to Fastify's benefit to have an example in the docs that is less complex than the AWS / Google Cloud examples"

They are both fairly complex examples if you don't already use AWS or GCP.

Vercel looked promising but to be a good candidate the docs should be watertight. I don't neccesarily think Vercel is the perfect choice but you should have at least *one* example using a lightweight cloud provider.

**Comment by Ekott2006** [comment]
Sorry, the updated docs has not yet been shipped, I don't know why but please check the markdown in the fastify repository?

@mcollina  When will the updated docs be updated in the website
