### ISSUE TITLE
Default path with ''

### ISSUE THREAD

**Issue by Shyam-Chen** [fastify/fastify#4742]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

```js
fastify.get('', async (request, reply) => {
  return reply.send({ hello: 'world' });
});

// ---

fastify.register(import('~/path/to/route'), { prefix: '/foo' });
```

to

```js
fastify.get(async (request, reply) => { // Default: set path to ''
  return reply.send({ hello: 'world' });
});

// ---

fastify.register(import('~/path/to/route'), { prefix: '/foo' });
```

I'm not sure if it will have a significant impact, but having this feature would be great.

### Motivation

File system based routing.

https://github.com/Vanilla-IceCream/vite-plugin-fastify-routes

### Example

https://github.com/Vanilla-IceCream/vite-plugin-fastify-routes/tree/main/examples/src

**Comment by climba03003** [comment]
I would say a no here.
It is convenient to the user but complicate the code and will de-optimize the function with multiple form of arguments.

**Comment by Shyam-Chen** [comment]
Ok, I get it now, thanks!
