### ISSUE TITLE
Incorrect type definition for genReqId in FastifyServerOptions

### ISSUE THREAD

**Issue by sergburn** [fastify/fastify#4748]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

Irrelevant

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Irrelevant

### Description

The type of `genReqId` server option [implies](https://github.com/fastify/fastify/blob/0dd31b71eeb79da4a43738473eaebcf5844fc8d4/fastify.d.ts#L112) its only argument is an instance of `FastifyRequest`:

```ts
    genReqId?: <...>(req: FastifyRequest<...>) => string,
```

However, in practice [it is given](https://github.com/fastify/fastify/blob/0dd31b71eeb79da4a43738473eaebcf5844fc8d4/lib/route.js#L397) `RawRequest` (e.g. `http.IncomingMessage`):

```js
function routeHandler (req, res, params, context, query) {
    const id = genReqId(req)
``` 

while `FastifyRequest` is [created only later](https://github.com/fastify/fastify/blob/0dd31b71eeb79da4a43738473eaebcf5844fc8d4/lib/route.js#L466) in this function.

### Steps to Reproduce

To reproduce, let's extend the test in [`test/genReqId.js`](https://github.com/fastify/fastify/blob/0dd31b71eeb79da4a43738473eaebcf5844fc8d4/test/genReqId.test.js#L11):

```js
    genReqId: function (req) {
      t.hasProp(req, 'id')
      t.hasProp(req, 'raw')
      return 'a'
    }
```
This test will now fail, because these two props normally found in `FastifyRequest` instance do not actually exist. (Well, `id` value is supposed to be provided by `genReqId` in the first place)

### Expected Behavior

The type definition should be something like this:

```ts
genReqId?: <...>(req: RawRequest) => string,
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by cesarvspr** [comment]
I can be wrong, but looks like there is no testing to the `genReqId` function at all. Can someone double-check?

**Comment by sergburn** [comment]
Yes, I'd be glad to contribute! It may take some time though...

**Comment by sergburn** [comment]
BTW, looks like the definition for `genReqId` in `FastifyLoggerOptions` is [also incorrect](https://github.com/fastify/fastify/blob/36e095db673876db96cad6c11d26fe661dadefcb/types/logger.d.ts#L78). It mentions `RawRequest`, but that in fact is `extends FastifyRequest`, which is weird, or at least not similar to other places where "RawRequest" name is used. 

However, it probably doesn't matter, because this `genReqId` is never called, AFAICS.
