### ISSUE TITLE
Remove URL rewrite logging?

### ISSUE THREAD

**Issue by brettwillis** [fastify/fastify#4753]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

If the rewriteUrl function is used, then a debug log is generated:
https://github.com/fastify/fastify/blob/c4cb3a87cdbd33524556314341aa2b9bea61422f/fastify.js#L798-L800

This issue is more of a personal preference, but this behaviour creates a lot of extra log entries (1 per every request), which in my mind are not interesting.

My proposal is that the logging be removed. If the developer is interested in knowing when the URL is changed, then they can write their own log in the `rewriteUrl` function that they provide. Perhaps then we need to bind the `rewriteUrl` function to the fastify instance, or provide it as a parameter to they can access the logger easily.

Small bonus is that in this way we can also eliminate the URL equality check.

**Comment by mcollina** [comment]
I'm +1 with it.
