### ISSUE TITLE
support both http and https from same app

### ISSUE THREAD

**Issue by gsimko** [fastify/fastify#4768]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Today we have to choose to either use HTTP or HTTPS/HTTP2 when creating the fastify object. In some cases it's preferable to have both protocols supported, which could be done by registering the app with http(s).createServer, however, fastify doesn't seem to support such an approach. Is there any way to do this?

**Comment by climba03003** [comment]
Managing multiple server for us is problematic, you can always do it yourself by providing a custom server which bind to both `http` and `https`.

**Comment by jsumners** [comment]
This is not planned. We will consider a PR that adds it.
