### ISSUE TITLE
jest: v27.x + fastify >= v4.16(tiny-lru: v11.x)  causes syntax error

### ISSUE THREAD

**Issue by artur-ma** [fastify/fastify#4777]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.16.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1

### Description

after updating fastify 4.12.0 to 4.17.0 tests are failing (revert helps) - the reason, is the update of `tiny-lru` pkg 10.x => 11.x in fastify

jest throws this error because tiny-lru

```
 FAIL  tests/t.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /private/tmp/test/node_modules/tiny-lru/dist/tiny-lru.js:178
    }export{lru};
     ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/fastify/lib/contentTypeParser.js:4:13)

```

### Steps to Reproduce

dependencies in package.json

```json5
  "dependencies": {
    "fastify": "^4.17.0"
  },
  "devDependencies": {
    "jest": "^27.5.1"
  }
```

jest.config.js

```ts
module.exports = {
  testEnvironment: 'node'
};
```

tests/t.test.js

```ts
const fastify = require('fastify')

describe('test', () => {
  it('should work', () => {
    const app = fastify()
  });
});
```

run

```
./node_modules/jest/bin/jest.js 
```

### Expected Behavior

Expect no breaking change in minor version of fastify

**Comment by climba03003** [comment]
It is the problem of `jest` picking up the wrong version of file.
`tiny-lru` respect the `types` field and `dist/tiny-lru.js` is expected to be ESM.

**Comment by artur-ma** [comment]
@climba03003 still by updating the major of tiny-url, u made fastify users not be able to use version >=4.16
not all users can update major of jest in a blink, since it was fixed only in jest 28.x

**Comment by climba03003** [comment]
> In terms of semver, it was breaking change that was introduced in minor version

No, it is the bug from `jest` causing the error because it does not support the proper `package.json` syntax.

**Comment by Uzlopak** [comment]
I can feel your pain. But I concur: this is a jest bug, and it was solved in upstream. 

Despite that fastify team is recommending to not use jest.
