### ISSUE TITLE
Reply `removeHeader()` return type incorrectly defined as void

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#4778]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

18.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

The reply `removeHeader()` function can be chained, and does work when chained.
However, TypeScript will flag this as an issue with `Property 'removeHeader' does not exist on type 'void'.`, and refers to this line: https://github.com/fastify/fastify/blob/8540fb48762961ec3bd2ff2d2dfd9cd1e9cc225a/types/reply.d.ts#L46 

I assume it just needs to be changed to use the same type as the other reply functions?

### Steps to Reproduce

Add the following hook to a Fastify instance:

```js
.addHook("onRequest", async (_req, res) => {
	res.removeHeader("cache-control")
		.removeHeader("expires")
		.removeHeader("pragma")
		.removeHeader("surrogate-control");
})
```

### Expected Behavior

For TypeScript to not throw an error.

**Comment by Omkar-kamble82** [comment]
Do we need to assert the type of the output.

**Comment by Fdawgs** [comment]
> > Fastify version
> > 3.17.0
> 
> Is this a typo?

Good spot, posted this issue pretty late for me 😆
