### ISSUE TITLE
Body reader should not overwrite status code if already set in the error

### ISSUE THREAD

**Issue by sergburn** [fastify/fastify#4785]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12

### Description

The raw body reader in `contentTypeParser.js` [attempts to send 400 status](https://github.com/fastify/fastify/blob/36e095db673876db96cad6c11d26fe661dadefcb/lib/contentTypeParser.js#L251) whenever an error is received from the stream. I'd suggest to change it so that if the error already has `statusCode` and it is >= 400, it would be used as-is.

### Steps to Reproduce

This is related to request timeout case. An application may define its own timeout handler on the raw request object with `req.raw.once('timeout', ()=> {...})`, which would send 408 status to the client. After that it naturally needs to break request processing and it would push an error to the stream, for example by `req.raw.destroy(err)`. The application wants this request to be logged with 408 status as well, but contentTypeParser will override it.

There is a workaround for this, of course, for example one can emit `new Error('too long', { cause: {statusCode: 400}}`, then intercept it in custom error handler, but things would be much nicer without this hack.

BTW, Fastify also subscribes on timeout event, but it does so on `raw.socket`, whereas when Node.js is already processing request, it seems to move the timeout listener to the request itself, at least in v16. 

### Expected Behavior

```js
if (err !== undefined) {
  if (!err.statusCode || err.statusCode < 400) err.statusCode = 400 // this line change
    reply[kReplyIsError] = true
    reply.code(err.statusCode).send(err)
    return
}
```

**Comment by metcoder95** [comment]
Hey! Thanks for reporting.
I think that it seems fair, if errored, we can check whether the `err` object contains a valid `number` type under `statusCode` and respect it, so custom implementations can avoid many tricks.

Would you like to contribute to that? 🙂 

> BTW, Fastify also subscribes on timeout event, but it does so on raw.socket, whereas when Node.js is already processing request, it seems to move the timeout listener to the request itself, at least in v16.

I'm not sure what are you referring to exactly, but the `socket` is the one that provides such event. Can you elaborate?

**Comment by sergburn** [comment]
> I'm not sure what are you referring to exactly, but the socket is the one that provides such event. Can you elaborate?

You're right, I misunderstood [this part in `_http_incoming.js`](https://github.com/nodejs/node/blob/6fd13beae07fdd8ba7e153c0b0ecc8b440407025/lib/_http_common.js#L106-L108). Here it just moves request timer. 

But I still believe there is a small issue with the `onTimeout` hook, although not relevant here, so I'll create another issue.

> Would you like to contribute to that?

Sure, why not? 😄

**Comment by sergburn** [comment]
Still some words about why `onTimeout` hook was mentioned here. The way it is defined and implemented is the reason why the user application needs to subscribe to the timeout event on the raw request in order to send 408 status to the client (related issue  #4532).

Since the hook is bound to socket's timeout event, it is "too late" to send any response in the hook - the socket is already closed by then by `http.Server`'s own [timeout event handler](https://github.com/nodejs/node/blob/6fd13beae07fdd8ba7e153c0b0ecc8b440407025/lib/_http_server.js#L622), which does so _unless_ there is custom timeout handler on any of `req`, `res` or `server`. 

I wish there was a timeout hook in Fastify, which is triggered _before_ the socket is closed or some other way to define the timeout response in the user application's format (as opposed to the [very simple format](https://github.com/nodejs/node/blob/6fd13beae07fdd8ba7e153c0b0ecc8b440407025/lib/_http_server.js#L701)  used by Node)

**Comment by metcoder95** [comment]
The current `onTimeout` hooks are executed after the socked triggered the `timeout`, being closed afterward and for instance not being able to execute any other writer at the socket.
Though, the use case sounds like something that has been recurrently happening (maybe have a way to even define a custom `timeout` response instead?

I suggest you open a new issue with those points to trigger a new discussion about it 🙂
