### ISSUE TITLE
Error reading "env" using pm2/ts-node

### ISSUE THREAD

**Issue by HellpMe** [fastify/fastify#4794]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Recently I've been trying to use pm2/typescript to bring the application online and to test it itself, but when I run it with the pm2 transpiler, the "env" simply isn't recognized, I've tried using typescript-paths and still haven't been able to find nothing related to this

import fastifyRegister from "./fastityRegisters";

fastifyRegister().then((fastify) => {
  fastify.ready((err) => {
    if (err) {
      fastify.log.error(err);
      process.exit(1);
    }
    fastify.listen({ port: fastify.env.PORT, host: fastify.env.HOST }).catch((e) => {
      fastify.log.error(e);
      process.exit(1);
    });
  });
}).catch((err: Error) => { console.error(err.message); });

Error this, src/server.ts(9,60): error TS2339: Property 'env' does not exist on type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.

**Comment by HellpMe** [comment]
@mcollina,

here is the repository, to execute the same as I am doing and have the results
npm i pm2 -g
npx pm2 install typescript
npx pm2 start ecosytem.config.js
npx pm2 logs

https://github.com/HellpMe/fastify-test

**Comment by Solant** [comment]
@HellpMe 

You have 2 different ways of running ts file: `ts-node` and `tsx`

In pm2 instance you use ts-node runtime resolver, and it's not 100% accurate with type resolution: https://github.com/TypeStrong/ts-node#missing-types , this is intended behavior from ts-node to make it faster

You can either make changes as described in the link above, or pre-compile TS to JS before running it with pm2 (I would recommend second option, as it will remove memory and some performance overhead)

@mcollina that's not a fastify issue, just ts-node caveat

**Comment by HellpMe** [comment]
@Solant,

I had already seen this missing types, I even used the include and exclude properties and even then it still didn't recognize the properties applied to it, in case I would have to use extends?
Is there a place where I can call you if you prefer, because as I already use the include, I didn't quite understand what you tried to tell me

**Comment by Solant** [comment]
@HellpMe 

You are missing a configuration step from https://github.com/fastify/fastify-env#typescript

You should add declaration for plugin to work with type checks:
```ts
declare module 'fastify' {
  interface FastifyInstance {
    env: { // based on your usage of fastify.env
      PORT: number,
      HOST: string,
      // etc
    }
  }
}
```

**Comment by HellpMe** [comment]
@Solant,

I made the mentioned corrections, even so the error is either in the fastify instance that cannot read the port and host of the api, if you can confirm again in the repository where I updated today, the only difference I used in NodeJS.ProcessEnv

**Comment by Solant** [comment]
@HellpMe 

If you try using actual type for `env` as in my example instead of `NodeJS.ProcessEnv`, it will work

`NodeJS.ProcessEnv` works like a Record<string, string>, that's why you get this error using `NodeJS.ProcessEnv`

**Comment by HellpMe** [comment]
@Solant

Strange, I was able to start normally by setting NodeJs.ProcessEnv

I keep getting the same error

src/server.ts(9,5): error TS2769: No overload matches this call.
   Overload 1 of 7, '(opts?: FastifyListenOptions | undefined): Promise<string>', gave the following error.
     Type 'string | undefined' is not assignable to type 'number | undefined'.

**Comment by Solant** [comment]
@HellpMe

> I was able to start normally by setting NodeJs.ProcessEnv

That is because tsx doesn't make any type checks, so you don't get any type checking during `npm run dev`

>I keep getting the same error

Try using inline type instead of `NodeJS.ProcessEnv`. Here is an example how it works after the change:
![image](https://github.com/fastify/fastify/assets/5971578/e6ddf242-222f-4e5d-9b9f-97334dbea8c6)
![image](https://github.com/fastify/fastify/assets/5971578/fcb584c4-93b5-497f-996a-77ed58e1fcd2)

**Comment by HellpMe** [comment]
@Solant 

![image](https://github.com/fastify/fastify/assets/64676117/8f6eb295-d436-4114-b925-e52508611068)
Right, then I would have to define the other prefixes that I use? because I use RouteOptions.d.ts as you can see, but now it no longer recognizes it itself, even if passed in the fastify register

**Comment by Solant** [comment]
@HellpMe 

That is because interface `FastifyRoutesOptions` is imported globally via `compilerOptions.typeRoots` and/or `include` via `ts-node`, but it is not recognized.

This issue is not related to fastify, so to fix it you should either change your code or make amendments `tsconfig.json`

**Comment by HellpMe** [comment]
@Solant,

Ahh right, now it kind of depends on how I configure tsconfig.json? because then having to add it like in that documentation you sent me from the types file, but now on top of that it cleared the doubt that I was really there, and thanks for the help '-'/
