### ISSUE TITLE
Not binding to IPv6 catch-all when specifying ::/0 in fastify.listen({ host })

### ISSUE THREAD

**Issue by LeeKorbis** [fastify/fastify#4795]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11.0

### Node.js version

19.4.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux

### Description

This is more of a DevX problem. When connecting other services together and trying to test on a local system, specifying 0.0.0.0 is not sufficient - they will resolve localhost to ::1, and since fastify has not bound the services to an IPv6 address, ECONNREFUSED is returned.

When specifying ::/0 as the IPv6 catch-all, fastify is unable to bind.

I suspect the issue is not in fastify itself but in NodeJS's options, since that's what it uses.

**What I propose is a documentation update to mention this problem and a potential solution**

I'm looking at the NodeJS documentation now to see what can be done.

### Steps to Reproduce

1. Setup two services bound to 0.0.0.0
2. Try to connect one service to the other by connecting to localhost:<other-service-port>
3. See ECONNREFUSED

### Expected Behavior

The system itself is not buggy - it's the documentation which should be updated.

**Comment by LeeKorbis** [comment]
The solution is to bind to ::, and not ::/0, despite https://serverfault.com/questions/698369/what-is-the-ipv6-equivalent-of-0-0-0-0-0

It would be very helpful to see this in the documentation.

**Comment by jsumners** [comment]
It's not clear to me that `/0` is a valid prefix. It is at least not in the table found at https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv6_CIDR_blocks. Though, it is listed as the default unicast address in https://en.wikipedia.org/wiki/IPv6_address#Default_address_selection.

Regardless of wether or not `::/0` is a valid address, it is not supported by Node.js core:

![image](https://github.com/fastify/fastify/assets/321201/e282ff9b-bb33-44b8-a272-80cd96359468)


```js
'use strict'

const net = require('net')

const server = net.createServer(conn => {
  console.log('client connected')
  conn.on('end', () => console.log('client disconnected'))
  conn.write('\r\n')
})

server.on('error', console.error)

server.listen({ host: '::/0', port: 8000 })
```

**Comment by Eomm** [comment]
How would you improve the docs https://www.fastify.io/docs/latest/Reference/Server/#listen ?

![image](https://github.com/fastify/fastify/assets/11404065/bbbdc614-4a4a-49d9-8ad6-b6e10a4bf19d)

**Comment by LeeKorbis** [comment]
The presentation needs to be changed so the table isn't under the larger "listenTextResolver" heading. I had went to that exact place in the documentation, jumped to the NodeJS documentation, and then opened an issue here. It wasn't obvious that 0.0.0.0 would be insufficient for IPv6, but :: would be sufficient for both. Having this explanation even beneath the table doesn't help it be discovered...

It's interesting because this problem really only appears when you have services talk with each other, but when you want them to also be accessible from your mobile on the local network it becomes a problem. Otherwise if everything sat on localhost I would have never encountered the problem.

Maybe the problem is too niche, but I imagine there are many who'd like their frontend clients accessed from mobile to be able to speak to communicate with their fastify backends.
