### ISSUE TITLE
Merge main into next

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4798]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The next branch should be synced with main. I wanted to implement some functionality, but the diverging bases makes me believe, that it would result in heavy merge conflicts in the future.
```[tasklist]
### Tasks
```

**Comment by climba03003** [comment]
You would like an automatic pipeline for this action?

**Comment by Uzlopak** [comment]
Actuall I wanted to suggest that you or another maintainer does this. But I could provide a workflow, which could e.g. weekly create a PR for merging main into next. 

Should I create a PR with the workflow? Is that something of interest?

**Comment by Uzlopak** [comment]
proposed a PR.
