### ISSUE TITLE
Content type with charset

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#48]
When using `'Content-Type': 'application/json'` some http client append the charset to the header, so the content type becomes `'application/json;charset=utf-8'`.
When this happens, Fastify returns a *415*, because of our check
```js
if (req.headers['content-type'] && req.headers['content-type'] === 'application/json') {
```
An easy fix is use `.indexOf` or `.split(;)[0]`
```js
if (req.headers['content-type'] && req.headers['content-type'].indexOf('application/json') > -1) {
```

I ran the benchmarks and there wasn't any sensible changes.
Any other idea to solve this?

cc @mcollina @lucamaraschi

**Comment by mcollina** [comment]
No, go ahead and fire a PR.
