### ISSUE TITLE
Inconsistent logger call in frameworksError wrapper

### ISSUE THREAD

**Issue by sergburn** [fastify/fastify#4808]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.7

### Description

The wrapper for `frameworkErrors` custom handler in `fastify.js`, `onBadUrl()` supplies _raw_ request to the "incoming request" logger, unlike in normal logging case in `route.js`.

This breaks input expectation for custom logger's request serializer - normally `req` argument is Fastify request, but in this case it is raw request. This can lead to an exception.

BTW, it also doesn't honor `disableRequestLogging` option in this case.

Same is true for `onAsyncConstraintError` framework error case.

See also #4807 

### Steps to Reproduce

```js
test('Should supply Fastify request to the logger in frameworkErrors wrapper - FST_ERR_BAD_URL',  t => {
  t.plan(5)

  const logStream = split(JSON.parse)

  const fastify = Fastify({
    frameworkErrors: function (err, req, res) {
      res.send(`${err.message} - ${err.code}`)
    },
    logger: {
      stream: logStream,
      serializers: {
        req (request) {
          return { httpVersion: request.raw.httpVersion }
          //                            ^^^
          // test/router-options.test.js 2> TypeError: Cannot read properties of undefined (reading 'httpVersion')
        }
      }
    },
    genReqId: () => 'REQ-1234'
  })

  fastify.get('/test/:id', (req, res) => {
    res.send('{ hello: \'world\' }')
  })

  logStream.on('data', (json) => {
    console.log(json)
    t.same(json.msg, 'incoming request')
    t.same(json.reqId, 'REQ-1234')
    t.same(json.httpVersion, '1.1')
  })

  fastify.inject(
    {
      method: 'GET',
      url: '/test/%world'
    },
    (err, res) => {
      t.error(err)
      t.equal(res.body, '\'/test/%world\' is not a valid url component - FST_ERR_BAD_URL')
    }
  )
})
```

### Expected Behavior

Should supply Fastify request object

**Comment by Eomm** [comment]
I think fastify's request/reply objects are not created when `frameworkErrors` happens.

Related to https://github.com/fastify/fastify/pull/4716

Worth investigating if we can create empty objects

**Comment by sergburn** [comment]
They _are_ created, [here for bad url case](https://github.com/fastify/fastify/blob/f4a8f3624c87ab23bec79280b876ad955ac5fafa/fastify.js#L697) and [here for async constraint error](https://github.com/fastify/fastify/blob/f4a8f3624c87ab23bec79280b876ad955ac5fafa/fastify.js#L719).

It's just that logger is called before that. My suggestion is to call the logger after Fastify req/reply objects are created and only if `disableRequestLogging ` option is not set. In the same way [route does it](https://github.com/fastify/fastify/blob/f4a8f3624c87ab23bec79280b876ad955ac5fafa/lib/route.js#L472).

**Comment by Eomm** [comment]
uuuu you are right - I would go for it then!

I would not consider it breaking tho - if someone implemented the log serializer it should support both `req` formats. with your changes only one is required
