### ISSUE TITLE
Better async/await support

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#481]
I've been trying to use fastify for one of the projects I'm working on and there's one thing that annoys me to no end - fastify supports async functions in route callback, yet you cannot `await` anything else and have to use callbacks (e.g. `.listen`, `.ready`, `.register().after()`, etc).

One example would be using auth plugin. You cannot just do (which is literally the example of fastify-auth and probably has to be fixed because it throws an error with current versions):
```js
fastify.register(require('fastify-auth'))

fastify.route({
  method: 'GET',
  url: '/auth',
  beforeHandler: fastify.auth([fastify.validate]),
  handler: (req, reply) => {
    req.log.info('Auth route')
    reply.send({ hello: 'world' })
  }
})
```

If you run the code above, you'll end up with `fastify.auth is not a function` because fastify-auth does something asynchronously and requires waiting for it. 
Currently to solve this one has to use after method:
```js
fastify.register(require('fastify-auth'))
.after(() => {
  fastify.route({
    method: 'GET',
    url: '/auth',
    beforeHandler: fastify.auth([fastify.validate]),
    handler: (req, reply) => {
      req.log.info('Auth route')
      reply.send({ hello: 'world' })
    }
  })
})
```

This will work, but adds unnecessary nesting via callback. Why not allow doing:
```js
await fastify.register(require('fastify-auth')) // or .after()

fastify.route({
  method: 'GET',
  url: '/auth',
  beforeHandler: fastify.auth([fastify.validate]),
  handler: (req, reply) => {
    req.log.info('Auth route')
    reply.send({ hello: 'world' })
  }
})
```

**Comment by allevo** [comment]
Your proposal is nice.

Currently the `register`  method returns the fastify instance in order to allow the developer chaining the registration

But:
```
await fastify.register(require('fastify-auth'))
  .register(require('fastify-redis'))
  .register(require('fastify-mongodb'))
  .asPromise()

console.log(fastify.mongo)
console.log(fastify.redis)
```
seems to be possible.


`asPromise` returns the promise waiting the `after`  event.
@fastify/fastify thoughts?

**Comment by zenflow** [comment]
Makes sense. Seems like the proposal would add some flexibility to our control-flow for configuring/initializing fastify.

Only problem I see is that `fastify.register()` currently returns `fastify` (the fastify instance) for chaining more method calls, e.g. `fastify.register(somePlugin).route(someRouteDefinition)`, so changing it to return a Promise would be a breaking change.

**Comment by zenflow** [comment]
@allevo's `.asPromise()` idea sounds fantastic!

**Comment by jsumners** [comment]
This sounds like a bug to me. `fastify-auth` doesn't do anything asynchronous during registration. It just decorates the instance -- https://github.com/fastify/fastify-auth/blob/c79107a493ce8e346a7381a731048ac1c097f7c0/fastify-auth.js#L7

Are you using Fastify 0.33.0 or later?

**Comment by allevo** [comment]
@jsumners if I remember correctly the decoration is made async [here](https://github.com/mcollina/avvio/blob/master/boot.js#L192)

**Comment by jsumners** [comment]
@allevo but look at https://github.com/fastify/fastify/blob/80132c96b0655a3c81ccc878a502f4da21ec3747/test/handler-context.test.js#L18-L26

That's how it should be working. Registration of one plugin is supposed to be available to subsequently registered plugins(routes).

**Comment by yamalight** [comment]
@jsumners tried with latest versions from npm. fastify 0.35.1 and fastify-auth 0.1.0

**Comment by allevo** [comment]
@jsumners  the example and the code are different: the example use the decoration *in* a route that is called after the `after` avvio event (async); the code above uses the decoration *after* the registration when the `after` event is not triggered yet (sync).

**Comment by jsumners** [comment]
@allevo ah, so it's the `beforeHandler` that is causing the discrepancy.

**Comment by delvedor** [comment]
This behaviour arrives from [`avvio`](https://github.com/mcollina/avvio). Me and @mcollina are discussing how to support your proposal, but is not that easy.

As said by @allevo `register` and `after` return the Fastify instance, if your return a promise we will break a lot of stuff.

`asPromise` could be a solution, but I don't like it so much, it's something that we should figure out inside `avvio`.
For the moment:
```js
fastify.register(require('fastify-auth'))
.after(() => {
  fastify.route({
    method: 'GET',
    url: '/auth',
    beforeHandler: fastify.auth([fastify.validate]),
    handler: (req, reply) => {
      req.log.info('Auth route')
      reply.send({ hello: 'world' })
    }
  })
})
```
Is the go-to solution.

**Comment by mcollina** [comment]
Returning a Promise from register will break encapsulation. I would love to do it, but I don’t think it will be possible.

Another solution is to define the routes in a subsequent plugin.

**Comment by yamalight** [comment]
If the final conclusion is not to implement awaitable registration then I feel like the current flow should be documented better. And fastify-auth example needs to be fixed as well.

**Comment by delvedor** [comment]
@yamalight the readme contains a very light example, if you look at the [example file](https://github.com/fastify/fastify-auth/blob/master/example.js) you will see the correct implementation.
If you want to send a PR, go ahead! :)

**Comment by yamalight** [comment]
@delvedor PR sent!
Also, either I'm blind or `.after()` doesn't have any docs for it currently 🤔

**Comment by delvedor** [comment]
> Also, either I'm blind or .after() doesn't have any docs for it currently 🤔

Uhm.. looks like your are right!

**Comment by yamalight** [comment]
What are you thoughts about promisification of `.listen()`, `.ready()`, etc?
As far as I understand, they do not don't have same encapsulation stopper.

**Comment by mcollina** [comment]
.listen() now returns a promise if there is no callback. Would you or someone else send a PR for .ready()?

**Comment by yamalight** [comment]
@mcollina sure, I'll send a PR for it in the next few days

**Comment by coreyfarrell** [comment]
FYI `.listen()` returns a Promise if used without a callback (PR #502).
I have a patch that adds Promise capability to `.ready()` if used without a callback.  This one is not posted yet, hopefully soon.

**Comment by yamalight** [comment]
@mcollina I've tried finding where `.ready` is defined, but couldn't quite figure it out.
As far as I can see, all functions are defined here: https://github.com/fastify/fastify/blob/master/fastify.js#L92
But `.ready` is not there. I can only see it being called, but not defined. And as far as I know it's not part of HTTP Node API.
Help? What am I missing? 🤔

**Comment by mcollina** [comment]
https://github.com/mcollina/avvio#ready here it is!

**Comment by yamalight** [comment]
Ah, it was part of support lib. Thanks for the explanation! 👍

**Comment by coreyfarrell** [comment]
PR at mcollina/avvio#37

**Comment by delvedor** [comment]
@mcollina can we close this?

**Comment by mcollina** [comment]
👍

**Comment by jtlapp** [comment]
@yamalight, I'm evaluating whether to go with Fastify. What's the verdict on its support for async/await for making simpler, more readable code?

**Comment by yamalight** [comment]
@jtlapp as you can see from the discussion above - all suggested improvements were implemented and shipped. So, I'd say it's pretty good?

**Comment by jtlapp** [comment]
Thanks @yamalight. Fastify is looking very nice -- a simpler HAPI. I'll give it a shot, though I'll be doing it from Typescript.
