### ISSUE TITLE
fastify.io domain is down => use fastify.dev

### ISSUE THREAD

**Issue by rmcarias** [fastify/fastify#4827]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

navigate to fastify.io -> Domain is down @mcollina

**Comment by peter-logo** [comment]
I am experiencing this issue at the moment.  The domain is still down, has the domain expired @mcollina  ?

**Comment by Eomm** [comment]
The domain is in charge of the OpenJS Foundation

Maybe it is being redirected to the new website.
You can already access it at: https://fastify.dev/

**Comment by Shyam-Chen** [comment]
![image](https://github.com/fastify/fastify/assets/13535256/c70efaea-3da5-4d6b-9a5c-8c021537f3dc)

This place needs to be replaced.

**Comment by Uzlopak** [comment]
Pull Requests are welcome

**Comment by jsumners** [comment]
The provided screenshot is of a GitHub repository setting. A PR cannot solve it. But I don't want to change it until things are confirmed ready. I know that @mcollina is working on this, and it should be solved soon.

**Comment by rmcarias** [comment]
Thanks for the update @jsumners and @Eomm - will note the updated URL moving forward

**Comment by mcollina** [comment]
@Eomm that is incorrect. @lmammino   @delvedor and myself have access and can fix it. I'll add @jsumners  as soon as I'm in front of the laptop.

I'll try to get to it asap but it's the weekend and I'm on babysitting duties until she goes to bed & I have finished house chores.

**Comment by mcollina** [comment]
Unfortunately I cannot restore this today. We use cloudflare for DNS hosting and it does not recognize the its own config anymore.

**Comment by mcollina** [comment]
The authoritavie nameserver would need to be updated, and somebody with access can do it tomorrow.

**Comment by peter-logo** [comment]
@mcollina is it possible to move the domain to a different DNS provider?

**Comment by mcollina** [comment]
I do not have access to the registrar. We can only control the resolution via our cloudflare account.

**Comment by peter-logo** [comment]
Ok got it 👍

**Comment by mcollina** [comment]
`fastify.io` was restored

**Comment by rmcarias** [comment]
> `fastify.io` was restored

Thank You @mcollina 🙌🏽
