### ISSUE TITLE
Synchronous start Fastify server to listen receives aborted signal from `AbortController` before `listenCallback.call`.

### ISSUE THREAD

**Issue by iselo** [fastify/fastify#4829]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18.0

### Node.js version

v16.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.11.6

### Description

The example from https://www.fastify.io/ of Fastify server start (TypeScript Support ) has an issue with ignoring abort signal. 
Probably issue related to call [this.ready(listenCallback.call(this, server, listenOptions))](https://github.com/fastify/fastify/blob/61b86760019c85afbef6cc0f175c75870381ed04/lib/server.js#L100) of  `createServer(...)` sub-function `listen(listenOptions, ...args)` at`lib/server.js` because [server.listen(listenOptions, wrap)](https://github.com/fastify/fastify/blob/61b86760019c85afbef6cc0f175c75870381ed04/lib/server.js#L195) has been called with already true aborted signal. 

```js
listenOptions before call this.ready(listenCallback.call(this, server, listenOptions))
{
  port: 0,
  signal: AbortSignal { aborted: false },
  cb: [Function (anonymous)],
  host: 'localhost'
}
listenOptions before call server.listen(listenOptions, wrap)
{
  port: 0,
  signal: AbortSignal { aborted: true },
  cb: [Function (anonymous)],
  host: 'localhost'
}
listenOptions before call server.listen(listenOptions, wrap)
{
  port: 54991,
  signal: AbortSignal { aborted: true },
  cb: [Function: cb],
  host: '::1'
}

```

### Steps to Reproduce

```typescript
const controller = new AbortController();
server.listen({port: 0, signal: controller.signal}, () => { console.log(server.server.address())});
controller.abort();
```

### Expected Behavior

Expected behaviour should be the same to call `listen(...)` of RawServer or at least documentation should be updated. 
```typescript
const controller = new AbortController();
server.server.listen({port: 0, signal: controller.signal}, () => { console.log(server.server.address())});
controller.abort();
```

**Comment by metcoder95** [comment]
Hi!
Nice catch! I think this can be considered a bug as currently `fastify` does not check whether or not the signal has been aborted or not but rather waits until the `server.listen` does its job.

Would you like to send a PR? 🙂

**Comment by iselo** [comment]
Thank you for the proposition. I'm working on another project now and I need extra time to fix my house till the fall/winter since I pretty close to battle field in Ukraine. Maybe later if an issue will be opened.

**Comment by VishalMCF** [comment]
Any suggestion for a newbie developer like me to start contributing to this project?? Your guidance will be much appreciated

**Comment by metcoder95** [comment]
Hi @VishalMCF, thanks for looking forward to contributing 🙂 

I recommend you take a closer look at @iselo's description of the issue, and then to the following check the [`lib/server.js`](https://github.com/fastify/fastify/blob/6e062296d7b3a3b05407b169bd1a84e103293587/lib/server.js#L28) which is the one that creates a wrapper around `httpServer.listen`.
