### ISSUE TITLE
Constraints option missing

### ISSUE THREAD

**Issue by GHNewbiee** [fastify/fastify#4831]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

At `Routes.md` - > **`Route options`** `constraints` option iwith short description is missing. A section related to the topic just appears in the end of the page. *Tia*

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?
