### ISSUE TITLE
Adding the ajv-keywords plugin to fastify ajv causes an error

### ISSUE THREAD

**Issue by Liam-Tait** [fastify/fastify#4844]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18.0

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4

### Description

When adding [ajv-keywords](https://ajv.js.org/packages/ajv-keywords.html) as a plugin to the ajv instance with pluginOptions or without pluginOptions described [here](https://www.fastify.io/docs/latest/Reference/Server/#ajv) An error occurs when using the [transform](https://ajv.js.org/packages/ajv-keywords.html#transform) keyword to transform a string

### Steps to Reproduce

package.json
```json
{
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "ajv-keywords": "5.1.0",
    "fastify": "4.18.0"
  }
}
```

index.js
```javascript
const fastify = require("fastify")({
  logger: true,
  ajv: {
    plugins: [[require("ajv-keywords"), "transform"]],
  },
});

fastify.get(
  "/",
  {
    schema: {
      querystring: {
        type: "object",
        properties: {
          echo: {
            type: "string",
            transform: ["trim", "toUppercase"],
          },
        },
      },
    },
  },
  async (request) => {
    return { echo: request.query.echo };
  }
);

const start = async () => {
  try {
    await fastify.listen({ port: 3000 });
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();
```

Error
```
{
  "level": 50,
  "time": 1687423951391,
  "pid": 22490,
  "hostname": "qpwntf",
  "err": {
    "type": "FastifyError",
    "message": "Failed building the validation schema for GET: /, due to error keyword \"transform\" value is invalid at path \"#/properties/echo\": data/1 must be equal to one of the allowed values",
    "stack": "FastifyError: Failed building the validation schema for GET: /, due to error keyword \"transform\" value is invalid at path \"#/properties/echo\": data/1 must be equal to one of the allowed values\n    at Boot.<anonymous> (/workspace/node_modules/fastify/lib/route.js:369:21)\n    at Object.onceWrapper (node:events:627:28)\n    at Boot.emit (node:events:525:35)\n    at /workspace/node_modules/avvio/boot.js:160:12\n    at /workspace/node_modules/avvio/plugin.js:275:7\n    at done (/workspace/node_modules/avvio/plugin.js:200:5)\n    at check (/workspace/node_modules/avvio/plugin.js:224:9)\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)",
    "code": "FST_ERR_SCH_VALIDATION_BUILD",
    "name": "FastifyError",
    "statusCode": 500
  },
  "msg": "Failed building the validation schema for GET: /, due to error keyword \"transform\" value is invalid at path \"#/properties/echo\": data/1 must be equal to one of the allowed values"
}

```

### Expected Behavior

Adding `ajv-keywords` to the fastify ajv plugins and using `transform` would apply the specified transformation without an error

**Comment by gurgunday** [comment]
The issue seems to be with using `ajvKeywords` with the `querystring` property, it works correctly when it's used with `body` like so:

```js
const fastify = require("fastify")({
  logger: true,
  ajv: {
    plugins: [[require("ajv-keywords"), "transform"]],
  },
});

fastify.post(
  "/",
  {
    schema: {
      body: {
        type: "object",
        properties: {
          echo: {
            type: "string",
            transform: ["trim", "toUppercase"],
          },
        },
      },
    },
  },
  async (request) => {
    return { echo: request.body.echo };
  }
);
```

**Comment by giuliowaitforitdavide** [comment]
Hi @gurgunday the correct value of the transform field in your case should be ```transform: ["trim", "toUpperCase"],``` as stated [here](https://ajv.js.org/packages/ajv-keywords.html#transform:~:text=to%20lower%20case-,toUpperCase,-%3A%20convert%20to%20upper). Could you give it a try and let us know if it works? I tried this way and it worked

**Comment by Liam-Tait** [comment]
Thank you @giuliowaitforitdavide  and @gurgunday 

I have figured out the issue, and it's on my end. Also the incorrect casing of `toUpperCase`

I am running fastify in a monorepo using yarn. At the top level of that monorepo, I had `eslint` as a dependency, which depends on `@eslint/eslintrc`, which depends on ajv `^6.10.0`


This meant that ajv `^6.10.0` was used instead of the required`^8.11.0` when running fastify in the subdirectory.

I temporarily fixed this issue by defining the required version of ajv in the workspace package.json

```json
{
  "dependencies": {
    "ajv": "8.12.0",
  }
}
```


```
repo/
├─ packages/
│  ├─ api/
│  │  ├─ package.json
├─ package.json <-- Added ajv dependency here
```
