### ISSUE TITLE
How to remove the req.log and replace it with own custom logger

### ISSUE THREAD

**Issue by RjManhas** [fastify/fastify#4847]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

How to remove the req.log and replace it with own custom logger

**Comment by voxpelli** [comment]
When you create `fastify` you can pass it a [`logger`](https://fastify.dev/docs/latest/Reference/Server#logger) option.

Do note that the `logger` is expected to:

> conform to the Pino interface by having the following methods: info, error, debug, fatal, warn, trace, child.

Example:

```js
const customLogger = {
  info: function (o, ...n) {},
  warn: function (o, ...n) {},
  error: function (o, ...n) {},
  fatal: function (o, ...n) {},
  trace: function (o, ...n) {},
  debug: function (o, ...n) {},
  child: function() {
    const child = Object.create(this);
    child.pino = pino.child(...arguments);
    return child;
  },
};

const fastify = require('fastify')({logger: customLogger});
```

Somewhat self-promotion:

I have a module, [`bunyan-adaptor`](https://github.com/voxpelli/node-bunyan-adaptor), that you can use to [adapt any non-pino logger](https://github.com/voxpelli/node-bunyan-adaptor#createlogger--map-any-logger-to-bunyanlite-subset) to a pino-compliant logger
