### ISSUE TITLE
Schema validation produces unexpected error in relation to alternative constants

### ISSUE THREAD

**Issue by mathiasbockwoldt** [fastify/fastify#4854]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18.0

### Node.js version

18.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Under certain circumstances, the schema validation in fastify is buggy, or at least gives unexpected errors. I could not pinpoint the problem 100%, but it seems to be related to alternatives (`oneOf` or `anyOf`), where both alternatives share some properties and differ in others. Also, it seems that to trigger this problem, both alternatives need to have a property with a `const` that distinguishes the two alternatives.
More information and a concrete example with a schema triggering the error and another one that mitigates the error can be found in the repo linked in the "steps to reproduce" section.

### Steps to Reproduce

I prepared a repo with an explanation and all necessary files here:
https://github.com/mathiasbockwoldt/schemabug

### Expected Behavior

I would expect the "broken" endpoint in the above-mentioned repo to be working.

**Comment by Eomm** [comment]
It is not related to fastify, as the schemas are processed by ajv

Here is the explanation:

https://ajv.js.org/json-schema.html#oneof

> The value of the keyword should be an array of JSON Schemas. The data is valid if it matches exactly one JSON Schema from this array. Validators have to validate data against all schemas to establish validity according to this keyword.

Note that the additional properties are removed as this is the default fastify's ajv configuration has the `removeAdditional=true` prop:

https://github.com/fastify/ajv-compiler#ajv-configuration

and you may want to set it as `failing` : https://ajv.js.org/options.html#removeadditional
