### ISSUE TITLE
Typebox Union on Fastify Schema validator does not reflect properly

### ISSUE THREAD

**Issue by Dmitriyx** [fastify/fastify#4868]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15

### Node.js version

19

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Win 10 Pro

### Description

Using Fastify schema validator + typebox from sinclair, I do not get desired results.

### Steps to Reproduce

```
import { Type } from '@sinclair/typebox';

export const OrderIdOnly = Type.Object({
    orderId: Type.String(),
    trackingNumber: Type.String(),
});

export const OrderProductIdAndTrackingNumber = Type.Object({
    orderedProductId: Type.String(),
    trackingNumber: Type.String(),
})

const FulFillOrderDto = Type.Union([OrderIdOnly, OrderProductIdAndTrackingNumber]);

export default FulFillOrderDto;
```

```
fastify.put<{ Body: Static<typeof FulFillOrderDto> }>('/fulfill', { schema: { body: FulFillOrderDto } }, async (request, reply) => {}
```

try to send body with just 
```
{
    orderedProductId: Type.String(),
    trackingNumber: Type.String(),
}
```
or 
```
{
    orderId: Type.String(),
    trackingNumber: Type.String(),
}
```

### Expected Behavior

i expected the OR conditions to work correctly in the schema validators.

I expected that when I send example payload:
```
{
    orderedProductId: "abc123",
    trackingNumber: "aaa111"
}
```
for this for work and vise versa for the other type

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Dmitriyx** [comment]
Thanks for the quick response.
As I was reproducing the issue, I realized where the problem was.  

typebox for schema validation
```
const Option1 = Type.Object({
    property1: Type.String(),
});

const Option2 = Type.Object({
    property3: Type.String(),
})

const UnionType = Type.Union([Option1, Option2]);
```

**bad** code:
```
{ schema: { body: { UnionType } } }
```
good code:
```
{ schema: { body: UnionType } }
```


first piece of code has as extra set of brackets.
