### ISSUE TITLE
Is there a way to disable hooks on specific route?

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#487]
I'm trying to setup auth as per example from `fastify-auth`:

```js
fastify.addHook('preHandler', fastify.auth([fastify.verifyJWT]))

fastify.route({
  method: 'POST',
  url: '/auth-multiple',
  handler: (req, reply) => {
    req.log.info('Auth route')
    reply.send({ hello: 'world' })
  }
})
```

But I need to have a couple of routes that shouldn't trigger the auth `preHandler` on them.
Is there a way to disable this preHook for specific routes? Or maybe there's a different way of defining routes so that hook won't get executed?

**Comment by jsumners** [comment]
Just register those routes in a different context:

```js
fastify.register((instance, opts, next) => {
  // authenticated routes
  instance.addHook('preHandler', fastify.auth([fastify.verifyJWT])
  fastify.route(/*...*/)
})

fastify.register((instance, opts, next) => {
  // non-authenticated routes
  fastify.route(/*...*/)
})
```

**Comment by yamalight** [comment]
@jsumners thanks! 
would you be open to a docs PR that clarifies that in hooks section? currently that's only mentioned way below closer to the end, I think it'd be useful to mention the fact that hooks are scoped in the very beginning.

**Comment by jsumners** [comment]
We are always receptive to PRs that improve documentation.

**Comment by yamalight** [comment]
@jsumners PR open: https://github.com/fastify/fastify/pull/488
Does that looks OK?

**Comment by yamalight** [comment]
Closing this.

**Comment by ahsandev2019** [comment]
i know this is old issue but i get same problem too, i solve with this 

```javascript
fastify.addHook("preHandler", async (request, reply) => {
  // some validation 
  return;
});

fastify.get(
  "/getaddress",
  {
    schema: {
      query: Joi.object()
        .keys({
          data1: Joi.string().required(),
        })
        .required()
    },
    validatorCompiler: ({ schema, params, method, url, httpPart }) => {
      return data => schema.validate(data);
    },
    preHandler: async (request, reply, done) => {
      // spesific validation
      return;
    }
  },
```

**Comment by JaosnHsieh** [comment]
> i know this is old issue but i get same problem too, i solve with this
> 
> ```js
> fastify.addHook("preHandler", async (request, reply) => {
>   // some validation 
>   return;
> });
> 
> fastify.get(
>   "/getaddress",
>   {
>     schema: {
>       query: Joi.object()
>         .keys({
>           data1: Joi.string().required(),
>         })
>         .required()
>     },
>     validatorCompiler: ({ schema, params, method, url, httpPart }) => {
>       return data => schema.validate(data);
>     },
>     preHandler: async (request, reply, done) => {
>       // spesific validation
>       return;
>     }
>   },
> ```

this will invoke multiple hook functions instead skipping it.
