### ISSUE TITLE
Are decorators scoped?

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#489]
I'm setting up my auth as a plugin, i.e.:
```js
// auth setup
fastify.register((fastify, opts, next) => {
  fastify.decorate('verifyJWT', (request, reply, done) => {
    // ...
  });
});
```

Then in other place I register a bunch of routes that should be protected by auth, so I follow the example, i.e.:
```js
fastify.register((fastify, opts, next) => {
  fastify.addHook('preHandler', fastify.auth([fastify.verifyJWT]));
  // methods...
});
```

The code above throws errors. Am I correct in my assumption that decorators are scoped (along with hooks)? If yes - this should be mentioned in the docs.

**Comment by yamalight** [comment]
Additional question: if they are scoped, is there a way to define global decorator from scope?

**Comment by mattbrunetti** [comment]
@yamalight 

> Am I correct in my assumption that decorators are scoped (along with hooks)? If yes - this should be mentioned in the docs

Yes, that's correct. It's not mentioned in `Decorators.md` (yet), but it is mentioned elsewhere (I don't recall where exactly)

> if they are scoped, is there a way to define global decorator from scope?

Wrap your plugin with this: https://www.npmjs.com/package/fastify-plugin

**Comment by jsumners** [comment]
It depends on where you apply the decoration.

This is global:

```js
const fastify = require('fastify')()
fastify.decorate('foo', 'foo')

fastify.listen(3000)
```

This is scoped:

```js
const fastify = require('fastify')()
fastify.register((instance, opts, next) => {
  instance.decorate('foo', 'foo')
  instance.get('/foo', function (req, reply) {
    reply.send(this.foo) // 'foo'
  })
  next()
})

fastify.get('/foobar', function (req, reply) {
  reply.send(this.foo) // undefined
})

fastify.listen(3000)
```

**Comment by mattbrunetti** [comment]
@jsumners Global scope is a scope :wink:

**Comment by delvedor** [comment]
@yamalight I highly recommend you to read [the hitchhiker's guide to plugins](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md) :)

**Comment by yamalight** [comment]
@delvedor that guide actually explained most of the things i was confused about!

I feel like some of those things should be mentioned directly in decorators doc. Or at least, that guide should be linked from there saying you can find more in-depth info on decorators there (because I'd never though you explain decorators in plugins guide 🤷‍♂️)

**Comment by jsumners** [comment]
@yamalight if you'd like to help with https://github.com/fastify/fastify/issues/296, that'd be fantastic.

**Comment by yamalight** [comment]
@jsumners I'll take a look!

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)

**Comment by yamalight** [comment]
Whoops, should've done this myself. Thanks!
