### ISSUE TITLE
c8 and code coverage artifact upload "broken"

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4907]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I guess c8 is not generating lcov files as expected by our code coverage workflows, resulting in this kind of warnng:

![image](https://github.com/fastify/fastify/assets/5059100/a1576243-abea-40f5-8731-ee11b1d7692c)

**Comment by mcollina** [comment]
cc @Fdawgs could you take a look?

**Comment by jsumners** [comment]
```sh
c8 --reporter lcov
```

**Comment by Fdawgs** [comment]
> cc @Fdawgs could you take a look?

@Uzlopak Beat me to it 😂
