### ISSUE TITLE
avvio says it's already booted before `fastify.listen` is invoked

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#491]
```js
'use strict'

const fastify = require('fastify')()
const fp = require('fastify-plugin')

const plugin1 = fp(function plugin1(instance, opts, next) {
  instance.decorate('plugin1', true)
  next()
})

const plugin2 = fp(function plugin2(instance, opts, next) {
  instance.decorate('plugin2', true)
  next()
})

const plugin3 = fp(function plugin3(instance, opts, next) {
  instance.decorate('plugin3', true)
  instance.get('/', (req, reply) => reply.send('plugin3'))
  next()
})

async function doThings () {
  fastify.register(plugin1).register(plugin2)
  return true
}

doThings()
  .then(() => {
    fastify
      .register(plugin3)
      .listen(3000)
  })
  .catch((err) => {
    console.error(err)
  })
```

If you run that, you'll get:

```
Error: root plugin has already booted
    at Boot._init (/private/tmp/26/node_modules/avvio/boot.js:125:11)
    at Boot._addPlugin (/private/tmp/26/node_modules/avvio/boot.js:180:8)
    at Boot.use (/private/tmp/26/node_modules/avvio/boot.js:160:10)
    at Function.server.(anonymous function) [as register] (/private/tmp/26/node_modules/avvio/boot.js:30:14)
    at doThings.then (/private/tmp/26/index.js:30:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

My guess is this is due to:
https://github.com/mcollina/avvio/blob/6d7554cfe4113985609b33e531f60ba72d36edf3/plugin.js#L83-L99

I most assuredly think that Fastify should allow registrations up until the point `.listen()` is invoked.

**Comment by allevo** [comment]
Could you add a test for this?

Another thing: if the `done` call in plugin3 is postponed with a `setTimeout`, does the bug persist?

**Comment by delvedor** [comment]
The Fastify plugin system provides a method to handle all the async operations you could have, use a mixed approach can lead to this problem.

What you should do is:
```js
...
async function doThings (instance, opts) {
  instance.register(plugin1).register(plugin2)
}

fastify
  .register(doThings)
  .register(plugin3)
  .listen(3000, err => {
    if (err) throw err
  })
```

In https://github.com/mcollina/avvio/pull/36 you can find a proposal to give a better support for *async-await* without breaking the encapsulation model.

**Comment by jsumners** [comment]
Don't focus on the `async` keyword. It's just a simplification for illustration. The issue is registering plugins on next tick. If you modify the example to:

```js
'use strict'

const fastify = require('fastify')()
const fp = require('fastify-plugin')

const plugin1 = fp(function plugin1(instance, opts, next) {
  instance.decorate('plugin1', true)
  next()
})

const plugin2 = fp(function plugin2(instance, opts, next) {
  instance.decorate('plugin2', true)
  next()
})

const plugin3 = fp(function plugin3(instance, opts, next) {
  instance.decorate('plugin3', true)
  instance.get('/', (req, reply) => reply.send('plugin3'))
  next()
})

setImmediate(() => {
  fastify
    .register(plugin1)
    .register(plugin2)
    .register(plugin3)
    .listen(3000)
})
```

You can see the same behavior.

**Comment by delvedor** [comment]
The issue is to leave *generic* asynchronous operations outside registers.
Every operation that will do something asynchronously should be wrapped inside a register.
That's the deal, we handle the asynchronicity, not some weird timeout/promise/sleep/wait/nextTick logic :)

**Comment by jsumners** [comment]
Not everything in certain applications need to be a Fastify plugin. Sure, refactoring things into Fastify plugins, and simply never dealing with the passed in `instance`, works. But it's not right to force people to wrap their things with `(fastify, options, next) => {}` when those things don't need to touch the Fastify instance.

**Comment by mcollina** [comment]
This issue asks if we should start booting the fastify instance before .listen (or .ready, or .inject) are called. I’m not 100% sure that the current behavior of autostart provides the best possible API.

Adding a start method in avvio and an autostart oprion might solve a lot of issues. Then we will not start loading until the last possible minute.

.listen is currently handled through avvio. We can also do something special for this and bypass avvio.

**Comment by jsumners** [comment]
You understand it correctly @mcollina.

**Comment by mcollina** [comment]
Would you mind to fire a PR on avvio to add an autostart option and a start method? Or maybe launch and autolaunch.

**Comment by jsumners** [comment]
I will at least look into it soon.
