### ISSUE TITLE
Detect invalid return values which cause major (and very hard to debug) application errors

### ISSUE THREAD

**Issue by johnspackman** [fastify/fastify#4911]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

If a URL handler uses `async`/`await` and does not return the reply object, then this will silently break the application in a manner very hard to debug.

Please see https://github.com/fastify/fastify/issues/4908 and possibly https://github.com/fastify/fastify/issues/3994

EG this code:

```
   app.get(
        "*",
        async (req, reply) => {
          reply.send("hello");
        }
    );
```

The solution is [documented here](https://fastify.dev/docs/latest/Reference/Routes/#async-await) but the problem is easily overlooked.

The correct answer is to either (a) `return reply` (b) `return reply.send(...)`, or (c) `await reply`, however if you use the code above fastify/your app will call `reply.send` twice, causing the underlying HTTP implementation to throw an error.

It is **virtually impossible** to determine what caused the exception to be thrown by the underlying node HTTP library, even by debugging the fastify code.

From an end users point of view, the data has been sent (ie `reply.send()` has been called) and all promises have been awaited for - but gotcha! we have to know to await something not generally considered to be a promise, or return it.

Are there any circumstances when a URL handler can return a promise which resolves as `undefined`?  AIUI the only time would be if the handler used `await reply` already.

It would be **massively** more helpful to detect a return of `undefined` and warn the user that is probably not correct, and then to `await reply` before continuing.

### Motivation

The silent killer nature of this problem (which exhibits itself as an exception thrown by the underlying node http library) means that there is no clue as to the problem.

**Comment by Uzlopak** [comment]
I still think that we should cover this by an eslint plugin, like i proposed in #4434 

But implementing an eslint rule is not that trivial.

**Comment by mcollina** [comment]
We have been back-and-forth this quite a few times in the history of Fasfity. We added the warning you mentioned in https://github.com/fastify/fastify/pull/887, but then removed it in https://github.com/fastify/fastify/pull/2702.

> Are there any circumstances when a URL handler can return a promise which resolves as undefined? AIUI the only time would be if the handler used await reply already.

Unfortunately so. We need to support `return undefined` to send back an empty response to the caller, which is exactly what you are doing in your case.

---

I think the best way to fix is to wrap https://github.com/fastify/fastify/blob/f4a661295cf0685c0dd05497bafa05e23a012746/lib/reply.js#L597 in a try-catch, check for `ERR_HTTP_HEADERS_SENT`, log the error with a usable message and stop processing. That logged message could even include a link to the doc.

**Comment by johnspackman** [comment]
> We have been back-and-forth this quite a few times in the history of Fasfity. We added the warning you mentioned in https://github.com/fastify/fastify/pull/887, but then removed it in https://github.com/fastify/fastify/pull/2702.

That's a shame - that error checking is exactly what IMHO is needed here, and would save end users like me a *lot* of man hours and frustration.

> in a try-catch, check for ERR_HTTP_HEADERS_SENT, log the error with a usable message and stop processing

That would work, although one of my concerns was whether one of the many hooks (from our app or the plugins) could be deleting the payload - eg if `onSend` hook does not return the payload, again we get undefined.  That would be a bug, but it is also not trapped and leaves us wandering through all the code (including third party plugin modules) looking for problems.

> Unfortunately so. We need to support return undefined to send back an empty response to the caller

Is it possible that those use cases are rare?  EG @Eomm suggested an option like `allowEmpty: true` which could be false by default.  It could mean that if the end user really wants to return `undefined` instead of `""`, then it's supported but otherwise it's flagged up with the URL and handler.

This would allow the `onSend` and other hooks to be similarly trapped.

**Comment by mcollina** [comment]
> That would work, although one of my concerns was whether one of the many hooks (from our app or the plugins) could be deleting the payload - eg if onSend hook does not return the payload, again we get undefined. That would be a bug, but it is also not trapped and leaves us wandering through all the code (including third party plugin modules) looking for problems.

We can even add the actual route doing this.

**Comment by mcollina** [comment]
Here is the PR: https://github.com/fastify/fastify/pull/4921

**Comment by johnspackman** [comment]
Hi,

Thank you for your email - I am unavailable, returning on August 8th
  
 For customers with extended support, please contact your IT department in the first instance, who will be able to pass on any questions to the appropriate person to handle your query in my absence.
  
 I will get back to you as soon as possible, but if you have an emergency support issue please describe your issue in detail in email and then send a text message to the mobile number you have for me.

Regards
John Spackman

**Comment by terminalqo** [comment]
Hi, what if I use `decorateReply` like this:
```javascript
```
