### ISSUE TITLE
 Fastify Break Version FastifyPluginCallback

### ISSUE THREAD

**Issue by GNURub** [fastify/fastify#4915]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

`4.19.1`

### Stopped working in version

`>=4.19.2`

### Node.js version

20.3.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

23.04

## Overview:
When attempting to register the fastify-multer plugin in a Fastify application, a type error occurs, preventing the code from compiling. The error is related to the compatibility of the plugin callback function and the required parameter types.

## Error Details:
The error message indicates that the argument passed to the register method, specifically the `FastifyPluginCallback`, is causing the type mismatch. The expected parameter types for the `FastifyPluginCallback` are either `FastifyPluginCallback<PluginOptions>, FastifyPluginAsync<PluginOptions>, Promise<{ default: FastifyPluginCallback<PluginOptions>; }> or Promise<...>`. However, the provided argument is of type `FastifyPluginCallback<PluginOptions, Server<typeof IncomingMessage, typeof ServerResponse>, FastifyTypeProviderDefault, FastifyBaseLogger>`.

Further analysis of the error message reveals that the parameter named instance in the callback function has a type mismatch. The expected type for `instance` is `FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>`, but the provided `instance` has the type `FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>`. The error specifically mentions that the `childLoggerFactory` and `setChildLoggerFactory` properties are missing in the provided `instance` object.

### Steps to Reproduce

To reproduce this error, follow these steps:

1. Set up a Fastify application.
2. Attempt to register the fastify-multer plugin using the register method.
3. Observe the error message indicating the type mismatch and the missing properties in the instance object.

### Expected Behavior

The plugin should be successfully registered without any type errors, allowing the application to continue functioning as expected.

**Comment by Uzlopak** [comment]
We should first review, merge and publish https://github.com/fastify/fastify-plugin/pull/218
and then check if this issue is still existing. 

fastify-plugin was not passing Logger as GenericType. Maybe fixing this in fastify-plugin,
will fix this issue too.

**Comment by BrendenInhelder** [comment]
Hey @Uzlopak and @GNURub I tested the fastify-multer plugin and I believe it is functioning properly now.
Here is the basic file I used to test the plugin:
```
const Fastify = require('../fastify')

const fastify = Fastify()
const multer = require('fastify-multer')

fastify.register(multer.contentParser)

fastify.listen({
  host: 'localhost',
  port: 3000
}, (err) => {
  if (err) {
    console.error('Error starting server:', err)
    process.exit(1)
  }
  console.log('Server is running on http://localhost:3000')
})

fastify.get('/', async function (request, reply) {
  reply.code(200).send({ data: 'home page' })
})

fastify.post('/post/:id', async function (request, reply) {
  const { id } = request.params
  reply.code(201).send({ data: `${id}` })
})

fastify.put('/put/:id', async function (request, reply) {
  const { id } = request.params
  reply.code(200).send({ data: `${id}` })
})

fastify.delete('/delete/:id', async function (request, reply) {
  const { id } = request.params
  reply.code(204).send({ data: `${id}` })
})

fastify.post('/upload', async (request, reply) => {
  // Access the uploaded files via `request.files`
  const files = request.files
  reply.send({ message: 'Files uploaded successfully' })
})
```
Here is the terminal after running the file (I just edited integration/server.js):
![image](https://github.com/fastify/fastify/assets/96445076/f851709d-54b5-4013-9170-f84ee5986330)

Also, I did a basic curl with the readme file just to see if anything breaks:
![image](https://github.com/fastify/fastify/assets/96445076/3b57f8ea-8f94-4ce6-ae54-02bb9d75b764)

I know I have not provided any comprehensive testing but I saw this issue and thought I would try it out in case the new fastify-plugin version 4.5.1 fixed the issue.
