### ISSUE TITLE
Accepting file streams

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#492]
I am trying to accept a file stream using fastify and I only get `HTTPError: Response code 415 (Unsupported Media Type)` in response.
Here's simple code to reproduce this:
```js
// server.js
const fastify = require('fastify')();
fastify.post('/', (req, res) => {
  console.log(req);
  res.send('ok');
});
fastify.listen(8080);

// client.js
const fs = require('fs');
const got = require('got');
fs.createReadStream('package.json').pipe(got.stream.post('http://localhost:8080'));
```

The code above works perfectly fine with e.g. hapi.js.
I see a ton of examples (and tests) of sending a stream back to client, but none for accepting one - is that even possible with fastify?

I've also tried adding content type parser from example but that doesn't help:
```js
fastify.addContentTypeParser('*', function (req, done) {
  var data = ''
  req.on('data', chunk => { data += chunk })
  req.on('end', () => {
    done(data)
  })
})
```

**Comment by jsumners** [comment]
What is the content type being sent by your `POST` request?

**Comment by yamalight** [comment]
@jsumners headers sent by got are as follows:
```js
{
  headers:
   { 'user-agent': 'got/8.0.0 (https://github.com/sindresorhus/got)',
     'accept-encoding': 'gzip,deflate',
     host: 'localhost:8080',
     connection: 'close',
     'transfer-encoding': 'chunked' },
}
```

**Comment by yamalight** [comment]
This behaviour is also reproducible with the following test:
```js
test(`${upMethod} - input-validation data stream`, t => {
  t.plan(2)
  sget({
    method: upMethod,
    url: 'http://localhost:' + fastify.server.address().port + '/',
    body: fs.createReadStream(path.join(__dirname, '/input-validation.js'))
  }, (err, response, body) => {
    t.error(err)
    t.strictEqual(response.statusCode, 200)
  })
})
```

**Comment by allevo** [comment]
Hi,
  sorry for the delay.
Truly, the above test has the same behaviour of [this](https://github.com/fastify/fastify/blob/master/test/custom-parser.test.js#L240) where the `Content-type` is not defined.

The stream does not have anything to do with this behaviour: the `Content-type` header is relative to the type of the body content.
`Content-type` header should always be set even if you are using the stream.

In your example, a possible content type could be `application/javascript` or `text/javascript`.
If you'd like to handling a javascript file, please consider to read fastify [ContentTypeParser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md) documentation.
Adding a custom content-type parser should be fit for you.

If you are a limited list of a possible content type, consider to add a single content type parser for each of them. Anyway a "catch all" parser is always possible.

**Comment by yamalight** [comment]
@allevo as I mentioned in the original post - adding "catch all" parser doesn't help - you'll still get 415 😞 
Also, AFAIK `Content-type` header is not mandatory and should default to `application/octet-stream` as defined [per spec](https://tools.ietf.org/html/rfc1945#section-7.2.1)

**Comment by jsumners** [comment]
A little more recent than 1.0:

https://tools.ietf.org/html/rfc2616#section-7.2.1
> Any HTTP/1.1 message containing an entity-body SHOULD include a
   Content-Type header field defining the media type of that body. If
   and only if the media type is not given by a Content-Type field, the
   recipient MAY attempt to guess the media type via inspection of its
   content and/or the name extension(s) of the URI used to identify the
   resource. If the media type remains unknown, the recipient SHOULD
   treat it as type "application/octet-stream".

**Comment by yamalight** [comment]
So, the field _is_ mandatory, but content sent without it should still be treated as `application/octet-stream` which doesn't seem to be the case for fastify currently

**Comment by allevo** [comment]
@yamalight  Sorry my bad. I'll investigating... and thank you for the report!

**Comment by yamalight** [comment]
@allevo let me know if there's any way I can help - will be happy to!

**Comment by allevo** [comment]
@yamalight oh, yeah!
If you are ok, please open a PR! But... consider that `fastify` team has already discussed the `application/octet-stream` fallback or add the "catch all" by default and has already choosen not to include in `fastify`.

Anyway, with your "catch all" contentTypeParser, the test should pass.

**Comment by yamalight** [comment]
@allevo sounds like you already have a different approach in mind - so I'll leave that to you as it feels like it's probably going to take longer to explain it to me :)

I've just tried adding catch-all parser to tests and they still fail. So there's either a bug in the docs (and the code for catch-all parser I've posted above) or in the code related to that bit of code.

**Comment by yamalight** [comment]
@allevo @jsumners I've made a simple test case in glitch (web playground) that you can try out for yourself:
http://glitch.com/edit/#!/fastify-stream-bug

**Comment by yamalight** [comment]
Just tried adding `'Content-Type': 'application/octet-stream'` header - still getting same `HTTPError: Response code 415 (Unsupported Media Type)` response 😞
