### ISSUE TITLE
`hasPlugin` does not check outer scopes

### ISSUE THREAD

**Issue by MeowningMaster** [fastify/fastify#4925]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.20.0

### Node.js version

18.16.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

`hasPlugin` does not check outer scopes for registered plugins

### Steps to Reproduce

```
import fastify from 'fastify'
import fastifyPlugin from 'fastify-plugin'

const server = fastify()

const pluginCallback = (server, options, done) => {
    done()
}
const pluginName = 'awesome-plugin'
const plugin = fastifyPlugin(pluginCallback, {name: pluginName})

await server.register(plugin)

await server.register(async (server) => {
    const hasPlugin = server.hasPlugin(pluginName)
    console.log(hasPlugin) // prints: false

    const hasPluginWorkaround =
    server[Symbol.for('registered-plugin')]
        .includes(pluginName)
    console.log(hasPluginWorkaround) // prints: true
})
```

### Expected Behavior

`hasPlugin` should be `true`

**Comment by metcoder95** [comment]
Hey 👋 
Thanks for the report! Indeed, seems like a bug. It looks like we are not respecting the chain of plugins registered within the parent instance when creating a child context.
Although it might not be 100% reliable accordingly to different conditions of how the plugins are being registered, the best effort can be made.

Would you like to send a PR?

**Comment by MeowningMaster** [comment]
Does my workaround solution good for PR?
```
server[Symbol.for('registered-plugin')]
        .includes(pluginName)
```

I think we should first investigate what logic lays behind `Symbol('fastify.pluginNameChain')` and `Symbol('registered-plugin')`

**Comment by metcoder95** [comment]
I suggest you to take a look at the `hasPlugin` method first: https://github.com/fastify/fastify/blob/b31b1b48a148e8fae4d65a7b8eb2d271389d02db/fastify.js#L314

There is where the logic we are looking for starts

**Comment by JonathanAlbertMorales** [comment]
` hasPlugin: function (name) {
            return this[kPluginNameChain].includes(name) || this[pluginUtils.registeredPlugins].includes(name)
    },`
I think this would be it.
