### ISSUE TITLE
Support use of Ajv configuration methods

### ISSUE THREAD

**Issue by zenflow** [fastify/fastify#493]
Currently it is not possible to configure the Ajv instance using instance methods like [`ajv.addFormat`](https://github.com/epoberezkin/ajv#addformatstring-name-stringregexpfunctionobject-format---ajv) or [`ajv.addKeyword`](https://github.com/epoberezkin/ajv#addkeywordstring-keyword-object-definition---ajv), or using extensions like [`ajv-keywords`](https://github.com/epoberezkin/ajv-keywords) or [`ajv-errors`](https://github.com/epoberezkin/ajv-errors), *without making ajv a direct dependency of my app and using `fastify.setSchemaCompiler`*.

I'd like to avoid making ajv a direct dependency of my app, since it is already a dependency included with fastify.

This is basically the same issue as #186, except not limited to options/parameters passed to the `Ajv` constructor. I'd also like to be able to use the many instance methods for configuring ajv.

**Comment by delvedor** [comment]
Hi, thank you for checking out Fastify!
You can pass some custom option to the Ajv instance just by passing `ajv` as option to the Fastify constructor:
```js
const fastify = require('fastify')({
  ajv: {
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: true
  }
})
```
Checkout the [docs](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#schema-compiler)!

If you want to customize even more the validation library you can use the `setSchemaCompiler` api, which accepts a custom validator.
We have chosen to not allow the user to heavily customize the internal Ajv instance, and expose just the `setSchemaCompiler` api to allow further modifications.

Unfortunately it appears that is not well documented, would you mind to send a pr? :)

**Comment by zenflow** [comment]
@delvedor Thanks for your response. I've looked at #167, #187 and #253, and I still can't understand why allowing this kind of configuration (without resorting to setSchemaCompiler) should not be allowed.

It makes perfect sense that you would want to avoid leaking Ajv's API through fastify; if Ajv is swapped out for something else in the future, it would cause breaking changes. 

But considering that an `ajv` option has been implemented regardless (so there will be breaking changes if Avj is swapped out), I see no harm in allowing unlimited configuration of Ajv.

**Most** configuration can be done through Ajv's options, but **some** of it can not.. particularly [`ajv.addKeyword`](https://github.com/epoberezkin/ajv#addkeywordstring-keyword-object-definition---ajv) and [`ajv.addSchema`](https://github.com/epoberezkin/ajv#addschemaarrayobjectobject-schema--string-key---ajv). Also decorators like like [`ajv-keywords`](https://github.com/epoberezkin/ajv-keywords) or [`ajv-errors`](https://github.com/epoberezkin/ajv-errors) cannot be applied through any of Ajv's options; we need temporary access to the Ajv instance to do that.

IMHO fastify should give direct access to all of Ajv's configuration, or none at all.

Why not give access to the rest of Ajv's configuration directly with the following functional API?

```js
const fastify = require('fastify')({
  ajv: (Ajv, defaultOptions) => {
    return require('ajv-keywords')(new Ajv({ ...defaultOptions, ...myCustomOptions }))
      .addKeyword(require('./example-keyword'))
      .addSchema(require('./example-schema.json'));
  }
})
```

I suspect this request will continue to come up: https://github.com/fastify/fastify/issues/520#issuecomment-357531366
