### ISSUE TITLE
Required headers always result in validation error

### ISSUE THREAD

**Issue by sceccotti89** [fastify/fastify#4935]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.18.0

### Stopped working in version

4.19.0

### Node.js version

18.14.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.14.1 (c)

### 💥 Regression Report

Updating fastify to version 4.21.0 mandatory headers always result in validation error.

### Steps to Reproduce

1. install fastify: `npm i fastify@4.21.0`
2. define a route with required header and send a request with that header defined (see example below)
3. response will be `422` instead of `200`

This schema definition fails trying to validate a request with a required header:

```js
{
  method: 'GET',
  url: '/test',
  schema: {
    headers: {
      type: 'object',
      properties: {
        key: { type: 'string' }
      },
      required: ['key']
    },
    response: {
      200: {}
    },
  },
  handler: (_req, res) => res.status(200).send()
}
```

### Expected Behavior

No validation issue

**Comment by mcollina** [comment]
I cannot reproduce:

```js
const app = require('./fastify')({ logger: true });

app.route({
  method: 'GET',
  url: '/test',
  schema: {
    headers: {
      type: 'object',
      properties: {
        key: { type: 'string' }
      },
      required: ['key']
    },
    response: {
      200: {}
    },
  },
  handler: (_req, res) => res.status(200).send()
})

app.listen({ port: 3000 })
```

```
➜ curl -v -H 'key: something' http://localhost:3000/test
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /test HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.88.1
> Accept: */*
> key: something
>
< HTTP/1.1 200 OK
< content-length: 0
< Date: Fri, 28 Jul 2023 11:15:02 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
<
* Connection #0 to host localhost left intact
```

```
➜  curl -v -H key=something http://localhost:3000/test
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /test HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=utf-8
< content-length: 122
< Date: Fri, 28 Jul 2023 11:17:28 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
<
* Connection #0 to host localhost left intact
{"statusCode":400,"code":"FST_ERR_VALIDATION","error":"Bad Request","message":"headers must have required property 'key'"}%
```

**Comment by sceccotti89** [comment]
@mcollina Sorry you're right. To reproduce the error you have to use an uppercased header.
Probably it's related to this PR https://github.com/fastify/fastify/pull/4906 as already reported in the review.

**Comment by Uzlopak** [comment]
If we would allow case insentive validation, then i think it would become very slow. Better just define lowercase

**Comment by sceccotti89** [comment]
Unfortunately I cannot define the header as lowercased because the endpoint using it is exposed as a webhook for a third-party company. I can survive with the workaround I put in place but it's definitely not ideal.

**Comment by Uzlopak** [comment]
Maybe it is worth to manipulate the swagger document directly by using the transform option of fastify swagger ui.

**Comment by mcollina** [comment]
headers come down as lowercased by Node.js, so there is little we can do here.
I'm not sure why it worked before.

**Comment by Eomm** [comment]
Could you provide an example that works with 4.18 and breaks with 4.21?
Are you using the `requestIdHeader` option too?
Do you use some ajv plugin?
How is the weather of your server's country? 😄

Adding an example would avoid my silly questions 🤣

**Comment by climba03003** [comment]
> Unfortunately I cannot define the header as lowercased because the endpoint is exposed as a webhook for a third-party company.

Why? Validation always on lowercase for the headers because it is how the headers given by `node.js`.

If it is only concern on the documentation, why can't you use the `transform` method? https://github.com/fastify/fastify-swagger#transform

**Comment by sceccotti89** [comment]
@climba03003 my last comment contains a repoducible example. As I xplained there I was using a "customized" version of ajv.
But that's doesn't matter anymore because setting the header as lowercase in the schema solved the problem.

**Comment by climba03003** [comment]
>  As I xplained there I was using a "customized" version of ajv.

No, the result is the same for all version you mentioned using your script. 
So, I ask for which version cause regression and the actual script that can reproduce the problem.
