### ISSUE TITLE
Error: Timeout was reached 30s

### ISSUE THREAD

**Issue by hoanghiep1x0** [fastify/fastify#4939]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

1.0.0

### Node.js version

18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Description

Error: Timeout was reached.
setting in serve requestTimeout: 60000  not working

### Steps to Reproduce

```
module.exports = {
  disableRequestLogging: true,
  logger: true,
  ajv: {
    customOptions: {
      removeAdditional: 'all'
    }
  },
  requestTimeout: 60000
}
```

### Expected Behavior

I expect response timeout to increase to not 30s and return Error Error: Timeout was stopped

**Comment by Uzlopak** [comment]
are you really using fastify 4.2.0? latest is 4.20.0

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by hoanghiep1x0** [comment]
@Uzlopak Yes is it.

package json :

 "fastify": "^4.2.0",
 "fastify-cli": "^4.2.0"

**Comment by hoanghiep1x0** [comment]
@mcollina Hello.
I don't have the code available at the moment because my code checks the logic like this: access an internet route of a particular website, for example a story page. I scan all data by user-submitted url. In that url there are many pagination. I have to use crawl to click on each link and scan all the urls in that website, for example, there are 20 pages, it runs all 20 pages and returns the results. It took me almost 2 minutes = 120s initially for it to scan all the data.
I tried different settings to increase the duration but it didn't work. I'm using insomnia on macos to send data and the results always count to 30s and it shows the above message.
My code is not yet available to simulate the crash because it has a lot of stuff inside.

**Comment by climba03003** [comment]
> I tried different settings to increase the duration but it didn't work. I'm using insomnia on macos to send data and the results always count to 30s and it shows the above message.

You have some misunderstanding on the option. 
Request Timeout do not timeout the response, it is used to prevent long staling body from the user.

I am suggest you to use `.listen` directly and isolate the problem to `fastify` only.

**Comment by climba03003** [comment]
I double checked the default configuration of `Insomnia` and I believe it is the problem of `Insomnia`. 
So, closing the issue.

![image](https://github.com/fastify/fastify/assets/23028015/13af48eb-36ce-4745-93c4-7773a0049542)

I you believe it is the problem of `fastify`, please show the configuration of `Insomnia` or use other software like `curl` for testing.
