### ISSUE TITLE
Fastify returns empty 200 response when using sequelize

### ISSUE THREAD

**Issue by LeGeek01** [fastify/fastify#4940]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.29.5

### Stopped working in version

4.0.0

### Node.js version

20.2.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10 Pro x64 22H2

### 💥 Regression Report

Fastify returns a 200 response with type "octet-stream" and an empty result without knowing why. This happens with the use of sequelize and the `async` argument. Without this `async` and annotating what depends on it, the code works fine. This same code works in version 3, and no longer works from v4.0.0.
We tried several versions of sequelize, without success.

### Steps to Reproduce

Here is the code: https://pastebin.com/anMse2zK (note that we're french developer, so the errors messages are in french). The async that's we need to remove is the first, at line 1.
If the validator at the beginning isn't passed, the error is correctly returned. After, there is this 200 code with no body.

Sequelize v6.32.1

### Expected Behavior

The return is as expected

**Comment by Uzlopak** [comment]
See
https://fastify.dev/docs/latest/Reference/Routes#promise-resolution

You are not returning the response.

**Comment by LeGeek01** [comment]
can you explain so why the error at the validator is returned but not others?

**Comment by climba03003** [comment]
> can you explain so why the error at the validator is returned but not others?

It just racing condition and it is hard to tell which one will be executed first without deeply understand the code inside `sequelize`.
If you need to guarantee the response from fastify always waiting for `reply.send`, please return the `reply` object.
Or you may choose to use `try - catch` wrapper instead of `.catch` chaining.
