### ISSUE TITLE
Object support in querystring validation

### ISSUE THREAD

**Issue by darkterra** [fastify/fastify#4957]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Possibility to validating objects in query strings => `?foo={bar:0} # URL-encoded: ?foo=%7Bbar%3A0%7D`

I tried different possibilities, but I either get the error described below in the example or fastify considers having another property _(Ex: `?projection.filename=1`)_
See: https://medium.com/raml-api/objects-in-query-params-173d2712ce5b

### Motivation

Validating objects in query strings _(like: `?foo={bar:0} # URL-encoded: ?foo=%7Bbar%3A0%7D`)_ either has a bug or is a missing feature ?

Because if I parse the parameter at the 'preValidation' hook level everything works fine :
```js
if (typeof request.query?.projection === 'string') {
  request.query.projection = JSON.parse(request.query.projection);
}
```

But I see several problems using this "patch".

Firstly even if the number of characters that can be transmitted in 'query' is limited compared to the data that can be transmitted in 'body' with the verb 'POST ', I find it a shame to have to go through a function (JSON.parse()) which is much more demanding and slower than 'fast-json-stringify' used by default by fastify.

Moreover, if my schema evolves, I will have to take these changes into account at the hook level. It's not 'dry'.

### Example

```js
const HOST = '0.0.0.0';
const PORT = 3000;

const fastify = require("fastify")({ logger: true });

// Hook to see how we received the data.
fastify.addHook('preValidation', (request, reply, done) => {
  console.log('preValidation hook');
  console.log('request.query: ', request.query);
  console.log('request.query?.projection: ', request.query?.projection);
  console.log('typeof request.query?.projection: ', typeof request.query?.projection);

  done();
});

// Def of input validation for the request
const listImgV = {
  description: 'List all images',
  tags: ['images'],
  operationId: 'ListImages',
  query: {
    type: 'object',
    properties: {
      filter: {  type: 'object'},
      projection: {
        type: 'object',
        properties: {
          _id: { type: 'string' },
          filename: { type: 'number' },
          length: { type: 'number' },
          chunkSize: { type: 'number' },
          uploadDate: { type: 'string' },
          metadata: { type: 'object' }
        },
        additionalProperties: false
      },
      sort: { type: 'object' },
      limit: { type: 'number' },
      skip: { type: 'number' }
    },
    additionalProperties: false
  }
};

// Def of handler function who manage the input request with input data
async function listImgC (request, reply) {
  const { query: { filter, projection, sort, limit, skip }} = request;

  // Some process (with received data above) before response
  return { message: `List of ${images?.length || 0} Image(s)` };
}

// Define the new GET route with schema and handler above
fastify.route({ method: 'GET', url: '/v1/media/', schema: listImgV, handler: listImgC });

// Start the fastify server
const start = async () => {
  try {
    await fastify.listen({ PORT, HOST });
    console.log(fastify.printRoutes());
  }
  catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
}

start();


// ----------------------------------------------------------------------------------------------
// If a call this route with one query parameter (projection: {"filename": 1}) encoded => http://localhost:3000/v1/media?projection=%7B%20%22filename%22%3A%201%20%7D

// There is the fastify response :
{
  "statusCode": 400,
  "code": "FST_ERR_VALIDATION",
  "error": "Bad Request",
  "message": "querystring/projection must be object"
}

// And here we can see what we get in the 'preValidation' hook :
preValidation hook
request.params:  {}
request.query:  Empty <[Object: null prototype] {}> { projection: '{ "filename": 1 }' }
request.query?.projection:  { "filename": 1 }
typeof request.query?.projection:  string
```

As explained before the example, given that we indeed receive a string and that it is decoded, all that remains is to parse it when we indicate to the schema that we are receiving a data of the `object` type _(like here my 'projection' property)_ so that it is valid.

I think the best solution to not lose performance and stay 'dry' is for the internal validation step to parse the received serialized JSON _(if the type for this property is 'object')_ before calling AJV to validate or not the type of data received.

**Comment by Uzlopak** [comment]
Why arent you setting your favorite qs parser by setting the `querystringParser` option when initializing your fastify instance?

Of course the default querystring parser does not know what `foo.bar` means.

**Comment by darkterra** [comment]
Hello ! Thank you for your reply.
I don't know a qs parser, if you recommend one, I'd love to try it :)
However, don't you think the default querystring parser deserves to handle serialized "objects" like this example  `?foo={bar:0} # URL-encoded: ?foo=%7Bbar%3A0%7D` ?

**Comment by Eomm** [comment]
> don't you think the default querystring parser deserves to handle serialized "objects" like this example

No - it has an impact on performance.
EG: The majority of applications I worked on do not send JSON objects via query string so I would pay for your use case. It is not fair tho

> I don't know a qs parser, if you recommend one, I'd love to try it :)

There is a nice code example in the doc to change the default query string parser with qs:

https://fastify.dev/docs/latest/Reference/Server/#querystringparser

**Comment by Uzlopak** [comment]
Just a remark:

You could alway implement your own qs parser. The query string is just a string after the `?` character in the url till the `#` symbol for indicating an anker.

So you could basically write a custom querystring parser which uses JSON stringify and parse and encodes special characters, especially `?` and `#`, and use it as you qs parser.
