### ISSUE TITLE
Error in body validation

### ISSUE THREAD

**Issue by JbIPS** [fastify/fastify#497]
Hi, 

I'm defining the following schema in my route:
```js
{
  body: {
    type: 'object',
    required: ['services'],
    properties: {
      services: {
        type: 'array',
        items: {type: 'string'}
      }
    }
  }
}
```
and try to send:
```js
{
  services: [1,2]
}
```
and it worked like a charm. I looked at ajv (v5.5.0) in a separate project but the validation throw an error (`should be string`). Looks like Fastify is using the same version so I don't understand why it do not reject the request.

BTW, other validations (no `services` or not an `Array`) works fine.

**Comment by allevo** [comment]
Hi!
 thanks for using `fastify`!
Currently fastify uses an internal ajv instance. Building that instance, we're using `coerceTypes` options described [here](https://www.npmjs.com/package/ajv#coercing-data-types)

**Comment by JbIPS** [comment]
I'm sorry, I didn't see this line 😅 :

> Note that Ajv will try to coerce the values to the types specified in your schema type keywords, both to pass the validation and to use the correctly typed data afterwards.

Thank you!
