### ISSUE TITLE
Response return date-time for date string when schema format is date

### ISSUE THREAD

**Issue by tzelon-cypator** [fastify/fastify#4975]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.21.0

### Node.js version

20.5.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4.1

### Description

Hey there, 
using the following schema `response: { 200: { date: { type: "string", format: "date" } } }`
If we respond with `{ date: new Date() }` the response will be YYYY-MM-DD but if we respond with `{date: new Date().toISOString() }` the response is full date time. 

I would expect it to be YYYY-MM-DD or to throw an error that string is not Date object. 

Is that a bug or the expected behavior? 

Thank you. 

### Steps to Reproduce

https://codesandbox.io/p/sandbox/boring-dijkstra-vgxnzk?welcome=true

### Expected Behavior

Return `YYYY-MM-DD` in both cases.

**Comment by jsumners** [comment]
https://github.com/fastify/fast-json-stringify/blob/920317fc218cc84d94e10c5ca1e03da398bce261/README.md?plain=1#L168
