### ISSUE TITLE
Losing types when use register function.

### ISSUE THREAD

**Issue by MosheYamini** [fastify/fastify#4976]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.21.0

### Plugin version

2.2.2

### Node.js version

2.2.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

When i register my route in the main fastify instance everything works fine.
```typescript
export const server = Fastify({
  logger: true,
}).withTypeProvider<JsonSchemaToTsProvider>();

server.get(
  "/api/something",
  {
    schema: {
      querystring: {
        type: "object",
        properties: {
          foo: { type: "number" },
        },
        required: ["foo"],
      },
    } as const,
  },
  (request, reply) => {
    const { foo } = request.query; // <--- Everything fine here
  }
);
```
But when I try to register the route, it loses the type safety.

### Steps to Reproduce

```typescript
// server.ts
server.register(something, { prefix: "/api" });

// route.ts
export async function something(fastify: FastifyInstance) {
  fastify.get(
    "/something",
    {
      schema: {
        querystring: {
          type: "object",
          properties: {
            foo: { type: "number" },
            bar: { type: "string" },
          },
          required: ["foo", "bar"],
        },
      } as const,
    },
    async (request, reply) => {
        const { foo } = request.query;  // <---- Property 'foo' does not exist on type 'unknown'
    }
  );
```

**Comment by climba03003** [comment]
You are declaring the `fastify` as `FastifyInstance` in your example and it is expected to lost the type provider function.
The main reason is that TypeScript do not have ability to pass the generic argument and infer by others separate functions.

So, you are either required to pass all the required generic parameter to `FastifyInstance` or re-map the `fastify` with `.withTypeProvider` inside every plugin.
Note that re-map required to store as new variable.

**Comment by MosheYamini** [comment]
Thanks. Can you provide a quick code snippet for both cases?

**Comment by jgburet** [comment]
Surprisingly this does not work:
```ts
const server = fastify({}).withTypeProvider<TypeBoxTypeProvider>();
type FastifyInstance = typeof server;

async function router(f: FastifyInstance) {
    f.get(
        '/:name',
        { schema: { params: Type.Object({ name: Type.String() }) } },
        ({ params }) => { return { params } }
    )
}

server.register(router)
```
the type of `params` is `unknown` even though the type of `f` corresponds to your directive.

Like alternatively suggested, you need to add `f.withTypeProvider<TypeBoxTypeProvider>();` again at the beginning of your function.

I think this should be documented within the [plugins](https://fastify.dev/docs/latest/Reference/Plugins/) page.
