### ISSUE TITLE
Can't deploy contribution environment

### ISSUE THREAD

**Issue by Rantoledo** [fastify/fastify#4981]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi guys,

I'm trying to set up my environment for contribution.
I've been following this guide: 
(https://github.com/fastify/fastify/blob/main/docs/Guides/Contributing.md)
And successfully accomplished most of the steps.
Successfully deployed my vscode environment but failed to replace the "open default settings", because it's a read-only file.
I thought to replace the "open user settings" instead with the provided JSON.
```
{
    "[javascript]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint",
        "editor.codeActionsOnSave": {
            "source.fixAll": true
        }
    },

    "workbench.colorCustomizations": {
        "statusBar.background": "#178bb9"
    }
}
```
Then, the next step is to run "npm i" in the terminal, but the problem is that there's no package.json file there.

What am I missing here?

**Comment by metcoder95** [comment]
Are you located within `fastify` project?

**Comment by Rantoledo** [comment]
I'm located in /Applications/VSCodeFastify folder

**Comment by Rantoledo** [comment]
Oh, I think I get it...
Need to fork and clone `fastify` right?
Are there any `fastify` specific guidelines for this process?

**Comment by metcoder95** [comment]
Yes, the `npm i` can only be done within the `fastify` project, as it contains the `package.json` and other files necessary to run.

>Are there any fastify specific guidelines for this process?

You can take a look at: https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md for more information about the PR process, in a formal manner.
To create a PR, fork the project, and clone your forked repository. After you made the changes, and push them to your forked repository, GH automatically will allow you to open a PR to the `upstream` (fastify's repo) 🙂

**Comment by Rantoledo** [comment]
Thanks, 

> You can take a look at: https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md for more information about the PR process, in a formal manner. To create a PR, fork the project, and clone your forked repository. After you made the changes, and push them to your forked repository, GH automatically will allow you to open a PR to the `upstream` (fastify's repo) 🙂

Yes, I'm aware of the PR process.
Once I'll deploy the environment completely I'll close this issue.
