### ISSUE TITLE
add an `isPluginAvailable` method on FastifyInstance

### ISSUE THREAD

**Issue by bienzaaron** [fastify/fastify#4987]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'd like to optionally register a plugin within another plugin, but _only_ if a parent encapsulation context has not already registered the plugin.

### Motivation

Specifically, I have a plugin that internally registers `@fastify/cookie` - I want to register this within a plugin _only_ if it's not already registered in a parent context.

If I try to do something like this now:
```
const Fastify = require('fastify');
const fastifyCookie = require('@fastify/cookie');

const fastify = Fastify();
fastify.register(fastifyCookie);

// imagine this bit is inside a separate plugin published to npm, etc
fastify.register(async (child) => {
  if (!child.hasPlugin('@fastify/cookie')) {
    fastify.register(fastifyCookie);
  }
});

fastify.ready().then(() => { fastify.listen() });


```

I get:
```
/Users/me/scratch/abc/node_modules/fastify/lib/decorate.js:41
    throw new FST_ERR_DEC_ALREADY_PRESENT(name)
    ^
FastifyError [Error]: The decorator 'cookies' has already been added!
    at decorateConstructor (/Users/me/scratch/abc/node_modules/fastify/lib/decorate.js:41:11)
    at Object.decorateRequest (/Users/me/scratch/abc/node_modules/fastify/lib/decorate.js:123:3)
    at plugin (/Users/me/scratch/abc/node_modules/@fastify/cookie/plugin.js:154:11)
    at Plugin.exec (/Users/me/scratch/abc/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/Users/me/scratch/abc/node_modules/avvio/plugin.js:272:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_DEC_ALREADY_PRESENT',
  statusCode: 500
}


```

I'd like to propose adding a new method, `isPluginAvailable`, which is similar to `hasPlugin`, but will return `true` if the current context _or_ any parent context has already registered the plugin. This is different from `hasPlugin`, which only returns true if the current context has registered the plugin.

I have considered using a workaround, like checking if a decorator added by the plugin is already available, but this seems like an implementation detail specific to the particular plugin being registered. It also wouldn't work if the plugin doesn't register any decorators.

I could also ask users of my plugin to register `@fastify/cookie` and not register it in my plugin, but this feels like a clunky user experience to me, for those that are not directly using `@fastify/cookie` in their code already.

### Example

same as the above code sample, but replace `hasPlugin` with `isPluginAvailable`:
```
if (!child.isPluginAvailable('my-plugin')) {
  fastify.register(myPlugin);
}
```

**Comment by metcoder95** [comment]
Hey! I believe this should be covered within `fastify.hasPlugin`. I think there should be a bug that is causing us to not find the plugin already registered within the parent context.

cc: @Eomm

**Comment by climba03003** [comment]
Can you install `npm install fastify/fastify#main` to see if it solved?

It is actually duplicated of https://github.com/fastify/fastify/issues/4925 and solved already.
But it is not released yet, so I closed it for now and if the main branch is not solved.
I am happy to reopen the issue.
