### ISSUE TITLE
Unpredictable behavior using multiple plugins with prefix and running with Bun

### ISSUE THREAD

**Issue by sher** [fastify/fastify#4991]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.21.0

### Plugin version

Bun 0.8.0

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Darwin 22.5.0 arm64 arm

### Description

As I am not sure if the problem is with Bun or fastify, asking the same question on both repositories.

Creating a simple server with 3 plugins with prefix, some routes become nested, even though they should use the root-level server instance.

```ts
import fastify, { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

await start();

async function start() {
  const server = fastify();

  await server.register(plugin, { prefix: '/en' });
  await server.register(plugin, { prefix: '/ja' });
  await server.register(plugin, { prefix: '/fr' });
  
  console.log(server.printRoutes());
}

async function plugin(server: FastifyInstance) {
  server.get('/', async function handler(request: FastifyRequest, reply: FastifyReply) {
    return reply.send({ ok: true })
  });
}
```
```sh
bun-fastify $ bun index.ts    
└── /
    ├── en (GET, HEAD)
    │   └── / (GET, HEAD)
    └── ja (GET, HEAD)
        └── / (GET, HEAD)
            └── fr (GET, HEAD)
                └── / (GET, HEAD)
```

Only if I add an **explicit delay** `wait(1000)` somewhere between the plugin registration methods, the output of `console.log(server.printRoutes())` is as expected.

```ts
...
async function start() {
  const server = fastify();

  await server.register(plugin, { prefix: '/en' });
  await server.register(plugin, { prefix: '/ja' });

  // added some delay
  await wait(1000);
  await server.register(plugin, { prefix: '/fr' });
  
  console.log(server.printRoutes());
}
...

// added wait util
async function wait(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
```
```sh
bun-fastify $ bun index.ts
└── /
    ├── en (GET, HEAD)
    │   └── / (GET, HEAD)
    ├── ja (GET, HEAD)
    │   └── / (GET, HEAD)
    └── fr (GET, HEAD)
        └── / (GET, HEAD)
```

The actual output, and plugin prefix levels, is incorrect. The last plugin with prefix `/fr` was passed not the top level server instance, but the one that was passed to the plugin with the prefix `/ja`.

### Steps to Reproduce

```sh
bun-fastify $ bun index.ts    
└── /
    ├── en (GET, HEAD)
    │   └── / (GET, HEAD)
    └── ja (GET, HEAD)
        └── / (GET, HEAD)
            └── fr (GET, HEAD)
                └── / (GET, HEAD)
```

### Expected Behavior

```sh
bun-fastify $ bun index.ts
└── /
    ├── en (GET, HEAD)
    │   └── / (GET, HEAD)
    ├── ja (GET, HEAD)
    │   └── / (GET, HEAD)
    └── fr (GET, HEAD)
        └── / (GET, HEAD)
```

**Comment by Eomm** [comment]
> As I am not sure if the problem is with Bun or fastify, asking the same question on both repositories.

Since it works like a charm on node.js it is a bun.

As tentative:

```
  server.register(plugin, { prefix: '/en' });
  server.register(plugin, { prefix: '/ja' });
  await server.register(plugin, { prefix: '/fr' });
```

Closing per https://github.com/fastify/fastify/issues/2173
We are not yet supporting the bun runtime yet.
