### ISSUE TITLE
The request is stuck in a pending state when return undefined in async route handler

### ISSUE THREAD

**Issue by cage1618** [fastify/fastify#4999]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.22.0

### Plugin version

4.5.1

### Node.js version

18.12.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1 

### Description

The request is stuck in a pending state when return undefined in async route handler

### Steps to Reproduce
```
const fastify = require('fastify');

fastify.get('/', async (request, reply) => {
  // not doing anything or return void(0)
})
```

### Expected Behavior

normal response with 200 statusCode

**Comment by Uzlopak** [comment]
See:
https://fastify.dev/docs/latest/Reference/Routes#promise-resolution

**Comment by cage1618** [comment]
Does this behavior was new in 4.22? 
I remember this has always been there, but before 4.22, when I didn't return any value in the async handler, it would respond normally.

**Comment by climba03003** [comment]
> Does this behavior was new in 4.22?

No, it is always the same in `fastify@4`
