### ISSUE TITLE
Supplying a logger removes the stream of the logger

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#50]
```js
'use strict'

const log = require('pino')()
const fastify = require('fastify')({logger: log})

log.info('pino is working')

fastify.get('/', (req, reply) => reply.send({hello: 'world'}))

fastify.listen(8000, (err) => {
  if (err) throw err
  // the next line will fail because `pino-http` removes the stream from `log`
  log.info('server started: http://localhost:%s', fastify.server.address().port)
})
```

**Comment by delvedor** [comment]
The logger option purpose is not intended for setting a custom logger, but for pass some options to the internal `pino-http` instance.
Have a look [here](https://github.com/fastify/fastify/blob/master/fastify.js#L24-L26) and [here](https://github.com/fastify/fastify/blob/v0.11.1/docs/Logging.md) :)

**Comment by delvedor** [comment]
Probably you can try with:
```js
const log = require('pino')()
const fastify = require('fastify')({
  logger: {
    logger: log
  }
})
```
[pino-http options](https://github.com/pinojs/pino-http#api)

**Comment by jsumners** [comment]
Then I think it should support passing in a custom logger. I didn't include it in the example, but I would further use `req.log` in request handlers. This means I only have to configure one logger to use it in both manners: regular logs and request logs.

**Comment by jsumners** [comment]
The `{logger: {logger: log}}` is ugly, but it works.

**Comment by delvedor** [comment]
Yeah, I agree.
I would like to ask to the *'pino guy'* @mcollina: any idea on how design a nicer api?

**Comment by delvedor** [comment]
Ops! Sorry :P

Anyway, PR are welcome!

**Comment by mcollina** [comment]
thanks @jsumners!!

**Comment by delvedor** [comment]
#52
