### ISSUE TITLE
Using REST with Socket - already listening!?

### ISSUE THREAD

**Issue by kristianmandrup** [fastify/fastify#500]
I guess would require two separate instances of `fastify` then?

```js
const {
  fastify
} = require('./socket-conn')

let fastSocket
fastify.ready(() => {
  console.log('fastify ready: open socket conn')
  fastify.ws
    .on('connection', socket => {
      console.log('connection', {
        socket
      })
      fastSocket = socket
      socket.on('message', msg => socket.send(msg)) // Creates an echo server
    })
})

fastify.listen(34567)

// setup routes

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

**Comment by delvedor** [comment]
You can't call two times `listen`.
Your websocket server will listen in the same port of your REST routes. *(same port but different protocol, `http` and `ws`)*
For example:
```js
'use strict'

const fastify = require('fastify')()

fastify.register(require('fastify-ws'))

fastify.ready(err => {
  if (err) throw err

  fastify.ws.on('connection', socket => {
    console.log('connection')
    socket.on('message', msg => {
      console.log(msg)
      socket.send(msg)
    })
  })
})

fastify.get('/hello', (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log('listening')
})
```
Now open you browser and navigate to `http://localhost:3000/hello` and you will get `{ hello: 'world' }` as response. In the same page, open the developers tools and type the following:
```js
const host = location.origin.replace(/^http/, 'ws')
const ws = new WebSocket(host)
ws.onmessage = msg => console.log(msg.data)
ws.send('WebSockets are awesome!')
```
As you can see, everything is working. Checkout also the server logs ;)

**Comment by kristianmandrup** [comment]
Thanks :) I will try your demo/example shortly

**Comment by gj** [comment]
Hey @kristianmandrup, did you get it working?

**Comment by akhilshastri** [comment]
How can I map REST call to Websocket..?

**Comment by mcollina** [comment]
What do you mean?

**Comment by akhilshastri** [comment]
If you see with SailsJS, a controller can be used as a REST service with HTTP or with Websocket; I am trying to implement with fastify.. Any clue on how to start ..?

**Comment by mcollina** [comment]
I think you have to combine fastify.inject (the method) with fastify-websocket, and develop a new plugin on top.

**Comment by akhilshastri** [comment]
Thanks, I am very new fastify, will try this
