### ISSUE TITLE
docs:  Thenable is not according to A+ spec

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#5005]
> I actually dont like it either. Also it is lacking of unit tests so i also dont see what the purpose of these changes are
> 
> But @piranna has a point. In the comments to then we have 
> 
> https://github.com/fastify/fastify/blob/95f9fa5abc105397a715fc376c3a6e704181d2e1/lib/reply.js#L429
> 
> And according to the spec https://promisesaplus.com/#point-40 `then must return a promise [[3.3]`
> 
> But we are not returning a Promise, we are returning void. So we maybe have to remove the reference to the definition to clarify we dont follow the A+ spec. Or we actually return a Promise and fulfill the spec.
> 
> But I am not saying, that this PR is the correct implementation.
> 
> _Originally posted by @Uzlopak in https://github.com/fastify/fastify/issues/4152#issuecomment-1193310968_
>             

Task:

Search for references to the promiseaplus.com in the source code and check if the documented behaviour of the corresponding Object is fitting A+ spec or not. If not adapt code to A+ spec or correct the documentation.

**Comment by metcoder95** [comment]
Haven't checked yet, but it will have side-effects to fully move to A+ spec?

**Comment by Uzlopak** [comment]
The issue is, that not always being full A+ compatible is desirable.

E.g. the original issue arose because of reply-class is documented to be full A+ compatible. 

Problem is, that per http request we create a reply instance (obviously) and adding a .catch handler to be fully A+ compatible can make the reply instanciation and catch handling slower. 

So you are potentially adding a perf bottleneck just to be A+ spec compliant despite you are basically never using the .catch() feature.

Iirc the fastify instance itself claims to be A+ compatible i think. In that case a perf bottleneck is maybe neglectable, as it is only instanciated once.

**Comment by Eomm** [comment]
I can't read where we claim to be spec compliant

https://fastify.io/docs/latest/Reference/Reply/#thenfulfilled-rejected

Do we want it?

**Comment by jsumners** [comment]
```
❯ rg aplus
lib/reply.js
456:// - https://promisesaplus.com/ for the definition of thenable

docs/Reference/Plugins.md
137:`fastify` being a [Thenable](https://promisesaplus.com/).

docs/Reference/Reply.md
895:- https://promisesaplus.com/ for the definition of thenables
```

**Comment by jsumners** [comment]
The link is accurate:

https://promisesaplus.com/#point-7
> “thenable” is an object or function that defines a then method.

**Comment by mcollina** [comment]
The doc is incorrect, as the fastify instance is not working according to that spec.
