### ISSUE TITLE
fastify.listen handles null cb inconsistently.

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify#501]
fastify.listen has two ways to call cb, directly from fastify.ready or through the `wrap` function called by server.listen.  We should just always use the `wrap` so we consistently support fastify.listen(0) - without an address or callback.

The wrap function removes itself from the `error` event listener, this is harmless in the path where the callback to fastify.ready has not yet added the `error` event listener.

**Comment by jsumners** [comment]
Actually, `fastify.ready` is not strictly equivalent to `fastify(0, cb)`. As an example from a project I am working on:

```js
server.ready((err) => {
  if (err) {
    log.error('could not boot server: %s', err.message)
    log.debug(err.stack)
    log.info('aborting startup')
    process.kill(process.pid, 'SIGTERM')
    process.exit(1)
  }
  server.listen(
    config.get('server').port,
    config.get('server').address,
    serverListenCB
  )
})
```

The difference is that `ready` is fired once all plugin registrations have occurred. In my situation, I need to know that has happened _before_ I fire up the listener.

**Comment by coreyfarrell** [comment]
The goal of this report is for the following two lines of code to effectively do the same thing:
fastify.listen(8080, err => { if (err) throw err; });
fastify.listen(8080);
