### ISSUE TITLE
Unpackaged size growth between v4.22.0 and v4.22.1

### ISSUE THREAD

**Issue by niels-bosman** [fastify/fastify#5011]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Something I noticed while taking a look at Fastify versions on npm is that the unpacked size grew significantly between `4.22.0` and `4.22.1` (which should probably only include fixes?).

`4.22.0`: 2.25MB (https://www.npmjs.com/package/fastify/v/4.22.0)
`4.22.1`: 3.16MB (https://www.npmjs.com/package/fastify/v/4.22.1)

Maybe something to take a look at, seems a bit off.

**Comment by metcoder95** [comment]
Thanks for the report!
I wouldn't worry too much about the size, it seems that the last release was packed by accident with the outcome of the testing run:
![image](https://github.com/fastify/fastify/assets/10200776/482b20f6-de0e-49b0-a52f-0e567d80904e)

**Comment by niels-bosman** [comment]
@metcoder95 Ah okay, good. Just funny to know that there will be an additional ~1000GB extra data downloaded from the package with the 12.000.000 weekly downloads 😆.

**Comment by metcoder95** [comment]
Hopefully `npm` will block the publish if that happens 😂

**Comment by Eomm** [comment]
cc @mcollina

**Comment by mcollina** [comment]
Good spot, shipped v4.22.2.
