### ISSUE TITLE
Error when trying to reference a schema starting with # in response

### ISSUE THREAD

**Issue by sinedied** [fastify/fastify#5023]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.22.2

### Node.js version

18.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6.8

### Description

When trying to use this shared schema:
```ts
  fastify.addSchema({
    $id: '#httpError',
    type: 'object',
    properties: {
      statusCode: { type: 'number' },
      code: { type: 'string' },
      error: { type: 'string' },
      message: { type: 'string' },
    },
  });
```
in a response, ie:
```
schema: {
      response: {
        500: { $ref: '#httpError' },
      },
    },
```
I get this error:
```
FastifyError [Error]: Failed building the serialization schema for POST: /indexes, due to error Cannot find reference "#httpError"
```

Referencing this schema in the body properties works fine, but not in the response.

If I rename the schema id to `httpError` without the `#` prefix it works without error too.

### Steps to Reproduce

1. Add a shared schema in the app, with a `#` prefix:
```ts
  fastify.addSchema({
    $id: '#httpError',
    type: 'object',
    properties: {
      statusCode: { type: 'number' },
      code: { type: 'string' },
      error: { type: 'string' },
      message: { type: 'string' },
    },
  });
```

2. Reference this schema in a route for a response, example:
```ts
fastify.post('/', {
    schema: {
      response: {
        500: { $ref: '#httpError' },
      },
    },
    handler: async function (request, reply) {  },
  });
```
3. Build and try to run the app

### Expected Behavior

No error

**Comment by jsumners** [comment]
Please review:

+ https://json-schema.org/understanding-json-schema/structuring.html
+ https://json-schema.org/draft/2020-12/json-schema-core.html#name-the-id-keyword

`#` indicates a fragment identifier.

**Comment by climba03003** [comment]
It is working as expected following the spec.
