### ISSUE TITLE
request.routeOptions.config.url doesn't exist

### ISSUE THREAD

**Issue by tacozilla** [fastify/fastify#5031]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.0

### Plugin version

n/a

### Node.js version

n/a

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

n/a

### Description

When using `request.routerPath`, Fastify emits a deprecation warning [1]:

> You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.config.url" instead. Property "req.routerPath" will be removed in `fastify@5`.

The docs also were updated to point to this, but I believe the correct property should be `request.routeOptions.url`. Not only does it make more sense since URL isn't passed in as part of the config object to a route, but if no config is passed, `request.routeOptions.config.url` won't exist.

Could someone please verify if this is correct or if I'm misunderstanding?

[1] https://github.com/fastify/fastify/blob/main/lib/warnings.js#L34

### Steps to Reproduce

```mjs
// Import the framework and instantiate it
import Fastify from 'fastify'
const fastify = Fastify({
  logger: true
})

// Declare a route
fastify.get('/', async function handler (request, reply) {
  console.dir(request.routeOptions); // config doesn't exist but url does
  return { hello: 'world' }
})

// Run the server!
try {
  await fastify.listen({ port: 3000 })
} catch (err) {
  fastify.log.error(err)
  process.exit(1)
}
```

### Expected Behavior

I believe the docs and deprecation warning need to be updated to point at `request.routeOptions.url`.

**Comment by Eomm** [comment]
the `config` is not enumerable:

```
console.dir(request.routeOptions.config)

const x = Object.getOwnPropertyDescriptors(request.routeOptions)
console.dir(x)
```

<img width="241" alt="image" src="https://github.com/fastify/fastify/assets/11404065/3a1304bb-4b00-4f26-9754-425584829b56">

**Comment by tacozilla** [comment]
@Eomm - Can you please reopen this, unfortunately your response doesn't actually address the issue.

I gave a bad example; I wasn't intending to imply it was enumerable, but rather that `url` is a top-level key of `routeOptions`. The docs show both, so it isn't clear which is the actual correct one.

* The actual code adds `url` as a top-level key to `routeOptions`: https://github.com/fastify/fastify/blob/main/lib/request.js#L187
* The docs show a code example referencing `request.routeOptions.url` as well: 
![docs](https://github.com/fastify/fastify/assets/141896687/54c7bcb1-3c04-4c6d-bf86-275c81702cda)
* The deprecation note in the docs and in code, however, point people to `request.routeOptions.config.url`.

Can you clarify why the deprecation notes point people to `request.routeOptions.config.url` instead of `request.routeOptions.url`?

**Comment by Uzlopak** [comment]
Ok. Ok. I messed up, when I wrote the deprecation warning.

:)

**Comment by tacozilla** [comment]
@Uzlopak - I think there's one spot in the docs as well:

![docs2](https://github.com/fastify/fastify/assets/141896687/37a64ed8-bdf9-47dc-96cb-37f2467b898c)

Otherwise, thanks for the quick response!
