### ISSUE TITLE
reply.context.config is marked as deprecated in typescript but documented

### ISSUE THREAD

**Issue by twalling** [fastify/fastify#5033]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.0

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Mac

### Description

According to the docs: https://fastify.dev/docs/latest/Reference/Routes#config

One should access the request config object via `reply.context.config` but this is marked as deprecated in the typescript types.

```
/**
 * Route context object. Properties defined here will be available in the route's handler
 */
export interface FastifyContext<ContextConfig = ContextConfigDefault> {
  /**
   * @deprecated Use Request#routeConfig or Request#routeSchema instead
   */
  config: FastifyContextConfig & FastifyRouteConfig & ContextConfig;
}
```

### Steps to Reproduce

Try to add a response hook which accesses `reply.context.config`

```
fastify.addHook('onResponse', async (request, reply) => {
    if (reply.context.config['metrics']) {
      const status = reply.statusCode < 400 ? 'success' : 'error';
      logMetric(getRouteKey(request, status), reply);
    }
  });
```

**Comment by giuliowaitforitdavide** [comment]
@mcollina @Eomm @metcoder95 @jsumners it seems that this problem is due to the fact that request and reply refers to the same context type inside the `types/context.d.ts` file, but it's not clear to me if we want to keep the `context.config` property deprecate for the FastifyRequest and FastifyReply objects or if just for the first one: I think I have the solution in both cases, I need to be sure what we would like to achieve

**Comment by jsumners** [comment]
Please do not ping me for TypeScript things.

**Comment by metcoder95** [comment]
> @mcollina @Eomm @metcoder95 @jsumners it seems that this problem is due to the fact that request and reply refers to the same context type inside the `types/context.d.ts` file, but it's not clear to me if we want to keep the `context.config` property signed as deprecated for both the FastifyRequest and FastifyReply objects or just for the first one: I think I have the solution in both cases, I need to be sure what we would like to achieve

The context deprecation is intentional, `<request|reply>.routeOptions` should be the one to be used instead; `context` might not be publicly available by next major (I think we haven't settle down this).
Instead, the documentation should be changed, as it does not reflects its deprecation and the usage of `routeOptions` instead

**Comment by giuliowaitforitdavide** [comment]
> > it seems that this problem is due to the fact that request and reply refers to the same context type inside the `types/context.d.ts` file, but it's not clear to me if we want to keep the `context.config` property signed as deprecated for both the FastifyRequest and FastifyReply objects or just for the first one: I think I have the solution in both cases, I need to be sure what we would like to achieve
> 
> The context deprecation is intentional, `<request|reply>.routeOptions` should be the one to be used instead; `context` might not be publicly available by next major (I think we haven't settle down this). Instead, the documentation should be changed, as it does not reflects its deprecation and the usage of `routeOptions` instead

The main thing here is that when using the reply.context object you expect a warning to be prompted, but in this case it does not prompt anything

**Comment by metcoder95** [comment]
I understood the contrary, maybe I'm wrong then, but wasn't the issue described that the `route.context` prompts on TS as deprecated but this isn't documented?

If it doesn't prompt, then we should make it prompt for now. Also, I just noticed that the description of the deprecation does not show the correct message of using `request.routeOptions` 😅

**Comment by giuliowaitforitdavide** [comment]
![Screenshot 2023-10-06 alle 16 08 51](https://github.com/fastify/fastify/assets/50294725/2e6a45fd-f476-422e-a02d-ecca2b0584de)
If I understood correctly what @twalling meant to say, TypeScript is correctly prompting the deprecation of the property (although with the wrong message that I'm gonna fix). But, when calling the server on localhost:3000, it does not print on the console the expected message "You are accessing the reuqest.config object which is deprecated excetera"
So I think I have to fix these two things, don't I? @metcoder95

**Comment by gurgunday** [comment]
> Also: how do we want to manage the access from the reply object to the request.context object? Do we want to mark as deprecated also that one and create a new property to accesso the request.routeOptions.config property?

Do you mean an access like `reply.request.context`? All access to `request.context` should be deprecated and emit warnings

**Comment by metcoder95** [comment]
>If I understood correctly what @twalling meant to say, TypeScript is correctly prompting the deprecation of the property (although with the wrong message that I'm gonna fix). But, when calling the server on localhost:3000, it does not print on the console the expected message "You are accessing the Request#config object which is deprecated [...]"

Got it, in that case yes; we have to fix those two things. Print the warning when accessing the property, and adjust the TS prompt to show the right message, as well as the documentation for Request/Reply (See [Request docs](https://fastify.dev/docs/latest/Reference/Request)).

>Also: how do we want to manage the access from the reply object to the request.context object? Do we want to mark as deprecated also that one and create a new property to accesso the request.routeOptions.config property?

This:
>Do you mean an access like reply.request.context? All access to request.context should be deprecated and emit warnings

Also, `routeOptions` already contains the `config` property (See [Request docs](https://fastify.dev/docs/latest/Reference/Request)).

**Comment by giuliowaitforitdavide** [comment]
Ok thank you, I'm gonna work on that
