### ISSUE TITLE
fs.createReadStream isn't working. "dest.on is not a function"

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [fastify/fastify#5038]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.22.2

### Node.js version

20.6.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.03 LTS

### Description

So when trying to send the read stream (createReadStream) it logs this error here:

```
{"level":50,"time":1694890984836,"pid":5190,"hostname":"user","reqId":"req-3","req":{"method":"GET","url":"/video/test.mp4","hostname":"192.168.178.32","remoteAddress":"127.0.0.1","remotePort":56796},"res":{"statusCode":500},"err":{"type":"TypeError","message":"dest.on is not a function","stack":"TypeError: dest.on is not a function\n    at Readable.pipe (node:internal/streams/readable:711:8)\n    at Object.<anonymous> (/home/user/server/index.js:75:8)"},"msg":"dest.on is not a function"}
```

### Steps to Reproduce

By clicking a `<div>` that works as a link, sets a `<video>` elements `src` attribute to a specific route.
I did a test to return the `fs.stat` and it works, so the route, and link works 100%.

```
app.get("/movies/:folder/:title", async (req, res) => {
        let {folder,title} = req.params
        title = decodeURI(title)
        folder = decodeURI(folder)

        let filePath = path.join(process.env.MOVIE_PATH, folder, title)

        let fileStat = await stat(filePath)

        let videoSize = fileStat.size
        let videoRange = req.headers.range

        if(videoRange){
                let parts = videoRange.replace(/bytes=/, "").split("-")
                let start = parseInt(parts[0], 10)
                let end = parts[1] ? parseInt(parts[1], 10) : videoSize-1
                let chunkSize = (end-start) + 1
                let file = createReadStream(filePath, {start, end})

                let header = {
                        'Content-Range': `bytes ${start}-${end}/${videoSize}`,
                        'Accept-Ranges': 'bytes',
                        'Content-Length': chunkSize,
                        'Content-Type': 'video/mp4'
                }

                res.headers(header)
                res.statusCode = 206


                file.pipe(res)
        } else {
                let header = {
                        'Content-Length': videoSize,
                        'Content-Type': 'video/mp4'
                }

                res.headers(header)
                res.statusCode = 200

                fs.createReadStream(moviePath).pipe(res)
        }

})
```

### Expected Behavior

Stream the video to the browser? Works with Express.

**Comment by Eomm** [comment]
> Stream the video to the browser? Works with Express.

Please, take a moment to read ["Why you should not say _«I will use X»_ to a Fastify maintainer"](https://gist.github.com/Eomm/4b72531ed9e2bdaefccf144ff9d7ce9a).

# +

Take the time to understand that Fastrify is not Express, and you need to study the differences:

- Buy my book: https://backend.cafe/the-fastify-book-is-out
- Read the article: https://dev.to/eomm/why-should-i-prefer-fastify-to-expressjs-44c4

> Fastify has its own Request and Reply objects that are built on top of the Node.js's `http.ClientRequest` and `http.ServerResponse`. This is more flexible because Fastify does not break the Node.js internals, and both can evolve without conflicting with each other. Express, instead, monkey patch those standard objects with an impact on the Node.js contributors that must be cautious to introduce new features because of Express!

So...

```diff
-fs.createReadStream(moviePath).pipe(res)
+fs.createReadStream(moviePath).pipe(res.raw)
```

**Comment by 4e576rt8uh9ij9okp** [comment]
> > Stream the video to the browser? Works with Express.
> 
> Please, take a moment to read ["Why you should not say _«I will use X»_ to a Fastify maintainer"](https://gist.github.com/Eomm/4b72531ed9e2bdaefccf144ff9d7ce9a).
> # +
> 
> Take the time to understand that Fastrify is not Express, and you need to study the differences:
> 
>     * Buy my book: https://backend.cafe/the-fastify-book-is-out
> 
>     * Read the article: https://dev.to/eomm/why-should-i-prefer-fastify-to-expressjs-44c4
> 
> 
> > Fastify has its own Request and Reply objects that are built on top of the Node.js's `http.ClientRequest` and `http.ServerResponse`. This is more flexible because Fastify does not break the Node.js internals, and both can evolve without conflicting with each other. Express, instead, monkey patch those standard objects with an impact on the Node.js contributors that must be cautious to introduce new features because of Express!
> 
> So...
> 
> ```diff
> -fs.createReadStream(moviePath).pipe(res)
> +fs.createReadStream(moviePath).pipe(res.raw)
> ```

Never said "I will use X" but you do you.

I've changed it to `.(res.raw)` and it looks like it's doing something in the logger but the video won't load in the browser.

```
{"level":30,"time":1695185671149,"pid":10697,"hostname":"user","reqId":"req-3ox","req":{"method":"GET","url":"/movies/test.mp4","hostname":"192.168.178.12","remoteAddress":"127.0.0.1","remotePort":33644},"msg":"incoming request"}
{"level":30,"time":1695185671149,"pid":10697,"hostname":"user","reqId":"req-3ox","res":{"statusCode":206},"responseTime":0.20128297805786133,"msg":"request completed"}
^C
```

**Comment by AlttiRi** [comment]
You just need to _return_ `res`.

https://github.com/fastify/fastify/issues/4412#issuecomment-1311199001
https://github.com/fastify/fastify/issues/5203#issuecomment-1849817511

**Comment by AlttiRi** [comment]
However, it works correctly only with
```js
    return reply.send(stream);
```
not with 
```js
    stream.pipe(reply.raw);
    return reply;
```

For unknown reason in this case headers (`Content-Length`, `Content-Type`) are not set.
