### ISSUE TITLE
`FastifySchema` type should include the `security` property

### ISSUE THREAD

**Issue by jclangst** [fastify/fastify#5039]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The `security` property should be added as optional to `FastifySchema` with the type outlined in the [openapi spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#securityRequirementObject) under `Security Requirement Object`.

### Motivation

This provides additional functionality to generated OpenAPI documentation and UIs surrounding how various routes are protected.

### Example

```
schema: {
  security: [{'cookie': []}]
} 
```

Today, this must be written as

```
schema: {
  security: [{'cookie': []}]
} as FastifySchema
```

**Comment by metcoder95** [comment]
For this kind of requirement, it is better if you use [`fastify-swagger`](https://github.com/fastify/fastify-swagger) as it provides `openapi` spec based on request/response schema definitions added for each route.
Fastify schemas are meant to follow [JSON Schema Spec](https://json-schema.org/specification.html) for validating incoming HTTP requests and its parts.

**Comment by jclangst** [comment]
Thanks for the direction! I do see in `fastify-swagger` that `FastifySchema` is extended [here](https://github.com/fastify/fastify-swagger/blob/master/index.d.ts) to accommodate the additional properties. 

Adding the following the project fixed the Typescript issue by importing that type declaration module:

```ts
// Required for extending the default fastify types with support for
// OpenAPI schema extensions
// @ts-ignore
import * as swagger from "@fastify/swagger";
```

Might be nice to add that to the docs for `fastify-swagger`, but I am closing out this issue.
