### ISSUE TITLE
docs: missing docs about warnings or deprecation warnings

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#5040]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I could not find any hints regarding deprecation warnings in the docs. 

After I added https://github.com/fastify/process-warning/pull/83 to extend the documentation regarding process-warning I think we should add similar information to the docs. I mean a paragraph about how to suppress warnings (on their own risk) would be good.

Also we could make an extra page about deprecation warnings. Similar to errors.md. We should note since which version a deprecation warning was introduced, and how you can update your code to avoid the deprecation warning. Benefit is also, that you could then just copy paste that for a migration guide. So everytime we introduce a deprecation warning, we just need to make sure that the deprecations.md (name pending) also has a new entry with proper information.

**Comment by mcollina** [comment]
Good idea!

**Comment by Uzlopak** [comment]
Good first issue?

**Comment by eugleenyc** [comment]
Is this being worked on? I can take a stab at it.
