### ISSUE TITLE
`FastifyPlugin` type deprecation notice in code JSdoc is unhelpful

### ISSUE THREAD

**Issue by loucadufault** [fastify/fastify#5044]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.7.x

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

The deprecation notice for `FastifyPlugin` added in https://github.com/fastify/fastify/pull/2350 is uninformative, and not easily actionable. 

It mentions to see `FastifyRegister`, which makes no mention of the `FastifyPlugin` or how to replace it.

It should instead mention to use `FastifyPluginCallback`, as a synchronous analog to `FastifyPluginAsync`.

For those without the context of the deprecation of `FastifyPlugin` being replaced with the `Async` and `Callback` variants, it is not evident which plugin type to use for the case of synchronous plugin registration. The use of the `Callback` variant is not obvious if one does not anticipate making use of the `done` callback (i.e. full synchronous plugin registration).

This is made worse by the fact the `FastifyPlugin` is still referenced in the docs:
https://fastify.dev/docs/latest/Reference/TypeScript/#fastifyfastifypluginoptions-rawserver-rawrequest-requestgeneric:~:text=Open%20index.d.ts%20and%20add%20the%20following%20code%3A

Although a more informative deprecation guide is provided for the entry https://fastify.dev/docs/latest/Reference/TypeScript/#fastifyfastifypluginoptions

### Steps to Reproduce

Use `FastifyPlugin` type when defining a plugin.

### Expected Behavior

Should clearly indicate the non-deprecated replacement(s), especially for synchronous use case.

**Comment by Uzlopak** [comment]
A PR would be welcome ;)

**Comment by loucadufault** [comment]
Yes, I will address in a few hours
