### ISSUE TITLE
Security Audit 

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5052]
[The OpenJS Foundation was granted funding by the Sovereign Tech Fund](https://openjsf.org/blog/2023/05/02/openjs-foundation-receives-major-government-investment-from-sovereign-tech-fund-for-web-security-and-stability/) to invest in projects and their security posture. A portion of that funding was dedicated to security audits, and projects that showed interest in participating were chosen to undergo the process. I volunteered Fastify.

Security audits are a powerful tool and exercise for helping open source projects improve their security posture. A security audit aims to engage security experts to collaborate with project maintainers to define a threat model, review code, and augment security tooling. The Fastify security audit would be performed by O

#### Background on Open Source Technology Improvement Fund, Inc: 

[Open Source Technology Improvement Fund, Inc or OSTIF,](https://ostif.org/) is a strategic partner to Linux Foundation and many other organizations and foundations. The nonprofit specializes in navigating and managing all aspects of a security audit from start to finish, and was engaged for the OpenJS audits. 

https://github.com/ostif-org/OSTIF

#### Background on Ada Logics: 

[Ada Logics](https://adalogics.com/) consists of security experts David Korczynski and Adam Korczynski, who have carried out thousands of hours of security audits and related work. They have extensive experience in security auditing and fuzzing, and have collaborated on numerous Linux Foundation projects. 

@AdamKorcz
@DavidKorczynski

## Logistics

The audit will be performed between now and the end of the year, aiming to publish the report in Q1 2024.

I've created a private channel on our discord. Please ping me there if you want to get added.

**Comment by Eomm** [comment]
I would like to be added

**Comment by gurgunday** [comment]
Me too! 😄

**Comment by RafaelGSS** [comment]
I'd like to be added

**Comment by Uzlopak** [comment]
Please also add me @mcollina

**Comment by metcoder95** [comment]
Me as well 🙂
