### ISSUE TITLE
Test log flaky

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#5059]
https://github.com/fastify/fastify/actions/runs/6289773425/attempts/1?pr=5058

The `file option` test is flaky - we should refactor a bit the `test/serial/logger.1.test.js` and spit it into smaller files as we did before.

This should reduce the flakiness

**Comment by giuliowaitforitdavide** [comment]
Ciao @Eomm 
I would like to work on this but I want to be sure I understood the request: the main thing here is that pipeline fails because of the timeout for a single test, so we want to split logger test files into smaller pieces, don't we?

If that's the case, I came up with an idea I would like to share with you: we could divide`logger.1.test.js` and `logger.0.test.js` into 5 files `logger.[i].test.js` containing tests divide by topic. I found that the main topics of these tests are:

- Response serialization 
    - Should use serializers from plugin and route
    - Should use serializers from instance fastify and route
    - Should use serializers inherit from contexts
    - The default 404 handler logs the incoming request
    - should serialize request and response
    - should not rely on raw request to log errors
    - should not throw error when serializing custom req
    - The logger should accept custom serializer

- Actual logging
    - should log the error if no error handler is defined
    - should log as info if error status code >= 400 and < 500 if no error handler is defined
    - should log as error if error status code >= 500 if no error handler is defined
    - should not log the error if error handler is defined and it does not error
    - reply.send logs an error if called twice in a row
    - should not log incoming request and outgoing response when disabled
    - should not log incoming request and outgoing response for 404 onBadUrl when disabled
    - defaults to info level
    - test log stream
    - test error log stream

- Logger instantiation
    - should create a default logger if provided one is invalid
    - can use external logger instance
    - expose the logger
    - Wrap IPv6 address in listening log message
    - Do not wrap IPv4 address
    - file option
    - should be able to use a custom logger
    - should throw in case a partially matching logger is provided
    - can use external logger instance with custom serializer
    - should throw in case the external logger provided does not have a child method

- Request Validation
    - The request id header key can be customized
    - The request id header key can be ignored
    - The request id header key can be customized along with a custom id generator
    - The request id header key can be ignored along with a custom id generator
    - The request id log label can be changed
    - should redact the authorization header if so specified

- Logger options
    - logger can be silented
    - Should set a custom logLevel for a plugin
    - Should set a custom logSerializers for a plugin
    - Should set a custom logLevel for every plugin
    - Should set a custom logSerializers for every plugin
    - Should override serializers from route
    - Should override serializers from plugin
    - Should increase the log level for a specific plugin
    - Should set the log level for the customized 404 handler
    - Should set the log level for the customized 500 handler
    - Should set a custom log level for a specific route
    - should pass when using unWritable props in the logger option

What do you think about this splitting?

**Comment by Eomm** [comment]
> What do you think about this splitting?

That would be great!
we could move them in a `test/log/` folder as well and name them without a aweful number as I did in past 😂

**Comment by giuliowaitforitdavide** [comment]
> > What do you think about this splitting?
> 
> That would be great! we could move them in a `test/log/` folder as well and name them without a aweful number as I did in past 😂

😂😂😂 thx for the feedback
Gonna work on that asap
