### ISSUE TITLE
Named parameter paths such as `/:path`, when the path is too long, the route cannot be hit and throws a 404.

### ISSUE THREAD

**Issue by Innei** [fastify/fastify#5066]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Node.js version

18.18.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Not care, macOS and Linux all reproduce

### Description

Named parameter paths such as `/:path`, when the path is too long, the route cannot be hit and throws a 404.

I has a route `/trpc/:path` and I get `/trpc/ConfigByKey,category.getCategoryOrDefaultById,category.getAllForSelector,post.related`

It works, return 200, no problem.

<img width="1157" alt="image" src="https://github.com/fastify/fastify/assets/41265413/b6178d4e-a94c-4eb2-ba4d-e274b3798a12">

Now, I increase the length of this path, for example `/trpc/ConfigByKey,category.getCategoryOrDefaultById,category.getAllForSelector,post.relatedttttttttttttttttttttttttttttttttttt`

Got 404, not found.

<img width="1405" alt="image" src="https://github.com/fastify/fastify/assets/41265413/fdfdd1fb-f04f-43a8-aea1-ebad485ebd4b">

### Steps to Reproduce

1. minimum repro https://stackblitz.com/edit/stackblitz-starters-kr4grf?description=A%20simple%20starter%20for%20using%20nodemon%20printing%20no%20messages%20in%20a%20terminal&file=index.js&title=Nodemon%20Starter

Code is:

```ts
/* eslint strict:"off" */
"use strict";

const fastify = require("fastify");

function build(opts) {
  const app = fastify(opts);

  app.all(`/trpc/:path`, (req, res) => {
    return res.send(req.params.path);
  });

  return app;
}
 

async function start() {
  const app = build({ logger: true });
  try {
    await app.listen(11111);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
}

if (require.main === module) {
  start();
}

```

`https://stackblitzstarterskr4grf-jahr--11111--744619a5.local-credentialless.webcontainer.io/trpc/ConfigByKey,category.getCategoryOrDefaultById,category.getAllForSelector,post.relatedttttttttttttttttttttttttttttttttttt`

### Expected Behavior

Should return 200 and hit the route

**Comment by jsumners** [comment]
https://fastify.dev/docs/latest/Reference/Server#maxparamlength
