### ISSUE TITLE
Cant listen to 0.0.0.0 in node 18

### ISSUE THREAD

**Issue by rluvaton** [fastify/fastify#5071]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Node.js version

18.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

when trying to send request to fastify server that listen to 0.0.0.0 it fails with ECONNREFUSED

in node 16.18.1 it does not happen

### Steps to Reproduce

Run this:

```js
import {fastify as Fastify} from "fastify";
import http from "node:http";

const fastify = Fastify({});
fastify.all('*', (req, reply) => {
    reply.send({});
});

await fastify.listen({
    port: 3009,
    host: '0.0.0.0',
});

console.log('fastify', fastify.server.address())

http.get({
    hostname: 'localhost',
    port: 3009,
    path: '/',
    agent: false,
}, (res) => {
    res.on('data', (d) => {
        console.log(d.toString());
    })
});
```

and you will get:
```
❯ node index.mjs
fastify { address: '0.0.0.0', family: 'IPv4', port: 3009 }
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:3009
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3009
}

Node.js v18.18.0
```

### Expected Behavior

to connect

**Comment by mcollina** [comment]
This is expected. You are listening to `0.0.0.0` which is an `IPv4` address, and you are connecting to `::1`, which is a IPv6 address. This is the reason why in Node.js v20 we added support for happy eyeballs.

You can run `node --dns-result-order=ipv4first bug.mjs` to restore the previous behavior.
