### ISSUE TITLE
Static url and parametric url

### ISSUE THREAD

**Issue by rabbitmeow** [fastify/fastify#508]
url: '/s' 
url: '/:filename'

Then both urls cannot match all urls beginning with 's'
Such as '/styles.css'

**Comment by rabbitmeow** [comment]
Well, except '/s'.

**Comment by delvedor** [comment]
Hi! Thank you for contributing!
It's an error in our router, I'm working on it :)

**Comment by rabbitmeow** [comment]
Thank you for your work.😋
