### ISSUE TITLE
Method 'HEAD' already declared for route - regression in 4.24.0

### ISSUE THREAD

**Issue by knolleary** [fastify/fastify#5089]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.0

### Node.js version

16.20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

With the 4.24.0 release, our application no longer starts due to an error:

```
Failed to start: Error: Method 'HEAD' already declared for route '/api/v1/devices/:/editor/proxy/*' with constraints '{}'
```

Our application makes two calls to `app.route` - the first handles GET requests that *could* be a WebSocket connection, the second handles all the other methods we need to cope with.

```
    app.route({
        method: 'GET',
        url: '/proxy/*',
        ...
    })

    app.route({
        method: ['POST', 'DELETE', 'PUT', 'HEAD', 'OPTIONS'],
        url: '/proxy/*',
        ...
    })
```

With 4.24.0, this second call is triggering the error. Previous versions worked fine.

### Steps to Reproduce

I will update with a link to a repo containing as minimal reproduction as I can create tomorrow.

I wanted to get the issue recorded quickly as it appears to be a regression in 4.24.0. Looking at PRs in the release, https://github.com/fastify/fastify/pull/5078 appears very relevant.

**Comment by mcollina** [comment]
cc @ivan-tymoshenko

**Comment by gurgunday** [comment]
I believe it is working correctly now

You need to set `exposeHeadRoute: false` when creating the GET route

**Comment by gurgunday** [comment]
Can you try the following when declaring the GET route?

```js
 app.route({
        method: 'GET',
        url: '/proxy/*',
        exposeHeadRoute: false,
        ...
    })
```

**Comment by mcollina** [comment]
If you invert the order of definitions you should be able to unpin it.

**Comment by ivan-tymoshenko** [comment]
Anyway it looks like a bug. From the code I see, fustily should remove a default `HEAD` handler and set a custom one. It should not throw. Will take a look tomorrow, if somebody will not solve this earlier.

**Comment by ivan-tymoshenko** [comment]
There is another small bug in the fastify.

**Comment by knolleary** [comment]
Thanks all for the fast responses. I can confirm that setting `exposeHeadRoute: false` has resolved it for us - decided that was a more explicit fix than relying on just the order the routes were registered that could be unknowingly changed in the future.

**Comment by mcollina** [comment]
> decided that was a more explicit fix than relying on just the order the routes were registered that could be unknowingly changed in the future.

It actually is the best choice.

**Comment by metcoder95** [comment]
> Anyway it looks like a bug. From the code I see, fastify should remove a default `HEAD` handler and set a custom one. It should not throw. Will take a look tomorrow, if somebody will not solve this earlier.

I recall was intended, but not remember why. Anyhow, I agree that `fastify` should check if the `HEAD` route already stored was made in auto, and remove it to make the new one take highest priority.

**Comment by ivan-tymoshenko** [comment]
I found the problem. Working on it.
