### ISSUE TITLE
Use `fmw.hasRoute` for `fastify.hasRoute`

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fastify#5092]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

If we do this, this will be a breaking change so it should be done in the next major.
Having that this is a breaking change, it might be also a reasonable solution to keep it as it, but IMHO `fastify.hasRoute` doesn't work correctly/doesn't make much sense in current implementation.

**Comment by mcollina** [comment]
In what sense hasRoute does not work?

**Comment by ivan-tymoshenko** [comment]
> In what sense hasRoute does not work?

1. `fastify.hasRoute` searches route using a `fmw.find` method.
2. `fmw.find` designed to find a route by url received from a client.
3. `fastify.hasRoute` IMHO should search for route using a path that was used to set the route.

**Comment by Uzlopak** [comment]
@dancastillo 

This landed in the next branch, right? So can we close this issue?
