### ISSUE TITLE
question: why beforeHandler is not called?

### ISSUE THREAD

**Issue by dsun9** [fastify/fastify#510]
Hi, please help, thanks

const fastify = require('fastify')();
fastify.register(require('./routes/jwtRoutes'));
fastify.listen(process.env.PORT || 80, function (err) {
  if (err) throw err
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
})

...jwtRoutes...

const opts = {
	beforeHandler: function (request, reply, done) {
		var token = request.headers.authorization
		var decoded = jwt.verify(token,SECRET)
		console.log(decoded)
		done()
	}
};

async function jwtRoutes (fastify, opts, next) {
  fastify.get('/users/:userId', getData)
  next()
}

**Comment by delvedor** [comment]
Hi!
You are not passing the `opts` object to the route declaration.
```js
const opts = {
  beforeHandler: function (request, reply, done) {
    var token = request.headers.authorization
    var decoded = jwt.verify(token,SECRET)
    console.log(decoded)
    done()
  }
}

async function jwtRoutes (fastify, opts) {
  fastify.get('/users/:userId', opts, getData)
}
```
I suggest you to have a look at our [routes documentation](https://github.com/fastify/fastify/blob/master/docs/Routes.md) :)

Feel free to reopen if you have more questions :)

**Comment by dsun9** [comment]
per your suggestion, I added opts like below, but still debugger does not stop and console did not log

fastify.get('/users/:userId', opts, getData)

**Comment by delvedor** [comment]
My bad, you should change the name of the `opts` object, otherwise the one of the plugin function will overwrite the top level `opts`.
```js
const opts = {
  beforeHandler: function (request, reply, done) {
    var token = request.headers.authorization
    var decoded = jwt.verify(token,SECRET)
    console.log(decoded)
    done()
  }
}

async function jwtRoutes (fastify, options) {
  fastify.get('/users/:userId', opts, getData)
}
```

**Comment by delvedor** [comment]
You are using the wrong name as option object:
```js
const {getgetData} = require('../controllers/indexController');
const jsonwebtoken = require("jsonwebtoken");
const SECRET = ...;

const jwtoptions = {
  beforeHandler: function (request, reply, done) {
    var token = request.headers.authorization;
    var decoded = jwt.verify(token,SECRET);
    console.log(decoded);
    done()
  }
};

async function jwtRoutes (fastify, options) { // <= this should be just options
  fastify.get('/users/:userId', jwtoptions, getData)
}

module.exports = jwtRoutes
```

**Comment by dsun9** [comment]
Thanks very much! my bad
