### ISSUE TITLE
Fastify Schema Validation is not working as expected with minProperties: 1 + additionalProperties: false

### ISSUE THREAD

**Issue by lifeiscontent** [fastify/fastify#5104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.2

### Node.js version

18.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

full breakdown can be found here: https://github.com/lifeiscontent/fastify-invalid-schema-issue

### Steps to Reproduce

full breakdown can be found here: https://github.com/lifeiscontent/fastify-invalid-schema-issue

### Expected Behavior

full breakdown can be found here: https://github.com/lifeiscontent/fastify-invalid-schema-issue

**Comment by Eomm** [comment]
> I've talked with the creator of TypeBox and during our testing we found that the schema is valid in Ajv so the source of the bug must be related to fastify and how its handling the schema.

Fastify does not do any fancy to the input schemas - Fastify is an ajv user.

I can replicate the issue with AJV only: https://runkit.com/embed/2y52wixsv0of

<img width="705" alt="image" src="https://github.com/fastify/fastify/assets/11404065/86a41a5d-8d3d-46b3-95ca-9aa9639a9776">
