### ISSUE TITLE
hooks doesn't wait for async handlers

### ISSUE THREAD

**Issue by its-dibo** [fastify/fastify#5114]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.0

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22

### Description

for the following hook
```
 app.addHook('onRoute', (opts) => {

  // this works
 // opts.schema = { /* schema object */ }

// but this doesn't work
import('./myschema').then(m=> opts.schema=m.default)

// also using async/await doesn't work
})
```
it seems that fastify doesn't wait until the hook fullfils

.

**Comment by mcollina** [comment]
onRoute is a synchronous hook, so it does not wait for anybody. Essentially it's there for data collection.
