### ISSUE TITLE
Sending a Uint8Array as a view on a larger ArrayBuffer sends the whole ArrayBuffer

### ISSUE THREAD

**Issue by achingbrain** [fastify/fastify#5118]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

20.8.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.5.1

### Description

I have a `RouteHandlerMethod` that sends a `Uint8Array` that is a view on part of a `ArrayBuffer`: 

```js
fastify.route({
    method: 'GET',
    url: '/path',
    handler: async (request, reply) => {
      const arr = new ArrayBuffer(100)
      const ui8 = new Uint8Array(arr, 0, 10)

      return reply.send(ui8)
    }
})
```

On the client side:

```js
const req = await fetch('/path')
const body = await req.arrayBuffer()

console.info(body.byteLength) // 100   <-- should only be 10 bytes not 100
```

This is quite bad as the array buffer offset past `10` could be random unrelated memory depending on the source of the `Uint8Array`/`ArrayBuffer`.

Node.js Buffers work as expected:

```js
fastify.route({
    method: 'GET',
    url: '/path',
    handler: async (request, reply) => {
      const arr = new ArrayBuffer(100)
      const buf = Buffer.from(arr, 0, 10)

      return reply.send(buf) // only sends 10 bytes
    }
})
```

### Steps to Reproduce

See above.

### Expected Behavior

Only the first 10 bytes should be sent:

```js
const req = await fetch('/path')
const body = await req.arrayBuffer()

console.info(body.byteLength) // 10
```

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Uzlopak** [comment]
I have the feeling that is anyway bad to use an ArrayView?!

**Comment by metcoder95** [comment]
Hmm, not sure of the decision behind it; but I imagine that it is to avoid duplicating the buffer and then saving memory. However, it is a valid concern, as the `Buffer` itself extends up to the `ArrayView` not the `TypedArray`.

**Comment by achingbrain** [comment]
You don't always control the allocation of `Uint8Array`s (or `Buffer`s for that matter), for example if it's done by a third party module they might use an `ArrayBuffer` internally for efficiency and then return a view on that `ArrayBuffer`.

https://github.com/fastify/fastify/blob/9b8a7825dc033887d293549e40284284bf27c5a5/lib/reply.js#L167

Does `payloadToSend` have to be a `Buffer`?  Would a `Uint8Array` suffice?

```js
const payloadToSend = payload instanceof Uint8Array ? payload : Buffer.from(payload.buffer) 
```

This will pass `Buffer`s and `Uint8Array`s through since `Buffer` extends `Uint8Array` since node 4 or something.

If it must be a `Buffer` we can convert `Uint8Array`s to `Buffer`s without copying as:

```js
const payloadToSend = Buffer.isBuffer(payload) ? payload : Buffer.from(payload.buffer, payload.byteOffset, payload.byteLength) 
```

**Comment by mcollina** [comment]
The latter proposal would be perfect.

**Comment by metcoder95** [comment]
+1 on the latter as well

**Comment by SgtPooki** [comment]
Just FYI, looking into this, and the latter is causing an error at https://github.com/fastify/fastify/blob/9b8a7825dc033887d293549e40284284bf27c5a5/lib/reply.js#L616-L618 which means we also have to change `typeof payload !== 'string' && !Buffer.isBuffer(payload)` to `typeof payload !== 'string' && !Buffer.isBuffer(payload) && !(payload instanceof Uint8Array)` or similar.

will check if other things break.
