### ISSUE TITLE
Basic typescript types are broken in 4.24.x

### ISSUE THREAD

**Issue by danomatic** [fastify/fastify#5122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.23.2

### Stopped working in version

4.24.0

### Node.js version

any

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Ventura 13.6

### 💥 Regression Report

TypeScript types are broken in the latest version. The most basic app possible has breaking types:

```ts
server.get('/', async (request, reply) => {
    return { hello: 'world' };
});
```

<img width="1060" alt="Screenshot 2023-10-24 at 9 56 33 AM" src="https://github.com/fastify/fastify/assets/459337/b9326808-c9d4-4254-b9ad-37ff27d2e75d">
<img width="951" alt="Screenshot 2023-10-24 at 9 56 20 AM" src="https://github.com/fastify/fastify/assets/459337/5131e5f9-2a39-4a1e-ab7c-2bf569cad219">
<img width="557" alt="Screenshot 2023-10-24 at 9 56 06 AM" src="https://github.com/fastify/fastify/assets/459337/098f1218-46e9-42cc-81e4-50c7276efc70">

### Steps to Reproduce

Just create any barebones TypeScript app with Fastify:

```ts
import fastify from 'fastify';

const server = fastify();

server.get('/', async (request, reply) => {
    return { hello: 'world' };
});
```

### Expected Behavior

Clean type checks

**Comment by Uzlopak** [comment]
Provide a repo to clone as mvce please

**Comment by DemonHa** [comment]
@danomatic If you are using typescript v4 or earlier, please switch to v5. See related issue: [here](https://github.com/fastify/fastify/issues/5103)

**Comment by danomatic** [comment]
> @danomatic If you are using typescript v4 or earlier, please switch to v5. See related issue: [here](https://github.com/fastify/fastify/issues/5103)

I attempted with TypeScript v4 and v5, but maybe I did something wrong

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by danomatic** [comment]
I briefly installed TS v5 in my project and the issue didn't go away, but it's a yarn workspaces project and the setup isn't very simple. For now it resolved the issue for me just to roll back the Fastify version to 4.23.x. I already lost a lot of working hours figuring this out, so I can't justify taking more time to try and create an example for you beyond what I put in this ticket. If you are confident that it's a TS version issue I'll try again another time. Feel free to close this if you'd like.

**Comment by salmankhalid-plt** [comment]
I am using TS ^5.2.2 and fastify ^4.24.3 and i am getting getting error with `server.get` it says 
```
Property 'get' does not exist on type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.ts(2339)
```

**Comment by salmankhalid-plt** [comment]
Ok was having similar type issues .. even though i had installed TS 5 .. the VSCODE IDE was still using 4 ... changing that to version use version 5 solved the type issues i was facing
