### ISSUE TITLE
preHandler types are broken for version >= v4.23.2

### ISSUE THREAD

**Issue by rconjaerts** [fastify/fastify#5125]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Plugin version

4.5.1.

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

I was updating fastify, and once the version was >= 4.23.2, my handler throws typescript errors everywhere that I use a preHandler. For example I've got an endpoint that is dedicated to handle webhooks from Stripe.

It looks like this.

**index**
```
import { FastifyPluginAsync } from "fastify";

import { post } from "./stripe/handlers";
import * as Schemas from "./stripe/schemas";
import { stripeSignatureCheck } from "./stripe/util";

const webhooksPlugin: FastifyPluginAsync = async function (fastify) {
  fastify.post(
    "/stripe",
    {
      config: { rawBody: true },
      preHandler: stripeSignatureCheck,
      schema: Schemas.post,
    },
    post,
  );
};

export default webhooksPlugin;
```

**preHandler**
```
import { FastifyRequest, preHandlerAsyncHookHandler } from "fastify";
import { Unauthorized } from "http-errors";
import Stripe from "stripe";

export const stripeSignatureCheck: preHandlerAsyncHookHandler = async (req: FastifyRequest) => {
  // code to verify stripe signature
};
```

**handler**
```
import { RouteHandler } from "fastify";

import { PostBody } from "./schemas/post/body";

export const post: RouteHandler<{
  Body: PostBody;
}> = async (req, res) => {
  const body = req.body;
  // code to handle webhook
  return await res.status(200).send();
};
```

The error I'm getting is the following:
```
Argument of type 'RouteHandler<{ Body: ({ id: string; } & { type: "customer.subscription.deleted" | "customer.subscription.paused" | "customer.subscription.resumed" | "customer.subscription.updated" | "customer.subscription.created"; data: { ...; }; }) | ({ ...; } & { ...; }); }>' is not assignable to parameter of type 'RouteHandlerMethod<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, RouteGenericInterface, unknown, { ...; }, FastifyTypeProviderDefault, FastifyBaseLogger>'.
  Types of parameters 'request' and 'request' are incompatible.
    Type 'FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, { tags: string[]; summary: string; body: TUnion<[TIntersect<[TObject<{ id: TString; }>, TObject<...>]>, TIntersect<...>]>; }, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>' is not assignable to type 'FastifyRequest<{ Body: ({ id: string; } & { type: "customer.subscription.deleted" | "customer.subscription.paused" | "customer.subscription.resumed" | "customer.subscription.updated" | "customer.subscription.created"; data: { ...; }; }) | ({ ...; } & { ...; }); }, ... 6 more ..., ResolveFastifyRequestType<...>>'.
      Type 'RouteGenericInterface' is not assignable to type '{ Body: ({ id: string; } & { type: "customer.subscription.deleted" | "customer.subscription.paused" | "customer.subscription.resumed" | "customer.subscription.updated" | "customer.subscription.created"; data: { ...; }; }) | ({ ...; } & { ...; }); }'.
        Types of property 'Body' are incompatible.
          Type 'unknown' is not assignable to type '({ id: string; } & { type: "customer.subscription.deleted" | "customer.subscription.paused" | "customer.subscription.resumed" | "customer.subscription.updated" | "customer.subscription.created"; data: { ...; }; }) | ({ ...; } & { ...; })'.
```

When checking the changes from [4.23.1 => 4.23.2](https://github.com/fastify/fastify/compare/v4.23.1...v4.23.2), I don't really see what could have caused this, but I don't know fastify that well.

### Steps to Reproduce

Create a basic project with a preHandler that uses a schema, and notice that the typescript throws an error for the request types.

### Expected Behavior

I didn't expect typescript to throw an error on types not being compatible between the handler and preHandler.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment]
I could fix it like this:

https://github.com/rconjaerts/fastify-types-issue/pull/3

**Comment by DemonHa** [comment]
The issue seams to be related with return types of `RouteHandlerMethod` and `RouteHandler` which produce different results. This type `ResolveFastifyReplyReturnType` is returning `unknown` while it RouteHandler return type expects the shape you provided on the schema. An easy fix on your side for the moment would be to use `RouteHandlerMethod` instead of `RouteHandler`
```ts
export const handlerGet: RouteHandlerMethod<
  RawServerDefault,
  RawRequestDefaultExpression,
  RawReplyDefaultExpression,
  {
    Params: GetParams;
  }
> = async (req, res) => {
  const params = req.params;
  console.log(params);
  return await res.status(200).send();
};
```
This is going to get rid of all errors for the moment

**Comment by DemonHa** [comment]
The problem with the updated version seams to be that typescript is infering the type of RouteGeneric from the Guard, which result to the default RouteGeneric, and therefore you see that error. An easy fix could be found [here](https://github.com/rconjaerts/fastify-types-issue/pull/4)

**Comment by DemonHa** [comment]
@rconjaerts The problem with the updated version seams to be that typescript is infering the type of RouteGeneric from the Guard, which result to the default RouteGeneric, and therefore you see that error. An easy fix could be found [here](https://github.com/rconjaerts/fastify-types-issue/pull/4)

**Comment by DemonHa** [comment]
@rconjaerts I don't know if there is a way to tell typescript to prioritise handler to infer the types yet, but i think it is a normal behaviour, since the options come before the handler, so it try to infer it from options.
