### ISSUE TITLE
Getting started tutorial problem

### ISSUE THREAD

**Issue by dolphin278** [fastify/fastify#513]
I am following "Getting started" tutorial (Section ["Your first plugin"](https://www.fastify.io/docs/v0.35.x/Getting-Started/#your-first-plugin)) and it got me really puzzled - I can not access my database connection from `routes` plugin.

Here the code:

```js
// server.js
const fastify = require('fastify')();

fastify.register(require('./our-db-connector'), {
  url: 'mysql://username:pass@localhost/database'
});

fastify.register(require('./our-first-route'));

fastify.listen(3000, function (err) {
  if (err) throw err;
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
});
```

```js
// our-db-connector.js
const mysql = require('mysql2/promise');

async function db(fastify, options) {
  const url = options.url;
  delete options.url;

  const db = await mysql.createConnection(url);
  const [[{sum}]] = await db.query('SELECT 1 + 1 AS sum'); 
  console.log('sum', sum); // connection successful, prints "sum 2"

  fastify.decorate('mysql', db)
}

module.exports = db;
```

```js
// our-first-route.js
async function routes (fastify, options) {
  const connection = fastify.mysql;
  console.log('connection', connection); // prints "connection undefined"

  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  });

  fastify.get('/accounts/:id', async (request, reply) => {
     return await connection.query("SELECT * FROM accounts WHERE id = ?", [request.params.id])[0];
  })
}
module.exports = routes;
```

Why `mysql` is `undefined` on `fastify` in `our-first-route.js`?

I've found similar issue considering scoping of generators (#489) and tried to wrap my db connectior (`db` function exported) using `fastify-plugin`, but nothing changes.

Looks like I am missing something obvious, but I can not figure out what it is :(

Node version is v8.9.1, fastify@0.35.3.

**Comment by jsumners** [comment]
You are missing the `next()` call in your `our-db-connector` plugin. The plugin signature is `function plugin (fastify, options, next) {}`. The `next` function must be invoked to properly register the plugin.

**Comment by jsumners** [comment]
@dolphin278 I think so. The `.register` method is really just `middie` under the hood. And I don't see where `middie` accommodates promises at all:

https://github.com/fastify/middie/blob/2ac769a0a64e396de5d2d08990e82863a154f3cd/middie.js#L81-L91

@delvedor @mcollina am I wrong?

**Comment by delvedor** [comment]
@jsumners yes, if you use an *async* plugin there is no need to call `next` :)
And `register` uses `avvio`, which supports promises.

The reason why the code is not working is because the getting started guide has an error, the database connector plugin should be wrapped with [`fastify-plugin`](https://github.com/fastify/fastify-plugin).

I'll update that document very soon, thank your for the report! :)

**Comment by dolphin278** [comment]
I've got this code working by wrapping plugin in `fastify-plugin` **AND** using explicit `done()` call in my async plugin function. Using `fastify-plugin` alone was not enough.

**Comment by delvedor** [comment]
@dolphin278 Can you paste a gist with your code?

**Comment by jsumners** [comment]
@delvedor https://github.com/fastify/fastify/blob/0c5b2ec4d0292f3e26e1ae04b41462390f1f7f1e/fastify.js#L519-L527

https://github.com/fastify/fastify/blob/0c5b2ec4d0292f3e26e1ae04b41462390f1f7f1e/fastify.js#L121

https://github.com/fastify/fastify/blob/0c5b2ec4d0292f3e26e1ae04b41462390f1f7f1e/fastify.js#L136

That doesn't reference `avvio` at all.

**Comment by delvedor** [comment]
@jsumners checkout avvio's docs, avvio will add some methods to your server instance, such as `use`, `after`, `ready` and so on.
Internally in Fastify we reassign the avvio's `use` to `register`, then `use` to the middie's one.

**Comment by jsumners** [comment]
Ah,  I see https://github.com/fastify/fastify/blob/27c184db707c1edaa451600af38af9ba34e79d31/fastify.js#L56

**Comment by dolphin278** [comment]
@delvedor I've remade everything from scratch again and it's worked just fine (`async function` + `fp` without calling `done()`) – somehow I messed things up yesterday. Thanks everyone!
