### ISSUE TITLE
Unwanted body type conversion happening when applying schema

### ISSUE THREAD

**Issue by rolanday** [fastify/fastify#5130]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.5.0

### Node.js version

18.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14 (Sonoma)

### Description

Apologies in advance if should be a discussion topic.

Unexpected behavior when applying schema to validate body where object mutates. Specifically `{ test: 4 }` becomes `{ test: "4" }. If comment out the schema arg and manually check (as shown below), then body is as expected (4 is number) and the manual schema validation using `Value.Check(..`) fails, as expected.

repo: https://github.com/rolanday/fastify-typebox
```
// ESM
import Fastify from "fastify";
import { TypeBoxTypeProvider } from "@fastify/type-provider-typebox";
import { Type } from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";
const fastify = Fastify({
  logger: true,
}).withTypeProvider<TypeBoxTypeProvider>();

const TBBody = Type.Object({
  test: Type.String(),
});

// The following post should fail, but doesn't because 4 getting converted to a string ("4")
// post http://localhost:3000
// {
//     "test": 4
// }

fastify.post(
  "/",
  // { // If uncomment these lines, test val gets converted to a string (i.e., "4", instead as expected, 4)
  //   schema: {
  //     body: TBBody,
  //   },
  // },
  async (request, reply) => {
    const checked = Value.Check(TBBody, request.body);
    console.log("checked", checked); // false <== as expected (test val should be a string). unless uncomment schema check above, in which cases true

    console.log(request.body);
    return { hello: "world" };
  }
);

/**
 * Run the server!
 */
const start = async () => {
  try {
    await fastify.listen({ port: 3000, host: "0.0.0.0" });
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();

```

### Steps to Reproduce

1. Clone repo: https://github.com/rolanday/fastify-typebox
2. bun -i
3. bun start, observe that manual schema check fails
4. Un-comment lines 22-26, inclusive, and rerun, and note console output showing body mutation (and passes schema validation when it should not)

### Expected Behavior

Body validation does not alter object, and fails schema check

**Comment by climba03003** [comment]
It is expected and well written behavior, please change the `ajv` setting according to your needs.

https://github.com/fastify/fastify/blob/c3a9f49d534026eb0305c2948a0d99fc05692f96/docs/Reference/Validation-and-Serialization.md?plain=1#L238-L240

**Comment by rolanday** [comment]
Thank you! :-) And apologies for not catching this.
