### ISSUE TITLE
Unable to set Content type when status code is 204 or 304

### ISSUE THREAD

**Issue by pramodhsubramanian** [fastify/fastify#5135]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Plugin version

4.5.1

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.5.2

### Description

Unable to set Content type when status code is 204 or 304. Content type becomes empty when the response is sent to the front end.

### Steps to Reproduce

Plugin Code 
```
function responseHandler(app, options, next) {
   app.addHook('onSend', (request, reply, payload, next) {
      const { statusCode } = reply
      if (statusCode === 204 || statusCode === 304) {
          reply.header('Content-Type', 'application/json; charset=utf-8')
     }
    next()
   })
 next()
}
```

Usage

```
const fastify = require('fastify')
const fastifyPlugin = require('fastify-plugin')

const app = fastify()
app.register(fastifyPlugin(responseHandler))

```

### Expected Behavior
 Content type is set in response header.

**Comment by jsumners** [comment]
Neither response code is allowed, per spec, to have any content. This is working as intended.
