### ISSUE TITLE
Consider removal of fastify-cli from main package dependencies

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify#514]
From latest git revision of fastify `npm install --prod` installs 124 packages (15 out of date), 7.2mb.  If I remove fastify-cli from package.json, and `npm prune --prod` I'm left with 47 packages (4 out of date), 5.0MB.

I'm less concerned about the install size, more concerned with the ability to identify important dependencies.  Issues with the 47 packages are far more important than security in the other 78 packages.

**Comment by StarpTech** [comment]
Hi @coreyfarrell fastify-cli is only used in cli mode. It has zero impact of a running server instance. Outdated does not implicit a security risk. We @fastify/fastify will ensure that fastify is secure, fast as possible. E.g https://snyk.io is a better source of truth to measure security.

**Comment by delvedor** [comment]
At the beginning of this project, `fastify-cli` was a separated package. Then we decided to ship it directly with Fastify itself as utility to help users automate their services and improve the overall experience.

Thank you for the proposal and the analysis, but for now I'd say that `fastify-cli` will remain where it is :)

**Comment by mcollina** [comment]
BTW, we might want to reassess this, as the decision was made long ago. What other thinks?

@delvedor do we have snyk enabled in this org?

**Comment by delvedor** [comment]
> @delvedor do we have snyk enabled in this org?

Nope.

**Comment by mcollina** [comment]
I think we should.

**Comment by coreyfarrell** [comment]
Thank you for pointing me to snyk.io, I'm considering using it for some of my projects.  I shouldn't have mentioned 'security' as regular bugs are just as much of a concern but more work to track down.  Unlike security issues there is no tool that will scan for known bugs.  Please don't misunderstand, the fastify team does a great job but time is finite.

@mcollina you said a decision was made long ago, is there a thread/bug/etc I can read?  I tried searching closed fastify bugs but didn't find anything.

**Comment by mcollina** [comment]
I’m not really sure, can’t find it either. Anyway, what do @fastify thinks? I’m open to remove it as a direct dependency if everybody agrees. BTW, most of the dependencies come from update-notifier, so we can definitely slim it by removing that.

**Comment by jsumners** [comment]
1. We definitely should be validating against at least Snyk
1. I really don't even know what `fastify-cli` does. I have never used it. I think it would be better as a separate entity.

**Comment by allevo** [comment]
[optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) ?

**Comment by jsumners** [comment]
@allevo optional deps still install by default.

**Comment by ansarizafar** [comment]
Separate package for fastify-cli is a good idea.

**Comment by allevo** [comment]
Could we invert the dependency?

**Comment by coreyfarrell** [comment]
@allevo if you mean make fastify-cli depend on fastify, yes.  Actualy fastify-cli should depend on fastify, I suspect the only reason it doesn't already is because that would create a circular dependency.

**Comment by allevo** [comment]
`fastify-cli` hasn't `fastify` as depedendy

https://github.com/fastify/fastify-cli/blob/708af9185d86bab55618e363cf87d9b54a230cb7/package.json#L35-L39

But is required here:

https://github.com/fastify/fastify-cli/blob/708af9185d86bab55618e363cf87d9b54a230cb7/cli.js#L50

And `fastify` requires `fastify-cli` is required here

https://github.com/fastify/fastify/blob/d3518f04430156d03d48f9c07b38f7ed6081dfb4/lib/bin.js#L5

So, is more logical inverting the deps

**Comment by coreyfarrell** [comment]
@allevo if we proceed with my proposal lib/bin.js would be deleted.

Just to be explicit for the record, I'm proposing the following changes to fastify:
* Delete lib/bin.js
* Remove "bin" setting from package.json
* Remove fastify-cli dependency from package.json
* Document that fastify should be installed locally to be used as a library, binary can be installed to path with `npm install -g fastify-cli`

And changes to fastify-cli:
* Move fastify from devDependency to dependency.

**Comment by delvedor** [comment]
If I may, why do you need to remove `fastify-cli`, just to save space on disk?
The idea of having it shipped with Fastify is to solve the issue of `fastify-cli` that depends on an older/wrong version of Fastify.
If we ship it within the framework, you can be sure that will always work.

The idea of `fastify-cli` is that you can run a Fastify service in your server just by typing some cli parameter. Without the need to messing up the environment.

If the reason of all this discussion is just to save space, I'm 👎  about this.

**Comment by StarpTech** [comment]
I like the idea to strip fastify to a minimum. @delvedor do you use the fastify-cli feature? Personally, I'd never run a single fastify plugin with the cli. I always instantiate a server in code. That's no reason for me to have it on board.

**Comment by coreyfarrell** [comment]
The space is trivial, I'm more interested in controlling the count of dependent modules.  Having a limited number of dependencies makes it more likely we (the fastify community) can manually review them all.

About dealing with different versions, would that be a v1.x issue or is it just because of how frequently breaking changes are made to v0.x releases?  Once we hit v1.0.0 we should not have continuous semver major changes so fastify-cli will not have to be continuously pointed to new versions.

**Comment by delvedor** [comment]
@StarpTech if I have to run very small services, yes I use it. It comes very handy.

@coreyfarrell if the problem is the dependencies I agree that we should control them. As suggested by @mcollina we can remove the `update-notifier` module (even if is made by Sindre Sorhus, which is an amazing developer and respected member of the community).

**Comment by jsumners** [comment]
@delvedor I completely agree with @coreyfarrell in regard to being able to audit the library. It is my opinion that the functionality of `fastify-cli` is not essential to the core library; it is merely making it more difficult for people to determine the potential attack vectors of Fastify and how it can fit into their project.

**Comment by mcollina** [comment]
@coreyfarrell would you mind checking if removing `update-notifier` reduce the amount of deps to a more manageable state?

In any case, I'm ok in removing if the rest are ok with it.

**Comment by coreyfarrell** [comment]
Current numbers for `npm i --prod`:
* master: 125
* without update-notifier: 61
* without cli: 47

14 extra packages is better than 78 extra packages but my vote is still to stop bundling fastify-cli.  I'll never use fastify-cli so I would feel wrong giving :+1: to removal of a feature from it.  I also think update-notifier is a very reasonable feature for fastify-cli to have.

**Comment by coreyfarrell** [comment]
Has a decision been made which route to take?  I can prepare PR's for fastify and fastify-cli.

If we go with my proposal should fastify-cli use `dependencies` or `peerDependencies` to require fastify?  Using `peerDependencies` would require that users `npm i -g fastify fastify-cli` (npm will warn if they don't install fastify).  This might be desirable as users could control which version of each package they install instead of fastify being installed by fastify-cli.

**Comment by mcollina** [comment]
Here is a poll:

[![](https://api.gh-polls.com/poll/01C1FDPT2FQWG6ARBCTSWK32B4/remove%20fastify-cli%20from%20fastify%20dependencies)](https://api.gh-polls.com/poll/01C1FDPT2FQWG6ARBCTSWK32B4/remove%20fastify-cli%20from%20fastify%20dependencies/vote)
[![](https://api.gh-polls.com/poll/01C1FDPT2FQWG6ARBCTSWK32B4/keep%20fastify-cli%20as%20a%20fastify%20dependency)](https://api.gh-polls.com/poll/01C1FDPT2FQWG6ARBCTSWK32B4/keep%20fastify-cli%20as%20a%20fastify%20dependency/vote)
[![](https://api.gh-polls.com/poll/01C1FDPT2FQWG6ARBCTSWK32B4/other%20(please%20comment))](https://api.gh-polls.com/poll/01C1FDPT2FQWG6ARBCTSWK32B4/other%20(please%20comment)/vote)

Folks, feel free to vote!!!

(I'm 👎  on any use of peerDependency).

In any case, the best way to progress this would be to have _actual implementations_ of this change.
