### ISSUE TITLE
docs: align errors and warning docs

### ISSUE THREAD

**Issue by giuliowaitforitdavide** [fastify/fastify#5142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Recently we added the `docs/Reference/Warnings.md` to better document all the warnings emitted by Fastify. To do that, we used tables in the format

| Code | Description | How to solve | Discussion |
| ---- | ----------- | ------------ | ---------- |

In the `docs/Reference/Errors.md` instead we list all the errors with a short description. 
What do you think about aligning the style of the two pages by using a similar table for the errors? Maybe it could not be possible to write the `How to solve` column for all of the errors, but it could make the page more readable.

**Comment by Uzlopak** [comment]
I am -1 for this.

**Comment by jsumners** [comment]
I think the current doc is mirroring https://nodejs.org/dist/latest-v20.x/docs/api/errors.html#nodejs-error-codes

The difference is we don't have an in-page table-of-contents like they do. See top of https://nodejs.org/dist/latest-v20.x/docs/api/errors.html

I'm really not sure what would be better. An example shown here would help.

**Comment by giuliowaitforitdavide** [comment]
@jsumners you mean an example of what I'm proposing?
Because, for example, I was thinking of something like that

| Code | Description | How to solve | Discussion |
| ----- | ------------ | ------------- | ---------- |
| FST_ERR_NOT_FOUND | 404 not found | - | [#2339](https://github.com/fastify/fastify/pull/2339) |

I like the idea of mirroring [nodejs-error-codes](https://nodejs.org/dist/latest-v20.x/docs/api/errors.html#nodejs-error-codes), but I don't think it's a constraint to be strictly followed: I'm quite sure a table representation would improve readability a lot.
Also the solution you propose seems like a nice solution to me (in-page table-of-contents like the top of the nodejs doc you sent), but I suggest to align also the warning page we wrote [here](https://github.com/fastify/fastify/pull/5108) to have a uniform style.

**Comment by Uzlopak** [comment]
I dislike the idea of a table structure.

**Comment by Uzlopak** [comment]
And if we have to link to a discussion/issue then the documentation wont be self contained.

**Comment by jsumners** [comment]
I'm good with the suggestion. It would make things more legible. But each row _should_ have an anchor so that errors can easily be linked.

@fastify/core ?

**Comment by Eomm** [comment]
I think a link does not hurt and Google+SEO will help someone during the debug

**Comment by metcoder95** [comment]
Structure LGTM, just wondering about what are the exact intentions with the `Discussion` column?
It is to point to the rationale or what exactly?

**Comment by giuliowaitforitdavide** [comment]
> Structure LGTM, just wondering about what are the exact intentions with the `Discussion` column? It is to point to the rationale or what exactly?

I was thinking to add the PR in which we add that specific error code
