### ISSUE TITLE
Add hooks in app.register() options. 

### ISSUE THREAD

**Issue by ildella** [fastify/fastify#5146]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Allow hooks in app.register() options along with "prefix" to simplify mounting many roots like `/users/:userId` and make the same checks for each route - eg: does the userId exists? 

### Motivation

Hi. Often in my HTTP API I have the same application to handle multiple routes, like /users and /conversations and whatever else. 

I do not have a way to add a "check user id" hook onRequest. Here is what I do: 

```js
const mountRoutes = (app, _, done) => {
  app.route(require('./routes/aaaa))
  app.route(require('./routes/bbbb'))
  done()
}

app.register(mountRoutes, {prefix: '/users/:userId'})
```

Then I want a `onRequest` hook to check for the userId to be in the database, and reply.code(404) if it does not. 

The only way I can do it are.

1. pass the hook function to each route, which is a repetition
2. manually do this: 
```
  app.addHook('onRequest', async (request, reply) => {
    const {url, params, log} = request
    if (url.startsWith('/users/')) {
     .... check, if not exists --->  return reply.code(404).send({...})
      request.userId = userId
    }
  })
```

At least that's the best I can find. Maybe I am missing something...

### Example

It would be great to do something like this: 

```js
const checkUserId = (request, reply) => {...}

app.register(mountRoutes, {prefix: '/users/:userId', onRequest:  [checkUserId]})
```

**Comment by cesconix** [comment]
You can use fastify encapsulation feature with the register method. This allows you to apply the hook specifically to a group of routes:
```
async function checkUserId(request, reply) {
  // Logic to check userId in the database
  // If not found, reply with 404
}

const mountRoutes = (app, _, done) => {
  app.addHook('onRequest', checkUserId);
  app.route(require('./routes/aaaa'));
  app.route(require('./routes/bbbb'));
  done();
}

app.register(mountRoutes, { prefix: '/users/:userId' });
```
This setup ensures that your **checkUserId** hook is applied only to the routes under `/users/:userId`, avoiding repetition and keeping your route handling clean.

**Comment by Eomm** [comment]
That's correct @cesconix It is the encapsulation in action.

Further reading:

- https://backend.cafe/the-complete-guide-to-the-fastify-plugin-system
- https://stackoverflow.com/a/61054534/3309466
- https://github.com/Eomm/fastify-overview/
