### ISSUE TITLE
Update linting/formatting tooling

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#5159]
There's a great disturbance in the force. See https://twitter.com/jsumners79/status/1724164412599050587.

We should update our eslint config to use https://eslint.style/guide/migration. Basically, we need to update:

https://github.com/fastify/fastify/blob/b4a413889f78029b9709e991e8869d450c26c9a0/package.json#L160-L165

And possibly:

https://github.com/fastify/fastify/blob/b4a413889f78029b9709e991e8869d450c26c9a0/.eslintrc#L1-L4

And maybe all of:

https://github.com/fastify/fastify/blob/b4a413889f78029b9709e991e8869d450c26c9a0/docs/Guides/Contributing.md?plain=1#L138-L184

**Comment by mcollina** [comment]
I've opened https://github.com/standard/standard/issues/1948 to discuss with the standard team. Overall, I think we should try to minimize the migration work for us.

Maybe @Fdawgs and others could help.
