### ISSUE TITLE
Typebox schema issue

### ISSUE THREAD

**Issue by MariuzM** [fastify/fastify#5169]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13

### Description

Im making response schema with typebox but for some reason getting this error, im really not sure where the issue is what i'm doing wrong. 

<img width="604" alt="image" src="https://github.com/fastify/fastify/assets/36937039/b16f1c1c-bbff-4486-88c8-5b647ad73456">

```json
{
  "code": "FST_ERR_SCH_SERIALIZATION_BUILD",
  "name": "FastifyError",
  "statusCode": 500,
  "message": "Failed building the serialization schema for GET: /messages, due to error schema is invalid: data/items/properties/created_at/type must be equal to one of the allowed values",
  "stack": "Error: Failed building the serialization schema for GET: /messages, due to error schema is invalid: data/items/properties/created_at/type must be equal to one of the allowed values\n    at <anonymous> (/Volumes/Media/Dev/Projects/project__1/serverV2/node_modules/fastify/lib/route.js:404:87)\n    at <anonymous> (native)\n    at emit (native)\n    at <anonymous> (/Volumes/Media/Dev/Projects/project__1/serverV2/node_modules/avvio/boot.js:160:19)\n    at <anonymous> (/Volumes/Media/Dev/Projects/project__1/serverV2/node_modules/avvio/plugin.js:275:5)\n    at done (/Volumes/Media/Dev/Projects/project__1/serverV2/node_modules/avvio/plugin.js:199:10)\n    at check (/Volumes/Media/Dev/Projects/project__1/serverV2/node_modules/avvio/plugin.js:223:13)\n    at processTicksAndRejections (native)"
}
```

### Steps to Reproduce

...

**Comment by Uzlopak** [comment]
Date is not a valid json schema type.

**Comment by MariuzM** [comment]
Using Any is same problem

**Comment by climba03003** [comment]
In Typebox `Any` is a schema without content, that means it is not a valid JSON schema.
You should study the difference between Typebox and JSON schema.

**Comment by MariuzM** [comment]
@climba03003 that's fine, problem is that using Drizzle i get this format as Date hence I'm trying to match with schema, i think using ElysiaJS this was working fine. So looks like Fastify does not support this and i will have to look into my own validator for date, setting as string is not option for me.

**Comment by climba03003** [comment]
@MariuzM `ElysiaJS` using typebox as validator which you can use https://github.com/fastify/fastify-type-provider-typebox#type-compiler for the similar feature.

**Comment by MariuzM** [comment]
Missed this one thank you!!
