### ISSUE TITLE
Custom header value isn't encoded as UTF-8

### ISSUE THREAD

**Issue by maximelafarie** [fastify/fastify#5171]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.1 (23B81)

### Description

If I set a custom header with an utf-8 value, the value received is not utf-8 encoded.

### Steps to Reproduce

```typescript
// whatever you want

// set a header value with special chars or at least with accents
// maybe `text/csv` content-type has something to do with it
reply.headers({
    'Content-Type': 'text/csv; charset=UTF-8',
    'x-suggested-filename': `pièce-jointe-edit.csv`
});

await reply.send(); // any reply you want
```

```
Expected: "pièce-jointe-edit.csv"
Received: "piÃ¨ce-jointe-edit.csv"
```

### Expected Behavior

Receive natively the string value as it was defined without conversion.

**Comment by climba03003** [comment]
I would close it since headers always encoded as ASCII.
There is no way to change this inherited behavior from `Node.js`.

```js
import http from 'http'

http.createServer(function(request, response) {
  response.writeHead(200, {
    'content-type': 'text/csv; charset=UTF-8',
    'x-suggested-filename': `pièce-jointe-edit.csv`
  }).end(null,null,null)
}).listen(3000)
```
