### ISSUE TITLE
custom schema support installed by setValidatorCompiler removed if any schemas are added

### ISSUE THREAD

**Issue by derammo** [fastify/fastify#5178]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

18.18.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

bookworm

### Description

At this location:

https://github.com/fastify/fastify/blob/1891f243ab8666ef926218691135eb032008632a/lib/schema-controller.js#L112

Any custom schema support is removed if any schemas were added, because the default builder is used to overwrite the installed `validatorCompiler`.

The order of operations does not appear to matter, because both registering the custom schema support and adding schemas by id will happen before `listen` and this initialization is run at that time.

### Steps to Reproduce

```
const server: Fastify = fastify({
  logger: true
});
server.setValidatorCompiler(...)
server.addSchema(...)
server.setValidatorCompiler(...) // again if you want to, it won't help
server.listen(...)
```

Any validation schema that needs the customization from `setValidatorCompiler(...)` will fail to compile because the default compiler is actually used.

### Expected Behavior

if `this.isCustomSerializerCompiler` then it should not overwrite the installed compiler

**Comment by derammo** [comment]
Yes I am working on making an example repo I can share.  Just letting you know so you don't waste more time on this in the meantime :)

**Comment by derammo** [comment]
@giuliowaitforitdavide try this https://github.com/derammo/minifast

`npm install && npm run build && npm run start` 

`npm run fail` to see the problem happen

The only difference is that it registers a schema in the 'fail' case.

```
FastifyError [Error]: Failed building the validation schema for POST: /test, due to error strict mode: unknown keyword: "cli_item_name"
```

**Comment by metcoder95** [comment]
Yeah, I can reproduce the issue; it seems we know but we are not respecting the fact that there's possibly already a validator set for the given instance and we instead do a recursive lookup for the parent.

Didn't dig into the repercussions of that but given that the `SchemaController` instance is aware of its parent's schemas since its instantiation, it should be safe to do a fast return if the schema already has a custom validator.

Would you like to send a PR to address it?

**Comment by derammo** [comment]
I would have PR'd it but I felt like someone with more core knowledge would have a better chance at knowing what the impact of the one line change would be?   I have only one week experience with fastify....  Is it ok to just leave this with you?

**Comment by Eomm** [comment]
Could you check this test case?
https://github.com/fastify/fastify/blob/84ad944d7324fad338a09043fbb82f041a02db98/test/schema-validation.test.js#L108

How many times `validatorCompiler` is executed?
What if `standardValidator` is removed instead?

The most useful thing would be to open a draft PR with a failing test case, then we can pick it up or support you to write the fix 👍🏼

**Comment by derammo** [comment]
as referenced above, just note I had not used TAP before, but this test trivially fails now
