### ISSUE TITLE
Websocket connections to secondary server prevents server from shutting down

### ISSUE THREAD

**Issue by kingston** [fastify/fastify#5180]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

20.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.1

### Description

When a websocket connection is connected to a secondary server (e.g. when we are listening to both 127.0.0.1 (secondary) and ::1 (primary) and a client connects to 127.0.0.1), we don't run the preClose operations prior to closing the secondary server. This causes the server close hook to hang indefinitely since the websocket connection is still live.

I tried debugging the issue and it appears to be related to this line (https://github.com/fastify/fastify/blob/main/lib/server.js#L178) where Fastify attaches a onClose handler that tries to close the secondary server without calling any preClose hooks unlike the primary server (https://github.com/fastify/fastify/blob/main/fastify.js#L433). This means that @fastify/websocket is unable to shutdown the sockets appropriately leading the secondary server to stall the close process indefinitely.

I was wondering if it was on @fastify/websocket side to fix, but I don't see a way they can solve this without a fix on Fastify's side since it appears the Fastify close process is hanging before any plugin can do any clean up.

### Steps to Reproduce

I created a minimal reproduction repository here: https://github.com/kingston/fastify-websocket-repro

1) Run `node index.js`
2) Open `index.html`
3) Ctrl-C the node process

### Expected Behavior

Fastify shuts down cleanly without timing out

**Comment by kingston** [comment]
> 👋
> 
> > I tried debugging the issue and it appears to be related to this line ([main/lib/server.js#L178](https://github.com/fastify/fastify/blob/main/lib/server.js?rgh-link-date=2023-11-30T11%3A39%3A14Z#L178)) where Fastify attaches a onClose handler that tries to close the secondary server without calling any preClose hooks unlike the primary server ([main/fastify.js#L433](https://github.com/fastify/fastify/blob/main/fastify.js?rgh-link-date=2023-11-30T11%3A39%3A14Z#L433)). This means that @fastify/websocket is unable to shutdown the sockets appropriately leading the secondary server to stall the close process indefinitely.
> 
> The `preClose` hook should not be called twice, AFAIC, the order seems to be correct. `preClose` will be called just before closing the first, and subsequently, the secondary server. Trying to run it in both will cause a duplicate of running hooks; unless that's the desired behaviour, here we will change the experience.
> 
> I'm guessing here that `websocket` might not be aware of the existence of the two servers. I can see an explicit detach `upgrade` event from server A but not B.
> 
> Have you tried providing your own `preClose` cb?

The issue is that the global preClose hooks are called after the secondary server runs its onClose handler. Therefore, there's nothing to hook into before the secondary server calls onClose which hangs indefinitely since there are open websockets. I think what should happen is:
1) preClose hooks
2) close primary server
3) close secondary server

But what is happening appears to be (based on debug statements):
1) close secondary server
2) preClose hooks
3) close primary server

I can take a look at the code to see if a quick PR can be made but less familiar with how the whole hook system works.

**Comment by metcoder95** [comment]
Yeah, it makes sense now.
Feel free to open a PR, we can provide some guidance there 👍 

I'd recommend you take a look at this function call: https://github.com/fastify/fastify/blob/b9336a3f3979f0d024a73222e193d1317bafc69a/fastify.js#L433-L452

And seek if there's a way of closing the secondary just after the hooks has run (when is basically when the CB submitted to the `hook runner` gets called).
As hooks can be asynchronous, most likely we reach this line https://github.com/fastify/fastify/blob/b9336a3f3979f0d024a73222e193d1317bafc69a/fastify.js#L459 before even finishing the execution of all the hooks, leading to this problem.

**Comment by mcollina** [comment]
I think that would work! Would you like to try implementing that?
