### ISSUE TITLE
CI failure with v18.19.0

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#5198]
https://github.com/fastify/fastify/pull/5195 shows that our CI fails with Node.js v18.19.0. I can confirm this locally. I am seeing issues with v18.19.0 in another project and found the commit breaking that project to be https://github.com/nodejs/node/commit/bac9b1758f36fb3504589ffc5ed610d574dca47d. However, a build of Node with that commit passes the Fastify CI. So our issue here is somewhere between that commit and the `v18.19.0` tag.

**Comment by jsumners** [comment]
The commit that triggers our CI failure is https://github.com/nodejs/node/commit/29697229b61a8cbdf12e6abe0cbaa9fecc9a5102.

**Comment by Uzlopak** [comment]
So closeIdleConnections was backported?

**Comment by jsumners** [comment]
Looks that way.

**Comment by jsumners** [comment]
There was discussion at the end of https://github.com/nodejs/node/pull/48383 about it breaking core's CITGM within Fastify.

**Comment by Uzlopak** [comment]
Reopened #5195

**Comment by mcollina** [comment]
My bad, I didn't notice this was actually backported to node v18, the last few months have been hectic.
