### ISSUE TITLE
should some DeprecationWarnings be Warnings?

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#5200]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The goal of deprecation warnings is to one day remove the deprecated code and the deprecated warning too. But this is not always the case.

FSTDEP006 
https://github.com/fastify/fastify/blob/49b62f56a35f1a9a958de6aec07cee851ac2aa43/lib/warnings.js#L28C28-L28C37

Imho this deprecation warning can happen when an unexperienced dev will uses a non-primitive value and decorate request or reply with it. So I assume we can never drop this DeprecrationWarning?

FSTDEP007
https://github.com/fastify/fastify/blob/49b62f56a35f1a9a958de6aec07cee851ac2aa43/lib/warnings.js#L30C28-L30C37

This is a warning about a misconfiguration.

**Comment by mcollina** [comment]
we plan to start throwing errors for both DEP006 and DEP007 in v5.

**Comment by Uzlopak** [comment]
Ok 👍
