### ISSUE TITLE
"stream closed prematurely" error happens when replied with streams

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [fastify/fastify#5203]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.x.x

### Stopped working in version

4.x.x

### Node.js version

v21.4.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.2 Beta

### 💥 Regression Report

Responding with stream worked just fine until I've upgraded to latest fastify version(4.x.x). Previously, I was on 3.x.x, where I did not faced any problems. 

### Steps to Reproduce

I have put together [this repo](https://github.com/tamilvendhank-helptap/stream-closed-prematurely) which replicates the problem. 

The complete code is the following:
```
import fs from 'fs';

import Fastify from 'fastify';

const fastify = Fastify({
  logger: true
})

// Declare a route
fastify.get('/', async function handler (request, reply) {
  const stream = fs.createReadStream('./sample.txt', 'utf8')
  reply.header('Content-Type', 'application/octet-stream')
  reply.send(stream);
})

// Run the server!
try {
  await fastify.listen({ port: 3456 })
} catch (err) {
  fastify.log.error(err)
  process.exit(1)
}
```

1. Start the server with the above code. 
2. Create a file called `sample.txt` with some content.
3. Visit: http://127.0.0.1:3456
4. Observe empty response, instead of contents of sample.txt
5. Observe the following logs
```
{"level":30,"time":1702288665137,"pid":54308,"hostname":"Tamils-iMac.local","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"127.0.0.1:3456","remoteAddress":"127.0.0.1","remotePort":58529},"msg":"incoming request"}
{"level":30,"time":1702288665144,"pid":54308,"hostname":"Tamils-iMac.local","reqId":"req-1","res":{"statusCode":200},"responseTime":6.139292001724243,"msg":"request completed"}
{"level":30,"time":1702288665152,"pid":54308,"hostname":"Tamils-iMac.local","reqId":"req-1","res":{"statusCode":200},"msg":"stream closed prematurely"}
```

### Expected Behavior

Here the expected behaviour is to return the sample.txt file.

**Comment by climba03003** [comment]
Please check the migration guide.
https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V4.md#need-to-return-reply-to-signal-a-fork-of-the-promise-chain

If the problem exists when you `return reply`, please let me know. I will re-open the issue.

**Comment by tamilvendhank-helptap** [comment]
@climba03003, yes, it worked! Thanks for the response.
