### ISSUE TITLE
Update callouts in documentation with GitHub extension

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#5217]
All of the documentation should be reviewed to find our callouts and update them with GitHub's [new Markdown extension](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/). There may need to be some coordination with @fastify/website to recognize these when building the website.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

As an example, this callout:
https://github.com/fastify/fastify/blob/e3a07eaa444d0e769802195816d4e1718c2fc9ea/README.md?plain=1#L183-L192

Should be replaced with:
```md
> [!IMPORTANT]
> `.listen` binds to the local host, `localhost`, interface by default
> (`127.0.0.1` or `::1`, depending on the operating system configuration). If
> you are running Fastify in a container (Docker,
> [GCP](https://cloud.google.com/), etc.), you may need to bind to `0.0.0.0`. Be
> careful when deciding to listen on all interfaces; it comes with inherent
> [security
> risks](https://web.archive.org/web/20170711105010/https://snyk.io/blog/mongodb-hack-and-secure-defaults/).
> See [the documentation](./docs/Reference/Server.md#listen) for more
> information.
```

Which will result in:
> [!IMPORTANT]
> `.listen` binds to the local host, `localhost`, interface by default
> (`127.0.0.1` or `::1`, depending on the operating system configuration). If
> you are running Fastify in a container (Docker,
> [GCP](https://cloud.google.com/), etc.), you may need to bind to `0.0.0.0`. Be
> careful when deciding to listen on all interfaces; it comes with inherent
> [security
> risks](https://web.archive.org/web/20170711105010/https://snyk.io/blog/mongodb-hack-and-secure-defaults/).
> See [the documentation](./docs/Reference/Server.md#listen) for more
> information.

**Comment by Fdawgs** [comment]
Whilst I was originally a big supporter of this, I am -1:

- The syntax is [still in beta](https://github.com/orgs/community/discussions/16925) and can change at any time... again
- The syntax is a GitHub native extension to markdown. It doesn't render if you're, for example, viewing the readme of a module that uses this syntax on NPM, or viewing it in VS Code (without a third party extension)
- The above point flys in the face of the reason [why we still include tests and docs with modules](https://github.com/fastify/fastify/pull/3467#issuecomment-974677518). If you have to view the docs on GitHub to get best results then we may as well remove them from published packages
