### ISSUE TITLE
The request hangs until timeout when sending an object as {message: 'Foo "bar"'} in the reply.send method

### ISSUE THREAD

**Issue by Kosrotoff** [fastify/fastify#5223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.1

### Node.js version

18.16.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

When sending an object as `{message: 'Foo "bar"'}` in the reply.send method, the request gets stuck and does not complete until the timeout expires.

![image](https://github.com/fastify/fastify/assets/50526865/cf701e5f-3be6-4efd-9284-7b646112b79b)

### Steps to Reproduce

```javascript
server.setErrorHandler((error, request, reply) => {
    void reply
        .status(500)
        .send({message: 'Foo "bar"'});
});
```

But this works:
```javascript
server.setErrorHandler((error, request, reply) => {
    void reply
        .status(500)
        .send(JSON.stringify({message: 'Foo "bar"'})); // added JSON.stringify
});
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Kosrotoff** [comment]
Sorry, I forgot to call done in middleware 😢

**Comment by Kosrotoff** [comment]
I still can’t fully understand why it has this behavior.

My error handler looks like this:
```javascript
server.setErrorHandler((error, request, reply) => {
    void reply
        .status(500)
        .send({message: 'Foo "bar"'});
});
```

If I do in my middleware: `return done()` then my request hangs. If I call `done` without `return` then the request works.
If I use `.send(JSON.stringify({message: 'Foo "bar"'})); // added JSON.stringify` then the request always works.
