### ISSUE TITLE
fastify listens twice when host not defined

### ISSUE THREAD

**Issue by hulkish** [fastify/fastify#5224]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.1

### Node.js version

21.5.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Sonoma 14.1.1

### Description

fastify seems to listen twice

### Steps to Reproduce

1. Create `server.mjs`:
```js
import fastify from 'fastify';

const server = fastify({ logger: true });
server.listen({ port: 3000 }, (err) => {
  console.log('listening');
  if (err) {
    throw err;
  }
});
```

2. run it: 
```sh
node server.mjs
```

This will produce the following logs:
```sh
{"level":30,"time":1703102194651,"pid":7971,"hostname":"My-MacBook-Pro.local","msg":"Server listening at http://[::1]:3000"}
{"level":30,"time":1703102194652,"pid":7971,"hostname":"My-MacBook-Pro.local","msg":"Server listening at http://127.0.0.1:3000"}
listening
```

However, when you specify `host`, for ex:
```js
import fastify from 'fastify';

const server = fastify({ logger: true });
server.listen({ host: '0.0.0.0', port: 3000 }, (err) => {
  console.log('listening');
  if (err) {
    throw err;
  }
});
```
It will only log a single listening:
```sh
{"level":30,"time":1703102345963,"pid":7989,"hostname":"My-MacBook-Pro.local","msg":"Server listening at http://0.0.0.0:3000"}
listening
```

### Expected Behavior

It should only register/log a single listen `server.listen()`.

**Comment by metcoder95** [comment]
👋 

This is expected and documented within Fastify's documentation. Fastify enables the resolution of two IPv families within `localhost` to `127.0.0.1` and `[::1]`.
It facilitates local clients to avoid conflicts whenever the OS brings different local hostname resolutions when resolving to `localhost`, e.g. `osx` prioritises first the `ipv6` family over the `ipv4`.

**Comment by hulkish** [comment]
> 👋
> 
> This is expected and documented within Fastify's documentation. Fastify enables the resolution of two IPv families within `localhost` to `127.0.0.1` and `[::1]`. It facilitates local clients to avoid conflicts whenever the OS brings different local hostname resolutions when resolving to `localhost`, e.g. `osx` prioritises first the `ipv6` family over the `ipv4`.

but that alters default server behavior in node - which I would argue would be overstepping to have as default behavior on behalf of a server framework

**Comment by jsumners** [comment]
I don't understand the objection. Core will listen on all local host interfaces or a single and you have no idea ahead of time which it will be because it is OS dependent. Fastify has made it predictable.
