### ISSUE TITLE
Ecosystem.md, missing @fastify/kafka, maybe other core plugins missing too

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#5232]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Add following core plugins to the ecosystem.md file

- [ ] @fastify/express
- [ ] @fastify/kafka
- [ ] @fastify/mysql
- [ ] @fastify/passport
- [ ] @fastify/swagger-ui
- [ ] @fastify/zipkin

**Comment by Uzlopak** [comment]
@fastify/mysql is also missing

**Comment by Fdawgs** [comment]
I'll hop on this one, homeslice.
