### ISSUE TITLE
Cant we make this an options to be passed for useSemicolonDefault to find-my-way?

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5237]
Cant we make this an options to be passed?
Solve it maybe like this?

```suggestion
  options.config.useSemicolonDelimiter ?= true // To avoid a breaking change
```

+ typescript typings and documentation?

_Originally posted by @Uzlopak in https://github.com/fastify/fastify/pull/5236#discussion_r1436525251_

**Comment by Fdawgs** [comment]
Can we roll this into v5 as a breaking change and keep it disabled and non-configurable?

From reading the spec linked in the original issue it's going against the standard so I don't think we should be encouraging it?

**Comment by Uzlopak** [comment]
I am a configuration fetishist. :)

But i dont have a strong opinion on this.

**Comment by gurgunday** [comment]
> Can we roll this into v5 as a breaking change and keep it disabled and non-configurable?
> 
> From reading the spec linked in the original issue it's going against the standard so I don't think we should be encouraging it?

+1

**Comment by mcollina** [comment]
We should add an option right now, and flip the default in v5.
