### ISSUE TITLE
Drop security, governance, coc, and contributing files from this repo?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#5241]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Rather than maintaining/updating two versions of the same document, can we drop `SECURITY.md`, `GOVERNANCE.md`, `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` from this repo so that the shared ones from [`fastify/.github`](https://github.com/fastify/.github) will be used instead?
See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by mcollina** [comment]
SGTM. I would prefer to keep the files with a markdown link in there.

**Comment by Fdawgs** [comment]
> I would prefer to keep the files with a markdown link in there.

Sorry you've lost me there @mcollina, what do you mean?

**Comment by mcollina** [comment]
There are external links (plenty) in OpenJS pointing to those files. I don't want 404s to handle. If you want to remove the duplication, keep the files and add a single markdown link to the new location.

**Comment by Eomm** [comment]
I would set a default on `.github` repo that talk about pluging, but the main fastify repo needs info that is unrelated to plugins IMHO

Eg:

This section
- https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md#fastify-previous-versions

does not make sense for all the repos
