### ISSUE TITLE
Cannot addHook(), keeps returning error.

### ISSUE THREAD

**Issue by VietnamecDevelopment** [fastify/fastify#5243]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Node.js version

21

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux.

### Description

I wanted to create a hook to validate API Keys (preValidation), bu i keep getting the error of src/index.ts(10,10): error TS2339: Property 'addHook' does not exist on type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.

### Steps to Reproduce

```ts
import fastify, {FastifyInstance} from "fastify"
import db from "database"

const instance: FastifyInstance = fastify();

instance.addHook("preValidation", async (req, res) => {
  const apiKeyHeader = req.headers["api_key"].toString();
  if (!apiKeyHeader) {
    res
      .code(401)
      .send({ error: "Unauthorized", message: "API key is missing" });
    return;
  }

  const apiKey = apiKeyHeader.trim();

  try {
    const apiRecord = await db.apiKey.findUnique({
      where: { key: apiKey },
    });

    if (!apiRecord) {
      res.code(401).send({ error: "Unauthorized", message: "Invalid API key" });
      return;
    }
  } catch (err) {
    console.error(err);
    res.code(500).send({
      error: "Internal Server Error",
      message: "Something went wrong",
    });
  }
});
instance.listen(
  { host: process.env.HOST as string, port: Number(process.env.PORT) },
  (err, host) => {
    if (err) return;

    console.log(`Starting backend on ${process.env.HOST}:${process.env.PORT}`);
  },
);
```
```[tasklist]
### Tasks

**Comment by mcollina** [comment]
I cannot reproduce using your snippet.

We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by VietnamecDevelopment** [comment]
> I cannot reproduce using your snippet.
> 
> We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

It just does with every addHook.....

**Comment by VietnamecDevelopment** [comment]
Even if i paste a console log in that hook, it wont work

**Comment by mcollina** [comment]
Well, something else is at play, because a slightly simplified version of your code works.

So...

1. create a GH repository
2. put all the files needed for this error to reproduce (remove all the db reference), remember to include your tsconfig and package.json
3. include the exact commands you run to get the error

**Comment by Uzlopak** [comment]
I checked it on typescript playground. You are using typescript v 4.9.5 or lower. Upgrade your typescript version and then it will work.

**Comment by VietnamecDevelopment** [comment]
U are my lifesaver, thank you <3
