### ISSUE TITLE
ContentType parser API

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#525]
I think the API for the ContentType Parser is wrong.

https://github.com/fastify/fastify/blob/64f03922f49ef4f045b84bbb3832c90b3c1d8cd2/test/custom-parser.test.js#L87-L92

As an example:

```js
  function customParser (req, done) {
    jsonParser(req, function (err, body) {
      if (err) return done(err)
      done(body)
    })
  }
```

I think this should be:

```js
  function customParser (req, done) {
    jsonParser(req, function (err, body) {
      if (err) return done(err)
      done(null, body)
    })
  }
```

And we should also support async/await (maybe in the future, dealing with streams with promises is currently very bad):

```js
  async function customParser (req) {
    return await jsonParser(req)
  }
```

**Comment by allevo** [comment]
Absolutely :+1:

**Comment by StarpTech** [comment]
+1 This should be a blocker for 1.0 and can be fixed quick.

**Comment by Ethan-Arrowood** [comment]
Can i give this a shot?

**Comment by jsumners** [comment]
@Ethan-Arrowood most certainly.

**Comment by Ethan-Arrowood** [comment]
Yay! If you guys have any other pointers for me that would be much appreciated

**Comment by Ethan-Arrowood** [comment]
@mcollina can you expand on what changes you'd like to see in the ContentTypeParser api?

**Comment by mcollina** [comment]
@Ethan-Arrowood the `done()` function currently receives both errors and data as the first argument. That is a bug, error first, and data second.

Plus, we need `Promise` support for this change.

**Comment by Ethan-Arrowood** [comment]
Alright thank you! I'll see what I can come up with
