### ISSUE TITLE
Failed building the ajv validation schema due to error strict mode

### ISSUE THREAD

**Issue by tbhaxor** [fastify/fastify#5255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Node.js version

18.18.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro

### Description

I am getting the following error on the POST route schema.

```
FastifyError [Error]: Failed building the validation schema for POST: /, due to error strict mode: default is ignored for: data1.bearer
```

This error is suppressed when strict mode is disabled. But the point is I am not getting this error when using Ajv

```js
import Ajv from "ajv";

const ajv = new Ajv({ strict: true });

const validate = ajv.compile({
  type: "object",
  properties: {
    authorisation: {
      type: "object",
      description: "Set the authorization he header for the request.",
      oneOf: [
        {
          properties: {
            username: { type: "string" },
            password: { type: "string" },
          },
          required: ["username", "password"],
        },
        {
          properties: {
            token: { type: "string" },
            bearer: { type: "boolean", default: false },
          },
          required: ["token"],
        },
      ],
    },
  },
});

console.assert(validate({ authorisation: { token: "Hello World" } }));
```

**Additional Node** I am using @fastify/swagger for which I have to add the custom plugin. Not sure if that is causing the error

```js
const fastify = require("fastify")({
  logger: { transport: { target: "pino-pretty" } },
  ajv: {
    // customOptions: { strict: "log" },
    plugins: [
      function (ajv) {
        ajv.addKeyword({ keyword: "x-examples" });
      },
    ],
  },
});
```

### Steps to Reproduce

1. Create a POST route with following schema

```js
const schema = {
  $id: "MySchema",
  type: "object",
  properties: {
    authorisation: {
      type: "object",
      description: "Set the authorization he header for the request.",
      oneOf: [
        {
          properties: {
            username: { type: "string" },
            password: { type: "string" },
          },
          required: ["username", "password"],
        },
        {
          properties: {
            token: { type: "string" },
            bearer: { type: "boolean", default: false },
          },
          required: ["token"],
        },
      ],
    },
  },
};
```
2. Start the fastify server, you will get the error

### Expected Behavior

It is working fine with the ajv code. So it should work with fastify as well.

**Comment by Uzlopak** [comment]
Please provide a repository to easily clone it ;).

**Comment by Uzlopak** [comment]
https://ajv.js.org/strict-mode.html#ignored-defaults

**Comment by tbhaxor** [comment]
Thanks @Uzlopak this worked. So basically problem is with default set to `true` with `oneOf` or `anyOf` configured. After removing default it is working.
