### ISSUE TITLE
live-server on port 8080 doesn't work with parameter routes 

### ISSUE THREAD

**Issue by jebarpg** [fastify/fastify#5271]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Node.js version

v18.17.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Clear Linux OS installed version 40410

### Description

using the live-server package here: git+https://github.com/tapio/live-server.git#ad22544 
when looking at http//127.0.0.1:8080/user/1 
I get an error

GET /user/1 404 14.359 ms - 145

but using http//127.0.0.1:3000/user/1 
it works fine.

my code is the basic example using a parameter route of 
```
server.get('/user/:id', async (req, reply) => {
console.log(req.params.id)
}
```

### Steps to Reproduce

```
import Fastify from 'fastify'
const fastify = Fastify({
  logger: true
})
// CommonJs
const fastify = require('fastify')({
  logger: true
})

// Declare a route
fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})

fastify.get('/user/:id', async (req, reply) => {
console.log(req.params.id)
}

// Run the server!
fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
  // Server is now listening on ${address}
})
```

**Comment by climba03003** [comment]
I am closing the issue because you are listening to `3000` port, it is expected to only works on `3000` port.
I am not sure how you use the `live-server` package because it show nothing on your information.
