### ISSUE TITLE
Error with Fastify version 4.* in TypeScript: 'register' method expects 0 arguments, but got 1 in 'fastifyRoutes'

### ISSUE THREAD

**Issue by tanmoy-witbybit** [fastify/fastify#5272]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.0

### Node.js version

20.8.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.3 LTS

### Description

Index.ts file

```
import app from './app';

const PORT = Number(process.env.PORT) || 8080;
const ENV = process.env.ENV || 'development';
app()
	.then(app => {
		app.listen({ port: PORT }, (err, address) => {
			if (err) {
				console.error(err);
				process.exit(1);
			}
			console.log('Server running at port -> %d in %s mode', PORT, ENV);
		});
	})
	.catch(err => {
		console.log(err);
	});
```
app.ts 

```
import Fastify from 'fastify';
import routes from './routes';

export default async function app() {
	const fastify = Fastify({
		logger: true
	});
	await fastify.register(routes, { prefix: '/' });
	return fastify;
}
```

routes.ts

```
import { FastifyInstance } from 'fastify';
export type FRequest = FastifyRequest<{
	Params: { [key: string]: string };
	Body: { [key: string]: any };
	Querystring: { [key: string]: string };
}>;
export default async function fastifyRoutes(fastify: FastifyInstance) {
	fastify.route({
		method: 'POST',
		url: '/user/me',
		preHandler: [
			async (request: FRequest, reply) => {
				await foo(request, reply);
			},
			async (request: FRequest, reply) => {
				await foo2({},request,reply);
			}
		],
		handler: async function (request: FRequest, reply) {
			await foo3({}, request, reply);
		}
	});
}
```

I am encountering an issue when using Fastify version 4.* with TypeScript. The error message suggests a problem with the 'register' method in the 'fastifyRoutes' function within my codebase. Specifically, it indicates that the 'routes'' method expects 0 arguments but receives 1. Same thing happens with other methods like GET, POST ...

i user `ts-node --files src/index.ts` to run the code.

![image](https://github.com/fastify/fastify/assets/144437163/a70a944d-4dda-4916-8ff2-39eea75bac8d)

But when i try to user `Fastify version 3.* ` it works perfectly no issue.
Also if i try to run `ts-node **-T** --files src/index.ts` my code works but i don't want to do so.

### Steps to Reproduce

1. Use Fastify version 4.* in a TypeScript project.
2. Attempt to run the server using the command: ts-node --files src/index.ts
3. Observe the error related to the 'register' method in the 'fastifyRoutes' function.

**Comment by mcollina** [comment]
There is an option object passed to your plugin as an option.

**Comment by tanmoy-witbybit** [comment]
Can you please share a code sample, that could be very helpful. like how to user `fastify.route()` properly. @mcollina

**Comment by mcollina** [comment]
Can you please upload all your files in a repository?

Note that there is no call to `register()` in the example, and in the last message you message `.route()`.

**Comment by tanmoy-witbybit** [comment]
Thanks for the response, as you can see in app.ts file I have use the register to use the routes. The issue is that when i passed the route in the app.register() and then it throws the error (a type error cause without type checking the code works fine).

**Comment by bowber** [comment]
I had the same issue, upgrading to Typescript 5 should fixed this.
After I sneak into the source code, I find out that it uses `const` modifier to a type parameter, this is a new feature of Typescript 5.

**Comment by climba03003** [comment]
It should be solved by upgrading the TypeScript version.
