### ISSUE TITLE
Return Response.body from a fetch call as a stream

### ISSUE THREAD

**Issue by TJBlackman** [fastify/fastify#5279]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Node.js version

20.10

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I make a fetch call on my Fastify server and I want to return the response from that fetch call as the response of my Fastify route **as a stream**. 

I thought this would work since Fastify has stream docs (https://fastify.dev/docs/latest/Reference/Reply/#streams), but it does not. 

### Steps to Reproduce

Clone this github repo: [https://github.com/TJBlackman/fastify-stream-test](https://github.com/TJBlackman/fastify-stream-test)

Install dependencies and run the project: 

- npm i
- npm run dev

Make requests to the API: 

- GET http://localhost:3000/api/json - Works!
- GET http://localhost:3000/api/stream - Does not work :(

For the sake of completeness, here is the demo server file you could copy/paste if you want.

```js 
const fastify = require("fastify")({ logger: true });

// return JSON from SWAPI - works!
fastify.get("/api/json", async (request, reply) => {
  const response = await fetch("https://swapi.dev/api/people/1/");
  const json = await response.json();
  return reply.send(json);
});

// return stream from SWAPI - doesn't work
fastify.get("/api/stream", async (request, reply) => {
  const response = await fetch("https://swapi.dev/api/people/1/");
  return reply.send(response.body);
});

fastify.listen({ port: 3000 }, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```

### Expected Behavior

The streamed response should be the same as the JSON response.

**Comment by Uzlopak** [comment]
```js
'use strict'
const { pipeline } = require('node:stream')

const fastify = require(".")({ logger: true });

// return stream from SWAPI - doesn't work
fastify.get("/api/stream", async (request, reply) => {
  const response = await fetch("https://swapi.dev/api/people/1/");
  pipeline(
    response.body,
    reply.raw,
    (err) => err && fastify.log.error
  );
  return reply;
});

fastify.listen({ port: 3000 }, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```


I guess, fetch returns a WHATWG Stream, which is not providing a pipe method, thus not being streamed when using reply.send. 

Maybe a bug, because we dont detect Webstreams, or we have to clarify in the docs, that it need to be a NodeStreamsnot webstreams.

**Comment by TJBlackman** [comment]
I didn't know there was a difference, thank you for the quick answer! Others might benefit from a note about it in the doc site.

**Comment by Uzlopak** [comment]
@climba03003 wrote on discord:

> Prevent pipeline reply.raw if you don't use .hijack
Use node.js provided helper to change between WebStream and NodeStream.
```js
'use strict'
const { Readable } = require('node:stream')

const fastify = require(".")({ logger: true });

fastify.get("/api/stream", async (request, reply) => {
  const response = await fetch("https://swapi.dev/api/people/1/");
  return Readable.fromWeb(response.body);
});

fastify.listen({ port: 3000 }, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```
