### ISSUE TITLE
Fastify response log does not include request details

### ISSUE THREAD

**Issue by SeanReece** [fastify/fastify#5283]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

By default, fastify response logs include details like response time and status code but does **not** include the request URL or method. This makes it difficult to tell what route the response log is for - especially in production environments where there are multiple users and services which can cause the "incoming request" and "request completed" logs to be seperated by multiple other logs.

This works well for local development, but can make it difficult to search for logs in a production environment with multiple users and services running together.

### Current log

<img width="364" alt="image" src="https://github.com/fastify/fastify/assets/2258445/fd875c13-a667-4627-b9b2-deaed4dabcf6">

### Proposal
By including URL and Method in the response logs as well makes it easy to see what this response was for.

<img width="365" alt="image" src="https://github.com/fastify/fastify/assets/2258445/3872f684-b85a-448f-9684-7472669ad304">

### Example
In a production environment with multiple users and services it makes it difficult to find details like response time or user details for a certain endpoint since you must first find the incoming request log, then link the response using the request ID.

This is maybe not the *best* example (I can't display production logs here), but you can see here how 3 requests came in quickly then 3 responses, it is non-obvious which response times are for which request without manually comparing request IDs. You can see how this would be a problem in a busy production environment with millions of logs per hour. Having URL and method in the response would solve this issue.

![image](https://github.com/fastify/fastify/assets/2258445/3c6a68eb-4263-4841-9496-1d3e3680169e)

If this seems like something that would be accepted into Fastify by default I would love to submit a PR. This is possible to do using custom serializers, but this just makes sense to me to include by default.

Thanks!

**Comment by metcoder95** [comment]
👋 
Thanks for the detailed explanation of the issue.
Although I agree with all your statements, the default implementation made by `fastify` was meant to provide the bare minimum requirements for you to kick off a project with low effort but have the opportunity to fully customize the application to your needs.

If seeking to customize the incoming response/request logs, that can be easily done by:
1. Setting `dissableRequestLogging` to `false`
2. Adding an `onRequest` and `onResponse` hook to create the custom logs.

e.g. 
```js
const Fastify = require('fastify');

const fastify = Fastify({ disableRequestLogging: true });

fastify.addHook('onRequest', (request, reply, done) => {
  const newLogger = request.log.child({
    /* custom props here */
  });
  request.log = newLogger;
  done();
});

fastify.addHook('onResponse', (request, reply, done) => {
  request.log.info({
    res: {
      statusCode: reply.statusCode,
      headers: reply.getHeaders(),
      // more info if needed
    },
  });

  done();
});

fastify
  .listen({ port: 3000 })
```

**Comment by climba03003** [comment]
You do not need that complicated code, all information is given to you in `reply`.
If you want the `res` to show more information from the `reply` object in your desire way.
Just customize the logger serializer.

```js
import Fastify from 'fastify'

const fastify = Fastify({ 
  logger: {
    serializers: {
      res(reply) {
        return {
          method: reply.request.method,
          url: reply.request.url,
          statusCode: reply.statusCode
        }
      }
    }
  } 
})

fastify.get('/',  async function(request) {
  return { ok: true }
})

const { body }= await fastify.inject({
  path: '/',
  method: 'GET'
})
console.log(body)
```

**Comment by SeanReece** [comment]
Thanks everyone for the discussion. We had already implemented a serializer like @climba03003 suggested, which I think is the best way to do this.

Just wanted to float the idea out there, but sounds like we want to keep this as-is in fastify for now. I’ll close this issue.
