### ISSUE TITLE
type for onSend hook

### ISSUE THREAD

**Issue by manzonif** [fastify/fastify#529]
There is no type for onSend hook in fastify.d.ts

**Comment by mcollina** [comment]
Would you like to send a PR for it?

cc @evanshortiss

**Comment by manzonif** [comment]
something like this could work?

`addHook(name: 'onSend', hook: (req: FastifyRequest<HttpRequest>, reply: FastifyReply<HttpResponse>, payload: any, done: (err?: Error) => void) => void): FastifyInstance<HttpServer, HttpRequest, HttpResponse>`

**Comment by mcollina** [comment]
I'm a bit lost here. Can you send a PR with the best change for you?

**Comment by manzonif** [comment]
I tried to explain myself better here #533
