### ISSUE TITLE
Incorrect Dependencies Checking

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#5291]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Node.js version

20.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

The code below should not throw an error. Since I specify the plugin `todoService` as a dependency for the plugin `todoRoutes`, but this plugin is also available in the context.  

### Steps to Reproduce

```js
import Fastify from 'fastify'
import fp from "fastify-plugin";

const todoService = fp(async (instance, opts) => {

    instance.decorate('listTodos', (size, offset) => [{ id: 1, title: 'My first todo', text: 'I should write more todos' }])
}, {
    name: 'todoService'
})

const todoRoutes = fp(async (instance, opts) => {

    instance.get('/api/todos', {
        query: {
            size: {
                type: 'integer',
                default: 2
            },
            offset: {
                type: 'integer',
                default: 0
            }
        }
    }, async function (req, reply) {
        return this.listTodos(req.query.size, req.query.offset)
    })
}, {
    name: 'todoRoutes',
    encapsulate: true,
    dependencies: [ 'todoService' ] // if you remove the dependencies option no error will be thrown and we can call the route without any error
})

const app = Fastify()

app.register(todoRoutes).register(todoService)

app.inject('/api/todos', (err, res) => {
    if (err) console.error(err)
    else console.log(res.json())
})

```

The given code will throw the error with the message `AssertionError [ERR_ASSERTION]: The dependency 'todoService' of plugin 'todoRoutes' is not registered`. You can prevent this error by removing the `dependencies: [ 'todoService' ]` option. But since we `can (!)` use the `listTodos` decorator within the `todoRoutes` plugin the assertion should not fail.

**Comment by climba03003** [comment]
I am closing the issue because the dependency check is correct.
You register `todoRoutes` before `todoService`.

`listTodos` can be use because it is inside route handler and all the plugin will be finalized in that time.
If you use it in the plugin of `todoRoutes`, it will not be succeed.
