### ISSUE TITLE
Getting Started should probably include a ESM example for the 'Your First Plugin' section

### ISSUE THREAD

**Issue by mc6415** [fastify/fastify#5292]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently in the documentation under Getting Started and Your First Plugin  [here](https://fastify.dev/docs/latest/Guides/Getting-Started/#your-first-plugin)

There is no ESM example for the plugin, this should probably be added as there's no real mention until that point of the `fastify-plugin` library until the next section so if you just followed the code verbatim you get an error around the module not having an export named default

**Comment by metcoder95** [comment]
Thanks for the report, would you like to submit a PR for it?

**Comment by atilagulers** [comment]
@metcoder95 i've submitted the PR for issue #5292 as suggested.

It includes the ESM example in the 'Your First Plugin' section along with a snipped for `"type: "module"` configuration in the documentation to clarify setup for ESM. Looking forward to the review and feedback.
