### ISSUE TITLE
fastify.inject fails to execute when passing file stream as payload

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#530]
I'm trying to test method that accepts file streams (see https://github.com/fastify/fastify/issues/492 for initial discussion) and I'm using fastify.inject for it.
I've adapted the catch-all test from `custom-parser.test.js` to use inject. The test fails due to timeout (it seems like it just hangs indefinitely):

```js
test('\'*\' catch undefined Content-Type requests via inject', t => {
  t.plan(4)

  const fastify = Fastify()

  t.tearDown(fastify.close.bind(fastify))

  fastify.addContentTypeParser('*', function (req, done) {
    var data = ''
    req.on('data', chunk => { data += chunk })
    req.on('end', () => {
      done(data)
    })
  })

  fastify.post('/', (req, res) => {
    // Needed to avoid json stringify
    res.type('text/plain').send(req.body)
  })

  fastify.listen(0, function (err) {
    t.error(err)

    const fileStream = fs.createReadStream(__filename)

    fastify.inject({
      method: 'POST',
      url: 'http://localhost:' + fastify.server.address().port + '/',
      payload: fileStream
    }, (response) => {
      const body = response.payload
      t.strictEqual(response.statusCode, 200)
      t.strictEqual(body + '', fs.readFileSync(__filename).toString())
    })
  })
})
```

Any ideas why that might happen?

**Comment by yamalight** [comment]
I've openend a PR with a failing test here: https://github.com/fastify/fastify/pull/531

**Comment by StarpTech** [comment]
@yamalight https://github.com/fastify/fastify/blob/master/lib/reply.js#L69 you can only send a stream if you don't set the content-type. Try `res.send(req.body)`

**Comment by StarpTech** [comment]
@yamalight refer to https://github.com/fastify/fastify/blob/master/lib/reply.js#L70 did you try `res.send(req.body)` ?

**Comment by yamalight** [comment]
@StarpTech the issue is in receiving stream, not sending it. Test never even goes to body handling.
Send in this case would dispatch aggregated data from `"*"` content parser (at least as far as I understand it).

**Comment by StarpTech** [comment]
@yamalight perhaps fastify.inject fallback to `application/json` ?

**Comment by yamalight** [comment]
@StarpTech seems like it does indeed adds `application/json` content header, but it is still not clear why the test never finishes - IMO in that case it should throw an error (e.g. cannot parse JSON)

**Comment by yamalight** [comment]
Just tried adding: 
```js
headers: {
  'Content-Type': 'application/octet-stream'
},
```

The result is the same - timeout.

**Comment by mcollina** [comment]
Interesting bug! :)

**Comment by StarpTech** [comment]
@yamalight I tried your code outside of the tests and it works. You run into a timeout because you expect 4 asserts but `t.teardown` does not count :D

**Comment by yamalight** [comment]
Ah, dammit. So that _was_ my stupid mistake.
It does indeed work now, thanks for help!
