### ISSUE TITLE
Conditionals in FastifyRequest based on ContextConfig broken since 4.19.0

### ISSUE THREAD

**Issue by BrianValente** [fastify/fastify#5322]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.1

### Node.js version

18.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.3.1

### Description

Hello! In my project I have conditionals for the `FastifyRequest` type based on the route config in `FastifyContextConfig`. For example, I can add a `needsUserCountry` config to `FastifyContextConfig` like this:

```typescript
declare module 'fastify' {
  interface FastifyRequest<ContextConfig extends FastifyContextConfig> {
    country: ContextConfig['needsUserCountry'] extends true ? string : never;
  }

  interface FastifyContextConfig {
    needsUserCountry?: boolean;
  }
}
```

And then create a route like this:

```typescript
app.get(
  '/countryStringLength',
  {
    config: {
      needsUserCountry: true,
    },
  },
  async (req) => req.country.length,
);
```

The config will be handled by a hook, so the value will be set and the type is correct.

If I set needsUserCountry to false or I don't set it, it will throw an error due to `req.country` being `never`:
<img width="600" alt="image" src="https://github.com/fastify/fastify/assets/3992081/25315b5d-86e9-46f3-922b-a3d618e9a78c">

And if I set it to true, it will work.
<img width="851" alt="image" src="https://github.com/fastify/fastify/assets/3992081/618a31b5-3b44-4bdb-a655-961030a29c71">

In newer releases this behavior is broken.

In 4.19.0 and 4.19.1 the config type requires `url` and `method`, passing random values makes it work. The behavior of `needsUserCountry` works as expected. 
<img width="829" alt="image" src="https://github.com/fastify/fastify/assets/3992081/d4d5dbab-f2f1-4a9b-af90-6cbdb1db28ce">
<img width="948" alt="image" src="https://github.com/fastify/fastify/assets/3992081/d7b2c1cd-ab66-4dfe-94fc-6c8588232421">
<img width="625" alt="image" src="https://github.com/fastify/fastify/assets/3992081/60951761-5f44-444c-aaf3-ff9bb7b198cc">

Since 4.20  `url` and `method` are no longer required, but now configs are not being detected, as if I didn't pass a `config` object.
<img width="600" alt="image" src="https://github.com/fastify/fastify/assets/3992081/ba605e53-d1d9-4e0b-aaef-1ebd6780ecd7">

### Steps to Reproduce

Try this code with Fastify 4.18 and 4.26.1. In 4.18 it will work, in 4.26.1 types will fail.

```typescript
import fastify from 'fastify';

const app = fastify();

declare module 'fastify' {
  interface FastifyRequest<ContextConfig extends FastifyContextConfig> {
    country: ContextConfig['needsUserCountry'] extends true ? string : never;
  }

  interface FastifyContextConfig {
    needsUserCountry?: boolean;
  }
}

app.get(
  '/countryStringLength',
  {
    config: {
      needsUserCountry: true,
    },
  },
  async (req) => req.country.length,
);
```

### Expected Behavior

I expect the `req` object passed to the handler to have the correct types based on the config object of the endpoint.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
