### ISSUE TITLE
Consider using alternative linters/formatters instead of eslint/standardjs

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#5327]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

With this biome.json I can get very close to standardjs. But it will be still result in a lot of changes, as e.g. space between function name and opening paranthesis is not covered by biome and never will be.

```json
{
    "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
    "javascript": {
      "formatter": {
        "bracketSpacing": true,
        "lineEnding":"lf",
        "lineWidth": 120,
        "indentWidth": 2,
        "quoteProperties":"asNeeded",
        "semicolons": "asNeeded",
        "indentStyle": "space",
        "quoteStyle": "single",
        "trailingComma": "none"
      }
    }
  }
```

It should be faster and less space hungry than eslint.

But to be honest I still hope that oxlint by @Boshen adapts all the necessary eslint rules to use oxlint instead of eslint as engine for standardjs.

**Comment by climba03003** [comment]
Massive linting change breaks `git blame` which we should avoid.

**Comment by Eomm** [comment]
I was working on it too, I came up with this setup

```
{
  "$schema": "https://biomejs.dev/schemas/1.3.3/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "style": {},
      "recommended": true,
      "nursery": {
        "all": true
      },
      "correctness": {
        "all": true,
        "useExhaustiveDependencies": "off"
      }
    },
    "ignore": [
      "build/",
      "coverage/",
      "node_modules/"
    ]
  },
  "formatter": {
    "enabled": true,
    "formatWithErrors": false,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 120,
    "ignore": [
      "coverage/",
      "node_modules/"
    ]
  },
  "javascript": {
    "formatter": {
      "semicolons": "asNeeded",
      "quoteStyle": "single",
      "trailingComma": "none"
    }
  }
}
```

**Comment by jsumners** [comment]
In my opinion, if the tool does not ship with Node.js (as `npm` does), then it should be installable via `npm` without needing extra intervention. Does this tool work like that?

**Comment by Uzlopak** [comment]
You can install biome as a npm package, if this is your question?

**Comment by mcollina** [comment]
A few bits:

1. Please don't change the formatting rules. Changing them makes maintaining multiple lines _a nightmare_ (more than what it already is).
2. I'm generically -1 in installing a binary dependency for most modules, as it makes running our kit much harder on _odd_ platforms that Node.js supports (AIX for one). They require _so much more maintenance work_, and it would be problematic if they become unmaintained. (I've heard that biome were looking into a wasm build, in case we could consider using that).

Generically, I'm -1 for biome.

@voxpelli is working on the problem, or possibly standard will actually resume work soon. Either way, we can find a good solution for this using @stylistic/eslint-plugin.

I'm not sure how often you run standard, but I ran it _once_ before doing a commit and it takes  very little time.


--

Does Biome support some form of reusable config, so we can share it across all our repos without having to add it everywhere?

**Comment by voxpelli** [comment]
If `standard` is too slow then we should fix `standard`

Often when ESLint is slow it's because one uses a rule from eslint-plugin-import or typescript-eslint that causes eg all types to be calculated for the entire project

As far as I know no such rule is part of standard core

**Comment by jsumners** [comment]
> You can install biome as a npm package, if this is your question?

As @mcollina hinted, it may have an npm package but that doesn't mean you can run it from the npm package. Last I heard, you _must_ download a binary and install it in your `PATH` before it can be used. I am staunchly against that, unless, as I said, it ships with Node.js.

**Comment by mcollina** [comment]
> With this biome.json I can get very close to standardjs. But it will be still result in a lot of changes, as e.g. space between function name and opening paranthesis is not covered by biome and never will be.

why it _never will be_? Has anybody asked for this feature? This seems a deal breaker for me - it would create a massive amount of churn.

**Comment by Uzlopak** [comment]
Yes, @KhafraDev asked explicitly for this and they rejected his request.

**Comment by Uzlopak** [comment]
Accidently closed

**Comment by Uzlopak** [comment]
@mcollina 

References
https://github.com/biomejs/biome/discussions/982
https://github.com/biomejs/biome/discussions/1193

**Comment by mcollina** [comment]
I guess this settle it then.
