### ISSUE TITLE
Is piping request streams possible?

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#534]
As I've figured it out with your help (thank you again for bearing with me 😄 ) in https://github.com/fastify/fastify/issues/492, one can accept streams using content type parser, i.e.:
```js
fastify.addContentTypeParser('*', function (req, done) {
  var data = ''
  req.on('data', chunk => { data += chunk })
  req.on('end', () => {
    done(data)
  })
})
```

My question is - is it possible to pipe request stream into something? E.g. in express/hapi/micro/etc one can do something like this:
```js
// init project
var express = require('express');
var app = express();

// http://expressjs.com/en/starter/basic-routing.html
app.post("/", function (request, response) {
  request.pipe(response);
});

// listen for requests :)
var listener = app.listen(process.env.PORT, function () {
  console.log('Your app is listening on port ' + listener.address().port);
});
```

And when sending POST request to `/` you'll get your body as a response.
Is it possible to do this with fastify? (not speaking about piping request to response, but rather piping request to other useful libs)

**Comment by mcollina** [comment]
I think you can do:

```js
fastify.addContentTypeParser('*', function (req, done) {
  done()
})
```

and then access the core HTTP request directly, and pipe it where you want:

```js
app.post('/hello', (request, reply) => {
  reply.send(request.req)
})
```

**Comment by yamalight** [comment]
@mcollina well, that was easy. Thanks! 👍 
Gonna close this :)

**Comment by dbauszus-glx** [comment]
I am struggling to get this working.

I have an endpoint which calls a module to handle images being uploaded to the server.

```
fastify.route({
  method: 'POST',
  url: global.dir + '/api/images/new',
  beforeHandler: fastify.auth([fastify.authRoutes]),
  handler: (req, res) => {
    require('./mod/images').save(req, res, fastify);
  }
});
```

Following the first example I see the data but done(data) doesn't seem to call the route.
```
fastify.addContentTypeParser('*', function (req, done) {
  var data = ''
  req.on('data', chunk => { data += chunk })
  req.on('end', () => {
    done(data)
  })
})
```

Following the second example the route is called but the body is empty and I wouldn't know how to handle the stream.
```
fastify.addContentTypeParser('*', function (req, done) {
  done()
})
```

**Comment by dbauszus-glx** [comment]
This seems to work...

Just need to figure a way to set the encoding to binary.

```
    fastify.addContentTypeParser('*', (req, done) => {
        done();
    });

    fastify.route({
        method: 'POST',
        url: global.dir + '/api/images/new',
        handler: (req, res) => {
            req.body = '';
            req.req.on('data', chunk => { req.body += chunk });
            req.req.on('end', () => {
                require('./mod/images').save(req, res, fastify);
            });
        }
    });
```

**Comment by dbauszus-glx** [comment]
Might be me doing something wrong but the only way I could create the binary buffer was like so...

```
    fastify.addContentTypeParser('*', (req, done) => {
        done();
    });

    fastify.route({
        method: 'POST',
        url: global.dir + '/api/images/new',
        handler: (req, res) => {
            var data = [];
            req.req.on('data', chunk => data.push(chunk));
            req.req.on('end', () => {
                req.body = Buffer.concat(data);
                require('./mod/images').save(req, res, fastify);
            });
        }
    });
```

The body can then be transformed to a base64 string for upload to cloudinary et al.

Might be helpful to someone coming from express like me and trying to convert their backend to fastify.
