### ISSUE TITLE
customErrorHandler is a mystery in the documentation

### ISSUE THREAD

**Issue by tmcw** [fastify/fastify#5353]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In the documentation for [onError](https://fastify.dev/docs/latest/Reference/Hooks/#onerror), it mentions:

> This hook will be executed only after the customErrorHandler has been executed, and only if the customErrorHandler sends an error back to the user (Note that the default customErrorHandler always sends the error back to the user).

The only other mention I can find of customErrorHandler is in the TypeScript reference, which [says the same thing](https://fastify.dev/docs/latest/Reference/TypeScript/#fastifyonerrorhookhandlerrawserver-rawrequest-rawreply-requestgeneric-contextconfigrequest-fastifyrequest-reply-fastifyreply-error-fastifyerror-done---void-promiseunknown--void)

I think that what both of these are referring to is the [argument to setErrorHandler](https://fastify.dev/docs/latest/Reference/Errors/#errors-in-fastify-lifecycle-hooks-and-a-custom-error-handler), which is called "Custom Error Handler", but this is a little surprisingly difficult to figure out, without a link or a searchable name.

**Comment by mcollina** [comment]
good spot! A custom error handler is indeed what is set by `setErrorHandler()`. Would you like to open a PR to amend the docs?

**Comment by tmcw** [comment]
Yep! Might be a day or two but it's on my todo list.
