### ISSUE TITLE
Attaching .on('data', (chunk) => { }) to fs.createReadStream(filePath) returns incomplete/corrupted downloads on the client.

### ISSUE THREAD

**Issue by jerrywoo96** [fastify/fastify#5362]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

21.7.1

### Operating system

Windows 10 Pro

### Operating system version (i.e. 20.04, 11.3, 10)

Version 22H2 (OS Build 19045.4170)

### Description

I'm trying to keep track if the file is still actively accessed or transferred to the client.  My use case in the listener is to reset a timeout that is used to delete the file after a certain period of time if the file is not accessed anymore.

Not working, file did not complete downloading on the client:
```
fastify.get('/', async (req, res) => {
  return fs.createReadStream(filePath).on('data', (chunk) => { });
});
```

Working as expected, file is downloaded successfully, full and intact:
```
fastify.get('/', async (req, res) => {
  return fs.createReadStream(filePath);
});
```

### Steps to Reproduce

```
fastify.get('/', async (req, res) => {
  return fs.createReadStream(filePath).on('data', (chunk) => { });
});
```

### Expected Behavior

complete and intact file after download is finished.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment]
Just a short conjecture:

A ReadableStream inherits the `.on()` method from EventEmitter. `.on()` does not return the Stream, but an AsyncIterator of the events you specified. So by returning the result of the `.on()` call you get only an Iterator of `data` events, and probably send only the first chunk as the AsyncIterator will probably only awaited once, as it is not identified as a stream.

So if my assessment is right, as I actually did not test if the claims regarding the AsyncIterator etc. are right, then you should do:

```js
fastify.get('/', async (req, res) => {
  const fileStream = fs.createReadStream(filePath);
  fileStream.on('data', () => {});
  return fileStream;
});
```
