### ISSUE TITLE
POST with empty body fails

### ISSUE THREAD

**Issue by yamalight** [fastify/fastify#537]
Fastify fails when handling POST requests with empty body (be it none specified or `content-length: 0`) - `HTTP/1.1 415 Unsupported Media Type`.
Is that intended? Or are there any additional steps needed to make it work?

**Comment by delvedor** [comment]
Hi!
Have a look at #297, #419 and #450 :)

*Closing this and marking as duplicate.*

**Comment by yamalight** [comment]
Ah, should've searched first. Thanks!
