### ISSUE TITLE
setSerializerCompiler bugs

### ISSUE THREAD

**Issue by lacherogwu** [fastify/fastify#5370]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

20.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.6.3

### Description

1. if fastify router handler returns a number, even tho the schema response 200 is expecting a number or even any, it return an error FST_ERR_REP_INVALID_PAYLOAD_TYPE "Attempted to send payload of invalid type 'number'. Expected a string or Buffer.
2. fastify.setSerializerCompiler not called if a string is returned from route handler

### Steps to Reproduce

First issue:
```javascript
import Fastify from 'fastify';

const fastify = Fastify({
	logger: true,
});

fastify.setSerializerCompiler(() => {
	return data => {
		console.log('data');
		return data;
	};
});

fastify.route({
	url: '/',
	method: 'GET',
	handler: async (request, reply) => {
		return 1234; // this route returns error FST_ERR_REP_INVALID_PAYLOAD_TYPE (Attempted to send payload of invalid type 'number'. Expected a string or Buffer.)
	},
	schema: {
		response: {
			200: {
				type: 'number', // even if I used 200: z.any() it has the same results
			},
		},
	},
});

await fastify.listen({
	port: 3000,
	host: '0.0.0.0',
});

```

Second issue:

```javascript
import Fastify from 'fastify';

const fastify = Fastify({
	logger: true,
});

fastify.setSerializerCompiler(() => {
	return data => {
		console.log('data'); // this not even called
		return data;
	};
});

fastify.route({
	url: '/',
	method: 'GET',
	handler: async (request, reply) => {
		return 'hello; 
	},
	schema: {
		response: {
			200: {
				type: 'string',
			},
		},
	},
});

await fastify.listen({
	port: 3000,
	host: '0.0.0.0',
});

```

### Expected Behavior

First issue:
the schema should pass because the route handler returns a number and the schema expects a number

Second issue:
the serialize compiler callback should be called

**Comment by climba03003** [comment]
1. `setSerializerCompiler` must return either `string` or `Buffer` despite how the `schema` is defined.
That being said, when you schema defined a `object`. You still need to return `string` or `Buffer` because it is what it expected to be passed through Internet.

2. `string`, `Buffer`, `Readable`, `ReadableStream` are treated as already serialized content. So, it will not trigger any serialization.
