### ISSUE TITLE
feat: Dependency graph for Plugins on Teardown

### ISSUE THREAD

**Issue by metcoder95** [fastify/fastify#5375]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, `fastify` allows specifying dependency between plugins at startup, meaning that if plugin A hasn't been registered at the moment plugin B is being registered, and has A marked as a dependency of B, the bootup will fail as this requirement hasn't been met.

There will be use cases where the same graph might be required on `teardown` while calling `fastify.close`, as is possible plugins has hooks set for `onClose` that executes cleanup processes that depends on other plugins.

### Motivation

_From: https://github.com/fastify/help/issues/1018_

>Is there any way to specify which onClose (or preClose) hooks from each plugin should be executed before the others? I have some plugins that rely on other main plugins in order to execute correctly their onClose hooks.
>
>E.G.: Some plugins need the database plugin in order to perform some cleaning operations on the database before closing the server. If the database plugin gets torn down before the plugin, the database client results disconnected.

### Example

```js
const fastify = require('fastify');
const dbPlugin = require('./my-db-plugin');
const otherPlugin = require('./my-other-plugin');

// my-db-plugin.js
async function plugin(instance, opts) {
	fastify.decorate('database', mydbdriver);

	fastify.addHook('onClose', async (app) => {
		console.log('second');
		// Let's say that my-other-plugin requires
		// the database plugin to execute some cleanup work, whatever this could be
		await app.database.close();
	});
}

module.exports = fp(plugin, { name: ['database']});

// my-other-plugin.js
async function plugin(instance, opts) {
	fastify.addHook('onClose', async (app) => {
		console.log('first');
		// Let's say that my-other-plugin requires
		// the database plugin to execute some cleanup work, whatever this could be
		await app.database.cleanup();
	});
}

module.exports = fp(plugin, { name: 'other', dependencies: ['database']});

// index.js
// ... all the bootup process
await fastify.close();

// fastify understands the graph and knows my-db-plugin is dependency of my-other-plugin
// for instance it executes hooks in the inverse order of the dependency graph.
// Starting with my-other-plugin and later my-db-plugin.
// Printing in the console
// first <- from my-other-plugin
// second <- from my-db-plugin

```

**Comment by giovanni-bertoncelli** [comment]
Thank you @metcoder95, for a PR where would you suggest to start?

**Comment by mcollina** [comment]
those hooks are executed in reverse order. What's the problem?

**Comment by jsumners** [comment]
Also, there isn't a graph of the plugins. It's a simple check when loading each one to determine if another plugin is in scope that satisfies the requirements.

**Comment by giovanni-bertoncelli** [comment]
So this feature is already included in Fastify? The teardown sequence is the boot sequence in reverse order?

**Comment by metcoder95** [comment]
True, I overlooked that; as @jsumners suggested, it's not exactly like a graph so maybe not so strict as that, but when loading the plugins you have an explicit dependency that will be checked while registering your plugin, and for instance, the hooks will be added in that specific order. It fulfills the requirements:

e.g.
```js
const fastify = require('fastify');
const fp = require('fastify-plugin');

// my-db-plugin.js
async function pluginA(instance, opts) {
    const db = {
        close: () => {
            console.log('closing db');
        },
        closed: false,
    }

    instance.decorate('database', db);

    instance.addHook('onClose', async (app) => {
    console.log('second');
    await app.database.close();
  });
}

// my-other-plugin.js
async function pluginB(instance, opts) {
    instance.addHook('onClose', async (app) => {
    console.log('first');
    console.log('is it closed?', app.database.closed)
  });
}

const databaseplugin = fp(pluginA, { name: 'database' });
const otherPlugin = fp(pluginB, { name: 'other', dependencies: ['database'] });

// index.js
// ... all the bootup process
const app = fastify();
app.register(otherPlugin);
app.register(databaseplugin);

(async () => {
    await app.ready();
    await app.listen();
    await app.close();
})()
```

Prints:
```shell
first
is it closed? false
second
closing db
```

You have an explicit order there marked by your dependencies, if e.g. you change the order you register the plugins:
```js
const otherPlugin = fp(pluginB, { name: 'other', dependencies: ['database'] });
const databaseplugin = fp(pluginA, { name: 'database' });
```

This will automatically fail to stop you from the beginning

**Comment by Eomm** [comment]
TBH I think this could be a feature here: https://github.com/Eomm/fastify-overview/
It generates a graph of your application at runtime, but it does not have this debug mode when the server crash

**Comment by metcoder95** [comment]
Shall we move the issue there?
