### ISSUE TITLE
'type' parameter name gives error in schema.querystring Routes options

### ISSUE THREAD

**Issue by AlexanderRyzhov** [fastify/fastify#5376]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

20.10.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

While configuring query params validation schema I wanted to set 3 parameters: **limit**, **skip**, **type**.
Here is the code:
``` javascript
const getAllCompaniesOptions = {
  schema: {
    querystring: {
      skip: { type: "number" },
      limit: { type: "number" },
      type: { type: "string" },
    },
  },
};

async function routes(fastify, options) {
  fastify.get("/", getAllCompaniesOptions, companyController.getAllCompanies);
}
```
this code gives me this error after running:
```
FastifyError [Error]: Failed building the validation schema for GET: /api/v1/companies, due to error schema is invalid: data/type must be equal to one of the allowed values, 
data/type must be array, data/type must match a schema in anyOf
    at Boot.<anonymous> (G:\apps\mss-gis\crm_api\node_modules\fastify\lib\route.js:396:21)
    at Object.onceWrapper (node:events:628:28)
    at Boot.emit (node:events:526:35)
    at Boot.emit (node:domain:488:12)
    at G:\apps\mss-gis\crm_api\node_modules\avvio\boot.js:160:12
    at G:\apps\mss-gis\crm_api\node_modules\avvio\plugin.js:275:7
    at done (G:\apps\mss-gis\crm_api\node_modules\avvio\plugin.js:200:5)
    at check (G:\apps\mss-gis\crm_api\node_modules\avvio\plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9) {
  code: 'FST_ERR_SCH_VALIDATION_BUILD',
  statusCode: 500
}
```
Seems, that error ocuures because parameter name **type** matches to reserved name **type**.
But technically this is valid json schema and it must work.

### Steps to Reproduce

``` javascript
const getAllCompaniesOptions = {
  schema: {
    querystring: {
      type: { type: "string" }
    },
  },
};

async function routes(fastify, options) {
  fastify.get("/", getAllCompaniesOptions, companyController.getAllCompanies);
}
```

### Expected Behavior

I expect, that provided schema should not give any error while application is starting.

**Comment by climba03003** [comment]
I would say that always use the complete `JSON Schema`.

The shorten form will only be transformed when both `type` and `properties` are not exists.
https://github.com/fastify/fastify/blob/af2ccb5ff681c1d0ac22eb7314c6fa803f73c873/lib/schemas.js#L134-L139
