### ISSUE TITLE
Strings should not be wrapped in quotes

### ISSUE THREAD

**Issue by thupi** [fastify/fastify#538]
Hi,

First of all i love the simplicity and clean approch with the framework.

However, i am woriking with at SqlServer that returns json as a string.

I would like to output the  string while keeping the content-type as json.

As far as i know fastify automaticly wraps the content ind quotes if reply.send is passed a string.

How would one achive this :-) ?

My current workarround is the following.

`
reply.header("Content-Type", "application/json").serializer(i => i).send(result.recordsets[0][0]["JSON_F52E2B61-18A1-11d1-B105-00805F49916B"]);
`

**Comment by jsumners** [comment]
If the result is `"foo"`, that is valid JSON per RFC.

**Comment by jsumners** [comment]
Closing because PR #540 should resolve this. Re-open if you determine otherwise.

**Comment by thupi** [comment]
@jsumners How would i be able to apply type('application/json') without fastify automaticly json.stringify the content :-) ? 

As far as i know i still have to do the trick i mentioned before :-) ?

**Comment by nwoltman** [comment]
@thupi In the next version of Fastify, you could also send your payload as a buffer:

```js
const payload = Buffer.from(result.recordsets[0][0]["JSON_F52E2B61-18A1-11d1-B105-00805F49916B"]);
reply.header("Content-Type", "application/json").send(payload);
```

**Comment by thupi** [comment]
@nwoltman Thats the exact use case i need that behavior for :-) ! Thanks for letting me know :-) !
