### ISSUE TITLE
Should send error response from a errorHandler without executing request lifecycle

### ISSUE THREAD

**Issue by ritikrao1** [fastify/fastify#5385]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

14.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.3

### Description

when we try to send response from a custom error handler with statuscode 500, it executes request lifecycle with preserialization, onsend hooks, but we guessed it sends response when sent from a error handler

### Steps to Reproduce

run the code below and hit 'http://localhost:3000/' 
```
const fastify = require("fastify");
const app = fastify({logger: true});

app.addHook('preHandler', async (req, res) => {
    console.log(req.method);
    console.log("authentication");
    return ;
})

app.addHook('preValidation', (request, reply, done) => {
    if(request.method === 'POST'){
      request.body = request.body || {};
    }
    done();
})

const asyncfunction = async ( ) => {
    console.log('in async function');
    return {};
}

const plugin1 = (app, options, done)=>{
    app.post('/', {handler: async (req, res) => {
        req.result = { msg: "hello"};
        res.status(200).send(req.result);
        return res;
    }})

    app.addHook('preSerialization', async (req, res, payload) => {
        const newPayload= await asyncfunction();
        throw new Error('preSerialization error');
        return newPayload;
    });
    
    app.setErrorHandler(async (err, req, res) => {
        console.log('in inner error');
        throw new Error('preSerialization error');
    });
    done();
}

app.register(plugin1);

app.setErrorHandler(async (err, req, res) => {
    console.log('in inner outer');
    res.status(500).send({ msg: "error response" });
    return res;
})

app.addHook('onReady', (done) => {
    console.log("Service running on port: 3000");
    done();
});
app.listen({host: 'localhost', port: 3000});
```

### Expected Behavior

getting this response :- 
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "preSerialization error"
}
expected response:-
{
    "msg": "error response"
}
which is sent from error handler at root context

**Comment by climba03003** [comment]
The current behavior is actually well documented.

https://github.com/fastify/fastify/blob/c90ac14c7179606bb0833447dda1b83007156fa5/docs/Reference/Errors.md?plain=1#L158-L172

If you wish to skip `preSerialization`, you should send serialized content (e.g. `string`, `Buffer`, `stream`).

**Comment by climba03003** [comment]
> can you confirm if it will break in any case ?

At least I don't see it will break in a case currently.
For my own project, I do send serialized content as last resort.
Working fine since I use `fastify`.
