### ISSUE TITLE
docs: update the HTTPS server tutorial link of the section regarding TypeScript 

### ISSUE THREAD

**Issue by Tony133** [fastify/fastify#5387]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In the Typescript section, in the chapter "`API type system documentation`", in `"example 2 https-server"` (see here:
https://fastify.dev/docs/latest/Reference/TypeScript/#example-2-https-server), the link `Node.js https server guide`, returns page not found ( see screenshot ),

<img width="1045" alt="link-example" src="https://github.com/fastify/fastify/assets/11542387/f898bdf7-9f09-4c79-9888-8ffcfa1bcd3f">
<img width="1512" alt="page-not-found" src="https://github.com/fastify/fastify/assets/11542387/5157b96d-79e5-42b5-92e9-4a0726a7ca2c">

**Comment by metcoder95** [comment]
Thanks for the report, would you like to send a PR?

**Comment by Tony133** [comment]
> Thanks for the report, would you like to send a PR?

Yes of course, but what link do we put in place of the one that doesn't work ? I found this example in the Node.js documentation: https://nodejs.org/api/https.html#httpscreateserveroptions-requestlistener

could it be ok ?  because I don't remember exactly the tutorial `"Node.js https server guide"` what example it showed  😅

**Comment by metcoder95** [comment]
Yeah, that should be a good start, maybe we'll need to change the wording to state that the link points to the official documentation instead

**Comment by Tony133** [comment]
Created PR: #5389

**Comment by Fdawgs** [comment]
closed by #5389
