### ISSUE TITLE
Serve both home page and static assets from /

### ISSUE THREAD

**Issue by stephen-last** [fastify/fastify#539]
I'm using `fastify-static` to serve static assets (`js`, `css`):

```js
import fastify from 'fastify'
import fastifyStatic from 'fastify-static'

fastify.register(fastifyStatic, {
  root: path.join(__dirname, '/../../', 'public'),
  prefix: '/public/'
})
```

This works, and I can use `/public/js/main.js` etc. However, I'd like to serve the static assets from `/js/main.js`. Changing `prefix: '/public/'` to `prefix: '/'` seems to add a conflict and I get:

> Error: GET already set for /

I already have a route which is used to stream my server rendered React HTML:

```js
fastify.get('/', async (request, reply) => {
  const stream = new PassThrough()
  stream.write('<!DOCTYPE html>')
  const reactStream = ReactDOMServer.renderToNodeStream(
    <HTML>
      <PageComponent />
    </HTML>
  )
  reactStream.pipe(stream, { end: false })
  reactStream.on('end', () => stream.end())
  reply.header('Vary', 'Accept-Encoding').type('text/html').send(stream)
})
```

Serving both the HTML and static assets from the root is possible using `express`.

How do I do this using `fastify`..?

**Comment by mcollina** [comment]
This is currently not possible with fastify. I don’t think this would be a good idea, as it would definitely slow things down: currently our router match one handler and one handler only.

I’m not sure what the others think.

**Comment by jsumners** [comment]
I can understand the desire, but I really don't see a problem with having routes for resources. Plus, this could be solved in your proxy. Here's an HAProxy example:

```conf
frontend foo-service
  bind 10.0.0.5:80
  default_backend foo-backend

  acl images path_beg /images
  use_backend images-backend if images

backend foo-backend
  server foo1 10.0.0.6:8080 check

backend foo-images
  http-request set-path %[path,regsub(/images/,/)]
  server foo1 10.0.0.6:8080 check
```

**Comment by jsumners** [comment]
If you have an application that you're trying to port over, and don't want to update all of your templates to reference new resource locations, one solution would be to have a different server specifically for your static resources. Then you would configure your proxy to reference that server:

static server:
```js
const fastify = require('fastify')()
fastify.register(require('fastify-static'), {prefix: '/'})
// etc.
```

HAProxy example:
```conf
frontend foo-service
  bind 10.0.0.5:80
  default_backend foo-backend

  acl static path_end .gif .jpg .jpeg .png
  acl static path_end css js
  acl static path_beg /images/ /users/
  acl static path_dir static
  use_backend foo-static if static

backend foo-backend
  server foo1 10.0.0.6:8080 check

backend foo-static
  # redirect some requests to /
  http-request set-path %[path,regsub(/images/,/)]
  server foo1 10.0.0.6:8888 check
```

**Comment by stephen-last** [comment]
The main reason for this question relates to when third-parties ask for, or even require something be accessible from the root.

In my experience it's mainly been round providing proof of domain ownership from services ranging from webmaster tools to SSL certs. Because of these, I've always tried to serve static assets from the root to avoid problems down the road.

They might say "create a file called `/godaddy.html` and put this string in it", or "download this HTML verification file. `google6fefe36644ee8362.html`"etc... I know most offer alternative ways of doing these things, it's just I often find it easiest to drop a file into the static assets folder.

This isn't really problem, I guess new static routes can be added to serve one off requests like these, it's just not as easy.

I'm on Windows (in dev and prod) and had never heard of `HAProxy` before.

**Comment by jsumners** [comment]
Well, in all of those situations I would turn to HAProxy 😆

There's a couple solutions I can think of:

1. Use whatever proxy you (probably?) have in front of your application to direct such requests to the right place
2. Implement a parameterized `/` handler, e.g. `fastify.get('/:item', ...)`
3. Use a custom 404 handler to serve out the content

You should really consider the security ramifications of 2 and 3 (if they are even viable).
