### ISSUE TITLE
Route schema might be undefined

### ISSUE THREAD

**Issue by nflaig** [fastify/fastify#5393]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Node.js version

20.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Description

`FastifyRequest.routeSchema` might be undefined, for example if route does not exists. The type currently can't be trusted if you would try to access the schema within any [hook](https://fastify.dev/docs/latest/Reference/Hooks/#requestreply-hooks).

I think the type here should be marked as optional

https://github.com/fastify/fastify/blob/4a35a5ae7d011b700446d7a145382958ba62d517/types/request.d.ts#L67

and same goes for schema in route options
https://github.com/fastify/fastify/blob/4a35a5ae7d011b700446d7a145382958ba62d517/types/request.d.ts#L34

### Steps to Reproduce

Set up fastify with a hook like `onRequest` and observe schema while calling a route that has no been defined.

### Expected Behavior

The type should correctly reflect runtime behavior

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gurgunday** [comment]
I think in `next` we should fix the type instead and it should be undefined again

**Comment by mcollina** [comment]
We can do that in v4 if you all prefer to allow it to be undefined.
