### ISSUE TITLE
Should "disableRequestLogging" suppress aborted requests?

### ISSUE THREAD

**Issue by kwaschny** [fastify/fastify#5398]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When having `disableRequestLogging: true` as server option, the logger will still write an info about every request that has been aborted, either due to the [server being in closing state](https://github.com/fastify/fastify/blob/main/lib/route.js#L490) or the [request having an invalid HTTP version](https://github.com/fastify/fastify/blob/main/lib/route.js#L461).

This has been [documented](https://fastify.dev/docs/latest/Reference/Server/#disablerequestlogging):
> Other log messages emitted by Fastify will stay enabled, like deprecation warnings and messages emitted when requests are received while the server is closing.

Now my question is: **Why is logging of these requests not considered by `disableRequestLogging`?** These requests are expected to be aborted/rejected, so why would I want them to appear in the log when disabling request logging?

---

_(As a side note: The content length of the `503` response during server closing [is hardcoded](https://github.com/fastify/fastify/blob/main/lib/route.js#L486)). The `505` response is doing it [the right way](https://github.com/fastify/fastify/blob/main/lib/route.js#L465).)_

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/pull/4600#discussion_r1117936668

**Comment by kwaschny** [comment]
I see. So it has not been overlooked, it is just an opinion. Thanks for pointing to the decision.
