### ISSUE TITLE
do not JSON.stringify strings by default

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#540]
Currently we are converting strings to JSON by default, but possibly we should render them as text-plain, without kicking in the serializer.

**Comment by mcollina** [comment]
This is slightly related to https://github.com/fastify/fastify/issues/538, but a different use case.

I propose that:

```js
fastify.get('/', (req, reply) => {
  reply.send('hello world')
})
```

Renders `hello world` instead of `"hello world"`.

**Comment by delvedor** [comment]
Agree, I'll do this.

**Comment by allevo** [comment]
Why?

This can be achieved with
```
fastify.get('/', (req, reply) => {
  reply.type('text/plain').send('hello world')
})
```

**Comment by mcollina** [comment]
Because that's not what user will expect.
