### ISSUE TITLE
`addContentTypeParser` doesn't work well after `await register`

### ISSUE THREAD

**Issue by scott1028** [fastify/fastify#5401]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

v4.26.2

### Node.js version

20

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

`addContentTypeParser` doesn't work as expected when previous statement is `register` with `await`.

### Steps to Reproduce

ex:

```
'use strict'

const main = async () => {
  const server = require('fastify')({
    logger: true,
  });

  const schema = {
    schema: {
      response: {
        200: {
          type: 'object',
          properties: {
            hello: {
              type: 'string',
            },
          },
        },
      },
    },
  };

  await server.register((fastify, options, done) => {
    fastify.get('/api/upload', async (req, res) => {
      return { hello: 'world0' };
    })
    fastify.post('/api/upload', async (req, res) => {
      return { hello: 'world1' };
    })
    done();
  });

  server.get('/', schema, function (req, res) {
    res.send({ hello: 'world2' });
  });

  // This parser will not work after "server.register" in "await"
  server.addContentTypeParser(
    'text/csv',
    { parseAs: 'string' },
    (req, body, done) => {
      // Custom parsing logic for text/csv content type for api plugin
      const csvData = body.split('\n').map((row) => row.split(','));
      done(null, csvData);
    },
  );

  server.listen({ port: 3000 }, (err, address) => {
    if (err) {
      throw err;
    }
  });
};

main();
```

```
curl -H "Content-Type: text/csv" -X POST --data "a,b,c" http://localhost:3000/api/upload
// you will get below
{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: text/csv"}
```

### Expected Behavior

the CSV parser should work as expected.
```
curl -H "Content-Type: text/csv" -X POST --data "a,b,c" http://localhost:3000/api/upload
{"hello":"world1"}
```

**Comment by Uzlopak** [comment]
So you claim there is a race condition?

**Comment by scott1028** [comment]
> So you claim there is a race condition?

I don't think it a race condition issue because it can work by removing `await`.

**Comment by climba03003** [comment]
Not sure if is it mentioned in document.
But `await fastify.register` is the same as `fastify.after` which means all the later code will be run in different context.

My suggestion is that only add `await` when necessary.

**Comment by climba03003** [comment]
I believe similar fix can be used like `setErrorHandler`.
See https://github.com/fastify/fastify/issues/4204#issuecomment-1219350123 https://github.com/fastify/fastify/pull/4205

**Comment by mcollina** [comment]
Albeit surprisingly, this is expected behavior. This should be clarified in our docs.

**Comment by moradebianchetti81** [comment]
I'd like to take on this documentation update issue
