### ISSUE TITLE
 Backport webdav methods from next to current branch

### ISSUE THREAD

**Issue by johaven** [fastify/fastify#5412]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi team,

I would like to know if it would be possible to backport this commit (https://github.com/fastify/fastify/pull/4409) to the current branch. 

It was merged a long time ago now and I'm not sure that v5 will be ready soon.

On NestJS side I have a PR waiting for these changes: https://github.com/nestjs/nest/pull/13278

These changes have been expected by many for some time, with very little effort I think we could offer this feature right now.
I tested these changes and everything works fine on v4.2 (only the body parsing is missing: https://github.com/fastify/fastify/pull/5411)

**Comment by gurgunday** [comment]
Moving my comment here:

Per @climba03003's comment: https://github.com/fastify/fastify/pull/4409#pullrequestreview-1173708744

Backporting these shorthands could conflict with decorated properties of current users, making this breaking

**Comment by johaven** [comment]
Is there currently a system to prevent http methods from being used as decorators?

We could implement a way to warn the user that he will not be able to use a method name as a decorator in the next version.

In the current version we could check the name of the decorator used, display a warning and prioritize the execution of the user decorator rather than the method to avoid any break.

Just an idea :)

Even if V5 was released tomorrow, I think the NestJs team will take some time before integrating this version into their framework.
I'm just trying to find a solution to prevent the community from waiting a few more years just for some rather standard methods (which are very useful to us in our tools and applications).

**Comment by gurgunday** [comment]
> Is there currently a system to prevent http methods from being used as decorators?

It just throws, as an example you can try: `fastify.decorate('head', () => {})`, it should throw

> I'm just trying to find a solution to prevent the community from waiting a few more years

I (and others) really want `v5` to be released as soon as possible and we will be pushing for it, right now I just know that most maintainers are busy as node 22 (next LTS) is about to be released, so there is focus on getting as much stuff in it as possible

How about making decorated webdav methods an option (turned off by default in `v4`)

I would fully support that actually

**Comment by climba03003** [comment]
You are not block from using those methods by `fastify.route`.
It is not necessary for the shorten method exist before using.

**Comment by mcollina** [comment]
I think that creating the verb helpers could be done inside Nest if you really need them.

Generically this is not needed, because you can always use `.route()`. If you can't, it's on Nest.

**Comment by johaven** [comment]
All verb helpers are well defined in PR: https://github.com/nestjs/nest/pull/13278/files

Indeed the problem is that Nest uses the instance followed by the method to handle the requests in their adapter: https://github.com/nestjs/nest/blob/727032e46e2371a934a1a99ec42634fabd271738/packages/platform-fastify/adapters/fastify-adapter.ts#L705

**Comment by johaven** [comment]
> I think that creating the verb helpers could be done inside Nest if you really need them.

This is probably the best solution in the meantime.

In my view, Nest's Fastify adapter should call methods from `fastify.route` rather than from the instance to ensure that the call is made on a method rather than a user decorator.

If there are no other comments I will close this discussion.
