### ISSUE TITLE
Drop Boom support

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#542]
In the same way that we are not supporting out of the box [Joi](https://www.npmjs.com/package/joi), I think we should not support out of the box [Boom](https://www.npmjs.com/package/boom).
If a user wants to use Joi, it can do it by using the [setSchemaCompiler](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#setschemacompiler) api.
I think that in the same way if a user want to use Boom *(which is not a core Fastify library)* it can use the [setErrorHandler](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#seterrorhandler) api and handle it accordingly.

Why this proposal?
I want to simplify the logic of Reply before release the v1.0.0, and in my opinion the Boom support is something that we can remove since is unnecessary.

To be very specific, I'm proposing to remove the following lines:
https://github.com/fastify/fastify/blob/4a6396e8a3f1ba0292f5a52e220122e382e0440f/lib/reply.js#L49-L62

@fastify/fastify thoughts?
Please do no think *"but I need it"*, you can accomplish the same thing with `setErrorHandler`, I'm just talking about if it is needed by the framework itself.

**Comment by jsumners** [comment]
Works for me.

**Comment by allevo** [comment]
I like the error handling in `fastify`: it simplifies a lot the development. Moving the `Boom` support to outside could be a not good thing for the new users. We have to write a plugin that implement the same `Boom` interface. 

On the other side, I'd like to keep `fastify` as light as possible.

So I'm :+1:  with a nit

**Comment by mcollina** [comment]
I think we should provide a plugin to do that, it will be a good example.

**Comment by jsumners** [comment]
Closing since the actual issue is resolved. I created #569 to deal with the plugin idea.
