### ISSUE TITLE
Merge main into next

### ISSUE THREAD

**Issue by gurgunday** [fastify/fastify#5421]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

- The difference between the branches is growing larger and larger, it already requires a careful rebase/merge — there are conflicts
- I don't have access and even if I did, I don't know if pushing directly is the right way to do it

Cc @climba03003 since you've done this a few times I believe 🤠

**Comment by climba03003** [comment]
> The difference between the branches is growing larger and larger

Not that large than I thought.

> it already requires a careful rebase/merge — there are conflicts

Conflict always there if you are working on two branch, you may also see the same when backporting.

> I don't have access and even if I did, I don't know if pushing directly is the right way to do it

For me, what it does is the same as sending PR. Reviewing the merge conflict or that large amount of commits is not feasible.
We may try to do in PR approach, but I assume it unlikely be reviewed. Or it may just be direct merge when unit test pass.

**Comment by gurgunday** [comment]
Okay I agree that direct merge is easier, can you do it today?

Because I want to merge https://github.com/fastify/fastify/pull/5419 but if we do it before rebaseing/merging from main, the conflicts will increase

Would you want to do it after or before https://github.com/fastify/fastify/pull/5419?

**Comment by gurgunday** [comment]
Thanks
