### ISSUE TITLE
Flaky test on N|Solid 20 MacOS

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#5426]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I often see N|Solid 20 MacOS test are failing in the first / second run but success later on.
The `node@20` is successful in all variant.

**Comment by climba03003** [comment]
Some Reference
https://github.com/fastify/fastify/actions/runs/8797599941
https://github.com/fastify/fastify/actions/runs/8767776142

**Comment by gurgunday** [comment]
In fact on MacOS `test/close-pipelining.test.js` is flaky in all versions

https://github.com/fastify/fastify/actions/runs/8797599941/job/24142842253
