### ISSUE TITLE
Use http-errors

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#543]
As titled: http://npm.im/http-errors

**Comment by allevo** [comment]
Internally or using `setErrorHandler` in a plugin?

**Comment by mcollina** [comment]
internally and advertise it as our supported solution.

**Comment by jsumners** [comment]
Are we putting this on the v1.0.0 list?

**Comment by mcollina** [comment]
I propose so.

**Comment by mcollina** [comment]
I don’t think we are there just yet.

**Comment by jsumners** [comment]
Fixed in #571
