### ISSUE TITLE
Where is the documentation for <Reply>.sendFile?

### ISSUE THREAD

**Issue by SpeedyCraftah** [fastify/fastify#5447]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I've had a look at the documentation both on GitHub and on fastify.dev but have found no reference to <Reply>.sendFile and any description of its parameters, even though it's implemented as an actual function.
The only reference I've found for it is in [this example](https://fastify.dev/docs/latest/Reference/Hooks/#respond-to-a-request-from-a-hook) which uses it to send a file with no options.

If it in fact does not exist, I'd be happy to propose a PR adding it to the documentation!

**Comment by gurgunday** [comment]
It's a fastify-static method: https://github.com/fastify/fastify-static

Is it implemented somewhere else?

**Comment by SpeedyCraftah** [comment]
> It's a fastify-static method: https://github.com/fastify/fastify-static
> 
> Is it implemented somewhere else?

Ah, so it is. The intellisense was seamless so I thought it was part of Fastify itself, but it's part of the static middleware.

Thank you!
