### ISSUE TITLE
Fastify v5 coordination

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5453]
Task lists:

* [x] Create `4.x` branch
* [x] Land `next` into `main`
* [x] Issue `v5.0.0-alpha.1` release with the `next` tag on npm.
* [x] remove all deprecations done in v4
* [x] Update all official modules for the v5 release https://github.com/fastify/fastify/issues/5116, and issue releases for them with the `next` tag on npm.
* [x] Write the upgrade guide.
* [x] Write blog posts and coordination with OpenJS marketing
* [x] Issue Fastify `v5.0.0` as latest on npm.
* [x] Retag all official plugins as latest

The target date is September 17th, but it can happen sooner or later.

**Comment by jsumners** [comment]
Going to try and tick off what I can when I'm able.

**Comment by mcollina** [comment]
I would try to get https://github.com/fastify/fastify/issues/5061 lined up too, but this is entirely optional.

**Comment by jsumners** [comment]
I/We need to do a pass or two on what we deprecated in v4 and remove what should be removed in v5.

**Comment by gurgunday** [comment]
And just FYI, a lot of the deprecated stuff is still in the codebase, they should be removed before the full release

**Comment by gurgunday** [comment]
These shorthand types are missing too, but I’ll look into them: https://github.com/fastify/fastify/pull/5444

**Comment by jsumners** [comment]
I have started merging `next` branches and then publishing pre releases for the modules. I'm doing this in chunks (so far, with a round of 1, 4 at a time). Note that the pre releases are tagged in the format:

+ `X.0.0-pre.fv5.N` where `X` is the next major version number and `N` is `1...N` for however many pre releases are issued.

The `fv5` is for "fastify v5".

## Steps taken

1. Open a PR to merge `next` into the mainline branch
2. On the current mainline create a new branch: `git branch v$(jq -r '.version | split(".") | .[0]' package.json).x`
3. Push up new branch: `git push vX.x` where `X` is the new major
4. Once PR is approved:
	1. Merge PR and delete `next` branch
	2. Pull changes and update version in `package.json` to match aforementioned format
	3. Push changes
	4. `npm publish --tag next`

**Comment by gurgunday** [comment]
> I have started merging `next` branches and then publishing pre releases for the modules. I'm doing this in chunks (so far, with a round of 1, 4 at a time). Note that the pre releases are tagged in the format:
> 
> * `X.0.0-pre.fv5.N` where `X` is the next major version number and `N` is `1...N` for however many pre releases are issued.
> 
> The `fv5` is for "fastify v5".
> 
> ## Steps taken
> 1. Open a PR to merge `next` into the mainline branch
> 2. On the current mainline create a new branch: `git branch v$(jq -r '.version | split(".") | .[0]' package.json).x`
> 3. Push up new branch: `git push vX.x` where `X` is the new major
> 4. Once PR is approved:
>    
>    1. Merge PR and delete `next` branch
>    2. Pull changes and update version in `package.json` to match aforementioned format
>    3. Push changes
>    4. `npm publish --tag next`

After this process is complete, we should release `fastify/workflows@5` so that dependabot kicks in and updates the workflows to the latest version

**Comment by climba03003** [comment]
All the deprecation warning is removed (or having PR waiting to merge).
The next thing I will do is the `TODO` comment that related to `node` version that we support.

**Comment by mcollina** [comment]
I'll start the final steps to ship Fastify v5 starting from next week.
