### ISSUE TITLE
querystring with property of type number fails

### ISSUE THREAD

**Issue by AmosSzust** [fastify/fastify#5467]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.27.0

### Node.js version

20

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I defined the following schema
```
export const GetDataSchema = {
  querystring: {
    type: "object",
    properties: {
      dataMode: {
        type: "number",
      },
    },
  },
};
```
I applied it to the route
`server.get("/:id/dataItems", { schema: GetDataSchema }, getDataItems);`

The request looks like this
http://localhost/api/test/15/dataItems?dataMode=3

And I get the following error from fastify
Error: Error: querystring/dataMode must be number

Last time I checked, 3 is a number so I have no idea why is it failing, was I missing something?

### Expected Behavior

3 is a number so I expect fastify to accept this value instead of throwing a 400 error.

**Comment by metcoder95** [comment]
You can solve this by either enabling [`coerceTypes`](https://ajv.js.org/guide/modifying-data.html#coercing-data-types) on `ajv` or parse the `req.query` property and parse the type before doing the validation using the `preValidation` hook.

Fastify uses `find-my-way` as a router, and `find-my-way` uses [`fast-querystring`](https://www.npmjs.com/package/fast-querystring) which mimics the behaviour of `node:querystring` in a more performant way, and by default a query string number will always be parsed as `string`.

**Comment by AmosSzust** [comment]
> and by default a query string number will always be parsed as string.

After struggling with it, I realized that. I thought I did something wrong with fastify. So there is no real meaning for validating query string params as they are always string.

**Comment by metcoder95** [comment]
You can validate its format but nothing else unless manually coerced

**Comment by mcollina** [comment]
We might think of enabling coerceTypes by default in v5.

**Comment by gurgunday** [comment]
Why are these tests passing?

```js
'use strict'

const { test } = require('tap')
const Fastify = require('..')

test('querystring', t => {
  t.plan(4)

  const fastify = Fastify()

  fastify.get('/:id', {
    schema: {
      querystring: {
        type: 'object',
        properties: {
          a: { type: 'number' }
        }
      }
    }
  }, function (req, reply) {
    t.equal(req.query.a, 42)
    reply.code(200).send()
  })

  fastify.inject({
    method: 'GET',
    url: '/12?a=42'
  }, (err, res) => {
    t.error(err)
    t.equal(res.statusCode, 200)
    t.equal(res.payload, '')
  })
})

test('params', t => {
  t.plan(4)

  const fastify = Fastify()

  fastify.get('/:a', {
    schema: {
      params: {
        type: 'object',
        properties: {
          a: { type: 'integer' }
        }
      }
    }
  }, function (req, reply) {
    t.equal(req.params.a, 42)
    reply.code(200).send()
  })

  fastify.inject({
    method: 'GET',
    url: '/42'
  }, (err, res) => {
    t.error(err)
    t.equal(res.statusCode, 200)
    t.equal(res.payload, '')
  })
})

```

**Comment by Eomm** [comment]
We coerce the type already:
https://github.com/fastify/ajv-compiler?tab=readme-ov-file#ajv-configuration

<img width="571" alt="image" src="https://github.com/fastify/fastify/assets/11404065/214408ba-e749-4299-8662-8f3f2c3df053">

https://runkit.com/embed/4gzt2onngmx9


Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by AmosSzust** [comment]
Silly me, I initialize fastify like this
```
  ajv: {
    customOptions: {
      coerceTypes: false,
    },
  },
```
and I don't event remember why I did that, I copied this from another project I did and forgot about it. Thanks.
