### ISSUE TITLE
Question about async handlers that call reply.send()

### ISSUE THREAD

**Issue by nwoltman** [fastify/fastify#548]
Why is the check implemented [this way](https://github.com/fastify/fastify/blob/67e111e8bc4e5f47d4aa93468a71bccdb8664037/lib/handleRequest.js#L124-L126)?

```js
if (payload !== undefined || state.reply.res.statusCode === 204) {
  state.reply.send()
}
```

I would have expected it to be:

```js
if (payload !== undefined || !state.reply.sent) {
  state.reply.send(payload)
}
````

I'm mainly concerned because I have a reply decorator that does this:

```js
reply.code(204).send();
```

and if I use that inside an `async` handler, `reply.send()` gets called twice.

Plus I feel like it would be a better developer experience to send an empty response if the developer doesn't call `reply.send()` inside a handler that resolves to `undefined` rather than letting the request hang.

**Comment by allevo** [comment]
Hi! 
  and thank you for trying fastify!

That behaviour was introduced to handle the `return undefined` in async function.

Truly in async function I used to use the return statement instead of calling `send` method.

```
async function () {
  return somePromise()
}
```

Which is the behaviour you aspect?

**Comment by nwoltman** [comment]
I expect that `state.reply.send(payload)` **won't** be called when this handler resolves:

```
async function handler(request, reply) {
  reply.code(204).send();
}
```

That code causes [this line](https://github.com/fastify/fastify/blob/67e111e8bc4e5f47d4aa93468a71bccdb8664037/lib/reply.js#L25) to be run which logs the warning: `Reply already sent`.

---

I also expect that `state.reply.send(payload)` **will** be called when this handler resolves:

```
async function handler(request, reply) {
  reply.code(200);
}
```

Right now with that code, the request will never end.

**Comment by mcollina** [comment]
As I do a lot of times, I’d recommend you to issue a pull request. It’s
better to discuss in front of working code.
Il giorno dom 17 dic 2017 alle 18:09 Nathan Woltman <
notifications@github.com> ha scritto:

**Comment by nwoltman** [comment]
Sure. I'll have one open soon :)
