### ISSUE TITLE
Whole API breaks when passing non-async function to fastify.register

### ISSUE THREAD

**Issue by serg06** [fastify/fastify#5489]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

v18.5.0 and v20.12.2

### Operating system

Windows and Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11 23H2 and Amazon Linux 2

### Description

When I call `fastify.register` with a non-async function, it breaks the whole API.

Example:

```ts
const fastify = Fastify();

fastify.register(instance => {
    instance.get("/", () => "hello");
});

// Breaks, times out and errors, because we passed a non-async function to `fastify.register`
const res = await fastify.inject({ method: "GET", url: "/" });
```

Runnable example: https://replit.com/@JonkPank/fastify-register-breaking

This confused me a lot before I figured it out. Now any time my API breaks, I know it's because I forgot to put `async` somewhere. This is frustrating because it feels like it's an easily preventable issue, e.g. by wrapping all plugins passed to `fastify.register` with `Promise.resolve(plugin)`.

### Link to code that reproduces the bug

https://replit.com/@JonkPank/fastify-register-breaking

### Expected Behavior

It works exactly the same way as when I call:

```ts
// Note the `async`
fastify.register(async instance => {
    instance.get("/", () => "hello");
});
```

**Comment by climba03003** [comment]
You forgotten to call the `done` callback inside the plugin.
My advice is when the plugin doesn't need to be `async`, always specify all the parameters.
So, you can see the `done` in last parameter.

```js
const fastify = Fastify();

fastify.register((instance, _, done) => {
    instance.get("/", () => "hello");
    done()
});

// Breaks, times out and errors, because we passed a non-async function to `fastify.register`
const res = await fastify.inject({ method: "GET", url: "/" });
```

**Comment by serg06** [comment]
@climba03003 Ah, thanks, I wasn't aware that plugins had to call `done`.

I feel this interface is a little counter-intuitive. Is there a reason that sync plugins can't "just work" without calling `done`?

**Comment by climba03003** [comment]
> Is there a reason that sync plugins can't "just work" without calling done?

The plugin is expected to be running in asynchronous. 
So, it requires a function to tell `fastify` when the plugin is ready and move on for the next one.

It is useful because sync or callback is faster than `async-await`.
Keep reducing unnecessary promise creation is the key point of performance.
