### ISSUE TITLE
Update reply.then and fastify.then types to use branded types to please typescript-eslint

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5498]
Here is an example: https://typescript-eslint.io/play/#ts=5.4.2&fileType=.tsx&code=C4TwDgpgBAyghgMwgBQE4HsC2BLAzhAHgBUA%2BKAXijSz0NKgDIoBvKAfTYCNU4A7AEwBcUAETwk1HPhFQAvgG4AUIv4QAxgBs4qaAgCuvNcGzpeUTHADWEXAFVeuRCgxSIACgCUwybQK5gqNi8AOYkSqqa2roGRiZmFta44s40%2BJ7CyT74fgFBoUqKCTb2jhIutJ4FRUlOWe4eSkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTowAbUiJoE6JAA0mcNhz94fAO4AxDtADSnQ0wDK-bogAKE6bNQYFO3RFatMUbhd5SGJ%2BMgBrfmFETSgmfkkYjEhjfmQhbkI7B2cpGUQAeWgbKUQbWDIAC1iQsMjo4NxuNIzCVkR8MkgwAF8NL29gAKDk7kokGvjE4OynF3zIHoGIAF0BnrWIJZ6gA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

**Comment by JoshuaKGoldberg** [comment]
Context:

1. [`@typscript-eslint/no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises) is the standard lint rule for catching "floating" Promises: those that are created and then not handled (e.g. `await`ed or stored in a variable)
    * Note: other linters such as Biome will eventually have it too. This is a general JavaScript/TypeScript concept, not something specific to the typescript-eslint team's opinions.
2. Some framework/library code intentionally creates Promises that are "safe" to let float, such as Fastify (https://github.com/fastify/fastify/issues/5466) `node:test` (https://github.com/nodejs/node/issues/51292), and RTK (https://github.com/reduxjs/redux-toolkit/issues/4101)
3. For a long time, typescript-eslint didn't provide any options to mark some Promise as "safe", which led to user pain of those safe-Promise-creating APIs
4. We in typescript-eslint are now in the process of adding in those options

As of [typescript-eslint v7.12.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v7.12.0), `@typescript-eslint/no-floating-promises` has an `allowForKnownSafePromises` option to mark a _specific type_ as safe. That's what this OP mentions.

Further pending typescript-eslint work that'll land Soon ™️:

1. https://github.com/typescript-eslint/typescript-eslint/pull/9234: an option to mark a _specific function_ as safe to call
2. https://github.com/typescript-eslint/typescript-eslint/issues/8088
3. https://github.com/typescript-eslint/typescript-eslint/issues/8433: not checking `PromiseLike`s by default (https://github.com/fastify/fastify/issues/4399)

Sorry for the giant wall of links+text 🙂 - we've seen a lot of FUD around these rules and I want to make sure it's clear what's going on and why.

**Comment by mcollina** [comment]
@JoshuaKGoldberg you didn't mention that we should be using the branded version, with the example in the OP.

**Comment by JoshuaKGoldberg** [comment]
Oop sorry - still learning how to explain+phrase these things! Yes, to be clear: right now, with the new [`allowForKnownSafePromises` option](https://typescript-eslint.io/rules/no-floating-promises/#allowforknownsafepromises), you can mark a specific type as "safe" to be floating. One pattern that we're recommending folks try out is a "branded" type (WIP article explaining what that is more deeply: https://github.com/LearningTypeScript/site/pull/135). 

The OP's code snippet is a good example:

```ts
type SafePromise<T> = Promise<T> & { __brand: "SafePromise" };
```

A framework can make this type the return type of its APIs that are "safe" to call & then float. Users can then allowlist that type. https://github.com/reduxjs/redux-toolkit/issues/4101 is an example of a framework doing just that.

**Comment by climba03003** [comment]
I am a bit confuse here, should the escape be `__linterBrands` or `__brand`?

From what I found in the document of `TypeScript ESLint` and source code, 
`__linterBrands` is used in rule `no-floating-promises`.
`__brand` is used in rule `no-unnecessary-condition`

**Comment by JoshuaKGoldberg** [comment]
From the perspective of typescript-eslint and other linters, it doesn't matter what brand name is used. https://github.com/reduxjs/redux-toolkit/pull/4102 -> https://github.com/reduxjs/redux-toolkit/pull/4102/#discussion_r1460303311 ended up going with `__linterBrands` to make it a little more clear that the brand was targeted for linting scenarios, not RTK-specific logic.
