### ISSUE TITLE
Custom format for ajv gets overwritten by ajv-formats

### ISSUE THREAD

**Issue by floratmin** [fastify/fastify#5512]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.27.0

### Node.js version

22.0.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.4

### Description

When adding custom formats for ajv, then formats defined in ajv-formats get overwritten. To fix this `ajv.addFormat` has to be called for each custom format after `ajvFormats(ajv)`.

### Link to code that reproduces the bug

https://github.com/floratmin/fastify-ajv-custom-format

### Expected Behavior

When posting `"foo"` to `http://localhost:3000` it should validate.

**Comment by floratmin** [comment]
I am not sure, if this could introduce breaking changes for some users. The problem lies in `@fastify/ajv-compiler` in the file `validator-compiler.js`. Should I reopen this issue there? Maybe this fix could be introduced for fastify version 5?

**Comment by mcollina** [comment]
Yes, I think we could fix it in Fastify v5. A PR would be mostly welcomed.

**Comment by floratmin** [comment]
Created pull request [fix: do not overwrite customOptions.formats](https://github.com/fastify/ajv-compiler/pull/122)
