### ISSUE TITLE
custom error handler not breaking encapsulation using fastify-plugin

### ISSUE THREAD

**Issue by ritikrao1** [fastify/fastify#5515]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

4.5.1

### Node.js version

14.18.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

14.3

### Description

i have set 2 error handlers, i want that error handler that is sending response 'internal error' should be invoked when handler throws error, but in this external custom error handler is getting invoked and reply sent is 'external error'
```
const fastify = require("fastify");
const app = fastify({logger: true, caseSensitive: false});
const fp = require('fastify-plugin')
app.register(function (app,options, done){
    app.route({
        method: "post",
        url : '/testingApi', 
        handler: async (req, res) => {
            throw new Error("in api handler");
            req.result = { msg: "sent successfully"};
            res.status(200).send(req.result);
        }
    });
    app.register(fp(addErrorHandler), {});
    done();
})

const addErrorHandler = (app, options, done) => {
    app.setErrorHandler(async (err, req, res) => {
        res.status(500).send('internal error');
        return res;
    })
    done();
}

app.setErrorHandler(async (err, req, res) => {
    res.status(500).send('external error');
    return res;
})

app.addHook('onReady', (done) => {
    console.log("Service running on port: 3000");
    done();
});
app.listen({host: 'localhost', port: 3000});
```

### Expected Behavior

should get reply 'internal error' on hitting api /testingApi

**Comment by mcollina** [comment]
https://github.com/fastify/fastify-plugin/issues/240#issuecomment-2160310791
