### ISSUE TITLE
Only automatically run workflows when a member approved them or if the PR is created by a member

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#5520]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

As poposed on twitter this morning:

Imho we should only run workflows, when a member approved the workflow.

Currently any PR of a contributor is run automatically. So if somebody provided a typo fix in the markdown file and it got merged, then the workflows in following PRs are run automatically. 

This should be done globally in the org.

**Comment by Fdawgs** [comment]
Easy enough to enable. @mcollina are you happy for this to be done? I can do it and only takes 2 seconds.

**Comment by mcollina** [comment]
I don't think this is needed because they do not have access to secrets.
