### ISSUE TITLE
Missing cookie field in headers of upgrade websocket request

### ISSUE THREAD

**Issue by philSixZero** [fastify/fastify#5526]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

20.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

To authenticate an upgrade request, I want to access the cookie field in the headers of the incoming request. Somehow, this field is not available at all, although cookies are set and available in HTTP requests.

```typescript
server.on('upgrade', function upgrade(request, socket, head) {
  socket.on('error', onSocketError);

  // ERROR: request.headers.cookie missing
  authenticate(request, function next(err, client) {
    if (err || !client) {
      socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
      socket.destroy();
      return;
    }

    socket.removeListener('error', onSocketError);

    wss.handleUpgrade(request, socket, head, function done(ws) {
      wss.emit('connection', ws, request, client);
    });
  });
});
```

#### Used Packages

- ws@v8.17.0
- nestjs@v10.3.9
- fastify@v4.26.2

### Expected Behavior

I would expect the request.headers.cookie field to be available, so that authentication on `upgrade` requests can be implemented.

**Comment by climba03003** [comment]
I don't think it is related to `fastify`.
You are using `server.on('upgrade')` which is the built-in `Node.js` Server.

I am closing the issue unless you provide more context, including the payload sent and without `nestjs`.

**Comment by philSixZero** [comment]
@climba03003  Thanks for your reply! You're right, doing the upgrade request using curl works for me as well. So it seems like the browser just doesn't include the cookies in the request...
