### ISSUE TITLE
Published packages contain unnecessary files

### ISSUE THREAD

**Issue by eavidy** [fastify/fastify#5536]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I saw that the fastify package in the npm repository contains test files, coverage related files, and they're pretty big. Maybe they shouldn't be included in the package

<img width="974" alt="image" src="https://github.com/fastify/fastify/assets/73151139/695654a8-2717-4219-9f41-d23391fa7d93">

**Comment by Eomm** [comment]
Thanks for pointing out!
We should remove the `.tap/` folder.

Regarding the tests, please see the discussion in https://github.com/fastify/skeleton/issues/42#issuecomment-1208090783 for my reasoning against such a change.

**Comment by Uzlopak** [comment]
Basically add .tap to .npmingore

**Comment by Eomm** [comment]
Done

<img width="347" alt="image" src="https://github.com/fastify/fastify/assets/11404065/f581366b-8c98-4fe2-8af6-c6f6318baccf">
