### ISSUE TITLE
Review on supporting schema shortened

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#5550]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Schema shortened is a useful feature when the user can provide schema properties only.
But times go by, we support more and more variation in the route schema and I think that it is the time to say goodbye to the shortened schema.

I also believe most people are using tools to generate schema which is always full schema. 
So, the impact should be minimal.

The main benefits would be
1. Simplify the code-base
2. No more quirk on the schema, currently `onRoute` is receiving the user defined schema but after `ready` it will be normalized.
3. Plugins creator can be more strict forward to handle the schema.

We should discussion in supporting the shortened schema in 2 aspect.
1. Headers and Querystring
Both of them is always key-value pairs, having shortened schema is good to have feature and do not have any confusion.
2. Body and Response
Both of them may vary based on `Content-Type`. And after #5545, both support schema based on `Content-Type`.
I hope we would move towards OpenAPI standard and support only full schema (default to "application/json") and `Content-Type` with schema.

**Comment by Eomm** [comment]
> it is the time to say goodbye to the shortened schema.

I agree to drop it already in v5 - note that this could be a plugin with an `onRoute` hook 😄

**Comment by gurgunday** [comment]
> But times go by, we support more and more variation in the route schema and I think that it is the time to say goodbye to the shortened schema.

> I hope we would move towards OpenAPI standard and support only full schema (default to "application/json") and Content-Type with schema.

+1

@climba03003 so you are fine with https://github.com/fastify/fastify/pull/5545? Just having contentType variations in `response` and `body`? Asking because I will approve that PR if that's the case

**Comment by climba03003** [comment]
> Just having contentType variations in response and body (not in headers, querystring/query)?

Yes, I don't see how `headers` or `querystring` will be differ based on `content-type`.
Let talk about the common example,
1. Authorization header
I don't see a reason to accept or not accept the header based on `content-type`.
2. Pagination header
pagination should be the same no matter how the result is (XML / JSON).

One additional point is that `body` is always the request content-type and `response` is always the response content-type.
It is hard to decide if `header` or `querystring` is based on request or response content-type.

**Comment by mcollina** [comment]
Let's do this.

**Comment by jsumners** [comment]
To be clear: we don't have any way of measuring the usage of the feature. I know that when I'm concocting a simple experiment, I utilize it instead of spending the effort to write a full schema. So removing it will result in a higher bar to clear for defining schemas.

**Comment by climba03003** [comment]
> So removing it will result in a higher bar to clear for defining schemas.

It is always possible to support through simple plugin. So, migration or impact to remove from core should be minimal.
