### ISSUE TITLE
Empty `reply.request` in loggers.serializers.res

### ISSUE THREAD

**Issue by mch-dsk** [fastify/fastify#5556]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.6.0

### Node.js version

20.11.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

Hello, I want to log the duration of a request using a custom serializers. While doing so, I encoutered the following error : 

```typescript
const fastify = Fastify({
    logger: {
        serializers: {
            res(reply) {
                console.log(reply.request); // undefined
            },
        },
    },
});
```

When an user aborts a request, `reply.request` is empty.

[This line](https://github.com/fastify/fastify/blob/5c64dc48e0d2ddef0f310e03040d8ad9870a0335/lib/reply.js#L727) should be `logStreamError(reply.log, err, reply)`.

### Expected Behavior

`reply.request` should be correctly populated

**Comment by metcoder95** [comment]
What are you exactly trying to measure?

Overall, if interested in the elapsed time since received the request until its served, you can use [`request.elapsedTime`](https://fastify.dev/docs/latest/Reference/Reply/#elapsedtime) on the `onResponse` hook (which is triggered when the response has been sent).

**Comment by mch-dsk** [comment]
Thanks for the very fast answer, my use case is only an example and shouldn't really be taken into account :)

The underlying issue stays the same, we expect a `Reply` (see [doc](https://fastify.dev/docs/latest/Reference/Logging/#usage)) but we get a `res` instead
