### ISSUE TITLE
Disable exposeHeadRoutes by default for fastify v5

### ISSUE THREAD

**Issue by SeanReece** [fastify/fastify#5573]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I know this was enabled by default in v4 with this change: https://github.com/fastify/fastify/pull/2826

Not exactly sure what the reasoning was to enable by default, but I'd like to propose we disable this by default for fastify v5, in the interests of being *fast* by default 😄 

I actually wasn't aware this was enabled by default until I was doing some debugging and ran a `printRoutes()` and saw all these extra HEAD routes (2 HEAD routes *per* GET are added). I have since disabled on all our applications since we do not support HEAD. (I especially didn't notice since fastify-swagger ignores these routes by default)

For a somewhat large application, there are non-negligible performance gains by disabling head routes. We use extensive schemas for all our endpoints, I believe the extra memory and time are because of the extra schema compilation and we are currently not making heavy use of $ref.

### Improved startup time and memory usage

| BEFORE | AFTER | Improvement  |
| ------ | ------ | ------ |
| Startup Time: **1472ms**       | Startup Time: **1068ms**       | **38%** |
| Peak Memory: **155MB**       | Peak Memory: **130MB**       | **19%** |
| Settled Memory: **105MB** | Settled Memory: **93MB** | **13%** |
| Peak CPU: **72%** | Peak CPU: **66%** |  |
| ![image](https://github.com/user-attachments/assets/6b1ac48c-6d3e-410f-bf1f-1191960113a1)  |  ![image](https://github.com/user-attachments/assets/d2c327b8-4c82-41a4-88b5-3a687a0b911e) |

In my application, total routes goes from **91** to **63**

#### RTFM

I know I should have read the docs enough to notice this earlier, but I think there are most likely lots of fastify users running with this option enabled and have not noticed. IMO use cases for HEAD are specific enough that users wanting HEAD routes could enable this feature.

Let me know what you think. If we decide to keep it as-is for the sake of out-of-the-box experience, I think we need dedicated documentation around performance suggestions + tweaks.

Thanks!

**Comment by gurgunday** [comment]
> 2 HEAD routes _per_ GET are added

Isn't it 1 HEAD route per GET? What's the other one?

**Comment by Uzlopak** [comment]
If I remember correctly there was a bug at the beginning, resulting in doubles.

@climba03003 do you have some more info?

**Comment by purplepenguin42** [comment]
It creates two `HEAD` routes with an optional trailing slash, so if you have `GET /apples`, it'll autogenerate `HEAD /apples` and `HEAD /apples/` routes respectively.

**Comment by climba03003** [comment]
> do you have some thoughts on this?

Here demonstrate how `GET` related to the auto creation of `HEAD`

```js
import Fastify from 'fastify'

const fastify = Fastify()

// 1 to 1 mapping
fastify.get('/foo', () => {})

fastify.register((fastify, _, done) => {
  // 1 to 2 mapping
  fastify.get('/', () => {})

  done()
}, { prefix: '/bar'})


fastify.register((fastify, _, done) => {
  // 1 to 1 mapping
  fastify.get('', () => {})

  done()
}, { prefix: '/cow'})

await fastify.ready()

console.log(fastify.printRoutes())
```

**Comment by mcollina** [comment]
[rfc 9110 states](https://datatracker.ietf.org/doc/html/rfc9110#section-9.3.2) that

> The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request method had been GET.

Following the spec comes _before_ startup speed and memory at rest.

@SeanReece in your analysis, you are inverting causality. You clearly state that there is an added cost for your schemas:

> For a somewhat large application, there are non-negligible performance gains by disabling head routes. We use extensive schemas for all our endpoints, I believe the extra memory and time are because of the extra schema compilation and we are currently not making heavy use of $ref.

This is a known issue, and something that can be massively optimized by using precompiled schemas: https://backend.cafe/how-to-unlock-the-fastest-fastify-server-startup.

> Let me know what you think. If we decide to keep it as-is for the sake of out-of-the-box experience, I think we need dedicated documentation around performance suggestions + tweaks.

We 100% need to improve docs on this area! Can you send a PR?

**Comment by climba03003** [comment]
I am thinking can we do some optimization on the route creation.
For example, 
1. Ban adding custom `HEAD` after `GET` in `v5`. (Remove the logic of remove route.)
2. Instead of running `prepareRoute` again, we add `HEAD` to the method list.

**Comment by Uzlopak** [comment]
Either we have a convention or we dont. Making something conditional in a convention can be irritating.

Imho better we finally implement a performance guideline, if not existing already. E.g. use precompiled ajv schemas, disable head schema generation if not needed etc..

**Comment by metcoder95** [comment]
Agree on all the points related to docs. This seems mostly something that can be clarified with improvements over the performance documentation as the problem stated does not seem to by in sync with the feature set as possible root cause.

Nevertheless, there are quite few things that can be optimized for the `HEAD` route handling (e.g. reused normalized schema from `GET` sibling). We might be able to set a fast path for this. But stills, guideline for performance optimization will sort help more on this.

**Comment by SeanReece** [comment]
@mcollina is totally right. Since RFC 9110 is pretty clear that HEAD MUST be supported, so I agree we shouldn’t disable by default.

> All general-purpose servers MUST support the methods GET and HEAD

That being said I do think there are some improvements to be made. @climba03003 had some great suggestions. Also, I’m not sure if the current implementation is respecting `ignoreTrailingSlash` option (I’ll have to test this). I could try my hand at a PR for this but it’s not a priority for me currently as we have disabled head routes.

What I **will** do in the meantime is create an issue/discussion to brainstorm some performance recommendations + best practices, and I can work on a PR to add some documentation. I’ve got some ideas but I know there’s probably lots I’m not aware of.

we currently have these recommendations but it’s more production focused https://fastify.dev/docs/latest/Guides/Recommendations/

### Some ideas:
- Use schemas!
- FJS specific schema tweaks (currently working on some benchmarks for this)
- Use $ref to avoid schema duplication
- Precompile schemas for faster startup 
- disable exposeHeadRoutes if not needed
- …
