### ISSUE TITLE
creating codemods for fastify upgrade v4

### ISSUE THREAD

**Issue by arshcodemod** [fastify/fastify#5574]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Building codemods for fastify upgrade v4.

At [Codemod](https://www.codemod.com), we are contributing open-source codemods for popular frameworks like [React](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#codemods), Remix, Nuxt, and others to help with their latest updates and changes. Right now, I'm working on the fastify v4 upgrade. I've gone through the upgrade guide and raised a [GitHub issue](https://github.com/codemod-com/codemod/issues/972) for the missing codemods. 

Looking forward to add these and help fastify users have a smooth migration experience.

### Motivation

The motivation to create codemods is that it would streamline the process for millions of users, and also ensure that the application stays efficient and secure while leveraging the latest advancements in Fastify.

### Example

These codemods would help migrate to fastify v4 real quick as running :

npx codemod fastify/4/migration-recipe which would include all the codemods.

**Comment by mcollina** [comment]
Of course!

We will soon start shipping Fastify v5. I think you might want to develop that too.

**Comment by arshcodemod** [comment]
Definitely, while i am in close contact with contributors, devs from our team are also helping in v4 upgrade :)
