### ISSUE TITLE
Default hostname when providing a nullish `host` in listening options

### ISSUE THREAD

**Issue by metcoder95** [fastify/fastify#5583]
### Discussed in https://github.com/fastify/fastify/discussions/5582

<div type='discussions-op-text'>

<sup>Originally posted by **driimus** July 23, 2024</sup>
## Context
Fastify currently listens on `localhost` by default, but there are still scenarios where that default isn't propagated to `listenOptions`.

One example of this is when listening options are provided and the `host` property is falsy:
```js
 require('fastify')().listen({host: undefined, port: 3000})
```
Which works, but produces a deprecation warning due to `dns.lookup()` not liking falsy `hostname` values (since node v12 - [code](https://github.com/nodejs/node/blob/cf2bce63862d995d238802ff4a7a24966361360a/lib/dns.js#L200:L201)):
```
> (node:156681) [DEP0118] DeprecationWarning: The provided hostname "undefined" is not a valid hostname, and is supported in the dns module solely for compatibility.
    at emitInvalidHostnameWarning (node:internal/dns/utils:270:13)
    at Object.lookup (node:dns:195:5)
    at Object.multipleBindings (/home/driimus/personal/fastify-test/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/server.js:140:7)
    at /home/driimus/personal/fastify-test/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/server.js:116:30
    at new Promise (<anonymous>)
    at /home/driimus/personal/fastify-test/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/server.js:114:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Proposed change
I think it would be nice to get rid of the warning by re-assigning `listenOptions.host` even if the property already exists, in https://github.com/fastify/fastify/blob/9226a4793311c003e30dfddec4fd580deffcd28c/lib/server.js#L58-L60
As long as the provided value is nullish, which would more closely match the fallback for `host`:
https://github.com/fastify/fastify/blob/9226a4793311c003e30dfddec4fd580deffcd28c/lib/server.js#L54

## Use case
Looking back at the original example, a more likely use case is to override `host` using an env var or similar variable which is potentially undefined:
```js
 require('fastify')().listen({host: process.env.FASTIFY_HOST, port: 3000})
```</div>

**Comment by S-Abhishek** [comment]
Hey team,

I am curious about the end user perspective, if I provide option of `host` with value that resolves to `undefined` (could be unintentional). It may a deviation in what I might expect due to implicitly using default instead of throwing an error saying `host` if provided must be truthy value. If `host` key itself is not provided, then default seems fine. 

What do you think about this?

**Comment by metcoder95** [comment]
Overall, I believe that we should align to the underlying behaviour of `node:http` as much as we can. This to avoid misalignments that cause confusion as well people can rely on documentation in a clear way.

With this proposal, we are just aligning with Node's expectations.

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fastify/pull/5590
