### ISSUE TITLE
Plugins specifying a Fastify version restriction that needs updated for v5

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#5585]
The following projects need their `fastify-plugin` restriction updated for `fastify@5`:

- [x] csrf-protection
- [x] fastify-accepts
- [x] fastify-accepts-serializer
- [x] fastify-auth
- [x] fastify-basic-auth
- [x] fastify-bearer-auth
- [x] fastify-caching
- [x] fastify-circuit-breaker
- [x] fastify-cookie
- [x] fastify-cors
- [x] fastify-diagnostics-channel
- [x] fastify-elasticsearch
- [x] fastify-env
- [x] fastify-etag
- [x] fastify-express
- [x] fastify-formbody
- [x] fastify-helmet
- [x] fastify-http-proxy
- [x] fastify-jwt
- [x] fastify-kafka
- [x] fastify-leveldb
- [x] fastify-mongodb
- [x] fastify-multipart
- [ ] fastify-nextjs
- [x] fastify-oauth2
- [ ] fastify-opensearch
- [x] fastify-postgres
- [x] fastify-rate-limit
- [x] fastify-redis
- [x] fastify-reply-from
- [x] fastify-request-context
- [x] fastify-response-validation
- [x] fastify-routes
- [x] fastify-routes-stats
- [x] fastify-schedule
- [x] fastify-secure-session
- [x] fastify-sensible
- [x] fastify-swagger-ui
- [x] fastify-throttle
- [x] fastify-url-data
- [x] fastify-websocket
- [x] middie
- [x] point-of-view
- [x] session

For reference, the list is compiled by querying the "main" file of each project (as listed in its `package.json`) for a line that matches the regular expression `^(?:\s+)?fastify:\s+['"].*(\d+)`.

**Comment by Fdawgs** [comment]
I'll do this one, lads. Got a mass update script that'll make this easy.

**Comment by Fdawgs** [comment]
Made the PRs. Will take a look at the failing ones over the weekend.

**Comment by jsumners** [comment]
Please remember to publish new releases.

**Comment by Fdawgs** [comment]
> Please remember to publish new releases.

I'll be honest, I have never cut a release for the fastify repos even though I have permissions, is there anything special we have to do due to it being an org or is it just the usual `npm run version [hotfix/minor/major` -> commit and push -> `npm publish`?

**Comment by jsumners** [comment]
Basically, yes. We are not doing tags for these pre-releases. So that covers the process. You will likely need to edit the pkg manifests directly since these are pre-releases. Bump the `.1` to `.2`.

**Comment by Fdawgs** [comment]
@climba03003 @gurgunday thanks for doing some of these, I did intend to do these over the weekend but... life.
Could you check you've ticked the ones you've done already please?

**Comment by climba03003** [comment]
I am closing the issue because it is all resolved.
`fastify-opensearch` and `fastify-nextjs` is not prepared for `5.x`, so I am ignoring it.
