### ISSUE TITLE
Broken test suite

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#5588]
Every time I run `npm test` on the current main branch, I get:

```sh
/Users/jsumners/Projects/oss/fastify/fastify/test/types/import.js
  1:1   error  Strings must use singlequote  @stylistic/quotes
  1:13  error  Extra semicolon               @stylistic/semi
  2:32  error  Strings must use singlequote  @stylistic/quotes
  2:62  error  Extra semicolon               @stylistic/semi

✖ 4 problems (4 errors, 0 warnings)
  4 errors and 0 warnings potentially fixable with the `--fix` option.
```

But I can't find that file. So, two things:

1. Someone who knows where that file comes from, please provide a way to fix this error.
2. Can we please disable the singlequote rule? It will prevent writing strings with template literals (e.g. when the string needs a singlequote inside of it, it's easier to use a template literal to reduce the need for escaping characters).

**Comment by climba03003** [comment]
I think you should change `tsc test/types/import.ts && tsd` to `tsc test/types/import.ts --noEmit && tsd`
https://github.com/fastify/fastify/blob/9af8a5ce3f66496dfbeda130d1ad287607883312/package.json#L25

The file exist because you run `npm run test` multiple times and it created at the first time.
