### ISSUE TITLE
Confused by deprecation

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#5596]
https://github.com/fastify/fastify/blob/ba276fd56b6c15e5602ec5d6f24e02f400d8bb93/lib/route.js#L425-L430

I am confused by that deprecation. It was introduced in https://github.com/fastify/fastify/pull/4052. 

What is the expected behavior if the deprecation is removed? It seems like there are two governing options, which one should be removed?

**Comment by climba03003** [comment]
The expected behavior is that you should always add `HEAD` route before `GET` route.
