### ISSUE TITLE
server.listen callback function issue

### ISSUE THREAD

**Issue by xcfio** [fastify/fastify#5597]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

22.3.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10-22H2

### Description

I copied code from https://fastify.dev/docs/latest/Reference/TypeScript/#getting-started and when I'm running this code I got error that say "localhost"

**Comment by sourcecodeit** [comment]
Can you show more details (your `index.ts` and the commands you run) and the full error?

**Comment by xcfio** [comment]
> Can you show more details (your `index.ts` and the commands you run) and the full error?

src/index.ts
```ts
import fastify from "fastify"

const server = fastify()

server.get("/ping", async (request, reply) => {
    return "pong\n"
})

server.listen({ port: 8080 }, (err, address) => {
    if (err) {
        console.error(err)
        process.exit(1)
    }
    console.log(`Server listening at ${address}`)
})
```
command output
```sh
> bun run --watch src/index.ts
< localhost
```
That's it. Nothing more in the terminal.

**Comment by dancastillo** [comment]
Hey @xcfio, I tried to reproduce the issue with the example you provided, but I wasn't able to get the same error. I've put together a sample repository that is working for me. You can check it out [here](https://github.com/dancastillo/bun-fastify-example)

**Comment by PcmKomanda** [comment]
I just had the same issue. I downgraded the version to 4.28.0 and now it works.

**Comment by jsumners** [comment]
Thank you for the report. This project targets the [Node.js](https://nodejs.org) runtime. If you are encountering issues using Bun, please file issues there as [requested by them](https://twitter.com/jarredsumner/status/1700497869160268155).
