### ISSUE TITLE
request.log.setBindings is not stubbed (and has no type)

### ISSUE THREAD

**Issue by mattyod** [fastify/fastify#5605]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x.

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

When running Fastify without a logger (e.g. for running tests) the majority of methods on `request.log` are stubbed using abstract-logging or a custom method for `.child()`. https://github.com/fastify/fastify/blob/main/lib/logger.js#L76-L81

We are utilising `request.log.setBindings()` which is not stubbed for this scenario. We've worked round this by adding a custom global type:
```
declare module "fastify" {
  interface FastifyBaseLogger {
    setBindings(bindings: import("pino").Bindings): void;
  }
}
```
and using optional chaining:
```
log.setBindings?.({ itemToLogLater });
```

But it would be nice not to have to do this. Would we be open to PR to address these two niggles?

**Comment by jsumners** [comment]
```js
// if no logger is provided, then create a default logger
  if (!options.loggerInstance && !options.logger) {
    const logger = nullLogger
    logger.child = () => logger
    logger.setBindings = () => {}
    return { logger, hasLogger: false }
  }
```

**Comment by climba03003** [comment]
I don't think we should expect `.setBinding` to be exist.
The null logger is currently the minimal interface we expect for a logger, which match my expectation.

**Comment by mattyod** [comment]
Closing as discussed in the PR thread.
