### ISSUE TITLE
Typescript plugin compatibility with Fastify 3.x

### ISSUE THREAD

**Issue by simkessy** [fastify/fastify#5622]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.5

### Plugin version

latest

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18

### Description

I upgrade from Fastify 2x to 3.29.5 and updated the plugins to the latest version but typescript is returning a lot of type errors and I'm assuming it's because the latest plugin types are for Fastify 4x but I can't figure out how to determine which versions support 3.29.5? 

For example I have these: 

```
    "@fastify/http-proxy": "7",
    "@fastify/request-context": "^5.1.0",
    "@fastify/secure-session": "^7.5.1",
    "@fastify/sensible": "4.1.0",
```

And I can't tell if they're all supposed to be compatible with 3x also?

**Comment by Uzlopak** [comment]
try with fastify-http-proxy, fastify-request-context, fastify-secury-session, fastify-sensible

**Comment by jsumners** [comment]
Please see https://fastify.dev/docs/latest/Reference/LTS/. Fastify v3 has not been supported since 2020.
