### ISSUE TITLE
Fastify typescript compatibility

### ISSUE THREAD

**Issue by Bobetti** [fastify/fastify#5639]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Node.js version

latest

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

windows 10

### Description

Cannot start local dev server for my project using latest fastify version, vercel cli, and typescript. 
By running command: npm run vercel - my local server starting. When I visit browser link - i see {"hello":"world!!"} as expected, but on the server side I see huge list of errors: 

minimal project is here: https://www.dropbox.com/scl/fi/6evw6jzx4ae9fplhpsobf/fastify.zip?rlkey=4sf9njqbquyvxq1hgder9ou7q&dl=0

Seems to me some trouble with tsconfig.json - but I can't figure it out what exactly wrong for several days already.

Any help is highly appreciated, because my development just stopped. 

![image](https://github.com/user-attachments/assets/6a65ef52-e35a-454a-88b0-fb0f88b5c36e)

### Expected Behavior

no errors

**Comment by Fdawgs** [comment]
@Bobetti No-one is going to download and extract a random `.zip` file. Please upload the code to a publicly accessible repo.

**Comment by Bobetti** [comment]
@Fdawgs  dropbox gives you the access to the inside of zip without downloading it - similar to  publicly accessible repo, no difference

**Comment by climba03003** [comment]
The problems is related to the version of TypeScript used by vercel.

**Comment by Bobetti** [comment]
@climba03003 I installed  "typescript": "4.9.5" for my project, but don't see any changes in the behavior. Still lots of errors.

**Comment by climba03003** [comment]
I means the version is too old to be supported. As I remembered, the current types require at least 5.2.
Note that your project `typescript` doesn't means `vercel` is using that version, it is explicitly pinned to `4.9` which is not supporting our current types.
