### ISSUE TITLE
Make the import types (ESM/CommonJS) in examples to be with tabs

### ISSUE THREAD

**Issue by dvmhmdsd-amana** [fastify/fastify#5643]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

When I read the docs, I found that the importing in examples written in ESM then in CommonJS. I suggest to make it with tabs, which means, no need to add the both examples after each other, just add tabs **ESM** & **CommonJS** and user can switch between them and store his selection on all the docs pages. 

To clarify more, when you read for example [this strapi docs page](https://docs.strapi.io/dev-docs/typescript), you'll find importing options as tabs, `npm` or `yarn`.

I am ready to work on this issue if accepted, but want to know where is the source of docs internals not only the content.

Thanks

**Comment by Fdawgs** [comment]
@dvmhmdsd-amana Thanks for the PR, please provide an example page. On the homepage of https://fastify.dev/ we have tabs for basic ESM/CommonsJS examples.

**Comment by dvmhmdsd** [comment]
Aha, that's what I was meaning, ok I will close the issue. Thanks
