### ISSUE TITLE
Missing fields in anyOf subschemas are not ignored as with standard subschemas

### ISSUE THREAD

**Issue by maRci002** [fastify/fastify#5647]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

20.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

22h2

### Description

When I add additional properties to a subschema in `anyOf`, I receive the following error:

```
{"statusCode":500,"error":"Internal Server Error","message":"The value of '#/properties/snippet' does not match schema definition."}
```

**Code to reproduce:**

```typescript
import Fastify from 'fastify';

const snippetSchema = {
    type: 'object',
    properties: {
        username: { type: 'string' }
    },
    required: ['username'],
    additionalProperties: false
};

const profileSchemaNullable = {
    type: 'object',
    properties: {
        snippet: {
            anyOf: [
                snippetSchema,
                { type: 'null' }
            ]
        }
    },
    required: ['snippet'],
    additionalProperties: false,
    $schema: 'http://json-schema.org/draft-07/schema#'
};

const profileSchemaOptional = {
    type: 'object',
    properties: {
        snippet: snippetSchema
    },
    additionalProperties: false,
    $schema: 'http://json-schema.org/draft-07/schema#'
};

const profile = {
    snippet: {
        username: '',
        additionalProperty: '',
    },
};

const server = Fastify({ logger: true });

server.get(
    '/nullable',
    { schema: { response: { 200: profileSchemaNullable } }, },
    async (request, reply) => reply.send(profile), // throws error
);

server.get(
    '/optional',
    { schema: { response: { 200: profileSchemaOptional } }, },
    async (request, reply) => reply.send(profile), // ok
);

async function main(): Promise<void> {
    try {
        await server.listen({ port: 3000 });
    } catch (e) {
        server.log.error({ err: e }, 'Server couldn\'t start');
        process.exit(1);
    }
}

void main();

```

**Note:** When I call `/optional` endpoint additional properties are allowed on `snippetSchema`.

### Expected Behavior

Subschemas within `anyOf` should be serialized just like normal subschemas.

> https://github.com/fastify/fast-json-stringify?tab=readme-ov-file#additional-properties
> 
> If *additionalProperties* is not present or is set to `false`, every property that is not explicitly listed in the *properties* and *patternProperties* objects,will be ignored, as described in <a href="#missingFields">Missing fields</a>.
> Missing fields are ignored to avoid having to rewrite objects before serializing.

**Comment by jsumners** [comment]
How is this a Fastify issue? This sounds like a feature of your schema validator?

**Comment by maRci002** [comment]
I am using the default schema validator provided by Fastify (AJV).

As you can see in both cases, `additionalProperties` are not allowed based on my schema definition; however, only `nullable` will throw an error:

```json
"snippet": {
  "type": "object",
  "properties": {
    "username": {
      "type": "string"
    }
  },
  "required": [
    "username"
  ],
  "additionalProperties": false
}
```

To the best of my knowledge, Fastify removes additional fields that do not belong to the schema.

**Comment by maRci002** [comment]
I can add `passthrough`, and it will work, but it might leak sensitive information. However, this isn't required when using `optional`. In the case of `optional`, `fast-json-stringify` automatically removes the additional sensitive information.

```
const profileModelZod = z.object({
    snippet: z.object({
        username: z.string(),
    }).passthrough().nullable(),
});
```

**Comment by Eomm** [comment]
> I am using the default schema validator provided by Fastify (AJV).

There is no validation here because we are talking about `response` schema configuration, but as you already pointed out it is a `fast-json-stringify` business. 

Moreover, if you read the docs it is explained by it triggers an error:
https://github.com/fastify/fast-json-stringify?tab=readme-ov-file#anyof-and-oneof

> Nullable should support additional properties just like the optional one does.

I don't agree, nullable means that something can be `null` and it is not "free format" json - but whatever, I'm missing the target here and I don't know `zod` well TBH.

If I read the first JSON Schema (with nullable), valid inputs are:

1. `{ username: 'foo' }`
2. `null`

Now I don't know how to write json schema with `zod`, but it seems it you may need to configure the `additionalProperties` accordingly: https://github.com/fastify/fast-json-stringify?tab=readme-ov-file#additionalProperties

**Comment by maRci002** [comment]
> Now I don't know how to write json schema with `zod`

I have updated the description to remove the `Zod` dependency.

> I don't agree, nullable means that something can be `null` and it is not "free format" json - but whatever, I'm missing the target here and I don't know `zod` well TBH.
> 
> If I read the first JSON Schema (with nullable), valid inputs are:
> 
> 1. `{ username: 'foo' }`
> 2. `null`

When I remove `{ type: 'null' }` from `anyOf`, meaning only `snippetSchema` should be accepted, it throws an error upon adding additional properties.

According to the documentation, missing fields should be ignored (not included in the response); however, Fastify throws an error

> https://github.com/fastify/fast-json-stringify?tab=readme-ov-file#additional-properties
> 
> If *additionalProperties* is not present or is set to `false`, every property that is not explicitly listed in the *properties* and *patternProperties* objects,will be ignored, as described in <a href="#missingFields">Missing fields</a>.
> Missing fields are ignored to avoid having to rewrite objects before serializing.

**Comment by maRci002** [comment]
When `"type": ["string", "null"]` is used instead of `anyOf`, it works well for nullable cases. I've submitted an issue to the `zod-to-json-schema` repository to support this feature. StefanTerdell/zod-to-json-schema#142

Closing in favor of  fastify/fast-json-stringify#736
