### ISSUE TITLE
Fastify inject call on endpoint with schema wipes `body.required` field

### ISSUE THREAD

**Issue by JagoEFP** [fastify/fastify#5658]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

16.20.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.3

### Description

I have a user login endpoint with a validation schema akin to:
```js
const authSchema = {
    body: {
        type: 'object',
        additionalProperties: false,
        required: ["email", "password"],
        properties: {
            email: { type: "string" },
            password: { type: "string" }
        }
    }
}
```
with the route looking like this:
```js
fastify.post('/user/login', { schema: authSchema }, async (request, reply) => {
    console.log(authSchema); // this is added for testing purposes that will make sense as this post continues
    ...
}
```
This works perfectly when running normally in my app; the schema correctly validates the `request.body` and handles errors accordingly (returns `400` code if request body doesn't match etc.). Also, the `console.log` prints the `authSchema` as shown above.

Now, I am trying to implement unit tests for this using JEST and `fastify.inject` to test my endpoints and the issue arises here. When I call `fastify.inject({method: 'POST', url: '/user/login', payload: {email: ''}})` for example, I expect to get a status code of 400 (as `password` field isn't in `body`) and the endpoint not to run, however, it does and the `console.log` prints this instead:
```
{
  body: {
    type: 'object',
    additionalProperties: false,
    required: [],
    properties: { email: [Object], password: [Object] }
  },
  [Symbol(fastify.schemas.visited)]: true
}
```
(Note: the `required` field is now empty?)
And thus the endpoint runs as the validation schema isn't enforced because of this. Not sure what's going on here, why would the `required` field get wiped in this way? Is it because of `fastify.inject`? Any help is appreciated, many thanks :)

### Expected Behavior

Expected to receive a status code of 400 and the endpoint not to run for a `fastify.inject` call to '/user/login' with a Bad request according to the `authSchema` `request.body` validation.

**Comment by climba03003** [comment]
I cannot reproduce your problem, please provide a minimal reproducible code that we can run directly.

```mjs
import Fastify from "fastify";

const fastify = Fastify()

const schema = {
  body: {
    type: 'object',
    properties: {
      foo: { type: 'string' },
      bar: { type: 'string' },
    },
    required: ['foo', 'bar']
  }
}

fastify.post('/', {
  schema
}, async (request) => request.body)


{
  const response = await fastify.inject({
    method: 'POST',
    path: '/',
    body: { foo: '1', bar: '2' }
  })
  console.log(response.statusCode, response.body)
}
{
  const response = await fastify.inject({
    method: 'POST',
    path: '/',
    body: { foo: '1' }
  })
  console.log(response.statusCode, response.body)
}
```

**Comment by JagoEFP** [comment]
Thank you for the reply! Apologies, I've continued to look into it and I think it's a JEST issue with mocking and resetting mocks, so nothing wrong with fastify. Appreciate the offer of help though, many thanks

**Comment by nandanraj56** [comment]
@JagoEFP I am also facing similar issue, how did you got around with it?
