### ISSUE TITLE
Release majors for all the modules

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5659]
This is a tracking issue of releasing a new major of all the modules. 

## For each module

1. ensure that it uses Fastify v5
2. ensure that the plugins it uses are all using Fastify v5
3. verify that it only support Node 20+
4. release on npm:
  a. If it's a plugin, release will go under the `next` tag.
  b. If it's a standalone library it will just be `latest`

## Modules

+ [x] [accept-negotiator](https://github.com/fastify/accept-negotiator)
+ [x] [ajv-compiler](https://github.com/fastify/ajv-compiler)
+ [x] [avvio](https://github.com/fastify/avvio)
+ [ ] [aws-lambda-fastify](https://github.com/fastify/aws-lambda-fastify)
+ [x] [busboy](https://github.com/fastify/busboy)
+ [x] [create-fastify](https://github.com/fastify/create-fastify)
+ [x] [csrf](https://github.com/fastify/csrf)
+ [x] [csrf-protection](https://github.com/fastify/csrf-protection)
+ [x] [deepmerge](https://github.com/fastify/deepmerge)
+ [x] [env-schema](https://github.com/fastify/env-schema)
+ [x] [fast-content-type-parse](https://github.com/fastify/fast-content-type-parse) 
+ [x] [fast-json-stringify](https://github.com/fastify/fast-json-stringify)
+ [x] [fast-json-stringify-compiler](https://github.com/fastify/fast-json-stringify-compiler)
+ [x] [fast-uri](https://github.com/fastify/fast-uri)
+ [ ] [fastify](https://github.com/fastify/fastify)
+ [x] [fastify-accepts](https://github.com/fastify/fastify-accepts)
+ [x] [fastify-accepts-serializer](https://github.com/fastify/fastify-accepts-serializer)
+ [x] [fastify-auth](https://github.com/fastify/fastify-auth)
+ [x] [fastify-autoload](https://github.com/fastify/fastify-autoload)
+ [x] [fastify-awilix](https://github.com/fastify/fastify-awilix)
+ [x] [fastify-basic-auth](https://github.com/fastify/fastify-basic-auth)
+ [x] [fastify-bearer-auth](https://github.com/fastify/fastify-bearer-auth)
+ [x] [fastify-caching](https://github.com/fastify/fastify-caching)
+ [x] [fastify-circuit-breaker](https://github.com/fastify/fastify-circuit-breaker)
+ [x] [fastify-cli](https://github.com/fastify/fastify-cli)
+ [x] [fastify-compress](https://github.com/fastify/fastify-compress)
+ [x] [fastify-cookie](https://github.com/fastify/fastify-cookie)
+ [x] [fastify-cors](https://github.com/fastify/fastify-cors)
+ [x] [fastify-elasticsearch](https://github.com/fastify/fastify-elasticsearch)
+ [x] [fastify-env](https://github.com/fastify/fastify-env)
+ [x] [fastify-error](https://github.com/fastify/fastify-error)
+ [x] [fastify-etag](https://github.com/fastify/fastify-etag)
+ [x] [fastify-express](https://github.com/fastify/fastify-express)
+ [x] [fastify-flash](https://github.com/fastify/fastify-flash)
+ [x] [fastify-formbody](https://github.com/fastify/fastify-formbody)
+ [x] [fastify-funky](https://github.com/fastify/fastify-funky)
+ [x] [fastify-helmet](https://github.com/fastify/fastify-helmet)
+ [x] [fastify-hotwire](https://github.com/fastify/fastify-hotwire)
+ [x] [fastify-http-proxy](https://github.com/fastify/fastify-http-proxy)
+ [x] [fastify-jwt](https://github.com/fastify/fastify-jwt)
+ [x] [fastify-kafka](https://github.com/fastify/fastify-kafka)
+ [x] [fastify-leveldb](https://github.com/fastify/fastify-leveldb)
+ [x] [fastify-mongodb](https://github.com/fastify/fastify-mongodb)
+ [x] [fastify-multipart](https://github.com/fastify/fastify-multipart)
+ [x] [fastify-mysql](https://github.com/fastify/fastify-mysql)
+ [x] [fastify-oauth2](https://github.com/fastify/fastify-oauth2)
+ [x] [fastify-passport](https://github.com/fastify/fastify-passport)
+ [x] [fastify-plugin](https://github.com/fastify/fastify-plugin)
+ [x] [fastify-postgres](https://github.com/fastify/fastify-postgres)
+ [x] [fastify-rate-limit](https://github.com/fastify/fastify-rate-limit)
+ [x] [fastify-redis](https://github.com/fastify/fastify-redis)
+ [x] [fastify-reply-from](https://github.com/fastify/fastify-reply-from)
+ [x] [fastify-request-context](https://github.com/fastify/fastify-request-context)
+ [x] [fastify-response-validation](https://github.com/fastify/fastify-response-validation)
+ [x] [fastify-routes](https://github.com/fastify/fastify-routes)
+ [x] [fastify-routes-stats](https://github.com/fastify/fastify-routes-stats)
+ [x] [fastify-schedule](https://github.com/fastify/fastify-schedule)
+ [x] [fastify-secure-session](https://github.com/fastify/fastify-secure-session)
+ [x] [fastify-sensible](https://github.com/fastify/fastify-sensible)
+ [x] [fastify-static](https://github.com/fastify/fastify-static)
+ [x] [fastify-swagger](https://github.com/fastify/fastify-swagger)
+ [x] [fastify-swagger-ui](https://github.com/fastify/fastify-swagger-ui)
+ [x] [fastify-throttle](https://github.com/fastify/fastify-throttle)
+ [x] [fastify-type-provider-json-schema-to-ts](https://github.com/fastify/fastify-type-provider-json-schema-to-ts)
+ [x] [fastify-type-provider-typebox](https://github.com/fastify/fastify-type-provider-typebox)
+ [x] [fastify-url-data](https://github.com/fastify/fastify-url-data)
+ [ ] [fastify-vite](https://github.com/fastify/fastify-vite)
+ [x] [fastify-websocket](https://github.com/fastify/fastify-websocket)
+ [x] [fastify-zipkin](https://github.com/fastify/fastify-zipkin)
+ [x] [fluent-json-schema](https://github.com/fastify/fluent-json-schema)
+ [x] [forwarded](https://github.com/fastify/forwarded)
+ [x] [json-schema-ref-resolver](https://github.com/fastify/json-schema-ref-resolver)
+ [x] [light-my-request](https://github.com/fastify/light-my-request)
+ [x] [middie](https://github.com/fastify/middie)
+ [x] [one-line-logger](https://github.com/fastify/one-line-logger)
+ [x] [point-of-view](https://github.com/fastify/point-of-view)
+ [x] [process-warning](https://github.com/fastify/process-warning)
+ [x] [proxy-addr](https://github.com/fastify/proxy-addr)
+ [x] [restartable](https://github.com/fastify/restartable)
+ [x] [safe-regex2](https://github.com/fastify/safe-regex2)
+ [x] [secure-json-parse](https://github.com/fastify/secure-json-parse)
+ [x] [send](https://github.com/fastify/send)
+ [x] [session](https://github.com/fastify/session)
+ [x] [under-pressure](https://github.com/fastify/under-pressure)

**Comment by mcollina** [comment]
Most of the modules are ready @fastify/collaborators. I'm going to prepare the blog posts, migration guide and changelog next week. As soon as the migration guide is done, I'll cut a `-rc.1` release.

I plan to cut v5 on September 17th.

**Comment by simoneb** [comment]
Shout if there's any help needed on any of that

**Comment by mcollina** [comment]
Closing. They are all done minus `@fastify/vite`, which @galvez would do in the weekend, and `@fastify/aws-lambda`, which @adrai will release after fastify v5 is cut.

**Comment by galvez** [comment]
@mcollina New @fastify/vite `next` release: https://github.com/fastify/fastify-vite/releases/tag/v7.0.0-alpha.1

**Comment by adrai** [comment]
`@fastify/aws-lambda` v5 is released
