### ISSUE TITLE
types are wrong for preParsing handlers

### ISSUE THREAD

**Issue by lifeiscontent** [fastify/fastify#5680]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.6.1

### Description

preParsing types are wrong, the `request.body` says its the fully qualified type, but it will always be undefined.

### Expected Behavior

I'd expect types to be correct

**Comment by Uzlopak** [comment]
I guess you can simply do an Omit<..., 'body'> here

https://github.com/fastify/fastify/blob/d623d4710f8d2423b63ed4743d47533daa03976a/types/hooks.d.ts#L98
