### ISSUE TITLE
plugin: Support using Boom for errors

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#569]
Previously, Fastify included built-in support for [Boom errors](https://github.com/hapijs/boom). Issue #542 and PR #558 removed that support in an effort to simplify error handling within the core library. Thus, it would be nice to have a plugin within the ecosystem that provides this functionality.

This should be a very easy plugin to create. It merely has to replicate the following code:

https://github.com/fastify/fastify/blob/4a6396e8a3f1ba0292f5a52e220122e382e0440f/lib/reply.js#L49-L62

**Comment by nwoltman** [comment]
I think this would replicate the old boom error handling:

```js
fastify.setErrorHandler((error, reply) => {
  if (error && error.isBoom) {
    reply
      .code(error.output.statusCode)
      .type('application/json')
      .headers(error.output.headers)
      .send(error.output.payload)
    return
  }
  // ... Handle non-boom errors
})
```
