### ISSUE TITLE
Question: Tests migration

### ISSUE THREAD

**Issue by danteoss** [fastify/fastify#5690]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi! I'm trying to work on bundler-test.js file, for framework migration, but i have some questions:

This is the original test, using tap:
```
test('Bundled package should not work with bad plugin version', (t) => {
  t.plan(1)
  fastifyFailPlugin.ready((err) => {
    t.match(err.message, /expected '9.x' fastify version/i)
  })
})
```

For instance, i'm trying to rewrite this test, but i'm having some troubles when i simply try to use equivalent methods from node:tests

When i do:
```
test('Bundled package should not work with bad plugin version', (t) => {
  t.plan(1)
    fastifyFailPlugin.ready((err) => {
      t.assert.match(err.message, /expected '9.x' fastify version/i)
    })
  })
```

I'm getting an error message like: 
`Error: Test "Bundled package should not work with bad plugin version" at bundler-test.js:25:1 generated asynchronous activity after the test ended.`

But when i do:
```
test('Bundled package should not work with bad plugin version', async(t) => {
  t.plan(1)
  await new Promise((resolve) => {
    fastifyFailPlugin.ready((err) => {
      t.assert.match(err.message, /expected '9.x' fastify version/i)
      resolve()
      })
    })
  })
```

The test passes. It's ok if I use async methods to rewrite the tests and make the framework migration succesfully?

**Comment by gurgunday** [comment]
You can indeed use async with await for tests that are asynchronous or promise based

Just don’t forget to remove t.plan once you make a test async
