### ISSUE TITLE
Release new patch for each plugin

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5694]
This is a tracking issue of releasing a new minor of all the plugins. For each module we should swap in `package.json` `"fastify": "5.0.0-alpha.X"` to `"fastify": "^5.0.0"`. 

## Modules

+ [x] [accept-negotiator](https://github.com/fastify/accept-negotiator)
+ [x] [ajv-compiler](https://github.com/fastify/ajv-compiler)
+ [x] [avvio](https://github.com/fastify/avvio)
+ [x] [aws-lambda-fastify](https://github.com/fastify/aws-lambda-fastify)
+ [x] [busboy](https://github.com/fastify/busboy)
+ [x] [create-fastify](https://github.com/fastify/create-fastify)
+ [x] [csrf-protection](https://github.com/fastify/csrf-protection)
+ [x] [fast-json-stringify-compiler](https://github.com/fastify/fast-json-stringify-compiler)
+ [x] [fast-uri](https://github.com/fastify/fast-uri)
+ [x] [fastify](https://github.com/fastify/fastify)
+ [x] [fastify-accepts](https://github.com/fastify/fastify-accepts)
+ [x] [fastify-accepts-serializer](https://github.com/fastify/fastify-accepts-serializer)
+ [x] [fastify-auth](https://github.com/fastify/fastify-auth)
+ [x] [fastify-autoload](https://github.com/fastify/fastify-autoload)
+ [x] [fastify-awilix](https://github.com/fastify/fastify-awilix)
+ [x] [fastify-basic-auth](https://github.com/fastify/fastify-basic-auth)
+ [x] [fastify-bearer-auth](https://github.com/fastify/fastify-bearer-auth)
+ [x] [fastify-caching](https://github.com/fastify/fastify-caching)
+ [x] [fastify-circuit-breaker](https://github.com/fastify/fastify-circuit-breaker)
+ [x] [fastify-cli](https://github.com/fastify/fastify-cli)
+ [x] [fastify-compress](https://github.com/fastify/fastify-compress)
+ [x] [fastify-cookie](https://github.com/fastify/fastify-cookie)
+ [x] [fastify-cors](https://github.com/fastify/fastify-cors)
+ [x] [fastify-elasticsearch](https://github.com/fastify/fastify-elasticsearch)
+ [x] [fastify-env](https://github.com/fastify/fastify-env)
+ [x] [fastify-error](https://github.com/fastify/fastify-error)
+ [x] [fastify-etag](https://github.com/fastify/fastify-etag)
+ [x] [fastify-express](https://github.com/fastify/fastify-express)
+ [x] [fastify-flash](https://github.com/fastify/fastify-flash)
+ [x] [fastify-formbody](https://github.com/fastify/fastify-formbody)
+ [x] [fastify-funky](https://github.com/fastify/fastify-funky)
+ [x] [fastify-helmet](https://github.com/fastify/fastify-helmet)
+ [x] [fastify-hotwire](https://github.com/fastify/fastify-hotwire)
+ [x] [fastify-http-proxy](https://github.com/fastify/fastify-http-proxy)
+ [x] [fastify-jwt](https://github.com/fastify/fastify-jwt)
+ [x] [fastify-kafka](https://github.com/fastify/fastify-kafka)
+ [x] [fastify-leveldb](https://github.com/fastify/fastify-leveldb)
+ [x] [fastify-mongodb](https://github.com/fastify/fastify-mongodb)
+ [x] [fastify-multipart](https://github.com/fastify/fastify-multipart)
+ [x] [fastify-mysql](https://github.com/fastify/fastify-mysql)
+ [x] [fastify-oauth2](https://github.com/fastify/fastify-oauth2)
+ [x] [fastify-passport](https://github.com/fastify/fastify-passport)
+ [x] [fastify-plugin](https://github.com/fastify/fastify-plugin)
+ [x] [fastify-postgres](https://github.com/fastify/fastify-postgres)
+ [x] [fastify-rate-limit](https://github.com/fastify/fastify-rate-limit)
+ [x] [fastify-redis](https://github.com/fastify/fastify-redis)
+ [x] [fastify-reply-from](https://github.com/fastify/fastify-reply-from)
+ [x] [fastify-request-context](https://github.com/fastify/fastify-request-context)
+ [x] [fastify-response-validation](https://github.com/fastify/fastify-response-validation)
+ [x] [fastify-routes](https://github.com/fastify/fastify-routes)
+ [x] [fastify-routes-stats](https://github.com/fastify/fastify-routes-stats)
+ [x] [fastify-schedule](https://github.com/fastify/fastify-schedule)
+ [x] [fastify-secure-session](https://github.com/fastify/fastify-secure-session)
+ [x] [fastify-sensible](https://github.com/fastify/fastify-sensible)
+ [x] [fastify-static](https://github.com/fastify/fastify-static)
+ [x] [fastify-swagger](https://github.com/fastify/fastify-swagger)
+ [x] [fastify-swagger-ui](https://github.com/fastify/fastify-swagger-ui)
+ [x] [fastify-throttle](https://github.com/fastify/fastify-throttle)
+ [x] [fastify-type-provider-json-schema-to-ts](https://github.com/fastify/fastify-type-provider-json-schema-to-ts)
+ [x] [fastify-type-provider-typebox](https://github.com/fastify/fastify-type-provider-typebox)
+ [x] [fastify-url-data](https://github.com/fastify/fastify-url-data)
+ [x] [fastify-vite](https://github.com/fastify/fastify-vite)
+ [x] [fastify-websocket](https://github.com/fastify/fastify-websocket)
+ [x] [fastify-zipkin](https://github.com/fastify/fastify-zipkin)
+ [x] [light-my-request](https://github.com/fastify/light-my-request)
+ [x] [middie](https://github.com/fastify/middie)
+ [x] [one-line-logger](https://github.com/fastify/one-line-logger)
+ [x] [point-of-view](https://github.com/fastify/point-of-view)
+ [x] [restartable](https://github.com/fastify/restartable)
+ [x] [session](https://github.com/fastify/session)
+ [x] [under-pressure](https://github.com/fastify/under-pressure)

**Comment by mcollina** [comment]
@Fdawgs I recall you have some sort of script to massively do these. I can take care of publishing if you do the changes. I have a script for publishing, and a physical OTP token, so that I can script around OTP.

**Comment by Fdawgs** [comment]
> @Fdawgs I recall you have some sort of script to massively do these. I can take care of publishing if you do the changes. I have a script for publishing, and a physical OTP token, so that I can script around OTP.

Sure! Should be able to do it this evening.

**Comment by jsumners** [comment]
Please just merge them all. Having to:

1. Click the notification
2. Click the files tab
3. Click the dropdown
4. Click approve
5. Click "done"

Is just way too much for so many at once. These sorts of org wide changes should be done in batches in order to reduce the impact on team members (notifications overload, overload of manual interactions, etc.).

**Comment by Fdawgs** [comment]
@mcollina Have updated the checklist and done releases, the only ones that I haven't done are:
- [fastify-throttle](https://github.com/fastify/fastify-throttle) (I get a 404 when running `npm publish`)
- [fastify-type-provider-json-schema-to-ts](https://github.com/fastify/fastify-type-provider-json-schema-to-ts) (also get a 404 when running `npm publish`)
- [one-line-logger](https://github.com/fastify/one-line-logger) (TypeScript errors that I'm struggling to fix, my knowledge of TS is very basic)

**Comment by Fdawgs** [comment]
> @mcollina @fastify/plugins Have updated the checklist and done releases, the only ones that I haven't done are:
> 
>     * [fastify-throttle](https://github.com/fastify/fastify-throttle) (I get a 404 when running `npm publish`)
> 
>     * [fastify-type-provider-json-schema-to-ts](https://github.com/fastify/fastify-type-provider-json-schema-to-ts) (also get a 404 when running `npm publish`)
> 
>     * [one-line-logger](https://github.com/fastify/one-line-logger) (TypeScript errors that I'm struggling to fix, my knowledge of TS is very basic)

@fastify/core Don't appear to have permissions to publish for the two mentioned above, can someone do a release for them or grant me access please?

**Comment by jsumners** [comment]
@Fdawgs `throttle` has been added to the plugins team in npm. The other two are considered independent libraries, and, as such, are under the "libraries" team in npm. Would you like to be added to the libraries team?

**Comment by Fdawgs** [comment]
> @Fdawgs `throttle` has been added to the plugins team in npm. The other two are considered independent libraries, and, as such, are under the "libraries" team in npm. Would you like to be added to the libraries team?

Yes please!

**Comment by jsumners** [comment]
Done.

**Comment by Fdawgs** [comment]
All done!
