### ISSUE TITLE
Add HeroDevs mentions.

### ISSUE THREAD

**Issue by AndreAngelantoni** [fastify/fastify#5698]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

[IN PROCESS]
Sister issue to https://github.com/fastify/website/issues/250.

Add mentions to HeroDevs extended support on:
- Add table with version support on the LTS page
- add a new top banner on the V3 and V4 migration pages

**Comment by climba03003** [comment]
How is it different than https://github.com/fastify/fastify/issues/5623?

**Comment by mcollina** [comment]
It seems we have 3 issues to track for HeroDevs integration.

@joeeames can we solidify into one?

**Comment by AndreAngelantoni** [comment]
Closing in favor of https://github.com/fastify/fastify/issues/5623.
