### ISSUE TITLE
Should the "engines" requirement be explicit?

### ISSUE THREAD

**Issue by mureinik** [fastify/fastify#5700]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

N/A

### Node.js version

18.0.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

MacOs Sonoma 14.7

### Description

#5560 states that:
> Fastifyv5 engine targets means we no longer need the dc-polyfill package. 
>
>diagnostics_channel became stable @ v18.13.0.
tracingChannel class api was added in v18.19.0 and is still experimental, however, dc-polyfill uses the internal version if node >=18.19 so it does nothing for us in fastify v5.

However, `package.json` doesn't have an `engines` entry, and indeed, fastify 5 can be installed on older Node.js versions. E.g.:
```none
➜  fastifydemo nvm use 18.0.0
Now using node v18.0.0 (npm v8.6.0)
➜  fastifydemo npm install fastify

added 56 packages, and audited 57 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Using a basic "hello world" application from the docs (https://fastify.dev/docs/latest/Guides/Getting-Started/, [attached](https://github.com/user-attachments/files/17058528/polifill-repro.zip)
), it's easy to see that fastify 5 indeed won't work with Node.js 18.0.0 and does require a newer version

```none
➜  fastifydemo node index.js
/Users/allon/src/fastifydemo/node_modules/fastify/lib/wrapThenable.js:9
const channels = diagnostics.tracingChannel('fastify.request.handler')
                             ^

TypeError: diagnostics.tracingChannel is not a function
    at Object.<anonymous> (/Users/allon/src/fastifydemo/node_modules/fastify/lib/wrapThenable.js:9:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/allon/src/fastifydemo/node_modules/fastify/lib/handleRequest.js:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

Node.js v18.0.0
```

### Expected Behavior

There are two options here, IMHO.

If the intention is indeed to require these higher versions, explicilty state it in an `engines` entry in `package.json`, so installing fastify 5 with an older version will issue a warning:
```
"engines": {
    "node": "^18.19.0 || >=19.9.0"
}
```
(see https://nodejs.org/api/diagnostics_channel.html#diagnostics_channeltracingchannelnameorchannels for version detail)

If this behavior is not intended and the intention is to support versions like 18.0.0, #5560 should be revertted.

**Comment by Uzlopak** [comment]
We do not support node 18.

**Comment by mureinik** [comment]
@Uzlopak so shouldn't that be explicitly stated in `package.json` with an "engines" clause? Probably not the one I noted, but something like `"node": ">=20"` ?

**Comment by Uzlopak** [comment]
We are discussing this for 2 weeks already here

https://github.com/fastify/fastify/pull/5667

And we it doesnt look like we will adapt it.

**Comment by mureinik** [comment]
Shame on me.
I was looking for existing issues, but didn't think about looking at existing PRs. Thanks for the pointer.
