### ISSUE TITLE
Removal of Custom Logger Instance Option in Fastify Logger

### ISSUE THREAD

**Issue by Towerss** [fastify/fastify#5703]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.28.1

### Stopped working in version

5.0.0

### Node.js version

20.15.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

22H2

### 💥 Regression Report

Hi Fastify team,

First of all, thanks for your continued hard work on Fastify—it's been a fantastic framework for our projects.

I've noticed that after a recent update, it seems that using a custom logger instance with Pino is no longer supported due to the changes in the logger type definition. I know this is a major release that might have breaking changes, but I think this still should be allowed to use custom-logged instances.

Previously, it was possible to pass a custom Pino logger instance like this:

logger?: boolean | FastifyLoggerOptions<RawServer> & PinoLoggerOptions | Logger,

For example, we had something similar to this setup:

```
const stream = pino.transport({
    targets: [
        {
            target: 'pino-pretty',
            level: `${isProduction ? 'warn' : 'trace'}`,
            options: {
                colorize: true,
                levelFirst: true,
                translateTime: 'yyyy-mm-dd, h:MM:ss TT',
            },
        },
        {
            target: 'pino/file',
            level: `${isProduction ? 'warn' : 'trace'}`,
            options: {
                levelFirst: true,
                translateTime: 'yyyy-mm-dd, h:MM:ss TT',
                destination: path.resolve(
                    __dirname,
                    isProduction || isStaging
                        ? `../../logs/api/${getFormattedDate()}-logger.log`
                        : `../logs/api/${getFormattedDate()}-logger.log`,
                ),
            },
        },
    ],
});

export const logger = pino(stream);

const fastify = Fastify({
    logger: logger
});
```

Which allowed us to use the logger in parts of the code where the Fastify instance is not available, like when running cron jobs. However, with the updated types:

`logger?: boolean | FastifyLoggerOptions<RawServer> & PinoLoggerOptions,`

It seems no longer possible to pass a custom logger instance. The new type definition doesn’t support our custom Pino configuration, which was an essential part of our logging strategy.

Is this an intentional change, or could support for custom logger instances be reconsidered?

Thanks again for all the work you do—looking forward to your feedback.

### Steps to Reproduce

1. Set up a new project with Fastify and Pino (including pino-pretty for transport).
2. Use the latest version of Fastify where the logger type changes were introduced: `npm install fastify pino pino-pretty`
3. Create a custom Pino logger instance:

```
const stream = pino.transport({
    targets: [
        {
            target: 'pino-pretty',
            level: 'trace',
            options: {
                colorize: true,
                levelFirst: true,
                translateTime: 'yyyy-mm-dd, h:MM:ss TT',
            },
        },
        {
            target: 'pino/file',
            level: 'trace',
            options: {
                levelFirst: true,
                translateTime: 'yyyy-mm-dd, h:MM:ss TT',
                destination: './logs/custom-log.log',
            },
        },
    ],
});

export const logger = pino(stream);
```

4. Pass the custom logger instance to Fastify:

```
const fastify = Fastify({
    logger: logger
});
```

6. Try to start the Fastify server. You will encounter a TypeScript error related to the logger type because custom Pino loggers are no longer allowed.

### Expected Behavior

The Fastify server should accept the custom logger instance and start normally, as it did in previous versions.

**Comment by Tony133** [comment]
Look in the migration documents for v5 of Fastify, see here : https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/#new-logger-constructor-signature

Try this:

```
const loggerInstance = require('pino')();
const fastify = require('fastify')({
  loggerInstance
});
```
or 

```
const pinoLogger = require('pino')();
const fastify = require('fastify')({
  loggerInstance: pinoLogger 
});
```

**Comment by Chaz0r** [comment]
We still have an issue here.
If we import fastify via require, it works exactly like the migration document tells us. 

The getting started page of the docs tells us that we can also do an ESM import like this:

```
import Fastify from 'fastify'

const fastify = Fastify({
  logger: true
})
```

If we do it like this the our typescript transpiler is complaining:

We tried it exactly like this:
```
import Fastify from 'fastify'

 const fastify = Fastify({
      loggerInstance: loggerInstance //loggerInstance is a pino logger instance that works if you do the import via require
    }) 
```
then we get the following error:
```
The last overload gave the following error.
    Object literal may only specify known properties, and 'loggerInstance' does not exist in type 'FastifyHttpOptions<Server<typeof IncomingMessage, typeof ServerResponse>, FastifyBaseLogger>'.ts(2769)
fastify.d.ts(232, 18): The last overload is declared here.
```

What we can (but shouldn't do) is the following:
```
const fastify = Fastify({
      // @ts-ignore
      loggerInstance: loggerInstance
    })
```

Then the transpiler of course does not complain and it looks like everything is working. So are we holding it wrong or is there some king of typing issue?

Beside that (after we addes the ts-ignore) we save the fastify constant above in a class property of type FastifyInstance which worked before version 5.

Now we get the following error:
```
Type 'FastifyInstance<Http2SecureServer<typeof IncomingMessage, typeof ServerResponse, typeof Http2ServerRequest, typeof Http2ServerResponse>, Http2ServerRequest, Http2ServerResponse<...>, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.
  Types of property 'server' are incompatible.
    Type 'Http2SecureServer<typeof IncomingMessage, typeof ServerResponse, typeof Http2ServerRequest, typeof Http2ServerResponse>' is missing the following properties from type 'Server<typeof IncomingMessage, typeof ServerResponse>': maxHeadersCount, maxRequestsPerSocket, timeout, headersTimeout, and 4 more.
```

Again a typing issue. So same question above: Are we holding it wrong or is there a typing issue?

**Comment by Towerss** [comment]
Hi @Chaz0r,

Please give this a try:

import Fastify, { FastifyBaseLogger } from 'fastify';

export const loggerInstance = pino();

const fastify = Fastify({
	loggerInstance: loggerInstance as FastifyBaseLogger,
});
