### ISSUE TITLE
HTTP2 connection hangs when FST_ERR_CTP_INVALID_CONTENT_LENGTH happens

### ISSUE THREAD

**Issue by gugu** [fastify/fastify#5715]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

20.15.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

debian-slim

### Description

We have Golang HTTP client frontend and Fastify backend communicating using HTTP2 (SSL mode). Once in a while we have unexpected error FST_ERR_CTP_INVALID_CONTENT_LENGTH happen, after that the stream becomes a black hole - none of requests is handled. Restarting stream helps

What I noticed - right now this error type sends Connection: close. I guess it can be an issue with HTTP2, because they have a different way of closing connection.

Does fastify really need it? Is it required in HTTP2 mode?

### Link to code that reproduces the bug

I can not imagine how did it happen because http2 module does not allow requests with invalid content-length. Looks like there are some miscalculation and I added logging to our system

### Expected Behavior

Connection needs either survive such requests or correctly close in HTTP2 mode

**Comment by climba03003** [comment]
It is a bit interesting for me, how the payload and content-type look like?

From the document it stated that `Node.js` will reject the message earlier than we receive it.
https://nodejs.org/api/http2.html#responsewriteheadstatuscode-statusmessage-headers
> On outbound messages, Node.js does not check if Content-Length and the length of the body being transmitted are equal or not. However, when receiving messages, Node.js will automatically reject messages when the Content-Length does not match the actual payload size.

**Comment by gugu** [comment]
Yes, it is interesting for me as well. I could not reproduce this locally, it happens around once per week or so in our project with thousands RPS. I've added logging today, next time I'll get the content

**Comment by gugu** [comment]
```
{
  ':authority': 'REDACTED:8080',
  ':method': 'POST',
  ':path': '/redacted',
  ':scheme': 'https',
  'content-type': 'application/json',
  'content-length': '163',
  'accept-encoding': 'gzip',
  'user-agent': 'Go-http-client/2.0',
  [Symbol(sensitiveHeaders)]: []
}
Http2ServerRequest {
  _events: {
    close: undefined,
    error: undefined,
    data: undefined,
    end: undefined,
    readable: undefined,
    pause: [Function: onRequestPause],
    resume: [Function: onRequestResume]
  },
  _readableState: ReadableState {
    highWaterMark: 16384,
    buffer: [],
    bufferIndex: 0,
    length: 0,
    pipes: [],
    awaitDrainWriters: null,
    [Symbol(kState)]: 66062088,
    [Symbol(kDecoderValue)]: StringDecoder {
      encoding: 'utf8',
      [Symbol(kNativeDecoder)]: <Buffer 00 00 00 00 00 00 01>
    },
    [Symbol(kEncodingValue)]: 'utf8'
  },
  _maxListeners: undefined,
  _eventsCount: 2,
  [Symbol(shapeMode)]: true,
  [Symbol(kCapture)]: false,
  [Symbol(state)]: { closed: true, didRead: true },
  [Symbol(headers)]: [Object: null prototype] {
    ':authority': 'REDACTED:8080',
    ':method': 'POST',
    ':path': '/redacted',
    ':scheme': 'https',
    'content-type': 'application/json',
    'content-length': '163',
    'accept-encoding': 'gzip',
    'user-agent': 'Go-http-client/2.0',
    [Symbol(sensitiveHeaders)]: []
  },
  [Symbol(rawHeaders)]: [
    ':authority',
    'REDACTED:8080',
    ':method',
    'POST',
    ':path',
    '/redacted',
    ':scheme',
    'https',
    'content-type',
    'application/json',
    'content-length',
    '163',
    'accept-encoding',
    'gzip',
    'user-agent',
    'Go-http-client/2.0'
  ],
  [Symbol(trailers)]: {},
  [Symbol(rawTrailers)]: [],
  [Symbol(stream)]: Http2Stream {
    id: 3,
    closed: true,
    destroyed: true,
    state: {},
    readableState: ReadableState {
      highWaterMark: 16384,
      buffer: [],
      bufferIndex: 0,
      length: 0,
      pipes: [],
      awaitDrainWriters: null,
      [Symbol(kState)]: 193987578,
      [Symbol(kErroredValue)]: Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_PROTOCOL_ERROR
          at ServerHttp2Stream._destroy (node:internal/http2/core:2375:13)
          at _destroy (node:internal/streams/destroy:121:10)
          at ServerHttp2Stream.destroy (node:internal/streams/destroy:83:5)
          at Writable.destroy (node:internal/streams/writable:1120:11)
          at Http2Stream.onStreamClose (node:internal/http2/core:562:12) {
        code: 'ERR_HTTP2_STREAM_ERROR'
      }
    },
    writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 1091450362,
      [Symbol(kBufferedValue)]: null,
      [Symbol(kErroredValue)]: Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_PROTOCOL_ERROR
          at ServerHttp2Stream._destroy (node:internal/http2/core:2375:13)
          at _destroy (node:internal/streams/destroy:121:10)
          at ServerHttp2Stream.destroy (node:internal/streams/destroy:83:5)
          at Writable.destroy (node:internal/streams/writable:1120:11)
          at Http2Stream.onStreamClose (node:internal/http2/core:562:12) {
        code: 'ERR_HTTP2_STREAM_ERROR'
      }
    }
  },
  [Symbol(aborted)]: true
}
```
expected content-length: 163, real content-length: 0

**Comment by climba03003** [comment]
I can see it is blocked from the `Node.js` side.
See the error `NGHTTP2_PROTOCOL_ERROR`, it is not throwing with `FST_ERR_CTP_INVALID_CONTENT_LENGTH` as you mention.

**Comment by gugu** [comment]
That was debug logging, this is the error:
```
FastifyError [Error]: Request body size did not match Content-Length
    at Http2ServerRequest.onEnd (/redacted/node_modules/.pnpm/fastify@4.28.1_patch_hash=redacted/node_modules/fastify/lib/contentTypeParser.js:276:18)
    at Http2ServerRequest.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_CTP_INVALID_CONTENT_LENGTH',
  statusCode: 400
```

**Comment by climba03003** [comment]
I see the the request does actually handle by `fastify`, but testing with `curl`. The response never get to the other side.
So, it may not be related to the `connection` header, but `Node.js` force close the connection without notice.

```js
import Fastify from 'fastify'

const fastify = Fastify({
  http2: true,
  logger: true
})

fastify.post('/', () => Promise.resolve({}))

fastify.setErrorHandler((error) => {
  console.log(error)
})

fastify.listen({ port: 3000 })

// curl --http2 --http2-prior-knowledge -d '{"text":"012345678901234567890123456789"}' -H 'Content-Type: application/json' -H 'Content-Length: 20' http://127.0.0.1:3000
```

**Comment by climba03003** [comment]
> Connection needs either survive such requests or correctly close in HTTP2 mode

Since the request is closed by `Node.js`, there is nothing to do with us.

> What I noticed - right now this error type sends Connection: close. I guess it can be an issue with HTTP2, because they have a different way of closing connection.
> Does fastify really need it? Is it required in HTTP2 mode?

We can selectively send the header, but as explained above the problematic header should not get sent in `HTTP/2` in this particular case.
So, adding an extra `if` doesn't make sense for me.

**Comment by gugu** [comment]
The problem is not with broken request, but with fastify instance in unresponsive state after the error I mentioned. 

I'm trying to reproduce it using your curl command in the infinite loop, but not successfully yet - I'm not getting this exception, it just closes a stream

**Comment by climba03003** [comment]
> The problem is not with broken request, but with fastify instance in unresponsive state after the error I mentioned.

It needs more info to identify the cause.
At this stage, even if I use `curl` with `content-length: 163` without payload. It has no success to stale `fastify`.

I am think is it related to any plugin instead of core?

**Comment by gugu** [comment]
no, it does not have any plugins except of prometheus

**Comment by gugu** [comment]
Okay, they problem with hanging stream was withing golang http.Client. After setting a different timeout the stream was closed correctly from the both sides

**Comment by gugu** [comment]
Yes, fixing the problem on client side (golang) helped
