### ISSUE TITLE
Logger instance causes FST_ERR_LOG_INVALID_LOGGER_CONFIG error

### ISSUE THREAD

**Issue by Ghirigoro** [fastify/fastify#5725]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.28.1

### Stopped working in version

5.0.0

### Node.js version

20.11.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.6.1

### 💥 Regression Report

In previous versions of Fastify you could initialize Fastify with an instance of a logger (as long as it supported the interface of Pino loggers):

```js
// This used to work...
const server = Fastify({ logger: myCustomLogger });
```
but since upgrading to Fastify 5.0.0 this fails with the following error:
`FastifyError [FST_ERR_LOG_INVALID_LOGGER_CONFIG]: logger options only accepts a configuration object.`

### Steps to Reproduce

Create an instance of Fastify while supplying a custom logger.

### Expected Behavior

Fastify to create an instance without throwing an error.

**Comment by gurgunday** [comment]
You need to pass it to the loggerInstance option
