### ISSUE TITLE
npm audit: cookie accepts cookie name, path, and domain with out of bounds characters

### ISSUE THREAD

**Issue by borfig** [fastify/fastify#5731]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

20.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Alpine 3.19.0

### Description

This package depends on `light-my-request` which depends on a vulnerable version of the `cookie` dependency.
```
# npm audit report

cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
fix available via `npm audit fix --force`
Will install fastify@2.11.0, which is a breaking change
node_modules/cookie
  light-my-request  >=3.7.0
  Depends on vulnerable versions of cookie
  node_modules/light-my-request
    fastify  >=2.12.0
    Depends on vulnerable versions of light-my-request
    node_modules/fastify

3 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
Downgrading to the previous major version of fastify is not an option for us.

### Expected Behavior

`npm audit` should report `0` vulnerabilities

**Comment by Uzlopak** [comment]
ask the cookie maintainers to use semver versioning and then we could just set it to ^1.0.0

**Comment by jsumners** [comment]
`fastify@2` is no longer supported. See https://github.com/fastify/fastify/blob/eb3deddee77fea2a0d99988a72738a09c9d4ef4e/docs/Reference/LTS.md#schedule
