### ISSUE TITLE
Bad URLs return HTTP 400 on v5 and never hits the setNotFoundHandler

### ISSUE THREAD

**Issue by leftieFriele** [fastify/fastify#5735]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Node.js version

22.5.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.6.1

### Description

```js
import fastify from "fastify";

const app = fastify();
app.setNotFoundHandler(function (request, reply) {
	reply.code(404).send();
});

app.get("/what-ever", async (req, reply) => {
	return reply.code(404).send("Not found");
});
await app.listen({ port: 8080, host: "0.0.0.0" });
```
Sending a bad URL to the server like this:
```sh
 curl -I "localhost:8080/ahvenanmaa/piha_ja_puutarha/static/..;/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/etc/passwd"
```
Produces a HTTP 400 on v5:
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 263
Date: Thu, 10 Oct 2024 07:38:48 GMT
Connection: keep-alive
Keep-Alive: timeout=72
```
with this log output:
```json
{
 "error":"Bad Request", 
 "code":"FST_ERR_BAD_URL", 
 "message":"'/ahvenanmaa/piha_ja_puutarha/static/..;/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/etc/passwd' is not a valid url component",
 "statusCode":400
}
```

### Expected Behavior

Expected output, which is the one which I get from v4.28.1: 
```
HTTP/1.1 404 Not Found
Date: Thu, 10 Oct 2024 07:39:40 GMT
Connection: keep-alive
Keep-Alive: timeout=72
```

**Comment by mcollina** [comment]
I don't recall why that is now a bad URL vs a 404 and I don't have much time to dig into PRs that went into v5.

However the behavior looks correct: that's a bad url.

You can customize the response with https://fastify.dev/docs/latest/Reference/Server/#frameworkerrors.

**Comment by climba03003** [comment]
> I don't recall why that is now a bad URL vs a 404 and I don't have much time to dig into PRs that went into v5.

It is because the `/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/etc/passwd` part treats as querystring on `fastify@4` and since https://github.com/fastify/fastify/pull/5320, it is part of the path.

**Comment by leftieFriele** [comment]
thank you so much for the explanation @climba03003 🙇 
I somehow missed to read the [Migration-Guide-V5.md](https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V5.md)

**Comment by cristobal** [comment]
> thank you so much for the explanation [@climba03003](https://github.com/climba03003) 🙇 I somehow missed to read the [Migration-Guide-V5.md](https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V5.md)

Same here nice to see you here wondering the same thing as us @leftieFriele.

Yes this is important when one has a CDN in front that take into account `cache-control` header, to ensure that we can offload the 400 responses to the CDN in case of misuse and/or DDoS attacks.
