### ISSUE TITLE
`addContentTypeParser()` no longer case-sensitive

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#5740]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Node.js version

20.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Spotted whilst trying to upgrade one of my projects from Fastify v4.28.1 to v5.0.0, `addContentTypeParser` is no longer case-sensitive and will only parse requests if the content-type is in lower-case.

For example, with v4.28.1 `addContentTypeParser('application/vnd.ms-word.document.macroEnabled.12', ...)` would parse `application/vnd.ms-word.document.macroEnabled.12` but not `application/vnd.ms-word.document.macroenabled.12`, as expected.

With v5.0.0, `application/vnd.ms-word.document.macroEnabled.12` is no longer parsed and throws a 415 error, whilst `application/vnd.ms-word.document.macroenabled.12` is parsed.

This isn't ideal when there are mime-types that generally have uppercase values in them, [such as Microsoft Office documents](https://learn.microsoft.com/en-us/previous-versions/office/office-2007-resource-kit/ee309278%28v=office.12%29).

This was not documented as a change in the v5 migration guide, so I assume it is unintended.

### Link to code that reproduces the bug

https://github.com/Fdawgs/fastify-content-type-parser-bug

### Expected Behavior

With Fastify v4.x `addContentTypeParser` was case-sensitive, and in v5.0.0 it is lowercase only.
However, both implementations are wrong and it should be case-insensitive as per [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-3.7). and [RFC 6838](https://www.rfc-editor.org/rfc/rfc6838.html).

**Comment by Fdawgs** [comment]
Thanks @gurgunday!

**Comment by gurgunday** [comment]
No problem!

Thanks for bringing it up and the great issue description
