### ISSUE TITLE
Bump up version the "cookie" library by "light-my-request".

### ISSUE THREAD

**Issue by tolluset** [fastify/fastify#5743]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The "cookie" library has below issue.
https://github.com/advisories/GHSA-pxg6-pf52-xh8x

The fixed "cookie" version is `v7.0.0` but the dependencies of fastify what "light-my-request" has `v6.0.0` "cookie" verison.
https://github.com/fastify/light-my-request/releases/tag/v6.1.0

We can fix this issue by bump up "light-my-request" version to `v6.1.0`

**Comment by mcollina** [comment]
There is nothing to do here. Update your dependencies and it will pull down the right one.

**Comment by tolluset** [comment]
Close it because I found PR that not update the verion.

https://github.com/fastify/fastify/pull/5739
