### ISSUE TITLE
Use of `var` for initialising variables

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#5756]
Noticed this whilst looking at https://github.com/fastify/fastify/pull/5745, Fastify has a few `var`s knocking about in both [`fastify` itself](https://github.com/search?q=repo%3Afastify%2Ffastify%20var&type=code) and supporting plugins, primarily in loops.

Is there a performance reason for using `var` over `let` or `const`?

**Comment by jsumners** [comment]
> Is there a performance reason for using `var` over `let` or `const`?

There was, yes. I think that has largely been resolved and we can replace all such instances.

**Comment by ChinoUkaegbu** [comment]
Hi I'd like to work on this! Just to clarify, the changes are to be made in this repository only?

**Comment by gurgunday** [comment]
If within a block the declarations are at the top, the runtime effect is pretty much non-existant in modern V8

let/const are only (very-slightly) worse when they are used after other statements within a block (TDZ) AFAIK

**Comment by Fdawgs** [comment]
@ChinoUkaegbu If/when https://github.com/fastify/fastify/pull/5759 is merged then feel free to make similar PRs if you find any in the other Fastify repos.

**Comment by gurgunday** [comment]
This provides solid insights into how V8 team is eliminating the TDZ checks:

https://docs.google.com/document/d/1klT7-tQpxtYbwhssRDKfUMEgm-NS3iUeMuApuRgZnAw/edit?tab=t.0

Like I said, simple cases where let and const are declared at the beginning of a scope/function are easily optimized
