### ISSUE TITLE
Hacktoberfest 2024 - Coding Bunker

### ISSUE THREAD

**Issue by pmarchini** [fastify/fastify#5785]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi Everyone,

Today, as part of an open-source event related to Hacktoberfest, we opened some PRs.
We would love to have them labelled as `hacktoberfest-accepted` if possible 😁 

Here is the list:

- https://github.com/fastify/fastify/pull/5772
- https://github.com/fastify/fastify/pull/5773
- https://github.com/fastify/fastify/pull/5774
- https://github.com/fastify/fastify/pull/5775
- https://github.com/fastify/fastify/pull/5776
- https://github.com/fastify/fastify/pull/5777
- https://github.com/fastify/fastify/pull/5778
- https://github.com/fastify/fastify/pull/5779
- https://github.com/fastify/fastify/pull/5780
- https://github.com/fastify/fastify/pull/5781
- https://github.com/fastify/fastify/pull/5782
- https://github.com/fastify/fastify/pull/5783
- https://github.com/fastify/fastify/pull/5784

Thank you in advance 🚀 

/cc @jsumners @simoneb

**Comment by Uzlopak** [comment]
We are not participating in hacktoberfest. We will not introduce `hacktoberfest-accepted`.

**Comment by Uzlopak** [comment]
Reopening, because i missed the fact that this was discussed in https://github.com/fastify/fastify/pull/5782#issuecomment-2439664744

**Comment by simoneb** [comment]
I have applied the hacktoberfest-accepted label to the above PRs. closing

**Comment by jsumners** [comment]
Thank you to the contributors for your excellent contributions.

For the organizers, in the future, please put up a proposal/heads-up issue before including a project in such an initiative. It would have allowed us to prepare for handling the issues in the way you were expecting.

**Comment by simoneb** [comment]
You're right @jsumners , I had contacted Matteo privately to gather his interest but I didn't get an answer, so I searched for an existing conversation and found this https://github.com/fastify/fastify/discussions/2583. So I assumed it would be fine to participate, which is why I gave @pmarchini the green lights - as the contributions came during a community event that he organized -only to discover that I could not create the label myself. Thanks for your help

**Comment by jsumners** [comment]
We usually don't participate in "hacktober" events due to a bad experience with the first one. But I am quite pleased with the quality of this event, and am very willing to work with such groups in the future. We just need to coordinate.
