### ISSUE TITLE
How do you execute the benchmark tests?

### ISSUE THREAD

**Issue by AutoSponge** [fastify/fastify#58]
I looked through the docs and the tests but don't see what you're using to execute the X/rps.

**Comment by delvedor** [comment]
Hi, we updated the docs recently and we forgot to add the benchmark runner test, I'll update them asap.

By the way, all benchmarks where average taken over 5 seconds, on the second run of:
```
$ autocannon -c 100 -d 5 -p 10 localhost:3000
```
