### ISSUE TITLE
Route path not working in query when path includes the - hyphen

### ISSUE THREAD

**Issue by anishkumar127** [fastify/fastify#5804]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^5.0.0

### Node.js version

v20.13.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11 latest

### Description

![image](https://github.com/user-attachments/assets/975c1baa-075c-48ed-904c-36dc526280b9)

```js
export const redirectPermanentlyByQuery = async (request: FastifyRequest, reply: FastifyReply) => {
    try {
        const { link } = request.query as { link: string };
        if (!link || typeof link !== 'string') {
            return reply.code(401).send({ error: 'Missing link' });
        }
        return reply.status(301).redirect(link);
    } catch (error) {
        return reply.status(500).send({ error: 'Internal Server Error' });
    }
};
```
```js
  fastify.get('/redirect-to', {
        handler: redirectPermanentlyByQuery,
        schema: {
            querystring: {
              type: 'object',
              properties: {
                link: { type: 'string' }
              },
              required: ['link']
            }
          }
    });
```

```http
http://localhost:3000/api/v1/redirect-to?link=google.com
```

### Expected Behavior

It's should be redirect to google.com but it's not working with redirect-to  
maybe the issue with - case when include this symbol - it's not working 

also in chrome coming like this when do with - 

![image](https://github.com/user-attachments/assets/259d67b6-fb60-4487-a664-b205ac1d8e70)

it's changed the even url also in chrome i put this `http://localhost:3000/api/v1/redirect-to?link=google.com` in url but it's become after hit enter this `http://localhost:3000/api/v1/google.com`

am i doing something wrong ?  please let me know.

**Comment by metcoder95** [comment]
This is not an issue with Fastify but its how are you handling the redirect.

First, the redirect should should contain the complete URL of the origin destination (including scheme, i.e. `https://google.com`).

Second, this will work on `cURL` and but I'm doubtful will work on browsers as your are doing a cross-domain redirect, and that will require your site to be under secure TLS connection to ensure the certificate chain is validated while redirecting.

example:
`curl -L -r 0-99 -v http://localhost:57093/redirect-to\?link\=https://google.com`
