### ISSUE TITLE
Graceful shutdown after synchronous error

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#582]
When a synchronous error is thrown (err-first-callback) fastify should gracefully shutdown. As a user I expect that the  `onClose` hook is called and fastify will exit with the error. When using Promises or Async / Await the error is handled automatically and the user is responsible for that.

**Comment by mcollina** [comment]
Can you make a code example?

We handle promises and errbacks with the same codebase, so the behavior will likey be identical.

**Comment by StarpTech** [comment]
This code will lead to an uncaught error and the user is not able to gracefully shutdown fastify (close connection etc..)

```js
fastify
  .get('/', schema, function (req, reply) {
   		throw new Error('####')
  })
```

My proposal is to catch synchronous errors and call `close()`

**Comment by mcollina** [comment]
Unfortunately, this is not easy to do reliably and with decent performance. Plus, it completely prevent you to use post-mortem debugging.

What you want in your code is:

process.on(‘uncaughtException’, () => { server.close() }.

I’m +1 in having that into a plugin in the main org, and mention this in the docs.

Supportig bounce-like logic is actually a very good idea for promisified code. I’m -1 on wrapping every handler with a try/catch - it’s a very unreliable way to achieve this goal.

**Comment by StarpTech** [comment]
Hi, @mcollina I don't mean to catch any uncaught error. I'm talking primarily about a solution to gracefully shutdown fastify in any scenario. Fastify can still exit but in combination with `onClose` -> `throw err`

**Comment by mcollina** [comment]
why process.on(‘uncaughrException’) is not enough?

**Comment by StarpTech** [comment]
Because `close` can not be called since the interface of `uncaughtException` is synchronous..

Source: https://nodejs.org/api/process.html#process_event_uncaughtexception

> Exceptions thrown from within the event handler **will not be caught**. Instead the process will exit with a non-zero exit code and the stack trace will be printed. This is to avoid infinite recursion.

> The correct use of 'uncaughtException' is to perform **synchronous** cleanup of allocated resources (e.g. file descriptors, handles, etc) before shutting down the process. It is not safe to resume normal operation after 'uncaughtException'.

**Comment by mcollina** [comment]
Indeed it is. However this is the exact same that you want to achieve.

**Comment by StarpTech** [comment]
No, I just want to catch synchronous errors because fastify support callback style and the user is not possible to react on it. We can also highly recommend async or promise style in the docs and mark callback style as deprecated. When this is not our goal we should provide at least the same safety which other styles (promise..)  provide and with callback style we have to use try/catch.

**Comment by nwoltman** [comment]
What if Fastify [called the handler](https://github.com/fastify/fastify/blob/0d8de7e8ec5a45721360a87c1b0d6c42fceb07b4/lib/handleRequest.js#L122) inside a `try-catch` block?

**Comment by StarpTech** [comment]
Yes, this is my intention but it has significant performance impact on older node versions (before turbo fan)

**Comment by mcollina** [comment]
I’m -1 with adding a try/catch block. That creates a difference between synchronous and asynchronous code when using callbacks. Relying on that pattern will cause unexpected behavior.

**Comment by StarpTech** [comment]
A mixture is in general bad practice and I'm talking about users who follow callback convention strictly.

**Comment by mcollina** [comment]
Then I’m not understanding what you want to achieve, your last comment seems in contradiction with wrapping the handler in a try/catch.

**Comment by StarpTech** [comment]
Ok I'm trying to explain it again. If you decide to use callback style it will happen that you can't catch the error and the server will exit. I want go give users the same safety as with async / await. In my opinion it's very convenient to catch synchronous errors when using callback style. This should be no problem because any other error is handled by promises or async / await and is evaluated with catch handler.

**Comment by StarpTech** [comment]
```diff
function preHandlerCallback (err, state) {
  if (err) {
    state.reply.send(err)
    return
  }
// Handle synchronous errors
++    var result
++     try {
++      result = state.context.handler(state.request, state.reply)
++     } catch(err) {
++     Bounce.rethrow(err, 'system');
++     state.reply._isError = true
++     state.reply.send(err)
++     return
++  }
 // Handle asynchronous errors
  if (result && typeof result.then === 'function') {
    result.then((payload) => {
      // this is for async functions that
      // are using reply.send directly
      if (payload !== undefined || (state.reply.res.statusCode === 204 && !state.reply.sent)) {
        state.reply.send(payload)
      }
    }).catch((err) => {
++    Bounce.rethrow(err, 'system');
      state.reply._isError = true
      state.reply.send(err)
    })
  }
}
```
NB: Rethrow on System errors https://github.com/hapijs/bounce/blob/master/lib/index.js#L13

**Comment by mcollina** [comment]
Bounce is not ok as a dependency becuase it supports 8+. I would also like to check what the performance look like.

I’m very -1 with this change to happen on the callback side for the consistency reason we discussed above, it just covers the synchronous part. For async/await and promises, yes absolutely but we need an alternative to Bounce.

**Comment by StarpTech** [comment]
Could you go in detail if you talking about "consistency" ? The `try / catch` only prevents from crashing the server immediately everything else is the same.

**Comment by mcollina** [comment]
Inside a handler, synchronous and asynchronous errors should be treated the same. Adding a try/catch on the synchronous side makes this logic inconsistent.

**Comment by StarpTech** [comment]
I looked some other implementations. They all tend to exit the server immediately (restify) or using async / await (Koa2). Hapi is exceptional it catches any sync error as well as uing async / await. For me it's ok to say that if you need more flexibility you should use a different way but @mcollina what when we exit on system errors in promises or async / await, should the error be logged, should the server exit gracefully or hard?

**Comment by jsumners** [comment]
You have already opened this issue once and it got resolved there -- https://github.com/fastify/fastify/issues/260

**Comment by mcollina** [comment]
I think we should discuss about what to do with promises. My instinct would be to rethrow and have the error land in 'unhandledRejection'. There, we can have a plugin that listen for that event and do the graceful shutdown.

@jsumners I think we should rethrow on system errors when handling promises. This is novel.

**Comment by StarpTech** [comment]
@jsumners this was a different issue. Here we are talking about a graceful shutdown of synchronous errors in the handler.

**Comment by StarpTech** [comment]
I close this issue the result is https://github.com/fastify/fastify/pull/591
