### ISSUE TITLE
Accessing `req.hostname` throws if `Host` HTTP header is missing

### ISSUE THREAD

**Issue by zdila** [fastify/fastify#5841]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Node.js version

22

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian Testing

### Description

Accessing `req.hostname` throws if `Host` HTTP header is missing.

```
Cannot read properties of undefined (reading 'split')
```

https://github.com/fastify/fastify/blob/54b1022839a85f32899932e237e1a5463bfd96da/lib/request.js#L223

```
> telnet localhost 8080
GET / HTTP/1.0

Connection closed by foreign host.
```

### Expected Behavior

Value of `req.hostname` should be `null` or `undefined` if `Host` HTTP header is missing.

**Comment by climba03003** [comment]
`Host` should never be empty, it is blocked on the `Node.js` level and should never reach our code.
Even if you allows by using the `requireHostHeader` option, we should be able to fallback to empty string.

Please provide a proper minimal reproducible code snippets that we can run directly.
Otherwise, I might consider to close it within a week.

**Comment by zdila** [comment]
Testcase:

```js
import Fastify from "fastify";
import pino from "pino";

const fastify = Fastify({
  loggerInstance: pino().child(
    { name: "logger" },
    {
      serializers: {
        req(req) {
          return {
            hostname: req.hostname,
          };
        },
      },
    }
  ),
});

fastify.get("/", function (request, reply) {
  reply.send({ hello: "world" });
});

fastify.listen({ port: 3000 }, function (err) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```

**Comment by climba03003** [comment]
The problems here is related to `HTTP/1.0` which is different than `HTTP/1.1`.
Seems like we should also use `??=` when `HTTP/1.0` or `HTTP/0.9`.

cc @fastify/core

**Comment by gurgunday** [comment]
Should we even support HTTP versions < 1?

**Comment by climba03003** [comment]
> Should we even try to support HTTP versions < 1?

`HTTP/0.9` is still used for debugging purpose.

**Comment by SeanReece** [comment]
This error can also be reproduced by setting a header schema with `additionProperties: false`.

```ts
import fastify from 'fastify'

const app = fastify()

const schema = {
  headers: {
    type: 'object',
    properties: {
      custom: { type: 'string' },
    },
  },
}

const schema2 = {
  headers: {
    ...schema.headers,
    additionalProperties: false,
  },
}

app.get('/good', { schema }, async (request, reply) => {
  return { hostname: request.hostname }
})

app.get('/bad', { schema: schema2 }, async (request, reply) => {
  return { hostname: request.hostname }
})

app
  .inject({
    method: 'GET',
    url: '/good',
  })
  .then((response) => {
    console.log(response.json())
  })

app
  .inject({
    method: 'GET',
    url: '/bad',
  })
  .then((response) => {
    console.log(response.json())
  })
```

Will result in 

```jsonc
// GET /good
{ hostname: 'localhost' }

// GET /bad
{
  statusCode: 500,
  error: 'Internal Server Error',
  message: "Cannot read properties of undefined (reading 'split')"
}
```

One might argue, "Just don't do that" which I agree with - but this scenario should probably be better handled.

**Comment by jsumners** [comment]
🤔 technically we only advertise "specification adherence":

https://github.com/fastify/fastify/blob/87f9f20687c938828f1138f91682d568d2a31e53/docs/Reference/Principles.md?plain=1#L76-L78

But I can't recall a time where we have ever reference any HTTP spec other than v1.1. @fastify/core do you think we should directly support HTTP/1.0? I do _not_ think we should directly support anything less than HTTP/1.0.
