### ISSUE TITLE
Include hook names in timeout errors if available

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify#5850]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently it is very difficult to debug issues happening within hooks. E. g. if one of the `onReady` hooks is timing out, it is very difficult to understand which exact hook is at fault.
In case a named function was passed as a hook, we actually have useful information that can be used to narrow down the source of the problem. It would be helpful to include it in the error thrown from the fastify side.

### Motivation

It is difficult to debug issues with hooks when it is unclear which hooks are causing issues

### Example

```js
fastify.addHook('onReady', async function NamedOnReadyHook () {
  // Some async code
  await loadCacheFromDatabase()
})
```

**Comment by freiondrej-lokalise** [comment]
@kibertoad I vaguely recall a fastify functionality that if you pass a named function, it would use its name in the logs. Maybe this would be usable in this case too? 🤔

**Comment by kibertoad** [comment]
This is what we have:
```
![image](https://github.com/user-attachments/assets/250260cd-9120-47b9-b456-d34460515110)
```

**Comment by kibertoad** [comment]
I can send a PR for this if this change is approved.

**Comment by jsumners** [comment]
Sounds like a good idea.
