### ISSUE TITLE
request.ip can be spoofed when using a reverse proxy that includes original X-Forwarded-For headers

### ISSUE THREAD

**Issue by peroneu** [fastify/fastify#5865]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Node.js version

22.11.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian 12

### Description

**TL;DR** A client can spoof its real IP address (by providing a _X-Forwarded-For_ header with its request) if Fastify is running behind Nginx configured to include the original header, which is the recommended way in many guides and tutorials. This allows the client to bypass rate limiters and other plugins or code which relies on the accuracy of _request.ip_.

Scenario: A Fastify server (with **trustProxy: true**) is running behind an Nginx server that includes the following line in its configuration:

`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

According to the [Nginx documentation](https://nginx.org/en/docs/http/ngx_http_proxy_module.html), this means that the client's IP is added at the end of all the IPs (if any) provided by the client in the _X-Forwarded-For_ header.

> **$proxy_add_x_forwarded_for**
>
> the “X-Forwarded-For” client request header field with the $remote_addr variable appended to it, separated by a comma. If the “X-Forwarded-For” field is not present in the client request header, the $proxy_add_x_forwarded_for variable is equal to the $remote_addr variable.

Eg. The client's request contains a contrived header, as following:

`X-Forwarded-For: 1.1.1.1, 2.2.2.2, 3.3.3.3`

The header provided by Nginx is (supposedly):

`X-Forwarded-For: 1.1.1.1, 2.2.2.2, 3.3.3.3, real-ip-of-the-client`

However, _request.ips_ has the IPs in the following order:

`127.0.0.1, real-ip-of-the-client, 3.3.3.3, 2.2.2.2, 1.1.1.1`

And since _request.ip_ returns the last item of _request.ips,_ it actually contains the first IP provided by the client, which means that whatever the client sends in the _X-Forwarded-For_ is perceived as the real IP, therefore allowing the client to spoof its IP address.

This can be solved by reconfiguring Nginx to skip the incoming X-Forwarded-For header and just return the actual IP of the client (see below), but as far as I understand, it's common practice to include the incoming header as well, which is safe to do, as long as the real IP is the last one, and I'm wondering how many Nginx servers are configured this way.

`proxy_set_header X-Forwarded-For $remote_addr;`

After checking the _request.js_ source file, I suspect that the issue is not with Fastity itself, but with the **_proxy-addr_** package.

Here's what proxy-addr's documentation states, which I find a bit odd (unless I am misundersdanding it...):

> **proxyaddr.all(req, [trust])**
>
> Return all the addresses of the request, optionally stopping at the first untrusted. This array is ordered from closest to furthest (i.e. arr[0] === req.connection.remoteAddress).

If the array is ordered from closest (server) to furthest (client), shouldn't the remoteAddress be the last in the list, instead of arr[0]?

### Expected Behavior

I would expect _request.ip_ to contain the actual IP of the client (ie. the last IP provided by Nginx in the _X-Forwarded-For_ header).

**Comment by Uzlopak** [comment]
> This can be solved by reconfiguring Nginx to skip the incoming X-Forwarded-For header and just return the actual IP of the client (see below), but as far as I understand, it's common practice to include the incoming header as well, which is safe to do, as long as the real IP is the last one, and I'm wondering how many Nginx servers are configured this way.

This is a known issue and has to be configured properly by the reverse proxy (nginx, traefik etc.).

Nothing to do here.

**Comment by climba03003** [comment]
`X-Forwarded-For` header is known to be spoofed, using `trustProxy: true` is blindly trusting all the address and should be avoided in production environment.

You should only using `hop number` or `address` to check the `trust proxy` and remove the unwanted one.
```js
import Fastify from 'fastify'

async function checkTrustProxy(trustProxy, remote) {
  const fastify = Fastify({
    trustProxy
  })
  fastify.get('/', async (request) => {
    return {
      ip: request.ip,
      ips: request.ips
    }
  })
  const response = await fastify.inject({
    method: 'GET',
    path: '/',
    headers: {
      'X-Forwarded-For': remote
    }
  })
  return response.json()
}

const REMOTE = '1.1.1.1, 2.2.2.2, 3.3.3.3, 123.123.123.123'
console.log('Using "%s" as X-Forwarded-For', REMOTE)
// trusting all remote
console.log('true', await checkTrustProxy(true, REMOTE))
// trust only the first hop
console.log('1', await checkTrustProxy(1, REMOTE))
// trust only the localhost, private subnet
console.log('127.0.0.1', await checkTrustProxy(['127.0.0.1', '192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8'], REMOTE))
```

**Comment by peroneu** [comment]
@climba03003 Thanks for clarifying, I appreciate it.
