### ISSUE TITLE
Removed `request.connection` still has a type definition in v5.1

### ISSUE THREAD

**Issue by ianjkaplan** [fastify/fastify#5875]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.1

### Node.js version

22.12

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

sonoma 14.6.1

### Description

After migrating to fastify >5.0.0 and reading the migration guide I found that the `req.connection` property had been full deprecated and removed. However the type definition still exists for this property on the `FastifyRequest` object, while at runtime the value is undefined. 

This difference in the type vs the value can lead to errors at runtime and it makes the migration process more error prone for typescript users who rely on the type checker to surface breaking changes like this.

I appreciate any clarification if I am missing context and I would be happy to submit the fix myself if that is preferred.

Thanks in advance

### Expected Behavior

expected behavior: 
The `FastifyRequest` type should not have a `connection` property type.

actual behavior:
The `FastifyRequest` type has a `connection` property type equivalent to the preferred`socket` property type

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?
