### ISSUE TITLE
Outdated fastify docs on error handling 

### ISSUE THREAD

**Issue by kamatheuska** [fastify/fastify#5876]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Regarding error handling documentation https://fastify.dev/docs/latest/Reference/Errors/#errors-in-fastify, the error handling docs might be outdated.

Here is the relevant part: https://github.com/fastify/fastify/blob/3d1bb6830229a57a5de29d757d88232aae386a12/docs/Reference/Errors.md?plain=1#L262

From what I understood in the issue https://github.com/fastify/fastify/issues/4998 we should probably use a helper function as described in this comment https://github.com/fastify/fastify/issues/4998#issuecomment-1695712561 instead of checking `instanceof` the error (which does not work in my case)

I am happy to do a PR to updated them

**Comment by metcoder95** [comment]
PRs are always welcomed!

**Comment by climba03003** [comment]
I have double checked the example, it is working as expected.
Although it is recommended to use the `.code` property, using `instanceof` will be some code styles choices.
It works when no monkey-patching of `Error` exists.

```js
const Fastify = require('fastify')

// Instantiate the framework
const fastify = Fastify({
  logger: true
})

// Declare a route
fastify.get('/', function (request, reply) {
  reply.code('bad status code').send({ hello: 'world' })
})

fastify.setErrorHandler(function (error, request, reply) {
  if (error instanceof Fastify.errorCodes.FST_ERR_BAD_STATUS_CODE) {
    // Log error
    this.log.error(error)
    // Send error response
    reply.status(500).send({ ok: false })
  } else {
    // fastify will use parent error handler to handle this
    reply.send(error)
  }
})

fastify.inject('/').then((response) => {
  console.log(response.statusCode, response.json())
})
```

**Comment by cyantree** [comment]
I'm unsure whether to open a new issue but will do so if you think it's a bug:
The above example `error instanceof Fastify.errorCodes.FST_ERR_BAD_STATUS_CODE` doesn't work for validation errors:
```js
import Fastify from 'fastify';

// Instantiate the framework
const fastify = Fastify({
  logger: true
})

// Declare a route
fastify.get('/', {schema: {query: {type: 'object', properties: {name: {type: 'string'}}, required: ['name']}}}, function (request, reply) {
  return 'ok';
})

fastify.setErrorHandler(function (error, request, reply) {
  if (error instanceof Fastify.errorCodes.FST_ERR_VALIDATION) {
      // >> This doesn't fire
    console.log('is validation error');
    
    // Log error
    this.log.error(error)
    // Send error response
    reply.status(400).send({ ok: false })
  } else {
    // Fastify will use parent error handler to handle this
    reply.send(error)
  }
})

// Run the server!
fastify.listen({ port: 3000 }, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  // Server is now listening on ${address}
})
```

Is this the expected behaviour?
As already discussed in [#4998](https://github.com/fastify/fastify/issues/4998#issuecomment-1914266668) it's not to be expected that every error inherits from `FastifyError` but I would've thought the `errorCodes` way should work for this error too.
