### ISSUE TITLE
default encoding in views

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#590]
Hi all,
I just see that if I dont' set in explitic way reply encoding, Firefox will complaint on missing encoding.
So for reply.view I need to do (anytime) something like:
  reply.type('text/html; charset=utf-8').view('index', data)

What do you think on adding that encoding as default for views (could be a good default) ?
Or check the encoding of related view (file) ... but this could be too much and alittle more expensive in performances.

What do you think ?

Thanks,
Sandro

**Comment by delvedor** [comment]
Hi!
Can you reopen this issue in [`point-of-view`](https://github.com/fastify/point-of-view)?

Thanks!

**Comment by smartiniOnGitHub** [comment]
ok, thanks (wasn't sure if the right place for it was here ...) I'll reopen there.
