### ISSUE TITLE
"fastify": "^0.35.7",

### ISSUE THREAD

**Issue by rabbitmeow** [fastify/fastify#595]
```js
const fastify = require('fastify')

const server = fastify()

server.get('/', async (request, reply) => {
    reply.type('text/html')
    reply.send(request.req.headers)
}).listen(8080)
```

no response and no error

**Comment by StarpTech** [comment]
Hi @rabbitmeow it depends on the content-type. You can't pass json and send it as `text/html`. You also should see an `UnhandledPromiseRejectionWarning:` in the console.

```js
fastify
  .get('/', schema, async function (req, reply) {
    reply.type('text/html')
    reply.send(JSON.stringify(req.headers))
  })
```

**Comment by rabbitmeow** [comment]
I know that. But the previous version would throw an error.

**Comment by StarpTech** [comment]
Please always write this on the issue. I could reproduce it.

**Comment by rabbitmeow** [comment]
thanks for your work.

**Comment by StarpTech** [comment]
@rabbitmeow thanks for reporting.
