### ISSUE TITLE
Serve static contents in compressed gzipped and brotli?

### ISSUE THREAD

**Issue by proyb6** [fastify/fastify#602]
How do you serve compressed contents over fastify?

**Comment by nwoltman** [comment]
Two questions:

1. Are you looking to compress contents as they are served or serve pre-compressed static files?
2. Are you currently using [`fastify-static`](https://github.com/fastify/fastify-static) to serve static files?

**Comment by proyb6** [comment]
1. Serve pre-compressed static files as in index.html.br and index.html.gz
2. I have not use Fastify yet.

**Comment by delvedor** [comment]
You can use the [`fastify-compress`](https://github.com/fastify/fastify-compress) plugin :)

**Comment by jsumners** [comment]
I believe @nwoltman has answered your question. You serve pre-compressed files the same way you would serve any other static file.

Feel free to re-open if you think your question is not sufficiently answered.

**Comment by proyb6** [comment]
@jsumners I think the Readme in Fastify-static could include more example of serving **example.html.gz**, **example.html.br** and blobs.

**Comment by jsumners** [comment]
@proyb6 that would be an issue for the `fastify-static` repository. But I don't see how adding a specific example with a '.gz' ending would be any different than the current example.

**Comment by nwoltman** [comment]
@proyb6 @jsumners When using `fastify-static` to serve compressed files, you need to use the [`setHeaders`](https://github.com/fastify/fastify-static#setheaders) option to set the right `Content-Type` and `Content-Encoding` headers.

Here's an example:

```js
const path = require('path')

function setHeaders(res, filePath) {
  const parsedPath = path.parse(filePath)

  if (parsedPath.ext === '.gz') {
    res.setHeader('Content-Encoding', 'gzip')
  } else if (parsedPath.ext === '.br') {
    res.setHeader('Content-Encoding', 'br')
  } else {
    return
  }

  if (path.extname(parsedPath.name) === '.html') {
    res.setHeader('Content-Type', 'text/html')
  }
}
