### ISSUE TITLE
Proposal - Add 'onRoute' extension to configure routes at startup time

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#605]
This issue result from https://github.com/fastify/fastify-auth/issues/8#issuecomment-355022588

### Introduction
Right now, there is no way to customize a route after it was defined. We encourage the user in [fastify-auth](https://github.com/fastify/fastify-auth) to configure the auth mechanism at definition `.route()`. This has the drawback that the implementation details are bound to the route definition and cannot be abstracted in an easy way. I propose to configure routes with the help of an `onRoute` extension. This solution is more powerful because it allows responding to specific route options.

This extensions could cleanup the routine to allocate all routes in [fastify-swagger](https://github.com/fastify/fastify-swagger/blob/master/index.js#L68).

#### Example
```js
fastify.route({
      method: 'POST',
      auth: 'basic',
      url: '/auth',
      handler: ....
})

function fastifyAuth(fastify, opts, done) {
 fastify.addHook('onRoute', (route, done) => {
   if(route.options.auth === 'basic') {
     route.beforeHandler.add(require('fastify-basic-auth'))
   }
   done()
 })
}
```

**Comment by allevo** [comment]
Nice! but how to handle the encapsulation?

**Comment by StarpTech** [comment]
What do you mean in detail? Where do you see the need? Plugin is already encapsulated.

**Comment by StarpTech** [comment]
@fastify/fastify  WDYT? I would start to implement it. @allevo ping.

**Comment by allevo** [comment]
```
fastify.register(async f => {
  f.addHook('onRoute', ....)
  f.get('/', myAwesomeHandler)
})
fastify.addHook('onRoute', ....)
```

Is `onRoute` hook fired for both of `fastify` instances?

NB: the `beforeHandler` is only one for route and for the time being is treated as preHandler. https://github.com/fastify/fastify/blob/dfd54dbf52d927e094246344e405c96f3f9bc8ba/fastify.js#L434

**Comment by jsumners** [comment]
Why is this needed over registering routes within a plugin?

**Comment by StarpTech** [comment]
@allevo yes, it's fired for each registered hook handler.
@jsumners did you read the issue description?

**Comment by jsumners** [comment]
@StarpTech no, I just randomly wrote some words.

**Comment by mcollina** [comment]
It is an interesting question to answer.

**Comment by StarpTech** [comment]
@jsumners keep calm, it would help if you could refer to my points and make a reasonable approach.

> Why is this needed over registering routes within a plugin?

Where do you see the difference between registering inside a plugin or on root level? The `onRoute` allows us:

- Configure the route from other plugins "event-based".
- Log which route was added.
- ...

**Comment by jsumners** [comment]
```js
const fatify = require('fastify')()

fastify.register(function (instance, opts, next) {
  // authenticated routes
  instance.register(require('fastify-bearer-auth'), {keys: new Set(['123456'])})

  instance.get('/foo', (req, reply) => {
    reply.send({authenticated: true})
  })
})

fastify.get('/', (req, reply) => {
  reply.send({authenticated: false})
})
```

Why isn't that sufficient? What would `onRoute` provide that that pattern does not? Proper Fastify plugins support encapsulation and can be registered as many times as needed.

**Comment by StarpTech** [comment]
`beforeHandler` are specific to a single route how do you use the encapsulation feature for this?

The other question:
- How do you react to specific route options with the existing hooks?

**Comment by allevo** [comment]
Manipulating the previous route definition can bring up to nightmare.

```
async function myAwesomePluing (fastify, opts) {
  fastify.addHook('onRoute', async route => {
    route.preHandler = []
    route.handler = () => Promise.resolve('foo-bar')
  })
}
```

**Comment by StarpTech** [comment]
This is a deal with dynamically typed language. Your use case can be adapted to any case.
Therefore we haven't defined the `route` interface it doesn't have to provide the full API.

**Comment by StarpTech** [comment]
@jsumners I think you mixed up `preHandler` with `beforeHandler`

**Comment by allevo** [comment]
Now `fastify` doesn't allow you to change the previous route definition. And this is a good thing.

I'd like to keep this approach. I don't like "event-based" management.

**Comment by jsumners** [comment]
@StarpTech what are you talking about?

**Comment by StarpTech** [comment]
@jsumners 
> beforeHandler are specific to a single route how do you use the encapsulation feature for this?

**Comment by jsumners** [comment]
Just as I showed in my example above.

**Comment by StarpTech** [comment]
This does not work. I'm talking about `beforeHandler` NOT `preHandler`. In your example, you can't specify a route without the `bearer-auth` handler. You have to create a plugin for any particular case. This is a solution but it doesn't solve the problem that you have to pass the complete route definition at creation time `instance.route()`. What if you have plugins which provide different `auth` strategies? You will end up like this:

`beforeHandler`
```js
fastify.register(function (instance, opts, next) {
  instance.register(require('fastify-bearer-auth'), {keys: new Set(['123456'])})
  instance.get('/foo', {  beforehandler: [fastify.bearerAuthHandler] })
})
fastify.register(function (instance, opts, next) {
  instance.register(require('fastify-basic-auth'), {keys: new Set(['123456'])})
  instance.get('/foo', {  beforehandler: [fastify.basicAuthHandler] })
})
fastify.register(function (instance, opts, next) {
  instance.register(require('fastify-jwt-auth'), {keys: new Set(['123456'])})
  instance.get('/foo', {  beforehandler: [fastify.jwtAuthHandler] })
})
```
`preHandler`
```js
fastify.register(function (instance, opts, next) {
  instance.register(require('fastify-bearer-auth'), {keys: new Set(['123456'])})
  instance.get('/foo', x => 'bar')
// How do you define a route with a different auth strategy?
})
```
instead
```js
instance.register(require('fastify-bearer-auth'), {keys: new Set(['123456'])})
instance.register(require('fastify-basic-auth'), {keys: new Set(['123456'])})
instance.register(require('fastify-jwt-auth'), {keys: new Set(['123456'])})

fastify.get('/foo', { auth: 'jwt' }, x => 'bar')
fastify.get('/foo', { auth: 'bearer' }, x => 'bar')
fastify.get('/foo', { auth: 'basic' }, x => 'bar')
```

**Comment by nwoltman** [comment]
What if the plugins created decorators instead?

```js
fastify.register(require('fastify-bearer-auth'), {keys: new Set(['123456'])})
fastify.register(require('fastify-basic-auth'), {keys: new Set(['123456'])})
fastify.register(require('fastify-jwt-auth'), {keys: new Set(['123456'])})

fastify.get('/foo', { beforeHandler: fastify.jwtAuth }, x => 'bar')
fastify.get('/foo', { beforeHandler: fastify.bearerAuth }, x => 'bar')
fastify.get('/foo', { beforeHandler: fastify.basicAuth }, x => 'bar')
```

**Comment by StarpTech** [comment]
If you match them by configuration pattern the solution is decoupled from their concrete implementations.

**Comment by StarpTech** [comment]
@mcollina @delvedor what's your opinion?

**Comment by mcollina** [comment]
I think we need more time to reason this about.

I think being able to 'intercept' route definitions and alter them could be very powerful, and simplify some of the current issues with auth.

Specifically:

```js
fastify
  .decorate('verifyJWTandLevel', function (request, reply, done) {
    // your validation logic
    done() // pass an error if the authentication fails
  })
  .decorate('verifyUserAndPassword', function (request, reply, done) {
    // your validation logic
    done() // pass an error if the authentication fails
  })
  .register(require('fastify-auth'))
  .after(() => {
    fastify.route({
      method: 'POST',
      url: '/auth-multiple',
      beforeHandler: fastify.auth([
        fastify.verifyJWTandLevel,
        fastify.verifyUserAndPassword
      ]),
      handler: (req, reply) => {
        req.log.info('Auth route')
        reply.send({ hello: 'world' })
      }
    })
  })
```

As you note, our current model requires the route definition to be placed within `after()`, otherwise all the required plugin will not be correctly loaded.
Adding a __route definition interceptor__ can definitely simplify that block of code.

I do not like the example provided at the top of this issues. Things that are not working for me:

1. the current fastify instance context is lost, and we would need to preserve it
2. adding a possibly dynamic require within fastify-auth it's not something I'm comfortable with

I would recommend to start with the target API we want for fastify-auth and walk back to the internals that we need.

What I would like to write:

```js
fastify
  .decorate('verifyJWTandLevel', function (request, reply, done) {
    // your validation logic
    done() // pass an error if the authentication fails
  })
  .decorate('verifyUserAndPassword', function (request, reply, done) {
    // your validation logic
    done() // pass an error if the authentication fails
  })
  .register(require('fastify-auth'))
  .route({
    method: 'POST',
    url: '/auth-multiple',
    auth: [
      'verifyJWTandLevel',
      'verifyUserAndPassword'
    ],
    handler: (req, reply) => {
      req.log.info('Auth route')
      reply.send({ hello: 'world' })
    }
  })
```

**Comment by allevo** [comment]
@mcollina if `auth` is inside `config` property the route definition keep it for you

For example in the repo `fastify-example-twitter` I have use it:

https://github.com/fastify/fastify-example-twitter/blob/9fce27882f90778a7f0078c84c3d95d518a60660/tweet/index.js#L54-L61

**Comment by StarpTech** [comment]
@mcollina your last approach is definitely better. We can reuse a lot of our existing api to provide a practical solution without to introduce a whole new concept.

- Use `config` property as @allevo previously mentioned.
- Use decorator to expose handlers. @nwoltman 
- Support string in `beforeHandler` for better decoupling. I like the idea: We can extend fastify by decorators and other components are able to do some introspection.

What has to be done?
- Support strings in `beforeHandler`
```js
fastify
  .decorate('verifyJWTandLevel', function (request, reply, done) {
    // your validation logic
   reply.context.config.auth // auth config
    done() // pass an error if the authentication fails
  })
  .register(require('fastify-auth'))
  .after(() => {
  	fastify.route({
     method: 'POST',
     url: '/auth-multiple',
     config:  { auth: 'jwt' },
     beforeHandler: [
      'verifyJWTandLevel'
     ],
     handler: (req, reply) => {
       req.log.info('Auth route')
       reply.send({ hello: 'world' })
     }
   })
})
```

**Comment by StarpTech** [comment]
> the current fastify instance context is lost, and we would need to preserve it

Correct me if I'm wrong but the `onRoute` would behave like the `onClose` which is not part of the request cycle.

```js
fastify.addHook('onRoute', (instance, done) => {
  // some code
  done()
})
```

> adding a possibly dynamic require within fastify-auth it's not something I'm comfortable with

This was just for demo purpose. The handler could be provided by a decorator or can be passed as plugin option.

**Comment by mcollina** [comment]
Can you make a full example on how that will look like?

**Comment by StarpTech** [comment]
Merged with https://github.com/fastify/fastify/pull/642
