### ISSUE TITLE
Do not JSON.stringify buffers when calling reply.send(buf)

### ISSUE THREAD

**Issue by mafintosh** [fastify/fastify#607]
Right now when passing a buffer to `reply.send` the buffer is JSON serialized.

This was confusing behavor to me, as I would expect to by bypass serialization when passing a string/buffer, in fact this already happens when passing a string.

If you want, then I'm happy to send a PR that adds this :)

**Comment by mcollina** [comment]
👍  for a PR, very good spot.

**Comment by delvedor** [comment]
Thanks!!

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/613.
