### ISSUE TITLE
Declare an empty response for 204 with fastify-swagger

### ISSUE THREAD

**Issue by tnguyen14** [fastify/fastify#609]
I'm using `fastify-swagger`, which I think adds some rules for validation. For 204 response (empty response), Swagger allows for its description by not specifying a `content` https://swagger.io/docs/specification/describing-responses/.

However, for `fastify-swagger`, I haven't found a way to do that yet. If I do:
```
{
  schema: {
    response: {
      204: {
        description: 'Successfully deleted item'
      }
    }
  }
}
```

I get the following stack trace:
```
Uncaught Exception Error: undefined unsupported
    at build (/Users/tri/project/node_modules/fast-json-stringify/index.js:80:13)
    at getValidatorForStatusCodeSchema (/Users/tri/project/node_modules/fastify/lib/validation.js:12:10)
    at /Users/tri/project/node_modules/fastify/lib/validation.js:18:21
    at Array.reduce (<anonymous>)
    at getResponseSchema (/Users/tri/project/node_modules/fastify/lib/validation.js:17:22)
    at build (/Users/tri/project/node_modules/fastify/lib/validation.js:44:28)
```

I first opened this issue at fastify/fastify-swagger#13

**Comment by scriptjs** [comment]
Running into the same issue. It is possible to eliminate this with an object but swagger/openapi does not normally require it. ie:

```json
schema: {
  response: {
    405: {
      description: 'Invalid ID supplied',
      type: 'object',
      properties: {
        code: {
          type: 'string'
        },
        message: {
          type: 'string'
        }
      },
      required: [
        'code', 'message'
      ]
    }
  }
}
```

**Comment by mcollina** [comment]
Would any of you send a PR to the relative projects (it can either be here or https://github.com/fastify/fast-json-stringify)?

**Comment by scriptjs** [comment]
@mcollina I don't believe this is an issue with fast-json-stringify. Its is impedance between fastify-swagger and swagger 2. The following would produce valid JSON but is not a valid JSON Schema.

```
schema: {
  response: {
    405: {
      description: 'Invalid ID supplied'
    }
  }
}
```

When a valid JSON Schema is provided there is nothing to fix but works against the grain for swagger for the UI with description only. Thus, it requires some discussion as to how to resolve this properly. Swagger is not exactly JSON Schema.

A possible resolution may be that fastify-swagger uses a `responses` object instead of `response` since swagger uses the plural name `responses` and you generate response schema in fastify-swagger but not sure if that makes sense either.

**Comment by mcollina** [comment]
I'm lost: you showed a stacktrace at the beginning. If we are throwing an exception and we shouldn't, then it's likely we have a bug.

**Comment by scriptjs** [comment]
Its a bug for fastify-swagger that it should not allow the description on its own that is the only required property for a response object. Currently it appears to be expecting a valid JSON Schema object to validate. Got it ? :) I am making fixes to fastify-swagger currently. I'll see whether I can fix this as well.

**Comment by mcollina** [comment]
That is passed down to fastify to validate, so it might be a bug here.

**Comment by scriptjs** [comment]
No problem. I'll find and fix. Got the security definitions and security on routes thing fixed now so this one is next.

**Comment by scriptjs** [comment]
Pull request https://github.com/fastify/fastify-swagger/pull/19 fixes this with an explicit `type: null` for empty responses.

**Comment by mcollina** [comment]
This is fixed.
