### ISSUE TITLE
Governance model

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#623]
## Proposal

According to the [Contributing](https://github.com/fastify/fastify/blob/aaa892ed8a39c78616801d2bc81d8696f0031549/CONTRIBUTING.md) document, Fastify uses an open governance model. Specifically it states:

> Individuals making significant and valuable contributions are given commit-access to the project to contribute as they see fit. This project is more like an open wiki than a standard guarded open source project.

Given recent events, my opinion is that this does not work; at least not as it is currently structured. I attempted to make it feasible with [PR 422](https://github.com/fastify/fastify/pull/422), later revised in [PR 614](https://github.com/fastify/fastify/pull/614), but I don't know that it is enough. I think we need to consider a different [governance model](http://oss-watch.ac.uk/resources/governancemodels).

I recognize that a "benevolent dictator" model is overly burdensome on a single individual. So I think a committee based model would be a better fit. That is, a designated team, or teams, is allowed to make final decisions on which PRs can be merged.

I propose that a single ultimate team, with full merge authority, consist of @delvedor and @mcollina. If other teams are desired then [GitHub's code owners](https://github.com/blog/2392-introducing-code-owners) feature should be investigated. For example, there could be a documentation team wherein all of @fastify/fastify is capable of making a merge to `master`.

## Final Thoughts

Fastify is quickly becoming a significant project within the Node.js ecosystem. I think this necessitates the project management be flexible enough to attract contributors, but also strong enough to make unpopular decisions.

I have been trying to do my part to make that a reality (see Issue #229), and this is another attempt to do so.

Please use this issue to voice your concerns on this matter. 

## Collaboration Section

*This section left blank for future usage. Ideas/proposals from the discussion may be added here by project owners so that future readings can get important information without reading through every message.*

**Comment by mcollina** [comment]
Thanks for taking this on your shoulders. This type of community work is __very hard__.

I think we should move to something resembling https://github.com/nodejs/node/blob/master/GOVERNANCE.md#collaborators. The language is more clear.

I would stress the fact that only breaking changes should be subjected to the "core team" approval. I would say that it requires 2 LGTMs from the core team, in case we grow it to more people.

**Comment by jsumners** [comment]
@mcollina or @delvedor please create a new team labeled "core" with at least yourselves in it. That way we can continue this discussion with an accurate concept of privilege separations.

**Comment by mcollina** [comment]
Done.

**Comment by jsumners** [comment]
@mcollina I like how that document gives a clear outline of what one has to do to be considered for being made a "collaborator". I will think on it some more and make a proposal (unless someone else beats me to it).

**Comment by corbinu** [comment]
@jsumners Thanks for taking this on. If I can give my two cents. I really admire/like the way the eslint project is run. Might be good to take a bit from their documentation on how they handle this.

**Comment by jsumners** [comment]
I need to get back to this. I'll look at the eslint stuff when I do.

**Comment by smartiniOnGitHub** [comment]
Hi all, some useful reference: 
- [PMCs - Apache](http://www.apache.org/foundation/governance/pmcs.html)
- [How Apache Works](https://www.apache.org/foundation/how-it-works.html)
on a biger scale ... where core Fastify Team Members could be seen as the PMC.
Hope this helps. Bye

**Comment by mcollina** [comment]
@smartiniOnGitHub this is on my list post 1.0.0.

**Comment by smartiniOnGitHub** [comment]
@mcollina great !! If I can help tell me (I have some experience at Apache :-) ).

**Comment by mcollina** [comment]
Given that I’ve not had the time in the last 6 months, I’d really love some help ;).

**Comment by jsumners** [comment]
At this point, I think anyone that can provide a fair proposal is going to get heard. I just don't have the time.

**Comment by smartiniOnGitHub** [comment]
Some more info:
Another important thing done at Apache is for PMC Members of a Project to be at least 3 (more welcome) with binding/veto vote when needed (like vote for releases or for important code modifications).
Then, to ensure real independence usually a good practice is to have a mixed list of members/contributors belonging to different companies ... but don't think it's a problem here.
For transparency, all discussions must be done in public contexts (usually mailing lists, I know this seems a little outdated :-) ), and the same for meetings and documentation: even reports every 3 months.
A clear (ever-evolving) RoadMap could help even to discuss more and attract more people.

Last, any contributor need to sign an ICLA (and similar for Companies, CCLA), as seen [here](https://www.apache.org/dev/new-committers-guide.html#becoming-a-committer), not sure with the PR model if it's good the same (probably yes).
For contributions (and for dependencies) the license must be compatible with the project license.
Probably a complex point to handle is meritocracy, like when someone is elected for write rights in a repo in this organization (the same for contributions on code, tests, documentation, participation in discussions/proposals, etc), and next step maybe even for the governance team ... and with formal/public/documented vote sessions maybe even this could be a little simpler: maybe a repo for saving all kind of puclic activity could be good (in a specific repo), for example look at a similar model adopted by the Scala Center, for example for Public Records, see [here](https://scala.epfl.ch/records.html) ... but of course all this is not for free, at least more time will be needed for this and usually technical people doesn't like so much but it's another story.

Hope you'll find these info useful; I'll be happy to give others if/when needed.

The [Node.js Governance](https://github.com/nodejs/node/blob/master/GOVERNANCE.md) model linked by Matteo seems very good, maybe something simpler could be good the same for now.

For continuing this discussion (and maybe all together work on a draft), what do you think on a wiki page in a repo here, or a dedicated channel in Gitter ?

Bye

**Comment by mcollina** [comment]
This is a great writeup.

I’m -1 to adding a CLA for the time being, but we might decide to enforce the DCO that we already have (there is a bot for that).

What is a PMC? This seems something similar to what we already have, minus one member. Would you mind writing something up?

Can you cover also new collaborators individuals that have mostly contributed to plugins of the org? I’d like to share the responsibility of those to a larger number of people, as there is a lot of traffic on them these days.

**Comment by smartiniOnGitHub** [comment]
Hi, the definition and duty of PMC is [here](http://www.apache.org/dev/pmc.html); in short it's the governance team of the project, with binding votes on releases (that here doesn't apply) and technical decision (like currently). In this case maybe here only we'd need at least another PMC Member (but could be even more, depinding on core contributors to the project).

At Apache external collaborators can contribute code but via patch files in attach to JIRA issues (where you accept the transfer/donation of code with the Apache License); then after some time and involvement (and knowledge) they can be invited to become a contributor (write access to the repo); then after the next level is to be invited to become a PMC Member (but for many people never, often because they don't want to be involved more), see [meritocracy](https://www.apache.org/foundation/how-it-works.html#meritocracy).

Another important thing to check is the commit policy and related model, for example look at [Commit-Then-Review](https://www.apache.org/foundation/glossary.html#CommitThenReview).
Last, if useful, a [Glossary](https://www.apache.org/foundation/glossary.html) of Apache Terms.

But maybe we could adopt some of these in a second step, to avoid too much bureocracy now.
Question: someone already tried to think if/how the project could converge to the Node.js Foundation ? Does it makes sense ?

On Plugins as a governance model maybe we could at least ask to use a License compatible to that of Fastify (and even dependencies); maybe an automatic check on this could help too.
From a technical point of view I think that on Plugins the only real problem in my experience is that with the big number of different combinations/usage that anyone can do, to have something that test many different combinations, or at least all core.

**Comment by mcollina** [comment]
> Hi, the definition and duty of PMC is here; in short it's the governance team of the project, with binding votes on releases (that here doesn't apply) and technical decision (like currently). In this case maybe here only we'd need at least another PMC Member (but could be even more, depinding on core contributors to the project).

This seems sound. I think we should have at least 3 members there to avoid tie breaks. @delvedor what do you think?

> But maybe we could adopt some of these in a second step, to avoid too much bureocracy now.
Question: someone already tried to think if/how the project could converge to the Node.js Foundation ? Does it makes sense ?

I do not think this will ever happen. This project should set up its own governance.

> On Plugins as a governance model maybe we could at least ask to use a License compatible to that of Fastify (and even dependencies); maybe an automatic check on this could help too.
From a technical point of view I think that on Plugins the only real problem in my experience is that with the big number of different combinations/usage that anyone can do, to have something that test many different combinations, or at least all core.

I think we should formalize what are the requirements for a core plugin. I see a business-friendly OSS license as a requirement (MIT, BSD, Apache 2).
My main concern is to guarantee that a bigger number of people can a) do releases b) do not break things. I see the plugins as a responsibility of all the people listed in the README, and those part in the organizations (minus generic components).

Would you like to send a PR that edits our https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md?

**Comment by smartiniOnGitHub** [comment]
Would you like to send a PR that edits our https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md?
@mcollina who is the "you" here ? maybe I know the anwswer, but just to be sure :-) ... anyway I'd be happy to help, I only need some time.

Sorry on the license compatibility on dependencies, this applies even for Fastify and its core plugin, but there is something already in place (as a tool or a service) or it would be better to so a manual review (could be good the same, at least for now) ? Should I add an issue for this ?

Last, at Apache every source file should must have as header the license (in the right format, depending on file type), what do you think on this ? And at least before any release we run a checker tool, [RAT](https://creadur.apache.org/rat/) to ensure all is good, and publish in the staging area its results; it requires Java to run but should work even with JavaScript sources (maybe there is something similar as a Node.js tool). Another issue ?

Let's update soon.

**Comment by mcollina** [comment]
I’m +1 if you want to help with this. Up to this point no one contributed in this regard, so if you think you can do some edits it would be good.

I think manual checking is ok. We should just document the process and the checks we do for adding a package to the org (official) or the ecosystem page. I think this is substantially different from the project governance of those modules too. Maybe we should spin off into its own discussion.

**Comment by mcollina** [comment]
@fastify what do you think?

**Comment by jsumners** [comment]
> Last, at Apache every source file should must have as header the license (in the right format, depending on file type), what do you think on this ?

Ugh, no.

I think my original posting on this issue still covers everything I would be concerned with. I don't think this needs quite as much bureaucracy as an Apache project. Just a clear outline of who can do what and why.

**Comment by cemremengu** [comment]
Is this discussion settled? Should we close it?

**Comment by smartiniOnGitHub** [comment]
Hi all, I tink the current status of the project and the community is good, and related documentation for contributing etc is clear; I'd expect more people involved in this but I know it's a not-so-easy discussion.
So unless objections I think it's good to close for now and maybe restart later ... but that's just my opinion. Bye

**Comment by mcollina** [comment]
I'm closing this. I think we should give some more thoughts to this, but we are currently very busy and the current system is working.
