### ISSUE TITLE
Support for multi part requests

### ISSUE THREAD

**Issue by GavinDmello** [fastify/fastify#63]

**Comment by mcollina** [comment]
Definitely. Should this be a plugin, or something in core?

**Comment by GavinDmello** [comment]
I'm not quite sure what's the standard approach people follow. I usually prefer the framework giving the request stream to me and I handle the multi part myself using whatever I want e.g Formidable.
But something out of box would be fine too

**Comment by mcollina** [comment]
We should bundle https://www.npmjs.com/package/multipart-read-stream in to help with this.

**Comment by delvedor** [comment]
Done in https://github.com/fastify/fastify-multipart

**Comment by GavinDmello** [comment]
Thanks @mcollina  @delvedor

**Comment by delvedor** [comment]
Thank you too for the suggestion!
Please, if you have more we'd love to hear them :)
