### ISSUE TITLE
Support HTTP/1.1 trailers

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#630]
as titled, I think `reply` might needs some facility to set trailers. It might also be a bad idea, as the actual response is always accessible and they could be set in that way if we want to.

**Comment by StarpTech** [comment]
@mcollina How common is it to use `trailing headers` ? Is it worth to pull it up to fastify? After some research, I found out that even Hapi, Koa2 has no support for this.

**Comment by mcollina** [comment]
I don’t think they are common, so maybe we can avoid them altogether. But it’s a discussion that’s worth having.

**Comment by jsumners** [comment]
I can confidently say that I have never used them. And I can _almost_ as confidently say I have never seen them used.

**Comment by jsumners** [comment]
@fastify/fastify anyone else have an opinion?

**Comment by nwoltman** [comment]
I've never used them, never seen them used, and I'm not sure if I'll ever need to use them.

**Comment by mcollina** [comment]
Closing for now, but we can revisit anytime!

**Comment by mattbishop** [comment]
It would be nice to offer semantic support for trailers. The handler has to specify the trailer keys in headers, then stream the response, then set the trailer header. Maybe something like this:

```js
reply.trailer("etag", async (reply, next) => { return calculatedEtagValue });
```

After the body stream is complete, the trailer callbacks would be executed and they would return their value to be stored in Node's http.response.addTrailers().

This may be better served as a plugin.

**Comment by mcollina** [comment]
I have a feeling this might only be served by implementing it in the framework. Anyway, would you like to work on this?

**Comment by mattbishop** [comment]
Maybe so. I can imagine the `Server-Timing` plugin would be interested in using it.

I'll hack at a plugin first to see how much effort it is.

**Comment by s9tpepper** [comment]
etags are the exact reason I ended up on this thread. I'm trying to send a file stream in reply.send() and I'm piping the stream to a hash so I can calculate an etag value that I want to send as a trailing header. @mattbishop did  you ever make any headway on this?

**Comment by climba03003** [comment]
I think it is not hard to make it success using `onSend` hook.

Generally speaking,
1. If you pass `object`, `string` in `payload`. It will be `string` in `onSend` hook and we can embed the `trailers` easily.
2. If you pass `buffer` in `payload`. It will be `buffer` in `OnSend`, it should be almost the same case as `1.`.
3. If you pass `stream` in `payload`. It will be `stream` in `OnSend` and we need to create a new `stream` for piping the original  stream and add the `trailers` at the end.

**Comment by MetCoder95** [comment]
Seems interesting, if ok I’ll give it a try during the weekend. I see this mostly in a form of a plugin. I’ll shake my head around it

**Comment by s9tpepper** [comment]
#3 is what I was trying but I was implementing in a route handler, so I moved it to an on send hook.
```javascript
const onSendHook = async (request, reply, payload) => {
  if (!reply.getHeader('etag') && typeof payload.pipe === 'function') {
    const hasher = new Stream(0xCACACAFE)
    const stream = payload.pipe(hasher)
    stream.on('finish', () => {
      const etag = hasher.read()
      console.log(`> etag is: ${etag}`)
      reply.raw.addTrailers({ etag })
      console.log('sent etag')
    })
  }
```
But it throws an error, I assume its because as soon as the stream sends the `finish` event the framework is calling `end()` and then I can't send anymore headers by the time the `finish` callback executes that I added to the stream object.

**Comment by climba03003** [comment]
Some prototype here, not tested.
I have read the above issue deeply and see it can make use of `response.addTrailers`. However, it cannot dynamic calculate the header when the payload is `stream`.

```js
const trailer = Symbol('reply.trailer');
fastify.decorateReply(trailer, null)
fastify.decorateReply('trailer', function(name, compute) {
  this[trailer].push({ name, compute })
})
// we initialize the trailer store
fastify.addHook('onRequest', function(request, reply, done) {
  reply[trailer] = []
  done()
})
// we add onSend hook to compute trailer
fastify.addHook('onSend', async function(request, reply, payload) {
  // if no trailers set in reply, we skip it
  if(reply[trailer].length) return payload
  const trailers = Object.create(null)
  // if payload is stream, as we cannot read the stream twice. Pass null to the callback
  const trailerPayload = typeof payload.pipe === 'function' ? null : payload
  for(const { name, compute } of reply[trailer]) {
    trailers[name] = await compute(request, reply, trailerPayload)
  }
  reply.raw.addTrailers(trailers)
  return payload
})
```

**Comment by s9tpepper** [comment]
Sorry, I spoke too soon. I left the old code in place and so the console output was wrong, you can see the output is actually missing the `>` character I have in the example code, my mistake. 

After I fixed that, the RTE went away, but the headers aren't sent.

```shell
> etag is: 3880014421
sent etag
```

But the headers aren't there:
```
< HTTP/1.1 200 OK
< content-type: text/html
< edge-cache-tag: develop
< cache-tag: develop
< xkey: develop
< Date: Thu, 24 Mar 2022 22:46:33 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
```
It's missing the `etag` header I'm trying to set.

**Comment by s9tpepper** [comment]
@climba03003 If I turn the onSend hook to an async function and then await on the calculation of the header value before I return the payload, doesn't that effectively block the response until the header is computed? Cause if so I could simply just calculate the header before even sending the response and add it via normal means.

But I'm trying to do it without blocking the response which is why I was trying to pipe the response stream into another stream object that hashes the contents. Then I was attaching a finish event handler to read the hash and add the value as a trailing header:

```javascript
const onSendHook = async (request, reply, payload) => {
  if (!reply.getHeader('etag') && typeof payload.pipe === 'function') {
    const hasher = new Stream(0xCACACAFE)
    const stream = payload.pipe(hasher)
    stream.on('finish', () => {
      const etag = hasher.read()
      console.log(`> etag is: ${etag}`)
      reply.raw.addTrailers({ etag })
      console.log('sent etag')
    })
  }
}
```

**Comment by climba03003** [comment]
> @climba03003 If I turn the onSend hook to an async function and then await on the calculation of the header value before I return the payload, doesn't that effectively block the response until the header is computed? Cause if so I could simply just calculate the header before even sending the response and add it via normal means.
> 
> But I'm trying to do it without blocking the response which is why I was trying to pipe the response stream into another stream object that hashes the contents. Then I was attaching a finish event handler to read the hash and add the value as a trailing header:
> 
> ```js
> const onSendHook = async (request, reply, payload) => {
>   if (!reply.getHeader('etag') && typeof payload.pipe === 'function') {
>     const hasher = new Stream(0xCACACAFE)
>     const stream = payload.pipe(hasher)
>     stream.on('finish', () => {
>       const etag = hasher.read()
>       console.log(`> etag is: ${etag}`)
>       reply.raw.addTrailers({ etag })
>       console.log('sent etag')
>     })
>   }
> }
> ```

Since, we are using `response.end(payload)` or `payload.pipe(response)` in the code.
You cannot send any `trailer` afterward. That's why it am awaiting the `trailers` before sending any.

https://github.com/fastify/fastify/blob/802e3e8935dd8a84e08330faca83b7f7a108dad2/lib/reply.js#L394-L433

If the order need to be correct, it needs to update the core for this feature.

**Comment by s9tpepper** [comment]
Yea it makes sense now. I was trying to do it in this order basically to try to incur as little cost to the response time by not awaiting a header value but still be able to calculate a deterministic etag header based on the file contents.

**Comment by kurtextrem** [comment]
short question: how would you generate an etag trailer for a stream using the "native" supported trailers now?
This might become more relevant in the ecosystem, since react now supports streaming.

However, I'm not sure if it even makes sense, since the stream is getting streamed to the client before the etag can be generated, so everything is already at the client when the client finds out the etag matches - so with streams there can't be any 304 responses? Did I miss anything?

**Comment by mcollina** [comment]
> However, I'm not sure if it even makes sense, since the stream is getting streamed to the client before the etag can be generated, so everything is already at the client when the client finds out the etag matches - so with streams there can't be any 304 responses? Did I miss anything?

No this is a good analysis. Streaming with React SSR can only be cached with a TTL, no etags.

As I said elsewhere, trailers are of limited utility.
