### ISSUE TITLE
Log level at plugin level

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#636]
Hi folks!

## The context

In my applications some routes are defined by plugins that are not under my control. Only to make some example:
- [point-of-view](https://github.com/fastify/point-of-view)
- [fastify-static](https://github.com/fastify/fastify-static)

Assuming I'm building a website like [fastify-example-twitter](https://github.com/fastify/fastify-example-twitter). The pages are served using the `fastify-static` plugin.

My JSON APIs are the core business but when a request arrives, a log line [was dropped](https://github.com/fastify/fastify/blob/629c16c9c9d09109a264f8868f7f0844907bb5a3/fastify.js#L175) with severity `info`. Always for every requests. Even for the static files.

The output is annoyed by the `html`, `css` and `js` files.

### `logLevel` key in plugin option:
```
fastify.register(require('fastify-static'), { ...., logLevel: 'fatal' })
```

I don't know if this way can be implementable because the Context is loaded after the lookup made by `find-my-way`.

Anyway this is the nicer feature.

### `childLogCreator` function as `fastify` option
```
const fastify = require('fastify')({
  logger: {
    level: 'trace',
    childLogCreator: function (req) {
      // this is the fastify instance
      const child = fastify.log.child({ reqId: req.id })
      if (/^\/static/.test(req.url) child.level('trace')
      return child
    }
  }
})
```

This can be done without any problem: the line https://github.com/fastify/fastify/blob/629c16c9c9d09109a264f8868f7f0844907bb5a3/fastify.js#L172 will change
 
cc @fastify/fastify

**Comment by delvedor** [comment]
This could be a nice thing to have.
With Pino you can change the log level at [any time](https://github.com/pinojs/pino/blob/master/docs/API.md#level). We can try to find a way to use this feature.

**Comment by jsumners** [comment]
I'm afraid I don't understand the problem. Are you saying the plugins are creating their own instance of the logger? They should be using `fastify.log` or `req.log`; this means logging only has to be configured once.

**Comment by jsumners** [comment]
I think this goes back to issue #304.

**Comment by allevo** [comment]
> I'm afraid I don't understand the problem. Are you saying the plugins are creating their own instance of the logger? They should be using fastify.log or req.log; this means logging only has to be configured once.

@jsumners the plugins don't create the own logger. The logger instance is always created by `fastify` [here](https://github.com/fastify/fastify/blob/629c16c9c9d09109a264f8868f7f0844907bb5a3/fastify.js#L172). Anyway in some circumstance you are interested to change the log level only for a sub path.

Just for example, in `fastify-example-static` I'd like to turn the incoming request and the response logs off for static files because for the business logic that paths are not important.

**Comment by mcollina** [comment]
I don’t think this will be possible, or possible with a decent level of performance.

**Comment by allevo** [comment]
@mcollina why are you concerned about a drop of performance ?

The second possibility suggests this change: 

`req.log = res.log = log.child({ reqId: req.id })` => `req.log = res.log = createLogger(log, req)`

with
```
function createLogger(log, req) {
  return log.child({ reqId: req.id })
}
```
on the top of `fastify.js` file

If you are ok, I try to make a PR with some benchmark

**Comment by mcollina** [comment]
That’s one of the worst hot paths in fastify, and I would prefer it to be left alone. Moreover, adding a regexp check in there is only causing more problems in the future: it is not the same logic that we are using for routing.

**Comment by mcollina** [comment]
I’m -1 withe the change

**Comment by allevo** [comment]
Understood.

But the problem is real. The health check url is another example.

Am I the only one that has this problem?  How can I avoid this kind of issue?

**Comment by mcollina** [comment]
I truly do not see this annoying to see the log lines.  In production you should serve those via nginx or something similar.

**Comment by jsumners** [comment]
I'm also having a difficult time seeing the issue. The referenced "incoming request" log line is useful information to determine when a request was started, and provides the identifier for examining the rest of the request.

**Comment by delvedor** [comment]
I've implemented this feature to see how the performances changes.
Unfortunately we lose 10% req/sec if we try to set dynamically the log level. (around 2-3k)
Which is too much.

If you come up with *at least same performances*method I'm all hears! :)

**Comment by delvedor** [comment]
Me and @mcollina had an idea, I'll open a pr very soon ;)

**Comment by PavelPolyakov** [comment]
Hello,

I've also met the issue when the health check route is spamming the logs.
I see the PR from @delvedor, good that we have it merged, but first I thought that this `logLevel` will actually set the log level of the route log. Like if I set `{logLevel:'health'}` (my custom log level) than it will log all requests as `health`.

But it appeared that the `logLevel` is min log level for this particular route. Which is not bad as well.

Does anybody else think that there should be an option to influence the actual level of the message for the routes request itself, PER route?

**Comment by delvedor** [comment]
@PavelPolyakov if you pass `logLevel` as route option you will get the specific log level PER route, it is documented [here](https://github.com/fastify/fastify/blob/master/docs/Routes.md#full-declaration) :)

**Comment by PavelPolyakov** [comment]
@delvedor you are right. But what I meant was a little bit different, like force logger to use certain level and log `on request` and `on response` logs using that certain level. 

But at the end I think current functionality should be enough.
