### ISSUE TITLE
browserify + sheetify plugin

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#64]
We can base ourselves on https://github.com/yoshuawuyts/bankai, or we can get inspired and write our own thing.

**Comment by delvedor** [comment]
@yoshuawuyts already did an awesome job on bankai, I use it basically every day. I think that a plugin for use fastify and bankai together is definitely enough.
Maybe in the future we can think something different, but for the moment I don't see the need to reinvent the wheel :)

**Comment by delvedor** [comment]
https://github.com/fastify/fastify-pigeon
