### ISSUE TITLE
Split `addHook` method

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#644]
Hi folks!
  I don't like to mix the "request handling" hooks with fastify instance ones: I like to have two different method on fastify for splitting logically the hooks too.

### Proposal:

with `addHook`:
- onRequest
- preHandler
- onResponse
- onSend

with `addFastifyLifecycleHook`:
- onRoute
- onClose

thoughts @fastify/fastify ?

*NB:* I'm good at choosing names

**Comment by StarpTech** [comment]
What do you think about to be more concrete with the names?

`onRouteAdd`
`onServerClose`

IMO the other hooks point out that they extend the request-cycle.

- onRequest
- preHandler
- onResponse
- onSend

**Comment by nwoltman** [comment]
I like the idea of keeping the other hooks separate from the request handling hooks, although I'm not sure that `addFastifyLifecycleHook` is the best name because "lifecycle" makes me think of the [request lifecyle](https://www.fastify.io/docs/latest/Lifecycle/).

**Comment by jsumners** [comment]
Very much like the idea. Would `addProcessHook` fit better?

**Comment by mcollina** [comment]
I don't like the new name, and I have no good idea, let's keep bikeshedding. I have no opinion on separating them or not. I'd like to keep a "small API surface" on Fastify itself, but those are truly two separate concerns.

Given we have `fastify.onClose()`, can we add `fastify.onRoute()` and be done with it? If we want to add new methods, this might be simpler to understand. This is in contrast to what I just said of keeping a small API surface, but it's another idea to keep in mind.

**Comment by allevo** [comment]
I'll fire a PR this evening for continuing the discuss

**Comment by StarpTech** [comment]
@allevo after my PR ? 😄

**Comment by allevo** [comment]
@StarpTech yeah, you are right. Sorry man, I'm too tired

**Comment by StarpTech** [comment]
Same here GMT +1 😃

**Comment by delvedor** [comment]
Personally I prefer to leave the api as is.
We are always talking about hooks, the documentation should be enough to explain to the users where and why the hooks are executed.

**Comment by allevo** [comment]
I'm closing this issue.

> We are always talking about hooks, the documentation should be enough to explain to the users where and why the hooks are executed.

After this comment, I'm convinced.
