### ISSUE TITLE
Force to break the encapsulation

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#657]
Hi!
yeah, the title is very bad.

## The context
I've to create an a simple HTTP API. That API should make a query to mongo with a specific logic and return the result.
In order to split the bootstrapping, the HTTP layer and the business logic:
Business logic:
```js
async function decorateWithTheInstance (fastify) {
  fastify.decorate('myBusinessLogicClassInstance', new MyBusinessLogicClass(fastify.mongo.db))
}
async function createMyBusinessLogicClass (fastify) {
  fastify.register(require('fastify-mongodb'), { url: 'mongodb://localhost/mydb' })
    .register(fp(decorateWithTheInstance))
}
```

HTTP layer
```js
function doStuffHandler () {
  return this.myBusinessLogicClassInstance.dosStuff()
}
async function httpLayer (fastify) {
  fastify.get('/doStuff', doStuffHandler)
}
```

Bootstrapping
```js
fastify.register(fp(createMyBusinessLogicClass))
  .register(httpLayer)
```
With this configuration, we have split the business logic from the network layer.

An example is `fastify-example-twitter`

## The problem

In the network layer the mongodb connection is set because `createMyBusinessLogicClass` is registered with `fp` and internally `fastify-mongodb` does the same.
The "chain" of `fp` makes every decoration "public" in all plugins in the chain.
Which configuration allow us to "export" only `myBusinessLogicClassInstance`?

Thoughts?

Related discussion: https://github.com/fastify/fastify/issues/336
cc @StarpTech

**Comment by mcollina** [comment]
Here is the problem MyBusinessLogicClassInstance should not exists.
Divinding your application into horizontal layers do not scale in complexity. Having singleton services do not scale in complexity. 

You should split your applications into vertical layers, by features. Put everything in modules, and instatiate them in your plugins. You can even decide to split one of your plugins and run it independently then. Do not build a monolith.

**Comment by allevo** [comment]
> Here is the problem MyBusinessLogicClassInstance should not exists.

Are you suggesting to avoid the class usage at all preferring single functions?

Like:
```js
async function decorateWithFunctions (fastify) {
  fastify.decorate('doStuff', myDoStuffFunction.bind({ db: fastify.mongo.db }))
}
async function createMyBusinessLogicFunctions (fastify) {
  fastify.register(require('fastify-mongodb'), { url: 'mongodb://localhost/mydb' })
    .register(fp(decorateWithFunctions))
}
```

```js
function doStuffHandler (request) {
  return this.dosStuff(request.body)
}
async function httpLayer (fastify) {
  fastify.get('/doStuff', doStuffHandler)
}
```

```js
fastify.register(fp(createMyBusinessLogicFunctions))
  .register(httpLayer)
```

repeating the last code lines for each modules?

**Comment by mcollina** [comment]
I mean to not (never) expose business logic as singletons within fastify. Re-instantiate things if needed, fastify is for web routes.

**Comment by allevo** [comment]
```js
function doStuffHandler () {
  return this.myBusinessLogicClassInstance.dosStuff()
}
async function addDoStuff (fastify) {
  fastify.decorate('myBusinessClassInstance', new MyBusinessClass(fastify.mongo.db))

  fastify.get('/doStuff', doStuffHandler)
}

fastify.register(require('fastify-mongodb'), { url: 'mongodb://localhost/mydb' })
  .register(addDoStuff) // without fp
```

Better?

**Comment by jsumners** [comment]
I think so, yes.

**Comment by allevo** [comment]
Nice!
thanks @mcollina and @jsumners .
I'll update the `fastify-example-twetter` a soon as possible.
