### ISSUE TITLE
What about including req in all logs (instead of only reqId)

### ISSUE THREAD

**Issue by jeromemacias** [fastify/fastify#659]
This is just a question but why don't you include the complete request in all logs instead of only `reqId` ?

I try to get better logs as possible using Sentry as tracking software (Pino specific logger will be publish as soon as possible).

On error logs, if I don't have the request and my log level is set on `error`, It's impossible to get any request details (if I'm not wrong ?)

We can replace `reqId: req.id` by `req: req` on this line: https://github.com/fastify/fastify/blob/cf0c32705f45325482f6f8f00dd412aaa82c0028/fastify.js#L177

I'm very grateful for all your works, really appreciate it!

**Comment by jsumners** [comment]
You really just need a `req.log.info(req)` somewhere in your request path. It's a lot of information to log by default. It should be left up to the author of an app to log the whole request if that is what they desire.

**Comment by mcollina** [comment]
That has been removed from performance reason. What we might do is including the full response only for errors.

**Comment by jeromemacias** [comment]
You’re right, req is not needed for every log.

But, is there a way to add request object only for errors ? As the error handler only receive `res` and I did’nt find any way to override this handler (

**Comment by mcollina** [comment]
there is an handleError function in the reply.js file. Add it there.

**Comment by jeromemacias** [comment]
Sorry, but I didn't found a way to add `req` to the logger before error was sent as the `customErrorHandler` in the `handleError` is called after and there is no other hook.

The only way I found for the moment is to to add req into the logger in the `onRequest` hook (which seems ok in my case, I want to only send error logs).

**Comment by mcollina** [comment]
I mean that we should change fastify to support this.

**Comment by jeromemacias** [comment]
What I do actually is redirect all logs into std out, as it's, IMO, the philosophy of Fastify / Pino, and send logs to Sentry (I'm working on a `pino-raven` which works like `pino-socket` for example) so I really want to rely on framework logs as much as I can.
