### ISSUE TITLE
accept headers parsing

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#66]
as titled

**Comment by delvedor** [comment]
How do we want to implement this?
Having the field `headers` directly into the `request` object instead of `request.req` could be useful?

**Comment by mcollina** [comment]
I think we need to add a bunch of methods to `Request`, maybe based on https://www.npmjs.com/package/accepts.

Should we do this on a plugin?

**Comment by delvedor** [comment]
That would be perfect. I think a plugin is better, so if a user do not need it, will not pay that cost.

**Comment by allevo** [comment]
Maybe a getter on Request object can be an help

**Comment by mcollina** [comment]
yes. Do you want to create the plugin @allevo?

**Comment by allevo** [comment]
yea, but the nightmare is on the serialization.

The another solution could be to implement it in fastify to be described in routes definition.
Like: 
```
fastify.route({
  method: 'GET',
  url: '/',
  schema: { ... },
  beforeHandler: function (request, reply, done) { ... },
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  },
  accepts: ['application/json', 'text/html'],
})
```

**Comment by mcollina** [comment]
No, I prefer this to be handled all in code. You'll need code there anyway.

why the nightmare is on the serialization? what do you mean?

**Comment by allevo** [comment]
For example:

```
fastify.get('/foobar', (req, res) => {
   switch(req.accept.type(['json', 'html'])) {
    case 'json':
      // handle json response
      break
    case 'html':
      // handle html response
      break
    default:
      // the fallback is text/plain, so no need to specify it above
      // handle plain response
      break
  }
  // 406
})
```
can be tricky (or not?)
For example the 406 response can be forgotten.

Another approach can be:
```
fastify.get('/foobar', (req, res) => {
  res.render({ });
})

fastify.decorateReply('render', (obj) => {
   // assuming this == res
  
   switch(res.req.accept.type(['json', 'html'])) { //  <-----  ugly access to req obj HERE
    case 'json':
      // handle json response
      this.json(obj) // NB: this reuses the serialization implemented in fastify
      break
    case 'html':
      // handle html response
      this.type('html')
      this.res.end('<html>' + JSON.stringify(obj) + '</html>')
      break
    default:
      // the fallback is text/plain, so no need to specify it above
      // handle plain response
      break
  }
  // 406
})
```
where the reply decoration is made into a plugin.

The second way allows us to split the request handler from the response serialization.

**Comment by mcollina** [comment]
That approach would not work in practice, because you would have to customize both the HTML and other types. So, maybe we can build a general mechanism on top of this to provide that functionality, but let's start simple and add the `accept()` part to the `Request`.

**Comment by delvedor** [comment]
Let's consider that swagger uses the `accepts` field, so could be nice find a way to set it in a way that another plugin can see that rule.

@allevo if you need a good example on how decorate the `Request` object check out [fastify-multipart](https://github.com/fastify/fastify-multipart).

**Comment by allevo** [comment]
`fastify/fastify-accepts` or `allevo/fastify-accepts` ????

**Comment by mcollina** [comment]
I would recommend fastify/fastify-accepts.

**Comment by allevo** [comment]
https://github.com/fastify/fastify-accepts

**Comment by allevo** [comment]
The PR was already merged https://github.com/fastify/fastify/pull/144

If there are other things, I'd prefer move the conversation to [fastify-accepts](https://github.com/fastify/fastify-accepts)
