### ISSUE TITLE
Add `api change` label for PRs modifying the public api

### ISSUE THREAD

**Issue by NoNameProvided** [fastify/fastify#666]
The title says it mostly, as it seems in #649 that typings will stay, can you guys add a label saying `API change` (or something like that)?

If this label is added to the PRs (for every public api change) it would make it easier to check on which PR-s need attention from the ones who maintain typedefs. Without these, every change must be read to see if it requires a change in typedef or not.

I think this is a good balance between helping both sides, as the core contributors don't need to know how to write typings, and typedef maintainers don't need to read every commit.

**Comment by jsumners** [comment]
While the vote on #649 is not completed, I don't see a reason this label shouldn't exist. I have created it.

**Comment by NoNameProvided** [comment]
Thanks, should be it added to the PR template as a checklist item? 

```
Added the `api change` label if public API has been changed
```

**Comment by delvedor** [comment]
@jsumners I think the `breaking change` api is enough.

**Comment by jsumners** [comment]
Okay.

**Comment by NoNameProvided** [comment]
> I think the breaking change api is enough.

No, that's not enough if I understand you correctly. When you add a new parameter to a function or add a new option to a config object it won't be a breaking change, but the typing still needs to be updated.

**Comment by jtlapp** [comment]
I agree that "breaking change" isn't quite what we need to signal a change in the typings.

The typings are a definition of the public interface. The typings change whenever the public interface changes, even when the change is backward-compatible.

**Comment by mcollina** [comment]
I think we should remove the breaking-api label, and adopt semver-* labels. Anything above patch, would need to be reviewed. I think that’s simple enough and it will help with generic maintenance.

**Comment by jtlapp** [comment]
There you go, and if you can't get a Typescript dev to commit to reviewing each bump in minor version prior to publication, drop the typings.

**Comment by mcollina** [comment]
Would you commit to it @jtlapp?

**Comment by delvedor** [comment]
I agree with @mcollina. We will keep the `breaking change` label until version 1. Then we will use `semver-*`.

**Comment by jtlapp** [comment]
>Would you commit to it @jtlapp?

Happily, but right now I'm evaluating whether or not to build on Fastify. I won't even able to start looking at it in earnest until later this week. If I'm still around in a few weeks you can count on me to do it. I just can't commit to doing it before I've definitively committed my project to Fastify.

(I only just started prowling around here to evaluate Fastify. For some reason, Fastify never landed on my original list of frameworks to investigate, which I put together about two months ago. I only just happened across it searching reddit for koa/typescript/ajv solutions. And it looks like hapi.js with an emphasis on performance -- exactly what I was hoping for! But too soon to be sure.)

**Comment by jtlapp** [comment]
But I can offer this now: I'll submit the PRs I need to get the typings working, should they be out of sync.

I just can't make a commitment to do this on an ongoing basis yet.
