### ISSUE TITLE
Proposal: Run onSend hooks after serialization

### ISSUE THREAD

**Issue by nwoltman** [fastify/fastify#672]
I was recently about to write an `onSend` hook in my application when I realized that my hook would need the serialized payload to work properly. I checked out [`fastify-compress`](https://github.com/fastify/fastify-compress) to see how it handles this problem and found that it [serializes the payload itself](https://github.com/fastify/fastify-compress/blob/671d3731d1e32f5572d52abf1413107850a19fc4/index.js#L103-L105) using `reply.serialize()` if it is not already a stream or string. Unfortunately, that particular solution isn't complete because to be fully compatible with the current version of Fastify it would need to duplicate most of [Fastify's serialization code](https://github.com/fastify/fastify/blob/c76e366b1d1dc4b10ceb679e0a25cf6bc19bb814/lib/reply.js#L140-L159).

This means that any `onSend` hook that needs the serialized payload would also need to duplicate Fastify's serialization code, or alternatively, require users to serialize the payload and set the right headers themselves before calling `reply.send()`. It doesn't seem right to put that burden on developers.

Additionally, the documentation for [Hooks](https://github.com/fastify/fastify/blob/c76e366b1d1dc4b10ceb679e0a25cf6bc19bb814/docs/Hooks.md) currently includes the following information:

> If you are using the onSend hook you can update the payload, for example:

```js
fastify.addHook('onSend', (request, reply, payload, next) => {
  var err = null;
  payload.hello = 'world'
  next(err, payload)
})
```

Updating the payload in this way does not seem very useful and could actually be considered bad practice. If anyone needs to modify a payload in that way, they could use a custom serializer or set a response schema to be used by `fast-json-stringify`.

With this information in mind, I'd like to propose that the order of serialization and `onSend` hooks be switched so that serialization happens before running the hooks. With this format, `onSend` hooks will receive the serialized payload—which can still be modified just like it can be now. This will also allow the `onSend` hooks to see the right `Content-Type` header (which is set when the payload is serialized).

**Comment by delvedor** [comment]
We have discussed about this in https://github.com/fastify/fastify/pull/330 and https://github.com/fastify/fastify/pull/447, at the end we have decided to allow payload changes inside the `onSend` hook.

**Comment by mcollina** [comment]
It seemed a good idea at the time, but maybe we were wrong. Are there any other opinions?

An alternative option could be to expose the current serializer as `reply.serializer`, and leverage that during compression.

**Comment by delvedor** [comment]
While we can discuss if upload the payload could be useful or not you are right about
> I checked out fastify-compress to see how it handles this problem and found that it serializes the payload itself using reply.serialize() if it is not already a stream or string. Unfortunately, that particular solution isn't complete because to be fully compatible with the current version of Fastify it would need to duplicate most of Fastify's serialization code.

We should find a solution about this.

**Comment by nwoltman** [comment]
I have read through #330 and #447 and I didn't find any strong reasons for being able to change the unserialized payload. If anyone does have a good use case for modifying an unserialized payload though, then I would rethink my stance on this proposal.

@delvedor Has a good [point](https://github.com/fastify/fastify/pull/330#issuecomment-334081794) in #330 about how modifying the unserialized payload in an `onSend` hook can cause problems:

> if the user is using `fast-json-stringify` the `onSend` could change the payload in unexpected ways, causing lot headaches.

As of right now, here are the main use cases I see for the `onSend` hook:

1. Saving application state (i.e. sessions)
2. Setting extra headers before the response is sent
  • This sometimes requires the serialized payload (i.e. to generate an ETag header)
3. Changing the format of the payload (i.e. turning it into a stream)
  • This should include clearing the payload to send an empty body if the hook decides that a `304 - Not Modified` response should be sent, but there are complications with this if serialization happens during or after the hooks

Notice how case 1 doesn't care about the payload, case 2 sometimes requires the serialized payload, and  case 3 always requires the serialized payload.

@mcollina's Idea of exposing the serialization logic through `reply.serializer` could work, although I think this could make things a little more complicated and a bit of performance may be lost because:

+ Hooks that need the serialized payload will always need to call the `reply.serializer` logic
  + Reason: If the hook is passed a string as the payload, it won't know if it's the serialized payload or a string that still needs to be serialized (JSON string)
+ `onSend` hooks that serialize the payload will need to remember to call `next(null, serializedPayload)` or else the payload will need to be serialized again later on
+ The full type-checking/serialization logic will always need to be run after the `onSend` hooks because the payload may or may not have been serialized during the hooks
  + (If serialization happened before the hooks, the code after the hooks would only need to make sure the payload is the right type to send)
+ Some of this could be avoided with an `alreadySerialized` flag, but flags usually make code more difficult to maintain
  + It probably isn't even possible to have a flag like this because if the `reply.serializer` logic is a public API, users will expect to be able to call it whenever they want even if it's already been called to serialize the payload

**Comment by nwoltman** [comment]
Sure thing 👍
