### ISSUE TITLE
End request in async preHandler

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#677]
Let's assume you have a plugin that supplies a `preHandler` hook. This plugin does some validation of incoming requests and returns an error response (401) if the request fails validation and terminates the request chain. With the traditional interface this looks like:

```js
fastify.addHook('preHandler', function (req, reply, next) {
  if (req.headers['foo'] === foo) return next()
  req.code(401).send({error: 'nope'})
  return
})
```

But what do we do if the hook is an `async` function?

```js
fastify.addHook('preHandler', async function (req, reply) {
  if (req.headers['foo'] === foo) return
  req.code(401).send({error: 'nope'})
  return
})
```

In this case we will get an error informing us that the reply has already been sent because 1. it has and 2. the request continues as if the hook didn't encounter an error *despite* `undefined` being returned. So let's modify it to satisfy the error check:

```js
fastify.addHook('preHandler', async function (req, reply) {
  if (req.headers['foo'] === foo) return
  req.code(401).send({error: 'nope'})
  return Error('make fastify realize an error occurred')
})
```

Oops, we have a new problem. In this case we are creating an unhandled rejection. 

It seems to me that there is no way to properly terminate a request at the `preHandler` step when using an `async` hook. I think there needs to be a way to do it to be consistent with the traditional interface.

Maybe `async` hooks can look for specific return values to determine what to do? For example, maybe this would terminate the request correctly?:

```js
fastify.addHook('preHandler', async function (req, reply) {
  if (req.headers['foo'] === foo) return
  req.code(401).send({error: 'nope'})
  return fastify.TERM_REQ
})
```

#### Context

* *node version*: 8
* *fastify version*: 0.39.1
* *os*: Mac

**Comment by nwoltman** [comment]
A possible solution would be:

```js
fastify.addHook('preHandler', async function (req, reply) {
  if (req.headers['foo'] === foo) return
  reply.code(401)
  return new Error('nope')
})
```

Unless you're trying to avoid running the [error handling code](https://github.com/fastify/fastify/blob/4d6e827347e633a24aeeb316ea60ae17bfd798a5/lib/reply.js#L180-L235).

**Comment by mcollina** [comment]
IMHO I think that we should stop processing `preHandler` hooks if `reply.send()` gets called, i.e. if `reply.sent` is `true`. I think this a bug.

**Comment by nwoltman** [comment]
It looks like @mcollina's suggestion would be as simple as adding a `reply.sent` check between these two lines:
https://github.com/fastify/fastify/blob/fd1b24550bec63c1167a277a1e65be5439773b4e/lib/handleRequest.js#L151-L152

**Comment by delvedor** [comment]
> IMHO I think that we should stop processing preHandler hooks if reply.send() gets called, i.e. if reply.sent is true. I think this a bug.

Agree, should we do the same for `onRequest` and middlewares?

**Comment by mcollina** [comment]
I _think_ so.

**Comment by jsumners** [comment]
Would someone more familiar with the inner working of the lifecycle than me like to take this on?

**Comment by delvedor** [comment]
I'm working on this :)
