### ISSUE TITLE
support for custom content types in POST/..

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#68]
we need a generic support for content types

**Comment by delvedor** [comment]
We want this in core or as a plugin?
Same question for #66.

**Comment by mcollina** [comment]
Some work needs to happen in core for this: https://github.com/fastify/fastify/blob/master/lib/tier-node.js#L38-L59.

#66 might be a plugin.

**Comment by delvedor** [comment]
If we want this as plugin I guess we must expose the parsing part.

**Comment by delvedor** [comment]
Done in #72
