### ISSUE TITLE
regex matched routes

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/fastify#684]
In the documentation it's stated that it's possible to declare routes like this:
```javascript
fastify.get('/example/at/:hour(^\\d{2})h:minute(^\\d{2})m', (req, reply) => {}))
```

I tried, the one from the example but was not able to match it. Always 404. I started to look for example and found that `find-my-way` router is used. In the documentation of which the same route is used, BUT in the tests the regex is slightly different:
https://github.com/delvedor/find-my-way/blob/master/test/issue-17.test.js

```javascript
findMyWay.on('GET', '/at/:hour(^\\d+)h:minute(^\\d+)m', (req, res, params) => {
    t.equal(params.hour, '0')
    t.equal(params.minute, '42')
  })

  findMyWay.lookup({ method: 'GET', url: '/at/0h42m' }, null)
```

So I put it together into the simple fastify server:
```javascript
const fastify = require("fastify")();

fastify.get("/hello", async (req, reply) => ({
    hello: true
}));
fastify.get("/example/at/:hour(^\\d+)h", (req, reply) => ({
    hour: req.params.hour
}));

const start = async () => {
    try {
        await fastify.listen(3000);
        console.log(`server listening on ${fastify.server.address().port}`);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

start();
```

#### What was the result you received?
Whenever I call http://localhost:3000/example/at/22h - it just continues to load, I don't think routing is working.
http://localhost:3000/hello works perfectly

#### What did you expect?
I expect that `hour` param will be parsed from the url and returned in the object.
As a bonus - I think it'll be good to provide examples for the routes in the documentation.

#### Context

* *node version*: v8.9.3
* *fastify version*: 0.39.1
* *os*: Mac

**Comment by nwoltman** [comment]
Hey @PavelPolyakov! Thanks for using Fastify.
In the simple server you put together, the route matching is actually working properly, but you wrote your handler as if it were an async handler but didn't add the `async` keyword to the function. This would work:

```js
fastify.get("/example/at/:hour(^\\d+)h", async (request, reply) => ({
    hour: request.params.hour
}));
```

When you're handler isn't `async`, you need to use `reply.send()`.

```js
fastify.get("/example/at/:hour(^\\d+)h", (request, reply) => {
    reply.send({hour: request.params.hour});
});
```

As for the example from the documentation:

```js
fastify.get('/example/at/:hour(^\\d{2})h:minute(^\\d{2})m', (request, reply) => {}))
```

The regex contains `\\d{2}` which means that it will only match if the URL has 2 digits before the `h` and the `m`, so `/example/at/00h42m` will match but `/example/at/0h42` will not.

**Comment by PavelPolyakov** [comment]
@nwoltman 
you are right, missing `async` did the mess. Everything is working as expected.

Thanks for the help! 👍
