### ISSUE TITLE
Plugin needs to know its full path

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#686]
Sometimes a plugin needs to be able to compose the full URL to the handlers it defines. For example, when working with SAML you must tell the remote IdP the callback URL to use when it POSTs back to you. If the SAML communication is implemented in a plugin, then that plugin could be mounted with a prefix that is itself under another prefix. But the plugin only has access to its *immediate* prefix. Example:

https://github.com/fastify/fastify/blob/4a5cd18e5bda435548370623034c7cedeafcf55b/test/route-prefix.test.js#L20-L25

On the line where the route gets registered the following is true:

1. `opts.prefix` is set to `/v2`
1. `fastify._routePrefix` is set to `/v1/v2`

So let's use the public API:

```js
fastify.register(function (instance, opts, next) {
  instance.register(function (instance, opts, next) {
    instance.get('/foo', function (req, reply) {
      const address = instance.server.address()
      // next line is returning the wrong result
      reply.send( `url = ${address.addres}:${address.port}${opts.prefix}` )
    })
    
    next()
  }, {prefix: '/v2'})
  
  next()
}, {prefix: '/v1'})
```

I propose that the `instance` should expose a public property that provides the full path, e.g.:

```js
fastify.register(function (instance, opts, next) {
  // 'basePath: /v1'
  instance.log.debug('basePath: %s', instance.basePath)

  instance.register(function (instance, opts, next) {
    // 'basePath: /v1/v2'
    instance.log.debug('basePath: %s', instance.basePath)

    next()
  }, {prefix: '/v2'})

  next()
}, {prefix: '/v1'})
```

**Comment by allevo** [comment]
:+1:
