### ISSUE TITLE
querystring schema-shortcut does not work

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#694]
Behaviour is documented [here](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#validation)

Calling `/?hello=foo` Returns `200` with `{"hello":"world"}`
```js
const querySchema = {
  querystring: {
    hello: { type: 'number' }
  }
}

fastify
  .get('/', querySchema, function (req, reply) {
    console.log(req.query)
    reply
      .send({ hello: 'world' })
  })
```
Calling `/?hello=foo` Returns `400` with `{"statusCode":400,"error":"Bad Request","message":"[{\"keyword\":\"type\",\"dataPath\":\".hello\",\"schemaPath\":\"#/properties/hello/type\",\"params\":{\"type\":\"integer\"},\"message\":\"should be integer\"}]"}`
```js
const querySchema = {
  schema: {
    querystring: {
      type: 'object',
      properties: {
        hello: {
          type: 'integer'
        }
      }
    }
  }
}

fastify
  .get('/', querySchema, function (req, reply) {
    console.log(req.query)
    reply
      .send({ hello: 'world' })
  })
```

**Comment by allevo** [comment]
What do you expect?

**Comment by StarpTech** [comment]
The same behavior with the full schema description. 

I expect that both returns `400` with the schema error payload.

**Comment by mcollina** [comment]
Would you mind firing a PR to fix this?

**Comment by StarpTech** [comment]
Sure

**Comment by allevo** [comment]
I don't understand: the first example define `hello` as a string; the second one as an `integer`

**Comment by StarpTech** [comment]
This was a typo the issue is the same.

**Comment by StarpTech** [comment]
This is not a bug it's badly documented. We have to wrap it inside `schema` property.

**Comment by StarpTech** [comment]
I will create a PR to improve the examples.

**Comment by StarpTech** [comment]
https://github.com/fastify/fastify/pull/695
