### ISSUE TITLE
Inconsistency between registering hooks and middleware inside a plugin

### ISSUE THREAD

**Issue by nwoltman** [fastify/fastify#696]
#### Steps to reproduce

```js
const fastifyPlugin = require('fastify-plugin')
const fastify = require('fastify')()

fastify.get('/', (request, reply) => {
  console.log('handler')
  reply.send('OK')
})

fastify.register(fastifyPlugin((fastify, options, next) => {

  fastify.addHook('onRequest', (req, res, next) => {
    console.log('onRequest', req.url)
    next()
  })

  fastify.use((req, res, next) => {
    console.log('middleware', req.url)
    next()
  })

  next()
}))

fastify.listen(8080, (err) => {
  if (err) throw err
  console.log('Server listening')
})
```

#### What was the result you received?

Start the server and navigate to `http://localhost:80/`. You'll see this in your console:

```
$ node index.js
Server listening
middleware /
handler
```

#### What did you expect?

Either both the hook and the middleware should run or neither should run.

I can open a PR to make it so that middleware are added to routes the same way that hooks are (so that in this example the middleware won't run). I just want to make sure that's the expected functionality. It's a little unclear what should happen because if you add both the hook and the middleware after the handler outside of a plugin:

```js
fastify.get('/', (request, reply) => {
  reply.send('OK')
})

fastify.addHook('onRequest', (req, res, next) => {
  console.log('onRequest', req.url)
  next()
})

fastify.use((req, res, next) => {
  console.log('middleware', req.url)
  next()
})
```

then both will run.

```
Server listening
onRequest /
middleware /
handler
```

**Comment by allevo** [comment]
This is a bug. Please fire a PR!

**Comment by delvedor** [comment]
Probably there is an issue in the encapsulation model here
https://github.com/fastify/fastify/blob/500ad8ff391ab2e59145bcc6cb313c057a47c7c3/fastify.js#L312-L340

The weird thing is that all these test are not failing:
https://github.com/fastify/fastify/blob/500ad8ff391ab2e59145bcc6cb313c057a47c7c3/test/middleware.test.js#L153-L188

**Comment by nwoltman** [comment]
@delvedor Those tests are passing because they're not using `fastify-plugin` and they register the middleware _before_ the handler.
