### ISSUE TITLE
Feature: toString method

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#703]
As discussed in #702 could be a nice feature expose a `toString` method.
It should print the routes, the decorators/hooks/middlewares for every encapsulation level as well as custom error handlers and not found handlers.

I think it could be an amazing feature, extremely useful for debugging and see the "size" and complexity of your application visually.
@fastify/fastify what do you think?

Example:
```
 Hooks: [authHook, compressHook]
├── /
│
├── test (GET)
│   │    Plugins: [cookie-plugin]
│   └── /hello (GET)
│
│   Plugins: [point-of-view, fastify-postgres]
│   Custom handlers: [500handler]
└── hello/world (GET)
```

Thanks to the `onRoute` hook I think it could even be a plugin.

**Comment by jsumners** [comment]
Also mentioned was adding a custom `util.inspect` method. So might as well round off the set and add https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag.

I'd really like to see `.toJSON` added at the same time. While the described `.toString` behavior would be fine for debug purposes, I can guarantee you that someone will end up using it in production. Therefore, providing a mechanism to accomplish the same thing for production logging would head off some issues.

**Comment by PavelPolyakov** [comment]
+1 for `.toJSON`, I expect it to be more useful for developers.

**Comment by Ethan-Arrowood** [comment]
I like this idea and interested in working on it.

**Comment by mcollina** [comment]
Fantastic!

**Comment by Ethan-Arrowood** [comment]
What are the properties that need to be printed? Should this be its own plugin or can I add this to fastify core?

**Comment by mcollina** [comment]
I think it would be good to have it in fastify itself, because we are likely not keeping track of all the info atm.

We should print:

1. plugins
2. hooks registered for every lifecycle phase
3. routes
4. middlewares (ideally)

**Comment by Ethan-Arrowood** [comment]
Spent some time on this today. Not complete yet but I think its a good start. Check out my notes on the PR for more details and maybe we can continue the implementation discussion over there.

**Comment by Ethan-Arrowood** [comment]
Hello, in spirit of the upcoming JS Interactive conference and hacktoberfest i'd like to try and finish what I started here. Can someone bring me up to speed on current expectations for this feature? 

#861 is very much behind master (100 something commits). Is it worth trying to rebase that branch, or should I start a new one and cherry pick any relevant commits over?

**Comment by cemremengu** [comment]
Hello! I think rebasing looks fine and will save you some time. Only `package.json` is in conflict. Try and see if it works.

For expectations, others will know better :)

**Comment by Ethan-Arrowood** [comment]
Good point @cemremengu 😄

**Comment by delvedor** [comment]
I'm not 100% convinced about this feature, IMHO it falls in the "nice to have but a nightmare to maintain" section.

@fastify/fastify thoughts?

**Comment by Ethan-Arrowood** [comment]
@delvedor mentioned using `node-archy` to revamp how `find-my-way` pretty prints routes. Maybe that would be a more worthwhile contribution?

**Comment by delvedor** [comment]
@Ethan-Arrowood `find-my-way` internals will probably change a lot in the future.
I'm not sure if supporting `prettyPrint` will be feasible.

**Comment by jsumners** [comment]
I really prefer having a JSON representation that I can format any way I desire.

**Comment by nwoltman** [comment]
Having a `toJSON()` method could also reduce the amount of maintenance needed because then a `toString()` method could be implemented in a plugin.

**Comment by Ethan-Arrowood** [comment]
Okay so it seems like a `toJSON()` method would be better than `toString()`. And I think someone said it before; the information from `toJSON()` could be used in a `toString()` implementation (plugin or not) too.

Should I go forward with this?

**Comment by Eomm** [comment]
I created a branch to try this [feature](https://github.com/Eomm/fastify/commit/7d69c22f029a825a0e53c0e6f2753b76f4572ccd)

The output of the example is the plugins tree:

```
bound root 12 ms
├── eng 2 ms
└─┬ ita 2 ms
  └── dialect 0 ms
```

But hooks, decorator, and routes are not traced, we should try with all the hooks and the new `onRegister`.

**Comment by mcollina** [comment]
I think this would be way better than our current situation. Adding the routes would be even better.

**Comment by simo-eskalera** [comment]
Hi, just another user coming here to weigh in :)
I don't think breaking words makes sense. Breaking paths would make sense. I'm sure you'll find the output below a bit painful to read?

```
 └── /
    ├── api/v1/
    │   ├── pro
    │   │   ├── ject
    │   │   │   ├── s (GET|POST)
    │   │   │   │   └── /
    │   │   │   │       └── :id (DELETE)
        │   │   │   │       :id (GET)
        │   │   │   │       :id (PUT)
    │   │   │   └── -templates (GET|POST)
    │   │   │       └── /
    │   │   │           └── :id (DELETE)
        │   │   │           :id (GET)
        │   │   │           :id (PUT)
    │   │   └── file (GET)
    │   └── a
    │       ├── uth/log
    │       │   ├── in (POST)
    │       │   └── out (GET)
    │       └── ccounts (GET)
    └── healthz (GET)
```

**Comment by RafaelGSS** [comment]
Closing, because it looks like was solved by: https://github.com/fastify/fastify/pull/2997. Feel free to re-open in case of a mistake.
