### ISSUE TITLE
Web process failed to bind to $PORT

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/fastify#709]
With the update to v0.4.0 our heroku deployment broke. The server starts up properly, but the port binding fails.

#### What was the result you received?

That's with `v0.40.0`
```
2018-01-24T13:47:32.418040+00:00 app[web.1]: > node index.js
2018-01-24T13:47:32.418042+00:00 app[web.1]: 
2018-01-24T13:47:33.121892+00:00 app[web.1]: [2018-01-24T13:47:33.117Z] INFO (20 on 8f0b1483-5eef-4eff-b7b3-d0dd20add2cb): Server listening at http://127.0.0.1:12727
2018-01-24T13:47:33.123742+00:00 app[web.1]: server listening on 12727
2018-01-24T13:48:30.937259+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-01-24T13:48:30.937259+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-01-24T13:48:31.037535+00:00 heroku[web.1]: Process exited with status 137
2018-01-24T13:48:31.059699+00:00 heroku[web.1]: State changed from starting to crashed
```
#### What did you expect?

That's with `v0.39.1`
```
2018-01-24T13:54:52.113023+00:00 app[web.1]: > node index.js
2018-01-24T13:54:52.113024+00:00 app[web.1]: 
2018-01-24T13:54:52.669357+00:00 app[web.1]: [2018-01-24T13:54:52.665Z] INFO (20 on 018b92b8-d095-48d2-8a70-1de5605f4a60): Server listening at http://:::12974
2018-01-24T13:54:52.670567+00:00 app[web.1]: server listening on 12974
2018-01-24T13:54:53.333092+00:00 heroku[web.1]: State changed from starting to up
```

#### Context

* *node version*: 8
* *fastify version*: =0.4.0
* *any other relevant information*: Heroku

**Comment by jsumners** [comment]
What happens if you supply either `0.0.0.0` or `::` for the listening address?

**Comment by mcollina** [comment]
You should change:

```
.listen(process.env.PORT) 
```

to

```
.listen(process.env.PORT, '0.0.0.0')
```

**Comment by PatrickHeneise** [comment]
we currently use:

```
fastify.listen(process.env.PORT || 3000, function (err) {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

as specified in the readme. Why is the additional parameter required?

**Comment by jsumners** [comment]
We aren't saying that it is *required*, but your environment does not seem to like the shorthand method. We are asking you to test that the full declaration works as expected.

This is related to https://github.com/fastify/fastify/pull/667 which is outlined in https://github.com/fastify/fastify/releases/tag/v0.40.0.

**Comment by PatrickHeneise** [comment]
That worked! Will check how that change affects the other systems apart from Heroku.

Since it's breaking a platform, this could be considered a breaking change, no?

**Comment by jsumners** [comment]
@PatrickHeneise yes, that is why it is labeled as a breaking change both on the issue and the releases page.

**Comment by ACXgit** [comment]
This also happened to me yesterday night on a dev VM with the network interface configured as NAT. Adding '0.0.0.0' fixed the problem.

**Comment by jsumners** [comment]
I don't think there is anything to do here. If your system isn't allowing you to bind to ports on `127.0.0.1` then either/both:

1. You are attempting to bind on a privileged port (e.g. < 1024) without sufficient privileges
2. Your system is non-standard

Fastify is working as intended: defaulting to binding on the localhost interface.

**Comment by PatrickHeneise** [comment]
@jsumners didn't see the breaking changes part in the Changelog and didn't look for it, as it was numbered as _minor version_ update. greenkeeper updated the package, tests all worked fine, merged, deployed, heroku production environment blows up, 2 devs debug for 2 hours, not cool. Wouldn't have happened if it was a 1.0.0.

**Comment by allevo** [comment]
See `Default to listening on 127.0.0.1 - #667` in "Breaking changes" section

**Comment by delvedor** [comment]
@PatrickHeneise sorry about the hard time you had.
As you can see we are still in beta (`v0.x.y`), so breaking changes can happen at any time, and the only way to see them is to check the release notes.
As far as I know greenkeeper shows them to you.

In any case we are very close to the `v1.x.y` release, after that every breaking change will be released as semver major.

Thanks for understanding and using Fastify! :)

**Comment by nwoltman** [comment]
@PatrickHeneise See point 4 in the [semver spec](https://semver.org/#semantic-versioning-specification-semver).

**Comment by PatrickHeneise** [comment]
@nwoltman thanks!

It's all resolved now, looking forward to 1.0 though and not running into these issues again ;). Will definitely look for breaking changes in the Changelog next time.

**Comment by allevo** [comment]
@PatrickHeneise  Anyway feel free to open other issue if the release notes are not clear!

**Comment by PratapDessai** [comment]
Could you update this in doc. It's definitely a miss or else make it default

You should change:

.listen(process.env.PORT) 
to

.listen(process.env.PORT, '0.0.0.0')

**Comment by sabit990928** [comment]
Sorry guys. I'm not using fastify using fastify, but have the same issue. I have my Node JS(Express) server in other heroku pipeline. It works well, but my client side showing the R10 boot error. 
Is it mean that there is some trouble with some library and not my project itself?

**Comment by Eomm** [comment]
Trouble in some library is trouble in your project!

Anyway, this mean that your startup is not working and the general cases are:
- `npm start` command
- lost connections (do you have connection's URL to some DBS?)
- mismatch of nodejs version between your local development and Heroku instance
- very slow startup (prefetching)
- as this issue: wrong binding of the server

**Comment by sabit990928** [comment]
@Eomm, thanks for the answer. I have a problem with next.js start. There is was local changes where we remove server.js file(from version 9 it's not needed). 
To fix this issue I changed npm start command to 
`"start": "NODE_ENV=production next start -p $PORT ./app",`

**Comment by jsumners** [comment]
@sabit990928 you have stated that you are not using Fastify. Therefore, your issue is outside of our scope. Please file issues with the modules that you are actually using.

**Comment by nato-re** [comment]
this solved to me: 
```js
  app.listen(process.env.PORT || 3000, process.env.HOST || '::', err => {
    if (err) throw err
    console.log(`server listening on ${app.server.address().port}`)
  })
```

**Comment by Dzelix** [comment]
When I use both nodemon as local server and Heroku for production the following works for me:
`await fastify.listen(process.env.PORT, process.env.HOST || '0.0.0.0');`

and in package.json

`"dev": "PORT=${PORT:=3000} HOST=${HOST:=localhost} nodemon"`
