### ISSUE TITLE
Squash commits before merging

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#712]
I would like to disable "allow merge commits", and leave only squashing.
This should help with LTS.

Is anybody against this?

**Comment by jsumners** [comment]
Works for me.

**Comment by nwoltman** [comment]
I am in favour of this 👍

**Comment by StarpTech** [comment]
Jep :+1:

**Comment by delvedor** [comment]
👍

**Comment by mcollina** [comment]
Done
