### ISSUE TITLE
[0.40.0] breaking change with plugin registration after avvio@5.0.0 upgrade

### ISSUE THREAD

**Issue by avaragado** [fastify/fastify#720]
Upgrading to v0.40.0, which includes an upgrade to avvio@5.0.0 (#651), breaks plugin registration in some cases.

Before v0.40.0, you could register an array of plugins with one call to `fastify.register`. Now, you can't: `fastify.register` registers one plugin at a time. This is a breaking change.

#651 removes the documentation for the old array case, but that doesn't help those of us that already made use of it!

As fastify has a "Breaking changes" section in the Github releases list, this change should be mentioned there.

Thanks!

**Comment by delvedor** [comment]
Hi! Thank you for spotting it!
I'll update the release notes and and the correct label.
Sorry for the bad time!
