### ISSUE TITLE
returning undefined from async/await

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/fastify#723]
#### What are you trying to achieve or the steps to reproduce?
According to the documentation, we can declare `async/await` handlers and simply `return` from them.
https://www.fastify.io/docs/latest/Routes/#async-await

BUT, it appeared that one can not return `undefined` or `return;`, `fastify` will not send this payload to the user.

This was already partly touched [here](https://github.com/fastify/fastify/issues/548), so I see the code which does the check, but why?

```javascript
const fastify = require("fastify")({ logger: true });

fastify.get(`/works`, async (request, reply) => {
    console.log("I am here");
    return "";
});

fastify.get(`/does-not-work`, async (request, reply) => {
  console.log("I am here");
  return;
});

(async function() {
  try {
    await fastify.listen(3000);

    console.log(`🌎  127.0.0.1:3000`);
  } catch (error) {
    console.error(error);
  }
})();
```

Why undefined payload is not considered as real payload?

#### What was the result you received?
Response is never sent.

#### What did you expect?
Clean `200` response.

#### Context

* *node version*: 8
* *fastify version*: >=0.41.0
* *os*: Mac

**Comment by mcollina** [comment]
I think this is a doc-bug. Would you like to send a PR to document the current behaviour? In the first example we should add a note that `processed`  __must__ not be `undefined`.

The underlining reason for this is to provide async-await, promise support and callback support throughout the framework. Unfortunately, it's not possible to detect if there is a promise that returns `undefined`  if we need to expect a call to `send()`  afterwards.

See https://github.com/fastify/fastify/pull/241/ and https://github.com/fastify/fastify/issues/238.

**Comment by PavelPolyakov** [comment]
@mcollina 
clear

> Unfortunately, it's not possible to detect if there is a promise that returns undefined  if we need to expect a call to send()  afterwards.

In the documentation it's also stated that if you use `return reply.send()` first one executed will win. Can't the same kind of rule be applied for the `return;` vs `send()` case? The way that `then` of the promise has priority, if it was called - do not wait for possible `reply.send()`.

here is the docs update:
https://github.com/fastify/fastify/compare/master...PavelPolyakov:patch-2

**Comment by delvedor** [comment]
Closed in async/await return specification improved #725. Thanks!

**Comment by jsumners** [comment]
I'm re-opening this. I think the reason *why* the return value cannot be `undefined` needs to actually be explained in the documentation. Simply stating that the return value cannot be `undefined` is not sufficient.

**Comment by allevo** [comment]
If you set the status code to 204, works fine.

**Comment by StarpTech** [comment]
This PR https://github.com/fastify/fastify/pull/887 will log a warning message to inform about this case.

**Comment by StarpTech** [comment]
In https://github.com/fastify/fastify/pull/885 you can find useful information to write a better documentation.

**Comment by StarpTech** [comment]
Anybody working on this?

**Comment by StarpTech** [comment]
Please check https://github.com/fastify/fastify/pull/889
