### ISSUE TITLE
Parsed request query should support bracket and indexed array formats

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#726]
It seems like the parsed query parameter on the Request object uses default query-string array behavior. After researching the proper way to pass arrays of information through the query string it seems like this parse function should also support bracket and indexed notation.

- Bracket notation: `/api?foo[]=bar&foo[]=fuzz&foo[]=buzz` 
  - should be => `{ foo: [bar, fuzz, buzz] }`
  - currently is => `{ foo[]: [bar, fuzz, buzz] }`
- Index notation: `/api?foo[0]=bar&foo[1]=fuzz&foo[2]=buzz`
  - should be => `{ foo: [bar, fuzz, buzz] }`
  - currently is => `{ foo[0]: bar, foo[1]: fuzz, foo[2]: buzz }`
- Default notation: `/api?foo=bar&foo=fuzz&foo=buzz`
  - should be => `{ foo: [bar, fuzz, buzz] }`
  - currently is => `{ foo: [bar, fuzz, buzz] }`

I find the Index notation very useful when you want to specify the order of the array elements explicitly.

What are your thoughts on implementing this feature? Where could the user specify which notation they want the query string parsed as?

**Comment by jsumners** [comment]
There isn't a standard for supplying arrays via a query string. Trying to figure out which format has been sent in is too expensive. A plugin could be written to handle this.

**Comment by Ethan-Arrowood** [comment]
Sounds good to me. You can mark this as good-first-issue in case someone else wants to take a stab at it before I get around to it

**Comment by Larry850806** [comment]
I just recently dealt with a similar problem. Maybe I can help writing this plugin.

**Comment by Ethan-Arrowood** [comment]
Go for it! I’d be happy to mentor / review it for you if you’d like.

**Comment by Larry850806** [comment]
I am working on this. I think using `req.query` to get parsed query string is a good way, but `req.query` is used by default query object. Is there any good way I can over overwrite it?

**Comment by Ethan-Arrowood** [comment]
Sorry for the late response. Let me look into this now and see what i can find.

**Comment by Ethan-Arrowood** [comment]
See if there is something on the main Fastify object you can decorate. If `req.query` is forced to use `default query object` then you may need to edit the Fastify source itself.

**Comment by delvedor** [comment]
Fastify v2 has just been published, and with it the `querystringParser` option, that will also address this issue :)

**Comment by melroy89** [comment]
I also noticed that Fastify has still issues with query parameters, it also doesn't detect it as an object in case of for example:

```
?somequery[KEY]=somevalue
```

Then `somequery` should actually become an object instead of a string...

```js
const { somequery } = req.query
typeof somequery
// Should be type of object, instead of type string
```

Workaround is to change indeed still the query parser too bad (like `qs`)...

```
  const app = fastify({
    querystringParser: str => qs.parse(str)
  });
```

**Comment by KaKi87** [comment]
Hi @delvedor, it would still be nice for Fastify to support this by default. Thanks

**Comment by kr-yeon** [comment]
I also needed that feature, but the current state is also the most basic and I think it's a good expandable method.

I'd like to hear other people's thoughts too.
