### ISSUE TITLE
How to add a middleware to authenticate some request, but not all requests?

### ISSUE THREAD

**Issue by guotie** [fastify/fastify#740]
I found the middleware is apply to all the request, if I want authenticate some request, how to do?

In some framework, you can do this like

```
fastify.get('/usr', mid1, mid2, handler)
```

**Comment by nwoltman** [comment]
You can do something very similar by using the `beforeHandler` route option:

```js
fastify.get('/usr', {beforeHandler: [mid1, mid2]}, handler)
```

Be aware though that `beforeHandler` functions receive the Fastify [`Request`](https://github.com/fastify/fastify/blob/master/docs/Request.md) and  [`Reply`](https://github.com/fastify/fastify/blob/master/docs/Reply.md) objects (not Node's `req` and `res` objects, although they can be accessed as `request.req` and `reply.res`).

You can read about defining routes in Fastify here: https://github.com/fastify/fastify/blob/master/docs/Routes.md

**Comment by guotie** [comment]
thanks.

**Comment by delvedor** [comment]
The best thing to do is to register the middlewares (I assume express middlewares) with the `use` api and encapsulated them with a plugin.

```js
fastify.register((instance, opts, next) => {
  instance.use(mid1)
  instance.use(mid2)
  instance.register(require('./auth-routes'), opts)
})

fastify.register((instance, opts, next) => {
  instance.register(require('./no-auth-routes'), opts)
})
```
Checkout out our [plugins guide](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md) :)

**Comment by Ch-Valentine** [comment]
```javascript
const routes = [
  {
    method: 'GET',
    url: '/users',
    handler: UsersController.list,
    beforeHandler: [middleware1, middleware2],
    schema: swaggerSchema.getUsers
  },
  {
    method: 'POST',
    url: '/users',
    handler: UsersController.create,
    schema: swaggerSchema.postUsers
  }
]
```

**Comment by Cristiandi** [comment]
Now days `beforeHandler` is deprecated, instead you must use `preHandler`, but the functionality is the same:
```js
const midd1 = async (request, reply, next) => {
    app.log.info('request', Object.keys(request));
    app.log.info('reply', Object.keys(reply));
    app.log.info('done', next);
  };

// create
app.post('/', { schema: createSchema, preHandler: [midd1] }, async (request, reply) => {
  const { body } = request;

  app.log.info('body', body);

  const created = await userController.createUser({ user: body });
  return reply.code(201).send(created);
});
```

**Comment by RaghavaBusanaboina** [comment]
When I'm using preHandler, my route is executes twice, how can I solve this?

**Comment by RaghavaBusanaboina** [comment]
> Now days `beforeHandler` is deprecated, instead you must use `preHandler`, but the functionality is the same:
> 
> ```js
> const midd1 = async (request, reply, next) => {
>     app.log.info('request', Object.keys(request));
>     app.log.info('reply', Object.keys(reply));
>     app.log.info('done', next);
>   };
> 
> // create
> app.post('/', { schema: createSchema, preHandler: [midd1] }, async (request, reply) => {
>   const { body } = request;
> 
>   app.log.info('body', body);
> 
>   const created = await userController.createUser({ user: body });
>   return reply.code(201).send(created);
> });
> ```
When I'm using preHandler, my route executes twice, how can I solve this?

**Comment by climba03003** [comment]
> When I'm using preHandler, my route is executes twice, how can I solve this?

Please create your own issue with reproducible code.
