### ISSUE TITLE
onProcessExit handler for process shutdown events in respect to service cleanup

### ISSUE THREAD

**Issue by jimmiehansson** [fastify/fastify#742]
#### You have already researched for similiar issues?

Yes

#### Are you sure this is an issue with the fastify or are you just looking for some help?

This is a mere suggestion rather than issue that may need to be addressed

#### Is this a security related issue?

Not on the application layer

#### What are you trying to achieve or the steps to reproduce?

To gracefully inform the second-party services attached via e.g. plugins that the main process is being terminated and there is a shutdown in progress, it should not leave stale connections on the system. This could also benefit to address cleanup. The plugin should not directly engage with process exit event.

```js
fastify.addHook('onProcessExit', unref)
function unref (fastify, done) {
  fastify.redis.unref()
}
```

#### What was the result you received?

For the core application to pay respect to the attached services / plugins in order to cleanly disengage any runtime that has been started by fastify. 

#### What did you expect?

That process termination should respect second-party services that are attached. 

#### Context

* *node version*: v9.4.0
* *fastify version*: >=0.4.2
* *os*: Mac, Unix

**Comment by delvedor** [comment]
We discussed about this in the past and we decided to not have process events in core.
You can implement your own and call `fastify.close` or use [`fastify-graceful-shutdown`](https://github.com/hemerajs/fastify-graceful-shutdown).

**Comment by jimmiehansson** [comment]
Thank you for the quick response @delvedor
Why is it necessary for the `fastify-graceful-shutdown` to implement a separate behavior though? Hence not be a default or standard. 
Should the default behavior imply to support more signals in the event of interruption? Please clarify and thank you for the help 👍

**Comment by delvedor** [comment]
> Please clarify and thank you for the help 👍

I can do more, I can point you to the actual discussion! ;) https://github.com/fastify/fastify/issues/260

**Comment by jimmiehansson** [comment]
Thanks for the clarification and quick response. In future for questions that may need more clarification where would I turn? Hence closing the question. 
I'm partially asking this question to evaluate how the workflow and feedback is being received incase of contribution.
I'm currently in an enterprise environment where weigh and balance between proper discussions and quality assessment is of major importance.

As per the subject. I can see the benefit of speed as I agree with the decision (which was status-quo) but the current design may not imply that actual SIGX to be handled properly as per injection of the plugin.

**Comment by delvedor** [comment]
>  In future for questions that may need more clarification where would I turn?

We have just created the help repo! [fastify/help](https://github.com/fastify/help)

> but the current design may not imply that actual SIGX to be handled properly as per injection of the plugin.

I'm not sure I've understood what you mean here

**Comment by jimmiehansson** [comment]
Thanks :) I wasn't aware I'll look into that repo in the future 👍 

In the case a process gets trapped because of paging faults, drive failure or mapping faults in memory the system will respond with other signals than those currently implemented. If this should be handled by inversion control as per plugin, the chances are larger that it will never get caught in time.

**Comment by jsumners** [comment]
@jimmiehansson as you can see in the issue @delvedor linked, I'm not a fan of having a generic plugin. This is something that is *very* specific to each application. Most of them can get away with a simple:

```js
fastify.listen(0, (err) => {
  if (err) process.exit(1)
  process.on('SIGTERM', fastify.close.bind(fastify))
})
```

But there are plenty of situations where your shutdown logic is going to be much more complicated. Thus, each app should have its own logic for handling shutdown.

As another example, look at what I added to the `fastify-oracle` plugin's readme this morning:

https://github.com/jsumners/fastify-oracle/commit/7b5534cf849b399da028c17491d9be3602953104

Applications using that plugin need to recognize that the `oracledb` module will block shutdown without an explicit `.close()` on the opened pool. So they need to issue that `.close()` themselves if the Fastify instance fails to bind properly, and attach listeners to the appropriate shutdown signals.

This is something a general purpose library like Fastify should not be dealing with.

**Comment by jimmiehansson** [comment]
Thanks for your detailed response @jsumners May I be missing how the construction of the plugin catches this in time for `fastify-graceful-shutdown` though? I will have to look further, a lot of questions since I just started looking at the code. I certainly agree that the design makes the most sense in this case since it operates very declarative.

**Comment by jsumners** [comment]
I don't know anything about `fastify-graceful-shutdown` for the reasons I outlined above.

**Comment by jimmiehansson** [comment]
@jsumners It makes more sense, thanks for the help!

**Comment by leoplaw** [comment]
There is also `http-graceful-shutdown` which might fulfil the requirement.
Gracefully shuts down a node.js http server.
can be used with express, koa, fastify, native node http, http2 ... see examples
https://github.com/sebhildebrandt/http-graceful-shutdown
