### ISSUE TITLE
Accessing the Request object in an error handler

### ISSUE THREAD

**Issue by nwoltman** [fastify/fastify#744]
Sometimes it's necessary access the Fastify `request` object inside an error handler ([`fastify.setErrorHandler`](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#seterrorhandler)) such as to check request headers.

This can currently be done by accessing `reply.request`, but this may not be the best API (will `reply` always have the `request` property in the future?).

My question is, should we:

**A)** Document `reply.request`
or
**B)** Change the error handler signature to: `function (error, request, reply) { ... }`

My personal preference is B because that seems more future-proof and is closer to the signature of regular handlers. But I'd like to hear what everyone else thinks about this.

**Comment by jsumners** [comment]
I like `B`. But you're going to hear about #169 in this thread.

**Comment by mcollina** [comment]
I like A. reply.request is not going away, and I would like to avoid another breakage and release 1.0.0-rc1.

**Comment by delvedor** [comment]
@mcollina I agree that another breaking change is not the best thing, but expose also `request` makes the api more consistent with other apis such as the not found handler.

```js
fastify.setNotFoundHandler(function (request, reply) {})

fastify.setErrorHandler(function(error, request, reply) {})
```

**Comment by mcollina** [comment]
I’m ok. Can one of you send a PR? let’s get it done before Monday.

**Comment by nwoltman** [comment]
I can do it 👍
