### ISSUE TITLE
Null or optional response schema property

### ISSUE THREAD

**Issue by jeromedecoster** [fastify/fastify#749]
Hi,

It is possible to have a defined or null property ?

Below, the property `HERE` define an object :
```js
schema = {
  response: {
    200: {
      type: 'object',
      properties: {
        HERE: { 
        type: 'object',
        properties: {
          id: { type: 'number' },
          url: { type: 'string' },
          title: { type: 'string' }
        },
        // other ...
      }
    }
  }
}
```
Below, the property `HERE` define a `null` :
```js
schema = {
  response: {
    200: {
      type: 'object',
      properties: {
        HERE: null,
        // other ...
      }
    }
  }
}
```

I also saw a related old issue about optional properties https://github.com/fastify/fastify/issues/32 but nothing in actual documentation.

Thanks.

**Comment by mcollina** [comment]
Have you checked the http://json-schema.org/ documentation?
What should be the expected output for you?
Can you produce an example?

**Comment by jeromedecoster** [comment]
Hi,

Thanks for the quick reply. Sorry if my question was not clear.

> What should be the expected output for you?

It's simple `127.0.0.1/api/?s=a` returns
```
{"HERE":null}
```
and `127.0.0.1/api/?s=b` returns

```
{"HERE":{"id":12, "url":"..."}}
```
Without schema, I can output whatever I want. But if I add a schema, it seems there is no possibility to have a "defined" or "null" result.

My actual solution is to returns an array with nothing

```
{"HERE":[]}
```

or "filled" with my object `{"id":12, "url":"..."}` but it is not clean as I expected

```
{"HERE":[{"id":12, "url":"..."}]}
```

**Comment by mcollina** [comment]
You can see https://github.com/fastify/fast-json-stringify/blob/85f1e0ef5a87a0538c12d587bdf1d61c191f0e36/test/anyof.test.js how to specify different types (`"null"` included).

**Comment by jeromedecoster** [comment]
`anyOf` ! Yes thank you very much

**Comment by oxyii** [comment]
for search engines: [nullable](https://github.com/fastify/fast-json-stringify#nullable) looks better solution for this
