### ISSUE TITLE
Unhandled promise rejection on async plugin

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#755]
#### Steps to reproduce
```js
const fastify = require('fastify')();

fastify
    .register(async (fastify, options, next) => {
        throw new Error('test');
    })
    .after(error => {
        throw error;
    });

fastify.listen(8080, error => {
    if (error) {
        throw error;
    }
    console.log('Listening at 8080');
});
```

#### What was the result you received?
The code above after running returns a `(node:21922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` message.

#### What did you expect?
I expect the `async` plugin function rejection will be handled and the error just passed so there will be no promise rejection warnings.

#### Context
* *node version*: 9.4.0
* *fastify version*: >=0.39.1
* *os*: Mac

**Comment by mcollina** [comment]
You are rethrowing inside after, which is not an async function. What is weird is that it get caught within a promise, and it should not do that.
I know what's going on and I'll file a PR for this.

**Comment by sarneeh** [comment]
@mcollina Uhm, yeah, well, I am rethrowing it inside `after` for a reason. I missed my case in this example, let me explain exactly what I wanted to achieve:

```js
const fastify = require('fastify')();
const fp = require('fastify-plugin');

const someAsyncFunction = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject(new Error('oops'));
    }, 500);
});

fastify.register(
    fp(
        async (fastify, options, next) => {
            await someAsyncFunction();
            fastify.decorate('test', { nestedValue: 'value' });
        },
        { name: 'module1' }
    )
);

fastify.register(
    fp(
        (fastify, options, next) => {
            console.log(fastify.test.nestedValue);
        },
        { name: 'module2', dependencies: ['module1'] }
    )
);

fastify.listen(8080, error => {
    if (error) {
        throw error;
    }
    console.log('Listening at 8080');
});
```

I have this kind of situation:
* `module1` does some setup, let's say database connection
* `module2` uses what `module1` creates

In the code above the error that I'm getting is `'nestedValue` is undefined`, but what I really wanted to see is the database initialization error - `oops`. Using `.after` made it work as expected for me, but still I'm getting it wrapped in a Promise rejection warning (instead of just getting an error).

**Comment by mcollina** [comment]
This should be fixed in the latest avvio, 5.1.0. Please reinstall and let us know if it's ok.

**Comment by sarneeh** [comment]
@mcollina Yup, it fixed the Promise deprecation issue! Thanks!

I have just one more question: please take a look at my previous comment - could you please explain me why in this example the error that is being thrown is the one from the second register (rather than the first one?). How can I solve this kind of dependency?

**Comment by mcollina** [comment]
That might be another issue. Can you open a different thread?
I think @allevo studied a lot this use case.
