### ISSUE TITLE
Plugin loading order - throwing exceptions

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#757]
Hey!

I'm coming with another issue. I have a problem with (understanding?) the plugin loading order. 

Consider this example:

* I have a `module1` which i.e. initializes the database and decorates fastify `fastify.db`
* I have `module2` which uses `fastify.db.doSomething()`
* Obviously, plugin `module2` depends on `module1` 

And now let's say that in `module1` the connection to database didn't work. What I expect now is that the app will crash with an database connection error. But something else happens - I get a `'doSomething' is undefined` error.

Here's the code to reproduce the problem:

```js
const fastify = require('fastify')();
const fp = require('fastify-plugin');

const connectToDb = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => {
            reject(new Error('connection didnt work'));
        }, 500);
    });

fastify
    .register(
        fp(
            async (fastify, options, next) => {
                await connectToDb();
                fastify.decorate('db', { doSomething: () => {} });
                next();
            },
            { name: 'module1' }
        )
    )

fastify.register(
    fp(
        (fastify, options, next) => {
            fastify.db.doSomething();
            next();
        },
        { name: 'module2', dependencies: ['module1'] }
    )
);

fastify.listen(8080, error => {
    if (error) {
        throw error;
    }
    console.log('Listening at 8080');
});
```

Now after a little bit of digging around I tried to add an `.after` method to catch and rethrow the error from `module1`:

```js
fastify
    .register(
        fp(
            async (fastify, options, next) => {
                await connectToDb();
                fastify.decorate('db', { doSomething: () => {} });
                next();
            },
            { name: 'module1' }
        )
    )
    .after(error => {
        if (error) throw error;
    });
```

And what happens now? I get the `connection didnt work` error as expected.

Why do I have to add an `.after` to get the error from the first loaded plugin which crashed (instead of the second)? I assumed that if `module2` depends on `module1`, I run register on `module1` first, before `module2`, and if `module1` won't load properly the process won't try to access `module2`.

Is it some kind of a bug, or do I just don't understand how it works? :) I'd very appreciate any explanation.

Pinning @allevo - I've heard you know a little about this use case :)

#### Context
* *node version*: 9.4.0
* *fastify version*: >=0.43.0
* *os*: Mac

**Comment by jimmiehansson** [comment]
They're running in different contextual cycles, your first plugin is set to await a timed result that will not be executed in the same context, which is also a blocking call. To my knowledge there is no implementation for Fastify to create a DI hook based on the awaited results. This is the power of the node core. I might have completely misunderstood the issue, but how could you otherwise catch the result of something that isn't yet returned? I've barely had the chance of looking at the Fastify code but this doesn't seem like a Fastify specific problem either. Great question!

**Comment by allevo** [comment]
I've opened a PR on `avvio` (the fastify plugin system) here https://github.com/mcollina/avvio/pull/45
There I've only added a failing test.


Consider those lines:
```js
fastify
  .register(moduleA)
  .register(moduleB)
```

If `moduleA` registration fails, the registration of the `moduleB` is performed anyway.

I'm looking for a solution inside `avvio` to make this behaviour configurable.
If you want, please file another PR!!

**Comment by mcollina** [comment]
This addresses the issue https://github.com/mcollina/avvio/pull/48, without compromising `.after()`.

Check it out.

**Comment by sarneeh** [comment]
Thank you!  👍
