### ISSUE TITLE
Confusing payload/body API

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#76]
```js
const route = {
  method: 'POST',
  path: '/foo',
  handler: (req, reply) => {
    reply.send({bar: req.body.bar})
  },
  schema: {
    payload: {
      type: 'object',
      properties: {
        bar: {type: 'string'}
      }
    }
  }
}
```

Notice that the validation schema for the `POST` body is labeled `payload`, whereas within the handler method it is referenced as `body`. This mix of terminology is confusing, particularly for someone used to using Hapi. Either the validation config should change "payload" to "body", or the handler should be passed `req.payload`.

**Comment by delvedor** [comment]
You are right, *body* is more intuitive.
In addition, I'm developing the [swagger plugin](https://github.com/fastify/fastify-swagger), and in the yaml file the *payload* is referenced as *body*.
I'm +1 on rename it, or at least make an alias.

@mcollina thoughts?

**Comment by mcollina** [comment]
I'm 👍 on fixing the inconsistency. I'm fine both ways.

**Comment by delvedor** [comment]
The problem with the "remove completely" is that we are not warning the user that we have changed the api. So probably use an alias until the v1.0 is the best way :)

**Comment by jsumners** [comment]
<1.0.0 is volatile. So if you wanted to change it completely I don't see why you'd need to keep an alias around.

**Comment by mcollina** [comment]
I'm 👍  in removing it completely right now.

**Comment by delvedor** [comment]
Ahahaha, we are in democracy, 2 vs 1 :P
Let's go with the direct change then!
@jsumners do you want to make a pr?

**Comment by jsumners** [comment]
I am unclear on the decided resolution (payload or body). I am fine with you implementing what you see as the solution @delvedor .

**Comment by delvedor** [comment]
Body :)

Ok, I'll do it, thanks for the suggestion!
