### ISSUE TITLE
Plugins cannot specify a satisfactory version range

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#763]
Currently, with `v1.0.0-rc.1` available, it is not possible to boot a Fastify instance that relies on versioned plugins, e.g. `fastify-cookie`. The issue is that `fastify-plugin` can't determine a range that includes 0.y.z releases along with rc release. This is because the `semver` package *does not follow the semver spec*. From the spec:

https://semver.org/#spec-item-11
> A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

From the `semver` package's documentation:

>  If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.
>
> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version. The version 3.4.5 would satisfy the range, because it does not have a prerelease flag, and 3.4.5 is greater than 1.2.3-alpha.7.
>
> The purpose for this behavior is twofold. First, prerelease versions frequently are updated very quickly, and contain many breaking changes that are (by the author's design) not yet fit for public consumption. Therefore, by default, they are excluded from range matching semantics.
>
> Second, a user who has opted into using a prerelease version has clearly indicated the intent to use that specific set of alpha/beta/rc versions. By including a prerelease tag in the range, the user is indicating that they are aware of the risk. However, it is still not appropriate to assume that they have opted into taking a similar risk on the next set of prerelease versions.

I'm really at a loss for what to do here. Clearly plugins need to be updated to provide a valid range. But they can't do that during the rc phase because `1.0.0-rc.1 || <1.0.0` will not validate via `semver.satisfies()`.

**Comment by mcollina** [comment]
I think fastify-plugin should be a little bit smarter than what it does right now, mainly drop `-rcX`  from `1.0.0` prefixed releases. It would fit our need.

I also plan to change all the plugins from `>= 0.43.0` to `^1.0.0`, which means they will support only one major, and they will require a new release when we bump the major.

**Comment by jsumners** [comment]
I have been planning to wait for 1.0.0 before issuing updates to the plugins I write.

**Comment by delvedor** [comment]
I agree with @mcollina, but I think we should print a warn about this.

**Comment by mcollina** [comment]
This should be fixed in https://github.com/fastify/fastify-plugin/pull/21
