### ISSUE TITLE
Missing plugin for use i18n labels

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#764]
#### You have already researched for similiar issues?
Yes, but din't find anything.
Thre are many for Express, and some generic like [i18next](https://github.com/i18next/i18next), [i18n-node](https://github.com/mashpie/i18n-node), etc.

#### Are you sure this is an issue with the fastify or are you just looking for some help?
This mainly is a discussion (already posted in Fastify Gitter Chat) to understand the better way to solve this in Fastify (probably with a plugin).
But maybe only a single plugin to solve these issues could become too complex, so maybe it would be better to tie a specific plugin to the package used, and start with a simpler one (maybe without using other packages).

#### Is this a security related issue?
No.

#### What are you trying to achieve or the steps to reproduce?
Define a default language/locale (for example 'en' by default) as a fallback, and a list of additional locales; usually in the Java world this is done by not appending to resource files a _locale suffix in the name(only for default language), and appending to any other, but I'm not sure in Node.js frameworks if it's a good practice.
Configure the plugin to point to right resources (could be 1 file per language, or a folder, or a DB table with a discriminant, or other); then when using it, anytime I ask for a label (given a key) if it's found in the user language, it's returned, otherwise label value in default language or if not found an error (or maybe a specific error text if configured).
Of course all this should be usable even from template engines, and should be as fast as possible to minimize the impact when serving pages.
It would be useful for this i18n label system to be able to expand label with nested values inside (maybe using Node.js templates syntax).
Sometimes could be useful even to ask for a label but using a different locale than the user current.

So a question: the right way to get user locale in Fastify (and to override), if any ?
Reading HTTP headers (with the in the right priority, as given from the browser) and a plugin configured (optional) request attribute with higher priority.
Sorry for the terms used, in Node.js could be a little different usually (I come from a Java background).

#### Context

* *node version*: N/A
* *fastify version*: >=0.43.0
* *os*: N/A
* *any other relevant information*: nothing

----

**Comment by ianwalter** [comment]
Hi, I tried out a basic implementation of `i18n-node` last night and it works pretty well if you use the raw request, e.g. 
```js
request.raw.__('myKey')
```

**Comment by delvedor** [comment]
@ianwalter Hi! Do you want to create a plugin for it? :)

**Comment by ianwalter** [comment]
@delvedor Sure, but do you think it's worth it? What would the plugin do? Just add a `decorateRequest('locals') so that the locals/locale object and methods can be accessed without going into the raw request?

**Comment by delvedor** [comment]
@ianwalter that's a good start :)

**Comment by ianwalter** [comment]
Actually just realized that if you add i18n in a `preHandler` hook like:
```js
fastify.addHook('preHandler', i18n.init)
```
The locale information/methods are on the root of the Request object and there's no need to use raw, so I don't think a plugin is necessary unless I'm missing something.

**Comment by delvedor** [comment]
@ianwalter I would not use the `preHandler` to decorate request, for two reasons:
1. there is the [`decorateRequest`](https://github.com/fastify/fastify/blob/master/docs/Decorators.md) method.
1. By using the `preHandler` as you did, you will re-initialize the library for every request that comes in, which is not very performant.

I don't know how `i18n` works, but probably the best solution is to use `decorateRequest` and `preHandler` together, with an instance of `i18n` already initialized.

If you want to create a plugin I'll be happy to review it :)

**Comment by smartiniOnGitHub** [comment]
Hi all and thanks for the feedback (and inital implementation) ... I don't have knowledge on i18n-node, but if I could help tell me (at least in additional plugin content like an example, review of documentation, etc).

**Comment by ianwalter** [comment]
@delvedor I don't think `i18n-node` works like that. I think the name is misleading and that the `init` method is meant to be used as middleware. Initially I was using `fastify.use(i18n.init)` as `i18n-node` usage directed for Express but it added the locale to the raw request. I wasn't sure how to use `decorateRequest` for this because the middleware needs to read the `Accept-Language` header on each request in order to determine which language to use for the request.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/915.
