### ISSUE TITLE
Fastify listen missed backlog parameter

### ISSUE THREAD

**Issue by mancioshell** [fastify/fastify#767]
Is it possibile to support backlog parameter to fastify listen method?
server.listen from http module support it:
```js
server.listen([port][, host][, backlog][, callback])
```
It seems fastify support only port, host and callback as listen parameters.

**Comment by delvedor** [comment]
At the moment is not supported.
Would you like to send a pr? :)

**Comment by mancioshell** [comment]
Hi, @delvedor i'have just published #769 pull request for this issue. This is my first pr, so i hope i haven't done wrong things :)

**Comment by mcollina** [comment]
Fixed.

**Comment by mancioshell** [comment]
Is it possible to publish a new version on npm ?

**Comment by delvedor** [comment]
@mancioshell the next rc release is scheduled on next monday. We should wait for https://github.com/fastify/fastify/issues/748.
