### ISSUE TITLE
Move all (?) examples into fastify/example

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#768]
We have https://github.com/fastify/example repo.

Should we use it for keeping the examples?

All examples?

If yes, we should rethink `npm run bench` script .

Please vote! 👍 for moving, 👎  for keeping it there.

cc @fastify/fastify

**Comment by mcollina** [comment]
I am -1

**Comment by delvedor** [comment]
I think we should keep them here.
Maybe add a `npmignore` could be a nice thing to do.
