### ISSUE TITLE
Expose logger instance?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#77]
The configured logger is exposed during requests, but it may be useful to expose it as a property. For example:

```js
const fastify = require('fastify')()
const log = fastify.logger
```

Thoughts?

**Comment by mcollina** [comment]
Good Idea. Also, we should accept a Pino logger as an option.

**Comment by jsumners** [comment]
@mcollina that part is done -- https://github.com/fastify/fastify/pull/52 ;)

**Comment by delvedor** [comment]
I'm 👍  with this, I'll do that in the `payload => body` pr :)

**Comment by delvedor** [comment]
Done in #78

**Comment by delvedor** [comment]
The `onSend` hook is you best shot, otherwise you can try something with `onResponse`, but I'm not sure it will work.
