### ISSUE TITLE
hasContentTypeParser API documentation is missing

### ISSUE THREAD

**Issue by amitguptagwl** [fastify/fastify#780]
While looking for the solution for handling [multiple contenttype for parsing](https://github.com/fastify/help/issues/1), I found that documentation for `hasContentTypeParser` API is missing from the [example](https://github.com/fastify/fastify/blob/master/examples/parser.js) as given on page [ContentTypeParser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md)

**Comment by delvedor** [comment]
Hi! Would you like to send a pr to fix this? :)

**Comment by amitguptagwl** [comment]
I would love to do that. But I couldn't find it's documentation or example anywhere that I can document. However let me check the code and see how can I figure out that.

**Comment by delvedor** [comment]
Here :)
https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md

**Comment by amitguptagwl** [comment]
I just tried this in my code and found that it returns true/false if there is a parser handling given content type .

```js
fastify.addContentTypeParser(someContentType, contentParser)
console.log(fastify.hasContentTypeParser(someContentType));//true
```js

**Comment by amitguptagwl** [comment]
PR raised. @delvedor feel free to reject the PR if it looks better to combine in single example instead of having multiple code examples.
