### ISSUE TITLE
Response headers validation

### ISSUE THREAD

**Issue by cortopy** [fastify/fastify#783]
I would like to define response headers for two reasons:
- response full validation (headers are still optional so no performance penalty if users don't want it)
- swagger documentation of responses

This is currently not possible in fastify since there is no headers object in the default reply serializer.

Ideally, there would be something like this instead of the current object definition:

```js
    200: {
          description: "Example response",
          body: {
            type: "object",
            properties: {
              value: "string"
            }
          },
          headers: {
            type: "object",
            properties: {
              "x-custom-header": {
                type: "string"
              }
            },
            required: ["x-custom-header"]
          }
        }
```

Could this be something to implement in core fastify or should users write their own serializer for this?

Happy to contribute either way. If this should be supported by fastify I'll make a PR here. Otherwise, I'll write a serializer for fastify-swagger. My preferred approach would be for fastify to do it though, mainly for consistency sake

**Comment by mcollina** [comment]
My preference would be for this to be done with an ecosystem plugin. I'm not sure this 100% possible.
This is useful metadata for swagger anyway, so we should provide a way to add the info, even if we do not act on it.

Side note: we do not validate the response. The response is serialized according to a schema, but a full validation is not performed, i.e. we do not throw if it does not match the schema.

**Comment by cortopy** [comment]
If `headers` would only act as metadata, then a plugin could be written without changing anything in fastify. Adding a headers object to a response definition doesn't throw, and plugins could parse that.

But if the response doesn't comply with the schema, an Error is thrown.

If I have this schema:

```js
response: {
        200: {
          description: "Example response",
          type: "object",
          properties: {
            requiredProp: { type: "string" }
          },
          required: ["requiredProp"]
        }
      }
```

and then I send `reply.code(200).send({})` I get:

```js
new Error('requiredProp is required!')
```

Perhaps I didn't understand this correctly, but I just assumed this was some sort of validation.

**Comment by mcollina** [comment]
It performs some _basic_ validation, but it's not a fully compliant json-schema validator.

**Comment by delvedor** [comment]
Closing this, if you have more questions feel free to reopen :)
