### ISSUE TITLE
Router bug

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#786]
#### What are you trying to achieve or the steps to reproduce?

```js

const fastify = Fastify()

async function plugin3 (fastify) {
  fastify.post('/bulk', async function (req, reply) {
    return { hello: 'world' }
  })
  fastify.get('/', async function (req, reply) {
    return { hello: 'world!!!!!!!!' }
  })

  fastify.setNotFoundHandler(async function notFoundHandler (request, reply) {
    reply
      .code(404)
      .send({
        error: 'not found'
      })
  })
}

async function plugin2 (fastify, { p: prefix }) {
  if (!prefix) throw new Error('`prefix` is undefined!')

  fastify.register(plugin3, { prefix: '/' + prefix + '/' })
}

async function plugin1 (fastify) {
  ['aa', 'bb'].forEach(prefix => fastify.register(plugin2, { p: prefix }))
}

fastify.register(async function (fastify, opts) {
  fastify
    .register(plugin1)
    .ready(() => {
      console.log(fastify.printRoutes())
    })
})

const response1 = await fastify.inject({
  method: 'POST',
  url: '/aa/bulk',
  payload: {}
})

t.strictEqual(response1.statusCode, 200)

const response2 = await fastify.inject({
  method: 'POST',
  url: '/bulk',
  payload: {}
})

t.strictEqual(response2.statusCode, 404)
```

#### What was the result you received?

The second assertion throws. `response2.statusCode === 200`

#### What did you expect?

`response2.statusCode === 404`

#### Context

* *node version*: 8
* *fastify version*: "8aa6b1d" (master)
* *os*: *
* *any other relevant information*: maybe it is a `find-my-way`

I'll file a PR in order to add the test

**Comment by mcollina** [comment]
If you do not use fp, the prefix is automatically handled for you.

**Comment by allevo** [comment]
@mcollina yeah. 

CURLing to `POST /aa/bulk`, 200 is returned.
CURLing to `POST /bulk`, 404 should be returned, but 200 is returned. This is a bug

The test fails on the second check.

**Comment by delvedor** [comment]
Fixed in https://github.com/delvedor/find-my-way/pull/65 :)
