### ISSUE TITLE
Use symbols to avoid exposing internal properties in fastify main object

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#788]
As an example, `fastify._hooks` should become `fastify[hooksKey]` where `const hooksKey = Symbol('fastify.hooks')`.

**Comment by jsumners** [comment]
I was concerned this might make debugging more difficult, but setting a break point within the `listen` callback of `examples/hooks.js` shows that it will not be so:

![2018-02-16 09-49-59 hooks js fastify](https://user-images.githubusercontent.com/321201/36313256-fb92bcc8-12fe-11e8-9aff-4d489ff1fae2.png)


I'm 👍 with this idea.

**Comment by Larry850806** [comment]
Is there anyone working on this ? Maybe I can do this.

**Comment by jsumners** [comment]
@Larry850806 we would love it if you would work on this.

**Comment by Larry850806** [comment]
Ok, I will finish it soon.

**Comment by cemremengu** [comment]
Landed in #1128

**Comment by mcollina** [comment]
Thanks!
