### ISSUE TITLE
Memory leak with RC 2

### ISSUE THREAD

**Issue by alizahid** [fastify/fastify#791]
Upgraded from RC 1 to RC 2 today, and got this error

> (node:5884) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preReady listeners added. Use emitter.setMaxListeners() to increase limit

I also have `cors` 2.8.4 and `fastify-multipart` 0.4.1 if that may matter

I have my app setup like this

### index.js

```
const users = require('./routes/users')

const options = {
  prefix: 'v1'
}

fastify.register(users, options)
```

### routes/users.js

```
module.exports = (fastify, options, next) => {
  fastify.route(createUser)
  fastify.route(updateUser)
  fastify.route(deleteUser)

  next()
}
```

The weird thing I've noticed is that if I only have two routes exported out of my module, eg, `createUser` and `updateUser`, the error doesn't throw. But any more than two triggers the warning

* *node version*: 9.5.0
* *fastify version*: 1.0.0-rc.2
* *os*: Mac

**Comment by delvedor** [comment]
Should be fixed by https://github.com/mcollina/avvio/releases/tag/v5.4.1.
Can you reinstall your dependencies and try again?

**Comment by astesio** [comment]
I had a similar problem, although my project structure is different, I have a logic that makes the reading of routes automatically, and I got the same error. More routes normally work, just notice the warning on the terminal.
`node:20910) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preReady listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by delvedor** [comment]
It should be fixed in the latest version of `avvio`, can you please reinstall your dependencies and try again?

**Comment by alizahid** [comment]
Reinstalling dependencies didn't help. I even tried installing `avvio` v5.4.1 as a peer dependency, but the warning remains.

Did you mean something else?

**Comment by delvedor** [comment]
I'll run some more test.
In the meantime do not worry about the warning, is an internal event that we are using during the bootstrap of the application and will not cause any problem during the normal lifecycle.

**Comment by mcollina** [comment]
Can you upload a full example that exhibits that behavior? Which versions of Node and NPM are you using?

**Comment by alizahid** [comment]
@delvedor Weirdly, when I tried to replicate this from scratch, I couldn't. I think it was my `yarn.lock` which prevented `avvio` from updating properly.

@mcollina This is the full example anyway.

Node v9.5.0
NPM v5.6.0
Yarn v1.3.2

```
const cors = require('cors')()
const fastify = require('fastify')({
  logger: true
})
const multipart = require('fastify-multipart')
const mongoose = require('mongoose')

mongoose.connect('mongodb://localhost/fast')
mongoose.Promise = global.Promise

fastify.use(cors)
fastify.register(multipart)

fastify.register(
  (fastify, options, next) => {
    fastify.route({
      method: 'GET',
      url: '/one',
      async handler() {
        return 'one'
      }
    })

    fastify.route({
      method: 'GET',
      url: '/two',
      async handler() {
        return 'two'
      }
    })

    fastify.route({
      method: 'GET',
      url: '/three',
      async handler() {
        return 'three'
      }
    })

    fastify.route({
      method: 'GET',
      url: '/four',
      async handler() {
        return 'four'
      }
    })

    next()
  },
  {
    prefix: 'v1'
  }
)

fastify.listen(3000, '0.0.0.0', err => {
  if (err) {
    throw err
  }

  console.log(`server listening on ${fastify.server.address().port}`)
})
```

**Comment by delvedor** [comment]
@alizahid so when creating the project from scratch the warning does not appears anymore?

**Comment by alizahid** [comment]
@delvedor No. All looks good! Thank you. 👍

**Comment by delvedor** [comment]
Perfect, thanks!

**Comment by goliatone** [comment]
I'm hitting a similar scenario while load testing my project with:
`npx autocannon -c 100 -d 5 -p 10 localhost:3003`

Error:
```
(node:92681) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:223:19)
    at Socket.addListener (events.js:240:10)
    at Socket.Readable.on (_stream_readable.js:775:35)
    at Socket.socketOnWrap [as on] (_http_server.js:668:37)
    at first (.../project/src/node_modules/ee-first/index.js:43:10)
    at onSocket (.../project/src/node_modules/on-finished/index.js:114:16)
    at attachFinishedListener (.../project/src/node_modules/on-finished/index.js:119:5)
    at attachListener (.../project/src/node_modules/on-finished/index.js:146:5)
    at onFinished (.../project/src/node_modules/on-finished/index.js:52:3)
    at SendStream.stream (.../project/src/node_modules/send/index.js:802:3)
    at SendStream.send (.../project/src/node_modules/send/index.js:708:8)
    at onstat (.../project/src/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:167:5)
```
node: v9.2.0
npm: 5.5.1

My code is a bit more involved because I'm embedding Fastify in a bigger application. The Fastify code only has one router tho:
```js
'use strict';
const path = require('path');

module.exports = async function routes(fastify, options) {
    console.log('dashboard.routes');

    fastify.get('/health', async function(req, res) {
        res.type('application/json').code(200);
        res.send({ status: 'ok' });
    });

    fastify.setNotFoundHandler(function(req, res) {
        res.sendFile('404.html');
    });

    fastify.register(require('fastify-static'), {
        root: path.join(__dirname, '../public'),
        prefix: ''
    });
  
    fastify.get('/', function(req, res) {
        res.sendFile('index.html');
    });
};
```
