### ISSUE TITLE
application/json parser should attach the raw body content

### ISSUE THREAD

**Issue by Imtnt** [fastify/fastify#794]
For signature verification purposes, I need the raw unparsed content of the body on a request using application/json.  Could either this be added to the built in parser, or could overriding the json parser be supported?

**Comment by jsumners** [comment]
See #785

**Comment by delvedor** [comment]
From the latest version ([`v1.0.0-rc.2`](https://github.com/fastify/fastify/releases/tag/v1.0.0-rc.2)) you can overwrite the default json parser, as shown [here](https://www.fastify.io/docs/latest/ContentTypeParser/).

**Comment by jsumners** [comment]
Closing because I think this has been answered. Please re-open if you have further questions.

**Comment by cyberwombat** [comment]
Can an example be posted of getting raw body?  Some things are unclear - "Fastify adds automatically the parsed request payload to the Fastify request object, you can reach it with request.body." - so what happens to the default JSON body that is already in `request.body`?  And how do I get this for just one route? 

I have tried (V 1.1.1) to add:
```
 function server (opts) {
  const fastify = Fastify(opts)
   fastify.addContentTypeParser('*', function (req, done) {    
      done(null, 'why no workie?')    
  })
  fastify.register(require('./services/auth'), { prefix: '/api/auth' })
  fastify.register(require('fastify-swagger'), swaggerOption)
 
```
as well as other variations. I have added this in many places but it is not ever called. I would expect `req.body` to have my new body but it does not. I'd love to see a working example of getting the raw body (and ideally not trash the existing json one)

**Comment by cyberwombat** [comment]
Ah... Ok I am thrown off by how light-my-request works.  If I do my payload like:
```
payload: {
      foo: 'hello'
    }
```
Then the contentTypeParser does not work (or at last the body that is available in the route is `{ foo: 'hello' }`. If, on the other hand, my payload in my test is `foo=hello` then the body in my route is ''why no workie?' as in above.  Is this intentional? I may be misunderstanding the process.
