### ISSUE TITLE
only pino supported as logger

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/fastify#799]
#### What are you trying to achieve or the steps to reproduce?

I wanted to try to use my custom logger, according to the documentation I can pass any, which matches the certain format.

> You can also supply your own logger instance. Instead of passing configuration options, simply pass the instance. The logger you supply must conform to the Pino interface; that is, it must have the following methods: info, error, debug, fatal, warn, trace, child.

Here is my code:
```js
const pino = require('pino')();
const logger = {};

Object.keys(pino.levels.values).forEach(level => {
    logger[level] = function() { 
        return pino.child({serviceName: 'serviceName', environment: 'test', '@timestamp': new Date().toISOString(), '@version': '1.0.0'})[level](...arguments);
}});

logger.child = pino.child.bind(pino);

const fastify = require('fastify')({logger});

logger.info('hello');
fastify.log.info('hello');
```
I believe problems are there because of `child` thing, but it doesn't work with the `noop` function or `pino.child` without any binding.

What have I missed? And how would you achieve the thing I need to achieve (throw in some common parameters to each log)?

#### What was the result you received?
```
{"level":30,"time":1519132914150,"msg":"hello","pid":95595,"hostname":"PP-MacBook-Pro.local","serviceName":"serviceName","environment":"test","@timestamp":"2018-02-20T13:21:54.150Z","@version":"1.0.0","v":1}
{"level":30,"time":1519132914152,"msg":"hello","pid":95595,"hostname":"PP-MacBook-Pro.local","v":1}
```
As you see, `fastify` logging is not going through the new `logger` for some reason.

#### What did you expect?
```
{"level":30,"time":1519132914150,"msg":"hello","pid":95595,"hostname":"PP-MacBook-Pro.local","serviceName":"serviceName","environment":"test","@timestamp":"2018-02-20T13:21:54.150Z","@version":"1.0.0","v":1}
{"level":30,"time":1519132914150,"msg":"hello","pid":95595,"hostname":"PP-MacBook-Pro.local","serviceName":"serviceName","environment":"test","@timestamp":"2018-02-20T13:21:54.150Z","@version":"1.0.0","v":1}
```

#### Context

* *node version*: 9
* *fastify version*: >=0.37.0
* *os*: Mac

**Comment by jsumners** [comment]
Your "expected" lines look very much like the second line of the "result received" example.

I don't the title is quite right. You are supplying a Pino instance, but one that you have modified. Fastify is dutifully using that logger as you have shown in your examples.

I don't understand this statement:

> I believe problems are there because of child thing, but it doesn't work with the noop function or pino.child without any binding.

Please show an example of what you mean.

**Comment by PavelPolyakov** [comment]
@jsumners 
Thanks for looking into the 2nd of my issues, I was wrong with copying expected result.

I expect that `fastify` will use `updated` logger, therefore in each of the logged events `serviceName`,`environment`, `@timestamp`, `@version` would be present. While the log which `fastify` does is "short", looks like it's done NOT by my logger object, but with the default one.

> I believe problems are there because of child thing, but it doesn't work with the noop function or pino.child without any binding.

if I do this:
```js
logger.child = pino.child;
// OR
logger.child = pino.child.bind(logger);
```
`fastify()` would not work and fail this way:
![image](https://user-images.githubusercontent.com/839290/36429813-e77cbd12-1653-11e8-972e-a2bbfa87bc36.png)

**Comment by nwoltman** [comment]
This isn't an issue with Fastify. The problem is with how you're creating a child logger.

```js
logger.child = pino.child.bind(pino);
```

That doesn't work because you're binding pino's `child` method to `pino`, so it will create a new child of `pino` and not a child of your `logger` object.

```js
logger.child = pino.child;
// OR
logger.child = pino.child.bind(logger);
```

That also doesn't work because you're trying to use pino's `child` method on your `logger` object, but that's not possible because the method expects to be called on a `pino` instance.

This can all be solved by using a `pino` child as your `logger` and replacing the default timestamp function with your own:

```js
function timestamp() {
    return ',"@timestamp":"' + new Date().toISOString() + '"';
}

const pino = require('pino')({timestamp});
const logger = pino.child({serviceName: 'serviceName', environment: 'test', '@version': '1.0.0'});
const fastify = require('fastify')({logger});

logger.info('hello');
fastify.log.info('hello');
```

Result:

```
{"level":30,"@timestamp":"2018-02-20T17:05:23.611Z","msg":"hello","pid":9528,"hostname":"your-hostname","serviceName":"serviceName","environment":"test","@version":"1.0.0","v":1}
{"level":30,"@timestamp":"2018-02-20T17:05:23.611Z","msg":"hello","pid":9528,"hostname":"your-hostname","serviceName":"serviceName","environment":"test","@version":"1.0.0","v":1}
```

**Comment by PavelPolyakov** [comment]
@nwoltman 
Thanks, this solves my issue with timestamp. Honestly I was searching for this in the docs, but thought these is only a dance around `time`.

But one question still remains, is it possible to provide a wrapper instead of the pino instance? It seems that `fastify` heavily relies on `pino`, especially it's `child` method (and further the road I saw the errors of missing `_setLevel` etc.

**Comment by jsumners** [comment]
The `_setLevel` error was internal to Pino because your wrapping broke the Pino instance.

As you quoted originally, Fastify supports any logger that matches the API of Pino. That includes having a `child` method.

**Comment by nwoltman** [comment]
@PavelPolyakov Yes it certainly is possible to provide a wrapper instead of a pino instance. Here's how you'd write your original example to make it work:

```js
const pino = require('pino')();
const logger = {pino};

Object.keys(pino.levels.values).forEach(level => {
    logger[level] = function() { 
        return this.pino.child({serviceName: 'serviceName', environment: 'test', '@timestamp': new Date().toISOString(), '@version': '1.0.0'})[level](...arguments);
    }
});

logger.child = function() {
    const child = Object.create(this);
    child.pino = this.pino.child(...arguments);
    return child;
}

const fastify = require('fastify')({logger});

logger.info('hello');
fastify.log.info('hello');
```

**Comment by PavelPolyakov** [comment]
@nwoltman @jsumners 
Thanks, you are the best!

Hope this thread helps somebody.
