### ISSUE TITLE
 HTTP.createServer().on('request', fastify) does not work

### ISSUE THREAD

**Issue by goriunov** [fastify/fastify#804]
Hello, i am just wondering if it is possible to use `fastify` together with `createServer()` from standard Node.js http/https, for example: 

```js
let server =  HTTP.createServer()

server.on('request', fastify) // That wont work

server.listen(8080)
```

If yes then how can i do it, and if no it would be good to have this functionality.

I know that we can do it with `express` and `koa`. Thank you.

**Comment by jsumners** [comment]
What benefit would that give?

**Comment by goriunov** [comment]
For example i will be able to use fastify with libraries such as socketcluster or clusterws (i am a developer of clusterws)

**Comment by nwoltman** [comment]
Fastify doesn't support that format because it's initialization process is asynchronous.

However, what you can do is use the [`fastify.server`](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#server) property:

```js
const Fastify = require('fastify')
const fastify = Fastify()

fastify.server // The HTTP Server
```

**Comment by goriunov** [comment]
That is not really appropriate solution unfortunately. But any way thank you.

**Comment by mcollina** [comment]
I think it should be possible to expose this through a promise/callback, or making this available _only after `ready()` is called.

@nwoltman @delvedor would that work for you?

**Comment by nwoltman** [comment]
That's certainly alright with me. @goriunov Would that solve your problem?

**Comment by goriunov** [comment]
Yes this will be good way, for example `koa` does the same  with `app.callback()
`

**Comment by mcollina** [comment]
PR?

**Comment by delvedor** [comment]
This has been closed in https://github.com/fastify/fastify/pull/937

**Comment by ayZagen** [comment]
This issue should be reopened.
serverFactory option doesn't work. I am trying to use socketcluster as @goriunov 

```node
serverFactory: (handler, opts) => {
  httpServer.on('request', (req,res) => {
        //all requests visits here but handler doesn't work!
        handler(req,res)
  })
  return httpServer
}
```

**Comment by mcollina** [comment]
Can you please upload a full example?
