### ISSUE TITLE
Add fastify-favicon to community plugins list

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#806]
Checklist
run npm run test and npm run benchmark
tests and/or benchmarks are included
documentation is changed or added
commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

**Comment by smartiniOnGitHub** [comment]
To ensure it really works (other than usual tests and example) I just used it in a sample webapp: [fastify-example](https://github.com/smartiniOnGitHub/fastify-example)

**Comment by smartiniOnGitHub** [comment]
Related PR is: [PR#807](https://github.com/fastify/fastify/pull/807)

**Comment by nwoltman** [comment]
Closing since #807 was merged.

**Comment by smartiniOnGitHub** [comment]
Thanks a lot :-)
