### ISSUE TITLE
Allow to use '*' (wildcard) in path to accept all routes

### ISSUE THREAD

**Issue by leesiongchan** [fastify/fastify#81]
Why isn't this been implemented? Are there any catches that I might have been missed out?

```javascript
fastify.get('*', handler)
```

**Comment by delvedor** [comment]
Wildcards are implemented, but looks like that in your case we must improve usability.
This solves your issue for the moment:
```js
fastify.get('/*', handler)
```
*The above wildcard will catch everything except `/`.*

**Comment by delvedor** [comment]
Closed by #114
