### ISSUE TITLE
Shorthand routes options support handler function

### ISSUE THREAD

**Issue by shuperry** [fastify/fastify#810]
Can we support handler in options at Shorthand routes.

**Comment by mcollina** [comment]
I'm a bit lost why this is needed. It is possible to add such support, but I do not know why it would be good to do so.

**Comment by shuperry** [comment]
When handler can put into options, and we collapse code, our code will be much more cleaner like this:/Users/perry/Desktop/D680BE75-D62A-4F85-9B30-3A30FE542D18.png

**Comment by mcollina** [comment]
This is something easy, maybe would you like to do a PR?

**Comment by shuperry** [comment]
All right, I will do a PR.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/843
