### ISSUE TITLE
reply.serialize() is untested

### ISSUE THREAD

**Issue by nwoltman** [fastify/fastify#825]
Currently, there is only one test that touches `reply.serialize()` and all it does is check that it's a function.

https://github.com/fastify/fastify/blob/bebddc5817d6e23c4a802d9449525f27b618e65a/test/internals/reply.test.js#L22

**Comment by Ethan-Arrowood** [comment]
Can I give this a shot?

**Comment by nwoltman** [comment]
@Ethan-Arrowood Of course! :)
