### ISSUE TITLE
Logger responseTime is null on 1.0.0-rc.3

### ISSUE THREAD

**Issue by MathieuDoyon** [fastify/fastify#826]
on *version 1.0.0-rc.3* the logger responseTime return null.

this line return `undefined` instead of the current time
https://github.com/fastify/fastify/commit/f545accb2976d54a63a573cc187a0b0472cba972#diff-20da0b6140a4768d182af0d9b185ac28R208

```js
const fastify = Fastify({
  logger: true
});
```

**Comment by mcollina** [comment]
cc @allevo

**Comment by mcollina** [comment]
Good spot!
