### ISSUE TITLE
Extendable response received logs

### ISSUE THREAD

**Issue by thearegee** [fastify/fastify#830]
When using Fastify logging with level set to `info` on a request you get both `incoming request` and `request completed`.

`request completed` contains a responseTime metric (although currently has a bug https://github.com/fastify/fastify/issues/826)- this could be useful for reporting on application performance per route. However it currently doesn't contain the URL, this can be found within the `incoming request`you can Identify the two with `reqId` but it makes it a little harder to connect these two things together. It would be nice if you could give the request a key, so you can group together certain types of metrics without the need for the full url.

What would be preferable would be if I could create a custom log with some of the data from both `incoming request` and `request completed`, which could look something like:

```JSON
{
  "msg": "Custom message",
  "url":"/en-gb/test",
  "key": "custom key",
  "res": { "statusCode": 200 },
  "responseTime": 125,
}
```

Also setting your own logging level so it doesn't have to be `info`.

**Comment by mcollina** [comment]
This seems to ask for three different things at the same time:

* [ ] expose `res._responseTime` as a more consumable API
* [ ] provide a flag to change level of the default request logging
* [ ] document how to use the above two points inside an hook to actually do custom logging

Most of those would qualify as good-first-issue, so would you like to send a PR?

**Comment by thearegee** [comment]
@mcollina sounds great, will look into it, might need pointing in the right direction

**Comment by mcollina** [comment]
@thearegee let me know if you have specific questions, or just open a quick PR with your ideas if it's easier to flash out in code.

**Comment by thearegee** [comment]
Ok great... I'm going to implement the feature that will use it, then work on this.

**Comment by thearegee** [comment]
@mcollina what do you think about me adding in the url into request complete:

```
$: request completed
     reqId: 1
     res: {
       "statusCode": 200
     }
     responseTime: 331.17247700691223
```

Adding in url (currently in incoming request)and the statsId (https://github.com/fastify/fastify-routes-stats/pull/5), so would look like this:

```
$: request completed
     reqId: 1
     res: {
       "statusCode": 200
     },
     url: "/my/path/here",
     statsId: "my-custom-grouping",
     responseTime: 331.17247700691223
```

I feel like with `fastify-routes-stats` - this is no longer needed but thought would check incase anyone wants to be able to easier log and graph on every request.

So I think this could just be closed.

**Comment by mcollina** [comment]
Closing then!
