### ISSUE TITLE
Cannot set multiple headers of the same name

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#834]
After this change: https://github.com/fastify/fastify/blame/5c29591ed64618b7428e0ccf8158d84c539e84b1/lib/reply.js#L83-L86

It is impossible to set multiple instances of the same header name. In turn, this makes impossible to send multiple cookies in one request (a totally valid thing to do). Additionally, it also makes the following check always return false -- https://github.com/fastify/fastify-cookie/blob/53378e8d3d7617c8b2ed4d8a16b2b4c0dde7606d/plugin.js#L13-L17

So we need two things:

1. We need to be able to define the same header multiple times
2. We need `getHeader` and `hasHeader` methods on `Reply`

#### Context

* *node version*: 8
* *fastify version*: 1.0.0
* *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a PR for this?

**Comment by vegerot** [comment]
As of 31c5f7e this works for `Set-Cookie`, but I want to add multiple [Server-Timing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) headers.  How would I add multiple `Server-Timing` headers?

**Comment by jsumners** [comment]
Please open a new issue.
