### ISSUE TITLE
Serialization and arrays

### ISSUE THREAD

**Issue by vforv** [fastify/fastify#835]
Some of my responses should return array, like this:

```
const responseList = {
    200: {
        description: 'Successful response result is array of objects',
        type: 'array',
        properties: {
            result: {
                type: 'object',
                properties: {
                    example: { type: 'string' },
                },
            },
        },
    },
};
```

this is schema response validator.

but when I put type as array I am getting error:

> node_modules/fast-json-stringify/index.js:521
>   if (schema.items['$ref']) {
>                   ^
> TypeError: Cannot read property '$ref' of undefined

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
I suggest you to read [understanding-json-schema](https://spacetelescope.github.io/understanding-json-schema/reference/array.html), it is a nice guide!
When declaring an array you **must** use the `items` property:
```js
const responseList = {
  200: {
    description: 'Successful response result is array of objects',
    type: 'array',
    items: {
      type: 'object',
      properties: {
        result: {
          type: 'object',
          properties: {
            example: { type: 'string' }
          }
        }
      }
    }
  }
}
```

**Comment by vforv** [comment]
Thanks, I will check it.
