### ISSUE TITLE
Out schema for non 2xx response

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#84]
Currently the out schema is applied to every response.
Is there a way to set a "global" out schema for all non 2xx request?
Or apply the out schema only to the 2xx response?
Any suggestions?

**Comment by delvedor** [comment]
Hi, thank you for the interest!
The `out` schema is not applied to all the routes, but only in the routes where you pass it as parameter.
Example:
```js
fastify.get('/no-schema', (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.get('/schema', {
  out: {
    type: 'object',
    properties: {
      hello: { type: 'string' }
    }
  }
}, (req, reply) => {
  reply.send({ hello: 'world' })
})
```
The out schema is applied in every case, not matter of the status code and there is no way to set it for all the routes. However, you could save it in a variable and pass it to all the routes.
```js
const schema = {
  out: {
    type: 'object',
    properties: {
      hello: { type: 'string' }
    }
  }
}

fastify.get('/route', schema, (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.get('/other-route', schema, (req, reply) => {
  reply.send({ hello: 'world' })
})
```
If you want to use an out schema for the "correct" response and support also a completely different object, you must use the [`.serializer`](https://github.com/fastify/fastify/blob/master/docs/Reply.md#serializer) method of reply, that forces reply to use a custom serializer.
Example:
```js
const schema = {
  out: {
    type: 'object',
    properties: {
      hello: { type: 'string' }
    }
  }
}

fastify.get('/route', schema, (req, reply) => {
  if (someError) {
    reply
      .serializer(JSON.stringify)
      .send({ error: 'message' })
    return
  }
  reply.send({ hello: 'world' })
})
```
___
@mcollina could be a nice idea support different output schema based on the status code, it will be useful for the swagger generator as well :)

**Comment by allevo** [comment]
Maybe a replacement for default serializer is enough.

I'd like to be sure to have all my 5xx and 4xx response bodies with the same structure.

**Comment by mcollina** [comment]
@delvedor I'm +1 on the idea.

**Comment by allevo** [comment]
Can we declare a specification for this issue ?

Maybe the `out` key could be used only for 200 and, if specified, the `out500` or `out5xx` could be used for 5xx responses.

In that way, the back compatibility is kept.

Let me know if this approach is fine for you

**Comment by mcollina** [comment]
@allevo the approach is fine for me.. @delvedor what do you think?

**Comment by delvedor** [comment]
Since we must support also [swagger](https://github.com/fastify/fastify-swagger), i think the best (and more elegant) solution will be something like:
```js
out: {
  '200': {},
  '500': {}
}
```
And so on.
Maybe we can rename `out` in `response`.
Since we are building the schema at compilation time we can check if the user is passing directly the schema or the different status codes, and create the function(s) accordingly.
An even better solution could be:
```js
out: {
  '2xx': {},
  '4xx': {},
  '404': {}
  '5xx': {}
}
```

**Comment by mcollina** [comment]
I'm 👍  with the change, the only things I do not like is that we need `'`?

**Comment by delvedor** [comment]
My bad, I thought that use numbers as key in objects was incorrect, but I was wrong :D

**Comment by mcollina** [comment]
@allevo, would you like to fire up a PR?

**Comment by allevo** [comment]
@mcollina I'll start as soon as possible

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/96.
