### ISSUE TITLE
require querystring

### ISSUE THREAD

**Issue by rabbitmeow** [fastify/fastify#840]
hello? how to do that?

**Comment by mcollina** [comment]
it is not clear what you want to achieve. Can you please make an example?

**Comment by rabbitmeow** [comment]
```js
schema: {
            querystring: {
                remember: { type: 'boolean' }
            },
            body: {
                type: 'object',
                properties: { username, passwd },
                required: ['username', 'passwd']
            }
        }
```
I want property remember also be required.

**Comment by delvedor** [comment]
You should use the full json schema declaration.
```js
const schema = {
  querystring: {
    type: 'object',
    properties: {
      remember: { type: 'boolean' }
    }
    required: ['remember']
  }
}
```

**Comment by rabbitmeow** [comment]
oops, I thought querystring cannot be set to object because it's not a json. Thank you.

**Comment by delvedor** [comment]
When you access the request `query` object you are accessing an `Object`.
The json schema defines that object, you used the shorthand version, but you can always use the full declaration.
