### ISSUE TITLE
use the library Netxjs and i18next with fastify

### ISSUE THREAD

**Issue by torloneg** [fastify/fastify#842]
hi
I am trying to use the library  i18next, nextjs into a fastify project

i'm new on fastify, i found this example with express
https://github.com/zeit/next.js/blob/canary/examples/with-react-i18next/server.js

How can I replace the function *use* in fastify ??

   // enable middleware for i18next
        server.use(i18nextMiddleware.handle(i18nInstance))

**Comment by delvedor** [comment]
As you can see from our [documentation](https://github.com/fastify/fastify/blob/master/docs/Middlewares.md), we do support `express` middlewares.
If it does not work for you, you can [write a fastify plugin](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md).

If you have never used Fastify before, you can read our [getting started](https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md) guide.

**Comment by torloneg** [comment]
work fine !
Thank you very much

**Comment by Sionarch** [comment]
Hi. As I couldn't get the i18next-express-middleware working, I implemented it as a Fastify plugin: [fastify-i18next](https://www.npmjs.com/package/fastify-i18next)

**Comment by Eomm** [comment]
Hi @Sionarch, it would be great if you could add some tests and a CI check to add your plugin to the [ecosystem](https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md) 💪
