### ISSUE TITLE
Real 404 Errors Get Lost

### ISSUE THREAD

**Issue by nwoltman** [fastify/fastify#848]
#727 was implemented mainly so that 404 errors on streams from the `send` module could cause the not-found handler to be invoked (which helped complete the API for `fastify-static`). This also introduced a new API where users could manually invoke the not-found handler by "sending" a 404 error:

```js
reply.send(Object.assign(new Error(), { status: 404 }))
```

However, [this comment](https://github.com/fastify/fastify/issues/844#issuecomment-372870211) from #844 shows that some users are throwing "real" 404 errors and would like to be able to handle the error with their error handler. Currently, all errors with a 404 status are sent directly to the not-found handler so the error is completely lost.

Some possible solutions could be:

1. Log the error before invoking the not-found handler.
   + This might not be enough for everyone, since some users may want to use information in the error to create their response.
2. Pass the error to the error handler just like any other error and let the user deal with it however they like.
   + Could also bring back the `reply.notFound()` method if doing this.
3. Pass the error as a third parameter to the not-found handler.
   + `fastify.setNotFoundHandler(function (request, reply, error) { })`
4. Do nothing

**Comment by mcollina** [comment]
I think things should be left as they are. The notFound handler is generic, and the problem you are describing is route-specific, so I think the route-specific behavior should be handled within the route itself. This stands also from a REST perspective, as the notFound handler would have the request path.

**Comment by nwoltman** [comment]
@edsamonte care to weigh in? You already have access to the request path (`request.raw.url`) in your not-found handler.

**Comment by edsamonte** [comment]
I'm not really an expert in REST API designs but would love to share my two-cents. In my case, I'm using a Service-layer approach:
Controllers -> Services -> Repositories

Say for example, you want to add a pair of two models through a pivot table: A _User_ using an third-party _Client_ wants to add a _Pet_. Normally we have a table called `user_pets`, which has related keys to `users` and `clients`. Whenever there's a request, I personally don't want to put the info directly to the `user_pets` table; I would want to check if the _User_ exists, the _Pet_ exists and the _Client_ exists, before pairing. (I don't want to rely on the MySQL thrown integrity error). In that case, if any of those does not exists, I have to throw an error of `ResourceNotFound`. 

In my approach, the controller only expects a result and not an error. I put the error handling to the `setErrorHandler` so I can have a better representation of the error:
```js
{
  "code": "ResourceNotFound",
  "message" "Pet does not exists"
}
```
```js
{
  "code": "ResourceNotFound",
  "message" "User does not exists"
}
```

If I have to catch every 404 errors (i.e. ResourceNotFound, NotFound, PageNotFound) thrown by the services on the controller side, then 1) it would be tedious to do it every time; and; 2)it would defeat the purpose of having a centralized error-handler for me. And, passing the reply object to services is not a good idea.

**Comment by edsamonte** [comment]
As per [Wikipedia](https://en.wikipedia.org/wiki/HTTP_404), 404 is missing resource. A resource could be anything (i.e. User, Pet, Client). I guess it would be best to *describe* to the API consumer what is missing rather than just a generic 404 especially if you have a REST docs saying that the endpoint really exists.

**Comment by jsumners** [comment]
It is correct to interpret a 404 as the resource, _not_ the endpoint, being missing. But that would be if the same endpoint can point to multiple resources, e.g. `/foo?query=bar`. To solve that problem, the route should be something like `/foo/bar`. In this case, a generic 404 imparts all of the necessary information: `bar` does not exist.

**Comment by edsamonte** [comment]
I would somehow agree with @jsumners. But for a case like `/foos/1/bars/20`, in the current framework structure, it is hard to know if it is a _foo_ resource that is missing or a _bar_. 

Also, there are cases you would want to stick with max of 2 levels for URLs. Which means that 3 or more related resource would complicates the URL (i.e. `/clients/1/users/20/pets`). So for this case, you might want to put, for instance, the `clientId` on the POST request instead of the URL. Just a rough example.

**Comment by jsumners** [comment]
`/foos/1/bars/20` is supposed to uniquely identify a resource. Therefore, it doesn't matter which part of the path is "not found," only that the unique resource requested cannot be found.

**Comment by edsamonte** [comment]
@jsumners, I do agree with that. But would it make sense to add a little more "context" to the error rather than just a plain not-found message?

```js
{
  "code": "ResourceNotFound"
}
```
versus
```js
{
  "code": "ResourceNotFound",
  "message" : "Foo does not exists"
}
```

**Comment by edsamonte** [comment]
And by the way, we're not only pertaining to GET method. It should also apply to POST/PATCH/PUT methods as well which does not uniquely identify a resource (i.e. `/clients/10/users/20/pets`).

**Comment by jsumners** [comment]
I'm merely commenting on your reference to what a 404 really means. For me, receiving a 404 status code is enough. But I can understand why you would want to display a standardized error JSON response.

I'm not very clear on the APIs involved here, so I'm not trying to voice any support for one method or another.

**Comment by nwoltman** [comment]
From the perspective of an API user, the extra error information could be pretty helpful:

+ `404 Not Found: /clients/10/users/20/pets`
  + "Why am I getting a 404? My code seems right..."
+ `404 Not Found: /clients/10/users/20/pets - User does not exist`
   + "Why does the user not exist? Oh I'm using the wrong ID!"

**Comment by mcollina** [comment]
@nwoltman I agree on that point, however from a code perspective you will end up with:


```js
function notFound (request, reply, err) {
  if (err instanceof MissingPet) {
  // ...
 } else if (err instanceof MissingClient) {
  // ...

 } else if (err instanceof MissingUser) {
  // ...
 }
}
```

It creates a brittle dependency between a generic component (the not found or error handlers) and route-specific things. This pattern should be discouraged and not encouraged.
(It is possible to do it right now with the error handler already, and it's a part that I do not necessarily like - even thought I do not have a better proposal just yet)

**Comment by delvedor** [comment]
Personally I think that the current behaviour is confusing.
```js
const fastify = require('fastify')()

fastify.get('/', (req, reply) => {
  const err = new Error('User not found')
  err.statusCode = 404
  reply.send(err)
})

fastify.get('/404', (req, reply) => {
  const err = new Error('User not found')
  reply.code(404).send(err)
})

fastify.inject('/', (err, res) => {
  if (err) throw err
  console.log(res.payload)
  // {"statusCode":404,"error":"Not Found","message":"Not found"}
})

fastify.inject('/404', (err, res) => {
  if (err) throw err
  console.log(res.payload)
  // {"statusCode":404,"error":"Not Found","message":"User not found"}
})
```
I think is confusing because if a just use another status code the payload will be the same
```js
const fastify = require('fastify')()

fastify.get('/', (req, reply) => {
  const err = new Error('User not found')
  err.statusCode = 400
  reply.send(err)
})

fastify.get('/404', (req, reply) => {
  const err = new Error('User not found')
  reply.code(400).send(err)
})

fastify.inject('/', (err, res) => {
  if (err) throw err
  console.log(res.payload)
  // {"statusCode":400,"error":"Bad Request","message":"User not found"}
})

fastify.inject('/404', (err, res) => {
  if (err) throw err
  console.log(res.payload)
  // {"statusCode":400,"error":"Bad Request","message":"User not found"}
})
```

Have this edge case is really confusing and I don't think we are handling it correctly.
Personally I prefer to have a custom api to call the 404 handler, such as `reply.notFound` or `reply.callNotFound` and leave the error work as expected.

**Comment by mcollina** [comment]
This behavior allows us to support the send() module and be generally more compatible with Express. In other terms, fastify-static relies on this heavily.
I’m not necessarily fond of this, but I do not think removing this functionality helps Fastify in any way, as it makes harder to move applications to Fastify.

Possibly, our default for a 404 is not a good one as well.

**Comment by delvedor** [comment]
> I’m not necessarily fond of this, but I do not think removing this functionality helps Fastify in any way, as it makes harder to move applications to Fastify.

I don't think we should remove it, but we should be more flexible.
```js
fastify.setNotFoundHandler(function (err, request, reply) { // same of `setErrorHandler`
  reply.code(404).send(err)
})
```
In this way the user can overwrite the default message and send one of its own.
Usually the 404 status is ok, but maybe a user wants to display a custom user friendly message from the server (which is the reason of the `message` field in the error responses).

**Comment by mcollina** [comment]
```js
fastify.setNotFoundHandler(function (err, request, reply) { // same of `setErrorHandler`
  reply.code(404).send(err)
})
```

Will lead to:


```js
fastify.setNotFoundHandler(function (err, request, reply) { // same of `setErrorHandler`
  if (..) { ... }
  else if (...) { ... }
  // 242 else if later
  else {
    reply.code(404).send(err)
  }
})
```

Also, are we __always__ passing a Error here, even when the routing is not matching?

**Comment by delvedor** [comment]
> Also, are we always passing a Error here, even when the routing is not matching?

We should always pass an error, if a route is not matching a `new Error('Not Found')` is enough.

I think we need to fix this, even if the solution is not the best one.
Currently a client has not way to know if the error is a 404 because it mistyped the route or because the data it's searching for is not present.

**Comment by delvedor** [comment]
We are doing it in any case.
https://github.com/fastify/fastify/blob/47f295f605d98ddc9dffec3a2ec3cd204b613f0a/fastify.js#L715-L717

If you have a better solution I'm all ears!

**Comment by mcollina** [comment]
Did we reach some conclusion here?  This issue is rather long, and I would like either a) get a PR b) close it.

**Comment by mcollina** [comment]
If you all agree that we should pass the error to `notFound`, that's ok for me.

**Comment by nwoltman** [comment]
That's not my favourite approach, but that's probably better than doing nothing.

**Comment by mcollina** [comment]
@nwoltman what would be your favourite approach?

**Comment by nwoltman** [comment]
I would prefer for all errors passed to `reply.error()` to go to the error handler (`fastify.setErrorHandler()`). That keeps the error API consistent.

Passing 404 errors to the not-found handler helps make Fastify and `fastify-static` compatible with the `send` module, but in general the `send` module is not very compatible with Fastify and we've had to add a bunch of hacks to make it work properly. Supporting the `send` module directly in Fastify isn't the best idea, so I don't think it's useful to keep the 404 errors feature around for the `send` module.

Addionally, I think it would be strange for the not-found handler to always receive an error object, especially for requests that didn't match a route. In that case, there wouldn't be much of a difference between the error handler and the not-found handler (so if we did do that, maybe we wouldn't need the not-found handler anymore).

**Comment by mcollina** [comment]
Basically you are proposing that all errors passed to `reply.send(err)` to got to the error handler? And we add back a `reply.notFound()` to route it to the not found handler (which is shared by the router)?

**Comment by nwoltman** [comment]
Yes. So that would be #__2__ from the original issue description.

**Comment by mcollina** [comment]
I'm happy to get a resolution on this issue.
I'm happy with 2 or 4 (do nothing).

**Comment by nwoltman** [comment]
Option 2 be a semver-major change. What does everyone think @fastify/fastify?

**Comment by delvedor** [comment]
👍 for solution **2** for the next major an **4** for the current version.

**Comment by jsumners** [comment]
I concur with @nwoltman in https://github.com/fastify/fastify/issues/848#issuecomment-396370631.

**Comment by sarneeh** [comment]
I've also just stumbled upon this issue and I do agree that having the ability to handle all the errors in the `errorHandler` and just having a `.notFound()` method for the `notFoundHandler` would be great 👍 

Btw. Do you have any plans/estimates when will the next major come live?

**Comment by mcollina** [comment]
@delvedor would you like to get a PR in for "solution 2"? Or maybe someone else?

@sarneeh when it's ready :D. Expect some release candidates before that.

**Comment by cyberwombat** [comment]
I'm using 1.12.x - seems like these changes have been merged but I am not sure how it's supposed to work. The notFound error swallows all my messages and replaces them with 'Not Found'. 
```
fastify.get('/throw', async (req, reply) => {
    reply.notFound('I will never ever find out about this...!')
  })
```
Results in this in the log
```
reqId: 1
    res: {
      "statusCode": 404
    }
    err: {
      "type": "Error",
      "message": "Not Found",
      "stack":
          Error: Not Found
```
I have tried setting the `setNotFoundHandler` but there is only a reply and request and nothing about the error that was thrown. Can you elucidate on how I am supposed to log or return my custom  message?

**Comment by sarneeh** [comment]
@cyberwombat This change has been merged to the `next` branch which aims for `fastify@2.0.0` version. Fastify team - correct me if I'm wrong.

**Comment by delvedor** [comment]
@sarneeh you are correct :)

**Comment by Marsup** [comment]
Does it really need to wait for 2.0? Any way to work around this in 1.x?

**Comment by mcollina** [comment]
@Marsup it's semver-major :/. I hope we can get a release candidate out as soon as possible. That changes break quite a few of our plugins unfortunately.

**Comment by Marsup** [comment]
Thanks for the quick response. So 1.x is stuck with this with no possible workaround? (I'm not complaining, just asking :slightly_smiling_face:)

**Comment by mcollina** [comment]
Yes and it’s essentially my fault as we had a very similar behavior in the beginning.
This breaks fastify-static specifically.

**Comment by delvedor** [comment]
@mcollina is not your fault, we all agreed on that change in https://github.com/fastify/fastify/pull/727 :slightly_smiling_face: 
Back then it seemed a good idea, and the time has revealed the contrary. We have already fixed it, and v2 will be out really soon.
Make everything right at the first try is not just impossible but also weird :wink:

**Comment by delvedor** [comment]
Fastify v2 has just been published :)
