### ISSUE TITLE
Should we handle uncaught errors in handlers?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#850]
I encountered a tricky problem earlier. I made a change that caused this test in my project to fail: https://github.com/jscas/cas-server/blob/fastify/test/integration/v3server.test.js

The failure was caused by https://github.com/jscas/cas-server/blob/41ae00c81d4176b624f451a05b61091346f9dff9/lib/routes/login.js#L16-L18

This conditional caused the following stack to be thrown:

```
test/integration/v3server.test.js _http_server.js:194
     throw new RangeError(`Invalid status code: ${originalStatusCode}`);
     ^
 RangeError: Invalid status code: undefined
     at ServerResponse.writeHead (_http_server.js:194:11)
     at onSendEnd (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/fastify/1.1.1/node_modules/fastify/lib/reply.js:194:7)
     at wrapOnSendEnd (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/fastify/1.1.1/node_modules/fastify/lib/reply.js:155:5)
     at next (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/fastify/1.1.1/node_modules/fastify/lib/hookRunner.js:43:7)
     at cache.set (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/fastify-server-session/2.0.0/node_modules/fastify-server-session/plugin.js:90:9)
     at Object.set (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/abstract-cache/1.0.1/node_modules/abstract-cache/lib/memclient.js:45:5)
     at storeSession (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/fastify-server-session/2.0.0/node_modules/fastify-server-session/plugin.js:77:18)
     at /Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/uid-safe/2.1.5/node_modules/uid-safe/index.js:90:5
     at RandomBytes.onRandomBytes [as ondone] (/Users/jsumners/Projects/oss/CAS/cas-server/node_modules/.node.int.clayton.edu/random-bytes/1.0.0/node_modules/random-bytes/index.js:97:22)
```

This was tricky to figure out because, due to the way the test has to be constructed, the code causing the error was being run in a `child_process.fork`. And the actual stack doesn't correspond to what was causing the issue. The actual issue was the fact that `req.query` does not have the `hasOwnProperty` method since it is an `Object.create(null)` object.

This could be handled by wrapping each invocation of the handler in a `try/catch` and returning a `500` if an error is caught:

https://github.com/fastify/fastify/blob/70ac47ab8a74d1be753fc82872b02c6fa5d9264c/lib/handleRequest.js#L13-L54

The question is, do we want to do this?

**Comment by delvedor** [comment]
I don't like the idea to wrap the entire handler inside a try catch, because we will certainly deoptimize the code. Furthermore what we should catch? Every errors? Only RangeError? Syntax?
We have discussed this in https://github.com/fastify/fastify/pull/617.
For now my opinion is to leave it as is, but I'm open to change my mind.

It's strange the error that you are getting in `req.query`, we never initialize it as `Object.create(null)`. Right?

**Comment by jsumners** [comment]
It's set in two places:

https://github.com/nodejs/node/blob/96cb4fb795808aa2774e842974aeb411c5d3dd94/lib/url.js#L432
https://github.com/nodejs/node/blob/96cb4fb795808aa2774e842974aeb411c5d3dd94/lib/querystring.js#L262

I do wish people would stop creating objects that way.

I'm really not sure what to do. I was clearly not expecting this error to occur. And it was very difficult to track down because the stack trace had nothing to do with the actual error; I was investigating the `onSend` hook firing off before it should be.

**Comment by mcollina** [comment]
I think that the bug we should fix is why the stacktrace was not the correct one.
I’m -1 on adding that, as we cannot catch all errors if the user is not using async/await.

**Comment by cortopy** [comment]
I was just revising the error handler for my application, and I bumped into this issue. It seems errors in handlers are not handled at all.

A typo like this would cause the whole application to crash and a reboot of fastify would be required:

```js
fastify.route({
  method: 'GET',
  url: '/',
  schema: {
    querystring: {
      name: { type: 'string' },
      excitement: { type: 'integer' }
    },
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: function (request, reply) {
    // simple typo mistake leading to undefined method
    reply.ssend({ hello: 'world' })
  }
})
```
At a more general level doing this also causes the application to crash:

```
function (request, reply) {
    throw Error("some sync operation caused an error")
    reply.send({ hello: 'world' })
  }
```

I guess fastify could be launched with something like [forever](https://www.npmjs.com/package/forever) to avoid the try/catch solution, but I wonder if this should be isolated internally. Requests that error may be dropped, but shouldn't the application self-heal somehow?

**Comment by mcollina** [comment]
It shouldn't. if it crashes in this way, you will likely be leaking memory or file descriptor, and your application will start to misbehave. You can use async/await instead, and that correctly wraps things, as long as you await promises.

**Comment by mcollina** [comment]
I would recommend you to try throwing in an express route. Your process will crash.

Fastify works very similarly to what all the others do. If you are using callbacks, you need to pass the error to send(). If you are using promises, this is handled for you.

**Comment by mcollina** [comment]
The docs can be clearer, would you like to send a PR?

**Comment by cortopy** [comment]
I just tried with an express application where an error handler is registered using `server.use` to be sure. It didn't crash, but returned a 500.

I would happily send a PR but I just don't understand how fastify handles errors, since the global error handler won't always get called

**Comment by mcollina** [comment]
How do you throw an error with express?

**Comment by cortopy** [comment]
I did: 

```js
export function testController(req, res, next) {
  throw Error("An error")
}
```

**Comment by nwoltman** [comment]
Looks like express uses a `try-catch`:
https://github.com/expressjs/express/blob/3ed5090ca91f6a387e66370d57ead94d886275e1/lib/router/layer.js#L94-L98

**Comment by mcollina** [comment]
Interesting, I didn't know! However

```js
export function testController(req, res, next) {
  setTimeout(() => throw Error("An error"), 500)
}
```

will crash your process.

This lead to a lot of unexpected crashes, because express taught its user that they were catching some errors. To me, it's either you catch them all or you don't catch any. Because of the domain snafu we cannot really catch them all right now, so it's way better to not catch any errors (see https://nodejs.org/en/docs/guides/domain-postmortem/).

The best thing you can do if you get an unexpected error is to crash.

**Comment by cortopy** [comment]
Thanks @nwoltman and @mcollina ! This is what I needed to understand what's going on. I would like to write a section on error handling in fastify if I may. But I have a couple of questions first.

I think it would useful to compare fastify with Express since most people would have it as a reference. Would you say this would be an accurate description to start with?

> Because of legacy domain limitations in node it's not possible to process all uncaught errors in a sensible way. Express chose to catch sync errors by wrapping methods within a try/catch. However, uncaught async errors (promises, async/await, etc.) won't be handled for now.
> 
> Fastify follows a more all-or-nothing approach, whereby until processing all uncaught errors is possible, the developer is responsible for making sure errors are handled properly. This may involve wrapping every single method, middleware and plugin function with try/catch blocks and passing the error to the function's callback. This way fastify will, in turn, pass it to the registered error handler.

I'm not too sure what the best practice would be for the last bit. I can see Express handles this in the Layer prototype of routers. Can the development of a fastify plugin for this be recommended? Otherwise, what would be a recommended best practice?

**Comment by mcollina** [comment]
Fastify follows a more all-or-nothing approach, whereby until processing all uncaught errors is possible, the developer is responsible for making sure errors are handled properly. We recommend not to wrap every route in a try-catch, and actually fix programmer errors. Application errors should be catched and handled properly: most of those are a result of unexpected input data, so we recommend to specify a JSON.schema validation (link) for your input data.

**Comment by cortopy** [comment]
I'm sorry but I still don't see how that's best practice. Somehow it reads as if the recommendation is: "in order to handle bugs please make sure there are none".

I can imagine many situations where "fixing programming errors" is just not possible like, for example, when the error is in a npm dependency out of the control of the developer.

**Comment by mcollina** [comment]
I think this discussion has gone its course, feel free to reopen if you think otherwise.
