### ISSUE TITLE
Missing payload should return 400 not 500

### ISSUE THREAD

**Issue by cyberwombat** [fastify/fastify#856]
I am running some tests and this is my schema:

```js
const forgotPasswordSchema = {
  schema: {
    body: {
      type: 'object',
      require: [ 'token', 'password' ],
      properties: {
        token: { type: 'string' },
        password: { type: 'string' }
      },
      additionalProperties: false
    },
    response: {
      204: {
        type: 'null',
        additionalProperties: false
      }
    }
  }
}
```

My test code:
```
 const response = await fastify.inject({
    method: 'POST',
    url: '/api/auth/reset'
    // payload: {
    //   token: fixtures.users[1].token,
    //   password: 'passw0rd'
    // }
  })
```

I would expect this to return a 400 error which is what I get if I pass either an empty payload or missing parameters. However this yields a 500 so I suspect there is something breaking when no payload object is found.

So:
```
payload: {} // 400
payload: { foo: 'bar' } // 400
no payload defined // 500
````

* *node version*: 9
* *fastify version*: 1.1.1
* *os*: Mac

**Comment by mcollina** [comment]
Can you please upload a full example to reproduce, using inject would be fantastic.

**Comment by cyberwombat** [comment]
Argh... Seems ok when I reproduce. Must be something in my more complex code. Ill reopen if I can recreate easily. Sowee bout that.
