### ISSUE TITLE
addContentTypeParser and hasContentTypeParser missing from TypeScript definitions

### ISSUE THREAD

**Issue by ShogunPanda** [fastify/fastify#858]
#### What are you trying to achieve or the steps to reproduce?

Being able to write:

```typescript
fastify.addContentTypeParser('multipart', () => {})
```

in a Typescript file

#### What was the result you received?

`Property addContentTypeParser does not exist on type FastifyInstance``

#### What did you expect?

No errors

**Comment by mcollina** [comment]
Would you mind sensing a PR for this?

**Comment by ShogunPanda** [comment]
Yup, will try to send it today.
