### ISSUE TITLE
Second 'close' listener receive fastify instance

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#867]
As titled. For me, it feels like a bug. I think this is the case https://github.com/mcollina/avvio/blob/master/boot.js#L317
I expect that both functions have the same interface.

```js
'use strict'

const fastify = require('../fastify')()

fastify
  .get('/', function (req, reply) {
    reply
      .send({ hello: 'world' })
  })

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)

  fastify.close((err) => {
    console.log('close 1')
    console.log(err instanceof fastify.constructor)
  })
  fastify.close((err) => {
    console.log('close 2')
    console.log(err instanceof fastify.constructor)
  })
})

/*
server listening on 3000
close 1
true
close 2
false
*/
```

**Comment by jsumners** [comment]
I'm confused. Why are you invoking `.close()` twice?

**Comment by StarpTech** [comment]
I'm not talking about a use case it's handled by avvio.

**Comment by jsumners** [comment]
Huh?

**Comment by StarpTech** [comment]
Fastify based on avvio and in avvio it is allowed to add multiple close listeners.

**Comment by jsumners** [comment]
What is your point? Fastify _uses_ avvio, it isn't based upon it per se. In Fastify sending multiple `.close()` calls is wrong.

**Comment by StarpTech** [comment]
My point is that we don't handle that. I expect an error and in avvio I expect the same interface.

**Comment by StarpTech** [comment]
It's totally valid to define multiple `close` handlers because avvio provided it.
After https://github.com/mcollina/avvio/pull/56 we can close this issue.

**Comment by StarpTech** [comment]
> What is your point? Fastify uses avvio, it isn't based upon it per se. In Fastify sending multiple .close() calls is wrong.

@jsumners a `close` handler is just an `onClose` hook with the difference that the **close** routine is triggered and some parameters differ. That's why it's legitimate.

**Comment by allevo** [comment]
From my point of view, this behaviour is right: your code is closing fastify twice.

The function signature is wrong: `(err, instance)` should be nicer

**Comment by StarpTech** [comment]
@allevo it won't close fastify twice it will just add another two `close` handler to the queue.

```
close handler in fastify.js
close 1
close 2
```

> The function signature is wrong: (err, instance) should be nicer

This already fixed in https://github.com/mcollina/avvio/pull/56

**Comment by allevo** [comment]
The close method shuts the server down and attaches the function to the onClose event. Like listen method does on the start up.

Calling close twice is wrong

**Comment by StarpTech** [comment]
Discussion https://github.com/mcollina/avvio/issues/57

**Comment by StarpTech** [comment]
Original issue was fixed with https://github.com/mcollina/avvio/pull/56
