### ISSUE TITLE
Proxy feature

### ISSUE THREAD

**Issue by simon-p-r** [fastify/fastify#87]
Hi

Just wondering whether you are looking at supporting proxies a bit like [H2o2](https://github.com/hapijs/h2o2)?

Thanks
Simon

**Comment by mcollina** [comment]
Hey @simon-p-r I don't think that is in our roadmap, but it should be possible with a plugin. Would you like to write one?

**Comment by simon-p-r** [comment]
Sure I will get it a try

**Comment by mcollina** [comment]
I've made some progress here: https://github.com/mcollina/fastify-reply-from.

I'll code a full blown solution as soon as possible.

**Comment by mcollina** [comment]
@fastify do you think we should move that to the org ^

**Comment by delvedor** [comment]
@mcollina if you are ok with it, I'm 👍 !

**Comment by jsumners** [comment]
Sounds good to me.

**Comment by nwoltman** [comment]
Sure 👍

**Comment by mcollina** [comment]
Here it is: https://github.com/mcollina/fastify-http-proxy.

Should I move this as well?

**Comment by jsumners** [comment]
I believe the consensus is "yes".

**Comment by delvedor** [comment]
Yup!
And maybe add it to the ecosystem list!
