### ISSUE TITLE
Feature Request: Add DTrace Probes

### ISSUE THREAD

**Issue by Smithx10** [fastify/fastify#900]
Would fastify be interested in adding DTrace probes similar to those in restify? 

https://github.com/restify/node-restify/blob/master/lib/dtrace.js

I think it would be a big win :)

**Comment by jsumners** [comment]
My personal response: no thank you.

**Comment by bradjonesca** [comment]
My personal response: Absolutely! It would be a HUGE win, especially when running under SmartOS and Triton ... furthermore I can see massive benefits incorporating Fastify into some kind of reference application that also makes use of Containerpilot.

**Comment by Smithx10** [comment]
Care to elaborate on why not?

**Comment by jsumners** [comment]
They are an extraneous native module.

**Comment by delvedor** [comment]
We should definitely investigate if it is possible to create a plugin for it.

**Comment by mcollina** [comment]
I’m -1 on adding any binary dependency to the project. Supporting dtrace via a plugin would be very nice.

Another solution might be detecting if dtrace is in the dependencies already, and then use it if it’s there.

Considering that dtrace is coming to Linux soon, it might be a good to provide some support.

What use case are you looking for when using dtrace? Which OS are you using? can you provide some examples to what you’d like to track?

**Comment by bradjonesca** [comment]
@mcollina I just realised that no one answered your questions here, at least about which OS. My and I believe @Smithx10 interest is for the SmartOS environment.  There are a lot of new developments occurring in that world which will go mainline in the next month or two and along with the upcoming Fastify 2.0 should make for a powerful conbination

**Comment by mcollina** [comment]
@bradjonesca do you think it would be possible to implement this as a plugin? 

Or would you like to send a PR that meet those three criteria:

1. does not introduce any overhead when disabled
2. does not add a dependency to any binary addons
3. it is well documented and the use cases are extremely clear.

**Comment by bradjonesca** [comment]
@mcollina I am not a developer but I will endeavour to get the right person to address this and once Fastify 2.0 lands and the correct course of action is agreed upon by you and your team then I will look to sponsor the PR.  I have great confidence in you and the team here and enjoy watching the well thought out approach you all take in approaching problems and formulating solutions.

**Comment by mcollina** [comment]
Awesome!

**Comment by mcollina** [comment]
Fastify 2.0 lives in https://github.com/fastify/fastify/tree/next.

@fastify/fastify what do you think? Is https://github.com/fastify/fastify/issues/900#issuecomment-417728109 feasible?

**Comment by allevo** [comment]
I'm 👍  with https://github.com/fastify/fastify/issues/900#issuecomment-417728109

**Comment by jsumners** [comment]
A plugin implementation would be ideal in my opinion.

**Comment by mcollina** [comment]
I'm closing this, as there has been no interested since 2018.
