### ISSUE TITLE
Fastify Typescript definition conflict with exisiting node definition 

### ISSUE THREAD

**Issue by addityasingh** [fastify/fastify#908]
#### You have already researched for similiar issues?
Yes. 

#### Are you sure this is an issue with the fastify or are you just looking for some help?
This issue is because `fastify` packages TS definitions (`"@types/pino": "^4.7.1",`) is a `dependency` and is not either a `devDependency` or decoupled  from `fastify`

#### Is this a security related issue?
No

#### What are you trying to achieve or the steps to reproduce?
I want to use `fastify` with `typescript` in a monorepo using `lerna`. But if I install `@types/node` in global scope in repo and then also install `fastify`, I get `TS2300: Duplicate identifier ` error. This happens because of extending the global [tsconfig.json](https://github.com/addityasingh/node-snippets/blob/master/tsconfig.json) in the individual package [tsconfig](https://github.com/addityasingh/node-snippets/blob/master/packages/node-snippets-server/tsconfig.json#L2)

Steps:
- Create a project using `lerna` for multiple packages
- Install `@types/node` at global repo level
- Install `fastify` as a dependency in one of the packages
- Use `Typescript` for the project files
- Add a global `tsconfig.json`. e.g. 

https://github.com/addityasingh/node-snippets/blob/master/tsconfig.json#L1-L15

- Extend the global `tsconfig.json` in specific package `tsconfig.json`. e.g

https://github.com/addityasingh/node-snippets/blob/master/packages/node-snippets-server/tsconfig.json#L1-L9

I created this [commit](https://github.com/addityasingh/node-snippets/commit/39257139b24a7d737ecbbebf46e919cc2491b176) to demonstrate the steps to reproduce this error

#### What was the result you received?
> ../../node_modules/@types/pino/node_modules/@types/node/inspector.d.ts:263:21 - error TS2300: Duplicate identifier 'ExecutionContextId'.
263         export type ExecutionContextId = number;
                        ~~~~~~~~~~~~~~~~~~
../../node_modules/@types/pino/node_modules/@types/node/inspector.d.ts:332:21 - error TS2300: Duplicate identifier 'Timestamp'.
332         export type Timestamp = number;
                        ~~~~~~~~~
....
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! node-snippets-logger@1.0.0 compile: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the node-snippets-logger@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adisingh/.npm/_logs/2018-04-25T21_37_17_161Z-debug.log
lerna ERR! exec Errored while executing 'npm run compile' in 'node-snippets-logger'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run compile
lerna ERR!     at Promise.all.then.arr (/Users/adisingh/Documents/dev/projects/node-samples/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm run compile
    at Promise.all.then.arr (/Users/adisingh/Documents/dev/projects/node-samples/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 2,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run compile',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.

#### What did you expect?
I expected the code to compile correctly

#### Context

* *node version*: 8,9
* *fastify version*: >=1.3.0
* *os*: Mac
* *any other relevant information*:

**Comment by mcollina** [comment]
Thanks for the report! It seems you have researched the issue deeply, and my knowledge of typescript is very limited. What would you recommend?

**Comment by addityasingh** [comment]
Preferrably, moving out the `"@types/pino": "^4.7.1"` from `dependency` and bundling the `fastify` type definition into `@types/fastify` would be the ideal solution. I can take a jab at trying this but I might need help in doing that

**Comment by mcollina** [comment]
I think it's a yarn/lockfile problem. Try to update your deps: https://github.com/addityasingh/node-snippets/blob/39257139b24a7d737ecbbebf46e919cc2491b176/yarn.lock#L15-L21.

the latest pino defs should definitely resolve to the same `@types/node` definition.

**Comment by addityasingh** [comment]
@mcollina Thanks a lot. Seems installing the new version of fastify resolved the error. But I still think that decoupling the Type definitions out of the dependencies would be more scalable and with less such issues (related to types) created in this repo. Thoughts?

**Comment by jsumners** [comment]
See https://github.com/fastify/fastify/issues/649

**Comment by addityasingh** [comment]
Closing this  in lieu of #649
