### ISSUE TITLE
Use UTF8 as default charset for Text and JSON

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#913]
Hi, when I return a string like `ÄÜÖ` the browser is interpreted as
```
Ã„ÃœÃ–
```
fastify will respond with
```
content-type: text/html;
content-type: application/json;
```
it's obvious that I use the wrong charset but UTF8 is defacto standard and should be used as default.
```
content-type: text/html; charset=utf-8
content-type: application/json; charset=utf-8
```

> A Unicode encoding such as UTF-8 is a good choice for a number of [reasons](https://www.w3.org/International/questions/qa-choosing-encodings).

References:
* https://www.w3.org/International/questions/qa-choosing-encodings
* https://www.w3.org/International/articles/http-charset/index#charset

**Comment by nwoltman** [comment]
`application/json` is `utf-8` by default, but Fastify could use `text/plain; charset=utf-8` here:
https://github.com/fastify/fastify/blob/2907be7c5352926eda073c5a4be7701f7de39006/lib/reply.js#L66

**Comment by StarpTech** [comment]
I recommend to enforce utf8 for json due to security reason

https://github.com/shieldfy/API-Security-Checklist/issues/25

**Comment by StarpTech** [comment]
I will prepare a PR or already done? @nwoltman 😄

**Comment by nwoltman** [comment]
Nope. Go ahead @StarpTech 👍
