### ISSUE TITLE
body schema minLength not working

### ISSUE THREAD

**Issue by billouboq** [fastify/fastify#92]
Just found that minLength in json schema isn't working as expected.
The required works, but not the minLength, am I missing something ?

my code with node js 7.10.0 :

```js
'use strict';

const fastify = require('fastify')();

fastify.post('/test', {
   body: {
      name: {
         type: 'string',
         minLength: 6,
      },
      required: ['name'],
   }
}, (req, res) => {
   console.log(req.body);
   res.send({hello: 'world'});
});

fastify.listen(3400, (err) => {
   if (err) throw err;
   console.log('listening on port 3400');
});
```

and the response with postman : 

<img width="981" alt="screen shot 2017-05-19 at 10 58 49 pm" src="https://cloud.githubusercontent.com/assets/7765196/26266735/06c74562-3ce7-11e7-9e47-78da95f2b0fc.png">

**Comment by delvedor** [comment]
For validate `query`, `params` and `body` we are directly using [Ajv](https://github.com/epoberezkin/ajv).
Can you try Ajv alone and check if you have the same issue?

**Comment by delvedor** [comment]
You did not write the schema correctly, try this:
```js
body: {
   type: 'object',
   properties: {
     name: {
        type: 'string',
        minLength: 6,
     },
   }
   required: ['name'],
}
```

**Comment by billouboq** [comment]
@delvedor my bad, sorry about that, thanks !

**Comment by delvedor** [comment]
You can check our [docs](https://github.com/fastify/fastify/blob/master/docs/Validation-And-Serialize.md) on data validation, at the end of the page you will find some useful resources on how write a correct json schema :)
