### ISSUE TITLE
Awesome Fastify

### ISSUE THREAD

**Issue by israeleriston** [fastify/fastify#921]
Hello everyone, I took liberty and created a repository to add all modules of the fastify ecosystem, third-party module, plugins, lectures, articles, video conferences, actually all about fastify and join only in a single repository, this week I will create a series of articles about fastify in portuguese and popular fastify by the brazilian community!

If there is already a similar repository or the core team does not look like a good repository, please tell me that I withdraw.

https://github.com/israeleriston/awesome-fastify

**Comment by mcollina** [comment]
Awesome! This is a a good initiative! Please include my talk https://www.youtube.com/watch?v=gltzZjKYK1I and this article https://thenewstack.io/introducing-fastify-speedy-node-js-web-framework/.

Also https://medium.com/the-node-js-collection/fastify-goes-lts-with-1-0-0-911112c64752 article.

**Comment by mcollina** [comment]
@delvedor what's your video?

**Comment by israeleriston** [comment]
@mcollina i will include your talking

**Comment by israeleriston** [comment]
if any of the contributors have articles, talks, anything, leave as a comment, that I will gradually translate, so we can have material in Portuguese for the Brazilian community.

**Comment by delvedor** [comment]
Wow! Thanks!
This is awesome :D

[This](https://www.webexpo.net/prague2017/talk/what-if-i-told-you-that-http-can-be-fast/) is the talk I gave the past year :)

**Comment by israeleriston** [comment]
@mcollina and @delvedor could ask/advise the contributors/team to publish the links of the materials here, to be able to add in this awesome

**Comment by israeleriston** [comment]
@delvedor adding all you talk and articles, what else can adding in repo?

**Comment by Ethan-Arrowood** [comment]
This is awesome @israeleriston! I think we should link this on the fastify site so that when new things are created (plugins, videos, blog posts) users can submit a PR directly to your `awesome-fastify` repo.

**Comment by israeleriston** [comment]
@Ethan-Arrowood , think it's perfect !!! I'm available, we have to talk to @mcollina , and @delvedor  to know what they think

**Comment by Ethan-Arrowood** [comment]
You could do it yourself by opening a PR on the [website repo](https://github.com/fastify/website) itself 😉

**Comment by israeleriston** [comment]
Awesome! @Ethan-Arrowood i will provide PR for this :smiley:

**Comment by paulZzhang** [comment]
A demo like [Symfony Demo](https://github.com/symfony/demo)

**Comment by jsumners** [comment]
Unfortunately, @israeleriston will no longer be able to work on this issue due to his untimely death. If someone would like to pick up his work in the future, that would be great. Until then, there is no reason to keep this issue open.
