### ISSUE TITLE
schema with key or id already exist

### ISSUE THREAD

**Issue by BastienAr** [fastify/fastify#922]
When reusing a schema added with `fustily.addSchema` directly in response, fastify throw `Error: schema with key or id "UserDisplay" already exists`. It works if I try to encapsulate the result in `{type:'array', items: 'ref#'}`

```js
const schema = {
  GET: {
    response: {
      200: {
        type: 'array',
        items: 'UserDisplay#'
      }
    }
  },
  POST: {
    body: 'UserCreate#',
    response: {
      200: 'UserDisplay#' // Works if I replace it with the same response schema as GET
    }
  }
};
export default function(fastify, opts, next) {
  fastify.get('/', { schema: schema.GET }, getUserList);
  fastify.post('/', { schema: schema.POST }, createUser);
  next();
}
```

#### What was the result you received?
`Error: schema with key or id "UserDisplay" already exists`

#### What did you expect?
Route registered with success

#### Context

* *node version*: 10.0.0
* *fastify version*: >=1.3.1
* *os*: Mac

**Comment by delvedor** [comment]
I can reproduce it, I'll investigate. Thank you for reporting!

**Comment by delvedor** [comment]
It should be solved now, you just need to update your dependencies.
I've opened a pr with your test case, thanks for reporting!

**Comment by BastienAr** [comment]
Yep, works with the new version of fast-json-stringify. Thanks !
