### ISSUE TITLE
When I set header to 'application/json; charset=utf-8', I got TypeError with payload.

### ISSUE THREAD

**Issue by jweboy** [fastify/fastify#928]
I added a custom header in the reference document, and then set the Content-Type to application/json; charset=utf-8.

```js
fastify.get('/', function (request, reply) {
  // Your code
  reply
    .code(200)
    .header('Content-Type', 'application/json; charset=utf-8')
    .send({ hello: 'world' })
})
```
But I got the following error message.

>    throw new TypeError(`Attempted to send payload of invalid type '${typeof payload}'. Expected a string or Buffer.`)
    ^
> TypeError: Attempted to send payload of invalid type 'object'. Expected a string or Buffer.
    at onSendEnd (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/reply.js:196:11)
    at onSendHook (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/reply.js:158:5)
    at _Reply.Reply.send (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/reply.js:80:3)
    at Object.<anonymous> (/Users/jweboy/GitRepo/node-server/app.js:83:6)
    at preHandlerCallback (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/handleRequest.js:85:30)
    at next (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/hookRunner.js:8:7)
    at Object.<anonymous> (/Users/jweboy/GitRepo/node-server/app.js:27:3)
    at hookIterator (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/handleRequest.js:75:10)
    at next (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/hookRunner.js:12:20)
    at hookRunner (/Users/jweboy/GitRepo/node-server/node_modules/fastify/lib/hookRunner.js:26:3)

Then I find relevant instructions in the documentation.
> As noted above, if you are sending JSON objects, send will serialize the object with fast-json-stringify if you set an output schema, otherwise JSON.stringify() will be used.

According to the understanding of the document, if it is a JSON object, the send function will automatically output the serialization, but why do you expect the value to be a string or a Buffer?

This is my project configuration：
* *node version*: 8.6.0
* *fastify version*: >=1.4.0
* *os*: Mac

**Comment by israeleriston** [comment]
Hi @jweboy try this _**application/json;charset=utf-8**_ instead of _**application/json; charset=utf-8**_ ?

**Comment by israeleriston** [comment]
Other question by default fastify working that way see https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md

**Comment by israeleriston** [comment]
@jweboy in the tests I did (follow code) I get the same problem.
```js
const fastify = require('fastify')()

fastify.get('/', {}, function (request, reply) {
  // Your code
  reply
    .code(200)
    .type('application/json')
    // .type('application/json;charset=utf-8') with this option generates the error
    // .header('Content-Type', 'application/json;charset=utf-8') with this option generates the error
    .send({ hello: 'world' })
})


fastify.listen(3000, err => {
  if (err) throw err
    console.log('Listen on 3000 ')
})

```

**Comment by lependu** [comment]
Hi! I think this related to #913 and #914 . It seems we do not need to set the charset anymore. I checked the [docs](https://www.fastify.io/docs/latest/Reply/) and it seems to me, that it reflects this change.

**Comment by lependu** [comment]
The [first example](https://github.com/fastify/fastify/blame/747ce5c5f7b82ea1d855dac7b53c504c245cd565/docs/Reply.md#L20-L26) shows how to set the header with the charset. It is the same as your passing case, so it works.

The [type](https://github.com/fastify/fastify/blame/747ce5c5f7b82ea1d855dac7b53c504c245cd565/docs/Reply.md#L78-L84)does not mention the charset.

So, based on the doc and the linked PRs I suspect that this is the intended behavior. Maybe we should  document more straightforward how to set the charset.

**Comment by delvedor** [comment]
This is actually a bug, I'll look into it, thank you for reporting!
The issue is here:
https://github.com/fastify/fastify/blob/747ce5c5f7b82ea1d855dac7b53c504c245cd565/lib/reply.js#L74-L78
