### ISSUE TITLE
JSONSchema in typescript definition is not a JSONSchema

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#931]
```
interface JSONSchema {
    // TODO - define/import JSONSchema types
    body?: Object
    querystring?: Object
    params?: Object
    response?: {
      [code: number]: Object,
      [code: string]: Object
    }
  }
```

Is not a JSONSchema. The fields are

**Comment by mcollina** [comment]
is there a good typescript definition of a json schema around?

**Comment by allevo** [comment]
I mean, JSONSchema is not the right name. That is not a jsonschema, each child are.
Maybe `HandlerScema` or something like that is better. I'm not good at choosing names.

**Comment by nwoltman** [comment]
How about `RouteSchema`?

**Comment by allevo** [comment]
After #933 I'll fire a PR
