### ISSUE TITLE
mocha test with error 'Promise may not be fulfilled with 'undefined' when statusCode is not 204'

### ISSUE THREAD

**Issue by jweboy** [fastify/fastify#932]
When I used mocha for fastify multipart file upload tests, I encountered the wrong message. Here is my code:

```js
it('should post pitcure for images', (done) => {
      chai.request(app)
        .post('/api/upload/picture')
        .attach('imageField', fs.readFileSync('static/nodejs.png'), 'nodejs.png')
        .end((err, res) => { 
          expect(err).to.be.null
          expect(res).to.have.status(200)
          expect(res).to.have.header('content-type', /application\/json/)
          expect(res).to.be.json
          done()
        })
    })
```
The error message is as follows:
> [2018-05-09T11:30:44.725Z] ERROR (node-resful-api-logger/4811 on jweboy-2.local): Promise may not be fulfilled with 'undefined' when statusCode is not 204
    Error: Promise may not be fulfilled with 'undefined' when statusCode is not 204

I checked the source code to find the corresponding code:

```js
  var result = reply.context.handler(reply.request, reply)
  if (result && typeof result.then === 'function') {
    result
      .then(function (payload) {
        // this is for async functions that
        // are using reply.send directly
        if (payload !== undefined || (reply.res.statusCode === 204 && reply.sent === false)) {
          // we use a try-catch internally to avoid adding a catch to another
          // promise, increase promise perf by 10%
          try {
            reply.send(payload)
          } catch (err) {
            reply.sent = false
            reply._isError = true
            reply.send(err)
          }
        } else if (reply.sent === false) {
          reply.res.log.error(new Error(`Promise may not be fulfilled with 'undefined' when statusCode is not 204`))
        }
      }, function (err) {
        reply.sent = false
        reply._isError = true
        reply.send(err)
      })
  }
}
```
The reply to my request returned 200, but the source code was judged to be 204. Then I read the comment explanation to roughly mean asynchronous functions. I would like to ask about the design of the status code 204. What can I do to solve this error message?

This is my project configuration：
* *node version*: 8.6.0
* *fastify version*: >=1.4.0
* *os*: Mac

**Comment by mcollina** [comment]
Thanks for reporting! Would you mind sending us a full example? I'm pretty interested in how `/api/upload/picture` look like.

**Comment by jweboy** [comment]
Okay, so here's the code for my POST part:

```js
module.exports = function (fastify, opts, next) {
  fastify
    .post('/upload/picture', {
      schema: {
        response: {
          200: 'uploadPictureSuccess#',
          400: 'uploadPictureError#'
        }
      }
    }, async function (req, reply) {
      /**
       * @param {String} field 文件字段
       * @param {Object} file 可读文件流
       * @param {String} filename 文件名
       * @param {String} encoding 文件编码
       * @param {String} mimetype 文件类型
       */
      async function handler (field, file, filename, encoding, mimetype) {
        // 只接收图片类型
        if (!/image\//.test(mimetype)) {
          return reply.send({
            code: 400,
            message: '图片格式错误',
            data: {}
          })
        }
        // 图片上传并返回
        const { respBody, respInfo } = await upload(file, filename)
        reply
          .send({
            code: respInfo.statusCode,
            message: '文件上传成功',
            data: respBody
          })
        next()
      }
      req.multipart(handler, (err) => { if (err) throw err })
    })
    .delete('/upload/picture/:fileKey', deleteFile)
    .get('/upload/picture/list', getFiles)
}

```

The upload function is the upload operation for the seven niuyun:

```js
const Qiniu = require('../../util/qiniu')

const qiniu = new Qiniu()

async function upload (...args) {
  // const file = 'static/nodejs.png'
  try {
    const upload = await qiniu.uploadFile(...args)
    return upload
  } catch (err) {
    throw err
  }
}
```

The land travel section is registered on the global stage:

```js
fastify
  .register(schema)
  .register(routes, { prefix: 'api' })
  .after(err => {
    if (err) {
      throw err
    }
    console.log('routes register success!')
  })

```

**Comment by nwoltman** [comment]
If you remove `async` from your route handler, the error message should go away.

```js
}, function (req, reply) {
```

A function only needs to be `async` if it contains an `await` expression. In your case, the `await` is inside the `handler` function (not your anonymous route function).

Also, a good rule to follow is if you're using `reply.send()`, your route handler shouldn't be `async`.

**Comment by jweboy** [comment]
Well, I saw the point where the problem was, I removed the await but kept the async, resulting in this function becomes a Promise. Your opinion is very valuable and I will further optimize my function.thank you~

**Comment by rahadian347** [comment]
> If you remove `async` from your route handler, the error message should go away.
> 
> ```js
> }, function (req, reply) {
> ```
> 
> A function only needs to be `async` if it contains an `await` expression. In your case, the `await` is inside the `handler` function (not your anonymous route function).
> 
> Also, a good rule to follow is if you're using `reply.send()`, your route handler shouldn't be `async`.

this helped me
