### ISSUE TITLE
Wildcard (*) issue

### ISSUE THREAD

**Issue by xemasiv** [fastify/fastify#943]
#### You have already researched for similiar issues?
 YES

#### Are you sure this is an issue with the fastify or are you just looking for some help?
YES

#### Is this a security related issue?
NOPES

#### What are you trying to achieve or the steps to reproduce?
```js
  app.get('*', (req, res) => res.send('test'));
```

#### What was the result you received?
`{"statusCode":404,"error":"Not Found","message":"Not Found"}`

#### What did you expect?
`test`

#### Context

* *node version*: 10
* *fastify version*: 1.4.0
* *os*: Windows
* *any other relevant information*: NONE :100:

**Comment by allevo** [comment]
Hi!
thanks for checking out fastify!

Have you tried the following code?
```
  app.get('/*', (req, res) => res.send('test'));

```

**Comment by xemasiv** [comment]
@allevo yes sir, I'm getting the same thing:

`{"statusCode":404,"error":"Not Found","message":"Not Found"}`

**Comment by mcollina** [comment]
This is very likely a bug. Would you like to work on a fix?

**Comment by xemasiv** [comment]
I would love to, but I'm unfortunately too occupied so I'll leave it open for now.
Will try to if I find the time :100:

**Comment by StarpTech** [comment]
I can't reproduce it. Are you sure that no other server is running on the same port?

```js
'use strict'

const fastify = require('../fastify')()

fastify.get('*', (req, res) => res.send('test'))

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

#### Context

* *node version*: 10.1.0
* *fastify version*: 1.4.0
* *os*: Windows

**Comment by delvedor** [comment]
I can't reproduce it as well.

**Context**
- node version: v8.11.1
- fastify version: v1.4.0
- os: MacOS

**Comment by lependu** [comment]
I can't reproduce it either.

##Context
    node version: docker node-alpine-[6,8,9,10]
    fastify version: v1.4.0
    os: debian linux

**Comment by delvedor** [comment]
@xemasiv are you running another Fastify process on the same port but inside a Docker container?

**Comment by xemasiv** [comment]
Sorry for late response. As that time I was running two instances in the same script. One instance at port 80 then another one at port 443.

It was like:
```js
import fastify from 'fastify';
let x = fastify();
let y = fastify(/* https opts with cert, key, ca */)
[x,y].map((app) => {
  app.get('/*', (req, res) => res.send('test'));
});
x.listen(80);
y.listen(443);
```
