### ISSUE TITLE
How to deploy on Firebase Functions/Google Cloud Functions

### ISSUE THREAD

**Issue by endigo** [fastify/fastify#946]
How to run the server from cloud functions?

in express
```javascript
const server = express();
exports.next = functions.https.onRequest((request, response) => {
	server(request,response);
});
```

**Comment by nwoltman** [comment]
This is not possible currently. #804 is a similar issue.

**Comment by delvedor** [comment]
We are working on that feature in https://github.com/fastify/fastify/pull/937.

**Comment by vincent178** [comment]
One more PR https://github.com/fastify/fastify/pull/960

**Comment by delvedor** [comment]
@endigo in the latest version of Fastify (`v1.6.0`) you can use the [`serverFactory`](https://github.com/fastify/fastify/blob/master/docs/Factory.md#serverfactory) option. It should help you.

Closing this, please feel free to reopen if you have other questions :)

**Comment by shwei** [comment]
@delvedor @mcollina would love to have some pointers to actually use fastify in Cloud Functions. The typical call for http triggered functions is done by calling Functions' built-in onRequest method:
`
const functions = require('firebase-functions');
...
exports.greetFromFastify = functions.https.onRequest(fastify);
`

The full code example is at https://gist.github.com/shwei/d34c7383a117451c07dc701ad12482f1

Is there a way I can make this happens with Fastify? Thank you all.

**Comment by mcollina** [comment]
@shwei you might want to use https://www.fastify.io/docs/v1.13.x/Server/#serverfactory and pass the given handler to https://gist.github.com/shwei/d34c7383a117451c07dc701ad12482f1#file-fastify-in-firebase-function-js-L9 instead of the fastify instance.

**Comment by shwei** [comment]
@mcollina thanks, but  I don't know how to pass the given handler from serverFactory out to onRequest. Here is what I've so far https://gist.github.com/shwei/d34c7383a117451c07dc701ad12482f1#file-fastify-in-firebase-function-js-L14

I know this is not what you're asking. But at this point I don't know what the concept I'm missing to understand it better. If you know, please let me know! Thanks again!

**Comment by mtermoul** [comment]
is this fixed yet? I tried to use the serverFactory as pointed out by @shwei but it's not working! Can you please provide me with a code example?
This is my code:

```
const functions = require('firebase-functions')
const http = require('http')
const Fastify = require('fastify')

exports.app = functions.https.onRequest((req, res) => {
    const serverFactory = (handler, opts) => {
      const server = http.createServer((req, res) => {
        handler(req, res)
      })
      return server
    }
    const fastify = Fastify({serverFactory})
    fastify.get('/', (req, reply) => {
      reply.send({ hello: 'world' })
    })
})
```

I am getting `Timed out waiting for function to respond.` error

**Comment by nwoltman** [comment]
@mtermoul Something like this should work:

```js
const functions = require('firebase-functions')
const http = require('http')
const Fastify = require('fastify')

let handleRequest = null

const serverFactory = (handler, opts) => {
  handleRequest = handler
  return http.createServer()
}
const fastify = Fastify({serverFactory})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})

exports.app = functions.https.onRequest((req, res) => {
  fastify.ready((err) => {
    if (err) throw err
    handleRequest(req, res)
  })
})
```

This is more efficient as well since it doesn't create a new Fastify instance on every request.

**Comment by shwei** [comment]
Thanks @nwoltman! This is very helpful. I had to put in the line before fastify.ready() call:
```js
  req = Object.assign({ip: ''}, {...req}); 

  fastify.ready((err) => {
  ...
```

Without that hacky line, I would get the error:

```js
error: /Users/shwei/Work/workspace/cf-fastify-restify-express/functions/node_modules/fastify/fastify.js:249
    
req.ip = req.connection.remoteAddress
       ^
TypeError: Cannot set property ip of [object Object] which has only a getter
        at _ipAsRemoteAddress (/Users/shwei/Work/workspace/cf-fastify-restify-express/functions/node_modules/fastify/fastify.js:249:12)
```

Is there a way to avoid this error?

[full code](https://gist.github.com/shwei/d34c7383a117451c07dc701ad12482f1#file-fastify-js-L35)

@mtermoul: thanks for following up with this man.

 
> @mtermoul Something like this should work:
> 
> ```js
> const functions = require('firebase-functions')
> const http = require('http')
> const Fastify = require('fastify')
> 
> let handleRequest = null
> 
> const serverFactory = (handler, opts) => {
>   handleRequest = handler
>   return http.createServer()
> }
> const fastify = Fastify({serverFactory})
> 
> fastify.get('/', (req, reply) => {
>   reply.send({ hello: 'world' })
> })
> 
> exports.app = functions.https.onRequest((req, res) => {
>   fastify.ready((err) => {
>     if (err) throw err
>     handleRequest(req, res)
>   })
> })
> ```
> 
> This is more efficient as well since it doesn't create a new Fastify instance on every request.

**Comment by mtermoul** [comment]
Thank you guys @nwoltman 🙌 👍 🏆  and @shwei  🌟 🎉 🎆   for the code sample. Fastify is finally working with cloud functions. And now going back to implement the real features and see how would Fastify hold.

**Comment by nwoltman** [comment]
@shwei It looks like that [error](https://github.com/fastify/fastify/issues/946#issuecomment-461566975) happens because `firebase-functions` passes Express's prototype-extended `req` and `res` objects to the handler function, but Fastify expects to receive Node's native `req` and `res` objects.

@fastify/fastify What do you think is the right thing to do here? Is this a problem that should be fixed in Fastify?

**Comment by shwei** [comment]
Thanks for looking into this @nwoltman . If this can be accommodated without too much sacrifice on performance, it would allow greater compatibility with one of very popular serverless infrastructures. 

Or maybe if we could pass an option to skip setting req.ip?


> @shwei It looks like that [error](https://github.com/fastify/fastify/issues/946#issuecomment-461566975) happens because `firebase-functions` passes Express's prototype-extended `req` and `res` objects to the handler function, but Fastify expects to receive Node's native `req` and `res` objects.
> 
> @fastify/fastify What do you think is the right thing to do here? Is this a problem that should be fixed in Fastify?

**Comment by nwoltman** [comment]
Another solution would be to set `ip` on the Fastify `request` object instead of Node's `req` object. @delvedor originally [suggested this](https://github.com/fastify/fastify/pull/1086/files#r211718687) in #1086.

**Comment by shwei** [comment]
@nwoltman when you said, "set ip on the Fastify request object", can you elaborate it a little more? Did you mean set trustProxy? 

```js
const fastify = Fastify({ trustProxy: true })
OR given IP/CIDR?
const fastify = Fastify({ trustProxy: 'IP/CIDR' })
```

Thanks!

> Another solution would be to set `ip` on the Fastify `request` object instead of Node's `req` object. @delvedor originally [suggested this](https://github.com/fastify/fastify/pull/1086/files#r211718687) in #1086.

**Comment by nwoltman** [comment]
@shwei Yes, it's related to the `trustProxy` option. I'm suggesting that a solution would be to pass `ip` to Fastify's Request constructor here:
https://github.com/fastify/fastify/blob/356cf6f078a9f93b009ddb6384deaffe549d1032/fastify.js#L307
rather than setting it on Node's `req` object here:
https://github.com/fastify/fastify/blob/356cf6f078a9f93b009ddb6384deaffe549d1032/fastify.js#L273-L283

Of course, if that were done, `ips` and `hostname` would also need to move to the Fastify Request object.

**Comment by shwei** [comment]
@nwoltman Interesting with passing ip in the context.Request call! It sounds like `handleTrustProxy(req)` may need to be tweaked. What are the steps we need to incorporate your proposed change? Anything I can do to help?

Another idea: if req.ip has a value and if there is an option we can pass into fastify to indicate that we want to skip calling the method `handleTrustProxy(req)`, we can just keep both _handleTrustProxy and _ipAsRemoteAddress unchanged. However, it will require a new logic and it can be too hacky and short-term. 

Express's prototype-extended `req` has an ip value in
https://gist.github.com/shwei/d34c7383a117451c07dc701ad12482f1#file-fastify-js-L27

> @shwei Yes, it's related to the `trustProxy` option. I'm suggesting that a solution would be to pass `ip` to Fastify's Request constructor here:
> [fastify/fastify.js](https://github.com/fastify/fastify/blob/356cf6f078a9f93b009ddb6384deaffe549d1032/fastify.js#L307)
> 
> Line 307 in [356cf6f](/fastify/fastify/commit/356cf6f078a9f93b009ddb6384deaffe549d1032)
> 
>  var request = new context.Request(params, req, query, req.headers, req.log) 
> 
> rather than setting it on Node's `req` object here:
> [fastify/fastify.js](https://github.com/fastify/fastify/blob/356cf6f078a9f93b009ddb6384deaffe549d1032/fastify.js#L273-L283)
> 
> Lines 273 to 283 in [356cf6f](/fastify/fastify/commit/356cf6f078a9f93b009ddb6384deaffe549d1032)
> 
>  function _handleTrustProxy (req) { 
>    req.ip = proxyAddr(req, proxyFn) 
>    req.ips = proxyAddr.all(req, proxyFn) 
>    if (req.ip !== undefined) { 
>      req.hostname = req.headers['x-forwarded-host'] 
>    } 
>  } 
>   
>  function _ipAsRemoteAddress (req) { 
>    req.ip = req.connection.remoteAddress 
>  } 
> Of course, if that were done, `ips` and `hostname` would also need to move to the Fastify Request object.

**Comment by nwoltman** [comment]
@shwei Having an option that is only used to avoid setting a particular property does seem pretty hacky, especially when there's a non-hacky solution. I'd suggesting submitting a PR to move `ip` to Fastify's `Request` object. You can probably figure out how to do that by looking at #1086. If not, you can open a new issue for the bug so it can be addressed properly (our conversation doesn't really fit the original issue anymore).

**Comment by shwei** [comment]
Thank you, @nwoltman. Finally got around to work on this. I'm fairly new to fastify, so would you please take a look at my changes? shwei/fastify@88f4c8a  Your comments are greatly appreciated. 

> @shwei Having an option that is only used to avoid setting a particular property does seem pretty hacky, especially when there's a non-hacky solution. I'd suggesting submitting a PR to move `ip` to Fastify's `Request` object. You can probably figure out how to do that by looking at #1086. If not, you can open a new issue for the bug so it can be addressed properly (our conversation doesn't really fit the original issue anymore).

**Comment by nwoltman** [comment]
> Thanks @nwoltman! This is very helpful. I had to put in the line before fastify.ready() call:
> 
> ```js
>   req = Object.assign({ip: ''}, {...req}); 
> 
>   fastify.ready((err) => {
>   ...
> ```
> 
> Without that hacky line, I would get the error:

@shwei I found another way to avoid the error that's less likely to introduce other bugs.

Instead of

```js
req = Object.assign({ip: ''}, {...req}); 
```

do

```js
Object.defineProperty(req, 'ip', {
  value: req.ip,
  configurable: true,
  enumerable: true,
  writable: true,
});
```

This just modifies the `ip` property instead of creating a new object that doesn't share the same prototype as the `req` object.

**Comment by mcollina** [comment]
Can you please explain to me what is the problem? I don’t understand.

**Comment by nwoltman** [comment]
The problem is that people who use Fastify with Google Cloud's Firebase Functions will run into this error on every request:

```
error: /functions/node_modules/fastify/fastify.js:249
    
req.ip = req.connection.remoteAddress
       ^
TypeError: Cannot set property ip of [object Object] which has only a getter
        at _ipAsRemoteAddress (/functions/node_modules/fastify/fastify.js:249:12)
```

This happens because Fastify is trying to set the `req.ip` property ([here](https://github.com/fastify/fastify/blob/29a77b9a98a12c2378cac6de306a6c9235a8511d/fastify.js#L280-L282)), but it fails because Firebase functions use the same `req` and `res` objects that Express uses. In Express, `req.ip` is defined only as a getter ([see here](https://github.com/expressjs/express/blob/dc538f6e810bd462c98ee7e6aae24c64d4b1da93/lib/request.js#L349-L352)), so trying to set that property is an error.

**Comment by mcollina** [comment]
I’m happy to add an option to disable that. I think it should work.

**Comment by shwei** [comment]
By all means, please do if that makes most sense. Hope the new option will be available for 1.x. Let me know how I can help. Thanks!

**Comment by mcollina** [comment]
@shwei can you update your PR in that direction? I'm happy to have the change backported.

**Comment by nwoltman** [comment]
@mcollina Just wondering, is the plan you're thinking of to:

1. Add the option to @shwei's PR (#1476) while still keeping his work to add the properties to Fastify's `Request` object
2. Remove the option and remove the properties from the Node core `req` object in v3?

**Comment by mcollina** [comment]
That’s the plan.

**Comment by nwoltman** [comment]
OK, that sounds good to me 🙂

**Comment by shwei** [comment]
@mcollina @nwoltman how does `skipAssignIpInNodeReq` in options sound? Any better names?

**Comment by mcollina** [comment]
@shwei I would go one step further and do: `addPropertiesToNodeReq`, and avoid adding the logger as well while we are at it.

**Comment by shwei** [comment]
@mcollina would this option apply to `res.log` also? 
`  req.log = res.log = log.child({ reqId: req.id, level: context.logLevel })`
https://github.com/shwei/fastify/blob/pass-ip-to-request-constructor/fastify.js#L307

**Comment by mcollina** [comment]
@shwei yes, I would actually go that far.

**Comment by jineshshah36** [comment]
We just spent a considerable amount of time trying to get fastify running on google cloud functions, and then we discovered google cloud run which shares many of the benefits of cloud functions but works much more easily with fastify. You just specify a docker file and cloud run will run your dockerized fastify server like a serverless function. It took 10 minutes to setup and required no major code changes from how you would run fastify on a regular server

**Comment by Eomm** [comment]
@jineshshah36 would you like to add your finding in the [Serverless.md](https://github.com/fastify/fastify/blob/master/docs/Serverless.md)?

This would help the community for sure 💪

**Comment by jineshshah36** [comment]
Yes, keep forgetting to do this. Will try to send a PR this weekend!

**Comment by jineshshah36** [comment]
Done: https://github.com/fastify/fastify/pull/1770

**Comment by mcollina** [comment]
I never had a chance. Would you like to investigate it and send a PR for the serverless docs?

**Comment by rfgamaral** [comment]
> I never had a chance. Would you like to investigate it and send a PR for the serverless docs?

I'm unfamiliar with Fastify's code base and Fastify itself to be honest. So I'm not the right guy for the job. I was under the impression that either @shwei or @nwoltman were close to a solution...

**Comment by nwoltman** [comment]
@rfgamaral It should work just fine if you set the [`modifyCoreObjects`](https://github.com/fastify/fastify/blob/master/docs/Server.md#modifycoreobjects) option to `false`.

**Comment by devotox** [comment]
So for anybody who is having trouble on google cloud functions or firebase functions use this in your package.json

```json
"@google-cloud/functions-framework": "devotox/google-cloud-functions-framework"
```

The problem with POST requests was that functions-framework already attached a body parser

**Comment by manasmishra** [comment]
> So for anybody who is having trouble on google cloud functions or firebase functions use this in your package.json
> 
> ```json
> "@google-cloud/functions-framework": "devotox/google-cloud-functions-framework"
> ```
> 
> The problem with POST requests was that functions-framework already attached a body parser

Any small working example will help the community a lot. How and where to use the above line?
Thanks.

**Comment by woobione** [comment]
To this day, the issue @devotox mentions is present.
When running Fastify as a Google Cloud Function (firebase-functions), using the suggested serverFactory approach, all `POST` and `PATCH` requests will just never return anything, as long as the `Content-Type header application/json` is present. Thought I would share my findings for anyone else having the same issue.

The root of the problem is in `contentTypeParser` and more explicitly the `rawBody` method which (if parseAs is string or buffer) will try to read the buffer from the body. However, the buffer has already been read by body-parser in the firebase-functions library, hence netiher `payload.on('data', onData)` or `payload.on('end', onEnd)` will ever run, resulting in `done` never being called. Fully expected by Fastify, but until I figured it out I've been pulling my hair out for hours thinking I'm going crazy.

Since the `rawBody` will be run, even if you provide your own contentTypeParser, you can not mitigate it simply by sending a your own parser for `application/json`. BUT if you provide a parser which does NOT specify the `parseAs` option, you bypass that method. And since the body has already been parsed, a simple solution is to do the following:

```
app.addContentTypeParser('application/json', {}, (req, body, done) => {
  done(null, body.body);
});
```

Hope I can help someone else wanting to use this superb library together with cloud functions 🤗

**Comment by nmggithub** [comment]
> To this day, the issue @devotox mentions is present. When running Fastify as a Google Cloud Function (firebase-functions), using the suggested serverFactory approach, all `POST` and `PATCH` requests will just never return anything, as long as the `Content-Type header application/json` is present. Thought I would share my findings for anyone else having the same issue.
> 
> The root of the problem is in `contentTypeParser` and more explicitly the `rawBody` method which (if parseAs is string or buffer) will try to read the buffer from the body. However, the buffer has already been read by body-parser in the firebase-functions library, hence netiher `payload.on('data', onData)` or `payload.on('end', onEnd)` will ever run, resulting in `done` never being called. Fully expected by Fastify, but until I figured it out I've been pulling my hair out for hours thinking I'm going crazy.
> 
> Since the `rawBody` will be run, even if you provide your own contentTypeParser, you can not mitigate it simply by sending a your own parser for `application/json`. BUT if you provide a parser which does NOT specify the `parseAs` option, you bypass that method. And since the body has already been parsed, a simple solution is to do the following:
> 
> ```js
> fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
>   done(null, body.body);
> });
> ```
> 
> Hope I can help someone else wanting to use this superb library together with cloud functions hugs
> 
> **Full Example Code**
> 
> ```js
> const functions = require('firebase-functions');
> let requestHandler = null;
> 
> const fastify = require('fastify')({
>   logger: true,
>   serverFactory: (handler) => {
>     requestHandler = handler;
>     return require('http').createServer();
>   },
> });
> 
> fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
>   done(null, body.body);
> });
> 
> fastify.post('/postToMeWithJSON', async (req) => {
>   return req.body;
> });
> 
> exports.myApi = functions.https.onRequest((req, res) => {
>   fastify.ready((err) => {
>     if (err) throw err;
>     requestHandler(req, res);
>   });
> });
> ```

I second this. I am experiencing the same issues.

**Comment by Taha-Firoz** [comment]
> To this day, the issue @devotox mentions is present. When running Fastify as a Google Cloud Function (firebase-functions), using the suggested serverFactory approach, all `POST` and `PATCH` requests will just never return anything, as long as the `Content-Type header application/json` is present. Thought I would share my findings for anyone else having the same issue.
> 
> The root of the problem is in `contentTypeParser` and more explicitly the `rawBody` method which (if parseAs is string or buffer) will try to read the buffer from the body. However, the buffer has already been read by body-parser in the firebase-functions library, hence netiher `payload.on('data', onData)` or `payload.on('end', onEnd)` will ever run, resulting in `done` never being called. Fully expected by Fastify, but until I figured it out I've been pulling my hair out for hours thinking I'm going crazy.
> 
> Since the `rawBody` will be run, even if you provide your own contentTypeParser, you can not mitigate it simply by sending a your own parser for `application/json`. BUT if you provide a parser which does NOT specify the `parseAs` option, you bypass that method. And since the body has already been parsed, a simple solution is to do the following:
> 
> ```js
> fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
>   done(null, body.body);
> });
> ```
> 
> Hope I can help someone else wanting to use this superb library together with cloud functions 🤗
> 
> **Full Example Code**
> 
> ```js
> const functions = require('firebase-functions');
> let requestHandler = null;
> 
> const fastify = require('fastify')({
>   logger: true,
>   serverFactory: (handler) => {
>     requestHandler = handler;
>     return require('http').createServer();
>   },
> });
> 
> fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
>   done(null, body.body);
> });
> 
> fastify.post('/postToMeWithJSON', async (req) => {
>   return req.body;
> });
> 
> exports.myApi = functions.https.onRequest((req, res) => {
>   fastify.ready((err) => {
>     if (err) throw err;
>     requestHandler(req, res);
>   });
> });
> ```

this fix in no longer valid since body is now an incoming message and there is no `body` property on body. If the `parseAs: 'string'` parameter is passed into `addContentTypeParser` then the body can be parsed.

**Comment by joenoon** [comment]
> > To this day, the issue @devotox mentions is present. When running Fastify as a Google Cloud Function (firebase-functions), using the suggested serverFactory approach, all `POST` and `PATCH` requests will just never return anything, as long as the `Content-Type header application/json` is present. Thought I would share my findings for anyone else having the same issue.
> > The root of the problem is in `contentTypeParser` and more explicitly the `rawBody` method which (if parseAs is string or buffer) will try to read the buffer from the body. However, the buffer has already been read by body-parser in the firebase-functions library, hence netiher `payload.on('data', onData)` or `payload.on('end', onEnd)` will ever run, resulting in `done` never being called. Fully expected by Fastify, but until I figured it out I've been pulling my hair out for hours thinking I'm going crazy.
> > Since the `rawBody` will be run, even if you provide your own contentTypeParser, you can not mitigate it simply by sending a your own parser for `application/json`. BUT if you provide a parser which does NOT specify the `parseAs` option, you bypass that method. And since the body has already been parsed, a simple solution is to do the following:
> > ```js
> > fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
> >   done(null, body.body);
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope I can help someone else wanting to use this superb library together with cloud functions 🤗
> > **Full Example Code**
> > ```js
> > const functions = require('firebase-functions');
> > let requestHandler = null;
> > 
> > const fastify = require('fastify')({
> >   logger: true,
> >   serverFactory: (handler) => {
> >     requestHandler = handler;
> >     return require('http').createServer();
> >   },
> > });
> > 
> > fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
> >   done(null, body.body);
> > });
> > 
> > fastify.post('/postToMeWithJSON', async (req) => {
> >   return req.body;
> > });
> > 
> > exports.myApi = functions.https.onRequest((req, res) => {
> >   fastify.ready((err) => {
> >     if (err) throw err;
> >     requestHandler(req, res);
> >   });
> > });
> > ```
> 
> this fix in no longer valid since body is now an incoming message and there is no `body` property on body. If the `parseAs: 'string'` parameter is passed into `addContentTypeParser` then the body can be parsed.

FWIW, body.body still works as of today, even though body is IncomingMessage, and the types say there is no body.body.  I'm using `done(null, (body as any).body)` and have verified with console.log that `(body as any).body` does return the parsed object.  Not sure why its not in the types.

**Comment by climba03003** [comment]
> even though body is IncomingMessage, and the types say there is no body.body

The typings is correct since the `body.body` is added by `firebase functions` or `goolgle cloud functions`.
It is not a official property.

**Comment by HugoGresse** [comment]
this solution won't work (or the one from the doc) for multipart / file upload :/ 
the `await request.file()` or attaching the file to the body never works, but when calling fastify directly (and not through the firebase-function onRequest) it works.

**Comment by ThomasKientz** [comment]
@HugoGresse Have you found a solution ? I am currently inspecting what you have done here https://github.com/HugoGresse/OpenPlanner/blob/main/functions/src/api/routes/file/parseMultipartFiles.ts, maybe you can pin point the solution.

**Comment by HugoGresse** [comment]
@ThomasKientz  Yep it works on OpenPlanner, I'm not happy with the code quality though.
- Serverles function (the one exported) : https://github.com/HugoGresse/OpenPlanner/blob/main/functions/src/api/index.ts
- FastifySetup for serverless : https://github.com/HugoGresse/OpenPlanner/blob/main/functions/src/api/setupFastify.ts#L37
(which mean you can use it locally without the serverless overhead)
- parsing multipart for file upload, only when neded   : https://github.com/HugoGresse/OpenPlanner/blob/main/functions/src/api/routes/file/files.ts#L61C34-L61C58

I think tha's all!
