### ISSUE TITLE
Error Handling with `next()` 

### ISSUE THREAD

**Issue by saikatharryc** [fastify/fastify#950]
*migrating an express app to fastify*
in express we i use to pass error in a particular route to `next()` and handle it to the `app.js` and loging it and also after processing sending error response.
 tried the same here, but unfortunately, 
```
fastify.get("/some_route", (req, res, next) =>{
});
```
here next is not available.

is there any way to handle error ? without sending it directly to the response like
`res.send(error);`
or to get `next()`  in the callback?

* *node version*: v8.7.0
* *fastify version*: >=^1.2.0
* *os*: Ubuntu

**Comment by mcollina** [comment]
There is no `next()`  in route handlers, you do `reply.send(err)`  instead.

The error will be routed to the error handler and it can be plugin specific.
