### ISSUE TITLE
Plugin for serializing events in the CloudEvents Specification format

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fastify#952]
Hi all,
I'm looking for a way to expose any kind of event from a Fastify webapp to the outside, and the new CloudEvents standard seems very interesting, see [here](https://github.com/cloudevents/spec).
So I think that I could write a plugin for start to serialize events (Fastify standards exposed via hooks, and even custom at application level) in that standard way, at least to try to be more future-proof (I hope :-) ).

After having that serialization I'll need to send/store somewhere but this could be handled bu different providers (starting from a simple list, to sending to message queues like NATS Streaming, etc) but maybe could be good for another plugin, let's see.

What do you think ?
Someone is interested too ?

Thanks,
Sandro

**Comment by mcollina** [comment]
This seems very interesting. I currently have not time availability to work on this, but I'll be happy to review!

**Comment by smartiniOnGitHub** [comment]
Ok, thank you very much for now. I need some week probably, but I'll keep you updated. Bye

**Comment by smartiniOnGitHub** [comment]
Hi all and sorry for the delay ... I pushed in the repo some content but it's still a work-in-progress.
Anyway is someone want to take a look, sources are at: [fastify-cloudevents](https://github.com/smartiniOnGitHub/fastify-cloudevents). 
Then I want to add some more feature like serialize in JSON and in other formats with user provided functions, and basic support for sendind events somewhere.
Add some test for massive load to ensure a lot of events can be generated/handled faster.
And complete the example: on this I'm thinking to add a listener to any Fastify hook, and send events to a simple store (like a file on disk for example).

And a quick question: currently I'm exporting some functions via decorate, but I wonder if exporting them as an ES6 class (and then decorate) does it makes sense ? There is a risk to be slower ?

@mcollina What do you think, sounds good ?

**Comment by delvedor** [comment]
Hi @smartiniOnGitHub!
Since you are already working on it there is no need to add the label `plugin suggestion`.
Actually we can close this issue since you are already working on it and once you are done you can open a pr to add it to our ecosystem, then one member of our team will review your plugin :)
