### ISSUE TITLE
Output validation

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#961]
Currently, route configurations sort of overload the `schema` configuration. It doubles as input *validation* and for output *serialization*. This is confusing to users expecting it to be solely for *validation* of all potential targets. Thus, when combined with the ability to supply alternate validators, e.g. Joi, we encounter a situation where the user will write an output validation that causes errors. As an example:

```js
server.route({
  path: '/foo',
  method: 'GET',
  schema: {
    response: {
      200: joi.object({ foo: joi.string().required() })
    }
  },
  handler (req, res) {
    res.send({foo: 'bar'})
  }
})
```

A user expecting schemas to be for validation may write this sort of schema and it will result in a circular reference error since Fastify is attempting to serialize according to the circular Joi schema.

The short solution is to replace the serializer for this route. However, that is not feasible when every route in a project should have the serializer replaced. Thus, we need to be able to supply a global serializer.

**Comment by mcollina** [comment]
Would the following be sufficient?

```js
fastify.addHook('onSend', async (request, reply, payload) => {
  var err = null;
  reply.context.config.validateResponse(payload)
  return payload
})
```

**Comment by delvedor** [comment]
@mcollina that could be a solution, but the payload is already serialized at that point.

**Comment by jsumners** [comment]
How does that work with the non-JSON-schema response description on the route?

**Comment by mcollina** [comment]
> @mcollina that could be a solution, but the payload is already serialized at that point.

My bad, we really need a way to override the default serializer.
