### ISSUE TITLE
npm install causes linter to fail but yarn does not

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#968]
#### What are you trying to achieve or the steps to reproduce?

1. Clone `fastify` to local machine (or delete node_modules)
2. Run `npm install` (nodejs = 10.4.0, npm = 6.1.0)
3. Run `npm run lint` or `npm run test` or `npm run lint:typescript`
    - All three commands result in `Resolve error: unable to load resolver "node"` (see below).

```
standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/ethanarrowood/Documents/Projects/fastify/fastify.d.ts:1:1: Resolve error: unableto load resolver "node".
  /Users/ethanarrowood/Documents/Projects/fastify/test/types/index.ts:1:1: Resolve error:unable to load resolver "node".
```

_Alternatively_

1. Clone `fastify` to local machine (or delete node_modules)
2. Run `yarn install` (nodejs = 10.4.0, yarn = 1.5.1)
3. Run `npm run lint` or `npm run test` or `npm run lint:typescript`
    - Everything runs as expected

#### What did you expect?

The linter to work and test suite to run with **npm** (it only works with **yarn**)

#### Context

* *node version*: 10.4.0
* *fastify version*: >=0.37.0
* *os*: Mac
* *npm*: 6.1.0

**Comment by mcollina** [comment]
Which version of npm are you using? Is this a bug about npm or yarn? It's not really clear what's the problem.

Can you add step-by-step instructions on how to reproduce?

**Comment by Ethan-Arrowood** [comment]
Updated now @mcollina

**Comment by mcollina** [comment]
I can't reproduce. Might be an npm bug. Remove `package-lock.json`  if you have one, and also the `.npm` folder in your home directory.

**Comment by Ethan-Arrowood** [comment]
Must've been the package-lock.json file. I'll keep this in mind going forward if I run into similar errors. Closing this now.
