### ISSUE TITLE
How to destroy resources initialized in plugin?

### ISSUE THREAD

**Issue by zhaoyao91** [fastify/fastify#969]
In the great docs I know how to init a mongo connection. But where can I register a stop or destroy callback? Otherwise the test won't finish correctly since there is open tpc connection.

**Comment by mcollina** [comment]
You should use "onClose" hook: https://github.com/fastify/fastify/blob/master/docs/Hooks.md#application-hooks.

**Comment by zhaoyao91** [comment]
@mcollina Thanks. I should have read it more carefully :)
