### ISSUE TITLE
Propagating HttpServer / HttpRequest / HttpResponse types

### ISSUE THREAD

**Issue by yuriy-yarosh** [fastify/fastify#970]
So, I'm impl some basic TS typings for `fastify-static` in here [#66](https://github.com/fastify/fastify-static/issues/66). I've made a PR but @mcollina asked me explicitly to make fastify a development dependency. I'll have to propagate fastify.Plugin type from the `fastify-plugin` package, but it takes HttpServer / HttpRequest / HttpResponse as generic type parameters, which are not exported from the `fastify` namespace in the `fastify.d.ts`.

I'd rather omit so many type parameters for the Plugin type and wrote something like
```javascript
declare namespace fastify {
  type HttpServer = (http.Server | http2.Http2Server)
  type HttpRequest = (http.IncomingMessage | http2.Http2ServerRequest)
  type HttpResponse = (http.ServerResponse | http2.Http2ServerResponse)

  type Plugin<T> = (instance: FastifyInstance<HttpServer, HttpRequest, HttpResponse>, opts: T, callback: (err?: Error) => void) => void
...
```
instead of [fastify.d.ts:25](https://github.com/fastify/fastify/blob/master/fastify.d.ts#L25)

Have no idea how many fastify plugins out there in the wild, so it might be better to stick with the bloated version. 

Is it fine to drop the excessive type parameters ?

**Comment by mcollina** [comment]
I do not know _why_ they are needed. I think we should re-export those and stick with the current typing scheme.

One of our typescript users might be of help here.

**Comment by delvedor** [comment]
cc @evanshortiss

**Comment by yuriy-yarosh** [comment]
I haven't found a way to implement proper fastify TS/Flow typings.
So, It's better, for me personally, to assume that fastify will not get decent TypeScript support whatsoever...

**Comment by mcollina** [comment]
@yuriy-yarosh I'm sorry to hear that you are giving up. We are doing our best to support Typescript, and we would be very happy to improve our typescript support, but very few of us are Typescript users. If you look at our CONTRIBUTING.md file, we give commit access to any individual that do valuable contributions. So, would you like to improve our types?

**Comment by yuriy-yarosh** [comment]
@mcollina Thank you for your concern.
It's not that I'm giving up, it's just TypeScript typings are insufficient for some of the Fastify's API.
Although flow typings should be usable in future releases of the flowtype afaik.
