### ISSUE TITLE
fastify-cli + nodemon?

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify#976]
It's possible to use nodemon with fastify-cli?
```
> nomikos@1.0.0 dev /Users/lgertel/nomikos
> fastify start -l info app.js -P

09:17:47 ✨ Server listening at http://127.0.0.1:3000
```
It would be awesome if the server auto restarts on change, but I'm not sure how to do it :)
Thanks

**Comment by delvedor** [comment]
From the [nodemon](https://github.com/remy/nodemon#usage) documentation:
```md
nodemon will also search for the scripts.start property in package.json (as of nodemon 1.1.x).
```

It just works :)
If you want the development setup of `fastify-cli`just swap `start` and `dev` scripts.

**Comment by lgertel** [comment]
Great! Here is the command to run without the need to swap values:

```nodemon --exec npm run dev

**Comment by mariusa** [comment]
Any ideas on how to run this with foreman?  (to load env vars: https://github.com/strongloop/node-foreman)
```
$ nf run nodemon --exec npm run start
error: unknown option `--exec'
```
