### ISSUE TITLE
Setting the basePath / _routePrefix property on a fastify instance

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify#980]
I am not sure I understand the concept of basePath / _routePrefix in fastify.

Not a big problem... I currently set all route URL like so:

```
        fastify.route({
            method: 'GET',
            url: process.env.DIR || '/' + 'something/else',`
            beforeHandler: fastify.auth([fastify.authLogin]),
            handler: async (req, res) => {
```

This works a-ok but I have a feeling that there is a better way of doing this.

Ideally I would like something where I register the basepath which then works for each and every route in the instance.

**Comment by dbauszus-glx** [comment]
Unfortunately, not a-ok as my endpoint definitions in the client side requests won't work like this.

**Comment by delvedor** [comment]
As said in https://github.com/fastify/fastify/issues/386, you should pass the `prefix` option to `register`:
```js
fastify.register(require('./routes/v1/users'), { prefix: '/v1' })
fastify.register(require('./routes/v2/users'), { prefix: '/v2' })
```

Internally Fastify will concatenate the prefix and the route.

**Comment by dbauszus-glx** [comment]
all good. this works.

below is the updated example from original post for reference.

```
fastify.register((fastify, opts, next) => {
  
  fastify.route({
    method: 'GET',
    url: '/'
    handler: async (req, res) => {
      res.send('foo!')
    }
  });

  next();

}, { prefix: global.dir });
```
