### ISSUE TITLE
Global variable?

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify#988]
Hello everyone. Simple question:

I need to create a global variable that will be changed by many services that is created.
What's the best way to deal with it using fastify?

Thanks

**Comment by delvedor** [comment]
Use global variables is **never** a good idea in JavaScript, you should avoid them at any cost.

If you need a variable accessible in all your plugins (which is not *global*, but is part of the Fastify instance) you can use the `decorate` API at the root of your app.

```js
fastify.decorate('conf', {
  db: 'some.db',
  port: 3000
})

console.log(fastify.conf)
```

https://www.fastify.io/docs/latest/Decorators/

**Comment by Eomm** [comment]
This issue is old.

Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
