### ISSUE TITLE
Route not match on long unicode 

### ISSUE THREAD

**Issue by mhf-ir** [fastify/fastify#994]
:+1: 
```
Matched 
Url: /tag/اشتغال%20زنان
Encoded version:
/tag/%D8%A7%D8%B4%D8%AA%D8%BA%D8%A7%D9%84%20%D8%B2%D9%86%D8%A7%D9%86
```
---
:cry: 
```
404:
Url: 
/tag/فراکسیون%20محیط%20زیست
Encoded version:
/tag/%D9%81%D8%B1%D8%A7%DA%A9%D8%B3%DB%8C%D9%88%D9%86%20%D9%85%D8%AD%DB%8C%D8%B7%20%D8%B2%DB%8C%D8%B3%D8%AA
```
---
```js
fastify.get('/tag/:tag', (request, reply) => {
 console.log(request.params);
});
```

When i use small tag it's matches seems be the problem is for long params.

#### What was the result you received?
404
#### What did you expect?
match the route and load the route method

#### Context

* *node version*: v8.11.3
* *fastify version*: ^1.6.0
* *os*: Ubuntu, Docker Container

**Comment by delvedor** [comment]
I guess you are working with a dynamic routes, so the declaration should be something like `/tag/:tagId`.
If so, Fastify has a configurable maximum length of the dynamic parameters, which is 100.
You can change it with [`maxParamLength `](https://github.com/fastify/fastify/blob/master/docs/Factory.md#maxparamlength) :)
