### ISSUE TITLE
fastify NODE_ENV production seconds request for pug template text/html

### ISSUE THREAD

**Issue by mhf-ir** [fastify/fastify#995]
Everithing is ok but when i run app using NODE_ENV=production
On second request response header will be `text/html; charset=utf8`

```js
fastify.register(pointOfView, {
  engine: {
    pug,
  },
  options: {
    filename: path.resolve('views'),
    pretty: process.env.NODE_ENV !== 'production',
  },
});


      reply
        .header('Content-Type', 'application/xml')
        .view('views/sitemap.pug', {
          config,
          sitemaps,
        });
```

#### What was the result you received?
First check will be ok then second response is 

#### What did you expect?
Always using same header for response `text/html`

#### Context

* *node version*: v8.11.3
* *fastify version*: ^1.6.0
* *os*: Ubuntu, Docker Container

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
Can you please provide a full example to reproduce?
Il giorno lun 25 giu 2018 alle 16:39 Muhammad Hussein Fattahizadeh <
notifications@github.com> ha scritto:

**Comment by mhf-ir** [comment]
Try this coide:
```
const path = require('path');

const pointOfView = require('point-of-view');
const pug = require('pug');

const fastify = require('fastify')({
  maxParamLength: 1024,
});

fastify.register(pointOfView, {
  engine: {
    pug,
  },
  options: {
    filename: path.resolve('views'),
    pretty: process.env.NODE_ENV !== 'production',
  },
});

fastify.listen(8080, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  fastify.log.info(`server listening on ${fastify.server.address().port}`);
});

fastify.get('/sample.xml', (request, reply) => {
  reply
    .header('Content-Type', 'application/xml')
    .view('views/sample.pug', {

    });
});

module.exports = {
  fastify,
};

```

**Comment by delvedor** [comment]
The "problem" happens because of [this](https://github.com/fastify/point-of-view/blob/75bf6da8c3cc0e24c16017aadaa4fe34b512f46f/index.js#L86-L92).
You should not use `.header('Content-Type', 'application/xml')`, `.view` will do it for you.

**Comment by mhf-ir** [comment]
so how can i have pug view with my custom header ?
